### ISSUE TITLE
Improvements to Test - What to do?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#10]
Going to Junit 4 + Hamcrest is an obvious improvement.

Using Spock looks interesting, particularly for maybe a functional or acceptance test suite (perhaps a larger scope even if it proves really awesome).

Regardless, what are the current visions for how to improve testing? I'm offering my help, I've a few ideas as well ;)

PS: I started this page to capture a list of test cases we'll want to be sure are captured: https://github.com/triplea-game/triplea/wiki/Some-Things-to-Test-(Functional-Test-List-Plan)

**Comment by ron-murhammer** [comment]
The biggest thing is just better functional test coverage in general. The improved frameworks should help. I'd say focusing on the complex delegate logic for purchases, movement, battles, and placement would be an excellent place to start but Veqryn would probably know best.

**Comment by veqryn** [comment]
What we really need to start with are tests that confirm that game rules are being followed.
ie: if i put units in a transport, move it here, unload, and then the transport dies in battle, the units it unloaded should die and be removed from the land battle
if a plane with paratroopers gets shot down by AA guns, the units it is carrying should (or should not, can't remember) die before participating in the battle
legal movements are legal
illegal movements are illegal
etc

this kind of stuff
