### ISSUE TITLE
Submarine Cannot Choose Not To Attack In V4 Rules (2.6.534)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#10020]
I was just playing in Bot804_London and, on the second Germans turn, my submarine in "1 Sea Zone", which I hadn't move, was not offered the option not to attack the enemy units in there, despite the fact that none of these was a destroyer. The main problem is that, as consequence, I was not able to move the submarine in Non Combat Move (beside editing).

The current program behaviour appears to be that, if I have 1 submarine starting its controller's turn inside a sea zone with enemy units but no enemy destroyers, my only options are moving it out during Combat Move or attack the units in the sea zone (of course, I can choose to submerge before anything may get hit).

What I believe it should happen is that every submarine starting its controller's turn in a hostile sea zone should be allowed neither to move nor to attack unless an enemy destroyer is present in the zone: I don't have to move the submarine out of the zone in order not to attack with it.

However, I'm not entirely sure of what I'm saying, so I defer to @panther2. 

### Attach a Save Game
[01_BUG.zip](https://github.com/triplea-game/triplea/files/7875504/01_BUG.zip)

### Engine Version

Engine Version: 2.6.534 (but I was playing in an automated host, and I don't know what version is the host).

### Is there anything else we should know?

I seem to remember I had this problem years ago too. I think it's an important issue.

**Comment by panther2** [comment]
@Cernelius 

Your German submarine is sharing the seazone with enemy surface warships.
You need to choose one option of the "Sea Units Starting in Hostile Seazones" rules.

Remaining with the submarine in that seazone and conducting combat is one ot those options.
You can of course submerge then. 
That is why you are not allowed a NCM.

You can choose not to attack by leaving that seazone during Combat Move Phase.

**Comment by Cernelius** [comment]
Closed as invalid.
