### ISSUE TITLE
UI Duplicating/Tiling Bug

### ISSUE THREAD

**Issue by goshenRU** [triplea-game/triplea#10054]
Hello,

I have a issue that keeps happening randomly whenever I am using TripleA. Randomly, my UI screens will start duplicating/tiling/spamming. There's nothing I can do but try and save and restart TripleA. I have uninstalled and reinstalled the application and updated Java with no change. 

Attached is a few screenshots of what it starts to look like when it bugs out. Every mouse move only makes it worse

Thanks for your time and support
![1](https://user-images.githubusercontent.com/47676993/151648122-1dc9321a-4919-4f4f-9e71-6e75a800c4aa.PNG)
![2](https://user-images.githubusercontent.com/47676993/151648115-3997fe03-43c0-40b3-8ec8-ebc6731a6c91.PNG)
.

**Comment by beelee1** [comment]
what triplea version are you using ? Does it only happen when history is open and there is a battle ? Does anything show up in "Debug"

**Comment by goshenRU** [comment]
Java Version: 11.0.6
Engine Version: 2.5.22294

I am not sure if it happens only when there is a battle. The problem happens maybe ever 20 minutes into a game, so I have just been saving and restarting. I haven't been able to predict when it happens, it appears to happen randomly, but it could be when the history and/or battle is open.

I have not checked Debug yet, I will check it when it happens next if I can. The whole UI bugs out so it's hard to click things.

**Comment by goshenRU** [comment]
I tried rolling back 1 version and still the same thing. I opened the Debug log while it was glitching and this was all that was shown.
![4](https://user-images.githubusercontent.com/47676993/151683820-08a34cd4-290e-4b89-93ee-5771670ec0f5.PNG)

**Comment by beelee1** [comment]
Hmm ... bummer. Yea 2.5 the latest stable version. What OS are you on ? @panther2  have you seen this before ?

**Comment by goshenRU** [comment]
After some digging on the forums I found someone else who was having "graphical errors" [here](https://forums.triplea-game.org/topic/1295/graphical-errors/7). It appears to be an NVIDIA and/or Alienware driver issue related to Java. I took the steps recommended that resolved their problem:

-------------------------------------
RoiEX  ADMIN 18 Apr 2019, 17:11
Ok, let's try the easiest things first:

Make sure you have the latest Nvidia graphics driver. Since you're on a laptop and I'm assuming that it has an Intel graphics unit as well, also make sure your Intel graphic drivers are up-to-date.
Check your Nvidia driver settings: Follow the steps as described [here](https://stackoverflow.com/questions/22737535/swing-rendering-appears-broken-in-jdk-1-8-correct-in-jdk-1-7/27768329#27768329)
Navigate to your TripleA installation folder. You'll find a TripleA.vmoptions file there. Edit this file with a text editor of your choice and add the following line to the end of the file: -Dsun.java2d.d3d=false
One of the steps should hopefully help. Let me know if that works for you.
-------------------------------------

So far I haven't had the issue yet. Fingers crossed. I'm going to give it another day or two of play time and report back here if the issue is fixed or not.

**Comment by goshenRU** [comment]
Played for many hours, no problems at all! Seems the fix above worked.

**Comment by panther2** [comment]
> Hmm ... bummer. Yea 2.5 the latest stable version. What OS are you on ? @panther2 have you seen this before ?

No, never.

**Comment by beelee1** [comment]
@goshenRU if this is still working for you, hope so :) you can close the issue

**Comment by goshenRU** [comment]
> @goshenRU if this is still working for you, hope so :) you can close the issue

Yes, still working fine! Closing now. Thanks for your time.
