### ISSUE TITLE
tutorial map has some mispellings

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1015]
Phase is spelled as fase in a couple of places

(from: http://tripleadev.1671093.n2.nabble.com/TripleA-1-9-0-0-Prerelease-td7592899.html#a7592987)

**Comment by ZjelcoP** [comment]
This has just been corrected in release 0.80.

> For future reference, this is the file that has the download URL: https://github.com/triplea-game/triplea/blob/master/.travis.yml

I didn't update this file. Seems easy enough but rather leave it to you.
