### ISSUE TITLE
spare Tech Tokens being deleted

### ISSUE THREAD

**Issue by SGE0** [triplea-game/triplea#10164]
We encountered an "Interesting" bug today: If you possess more than one tech token and roll atleast one 6 you get a technology but all other tech-tokens are lost. Even if you roll multiple 6s all you get is one technology (and still loose all other tech tokens).

**Comment by beelee1** [comment]
@SGE0 what game were you playing

**Comment by SGE0** [comment]
@beelee1 World War II v3 1941

**Comment by beelee1** [comment]
@SGE0 I'm not 100% certain but i think that's correct according to the rules
https://www.axisandallies.org/wp-content/uploads/2011/12/Axis-Allies-50th-Anniversary.pdf
Would you clarify @panther2

**Comment by SGE0** [comment]
@beelee1 you are absolutely correct, i must have misread that! I want to apologize for the false alarm and say a big "thank you" for taking care of this so quick and nicely.
