### ISSUE TITLE
Which forum to keep

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#102]
This release was particularly confusing with the multiple avenues for bug reports, multiple posts on multiple forums.

We previously discussed migrating from source forge and merging forums. In that context, @veqryn  and @ron-murhammer , which forum would you prefer to keep?

I think it's literally that sample. Start with choosing one, then post on the one that is being deprecated that it is going the way of the dodo. Eventually then close the ability to add new posts.  IMO we'll bleed over to the one forum for some time and then use the one for a considerable time (months/years)

**Comment by veqryn** [comment]
You will need a better migration plan then that.

All 3 sites have different purposes and different owners.
If possible, I'd like to have everything on A&A.org.  But then I'd want to have root access for all triplea dev admins (ie: redrum and myself currently), and have the site be much more about TripleA then it currently is, before switching over.  And I don't think the djensen would be up for that, and in any case I don't have the time to manage this and another website.
TripleAWarclub.org and triplea.sf.net serve different purposes and each have different features.  Until you can replicate all those features and services somewhere in one place (ie: on one of those two sites, or on a third site), then I think it is a bad idea to shut one of them down.

**Comment by gaborbernat** [comment]
What are those features we are looking for?

Bernát GÁBOR

**Comment by DanVanAtta** [comment]
Thanks for response, also curious if you've (@veqryn) thoughts on merging the source forge forum into warclub.org? That seems to me the only one that would be possible or potentially helpful.

**Comment by DanVanAtta** [comment]
@veqryn , I do not see anything that will make forum merging easier in the future (other than the game dying a slow death of a attrition maybe). I bring up forums because it is an obvious area of overhead that we can reduce. I think you may have mentioned this as a sourceforge dependency that would be good to remove and that you would like to merge these forums. On sourceforge forum I recall someone mentioning that merging the forums was important for consolidating the user community and reducing confusion.

3 forums is pretty clearly overkill. The sourceforge one I think could be merged into warclub probably could be merged.  We get bug reports from both, and warclub seems to be bug reports and more, source forge is mainly just bug reports / developer commentary or those that have shied away from warclub.

You also mentioned that I needed a more robust plan. The start of any plan I see is picking a forum to keep,  a course of action then figuring out requirements. Since I can't control how this is going to happen or even execute it, I can only try to give momentum to it. So it's a waste of my time to plan this out to the letter and then *maybe* who knows have it happen that way some time in the future when maybe that plan could still resemble reality. 

On that line of thought, I don't see any more immediate action items left in this issue.

**Comment by prastle** [comment]
I apologize for responding here but first link I clicked.

opened three new rooms in warclub as a developer area a few ?
needed answered

1
how to add more mods
 a few others as well
but u should be able to post maps and updates now
either way my attempt to help
real ? is
do we link it to home page?
 so it updates all new posts
since only ten there atm
developers will fill that in a few hrs :)
ty for the help

**Comment by DanVanAtta** [comment]
@prastle Here is how to open a new topic: https://github.com/triplea-game/triplea/issues/new  It is very much encouraged to open new issues, and it is easy to close and merge them to existing ones..

W.r.t rooms, I think we can structure them in a way to keep the communication flow more obvious. For more warclub forum organization, please see: http://www.tripleawarclub.org/modules/newbb/viewtopic.php?post_id=16977
