### ISSUE TITLE
Ready to add new map

### ISSUE THREAD

**Issue by tripleaukraine2022** [triplea-game/triplea#10215]
I have a playable map that is ready to be shared with the TripleA community.  Please send me an invitation to join my own my team at triplea-maps.

I know that this map is quite sensitive to current events, and will understand hesitancy on the part of the moderators to include this map at this time: https://github.com/tripleaukraine2022/ukraine2022

**Comment by tripleaukraine2022** [comment]
@Cernelius 
Thank you for your feedback!!

1. Done
2. Done
3. This was a tricky one.  They are now both Russian territories, but Ukraine has an objective and bonus if they are reclaimed.  I added a decoration to indicate the conflicting sovereignty there.
4. I added that to the notes.  At the end of Russia's battle phase, the victory condition is evaluated.
5. I added that to the notes.  The idea is that sanctions, military setbacks, insurgency, and worldwide support end the conflict with a settlement favorable to the Ukrainians.  This is evaluated at the end of Russia's battle phase on the 10th round.
6. I created a new a T-90 tank image, a new MiG image, and new APC images based on current military equipment in use.

There is still balancing to do, but I believe this map is off to a better start now.  Again, thank you for taking the time to look at it and provide constructive feedback.

**Comment by Cernelius** [comment]
The repository name is supposed to be the main folder name. You have called it "ukraine2022" instead of "ukraine_2022".

I'm not adding maps to the repository, by the way. Just letting you know that you need someone else for having this map added to the repository.

I'll let you know if I play it.

**Comment by tripleaukraine2022** [comment]
I renamed it as you suggested.

**Comment by DanVanAtta** [comment]
To add context on why this was closed, as was hinted in the OP - I think it's in poor taste to be "simulating" this ongoing conflict as a game - at least as an official map. As with any military conflict, there are interesting armchair-general strategies to discuss, so no judgment here on why such a map was created (there are certainly some interesting strategy discussions to be had). 

As for another reason, if this map is allowed as an official map - then other variants of the same conflict would presumably need to be accepted as well. That creates a very slippery slope that would invite a lot of unwelcome current politics into the game and community.
