### ISSUE TITLE
Extra error message when game host is unreachable

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#10251]
Precondition: the IP address of your computer shall not match "https://www.whatismyip.com/" and port forwarding must not be set up.

Repro steps:
  -  launch game
  -  join lobby
  -  host game
  -  wait for "your computer is not reachable from the internet" message to appear
  -  notice additional error message

Incorrect error message:
![Screenshot from 2022-03-30 21-13-27](https://user-images.githubusercontent.com/12397753/160975154-fa49bb2b-8e14-4ec0-a4d0-f51761bac5b8.png)

The right hand side should not appear, we already have the correct error message on screen on the left hand side.

Presumably this is problem with code contracts: expectation of where we expect exceptions to be thrown vs nullable return values.

**Comment by DanVanAtta** [comment]
Presumably host a game without port forwarding enabled. I found this
screenshot elsewhere and did not repro personally

**Comment by DanVanAtta** [comment]
Confirmed that is the repro case, ie:
- launch game
- join lobby
- host game
- wait for "your computer is not reachable from the internet" message to appear
- notice additional error message

Precondition: the IP address of your computer shall not match "https://www.whatismyip.com/" *and* port forwarding must _not_ be set up.

**Comment by RaiNova** [comment]
Let‘s clarify which parts of this fix are a good first issue and which should be done be people with more experience in the TripleA code. I see the following subtasks to fix this:
a) Reproduce the error and document in this issue how to reproduce it (Good first subtask, probably mainly already done by Dan)
b) Fix code contract
- find any documentation about where we expect exceptions to be thrown vs nullable return values (I guess there‘s none. Total absence is hard to find for a novice, so this is an expert subtask)
- produce a general guideline of where we expect exceptions to be thrown vs nullable return values (expert)
- identify where in the context of the error the guideline is violated (in the assumed current absence of a guideline, this is vast, but a novice could identify a small area that suits himself to work on)
- agree on the area to work on (novice + expert)
- fix the area (novice)

**Comment by suryakapurothu** [comment]
> Let‘s clarify which parts of this fix are a good first issue and which should be done by people with more experience in the TripleA code. I see the following subtasks to fix this: a) Reproduce the error and document in this issue how to reproduce it (Good first subtask, probably mainly already done by Dan) b) Fix the code contract
> 
> * find any documentation about where we expect exceptions to be thrown vs nullable return values (I guess there‘s none. Total absence is hard to find for a novice, so this is an expert subtask)
> * produce a general guideline of where we expect exceptions to be thrown vs nullable return values (expert)
> * identify where in the context of the error the guideline is violated (in the assumed current absence of a guideline, this is vast, but a novice could identify a small area that suits himself to work on)
> * agree on the area to work on (novice + expert)
> * fix the area (novice)

I'm willing to take up the good first subtask. 
@RaiNova Can you please advise if there's a need for it?

**Comment by RaiNova** [comment]
>  @RaiNova Can you please advise if there's a need for it?

My apologies that I can't: Since contributing to triplea in Kotlin was impossible and I am too slow in Java, I have moved on to another project.

**Comment by DanVanAtta** [comment]
@klarubbio I think the first step would be to identify where the null pointer exception is coming from. I would suspect that there is a chunk of logic that is being executed but should not be. There is likely a logic error, an error-of-omission (so namely something like an if statement that validates we do not have a null). The passing back-and-forth of a null value to flag a 'no-network' situation is not ideal perhaps, so the issues are deeper. At least fixing the extraneous NPE is a good start.

> find any documentation about where we expect exceptions to be thrown vs nullable return values (I guess there‘s none. Total absence is hard to find for a novice, so this is an expert subtask)

Generally exceptions should be thrown for any situation that the code cannot recover from. 

Nullable return values is a bit philosophical. Generally, avoiding 'null' entirely is a good way to avoid NPEs and instead of returning null, return an `Optional` type instead. The two considerations of exception vs null is a bit tangential. Returning null to indicate something fails is a bit of a code smell, hence the two are a bit tangential.


> produce a general guideline of where we expect exceptions to be thrown vs nullable return values (expert)

Agree, but perhaps this is best done by providing some links. The ways to avoid NPE and how to properly use `Optional` are pretty well documented in a variety of blog posts.

> fix the area (novice)

I think here, it's largely first a matter of  just finding where the NPE is, and adding a "null check" in a reasonable place to abort the logic that is likely assuming that a person has an internet connection.
