### ISSUE TITLE
Settings window description update - split up columns

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1028]
Task: Add a column for the default column and valid ranges. Perhaps consider adding two columns, one for the default value, a second for valid value range.

---

Original Thing to fix:
https://cloud.githubusercontent.com/assets/19562310/17273383/57492e8a-56b3-11e6-9ac1-fbbd73161227.png

**Comment by Cernelius** [comment]
The settings descriptions are scrollable, allowing me to read the full contents.
Yet, it doesn't look great, and I believe the (N - N, default: N), currently being the first line of the descriptions, would be better staying in a separate column, in between of descriptions and current values, that would also gain 1 full line for the actual descriptions.

![engine_settings_2_scrolling](https://cloud.githubusercontent.com/assets/19562310/17641447/3e245250-6120-11e6-80b6-42a4e8c8a596.png)

**Comment by DanVanAtta** [comment]
now re-purposing this ticket to the UI improvement of having the default+range be in a column of their own.

**Comment by ssoloff** [comment]
I know there was a lot of fire-fighting going on in the last week, so I just wanted to bump this issue to make sure it doesn't fall through the cracks...  All that's left is for someone to verify that #1511 satisfactorily addresses the concern raised in this issue so it can be closed.

**Comment by ssoloff** [comment]
@DanVanAtta Bumping...  I think this issue can be closed if you agree #1511 satisfies your requirements.

**Comment by DanVanAtta** [comment]
Above is merged, looks like this is done, closing.
