### ISSUE TITLE
Harbour and airfield in India are owned by UK Europe

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#1029]
I think this is the right place to raise this, but it is surely a bug that the harbour and airfield in India are owned and repaired by UK Europe rather than Pacific.

Apologies if this is already noticed. I tried to search briefly without much success.

**Comment by DanVanAtta** [comment]
Which map does this apply to? 
It might be more appropriate to raise this issue in the map repo for which this is a problem:https://github.com/triplea-maps, regardless, this is a good start for identifying/discussing the problem.

**Comment by simon33-2** [comment]
World War II Global 1940

I would imagine also World War II Balanced.

I've added the issue here: https://github.com/triplea-maps/world_war_ii_global/issues/1

Thanks.

**Comment by simon33-2** [comment]
In fact, it is in the notes: "* (EM) India (UK Pacific) must pay for repairing any damaged facilities on the pacific half of the board (instead of London paying) (use edit mode to subtrack the PUs from India and give back to London)."

Perhaps this is not just a matter of changing the ownership of the units which is what I would have thought on the face of it.

**Comment by panther2** [comment]
The territory owner of course is UK_Pacific. I think the issue is due to the programming approach of the "One Power, Two Economies" - status of the United Kingdom.

**Comment by simon33-2** [comment]
But who owns the actual Harbour and Airfield? I would have thought that if UK_Pacific owned them rather than Britain you wouldn't get that problem. But then if it was that simple, you'd wonder why it wasn't done already.

**Comment by panther2** [comment]
The controller of the territory "owns" the facilities.  On the complete map the owner always is the United Kingdom. The differentiation between UK_europe and UK_pacific - units is a programming approach in the TripleA map to realize the "One Power, Two Economies" - status of the UK. For the purpose of buying and placing the TripleA-map has this distinction - but after all of UK's action is done, the UK_pacific units changes ownership (to UK_Europe). You can see this at the end of a tripleA-turn-post, for example:
`Turn Complete - UK_Pacific
            Total Cost from Convoy Blockades: 0
                Rolling for Convoy Blockade Damage in 20 Sea Zone. Rolls: 4
            UK_Pacific collect 18 PUs; end with 18 PUs total
            Objective UK Pacific 2 Kwangtung And Malaya: UK_Pacific met a national objective for an additional 5 PUs; end with 23 PUs
            **Some Units in India change ownership: 2 artilleries and 3 infantry**`

So in the end all units are UK (europe) including Facilities - this is why the cost-editing becomes necessary. I am no programmer, so I don't know if there is a different way to code it...

**Comment by simon33-2** [comment]
I'm still unclear on the problem with what I suggested - just have UK_Pacific owning the facilities. I guess they could have a trigger to change ownership back to UK_Pacific if India is liberated - and similar with the Harbours in Malaya and Kwangtung. That would already need to be handled for the case where Japan builds an IC and the allies recapture it as UK, right?

Honestly though, I could accept that bug a bit more readily than the current one which is that it never works.

**Comment by DanVanAtta** [comment]
@simon33-2 , would you mind re-summarizing the issue? Seems like there is a need for better support of one country controlling two different economies (IE: fights as one, but buys as two)

**Comment by panther2** [comment]
Only one thing to do IMHO:
In the UK-pacific purchase and repair phase check whether there are damaged UK facilities present on UK-pacific territories. If so let UK-pacific economy pay for repairs.

**Comment by simon33-2** [comment]
Just tested this out by applying edit mode. Works perfectly well including harbours changing ownership on reconquests with just changing the ownership of the 3 harbours and airfield to UK_Pacific.

So we need to update the xml I guess. I'll close this issue because no change is required the engine - just the map.
