### ISSUE TITLE
Balanced Mod is not incorporated into the list of games in 1.8.0.9

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#1030]
Is there a reason for this? Surely it would be better to have it as a different game. Once you enable your installation for Balanced Mod you get annoying errors trying to use a vanilla game.

**Comment by DanVanAtta** [comment]
Is this a problem with 1.9? If so, could you be a bit more specific about which mod/map?

1.8.0.9 is not being updated unless there is a true emergency. The 1.9 release should be going out next weekend'ish.

**Comment by simon33-2** [comment]
It's not a problem - it's an enhancement.

There is a commonly used variant known as "Balanced Mod" - done by patching the environment: http://www.axisandallies.org/forums/index.php?topic=37883.0

The major annoyance for me is that it causes Java errors if you play a standard Global 1940 game after patching the environment. I'm wondering if this variant can be included in the list of selectable games. Would be an appreciated improvement.

**Comment by simon33-2** [comment]
Actually, has this already been done for 1.9? Appears to have, from this page: https://github.com/triplea-maps/world_war_ii_g40_balanced

**Comment by panther2** [comment]
If you place the map file downloaded from https://github.com/triplea-maps/world_war_ii_g40_balanced/releases inside the downloadedMaps-folder,
the map will show when hitting "Select Game", But it won't work. I have already openend an issue there:
https://github.com/triplea-maps/world_war_ii_g40_balanced/issues/1

**Comment by DanVanAtta** [comment]
To be listed for download, a map needs to have an entry in this file: https://github.com/triplea-maps/Project/blob/master/production_config/triplea_maps.yaml

The game pulls from that file, so updates to it will be live/visible immediately.

**Comment by DanVanAtta** [comment]
Can you open the error console and see if you are getting any errors? If there is a lot of stuff in the console, please clear it, try to open the map, and you should get a fresh error trace. 

It worked fine for at least me:

![loaded](https://cloud.githubusercontent.com/assets/12397753/17614439/31ae2164-601b-11e6-9413-e7697d886e9f.png)

**Comment by simon33-2** [comment]
I want the .yaml file updated otherwise I won't really count this as properly done.

Here's the PR for the .yaml file: https://github.com/triplea-maps/Project/pull/39

**Comment by panther2** [comment]
Seems to run fine now. Thanks.
