### ISSUE TITLE
Open saved games with double click - Feature request

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#1031]
Is it possible to have an option to load up a specified file and also switch into play by forum mode - or by email.

**Comment by DanVanAtta** [comment]
Would be good to not rely on command line for this feature, otherwise only a few power users would have access to this feature.

Some things that could be done:
- update OS on install to associate .tsvg files with tripleA
- encode in save games if the game is PBEM or PBF, and in those cases launch the appropriate game launch screen directly

I've also wanted an in-game feature to send PBEM games. That would help out on the other side of this equation where you save and email a game.

**Comment by simon33-2** [comment]
What's the point of doing the association if all that happens when you open up a tsvg file is that Triple-A is opened. I want to have associating the file load a saved game and ideally have an option to throw you straight into the game.

Perhaps there is some other way of loading up the tsvg file I am not aware of besides a command line option?

**Comment by DanVanAtta** [comment]
PBEM and PBF we cannot save all information in the save game, notably email addresses. So when you load from those files, in those cases we will not be able to go directly to game. It also might be undesirable if the game is going to be a multiplayer or vs AIs, in both cases you would have to back out to re-select the opponents. 

So there are a few problems to overcome one way or another. For certain we can record if a game was PBF/PBEM, and at least launch the game as far as possible with the given save file already selected.

**Comment by simon33-2** [comment]
Strange.

When I PBF the emails don't have to be reentered and as far as I am aware they appear correctly, even when I load the save game on a different computer to the one I started it on. I'm not aware of dice emails going to the wrong person or the person who's emails I last entered.

**Comment by DanVanAtta** [comment]
It does seem like the PBEM email is saved with the game, I was mistaken.
Regardless, normal users are going to be challenged to use command line args. Regrettably that will not be a good general solution. @simon33-2 , would you mind updating this ticket title to be more exact to the thing you want, namely "PBEM games autoload when double clicking them" or something like that. Command line arg is a no-go for this feature IMO.

**Comment by simon33-2** [comment]
ok, done.

**Comment by panther2** [comment]
I would vote for
-update OS on install to associate .tsvg files with tripleA
being an optional feature that may be selected/deselected during the installation process the same way as "Create a Start Menu Folder" and "Create shortcuts for all users"

**Comment by DanVanAtta** [comment]
I think https://github.com/triplea-game/triplea/pull/1783 would address this

**Comment by RoiEXLab** [comment]
@DanVanAtta It doesn't, but my next PR will ^^

**Comment by RoiEXLab** [comment]
Closing for #1031
