### ISSUE TITLE
Game locks up when it can't connect to check for updated maps

### ISSUE THREAD

**Issue by doctored** [triplea-game/triplea#1032]
let me know if you have any questions :)

**Comment by DanVanAtta** [comment]
Is this a problem in 1.9?
IIRC we removed the check altogether.

**Comment by doctored** [comment]
haven't checked yet will update if it does happen

**Comment by DanVanAtta** [comment]
We need to check what happened to the update map feature. I think it still might be in the game.

If it is, we need to at the very least provide a way to get out of the lock-up. For example, provide a cancel button, or a timeout. In addition any such check probably should be in the background, and not prevent normal game play.

**Comment by DanVanAtta** [comment]
https://github.com/triplea-game/triplea/pull/1044 will fix
