### ISSUE TITLE
Suggestion: Switch to using Duration instead of int + TimeUnit

### ISSUE THREAD

**Issue by asvitkine** [triplea-game/triplea#10338]
Right now, args that pass a duration specify both an `int` quantity and a `TimeUnit`. For example:

```
            new ExpiringAfterWriteTtlCache<>(
                GameListingClient.KEEP_ALIVE_SECONDS,
                TimeUnit.SECONDS,
                new GameTtlExpiredListener(playerMessagingBus)))
```

I suggest us to switch to the new (Java 1.8+) `Duration` class, which will allow a single argument in places we have two currently (outside of external APIs).

For example, the above would become:

```
            new ExpiringAfterWriteTtlCache<>(
                Duration.ofSeconds(GameListingClient.KEEP_ALIVE_SECONDS),
                new GameTtlExpiredListener(playerMessagingBus)))
```

I searched for use of "TimeUnit." in the codebase and there are 66 locations, so it shouldn't be too big of a clean up, although some may be calls to APIs that can't be converted.

**Comment by RoiEXLab** [comment]
I believe there was an errorprone check back when we still used it. But yeah no objections. java.time is nice

**Comment by DanVanAtta** [comment]
(late response) No objections here @asvitkine
