### ISSUE TITLE
world at war variant FUEL AA RANGE

### ISSUE THREAD

**Issue by kumodomuse** [triplea-game/triplea#10359]
The ability for Britian to send troops into Belgium via Dover or Whales with no boats and not in control of the sea zone is the dumbest thing ive seen so far, add that without the ability for Germany to build a factory in Tobruk even though you start the game with it ?

**Comment by asvitkine** [comment]
Seems like this a comment about a specific map and not the engine. I'll close it out, since it doesn't belong here.
You can post it on the github repo for the map: https://github.com/triplea-maps/world_at_war_variants
Or on the forums.
