### ISSUE TITLE
WarClub Bunker Forum Alternatives

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1040]
TripleaWarClub offers a secret forum for moderators to communicate with each other. Even if we do not remove warclub, is there a better way we can have moderators communicate?

To discuss here:
- Through what means can and should moderators communicate?

**Comment by DanVanAtta** [comment]
IMO this one is pretty straight forward, using the same login as you do for github, we can have moderators use Gitter to talk privately. Since gitter provides a log of the conversation to everyone, it's an effective replacement for a forum.

We can combine this with moderator actions producing an audit trail. Keeping an audit trail of chats from the lobby would then give us a more complete picture. We then no longer have to have moderators report via forum the actions they take (which is a broken system anyways since the reporting is all voluntary, good actors will report, bad ones will selectively report)

**Comment by ron-murhammer** [comment]
@DanVanAtta What is the drawback of having a limited access forum section? I feel like most forums support this and this is probably more common to most folks. I think gitter is fine for some development IM'ing but its probably better to keep a moderator section in the forums.

**Comment by DanVanAtta** [comment]
I think before we can really evaluate any forum, we should answer both:
1. why do we need a limited access forum?
2. given what we need, how can we achieve those needs?

We need to answer 1 before we can really answer 2. We have lots of possible ways to achieve our means, for number 2 we have available:
- warclub bunker forum
- gitter
- private github repo (does not exist, but this is easily funded)
- google group / email 
- other, perhaps some other forum altogether, maybe Trello for example
- in-game features: example: 
  - moderators could post moderator only lobby messages
  - add a whisper tool for moderators, or perhaps even a completely new window that only admins see that is effectively an admin chat.

The first question of why is really key though. If someone is ranting and gets banned, then they are banned, I see nothing further to discuss. If they want to be unbanned, that's going to need to go through a public channel anyways. 

At this point, I think it would be best if we really enumerate our needs and uses for a private forum. We should then take a critical look at each one, and see if we are actually best served with the bunker.

My 2 cents on forums: Much of what I think is being asked for seems very operational in nature. Forums I find to be a bad medium for that simply because you cannot close items that have been dealt with. Things like Gitter / slack,  solve that problem because anything not in recent chat logs is effectively closed. 

To re-iterate though, I think we need to take a really good look at the use cases that would require moderator-to-moderator secret communication.

**Comment by ron-murhammer** [comment]
@DanVanAtta I think moderators just want a limited access place they can discuss things such as bans, lobby issues, spam/security issues, server/bot stuff, etc. You'd be surprised how gray banning people becomes and some mods use their power questionably sometimes. I'd honestly just take a look at the threads in the bunker today as that probably gives the best indication of what its used for.

Just about any of those from your list could be used. I just think forums are easiest for most of the folks and what they are used to.

**Comment by DanVanAtta** [comment]
In the bunker I see:
- notes on how to admin bots + servers, this should be public IMO. Our security is in the fact that not just anyone can SSH to our server, not through obscurity of how the server operates, and which folder paths contain which scripts
- discussions of how to be a moderator, this can be public (IMO). Really it should be, with guidelines pretty clear cut.
- discussions of banning/muting. Much of this looks like audit activity, mods have instructions to record when folks are banned/muted. A log file could accomplish much of this automatically. Then leaves discussions of whether names are in a gray area or not. We can probably have that conversation in public, issue title "questionable names". If the name seems questionable enough to not even discuss in public, then we probably should add the name to the naming black list.

It's also interesting that the bunker does not actually have very much activity. Only 4 forum posts updated in the last 3 years. I can see the need for *a* secret communication channel, Gitter can do that for whispers or a secret group chat. Otherwise I think we are just missing process that would make things much less gray.

So I see a need for at least inter-admin chat. I do not think we need a secret forum to post ban/mute activity - we can automate that via activity logging. The lobby/admin instructions do not need to be secret either, so really I think it's only the private inter-admin chat that we need to support. Topics in that chat will be questions people have, or just general admin banter :) 

Thoughts? Do we need more than just a gitter-like chat channel?

**Comment by ron-murhammer** [comment]
I don't really have a strong opinion on it as I'm not really a lobby player but figured the easiest solution was just to leave it as is. I have a feeling most of the mods won't use or want gitter but it probably would suffice. Probably would be good to post this question there if you really want to get rid of it.

**Comment by DanVanAtta** [comment]
Posted a thread in the warclub about the bunker, waiting to see what conversation develops there.

**Comment by yamamot0** [comment]
Hi,

as already posted in the warclub: I dont see any need for any change to the bunker at the moment. 
The system work good for the purpose. If we take the warclub somewere else, we can take the bunker with us or use something else - doesnt really matter at this point, before we know were the warclub is going.
"It's also interesting that the bunker does not actually have very much activity. Only 4 forum posts updated in the last 3 years." I dont get that - we post and discuss a lot about bans and lobby rules.

Great would be an automatical post, wenn a mod takes action on the server. That would make the work for the _senior mod_ easier.


Best regards

**Comment by yamamot0** [comment]
And: I dont think we can get the mods to post anywere else at the moment than in the bunker: we have problems enough at the moment making them visit and post in bunker :)

**Comment by DanVanAtta** [comment]
Thank you for weighing in @yamamot0  . Part of the idea is to make life easier on senior mods by having fewer places to check.  

I wonder though, Ii mods are not posting to warclub regularly, is the answer really more warclub?

Github issues is replacing two components that were developer facing in source forge, and it has the potential to replace more than that. In addition, many websites are sharing login with github, which allows for more tools to be available simply by having a github account. These tools are very appealing since many require no effort/admin work from the development team. 

The other point worth considering, the secrecy of the bunker is doing harm to the community. Opaque standards, secret rules and guidelines is not good for anyone. It creates 'gray' areas in how the rules are applied.. This is yet more work for needing more admins to admin the admins. Not to mention the ramp up for new admins is an avalanche of new secret information. It's worth removing the secrets and limiting the use of the bunker to only that which really needs to be secret (IE: mac / IP / email addresses  to keep peoples identities more secure)

**Comment by DanVanAtta** [comment]
Okay, there is not much appetite for a transition at this point, we already have a lot of moderator process in flux. When things stabilize a bit more in a few months we can look at adopting new tools and process once again. 

Meanwhile it looks like warclub and the bunker will be around for some time to come yet. I believe that concludes we will not be seeking alternatives to the bunker at this time.

**Comment by DanVanAtta** [comment]
Linking some previous discussion on this topic: https://github.com/triplea-game/triplea/issues/102
