### ISSUE TITLE
Migrate Away From Derby DB To MySql

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1041]
There has been desire expressed for the lobby to use a MySql DB instead of DB.  Some points to consider:
- DB clients are well support for mysql, less so for Derby.
- We are running a mysql DB anyways for war club
- Better knowledge base around mysql compared to Derby, more people are going to be able to interact / use it

Should we make this migration a goal/project to be done for the next version after 1.9?

**Comment by ron-murhammer** [comment]
@DanVanAtta Short answer is yes. Longer answer is do we know exactly what the various DBs are used for today and everything to utilizes them? That is the bigger part as migrating the 'data' should be pretty easy. Making sure all clients are updated is the harder part.

**Comment by DanVanAtta** [comment]
We should verify a bit, but to my understanding the clients are:
derby -> lobby
mysql -> warclub PHP

So we would simply be having the lobby use a mysql DB. To be explicit, keeping the two separated is desired. It's more simply about switching DB technology. We don't necessarily need to move mysql, but I think that makes the most sense given the widespread knowledge base / support for it.

**Comment by ron-murhammer** [comment]
Agree. Better to use 1 technology and choose the one that has a larger user/knowledge base around it.

**Comment by simon33-2** [comment]
Downside might be that MySQL is only free for certain uses last I checked. With a game that is for personal use would probably ok.

**Comment by DanVanAtta** [comment]
I'll note we are already using MySQL, we would expand that usage to the game lobby as well.

**Comment by RoiEXLab** [comment]
When migrating we should start preparing #824

**Comment by DanVanAtta** [comment]
Added a 'requirements' section. There is probably more to be discussed. It does appear we have email address for registered users. The migration might really just be a 1:1 mapping of the ta_users table.

Related, the feature to manage the derby_db is broken:  https://github.com/triplea-game/triplea/issues/1352

When migrating we'll need to create a replacement version of the derby_db management console.

**Comment by DanVanAtta** [comment]
Closing for now (this issue is not helpful right now for tracking the DB migration). FWIW, for the record, I'm looking at postgres instead of mysql.

**Comment by simon33-2** [comment]
PostgreSQL is fully open source, better than free to non commercial users as per the MySQL licence. Or at least that's my understanding.
