### ISSUE TITLE
TripleA 2.6.33.8af5587ac3 crashes some maps with centers.txt error

### ISSUE THREAD

**Issue by TheDog-GH** [triplea-game/triplea#10417]
https://github.com/triplea-game/triplea/releases/tag/2.6.33.8af5587ac3

The above version causes this error before the 1st turn completes
![centers txt crash](https://user-images.githubusercontent.com/71022517/167223138-546af108-2046-4172-a057-3d13d09c0239.png)

On this map and crashes TripleA
https://triplea-game.org/map/ww2-oil-and-snow-2nd-edition/
It also causes the same error on this unpublishing map
The Shogun Advanced

**All versions after the above version cause the same error**
This version and before
https://github.com/triplea-game/triplea/releases/tag/2.6.13%4057528d46ee
**do not** have this error.

see TripleA forum for other posts
https://forums.triplea-game.org/topic/2998/2-6-testing-report-2-6-problems-here/48?page=3

**Comment by beelee1** [comment]
I cant test with pre release. Does it do it with other maps ? revised or global being two of the more popular ones

**Comment by TheDog-GH** [comment]
I dont play on many ww2 maps, I did test the Napoleonic map and it does **not** crash it.  

The crash happens within seconds of launching an all AI game on 
ww2-oil-and-snow-2nd-edition
The Shogun Advanced

Strangely the crash does not occur on the published The Shogun map, which shares lots of code/text with The Shogun **Advanced** map.

**Comment by beelee1** [comment]
Hmm ... seems as if it doesn't like something with the way the map is set up. With the centers that is. I think that means where stuff is located on the map ? Not real knowledgeable about the graphics part of triplea.

@WCSumpton you run into this before ?

**Comment by TheDog-GH** [comment]
To be clearer this crash error effects **all** versions after 2.6.33.8af5587ac3

**Comment by asvitkine** [comment]
I just tried ww2 oil and snow on current 2.6 HEAD and I'm not seeing a centers.txt error.

I do get a different error in an all-AI game:
`IllegalStateException: java.lang.IllegalStateException: Round 10,000 reached in a battle. Something must be wrong. Please report this to TripleA. Attacking unit types: bomber,leadershipOffensive, Defending unit types: seamines`

**Comment by TheDog-GH** [comment]
Im not sure which version 2.6 HEAD is, but downloaded 2.6.791 and still has the same error **centers.txt** error

Here is a link to Shogun Advanced, its not published or complete, it has the same error
https://drive.google.com/file/d/15c3lgecpoQrNztT_zvksFio5Fx8hPWo6/view?usp=sharing

Attached triplea.log deleted it, then running both ww2 oil and snow & Shogun Advanced to get the error.
[triplea.log](https://github.com/triplea-game/triplea/files/8752438/triplea.log)

This might be unrelated but in TripleA-2.5.22294 these game notes load correctly but in 2.6 they are;
**ww2 oil and snow - missing icons**

![image](https://user-images.githubusercontent.com/71022517/169770193-77ddc407-1e3d-4816-a863-16eebd810e8d.png)

.
.
**Shogun Advanced - missing the whole Game_notes.png**

It does not use the conventional game notes method, it has;
`<br><center><img src="Game_Notes.png"/></center>`

**In 2.5.22294 these games both display as intended.**

**Comment by asvitkine** [comment]
I downloaded the Shogun map and it's working fine for me, not getting a centers.txt error.

If I open Game Notes, it looks like this:
<img width="492" alt="Screen Shot 2022-05-23 at 8 26 55 PM" src="https://user-images.githubusercontent.com/17648/169924857-aee9c68f-d270-4ce6-ae84-ab50c8d3a24c.png">

Can you give more details about your set up for triplea? Do you have a custom maps folder configured or is it the default?

**Comment by TheDog-GH** [comment]
Im on Windows 10 64bit, Java version 
C:\Users\RYZEN>java -version
java version "1.8.0_331"
Java(TM) SE Runtime Environment (build 1.8.0_331-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.331-b09, mixed mode)

I have multiple versions of TripleA and put them in folders like TripleA-2.6.791
Change the TripleA.vmoptions file to;
-Xmx3072M
-Xms3072M
-Xss1536K

Use the downloadedMaps (its not customised)

Place the the unzipped map in the  downloadedMaps folder (sometimes write a map.yml for old maps I have unzipped)

ww2_oil_and_snow_2nd_edition\map has a "map" folder like your imperialism_1974_board_game
the_shogun_advanced does **not** have a maps folder 

Just downloaded 2.6.791 again and did a default install to TripleA folder and left the TripleA.vmoptions as intended, it still errors.
Both maps still error with the centers.txt

Ebbe who wrote/designed Oil & Snow is also on Windows 10 64 , has exactly the same problem as I do.

the_shogun is the basic version of the_shogun_advanced  
the_shogun does as intended and does not centers.txt error and shows the Game Notes as intended
Copying the 
`<br><center><img src="Game_Notes.png"/></center>` and the Game_Notes.png from the_shogun to the_shogun_advanced errors in advanced and works in basic :-/

This is what the Game_Notes.png should look like
![image](https://user-images.githubusercontent.com/71022517/169982612-b0bc4c8c-7220-4a14-8811-68b35b7b2ef6.png)

In your screen shot there should be a broken image but it is not displayed.  (I get the same, no broken image icon)

.
I traced the start of this error back to this version
**TripleA 2.6.33.8af5587ac3** crashes some maps with centers.txt error

**So perhaps comparing the code with the prior version will aid you in tracking down the fault?**

Thanks for taking the time to look at this.

**Comment by asvitkine** [comment]
I tried on Windows and am seeing the error, so I can debug. Interesting that it doesn't happen on Mac.

**Comment by asvitkine** [comment]
OK, I think the problem is that there is a polygons.txt file in the 'baseTiles' folder for the ww2 oil map. So the game decides that's the right place to look for all the other files. I think if that file is removed, it will work correctly.

I can see if I can change it to first consider files that are closer to the root dir, since there is a polygons.txt file in the root dir too.

**Comment by TheDog-GH** [comment]
As Winnie-the-Pooh would say " Oh Bother", I would say something stronger. :-P

I can confirm by removing the incorrect polygons.txt in both O&S and The Shogun Advanced, they both work as intended.

Please dont change anything on account of our school boy error,  the polygons.txt is **not** supposed to be in baseTiles

Thanks for getting to the 'root' of the problem.  :-)

I am going to close this thread.

**Comment by asvitkine** [comment]
I'm still going to improve things here because at the very least the inconsistent behavior between Mac and Windows can create confusion and waste people's time.

**Comment by TheDog-GH** [comment]
Fair enough.  👍
