### ISSUE TITLE
Ready to add map: imperialism_1974

### ISSUE THREAD

**Issue by asvitkine** [triplea-game/triplea#10436]
Hello!

I have a map that's ready to add to the repo, here:
https://github.com/asvitkine/imperialism_1974

I don't have access to triplea_maps so cannot add myself.

Thanks!

**Comment by asvitkine** [comment]
@beelee1 is this something you can help with? Thanks!

**Comment by beelee1** [comment]
@asvitkine sorry just saw this. I think there's a thing at the very bottom of the repo that says "change ownership". I can't remember if that has changed tho, Frostoin explains it here. Ok yea it has changed https://forums.triplea-game.org/topic/484/how-to-add-your-map-to-triplea-in-game-downloads/17

I'll try and figure it out later today

**Comment by asvitkine** [comment]
@beelee1 Thanks! I think you just fork my repository, but choose triple-maps/ as the location of the fork (instead of beelee1/) and then give me permission on the new repo.

**Comment by beelee1** [comment]
@asvitkine it's in triplea maps now. I'm not sure how to give you permission.

**Comment by beelee1** [comment]
@asvitkine ok think i figured it out

**Comment by asvitkine** [comment]
Thanks!

**Comment by asvitkine** [comment]
Actually, I don't have write access to the new repo. Is this something you can grant?

**Comment by beelee1** [comment]
I'll take another look. We'll get it sorted one way or another :)

**Comment by beelee1** [comment]
@asvitkine hmmm ... sadly I don't think I can. I can edit/write but can't add anybody else. Or don't think I can anyway. Looks as if you need to ask Dan. Ron can do it too but he's not really that active anymore. I don't think Roi can do it either.

If you can't get a hold of Dan, I guess i could try and upload it for you and then we can try and add you that way, but I kinda thought that's what we just tried.

**Comment by asvitkine** [comment]
@DanVanAtta @RoiEXLab hey, can either of you help by giving me commit access to the new repo?
https://github.com/triplea-maps/imperialism_1974

And should folks like @beelee1 be given permission to do that? It seems strange that they could create the repo but not give commit access to others.

**Comment by RoiEXLab** [comment]
@asvitkine sorry, I don't think I have any permission there

**Comment by beelee1** [comment]
@asvitkine in case you didn't see it, Dan gonna be gone for a while https://forums.triplea-game.org/topic/3230/dan-afk-for-a-few-weeks

If you don't get added before he splits, i guess i could add it as a new map. I think you should be able to work on it still. Would have to send PRs through me I guess. Not ideal, but should be a work around for now

**Comment by beelee1** [comment]
yea no worries. Do as many PRs as you want. I usually check git everyday. Do you want me to add the map ? been a while since i did a new one, so might take a bit if so : )

**Comment by asvitkine** [comment]
Thank you! I can add the map myself since it's in the code repo where I do have access.

**Comment by asvitkine** [comment]
I wonder if it's because https://github.com/triplea-maps/imperialism_1974 is marked as a fork?

https://stackoverflow.com/questions/16052477/delete-fork-dependency-of-a-github-repository

**Comment by asvitkine** [comment]
At this point, I'm thinking it might be best to delete and re-create, I can create a repository now, just can't delete that one!

@beelee1 Are you able to delete https://github.com/triplea-maps/imperialism_1974 ?

**Comment by beelee1** [comment]
Deleted Glad you got it up and running : )

**Comment by asvitkine** [comment]
Thanks for your help! Sorry for all the hassle. I wonder if the problem is that the original repo was created by cloning.
