### ISSUE TITLE
Add dependabot to CLAassistant exceptions

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#10438]
A thing that keeps bugging me for a while now is that the CLAassistant wants the dependabot to sign the CLA, which is not going to happen for obvious reasons. The most recent example: https://github.com/triplea-game/triplea/pull/10432#issuecomment-1123134151

From what I was able to find out is that it's possible to add the dependabot to an exception list on the claassistant website. The caveat: You need admin permissions to do it (or explicit approval from an admin to your request), write permissions are not sufficient. That's why I can't do it myself.

/cc @DanVanAtta @ron-murhammer

**Comment by DanVanAtta** [comment]
I have given this a shot before and the 'name' field seemingly never matches correctly (not sure if it is a case where the name does not match, or if the white list does not work..)
@RoiEXLab  do you know the exact text to use for the dependabot exception? I'm willing to give it a try..

**Comment by RoiEXLab** [comment]
@DanVanAtta The official respository provides an example: https://github.com/cla-assistant/cla-assistant#can-i-allow-bot-user-contributions

It looks like you need to add the tag at the end so it would be `dependabot[bot]`

**Comment by RoiEXLab** [comment]
@DanVanAtta Bump

**Comment by DanVanAtta** [comment]
`dependabot[bot]` added let's see if it does the trick

**Comment by RoiEXLab** [comment]
@DanVanAtta Looks like it worked: https://github.com/triplea-game/triplea/pull/10648#issuecomment-1153415217

I just triggered the recheck manually and it is green now

**Comment by RoiEXLab** [comment]
#10672 Does not trigger a cla assistant warning, looks like we're good
