### ISSUE TITLE
Game Ladder

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1043]
For discussion:
- in game support of ladder, what features do we need to provide?
- any external support we really want (potentially replacing the need for the war club website)

Of note, we can dump data to the new github website without too much trouble (available as a json value visible to javascript)

**Comment by ron-murhammer** [comment]
My thought long term is to integrate the ladder into the game and have the website just be read-only view of the standings/etc. All the ladder data would be saved to a DB. Some things to consider:
- Online/lobby vs PBF/PBEM?
- Ladder for which maps/settings?
- Need for a timer for online/lobby play?

**Comment by DanVanAtta** [comment]
I'm also curious what the win/loss reporting mechanism would be.

Perhaps we could call the ladder a 'league', and have a dedicated window for it. On this window you would see any open game challenges. You could also see league members and their stats. The stats could be just a game history, who they played against and the win/loss result. If not reported, then it'll simply be marked as not reported.

**Comment by Deltium** [comment]
Hi - as noted in my other post, the ladder and associated ELO ratings are a very important part of the community.

**Comment by yamamot0** [comment]
Hi,

only a system based on ELO would be meaningful.
https://en.wikipedia.org/wiki/Elo_rating_system
Old players should have a conservative K-faktor
New players should have a higher K-faktor for about 30 games
A system based on wins and loses is very easy abused and doesnt say anything about the strength of a player. 

The laddersystem should also make it easy for the mods to detect abuse, like a player playing against himself. This could maybe be done by saving Macs, IPs and opponent played, so the mods can check if somebody have suspicious results.

Best regards

**Comment by DanVanAtta** [comment]
I'm thinking we should first:
1. switch from derby to mysql
2. focus on storing match history, then we can re-calc ELO from scratch on the fly
3. with the match history, we can report the last game round played, the TUV of both sides
4. Then build a way to report wins/losses

It's going to be really tricky to get the last part working well. Players are going to want to game the system, and it'll be tough to keep it accurate.. We've some time before we cross that bridge though.

**Comment by RoiEXLab** [comment]
Refreshing this issue, since we got the new forum up and running...

**Comment by prastle** [comment]
Found this https://www.phpbb.com/community/viewtopic.php?t=2095711

Mysqk php based tho.  Cant seem to find any plugins for nodeb.  Have you had any luck @RoiEXLab

**Comment by RoiEXLab** [comment]
@prastle I got into nodebb coding yesterday I could probably code something like this in a week.
I thought @DanVanAtta was against an forum integrated solution?

**Comment by prastle** [comment]
Ah yes I guess he wants to build into engine.  Your prob correct.

**Comment by DanVanAtta** [comment]
Short, medium term, could actually make sense.

If we run the ladder with 6 month seasons (ie; ladder stats reset every 6 months), then we could simply spin it down when we have the in-game ladder built. The in-game ladder can be launched at any time meanwhile, then when the next season expires we can see if we want to have both, or just use the one. If the in-game one is any good, then players should not be too unhappy to have the next 'season' be only on the one ladder system.

**Comment by Deltium** [comment]
Out of curiosity, what is the benefit of resetting the statistics after 6 months?  If we are using ELO methodology, an improving player will naturally rise in the rankings, and vice-versa.  It would be discouraging for many (including myself) to work hard to achieve a rating and then have it all erased and start from scratch again.

That being said, I do advocate for players' names to actually fall off the rankings if they do not play at least one game quarterly, for example, or some other frequency/# that indicates that the player is not just sitting back and ranked as #1 indefinitely.   DAAK uses a similar approach on their website.

Last, but not least, we need to proactively deal with people who abandon games, which occurs typically when they have a losing position.  This is easily addressed but wanted to flag it.

Cheers, Deltium

**Comment by prastle** [comment]
To revisit this thought.  I realize that all would like the ladder built into the engine but I don't believe this is happening anytime soon.  I have opened us an account at Case's Ladder as a private league.  A private league is by invite only which can be done through our forum.

  Can some devs look at this a bit and see what they think?

1st it's free
2nd they maintain the ladder and we get a free site there.  Not that we need it.
3rd everything is still played and recorded using our server and forum
4th they have 13 million users which we could eventually access as well
5th once setup our members don't really ever have to look at case's ladder again if they don't want to other than a link for our private ladder standings through our forum

I have not bothered fleshing out the page yet until interest or agreement is reached. 

THE CATCH

some advertising but most can be removed
mods have to post the results ( called tournament directors there or td's)
we would need a private league per ladder  since all matches played get recorded to that private league's ladder

http://www.myleague.com/triplea

Thanks to all for all your hard work!
Pras

**Comment by DanVanAtta** [comment]
@prastle  bit late, but no objection to doing what you can in the meantime while we're waiting for more work to be done here. 

@Deltium  to answer your question: 
>  what is the benefit of resetting the statistics after 6 months?

Basically the idea is you would have 'seasons'. The stats/rankings wouldn't be deleted, but they would be frozen and new a season would start. The permanency, and knowing you 'won' a season would be more appealing I think over a single long running stat. 

Closing this for now. I'm working on a DB migration so we can expand our DB usage, which a tourney feature would require (among a few other things). Still some time out for tourneys..
