### ISSUE TITLE
TripleA-2.6.757 missing image icon that should NOT be there

### ISSUE THREAD

**Issue by TheDog-GH** [triplea-game/triplea#10453]
Testing 2.6.757 and this happened, in 2.5 this does **not** happen.

![image](https://user-images.githubusercontent.com/71022517/168809163-6a72d0e0-80aa-4bda-9e96-0e2fd17d6153.png)

xml wise this should be covered by the following line
`<option name="destroyedWhenCapturedBy" value="$AllPlayers$"/>`

So the missing image icon should **not** be shown ?
The units: = 3
But only 2 units are shown.
Not sure if this is relevant, but the territory does not contain the missing icon image, should it ?

**Comment by TheDog-GH** [comment]
Done
If you need the map its here
https://forums.triplea-game.org/topic/2467/settlers-fallen-empire-official-thread
or here
https://drive.google.com/file/d/1R-3ikP7eTXRAYzlILNXpdQcZRcJJSbYK/view?usp=sharing

**Comment by asvitkine** [comment]
Ah, so the issue is not that the image is missing, but that the unit shouldn't exist because it should be destroyed when captured? Can you confirm that this bug isn't present in 2.5 (i.e. check that the unit actually doesn't exist by using the territory tab).

**Comment by TheDog-GH** [comment]
_Ah, so the issue is not that the image is missing, but that the unit shouldn't exist because it should be destroyed when captured?_
Correct.

_Can you confirm that this bug isn't present in 2.5 (i.e. check that the unit actually doesn't exist by using the territory tab)._
Its difficult to replicate as that map has completely random setup.
I will try and edit an attack and try to get the same result in 2.5

**Comment by TheDog-GH** [comment]
2.5 edit mode battle

![image](https://user-images.githubusercontent.com/71022517/168853302-6da2916f-209b-41ea-acc3-9c24eeb04629.png)

The settlement did have a Sorcerers-Tower.
The territory **does** show the correct number of units, 9, (8 Spears + 1 Commander)

**Comment by TheDog-GH** [comment]
@asvitkine 
A gentle reminder about this issue.

**Comment by asvitkine** [comment]
Thanks for the ping. My guess is the root cause is the same as the one being discussed here: https://github.com/triplea-game/triplea/pull/9962

Let's wait for that to be fixed and re-check this.

**Comment by asvitkine** [comment]
Once it's available, can you check whether the issue happens on https://github.com/triplea-game/triplea/releases/tag/2.6.836 ?

**Comment by asvitkine** [comment]
@TheDog-GH Can you double check whether this still happens with the latest 2.6? I'd like to know whether the revert of the capturing issue fixed this or not.

**Comment by TheDog-GH** [comment]
I have literally just finished testing this with 2.6.858

I can confirm that the revert, fixed the issue and I dont get the missing icon image, so thanks.

So Im closing this issue.
