### ISSUE TITLE
Gracefully handle map folder deletion

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1045]
Use settings option to change which folder is used for maps.
Download a map.
Select the downloaded map, it will be the new 'default'
Now delete the map folder

Try to start the game, or download maps, etc..

**Comment by ron-murhammer** [comment]
@DanVanAtta So we just need to add a check for if the 'default' (which is really last selected I believe) can't be found then probably just use the first map in the list?

**Comment by DanVanAtta** [comment]
Problem could be a bit deeper. We make a number of assumptions that the map folder will exist, default or custom. For here, we need to verify that we'll handle the case that the folder is no longer present (which would imply no maps at all if we were to try and list them).

**Comment by ron-murhammer** [comment]
@DanVanAtta Gotcha. The issue I describe exists as well. Where even if you keep the standard folder but just delete the map you last played then the game shows the error console when you launch it (this actually is a regression as well since it works ok in 1.8.0.9).

**Comment by DanVanAtta** [comment]
#1052 handles both cases of this it turns out. Deleting the map or maps folder are handled well.
