### ISSUE TITLE
Improvements to PBEM

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1049]
Discuss here things we would like different about PBEM
- The setup is not very streamlined. Ideally would not need to enter in a server name at all. 
- Add a list of favorites so you can remember in-game opponent email addresses.
- Automatically allow a live game to be converted to PBEM and vice versa. When converting, prompt players for their emails, and then add a favorite contact that would match

**Comment by simon33-2** [comment]
Isn't point 3 already possible by saving and loading? Seems easy enough.

The only part about PBEM/PBF I find not streamlined is loading the existing save game.

**Comment by DanVanAtta** [comment]
Saving/loading can be cumbersome when saving to a file that is not on the default load path. Second, a live switch allows for someone to continue a game via PBEM while waiting for an opponent. For example, a person could play a game in the lobby connected to a dice roller, and turn the dice roller off when their opponent arrives.

@simon33-2 can you give details on what you may have had in mind to improve for the load game, or what you found particularly not stream lined?

**Comment by simon33-2** [comment]
What is cumbersome is needing to navigate to the download directory, change the sort order to descending by date/time and then loading up the file. That is why I suggested a command line option to allow the OS to connect TripleA to the .tsvg file extension. I don't see the problem with that but it seems others do.

I understand some of the above is improved in 1.9.

**Comment by DanVanAtta** [comment]
Linking a related issue, to use the Lobby as a built-in email relay to automatically send the game email from in-game: https://github.com/triplea-game/triplea/issues/675

**Comment by RoiEXLab** [comment]
@DanVanAtta While testing the new httpclient changes, I found some issues with the warclub site, related to the dice roller...
For one, the PHP version seems to be 5.5+ and the website is stil using the outdated mysql extension... Every time the webiste is "opened"/requested, a php warning is sent telling you that this extension is deprectated:
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
		<title>	M.A.R.T.I. Server --> "more accurate rolls than irony"- server</title>
	</head>
	<body>
		<br />
		<b>Deprecated</b>:  mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in <b>/usr/share/nginx/html/tripleawarclub.org/public_html/dice/dice.class.php</b> on line <b>39</b><br />
		<p>Dice results were sent via email!</p> <br> <a href="http://dice.tripleawarclub.org/MARTI_verify.php?<insert get params here>">click here to verify the roll</a><br>your dice are: 2<p><p>
	</body>
</html>
```

**Comment by DanVanAtta** [comment]
@RoiEXLab , is the above still a problem? I'd very much like to see the dice roller re-written to not be PHP, but that is another topic.

**Comment by RoiEXLab** [comment]
@DanVanAtta Not anymore... 
The dice server php version was updated to php7 and therefore those old commands were no longer available. 
Fortunately there was a file called dice.class.new.php in the root directory of the server which was ready for php7
