### ISSUE TITLE
How to build unstable release artifacts?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#105]
How are we going to build the unstable release artifacts? 

The Travis CI release work flow is triggered on tags. I propose we answer the above question above by tagging after we merge into master. If the version number did not increment we delete the current version tag and  re-add it to the current commit. In this case artifacts will auto-magically be regenerated. If the version number did change, then we simply add the new tag and again new artifacts will be created.

**Comment by gaborbernat** [comment]
What about adding another number at  the end. This notes each release
candidate. Some release candidates will not be stable.

Bernát GÁBOR

**Comment by DanVanAtta** [comment]
I think I went into a lot of detail about the release process in #129 (release numbers), or at least in that ticket a way to build release is implied based on the version. Will resolve this ticket in favor of #129.
