### ISSUE TITLE
TripleA-2.6.833 loss of a  Fort (Construction 0,0,0) first, even when defended

### ISSUE THREAD

**Issue by TheDog-GH** [triplea-game/triplea#10552]
In 2.6.833 this happens below, the loss of a  Fort (Construction 0,0,0), the defenders are supposed to die first and then the fort is either Captured or Destroyed, as in 2.5.

![image](https://user-images.githubusercontent.com/71022517/171405733-4b12a09b-1e4c-4659-9fa2-192a5a11be5b.png)

The image comes from here
https://forums.triplea-game.org/topic/2467/settlers-fallen-empire-official-thread
or here
https://drive.google.com/file/d/1R-3ikP7eTXRAYzlILNXpdQcZRcJJSbYK/view?usp=sharing

If you need a saved gamed just ask.

**Comment by TheDog-GH** [comment]
If you after the Fort xml code, it is below

```
    <attachment name="unitAttachment" attachTo="Fort" javaClass="games.strategy.triplea.attachments.UnitAttachment" type="unitType">
        <option name="maxBuiltPerPlayer" value="9"/>
		<option name="attack" value="0"/>
		<option name="defense" value="0"/>
		<option name="movement" value="0"/>
			<option name="isInfrastructure" value="true"/>						<!-- can be captured & does not take part in combat -->
            <option name="isConstruction" value="true"/>                      	<!-- place anywhere owned -->
            <option name="constructionType" value="a_Fort_structure"/>
            <option name="maxConstructionsPerTypePerTerr" value="1"/>			<!-- was 3 -->
			<option name="constructionsPerTerrPerTypePerTurn" value="1"/>
			<option name="canOnlyBePlacedInTerritoryValuedAtX" value="1"/>
				<option name="canBeDamaged" value="true"/>						<!-- used by catapult as raid damage -->
				<option name="maxDamage" value="2"/>
				<option name="canDieFromReachingMaxDamage" value="true"/>
			<option name="destroyedWhenCapturedBy" value="Merefolk:Celestial:Dragonkin:Ratkin:Demon"/>
			<option name="createsResourcesList" value="0:PUs"/>
    </attachment>

<!-- Fort -->
       <attachment name="supportAttachmentFortAllied" attachTo="Fort" javaClass="games.strategy.triplea.attachments.UnitSupportAttachment" type="unitType">
            <option name="unitType" value="Commander:Necromancer:Sorcerer:Wizard:Lgt-Infantry:Hvy-Infantry:Bow:Spear:Lgt-Cavalry:Hvy-Cavalry:Catapult:Horned-Demon:Mere:Gigas:Swarm:Pack:GiantRat"/>
            <option name="faction" value="allied"/>
            <option name="side" value="defence"/>
            <option name="dice" value="strength"/>
            <option name="bonus" value="2"/>
            <option name="number" value="5"/>
            <option name="bonusType" value="Fort_Wall_Allied"/>
            <option name="players" value="Imperial:Dwarf:Elf:Merefolk:Celestial:Dragonkin:AlAnfa:Orcs:Undead:Ratkin:Demon"/>
            <option name="impArtTech" value="false"/>
        </attachment>
       <attachment name="supportAttachmentFortEnemy" attachTo="Fort" javaClass="games.strategy.triplea.attachments.UnitSupportAttachment" type="unitType">
            <option name="unitType" value="Commander:Necromancer:Sorcerer:Wizard:Lgt-Infantry:Hvy-Infantry:Bow:Spear:Lgt-Cavalry:Hvy-Cavalry:Horned-Demon:Mere:Gigas:Swarm:Pack:GiantRat"/>	<!-- note not catapult -->
            <option name="faction" value="enemy"/>
            <option name="side" value="offence:defence"/>
            <option name="dice" value="strength"/>
            <option name="bonus" value="-1"/>
            <option name="number" value="10"/>
            <option name="bonusType" value="Fort_Wall_v_Enemey"/>
            <option name="players" value="Imperial:Dwarf:Elf:Merefolk:Celestial:Dragonkin:AlAnfa:Orcs:Undead:Ratkin:Demon"/>
            <option name="impArtTech" value="false"/>
        </attachment>

```

**Comment by TheDog-GH** [comment]
Note this example is using version **2.6.836**  so same result as 2.6.833, hence posting in this thread.

Below the attackers got wiped out, but still managed to destroy the Fort, its a Construction so should not happen.

This **might** be relevant, if the Ratkin **had** won the fight they would of destroyedWhenCapturedBy, see code extract above.

This was not a one off, but the best example. 

![Fort killed 1](https://user-images.githubusercontent.com/71022517/171574360-6c96b400-94e7-424c-92da-fb9f49711ab2.png)

**Comment by asvitkine** [comment]
Do you mind providing a savegame?

**Comment by TheDog-GH** [comment]
Here is the latest complete game map if you need it.
https://drive.google.com/file/d/1QnHemDe31oJCgNCdmO0fe-xyUJv4MkKd/view?usp=sharing

Here is the saved game, saved as a zip, just take the defaults and at least one of the combats should yield the loss of a Fort before its time.
[build-6-3.zip](https://github.com/triplea-game/triplea/files/8835912/build-6-3.zip)

**Comment by asvitkine** [comment]
@TheDog-GH

That save game is not working for me. The file inside doesn't have a tsvg extension. If I just change the file extension from .zip to .tsvg, it also doesn't work in TripleA.

**Comment by asvitkine** [comment]
I tried with 2.5 and am seeing the same thing - the fort just auto-dies. So it seems 2.5 and 2.6 are working the same?

Example save on 2.5:
[fort_test.tsvg.zip](https://github.com/triplea-game/triplea/files/8839262/fort_test.tsvg.zip)


For the effect you want, I think you just need to set `isInfrastructure` on it, no?

Or am I missing something?

**Comment by TheDog-GH** [comment]
My bad.
Yes isInfrastructure was missing.

Apologies for wasting your time.

Closing this Issue.
