### ISSUE TITLE
Tasklist/workflow

### ISSUE THREAD

**Issue by ZjelcoP** [triplea-game/triplea#1058]
As is obvious there are a huge number of tasks around for the game engine, map repo, website etc.
My request and advice would be to have a shortlist of tasks that more people can perform besides the core developers or experienced IT-people. This to relieve you java-wizards from some workload and perhaps get more people into contributing. By starting with easier tasks you lower the bar for people to contribute and they can learn and advance their knowledge. It is hard for everyone to follow all discussions and little projects around.
If however anyone can pick a task from the list that suites there skill set more people might do so.
Examples to put on the list would be play testing prerelease (what specifically?), updating map descriptions, writing guides etc.

We could make a sticky in sourceforge/General called "How can you help TripleA?"
The top post can hold the list with updated status.
The items could link to a specific issue in github.
I know there's this thread: http://tripleadev.1671093.n2.nabble.com/TripleA-is-looking-for-Volunteers-tp7582288.html  Thing is the functions offered though with some humor they could be intimidating for some. Get people started with little things and they might take up more in the long run.

Not wanting to pile up yet another task for you guys I can also put it up there but would need some input on tasks and their definitions/instructions (believe map descriptions are still awaiting final decision/design) and someone to sticky it.

**Comment by ron-murhammer** [comment]
@ZjelcoP My thought for now would be to have a label here in the github issues that can be used to mark certain issues as 'non-technical' or something. Then non-developers can filter by that to see what is available.

**Comment by ZjelcoP** [comment]
That sounds very good. Though i would still like to sum up some or all of those issues in the mentioned new post on sourceforge. This mainly for greater reach, we do get quite a few people with some skills visiting there i believe. Not many people know their way to github yet.
They items on the list would then connect directly to the labeled issue on github.
And they don't all have to be completely "non-technical", just lower level technical (not directly related to the game-engine).

**Comment by ron-murhammer** [comment]
@ZjelcoP So we are going to try out zenhub extension for organizing issues. I would recommend that we just have a SF post that links to the boards so we aren't copying/pasting back to SF. Please see #1059
