### ISSUE TITLE
Getting more done in GitHub with ZenHub

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#1059]
Hola! @ron-murhammer has created a [ZenHub](http://www.zenhub.com) account for the **triplea-game** organization. ZenHub is the only project management tool integrated natively in GitHub – created specifically for fast-moving, software-driven teams.

----

#### How do I use ZenHub?

To get set up with ZenHub, all you have to do is **[download the browser extension](https://www.zenhub.com?utm_source=ZHOnboarding)** and log in with your GitHub account. Once you do, you’ll get access to ZenHub’s complete feature-set immediately.

#### What can ZenHub do?

ZenHub adds a series of enhancements directly inside the GitHub UI:

- Real-time, customizable task boards for GitHub issues;
- Multi-Repository burndown charts, estimates, and velocity tracking based on GitHub Milestones;
- Personal to-do lists and task prioritization;
- Time-saving shortcuts – like a quick repo switcher, a “Move issue” button, and much more.

### [Add ZenHub to GitHub](https://www.zenhub.com?utm_source=ZHOnboarding)

_Still curious? See [more ZenHub features](https://www.zenhub.com/features?utm_source=ZHOnboarding) or read [user reviews](https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd/reviews). This issue was written by your friendly ZenHub bot, posted by request from @ron-murhammer._

![ZenHub Board](https://cloud.githubusercontent.com/assets/8771909/11153956/233ac4a8-89f1-11e5-94b1-1569d3f38b4d.png)

**Comment by DanVanAtta** [comment]
Any items where you think zenhub is of particular help  @ron-murhammer ? 
I need to get the plugin re-installed.

**Comment by ron-murhammer** [comment]
@DanVanAtta Mostly the task boards. I think we are hitting the threshold on number of open issues that can be managed with just tags. I think having boards to visually categorize and prioritize issues should help. Then we can use tags to further classify issues under each queue. I also think we want to limit the number of tags to say 10-15 different ones otherwise its too difficult to figure out what tags to use (I deleted a bunch of tags that weren't being used much).

I'm also starting to think general 'discussions' like some of the warclub stuff doesn't really belong in github issues here. I think we want to try to keep the focus on primarily engine discussions and code change issues. I think we want to keep github primarily for developers, map makers (in the maps repos), and users reporting issues.

**Comment by DanVanAtta** [comment]
I agree and think it makes sense to have the game engine issues (github.com/triplea-game/triplea/issues) be for task tracking (bugs, technical project tracking).

This implies to me we want three top level labels. Additional ones would be only meta tags. The three top level would be:
- wish list: I suggest we rename the current feature request queue to 'wish list', and add 'wish list' to just about anything else that is not already a feature request nor a bug. 
- 'Project': would be opened by developers to discuss/design/track projects they are about to start on, or  are working on. There should not be a whole lot of these. Third we'll also track bugs.
- Bug: basic bug tracking

I also agree that forums are better for discussions. There, let's pin a welcome message that has a link to the website's documentation page on how to submit bug reports and feature request instructions. Which raises a question, should feature requests always be discussed on forums first? If so, for how long should they be discussed there until they are moved to github? If not, any guidelines for which feature requests should be discussed where? Last, for items discussed on forums, if they are to be discussed there at all, who will move the items from forums to github?

**Comment by DanVanAtta** [comment]
To be more clear, I'm effectively suggesting that any issue always be tagged with one of "wish list" , "project", or "bug". We can keep the current tags we have, and work on those as things move along.

**Comment by ron-murhammer** [comment]
@DanVanAtta I think we have a lot of similar ideas here. I've actually already created a few boards to start from along the lines of your top level tags:
- Discussion - technical discussions, anything non-technical should be pushed to forum
- Feature Backlog (prefer feature over wishlist) - prioritized list of potential features
- Bug Backlog - prioritized list of bugs to fix
- Infra/Code Backlog - prioritized list of build, infra, code improvement, process, misc issues
- Next Release - what we are currently targeting for the next release (anything in progress should have an assignee)

My thought is every issue should get a tag identifying whether it is a discussion, feature, bug, infra/code (couple of tags here). Then we can have tags to categorize the portion of TripleA experience it affects such as UI, performance, AI, game play/rules, map support, etc.

For the most part each issue should end up with 2 tags with 1 from each list (sometimes it might not get a second tag or have multiple tags from the second list).

**Comment by DanVanAtta** [comment]
Updating README here:  https://github.com/triplea-game/triplea/pull/1082 

Will see about creating labels to match

**Comment by DanVanAtta** [comment]
Looks like Github now has a built in version: https://help.github.com/articles/tracking-the-progress-of-your-work-with-projects/
