### ISSUE TITLE
2.6: Defensive dice roll after attack inflicts casualties doesn't handle calculate support bonuses correctly

### ISSUE THREAD

**Issue by asvitkine** [triplea-game/triplea#10599]
### Reproduction Steps

1. Open the following save game: 
[2.5-correct-support-a.tsvg.zip](https://github.com/triplea-game/triplea/files/8848657/2.5-correct-support-a.tsvg.zip)
2. Attack Northern Italy with all units in the neighboring sea zone
3. Land 2 or more hits and select non-Infantry units to die as Germans

The defensive side should roll with 6 dice, regardless of number and types of units that were killed by the attack roll. This is how it works with 2.5.

In 2.6, the number of dice is reduced if supporting units were killed, which is incorrect.

### Attach a Save Game

See

### Engine Version

Engine Version: 2.6.857

**Comment by asvitkine** [comment]
@beelee1 filed based on your report on the forum. I confirm this looks like a 2.6 regression.

Probably this broke when a lot of the battle code was rewritten in 2.6. I'll try to find the revision.

**Comment by asvitkine** [comment]
I went as far back as 2.6.89 where the issue still repros (I needed to use edit mode from scratch because older 2.6 couldn't handle 2.5 saved games), here's a save that works with earlier 2.6 versions:
[repro-2.6-int.tsvg.zip](https://github.com/triplea-game/triplea/files/8849049/repro-2.6-int.tsvg.zip)

Before that tag, it used different numbering scheme so I couldn't go back in time. But if it's really the 89th PR since 2.6, then it shouldn't be too many to go through.

**Comment by asvitkine** [comment]
Actually, looks like older prereleases used bigger numbers for some reason, like:
https://github.com/triplea-game/triplea/releases/tag/2.6.22512

**Comment by asvitkine** [comment]
OK, getting somewhere.

[2.6.22311](https://github.com/triplea-game/triplea/releases/tag/2.6.22311) doesn't have the problem.
[2.6.22343](https://github.com/triplea-game/triplea/releases/tag/2.6.22343) does.

So somewhere between these releases.

**Comment by asvitkine** [comment]
Ok more narrow range, between [2.6.22324](https://github.com/triplea-game/triplea/releases/tag/2.6.22324) (good and [2.6.22328](https://github.com/triplea-game/triplea/releases/tag/2.6.22328) (bad)."

```
git log 2.6.22324..2.6.22328

commit bf7a5367047e34f0f384f19176654a45d54a0048 (tag: 2.6.22328)
Author: trevan <trevan@users.noreply.github.com>
Date:   Wed Nov 4 19:50:34 2020 -0700

    Use new roll dice, select casualties, and remove casualties steps (#8087)
    
    The Fire and FireAa classes are no longer used in building the 3 fire
    sub steps.
    
    The AirVsNonSubs step is removed because that firing group is now named
    and will be displayed in the battle ui when it fires, selects, and
    removes.

commit ca8059a6f04948016cb40638d3be5fea8519e0c9
Author: trevan <trevan@users.noreply.github.com>
Date:   Wed Nov 4 19:49:34 2020 -0700

    Make the gameChooser use DefaultGameChooserEntry instead of String (#8080)
    
    * Make the gameChooser use DefaultGameEntry instead of Strings
    
    In a map, a designer might accidentally include two map files with the
    same name.  Both will show up in the UI but because the UI uses the
    String as the key, selecting either of the two entries in the UI will
    always load the same map. By changing the UI to use the
    DefaultGameEntry object, both of the UI items will select their
    corresponding entry.

commit 573310f8823f8731ccdc208a314218c1f4e4a2c4
Author: trevan <trevan@users.noreply.github.com>
Date:   Wed Nov 4 19:49:03 2020 -0700

    Convert Map<Unit, TotalPowerAndTotalRolls> into an instance of TotalPowerStrengthAndRolls (#8078)
    
    Split AA logic and non-AA logic into two separate classes with a common
    interface. AaPowerStrengthAndRolls is for AA logic and
    PowerStrengthAndRolls is for non-AA logic. TotalPowerAndTotalRolls is
    the common interface.
    
    Correct terminology of power, strength, and rolls in methods and variables.
```

@trevan could you take a look?

**Comment by asvitkine** [comment]
@DanVanAtta I can't see @trevan in the list when I try to assign them the issue, do you need to add them?

**Comment by beelee1** [comment]
@asvitkine yea 2.6.801 is far as I can go back. Thanks for jumping in on this

**Comment by beelee1** [comment]
@asvitkine it appears this is only happening for the defensive Player.
![Screenshot from 2022-06-07 23-41-06](https://user-images.githubusercontent.com/24382682/172533321-4b9e282c-c1d3-4717-b2f6-ba664f4b6a44.png)

**Comment by asvitkine** [comment]
A possible fix is this:

```
 -           .friendlyUnits(step.getBattleState().filterUnits(ALIVE, step.getSide()))
 +           .friendlyUnits(step.getBattleState().filterUnits(ACTIVE, step.getSide()))
```

In MainDiceRoller.java. But I need to look more if there are other implications.

**Comment by asvitkine** [comment]
Should be fixed in the next prerelease. Please let me know if you notice something still not quite working right. Thanks!

**Comment by trevan** [comment]
@asvitkine , sorry but life made it more complicated to participate as much here.  But your fix looks like it should work.  ALIVE means units that have not been killed.  ACTIVE means units that haven't been removed from the battle because they have a chance to fire back.  So, for a support unit that has died but still should be giving support, ACTIVE would probably be the better enum.
