### ISSUE TITLE
crash latest beta running mint withcinnamon

### ISSUE THREAD

**Issue by BCS-DSO** [triplea-game/triplea#10635]
crash report suggested filing this

**Comment by asvitkine** [comment]
Is there any error message?

**Comment by BCS-DSO** [comment]
that one just crashed, though .895  the latest has bee stable apart from the latest AI which also causes a crash - otherwise was ok.

I still can’t get maps though!


Yours Faithfully,


David S. Misell MIET MBCS CISSP

0207 7239135

http://linkedin.com/in/misell

https://www.youracclaim.com/badges/b9e605c3-39d7-47f6-a38b-af3cebe94465

https://www.youracclaim.com/badges/30d3d123-a869-4d77-9a99-db7a4efb9f90





On 12 Jun 2022, at 04:07, asvitkine ***@***.***> wrote:


Is there any error message?

**Comment by asvitkine** [comment]
Can you provide a screenshot of the error when it crashed - even for AI crash.

**Comment by BCS-DSO** [comment]
all cleared now - i just put latest one in, sorry
Yours Faithfully,


David S. Misell MIET MBCS CISSP

0207 7239135

http://linkedin.com/in/misell

https://www.youracclaim.com/badges/b9e605c3-39d7-47f6-a38b-af3cebe94465

https://www.youracclaim.com/badges/30d3d123-a869-4d77-9a99-db7a4efb9f90





On 12 Jun 2022, at 22:15, asvitkine ***@***.***> wrote:


Can you provide a screenshot of the error when it crashed - even for AI crash.
