### ISSUE TITLE
AiGameTest > testAiGame sometimes fails with "No winner after 100 rounds"

### ISSUE THREAD

**Issue by asvitkine** [triplea-game/triplea#10649]
I've not seen this in any local runs of the test, but I have seen this on the CI bots. Example:
https://github.com/triplea-game/triplea/runs/6867290877?check_suite_focus=true

Ideally, we could dig into what's going on. The test run will actually result in autosaves like "autosave_round_even.tsvg" being saved, which can be loaded to inspect what happened in the game (the more granular autosaves are disabled).

So if we could get access to these, we can inspect the turns and figure out what's going wrong. Theoretically, it's possible the dice rolls end up such that the game is naturally a stalemate, but I suspect it's more likely that there's an AI bug that doesn't handle some game states well (e.g. perhaps building undefended transports that get destroyed each turn or whatever).

@DanVanAtta is there any way we can recover the save game from test bots? If not, could we make the test code upload the save file to somewhere in the case of such a failure?

**Comment by asvitkine** [comment]
OK, I got a repro locally. Here's a save.

Russians keep buying bombers and Germans keep buying tanks. No one ever invades the other because no ships built.
[autosave_round_odd.tsvg.zip](https://github.com/triplea-game/triplea/files/8896463/autosave_round_odd.tsvg.zip)

@ron-murhammer Any thoughts on this?

**Comment by asvitkine** [comment]
I think Russians AI is the one not playing right. They don't need so many bombers and given they got the middle island, they should instead build a fleet. At the very least, capturing Corner 1 should be simple.

Maybe it's a case where they can't build a useful fleet in one single turn and they don't know how to save up to build one later? But given Germans just have one bomber, they should be able to build up a fleet in their home sea zone even one turn at a time...

**Comment by asvitkine** [comment]
Interesting that the win% if 180%. That doesn't seem right.

If I boost the score of the cruiser, it does get chosen for simulation, but then the result is:
```
    SZ 1, can't defend TUVSwing=1061.7305011554643, win%=162.73050115546425, tried to placeDefenders=[cruiser owned by Russians], enemyAttackers=[bomber owned by Germans]
```

Even though a manual battle sim results in a 34% win rate for the bomber and both units cost the same amount of PUs to build. That seems suspect, I'll investigate.

(In terms of human strategy, I think building a cruiser is definitely the right call here with the available income, and over time building up an attack fleet.)

**Comment by asvitkine** [comment]
If I manually edit the map and add a few cruisers to the territory, it seems to unstuck the AI and it starts building transports and ground attack units, which I think will eventually allow it to attack Germany (but it takes Corner 1 pretty soon).

**Comment by asvitkine** [comment]
So then the AI proceeded to build enough units to be able to take the enemy's capital (99% win rate), but never attacked. Here's a save:
[test1_should_win?.tsvg.zip](https://github.com/triplea-game/triplea/files/8914599/test1_should_win.tsvg.zip)

So that also seems wrong.

**Comment by asvitkine** [comment]
Back to why the AI won't build the cruiser if I hardcode that to be the highest scoring unit.

The win % > 100 comes from the estimateStrengthDifference() code path. If I comment that out and make it do a real battle calc, then the result is more sensible:

```
    SZ 1, can't defend TUVSwing=1.8181818181818181, win%=35.35353535353535, tried to placeDefenders=[cruiser owned by Russians], enemyAttackers=[bomber owned by Germans]
```
That matches the battle calc (assuming win% is the attacker's win), although the AI still concludes "can't defend" - not sure if it just doesn't meet some threshold, or there's a bug where it's thinking it's own win rate is 35%.

**Comment by asvitkine** [comment]
OK, so the bomber attacks on a 4 and the cruiser defends on a 3. So actual win% is 40% for the attacker and 20% for the defender and 40% draw rate, so it's true that the attacker is favoured.

However, it's still the right move, since you want to build a fleet in this case (since all enemy territories are overseas). Obviously, another good strategy is for the AI to save its income and build a bigger fleet next turn in one go, but let's ignore that for now.

So the TUV swing is 2.4 for the attacker. We're making 12 PUs a turn and the enemy only 8. Both units cost 12 PUs.

So if we math it out:

40% draw rate = both sides lose 12 PUs, so we're turning income to 0 / -4.
20% defender win rate = we lose 0 PUs, they lose 12 PUs, so income becomes 12 / -4
40% attacker win rate = we lose 12 PUs, they lose 0 PUs, so income becomes 0 / 8

So average that out, our expected income becomes 2.4 and the enemy's 0.8, making us outproduce the enemy 3:1 (as opposed to 1.5:1 before). So it's still a worthwhile thing to do, although obviously because it's a toy map, we can perfectly calculate things and do it in isolation here, something that doesn't scale to real maps.

Still, I wonder whether we could use the PU income ratio between us and the enemy (or our alliance vs. the enemy's) to reason about TUV thresholds, as opposed to just having a `TUVSwing < 0` check.

**Comment by ron-murhammer** [comment]
Yeah, I think you are essentially hitting an edge case of the AI where it chooses not to start building a fleet as it sees it as it will lose TUV in the battle. Most maps there will be some factory where it can safely build a navy but some of these small test maps that's not the case.

**Comment by asvitkine** [comment]
If I double the player's PUs, they will build a carrier with a fighter on it. So maybe we could detect the "all enemies are overseas so we need a fleet" case and save our PUs if we don't need to buy any defense. In this case, it would cause one turn of no-buy and then them being able to recover appropriately.

**Comment by asvitkine** [comment]
Should be fixed with https://github.com/triplea-game/triplea/pull/10675.
