### ISSUE TITLE
Strategic Bombing bug

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#1066]
Hi,
Somewhat frustrated here. I have a fix for the Strategic Bombing bug which appears to work. That is the bug where you can send several bombers against a territory including tactical bombers which can't attack factories in Axis and Allies.

The bug comes in because the AA is rolled against the whole formation and allows the attacker to select casualties. This should not be allowed. The AA should roll against each attack group - the one attacking the airfield should be different from the one attacking the harbour which should be different from the one attacking the factory, so long as isAAforBombingThisUnitOnly is set, which it is in the map.

The problem is that I want to shelve the nice to have PR which I have outstanding and put this one in, which the community will say is very important because there is no reasonable work around. How can I do that. Don't mind forking again or branching but I'm confused about how to do so.

**Comment by DanVanAtta** [comment]
Generally it's easiest when you keep the 'master' branch on your fork to track the 'master' branch in the main project.

- Create a new branch from the tip of your master
- Use that new branch for a new PR of the 'nice to have' work.
- Switch back to your master branch and run `git reset --hard HEAD^` until you have removed all of the new changes. 
- Once at a point where your master matches the master in triplea-game, then create a new branch, and begin work from there

**Comment by simon33-2** [comment]
Ok, but I haven't used GIT before. How do I force off the committed changes into the new branch?

**Comment by RoiEXLab** [comment]
@simon33-2  Watch a git tutorial then... [YouTube](https://www.youtube.com/results?search_query=git)

**Comment by simon33-2** [comment]
Ok, I have some code which I think is ready to commit but a few tests seem to fail. Looks like the issue is one point difference in bombing damage. The tests seem to expect 1d6+1 damage but I think this is wrong. It should be 1d6+2. Perhaps for certain maps it's 1d6+1? It is certainly 1d6+2 in Global 1940 2nd edition. In any event, it is confusing that this would suddenly be coming up now.

Should I update the tests to change the expected results to be what I expect? I'm a bit reluctant to do so because presumably there is some reason why the test is the way it is.

**Comment by DanVanAtta** [comment]
Let's be sure we really understand why the test code is failing. Either the code update is incorrect, or th test case is. Most of the time the culprit is the code, not the test. So let's be sure about which one needs updating.

**Comment by simon33-2** [comment]
Looking at the manual it seems the damage should be 1d6, not 1d6+1. There's something not quite right. If I do a "gradle test", it should run all the tests or just selected ones? Proceeds very quickly.

**Comment by simon33-2** [comment]
Found it. Larry Harris Tournament Rules are 1d6+1.

**Comment by Cernelius** [comment]
LHTR (which is a WWIIv2 mod only) you either, on SBR:

normal bombers: roll 1d6

heavy bombers (tech): roll 2d6, discard lowest (keep highest), add +1

WWIIv3 works the same, except you don't add +1 for heavies; but before the errata it worked like basic WWIIv2, instead.

**Comment by panther2** [comment]
Sorry that I have to interfere:

In Pacific, Europe, Global 1940 Heavy Bombers is:

**Rulebook, Europe/Pacific, 2nd Ed. Page 41**

> Heavy Bombers. Your strategic bombers are now heavy bombers. When attacking, whether in a battle or a strategic bombing raid, roll two dice for each bomber and select the best result.

>

**Comment by panther2** [comment]
This is how heavy bombers work in Pacific, Europe, Global 1940 2nd Ed.:

**Rulebook, Europe/Pacific, 2nd Ed. Page 41**

> Heavy Bombers. Your strategic bombers are now heavy bombers. When attacking, whether in a battle or a strategic bombing raid, roll two dice for each bomber and select the best result.

>

**Comment by simon33-2** [comment]
Presumably you will still add two to the result of the best dice.

Anyway, this change has nothing to do with heavy bombers and it seems the existing bomber test is not a good base and needs a complete rethink.

**Comment by simon33-2** [comment]
Alright, I have some test code which compiles. Trouble is I can't see how to run it, which is a bit of a problem.

**Comment by DanVanAtta** [comment]
`gradlew test` to run via gradle, which is what the build will run.
IntelliJ or Eclipse have built in ways to run tests, sometimes more convenient.

**Comment by simon33-2** [comment]
What I mean is that when I run a "gradle test" (because I'm on linux), the new test I have written is not run, as far as I can tell.

**Comment by DanVanAtta** [comment]
Check for test annotations to have your class get picked up, that it is named properly (suffixed test), and is in the test folder. Failing that, submit a PR (that is only for feedback) so we can see what you have.

**Comment by simon33-2** [comment]
Alright, I've updated my open PR. Do you have to merge into master to push? That doesn't seem right.

**Comment by DanVanAtta** [comment]
@simon33-2 , please clarify which master. There are three:
- the triplea master branch in github
- your fork of triplea master branch in github
- your local master branch on your desktop/laptop

Pushes to the triplea master branch are restricted, changes are done via PR there.

**Comment by simon33-2** [comment]
Ok, I still don't really follow why the test isn't working. If this change won't be merged until that is done, there's no point re-forking (which I can't see how to do).
