### ISSUE TITLE
TripleA-2.6.929 show Zoom percentage request

### ISSUE THREAD

**Issue by TheDog-GH** [triplea-game/triplea#10693]
@asvitkine 
Im really liking the new 200%.  👍 

But could we have the percentage of the zoom shown on screen for say 5 seconds and then it disappear?

Perhaps it could go here on the **X** (to left of the current Player, for a short duration?

![Screenshot 2022-06-18 092338](https://user-images.githubusercontent.com/71022517/174429474-f730b131-c261-4d07-a2bf-733abd50f825.png)

Then the player can return to 100% easily and also remember what zoom percentage works best on certain maps.
Thanks in advance.

**Comment by FedaSkywalker** [comment]
Hello, I’d like to try do this feature. Can you assign t to me?

**Comment by asvitkine** [comment]
@FedaSkywalker done

**Comment by FedaSkywalker** [comment]
Good. Thanks !

**Comment by asvitkine** [comment]
I think this was implemented by https://github.com/triplea-game/triplea/pull/12082.
