### ISSUE TITLE
Updating existing installation results in errors using Win-64 installer

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#1069]
I tested and reproduced the issue with different prerelease versions.
Steps to reproduce:

- Have an older version installed,  for example 2749
- Install a newer version (I used 2756) choosing "Yes, update the existing installation"
- Installer shows "Uninstalling previous version"
- Installer installs new version. So far so good.

When executing triplea.exe, a window pops up saying "Couldn't load main class"

When uninstalling through the control panel, a window pops up saying:  "Error, maybe it has been uninstalled before, do you want to remove the entry from the list?"

In some cases there has not even been an entry in the programs' list in the control panel.

The folder of the TripleA installation has to be manually deleted.

When installing "new" (without updating) everything runs fine again.

I also noticed that - when updating an existing installation - the file "uninstall.exe" is not present in the triplea directory.

**Comment by DanVanAtta** [comment]
@RoiEXLab @ron-murhammer @gaborbernat , could one of you look into this? running linux here, wont' be able to do this as efficiently with a VM

@panther2 which version of windows?

**Comment by panther2** [comment]
Up-to-date Windows 7, 64 bit. Java 8u101.

**Comment by DanVanAtta** [comment]
The installer was tweaked, @panther2  - could you give it another shot?

**Comment by panther2** [comment]
@DanVanAtta 

Tried all new versions up to and including 2814.
Same issues as before, sorry.

**Comment by DanVanAtta** [comment]
Could you give 2823 a try?

**Comment by panther2** [comment]
@DanVanAtta 

I tested 2829 - no success again, sorry.

**Comment by prastle** [comment]
Just dl the new from both i.o and direct x64
can confirm above written by panther
( Am Sad other version was working ) but I erased that installer and forget which one it was

**Comment by DanVanAtta** [comment]
not good to hear. There have not really been any updates to the installer. If anyone is able to pinpoint any of the last working versions, or even when it broke, would be tremendously valuable. Not running windows, I have trouble working on this..

**Comment by prastle** [comment]
rough guess two weeks ago was last one I installed that worked
shouldn't have overwrote it

**Comment by DanVanAtta** [comment]
Had some luck on  a VM, hopefully will work for win7.

Please first uninstall any existing 1.9 installations.
Then install: 1.9.0.0.2836
Then please try to upgrade to the next version, this will simulate future updates to the game. 


Fingers crossed.. Not much left before we release

**Comment by DanVanAtta** [comment]
Still seeing problem. Though, game can be launched via command line. The .exe file is not functional though ...

**Comment by prastle** [comment]
I'm win 10
ill try when ur ready

**Comment by panther2** [comment]
Yes, i must confirm that the same issues still occur trying 2836/2840.

I wonder that the file "uninstall.exe" is not copied to the directory when updating...
Maybe there are some activities of the older installation present "in the background" that prevent the correct installation and execution of the new files (just an amateurish idea of course)?

**Comment by prastle** [comment]
I also manually deleted whole file.  And complete new install.  It No longer asked to uninstall.  Still same error.

**Comment by RoiEXLab** [comment]
Could somebody test this with versions 1.9.0.0.2603 and prior? Not sure wether this solves this problem, but this is my only idea.

**Comment by panther2** [comment]
I installed 2603 over 2599 - still the same issues.

**Comment by RoiEXLab** [comment]
Ok that means, that the problem is not occuring due to the GameRunner change.

**Comment by panther2** [comment]
I have no idea for how long this issue exists. I noticed it by accident. Because regularly I perform a clean uninstall before installing a new version.

**Comment by panther2** [comment]
The oldest versions I have tested by now are 2572 over 2565 - same issues - so it must have been introduced even before.

**Comment by DanVanAtta** [comment]
I somewhat suspect that maybe it was always a problem.

We did update GameRunner2 to be consolidated with GameRunner. That is the only other thing I can think of.

I've been looking at ways to disable the 'replace existing install' and force a new install into a new folder. Has not been fruitful yet, and also updating the overwrite modes to always overwriting. Bit of a slow process.. 

thanks for the help in checking versions.

**Comment by DanVanAtta** [comment]
Okay, found a way to work around this problem to some benefit. I've updated the installer so that it no longer prompts to install over the last version. Now the game is installed to a new versioned folder each time. This will allow you to run multiple game engine versions pretty easily.

**Comment by prastle** [comment]
Great ty  I will give it a shot

**Comment by panther2** [comment]
Fair workaround! That leaves the user the option to either perform an uninstall before in order to install the new version into the same directory or use different versions in different directories.
I am closing this issue now. Thanks!

**Comment by prastle** [comment]
Sadly I am still getting the white screen java error.  What was the fix for this?

**Comment by panther2** [comment]
@prastle 
Look here: https://github.com/triplea-game/triplea/issues/1090
