### ISSUE TITLE
Merging Source Forge Forum With Warclub

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1071]
Picking up the discussion from #1037, let's start tracking the merge of the source forge forum to warclub. Use this issue to communicate on the topic, to get the latest info. First we should finalize the decision.

Warclub post: http://www.tripleawarclub.org/modules/newbb/viewtopic.php?topic_id=2317
Sourceforge post: http://tripleadev.1671093.n2.nabble.com/Forum-Migrate-To-Warclub-tp7593273.html

**Comment by DanVanAtta** [comment]
It looks like we need a 'maps' section on warclub to have parity for discussion.

**Comment by prastle** [comment]
U need everything forum gave for free

maps one of them

**Comment by ron-murhammer** [comment]
@DanVanAtta I'd say we are 90% confirmed on this. We need to investigate how to technically do the migration as well. The SF forum uses nabble and the warclub forum uses newbb. My guess is that we will need to export the SF forum to something like XML then write some scripts to feed the data into the warclub forum (I doubt there is any kind of converter between them).

**Comment by DanVanAtta** [comment]
Interesting, I was thinking we were going to leave the forum in place, and lock the threads, directing folks to the new forum. I'm curious how we will stop the in-flow of new topics on SF.
 Once we've stopped the in-flow, I think we have some time before we really should migrate data (assuming we should, as opposed to archiving it in-place)

**Comment by ZjelcoP** [comment]
All the forumposts in sourceforge are a goldmine to many people especially the mapmakers, besides that they are a part of the glorious History of TripleA. Would be a shame to lose it (if that is what was considered as an option).

**Comment by DanVanAtta** [comment]
Losing the source forge forum is not really an option. It'll perhaps be frozen/archived initially, and then probably data migrated into warclub.

**Comment by ron-murhammer** [comment]
@DanVanAtta Yep that was the process I was thinking of as well though I'm not that concerned if we lose a few recent posts when we move over. I would like for us to at least have a general idea of how we plan to migrate the data before we go call in and start freezing it.

**Comment by prastle** [comment]
Guys I realize this has been a big war but truth is forum info needed as well for all of us.  Take it slow my humble opinion

**Comment by DanVanAtta** [comment]
Not a big war at all..  Question is where should the forum info live. A mass migration of SourceForge forum content to WarClub forums is in the cards. But, the static content in the shorter term is probably best on github.io and not in warclub forums.  So short term copying static info content to github.io seems to be a good move.

**Comment by DanVanAtta** [comment]
2 sites vs 1 is still slightly under consideration, but we have time. IMO using cloud hosting is a good thing for where we can. We can do similar skins for both sites, so users would not even know they are hitting different servers depending upon the page. I can see also reason to merge to 1. Regardless, it'll be perhaps 6 months to 2 years before we really need to consider merging the 2 sites to 1 (2 sites being github.io + warclub)

**Comment by ron-murhammer** [comment]
Yeah hoping more like 6 months than 2 years but we'll see. Priority order in my mind is:
1. Release 1.9 and retire SF website
2. Migrate SF forum to warclub forum
3. Merge github.io and warclub websites

**Comment by DanVanAtta** [comment]
Created milestones for 1,2,3: https://github.com/triplea-game/triplea/milestones?with_issues=no

**Comment by prastle** [comment]
Sadly unsure where to comment

example of our prob

but
opened new froum and sub forum all to u guys in warclub tonight
need some help with mod edits
other that
u guys have 3 new rooms not attached to home page
titled as before
best I can do without help
also turned on all uploads etc in those rooms for all cept anonymous user

trying to help love this site gl
hf gents

+

**Comment by DanVanAtta** [comment]
Thanks @prastle. 

If ever unsure of where to post a comment here, feel free to create a new one: https://github.com/triplea-game/triplea/issues/new  (or click the new button on this page:  https://github.com/triplea-game/triplea/issues)

**Comment by DanVanAtta** [comment]
Next steps are to replace and migrate to a new forum. Then figure out how to replace the lobby. Then things will be consolidated. That will not be tracked though in this issue.. Closing. (for now we have an uneasy status quo where warclub has impaired functionality, and the forum is the last thing left in source forge)

**Comment by prastle** [comment]
Server crashed need help it wont reload from old commands



________________________________
