### ISSUE TITLE
In-Game Challenge System

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1072]
Tracking system for everything related to an in-game challenge system.

"challenge" is defined here as an invite to play a game, with specific rules/parameters in mind. 

A first question, when a challenge is issued, how should the bidding work? Both players secretly submit their lowest bid for either side, and the lowest bid is then chosen?

IE: I'll play axis with 9 or allies with 8. While the opponent may say, axis with 15, or allies with 12. Then the bid of 8 for allies would win. Or should it be an option for a more fixed bid? IE: "8 goes to allies, you can play as them, or I will"

**Comment by Deltium** [comment]
Hi - with respect to bidding, it is important to allow the players to bid and not fix the bid.   There are two ways to do it.  The first way, is how AAMC handles bidding, e.g.  each side submits ONE bid and then computer determines the lowest bid.  In the event of a tie, the computer selects one person at random.   The second (and current method) is that two players simply agree to start bidding manually (e.g. a random Marti test die is rolled to see who begins bidding), and then each player bids lower until somebody decides to stop.    Either way is OK, and I don't think that we need to worry too much about the bidding system at the moment, as it's working OK in the interim.

**Comment by DanVanAtta** [comment]
Requirements:
- send a challenge request, with the following specified:
 -  which map
 - LL, dice or either
 - tech
 - specify bidding options
 - (maybe) handle generic game options, kamikaze for example
- view open challenges
- accept a challenge
- person who sends a challenge should confirm challenge acceptance before game starts IE: game starts after you accept the challenge, and then after I accept that challenge.


Non requirements:
- no result tracking for the moment, introduces a number of problems. Let's also not load down the first version with every feature we can think of out the gate


Challenge communications is something to consider. Email or in-game notifications are options. In-game I think is preferable and more useful in the end (for example, a window opens in the background that has a ladder news feed with notifications of when it is your turn, when challenges have been accepted, etc)

**Comment by DanVanAtta** [comment]
Closing for now. I'm still working on this, though this issue is not useful for tracking at the moment.
