### ISSUE TITLE
TripleA Major Development Initiatives

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1073]
I would like to list out the major goals/initiatives for tripleA, and to perhaps discuss them a bit.
- Right now the main development priority is to get 1.9 tested and released. This will simplify things as we will be in far less of a transitional state from sourceforge to github

Once that is done, there are a number of important projects:
## Efficiency And Ability to Release Code Updates
- general re-organization and re-modelling of the code so it is built in an OO and/or a functional way, and less procedural. This will allow us to be more efficient when working with the code.
- remove java RMI, means a new server to client communication technology
- remove java reflection, involves code re-structure
- remove serialization, involves removing the above java technologies as well as finding a new way to save game files.
- better map version compatibility

Once we have the above accomplished, game saves will be playable with any future versions, and game engine + lobby will be compatible with any version combination. Even games between players will be more flexible and will not always require the same game engine version.

With that done we will then be able to release more frequently, and with the better code structure we will be able to build new features more quickly as well (with less time spent figuring out why we broke something).
## Community
- In game challenge system.  -> #1072
- In game Ladder/ELO -> #1043 
- Game internationalization (translations)
## AI
- Improve Performance on Large Maps 
- Consider Purchasing 0 Movement Units (Static Defenses) 
- Valuing Objectives 
- Consider strafing and defending against strafing 
- Consider V3 rule around subs not blocking naval movement 
- Consider V3 rule where fighters don't defend against subs 
- Rewrite bid purchase/place 
- Consider victory city points 
- Improve AA gun movement 
- Defending capital against multi-turn amphib attacks 
- Improve unit production consideration to always use TripleAUnit.getProductionPotentialOfTerritory() 
- Add per map XML AI configuration 
- Add purchase 'value' for resources besides PUs 
- Transport mobile factories 
- Consider air/naval bases strategic value and purchasing 
- Consider value of saving at least 1 land unit when selecting casualties 
- Consider capital farming when determining whether to take back an allied capital 
- Add support for 'upgrading units' (consuming an existing units) 
- Consider interceptions and escorts
- Air/land transport support
- Fuel movement support 
## Maps
- Update/fix map content data, update map descriptions and fix up game notes. First focusing on core high quality maps including WaW (in-progress), NWO, TRS, all A&A maps, 270 BC, Napoleonic, etc.
- Better map version management? IE: easier to play save games when the map versions may have changed (this is more to do with the game engine than maps)
## Gameplay
- Efficiency improvements, purchase planning, streamlined UX (such as a 'fight all battles button', 'yes-to-all' buttons), battle calculator copy/paste and other utility features.
- Better info displays, NO's included in the stats, titles next to unit names
- Text zoom option, to increase the size of all text that is displayed

Interested to hear feedback on the list above, and if there is anything important that I left out of the list.

**Comment by simon33-2** [comment]
Hi @DanVanAtta ,
I started a similar thread on axisandallies.org recently: http://www.axisandallies.org/forums/index.php?topic=38399.0

Basically, the #1 priority for almost everyone playing G40 is fixing the Strategic Bombing bug (PR #1074). That's because there is no reasonable workaround.
#2 priority is the sub combat logic when a destroyer is present which is somewhat broken. Should roll all the attackers before the sub casualties are chosen when the defender has a destroyer and vice versa rather than the present situation of rolling the subs then choosing sub casualties then rolling other attackers. Similarly when air defenders are present against sub attackers without a destroyer. All the defenders should roll before the air defenders casualties are chosen.

Other priorities:
Reducing the numbers of times it asks you to select an option when only one option is available. e.g. when retreating from a battle.

My personal idea would be merging all of the politics/repair/purchase/combat movement phases but not many people agree with this one.

**Comment by BeornTheBold** [comment]
Something that would be very useful and time saving for players is the ability to pre-plan purchases when it is not their turn.  If they were able to fill out the purchase worksheet in advance, then only last minute changes would be necessary when their turn came up.  In the same vein, making political and user actions available for pre-planning any time would also be good.  Then they would only need final approval when the player's turn came about.

**Comment by FrostionAAA** [comment]
Preplaned purchases sounds like a cool idea, just like people do when playing real board games ... without revealing the purchase to the other players of course. And of course it should not be binding and still have an option to change. Maybe, if this was realized, the step where you see and acknowledge your purchase in the left part of the screen should stay. There you have the option to change purchase.
The only thing that worries me is that people don't know if they need to spend PUs on repair before maybe just before their turn. Maybe political situations.  Also, some maps have players with the option to give PUs and other stuff to other players before spending the rest on their own purchase. There might be some conflicting or complicated situations.

**Comment by simon33-2** [comment]
I think that would be very cool too, particularly with the panel showing the purchases. Then you can move Combat Movement to before Purchase Units with few side effects.

**Comment by BeornTheBold** [comment]
FrostionAAA, since the purchase would not be finalized until the normal moment of their turn, any last minute things like repairs, additional income, etc. could still be handled before finalization.  I'm just thinking like a worksheet which could then adjusted at the last minute if necessary.

**Comment by DanVanAtta** [comment]
captured the initiatives list on wiki: https://github.com/triplea-game/triplea/wiki/Development-Initiatives
