### ISSUE TITLE
Another instance of AiGameTest going to 100 turns with no winner

### ISSUE THREAD

**Issue by asvitkine** [triplea-game/triplea#10785]
Another instance of AiGameTest going to 100 turns with no winner.

Here's a save game:
[autosave_round_odd_new100.tsvg.zip](https://github.com/triplea-game/triplea/files/8987525/autosave_round_odd_new100.tsvg.zip)

Notably, it seems that the game state at the 100 turn mark is such that Germany can be defeated if the opponent just decides to load up all its units and invade, sending two fighters to the naval combat that needs to be cleared before landing. However, this does not happen, even if you run the game for 40+ more turns.

Need to figure out why AI is not choosing this option. 
<img width="489" alt="Screen Shot 2022-06-26 at 5 15 04 PM" src="https://user-images.githubusercontent.com/17648/175834084-948e20a0-6250-41bd-b358-83e7547f34e8.png">

**Comment by asvitkine** [comment]
The position really didn't change in the last 50 turns, though the odds for the ground combat increased over time. On turn 55, for example, it was already a 87% win rate for the invasion. Navy didn't change since.

**Comment by asvitkine** [comment]
Additionally, the AI doesn't care to capture the German sea zones, which could have let it get a bigger income advantage.

**Comment by asvitkine** [comment]
So ignoring how the AI got in this situation in the first place and even the sea zones, the question is why does it cause a stalemate? If AI thinks the sea combat is too risky, it should buy more ships or planes. Otherwise, it should see it could just attack through and win.

**Comment by asvitkine** [comment]
So if I make Germany's capital completely, empty, the AI still doesn't attack it.
<img width="491" alt="Screen Shot 2022-06-26 at 9 34 33 PM" src="https://user-images.githubusercontent.com/17648/175844368-2e240d97-e396-4c33-9a73-819b80c42002.png">

If I add 10 battleships to accompany the fleet of 92 transports, then they do attack the German fleet that turn, but don't move transports to land units at the same time.

Could it be that AI doesn't know how to do amphib attacks if there's a dependent sea battle to fight first? @ron-murhammer, do you know?

**Comment by ron-murhammer** [comment]
@asvitkine I don't think the AI does amphib after a sea battle (not 100% sure but at least I know it didn't for a long time). If I remember, the main reason is its complex to make sure you have good enough odds on the sea battle and don't take transports as casualties so the landing is then successful.

**Comment by asvitkine** [comment]
@ron-murhammer 

Thanks. I think making AI know how to do amphib landings past a sea battle would be a nice improvement, but I guess in this case, we could probably also settle for just a ships' arm race, which would allow the AI with the greater production to push through (over several turns).

**Comment by ron-murhammer** [comment]
Yeah it would be a good enhancement but probably not easy to implement. Generally the AI will just win the seas first then land the following turn so not ideal but in most games doesn't make or break the game.

**Comment by asvitkine** [comment]
So the code in question responsible for deciding if we need to build up our fleet in this case is `territoryHasLocalNavalSuperiority()`.

It ends up logging:
```
    SZ 1, current enemy naval attack strengthDifference=14.735557902580702, enemySize=2, alliedSize=96
    SZ 1, current allied naval attack strengthDifference=74.19501727482375, alliedSize=96, enemySize=2
```

The values are within the threshold: 
```
    // If I have naval attack/defense superiority then break
    return (defenseStrengthDifference < 50 && attackStrengthDifference > 50);
```

If I change the condition to: `attackStrengthDifference > 80`, the AI builds up the fleet over a couple turns and is able to close out the game.

The problem is an attack strength difference of 74% is enough to hesitate building a fleet, but also enough to hesitate doing an attack. The two thresholds are not in line.

**Comment by asvitkine** [comment]
So, the negative attack value is coming from a tuv swing result from `patd.getMaxBattleResult().getTuvSwing()` whereas the `attackStrengthDifference` check is using `estimateStrengthDifference()`, which doesn't simulate combat.

I guess we could make it do a combat sim, or perhaps keep track of whether there were territories that were removed due to TUV swing and take that into account for naval superiority checks.

**Comment by asvitkine** [comment]
OK, adding some logic like that and loading that save from t50 makes allows the allies to build up a fleet and win on turn 59.

Amusingly, using the same logic from turn 100 results in also allies winning... but on turn 236 only, due to some pretty spectacular blunders (unrelated to my logic) where they end up losing hundreds of transports and need to wait a long time to build them up again...

**Comment by asvitkine** [comment]
This is the hilariously bad move resulting in the loss of ~100 transports (round 103);
<img width="491" alt="Screen Shot 2022-06-27 at 12 07 52 AM" src="https://user-images.githubusercontent.com/17648/175858199-7ec355c3-f574-41d7-8aec-3ae0a9ddb17a.png">

The attack fails so Germany is left with a battleship with 1 HP. But we move our 94 transports to be with our destroyer, despite the fact that if we left them where they were, they'd be safe since the enemy has no air. So predictably, Germany then sinks the 94 transports that are guarded by a destroyer.
