### ISSUE TITLE
Can't Login to triplea

### ISSUE THREAD

**Issue by beelee1** [triplea-game/triplea#10804]
### Reproduction Steps

Can't post this anywhere else. Triplea won't let me login. Says my username and pw are both wrong. Tried to make a new one so I could post the problem at the site and got this 
![Screenshot from 2022-06-29 05-00-08](https://user-images.githubusercontent.com/24382682/176410165-dcb53f0f-9c00-48dc-8f68-caa904fb5f34.png)

Never had to do that before and I'm not doing it now. Hopefully someone can fix this.
1.
2.
Edit
Yea can't get into A&A.org either. Same bullshit. Must be some nodebb crap w/e I can get on git fine
3.

### Engine Version

Engine Version:

**Comment by RoiEXLab** [comment]
@beelee1 Did you try resetting your password? You should get an email which allows you to reset the password.

Regardless the screenshot you posted is just a privacy policy you have to agree with. At least in the EU they are legally obliged to ask for your permission before using your data.

**Comment by RoiEXLab** [comment]
Also I can login just fine on both forums, so it looks like its just you, not everyone.

**Comment by panther2** [comment]
@beelee1  According to the user's data you have been successfully logged in 7 hours ago. I am writing this at 17.33 UTC+2.

**Comment by beelee1** [comment]
Thanks for looking at it Roi and Panther. Idky it'd say I'm logged in when I cant. Wonder if the fact I probably don't have the email I signed up with years ago has anything to do with it. But it works for git so it still makes me think its a nodebb thing.

Anyway, I guess I'll have to make a new junk email n reregister.

**Comment by beelee1** [comment]
I can still login to the lobby so yea something fckd

**Comment by panther2** [comment]
@beelee1 

Do you still now for sure the email-addresses you registered with at the forums?

**Comment by RoiEXLab** [comment]
@beelee1 What exactly does the lobby have to do with the forums?

**Comment by beelee1** [comment]
@panther2 yea i don't have the email address I registered with.

@RoiEXLab I have the same username and pw for the lobby as i do for triplea forum. One works, the other doesn't. My git account works as well. The only thing that doesn't work are the two nodebb sites.

Anyway, it doesn't really matter

**Comment by beelee1** [comment]
@panther2 I made another beelee2 and it's still not working. I get a box on lower left saying 'click here to activate email" or something to that effect. Then when i do, I get an error message saying "Bad" something.

Same thing as the last beelee2.

![Screenshot from 2022-07-19 01-57-19](https://user-images.githubusercontent.com/24382682/179687684-b8f7c3e0-2995-4b92-a4b4-625a49107081.png)

![Screenshot from 2022-07-19 02-01-36](https://user-images.githubusercontent.com/24382682/179687726-c48963a9-2fb7-4aa0-916d-108105342671.png)

**Comment by beelee1** [comment]
Hmmm ... so go back to register then ? i'll give it a shot

**Comment by panther2** [comment]
No wait! WHat about the confirmation email that you received when you registered?

**Comment by beelee1** [comment]
yea i never got one. When I click on the box in the first picture above it takes me too the second one

**Comment by beelee1** [comment]
ty

**Comment by panther2** [comment]
Yes, I see. There is a server error related to sending out mails.

I will mention @RoiEXLab to please take a look into this:
![error](https://user-images.githubusercontent.com/20812775/179709756-556e4e06-d465-4d4c-9d7d-d83f1ae150f0.PNG)

**Comment by beelee1** [comment]
cool thanks again

**Comment by panther2** [comment]
@RoiEXLab 

We also found out that enforcing a mail-adress confirmation mail to the account "beelee" failed with the same error message as above (different user ID of course). A password-reset mail returned no error message ... but he is still waiting to receive that mail.

**Comment by beelee1** [comment]
@panther2 should i try and make a new user with a gmail ? You said some registrations are going through, not all though ? WDYT ?

**Comment by panther2** [comment]
@beelee1 
It is worth a trial. Contact me via PM on A&A .org, then.

**Comment by RoiEXLab** [comment]
@panther2 Sorry for the delayed response. I checked the logs and it looks like the forum is currently unable to send out emails because gmail is not accepting the credentials (even though I verified they work).

@prastle You created the account back in the day, can you log in to see if there's something that needs to be done to confirm your identity or something?

**Comment by beelee1** [comment]
I guess this isn't going to be resolved anytime soon. Thought it would have a higher priority. I know triplea only gets a handful of new users per year. i also know they aren't going to get any new users as long as it's broken.

**Comment by RoiEXLab** [comment]
@beelee1 I don't have access to the forum's Gmail account because of the strict google secure features.
I don't want to create a new account just because @prastle isn't responding instantly, but that would be the last resources and most likely a fix to this Problem

**Comment by beelee1** [comment]
@RoiEXLab thanks for the update and for looking into it

**Comment by beelee1** [comment]
When this is resolved, it'd be a good idea to have a backup. That way, if someone is no longer able to address any potential future problems, someone else can.

**Comment by beelee1** [comment]
I'm getting worn out with this process. I've been a triplea member for about 15 years. It'd be nice to get this resolved one way or another. There are other things i can do with my time

**Comment by RoiEXLab** [comment]
@beelee1 I'm working on it. Can't give an ETA yet unfortunately

**Comment by panther2** [comment]
I PM'd @prastle about this issue on the forum 8 days ago.

Just to let you know.

**Comment by beelee1** [comment]
@RoiEXLab Thank you

**Comment by RoiEXLab** [comment]
@beelee1 I think I was able to fix it, please try the password reset feature again. It should hopefully work this time.

**Comment by beelee1** [comment]
@RoiEXLab yea it seems to have worked. It said success when I clicked on the confirmation popup at the forum. Unfortunately this old machine having trouble accessing my email but that's a personal issue lol. 

Thanks for your help

**Comment by panther2** [comment]
@beelee1 Please use your beelee3 account to see my PM on the forum.
