### ISSUE TITLE
TripleA 2.6+886ea23 possible Production panel issue?

### ISSUE THREAD

**Issue by TheDog-GH** [triplea-game/triplea#10816]
@asvitkine 
I think this is caused by 2022-June-30 - 2.6+886ea23

**Settlers: Fallen Empire in 2.5** Look at the columns they are deliberately column grouped
1 4 7 etc
2 5 8
3 6 9
![image](https://user-images.githubusercontent.com/71022517/176876357-faad38c4-8699-44ff-884b-5696e61b5eb3.png)

.
**Settlers: Fallen Empire in 2.6** grouping is linear (like reading)
1 2 3 4 5 6 7 8 9 etc
![image](https://user-images.githubusercontent.com/71022517/176858178-8cdc8038-1120-4616-90f9-7eaa62a716af.png)

I am not alone in this format of column grouping,  Frostion uses it as well.

.
**For the above I am just pointing out what the change in code does.**

.
As there is an alternative to the issue above called production_tabs.properties I am not too fussed on the change.
These maps use production_tabs.properties
* civil_war
* war_of_the_relics
* the_shogun
* the_shogun_advanced
* stellar_forces
* feudal_japan_warlords
* hellas
to name a few.

**BUT, Tab Labels dont work properly in production_tabs.XXXX.properties**
**The error occurs in 2.5 and so is in 2.6  and is slightly broke, the tab labels are not correct, see**
https://forums.triplea-game.org/topic/3034/help-with-production_tabs-properties

Link to a map to test.
https://drive.google.com/file/d/1CZAcMh3p9kB7cR4TvKPIwNxhdpMgGbGE/view?usp=sharing

As I dont think any other maps use sub/XXXX production_tabs.XXXX.properties of the main production_tabs.properties.

**Comment by DanVanAtta** [comment]
The way items in a production panel are displayed was updated recently to avoid horizontal scrolling. IIRC
@asvitkine could you advise on this issue?

**Comment by beelee1** [comment]
yea you can see a lot more units at once with the change. I like it

**Comment by asvitkine** [comment]
@TheDog-GH 

Re: The properties issue, when I try the linked map with everyone but Rebels set to Hard AI, I get the following error:
"IllegalStateException: production_tabs: must include all player production rules/units"

I'm going to improve the error message so it tells you which ones were missing, in this case it's:
  buyFarmer, buyYumi-Sohei, buySohei, buyWako-Jong,

I'm not sure if that's the cause of the error you were seeing. Can you double check? (I also wonder why you didn't get that error...)

**Comment by TheDog-GH** [comment]
I do get that error now, with TripleA-2.6+14402 and this
![image](https://github.com/triplea-game/triplea/assets/71022517/ce2eac56-37c8-4ed0-afd8-eac666734eb5)

So a lot easier to debug THANKS!

I would like to park this issue as its only me that's asking and I have a work around already.

As your time is precious I would like a fix for this
https://github.com/triplea-game/triplea/issues/11740

There are 3 of us working on this map for the past 9 months.

Also I would like to help you get 2.6 over the line and released.
