### ISSUE TITLE
Game Notes Don't Show up Correctly with Prerelease

### ISSUE THREAD

**Issue by beelee1** [triplea-game/triplea#10815]
On 2.6.982 the Game Notes are way behind the latest map version. The map version also doesn't show up when the game/map is selected, which is important information imo.
Stable
![Screenshot from 2022-06-30 22-23-27](https://user-images.githubusercontent.com/24382682/176818486-3a700237-8c81-4808-bded-411bed9c7a05.png)

Pre
![Screenshot from 2022-06-30 22-21-26](https://user-images.githubusercontent.com/24382682/176818563-88ed76c0-be98-4019-bc86-372f506e26ae.png)

This probably more of a regression than a bug but the in game notes themselves are a bug.
Stable
![Screenshot from 2022-06-30 22-25-40](https://user-images.githubusercontent.com/24382682/176818677-ddb2f383-8269-42fb-8f95-19a3a0c0f305.png)

Pre
![Screenshot from 2022-06-30 22-22-33](https://user-images.githubusercontent.com/24382682/176818703-a9a0b46e-08cc-42ac-947f-57798f49ffdd.png)

Notice the difference in the Change Log. There are also many Notes missing as well. Another thing is you can't copy the Notes in the Pre. Notice the Hilight in the stable. This may have something to do with the trouble downloading the map with the pre that #10512 fixed and that i mentioned here #9252.

Seems the pre isn't correctly downloading the latest map. The Notes were deliberately changed, so that's where most of their issues are but it should still have the most up to date Notes. The map itself seems to play with the latest map version correctly.

**Comment by beelee1** [comment]
So when I open the games folder where the xml and notes are. The notes are what show up in the pre. In the stable the correct notes show up but only in game as there is only the one map in the downloaded maps folder which works for both pre and stable.

**Comment by DanVanAtta** [comment]
In 2.6, the game notes should be taken entirely from the 'global_40_expansion.notes.html' file.
The notes in the XML file are completely ignored in 2.6 and are only there for the benefit of 2.5 and prior engines.  Does that make the behaviour seem more consistent?

**Comment by beelee1** [comment]
yea i guess that's the issue then. html file isn't updating correctly. I still think it probably has to do with the above when asvitkine made it so I could dl maps with the prerelease.

At any rate, I'll look into it some more.
