### ISSUE TITLE
How to turn off prerelese feature

### ISSUE THREAD

**Issue by beelee1** [triplea-game/triplea#10826]
I only want to turn this one off so far. Can it be disabled without turning off all the new ones ? 2.6 7/2/22

![Screenshot from 2022-07-03 02-19-58](https://user-images.githubusercontent.com/24382682/177029580-cf6e3944-5ed3-4b16-bc82-1312087dd50d.png)

**Comment by beelee1** [comment]
Hmm ... now when I start a game with 2.5 the above shows up. I deleted the pre so i only have 2.5 and still get the prompt. Was this hardcoded into all triplea versions ?

i don't like it and would like the option to turn it off.

Disappointed it was added to the stable. Thought the stable wasn't supposed to b fckd with

**Comment by asvitkine** [comment]
That feature is behind "enable beta features" setting. It was added some time ago but hasn't graduated out of that setting yet.

We can probably add a "Don't show again" checkbox and corresponding pref and move it out of beta features.

**Comment by asvitkine** [comment]
I landed https://github.com/triplea-game/triplea/pull/10828, so this will now have a preference to control it and a "Do not show again" checkbox on the dialog.

**Comment by beelee1** [comment]
ty
