### ISSUE TITLE
AiGameTest fails in GameTestUtils

### ISSUE THREAD

**Issue by frigoref** [triplea-game/triplea#10823]
AiGameTest fails in GameTestUtils

    // Use a temp dir for downloaded maps to not interfere with the real downloadedMaps folder.
    if (tempHome == null) {
      tempHome = FileUtils.newTempFolder();
      System.setProperty("user.home", tempHome.toString());
    }
    ClientSetting.initialize();
    assertTrue(ClientFileSystemHelper.getUserMapsFolder().startsWith(tempHome.toAbsolutePath()));
    ClientSetting.aiMovePauseDuration.setValue(0);
    ClientSetting.aiCombatStepPauseDuration.setValue(0);

The comment seems to contradict the call for assertTrue. I wonder if the assert is actually needed here as the temp folder will always be different as far as I can see.

@asvitkine Any explanation why this could make any sense?

**Comment by asvitkine** [comment]
@frigoref 

The test works on the bots and on both my computers (Mac and Windows). We can try to figure out why it fails for you. What's your set up?

> The comment seems to contradict the call for assertTrue. I wonder if the assert is actually needed here as the temp folder will always be different as far as I can see.

The temp folder is set as "user.home" which is used during `ClientSetting.initialize()` to set the `ClientFileSystemHelper.getUserMapsFolder()`, so it's expected that the user map folder is a subdir of `tempHome`. If you print both paths, what do you get?

**Comment by frigoref** [comment]
`ClientFileSystemHelper::getUserRootFolder` returns the mapFolder path:
![image](https://user-images.githubusercontent.com/10353640/177012914-f6c06577-e63a-4aa4-93da-103c669f4379.png)
Seems that because I have a valid maps folder this one is used instead of the temporary folder.

**Comment by asvitkine** [comment]
The relevant code is:

```java
  public static Path getUserRootFolder() {
    final Path userHome = Path.of(SystemProperties.getUserHome());
    final Path rootDir = userHome.resolve("Documents").resolve(USER_ROOT_FOLDER_NAME);
    return Files.exists(rootDir) ? rootDir : userHome.resolve(USER_ROOT_FOLDER_NAME);
  }
```

And
```java
  public static String getUserHome() {
    return checkNotNull(System.getProperty("user.home"));
  }
```

Can you check why the above isn't working as expected for you? `System.getProperty("user.home")` should be getting set to the temp folder created.

**Comment by asvitkine** [comment]
Possibly you have `ClientSetting.mapFolderOverride` set?

**Comment by asvitkine** [comment]
@frigoref 
Can you try with https://github.com/triplea-game/triplea/pull/10824 and let me know if that fixes the test for you?

**Comment by frigoref** [comment]
@asvitkine No, it does not. If you have a valid mapFolderOverride (which I have) it is taken and the temp folder is not.
Maybe it needs to be initialized with `ClientSetting.mapFolderOverride.resetValue();`?

**Comment by asvitkine** [comment]
@frigoref can you try again with the updated PR? I suspect it should work with that one, but please confirm. Thanks!

**Comment by frigoref** [comment]
@asvitkine Sadly not as I now get the following **IllegalStateException** error. Can you please have another look for it?
```
ClientSetting framework has not been initialized. Did you forget to call ClientSetting#initialize() in production code or ClientSetting#setPreferences() in test code?
java.lang.IllegalStateException: ClientSetting framework has not been initialized. Did you forget to call ClientSetting#initialize() in production code or ClientSetting#setPreferences() in test code?
	at games.strategy.triplea.settings.ClientSetting.lambda$getPreferences$0(ClientSetting.java:277)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at games.strategy.triplea.settings.ClientSetting.getPreferences(ClientSetting.java:275)
	at games.strategy.triplea.settings.ClientSetting.setEncodedValue(ClientSetting.java:304)
	at games.strategy.triplea.settings.ClientSetting.setValue(ClientSetting.java:295)
	at games.strategy.triplea.settings.ClientSetting.setValueAndFlush(ClientSetting.java:342)
	at games.strategy.triplea.settings.ClientSetting.resetValue(ClientSetting.java:387)
	at games.strategy.engine.data.GameTestUtils.setUp(GameTestUtils.java:48)
```

**Comment by asvitkine** [comment]
@frigoref 

I don't see a `resetValue()` call from `GameTestUtils.setUp()`. Do you have local changes?

**Comment by frigoref** [comment]
@asvitkine You are right, my mistake. Now it is fixed. You just set empty preferences with `ClientSetting.setPreferences(new MemoryPreferences());`, right?

**Comment by asvitkine** [comment]
> @asvitkine You are right, my mistake. Now it is fixed. You just set empty preferences with `ClientSetting.setPreferences(new MemoryPreferences());`, right?

Yep, and they should have default values.
