### ISSUE TITLE
I'm ready to add my map (argomidweight)

### ISSUE THREAD

**Issue by JGreenLowe** [triplea-game/triplea#10859]
I have a playable map with 2 games that are ready to be shared with the TripleA community. Please send me an invitation to join my own map team at triplea-maps. Thank you!

**Comment by JGreenLowe** [comment]
https://github.com/JGreenLowe/argomidweight/tree/main

**Comment by beelee1** [comment]
I think the process has changed. Idk the specifics but @asvitkine did one fairly recently

**Comment by DanVanAtta** [comment]
@beelee1 2.6 will change the map ingestion process bit more compared to now.. FWIW, the map team is no longer necessary.

@JGreenLowe , would you mind renaming the branch 'main' to be 'master'
Once that is done we'll review the map, fork it into "triplea-maps/", and would add you as the owner of the forked repo

**Comment by JGreenLowe** [comment]
OK, I have renamed the branch to 'master'.
