### ISSUE TITLE
Global 40 House Rules - "Option Redesign" option no longer working

### ISSUE THREAD

**Issue by beelee1** [triplea-game/triplea#10862]
The above prerelease is not activating game/map options the way it does in 2.5 stable. Select "Option Redesign" from options and note that after "Changer" combat move, the map redraws with the new options. In the above 2.6 Pre, the map goes blank for a second, but nothing is changed.

Option Redesign activates many game options. The only option I've checked as not working is "Factory Limited" which replaces "Harbour" and "Airfield" with "Harbour 12" and "Airfield 12" as well as reducing the cost of a Minor factory from 15 to 12 PUs.

Here is stable that works correctly 
[2.6 7-02-22 Pre Regression 2.5 Stable.zip](https://github.com/triplea-game/triplea/files/9080172/2.6.7-02-22.Pre.Regression.2.5.Stable.zip)

Here is Pre that doesn't work
[2.6 7-02-22 Pre Regression 2.6 Pre.zip](https://github.com/triplea-game/triplea/files/9080167/2.6.7-02-22.Pre.Regression.2.6.Pre.zip)

Edit
The map is "Global 40 House Rules".

**Comment by DanVanAtta** [comment]
@beelee1 when you launch the '2.6 Pre.zip' file with a 2.5 engine, does it work correctly? How about vice versa, if you launch the '2.5 stable' save game with 2.6, does that not work correctly?

2.5 and 2.6 are save game compatible, so I'm wondering how/why the save is different and significant.

**Comment by beelee1** [comment]
@DanVanAtta yea so 2.6 save won't launch with 2.5. That's as expected and 2.5 save does launch with 2.6, which is also expected.

The problem is, in 2.5 "Option Redesign" when selected will activate several options. In 2.6 it doesn't activate any of them.

The Player that activates the Redesign option is "Changer" who only has one turn at the start of the game and then goes away. I vaguely remember a problem a while back with that, but am not certain. i'll do some more testing. 

This may be related https://forums.triplea-game.org/topic/3255/question-about-global-1940-house-rules-in-2_6 but I can't comment with my new triplea account to ask him.

**Comment by beelee1** [comment]
@DanVanAtta 2.6.885 works and 2.6.886 is where it breaks

**Comment by asvitkine** [comment]
https://github.com/triplea-game/triplea/releases/tag/2.6.886

**Comment by asvitkine** [comment]
Hmm, I'm confused. It doesn't repro for me, unless the steps I'm following are missing something.

Here's what I'm doing.
1. Map: "Global 40 House Rules"
2. Click "Game Options" and select "Factory Limited"
3. Finish Combat Move for Charger and Observe whether infrastructure units have been replaced with variants that say "12" at the end. I looked at the ones in UK.

This seems to be working for me - on 2.6+3479832 (just a prerelease I have installed, it's later than the mentioned change above).

Here's a save game from that: 
[testing_it2.zip](https://github.com/triplea-game/triplea/files/9107915/testing_it2.zip)

**Comment by asvitkine** [comment]
@beelee1 could you clarify what am I doing wrong in my steps or what am I missing?

**Comment by beelee1** [comment]
@asvitkine thanks for looking into this. You need to select "Option Redesign" which activates "Factory Limited" as well as more than another dozen or so options. Yea It works individually when selected as you did above.

The only option I'm seeing activated with option redesign in 2.6 is "Elite and Air Transport". Not sure why it's different. Checked xml. I'll check again.

**Comment by asvitkine** [comment]
Can you please provide a screenshot of the exact options selected?

**Comment by beelee1** [comment]
![Screenshot from 2022-07-15 00-15-20](https://user-images.githubusercontent.com/24382682/179155456-b8d44da0-0e39-4e39-a482-99918b885990.png)

**Comment by asvitkine** [comment]
@beelee1 

Your screenshot doesn't have "Factory Limited" checked, so I think it's working as expected that the infrastructure structures stay the same...
If I check it, I'm seeing the factories correctly get replaced.

Am I missing something?

**Comment by asvitkine** [comment]
Ohh, you're saying "Option Redesign" is supposed to work like "Factory Limited", even if "Factory Limited" is not checked?

**Comment by beelee1** [comment]
heh heh no worries :) Yea Redesign activates a whole buncha options. The ones I've activated individually seem to work tho. The only one that does work with redesign is "Elite and Air Transport". I think that was given to each Player individually as opposed to everybody at once if i remember right
