### ISSUE TITLE
Newer version of Triplea message

### ISSUE THREAD

**Issue by VictoryFirst2** [triplea-game/triplea#10873]
I am getting this message:

This save was made by a newer version of TripleA. To load this save, download the latest version of TripleA: https://triplea-game.org/download/  If this problem happens frequently and is something you cannot fix, please report it to TripleA 

While I have downloaded and installed the newest version of Triplea. How do I fix it?

**Comment by DanVanAtta** [comment]
Which version of TripleA do you have exactly?
Could you post the save game file to this issue (you will need to zip it first)?
Where did you get the save game from?

**Comment by VictoryFirst2** [comment]
I currently have 2.5.22294, the newest one.

I got it from TheGoodCaptain. He and I are currently playing a forum game of WW1 1914 (the axis and allies version). We are now in round 12 or something and I suddenly got that issue. This is the first time I have had that. He resent the file (I am not sure what he did with it) and I was able to load it. But when he sent me another save file a day later I wasn't able to load that as well, same issue. I asked him what he did to that file in order for it work

This is the current file that I am not able to load:
[g13.zip](https://github.com/triplea-game/triplea/files/9125421/g13.zip)

**Comment by beelee1** [comment]
@VictoryFirst2 if you dl the prerelease it'll work or it did for me anyway. Old saves we'll work on the prerelease but if he was on the pre and then saved again, it won't work with 2.5 stable

**Comment by beelee1** [comment]
@VictoryFirst2 did you get this to work ? If so, you can close it. Pretty sure the prerelease will fix it.

**Comment by VictoryFirst2** [comment]
TheGoodCaptain played against someone who had an older version of TripleA. Not sure what he did but all the files now work as usual. I guess he accidentally created the files on that old version, which he now doesn't.

**Comment by beelee1** [comment]
right arm we'll close this then
