### ISSUE TITLE
Strange installation path given with windows installer

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#1091]
C:\Program Files\${compiler:sys.shortName

appears to be not intended

(Win7.64)

Also the version No. appears twice in the Programs list of the control panel. it looks like this:

TripleA_1.9.0.0.2817 1.9.0.0.2817

**Comment by DanVanAtta** [comment]
The bad path should be fixed when the next release finishes building.

Still need to fix the double version in control panel.

**Comment by panther2** [comment]
Path is fine in 2823, thanks.
