### ISSUE TITLE
Uninstall fails in version 2817

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#1092]
Win7.64: Uninstall from control panel fails.
It is executed but does not uninstall.

Using uninstall.exe afterwards from the directory gives "Couldn't load main class."

**Comment by panther2** [comment]
Works fine in 2823, so issue is closed.

**Comment by DanVanAtta** [comment]
Hurray!! This was certainly more fixed by trial and error than an analytical fix, really glad to hear
