### ISSUE TITLE
Unable to log into TripleA lobby

### ISSUE THREAD

**Issue by Tomow123** [triplea-game/triplea#10984]
Hello, I am unable to log into the TripleA lobby. It has stopped working suddenly. It used to log me in no problems, but won't now. There is an error 500 message that comes up when I try to log in. The error message says the following: 
Error : Status 500 reading LobbyLoginFeignClient#login(MapLoginRequest)
Reason : Internal Server Error
{code "500," message":"There was an error processing your request. It has been logged (ID 1c9I762d969c4555)."}

I am hoping you are able to assist me with this problem. Thanking you in anticipation of your reply.
Regards,
Tomow

**Comment by beelee1** [comment]
@panther2 do you know who's in charge of the lobby these days ?

**Comment by DanVanAtta** [comment]
@beelee1  me and @RoiEXLab are best bets.

**Comment by DanVanAtta** [comment]
Resolved this earlier - deployment seemingly got far enough along that we updated database. We do not yet deploy lobby and it was not updated in order to pick up an updated database password. I updated the 2.5 lobby password and restarted it, bringing it back up.

**Comment by Tomow123** [comment]
It works again. Thank you to everyone for your help

**Comment by Tomow123** [comment]
Thank you. It works now and I am once again able to log into the TripleA lobby. Thank you very much for your help. It's appreciated.
Regards,
Tomow

------- Original Message -------
