### ISSUE TITLE
"This save was made by a newer version of Triple A"

### ISSUE THREAD

**Issue by ezeeric1** [triplea-game/triplea#10993]
I keep receiving this notification when trying to open a save file. But I have updated the game multiple times and even deleted and re-downloaded the whole game. 

Please let me know if there are any fixes. Thank you!

**Comment by TheDog-GH** [comment]
What version did you save the game with?
Please be specific, dont say 2.5 or 2.6, need the actual version number.

**Comment by panther2** [comment]
> I keep receiving this notification when trying to open a save file. But I have updated the game multiple times and even deleted and re-downloaded the whole game.
> 
> Please let me know if there are any fixes. Thank you!

It looks like the TripleA version that opens the savegame is older than the one the savegame was created with.

**Comment by DanVanAtta** [comment]
@ezeeric1 if you download the latest, this should not be a problem. To find the latest, check: https://github.com/triplea-game/triplea/releases
