### ISSUE TITLE
Class file cleanup

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#11]
Low priority, but I want consensus on this so we can do this while we move along on to bigger items. Below are some items that are somewhat whacky things going on in class files. I propose we fix the items below in an ad-hoc manner (and if someone really wants to, they can do a sweep and get everything!):

1. License on top of most files
-- It's not up there everywhere on every file. Let's post a copy with the source code and in this wiki.

2. @author comment in javadoc
-- We have git that tells us who authored what and when, it's not necessary to have this. Plus, I always wonder, okay, I've now modified 10% of this file, do I update the @author, how about at 70% when the file is starting to look completely new? Why are we bothering with those questions?? Let's worry about code!
-- Admittedly, this is a bit controversial, it's nice to have that @author at the top of the file. At the end of the day though there is very little value in having it there.

3. delete commented out code
-- religious removal, just delete it. Any objections?

4. methods that can be marked as static, mark them as static
-- indicating there are no instance dependencies is a good thing, let's do it.

5. empty javadac annotations
-- if there is nothign more than the name of a parameter, I'd rather not have it. It's one less thing to worry about when updating the parameter. Plus, am I the only one that when there are more than 3 javadoc @params, I immediately check their names and counts against the actual method. Unless we add value, let's not add maintenance burden.

**Comment by veqryn** [comment]
1. I actually hate having any non-code related junk in code files.  It messes up text-based searches.  I would prefer to remove all license information from every .java file, and just have a single license text file in the root directory.

2. I don't really care.

3. This should be done only on a case by case basis.  Good in principal, but 1% of the time it might be worth keeping something around.

4. Sure.

5. If there aren't any actual notes, then sure, scrap it.

**Comment by DanVanAtta** [comment]
Okay, we largely agree. On point 3 there is some disagreement, I would be more aggressive about it. Commented code doesn't give value, it even detracts since it comes up in searches and also causes developers to pause:
- is this worth keeping?
- why was this commented out?
- what did it do?
- does that current code do that? in which case was this a buggy attempt, a prototype?

So my perspective is that basically you never find miracle code in the commented out stuff. Rolling back version history to a working state is worthwhile and find stuff, but commented out code isn't worth it's weight. 

I'm going to close this since I think we largely agree.
