### ISSUE TITLE
At some point, diaglog graphics become garbled (version 2.5.22294)

### ISSUE THREAD

**Issue by pikido-edutainment** [triplea-game/triplea#11007]
<img width="1152" alt="Untitled" src="https://user-images.githubusercontent.com/111895572/186929447-2c2343ab-23aa-4d87-be41-7a5d23740f5c.png">

It happens while playing Big World: 1942 v3 Rules. Most of the time, after a few turns.
I've got a windows 11 machine.

I haven't played other maps yet.

**Comment by beelee1** [comment]
@pikido-edutainment what triplea version were you using ?

**Comment by pikido-edutainment** [comment]
Version 2.5.22294
The chances seem to increase after klicking to the information tabs (on
resouce production etc) on the right.

Op vr 26 aug. 2022 om 18:04 schreef beelee1 ***@***.***>:

**Comment by beelee1** [comment]
@pikido-edutainment  ah yea sorry I missed that in the title lol. Have you tried any other games yet ? You could also try the 2.6 prerelease and see if it happens there as well
