### ISSUE TITLE
triplea-maps:   Having a problem with this Pull request in triplea-maps

### ISSUE THREAD

**Issue by TheDog-GH** [triplea-game/triplea#11021]
Having a problem with this Pull request in triplea-maps
https://github.com/triplea-maps/arena_of_death/pull/3

I dont appear to able to Squash & merge :-/

Please advise where I have gone wrong?

Forgot to say that this fork is up to date, if needed
https://github.com/TheDog-GH/arena_of_death

**Comment by beelee1** [comment]
do you have write access ?

**Comment by TheDog-GH** [comment]
I thought I had write, as I was able to do a pull, but now I have
![image](https://user-images.githubusercontent.com/71022517/187849453-a63950a0-bd5b-43cc-9193-6aafdb9f5c20.png)

So Im not sure.  I think each commit now needs an approval from another map admin?

I think I have done it wrong, in that I should of done the changes direct to
https://github.com/triplea-maps/arena_of_death

Please could someone confirm?

**Comment by TheDog-GH** [comment]
So on my local GitHub Desktop I changed the remote repository by **Repository> Repository settings...**  from
https://github.com/TheDog-GH/arena_of_death.git
to
https://github.com/triplea-maps/arena_of_death.git
and got this

![image](https://user-images.githubusercontent.com/71022517/187853654-627067fb-91a1-4a45-8d9a-ee800bc80e08.png)

How can I grant myself write access to my map or can another map admin do so please?

**Comment by DanVanAtta** [comment]
@TheDog-GH I thought you were a map admin? (ie: 'triplea-maps' "map-admin" team).
That should give you write access.

FWIW, I added you to have write access to: https://github.com/triplea-maps/arena_of_death.git

**Comment by TheDog-GH** [comment]
@DanVanAtta  I am a map admin and uploaded my files of the_shogun direct to https://github.com/triplea-maps/the_shogun

Back to arena of death, for my 4 changes/commits see image below, its worked, THANKS.

![image](https://user-images.githubusercontent.com/71022517/188260565-4e9b9de2-0634-4a4f-a48c-8674b7a5fbe6.png)
