### ISSUE TITLE
Suggestion to add a label of Hacktoberfest to make more contributors engage

### ISSUE THREAD

**Issue by Diptonil** [triplea-game/triplea#11104]
## Upon adding the label of `hacktoberfest`:
- Project and maintainers can gain more popularity and exposure.
- More issues or bugs would be discovered easily.
- Newer ideas and rapid development of preexisting features.

**Comment by DanVanAtta** [comment]
Any suggestions for what to label with 'hacktoberfest', or how to further use it?
