### ISSUE TITLE
2.6 Lobby Chat Not Working

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#11145]
## Repro

- Using a 2.6, connect to lobby
- Type anything in message dialog and click send

Observe: nothing happens
Expected: typed message should appear

**Comment by beelee1** [comment]
yea same for me. i see you have a few bots up. I'll try and give one a spin soon

**Comment by beelee1** [comment]
@DanVanAtta I just tried it again and it's working

![Screenshot from 2022-10-21 19-13-27](https://user-images.githubusercontent.com/24382682/197307256-86e47497-e158-401b-8938-53c23e9f503b.png)

**Comment by DanVanAtta** [comment]
Same, seemingly a transient problem. Will close for now, this probably would come up again.
