### ISSUE TITLE
Request on Rules and Guidelines

### ISSUE THREAD

**Issue by JAGDF** [triplea-game/triplea#11170]
Hi, 

I am here to request a post to the triplea-games repository about the Rules and Guidelines. This link contains the community standards of a repository, all of which I want to propose: <a href="https://github.com/triplea-game/triplea/community">Community Standards</a>
As such, I wish to propose rules and security policies in case of any sort of detrimental activity occurs, should it happen. Please respond whenever you can. 

Thanks,
<a href="https://github.com/JAGDF">JAGDF</a>

**Comment by DanVanAtta** [comment]
Could use a bit more info on what is being requested please. What kind of Rules & Guidelines? As in contribution, conduct for issues, conduct for players? Who is the target audience?

> I wish to rules and security policies in case of any sort of detrimental activity occurs

Are you merely suggesting we create such a document, or are you suggesting to contribute to it? What kind of rules & security policies do you have in mind?

**Comment by JAGDF** [comment]
I was planning on contributing to it. However, I still need time to come up with rules that follow not only this repository, but also the game as well. It is still a work in progress.

**Comment by DanVanAtta** [comment]
FWIW, check: https://triplea-game.org/user-guide/

I think the website could use some help for organization and content.. The idea is that static documentation of interest to users (game-players) & map-makers would live on the website. There is a smattering of docs that are in the forums that I hope to have migrated to the website. The 'docs' in the repo are generally going to be developer orientated.
