### ISSUE TITLE
Resolve Latest Map Errors

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1121]
Didn't get 100% on all maps being updated.

For example: https://github.com/triplea-maps/middle_earth/issues/1

Task here, resolve all such errors.

**Comment by panther2** [comment]
Not sure whether this is the same issue, but 
https://github.com/triplea-maps/big_world/issues/3
is affected, too.

**Comment by panther2** [comment]
Thanks for fixing big_world.

**Comment by Cernelius** [comment]
You have:
color.Impassible
in map.properties of:
napoleonic_empire-political_map_skin
world_at_war-skin_sneak

**Comment by panther2** [comment]
Pull-request to fix napoleonic_empire-political_map_skin here:
https://github.com/triplea-maps/napoleonic_empire-political_map_skin/pull/1

**Comment by panther2** [comment]
Some issues with the Middle-Earth skin, still:
https://github.com/triplea-maps/middle_earth-map_skin2/issues/1
https://github.com/triplea-maps/middle_earth-map_skin2/issues/2

**Comment by DanVanAtta** [comment]
pacific_1942 error was resolved, but then the map is immediately not playable anyways. So the error is fixed at least (but map is likely to be delisted since not playable)

global war 2 is throwing an error as well, but it does not stop the game from loading 

```
SAXParseException: game: Global War 2, line: 2124, column: 18, error: The content of element type "attachment" is incomplete, it must match "(option)+".
```

We've at this point fixed all the errors that have prevented maps from loading :rainbow:
