### ISSUE TITLE
Global 500 Error when Accessing Triplea site

### ISSUE THREAD

**Issue by beelee1** [triplea-game/triplea#11228]
### Reproduction Steps

1.
2.
3.

### Engine Version

Engine Version:

### Is there anything else we should know?
Noticed it at 9 am Central US Time. Been about an hour or so now. I haven't seen the 500 error before. Says it's some sort of generic error.

Anyway, a heads up to @RoiEXLab and @DanVanAtta

**Comment by RoiEXLab** [comment]
@beelee1 Thanks for the quick information. I'll have a look at is as soon as possible (might take a couple of hours though)

**Comment by RoiEXLab** [comment]
@beelee1 Thank you for the quick notice, the issue is resolved now.

@DanVanAtta Because we were (once again) running out of disk space I upgraded the linode plan, which is 5$ more each month. I hope that's fine for you. So we should have no problems for a longer time now
