### ISSUE TITLE
whenCapturedChangesInto

### ISSUE THREAD

**Issue by BeornTheBold** [triplea-game/triplea#1122]
The unit attachment property **whenCapturedChangesInto** does not allow multiple uses in the same attachment.  For example, I wanted a large factory when captured to change into a small factory and also to produce 10 population units.  However, only the line listed last actually happens.

**Comment by DanVanAtta** [comment]
would you mind giving some XML samples @BeornTheBold ?

**Comment by BeornTheBold** [comment]
<attatchment name="unitAttatchment" attatchTo="factory2" javaClass="games.strategy.triplea.attatchments.UnitAttachment" type="unitType">
                         <option name="isFactory" value="true"/>
						 <option name="canOnlyBePlacedInTerritoryValuedAtX" value="2"/>
						 <option name="isAAforBombingThisUnitOnly" value="true"/>
						 <option name="canProduceXUnits" value="6"/>
						 <option name="maxDamage" value="6"/>
						 <option name="maxOperationalDamage" value="1"/>
						 <option name="consumesUnits" value="1:factory1"/> 
						 <option name="constructionType" value="factory"/>
                         <option name="constructionsPerTerrPerTypePerTurn" value="1"/>
                         <option name="maxConstructionsPerTypePerTerr" value="1"/>
						 <option name="whenCapturedChangesInto" value="any:any:true:factory1:1"/>
						 <option name="whenCapturedChangesInto" value="any:any:true:population:10"/>
</attatchment>

Using the above code when the factory is captured the factory2 disappears and 10 population appear, but the factory1 does not appear.

**Comment by FrostionAAA** [comment]
So if you list...
**_option name="whenCapturedChangesInto" value="any:any:true:factory1:1"
option name="whenCapturedChangesInto" value="any:any:true:population:10"_**
... then only 10 pop is generated. And if you list:
**_option name="whenCapturedChangesInto" value="any:any:true:population:10"
option name="whenCapturedChangesInto" value="any:any:true:factory1:1"_**
... then only the factory 1 is generated?

**Comment by BeornTheBold** [comment]
@FrostionAAA , yes that is correct.  I just tested it with the order reversed, and it behaved exactly as you describe.
