### ISSUE TITLE
Unit Purchase Display Improvements + Block Too Many Purchases

### ISSUE THREAD

**Issue by mcclelyd** [triplea-game/triplea#11258]
Delivering a feature that was requested on the forum here: https://forums.triplea-game.org/topic/3311/student-group-studying-triplea/2

**Comment by TheDog-GH** [comment]
@ArieLevental
https://github.com/triplea-game/triplea/discussions/11242

Just wondering how its progressing?

@beelee1

**Comment by panther2** [comment]
#9231
