### ISSUE TITLE
Engine Preferences Window needs Some Help

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1127]
The engine preferences window is a bit of a grab bag of controls and settings. Let's discuss here things wee think that could be better:

![engine_preferences](https://cloud.githubusercontent.com/assets/12397753/17885447/32d913f4-68d2-11e6-86d6-459295d7f121.png)

For sake of conversation/tracking, each element of this screen is numbered as follows
1) "Change Engine Properties"
2) Enable Sound Checkbox
3) Set Look And Feel
4) Enable/Disable Delayed Parsing of Game XML's
5) Set Default Casualty Selection Method
6) Setup Network and Proxy Settings
7) Set Max Host Wait Time For Clients and Opbsrevers
8) Set Max Memory Usage
9) Run the Map Creator
10) [Beta] Run teh Map creator
11) Show Console
12) Open User Maps and Savegames Folder
13) Open Installed Program Folder
14) Open README / User Manual

---

To start, I think we can drop 1, we don't need the text "Change Engine Properties", it is pretty obvious from the titel "Edit TripleA Engine Preferences", and the contents of the window.

5) Being discussed in https://github.com/triplea-game/triplea/issues/838
7) I suggest moving to Settings window
8) I suggest we move this to game_engine.properties, removing this button and the system.ini file that supports the memory. We may potentially need to do some research if the setting actually helps (with some timings and/or measurements from memory consumption, not just anecdotal). Or perhaps if someone can identify a good case where performance really degrades unless the max memory is adjusted. Ultimately considering removing this altogether to simplify

12) This feature/buttons are in the wrong place and grouped in a weird way. It's assumed that cleaning save games always has the task of cleaning maps as well. Splitting these two to two buttons would be an improvement. Folding this and 13 into the settings window I think would be a better way to go,

14) I think we can drop this. The Readme that is opened is rendered poorly, and we have on the previous screen "Help" and "Game Manual". The wording is confusing as well since "User Manual" is similar to "Game Manual", but instead the "user manual" is just an alias for the readme.html. Removing this button means we can also remove the readme.html file as well since there is no way to open it from in-game. If someone is searching the install folder for the readme file for documentation, then it is already too late, we have failed in providing timely documentation. Said another way, the download website or help button on the previous screen should take care of anything written in the readme.

**Comment by Cernelius** [comment]
As I've already said, I strongly believe that the current possibility of setting the Max Memory at whatever value you want to (like 4096 MB or whatever, by changing the system.ini) as well as setting the max wait time as much high as you wish should be kept.
Maps with very big xml may need a lot of memory, especially, but not only, for playing them with Hard AI.
Having an upper limit would be a pointless burden to any possible future mapmaking, mostly in term of xml dimensions and complexity.

**Comment by Cernelius** [comment]
Meaning that I believe the points:

7) Set Max Host Wait Time For Clients and Opbsrevers
8) Set Max Memory Usage

should keep the current possibilities, if somewhat changed, to not limit mapmaking possibilities (big and complex xml may require a lot of memory and a long starting time when hosted and there is not really a limit to what a mapmaker may want to do; also maps much heavier than, for example, war of the relics may be developed; I don't see why to make this potentially impossible, imposing a max memory limit or a max wait time limit, that I believe neither of such constrictions should exist).

If any of the above points get removed, then they should be both set to max equal to infinite.

**Comment by DanVanAtta** [comment]
Not suggesting a max, but instead let the OS manage the memory allocation and max, which the OS can dynamically increase unless you set an explicit max, like we are doing.

@Cernelius , can you recreate a game where changing this setting causes a notable difference? Please post such a save, so it can be analyzed. Creating a big pool of memory does not actually always make java apps run faster, GC times can increase with large memory pools and cause severe delays. 

Last point about this setting, if anything really did require the average user to update it so they could play a map, it is pretty damn broken. The map notes would have to describe/suggest to alter it, it's a hard to find option, and it's an option where the text tells you not to touch it. 

For 7) @Cernelius , please double check the suggestion more carefully in the description. It was recommended it be moved, not altered in any way.

**Comment by DanVanAtta** [comment]
@Cernelius war of the relics puts more strain on CPU than memory.  It is actually not memory bound, adding more memory should not really change the performance of war of the relics. For context, there are few hundred thousand if not millions of iterations that need to be done to read the XML file. Meanwhile, there are not a million XML objects, but even if there were, they are tiny and would take up a few MB in total.

**Comment by RoiEXLab** [comment]
I agree with @DanVanAtta 
IMO the memory setting is not really necessary

**Comment by Cernelius** [comment]
I did some experiments in the past, making some very big xml maps, and they would not open without much increasing the memory assigned, plus Hard AI would have been very slow and even unable to play without a max set very high.
I guess letting the OS manage the memory allocation and max is a good (and possibly the best) idea, that may cover all possible future mapmaking needs (I don't know).
And, yes, as now it would be much a power user thing, but only the one hosting the game needs to do it, so it is fairly doable (you need only the hoster being a power user).
Anyways, I can tell the current main burden against heavy xml is starting up a hosted game, that can take several minutes (which is a lot of time to wait), if the xml is very big (I guess this is related to savegame size).

**Comment by Cernelius** [comment]
A thing I might add is that the "Enable/Disable Delayed Parsing of Game XML's" makes not much sense as an option, as I don't see why you may want to parse all maps each time you wanna select a game.
Rather, I would suggest the behaviour always being "Parse Selected", plus having a "Parse All" button for parsing everything, when you want to do it.
Such a "Parse All" button could stay under the "Refresh Game List" button of the "Select a Game" window.

**Comment by Cernelius** [comment]
Anyway, even if the OS will be able to manage the memory allocation, I advise keeping the memory setting option, just in case.

For example, I just noticed that I cannot export the so called "screenshot" of World At War at default, and I had to increase the memory, to be able to get it (it is a 34.9 MB png, and maps of well over 100 MB png, when exported, are possible).

**Comment by DanVanAtta** [comment]
Could you elaborate kindly on "couldn't", did you get an error message, was it just very slow? If frozen, a stack dump would be useful.

**Comment by Cernelius** [comment]
I always got the same starting error message when something doesn't work because the memory setting is too low, no matter the case. It always just says (and said in this case too) "**OutOfMemoryError: Java heap space**".

But now I see it works anyway, despite going back to default, I don't know why. But previously it didn't work till I increased the ram. Never got a memory error taking a "screenshot" before, maybe because I usually just set the memory at 4096 and leave it be (thus I never hit it, because 4096 is practically infinite).

I lowered it at 600 now and I get this (which I think it is the same thing I got previously at default (796)):

java.lang.OutOfMemoryError: Java heap space
	at java.awt.image.DataBufferInt.<init>(Unknown Source)
	at java.awt.image.Raster.createPackedRaster(Unknown Source)
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
	at java.awt.image.BufferedImage.<init>(Unknown Source)
	at sun.java2d.loops.GraphicsPrimitive.convertFrom(Unknown Source)
	at sun.java2d.loops.GraphicsPrimitive.convertFrom(Unknown Source)
	at sun.java2d.loops.MaskBlit$General.MaskBlit(Unknown Source)
	at sun.java2d.loops.Blit$GeneralMaskBlit.Blit(Unknown Source)
	at sun.java2d.pipe.DrawImage.blitSurfaceData(Unknown Source)
	at sun.java2d.pipe.DrawImage.renderImageCopy(Unknown Source)
	at sun.java2d.pipe.DrawImage.copyImage(Unknown Source)
	at sun.java2d.pipe.DrawImage.copyImage(Unknown Source)
	at sun.java2d.pipe.ValidatePipe.copyImage(Unknown Source)
	at sun.java2d.SunGraphics2D.drawImage(Unknown Source)
	at sun.java2d.SunGraphics2D.drawImage(Unknown Source)
	at games.strategy.triplea.ui.screen.drawable.DecoratorDrawable.draw(DecoratorDrawable.java:25)
	at games.strategy.triplea.ui.screen.Tile.draw(Tile.java:124)
	at games.strategy.triplea.ui.screen.Tile.getImage(Tile.java:80)
	at games.strategy.triplea.ui.MapPanel.print(MapPanel.java:476)
	at games.strategy.triplea.ui.menubar.ExportMenu.saveScreenshot(ExportMenu.java:216)
	at games.strategy.triplea.ui.menubar.ExportMenu.lambda$saveScreenshot$609(ExportMenu.java:180)
	at games.strategy.triplea.ui.menubar.ExportMenu$$Lambda$194/1663121067.run(Unknown Source)
	at games.strategy.ui.SwingAction.invokeAndWait(SwingAction.java:61)
	at games.strategy.triplea.ui.menubar.ExportMenu.saveScreenshot(ExportMenu.java:185)
	at games.strategy.triplea.ui.menubar.ExportMenu.lambda$addSaveScreenshot$608(ExportMenu.java:140)
	at games.strategy.triplea.ui.menubar.ExportMenu$$Lambda$109/1481170329.accept(Unknown Source)
	at games.strategy.ui.SwingAction$1.actionPerformed(SwingAction.java:42)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)

Now it works at the default; I don't know why it previously didn't; I guessed it was reproducible, so I didn't copy paste, my bad. I guess the memory needed is very close to the default, so it sometimes works and sometimes not.

**Comment by Cernelius** [comment]
Also, I think the OS already well manages the memory, because, if you set it at a very high value, it doesn't go up to it, but it just avoids crashing if it reaches a lower max limit (you can set it at 4096, but it uses only 500 if it doesn't need more, or it can go over 2000, if you are playing a very heavy map with HardAI, but it usually stays between 1 GB and 2 GB, in "normal" maps).

In past Veqryn increased it to 1024, but several people found themselves unable to start TripleA; so Veqryn lowered to 796 and added this option, which I think was a very good addition, for not limiting the development of xml heavy maps.

So, I think everything can stay just as it is now (comprising the possibility of not having a real limit, by setting it very high), except that people in OS handling more than 796 may benefit from having the default set automatically higher than 796, if possible.

**Comment by DanVanAtta** [comment]
Closing, further memory follow up in: https://github.com/triplea-game/triplea/issues/836
