### ISSUE TITLE
Middle Earth Map's image not loading in 'Download Maps' dialog box in the process of installation

### ISSUE THREAD

**Issue by Memomer** [triplea-game/triplea#11276]
![image](https://user-images.githubusercontent.com/107757811/206153599-cea69bbc-6abc-4037-afb3-14b511faca74.png)

**Comment by DanVanAtta** [comment]
This is a problem in 2.5 @Memomer ? The way the preview images are generated is very different in 2.6

**Comment by Memomer** [comment]
I think I downloaded the latest version? Not sure if there was a image to start with @DanVanAtta  which is improbable

**Comment by Cernelius** [comment]
> I think I downloaded the latest version? Not sure if there was a image to start with @DanVanAtta which is improbable

Open your TripleA program and read and write here the "Engine Version" number. You should always do this when reporting a problem.

**Comment by Memomer** [comment]
> > I think I downloaded the latest version? Not sure if there was a image to start with @DanVanAtta which is improbable
> 
> Open your TripleA program and read and write here the "Engine Version" number. You should always do this when reporting a problem.

Thanks for correcting me, the engine is 2.5.22294.

**Comment by Cernelius** [comment]
> > > I think I downloaded the latest version? Not sure if there was a image to start with @DanVanAtta which is improbable
> > 
> > 
> > Open your TripleA program and read and write here the "Engine Version" number. You should always do this when reporting a problem.
> 
> Thanks for correcting me, the engine is 2.5.22294.

Since the new 2.6 release may be close, just letting you know that this issue is likely to go nowhere unless you can test and report the problem still exist with the latest pre-release.
https://github.com/triplea-game/triplea/releases/tag/2.6.14244

**Comment by Memomer** [comment]
> > > > I think I downloaded the latest version? Not sure if there was a image to start with @DanVanAtta which is improbable
> > > 
> > > 
> > > Open your TripleA program and read and write here the "Engine Version" number. You should always do this when reporting a problem.
> > 
> > 
> > Thanks for correcting me, the engine is 2.5.22294.
> 
> Since the new 2.6 release may be close, just letting you know that this issue is likely to go nowhere unless you can test and report the problem still exists in the latest pre-release. https://github.com/triplea-game/triplea/releases/tag/2.6.14244

Alright.
