### ISSUE TITLE
Can't Log In to 2.5 Lobby

### ISSUE THREAD

**Issue by beelee1** [triplea-game/triplea#11320]
### Reproduction Steps

1.
2.
3.

### Engine Version

Engine Version:
2.5 stable

### Is there anything else we should know?
Talked about here https://forums.triplea-game.org/topic/3369/i-am-unable-to-login

2.6 Lobby is working

**Comment by beelee1** [comment]
A headsup @DanVanAtta @RoiEXLab

**Comment by RoiEXLab** [comment]
Oh it looks like the certificate expired. As a workaround you can set back the time a year for now, but I don't know how to refresh the certificate because I'm not familiar with the build pipeline

**Comment by beelee1** [comment]
ok thanks @RoiEXLab Buncha people can't get into lobby. Can you give step by step instructions for reset ? 

 https://forums.triplea-game.org/topic/3369/i-am-unable-to-login

**Comment by RoiEXLab** [comment]
@beelee1 I'm currently working on it (perhaps I can get something working with my limited knowledge), but as I set, just set back your system time (the time on your computer) back and it should work. But in the best case I can get it working in the next hour or something

**Comment by RoiEXLab** [comment]
Okay, it should be working now, I just needed to restart the web server

**Comment by RoiEXLab** [comment]
@DanVanAtta 

I reloaded the nginx service and added a post-renewal hook like this:
```bash
sh -c 'printf "#!/bin/sh\nsystemctl reload nginx\n" > /etc/letsencrypt/renewal-hooks/post/nginx.sh'
chmod 755 /etc/letsencrypt/renewal-hooks/post/nginx.sh
```

This should work according to the "dry-run" is just performed.
Also I noticed the warning that nginx issued when running this command: `nginx: [warn] the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /etc/nginx/sites-enabled/lobby-2-5.conf:12`
#11322 has a pull request for this.

**Comment by beelee1** [comment]
@RoiEXLab :muscle: Thanks Brother !
