### ISSUE TITLE
Update My Forum User to not be an Admin

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#11386]
@DanVanAtta @RoiEXLab Can one of you update my forum user account to not be an admin as I can't login anymore as I got a new mobile phone so don't have my token now.

**Comment by RoiEXLab** [comment]
@ron-murhammer Removed your admin privileges. Tell me when you're ready to be added again

**Comment by ron-murhammer** [comment]
@RoiEXLab Hmm, its still asking me for 2 factor code. Is there a way to disable that?

**Comment by DanVanAtta** [comment]
Give it a try now

Looks like you were still in the MFA required group.

Followed these steps:
https://community.nodebb.org/topic/14109/user-2fa-broke-how-can-i-disable/2
@ https://forums.triplea-game.org/admin/plugins/2factor

**Comment by ron-murhammer** [comment]
@DanVanAtta Yep, all good now. Thanks.

**Comment by DanVanAtta** [comment]
Cool - I added you back to the admin group as well
I was a bit worried for a sec that there was no way to remove a lost MFA! One help article I ran across suggested updating the MongoDB directly..

**Comment by RoiEXLab** [comment]
@DanVanAtta If my memory is correct newer versions of NodeBB have the 2FA built in (within first party Plugin), so it might work better in newer versions

**Comment by DanVanAtta** [comment]
Our current forum version is getting dated. It has been tempting to do an update
