### ISSUE TITLE
can't play revised or download maps

### ISSUE THREAD

**Issue by RuinChristmas** [triplea-game/triplea#1142]
I posted the issue here http://www.tripleawarclub.org/modules/newbb/viewtopic.php?topic_id=2337

should i keep posting issues here or move there??

**Comment by DanVanAtta** [comment]
No here please. Github issues *is* a bug tracking system, warclub forums are not. For more on the organization of warclub, I started a conversation there: http://www.tripleawarclub.org/modules/newbb/viewtopic.php?post_id=16978

With respect to the can't download maps, the download file was messed up, but has been corrected earlier today.  Could you please confirm that things are working, and do any additional problems remain related to revised?

**Comment by RuinChristmas** [comment]
tried with version 2965, this time I still could not play revised but was able to download maps.  Since revised wasn't listed (bc installed), I uninstalled the exisiting, and redownloaded.  Now everything is okay except that when I load a game in 1.8.0.9 I get errors in my terminal window:

`triplea.engine.version.bin:1.8.0.9
SAXParseException: game: World War II Revised, line: 740, column: 19, error: Element type "attachmentList" must be declared.
SAXParseException: game: World War II Revised, line: 741, column: 134, error: Element type "attachment" must be declared.
SAXParseException: game: World War II Revised, line: 749, column: 135, error: Element type "attachment" must be declared.
SAXParseException: game: World War II Revised, line: 757, column: 135, error: Element type "attachment" must be declared.
SAXParseException: game: World War II Revised, line: 765, column: 134, error: Element type "attachment" must be declared.
SAXParseException: game: World War II Revised, line: 773, column: 136, error: Element type "attachment" must be declared.
SAXParseException: game: World War II Revised, line: 781, column: 137, error: Element type "attachment" must be declared.
SAXParseException: game: World War II Revised, line: 789, column: 138, error: Element type "attachment" must be declared.
SAXParseException: game: World War II Revised, line: 796, column: 135, error: Element type "attachment" must be declared.
SAXParseException: game: World War II Revised, line: 803, column: 136, error: Element type "attachment" must be declared.
SAXParseException: game: World War II Revised, line: 815, column: 135, error: Element type "attachment" must be declared.
`
x1000
I'm hoping to have both versions so I can still load old save games.

**Comment by panther2** [comment]
@RuinChristmas 

The maps downloaded for TripleA 1.9 are not compatible with 1.8.0.9.
Downloaded maps for TripleA 1.9 are in the folder... \downloadedMaps\
while the folder for 1.8.09 has been just ...  \Maps\

Just use the 1.8.0.9 built-in downloader to get your old map back in case you don't have it.
