### ISSUE TITLE
Download size

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#1146]
If we're worried about the size of the download, why include old .jar files?

**Comment by DanVanAtta** [comment]
Less concerned than we used to be. Recall the 1.8.0.9 release was 7 times the size it is now.

We removed some of the older old jars, we still have the others to load old games. The hope is that via serialization proxy pattern we'll be able to drop the need for old jars and the code that supports launching old versions. Then the hope is to move to a custom file format for saves which will be even more flexible for future compatibility.

Pruning down the assets folder is likely the next big gain to reduce DL size until we are able to remove the old jars.

At ~50MB, the download size is not quite so bad, and plus the download speed is about 10x faster as well (which means the game download is now about 70x faster than it was before :rainbow: )

**Comment by simon33-2** [comment]
Ah so the old jars are used to load old save games. Fair enough.

**Comment by simon33-2** [comment]
What would make sense to me is instead of duplicating parts of the assets folder in many maps, just utilise the assets folder. Doesn't reduce the size of the core download but reduces the size of the map downloads. Also, many of the files are still present in the tutorial. Is there really a need to have separate ones for each map? Apparently, some are slightly different as reported by diff but look the same in a viewer.

Perhaps then we can merge commonly used maps into the core download without it blowing out.
