### ISSUE TITLE
Download Maps window appears "behind" TripleA-window

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#1147]
I realized this beginning from 2965 (still present in 2968) on my Win7.64.

When hitting "Download Maps" the respective window opens but is overlayed by the TripleA-window.
![dld](https://cloud.githubusercontent.com/assets/20812775/18026646/459e8652-6c4e-11e6-9d48-ff9450c1cd48.jpg)

**Comment by Cernelius** [comment]
I confirm, and it is a bit annoying.

**Comment by DanVanAtta** [comment]
https://github.com/triplea-game/triplea/pull/1149 makes the DL window  always on top. We've tried a few ways to fix this.. so using the sledgehammer option this time.

**Comment by panther2** [comment]
Confirmed and issue closed, thanks!
