### ISSUE TITLE
Non Combat Move Unloading From Transports Unloaded During Combat Move Bug (1.9.0.0.2965)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#1148]
BugReportCernel13_World War II Revised_01_1.9.0.0.2965_20160827

In a v2 Rules game, the engine doesn't allow you to unload units from a transport, during Non Combat Move, if the transport unloaded anything during Combat Move, which is a bug.
The request at this issue is to **generally allow for unloading, during Non Combat Move, units from a transport that unloaded during Combat Move at the same turn, but restricted to unloading to the same territory the transport unloaded to during Combat Move** (of course, this would be possible only if the territory is friendly at the start of the Non Combat Move phase, which normally means it has been conquered during the previous Combat phase). My suggestion is always working this way, for the TripleA engine (then, if people are playing LHTR, or anything with more exensive restrictions than v2, they can limit themselves following the rules).
I believe this is a particularly problematic bug, because the rule is clear enough, yet it is not very easily understandable, thus you may have a hard time convincing your opponent to let you edit your aaGun in the territory you just took etc..
In this savegame, you should be able to unload 1 infantry from 18 Sea Zone to Brazil and 1 aaGun from 19 Sea Zone to West Indies, but the engine doesn't allow you to:
[BugReportCernel13_World War II Revised_01_1.9.0.0.2965_20160827.tsvg.zip](https://github.com/triplea-game/triplea/files/440614/BugReportCernel13_World.War.II.Revised_01_1.9.0.0.2965_20160827.tsvg.zip)

Side note (not actually part of this issue: I'm not suggesting to implement any LHTR rules at this issue), this applies only to basic v2 Rules. Under LHTR rules, instead, you must also follow the exception that an aaGun on a transport impedes any units in it to unload during Combat Move (I tend to suggest not supporting this, as it doesn't make any actual sense, and the players can just autolimit themselves following this nonsensical LHTR special rule, if they wish to). Thus I suggest the engine behaviour being the same both for basic v2 and v2 LHTR; it will be up to the LHTR players to know the rules and autolimit themselves.

Reference:
http://tripleadev.1671093.n2.nabble.com/Seig-trio-default-rules-discussion-tp7590530p7593384.html

**Comment by panther2** [comment]
Don't know if this is relevant here:

In all versions of Axis and Allies, at least starting from Anniversary Edition  (that means v3-v6 - I am no expert for earlier versions) ), your may either offload in combat move (amph. assault) or in noncombat move. Never in both phases.

**Comment by Cernelius** [comment]
Correct, since WW2v2 LHTR onwards, transports cannot unload in both combat and non combat move.
This, instead, was possible beforehand.

Since this is of very little influence, my suggestion was, as I said:

> My suggestion is always working this way, for the TripleA engine (then, if people are playing LHTR, or anything with more exensive restrictions than v2, they can limit themselves following the rules).

Anyways, first thing first, this should be corrected, as per what I said, as the default behaviour.

Then, if you really want to, you can make a property for having that restriction, and setting this property true in WWIIv2 LHTR, WWIIv3, WWIIv4, WWIIv5, WWIIv6, the Global series, and all games ending in "v2 LHTR Rules", "v3 Rules" and "v5 Rules".

As I said, since the matter is so marginal, and there are more similar unsupported silly restrictions, I just suggest not having this restriction, and letting the players limit themselves not doing it when playing LHTR and following, but, if you want, a property for supporting it is good too.

But for sure this restriction should not be default, unless the default is supposed to be v3 Rules, which is not. So, having this restriction as default, as it is currently, is surely a bug.

**Comment by Cernelius** [comment]
> So from this point of view making v2 "standard" and leaving the rest to the players would clearly be a step backwards.

Not a step backwards for sure, because the standard behaviour of the engine **never** went forward to the new rulesets as default, and, if it did, it is a bug (I think this is actually the only 1 case in which we have a v3 behaviour as the fault).

My point is that this is a marginal LHTR and following addition, that I don't think it makes any sense, so not a big need to support, but, yes, the best would be that default you can, and then you have a property for not being able to do it, and v2 LHTR and following have that property true, so everyone is happy.

I never noticed it before because I never play v1 or v2, nor I ever play any WWIIv2 based maps, like NWO etc..

**Comment by Cernelius** [comment]
It is up to the developers if they want to support the LHTR and following behaviour, but this is surely a bug, as you are not allowed to unload units from a transport, during Non Combat Move, if the transport unloaded anything during Combat Move, in Word War II Revised, while you should be able to (of course, it has the simple work-around of using Edit Mode).

**Comment by panther2** [comment]
I stumbled over this issue again, when dealing with "older" issues, and there is one aspect I have to add for completeness:

While it is correct, that in v2/AARE (2004) a transport is allowed to unload as well during Combat Move as during Non Combat Move, it may **never** do so into different territories.

The rulebook clearly states:

> [Revised (2004) Rulebook, page 31:] A transport can never offload in two territories during a single turn, nor can it offload cargo onto another transport.

Also it had been clarified in the official FAQ that had been published on the AH-Website:

> Must I offload all the units from a transport?
> No. Units may stay on board when other units offload. For example, one unit may offload during an amphibious assault, while another may offload into the same territory during the noncombat move.
