### ISSUE TITLE
Switch From 2.6 Lobby to 2.5 in Prerelease

### ISSUE THREAD

**Issue by beelee1** [triplea-game/triplea#11499]
### Reproduction Steps

1.
2.
3.

### Engine Version

Engine Version:

### Is there anything else we should know?

This is for information purposes. Wasn't sure where to put it, so here it is lol

This goes to 2.5 Lobby https://github.com/triplea-game/triplea/releases/tag/2.6%2B14129

This goes to 2.6 https://github.com/triplea-game/triplea/releases/tag/2.6%2B14130

Part of this discussion https://forums.triplea-game.org/topic/2999/2-6-release-getting-close-need-volunteers-to-help-beta-test-2-6/41?page=3

**Comment by DanVanAtta** [comment]
@beelee1 that behavior is as expected. There is now some routing of requests based on what version the game client states it is. If the game client does not include this version information, it is assumed to be 2.5. For a while 2.6 clients did not yet have this capability and so their requests went to the 2.5 lobby.

**Comment by beelee1** [comment]
@DanVanAtta right on. I didn't know if it'd help find the lobby bot break or not is why I posted it
