### ISSUE TITLE
Route Drawer To ArcheType Neutral Bug (1.9.0.0.2965)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#1151]
BugReportCernel15_Napoleonic Empires: FFA 8 Player_03_1.9.0.0.2965_20160828

In "Napoleonic Empires: FFA 8 Player", skipping all Politics, on France Combat Move round 1, when trying to move the France Fusiliers to Catalonia (not possible, as Spain is at Ceasefire), the route drawer bugs off and you receive this error:

https://gist.github.com/Cernelius/7f8de44af954cbde2221c083444fc6ab

**Comment by RoiEXLab** [comment]
#1153 should Fix this error
