### ISSUE TITLE
Is it possible to remove the ”double” version name?

### ISSUE THREAD

**Issue by FrostionAAA** [triplea-game/triplea#1152]
I noticed (just now) that the latest TripleA installs list the name two times in Windows 10 "programs and features", the place where you remove programs. I don’t know why. Here are some screenshots of the installs, including the latest1.9.0.0.2972.

Additional info about my installs:
The dir on my C-drive containing TripleA is automatically named “TripleA_1.9.0.0.2972” during install, so that is the name I see on my drive.
The Icon that is generated on my Win 10 desktop/start menu is named “TripleA-1.9.0.0.2972”.

![version](https://cloud.githubusercontent.com/assets/15268177/18032684/5db8cc9c-6d0d-11e6-89ba-1c85d05e8d80.png)

**Comment by RoiEXLab** [comment]
@FrostionAAA  Just because I'm wondering.. what is your native language? I'd guess a Scandinavian language...

**Comment by FrostionAAA** [comment]
@RoiEXLab
You are right. It is Danish. How could you tell? Have you been watching Vikings? (hehe ;-)

**Comment by RoiEXLab** [comment]
@FrostionAAA No I haven't, but since I'm German, I notice a lot of similar sounding words:
Organiser ≈ Organisieren
Installeret ≈ Installiert 
Alle Elementer ≈ alle Elemente 
And the Ø is a character I know from Scandinavian languages.

**Comment by Cernelius** [comment]
The people Jutland were Germans before the Danes invaded from southern Scandinavia (the peninsula).

**Comment by FrostionAAA** [comment]
Well, as far as I know every known tribe that we know of that have been living in Denmark is designated as being “North Germanic tribes”.
https://en.wikipedia.org/wiki/Cimbri (The “original” Jutland tribe)
https://en.wikipedia.org/wiki/Herules (The “original” Zealand tribe that got ass-kicked or culturally replaced by the Danes. 
https://en.wikipedia.org/wiki/Danes_(Germanic_tribe) An off-shoot of some Swedish tribe OR some tribe that just lived on Zealand and took control by beating the Heruli in a power struggle.
https://en.wikipedia.org/wiki/Swedes_(Germanic_tribe) 
BTW: There is no real sense in talking about Danish, Swedish and Norwegian decent, unless you talk geographically. The Norse culture and language was not divided at that stage. We were one happy North Germanic culture. Yay!

**Comment by DanVanAtta** [comment]
I took a look in install4j config to see if I could spot this, typically it is a short name field + version that  does this. Now that shortname include the version number, that is redundant. Though, I did not see any such instances. Sad to say, closing without a fix.
