### ISSUE TITLE
The TripleA program startup image.

### ISSUE THREAD

**Issue by FrostionAAA** [triplea-game/triplea#1157]
I have not seen anyone mention this, so I don’t know if it is just on my Win10 PC, if it is the same for everyone, or if this is not even considered an issue. Since the first version 1.9 I installed, there has been a startup image when starting TripleA. It looks like it is supposed to be with a transparent background, but it is shown with a black background.

Is the startup picture when starting TripleA not supposed to be transparent?

Here is how it currently looks on the center of my screen during startup:
![startup1](https://cloud.githubusercontent.com/assets/15268177/18087151/f29b706a-6eb3-11e6-95e5-a8f4d9e7683a.png)

Anyway, it would look better if it was transparent. Or maybe even better, with some “drop shadow” like this example:
![examplewithdropshadow](https://cloud.githubusercontent.com/assets/15268177/18087506/e1418f00-6eb5-11e6-8e9b-46c1a0c39b98.png)

**Comment by DanVanAtta** [comment]
The transparent version looks good. I'm not sure where the tripleA splash image is, but it should be just a matter of updating that image once we find.

**Comment by williamdekryger** [comment]
The splash image looks fine on Mac OS X 10.11 with the prerelease, just like your second image @FrostionAAA. Is this problem localized to Windows?

**Comment by RoiEXLab** [comment]
@DanVanAtta Found it! https://github.com/triplea-game/assets/tree/master/icons
No idea, what could be causing this,,,

**Comment by DanVanAtta** [comment]
I tried swapping the images for '*ico' images, and that did not work. On linux the image has the transparency. Seems to be a windows only problem. I'm not sure if there is anything we can do to fix this.

**Comment by FrostionAAA** [comment]
What about gif format? all though I would hate to see a low quality startup gif picture. Do high quality gif even exist?

**Comment by RoiEXLab** [comment]
@FrostionAAA No. The gif format is the worst unless using it for animations... Png Should work though. It seems that Install4j is broken at some point/ we are doing something wrong...

**Comment by Cernelius** [comment]
Only theoretically the worst, quality wise, but practically as good as the best: as a matter of that particular image, a properly indexed GIF would be undistinguishable from the highest quality image, due to limited colour variety; however GIF handles all or nothing transparency only, thus it is a no go for this task.

**Comment by RoiEXLab** [comment]
Stumbled upon this when fiddling around with install4j settings:
![Screenshot](https://user-images.githubusercontent.com/8350879/27080113-cf5e8d44-503a-11e7-933e-b4f4bfefafb7.png)
I believe that's whats causing the transparency issue

**Comment by FrostionAAA** [comment]
As of version TripleA_1.9.0.0.4568 the problem still exists. Would be nice to see it fixed :-)

**Comment by RoiEXLab** [comment]
I will create a PR once the current install4j related PR is being merged :)

**Comment by DanVanAtta** [comment]
Re-opening to confirm fix. #1922 potentially fixes this. Installer artifacts with the patch should be published shortly.

**Comment by RoiEXLab** [comment]
@DanVanAtta Yup, works perfectly!
