### ISSUE TITLE
Cannot open 1.8.0.9 savegames in 1.9.0.0.2994

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#1158]
I found the triplea_1_8_0_9.jar in the "old"-directory and thought it would be possible. But whenever opening any 1.8.0.9-created savegame (tried it with wwII-global) I get this:

triplea.engine.version.bin:1.9
Exception while parsing: savegame.tsvg : <html>Incompatible engine versions, and no old engine found. We are: 1.9 . Trying to load game created with: 0.0<br>To download the latest version of TripleA, Please visit http://triplea.sourceforge.net/</html>

**Comment by DanVanAtta** [comment]
Just for the sake of experiment, any idea if old versions worked when playing 1.8.0.9?

I was concerned that this feature did not work.. We should try to determine what is going on...

**Comment by panther2** [comment]
I remember it worked in the past ... my TripleA experience started about version 1.2.x.x - and I recall having it tested from time to time.

**Comment by DanVanAtta** [comment]
I'm quite sure it did once work, part of the question is if we broke in 1.9, or if it was already broken in 1.8.0.9, I would guess 1.9 is the culprit.

**Comment by ron-murhammer** [comment]
@DanVanAtta Yeah I've opened older saves 1.6, 1.7 with 1.8.0.9. So 1.9 is the culprit.

**Comment by DanVanAtta** [comment]
A fix is in https://github.com/triplea-game/triplea/pull/1165

**Comment by panther2** [comment]
@DanVanAtta 

Now (using 3004) 1.8.0.9 savegames trigger the version 1.8.0.9 - so far so good.

Please clarify: In order to play older savegames with 1.9 it appears to be necessary to have the older map versions installed, too? Because I get this having opened an old 1.8.0.9 savegame with only the latest map versions installed:
![warning](https://cloud.githubusercontent.com/assets/20812775/18219093/54aee7f4-7167-11e6-86e5-4545f5e51b8e.jpg)

So how can the user know which map version is needed? There are "before 1.9"-map-versions and "starting from 1.9"-map-versions...

**Comment by prastle** [comment]
was brokem in 1,9

**Comment by DanVanAtta** [comment]
Yes, you need the 'old' map version. You can actually download it as normal when the game launches in 'compatibility' mode.

**Comment by DanVanAtta** [comment]
We'll need to be a bit careful to tell people to not uninstall 1.8.0.9 in any way when they upgrade.

As part of that, updating the 'local' folder created at `~/triplea` probalby should be given consistent casing as the main app install, ie: `~/TripleA`

**Comment by panther2** [comment]
I agree, careful communication is necessary when releasing 1.9 - especially concerning 1.8.0.9 games.

Do we leave this issue open, as the original concern is fixed, or are we going to have a new one dealing with the discussed consequences?

**Comment by DanVanAtta** [comment]
Let's keep this issue on topic and close it. 
I've added an upgrade notes page to the website, linked from the download page: https://github.com/triplea-game/triplea-game.github.io/pull/99

I'm quite sure that is not as good as it can be, happy to see new issues with further recommendations on how to make the upgrade process easier, and/or PRs to improve the upgrade notes page.
