### ISSUE TITLE
Reference to sourceforge in error-log for the "latest version"

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#1159]
Found this in the console / error.log (2994):

triplea.engine.version.bin:1.9
Exception while parsing: savegame.tsvg : <html>Incompatible engine versions, and no old engine found. We are: 1.9 . Trying to load game created with: 0.0<br>To download the latest version of TripleA, **Please visit http://triplea.sourceforge.net/</html>**

**Comment by DanVanAtta** [comment]
Good spot, we likely should do another sweep searching for "sourceforge".. Let's get them updated!

**Comment by DanVanAtta** [comment]
Fixed in https://github.com/triplea-game/triplea/pull/1168
