### ISSUE TITLE
Simplify Map Making

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1160]
The map making process has been somewhat successful moving to github. There are some problems:
- instructions on how to get your map in github is not clear
- it takes an admin to do the travis setup, and that part is not scripted in isolation
- there are common mistakes where people do not download the zip file from releases, but instead click the 'clone or download' button to get a zip
- after any update, the yaml config file (https://github.com/triplea-maps/Project/blob/master/production_config/triplea_maps.yaml) needs to be updated, updating this in bulk requires a script (and can be tricky to make sure everything actually was updated)
- the travis map build adds another version number for us to manage, yet this version number does not really do anything.

It occurred to me, if we supported the 'clone or download' zip format, then we could have players simply use the download button: 
![dl_button](https://cloud.githubusercontent.com/assets/12397753/18099662/6fb0c7c0-6e9c-11e6-93f5-875346772129.png)

At that point, we gain a number of benefits:
- the travis build part goes away
- the yaml config will always refer to the latest version and will not need to be updated all the time
- anyone can set up a github repo and host it on their own. Given the way you can do a local download list, map makers could test the entire process locally with a simple github repo. In the same train of thought, it becomes easier to share maps as well, just create a repo, upload files, then you have the download button doing the work for you to zip everything up.

We have two maps right now that are pending incorporation to TripleA and they are a being held up. The first, war of the reich, needs a travis config. If we did the above, that map would be ready, would just need the initial entry in the yaml config.

The second map, posted to SF, needs to be uploaded. Given the relative complexity, it's been quite difficult to explain how to get things set up, and on top of that, we still need admins to do the travis piece. With the above in place, the process is simple enough that I think we could document pretty clearly how to create a repo and upload files to it. At that point the only thing you have to get right is the file structure, otherwise it's off to the races : ) 

Any thoughts? I think this can be done pretty quickly.
Since we will be updating all map links to refer to the master zips, and not the release zips, this will not be backwards compatible, old game engines cannot play those zips. This I think is worth pushing the 1.9 release back by a few days (which gives us some more time to test as well)

**Comment by Cernelius** [comment]
I understand only part of this, but what I understand all seems very good to have for the next release. It's quite painful for a mapmaker having to wait months hoping that his map will be added or updated to the DL. If the developers sometimes don't want to do the stuff readily, I guess the mapmakers should be able to have access themselves, if they are interested and up to the task, like RolfLarsson in the past, or whatever ways allowing to have maps uploaded / updated within a month from the request.

Whatever makes stuff easier / faster / less developers' dependant can only be good.

Automatically referring to the latest version is something I actually wanted to propose; seems pretty obvious.

**Comment by DanVanAtta** [comment]
We will lose automated map versioning going this route. Which is likely okay given the simplification. But going this route,  I think will we will need to rely on save games bundling the original map XML so that out of date map versions can still be loaded.

**Comment by Cernelius** [comment]
Lose what?

**Comment by Cernelius** [comment]
Not sure what that means, but I surely believe that whatever increasing savegame size should be avoided. It is not rare that savegames of big xml maps may take over 30 seconds to load (this is why the set time options were added).

**Comment by williamdekryger** [comment]
@DanVanAtta This is a really good idea. Map-making should be done in git anyways, and this will allow for map-makers to even begin their map in a personal repo before releasing it into a triplea-maps repo when it is done. Plus, it would be nice for those of us that have git to download maps via git straight into the maps folder, and then pull down new changes 👍

**Comment by DanVanAtta** [comment]
note, you can pull down changes by doing a git clone directly in the maps folder.

@Cernelius  - travis produces zips that are numbered, 01, 02, etc.. It keeps a history of every version in that manner. If we move to a 'master' zip, we lose that numbering. In that case we need to rely on a different way to have map compatibility.

**Comment by DanVanAtta** [comment]
#1164 adds support for this.

**Comment by Cernelius** [comment]
As long as this is not making the savegames significantly heavier or slower.

Most extreme example being War of the Relics, that takes 30 seconds from xml but only 2 seconds from savegame.

Savegames of big xml maps are already too slow to launch in hosted games, especially in multis (gets almost multiplied by the number) or with lots observers.

**Comment by DanVanAtta** [comment]
The XML in war of the relics is very inefficient. We shouldn't base perf/design decisions on that. The load game is fast because it is a different format that is more efficient to read in. Basically all hte inefficient parsing would have been done by the time you go to save the file.

> "Savegames of big xml maps are already too slow to launch in hosted games, "

Again, it's not at all because the size of the file is big, the setup of the file does not allow for efficient parsing, the design of the XML schema and code is not sufficient to handle files that have 40k unit attachment tags.

**Comment by DanVanAtta** [comment]
Nota bene, far more important to ensure we have map compatibility when games are played, even if it means an extra few seconds before it can be started. Better for it to start, than it to not start at all with, "sorry, but you have a newer map version and cannot play this old one, and btw, there is no way for you to downgrade either"

**Comment by Cernelius** [comment]
I understand close to nothing of the matter; I'm just suggesting that whatever making the savegames heavier / slower should be avoided (going the opposite direction would be nice), unless close to irrelevant.
Also I know that people on netbooks told me that they are already unable to play TWW, and, while not a TWW player myself, I recall past discussions when people took more than 1 minute to start TWW in a hosted game, and I know that the loading time almost multiplies by the number of players (like I had the impression that a 6 players multi is as slow to start as 5 times a 2 players one).
I'm under the impression that if somebody wants to do something of the gameplay quality of War of the Relics, it will end up with an xml about like that.

**Comment by DanVanAtta** [comment]
Sounds like for multi we are having one player load the XML, followed by the next, followed by the next.

There is nothing wrong particularly with having a long XML, the problem though is that it is inefficient. We could consolidate much of it, get rid of a lot of looping, then suddenly it would be processed fast. IE for example, today we are doing somewhere around 200k or so (IIRC, the number was large) iterations on the data in there. Most of that is fast work, but some of it is slower, 10-40ms range (with about 20-40k iterations taking that long, it adds up..)

The parsing has also been improved too compared to 1.8.0.9, so we'll need to re-benchmark against new maps before seeing how we can improve parsing performance. 

Regardless, next steps here: determine how we want to handle map versions if we go with the single URL route of map downloads.  Perhaps nothing needs to change, we might using the version in the XML file already, but we need to be sure. Some discussion as well about how to handle future map compatibility issues would be appropriate here as well.  (note: compatibiliyt between saves and map versions is perhaps on the biggest weak points we have)

**Comment by panther2** [comment]
In the context of this discussion I would like to point to issue #1185

**Comment by DanVanAtta** [comment]
This is now done thanks to some recent PRs. It's possible to play/download a map from the repo 'download map' feature.

**Comment by Cernelius** [comment]
I don't know if it is possible, but supporting being able to specify a release not being the last one may still have a value. Main example being when you are updating a map, but you don't want the regular users to download the latest version till you think it is good enough; much like having prereleases and releases in the engine.

But avoiding the various issues related to referring to a specific release is clearly more important; so, if it is not possible to have both, I believe the new system of always referring to the latest version is better than the old one of always requiring specifying the downloadable version.

**Comment by Cernelius** [comment]
https://github.com/triplea-game/triplea/issues/1236
