### ISSUE TITLE
Lubuntu 32 bit can't post in 1.9

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#1161]
I have a laptop running lubuntu 16.04 32 bit and Java 1.8

Trouble is under 1.9 I can't seem to post in play by forum. I get "Summary text: missing refresh header after login"

java -version:
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
OpenJDK Server VM (build 25.91-b14, mixed mode)

Perhaps a setup issue or something? Any suggestions?

Works on a 64 bit ubuntu 16.04 computer also running java 1.8

**Comment by simon33-2** [comment]
Hmm, seems to have fixed itself.

**Comment by DanVanAtta** [comment]
Alternate theory, perhaps was with forum and resolved itself somehow. The switch from lubuntu to ubuntu was perhaps a red herring. Hard to know exactly what happened. Good to hear it's not persistent :disappointed_relieved: .
