### ISSUE TITLE
2.6.14357 - PBF Regression (Dice Server Emails)

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#11631]
### Reproduction Steps
Try to create a PBF-game, enter more than 3 email-addresses.
Options to continue will be grayed out  and become unavailable.

### Engine Version

Engine Version: 2.6.14357

### Is there anything else we should know?
Regression, it used to work with more addresses.
-as reported here:
https://www.axisandallies.org/forums/topic/39868/only-3-emails-allowed-per-game
https://forums.triplea-game.org/topic/3506/1st-time-forum-game

@RoiEXLab Any chance you can take a look into it?

**Comment by DanVanAtta** [comment]
@panther2  this is not a problem in 2.5?

**Comment by Cernelius** [comment]
I really don't understand what's going on here.

If "it works with 2.5.stable, but not with 2.6.current", why is @ron-murhammer in forum saying "I'll take a look and see if I can fix it. This time I think I'll just put out a release with just the PBF fixes on top of 2.5 as I should have last time."

What's the point of putting a fix on top of 2.5 if 2.5 already works for what is needed to be fixed?

**Comment by panther2** [comment]
These are different topics. Ron is addressing TripleA's (legacy and current releases/pre-releases) incompatibility with current NodeBB versions, while this issue here is about something totally different: This issue here is about entering mail-addresses in the forum to address the dice server.

**Comment by asvitkine** [comment]
Hmm, I can't repro this. Can you double check with latest prerelease?

I assume the bug would result in the field staying red? For me, it's not red when entering multiple emails.

If you can repro, can you provide the exact text you entered?

**Comment by panther2** [comment]
@asvitkine Tested again with 14429;
![Tra1](https://github.com/triplea-game/triplea/assets/20812775/2df56672-7d17-4667-8ca6-42c89c143c18)

name1@mail.com name2@mail.com name5@mail.com
name3@mail.com name4@mail.com

**Comment by asvitkine** [comment]
OH, in the TO field, not the cc field.
What's the difference between listing them in To vs. Cc for the purpose of the dice server?

**Comment by panther2** [comment]
@asvitkine 

In the CC field, too:

![Tra2](https://github.com/triplea-game/triplea/assets/20812775/6241ee37-bad8-4ca8-9473-a258c65584ec)

Regarding your question:

For the dice server it would not make a difference. In multiplayer games people are usually used to enter the one faction into the TO-field, the other faction into the CC-field.

**Comment by Cernelius** [comment]
> For the dice server it would not make a difference. In multiplayer games people are usually used to enter the one faction into the TO-field, the other faction into the CC-field.

That is fairly obvious, BUT

- (FEATURE REQUEST from someone who never used the feature) I would substitute "To" with "your opponent's mail" and "Cc" with "your mail" (Cc is facultative, right?).

- how about three-or-more-players games? Especially in non-two-sides games (like FFA), shouldn't you send the dice outcomes to each of the other players? How do you do that?

**Comment by Cernelius** [comment]
Or are you supposed to put yourself and all participants in the game in the "To" and any spectators in the "Cc"? Why not having a single field for all mails instead of splitting them between "To" and "Cc"? The more I think about it, the less is clear to me what is supposed to go in "To" and what is supposed to go in "Cc".

What are the actual differences for the receiver between being in the "To" and being in the "Cc" field?

Are there some sort of guideline or tribal knowledge about who should be in the "To" and who should be in the "Cc" field?

**Comment by asvitkine** [comment]
Ohh, re: the bug, I see that entering 2 emails into a field is OK, but not 3.

**Comment by asvitkine** [comment]
Actually, looks like there's a max length of 40 for the field, so testing with short email addresses works...
