### ISSUE TITLE
unitSupportCount does nothing

### ISSUE THREAD

**Issue by BeornTheBold** [triplea-game/triplea#1163]
`<option name="unitSupportCount" value="2"/>`

This option on a unitAttachment does nothing.  I created a heavy artillery unit as follows:

`<attatchment name="unitAttatchment" attatchTo="hvy_artillery" javaClass="games.strategy.triplea.attatchments.UnitAttachment" type="unitType">
            <option name="movement" value="1"/>
            <option name="attack" value="5"/>
            <option name="defense" value="5"/>
            <option name="unitSupportCount" value="2"/>
            <option name="artillery" value="true"/>
            <option name="isLandTransport" value="false"/>
</attatchment>`

The idea is that it will support two infantry units instead of one like a regular artillery unit., but this does not happen.

**Comment by ron-murhammer** [comment]
@BeornTheBold This can definitely be done as I know 270BC elephants support multiple units. I would take a look at some of the other XMLs.

**Comment by BeornTheBold** [comment]
In the combat window, if attacking with two infantry and one heavy artillery, it shows one infantry attacking at 2, one attacking at 3, and the heavy artillery attacking at 5.  Instead both infantry should be attacking at 3, since the heavy artillery should support two units.

**Comment by BeornTheBold** [comment]
On checking the 270BC xml, I see that they are accomplishing this through a support attachment instead of using the option unitSupportCount.  I'll use that as a work-around, but it appears the option for unit attachments is bugged.

**Comment by simon33-2** [comment]
Wouldn't be the only attribute which doesn't function, @BeornTheBold .

There is also a tech which allows artillery to support multiple units and you may be able to use that if your idea doesn't work.

**Comment by sneakingcoward** [comment]
this option works.
it is used in world_at_war_variants
2 inf are supported by katyusha.
