### ISSUE TITLE
Battle calculator not pre-filling units on friendly countries...

### ISSUE THREAD

**Issue by Nova-111** [triplea-game/triplea#11664]
### Reproduction Steps

1. Open battle calculator in a map while hovering over a teammates territory. 
2. For example, in China's turn. I tried to check overall strength of American Navy as shown in screen shot.
3. See that his units in that territory are no longer prefilled into battle calculator as it was working in previous version.
4. Instead it defaults to the country on the current turn and one if it's enemies, not the country that has units in territory so even if there are units in the territory it will show "0"s for an enemy country rather than the actual stats for the targeted country.

### Attach a Save Game
 

[China9.zip](https://github.com/triplea-game/triplea/files/11641518/China9.zip)

### Engine Version

Engine Version: 2.6.14364

### Is there anything else we should know? I have tried this on 2 maps to make sure it wasn't a map problem.

![NVIDIA_Share_AkBrrWQznA](https://github.com/triplea-game/triplea/assets/87770311/9dc45cd7-0a3e-4d85-98fd-4923158fe720)

**Comment by jimparker96313** [comment]
As I'm interested in a fix for this too, I thought I'd add this info about the bug.

It affects the history as well with the added caveat that when clicking on territories in the history mode, the engine assumes it is France's turn--regardless of where you select in the history--and only will fill the battle calculator with French units (if there are any, or Axis units since they are the enemy)

I verified that this bug exists in 2.6 back to release 14247
The battle calculator worked as desired (clicking on any territory in current game or history would populate the battle calculator) in the release version 2.5-22294.

**Comment by asvitkine** [comment]
This regressed from https://github.com/triplea-game/triplea/pull/9602.

That PR uses the following order for choosing defenders, which seems to prioritize players with no units in such cases:
```
1. enemy on the same territory
2. any enemy
3. neutral on the same territory
4. any neutral
5. any player
```

So we end up picking an enemy with no units via 2.
A simple fix could be to change the above to:
```
1. enemy on the same territory
2. neutral on the same territory
3. player on the same territory
4. any player
```

The above results in the US being selected as the defender (while attacker is still active player, but with no units, so doesn't matter much).

**Comment by asvitkine** [comment]
As an aside, the issue with history is interesting, since I think https://github.com/triplea-game/triplea/pull/10759/files was supposed to fix the logic for choosing the active player.

**Comment by asvitkine** [comment]
Example repro:
  1. Napoleonic Empires, France (first turn)
  2. Do a battle calc on a Spanish territory (whose an ally)

In 2.5, Spanish units appear as defenders. UK is selected as an attacker (even if there's no units attackers).

In 2.6, France is selected as an attacker (with no units) and UK is selected as a defender (with no units).

Pretty clear that the 2.6 behavior is not what people would want here.

**Comment by asvitkine** [comment]
Another example if WW2 Global 2nd ed, bringing up the battle calc on UK should show both UK and French units.

**Comment by asvitkine** [comment]
So before https://github.com/triplea-game/triplea/pull/9602, the logic was:

 - Take the player list, ordered by number of units, except putting the current player first in the list if they have units there
 - If not water, set location owner as defender and choose first player in list that the defender is at war with

I'll have to read the details of that PR to understand what it was trying to achieve to understand why there was a logic change in the first place.

**Comment by asvitkine** [comment]
@DanVanAtta wondering if you agree that given the above, we shouldn't actually do "the attacker is always the current player" logic, given you're the one who suggested that on the above PR.

**Comment by asvitkine** [comment]
Ok, so let me try to document some cases that I think don't work as they should in 2.6:

WW2 Global 1940 2nd Ed:
  a. Germany's turn, open battle calc on Northern Italy (ally)
  Expected: Battle calc prepopulated with defending units of Italy
  b. Germany's turn, open battle calc on sea zone with Italian ships (ally)
  Expected: Battle calc prepopulated with defending units of Italy
  c. Germany's turn, open battle calc on a Russian territory (currently Neutral)
  Expected: Battle calc prepopulated with defending units of Russia
  
Let me see if I can set these up as test cases when working on a fix.
