### ISSUE TITLE
World at War 2.1.1 - Fighters don't defend against Bombers???

### ISSUE THREAD

**Issue by Falkon98** [triplea-game/triplea#11671]
World At War 3.0 or 2.1.1 ? - 2.5.2294 Java 11.0.6.  Download Maps shows Version World At War 3.0 but once installed says Version 2.1.1 ?!?

Played many rounds and Fighters do not defend against Bomber raids?!? This is a massive problem, game unplayable as a result and results in nothing but a Bomber mass build by all countries and ZERO income by any faction by round 3-4.  

Also -  Subs being able to be hit by planes without a destroyer ruined the game with the latest changes made to it.  Please tell me this is a bug and not intended?!?!  
![WAW Fighters dont defend Boming Raid 2](https://github.com/triplea-game/triplea/assets/28026000/5de6545e-d295-4150-b84e-f3a70afa3dd8)

As it stands now this game is ruined and unplayable by the 3.0 or 2.1.1 changes whatever the curr
![WAW Fighters dont defend Boming Raid](https://github.com/triplea-game/triplea/assets/28026000/7f87f271-c973-423d-be8e-1570851fe082)
ent download version is.

Falkon

**Comment by WCSumpton** [comment]
@Falkon98 

The screen shots that are posted are of "World At War" and not "World At War - v3". Thus, the game is playing by the rules it was designed for.

**Comment by Falkon98** [comment]
It's been a few years since I played World At War and the older version(s) played that fighters could defend vs. bombing raids, I have previous versions and save games that show this.  I've never played any of recent Variants of World At War.  This change completely unbalances the game by removing this fundamental function of Fighters.

**Comment by Falkon98** [comment]
Please close this out.  I was mistaken, it's been a few years since playing WaW.  Played 40+hours of 2.1.1 and it's well balanced as is.
