### ISSUE TITLE
Can't see Objectives panel in 1.9

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#1169]
Perhaps I'm missing something or perhaps it's a map issue but what has happened to the "Objectives" panel in 1.9?

**Comment by DanVanAtta** [comment]
hmm...  Any specific maps you know for sure where there was one?

**Comment by simon33-2** [comment]
It's in all the 1940 2nd ed ones and 1942 Global. Does seem to be map dependent. 1.809 didn't have it in classic, for example.

**Comment by simon33-2** [comment]
Oh, it's a map issue. It is present on certain maps in 1.9. I'll close the issue here and open one over in maps.
