### ISSUE TITLE
1.9.0.0.3010 can't open saveGames from 1.9.0.0.2984

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#1182]
Is this a wider problem or is it just a problem affecting saves from a few game versions?

Here's a link for a save created in 2984 which 3010 can't open: http://www.axisandallies.org/forums/index.php?action=dlattach;topic=38480.0;attach=532026

**Comment by DanVanAtta** [comment]
it's not completely unexpected, probably the update to the 'Version.java' property names caused this. Nothing we can do, the compatibility is broken. Java serialization is fun like this, very brittle..  The serialization proxy pattern work should help avoid this: https://github.com/triplea-game/triplea/issues/1036
