### ISSUE TITLE
No hint regarding a new map version given by the map-installer

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#1185]
Though a new map version has been released, there is no hint given by the ingame map-installer, that a new version is available. 
I have world_war_ii_global.zip version 0.24 installed (I have checked the respective world_war_ii_global.zip.properties file). Now that triplea-maps.yaml offers 0.27, this new version is not visible when using "Download Maps":
![map](https://cloud.githubusercontent.com/assets/20812775/18230550/42b97b8e-729f-11e6-89a0-d7d064a8d1b4.jpg)

**Comment by simon33-2** [comment]
Good point. It's still a significant step forward from 1.809 where the maps were static.

You have to know to remove and re-download the map.

**Comment by DanVanAtta** [comment]
The version is controlled in the yaml config file (not by the version in the XML, nor by the URL), eg: https://github.com/triplea-game/triplea/blob/master/triplea_maps.yaml#L14

**Comment by DanVanAtta** [comment]
PS: it's probably a good time to simplify the versioning for maps. AS is, they're a bit all over the place and do not mean all that much. So I plan to reset all maps to version: 1, we can increment from there. All 1.9 maps are going to look new, so this is a good time to do that.

**Comment by panther2** [comment]
@DanVanAtta 
Not sure, if I understand or if we talk about the same ... so I better describe again:
In 1.8.0.9 there obviously has been a process that compared the latest version existing with the latest version installed and notified the user by a different typeface that a new version is ready to download. Also there has been an automatic check for new maps from time to time.
I am missing this in 1.9 ... is the version control that you talk about leading to a similar process, or has this feature been aborted?

**Comment by DanVanAtta** [comment]
There is a version field in the triplea-maps.yaml file. The game engine looks there to determine if a map is out of date.

**Comment by panther2** [comment]
@DanVanAtta 

That is what I am talking about. Please see again my first statement:
The version field in the triplea-maps.yaml has been 0.27.
The map installed has been 0.24.

So the map installed has been out of date. But nothing happened.

**Comment by panther2** [comment]
Never mind, having followed all the commits that have been done during the last hours, I now realize the new process and understand it. So this issue is outdated now and thus closed.
Thank you anyway.
