### ISSUE TITLE
Map Categories

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1186]
https://github.com/triplea-game/triplea/pull/1181 added first class support for map categories. The existing 'high quality', etc.. might not be the best.

I would like to understand better how we would like map categories to evolve as a person is making a map. It seems like the first step is to launch a map as 'in development'. If a map lingers there for some time without modification, then it should be removed from 'in development'. We have a choice here if we move to a dedicated, 'unfinished' category (which would seem pretty poor quality to me if I were looking at the downloads), 'experimental', which would be a grab bag, or if we remove it completely.

Once a map is "finished", say it looks good, is playable, where should it go then? IMO it should then land to the "good" category, AKA completed maps. If there are more tweaks to perfect the map, then it happening in place is just fine (the map version number is there for that).

Are there any additional scenarios that are not considered as well? For 'best', seems like we've set the precedent for show-casing the very popular maps. Anything that is played a lot, it's pretty obvious what these are by looking at the lobby games, likely should move to this final category.

**Comment by Cernelius** [comment]
I like that the Development section has been cleaned up to only have what's actually supposedly being developed; it is surely helping. :+1: 

I don't like the new "best" and "good" names; I'd rather suggest "high quality" and "good quality", instead.

Also maybe "others" would fit better than "experimental", because it looks like there goes just everything not belonging to the other 3 cats.

**Comment by FrostionAAA** [comment]
Would it not be an idea to have the top listed category be reserved for maps that are simulations of real world printed card board A&A game (with no place for mods or house rules). Then all other maps and mod could be listed in other categories below this, even the popular ones.

I would think that these maps are the only maps a new TripleA player might actually know and maybe even downloaded the game to play. All mods and other maps are just new treasures to be discovered by the A&A player :-)

**Comment by FrostionAAA** [comment]
By the way… I have just noticed the new download categories.

The Age of Tribes, Star Trek and Star Wars maps are all past “in development”. I think they are pretty well balanced, playable and I have no ideas of how to improve on them right now.

Maybe you should think of merging the "In Development" and "Experimental" categories. I cant really see the diference. Maybe call them both “In Development” or “Maps in Beta”, hinting to players that they need work, even if there is no owner / map maker attached to the map?

**Comment by Cernelius** [comment]
A true development category is likely going to have 80% times like from 0 to 2 maps in total (probably 0 maps like half of the time), but I think that's fine. It highlights maps being worked on for which playtest and feedback is of paramount importance.

Maybe something that tells there are no maps in development, when the number is 0, as it is actually the case at the moment, as Frostion says.

**Comment by Cernelius** [comment]
> Would it not be an idea to have the top listed category be reserved for maps that are simulations of real world printed card board A&A game (with no place for mods or house rules). Then all other maps and mod could be listed in other categories below this, even the popular ones.
> 
> I would think that these maps are the only maps a new TripleA player might actually know and maybe even downloaded the game to play. All mods and other maps are just new treasures to be discovered by the A&A player :-)

Beside the dedicated category (I'm not against its removal), in the past that was also assured by the fact that only the clones were allowed to start with "World War II", nothing else.

Now, instead, there is also the "world_war_ii_g40_balanced".

I'm quite sure Veqryn would not have accepted that starting with "world_war_ii", but would have probably requested it being changed to at least "wwii".

Would now someone be allowed to call his own game "World War II", no matter what?
