### ISSUE TITLE
2.6+14509 Help> Unit Help gives An expected error occured!

### ISSUE THREAD

**Issue by TheDog-GH** [triplea-game/triplea#11968]
TripleA-2.6+14491 does not error.
TripleA-2.6+14509 does.

It appears to error on multiple maps with 

![image](https://github.com/triplea-game/triplea/assets/71022517/8e7be1d7-a0d5-4a75-b1fa-e2adebe78002)

Maps that error
1941 Global Command
Arena of Death
The Shogun Advanced
probably all maps

**Comment by asvitkine** [comment]
Can you click "Report To Triplea" so we can get the full details?

I'm not able to repro it myself. I don't get the error.

**Comment by TheDog-GH** [comment]
Reported To Triplea
[Report To Triplea](https://github.com/triplea-game/triplea/issues/11973)

**Comment by TheDog-GH** [comment]
This can be closed see
https://github.com/triplea-game/triplea/issues/11973
