### ISSUE TITLE
Cannot launch triplea after 1.9.0.0.2702 version

### ISSUE THREAD

**Issue by BlackjackKnows** [triplea-game/triplea#1198]
I am a long time (25 year) player of Axis and Allies. I have been playing triplea for the past ten years. I cannot launch triplea after the 1.9.0.0.2702 pre-release. 

I run a Windows x64 environment and always install the latest pre-release and have no historical issues. My machine and configuration have not changed. 

When I launce the triplea application I see the application icon and then immediately after the icon disappears the "TripleA Console appears in the upper left hand corner of my screen. The console is white in color and empty. Nothing further happens. I must launch Task Manager to kill the triplea process. 

I have tried the following: 
1. deleted my current Java version and reinstalled. 
2. downloaded both the Windows x32 and x64 environment 

Please help as this game means a lot to me. 

Blackjack Knows.

**Comment by panther2** [comment]
Yes, we had this here as issue #1050 

For a solution please see
http://tripleadev.1671093.n2.nabble.com/Error-after-triplea-windows-x64-1-9-0-0-2702-release-tp7593466p7593478.html

**Comment by BlackjackKnows** [comment]
Thank you so much for your help. I apologize for missing the issue as an existing issue. 

Fix worked, though the x2702 version had to be manually deleted.

Blackjack
