### ISSUE TITLE
TripleA-2.6+14513 not displaying units to place properly

### ISSUE THREAD

**Issue by TheDog-GH** [triplea-game/triplea#11994]
Clicking on Wales should allow Industry-Lgt and Industry-Med to placed because it is a 7pu territory
Also
London should display all 3 Industries

![image](https://github.com/triplea-game/triplea/assets/71022517/e0ba6c3a-49e7-43ac-b640-7274b3b8793c)

[autosaveAfterGermanyNonCombatMove-G21-place.zip](https://github.com/triplea-game/triplea/files/12754513/autosaveAfterGermanyNonCombatMove-G21-place.zip)

**Comment by asvitkine** [comment]
Thanks for the report, I understand the problem. Will work on a fix.
