### ISSUE TITLE
New map to be added to the list of downloadable maps

### ISSUE THREAD

**Issue by Ewanmx23** [triplea-game/triplea#11992]
So basically I just created my first map, and I haven't figured out how to actually play it, so I figured perhaps if it just gets added to the list of downloadable maps then I can play it? I honestly have no fucking clue what I'm doing, and according to Frostion's guide I need to ask somebody here to add my map. Here is the repository link: https://github.com/Ewanmx23/Civil_war_2028.git

**Comment by TheDog-GH** [comment]
First off, good effort as you have not even played your game.

Before you load it on to GitHub you need to get it working locally on your PC.

A few more changes are required.

In your xml you need an **info  name** something like
<game>
	<info name="Civil War 2028" version="0.005"/>

To get your map to work with TripleA 2.6 you will need **map.yml** that looks something like this
map_name: civil_war_2028
games:
- {game_name: Civil War 2028, file_name: civil_war_2028.xml}

If you join the forums and post here
https://forums.triplea-game.org/category/5/maps-mods

and create a heading of something like
**Civil War 2028 - Official Thread**

you will get more support and help than on here

**Comment by Ewanmx23** [comment]
sounds good, thanks for your help!
