### ISSUE TITLE
TripleA-2.6+14513 Bombardment TT repeated

### ISSUE THREAD

**Issue by TheDog-GH** [triplea-game/triplea#11999]
Asked many times, but there is only zone one TT to bombard

![image](https://github.com/triplea-game/triplea/assets/71022517/b55191b9-711d-4a2a-9789-a08811f447f7)

Apologies no save game

**Comment by asvitkine** [comment]
@TheDog-GH Did you have any autosaves to help repro it?

**Comment by asvitkine** [comment]
But I wonder if it's related to there being both an air battle and a regular battle at that territory...

**Comment by TheDog-GH** [comment]
Im away from my gaming laptop, I dont think I saved any autosaves.

Yes I too think it might be due an air battle and regular battle, as it does not happen often.

**Comment by TheDog-GH** [comment]
Hi, recreated it 
[2023-9-30-1941-Global-Command-Decision-G24-ComMove-2.zip](https://github.com/triplea-game/triplea/files/12774852/2023-9-30-1941-Global-Command-Decision-G24-ComMove-2.zip)
