### ISSUE TITLE
New developer jar libraries - guava, hamcrest-all, mockito

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#12]
The following three libraries I think will need to be added very soon:
- guava
- mockito
- hamcrest-all (contains additional hamcrest matchers)

Down the road I think we'll be adding the jars for:
- dagger2
- spock (?)

And of course eventually maven/gradle will be getting this stuff for us, so we won't have the jar file checked in. Till then, wanted to raise this issue, see if there was any objection.

**Comment by veqryn** [comment]
What specific functionality do each of these make possible?

**Comment by DanVanAtta** [comment]
guava - google's version of apache commons. Contains a dozen one-liner utilities, immutable collections, lots of useful stuff.

mockito - mocking library, triplatest had a discussion about alternatives. Seems like nobody minds too much and wished me a lot of luck to use mocks at all in this code 

hamcrest-all - adds additional hamcrest matchers, makes hamcrest unit assertions useful (the matchers are pretty key to hamcrest)

dagger2 - dependency injection. Spring but lighter weight, smaller scope, and no XML

spock - behavioral testing library

**Comment by veqryn** [comment]
mockito, hamcrest, and spock, would not make it into our production releases because they are only for testing, correct?

**Comment by DanVanAtta** [comment]
Assuming we bundle things well, correct. To boot, dagger and spock will be a bit more time and discussion before they are added in. Guava, mockito and hamcrest I would expect to be added in pretty soon.

**Comment by veqryn** [comment]
Do any of these libraries require a certain version of java (7/8)?
Would you still use guava if we upgraded to java 8?
I'm fine with junit4/hamcrest/mockito.

**Comment by DanVanAtta** [comment]
That library stack is effectively what I had at my last employer (couple months ago), so I've experience with them running with Java 6. So they can run in Java 6 with a version that will give us what we want (mostly the API).

Guava is an interesting one, and yes it would still be used going to java 8. It has some features that try to replicate Java 7 but in Java 6. For example:
List<String> myList = Lists.newArrayList(); 
Compare that to:
List<Sring> myList = new ArrayList<>();
vs:
List<Sring> myList = new ArrayList<String>();

The guava one is arguably better than Java7 since you don't invoke new (so maybe guava could create an array pool for you? who knows, but this is an example of DI a little bit, let others create objects, then use them)

If you are not familiar with guava, I very much recommend this:
https://code.google.com/p/guava-libraries/wiki/GuavaExplained
The above link describes a lot of features and even reasoning behind guava. A lot of it are useful day-to-day one liner type of things (these types of tool I regard as very important for being productive)

**Comment by DanVanAtta** [comment]
Closing, sounds like if we have some new Jars appear there won't be any surprise. Hamcrest and mockito likely will be very soon, guava same time or shortly later I would expect, and Dagger and Spock are more down the road type of items for the moment.
