### ISSUE TITLE
for quick chat use gitter.im

### ISSUE THREAD

**Issue by gaborbernat** [triplea-game/triplea#120]
Hello, 

I've tried in the last days and works quite great https://gitter.im. It allows platform for quick chating, a sort of better persistent IRC. What do you think, can we use this for easier and more casual communication? 

Thanks,

**Comment by DanVanAtta** [comment]
:+1:

**Comment by gaborbernat** [comment]
in that case a owner should authorize our organization on gitter.im. :)

**Comment by DanVanAtta** [comment]
@ron-murhammer , @veqryn , a chat would be useful for releases and reducing github chatter. Seems gitter is not going to hurt anything. Please approve it!

**Comment by ron-murhammer** [comment]
I believe this should be approved now.

**Comment by DanVanAtta** [comment]
Approval worked - thanks!

**Comment by DanVanAtta** [comment]
Sub-channels seem to be an obvious fit for some of our uses. Namely it can capture longer running conversations, which will help organize discussion and can reduce the number of open issues. As always GitHub Wiki would be used for recording decisions, and SF when community input or buy-in is needed. 

Some good examples for oher potential sub-channels (just to show there really is potential usage and to generate discussion points):
- sub-channel for the "how to package OS packages topic", which  would now be the "install4j" sub-channel to match the initiative. 
- GitHub releases automation pipeline
- mp3 encoding, or "shrinking the DL size"

**Comment by DanVanAtta** [comment]
@ron-murhammer , would you kindly see about creating the website sub-channel in gitter and then resolving this issue? I've created a personal website sub-channel that is getting use, an official one would be good to have. Alternatively please resolve this issue, seems like there is nothing left to do.

**Comment by ron-murhammer** [comment]
@DanVanAtta Added website sub-channel. Closing this issue now.
