### ISSUE TITLE
Srange things happening

### ISSUE THREAD

**Issue by ramon23035** [triplea-game/triplea#12091]
### Reproduction Steps

1.installed last version
2.checked launch triplea's box
3.runs perfectly
4.quit game
5.run the game
6.nothing happens
 

### Engine Version
<TripleA_2.5.22294_windows-64 installer>

Engine Version:

### it worked smoothly until i've updated the game.
Hope someone can help,thanks

**Comment by panther2** [comment]
Go to the TripleA installation directory and doubleclick on the TripleA.exe. The game should start, then. Does it?

Likely your TripleA shortcut (maybe on the desktop) does not point to the correct installation directory, then.

Which version did you update from? Did you remove the previous version and how?

**Comment by ramon23035** [comment]
@panther2 
Not working from the triplea.exe or shortcut,
But if I run the installer and click the box it works

**Comment by ramon23035** [comment]
Update problem fixed
the install program placed the folder assets in the wrong place .it was a sub of triplea directory, i've ran triplea-game-headed-2.5.22294.jar and it sayd missed subdir assets so placed it in the bin folder and now works

**Comment by panther2** [comment]
Thank you. However the installation file in question has installed correctly on hundreds if not thousands of systems. No one ever has reported a similar issue. So it is likely a specialty of your installation(s). Feel free to further investigate and share folder contents of your installation(s) when the problem occurs. 

For now I am closing this issue.

**Comment by ramon23035** [comment]
> Thank you. However the installation file in question has installed correctly on hundreds if not thousands of systems. No one ever has reported a similar issue. So it is likely a specialty of your installation(s). Feel free to further investigate, share folder contents of your installation(s) and answer my above questions when the problem occurs again.
> 
> For now I am closing this issue.

Sorry man, but i've just run the installer,changed the destination folder and it did everything without my help, but I had also to move all the content in the triplea folder and move it in the bin subire.i don't know why but I can't run the exe anymore but the .jar works fine.please update that tread or flagsmall will be missing

**Comment by panther2** [comment]
What is your Windows OS version?
Which TripleA version did you update from?
Have you removed the old version before? If not have you installed the update into a different directory?
Does your Antivirus maybe block the exe?

Under windows the *.jar is not supposed to be executed directly but the TripleA.exe. If the TripleA.exe does not work on your specific system anymore it is not an issue of the installer but of your local system.

There is nothing to update on the TripleA side. Only thing we can do is try to figure out what causes the issue on your side.

**Comment by ramon23035** [comment]
> What is your Windows OS version? Which TripleA version did you update from? Have you removed the old version before? If not have you installed the update into a different directory? Does your Antivirus maybe block the exe?
> 
> Under windows the *.jar is not supposed to be executed directly but the TripleA.exe. If the TripleA.exe does not work on your specific system anymore it is not an issue of the installer but of your local system / version management.
> 
> There is nothing to update on the TripleA side. Only thing we can do is try to figure out what causes the issue on your side.

win 10 x64, previous install uninstalled via windows app installer menu,previous version unknown
installed before in same dir as older version(default folder) then changed to C:\triplea
no antivirus issue that i know,no problem before,i really don't know what's going on
