### ISSUE TITLE
can't cancel rocket target

### ISSUE THREAD

**Issue by doctored** [triplea-game/triplea#1209]
version 1809 trying to cancel just refreshes the window.

**Comment by simon33-2** [comment]
I think cancel just cycles through the airbases. What do you think it should do, if you don't like this approach?

**Comment by doctored** [comment]
well when i did it there was only one airbase with damage so it kept showing the same one forcing me to repair.

**Comment by simon33-2** [comment]
It gives you the option of not attacking doesn't it? Deferring the decision until after other attacks is not a valid option.

**Comment by doctored** [comment]
no it just has a list of available targets and an ok/cancel

**Comment by simon33-2** [comment]
Oh. I'm sure that 1.8.0.9 had a don't attack button. In the meantime it will be an edit mode fix.

**Comment by doctored** [comment]
yeah but if you accidentally say attack thats when you get caught in the loop

**Comment by simon33-2** [comment]
Ahhh, now I see the problem. 

It is similar to the sub combat issues and the multiple airbase rockets. 

The problem is that the engine doesn't allow a store and forward type system where you select the attacks but don't see the results until you finish selecting. At least under certain circumstances.

**Comment by simon33-2** [comment]
I think the problem really is that there is a cancel button at all. Once you've said you're attacking a certain territory it doesn't make sense to cancel.

**Comment by doctored** [comment]
sure it does if it was accidental. :)

**Comment by simon33-2** [comment]
Not really. If there is only one facility you don't get the box at all.

**Comment by doctored** [comment]
maybe in that case yes but as long as you have choices you should have the option of backing out such as you do with repairing or rolling tech. in any event the cancel button does not function so either it should be removed or fixed imo :)

**Comment by simon33-2** [comment]
There are some things you can't back out of. Done buttons particularly, but you also can't revoke a DOW.

Anyway, my fix would be to remove the cancel button.

**Comment by ron-murhammer** [comment]
@doctored Do you have a save game that can be used to quickly reproduce and test this issue?

**Comment by doctored** [comment]
this one will probably work germany has rockets.

[autosave_round_odd.tsvg.zip](https://github.com/triplea-game/triplea/files/481473/autosave_round_odd.tsvg.zip)

**Comment by simon33-2** [comment]
I found it simple to reproduce. Just add rocket tech to Germany, click through to the end of combat movement, target London.

**Comment by DanVanAtta** [comment]
https://github.com/triplea-game/triplea/pull/1386 removes the cancel button in question (since the cancel button here did nothing). 

I created this ticket to follow up and add the cancel button back in with more useful behavior: https://github.com/triplea-game/triplea/issues/1387
