### ISSUE TITLE
2.5.22294 - TripleA Engine will not start on Debian 12 system (fresh install)

### ISSUE THREAD

**Issue by redwood-1** [triplea-game/triplea#12090]
### System Info
MX Linux 23.1
Debian version 12.2
Desktop KDE Plasma 5.27.5

Java --version
openjdk 17.0.9 2023-10-17
OpenJDK Runtime Environment (build 17.0.9+9-Debian-1deb12u1)
OpenJDK 64-Bit Server VM (build 17.0.9+9-Debian-1deb12u1, mixed mode, sharing)

### Reproduction Steps

1.  Installed using the Linux install script at https://github.com/triplea-game/triplea/releases/download/2.5.22294/TripleA_2.5.22294_unix.sh
2. Launch game (via .desktop file or directly)
3. Splash image appears and cursor changes to spinning rainbow
4. Nothing happens and splash screen disappears when you click somewhere else
5. Process remains in memory
6. New (duplicate) process is started if app is launched again 

### Contents of ~/TripleA/error.log file:
java.lang.ClassNotFoundException: org.triplea.game.client.HeadedGameRunner
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:80)
	at com.install4j.runtime.launcher.UnixLauncher.start(UnixLauncher.java:66)
	at install4j.org.triplea.game.client.HeadedGameRunner.main(Unknown Source)
Uncaught error fetching image:
java.lang.NullPointerException: Cannot invoke "java.net.URL.openConnection()" because "this.url" is null
	at java.desktop/sun.awt.image.URLImageSource.getConnection(URLImageSource.java:103)
	at java.desktop/sun.awt.image.URLImageSource.getDecoder(URLImageSource.java:113)
	at java.desktop/sun.awt.image.InputStreamImageSource.doFetch(InputStreamImageSource.java:264)
	at java.desktop/sun.awt.image.ImageFetcher.fetchloop(ImageFetcher.java:212)
	at java.desktop/sun.awt.image.ImageFetcher.run(ImageFetcher.java:176)

### Engine Version

Engine Version: 2.5.22294

### Is there anything else we should know?
Other users have experienced this issue. Discussion in progress at: (https://forums.triplea-game.org/topic/3675/failure-to-launch/3?_=1699634658362)

**Comment by beelee1** [comment]
@redwood-1 Idk if it matters at all. I've had 2.5 since it came out but had trouble with the install at first. What I ended up doing after dl was 

right click on it
go to properties
go to permissions
then check execute

As i said, idk if that's necessary and yours seems a different issue, but that's how I got it to work. Maybe @asvitkine can take a look when he gets time ?

**Comment by redwood-1** [comment]
Hi @beelee1. Thank you for the suggestion. However, it does not appear to be my problem. The script runs just fine and the program gets installed, it just wont start.
I also have run 2.5 on Debian systems since it came out. I'm only having this problem since upgrading from MX 21 (Debian 11) to MX 23 (Debian 12).

**Comment by panther2** [comment]
I see you guys run Java 17 on your systems.
I seem to remember that TripleA requires Java 11. At least the (Windows) downloads come with a bundled Java 11, that is not used system-wide, but only with the TripleA installation it is bundled with.

Isn't the "TripleA_2xxxxx_unix.sh" bundled with Java 11, too?

Maybe the issue is about Java incompatibility .....

**Comment by beelee1** [comment]
@redwood-1 yea i'm on 19. You could try that.

![Screenshot from 2023-11-11 16-17-29](https://github.com/triplea-game/triplea/assets/24382682/c02eebe8-0fb1-4163-a6b5-31c372a39fb5)

**Comment by redwood-1** [comment]
OK. I think I got it working. 

I removed all  versions of java (jdk and jre) from my computer, then ran the Triple A install script again. This time it starts up and tells me that the Java Version  is 11. It appears that Java 11 is bundled  with the installer after all. 
I think the issue is with JRE 17 and JRE 21 (which are the only two I was able to get working  on my Debian 12 computer). 

Since 2.6 is just around the corner, I don't think it's necessary to spend  any more time on this.  I'm going to  close the issue. Thanks to everyone who responded.

**Comment by beelee1** [comment]
well idk about just around the corner :) but glad you got it working

**Comment by aaron-michaux** [comment]
Java11 is now 6 years old. Not everyone can install it.

**Comment by beelee1** [comment]
@aaron-michaux 

you are unable to install java 11 ? I thought triplea did it automatically. You can't get triplea to work then ?

Will ask @astvikine and @frigoref

**Comment by aaron-michaux** [comment]
I was able it install the JRE in the application directory, and run HEAD via gradlow. I know it’s work, but the install script didn’t work out the box. Sent from my iPhoneOn Sep 21, 2024, at 11:06 PM, beelee1 ***@***.***> wrote:﻿
@aaron-michaux
you are unable to install java 11 ? I thought triplea did it automatically. You can't get triplea to work then ?
Will ask @astvikine and @frigoref

**Comment by beelee1** [comment]
well ... Dan cycling across America right now. The other guys probably busy but I imagine one of the Devs will get back to you at some point.

What OS are you on ? I have had some trouble with the linux one but just click through it and it usually works

**Comment by aaron-michaux** [comment]
Debian Trixie. Will be happy to work with devs.
