### ISSUE TITLE
Tutorial MiniMap not synced with world map

### ISSUE THREAD

**Issue by tvleavitt** [triplea-game/triplea#12117]
### Discussed in https://github.com/triplea-game/triplea/discussions/12116

<div type='discussions-op-text'>

<sup>Originally posted by **tvleavitt** November 23, 2023</sup>
The post title is awkwardly phrased, but as you can see, the tutorial "minimap" in the upper right-hand corner only covers the top portion of the overall world map, and thus the "selection" box in it doesn't correlate to what is displayed in the primary viewing area. Is this the result of a change in how 2.6 renders this? I imagine this problem isn't limited to the Tutorial map.

![Screenshot 2023-11-23 at 8 54 16 AM](https://github.com/triplea-game/triplea/assets/4445057/0e6fa730-d897-4fca-ae9e-6e700fec089e)
</div>

**Comment by DanVanAtta** [comment]
Big question here is whether this is an issue in 2.5
I don't believe anything would have changed around this functionality, but I'm really not sure what is happening.

**Comment by beelee1** [comment]
It seems specific to the Tutorial map, for me anyway. I'm on linux. Mac and triplea have had there issues in the past. Does it do it on other maps for you @tvleavitt ? 

2.5 Tutorial is correct for me but not 2.6. A different map and 2.5 and 2.6 both work.

2.5 Tutorial
![Screenshot from 2023-11-23 16-16-16](https://github.com/triplea-game/triplea/assets/24382682/4ad322d8-f736-4f3d-a9ed-1df710ffc980)

2.5 Global map
![Screenshot from 2023-11-23 16-20-08](https://github.com/triplea-game/triplea/assets/24382682/0db9792c-2d0b-4cf3-b6d8-ca635b9057cf)

2.6 Global map
![Screenshot from 2023-11-23 16-17-50](https://github.com/triplea-game/triplea/assets/24382682/9e32a802-0231-4d52-b71e-8cb1067a740c)

**Comment by tvleavitt** [comment]
I downloaded the "Charles De Gaulle 1939" map, and as you can see, the bottom of the map as shown in the minimap, is inaccessible (even when directly dragging the main map itself) and out of sync with the minimap.

![2023-11-25 15_22_39-Greenshot](https://github.com/triplea-game/triplea/assets/4445057/47a7bdef-6411-4a02-a541-57757193ea52)

**Comment by beelee1** [comment]
hmm ... I'm getting the same issue with "Charles De Gaulle 1939" . Works on 2.5 but off on 2.6. However https://github.com/beelee1/global_40_expansion_uhd_boxes works on both. The only thing different, is that you can't DL it from triplea. You have to DL the zip from the repo.

@tvleavitt mind trying that ?

**Comment by tvleavitt** [comment]
@beelee1 Will do when I get a chance.

**Comment by DanVanAtta** [comment]
@tvleavitt / @beelee1 - looks like @asvitkine jumped in with a fix here! How does this look now with the latest?

**Comment by beelee1** [comment]
Unfortunately, it didn't work for me. I installed the 14579 unix. The mini map is still off and now it doesn't, the mini map, show the entire map.

![Screenshot from 2023-11-27 09-54-22](https://github.com/triplea-game/triplea/assets/24382682/5420c7ea-55d4-41c3-accf-e6c1c5ad7314)

![Screenshot from 2023-11-27 09-54-49](https://github.com/triplea-game/triplea/assets/24382682/2b270bce-cb1e-4820-81a9-5f7cc8b98d0c)

**Comment by asvitkine** [comment]
@beelee1 Can you please double check that you actually ran the latest prerelease? Because I'm pretty sure that's the behavior exactly as it was before the fix. And I tried the latest prerelease and it doesn't behave that way.

Also, can you click "Report to TripleA" for the NullPointerException? The screenshot of the dialog doesn't help figure out what's wrong there.

**Comment by beelee1** [comment]
@asvitkine oops ! My bad. It does work correctly on 14579. Sorry about that. 

I submitted the NullPointerException error.

**Comment by ZjelcoP** [comment]
I did manipulate the dimensions of the minimap to unusual values so that the gamenotes would be at the right width.
This issue probably has something to do with it.

As the gamenotes-tab unfortunately has been booted I can change the minimap back tot the original one. 
Will give the Tutorial a makeover when 2.6 gets released.
