### ISSUE TITLE
Resource Image Not Showing up on 2.6

### ISSUE THREAD

**Issue by beelee1** [triplea-game/triplea#12183]
### Reproduction Steps

1.DL the zip directly from the repo here 
2.https://github.com/beelee1/global_40_expansion_uhd_boxes
3. Added 2 custom resources and there images showup on 2.5 but not 2.6 14586. The game behavior is correct though.
4. On Game start click on Resources and you will see there not present but the number of them are.
5. Then Declare war on russia with Germany. This will activate the resources in russia's purchase window. You can either tap through or load the saves. Probably just as easy todo either.
6. Here are some shots

### Engine Version

Engine Version:2.6 14586

2.5
![Screenshot from 2023-12-05 13-07-33](https://github.com/triplea-game/triplea/assets/24382682/4bb6ce3e-11ae-4c8e-af3c-552cd4d2d524)

2.6
![Screenshot from 2023-12-05 12-55-20](https://github.com/triplea-game/triplea/assets/24382682/3e7c9648-7aec-4f40-a1c8-1c50b1b6d87e)

2.5
![Screenshot from 2023-12-05 13-09-21](https://github.com/triplea-game/triplea/assets/24382682/e2c79190-9b65-4ca9-a01f-191a842c8359)

2.6
![Screenshot from 2023-12-05 12-56-12](https://github.com/triplea-game/triplea/assets/24382682/21bd793c-af61-4202-9a30-4784315892c7)

2.5 save
[2.5 Resource Image Save.zip](https://github.com/triplea-game/triplea/files/13572167/2.5.Resource.Image.Save.zip)

2.6 save
[2.6 Resource Image Save.zip](https://github.com/triplea-game/triplea/files/13572189/2.6.Resource.Image.Save.zip)

**Comment by TheDog-GH** [comment]
As an aside when installing the mod I get the following;  (Im a Windows user so we cannot have duplicate filenames even though Linux can, check the case)

You have put in some serious time to mod this 👍  👍 

![image](https://github.com/triplea-game/triplea/assets/71022517/61504349-9d5c-4ff4-b016-8805ad6a5419)

![image](https://github.com/triplea-game/triplea/assets/71022517/1cfd8641-1273-4571-8157-6e82829bebcc)

**Comment by beelee1** [comment]
@TheDog-GH hmm ... thought the ANZAC Ftr was fixed a long time ago. Still showing up though ? I will take a look at that again. TY

Yea it's been at 125 since the get go. Basically Elkstars map without max territories/tiles.
I may try a different mod using the existing WW II Global 2nd edition map and see if it happens then as well. 

Thanks for the reply

**Comment by asvitkine** [comment]
So this is what I'm seeing internally when it tries to load the images. Do you know where those images are supposed to be coming from?

```
java.lang.IllegalStateException: Cant load: AirLendLease  looking in: resources/AirLendLease.png
java.lang.IllegalStateException: Cant load: TankLendLease  looking in: resources/TankLendLease.png
```

I guess from `map/doc/images`... I'm not sure what changed in 2.6. We probably need to bisect through the prereleases...

**Comment by asvitkine** [comment]
I think 2.6 is expected these to be in `map/resources/AirLendLease.png` etc.

Why does 2.5 find them in `map/doc/images`?

**Comment by asvitkine** [comment]
Actually I see the exact same behavior with 2.5.

Can you double check it's not user error on your end?

**Comment by beelee1** [comment]
yea, so I go to the mainTripleA folder and open assets

![Screenshot from 2023-12-06 08-40-21](https://github.com/triplea-game/triplea/assets/24382682/83762236-c3ab-4971-9686-7004fbb815ee)

then resources

![Screenshot from 2023-12-06 08-40-47](https://github.com/triplea-game/triplea/assets/24382682/245975df-506c-43c9-bdc5-14437bbd1e56)

and that's where I put the new images. 

![Screenshot from 2023-12-06 08-40-57](https://github.com/triplea-game/triplea/assets/24382682/381c39e7-b006-4c4c-984e-bc2e639b20c6)

I also had them in the doc images folder and removed them but get same result.
I will go back throgh the prereleases and see where it changed

**Comment by beelee1** [comment]
@asvitkine yes they are in the resource folder. The reason I also had them in the doc/images, is because I want to reference them in the Game Notes.

I made it back to https://github.com/triplea-game/triplea/releases/tag/2.6.535 from Jan 3 2022 but it's the same. Idk how to use the search function that well. I'm not sure how to find the very first 2.6.

But yea, as stated in the first post, it works in 2.5

**Comment by TheDog-GH** [comment]
@beelee1 
I have not looked at your xml code.

But I notice that in both 2.5 & 2.6 Produce panel images there is no Resources tab like in one of my unpublished games below;

I hope this is helpful and not a distraction.

![image](https://github.com/triplea-game/triplea/assets/71022517/62b46447-edef-42ae-bdf0-5a7198b0e612)

**Comment by beelee1** [comment]
Hi Dog

Yea the resource is not produceable. You get a limited amount at game start. In this case, 3 of each. Basically, it is just a way to keep track of Lend Lease units. UK and or USA can send 3 Tanks or 3 Air units to russia. Just wanted a way to track it.

Anyway, the main point is, that it works in 2.5 and not 2.6 :)

**Comment by asvitkine** [comment]
So just to be clear:

1. In 2.5, you can go to TripleA's directory and put the resource image under "resources" dir and it will work in-game.
2. In 2.6, this doesn't work.
3. In both versions, putting it in the "resources" directory in the map's zip works fine.

If the above is correct, I think this is a WontFix since I don't think it's intended for people to put custom images in their TripleA installation directory. And the correct way, which is to put it in the folder of the map, works fine in both versions.

So closing per the above. But if I misunderstood, please re-open.

**Comment by Cernelius** [comment]
> So just to be clear:
> 
> 1. In 2.5, you can go to TripleA's directory and put the resource image under "resources" dir and it will work in-game.
> 2. In 2.6, this doesn't work.
> 3. In both versions, putting it in the "resources" directory in the map's zip works fine.
> 
> If the above is correct, I think this is a WontFix since I don't think it's intended for people to put custom images in their TripleA installation directory. And the correct way, which is to put it in the folder of the map, works fine in both versions.
> 
> So closing per the above. But if I misunderstood, please re-open.

My guess is that he/she put them in `TripleA/assets/resources` but not in `X/assets/resources` where "X" is the (user defined) name of the folder of the 2.6 installation, so of course they would be showing in 2.5 but not in 2.6 (because they are in the assets for 2.5 but not in those for 2.6).

If my understanding is correct, this would be "Invalid" rather than "WontFix", but please @beelee1 just correct me if I'm guessing wrongly.

**Comment by beelee1** [comment]
@Cernelius 

_My guess is that he/she put them in TripleA/assets/resources but not in X/assets/resources where "X" is the (user defined) name of the folder of the 2.6 installation, so of course they would be showing in 2.5 but not in 2.6 (because they are in the assets for 2.5 but not in those for 2.6)._

hmm ... this looks like the problem but I'm not sure. I have two triplea folders. 

![Screenshot from 2023-12-08 17-27-18](https://github.com/triplea-game/triplea/assets/24382682/5c46a269-6b79-464e-9204-311737ddb3b2)
 
The "TripleA" one is where the resources are and where I put the images .png 

I don't quite understand if I need to rename "TripleA" folder ?

@Cernelius is correct. 2.6+14586 has it's own "assets" folder and you need to put the images in it's "resources" folder. 

It now works correctly. 

Any suggestions on how to document this for future users so they don't have to spend hours of frustartion as i did @asvitkine

**Comment by asvitkine** [comment]
I'm still confused why you're putting these in the TripleA folder instead of making them part of the map.

**Comment by Cernelius** [comment]
> I'm still confused why you're putting these in the TripleA folder instead of making them part of the map.

@asvitkine I guess he/she simply doesn't know that he/she is supposed to do that.

I'm not sure what the current state of TripleA map-making documentation is, but here it is an example of where these things are supposed to stay:
https://github.com/triplea-maps/the_pact_of_steel/tree/master/map/resources

Besides, I'm going to re-close this issue properly.

**Comment by Cernelius** [comment]
@asvitkine About the two "triplea" and "TripleA" folders, I wonder if the developers changed the default folder name from "TripleA" to "triplea" at any point going from 2.5 to 2.6.

If they did, this is likely due to cause confusion for other users in case-sensitive systems because the new installation will not automatically over-write the previous one.

As far as naming goes, I would definitely suggest "TripleA" over "triplea".

@beelee1 If they did not, then I guess you just chose "triplea" (instead of the default "TripleA") as the name of the folder of the 2.6 installation, so now you have 2.5 in the "TripleA" folder and 2.6 in the "triplea" folder. They are simply two differently named folders so long as you use a case-sensitive system.

**Comment by beelee1** [comment]
@Cernelius actually 2.6 is in my "TripleA" folder. I didn't realize it had a separate "resources" folder from 2.5 that I needed to add the images to.

**Comment by Cernelius** [comment]
> @Cernelius 2.6 is in my "TripleA" folder. I didn't realize it had a separate "resources" folder from 2.5 that I needed to add the images to.
> 
> Thanks for your help.

@beelee1 Just to make sure, you are supposed to add those files into a "resources" folder of the "map" folder of your map (not into the TripleA assets) (unless you are planning to have those files added to the program itself, but I don't see this being the case).

**Comment by TheDog-GH** [comment]
@beelee1
Here is my Windows TripleA files
![image](https://github.com/triplea-game/triplea/assets/71022517/faf68e7c-ada8-48b9-875d-4242c8a39a68)

When I install a new version of TripleA I put the **version number** in the **folder name** and **shortcut**.

This means I know what the folders contain just by looking at them.
2.5.3 is a custom 2.5.22294 build
2.5.22294 is the current stable 2.5
2.6.14599
2.6.14604

Another advantage of this method is when I uninstall, it will only uninstall the version I want it to.

If you dont do this method and install multiple version of 2.6 into the same folder you never really know for sure what version or component is actually running, especially if the install fails or crashes.

**Comment by beelee1** [comment]
@TheDog-GH yea i just name the pre whatever it's number is. 

Hmm ... it seems i need a reources folder then inside map. I will do that. Thanks again.
