### ISSUE TITLE
Joining/Leaving Chat-Log Information

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#12247]
Especially since currently there are financial problems, which I believe can be easily solved by just reducing the number of automated hosts, which would again cause problems of users fighting over the few bots, I want to reiterate that it is very important that any chat-log which moderators can get gives full information on who entered and left the host (as it was indeed the case in the past), preferably with the time.

According to the rules (and common sense), amongst various users in the same bot, the one who has the primary right to use it is usually the one who entered it first, and this rule is defeated by the fact that moderators cannot know when anyone who is already inside the host entered it.

(This is a major issue only in case the number of hosts may be limited: obviously, if there are more hosts than users which want to use them (which is usually the case as of now, thanks to the many bots), there is no such problem.)

**Comment by Cernelius** [comment]
To be clear, this is a feature request for having the information about the users which joined and left when any moderator gets the chat-log of the automated hosts similarly to how they are displayed in chat when you are inside a host and somebody joins or leaves.

**Comment by DanVanAtta** [comment]
Closing, won't fix.
Efforts are going to be put into making the network relay system function. At this juncture everything related to bots is purely life-support and nothing more.

**Comment by Cernelius** [comment]
@DanVanAtta I don't think that this can be considered completed, so I'll re-close it differently. Let me know if I'm wrong and just re-re-close as completed in case.

Moreover, just posting here a link to a recent practical example:
https://forums.triplea-game.org/topic/17/post-here-if-you-boot-ban-or-mute-someone/1709

Also considering the well known and impactful problems which automated hosts do have (mainly the freeze-upon-joining problem with related game-saves corruption if saved or disconnected when thus frozen), I would argue that this may be still worth considering if automated hosts are going to be around for a few more years, but I agree that rather focusing efforts on what you mention would be much better also for financial considerations (as I suppose that we cannot exclude that the community may be decreasing over-time, so the automated hosts may become unsustainable in the future).
