### ISSUE TITLE
unt does not exist

### ISSUE THREAD

**Issue by redanto** [triplea-game/triplea#12249]
### Reproduction Steps

1. Tried to start a new game via Forum.
2. When I ran the test it says that my forum account does not exist
3.

### Attach a Save Game
 No

### Engine Version
   Version 2.5.22294 (2.5.22294)

Engine Version:   Mac OS   10.13.6 (17G14042)

**Comment by redanto** [comment]
Here is what it says - User redanto doesn't exist.  java.lang.IllegalStateException: User redanto doesn't exist.

**Comment by beelee1** [comment]
@redanto it may be related to this https://forums.triplea-game.org/topic/3685/password-issue

For now try logging in without an account

**Comment by panther2** [comment]
> Here is what it says - User redanto doesn't exist. java.lang.IllegalStateException: User redanto doesn't exist.

Please check that you have chosen the correct forum to post in (PBF setting).

**Comment by panther2** [comment]
#12207
