### ISSUE TITLE
Is Gradle Outdated ?

### ISSUE THREAD

**Issue by beelee1** [triplea-game/triplea#12255]
when trying to update a map to the yaml for #12254 I receive this error

![Screenshot from 2024-01-06 08-25-02](https://github.com/triplea-game/triplea/assets/24382682/c0751feb-f768-4da9-a4dc-3b81d2356f05)

**Comment by DanVanAtta** [comment]
That is a warning message that simply says when we upgrade Gradle to a next version - there are some features we are using which are considered 'deprecated'  and might not work when we upgrade. It's a non-issue until we upgrade, at the same time resolving those deprecations would better position us to be able to upgrade.

Upgrading early & often is a best practice. THe alternative is to upgrade rarely, in which case upgrade "projects" tend to be major projects and about as enjoyable as pulling teeth (the more stuff being upgrade, the more things changing, the more incompatibility that has to all be dealt with all at the same time).
