### ISSUE TITLE
UI Tweaks

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1226]
- [x] View menu: Rename "Show by default" -> "Show Unit Flags" 
- [x] Export menu: Rename"Export screenshot" -> "Export Map Snapshot"
- [x] Remove network menu from single player games

**Comment by Cernelius** [comment]
"Export screenshot" is definitively wrong and confusing. I would say "Export Full Game Image", as "Map" makes me thing I'm exporting just the map, like for printing it out as a boardgame, without the units on it etc..

Also, sometimes people want to actually export the map, to print it out; you may want to inform them they can do it by first ticking View/Show Units off.

**Comment by DanVanAtta** [comment]
"Game" vs "Map" has an interesting history. I think map makers know "game" very well as distinct from "map". The casual user thinks of a game as something that is taking place, while the map is more the territories and connections and initial unit allocation.

"Export Full Game Image" would then seem to render a full drawing of the map with the current unit locations.

**Comment by FrostionAAA** [comment]
I don’t get it. What’s wrong with Screenshot? I know it does not generate an image of JUST what is on the screen, but it is a normal word for what is happening. Using other words would be just as confusing.

Export map image could just as well mean exporting a clone of the map zip, at least in my understanding.
Game image could sound like a save game or something. 
What about renaming to “Export screenshot of entire map”? Or some other rephrasing?

It seems people have different understanding of the words and the interpreted meaning.

**Comment by DanVanAtta** [comment]
"Export map image could just as well mean exporting a clone of the map zip"

How so?

**Comment by FrostionAAA** [comment]
If “map” is understood as "the entire map" with all attached files, rules, setup and whatever, not only the graphics currently seen on screen. But again, maybe it is just a matter of perception and understanding of words.

**Comment by Cernelius** [comment]
Whatever sensible solution is much better than calling that thing "screenshot" or "screenview" or "screenanything".
Now you can't even say that you took an actual screenshot, without anyone else thinking that you exported that thing, instead.
"screenshot" should go for good, as a name.
What about:
"**Export Full View Image**"?

**Comment by DanVanAtta** [comment]
The feature in question also captures unit positions?
"Export Map Snapshot" would work in that case if we have units too. Otherwise I still like "export map image" the best so far. "Export full View image" is not bad, but a bit unclear what is meant by "full view", and "image" of what?  "Export full map image" might be better.

**Comment by Cernelius** [comment]
As long as screenwhatever goes.

**Comment by ron-murhammer** [comment]
@DanVanAtta - "network menu shows during single player games" should be fixed with #1281

**Comment by ron-murhammer** [comment]
@DanVanAtta - Renamed both menu options with #1282
