### ISSUE TITLE
Less Generic Game XMLs

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1227]
Now that we've removed Grid games, there may be cases where it really does not make sense to specify a delegate via XML. I'd like to raise the topic to see if anyone had similar ideas

**Comment by ron-murhammer** [comment]
It would be great to move game XMLs to a XSD and just use a framework to parse rather than the reflection stuff we have. It would make things easier to validate and should make the XML easier to work with.

**Comment by DanVanAtta** [comment]
XSD's can be pretty brittle.  An example in this ticket is the TripleA game loader. We use the same one everywhere now, and we no longer have to define it in the XML.

**Comment by ron-murhammer** [comment]
Fair. I guess I'd like to decouple the XML from the java packages all together. But I see at least in this issue you are just looking to remove places where there is really only 1 option.

**Comment by DanVanAtta** [comment]
This was done I believe. We have a translation layer between name and class instance. Before we instantiated classes directly based on what was in XML, adding in a layer in between allows us to change the code and not break XMLs
