### ISSUE TITLE
Crash for player with no capital

### ISSUE THREAD

**Issue by Eqqm4n** [triplea-game/triplea#12283]
[autosaveAfterBritishCombatMove.zip](https://github.com/triplea-game/triplea/files/13968130/autosaveAfterBritishCombatMove.zip)
After the battle in Angola is completed with British victory the game crashes due to no Capital for player NeutralAllied.

**Comment by beelee1** [comment]
@Eqqm4n we'll ping @RogerCooper as he has done some work on the map

**Comment by RogerCooper** [comment]
Please post your XML file, as you seem to have modified it.

**Comment by Eqqm4n** [comment]
[world_war_i_1914_b.zip](https://github.com/triplea-game/triplea/files/13970162/world_war_i_1914_b.zip)
Then the offending line is likely No. 1186, 
`<option name="capital" value="Contested"/>`
So what's happening is that I am trying to make a version of the Larry Harris WWI map that does a better job of implementing the ruleset.  One issue I tried to fix is the following ::
* Player A moves into an enemy territory (player B) and it becomes Contested
* Player A fails to clear the territory, so it remains Contested when player B takes their turn
* Player B does not do anything on their turn regarding moving units into/out of the territory and allows the combat to continue
* Player B's units are wiped out on their combat turn.  This should convert the territory to player A's ownership, but it doesn't, it remains Contested.  To fix this without using edit mode player A has to remain in the territory over their next turn so it correctly flips ownership.  This can be a bit of an issue when the territory is an enemy Capital as you now have a 1-turn delay in getting the proceeds from looting the Capital

I had thought that since Contested is a player on this map that the error was a result of that player never having any action phases assigned to it, so the engine never evaluated when Contested should lose control of a territory.  So I sprinkled some `<step name="contestedBattle" delegate="battle" player="Contested"/>` around hoping that this would trigger some sequence of checking who owns what territory.  However this caused a game crash since player Contested didn't have a capital, which is why I assigned one to a game space that Contested starts as the owner of.

**Comment by Eqqm4n** [comment]
Hmm even when I remove the Capital assignment from that territory I still get the crash...

**Comment by TheDog-GH** [comment]
@Eqqm4n 
Hatching on the map shows the territory it is contested to the players and if using 
```
    <!-- Any territory that contains enemy units will not produce any income or resources -->
    <property name="Contested Territories Produce No Income"	value="true" editable="false">	<boolean/>	</property>

```

then maybe this is good enough?

**Comment by WCSumpton** [comment]
@Eqqm4n 

This xml seems to have a few problems. And I think that this should be handled under **Map & Mods** form. This issue should be closed and moved there.

Cheers...
