### ISSUE TITLE
Napoleonic Empires FFA 8 Players, turning off politics is not working. 

### ISSUE THREAD

**Issue by Grinchveld** [triplea-game/triplea#12291]
![image](https://github.com/triplea-game/triplea/assets/135636727/f329aee3-ce5e-4cae-80a3-5bf4431dd2cf)

no matter what the settings are that I try it will not allow UK to attack the Ottomans turn 1. 

In previous versions there was not issue with that. 

Also, saving defaults for that map is no longer working.

thanks

**Comment by Cernelius** [comment]
I'm fairly certain it has always been this way.

Turning off politics "per se" means that the relationships cannot be changed, not that everyone gets to have War relationships with everyone else if this is what you meant.

In the specific case, if you turn the option off before starting the game, "UnitedKingdom" will be at ceasefire with "OttomanEmpire" forever.

Please, open an other issue for the other thing you mentioned (saving defaults), even though I think it is a problem which has been reported several times in the past (and never fixed).

**Comment by Grinchveld** [comment]
I figured it out. It was the wrong version of the map.
