### ISSUE TITLE
Failed to download the list of available maps from TripleA servers (2.6.14624 Mac)

### ISSUE THREAD

**Issue by mateddy** [triplea-game/triplea#12303]
Failed to download the list of available maps from TripleA servers. You can download the needed maps manually into your TripleA maps subfolder from https://github.com/triplea-maps/.  FeignException$Unauthorized: [401 Unauthorized] during [GET] to [https://prod.triplea-game.org/maps/listing] [MapsClient#fetchMapListing()]: [Invalid request]  If this problem happens frequently and is something you cannot fix, please report it to TripleA

**Comment by asvitkine** [comment]
Fixed with https://github.com/triplea-game/triplea/pull/12353.
