### ISSUE TITLE
Strategic bombing bug fix test doesn't work. 

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#1230]
The problem appears to be that while I can get the unit damage, bombing damage is held somewhere else and I for one can't seem to find it.

Would be nice to tidy up this loose end.

**Comment by ron-murhammer** [comment]
@simon33-2 Can you explain this a little more? Do you have a save game to test it?

**Comment by simon33-2** [comment]
Test in: https://github.com/triplea-game/triplea/blob/master/test/games/strategy/triplea/delegate/StratBombTest.java

Does nothing really. I have tried to get it to work, but had to comment out the lines 113-115 because they fail. It seems that the .getUnitDamage() method doesn't get the bombing damage but I can't see how to get the bombing damage - reading the code, getUnitDamage seems like it is correct but obviously I am missing something.

Is that clear now?

**Comment by simon33-2** [comment]
Re: save game, that is picked up automatically. Do a "gradle test".

**Comment by DanVanAtta** [comment]
Task: fix or remove (or break up into smaller test cases)  https://github.com/triplea-game/triplea/blob/master/test/games/strategy/triplea/delegate/StratBombTest.java

**Comment by DanVanAtta** [comment]
last link is broken, not really clear what needs to be done here. Closing for now. If there is a task to be done, please feel free to re-open.

**Comment by simon33-2** [comment]
Huh? @DanVanAtta 

You keep going on about the "test gap"; much more than the functionality gap to my frustration. The bug fix was for the problem that bombing a territory with multiple facilities allowed you to select a plane which didn't attack the factory (or vice-versa) if an AA gun hit. This was against the rules and led to perverse outcomes like people attacking a facility so they could be reasonably confident of hitting the factory even if there was an AA Gun hitting a plane - just take it on something not attacking the factory. This is against the rules of Axis and Allies.

**Comment by DanVanAtta** [comment]
This issue is about a test you're having trouble with, or about incorrect rules? Feel free to reopen if there is something outstanding. There is not much context in this ticket as to what the exact problem is and what needs to be done.
