### ISSUE TITLE
I'm ready to add my map

### ISSUE THREAD

**Issue by deusexludus** [triplea-game/triplea#12329]
Hi, 

I have a new playable map that I'd like to share with the TripleA community. Please send me an invitation to join my own map team at triplea-maps.

I had submitted a pull request to merge in my new domination mod, but it hasn't been accepted. So I'm requesting instead to be invited to start a new repo. Then I think I will need to create a pull request to update yaml

Here is my local repo
https://github.com/deusexludus/domination

Here was the pull request to merge the changes in
https://github.com/triplea-maps/domination/pull/2

Ref-
Following tutorial from 
**Guide - How to make your map downloadable in TripleA:**
https://docs.google.com/document/d/1FfF7N0srp9QG0_if5D-c1d1Aa1QTttdhxgm1GBh3pI4/edit

Which was found from the stickied forum thread:  **Map Maker Resources**
https://forums.triplea-game.org/topic/918/map-maker-resources?_=1707405304492

**Comment by TheDog-GH** [comment]
@RogerCooper 
Do you know how to help with this?

**Comment by RogerCooper** [comment]
It look to me that it has been committed and I see it in the repository.

Note that in-game downloads are not working.
