### ISSUE TITLE
Minor tweaks to Global 1940 Map

### ISSUE THREAD

**Issue by Stohrm** [triplea-game/triplea#12325]
There are two changes that I would like to see made to the Global 1940 Map.  The first has to do with the island of Malta: it is currently surrounded by sea zone 96; and I'd like to see it be the center of sea zones 94, 95 and 96.  The second has to do with the Gulf of Mexico: it is currently split between the East Coast of North America (sea zone 101) and the east coast of Southeast Mexico (sea Zone 89); I like to see it be a sea zone all its own.
Map changes are not something that I've managed to navigate, yet.  So, sadly, these are not changes I'm able to make on my own.  Plus, it's been a long, long while since I last visited this site/these forums, and I have a lot of catching up to do in that regard.
Last, but not least, this isn't really an "issue" per se: it's just a "wish" and I try not to make too many of those.  If someone can grant it that'd be great.

**Comment by beelee1** [comment]
Hi @Stohrm Black Elk replied to you at the triplea site, so I will close this :)
