### ISSUE TITLE
2.6.14633 whenHitPointsDamagedChangesInto allows unit to move after combat.

### ISSUE THREAD

**Issue by WCSumpton** [triplea-game/triplea#12334]
In 2.6 unit damaged during combat that have "whenHitPointsDamagedChangesInto" and change int the 'damaged' unit are allowed to move after the combat ends and that unit survives. In 2.5 the 'damage' unit is not allowed to move.
[autosaveaftergermanycombatmove.zip](https://github.com/triplea-game/triplea/files/14229555/autosaveaftergermanycombatmove.zip)
Saved game after German combat move. The battle in 23 Sea Zone. Allow the germanBattleShip to take one hit and the unit will change into germanBattleShip-Damaged. At the end of the battle the germanBattleShip-Damage will be able to move 1 space. This should not happen as the parent unit, germanBattleShip used it combatMovement to enter the embattled territory/sea zone.

Cheers...

**Comment by asvitkine** [comment]
So, I can see that in 2.6, the code for handling it is in `TransformDamagedUnitsHistoryChange` and `UnitUtils.translateAttributesToOtherUnits`. The code did change since 2.5.

In 2.5, it's done by `damagedChangeInto()` in `MustFightBattle`, which does call `UnitUtils.translateAttributesToOtherUnits`, but that function looks very different.

However, I would expect somewhere to transfer things like `unit.getWasInCombat()` and `unit.setAlreadyMoved()` but I don't see these...

**Comment by asvitkine** [comment]
Ah, I see this in the 2.5 code:

```
      final String transcriptText =
          MyFormatter.unitsToText(unitsToAdd) + " added in " + battleSite.getName();
      bridge.getHistoryWriter().addChildToEvent(transcriptText, new ArrayList<>(unitsToAdd));
      bridge.addChange(ChangeFactory.addUnits(battleSite, unitsToAdd));
      bridge.addChange(ChangeFactory.markNoMovementChange(unitsToAdd));
```

**Comment by asvitkine** [comment]
I think this broke with https://github.com/triplea-game/triplea/commit/984624aff7ffe53f4ec07014f69190ace47d1c17#diff-c8180939dc6f1dcf57f9df02ebc37d92d5c1f2be23ea2716733f5aa4bbecb394

In the diff, you can see the removal of:

```
 changes.add(
          ChangeFactory.addUnits(battleSite, unitsToAdd),
          ChangeFactory.markNoMovementChange(unitsToAdd));
```

But the replacement code doesn't have that logic.

**Comment by asvitkine** [comment]
One thing I'm not sure about is whether RemoveUnitsHistoryChange which calls TransformDamagedUnitsHistoryChange, should also have the `ChangeFactory.markNoMovementChange()` logic. I *think* the old code for that part didn't. So I can keep that behavior, but I guess I'm not sure the expectation.
