### ISSUE TITLE
2.6.14633 Unit Icon Overlays do not work like in 2.5

### ISSUE THREAD

**Issue by TheDog-GH** [triplea-game/triplea#12333]
@asvitkine @DanVanAtta 

In 2.6 download this map

https://drive.google.com/file/d/1LNUpcqoRW7CYEXSWIdIMaffRglvdJWtZ/view?usp=sharing
or do it from here
https://forums.triplea-game.org/topic/3729/middle-earth-3rd-age-official-thread

This screen shot is from 2.5
![image](https://github.com/triplea-game/triplea/assets/71022517/bbc119e5-dbfa-4931-97ca-c98d6a735fc1)
Note the Ent top right, it has 3 icons overlaid, a crown, a skull, a triangle.  These are overlaid icons from a folder called **unitIcons**
These represent Leader9, Fear5 & Mountaineer abilities in game.

In 2.5 load the game, select Saruman as Human, then navigate to Isengard on the map to see a good selection of Unit Icon Overlays.
In 2.6 you cannot see them.

The above also applies to an old map called TWW, Total World War, but you have to select Tech upgrades to see the Unit Icon Overlays on the map, this will take a few turns to show up.  So best to test with **3rd Age**.

**Comment by WCSumpton** [comment]
[autosaveaftergermanycombatmove.zip](https://github.com/triplea-game/triplea/files/14229524/autosaveaftergermanycombatmove.zip)
TWW where Germany has "Improved Anti-Tank" and the germanAntiTankGun located in Eastern Poland does not show the "green50left.png" for this upgrade.

**Comment by asvitkine** [comment]
How is that configured in the map?

**Comment by asvitkine** [comment]
In 2.5, there was a class named UnitIconProperties.java. This doesn't exist in 2.6. Maybe the feature was removed?

**Comment by asvitkine** [comment]
Indeed, looks it got removed here: https://github.com/triplea-game/triplea/pull/9825

The rationale was that it was unused. I guess not?

We could restore it.

@DanVanAtta WDYT?

**Comment by WCSumpton** [comment]
Unit Icon/Overlays was created for TWW to represent advantages given to units without having to create a new unit image. This could be used in other maps, but most map use the 'New Unit". Maybe an example could be added to PoS2 to show how this process works. The file "unit_icons.properties" does exist, but the example conditions and explanations are not in the xml. 

Cheers...

**Comment by Cernelius** [comment]
Removing functionalities without even asking in forum? Am I missing something?

Anyway, my suggestion is never removing any functionalities without leaving a discussion about it open in forum for at least 1 year (not every map-maker checks forum constantly) and never opening such discussion for any functionalities added less than 5 years ago (giving at least some years for map-makers to use new functionalities).

What other functionalities have been removed like that?

**Comment by Cernelius** [comment]
Though I would agree that "pos2" should be complete as a guide.

I think having added this functionality without having documented it in "pos2" has been sloppy if @WCSumpton is right there is no example in it.

My suggestion (in line with what I just said) is that, if a functionality is found non-used by any maps comprising the_pact_of_steel, a developer should give an ultimatum in forum for anyone to add it to this map and removing the functionality if nobody does it within 1 year thereafter (no matter if the functionality has been added recently).

**Comment by Cernelius** [comment]
Side note, back when I updated World At War with @ron-murhammer, I was actually thinking to use this functionality to display the "red dot" of the "red dot units".

**Comment by Cernelius** [comment]
I've opened a discussion to try to avoid problems like this one in the future:
https://github.com/triplea-game/triplea/discussions/12343

@asvitkine Obviously, this functionality should be restored.

**Comment by TheDog-GH** [comment]
FWIW I found this, it may help with the restore?
https://github.com/triplea-game/triplea/pull/3451

@asvitkine please restore 🙏 😀
