### ISSUE TITLE
Bug: User defined downloadedMaps and savedGames folder do not ...

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#1234]
... show when hitting "Engine Preferences" - "Open User Maps and Savegames Folder",
instead it (3160) shows an error:

> triplea.engine.version.bin:1.9
Loading map: , from: D:\Daten\triplea\downloadedMaps\
java.lang.IllegalArgumentException: **The file: C:\Users\"User"\triplea doesn't exist.**
	at java.awt.Desktop.checkFileValidation(Unknown Source)
	at java.awt.Desktop.open(Unknown Source)
	at games.strategy.net.OpenFileUtility.openFile(OpenFileUtility.java:24)
	at....

My user defined folders are on Partition D:\Daten\triplea\...

**Comment by DanVanAtta** [comment]
What happens when you go to the game settings window, what's the path for save and downloaded games?

**Comment by panther2** [comment]
They are saved (and used) as defined.

**Comment by DanVanAtta** [comment]
How are they defined? 
Does the path listed in the game engine settings window match the one in the error message above?
You're able to save games at all?


I've never been fond of this behavior, but the game engine has a hardcoded path to "triplea" off of your users folder. Seems like that hardcoding is running into trouble..

**Comment by panther2** [comment]
Yes exactly. 
Maps are saved in D:\Daten\triplea\downloadedMaps\
Savegames are saved in D:\Daten\triplea\savedGames\

Everything works as expected except the call of the "Open User Maps and Savegames Folder" from the Engine Preferences.

**Comment by DanVanAtta** [comment]
Took a look, seems like it should be pulling from the right location. But, this button has no real purpose anymore now that the same locations are given in the settings window. Easiest fix is to remove it.

**Comment by panther2** [comment]
Removed and closed.
