### ISSUE TITLE
Map version update causes new Engine release?

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#1239]
I just noticed that (only) the update of the WaW map version from 1.0 to 1.1 ( #1238 ) caused a new TripleA-release (3168). Is this intended - is this necessary?

I wonder because I successfully download the new map version (1.1) with my installed 3164-version.
The triplea_maps.yaml is not part of the map-download, is it?
So every map update triggers a new release?

**Comment by DanVanAtta** [comment]
Yes, which then drops the map yaml in to the webpage repo, which would then rebuild the data used for the maps webpage. https://github.com/triplea-game/triplea-game.github.io/issues/33

**Comment by panther2** [comment]
Thanks for the explanation. Issue closed,

**Comment by DanVanAtta** [comment]
Grant it, the whole brand new installer is wasteful since the maps yaml is not part of the game. In part we are piggy-backing on the build automation to wire in the website. FYI: the build also validates the triplea-maps.yaml file now as well, so we are less likely to break it.

**Comment by panther2** [comment]
That is what I thought, thanks.

**Comment by panther2** [comment]
Now closed.
