### ISSUE TITLE
Please update port forwarding instructions

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#124]
Please attach this sample configuration to the port forwarding page (http://tripleadev.1671093.n2.nabble.com/Download-Maps-Links-Hosting-Games-General-Information-td4074312.html#a4085700):

![port_forwarding_config](https://cloud.githubusercontent.com/assets/12397753/9509238/1f7fbbc4-4c12-11e5-824b-93a7ec648d5a.png)

Port forwarding clearly is tricky, and given very few games are hosted by non-bots in the lobby I think most do not have it correct. I for one did not, I did not put 0's for the external IP address for a long time and had issues.

The screenshot of the configuration (and maybe getting more screenshots from other routers) could help. Plus a small text saying that this opens 10 ports, 3300 through 3310.

**Comment by DanVanAtta** [comment]
Any disagreement to leave updates to the help documentation for the website? In which case this can be closed. 

The thread post on how to set up hosting in the SF forums has other broken images, so perhaps it is better to begin the deprecation of the SF help documentation in favor of getting good documentation on the website.

**Comment by veqryn** [comment]
the first row, with the 0.0.0.0, should not be necessary to port forward.  i think that might be something particular to your own setup (and the fact that there are so many particulars when it comes to port forwarding, is why lots of people can't do it easily)
