### ISSUE TITLE
Non-Existent AA Gun Rolled Snake Eyes

### ISSUE THREAD

**Issue by junk4** [triplea-game/triplea#12410]
Just playing vs AI for a bit of practice and did a bombing raid from Germany to Moscow Rd 2 with 2 bombers, the Soviets moved the Moscow AA battery to West Russia Rd 1 and I destroyed it while capturing the tile. As you can see in the attached pictures there is no AA gun in Moscow and both of my bombers were shot down. 

Thanks for your time and I hope this helps

![After Raid](https://github.com/triplea-game/triplea/assets/162606493/2e56dcf2-f6d9-4ed5-8d75-a8f630b7979f)
![Combat Result](https://github.com/triplea-game/triplea/assets/162606493/630f9e31-861d-4648-8e8c-677bb6e034ce)

**Comment by TheDog-GH** [comment]
Hi Junk4, I dont think this is a TripleA map, is it Allies & Axis online?

**Comment by beelee1** [comment]
yea it looks like beamdogs. Try posting here https://www.axisandallies.org/forums/category/68/axis-allies-1942-online
