### ISSUE TITLE
2.6 Download Map panel, the Map tab has 3 sorted states - should only have 2 ?

### ISSUE THREAD

**Issue by TheDog-GH** [triplea-game/triplea#12446]
On the Download Map panel, the Map tab has 3 sorted states;

default where it lists **Map** - numbers, **uppercase, lowercase** (123ABCabc)
click sort once, **Map ^** ........- numbers, **ignore case** (123AaBbCc)
click sort again, **Map v** .......- **ignore case**, numbers (cCbBaA321)

It would be better to reduce confusion and just remove the first state and go straight to **Map v** ?

Also are the pointers correct, shouldn't they be swapped to?
**Map v** ........- numbers, **ignore case** (123AaBbCc)

**Comment by asvitkine** [comment]
The arrows are correct, ▲ mean sort ascending (so A -> Z etc).
