### ISSUE TITLE
Downloadable Map Mods are Dead

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1246]
Options:
- consolidate stand-alone mods back together to their base map.
- continue hacking at the resource paths. Not preferred since stand-alone mods hacked together to begin with.
- roll back. Not great option since effort to roll back completely is greater than either fix. We also would lose the ability to work on a map in a format that you can also upload it in.

First option is looking pretty attractive, the standalone map mod feature never was properly supported.

Background: https://github.com/triplea-game/triplea/issues/1244

**Comment by ron-murhammer** [comment]
@DanVanAtta Not sure exactly what you wanna discuss here differently from #1247. I think its pretty much the same conversation and I laid out my thoughts in the other thread. Maybe this is to discuss just the short term solution for 1.9?

If so I'd still go with option 4:
- Copy necessary map assets into the variants zips

**Comment by DanVanAtta** [comment]
I was thinking this was going to be specific to the problem at hand, while #1247 would be for a more generic solution. We can perhaps talk about both in the same thread.
