### ISSUE TITLE
Mapskins Are In Game Wrongly Named (1.9.0.0.3183)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#1249]
They are named with the name of the original map; instead, they should be named with the added name of the skin.

For example:

View/Map Skins/napoleonic_empire

is wrong, and should be:

View/Map Skins/political_map_skin

This is particularly relevant, because maps can have more than 1 not original skin installed (example: new_world_order). I case of multiple skins installed for a map, only one of them is currently available.

This bug is not present in 1.8.0.9.

**Comment by Cernelius** [comment]
Also, minor note, I believe the map name should be "**napoleonic_empires**", not "napoleonic_empire", both for the original and the mapskin, but it was indeed "Napoleonic_Empire", at least since the current release, while the info name is and was "Napoleonic Empires", instead.

**Comment by ron-murhammer** [comment]
Confirmed that this is a bug.

**Comment by Cernelius** [comment]
Also, a thing I just remembered, is that in the release, as far as I know (no code knowledge), the "-" symbol alone in the folder's name was meant to identify mapskins (I'm sure that only mapskins were allowed having it).

Thus, if I'm right, a folder called "napoleonic_empire-master" would have been seen as a mapskin for "napoleonic_empire" called as "master". Then, you would have seen "View/Map Skins/master", to load it.

Just a warning (I guess already known), in case the addition of the "-master" part might conflict with the past use of "-", as the exclusive mean to identify mapskins (what was before the "-" was the name of the referring original skin, what was after the "-" was the name of that alternative skin for it).

**Comment by ron-murhammer** [comment]
Fixed in #1321

**Comment by Cernelius** [comment]
The naming is now correct, but mapskins are still limited to one per original map; refer to:
https://github.com/triplea-game/triplea/issues/1323
