### ISSUE TITLE
Stuck In Russian Combat Move

### ISSUE THREAD

**Issue by JaydenBarker72** [triplea-game/triplea#12490]
I passed my turn to the AI, they made all their moves, but the game didn't conduct any combat and is now stuck in the Russian turn waiting for the Russian AI to place units but combat hasn't even been resolved yet

**Comment by beelee1** [comment]
Hi Jayden 

What game are you playing ? Which triplea version ? The AI will take several minutes sometimes on a large map with lots of units before it moves.

**Comment by JaydenBarker72** [comment]
I figured it out, I had to save the game and leave then re enter it, fixed
the problem!

Thanks!

**Comment by beelee1** [comment]
Right on. Will close
