### ISSUE TITLE
github io for website?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#125]
Website came up a few times. There was a website builder company that offers free service, i checked them out and was not wowed. github.io I think would be a good tool. It allows us to modify source code quite directly and easily and we can get up and running quickly.

As motivation for example, this page would be lovely as sections on a website with links to index the sub-topics: http://tripleadev.1671093.n2.nabble.com/Download-Maps-Links-Hosting-Games-General-Information-td4074312.html

How excited are people by using github io? The URL would be: http://triplea-game.github.io/, the source code would live in a second repository that would serve as the web root. 

For an example, see: http://danvanatta.github.io/, and https://github.com/DanVanAtta/DanVanAtta.github.io

**Comment by ron-murhammer** [comment]
So I think there is a lot of interest in improvement/consolidation for TripleA websites. Zjelco from the dev forum has been looking into options. I'm not sure what the best solution is but I think it would be nice to have a better home page then: http://triplea.sourceforge.net/. It would also be nice to consolidate information into one website as having a separate warclub website/forum from the sourceforge tends to lead to confusion and divided community.

Here is a snippet from a post I made a while back that captures my thoughts on trying to make the website as sort of a starting point and hub for TripleA:
 "So the best solution if we had the manpower to both do it and maintain it would be to create a website (like tripleawarclub.org) where we could have or link to all these various functions. To me it would seem better to combine all these things with tripleA war club into a single site where people would come to download tripleA, chat in forums, play games, have a wiki, report bugs, and contribute. This would help reduce confusion and centralize all of the functions around TripleA."

**Comment by gaborbernat** [comment]
I for one would approve :)

Bernát GÁBOR

**Comment by DanVanAtta** [comment]
Closing, I'm trying to find others on the source forge forum that can contribute. With a working group we'll look at forming a plan.
