### ISSUE TITLE
Unit Size Different In Bottom Bar and Windows with Zoom in 2.6

### ISSUE THREAD

**Issue by beelee1** [triplea-game/triplea#12500]
### Reproduction Steps

1.
2.
3.

### Engine Version

Engine Version:

### Is there anything else we should know?

This is didcussed in the forum here https://forums.triplea-game.org/topic/2999/2-6-release-getting-close-need-volunteers-to-help-beta-test-2-6/113

Edit
Added to Problem Tracker under Triage. Probably should be under "Fix Sooner"

Changed to Fix Sooner

**Comment by Cernelius** [comment]
Was this an intended change (like someone thinking that the unit zoom is to be applied generally for some reasons) or not?

Anyway, bad change, in my opinion.

**Comment by Cernelius** [comment]
The only argument in favour of the new behaviour (of which I can think) is for the territory tab showing all units as many non-zoomed units may exceed the vertical space of the territory tab itself especially for less-than-full HD screens. Still, I would have zoom 100% there (as it used to be) or maybe just enough zoom to make them fit vertically, although the fact that they now show in bottom bar too somewhat reduces the importance of such a tab and conversely promotes what would be its unicity in showing the units non-zoomed if such previous behaviour would be restored.
