### ISSUE TITLE
Program freezes when trying to remove a map...

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#1250]
... using the ingame downloader.

To reproduce just use the ingame downloader, go to Installed Maps, choose a map and hit "Remove".

TripleA has to be killed manually via the Task Manager then.

Noticed with version 3183.

**Comment by ron-murhammer** [comment]
Confirmed bug and happens seemingly every time you try to remove a map.

**Comment by DanVanAtta** [comment]
https://github.com/triplea-game/triplea/pull/1254 should fix the problem.

It's a bit fun what is going on.

Download Maps window was set to 'always on top' to avoid it opening behind the main window.

On remove, there is a confirmation dialog. When the confirmation dialog is open, it is modal relative to it's parent window, and is the only thing you can click. This disables the ability to move the download window. On windows, it appears the 'always on top' is really respected to a T, and the download maps window stays on top of the confirmation dialog. This then creates  nice catch 22, to close the dialog you would have to move the window to see it, and to move the window you have to hit 'ok' in the dialog which you cannot see.

**Comment by panther2** [comment]
Sounds funny indeed.

But: Hitting 'enter' removes the map, but the program "keeps frozen".
I can't do anything then except killing the task.

**Comment by DanVanAtta** [comment]
hmm, maybe the window is not getting focus.
Latest build should be out in about 5 minutes, give that a try if you would. Should be fixed now that #1254 is merged.

**Comment by panther2** [comment]
Ok now, I can confirm it works now. Thanks. Issue closed.

**Comment by DanVanAtta** [comment]
good to hear. @panther2 , realized the behavior you saw was that the first 'return' was for the confirm remove map dialog, then the game has as second popup with the results of the removal.

**Comment by panther2** [comment]
Ah ok, I see.
