### ISSUE TITLE
Ingame downloader leaves a file in "temp", every time it is used

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#1251]
Every time the ingame downloader has been used, it leaves a file (88kb) in 
C:\Users\"User"\AppData\Local\Temp

This file will not be deleted when closing TripleA, so as time goes by, the collection of files constantly increases. 

Example:

[triplea6182787432272437484tmp.txt](https://github.com/triplea-game/triplea/files/484512/triplea6182787432272437484tmp.txt)

Note: The extension .txt has been added by me.

It appears to be a copy of the triplea_maps.yaml .

I am using 3183, but this issue has started before.

**Comment by DanVanAtta** [comment]
The download from URL library is a bit not smart and downloads URLs to a file, then it reads the file to get the data in memory. The system does not need to create this file at all.  https://github.com/triplea-game/triplea/blob/master/src/games/strategy/engine/framework/map/download/DownloadRunnable.java

Bandaid is to mark this file as delete on close. An alternative and more substantive fix is to read URL contents directly into memory.
