### ISSUE TITLE
Case Change Autoremoval Fails For Download (1.9.0.0.3183)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#1252]
In this code change (world_at_war/Code/Rename Land Territories):
https://github.com/triplea-maps/world_at_war/commit/4d91397831a1dd0e57d0be8f8cccd5813e9becd5

All "factory_hit" have been changed to "Factory_hit".

Yet, when you download the map, you get both "Factory_hit" and "factory_hit" (at least I do). "factory_hit" should not be there.

Zips are always case sensitive, but Windows systems are not. Thus, if you unzip the master-map folder, one of the two has to go.

I believe (but I can't be sure) this may be the reason why this bug was reintroduced, as I distinctively remember I corrected it, already, previously (I guessed it was me thinking that I had, while I hadn't, and I can't be sure about that).

Each time a new release was made by redrum, in the world_at_war repository, I restarted working from that one.

I can't be sure, but I believe this issue may cause old case corrections being reintroduced, when downloading and working on a map that had them already corrected.

This is not happening for the "marine" changed to "Marine", but I believe this is because "marine" appears to have been wholly erased from history. If you look at the first "map" folder commit, you can see that there is no "marine" nor "Marine" at all (while there should be "marine"):
https://github.com/triplea-maps/world_at_war/tree/674ebfe7858fa85b4bac7513cc9a9f3e2d00984d/map/units/Americans

And "marine" (as well as "Marine") is missing even at the point immediately before the change to "Marine":
https://github.com/triplea-maps/world_at_war/tree/81fc25b752ff61fe254401ed07b79be3c3cf440d/map/units/Americans

Thus, in order to correct this bug, you might need to totally erase "factory_hit" from history, like it seems it happened for "marine" (which now downloads fine, as only "Marine").

**Comment by ron-murhammer** [comment]
@Cernelius Yeah, git doesn't handle case-sensitivity that well. You usually need to explicitly remove the old case files and I didn't notice them. I removed them now in this commit so the latest zip shouldn't have them now: https://github.com/triplea-maps/world_at_war/commit/bdb7c4e6f79ff6128603fba94324eff4bfa11d83

**Comment by Cernelius** [comment]
Yes, but now, just as the "marine", "factory_hit" has totally disappeared from history.

So, you may want to keep track of this, because this means that whatever case changes destroy the ability to go back getting the actual old version of the map and likely makes it unplayable.

Example, I make a map calling (both in the xml and in units, thus not a bug) the units as "sergeants"; then, I decide, to go for "Sergeants", instead; the result would be that, for cleaning the current from such issues, I make the previous versions unplayable; in this case, it would rather make more sense to delete the repository as a whole, and restarting fresh, than having a repository with a bugged history (I'm surely not suggesting to do this in this case).

Also, I can easily see such things happening again (mapmakers making case changes), and mapmakers not getting what they need to do. This is why this title doesn't refer to world_at_war specifically.

**Comment by ron-murhammer** [comment]
@Cernelius The old files are still in the history of the repo and you could restore them or go back to that version. Here is the code base before the commit I made and you can see both version of 'factory_hit' in the Americans unit folder: https://github.com/triplea-maps/world_at_war/tree/cc1684599d67c0f7ddb42ecb8bfb63509b24339f/map/units/Americans

**Comment by Cernelius** [comment]
Ok, not totally, then, but if you "Browse the repository" at whatever point in history before the code change adding "Factory_hit", you can't see any "factory_hit" nor "Factory_hit" anymore. Is this of no relevance?

This is the commit just before the Rename Land Territories (that added the "Factory_hit"), lacking displaying any "factory_hit" or "Factory_hit" for Americans:
https://github.com/triplea-maps/world_at_war/tree/72a4fb845d381ddd657e9ad764d38cddec71a2dd/map/units/Americans

On the other hand, if I download the version 2.0 (the first of the ones I collaborated in the making) from here:
https://github.com/triplea-maps/world_at_war/releases/tag/0.6

There is "marine", but not "Marine", and there is "factory_hit", but not "Factory_hit", as it should be.

So, yes, it seems that the history is just fine, as a matter of what you download; the bug appears to be there only when browsing.

Still, there is anyway the issue that mapmakers not knowing this issue can hit this problem and maybe not even notice.

But if you think it can be called, feel free to close; nothing more to say.
