### ISSUE TITLE
No Welcome Message in Lobby

### ISSUE THREAD

**Issue by beelee1** [triplea-game/triplea#12566]
### Reproduction Steps

1.
2.
3.

### Engine Version

Engine Version:

### Is there anything else we should know?

There used to be one that said something similar to 

"Welcome to Triplea !"
"No Discussing Politics"
"Have Fun Gaming !"

**Comment by Cernelius** [comment]
I do not see the problem using 2.6.14737.

**Comment by DanVanAtta** [comment]
I suspect this issue was fixed in: https://github.com/triplea-game/triplea/commit/36af04011ba55439a61a4cb83284683ac170a740
