### ISSUE TITLE
Damage to captured infrastructure feature

### ISSUE THREAD

**Issue by FrostionAAA** [triplea-game/triplea#1257]
Would it be possible to add a new feature in TripleA that allowed “isInfrastructure” to be damaged upon capture?

It would seem logical that the losing side who is losing control of a huge industrial production capability, a factory, airfield or harbor would want to sabotage the facility before it falls into enemy hands. Or that it just gets battle damaged in the fighting. Thereby forcing the enemy to fix and use resources if they want to use the facility at full capacity, if the infrastructure even survives. The destroyedWhenCaptured features seem a bit extreme and unrealistic in some cases.
The feature would open up some possibilities for future maps and mods.

Maybe something like this, or some other solution?: (Highlighted with thick black)

_attachment name="unitAttachment" attachTo="Factory" javaClass="games.strategy.triplea.attachments.UnitAttachment" type="unitType"
   option name="isFactory" value="true"/
   option name="canProduceXUnits" value="10"/
   option name="constructionType" value="Factory"/
   option name="canBeDamaged" value="true"/
   option name="maxDamage" value="10"/
   option name="canDieFromReachingMaxDamage" value="true"/
   **option name="whenCapturedDamage" value="5"/**
/attachment_

**Comment by DanVanAtta** [comment]
Interesting, might not be that difficult to do.  In the example highlight, should it be a min damage function, or an add damage function? Ie: if a building is at 7 damage, does it go to 10 damage, or stay at 7 since 5<7. another example, a building with 4 damage would go to 9, or would it go to 5?

In that case perhaps the option might be named: 'addDamageWhenCaptured'

**Comment by FrostionAAA** [comment]
I had not really thought that long as I figured that other people might have some opinions. But the “addDamageWhenCaptured” sounds good. (Building keeps any already damage and gets some extra damage on top.)

Maybe, to open up other possibilities for mapmakers and units that are to be captured, there should also be a “when this unit is captured it will have this fixed amount of damage no matter what” option? I can imagine some units being designed in a way where the map maker wants them to be “disabled” or have have only 1 damadge point left when captured. Like if they have two infrastructure damage points and they would need fixing if captured. Or a unit that can only produce 1 unit every turn and if captured is disabled until fixing. A unit like that might have only two conditions; undamaged and 1 damage.

Anyway the more options the better :-)

**Comment by FrostionAAA** [comment]
Maybe names could be "addDamageWhenCaptured" and "setDamageWhenCaptured"?
