### ISSUE TITLE
Deleted maps still show up in list

### ISSUE THREAD

**Issue by VictoryFirst2** [triplea-game/triplea#12574]
When you download a map from TripleA, sometimes you get multiple games in the folder. For example, World War II Global comes with a module of 1st edition, 2nd edition, as well as variants with Combat-Move first. I never play these other games, so I deleted them from the games folder that's inside the folder World War II global.
![image](https://github.com/triplea-game/triplea/assets/101500879/efd64c9d-c0ad-4977-b80e-f3a4e1b5ee40)

However, those other games still show up in TripleA when you click on Select Game:
![image](https://github.com/triplea-game/triplea/assets/101500879/c3d970be-5e65-4b3f-a1e0-b04efe5b37ab)

This is with other maps too. How do I delete these from the list?

**Comment by VictoryFirst2** [comment]
2.614741

**Comment by WCSumpton** [comment]
The 'Select Game' reads the information contained in the map.yml file. To remove the games from the listing the map.yml should be edited. You do not need to remove the xml/html files for the game folder. This should be a user operation, since the user is the one that removed the xml/html files. 

Cheers...

**Comment by VictoryFirst2** [comment]
I edited the file you mentioned and it worked! The games don't show up anymore in the list. I did not know this before, so thank you very much!

**Comment by Cernelius** [comment]
Yeah, in 2.5 you had to delete the game-files, in 2.6 what @WCSumpton said.

That is why you should always clarify the version.
