### ISSUE TITLE
Download Maps window appears "behind" TripleA-window (1.9.0.0.3199)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#1260]
Same as:
https://github.com/triplea-game/triplea/issues/1147

**Comment by Cernelius** [comment]
I guess this is intended ( https://github.com/triplea-game/triplea/pull/1254 ), but since it is an arguably annoying behaviour, I would keep the issue opened, if not solved for the release.

**Comment by DanVanAtta** [comment]
Hopefully the migration to JavaFx for UI components will help solve this. So far each attempt to solve it in Swing has traded one problem for another.

**Comment by DanVanAtta** [comment]
Hopefully the switch to JavaFx will help solve this. Each attempt to solve it in Swing so far has traded one problem for another.

**Comment by Cernelius** [comment]
If nothing else works, I'd rather have it on top and get rid of the confirmation pop-up for removing. Since you can redownload, in case, I don't think that's a big deal.
