### ISSUE TITLE
Error on combat move

### ISSUE THREAD

**Issue by ErikWenslaffUWM** [triplea-game/triplea#12611]
When placing a unit into hostile territory during combat movement, I immediately get this error:

> (2:34:03 AM) Bot604_California:  SEVERE: Unrecognized error occurred. If this is a repeatable error, please make a copy of this savegame and report to:
> (2:34:03 AM) Bot604_California:  https://github.com/triplea-game/triplea/issues/new
> (2:34:03 AM) Bot604_California:  java.lang.RuntimeException: Exception on remote
> (2:34:03 AM) Bot604_California:  	at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:58)
> (2:34:03 AM) Bot604_California:  	at games.strategy.engine.framework.$Proxy32.startPlayerStep(Unknown Source)
> (2:34:03 AM) Bot604_California:  	at games.strategy.engine.framework.ServerGame.waitForPlayerToFinishStep(ServerGame.java:544)
> (2:34:03 AM) Bot604_California:  	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:407)
> (2:34:03 AM) Bot604_California:  	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:297)
> (2:34:03 AM) Bot604_California:  	at games.strategy.engine.framework.startup.launcher.ServerLauncher.launchInternal(ServerLauncher.java:173)
> (2:34:03 AM) Bot604_California:  	at java.base/java.lang.Thread.run(Thread.java:829)
> (2:34:03 AM) Bot604_California:  Caused by: java.lang.RuntimeException: Exception on remote
> (2:34:03 AM) Bot604_California:  	at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:57)
> (2:34:03 AM) Bot604_California:  	at com.sun.proxy.$Proxy15.performMove(Unknown Source)
> (2:34:03 AM) Bot604_California:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> (2:34:03 AM) Bot604_California:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> (2:34:03 AM) Bot604_California:  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> (2:34:03 AM) Bot604_California:  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> (2:34:03 AM) Bot604_California:  	at games.strategy.engine.player.PlayerBridge$GameOverInvocationHandler.invoke(PlayerBridge.java:154)
> (2:34:03 AM) Bot604_California:  	at com.sun.proxy.$Proxy15.performMove(Unknown Source)

**Comment by ErikWenslaffUWM** [comment]
Game: World War II Global 1940 2nd Edition

TripleA version: 2.6

Game-save: Unfortunately whenever I tried to save it, it would reload the save on the bot to the previous loaded save. I tried multiple times, but every time it did this, even on different bots.

Steps to reproduce: 

1. Load the map fresh on the bot (World War II Global 1940 2nd Edition
2. Do not change any of the default game options
3. Choose axis, have another player take every other nation (allies + neutrals, dutch...)
4. Proceed with game until you hit combat moves phase for Germany turn 1
5. Move any unit into a hostile territory

At that point, the game will immediately crash throwing the error above

**Comment by beelee1** [comment]
Hi Erik

What OS are you on and what is the exact 2.6 you are using ?

**Comment by asvitkine** [comment]
@ErikWenslaffUWM do you get the error when you try it solo without a bot?

**Comment by DanVanAtta** [comment]
This is fixed somewhat recently.

The problem is a 2.6 game playing against 2.5. It was previously thought that would be okay - but no, it's not and leads to the 
error posted.

The fix, 2.6 game clients now connect to a 2.6 lobby that has 2.6 bots. This creates a somewhat strong partition between 2.5 and 2.6 game clients and should avoid the problem going forward.
