### ISSUE TITLE
Retreat rule not always implemented correctly

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#1270]
Originally reported in:
https://github.com/triplea-maps/world_war_ii_global/issues/12

TripleA should not offer the attacker's option to retreat, if after a round of combat:
- in a seazone only a "defending" Transport is left
- in a territory only a "defending" AAA gun is left
- in a seazone only attacking air units are left as well as only a "defending" Submarine.

If these scenarios occur, the battle is over:
- the Transport is autodestroyed, given the attacker still has units with an attack value.
- the AAA gun is autodestroyed.
- the Submarine cannot be hit by air units

**Comment by simon33-2** [comment]
The transport one could be fixed by moving the position of the test for transport are removed to the end of the combat - before the retreat option is presented. Similar treatment for AAA.

**Comment by simon33-2** [comment]
The sub one would be fixed by making the sub auto submerge before asking them if they want to submerge. at the moment you are asked if you want to submerge and if you don't, the auto submerge happens anyway. Pretty stupid.

**Comment by panther2** [comment]
Thank you, @simon33-2 for working on this!

**Comment by simon33-2** [comment]
Don't thank me yet. The change hasn't been merged!

**Comment by DanVanAtta** [comment]
I see #1646 is merged, @simon33-2 thank you!  Question: is this issue closed or are there any loose ends that should still be tracked?

**Comment by simon33-2** [comment]
The third scenario of a sub against only air still needs resolution although this requires an incompatible release to fix the order in MustFightBattle, unless we come up with a dodgy work around.

**Comment by simon33-2** [comment]
Oh hold on - the first two issues are also still problems because the change was reverted in #1953.

#2080 resolves all known issues but hasn't been merged.

**Comment by panther2** [comment]
@simon33-2 @DanVanAtta 
I have tested the issues mentioned in the first posting using 6604 and wwII-global.
Generally they are resolved correctly.
Unfortunately there is one remaining issue:
In the attached savegame the Russian transport is removed incorrectly from SZ 115.
In the sea battle the hits were assigned to the cruisers leaving the German carrier and the Russian transport behind. As the carrier has no attack value the battle should have ended with both ships remaining there. But the Russian transport disappeared.

[test3_incorrect.zip](https://github.com/triplea-game/triplea/files/1304214/test3_incorrect.zip)

**Comment by simon33-2** [comment]
Bummer! I'll look at that over the weekend.

**Comment by panther2** [comment]
Thank you, @simon33-2 

While there, please look at another scenario, too:

[test4_incorrect.zip](https://github.com/triplea-game/triplea/files/1305496/test4_incorrect.zip)

Here a German cruiser and transport attack a Russian cruiser and transport.
Both cruisers hit, so the transports survive. In this special case the rulebook says:

> In a sea battle, **if both sides have only transports remaining**, the attacker’s transports can remain in the contested sea zone or retreat per the rules in Condition B below, if possible.

TripleA does not offer the retreat option.

**Comment by simon33-2** [comment]
That rule is a bit daft isn't it? If a transport is in an attack, it's either doing an amphibious assault or started in a hostile sea zone. In either case, I don't see why you should have the option to retreat. Is it the same in other variants?

**Comment by simon33-2** [comment]
@panther2 what platform do you use? Windows, is it 32 or 64 bit?

I have a fix for test3  - was using the defense power.

**Comment by simon33-2** [comment]
[mac.zip](https://github.com/triplea-game/triplea/files/1308018/mac.zip)
[unix.zip](https://github.com/triplea-game/triplea/files/1308019/unix.zip)
[win32.zip](https://github.com/triplea-game/triplea/files/1308021/win32.zip)
[win64.zip](https://github.com/triplea-game/triplea/files/1308020/win64.zip)

I decided to attach installers for all platforms. Are there any other cases I've missed?

**Comment by simon33-2** [comment]
I've tested your test4 scenario in versions back to 1.8 and this scenario has never been implemented as per the rulebook. I can't get excited about it.

**Comment by panther2** [comment]
Thank you @simon33-2 . I will run the test3 sceanrio soon using the latest TripleA-pre-release.

Concerning the test4-scenario:

>  Is it the same in other variants?

Yes, at least in v3, v4, v5, v6 and Global (not having checked older versions, though).

**Comment by panther2** [comment]
Anyway, this issue is different from the initial one (retreat options were incorrectly offered), so I am closing this issue and open a new one for the new scenario (here a retreat option is incorrectly **not** offered).
