### ISSUE TITLE
2.6.14785 Hard-AI (but not Fast-AI) freezes 

### ISSUE THREAD

**Issue by TheDog-GH** [triplea-game/triplea#12720]
Might be due to Subs submerging or Scrambling?

Tested with 1941 GCD v170 & (175 unreleased)

Note it only happens with **Hard-AI** (but not Fast-AI)

https://forums.triplea-game.org/topic/3326/1941-global-command-decision-official-thread/677?page=34
to the bottom of the page

There is a saved game in this post
https://forums.triplea-game.org/topic/3326/1941-global-command-decision-official-thread/678?page=34
Linked here
https://forums.triplea-game.org/assets/uploads/files/1720752241996-g1.tsvg

@asvitkine (One for you?)

**Comment by asvitkine** [comment]
Looks like AaCasualtySelector.findRandomTargets() infinite loops.
