### ISSUE TITLE
Triple A Error

### ISSUE THREAD

**Issue by Desp3456** [triplea-game/triplea#12721]
![Screenshot 2024-07-13 123015](https://github.com/user-attachments/assets/c4e921bf-dea3-429b-80d6-2245a4f68d51)

Trying to load a saved game of TripleA and receiving the following message (also see attached):

This Save was made by a newer version of TripleA. To load this save, download the latest version of TripleA:
If this problem happens frequently and is something you cannot fix, please report to TripleA.

I updated TripleA and it still didn't work. Then I uninstalled TripleA and reinstalled it to verify I'm on the latest version - still receiving the error.

Thanks!

**Comment by WCSumpton** [comment]
The save may have been made with pre-release 2.6+, which cannot be loaded into 2.5. Try downloading the [2.6+](https://github.com/triplea-game/triplea/releases/) and see if that helps. (Select "Assets" to see the download packages.)

Cheers...

**Comment by Desp3456** [comment]
That worked, thanks!
