### ISSUE TITLE
Broken Mods And MapSkins Caused By world_at_war Updates

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#1272]
Due to the world_at_war updates, starting from:
https://github.com/triplea-maps/world_at_war/releases/tag/0.6

the following two repositories are not anymore functional:
https://github.com/triplea-maps/world_at_war_pbem
https://github.com/triplea-maps/world_at_war-skin_sneak

I suggest somehow flagging them as obsolete (up until anyone will update them).
The easiest solution to put them back working would be to have them being stand-alone, with the latest compatible assets pasted accordingly, but I advise against it, as this would resume the old waw at a different place, being a variant of something obsolete and nor regularly downloadable, which I don't believe would be sensible.

At least world_at_war_pbem is also broken due to what explained at:
https://github.com/triplea-game/triplea/issues/1271

I've tested that the first release of the mod is functional for 1.8.0.9.

**Comment by ron-murhammer** [comment]
@Cernelius My recommendation would be to create an issue under each of those repos saying they need updated to be compatible with the latest WaW. We will remove any references from the downloads in-game menu to them until they are fixed.

**Comment by Cernelius** [comment]
Well, if I open an issue it is just me pointing out that issue, that may or may not be true. I guess better than nothing.
If there is no official way to flag something as obsolete or broken, I guess you can just leave them alone; myself, I don't care.
Or maybe this should be done in "Projects"? Since not everyone have permission to create new projects, that may be a good way to track officially confirmed issues?
Or having an official list of broken / obsolete map folders centralised somewhere?
Anyway, if anything, I'll leave you doing it, since you did the updates that made these other repositories obsolete for the latest world_at_war one.
Removing from download list seems not required, as both this collection of external mods and this mapskin are not present in either the 1.8.0.9 release download list, nor in the latest prerelease download list, or at least I didn't see them.
I also wanted to take a look at how much downloaded these folders are, but I can't find them in sourceforge:
https://sourceforge.net/projects/tripleamaps/files/maps/
Where did these folders come from?
I believe they were made by sneakingcoward (almost sure, especially for the mapskin called "skin_sneak").
The mod seems oriented for pbem, so I don't know if there is a good way to tell how much played it is (I don't remember having ever seen it hosted in lobby).
The mapskin might have been made at least partially redundant in its purposes by the world_at_war updates, but I imagine this would be highly subjective.
I'm fine with just closing this doing nothing; your call. I seem to remember other maps were removed from download list because they were broken; I don't know if there is a procedure for tracking such cases. If there is not at all, then I guess better doing nothing in this case too. If there is, then better proceed the same way, whatever it is (I don't know).

**Comment by Cernelius** [comment]
I just noticed that we indeed have a way of tracking outdated maps, and it is:

https://github.com/triplea-game/triplea/wiki/Broken-Maps

So I updated adding:

https://github.com/triplea-maps/world_at_war_pbem
https://github.com/triplea-maps/world_at_war-skin_sneak

For me this issue can now be closed.

**Comment by sneakingcoward** [comment]
this 2 maps are mine and will be updated by me.
