### ISSUE TITLE
Missing space in ”about” (map) window

### ISSUE THREAD

**Issue by FrostionAAA** [triplea-game/triplea#1274]
This is a tiny flaw, but still a flaw I think and maybe easy to fix?
Where is this missing space? See the white arrow, and it is like this no matter what map is chosen:
![unavngivet](https://cloud.githubusercontent.com/assets/15268177/19022494/177e0236-88da-11e6-8a53-f10efe170201.png)

**Comment by ron-murhammer** [comment]
Fixed: #1275
