### ISSUE TITLE
"Show Chat History" Is Blank (2.7.14825)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#12779]
Clicking on "Show Chat History" always returns no history even when somebody recently used the chat.

If this feature was removed, I see no reason to leave it blank instead of actually removing the feature altogether.

**Comment by DanVanAtta** [comment]
Yeah, that functionality should be removed. It's querying database to fetch chat records, and chat records from games is no longer uploaded to database.

**Comment by DanVanAtta** [comment]
I believe this all has been removed now.
