### ISSUE TITLE
Clarify the Difference between "Reset" and "Reset to Default" in "Settings" (2.7.14825)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#12777]
I assume that clicking on "Reset to Default" will return the "Settings" to their default values, but I don't know what would happen if I click on "Reset" instead (and how that is different from either "Save" or "Reset to Default").

I don't want to test it because I don't want to lose everything which I've customized in "Settings".

Regardless, whatever the difference is, I'm arguing that me not understanding it may mean that there is a substantial lack of clarity, which is the actual problem at this issue.

**Comment by DanVanAtta** [comment]
Reset IIRC removes any 'unsaved' changes. A better tooltip or removing the button would be good moves.

**Comment by Cernelius** [comment]
> Reset IIRC removes any 'unsaved' changes.

Then I would rename it to "Reset to Saved" or remove the button because you can do the same by closing without saving and then reopening.

> A better tooltip or removing the button would be good moves.

I'm not getting any tooltips. Besides, I don't like having tooltips appearing when hovering buttons (though I can agree with having them if they are needed).

**Comment by Cernelius** [comment]
"Reset to Saved" would actually mean "Reset to the Latest Saved State". Just trying to keep it short.

**Comment by frigoref** [comment]
@Cernelius Should be fixed with PR [12819](https://github.com/triplea-game/triplea/pull/12819) (Fix issues 12777 - Rename settings windows button from "Reset" to "Reset to Saved"). Please recheck and confirm.

**Comment by Cernelius** [comment]
> @Cernelius Should be fixed with PR [12819](https://github.com/triplea-game/triplea/pull/12819) (Fix issues 12777 - Rename settings windows button from "Reset" to "Reset to Saved"). Please recheck and confirm.

I confirm it for the latest (2.7.14871) release.
