### ISSUE TITLE
Mapskins Are Not In Game Available From Normal (Not-Zip) Folders

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#1279]
This happens both in basic and master folders alike.

Only mapskins in zip format are available in game (albeit only one of them, and wrongly named; see: https://github.com/triplea-game/triplea/issues/1249 ).

This is a problem for mapskinmakers, as you cannot work on a mapskin and test it without keeping zipping it each time. Moreover, it takes some time to realise that the problem is that you need to zip it, if you are not aware of it.

It is also weird and unexpected that maps work both zipped and not, while mapskins work only zipped.

Test case: Take a map skin, unzip it, delete the zip, see that you don't have it anymore in View/Map Skins.

Question is if not-zip mapskins are supposed to be not anymore supported or this is a bug?

Only zip folders, not regular ones, working would be a serious drawback for mapmaking.

This limit or bug (?) is not present in 1.8.0.9. I tested the "Diplomacy-MapSkin1" and it works both zipped and not zipped.

Related:
https://github.com/triplea-game/triplea/issues/1249

**Comment by DanVanAtta** [comment]
Likely a bug somewhere. The logic for how resources are loaded is quite special cased, wired together via shoestring... :disappointed:

**Comment by Cernelius** [comment]
Related to:
https://github.com/triplea-game/triplea/issues/1323

**Comment by ron-murhammer** [comment]
@Cernelius This should be resolved with #1324
