### ISSUE TITLE
2.7.14835 An unexpected error occured! - these cannot be posted to GitHub, have to abort by pressing OK Mk2

### ISSUE THREAD

**Issue by TheDog-GH** [triplea-game/triplea#12792]
**Note:** This maybe be related to the fix for
https://github.com/triplea-game/triplea/issues/12788

TripleA version 2.7.1483**5**
Map 1941 Global Command Decision v175
Set all players to Fast AI, so its Ai v AI, it might be random
Run/Play
Wait for errors, by turn 6 this had happen twice, as mentioned, it is rare (0-1 per game) this form of testing produces any error. This is the first time I have seen this format of errors.

Turn 8
![image](https://github.com/user-attachments/assets/92f4dac5-e741-4ac0-b18a-bbe62b232a34)

Turn 9
![image](https://github.com/user-attachments/assets/e724f084-3ae1-4bfe-bbdb-658e6d1f6c97)
![image](https://github.com/user-attachments/assets/ffde407f-49c1-4ffe-8ef2-554a4f0bd7d5)
![image](https://github.com/user-attachments/assets/c558b15b-96ca-4c7a-bfb3-fbd504f1d813)

.
Attached TripleA log file zipped
[triplea.zip](https://github.com/user-attachments/files/16412582/triplea.zip)

@DanVanAtta one for you?

**Comment by DanVanAtta** [comment]
Error report upload is fixed now.

**Comment by asvitkine** [comment]
@TheDog-GH @DanVanAtta 

Was there a separate issue filed for the ConcurrentModificationException? Is it still an issue?
I tried the above repro steps and haven't seen it in 16 rounds... But I'm not sure there was any change to fix it?

**Comment by asvitkine** [comment]
Ah, I see https://github.com/triplea-game/triplea/commit/2163a23eee04ecb93475e6720bdb58600fdbdf35 and the referenced issue.

**Comment by TheDog-GH** [comment]
@asvitkine
I think the above errors have been fixed, ran 3 games and none of the above occurred with version TripleA-2.7.14848

But I do get these errors below, but in fairness these **soft** errors have occurred randomly for many TripleA versions with 1941 GCD
![image](https://github.com/user-attachments/assets/580da104-8356-42c4-af4c-dc5bf3fbb224)
