### ISSUE TITLE
Select Parsing Method Changes To Parse All When Closing Select Parsing Method (1.9.0.0.3237)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#1283]
Test case: Be sure to have "Parse Selected" set, open Engine Preferences, open Enable/Disable Delayed Parsing of Game XML's, click on the "X" symbol to close the "Select Parsing Method" window, get told "Please restart TripleA to avoid any potential errors", ask yourself why the hell you are being told that like you changed anything, restart or not restart TripleA as you wish and see that now you have "Parse All" selected.

This weird behaviour doesn't manifest itself if, instead of closing by clicking on the "X" symbol, you click on the "Cancel" button.

I think this is a major problem, as a user might mess around and inadvertedly enable "Parse All" by closing the window, getting all the related delays, and not realising he needs to change to "Parse Selected".

My suggestion is just getting rid of this option and having "Parse Selected" always and only. Why a user should have an option that has exactly zero value for him and just causes delays if selected for no reasons?
There is no reason why any user may want to parse all maps each time he opens up the select screen or even ever at all.

At the very least, I suggest it changing to "Parse Selected", when closing (I believe "Parse Selected" is the default; and if it isn't I surely believe it should be).

This strange behaviour exists also in the 1.8.0.9 release, but I never noticed, because I see no reasons at all to be wanting to parse all.

**Comment by Cernelius** [comment]
Related to:
https://github.com/triplea-game/triplea/issues/979

I suspect that @DanVanAtta might have been a victim of this bug:

> I did not realize I still had parse all on.

**Comment by DanVanAtta** [comment]
Task here is to remove the 'parse_all' feature.

**Comment by DanVanAtta** [comment]
delay parsing option is removed in: https://github.com/triplea-game/triplea/pull/1921
