### ISSUE TITLE
Corsica not reachable in Coldwar

### ISSUE THREAD

**Issue by Aramis7609** [triplea-game/triplea#12843]
Hello,
Impossible to send a unit to Corsica in the map Coldwar.

Then, I can not export the game "xml",, an auto report has been sent to TripleA.

See, the attached game , but the name of the file of the game has been changed : 2024-8-9-Cold-War-249 - Copie.png elsewhere I can not attached this file.

![2024-8-9-Cold-War-249 - Copie](https://github.com/user-attachments/assets/7a43e5a8-5746-494e-ba50-fbe74fdbc302)
.

Please, can you help me ?

Regards
Francois
Aramis

![PUchart_coldwar](https://github.com/user-attachments/assets/267240ef-523d-420f-ad9c-b64561b1209c)
[stats_2024_08_19_Cold War_round_20_full.csv](https://github.com/user-attachments/files/16658578/stats_2024_08_19_Cold.War_round_20_full.csv)
![PUchart378-419](https://github.com/user-attachments/assets/4133ed4b-63e0-4a46-b4ac-929fb18fb43c)
[Americans.csv](https://github.com/user-attachments/files/16658579/Americans.csv)
[EFF.csv](https://github.com/user-attachments/files/16658580/EFF.csv)
[French.csv](https://github.com/user-attachments/files/16658581/French.csv)
[General Information.csv](https://github.com/user-attachments/files/16658582/General.Information.csv)
[Italians.csv](https://github.com/user-attachments/files/16658583/Italians.csv)
[NAF.csv](https://github.com/user-attachments/files/16658584/NAF.csv)
![PUchart0-41](https://github.com/user-attachments/assets/a1095d8a-a2aa-44e7-a5ff-e652e524a91e)
![PUchart42-83](https://github.com/user-attachments/assets/b9d7f213-4d3e-4939-83c6-05fa7f491f3a)
![PUchart84-125](https://github.com/user-attachments/assets/49203203-f8d8-4396-be22-c4ed0b1fde44)
![PUchart126-167](https://github.com/user-attachments/assets/5112eebb-2155-4e40-b1f4-d94247a83acb)
![PUchart168-209](https://github.com/user-attachments/assets/9ba46f83-26dc-49df-894a-71bd9f5d4886)
![PUchart210-251](https://github.com/user-attachments/assets/9e21f9df-9f4b-4b9d-a2ea-d695e8e41b12)
![PUchart252-293](https://github.com/user-attachments/assets/c33658ab-4264-420e-aa90-361978e48432)
![PUchart294-335](https://github.com/user-attachments/assets/b1fd3024-6c45-4087-b9ec-f65fa1747d59)
![PUchart336-377](https://github.com/user-attachments/assets/8670ca01-ff40-46f4-aac7-495acd779676)
[Satellites.csv](https://github.com/user-attachments/files/16658585/Satellites.csv)
[USSR.csv](https://github.com/user-attachments/files/16658586/USSR.csv)
[WFF.csv](https://github.com/user-attachments/files/16658587/WFF.csv)
![PUchart_coldwar](https://github.com/user-attachments/assets/d48ab614-6ffa-4035-aaf8-5731ede4d200)

**Comment by WCSumpton** [comment]
@Aramis7609 

I am sorry but you do not provide enough information. From the pictures, Corsica is an island in SZ 57. It appears that Satellites have 1 cruiser, 2 transport with 1 elite, 1 armor and 1 artillery in SZ 57. Corsica is France owned. Beyond this I can discern nothing else, ie; who's turn? what phase?

Also, I have not found an error message that relates to this problem.

To attach a saved game to Git, it needs to be contained in a zip file.

As this seems to be map related issue, and should be moved to the forms, and closed.

Cheers...

**Comment by Aramis7609** [comment]
Hello,
Yes Corsica is an island in SZ57.
But the elite, the armor and the artillery can not disembark in Corsica, I
wonder why.
I agree with you that is probably a map issue.
Please, find enclosed the game in a zip file.
It is the round 20 and the Combat phase.
Regards
Aramis
François

**Comment by Aramis7609** [comment]
Hello,
Thanks four answer.
[2024-8-9-Cold-War-249.zip](https://github.com/user-attachments/files/16679488/2024-8-9-Cold-War-249.zip)

Yes Corsica is an island in SZ57.
But the elite, the armor and the artillery can not disembark in Corsica, I wonder why.
I agree with you that is probably a map issue of Cold War.
Please, find enclosed the game in a zip file.
It is the round 20 and the Combat phase.
Regards
Aramis
François

**Comment by WCSumpton** [comment]
Sorry for not responding sooner and thank you for the save game file. There were territory name changes, that were preventing the save to load, but once these were tracked down, I was able to open your file. As to the problem with Corsica I was able to unload the transport to capture Corsica. I am very sorry, but I cannot recreate your problem. Please try with your save file and let me know if you are still having problems.

As of now I cannot recreate/track down this problem.

Cheers...

**Comment by Cernelius** [comment]
@frigoref More specifically, I'm pretty sure that what's needed is for the author to tell what version of TripleA he/she was using, encourage him/her to test it again with the latest version, after which I believe that this issue will be simply closed because the version was just old (and the issue has been already fixed a while ago).

Or maybe just closing already every issue where the TripleA version has not been indicated or are otherwise not detailed enough... How about that?

---

To clarify what is going on here, this used to be a map problem because in the past you needed (and were supposed to make sure) every enclave to have the name of the surrounding zone ending or starting in "Sea Zone" in order to be sure the zone not to be hidden in selection (for example, the zone named "SZ 57" should be renamed "57 Sea Zone" to fix the issue for those old engines). However, at some point in the more recent past, changes were made to the engine to assure enclaves would be selectable regardless (by making the engine smarter so not to need the aforementioned naming hack), indirectly fixing this map problem.

---

TL,DR @Aramis7609 Just update TripleA, and then you should be able to do what you want to do.

**Comment by Cernelius** [comment]
About updating, be warned that, if your version is too old, you may be unable to continue the (saved) game after updating.

**Comment by Cernelius** [comment]
Anyway, I believe that this issue does not exist in the latest release, so I'm closing this issue.

@Aramis7609 Please reopen this issue if you believe that it has not been fixed.

**Comment by Aramis7609** [comment]
OK, thanks. Regards


Le mar. 10 sept. 2024 à 00:38, Cernelius ***@***.***> a
écrit :
