### ISSUE TITLE
Wrong download size shown the first time selecting a list object

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#1288]
Noticed this when downloading some maps. When clicking on a map it displays 0 MB as download size. when selecting another list item and selecting the first again the download size is correct.,.

**Comment by ron-murhammer** [comment]
Yeah, I noticed this as well and I believe it has to do with some fix @DanVanAtta made when either the download sizes weren't available or were taking too long to load.

**Comment by RoiEXLab** [comment]
Right! I believe this has to do with #1210

**Comment by DanVanAtta** [comment]
Seems likely that we zero out the 'not found' case. Probably should be listed as a dash maybe.
