### ISSUE TITLE
2.7+ CPU usage is very low, on FastAI or HardAI

### ISSUE THREAD

**Issue by TheDog-GH** [triplea-game/triplea#12884]
Pick a map, I think any map will do and the CPU will barely run over 50%, possible averaging around 20%
Set all players to FastAI or HardAI
I have been testing using 1941 Global Command Decision
I am on TripleA-2.7.14866, Windows 11, with 16GB RAM

As this appears to affects all maps and testing,  I have labelled it as Major.

@asvitkine @frigoref

**Comment by frigoref** [comment]
@TheDog-GH What exactly is the contrast to the expected behavior? What ist the problem statement for this issue and what would be suitable acceptance criteria to close this ticket?

**Comment by TheDog-GH** [comment]
In the past versions 2.5 & 2.6 version would hit 100% CPU.

Maybe its my new Windows 11 PC, but sometimes the CPU usage drops below 10%, I have nothing else running, sometimes I close Chrome, hoping for more, but it does not improve.


Running Shogun Advanced, it does something similar, it has over 200 foreach loops and its slow as well.

My criteria not to drop below 20% CPU, so a modest increase in speed.

Im hoping you are on Windows and can replicate what happens.

**Comment by TheDog-GH** [comment]
More info FastAI testing will yield a quicker result, so Im hoping fix Fast and it will also fix Hard AI.

**Comment by TheDog-GH** [comment]
I also have an old desktop i7, with 20GB RAM
This is playing 1941 Global Command Decision, all factions are FastAI, round 1

![image](https://github.com/user-attachments/assets/ec4e7942-2b10-488a-b0e1-d23f5f0ca2f1)

This might help
![image](https://github.com/user-attachments/assets/8bc6ec05-9d92-4513-b5f8-e829926da8c2)

**Comment by Cernelius** [comment]
> @TheDog-GH What exactly is the contrast to the expected behavior? What ist the problem statement for this issue and what would be suitable acceptance criteria to close this ticket?

Why would you not want it always using as much CPU as possible?

**Comment by TheDog-GH** [comment]
@Cernelius 
> Why would you not want it always using as much CPU as possible?

Ideally I would, but it will be a complex issue and I have just asked for a modest minimum speed increase, over something that drops the cpu to sometimes below 10% for a few seconds.  This is something observable/measurable that hopefully can be fixed, rather than just saying its slow.

Cernelius do you find the same issue?

I/we can always ask again for anther look at a speed increase.

**Comment by Cernelius** [comment]
Actually, the question was to @frigoref. Your user-name is in the comment which I quoted.

>Cernelius do you find the same issue?

I actually have not played with any AI for a long time, so I'm oblivious about this.

**Comment by frigoref** [comment]
> > @TheDog-GH What exactly is the contrast to the expected behavior? What ist the problem statement for this issue and what would be suitable acceptance criteria to close this ticket?
> 
> Why would you not want it always using as much CPU as possible?

I was just trying to drive the issue to a point where it can actually be worked on (clear problem statement, reproducibility, acceptance criteria, etc.) and quite a few initial statements are just not enough for that. This increases the work load for our development resources that should rather focus on problem solving. 
Getting to your specific question, @Cernelius, which is already much more precise than x% are currently used, the CPU usage might stay low due to impossible/impractical parallelizations. Kind of the topic with 9 women that cannot give birth to a child in 1 month.

**Comment by TheDog-GH** [comment]
@frigoref 
Apologies, I had forgotten I had changed the **AI Move Pause Duration** from 0 to 200 🙄 
This is so I can move around the Shogun Advanced map I was testing, at 0 I cannot move the map after the 1st round.

Putting it back to my usual 0 and all is as it should be, the CPU never drops below 20%.

Closed.
