### ISSUE TITLE
Release numbers

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#129]
My vote is when we have continuous integration up, Travis pushing artifacts into github, then it'll be a better time to change version number schema. 

My proposal is this, let's drop the unused numbers from today. We have "a.b.c.d". A is not used, "c" and "d" are a bit arbitrary and seem to be redundant to each other.

What do we need? Map compatibility is useful. We need an increment number for when we change something and build a new artifact. Some sort of release numbering so we can recognize release.

I propose we do this then, we switch the current version number from 1.8.0.7 to version 8.0.0

Then whenever we merge to master, we look at the github release page to see what the last tag was, you then increment that and tag, so 8.0.1 in this example. Artifacts are then built, and we can then do regression testing. If we merge again then we'll be at 8.0.2, and so on.

Let's say we now want to do a release, we pick an artifact. Let's say we're at version 8.0.5. We then do regression testing of that release and do very thorough testing. We get some people to play full length games on the engine even, some beta volunteers in the lobby (hopefully it gets really easy for them to upgrade, and it'll be a matter of finding people that are about to start games they woudl play anyways). But eventually after enough of this we consider the candidate good.

Once the candidate has been established as suitable for release:
- we check out the tag, 8.0.5 in this example
- create a release branch from that point in history
-  increment the version number in code,  for example to: 8.1.0 (then next release will be either 8.2.0 or 9.0.0)
- commit and tag, push tag.
- rebase master on top of this branch, repush master. This will insert the version update into the history
- finally, renumber tags that are going to now be included in the next release. For example, 8.0.6 would be renumbered to 8.1.1, 8.0.7 if it exists would go to 8.1.2

Some nice benefits:
- we always get to increment the number when we change/add stuff, always!
- tags are light weight, using them for the common operation of version increment is a good pairing. There is no potential for merge conflict of increment number, no trying to guess you'll be the next PR to be merged and what the number should be. Also with no code change, there is no need for  a second PR to change the version number.
- tags solve the uncertainty of which release problem well. For example, if 8.0.5 failed testing, and we were already at 8.0.9, then the thing to do is to stop dev efforts and all hands on deck - get 8.0.9 to be rock solid. So you don't waste time on bad releases and doing lots of branching and multi-version merge work. Plus it ties into the idea of always keeping a working build, always keep the latest version working and the best so far. To discuss the alternative, 8.0.5 succeeds the more rigorous, in the wild testing for a some time, and it does get promoted to 8.1.0. If we used code changes for all other feature branches, for 8.0.6, we would have merge conflicts to resolve, and also extra commits for all these little merge conflicts and bumping of version numbers.
- there is pretty minimal use of actual numbers in the version number - only two that users will see, and three for developers

**Comment by DanVanAtta** [comment]
Want to emphasize, I *really* like that tags will keep track of all minor version numbers. Not having to update code for the frequent version number change is very nice : )
We can probably even automate a script to watch for merges to master, look for the last tag, and tag master with an increment (and then at that point we have a fully automated CI pipeline!!! today the only manual step we have is a manual creation and pushing of a tag. With this schema, we could do the day-to-day version tagging completely automatically)

**Comment by DanVanAtta** [comment]
@gaborbernat  : "this is exactly why I proposed adding an extra number at the end to allow for bug releases. It should be like 1.8.0.7.0, 1.8.0.7.1, etc... but perhaps we can skip the third 0, and make it 1.8.7.0 and so on"

I think we're in agreement, I suggest we also skip the first number too.

**Comment by ron-murhammer** [comment]
@DanVanAtta So interesting idea and I like that the numbering is simpler and that we have a number to identify each build uniquely. This would actually help out for pre-releases as well since I currently have no way to track them and would like to add a version number to the triplea.jar as well.

That being said the drawbacks are:
1. That our users are used to the existing system and what the version numbers mean (at least to some extent). 
2. This would be a decent amount of work to change as we would need to decide how to deal with the releases that use the existing versioning. Would need to look at the code in some places to see exactly how much work but even map XML has version number references.

My initial thoughts are maybe target a more limited change to say add a 5th number just used to track the build and for us developers. Also look to add the version number the the triple.jar. I think these 2 changes would give the most bang for the buck.

**Comment by DanVanAtta** [comment]
The increment or build number exists in Git only as a tag. So if we do that as a 5th number, there are *no* code changes needed. This would be a process only change. @ron-murhammer , I'm in favor of doing that.

I particularly like that we can then start the tagging after merge process. Hopefully we'll refine that and build a script to automate it. So then you can just run something after merging to update tags. This gives us 95% or more of the bang for our buck.

Seems then our current version of master would be tagged as 1.8.0.9.1, then after the next merge into master it would be tagged as 1.8.0.9.2 (and note, no java changes, the 5th number is only for build number and only visible to developers and testers, not even the code would see the 5th number!)


> "version number to the triplea.jar as well."

Already done!! See the .travis.yml file in PR #106, notice the: `artifacts/triplea-$TRAVIS_TAG-all.jar` . That line indicates what to push into github releases by name, the `$TRAVIS_TAG` is an env variable available during travis builds that has the value of the current Git tag. Because PR #106 only has an encrypted token valid for my repo, only I can do this right now, but if I were to check out that branch and push a tag "1.8.0.9.1", Travis would automatically build and push a  "triplea-1.8.0.9.1-all.jar" into github releases. You can see an example of this functionality working with the tag "test01" that I had pushed some time ago: https://github.com/DanVanAtta/triplea/releases


But for the record, it seems we only need three dimensions to be captured by our version number:
- map compatibility number
- release version number
- build or increment version number

With 5 numbers, and only 3 needed,  2 can be dropped, so we can simplify. We could do so in a backwards compatible way by using the left hand side numbers and zero padding to the right when needed. So then version 9.0.0.0 would just look like a far advanced version compared to 1.8.0.9 The other piece of good news is that the version number is centrally handled by a single object in the Java code, so we could make any other needed code modifications there (and spare us from having to update all the maps). But I would agree to leave the version numbering simplification for another day.

**Comment by veqryn** [comment]
So, I actually do not want a 5th version number.  We already have 1 too many version numbers, in my humble opinion.

Ideally, I would actually do the following:
Split out "end user visible version" from "developer build version", that way we can have the "end user visible version" accurately reflect the time spent on a release from a marketing point of view (think windows 10), while the "developer build version" would follow semantic versioning (http://semver.org/).

The example I am thinking of here, is the last approximately 1 year of work, between version 1805 and 1809, probably should have been considered a much larger increase in version numbers (to 1901 or 1811).  However, we bumped the version number to 1807/1809 because none of the changes actually broke savegames.

Here is what the ideal world would look like to me:
End user visible version number: 1.0, 1.1, 2.0, 2.1, 2.2, 3.0, etc.  
The major number would signify major features (ie: a new AI, new rules, large batch of smaller features), while the minor number would signify minor features or bug fixes only.

Developer visible version (following semantic versioning): 2.5.5, 6.0.5, 7.0.3, 8.0.5, 8.0.7, 8.0.9, etc.
This would basically just be almost the same as our current versioning scheme, except with the first number (1) lopped off.
The major number would signify API breaking changes.
The minor number would signify new features being added in a backwards compatible way.
The patch number would signify non-breaking, non-feature, bug fixes and extremely small changes.


The problems with moving to this kind of scheme are what Ron said earlier:
Everyone knows our versioning right now.
It is part of the map xml code.
It is part of the savegame file.

**Comment by DanVanAtta** [comment]
@veqryn Does that proposal allow for tagging each time after we merge into master with a unique version number? As far as integration with the CI pipeline, that is the only real requirement.

**Comment by DanVanAtta** [comment]
@veqryn  Since the 5th version number is just a tagging and tracking thing, do you have strong objection to its interim usage?

I don't particularly like it, but it is nice compromise until we can focus on changing the version number system to what we would really want it to be.

**Comment by veqryn** [comment]
I would actually be against it.
If you guys really need a "build" number, then why not just use one of the currently unused numbers?
For example, lets drop the 3rd digit from our current numbering scheme, since it is so rarely used.
1.8.0.9 would become 1.8.9.x, where x is our new 'build' number.

We might as well bump up to version 2.0 (2.0.1.x), and put code in place to say that savegame compatibility is now the 3rd number instead of the 4th number.

**Comment by DanVanAtta** [comment]
I think that is a good suggestion.

We will then have to update code for each build. On the one hand there is overhead there, on the other there are a number of  benefits too (which I think outweigh the cost here):
- if we group multiple merges into one version, the commit incrementing the build number will show us in the git history which commits were contained in which build (this is a very good benefit actually, but I'm assuming an effectively linear history though)
- the tag always matches the number a person would have just incremented in the code, so not much overhead is added since a person needs to check what the last tag or version number was anyways .
- the code having the exact version number is not a bad thing if we allow the overhead of incrementing it often. Bug reports generated by the code can have the exact version number, a range of more possibilities.
- five version numbers is a smell, four is a well considering we only use two or three of them, so better using the version numbers we have I think makes sense

**Comment by veqryn** [comment]
How were you planning to increment the build number anyway, assuming we went with a 5th number?  Some sort of hook into travis/gradle?  Can something similar not be done with the EngineVersion numbers?

**Comment by DanVanAtta** [comment]
I haven't identified a fully automated way to increment the version number (yet). So far to increment version number it is a set up steps, we can script those out to look up the last version number and increment and then to do the rest.

Some sort of commit hook or something would be nice, but an initial look didn't yield much luck.

So these would be the steps for an admin after merging:

```
git stash
git checkout master
git pull --rebase
 // determine what the last version number was, let's say it was 1.0.1.0
git tag -a 1.0.1.1 -m 'my version 1.0.1.1'
git push --follow-tags
```

(apparently --follow-tags is safer to use than --tags http://stackoverflow.com/questions/5195859/push-a-tag-to-a-remote-repository-using-git)


W.R.T updating the engine code,  the version number format is slightly different when stored in Java - but it certainly would be possible IMO to build a script that could commit the Java version number to match the tag, and to commit it with a standard commit message and push everything.


How about this as a way forward, let's build and commit a post-merge script that has all these steps and the things to do. We can work to improve the automation, and automation as documentation is a good form of documentation. I can have a PR with an initial version in a day or two if desired.

**Comment by ron-murhammer** [comment]
@DanVanAtta Have you used the Maven release plugin before? I've used that to essentially tag and increment the version number in an automated way. I've mostly worked with Jenkins/Maven and gotten it all wired up with those. Not sure exactly how to do it with Gradle but I have to imagine there is a way and would prefer to not reinvent the wheel with a bunch of custom scripts if we don't have to.

**Comment by veqryn** [comment]
Wouldn't having 1000s of tags clutter things up?
I mean, if we really need to debug things, it probably isn't hard to just go back through the commits til you have the commit with X version.

**Comment by DanVanAtta** [comment]
> Maven release plugin before? 

Does maven release help with the git commands? From what I can tell you *have* to run a few git commands no matter what. It is like rebasing a branch, you have to stash your local changes first and then you run a git pull --rebase. Then when to push you have to run `git push`. So the script, it has *2* lines to create a tag and then push it. The rest is git fluff to ensure you are on master, have the lastest code, etc... Whatever script would read and increment the version number, using maven sounds like overkill for that compared to a bash/python/perl one or two liner.

Last, we need to update `EngineVersion.java` in a relatively custom way. Namely to increment this:
```
public class EngineVersion {
  public static final Version VERSION = new Version(1, 8, 0, 9);
}
```

I don't think the plugin would help there either regrettably. Notably we would have to do this increment before the tag is created. 

Overall I would expect probably for the git commands, the java version increment and check in, all to be run by hand the first couple times. After that, it's wise to throw me in a shell script or something so it is not so repetitive. Eventually finding a way to run that script automatically would finish the automation. Until then there is no magic bullet I know that can make this more lazy of a process - the code update would be avoidable with a 5th number interim route - though we've discussed that.

> "Wouldn't having 1000s of tags clutter things up?"

We won't get to 1000s of tags any time soon, not even close. Would be three years before we got that with a steady one per night. But also tags can very easily be cleaned up programmatically. We'll likely clean up the unstables on semi-infrequent basis.

w.r.t. looking through commits - it's actually a *whole* lot more painful to go through the whole text history than to list out tags. You can list tags from command line in miilliseconds, plays nice with grep and other command line filters. Going through commit comments, you'll also find stuff like:  "fixing bug introduced in version x.y.z", etc.. 

But most importantly, these automated pipelines are building on a common release practice, tag your releases. So the tag triggers the automated release work flow, and is not only for marking where we've done releases, but to trigger the automation pipeline.

Once we have build artifacts we will have tested the packaging process, and we can then do a full regression test if we choose. Furthermore, with the unique numbers, we could have for example @ron-murhammer push a few AI changes and then we get a nightly build. He then asks someone to test stuff out, and perhaps there is some really new stuff in the next few nightly builds, or some more variations are tried out of the same code - @ron-murhammer  could ask someone to try out version 503 and then compare again with 505 perhaps to see which one does better. In addition if someone spends their sweet time with release testing it, they can report bug a exists in 503. We can then more easily check when that bug was fixed (we'll have commit history now to help with this, this is not something we would do often so full painful slow text searches is okay).

**Comment by veqryn** [comment]
Will this process still let us use github's merge ability for pull requests?
Can we have the custom script tied to a github hook?

**Comment by DanVanAtta** [comment]
> Will this process still let us use github's merge ability for pull requests?

This is a process that takes places after the github merge of a Pull Request. Pushing a git tag requires push privileges, so an admin would need to do it. The correct time to do so is after merge of a pull request.

> Can we have the custom script tied to a github hook?

Perhaps, I don't know how though. We don't have a custom script yet, so let's not put the cart before the horse too much. Simply pushing a git tag is not a huge deal even if it is not scripted or automatically run from a hook. The ideal would be for it to be run from a github hook of some sort, yes.

**Comment by DanVanAtta** [comment]
@ron-murhammer just realized, the maven release plugin would be something more that is run by Travis, configured in the .travis.yml. This process with the tag is to trigger the packaging process. Maven release plugin is a way to package, it is what you would want to trigger. So by that token even if we used that plugin (looks like we wouldn't since we don't push into sonatype or any other maven repo), you would still want and need the supporting git script and still need to do the git-fu to push a tag.

**Comment by ron-murhammer** [comment]
@DanVanAtta Yeah you can push a tag with the maven release process as well by specifying the SCM info such as: http://stackoverflow.com/questions/8901575/using-maven-git-how-do-i-tag-the-latest-version-of-my-code. But you are correct that in general there is a nexus or artifactory to push artifacts to as well that won't be part of our process since our artifacts are too large.

**Comment by DanVanAtta** [comment]
I recommend we complete and gain more experience with the new build process that uses Gradle and Travis before we introduce more components like Maven Releases or SCM. With more experience we'll know better what automation we would want and need, and how to integrate it. Right now we have yet to integrate Travis with Gradle, let alone without adding more technologies.

Secondly, with some more thought on the subject, it is actually a *huge* cost to require a code change if all you want to do is increment your build number. Making better use of the existing numbers is attractive, but requiring a code change for that benefit is far too high of a cost. Simplifying the version numbers should happen, but pinning our build process on that simplification is an unnecessary and detrimental dependency. Thus, the version number pushed by tag, unless it is a special one, will have N+1 digits compared to what is stored in code.

**Comment by DanVanAtta** [comment]
We started talking a lot more about the release process than the actual release numbers in this issue. The release process is the important thing, the version number is just a tool. I'm closing this issue in favor of talking more about the release process directly and in a focused manner in #200. Once there is more consensus on what the build and release process will become, it'll be easier to have a conversation about how to update version numbering to achieve those goals.

**Comment by DanVanAtta** [comment]
Some very good news, it does appear with some access token work Travis *can* automatically tag. We can use the Travis build number as our increment build number, no scripting or code changes or manual pushes will be needed. Simply merge and things will get tested, built and pushed :rocket:
