### ISSUE TITLE
What is triplea's development process?

### ISSUE THREAD

**Issue by tiagobalm** [triplea-game/triplea#1291]
Hi,

My name is Tiago Almeida and I'm a student at Faculdade de Engenharia da Universidade do Porto. Currently I'm studying Computer Engineering and for my Software Design class we were told to choose an open source project to analyze. Me and my group chose your project, the TripleA game. We have to write a report about the way the project was programmed and we would really appreciate if you could help us. We would like to know
* How long have you been developing the game?
* How many people were involved in the development process?
* What model did you follow when developing the software?

Thank you very much for your time,
TIago Almeida.

**Comment by good-old-music** [comment]
I am not a developer, they may well be busy working on the project. A good place to start might be https://en.wikipedia.org/wiki/TripleA which will answer your first question and, make a start on answering the second although besides changes in personnel, the second could be fairly open ended as you may have to include a large proportion of the end users in the total count as their feedback could sometimes also be interpreted as assisting in development.

**Comment by ron-murhammer** [comment]
@tiagobalm - The project has been around now for about 15 years. It has had many different developers over the years (maybe around 10-15 though about 4-5 core developers). There are a handful of active developers and none of us have been involved for more than a few years. You can see the main contributors in the github graphs though this is only partially accurate. About a year ago we moved from SourceForge/SVN to github which changed the development model. Previously there were just a 1-2 active folks with SVN commit access and everyone else would submit patch files. Now in github a number of us have commit access and everyone submits PRs for review. We have seen some uptick in new developers after moving to github.

Glad to answer any questions and feel free to contribute :)
