### ISSUE TITLE
Can't Use Edit Function to Change Money in Original "Pacific" 

### ISSUE THREAD

**Issue by kwaspek104** [triplea-game/triplea#12925]
![image](https://github.com/user-attachments/assets/5941a48e-86b6-432e-92b0-b2073317edd7)

I can't edit the money on Triple A for the Original Pacific Module.

**Comment by WCSumpton** [comment]
@kwaspek104 

There is a change between 2.5 and 2.7+ in that in 2.5 only PUs could be edited using edit mode. This was changed to allow for the ability to editing all resources. "PUs", "SuicideAttackTokens" have default icons, but "TemporaryVPs" does not. You will need to create a "resources" folder under pacific/map and put a "TemporaryVPs.png" icon there.

Cheers...

**Comment by kwaspek104** [comment]
It works...but now I have this giant part of the screen blocked off and it's annoying haha

![image](https://github.com/user-attachments/assets/519b4dcd-7f15-45d0-bd90-f1db536c9158)

**Comment by kwaspek104** [comment]
Perhaps the icon I chose was too big?

**Comment by kwaspek104** [comment]
lol...yes

![image](https://github.com/user-attachments/assets/53516e56-4e35-43f8-b696-98a14cf586ae)
where do you get these incredibly small cute icons? lol

I just used an artillery for now

**Comment by beelee1** [comment]
@kwaspek104 not sure if this is exactly what you're looking for, but there is a "Victory City" (vc.png) in the capital T Triplea folder in assets, misc. 

Also might ask @RogerCooper if he wants to add it to the map, as he did the last update i believe

**Comment by Cernelius** [comment]
>where do you get these incredibly small cute icons?

On this, all that TripleA currently generally offers for map-makers (or power users) is what you can find inside the 
`TripleA/assets/resources` folder (where you have installed TripleA, usually in `Programs`) as well as in
https://github.com/triplea-game/assets/tree/master/game_headed_assets/resources
plus what you can find in
https://github.com/triplea-game/map-maker-assets/tree/master/resources

For example, you could have used the
https://github.com/triplea-game/map-maker-assets/blob/master/resources/Leadership2.png
resource image (renaming it), but what you already did works too.
