### ISSUE TITLE
Change Game Notes Windows To Be Not Always On Top (1.8.0.9)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#1292]
The Notes window is always on top, currently, and this may cause problems when you have something to click on (like a political actions accept), and you can't get it with your cursor, because hidden by the Notes window.
Thus, I suggest to **change the Notes and Help windows (you open by clicking Help/Game Notes or Help/Unit Help) to not be always on top.**

User case from lobby:

> (22:23:21) Cernel:  You just slapped Neverlucky
> (22:23:22) Cernel:  you disc
> (22:23:29) Neverlucky:  i bugged myself
> (22:23:34) Neverlucky:  game notes bug me a lot :s
> jan7 has joined
> (22:24:17) Neverlucky:  i made error of pressing finish turn
> (22:24:22) Neverlucky:  and immediately go to unit game notes
> (22:24:26) Neverlucky:  that creates unclickable
> Hummel has joined
> (22:24:31) Neverlucky:  and produces a sound everytime i click something :S

**Comment by DanVanAtta** [comment]
Switching to a bug since this situation causes the game to be unplayable (turn cannot be advanced). After moving to JavaFx we'll need to double check about this problem.
