### ISSUE TITLE
Convoy Center labelled incorrectly in the Original Pacific

### ISSUE THREAD

**Issue by kwaspek104** [triplea-game/triplea#12927]
For whatever reason I can never post on the TripleA website lol...so I'll just post here 

This convoy center is incorrectly labeled as "Australian" in the Pacific module. 

![Screenshot (812)](https://github.com/user-attachments/assets/34826e56-2332-47c6-8219-e9a2875b2e6d)

But in the actual game, it's the same as the one in Sea Zone 52 & 49, shown here. 

![Screenshot (814)](https://github.com/user-attachments/assets/3e6ea040-20e7-4f0f-9223-46f75573ce5d)

Any tips on how to change it? I'm sure there's a guide on the TripleA website...

**Comment by beelee1** [comment]
@kwaspek104 can you log in to the site ? You can read but not write ? I would ask @panther2 for help using the triplea site.

Anyway, Pact of Steel2 xml explains most of the xml map making.

[POS2 xml.zip](https://github.com/user-attachments/files/17282700/POS2.xml.zip)

**Comment by kwaspek104** [comment]
thanks, the TripleA website works now, I just posted the same thing there (though the pics didn't work for some reason, I'll respond to it lol)

**Comment by beelee1** [comment]
right arm were all good here Panther
