### ISSUE TITLE
Add "Open User Maps and Savegames Folder" Button Back

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#1293]
This button was present in 1.8.0.9 but I don't see it in 1.9.0.1.

Not very important, but I would surely keep it, as I believe it has some good value, as it is a friendly way to try to make non-power users install maps. It often made easier for me to playtest maps needing manual install.

If it had to go because of the current ability of setting the maps folder, I believe that a button to find it is more important than the ability to customise it.

I actually suggest having it in main screen, under Engine Preferences, as it is not an Engine Preference, and it is the manual install alternative to clicking on Download Maps (best would be actually being under Download Maps).

Since now the path is customisable, I suggest having it just as "Open User Maps", opening directly that. I don't think there is much of a user case for opening the Savegames Folder (you normally do that in game, and there is the Open Saved Game).

**Comment by DanVanAtta** [comment]
The button had some problems. Under the hood it was quite ugly. We could support more easily an option to download a map from a custom URL. I'd suggest that as an alternative.

**Comment by Cernelius** [comment]
Not really. I don't think that will work well on upload services with ads, like SendSpace (the one traditionally used during Veqryn's age) (that keep changing URL at each download, to try avoiding you not seeing its ads), and it won't work well if you send the map via e-mail. Also, the button to open the maps' folder has the value of making the users know about what downloading a map actually means (many don't know that downloading a map means putting a zip into a folder).
But, again, this is a fairly important, but surely not very important, issue. Surely, the download from URL button is an interesting idea and better than nothing, and somewhat more user friendly than the button, albeit more limited and less informative.
So, yes, a download from URL may be a good addition, but not fully substitutive.
I'm just worried that may be used to make people download bad things, and if they don't put them there themselves, it won't be so easy to know what they are actually downloading and eventually go deleting it.

**Comment by DanVanAtta** [comment]
I disagree it is valuable for users to know about the map folder. It just gets down to hand managing of files. The other aspect is that sharing files via email is a very time consuming, novice unfriendly approach. Strangers are going to be disengaged if they have to cough up their email to then follow instructions on how to hand-install a map that is in progress. 

Hence the custom URL would be for if you trust the source. Which is pretty much the same as someone emailing you the file. 

If someone is working on a map, ideally they would save everyone trouble and do so via github, but not limited to that given any file hosting would work. Not being able to use Sendspace because it roates the URL I think is more a problem with Sendspace than the capability to download from a custom URL.

**Comment by Cernelius** [comment]
Ok, if you prefer the direct link download way that's good too, as I said.

**Comment by Cernelius** [comment]
Each has his pros and cons; the direct link is probably the most user friendly.

**Comment by DanVanAtta** [comment]
From a code point of view that approach is preferable. It's very similar to the existing map download, just a different URL. The code that was used to open a file window was a very custom to that functionality, added a lot of dependencies.

Okay, marking this as a feature request.
Goal: make it easy to do custom map installations
Task: add support for a custom URL to download map files. Idea being someone coudl post the URL, and others can then use that to download.

**Comment by DanVanAtta** [comment]
summarized and moving to: https://github.com/triplea-game/triplea/issues/1325
