### ISSUE TITLE
Launch of 1.8.0.9 don't work

### ISSUE THREAD

**Issue by Sylvest888** [triplea-game/triplea#1294]
I get this error when I try to launch;

"The registry refers to a nonexistent Java Runtime Environment installation or the runtime is corrupted

The system cannot find the path specified"

Have tried 2 downloads, updated my Java....

Any suggestions to what to do? ... dying for a game :)

**Comment by panther2** [comment]
Not a TripleA but a java problem. See
http://tripleadev.1671093.n2.nabble.com/Java-problem-td7593367.html#none

**Comment by Sylvest888** [comment]
Thanks a lot - working now


________________________________
Fra: P@nther <notifications@github.com>
Sendt: 15. oktober 2016 17:34
Til: triplea-game/triplea
Cc: Sylvest888; Author
Emne: Re: [triplea-game/triplea] Launch of 1.8.0.9 don't work (#1294)


Not a TripleA but a java problem. See
http://tripleadev.1671093.n2.nabble.com/Java-problem-td7593367.html#none

-
