### ISSUE TITLE
Java Error when changing maps in hosted game

### ISSUE THREAD

**Issue by americanknight** [triplea-game/triplea#1296]
triplea.engine.version.bin:1.9
INFO [AWT-EventQueue-0] ChatController -> Chatter:AmericanKnight port:3300 ip:2001:0:5ef5:79fd:2865:2cf8:3f57:febf is joining chat:games.strategy.engine.framework.ui.ServerStartup.CHAT_NAME
host:45.79.144.53 port:3304
INFO [Decoder -Server] ServerMessenger -> Connection added to:prastle port:55435 ip:24.53.232.136
INFO [pool-1-thread-2] ChatController -> Chatter:prastle port:55435 ip:24.53.232.136 is joining chat:games.strategy.engine.framework.ui.ServerStartup.CHAT_NAME
Loading map: , from: D:\Games\AxisandAllies\TripleA\TripleA_1.9.0.0.3266\..\maps\
Loading resources from the following paths: [D:\Games\AxisandAllies\TripleA\TripleA_1.9.0.0.3266\..\maps\, D:\Games\AxisandAllies\TripleA\TripleA_1.9.0.0.3266\assets]
SAXParseException: game: Global War 2, line: 2120, column: 18, error: The content of element type "attachment" is incomplete, it must match "(option)+".
SAXParseException: game: Global War 2, line: 2122, column: 18, error: The content of element type "attachment" is incomplete, it must match "(option)+".
SAXParseException: game: Global War 2, line: 2124, column: 18, error: The content of element type "attachment" is incomplete, it must match "(option)+".

**Comment by ron-murhammer** [comment]
@americanknight I think there is an issue with the map Global War 2. I don't think there is an engine issue for this.

**Comment by ron-murhammer** [comment]
Fixed: https://github.com/triplea-maps/global_war2/commit/f515b6fc78002c4c9c8a155d6f9e9acf2b66ed44
