### ISSUE TITLE
Chat Errors When In Game (1.9.0.0.3266)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#1298]
I have this java error now that I'm playing my first game in new lobby, every time I chat:

> java.lang.NullPointerException
>   at games.strategy.engine.chat.ChatMessagePanel.lambda$addMessageWithSound$16(ChatMessagePanel.java:213)
>   at games.strategy.engine.chat.ChatMessagePanel$$Lambda$132/1012819872.run(Unknown Source)
>   at java.awt.event.InvocationEvent.dispatch(Unknown Source)
>   at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
>   at java.awt.EventQueue.access$500(Unknown Source)
>   at java.awt.EventQueue$3.run(Unknown Source)
>   at java.awt.EventQueue$3.run(Unknown Source)
>   at java.security.AccessController.doPrivileged(Native Method)
>   at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
>   at java.awt.EventQueue.dispatchEvent(Unknown Source)
>   at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:360)
>   at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
>   at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
>   at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
>   at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
>   at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
>   at java.awt.EventDispatchThread.run(Unknown Source)

After restarting any games in a host, you gets the above error and cannot see what your are writing in the host chat, while the others can, but only until the game is in progress.

For example, this is what I had in chat, under the conditions above:

> redrum has joined
> prastle:  cept myself
> Master_Yoda:  cut i hear the noise of me typing
> redrum:  Yo
> redrum:  Yes
> Master_Yoda:  yes
> prastle:  and yoda got hit by a lightsaber
> Master_Yoda:  caues you are a noob
> prastle:  cause yod sucks
> redrum:  Interesting
> prastle:  same here cer
> Master_Yoda:  FUCK ME DICE
> prastle:  yoda still sucks light abers
> redrum:  I do see any errors or issues
> prastle:  ya i said that too
> redrum:  don't*
> prastle:  sorta
> redrum:  Yeah

Then, prastle disconnected, and I get to see what I wrote:

> redrum has joined
> Cernel:  hi
> prastle:  cept myself
> Master_Yoda:  cut i hear the noise of me typing
> Cernel:  can you see what I write?
> redrum:  Yo
> redrum:  Yes
> Cernel:  I cannot see what I write
> Master_Yoda:  yes
> Cernel:  damn
> Cernel:  I cannot
> prastle:  and yoda got hit by a lightsaber
> Master_Yoda:  caues you are a noob
> Cernel:  I see you saying yes
> prastle:  cause yod sucks
> Cernel:  but none of what I write is displayed for me
> redrum:  Interesting
> prastle:  same here cer
> Cernel:  you want me to hopen an issue, or you do it red?
> Cernel:  do you get the java error?
> Master_Yoda:  FUCK ME DICE
> prastle:  yoda still sucks light abers
> redrum:  I do see any errors or issues
> prastle:  ya i said that too
> redrum:  don't*
> prastle:  sorta
> Cernel:  ok
> Cernel:  so I open the issue
> redrum:  Yeah

**Comment by Cernelius** [comment]
It seems there is not the issue the first game you host, but it happens when you restart.

> Cernel:  let's try if the chat works
> Master_Yoda:  test
> Cernel:  uaeouaoeu
> Master_Yoda:  YEAHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHO
> Cernel:  it seems that now it works
> Master_Yoda:  what did you do?
> Cernel:  nothing
> Raville:  probe
> Cernel:  aoueoa
> Cernel:  uhm
> Master_Yoda:  t
> Master_Yoda:  t
> Master_Yoda:  lol
> Cernel:  ok
> Master_Yoda:  i got the error
> Cernel:  now it doesn't anymore
> Master_Yoda:  and now the shit
> Master_Yoda:  what did you do?
> Cernel:  so it happens when you reload
> Cernel:  it happens when you reload the game for a second time in the same host

In the above, first I started the game, and there was not the issue, then I restarted it (in the same host), and there was it.

> WARNING [AWT-EventQueue-0] UnifiedMessenger -> null
> java.lang.NullPointerException
> 	at games.strategy.engine.chat.ChatMessagePanel.lambda$addMessageWithSound$16(ChatMessagePanel.java:213)
> 	at games.strategy.engine.chat.ChatMessagePanel$$Lambda$129/1871772240.run(Unknown Source)
> 	at games.strategy.engine.chat.ChatMessagePanel.addMessageWithSound(ChatMessagePanel.java:237)
> 	at games.strategy.engine.chat.ChatMessagePanel.addMessage(ChatMessagePanel.java:205)
> 	at games.strategy.engine.chat.Chat$1.chatOccured(Chat.java:270)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeSingle(EndPoint.java:172)
> 	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeMultiple(EndPoint.java:150)
> 	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeLocal(EndPoint.java:132)
> 	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.invoke(UnifiedMessenger.java:153)
> 	at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:47)
> 	at com.sun.proxy.$Proxy2.chatOccured(Unknown Source)
> 	at games.strategy.engine.chat.Chat.sendMessage(Chat.java:198)
> 	at games.strategy.engine.chat.ChatMessagePanel.lambda$new$19(ChatMessagePanel.java:335)
> 	at games.strategy.engine.chat.ChatMessagePanel$$Lambda$105/2040436008.accept(Unknown Source)
> 	at games.strategy.ui.SwingAction$1.actionPerformed(SwingAction.java:42)
> 	at javax.swing.SwingUtilities.notifyAction(Unknown Source)
> 	at javax.swing.JComponent.processKeyBinding(Unknown Source)
> 	at javax.swing.JComponent.processKeyBindings(Unknown Source)
> 	at javax.swing.JComponent.processKeyEvent(Unknown Source)
> 	at java.awt.Component.processEvent(Unknown Source)
> 	at java.awt.Container.processEvent(Unknown Source)
> 	at java.awt.Component.dispatchEventImpl(Unknown Source)
> 	at java.awt.Container.dispatchEventImpl(Unknown Source)
> 	at java.awt.Component.dispatchEvent(Unknown Source)
> 	at java.awt.KeyboardFocusManager.redispatchEvent(Unknown Source)
> 	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(Unknown Source)
> 	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(Unknown Source)
> 	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown Source)
> 	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
> 	at java.awt.Component.dispatchEventImpl(Unknown Source)
> 	at java.awt.Container.dispatchEventImpl(Unknown Source)
> 	at java.awt.Window.dispatchEventImpl(Unknown Source)
> 	at java.awt.Component.dispatchEvent(Unknown Source)
> 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
> 	at java.awt.EventQueue.access$500(Unknown Source)
> 	at java.awt.EventQueue$3.run(Unknown Source)
> 	at java.awt.EventQueue$3.run(Unknown Source)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
> 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
> 	at java.awt.EventQueue$4.run(Unknown Source)
> 	at java.awt.EventQueue$4.run(Unknown Source)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
> 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
> 	at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:360)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
> 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
> 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
> 	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by Cernelius** [comment]
Since it got into the pasted chat, I'm not against the removal of the old skin mapskin of 270BC from download list.
It's up to the various people that like it to ask for it, if they want to (I know there are several).

**Comment by ron-murhammer** [comment]
Yeah this is a pretty annoying bug as the error seems to pop up rather frequently.

**Comment by ron-murhammer** [comment]
@DanVanAtta If you have some time, I'd appreciate if you can take a look at this one. I know you did some refactoring a small changes around the Chat stuff. Not sure if this is just a missed null check somewhere or a sequence/sync issue.

**Comment by Cernelius** [comment]
It's verified it's a general problem; just one of many cases:

> (21:32:37) hans:  strange
> Master_Blaster has joined
> (21:32:51) hans:  in the game all text I type is deleted when I click send
> Master_Blaster has left
> Longstreet23 has left
> dalecoots has joined
> AmericanKnight (1) has left
> dalecoots has left
> LittleAK has joined
> KingKelly has joined
> (21:37:31) Elenol:  If it's easy to do, someone might consider a brief "Known Issues" that comes along with the intro text (along with the Migration Notes, FAQ, etc)
> AdamF has left
> (21:37:45) Elenol:  I'm sure the mods get tired of addressing the same concerns repeatedly
> Master_Yoda has left
> (21:39:07) hans:  I have typed often before
> Master_Yoda has joined
> (21:39:35) hans:  In the previous version I never had that problem and initially neither here
> (21:39:55) Elenol:  I hvaen't seen the issue myself
> (21:40:03) Elenol:  I think they're saying currently with the bots it is happening sometimes
> (21:40:11) hans:  ok
> (21:40:27) Elenol:  When someone checks in who knows better, I'm sure they can give a better answer. =)
> elbert70 has joined
> elbert70 has left
> Longstreet23 has joined
> (21:42:22) hans:  good to know though that others have a similar problem; hopefully a minor issue of the new version

**Comment by DanVanAtta** [comment]
Can this problem be summarized?

**Comment by Cernelius** [comment]
@DanVanAtta Summarised in the first post.

**Comment by DanVanAtta** [comment]
patch fix: https://github.com/triplea-game/triplea/pull/1338 submitted. It's not a deep fix, but the chat should continue working. We might see further downstream errors, I suspect not - but we'll have to look at those if they come up when they do.
