### ISSUE TITLE
Windows Installer Creates 2nd .exe That Doesn't Do Anything

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#1299]
Creates triplea-headless.exe which most users shouldn't see and it doesn't seem to work. We've always just included scripts for hosting bots like the one I added here: https://github.com/triplea-game/lobby/blob/master/run_hosted_bot.bat

**Comment by ron-murhammer** [comment]
@DanVanAtta Any idea why this second .exe is being included and why the bot hosting scripts were removed?

**Comment by DanVanAtta** [comment]
I think it was included for legacy reasons, the last installer did so. We are not using that executable for running bots, and it does not work - #1389 removes it.
