### ISSUE TITLE
Paratrouper only takes shortest path

### ISSUE THREAD

**Issue by etoilebleu** [triplea-game/triplea#1300]
Small issue, but the bomber/paratrouper only takes the shortest path to an enemy territory.
If there is a longer route, you cannot choose to take that path.

It's only a problem when the shorter route passes a different enemy territory first;
Ex. I want to drop in territory B, but am forced to pass territory A first so therefore I cannot drop on B.
Even though there is another (longer) path that passes through friendly territory leading to B.

V.1.8.0.9 Windows 1942 v3 Map

**Comment by ron-murhammer** [comment]
@etoilebleu Can't you move one territory at a time or use Shift to have way points?

**Comment by etoilebleu** [comment]
@ron-murhammer 
wow. Fast reply!

No, moving one territory at a time, or Shift, is "red X: not enough transports".
When you click it cancels the paratroup attempt.

btw: Thank you for your help with this project. It's awesome!

**Comment by ron-murhammer** [comment]
@etoilebleu Alright. If you have a save game demonstrating the problem, please upload it here so we can take a look.

**Comment by simon33-2** [comment]
Isn't it ctrl to add waypoints? Shift to add all units, which explains the not enough transports message.

**Comment by Cernelius** [comment]
@simon33-2 Correct; keep Ctrl pressed and set the path.

But this can become a good feature request (automatically select the shortest route amongst the possible ones), as it is quite hard to figure out, even tho, as far as I know, it fully works (or at least fully worked), for paratroopers.

**Comment by Cernelius** [comment]
Generally speaking, it would be good if the engine never obliges you to use Ctrl to set the path, but automatically selects one of the shortest paths amongst the possible ones, if any. This is relevant also in a map like WAW in which you have islands canal that you may get around in 2 moves, while the game stuck you on the impossible single move through the canal, and you cannot do it in 2 steps if in the territory in between there is a sea unit your submarine can go through but not into, during Non Combat Move.

Anyway, this is (or at least was) not a bug, as you can do what you want by using Ctrl to set the path.

**Comment by etoilebleu** [comment]
That's it, ctrl to add waypoints works.

The red circle X is still there when you click (as the territory is not the first enemy territory), but it does add the waypoint.
That lets you manually select a longer route for the paratrouper.
Thanks @simon33-2
