### ISSUE TITLE
Make Easier To Find Info And To Learn How To Host Bots

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#1301]
The WOPR hostbots are gone:
http://www.tripleawarclub.org/modules/newbb/viewtopic.php?post_id=17303

Most people will think that all the WOPR bots are gone because of the new release, while it just happened in the course of its releasing.
So, the task would be to make easier for anyone willingly to learn how to host bots (with no need to be very tech savy) and then cross fingers somebody takes over for Frankie.

Also @ron-murhammer told me that the istructions in WarClub are outdated:
http://www.tripleawarclub.org/modules/newbb/viewtopic.php?topic_id=996

I think the WarClub should be the foremost place where to explain how to host bots.

Some feedback from the lobby:

> BammBamm75 has joined
> (01:26:50) Cernel:  even that Longstreet23
> (01:26:54) Cernel:  hi longstreet
> (01:26:58) BammBamm75:  where are all the bots.......some need to be added
> (01:27:09) Master_Yoda:  BAM
> (01:27:16) BammBamm75:  3 bots when the old room used to have 20
> (01:27:37) Cernel:  the WarClub bots were 3 there too
> mrdiamond has joined
> (01:28:11) Cernel:  for bots evelution info:
> (01:28:12) Cernel:  http://www.tripleawarclub.org/modules/newbb/viewtopic.php?post_id=17308
> (01:28:28) Cernel:  did you try to click on that "Host Game" button on your left?
> (01:28:32) BammBamm75:  so why are there no other bots here then>?
> (01:29:08) dust:  o wow
> (01:29:13) BammBamm75:  cant host 
> (01:29:21) BammBamm75:  so where are all the bots?
> (01:29:58) Cernel:  gone
> (01:30:09) Cernel:  just read the Topic I linked
> (01:30:18) BammBamm75:  and will they be back or are they trying to kill this place?
> AmericanKnight has joined
> (01:30:32) dust:  ok i will say that i can now host
> (01:30:39) dust:  never been able to do that before
> (01:30:41) Cernel:  they won't be probably back, as you can read in that Topic, as I said
> (01:30:47) BammBamm75:  i just wanna play no read links
> (01:30:50) Cernel:  good for you dust
> elbert70 has joined
> (01:31:00) dust:  anyone want to try and join my host
> (01:31:03) dust:  just to see if it works?
> (01:31:10) Cernel:  need 1 more in my multi
> Mezten has left
> KingKelly has left
> AmericanKnight has left
> mrdiamond has left
> PYD has left
> (01:33:27) Forkman57:  long  u in here ?
> (01:33:43) Longstreet23:  join my host
> (01:34:13) Master_Yoda:  need one baby eating carthaginian
> (01:34:35) BammBamm75:  You couldnt just say there are down do to harware fail?

...

> warthunder has joined
> (01:45:09) Cernel:  need 1 my multi
> (01:45:24) warthunder:  am i in the new zone?
> Ichabod1862 has joined
> (01:46:26) warthunder:  is this the new and improved site?
> (01:47:21) elbert70:  y
> (01:48:06) Cernel:  yes, new improvements and new bugs :)
> (01:48:10) BammBamm75:  not improved
> playin has joined
> Trojan has joined
> (01:48:48) BammBamm75:  no bots and lots of bugs
> Hippopotamus has left
> playin has left
> (01:49:03) warthunder:  oh lord
> Wagon has joined
> (01:49:21) Cernel:  Bamm, no bots has nothing to do with the release
> (01:49:22) BammBamm75:  good way to kill the place
> (01:49:28) Cernel:  there would be no bots in the old too
> (01:49:42) Cernel:  it is just a coincidence
> (01:49:44) BammBamm75:  ok bad timing then still blows
> (01:50:08) warthunder:  this is like when the restaurants stop carry thousand island dressing
> Wagon has left
> (01:50:55) Trojan:  anyone up to play?
> (01:51:00) BammBamm75:  well is there anyone who can host that wants to play NWO?
> (01:51:37) Nay:  AK, I can;t host games
> (01:52:05) warthunder:  me either...guess its back to playing 3 cushion
> (01:52:17) Cernel:  hey warthunder etc.
> (01:52:21) Cernel:  try to click on Host Game
> (01:52:31) Cernel:  maybe in new you can
> Patryn has joined
> (01:52:39) Ichabod1862:  hi patryn
> (01:52:46) Cernel:  cheers, you can
> (01:53:01) warthunder:  oh ok yeah i think it works thanks

**Comment by ron-murhammer** [comment]
@Cernelius I added the info here which is from AK: https://github.com/triplea-game/lobby#run-hosted-bots

This can probably be improved a little more but I think just referencing it from other places would be best.

**Comment by steve-yu** [comment]
Is there any information about how to automatically restart a bot if the lobby goes down and/or detect if connection to the lobby is lost?

**Comment by DanVanAtta** [comment]
@steve-yu , we need to add some code to do that robustly. Currently you have to restart the bot.

Anything left to do here?

**Comment by steve-yu** [comment]
@DanVanAtta Thank you.  I'll see if I can write a script to restart them then.

**Comment by Cernelius** [comment]
I don't think that it is currently easy to find info and to learn how to host bots. Main two items:
1) The bots stuff is not anymore in the download.
2) The WarClub topic about bots is outdated, and (afaik) there is nothing in the WarClub linking to the link @ron-murhammer  linked.
It was already quite hard to figure out how to host bots for others, and now it is much harder, and there is not an updated place where people can ask about this; the place is still this one (afaik):
http://www.tripleawarclub.org/modules/newbb/viewtopic.php?topic_id=996
It seems to me that this release made harder for people to host bots for others, or even think about doing it at all (because now even the bots stuff is gone from the installation, plus the longer drawn issue that the related Topic in the WarClub is outdated and I guess there is nobody teaching there).

It might be also worth considering readding in lobby a link to the instructions for hosting bots; Veqryn removed that after the WOPR almost covered the need.

**Comment by Cernelius** [comment]
For example, I've no clue if I should get the Windows x64 or the Windows x86 here.
http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
Also, why to oblige some people to download something like that? Wasn't it better like in 1.8.0.9 when you had the stuff already in the folder, and just needed some simple changes with notepad to make it work? Why to delete those?
Just saying, as I'm not interested hosting bots myself.
If the developers are fine with current, feel free to close this.

**Comment by Cernelius** [comment]
Also, I want to underline that @veqryn wanted only the bots hosted by the server to have "WarClub" in the name, while the current instructions appear to even encourage private hosters to label their bots as "WarClub" ones.
I think it is preferable that only the bots hosted by the server are called "WarClub", and I would suggest that being made into a Mod enforced rules, which is not yet (@veqryn used to take care of such details personally) (you need to inform the mods in the WarClub Bunker, preferably in a stickied Topic). If the main developers agree on this point, I believe the instructions linked by @ron-murhammer should be changed accordingly.

They currently are:

`triplea.name=Bot%BOT_NUMBER%_WarClub triplea.lobby.game.hostedBy=Bot%BOT_NUMBER%_WarClub`

**Comment by Cernelius** [comment]
> Is there any information about how to automatically restart a bot if the lobby goes down and/or detect if connection to the lobby is lost?
> 

> >@steve-yu , we need to add some code to do that robustly. Currently you have to restart the bot.
> 

> >> @DanVanAtta Thank you. I'll see if I can write a script to restart them then.

@steve-yu @DanVanAtta It is my understanding that is set via:

`triplea.lobby.game.reconnection=172800`

The default being in seconds, thus 2 days. Does that have issues if you like set it at 3600, to have it reconnecting after only 1 hour? Does the bot reconnect if there is a game in progress going on? Will it stop the game when that happens? Does that countdown start from the latests connection? I believe more info on this, and maybe others, items would be good.

**Comment by Cernelius** [comment]
I got it working by pasting the stuff inside the 1.8.0.9 bot file. Still I don't understand why to remove them from main installation.

Also, the map folder now is default to the preinstalled one, thus you only get the "Tutorial" as default. This doesn't seem a good default to me, and in 1.8.0.9 the default was to get all maps you get in a normal host.
I actually like this (new?) feature that you can set a bot maps folders different than your private one, but I think the default should be the same as normal hosts (if feasible), and I suggest being explained that you can customise it, and redirect to the default downloadedMaps, like:

```
Linux- /home/user/triplea/downloadedMaps
Windows 8, 7, Vista- C:/Users/YourName/triplea/downloadedMaps
Mac- /home/user/documents/triplea/downloadedMaps
```

I don't know if windows 10 or other recent stuff has different paths tho. Can anybody confirm this is fairly exhaustive?

**Comment by Cernelius** [comment]
As I said, this is just a general discussion, as I don't really intend to host bots myself.

**Comment by Cernelius** [comment]
For example:

> (21:49:20) Phyton:  how to create a bot to host a game?
> majorQ10 has joined
> (21:49:28) Cernel:  hi phyton
> (21:49:32) Phyton:  hi
> (21:50:07) Cernel:  https://github.com/triplea-game/lobby#run-hosted-bots
> markopolo187 has joined
> (21:51:03) blinchik:  hey ice, game?
> (21:51:14) Cernel:  You just slapped Navalland
> (21:51:15) Cernel:  hey navalland multi? we need 1
> (21:51:52) Phyton:  ok, thx

I find very unlikely that people will find those instructions by themselves.

**Comment by steve-yu** [comment]
Unfortunately the minimum timeout is not that much shorter than that 172800 parameter. I tried setting it to be less than a few hours and it rejected it.

**Comment by ron-murhammer** [comment]
@Cernelius I think we are mostly good on this for now. The only thing that could be done is updating forum posts to reference the instructions so they are easier to find (though I feel like most lobby players don't read the forums either).

**Comment by Cernelius** [comment]
I primarily suggest re-adding back all the bots file in the main installation (they were there in 1.8.0.9), and possibly having all explained how to set them up inside. That would cut the step of having to download the "Java SE Development Kit" and cut most of the need of having to search around for explanations in Forum etc..
I can host and rarely host bots, so anyway if you feel this can be closed I've no objections myself. Eventually if there is somebody interested in making a good bot service and propose himself in lobby or forum I think the mods can teach him.
I really don't understand why the bots files were removed tho; unless there is some reasons, I believe that was a bad move.

**Comment by DanVanAtta** [comment]
Added a link to: http://www.triplea-game.org/help/
Also linked to the same instructions from the github readme as well
