### ISSUE TITLE
Hosted Game Disconnects From Lobby When Switching To Old Engine Plus Errors (1.9.0.0.3266)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#1302]
Load a 1.8.0.9 savegame of "World War II v6 1941", click on "Yes & Close Current", get this error:

> Trying to play a map made for a newer version of TripleA. Map named 'Tutorial' requires at least TripleA version 1.9
> INFO [AWT-EventQueue-0] ChatController -> Chatter:Cernel port:3300 ip:82.60.36.149 is joining chat:games.strategy.engine.framework.ui.ServerStartup.CHAT_NAME
> host:45.79.144.53 port:3304
> games.strategy.engine.message.ConnectionLostException: Connection Lost
>   at games.strategy.engine.message.UnifiedMessenger.messengerInvalid(UnifiedMessenger.java:83)
>   at games.strategy.engine.message.UnifiedMessenger.access$000(UnifiedMessenger.java:31)
>   at games.strategy.engine.message.UnifiedMessenger$1.messengerInvalid(UnifiedMessenger.java:58)
>   at games.strategy.net.ClientMessenger.socketError(ClientMessenger.java:232)
>   at games.strategy.net.nio.NIOSocket.error(NIOSocket.java:85)
>   at games.strategy.net.nio.NIOReader.loop(NIOReader.java:143)
>   at games.strategy.net.nio.NIOReader.access$000(NIOReader.java:26)
>   at games.strategy.net.nio.NIOReader$1.run(NIOReader.java:48)
>   at java.lang.Thread.run(Unknown Source)
> Caused by: java.lang.Exception: Invoker Stack
>   at java.lang.Thread.getStackTrace(Unknown Source)
>   at games.strategy.engine.message.MessengerException.fillInInvokerStackTrace(MessengerException.java:19)
>   at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:53)
>   at com.sun.proxy.$Proxy7.postGame(Unknown Source)
>   at games.strategy.engine.framework.startup.ui.InGameLobbyWatcher.<init>(InGameLobbyWatcher.java:194)
>   at games.strategy.engine.framework.startup.ui.InGameLobbyWatcher.newInGameLobbyWatcher(InGameLobbyWatcher.java:129)
>   at games.strategy.engine.framework.startup.ui.ServerSetupPanel.createLobbyWatcher(ServerSetupPanel.java:75)
>   at games.strategy.engine.framework.startup.ui.ServerSetupPanel.<init>(ServerSetupPanel.java:65)
>   at games.strategy.engine.framework.startup.mc.SetupPanelModel.showServer(SetupPanelModel.java:50)
>   at games.strategy.engine.framework.startup.ui.MainFrame$2.run(MainFrame.java:131)
>   at java.awt.event.InvocationEvent.dispatch(Unknown Source)
>   at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
>   at java.awt.EventQueue.access$500(Unknown Source)
>   at java.awt.EventQueue$3.run(Unknown Source)
>   at java.awt.EventQueue$3.run(Unknown Source)
>   at java.security.AccessController.doPrivileged(Native Method)
>   at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
>   at java.awt.EventQueue.dispatchEvent(Unknown Source)
>   at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
>   at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
>   at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
>   at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
>   at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
>   at java.awt.EventDispatchThread.run(Unknown Source)

Then, the host is up, but not anymore connected to the lobby.

**Comment by DanVanAtta** [comment]
I don't think there is much we can do for this. We could disable the legacy game engine load feature, but it would be pretty painful to re-enable it when it is needed once again.

**Comment by DanVanAtta** [comment]
:white_flag:
