### ISSUE TITLE
Won't let me change map

### ISSUE THREAD

**Issue by nateusmc44** [triplea-game/triplea#13038]
I am stuck in a loop.  I tried to change the map to a middle earth map - it says it doesn't exist, but when I go to change the map to a different one, it just keeps coming up with a message to download the map I am trying to leave.  I uninstalled and reinstalled - nothing is working.

Nate
nmercer1111@gmail.com

**Comment by TheDog-GH** [comment]
Hi Nate
are you using the latest version?
https://github.com/triplea-game/triplea/releases

If not try and install that, hopefully it will fix your issues.

**Comment by TheDog-GH** [comment]
2 weeks old
