### ISSUE TITLE
TripleA Lobby "Exit" Leaves Ghost Of Current Lobby (1.9.0.0.3266)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#1305]
Click on:
File/Exit
and a new TripleA will open, but the current one appears not closing.
Yet, you indeed disconnected from lobby, and the current one just stays there dead (you notice that something is wrong because nobody talks or anything).
It closes fine for me using the "X" icon, instead.

**Comment by Cernelius** [comment]
Also, there may be other problems beside or related to this, this is the referring lobby chat log:

> champ73 has joined
> (04:46:25) prastle:  hi c
> Feanor75 has left
> (04:46:29) champ73:  join
> Feanor75 has joined
> (04:47:12) champ73:  please
> Feanor75 has left
> champ73 has left
> (04:53:15) prastle:  You were slapped by prastle
> (04:53:24) prastle:  did you explain to champ?
> (04:53:43) Cernel:  me what?
> (04:53:53) prastle:  ur git hub note
> (04:54:06) prastle:  he upset gigglez
> (04:54:14) prastle:  think we good now
> (04:54:18) Cernel:  what?
> (04:54:37) prastle:  wait a bit see if he rejoins
> Nay has left
> (04:54:52) Cernel:  what is the problem exactly?
> (04:55:20) Cernel:  what note?
> (04:55:21) prastle:  32 bit install and needed 64 i think
> (04:55:59) prastle:  ur 7 i recieved his am
> (04:56:01) prastle:  from git hub
> (04:56:07) prastle:  this
> (04:56:31) Cernel:  give me a link
> (04:56:43) prastle:  dosnt matter
> (04:56:57) prastle:  all i was asking is if you explained
> (04:57:04) prastle:  cause i couldnt
> champ73 has joined
> (04:57:16) prastle:  he left to fast after swearing
> (04:57:18) prastle:  ;)
> (04:57:24) champ73:  who me?
> (04:57:33) prastle:  yes u
> champ73 has left
> (04:57:56) Cernel:  uhm this is becoming weird
> (04:58:16) prastle:  dont matter
> (04:58:30) prastle:  he isnt in the con long enough to listen
> chessnerd (1) has joined
> (04:58:41) prastle:  note rejin and left time
> (04:58:42) chessnerd (1):  nice game elbert
> (04:58:45) elbert70:  u 2
> (04:58:57) elbert70:  did u see my chat?
> (04:59:00) chessnerd (1):  no
> (04:59:06) elbert70:  didnt think so
> (04:59:09) chessnerd (1):  lol
> (04:59:10) elbert70:  gg
> (04:59:10) Cernel:  so are you saing he can't stay connected in lobby but he keeps disconnecting
> (04:59:14) chessnerd (1):  that explains a lot
> (04:59:19) Cernel:  and this happened with the new release
> (04:59:23) prastle:  no ignore above
> (04:59:25) elbert70:  yes try 2 respond
> (04:59:35) prastle:  till ya can talk him through
> (04:59:37) chessnerd (1):  want to play agian
> (04:59:40) prastle:  the install
> (04:59:48) elbert70:  need 5 mins 
> (04:59:50) chessnerd (1):  some of it i saw
> (04:59:54) chessnerd (1):  not all thogh
> (04:59:59) chessnerd (1):  ok
> (05:00:04) elbert70:  ok
> (05:00:04) prastle:  yes
> (05:00:14) prastle:  all from new release
> (05:00:25) Cernel:  but he is upset at whom?
> (05:00:29) Cernel:  at me?
> (05:00:39) prastle:  all of us :)
> (05:00:44) prastle:  give him a day
> (05:00:46) prastle:  :)
> (05:01:26) prastle:  blue room at developers mods and general
> (05:01:30) prastle:  ;)
> (05:01:43) Cernel:  idk what a blue room is
> (05:02:06) prastle:  alot of words that are impolite filing air waves
> MooCow has joined
> (05:02:37) Cernel:  but just to be sure, the current release keeps crashing on him and he can't stay connected but briefly?
> (05:02:41) prastle:  main pt is
> (05:02:59) prastle:  he has to reinstall every time
> (05:03:05) prastle:  and close with task manager
> xeyo has left
> MooCow has left
> (05:03:19) prastle:  win 8 older comp
> (05:03:29) Cernel:  reinstall? that sonds very bad
> (05:03:37) prastle:  yes
> (05:03:56) prastle:  but he didnt stick around long enough for m to get more info
> (05:04:26) Cernel:  well, this is too general to make a bug report out of it, hopefully he does
> (05:04:40) prastle:  ur turn ;)
> (05:04:52) General_Zod:  dust rejoin
> uboat248 has joined
> (05:05:54) General_Zod:  rejoin plz
> uboat248 has left
> (05:06:23) Cernel:  so, does the game just crashes like that after some time?
> (05:06:39) AmericanKnight:  when ever someone leaves room
> (05:06:41) prastle:  nidea bro
> (05:06:41) Cernel:  and is this happening only in new release?
> (05:06:42) General_Zod:  dust left, crashed it
> (05:06:43) prastle:  got  slap
> (05:06:47) Cernel:  really
> (05:06:49) Cernel:  if a guest
> (05:06:52) Cernel:  leaves the room
> (05:06:55) AmericanKnight:  nope just player
> (05:06:56) Cernel:  the game crashes???
> (05:07:02) Cernel:  ok
> (05:07:07) Cernel:  well that always happened
> (05:07:08) AmericanKnight:  like normal
> (05:07:09) prastle:  got a java error
> (05:07:11) Cernel:  nothing new
> (05:07:15) elbert70:  chess nerd
> (05:07:15) Cernel:  ok so all normal
> (05:07:21) Cernel:  guess somebody got bad connection
> (05:07:33) General_Zod:  yeah looks like a typical disc deal
> champ73 has joined
> Wolfrequiem has joined
> (05:08:10) prastle:  @ zod
> (05:08:11) General_Zod:  it was just getting interesting too
> (05:08:23) prastle:  was i still listed in your room?
> (05:08:36) General_Zod:  i dont think so
> (05:08:47) prastle:  pt im saying is
> (05:08:54) prastle:  a java discon error
> (05:09:02) prastle:  when it closed
> (05:09:03) champ73:  well i dl'ed 62 bit, still have both problems
> (05:09:08) prastle:  after te fact
> (05:09:20) Cernel:  champ you should make bug report
> (05:09:21) AmericanKnight:  yes that part is new, when someone playing drops it give java error now rathere than just close room
> (05:09:27) prastle:  so stick around and chat br
> (05:09:31) Cernel:  with screenshot and everything detailed as much as possible
> (05:09:37) prastle:  @ champ
> (05:09:44) champ73:  cannot exit without task manager, must install game every time to enter lobby
> Patryn has joined
> (05:09:54) Cernel:  you need to register in GitHub
> (05:09:55) Cernel:  https://github.com/triplea-game/triplea/issues
> (05:09:55) prastle:  told him
> (05:10:03) dust (1):  argf
> (05:10:10) Cernel:  that sounds really bad
> (05:10:21) champ73:  so, registering in github fixes problems?
> (05:10:44) prastle:  n allows u to post screen shots of probs
> (05:10:45) Cernel:  registering in github, then opening an issue and describing the problems might
> (05:10:53) prastle:  so it can be fixed
> (05:11:04) elbert70:  ready to go?
> owner has left
> (05:11:15) Cernel:  that's surely something that should be fixed
> (05:11:25) champ73:  hey, i got a radical idea...why not fix problems BEFORE encouraging migration from old lobby
> (05:11:47) Cernel:  well if people playtest the prerelease and report bug that is possible too
> (05:11:47) prastle:  adly you are he only one to bring this one up
> dust has joined
> (05:12:17) champ73:  so not one person has reported these problems?
> (05:12:33) Elenol:  I haven't seen anyone say anything like this
> (05:12:36) prastle:  not a reinstall and tak manager leave no
> (05:12:40) dust:  trying to join
> (05:12:49) champ73:  every one else here can exit using File/Exit?
> (05:12:50) prastle:  ur the only one
> (05:12:52) Cernel:  I guess not (even tho sometimes bug are not corrected depending on developers judgment of their importance)
> (05:12:56) prastle:  chat issues yes
> Wolfrequiem has left
> (05:13:21) champ73:  every one else here can exit using File/Exit?
> (05:13:27) Cernel:  I can
> (05:13:33) prastle:  si
> champ73 has left

...

> (05:31:47) Cernel:  hey prastle
> (05:31:53) Cernel:  looks like champ was right
> (05:31:54) prastle:  ya c
> (05:32:07) prastle:  never said he was wrong
> (05:32:15) Cernel:  if you click on File/Exit you exit lobby, but it stays up as a ghost
> (05:32:22) prastle:  just needed him to explain prove

**Comment by Cernelius** [comment]
I'm posting it here, because it might be the same matter, or anyway I don't feel like opening an issue for this, since I believe the matter is too vague:

> General_Zod has joined
> General_Zod:  hi cernel
> General_Zod:  wierd says 270bc in lobby, in here says ww2 v6
> General_Zod:  You were slapped by General_Zod
> Cernel:  hey
> Cernel:  well last time I said v6
> Cernel:  so what do you want
> Cernel:  and multi or 1v1?
> General_Zod:  multi
> Cernel:  hey but you are not in lobby?
> Cernel:  ok multi of what?
> General_Zod:  ah
> General_Zod:  tht why i c 270bc in lobby
> General_Zod:  i reopen it
> General_Zod:  brb
> General_Zod has left
> General_Zod has joined
> General_Zod:  better now
> General_Zod:  il do a multi, of 270bc 40% , or i consider oter multis too
> General_Zod:  depends which
> Cernel:  ok
> Cernel:  but
> Cernel:  what did you mean? how did you join my host without being in lobby?
> General_Zod:  i have a map making question, when creating a map skin, is it possible to add multiple layers of relief tiles, eg, reliefTiles and then reliefTiles2
> Cernel:  can you first answer
> Cernel:  that
> Cernel:  how did that happen
> General_Zod:  i was in lobby for a while
> Cernel:  no, you weren't in lobby for a while
> Cernel:  before joining my game, and you still weren't listed
> General_Zod:  but it musta stopped working properly somewhere over the time i was in lobby
> Cernel:  did you click on File/Exit
> General_Zod:  nope
> Cernel:  ok

Practically, this user was not in the lobby for about 1 hour (not listed in my lobby screen and was recorded to have left about 1 hour before joining my host), but he had a lobby ghost up and he was able to join my private host through it, regardless.
So, it seems more like he was sort of still in lobby, but not figuring in it and not having it updated (not seeing new chat messages etc.; this is why he was surprised about not 270BC, since he didn't see me asking for v6).

**Comment by DanVanAtta** [comment]
Spotted where to fix the first part of this issue, a new release with a patch should be out soon.

For the second part, sounds like a possible combination of different problems with previous versions. Alternatively it is a newly identified issue. A clean bug report if it is still happening would be really appreciated, and perhaps the only effective way to continue working that problem.
