### ISSUE TITLE
TripleA 2.6.14526 failed to load new maps

### ISSUE THREAD

**Issue by Grinchveld** [triplea-game/triplea#13054]
TripleA 2.6.14526 failed to load new maps

I click on the download maps button and get 
"FeignException$NotFound: [404 Not Found]

**Comment by beelee1** [comment]
@Grinchveld 

yea, i can't remember why it did that. Anyway, latest prerelease should work https://github.com/triplea-game/triplea/releases/

**Comment by TheDog-GH** [comment]
2 weeks old
2.5 is not supported, upgrade to 2.7, as this does not happen in 2.7
https://github.com/triplea-game/triplea/releases
