### ISSUE TITLE
BattleCalc Add Ability to Change Unit Damage

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#1307]
In the battle calc you can't add say a damaged battleship to one of the sides.

**Comment by Cernelius** [comment]
This is an annoying problem for all maps having any multiple hitpoints units not automatically repairing by end of turn. It is another case of something in between a Bug and a New Feature, as you cannot really use the battlecalculator on such maps, so it might be argued it is closer to a Bug (it makes impossible to calculate when it is relevant).

Also, it might be argued it is close to a Bug with no workarounds, as the workaround of editing some damaged units may not work in some cases (politics with different frontiers, etc.).
