### ISSUE TITLE
Pardon Our Interruption

### ISSUE THREAD

**Issue by mymev** [triplea-game/triplea#13086]
https://shop.simplemobile.com/shop/en/simplemobile/phones?_gl=1*10s340r*_gcl_au*OTY1MjYyMTQ1LjE3MzU1NTQzMzQ.*_ga*MTg4MzYwOTQ0Ny4xNzM1NTUzOTA5*_ga_C13JTC30B7*MTczNTU1MzkwOC4xLjEuMTczNTU1NTExNi4wLjAuMA..

**Comment by TheDog-GH** [comment]
Spam
