### ISSUE TITLE
Enhance Fuel Movement

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#1310]
Several fuel issues that need enhanced are listed here: https://sourceforge.net/p/triplea/feature-requests/255/

**Comment by FrostionAAA** [comment]
Nice to see that people have seen these fuel issues before :-)
This is my opinion on that old post and ideas:

**Transported units**
I am in favor of all transported units NOT consumeing fuel. Land and sea alike, like when fighters follows a carrier. Not even if they are transported into combat … just to keep rules simple.

**Fuel indication at combat/noncombat**
It would be awesome if there was an indicator that worked like the movement indicator at the mouse pointer. Like right now the indicator say for example “2 / 6”. But maybe this indicator could be expanded to say like “2 Moves / 4 Total / 4 Fuel“ when a 4-move air unit moves 2 moves into combat and reserves 4 Fuel resources to make the move and want to be able to return. Also it should be possible to work with other resources. So it could say something like, when moving an Armored Company land unit, “2 Moves / 2 Total / 2 Supplies”.
Or maybe just ”2/2/2” if we don’t want words.

**Fuel consumption for defender**
I would argue against this being a standard rule. I would say that the fuel needed by real life fuel consuming military units to sit around and wait for the enemy and fight inside a given territory would not be anything near the fuel that units on the move would need. Maybe this could and should be optional via a property true/false. (Just like I don’t think fighters transported into sea zone combat should use fuel to fight)

**Comment by ron-murhammer** [comment]
From #1804:

I know that not many maps use fuel. But if more maps are to experiment with this it might be a good idea to support the fuel feature a bit more. Or food supplies or whatever “fuel” units need.

Right now when units use fuel there is no way of knowing how much fuel is available, unless the player opens up the economy tab when moving units around. And this leads to the player being constantly forced to swap between the Action and Economy tabs. It would be nice to have an easy overview and since fuel is a movement thing, I would suggest it displayed when any moving of fuel-using units take place.

Here is what I propose, and I have no idea how hard this would be to implement, and this red text should of course only be displayed for units consuming fuel and be the fuel type for the specific unit. In this mockup setting the player has 26 fuel left to use, so first move leaves the player with 25, the next 24:

![unavngivet1](https://cloud.githubusercontent.com/assets/15268177/26761457/2362851a-4930-11e7-9be7-c8d1049b7017.png)

![unavngivet](https://cloud.githubusercontent.com/assets/15268177/26761461/2c49afaa-4930-11e7-8741-de34b5765145.png)
