### ISSUE TITLE
Triple A for iOS... 

### ISSUE THREAD

**Issue by madpoet11** [triplea-game/triplea#1313]
Hello... 
I was just wondering if it would be possible to create an iOS version compatible with Triple A. These games, especially all the Axis and Allies variants, would be a perfect fit for an Apple iPad for example. I don't see the difficulty in making this possible. Thank you very much for your time.

**Comment by ron-murhammer** [comment]
@madpoet11 Not unless iOS decides to support Java.

**Comment by madpoet11** [comment]
Gotcha... So Java is the only issue. Figured as much. Thanks.
