### ISSUE TITLE
MARTI dice server seems to be unavailable

### ISSUE THREAD

**Issue by steve-yu** [triplea-game/triplea#1314]
The dice server at http://dice.tripleawarclub.org/ is returning an error when attempting to generate a dice roll.

Here is the error log:

Test
Contacting  dice.tripleawarclub.org

Error: email delivery failed

Text from dice server:

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>	M.A.R.T.I. Server --> "more accurate rolls than irony"- server</title>
</head>
<body>
<br />
<b>Deprecated</b>:  mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in <b>/usr/share/nginx/html/tripleawarclub.org/public_html/dice/dice.class.php</b> on line <b>39</b><br />
<p>Email delivery failed...</p> Dice results were not sent. <br> Please try it later again.<p>fatal error: email delivery failed!

**Comment by ron-murhammer** [comment]
@steve-yu Yeah the dice server is down right now. We are looking into it.

**Comment by steve-yu** [comment]
@ron-murhammer It appears to be back up now.  Thank you!
