### ISSUE TITLE
Route Drawer Does Not Wrap For Observer (1.9.0.0.3266)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#1315]
The route drawer does not wrap when observing a move made by someone else in a hosted game.
![bug_20161101](https://cloud.githubusercontent.com/assets/19562310/19875824/61eff696-9fd0-11e6-9504-a531c71b6f38.png)

I've loaded the game on local at this point, and verified that it wraps correctly when you are playing with yourself. I assume it can be reproduced with any wrapping maps.

**Comment by ron-murhammer** [comment]
That is very interesting.

**Comment by RoiEXLab** [comment]
Could reproduce this issue;
It's interesting this only happens when a direct path is drawn from the west to the east

**Comment by RoiEXLab** [comment]
#1431 is out to fix this issue

**Comment by RoiEXLab** [comment]
@Cernelius could you please convince @DanVanAtta that this issue is fixed using my latest PR? 😁

**Comment by DanVanAtta** [comment]
@Cernelius , do you know how to test out other people's branches? Even professional developers can have difficulty there (though that has a lot more to do with git experience than anything else).

@RoiEXLab , it's more so we have independent confirmation of a fix. Our CR process as agreed upon pretty long ago is that the reviewer should also test out the changes as well, so that we can get some additional testing and try and avoid bugs. Now that we are in a mode where each merge is potentially a new release, each one should be very solid.

**Comment by Cernelius** [comment]
> @Cernelius , do you know how to test out other people's branches?

No. Are normal users (development wise) supposed to learn that for making bug reports?

**Comment by RoiEXLab** [comment]
No, but it is useful ^^
Since the PR is merged already you can test this by simply installing the latest prerelease

**Comment by Cernelius** [comment]
Okey dokey.

I mean, I'm not interested in learning anything, but, if you really want to, I may try to look at it, if taught. I'm guessing then maybe better to make it into a documentation, for power users, rather than just teaching me.

Anyway, no matter. I'll run latest and see here.

**Comment by RoiEXLab** [comment]
Good suggestion... 
Since we don't want to require anyone to install development tools, we could just tell the users to download the right branch instead of teaching them git.
That combined with a gradlew run command should do the trick...
What do you think @DanVanAtta ?

**Comment by Cernelius** [comment]
Now it appears working sensibly:

![20170116](https://cloud.githubusercontent.com/assets/19562310/21967469/3820ba8c-db88-11e6-9346-7a0e2a9a0ce5.png)

**Comment by DanVanAtta** [comment]
It's perhaps worth documenting how to check out and run remote branches. It's challenging to keep it really simple..
