### ISSUE TITLE
Absence Of The Mapskin "new_world_order-skin_gudkarma_1" In Repository (1.9.0.0.3266)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#1316]
Why is the "new_world_order-skin_gudkarma_1" not in the repository?
https://github.com/triplea-maps
This skin is available for 1.8.0.9 (I don't think I've ever used it, but I don't play NWO).

Lobby report as of today:

> (22:56:34) moimemme:  hi, want to cont?
> (22:56:43) DayMar:  hi
> williamilsanguinario has joined
> (22:56:51) DayMar:  was just thinkin how to say
> (22:57:00) DayMar:  agreed vs someoneelse just
> (22:57:05) moimemme:  ok
> (22:57:07) DayMar:  waits a bit
> (22:57:11) DayMar:  but..
> (22:57:24) DayMar:  did u have save and old lobby still?
> (22:57:27) DayMar:  i deleted all
> (22:57:38) DayMar:  not sure when its close forever
> (22:57:54) Cernel:  you can still host games directly with the old engine
> (22:58:01) DayMar:  ok
> (22:58:07) DayMar:  so u got file ?
> (22:58:07) Cernel:  you don't need the lobby to play live, plus you can play by email
> (22:58:17) DayMar:  a Cernel
> (22:58:22) DayMar:  rly?
> (22:58:25) Cernel:  yes
> (22:58:28) DayMar:  i want to play live
> (22:58:35) Cernel:  yes, just host directly
> (22:58:36) DayMar:  now?
> moimemme has left
> (22:58:43) DayMar:  ok
> (22:58:44) Cernel:  "Host Networked Game"
> (22:58:47) DayMar:  no answer
> (22:58:53) DayMar:  but left
> (22:59:12) DayMar:  green roma fits anyways
> (22:59:19) DayMar:  np deletin that
> (22:59:19) Cernel:  you can try to do it
> (22:59:23) Cernel:  now with me
> (22:59:30) Cernel:  start the old 1.8.0.9
> (22:59:36) DayMar:  i have no old
> (22:59:38) Cernel:  and click on host networked game
> (22:59:43) DayMar:  i deleted
> (22:59:47) Cernel:  uh why?
> (22:59:48) Cernel:  lol
> flightpath has joined
> (22:59:58) Cernel:  well you can also redownload it
> (23:00:02) Cernel:  it is still disposable
> (23:00:11) DayMar:  caue normal hosting and playin here not works proper
> (23:00:23) DayMar:  dont need more tryin things
> (23:00:25) Cernel:  has nothing to do with old
> (23:00:53) DayMar:  to much hollywood again
> (23:00:58) DayMar:  only wants to play
> (23:01:16) DayMar:  dont care for save older then couple weeks anyways
> (23:01:26) DayMar:  nothin to do with lobby:)
> (23:01:51) DayMar:  map skins missing
> (23:02:02) Cernel:  map skins missing
> (23:02:06) Cernel:  there are the mapskins
> (23:02:12) Cernel:  but are partially bugged
> (23:02:13) DayMar:  it was 4
> (23:02:16) DayMar:  now its 2
> (23:02:20) Cernel:  2 what?
> (23:02:32) DayMar:  nwo got map skins several
> (23:02:35) DayMar:  included
> (23:02:44) DayMar:  told u yesterday
> (23:02:55) DayMar:  gudkarma not exist
> (23:03:13) Cernel:  there are 2 mapskins for new world order
> (23:03:15) DayMar:  hmm was 3
> (23:03:30) DayMar:  remind me 4
> (23:03:37) DayMar:  sieg
> (23:03:52) DayMar:  pulicat
> (23:04:22) DayMar:  well not the biggest problem just i love to switch all time
> Damon53 has left
> (23:04:53) Cernel:  ah but now you can't switch
> (23:04:58) Cernel:  the mapskins are also bugged
> (23:05:01) DayMar:  exactly

For the bug (regression) of being limited to 1 mapskin only, refer to:
https://github.com/triplea-game/triplea/issues/1249

**Comment by Cernelius** [comment]
For the bug (regression) of being limited to 1 mapskin only, redirect to:
https://github.com/triplea-game/triplea/issues/1323

**Comment by DanVanAtta** [comment]
IIRC there were swastikas in that skin and was removed.

**Comment by ron-murhammer** [comment]
@Cernelius Its added and available as in-game download: https://github.com/triplea-maps/new_world_order-skin_gudkarma_1
