### ISSUE TITLE
Cannot Join a Game

### ISSUE THREAD

**Issue by MadFritzy** [triplea-game/triplea#1318]
Hi my brother and are both having the same issues we can host a game but when we try to join we get the start menu for the game.  Not sure what the issue is.  Any thoughts.

**Comment by DanVanAtta** [comment]
A screenshot might help to clarify. There might also be an extremely long delay, could be worth leaving it for a while to check if that is the problem.

**Comment by ron-murhammer** [comment]
@MadFritzy Have you tried using a bot? Or joining someone else's game? It sometimes does take a minute or 2 for the game to initialize when joining.

**Comment by MadFritzy** [comment]
I have no problem joining another game.  I found if I host a game and use a
password for the other person to join it crashes.  If I don't use a
password for the other person to join they have no problem in joining.
Wierd.

**Comment by ron-murhammer** [comment]
@MadFritzy Yeah passworded games aren't functioning properly and we are tracking that bug here: #1303
