### ISSUE TITLE
Source code release goal and scope definition

### ISSUE THREAD

**Issue by gaborbernat** [triplea-game/triplea#132]
Hello, 

Can somebody enlighten me what's the scope of the source only zip release. At the moment Ant generates a lot of stuff that at first sight screams shouldn't be there. Trying to replicate with Gradle, however I want to know the goal and the scope of this release for that. Thanks a lot,

**Comment by DanVanAtta** [comment]
Github automatically creates a source only download. Currently that is the only thing available in github releases until we also start uploading artifacts.

**Comment by gaborbernat** [comment]
I was referring to the zip generated by ant.

**Comment by DanVanAtta** [comment]
So you're going to recreate that in gradle even though github automatically bundles it?

**Comment by gaborbernat** [comment]
Well we do create it now with the ant build. I'm asking if it's
required and what part of it :)

On 8/30/15, Dan Van Atta <notifications@github.com> wrote:
> So you're going to recreate that in gradle even though github automatically
> bundles it?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/triplea-game/triplea/issues/132#issuecomment-136162425


-- 
 Bernát Gábor
Student -  Budapest University of Technology and Economics - Computer
Engineering, M.Sc. - Budapest, Hungary
System Integrator - Gravity R&D | Rock Solid Recommendations - Budapest
office | 5-7 Expo ter | H-1101 | Budapest | Hungary

**Comment by DanVanAtta** [comment]
The source only zip was one of the release artifacts: https://sourceforge.net/projects/triplea/files/TripleA/1_8_0_7/

The new version of that page is: https://github.com/triplea-game/triplea/releases, which already has the source code zip. So it's pretty clear we do not need it, particularly since the Mac DMG and windows installer used the all_platform zip to build those artifacts, so by that token it appears the source-only zip  was purely a distribution artifact.

**Comment by gaborbernat** [comment]
Oh fine, so no need to make it part of the new release process, that's
just perfect for me.

On 8/30/15, Dan Van Atta <notifications@github.com> wrote:
> The source only zip was one of the release artifacts:
> https://sourceforge.net/projects/triplea/files/TripleA/1_8_0_7/
>
> The new version of that page is:
> https://github.com/triplea-game/triplea/releases, which already has the
> source code zip. So it's pretty clear we do not need it, particularly since
> the Mac DMG and windows installer used the all_platform zip to build those
> artifacts, so by that token it appears the source-only zip  was purely a
> distribution artifact.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/triplea-game/triplea/issues/132#issuecomment-136167372


-- 
 Bernát Gábor
Student -  Budapest University of Technology and Economics - Computer
Engineering, M.Sc. - Budapest, Hungary
System Integrator - Gravity R&D | Rock Solid Recommendations - Budapest
office | 5-7 Expo ter | H-1101 | Budapest | Hungary

**Comment by DanVanAtta** [comment]
:+1: 

Similar to the gradle shadowJar plugin, a huge chunk of ant code that can just disappear.  =D

**Comment by veqryn** [comment]
@gaborbernat: What does it generate that shouldn't be there?

**Comment by gaborbernat** [comment]
Ant generates a source only release, as I understand github automatically does this now; so no need to replicate it with Gradle.

**Comment by DanVanAtta** [comment]
@gaborbernat  or admins, good to close on this issue?

**Comment by gaborbernat** [comment]
Yes
