### ISSUE TITLE
Maps Folder Path Corrupted

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#1322]
Per Prastle:
triplea.engine.version.bin:1.9 
Error, downloaded maps folder does not exist: C:\Program Files\TripleA_1.9.0.0.3277\..\maps 
Error, downloaded maps folder does not exist: C:\Program Files\TripleA_1.9.0.0.3277\..\maps 

I downloaded about 20 diff versions all the way back to .2677  same error message. I also reinstalled stable first to see if that helped.  The error occurs also with .3266 and .3289 

This error comes from:
```
    final String path = ClientContext.folderSettings().getDownloadedMapPath();
    final File mapsFolder = new File(path);
    if (!mapsFolder.exists()) {
      try {
        mapsFolder.mkdirs();
      } catch (final SecurityException e) {
        ClientLogger.logError(e);
      }
    }
    if (!mapsFolder.exists()) {
      ClientLogger.logError("Error, downloaded maps folder does not exist: " + mapsFolder.getAbsolutePath());
    }
```
And DownloadedMapPath():
```
public String getDownloadedMapPath() {
    // return the override first, then user maps folder preference, then the default
    return SystemPreferences.get(SystemPreferenceKey.MAP_FOLDER_OVERRIDE,
      SystemPreferences.get(SystemPreferenceKey.USER_MAPS_FOLDER_PATH, DEFAULT_DOWNLOADED_MAPS_PATH.toString()));
  }
```

**Comment by ron-murhammer** [comment]
@DanVanAtta There appears to be issues with the new way you can specify a maps directory. There are ways that it ends up as a weird invalid path.

**Comment by ron-murhammer** [comment]
It also appears that changing the 'Map Download Folder' in 'Engine Preferences' -> 'Engine Settings' -> 'Folders' doesn't actually work. It prompts that the change is successful but doesn't actually take effect.

**Comment by panther2** [comment]
Works for me on Windows7.
I have specified D:\Daten\triplea\downloadedMaps and don't experience any problems.

IMHO you must choose a folder that is outside the system folders and though does not need admin privileges.

**Comment by panther2** [comment]
Please see follow up discussion starting from here:
http://tripleadev.1671093.n2.nabble.com/TripleaA-1-9-Release-tp7593849p7593959.html

**Comment by DanVanAtta** [comment]
The problem is in: `getDownloadedMapPath()`
Instead of returning the first system property value that exists, it should also check that the folder exists, and then default to the next value.

**Comment by DanVanAtta** [comment]
I might be able to get to this this weekend, been a bit swamped lately. Anyone is welcome to tackle the problem in the meantime.

**Comment by ron-murhammer** [comment]
@DanVanAtta Correct. That would at least avoid the invalid path issue. 

It also appears that changing the 'Map Download Folder' in 'Engine Preferences' -> 'Engine Settings' -> 'Folders' doesn't always work even though it prompts that its successful. Starting to think we should just remove the feature and go back to defaulting the maps directory.

**Comment by DanVanAtta** [comment]
Leaving unused code paths is not nice, alternatively it'll take half the time to remove it as it would be to debug. Failing that, just mark it as beta. There could be some OS specific items going on..

**Comment by DanVanAtta** [comment]
#1375 added some fixes that should help fix this. 
I have noticed that sometimes the download path setting does not take effect properly. If that is still a problem, a new issue to track it would be useful.
