### ISSUE TITLE
error messages

### ISSUE THREAD

**Issue by robertpatten1** [triplea-game/triplea#1329]
after I downloaded the new tripleA...I get this error message when I enter a game

Nov 04, 2016 5:26:29 PM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
triplea.engine.version.bin:1.9

after getting message, I can still play if it's a bot host, but can't play if its a human host

**Comment by ron-murhammer** [comment]
@robertpatten1 These steps should resolve the issue: http://stackoverflow.com/questions/16428098/groovy-shell-warning-could-not-open-create-prefs-root-node

**Comment by ron-murhammer** [comment]
1. Go into your Start Menu and type regedit into the search field.
2. Navigate to path HKEY_LOCAL_MACHINE\Software\JavaSoft (Windows 10 seems to now have this here: HKEY_LOCAL_MACHINE\Software\WOW6432Node\JavaSoft)
3. Right click on the JavaSoft folder and click on New -> Key
4. Name the new Key Prefs and everything should work.
