### ISSUE TITLE
Flashing screen when scrambling fighters

### ISSUE THREAD

**Issue by Sabovitch** [triplea-game/triplea#1333]
Hey there

Whenever the option to scramble fighters pops up. We cant make any selections and the game becomes unplayable. We always have to restart the game from the previous turn. It's impossible to select "Scramble" or anything else while the screen is flashing. 

Using a new mac book pro. 

Can be emailed at Sabovitch@live.ca

Thank you

Jared

**Comment by panther2** [comment]
Please see #1269

**Comment by ron-murhammer** [comment]
Closing this as a duplicate.
