### ISSUE TITLE
Feature Backlog

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1337]
We are tracking a large number of feature requests and have not been able to reduce their number off of the queue very effectively. I closed a number of issues I had opened with wish-list feature requests and moved them to a one-liner bullet point here: https://github.com/triplea-game/triplea/wiki/Feature-Back-Log

I suggest we update our feature request process to be this:
1. open an issue to talk about it
2. once the idea for the feature has been refined, and the developers have given some insight if the idea is feasible, we then move the issue to the feature back log wiki page.

**Comment by simon33-2** [comment]
Some of that stuff I've suggested e.g. roll until someone hits button. This particular one isn't as important now because of the enhancement in 1.9 which allows space to be automatically pressed where no decision is needed.

**Comment by DanVanAtta** [comment]
Hmm, this issue is not about any new suggestions, but how for us to track feature suggestions effectively. The issue queue is clogged with stuff that is not readily actionable.

**Comment by simon33-2** [comment]
My idea would be to just address the issues as possible then this wouldn't be such an issue.

**Comment by simon33-2** [comment]
I've noticed in the wiki that there is a label "Not Fixed / Ice Box". I think this label should be used. I've got a number of candidates for lower order issues that could be closed with this label:
#1613 #1594 #1572 #1516 #1510 #1501 #1479 #1452 #1444 #1230 #1031 #1025 #992 

About time we focused the development on the numerous issues that exist in this code line. Once the higher priority issues are resolved the ice box can be re-opened.

**Comment by DanVanAtta** [comment]
I've added a new 'Ice box - revisit later' label. @simon33-2 I think you raise a valid point how we can re-open issues marked with such a label.

I went through the issue list intending to ice box most of them. I found that many were closed. A few could maybe use a bit more conversation before they are ice boxed, others 'backlogged' to the feature backlog page.

In the meantime, will close this issue. Please feel free to re-open to discuss further.
