### ISSUE TITLE
Non-Compatible Changes - Next release branch?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1343]
I'm concerned/thinking about the next PR that breaks serialization/RMI and would require a major release.

- I would like for us to ask PR submitters to test version compatibility. This means logging in to the lobby and seeing if a game can launch and chat works (this tests java RMI for the most part). Ideally we'd automate or make this no longer required.. Some effort needs to be put into the docs so we have a single /clear place to put these instructions too. I'll see if I can help with that in the next week.
-  For changes that we do want, that must break compatibility, I suggest we merge them to a single well known branch. We then merge that to master when we are ready to break version compatiblility. We'll need/want to merge master into this 'next-release' branch frequently, (each each  PR merge ideally).

**Comment by ron-murhammer** [comment]
@DanVanAtta Agree. I'd prefer to not break lobby or save game compatibility for at least a few months. I think creating a separate branch for any changes that do break it would be best. I plan to have a similar approach for the AI as I don't want major AI overhauls released with small bug fixes/features if they haven't been tested. I think moving towards something like the feature branch workflow is what I'm envisioning to allow major features and compatability breaking things to live separately from our frequently released master.

**Comment by DanVanAtta** [comment]
I do think our branching model has served us well so far. I'm reluctant to switch.

I think as a better idea, we perhaps should just leave the PRs open if they do have conflicting changes.  We can do the review and assign them a label if they get approved and are just waiting.

I like this idea better because it keeps the burden of work decentralized, on the requester of the PR. Otherwise we have a bottleneck in what would otherwise be a centralized process that required us to do branch management, merging master into a 1.9.2 once a week or so (and then resolving the resulting merge conflicts)

**Comment by ron-murhammer** [comment]
The problem with leaving lots of PRs open is it clogs the queue and then they end up needing to continuously be rebased. I think its easier to have a 'feature' branch to merge these PRs into for large changes that we don't want to release in the frequent releases.

**Comment by DanVanAtta** [comment]
- if we merge them all to one branch, the same conflicts happen either way. So no obvious advantage there to me
- bit of a question of who is responsible and on the hook for doing the rebases/merge conflict work. With a long running 1.9.2 branch we might have some really bad ones if we do some good cleanups.  I'd like to keep the current branch problem on the submitter rather than admins. It's encouragement of a sort to minimize any conflicting changes until we are ready to jump release versions again. IMO we'll see that as evident when there are a number of conflicting PRs hanging out. If each PR is kept small, then the rebase work will be pretty minimal (and again, it won't be on the admins do that work).

**Comment by DanVanAtta** [comment]
I'm actually now concerned that once we start this process of maintaining on behalf of everyone a 1.9.2 branch, that will be set as precedent and will be expected again and again. I'm now strongly in favor of labeling PRs that version conflict and having the owner of the PR both minimize the content of those PRs, and also own the responsibility of keeping them up to date.

If any such PR is abandoned, then worst case the admins have less code content to merge (the alternative case is merging effectively everything rather than just the abandoned work).

**Comment by DanVanAtta** [comment]
Hmm, sorry to be thinking out loud so much.

Let's say we had 8 PRs hanging out. It would be natural to want to de-conflict those PRs, the answer would be an aggregation branch. I think the benefit of an aggregation branch really kicks in at the 2nd or 3rd PR).

With that:
- first conflicting PR gets labelled and remains unmerged
- second conflicting PR when approved, we create an aggregation branch from the first PR, and then merge the second PR into the aggregation branch. From then on any conflicting updates would go into the aggregation branch.

**Comment by ron-murhammer** [comment]
@DanVanAtta Exactly we want some sort of branch to aggregate all the changes together instead of lots of individual PRs much easier to manage and less to rebase again and again. I would say just create the 'incompatible version' branch just once we have a PR that would break lobby or save games.
