### ISSUE TITLE
Automated bots...

### ISSUE THREAD

**Issue by madpoet11** [triplea-game/triplea#1345]
How many automated bots are allowed to host at the same time? Is there a certain number that can be active at once? If there is some form of limitation, can the amount of bots be expanded or can we have an option to create or activate a bot in order to host? Thank you.

**Comment by DanVanAtta** [comment]
I'm not aware of any hard limitations for how many bots can be spawned.  Generally memory or CPU resources are the limiting factor.

**Comment by madpoet11** [comment]
Most times, there are rarely any open rooms, that's why I asked. Would be nice to see more bots available. 
 

 

 

-----Original Message-----

**Comment by ron-murhammer** [comment]
@madpoet11 Yeah, we need more folks to host bots and instructions can be found here: https://github.com/triplea-game/lobby#run-hosted-bots

We have limited CPU and memory on the warclub server to host more than a handful of bots at this time. We are consider upgrading to a larger server but having players that have available hardware host a few bots is very helpful.

**Comment by ron-murhammer** [comment]
@madpoet11 Closing this for now. If you have additional questions let us know.
