### ISSUE TITLE
How to Update Map Download Descriptions?

### ISSUE THREAD

**Issue by sneakingcoward** [triplea-game/triplea#1348]
NATO is not "trade", its North Atlantic Treaty Organization

**Comment by panther2** [comment]
Line 1241 of which file?

**Comment by sneakingcoward** [comment]
triplea_maps.yaml

how can i add lines here ???

**Comment by panther2** [comment]
Create a fork of the **triplea-game/triplea** repository, apply your edits and changes to the files you want to work at your fork (either using a branch (for testing purposes) or directly to your master) and then create a pull request to get your changes merged into the **triplea-game/triplea** project.
