### ISSUE TITLE
Some Nwo variants not in the new version 1.9

### ISSUE THREAD

**Issue by tek73** [triplea-game/triplea#1349]
I cant find ww2 new world order ( neutrals) in the new version. Cant download them inside the game neither. Have downloaded the games manually but cant install.  Can you guys fix this or give som advice on how to do it myself ?

**Comment by ron-murhammer** [comment]
@tek73 Can you provide a little more detail? Do you have links to the NWO variants for 1.8 that you were playing?

**Comment by panther2** [comment]
@tek73
Are you talking about this one?
https://github.com/triplea-maps/new_world_order_variants 

That includes the NWO_Variant_-_Neutrals.xml

You will find it when hitting "Download Maps" and then choosing "Experimental"... look for "NWO Variants"

**Comment by panther2** [comment]
@tek73 

You will find it here:
https://github.com/triplea-maps/new_world_order_variants

To install it hit the green "Clone or download"-button and hit "Download ZIP".
Place the downloaded zip-file into your downloadedMaps - folder.

You will see "New World Order Variant - Neutrals" next time you start TripleA and hit "Select Map".

@ron-murhammer 

It looks like this varaint didn't make it to the triplea_maps.yaml for any reason.

**Comment by tek73** [comment]
Great it worked or at least the best of them.  Ty very much panther 2, really made my day .  Hope it will be automaticaaly in the next version of the program.

**Comment by panther2** [comment]
You are welcome, enjoy gaming!

**Comment by DanVanAtta** [comment]
Seems like we just need to add that map to the download list/file 'triplea_maps.yaml' here: https://github.com/triplea-game/triplea/blob/master/triplea_maps.yaml

**Comment by panther2** [comment]
I would do it, but I don't know anything about this map/variant (except where to find it).
So if anyone could add:

- where to find the mini image, or can we use this one ?http://tripleamaps.sourceforge.net/images/TripleA_new_world_order_mini.png
- a brief description of this map/variant

I would create the pull request then.

Probably you can help out @tek73 ?

**Comment by DanVanAtta** [comment]
Please re-open if there are further actions to take.
