### ISSUE TITLE
Big World 1942 v3 - Mechanized Infantry Not Functioning

### ISSUE THREAD

**Issue by Cochise77** [triplea-game/triplea#1354]
Hello,

First, THANK-YOU for TripleA!

With the newest version, once Mechanized Infantry is awarded, the game isn't allowing infantry to be added to tanks (I haven't tried halftracks).

Thanks,
Steve

**Comment by Cernelius** [comment]
This is already tracked in:
https://github.com/triplea-game/triplea/issues/1332

I suggest closing this one.

Also, both armour and halftrack are fine. It is the infantry and marine that are bugged.

As a related matter, as a Big World player, do you think that "marine" should be able to be land-transported and/or air-transported too, or only the "infantry"?

**Comment by Cochise77** [comment]
Having the marines land or air transportable would certainly increase the utility of the marine, and make it more of a value compared to artillery.  

Right now, I only use the marines early/mid game for the US, or late game Germany/Japan (when conquering Great Britain or the Eastern US).  I've never found them to be a good value for the UK or Italy (where production constraints push me towards Infantry+Artillery), and can't ever see myself buying them for Russia or China.

For paratroopers (or para-marines), I don't think there's much benefit unless you could drop them in the 2nd enemy territory (i.e. drop them one spot behind enemy lines).  Requiring them to drop in the first enemy territory negates their usefulness.

Mechanized marines could be really interesting for Russia.  They'd also be useful for mainland Asia (Japan, USA, & UK).  They could also tip the value scale for Italy.

So blah, blah, blah, long way of saying it would be interesting.

**Comment by Cochise77** [comment]
Thanks for pointing out the previously logged issue, closing this one.

**Comment by Cochise77** [comment]
On the marine question, I should have stated it more plainly, yes, IMO, the marine should be air/land/sea transportable.
