### ISSUE TITLE
Link to download TripleA software is not correct

### ISSUE THREAD

**Issue by Deltium** [triplea-game/triplea#1355]
Just a FYI -- the current link on the website to "Download Triple" from SourceForge is not correct.  The current link yields an empty website without any software at all.   The correct link should be the following:

http://www.triplea-game.org/

This is a fairly important thing to update since all new players that come to the website don't know where to look for the software.   I've been referring quite a few people from AAMC and DAAK to our website, and now I know why I don't see them in the Lobby yet !!

Thanks, Deltium

**Comment by ron-murhammer** [comment]
@Deltium Which link are you referring to?

**Comment by Deltium** [comment]
Hi Ron, on the warclub website, the link under "Get Started" in the upper left corner.   The links there.

**Comment by ron-murhammer** [comment]
@Deltium Yeah those still link to the old SF pages that have been retired. Unfortunately, I think you probably have to update the PHP modules on the warclub server to change that. I don't think it can be updated from the Xoops admin console.

**Comment by DanVanAtta** [comment]
I do see the link updated in the Xoops admin console. It looks like that is the place, but, I do not know how to have Xoops to 'regenerate' the site. Seems like once we do that, the link should be updated.

**Comment by JayArghArgh** [comment]
hey @DanVanAtta  @Deltium looks like the site utilises caching - it has it's pros and cons but takes away from the dynamics a little if not setup correctly.
I'm not site admin but can talk whoever is through this; got to maintenance and clear the smarty cache.
![image](https://cloud.githubusercontent.com/assets/3242587/21089461/2b9d1834-c088-11e6-9700-74700e9c7679.png)

Ensure "no" is selected for the two other options and click send. This will clear the cache, specifically, the file that is being served to the viewers that contains the outdated information.

![image](https://cloud.githubusercontent.com/assets/3242587/21089514/8f69a530-c088-11e6-9c13-31e38d046425.png)

Refresh browser and changes will come through*

*disclaimer: changes _should_ come through :)

**Comment by DanVanAtta** [comment]
Does not seem to have worked, cache cleared but not seeing an update:
![results](https://cloud.githubusercontent.com/assets/12397753/21120285/635905ec-c07b-11e6-889b-16a37533a515.png)

@prastle should be able to make you an Xoops admin, I'll ask him on gitter to do so.

**Comment by prastle** [comment]
Ya np dan I just wanted to show him around but i guess our schedules are not matching

**Comment by DanVanAtta** [comment]
Created a ticket in the warclub repo to track this: https://github.com/triplea-game/tripleawarclub.org/issues/6

@Deltium , link to the github.org website instead: http://www.triplea-game.org/
That URL should be stable for some time to come, and is intended to be the main portal for downloading. From there we have the centralized/master set of links to get to the ladder (warclub), and help pages etc..
