### ISSUE TITLE
Lobby console SQL updates busted

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1358]
Reported from AmericanKnight that using the 'sql' functionality of the lobby console does not work, specifically SQL commands execute and then hang without completing. This impairs moderator/admin from updating DB easily.

Solutions:
1. Debug
2. Migrate the lobby to use a MySQL DB. This fits in with longer term objectives and would remove the need for the the lobby console SQL feature (we could connect via mysql directly).

**Comment by americanknight** [comment]
by the way, I noticed another switch when working this that were not useing in the current command line of the server. 
The current lobby loads with this command line
java -server  -Xmx256m -classpath bin/triplea.jar:lib/derby-10.10.1.1.jar -Dtriplea.lobby.port=3303 -Dtriplea.lobby.console=true games.strategy.engine.lobby.server.LobbyServer

What does triplea.lobby.ui=true do?

**Comment by ron-murhammer** [comment]
@DanVanAtta Yeah I think trying to make a short term fix to get it working again would be best to start. Then we can consider what it would take to migrate to MySQL DB to make things easier.

**Comment by DanVanAtta** [comment]
@americanknight  triplea.lobby.ui  starts the 'lobby admin console'

https://github.com/triplea-game/triplea/blob/master/src/games/strategy/engine/lobby/server/ui/DBExplorerPanel.java is the thing that connects to Derby and executes queries. The updates since 1.8 did not really touch any of that code in a significant way.

It seems less likely that it was just a refactoring mistake or something. The version of DB we have on lobby is not compatible with the latest. There is also the java8 upgrade that happened, which is perhaps. There might also be an environment condition that was not migrated to the 1.9 lobby successfully.

**Comment by DanVanAtta** [comment]
Closing in favor of: https://github.com/triplea-game/triplea/issues/1352
