### ISSUE TITLE
maps not included in triplea_maps.yaml

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1369]
- [x] https://github.com/triplea-maps/1941/issues/2
- [ ] https://github.com/triplea-maps/sleeping_giant/issues/2
- [ ] https://github.com/triplea-maps/tiberian_conquest_au/issues/2
- [ ] https://github.com/triplea-maps/tiberian_conquest_eu/issues/2
- [ ] https://github.com/triplea-maps/tiberian_conquest_sa/issues/2
- [ ] https://github.com/triplea-maps/caravan/issues/2

Need volunteers to do some quick QA of the maps, and then add them to triplea_maps.yaml

**Comment by panther2** [comment]
Please see and add #1349

**Comment by simon33-2** [comment]
How do we remove redundant repos? ww2_g40_balanced is redundant now - merged with global

**Comment by DanVanAtta** [comment]
Create an issue in either this repo or the maps/Project repo.  It'll let me know and start tracking. I just deleted the ww2_g40_balanced repo.

**Comment by simon33-2** [comment]
1941 cannot be included because it contains only numerics. You get these errors:
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
        at games.strategy.engine.framework.map.download.DownloadFileParser.parse(DownloadFileParser.java:36)
        at games.strategy.engine.framework.map.download.DownloadRunnable.readLocalFile(DownloadRunnable.java:56)
        at games.strategy.engine.framework.map.download.DownloadRunnable.getDownloads(DownloadRunnable.java:31)
        at games.strategy.engine.framework.map.download.DownloadMapsWindow.lambda$showDownloadMapsWindow$1(DownloadMapsWindow.java:74)
        at games.strategy.engine.framework.ui.background.BackgroundTaskRunner.lambda$null$1(BackgroundTaskRunner.java:17)
        at java.lang.Thread.run(Thread.java:745)


Change map name or change code?

**Comment by DanVanAtta** [comment]
This conversation just needs to be moved to the forums...

**Comment by RoiEXLab** [comment]
A general question:
The diplomacy map is currently broken (having multiple map centers on the exact same spot causes exceptions when moving).
So we could either make triplea more forgiving (not recommended) or just remove the duplicate territories (I can create a PR, but this still doesn't fix some movement issues, fleets can move on land normal armies on water etc.)

**Comment by DanVanAtta** [comment]
@RoiEXLab , do you know if there is  still a problem with Diplomacy map? A quick check and it seemed okay. If so, please create a ticket to track it - I'm going to stick a fork in this issue and close it.

**Comment by RoiEXLab** [comment]
@DanVanAtta I believe the map should work just fine right now.
I submitted a fix a couple weeks back that simply removes dummy territories
