### ISSUE TITLE
Add cancel button for rocket attack 'choose unit'

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1387]
Task: Add a cancel button to the rocket attack 'choose which unit to attack' dialog option. When clicked, user should go back and be able to choose a new territory to attack.

Current code that controls this is in:
https://github.com/triplea-game/triplea/blob/master/src/games/strategy/triplea/ui/TripleAFrame.java#L960

To test / repro:
- open WWII global
- give Germany rocket tech
- click through until rocket attack, choose UK
- Currently opens up an 'ok' dialog with no option to go back. Instead, we should have a new cancel button. When clicking the new button, the game shoudl go back to the previous pop-up window, and allow selection of a new territory.

This task is a follow for: https://github.com/triplea-game/triplea/issues/1209

**Comment by simon33-2** [comment]
The problem here is much broader. There needs to be a store and forward system of these types of rolls. That casualties need to be chosen for sub combats at inappropriate times is another bug.

**Comment by simon33-2** [comment]
These issues are resolved by PR #1535
