### ISSUE TITLE
New Issue Labeling process and wiki page

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1391]
Creating labels ad-hoc is good, but not having a shared definition of what labels mean is not. We have some notes on the main readme about what labels meant. This was not a complete list.

I copy/pasted our current label set (and created a 'not fixing / ice box' label), and put them in this wiki page: https://github.com/triplea-game/triplea/wiki/Issue-Labelling

So we should feel to update/add/remove from the label list, as long as we keep the wiki page updated. 

I then updated our readme instructions to consolidate and give the link to the labelling wiki: https://github.com/triplea-game/triplea/pull/1390

This ticket is mainly meant as an FYI.

**Comment by ron-murhammer** [comment]
@DanVanAtta I think the one thing I'd like to put some clarity around is feature backlog. We have a lot of open issues with 'feature backlog' label and a bunch also listed in the wiki here: https://github.com/triplea-game/triplea/wiki/Feature-Back-Log

I think the wiki approach may be better but in that case after some initial discussion and acceptance around the feature issue it should be closed and added to the wiki. We could also try to better categorize/prioritize the wiki page as well.

**Comment by DanVanAtta** [comment]
The listing is perhaps a prototype of how we can queue feature requests: https://github.com/triplea-game/triplea/wiki/Feature-Back-Log

I think it does work out well. Most features once accepted only need a one line summary. The link back to the original issue is then good context/detail on what should be done. I suspect there is agreement here to move feature requests issues to the wiki listing page so we can track them in a more consolidated manner.
