### ISSUE TITLE
Lobby RAM upgrade

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1405]
Tracking ticket for lobby downtime. 

Maintenance notification PR: https://github.com/triplea-game/triplea/pull/1406

Maintenance window:    Thursday 05:00 UTC (Wednesday 21:00 PST, Thursday 0:00 EST)

Estimated Time: Linode says about 50 minutes for the upgrade. Ideally everything will start up cleanly. 

Description: 
- Linode upgrade to 4GB of ram from 2GB

**Things impacted**:
- Lobby will be offline
- Dice servers will be offline
- Bots will be offline

---------- 

Detailed Task description:
- [x] SCP last derby database backup to a local file system (off of Linode)
- [x] Review lobby deployment steps in case of SNAFU
- [x] Notify lobby games to save in case of D/C, suggest continuing via direct host
- [x] Notify players in bot games to save
- [x] Shut down bots
- [x] Shut down lobby
- [x] Start linode upgrade via the linode website
- [x] Wait for that to be done
- [x] Start the lobby
- [x] Start 5 bots
- [x] remove lobby maintenance notice

**Comment by prastle** [comment]
ty
can we add a post in lobby about this? that displays over next few days?

**Comment by ron-murhammer** [comment]
@prastle Its already there: #1406 

@DanVanAtta Sounds good. Thanks for setting it up.

**Comment by americanknight** [comment]
This is in about 1/2 hour from now right?

**Comment by americanknight** [comment]
Never mind, figured it out. 11 PM CST. Ill be available during that time. Would like to use this down time as an opportunity to get a stack trace from the lobby app for troubleshooting the DB issue.

**Comment by DanVanAtta** [comment]
Scheduled for tomorrow. Good idea on going for the stack trace.

**Comment by americanknight** [comment]
Which tasks can I help with on the Detailed Task description: I know how to handle the lobby and bot stuff. do not know how to back it up or process the linnode upgrade. I assume thats dan right?

**Comment by americanknight** [comment]
Is this all we need for the stack trace of the running lobby?

**Comment by DanVanAtta** [comment]
Yup, looks like this is our thread:
```
"Headless console eval print loop" #20 prio=5 os_prio=0 tid=0x00007f9a0047d800 nid=0x643f runnable [0x00007f99e1bf3000]
   java.lang.Thread.State: RUNNABLE
        at java.io.FileInputStream.readBytes(Native Method)
        at java.io.FileInputStream.read(FileInputStream.java:255)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        - locked <0x00000000f0434b98> (a java.io.BufferedInputStream)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        - locked <0x00000000f03c9508> (a java.io.InputStreamReader)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.io.BufferedReader.readLine(BufferedReader.java:324)
        - locked <0x00000000f03c9508> (a java.io.InputStreamReader)
        at java.io.BufferedReader.readLine(BufferedReader.java:389)
        at games.strategy.engine.lobby.server.headless.HeadlessLobbyConsole.printEvalLoop(HeadlessLobbyConsole.java:69)
        at games.strategy.engine.lobby.server.headless.HeadlessLobbyConsole.lambda$start$263(HeadlessLobbyConsole.java:59)
        at games.strategy.engine.lobby.server.headless.HeadlessLobbyConsole$$Lambda$11/1470344997.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by DanVanAtta** [comment]
@americanknight  - prepping to do this in an hour. The lobby D/C will knock your bots offline.

**Comment by DanVanAtta** [comment]
About to start..

**Comment by DanVanAtta** [comment]
linode upgrade started, server is shut down. Files are currently migrated according to linode website

**Comment by DanVanAtta** [comment]
well, that was much faster than the linode said it would be, lobby is back up!

**Comment by DanVanAtta** [comment]
```
 free -m
             total       used       free     shared    buffers     cached
Mem:          3948       2593       1354         28         24       2025
-/+ buffers/cache:        543       3405
Swap:          255          0        255
```

Bringing bots back online now..

**Comment by DanVanAtta** [comment]
we're restarting lobby once more, updating the startup parameters. Lobby will be back soon

**Comment by americanknight** [comment]
Lobby restarting complete. Bots coming back now
