### ISSUE TITLE
Bomber shot down on bombing raid

### ISSUE THREAD

**Issue by rpjaxis** [triplea-game/triplea#1407]
World War II v5 1942 Edition:

Japan bombers on bombing mission shot down when no AA present but artillery present.
Over fly friendly territory.
Occurs on attack against Russia and India

Why?

**Comment by panther2** [comment]
Quote from rulebook:

> Air Defense: Industrial complexes can defend against a strategic bombing raid. Before bombers can attack a targeted industrial complex, they will be fired on by the **built-in air defenses** of the industrial complex. The industrial complex’s controlling player rolls a die for each attacking bomber. Each roll of “1” scores a hit and eliminates one bomber.

In case I misunderstood your issue, please attach a savegame so we can see what happened.

**Comment by rpjaxis** [comment]
Thank you for your answer.  I had not read the rules for factory closely.
If there is an AA present in factory territory are there 2 shots at each
bomber - one from factory and a second from AA?

**Comment by panther2** [comment]
No. AA-guns do not fire against strategic bombing but only against planes attacking the territory.

Please close this issue after reading - as this is not a TripleA-(software) related issue.

Let me invite you to join the [A&A](http://www.axisandallies.org/forums/) community.
Me and others will be happy to answer your rules related questions there.

**Comment by rpjaxis** [comment]
OK - got it.  Thank you for your help.
