### ISSUE TITLE
triplea 1.9.0.0.3453 liberated power takes no actions

### ISSUE THREAD

**Issue by kthugha** [triplea-game/triplea#1413]
on BigWorld2, as US, i liberated China, but then the "reactivated" China took no actions (no builds, moves (no units)) and it basically cost the allies 10 PUs and 3 production centers. Swung the game, honestly.

**Comment by DanVanAtta** [comment]
Do you have a save game where this happened? If so would you mind attaching it or posting it somewhere and providing a link?

**Comment by kthugha** [comment]
Please ignore me. The capital was recaptured before China's next turn, so this was as expected.
