### ISSUE TITLE
Uploading Map "Destination Berlin" for further development and ingame usage

### ISSUE THREAD

**Issue by Klitschie** [triplea-game/triplea#1414]
Where do I upload my own map-creations?

My map is from last year. I wanted to finish it once, but never found the time to do so.
I found it well balanced. Focus is on playability, not on historically correctness.
Motivation is to give the community something back for I enjoyed the game very much then.
Maybe there is someone liking the idea I bring up with this map and finishes it.

Scenario is the last big battle during the last few weeks of WWII, when original Triple A ends - the battle for the city of Berlin.
I attached my work as a ZIP-file:

[destination_berlin.zip](https://github.com/triplea-game/triplea/files/672914/destination_berlin.zip)

**Comment by DanVanAtta** [comment]
The docs are now consolidated on the website. Please see: http://www.triplea-game.org/dev_docs/maps/map_making

Let me know if you have any questions. That doc page is not terribly complete / clean, so your questions would guide an improvement to that documentation page.

**Comment by ron-murhammer** [comment]
@Klitschie Feel free to post questions here or to the TripleA dev forum here: http://triplea.sourceforge.net/mywiki/Forum

Closing this issue for now and we can reopen if you need assistance.
