### ISSUE TITLE
Conslidated Docs - All documentation is on website now!

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1418]
FYI - I grouped up what I think is all of our documentation to github.io website pages:

- http://www.triplea-game.org/help/
- http://www.triplea-game.org/dev_docs/
- http://www.triplea-game.org/dev_docs/maps/
- http://www.triplea-game.org/dev_docs/dev/
- http://www.triplea-game.org/dev_docs/map_admin/
- http://www.triplea-game.org/dev_docs/engine_admin/

- https://github.com/triplea-game/triplea-game.github.io

Going forward we should be able to refer people to the help page: http://www.triplea-game.org/help/

If they run into trouble, ideally we'll get feedback and update the help page(s) so they are better, and would help the next person.

Ultimately though we now have a single player for all documentation, rather than repeating documentation in several different places. The goal is then to get people to funnel through the single location and to keep improving the help documentation structure and contents.

To update the help documents, they are on github and PRs are welcome: github.com/triplea-game/triplea-game.github.io

**Comment by ron-murhammer** [comment]
@DanVanAtta Makes sense. I'd still like us to have a little more clarity on what belongs in:
1. Docs on the website
2. Readme in this repo
3. Wiki for this repo
4. Issues for this repo

**Comment by DanVanAtta** [comment]
> Docs on the website

- Essentially all documentation.
- New dev setup tutorial/instructions
- This is where we write down decisions.

> Readme in this repo

Not much since we are consolidating to website. Should generally just point folks to the website, perhaps picking out a few particularly useful links.

> Wiki for this repo

Non-permanent lists that we do not want to keep track of in issues

> Issues

- This is our bug queue. 
- This is where we raise and talk about longer running conversations that need input/advice or a decision to be made

> Gitter

- Anything that is relevant only if read in a timely manner. e.g: "I'm going to be updating xyz". Basically this is kind of like a news feed almost. Anything or important or of lasting consequence should be raised in a github issue and/or documented in the website.



Default place for 


Really this is the default place. Instead of having these sets of index links to the multiple documentation pages we have, we'll place all those pages in one locations (website), and then just direct people to the website. This clears up where we should add and look for documentation. We can iterate on improving this one location and will globally improve the project documentation.  We will also be able to better avoid duplicate documentation as well since it will now be consolidated.

> Readme in this repo

Not much, quick intro, link to the webpage, and perhaps a few useful links for developers. Any dev documentation we will focus on in the website.


This is the default place.

Context: Before we had docs in multiple places, website, readme, bundled with the code distribution, sourceforge forum, warclub forum, and files that come in the source code and are not distributed.

Observations:
- To handle this we created link indexes to point to all of these locations. We then duplicated that in multiple places. A good example are the help menu links, and the links in the lobby text.
- There was a lot of redundancy in documentation, since it was hard to keep track of what had already been written, and so we filled in documentation in multiple places

Desired Direction:
- We can work on a single set of documentation, and improve the quality in that one place iteratively
- We can avoid the index of links in favor of linking to our documentation. The documentation then will have a single link/index tree that we can manage more easily.
