### ISSUE TITLE
is sea infrastructure not being captured

### ISSUE THREAD

**Issue by beelee1** [triplea-game/triplea#1420]
didn't see this on here anywhere. Was wondering if it's still being worked on. Saw redrum's patch at sf had some problems.

here's original discussion

[http://tripleadev.1671093.n2.nabble.com/Sea-infrastructure-capturable-only-if-combat-in-territory-tp7585583.html](url)

Hmm...link isn"t working. Well once you're at tripleadev you can get there. Anyway isSea infrastructure can't be captured when there is no combat.

**Comment by ron-murhammer** [comment]
@beelee1 Yeah, I kind of gave up on trying to fix that since the original changes ended up having other side effects around preventing naval retreats. I think to fix this it would take a lot more time to evaluate all the naval capture logic but we should track this.

**Comment by beelee1** [comment]
Thanks for the reply

**Comment by FrostionAAA** [comment]
I had problems with a sea unit called “Young-Water-Dragon” in my map Dragon War. I wanted this unit to be capturable, but it wasn’t. I got it working eventually. I think I got it working by following this advice from Crazy German: "You need to set an owner for sea zones in the ownerinitialize section of the XML. If a sea zone doesn't have a designation in that section, it has no owner (not neutral, it has no ownership at all)"

Anyway, the sea unit is now capturable on this map, both if attached and if itself is attacking. The unit is isInfrastructure and isSea.

**Comment by beelee1** [comment]
Hey Great ! I'll give it a try again

**Comment by DanVanAtta** [comment]
@beelee1 were you able to give the map a try again, were the results good? Looks like this has come to a settling point, @beelee1 or @ron-murhammer please re-open if there is more to track or something that should be changed.
