### ISSUE TITLE
How to reach me (veqryn)

### ISSUE THREAD

**Issue by veqryn** [triplea-game/triplea#1432]
I should have written this earlier, but never late then never.
Due to the high activity in the triplea github repo (good job all!) and the fact that I had it 'watched', meant that inbox folder where all triplea stuff goes to was getting 10s of messages per day.  I haven't been active in a year or two now, and couldn't keep up with all the messages, so I basically put them off and never ended up reading most.

I've now changed to that to the following: I'm only sent notifications when someone does `@veqryn` or when I directly post in an issue/pr.

So if you want to reach me or involve me, please @veqryn and I will at least read that thread up to your message (`@veqryn` again later if you want me to read any new stuff).

Or you can just email me directly.

I've also silenced gitter, since I'm not involved in the day-to-day, so I don't believe I will receive any messages from it.
(I am not sure if I will get any messages from other repo's besides the main "triplea" one, as I do not have them watched, so please email me if I don't respond within a couple days.)

**Comment by ron-murhammer** [comment]
@veqryn Cool. Glad to see that you'll be around a bit more. Let me know if you have any questions or want to chat.
