### ISSUE TITLE
Use labels in same style as Bazel

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1434]
I ran across some interesting github issue label usage in the Bazel project: https://github.com/bazelbuild/bazel/labels

I like how they have their labels set up, any objects if we migrate to roughly the same style of labels? I think they have something of a similar system as us, but self-documented a bit more in the label names. I think we can also remove some of the label usage documentation we have migrating to the bazel project labels.

**Comment by RoiEXLab** [comment]
No objections

**Comment by ron-murhammer** [comment]
@DanVanAtta So I like that they use colors/prefix to categorize the labels. We can adjust to use a similar system though I think many of their specific labels wouldn't be relevant. Maybe posting a list of what you think the labels should be would be a good start.

**Comment by DanVanAtta** [comment]
Gave the labels an update: https://github.com/triplea-game/triplea/labels

For the most part was 1:1 renames and updated colors. 

A things we still don't have that the Bazel project uses:
- P0-P4 labels
- Release blocker label
- under investigation label

I don't know if any of those are quite right for us right now. Priority labels are the most interesting, worth discussing further, but still not without its downsides. Release blocker indicates we merged something that is bad, we should be testing solidly PRs and updating the release version that iteration.
Under investigation is a good way to show something is in progress. I don't think it's quite a right fit for us right now necessarily, but the idea of having a label to show things that are in-progress I think is good.

**Comment by DanVanAtta** [comment]
What are your (@all)  thoughts on the updated labels? 
Any strong feelings to having p0 - p4 labels? Thoughts on when we may want to give them a try if someday but not now?

**Comment by RoiEXLab** [comment]
I like the labels, but not their color ._.

**Comment by ron-murhammer** [comment]
@DanVanAtta Mostly like the changes. Couple of comments:
1. Don't really like the term 'breakage'
2. Should discussion be a 'type'
3. Colors could definitely be better (purple and blue are very similar)
4. I'd like to try the priority labels but maybe just have 3 levels to start. Maybe merge 'breakage' into priorities as well. It would be nice to have some way to track what we feel is important to tackle ASAP vs short-term vs long-term.

**Comment by DanVanAtta** [comment]
> 1. Don't really like the term 'breakage'

'regression' would work too. 'breakage' I find to be pretty descriptive.  @ron-murhammer any alternatives in mind?

> 2. Should discussion be a 'type'

I think no, not mutually exclusive to types. Maybe a category, but our categories are more what rather than "where in the process is this issues". Discussion is basically a process label, meaning we need to discuss next steps to know how to resolve the issue (or perhaps the point of the issue is to simply have discussion.). I'm okay with keeping 'discussion' independent from category and type for the moment until we learn more.

> 3. Colors could definitely be better (purple and blue are very similar)
 
Palette is limited, do feel free to play around with them.

> 4. I'd like to try the priority labels but maybe just have 3 levels to start. Maybe merge 'breakage' into priorities as well. It would be nice to have some way to track what we feel is important to tackle ASAP vs short-term vs long-term.

Interesting, though I disagree with merging in breakage. A breakage is not necessarily a P1, but important in its own right.  In the case of SNAFU, having different priorities between different 'breakage' tickets could perhaps be useful. 

I think before we decide to have priorities, we will need to decide on some guidelines for how priority is assigned. It can easily break down to where everything has roughly the same assigned priorities, and then people's pet projects are bumped up by one. Heuristics to keep it more objective/useful I think would be the key to making it work. 3 or 4 priority levels I think sounds about right.

**Comment by ron-murhammer** [comment]
1. I like regression better.
2. I'm fine leaving discussion as more of a 'state' then a 'type' or 'category'.
3. I'll play around with the colors.
4. We can leave priorities out for now and I agree we'd need guidelines to make sure they are useful and used consistently.

**Comment by ron-murhammer** [comment]
Updated the colors. You can actually select any color by typing the hex code.

**Comment by DanVanAtta** [comment]
I saw this late:
> Updated the colors

I mucked around with them once more thinking they were still the old ones. Please do feel free to change them back. I apologize for undoing the color update, did not mean to.
