### ISSUE TITLE
standardized source code paths

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1435]
The source code folders in triplea are not very standard. I've experienced some delays getting set up in IDE's due to locating all of the components for Triplea. I believe if we move to a more standardized folder structure IDEs will be able to bootstrap TripleA projects more easily:  https://docs.gradle.org/current/userguide/java_plugin.html#sec:java_project_layout

![standard_layout](https://cloud.githubusercontent.com/assets/12397753/21756070/23c74d56-d5d1-11e6-96e8-90101bc370ef.png)

**Comment by RoiEXLab** [comment]
No objections

**Comment by ron-murhammer** [comment]
@DanVanAtta Agree as most of the major java build frameworks use those as the defaults.

**Comment by DanVanAtta** [comment]
We moved and are moving in this direction. Compatibility issues make progress a bit slow. Will close for now as we agreed to make this update. New issues would be most appropriate to re-visit potential package structures, probably not ideal to discuss them here divorced from code and feature context.
