### ISSUE TITLE
files modified on fresh checkout - auto-conversion of line endings hassles

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#144]
When doing a fresh clone on ubuntu, with either value of autocrlf set to `input` or `false`, there is a list of files that are modified from the start. 

Perhaps the line endings are incorrect in repo with respect to the git attributes file. Perhaps windows somehow masks this problem. I'm not sure what exactly is going on, though it's proving something of a pain to work with.

Below shows the modified file list from two fresh clones, one done with `autocrlf = input`, the other `autocrlf = false`.

```
        autocrlf = input


dan@dan-desk:~/work/triplea9$ gss
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   old/triplea_1_5_2_2.jar
	modified:   old/triplea_1_6_0_1.jar
	modified:   old/triplea_1_6_1_5.jar
	modified:   old/triplea_1_7_0_5.jar
	modified:   run-headless-game-host-windows.bat
	modified:   system.ini
	modified:   test_data/Great Lakes War v1.4 test.xml
	modified:   test_data/Total_World_War_Dec1941_test.xml
	modified:   test_data/europe_incomplete_test.xml
	modified:   test_data/pact_of_steel_2_test.xml
	modified:   test_data/victory_test.xml
	modified:   test_data/ww2eur40_2nd_edition_test.xml
	modified:   test_data/ww2eur40_test.xml
	modified:   test_data/ww2global40_2nd_edition_test.xml
	modified:   test_data/ww2global40_alpha3_test.xml
	modified:   test_data/ww2global40_test.xml
	modified:   test_data/ww2global42_2nd_edition_test.xml
	modified:   test_data/ww2pac40_2nd_edition_test.xml
	modified:   test_data/ww2pac40_test.xml
	modified:   test_data/ww2v3_1941_test.xml
	modified:   test_data/ww2v3_1942_test.xml
	modified:   test_data/ww2v4_test.xml
	modified:   test_data/ww2v5_1942_2nd_edition_test.xml




        autocrlf = false

dan@dan-desk:~/work/triplea10$ gss
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   maps/middle_earth/polygons.txt
	modified:   maps/middle_earth/sounds.properties
	modified:   maps/new_world_order/2map.properties
	modified:   maps/new_world_order/NWO_Readme.txt
	modified:   maps/new_world_order/games/new_world_order.xml
	modified:   maps/new_world_order/map.properties
	modified:   maps/new_world_order/name_place.txt
	modified:   maps/the_pact_of_steel/actionstext.properties
	modified:   maps/the_pact_of_steel/capitols.txt
	modified:   maps/the_pact_of_steel/centers.txt
	modified:   maps/the_pact_of_steel/games/pact_of_steel.xml
	modified:   maps/the_pact_of_steel/games/pact_of_steel_2.xml
	modified:   maps/the_pact_of_steel/map.properties
	modified:   maps/the_pact_of_steel/name_place.txt
	modified:   maps/the_pact_of_steel/notifications.properties
	modified:   maps/the_pact_of_steel/objectives.properties
	modified:   maps/the_pact_of_steel/place.txt
	modified:   maps/the_pact_of_steel/politicstext.properties
	modified:   maps/the_pact_of_steel/polygons.txt
	modified:   maps/the_pact_of_steel/production_tabs.Russians.properties
	modified:   maps/the_pact_of_steel/production_tabs.properties
	modified:   maps/the_pact_of_steel/sounds.properties
	modified:   maps/the_pact_of_steel/tooltips.properties
	modified:   maps/the_pact_of_steel/vc.txt
	modified:   maps/unclassified/games/instructions.txt
	modified:   old/triplea_1_5_2_2.jar
	modified:   old/triplea_1_6_0_1.jar
	modified:   old/triplea_1_6_1_5.jar
	modified:   old/triplea_1_7_0_5.jar
	modified:   run-headless-game-host-windows.bat
	modified:   system.ini
	modified:   test_data/Great Lakes War v1.4 test.xml
	modified:   test_data/Total_World_War_Dec1941_test.xml
	modified:   test_data/europe_incomplete_test.xml
	modified:   test_data/pact_of_steel_2_test.xml
	modified:   test_data/victory_test.xml
	modified:   test_data/ww2eur40_2nd_edition_test.xml
	modified:   test_data/ww2eur40_test.xml
	modified:   test_data/ww2global40_2nd_edition_test.xml
	modified:   test_data/ww2global40_alpha3_test.xml
	modified:   test_data/ww2global40_test.xml
	modified:   test_data/ww2global42_2nd_edition_test.xml
	modified:   test_data/ww2pac40_2nd_edition_test.xml
	modified:   test_data/ww2pac40_test.xml
	modified:   test_data/ww2v3_1941_test.xml
	modified:   test_data/ww2v3_1942_test.xml
	modified:   test_data/ww2v4_test.xml
	modified:   test_data/ww2v5_1942_2nd_edition_test.xml
```

I'm not sure how to solve this.  The goal should be have it so we can do a fresh clone and not have any files be modified, no matter which developer OS  (running Ubuntu for the record).

**Comment by DanVanAtta** [comment]
Found something of a work-around: 
- if I go back in history before the git attribute file
-  fast forward via rebase the git file to past the merge commit and fixing of files, then there is no longer an insistence to update many files.

```
 git reset --hard HEAD^^^^
git pull --rebase origin master

dan@dan-desk:~/work/triplea2$ gss
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

```

Searching for guess, the commit of a new .gitattribute file and then another commit with fixes is suspect. Particularly when I jump over and replay forward do I not have trouble. So maybe an intermediary state, during history replay or something, is causing modifications to creep in.

To that extent, squashing the .gitattribute commit and the line ending fix into the same commit might help. That hypothesis is a bit out on a limb, relatively odd behavior IMO all in all..

**Comment by gaborbernat** [comment]
So a quick test confirms my hunch: 

```
bernat@g22 /run/rx/y/triplea (master●)$ git diff -R system.ini
diff --git w/system.ini i/system.ini
index 0bea2e4..a06208c 100644
--- w/system.ini
+++ i/system.ini
@@ -1,5 +1,5 @@
-#system.ini
-#Sat May 18 03:25:51 CST 2013
-triplea.memory.useDefault=true
-triplea.memory.Xmx=
-triplea.memory.onlineOnly=true
+#system.ini^M
+#Sat May 18 03:25:51 CST 2013^M
+triplea.memory.useDefault=true^M
+triplea.memory.Xmx=^M
+triplea.memory.onlineOnly=true^M
````

^M is CR. So the issue is that the carriege returns are added to the working directory copy, as the object database version the files are without it. 

Setting crlf means that git will convert LF line endings on checkout and commit to CRLF, however will not change what already is in object database (the git status always compares with the object database) version. This files need to be commited, although given that they weren't up to this point crlf I question if they should be crlf.

**Comment by gaborbernat** [comment]
Never man, scratch that :) The inverse is true, 

```
bernat@g22 /run/rx/y/triplea (master●)$ git diff system.ini| cat -A
diff --git i/system.ini w/system.ini$
index a06208c..0bea2e4 100644$
--- i/system.ini$
+++ w/system.ini$
@@ -1,5 +1,5 @@$
-#system.ini^M$
-#Sat May 18 03:25:51 CST 2013^M$
-triplea.memory.useDefault=true^M$
-triplea.memory.Xmx=^M$
-triplea.memory.onlineOnly=true^M$
+#system.ini$
+#Sat May 18 03:25:51 CST 2013$
+triplea.memory.useDefault=true$
+triplea.memory.Xmx=$
+triplea.memory.onlineOnly=true$
```
The CR are trimmed upon checkout.

**Comment by gaborbernat** [comment]
So I figured it out with the help of the git irc channel. It seems that for the .gitattributes to work as expected everything inside the object database should be LF. 

What you mark as CRLF will be changed to CRLF on commit, and on checkout into working directory.

So we need to commit all the files inside the object database (gits internal objects)  to LF via a new commit:

```
dos2unix **/*; git add -u; git commit -m 'Convert all the things'
```

After this what we mark as CRLF will be CRLF in the working directory. 

@DanVanAtta @ron-murhammer @veqryn I can do this lat

**Comment by gaborbernat** [comment]
Should I do this? Or does someone else want this?

**Comment by DanVanAtta** [comment]
Feel free to go ahead, you've more OS's to test on than I do currently.

**Comment by veqryn** [comment]
I think we need to add *.jar to the list of binary files...

**Comment by veqryn** [comment]
Let me play around with this just a little more before you do anything, please gabor.

**Comment by gaborbernat** [comment]
Ok.

**Comment by veqryn** [comment]
I just checked out a completely fresh copy of triplea from git.  Previous to checking it out, I set `git config --global core.autocrlf false`
When I go into my new triplea directory, I can see that system.ini has CRLF and all the java files have just LF, just as intended.
`git status` shows no files have changed, and nothing will be committed.

so.... i'm not sure what the problem is that you guys are encountering, and why...

**Comment by veqryn** [comment]
Reading http://schacon.github.io/git/gitattributes.html seems to confirm that things do not need to be LF in the git repo.

**Comment by veqryn** [comment]
Looking further, it seems that while system.ini has the right line endings, changelog.txt does not have CRLF.
I just deleted my triplea directory on my windows system, set core.autocrlf to false, and checked out a fresh copy, and on windows it is showing up as CRLF for changelog.txt
Now I am super confused, but I think it means that in the repo db it is just LF....?
It seems moving from svn to git is actually more difficult than it looks...

Maybe if we commit the things that need to be CRLF into the repo again as CRLF, it will fix it?
I will try running:
```
find ./ -type f -name "*.bat" -exec unix2dos {} \;
find ./ -type f -name "*.txt" -exec unix2dos {} \;
dos2unix MacOS_users_read_this_first.txt
find ./ -type f -name "*.ini" -exec unix2dos {} \;
find ./ -type f -name "*.prop" -exec unix2dos {} \;
find ./ -type f -name "*.properties" -exec unix2dos {} \;
find ./ -type f -name "*.xml" -exec unix2dos {} \;
find ./ -type f -name "*.html" -exec unix2dos {} \;
find ./ -type f -name "*.css" -exec unix2dos {} \;
find ./ -type f -name "*.dtd" -exec unix2dos {} \;
find ./ -type f -name "*.java" -exec dos2unix {} \;
find ./ -type f -name "*.sh" -exec dos2unix {} \;
```
#148

**Comment by gaborbernat** [comment]
maybe tell us your git version on centos ?

**Comment by ron-murhammer** [comment]
Have we gotten all this resolved yet? I'm assuming no since we still have open PR's (#148, #151)? I'm a little hesitant to merge anything else until we have this resolved due to the potential of conflicts.

**Comment by DanVanAtta** [comment]
#151 touches non-Java files only, the other open PRs are for a different file type. Assuming a few PRs had a few files that were non-java, Git should be able to auto-resolve this change.

Where we will get conflicts are going to be in new work done after the .gitattributes file was added, if anyone has a "forced commit" to fix EOL endings. There was one PR with one such commit but I fixed that up yesterday so it was rebased on to #151. As long as future PRs are rebased on #151 rather than individually fixing line endings, then we will be okay. Even if they are not, the auto-resolve should take care of problems anyways.

So merge conflict is not likely, and even if it exists, chances are good it won't need manual resolution anyways.

**Comment by DanVanAtta** [comment]
> I'm a little hesitant to merge anything else until we have this resolved due to the potential of conflicts.

Sorry, this is just a very striking statement to me since I don't think it considers either the potential source of conflicts, or the implications of those conflicts.  If there are conflicts, they will have to be resolved either way, not merging stuff doesn't make merge conflicts go away. 

What's more the point, the real pain and source of  potential conflicts will be between *local* work and #151. Said another way, long lived branches are sources for merge conflicts, and that includes both local and remote branches. Not merging quickly makes branches live longer. By hesitating, and having branches live even longer, ironically it exacerbates the merge conflict problem.

**Comment by DanVanAtta** [comment]
#151 does fix this problem, closing in favor of the PR.
