### ISSUE TITLE
Review best practices related to InterruptedException handlers

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/triplea#1448]
During the code review of PR #1419, a [discussion](https://github.com/triplea-game/triplea/pull/1419#discussion_r93999204) arose about whether or not the current thread should be re-interrupted when catching an instance of `InterruptedException` (and not re-throwing it).  As recommended in the aforementioned discussion, this issue is being created as a placeholder to review the best practices related to handling `InterruptedException` and to possibly implement the team's recommendation across the TripleA codebase.

A good place to start this research is with Brian Goetz's article, [Dealing with InterruptedException](https://www.ibm.com/developerworks/library/j-jtp05236/).  The section _Don't swallow interrupts_ is particularly interesting for the case where a caught `InterruptedException` cannot be re-thrown.

**Comment by ssoloff** [comment]
Note that a [TODO](https://github.com/triplea-game/triplea/blob/master/src/games/strategy/ui/SwingComponents.java#L406) was added in `SwingComponents#runWithProgressBar()` during the PR #1419 code review and should be removed when this issue is closed.

**Comment by DanVanAtta** [comment]
There are plenty of other good write ups that consistently recommend interrupting the current thread after InterruptedException:
```
https://docs.oracle.com/javase/7/docs/api/java/lang/InterruptedException.html

http://www.yegor256.com/2015/10/20/interrupted-exception.html
http://stackoverflow.com/questions/3976344/handling-interruptedexception-in-java
http://stackoverflow.com/questions/28544867/is-it-ok-to-ignore-interruptedexception-if-nobody-calls-interrupt
http://stackoverflow.com/questions/35723085/best-way-to-handle-interruptedexception
http://www.javapractices.com/topic/TopicAction.do?Id=251


Summary from: http://www.nurkiewicz.com/2014/05/interruptedexception-and-interrupting.html
Caught InterruptedException should be handled properly - most of the time it means breaking out of the current task/loop/thread entirely
Swallowing InterruptedException is rarely a good idea
If thread was interrupted while it wasn't in a blocking call, use isInterrupted(). Also entering blocking method when thread was already interrupted should immediately throw InterruptedException
```

#1472 updates ThreadUtil to return a boolean, false if the current thread is interrupted. The updated handling of that I think probably has fixed a few bugs. There are a good number of usages of ThreadUtil.sleep, I'm pretty sure there are more examples that handle interrupted poorly. A good number of the remaining ones may require some caution/thought on how to handle properly.
