### ISSUE TITLE
Moving after combat move Post for PBF/PBEM to after BattleTracker init

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#1452]
This is advantageous for a couple of reasons:
1) Allows autodetect of the questions that need to be asked of the defender, which can be added to the post
2) Allows bypass of post if no defender decisions needed
3) Puts post after purchase for maps with combat move before purchase

The obvious way to do this would be to put the post in BattleDelegate.start() rather than combat movement. What issues are likely to occur with that change?

**Comment by ron-murhammer** [comment]
@simon33-2 I agree with point 3 that the prompt should be after both combat move and purchase. But for strict games, even if you don't have any defender decisions people will require you post the turn so 1 and 2 aren't always valid. The reason is that let's say you have 2 battles (A and B) that if you win A then you'd want to fight B but if you lose A then you'd rather not fight B. If you don't post all your combat moves then you could roll for A then not move units to attack B.

**Comment by simon33-2** [comment]
Hmm, I've never heard of a game that strict. The only way to avoid fighting B is to crash out and claim a computer error which also lets you change your purchase. I don't know any people that would do so but I guess it is theoretically possible.

That really means that the post before battles should be mandatory in those games. Is there a reason why you wouldn't want to post when there is a defender decision? I can't think of one. Maybe change the "post after combat move" to "always post before battles".

**Comment by ron-murhammer** [comment]
@simon33-2 Yeah, most people don't use the post after combat moves much but I think removing it if there is no defender options would be a mistake. I do think it should be moved to right before combat dice are rolled so after both combat move and purchase on most maps.

**Comment by simon33-2** [comment]
Ok, but I would make it mandatory when there is a defender decision to be made. It can be optional other times.

**Comment by simon33-2** [comment]
I'm having real difficulty with this one. Specifically to be useful it needs to be called in the middle of the BattleDelegate.start() method. This seems to prevent this line from succeeding: m_delegateExecutionManager.blockDelegateExecution in engine/framework/ServerGame.java

I have tried saving before the BattleDelegate starts and then passing around the saveGameFile but that doesn't seem to work either. Is the BattleDelegate returned by getDelegate() different from the one which actually executes? It seems to be which is really weird.

Anyone interested in helping can have a look at what I've got so far by looking at branch tmp4 on my fork.

**Comment by DanVanAtta** [comment]
>  Is the BattleDelegate returned by getDelegate() different from the one which actually executes?

I would not be very surprised, there are some data copies of odd objects so we can simulate some functionality without it actually occurring.

@simon33-2 should we continue tracking this, is this still on your radar?

**Comment by simon33-2** [comment]
I guess it's too hard then.
