### ISSUE TITLE
Use scripts to control lobby + bots, drop 'screens' (ui) support

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1465]
I am proposing we remove the UI that is used to launch and manage bots and the lobby in favor of just having management/admin scripts. I think we can get to full feature parity without too much difficult and for much lower cost taking this approach.  For example, it's pretty easy to build a 'restart_lobby', 'restart_bot' script, etc... 

Listed below are some of the drawbacks and costs to having a UI / 'screens' support:
- requires a shared session, not good for server management
- greatly complicates deployment, interactions have to be done from a UI. This adds time and effort to starting and managing N bots. Ultimately not very sustainable since instances need to be hand managed effectively.
- server requires extra memory and CPU resources needed to run the UI.
- lots of code is used to support these features. Removing this code would lower development costs.

**Comment by ron-murhammer** [comment]
@DanVanAtta Agree with this. Just need to make sure you capture all the functionality so we don't have problems like not being able to manage users in the DB. I think creating all the scripts and working with a few of the more active mods to test/verify then retiring the old code.

**Comment by RoiEXLab** [comment]
Totally agree with this, not only was I wondering why there were 2 "versions" in the first place, I also don't like the way the gui works - not very consequently (I had some trouble trying to test stuff out using a local dedicated server)

**Comment by prastle** [comment]
If you teach we can try to learn.  Also has anyone figured out an alternative  way of fixing the mod list etc?

**Comment by americanknight** [comment]
Definitely agree but concerned about the ability to manage bots. we still do not have a way to edit mods so  we can not remove or make new mods in the tripleA mod lobby console. As it is, loading bots manually is cumbersome and requires some learning but having scripts run is defintley better as long as we can so something when the bots are down.

**Comment by yamamot0** [comment]
Sounds great to me

What is the status on the db access fix?

**Comment by prastle** [comment]
slap me for new triplea user password when ya have time

cheers pras


________________________________

**Comment by DanVanAtta** [comment]
Closing, summarizing:
@RoiEXLab hooked up 'service' scripts to start/stop lobby and bots
@yamamot0 db access is still dead.. half a year later. Though the replacement is coming along, an active effort right now. Fingers crossed that gets over the line and we'll start seeing new moderator/admin features
