### ISSUE TITLE
Map Thumbnail Images

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1468]
In triplea_maps.yml there is a link to map thumbnail image. 
It is an open question where such map images should be hosted.

In https://github.com/triplea-game/triplea/pull/1453 a few options were presented:
- dedicated repository
- use github file attachment hosting (can be done by attaching an image to a new issue, gives an immutable link)

Desired requirements:
- image location is relatively permanent, preferably immutable
- changes to the image are 'well known' before going live (the image can't be changed or hijacked without admins knowing of the image change)

**Comment by DanVanAtta** [comment]
I'm against a repo:
- encourages to save raw source files of the image, and then we have a grab-bag repository of everyones images
- binary files do not really belong in git
- it's okay and actually good for the URL to be for an immutable image. We can see changes to the images simply by knowing the URL has changed. Otherwise we are watching yet another repo for updates. Worse yet, images do not load in diffs, we'll have to do manual work to checkout out the PR branch and open the image file. If hosted on github, we can copy/paste the URL to verify it. This also even makes for easier testing, since for map dev's their map image won't be live until their branch is merged.
- we are further distributing all the various touch points for updating a map. Very soon it is, go here, tweak that, go there, do that, etc.. I think the direction where there is a standard map image in each map repository, and map repositories are picked up automatically is the best course.

For now attaching to github issues does not lose us anything, we'll have a copy of each image. I suggest we do that. Then next design standard image locations in map repositories. That would allow us to construct map image URLs directly from the map name.

**Comment by ron-murhammer** [comment]
@DanVanAtta I'd like to have a relatively easy way to move all the images in the future and to upload the existing ones. As long as whatever solution we go with has that then its fine with me.

**Comment by DanVanAtta** [comment]
I'd like to understand the 'move' use-case a bit more. Immutable URLs are just referenced, there is no real need to store or move them anywhere. If we are hosting all the images ourselves, then there will be a need perhaps to move them (the URL/location will not be immutable/permanent).

Downloading all the file images is pretty easy so long as we have a complete url for them. The bash would look something like this:
```
grep "url:" {file} | sed 's/^.*: //' | xargs wget
```

**Comment by Cernelius** [comment]
An annoyance for me is that, actually, since the new repository, it takes more time (like about 2 seconds, while previously it was almost instantaneous) to load and see a thumbnail. This might seem not much, but it is a quite annoying when you want to look through a lot of maps presentations rapidly.

I don't know why there is such a delay, since the thumbnails are very light, but I can tell there was not in the old repository, for me.

Related to this, it was requested those thumbnail being exactly 400 pixels wide, except that @ron-murhammer uploaded a larger thumbnail for ice's Rome Total War map (it takes 5 seconds for me to load that thumbnail), despite that was still a requirement at that time (I noticed it, but didn't point out). Is this 400 pixels wide rule still wanted by the new repository admins?

I believe currently all images are 400 pixels wide, except only the one of Rome Total War. Myself I like all Thumbnail having all the same wideness (meaning that I don't like the thumbnail of Rome Total War being wider than the other ones).

**Comment by DanVanAtta** [comment]
@Cernelius how do you mean more exactly by load and see a thumbnail? are you referring to the in-game map download window?

If so, I'm not sure if the repo has to do with it. You may be noticing sourceforge vs github download times, the SF ones are pretty slow, and make up the majority of thumbnails AFAIK.

First though we do need to decide where we will put map thumbnail images.

**Comment by Cernelius** [comment]
> are you referring to the in-game map download window?

Yes, the thumbnail that you see as part of the description of the map that you may choose to download, as the next step. Those images loaded/appeared almost instantly in the old repository, while now they take 2 or 3 seconds to load, for the most part, and I believe this is annoying if you want to rapidly look over the many maps, selecting them on the map download window, to see if there is something that may be particularly interesting.

As off topic, the other thing that I find annoying is that the "Available / Update / Installed" are subcategories of "High Quality / Good Quality" etc.. It should be the other way around: if you want to see the "Update" maps, you should not have to click on "Update" each time you change the Quality categories, but it would be better if you select "Update", and then you can move between "High Quality", "Good Quality" etc., while remaining on "Update".

Moreover, I would really add another category for all those maps meant to be actually or potentially owned by a multiplicity of unrelated makers, which means the Variants (meaning maps having or potentially having xml made by this or this other one maker, each one caring for his own work, for example "Big World Variations"). In general, whoever calls his own map as "Variants" should be meant as affirming that anyone is totally free to add xml into it, and such a map should go into a special category for those (that may have games of very different quality and popularity inside, and for the most part are not experimental at all, and in several cases very definitive and balanced, think about staples like Big World NekahNet or Big World Small's or NWO Smalls).

**Comment by DanVanAtta** [comment]
@Cernelius 

> Yes, the thumbnail that you see as part of the description of the map that you may choose to download, as the next step. Those images loaded/appeared almost instantly in the old repository, while now they take 2 or 3 seconds to load, for the most part, and I believe this is annoying if you want to rapidly look over the many maps, selecting them on the map download window, to see if there is something that may be particularly interesting.

Follow up in: #1864 

> As off topic, the other thing that I find annoying is that the "Available / Update / Installed" are subcategories of "High Quality / Good Quality" etc.. It should be the other way around: if you want to see the "Update" maps, you should not have to click on "Update" each time you change the Quality categories, but it would be better if you select "Update", and then you can move between "High Quality", "Good Quality" etc., while remaining on "Update".

Follow up in #1865

> Moreover, I would really add another category for all those maps meant to be actually or potentially owned by a multiplicity of unrelated makers, which means the Variants (meaning maps having or potentially having xml made by this or this other one maker, each one caring for his own work, for example "Big World Variations"). In general, whoever calls his own map as "Variants" should be meant as affirming that anyone is totally free to add xml into it, and such a map should go into a special category for those (that may have games of very different quality and popularity inside, and for the most part are not experimental at all, and in several cases very definitive and balanced, think about staples like Big World NekahNet or Big World Small's or NWO Smalls).

I would like to think that "anyone is totally free to add xml into it," is a general rule and always apply. I do think we could work out better how exactly new XMLs should be added, where. I'm not really sure what/how that should change for the moment. If you'd like more follow @Cernelius , kindly open a new issue starting the discussion from afresh. I'll be happy to discuss further, one key strength of TripleA has been the flexibility to update maps

That covers the last 3  issues raised here, now closing
