### ISSUE TITLE
Strip HTML from javadoc comments?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#147]
Ran across this code:

```
/**
 * Utility for loading and playing sound clips.
 * Stores a preference in the user preferences for being silent.
 * The property will persist and be reloaded after the virtual machine
 * has been stopped and restarted.
 * <br>
 * <br>
 * <br>
 * <br>
 * <br>
 * How it works: <br>
 * <b>Sound.Default.Folder</b>=ww2 <br>
 * This is the "key" that tells the engine which sound folder to use as the DEFAULT sound folder. <br>
 * The default folders are as follows: <br>
 * "<b>ww2</b>" (which should cover ww1 - ww2 - ww3 sounds), <br>
```

Should the html be there, or strip it favoring white space formatting?

We dont' really use or generate javadoc, having it is good for IDE auto display stuff, but otherwise I think we perhaps should optimize for whitespace (in-file) legibility.

**Comment by veqryn** [comment]
Whitespace doesn't keep when you are looking at the actual java docs instead of the comments (or when you are looking at the docs through an IDE.
Therefore we need to keep the html.
I personally think that we should optimize for both in-file and java doc legibility.

**Comment by DanVanAtta** [comment]
Some whitespace does keep, you don't have to litter `<br/>` all over the place to get line breaks.

The HTML in this comment renders very badly. We get the worst of both worlds. The text is hard to read, the HTML is hard to read.

We don't generate an HTML javadoc, so the *only* value we are getting from HTML is for that short time while *writing* code that an auto-complete pop-up shows up and gives you an HTML rendered javadoc. I don't see that necessitating we then format all Javadocs in HTML for just that one brief and somewhat rare use-case. Particularly when we add so much cost.

What are the costs of HTML in javadoc:
- HTML in javadoc is one more thing to get right, to correct, to maintain and not break. This increases overhead and lowers velocity while we spend extra time on javadoc HTML formatting
- It makes the text hard to read, this is the *majority* use case of how we read javadoc, as plain text. That is not good. I read javadoc to help me understand, if it's illegible because it is pages long with full HTML markup, it may as well be deleted for all the good it does someone trying to understand the code.
- It discourages comments to be updated - longer comments full of mark up requires more skill and time to update, making something more difficult means it is done less often.
- It seems like a poor use of time to have any author spend time on HTML formatting in javadoc, or any time for a reviewer to do the same. I'd rather we spend that time on comment content and not format.
- HTML javadoc is *one* more thing to test. After you write code, do you render all your javadocs to ensure that everything looks good? If you don't, then you pretty clearly don't care how javadoc renders in HTML. Unless it is library code where the javadocs *will* be read a lot, then a person should *not* care.

To one extent, I think HTML in javadoc was once encouraged but is now widely viewed as a legacy anti-pattern, similar to putting other needless stuff in javadoc that we just removed recently, like @author,.

**Comment by veqryn** [comment]
I'm not defending ten line breaks in a row, I am defending the use of basic html formatting in general.
If you want to clean them up a little, please go ahead, just make sure it looks good in both whitespace and html.
I do not like complex html, but a <br/> or a <p> here and there can really help a lot.

**Comment by DanVanAtta** [comment]
I am having some trouble seeing the other side of this coin for our case. Initially I was thinking, yeah, a few strategic `<br />` here and there could really help. Though, when do we *really* need more than one line of whitespace in a javadoc comment?  So by that token, I see trouble justifying even using `<br />`

The inline stuff could add a lot of mileage for formatting HTML, but IMO it is the most egregious for making the text hard to read. The bold tags in the example above I think demonstrate, it's really hard to not notice those tags prominently and spend time filtering them out mentally.

I think it then begs the question when we write HTML in javadocs, who are we writing the javadoc for? Is it someone viewing the javadoc as HTML, or someone who is staring at a file of source code?

**Comment by DanVanAtta** [comment]
@veqryn , escape the HTML in your last comment, it was rendered invisible!

**Comment by DanVanAtta** [comment]
Can we agree to:
- html in javadocs is okay as long as it is really minimal
- prefer to avoid any HTML  markup tags other than line break and paragraph  (so no lists! Avoid using bold and italics etc, and certainly no tables!)

**Comment by veqryn** [comment]
Sure
