### ISSUE TITLE
Headless server startup with config file instead of CLI args

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1475]
Today the bot startup config is done via command line args. It can be a bit time consuming to set up the args, and it also make it harder to work with bots out of the box from source code. I propose that instead of command line we get the bot parameters from configuration file. If bots already read 'game_engine.properties', I propose that file. If not then create a new one to store bot props so they do not need to be passed in on command line.

**Comment by ron-murhammer** [comment]
Fine with me.
