### ISSUE TITLE
TripleA help

### ISSUE THREAD

**Issue by bluelionman** [triplea-game/triplea#1481]
I have downloaded the new one and the old one and can't get to work. Cant get lobby to load 0- justa  nightmare.
My old Hard Drive gave out - got a new one but lost all programmes a mate rescued off all my old files from old HD including TripleA game saves but I can't get anything to work.

HELP????

**Comment by DanVanAtta** [comment]
Could you provide some more details / screenshots of what is happening? Please be as specific as possible, it can help to narrow the problem down.

**Comment by RoiEXLab** [comment]
Things we need:
- If triplea starts and crashes the error log
- If triplea isn't starting at all the steps how you wanted to start it (did you download the installer or the jar file, what happened)

**Comment by simon33-2** [comment]
Also what OS/version are you using?

**Comment by bluelionman** [comment]
Thanks guys - I deleted everything and started again with the newest download. 

I can now load the lobby and I have down loaded a few maps of the games I used to play. Now what I want to know is 2 fold - how can I get to play my old game saves and how do i put them back into the right area on my system so when i open gave saves it offers me both the old ones and any new ones I make. 

Can anyone advise me on this - do I need to go and somehow install an older version of TrileA to?

Last but not least when logging in to the lobby why does the field not accept non English letters - i.e. many European names have hypons and such - like 'Dünner' for instance.  Do you think at a future update these could be allowed so contentinal Europeans can spell their names correctly?

Thanks

**Comment by simon33-2** [comment]
If you want to play versions created with 1.809 you need to install that version too. I think you can still get it from the sourceforge site?

Probably install it to a directory called triplea1809 or similar and put the 1.809 save games in the savedGames sub folder. I think it might force you to have this as a subfolder of "triplea" even if you install to a different directory. You can't specify your own save game folder in the old version. In 1.9 you can put the save games wherever you like.

I'm not surprised about the non english characters not being accepted.

**Comment by bluelionman** [comment]
I'm not very teckie and think this is beyond me : Tried loading it up got this in the new version said it could do old ones due to some kind of BETA conversion but never loaded got this error message:

![triplea old gamesaves issues](https://cloud.githubusercontent.com/assets/25262507/22278050/423bbd64-e2b8-11e6-8325-330033ba4c2a.png)

Be real nice if I could just do something simple to allow me to access all these old game saves - so can finish them.

**Comment by panther2** [comment]
For playing savegames with the old 1.8.0.9 version you need to redownload all the 1.8.0.9-compatible old maps using the "Download Maps"-button from inside TripleA 1.8.0.9.

**Comment by bluelionman** [comment]
My problem with that panther2 is when I load up the old version 1.8.0.9 I cant connect to the lobby get some error message - so how can I load old Maps into the new version.... as it don't seem to offer that as far as I could see in new version(1.9)....?

**Comment by DanVanAtta** [comment]
@bluelionman The 1.9 engine is not backwards compatible with the 1.8 maps. Even if you do get them loaded, you'll hit errors in most of them pretty quickly.

The 1.8.0.9 game engine can be downloaded from here: http://www.triplea-game.org/old_downloads/
After launching 1.8.0.9, you can download maps from in-game as usual.

**Comment by bluelionman** [comment]
@ DanVanAtta - I have already downloaded the old version and in it can load up my old game saves but can't get old version to connect to lobby so how on Earth can I finish the old game saves if I can't get in lobby to find opponents to finish games with?

**Comment by RoiEXLab** [comment]
@bluelionman You can't use the lobby using legacy triplea versions...
If you want to finish your game you will need to play against AI or by forum

**Comment by DanVanAtta** [comment]
If you find them in the new lobby, if one of you can host, you can still do a direct host connection (host networked game from main screen).

**Comment by bluelionman** [comment]
I don't get that as I can't load old game maps up in new TripleA and can't get in lobby from old TripleA so how could I host old game from new lobby. Confused? :-s

**Comment by bluelionman** [comment]
Who's bright idea was it to make old maps unusable on new version rendering everyone's game saves redundant. I suppose most I'd never finish as have found people don't like to finish games especially if they didn't think it was going well. Hence why I have so many game saves. :-(

**Comment by RoiEXLab** [comment]
The bright idea you mention, is not something done on purpose, but rather a side effect of the probably easiest way to save games. Compatibility is broken once we edit the part of the code, which is being used by savegames...
This topic was discussed in earlier PRs and will probably be implemented in one of the next bigger versions

**Comment by RoiEXLab** [comment]
But the AI is a strong opponent... If you really want to finish your game, I'd definitely recommend that!

**Comment by Cernelius** [comment]
> rendering everyone's game saves redundant.

I don't understand what's so hard.
You can still perfectly finish all your games, not only with 1.8.0.9, but also before.
The lobby is not something magic that makes you play live.
The lobby is just a place that shows up your hosted games in it. Hosting the game itself and have people in it has nothing to do with the lobby and, as you have been already told and could have seen yourself, you can host your games clicking on the "Host Networked Game" button and other people can join them clicking on the "Connect to Networked Game" button. The lobby is 100% unnecessary for playing live: it just makes easier to find people to play with (and provides a chatroom to talk with them outside games, in which you can simply tell people to join your 1.8.0.9 hosts, as well (just like 10 seconds slower than double clicking)).
Of course, this assuming that you or your opponent can host; if the matter is that you need an automated host service (bots), that is not anymore provided for 1.8.0.9.

If they are too lazy and refuse to join your host using the "Connect to Networked Game" with the old 1.8.0.9 (really, a 10 seconds effort), because anything more than a double click is just too much work, I guess you can count it as a victory for yourself and tell them so...
