### ISSUE TITLE
version compat issues reported

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1482]
With different versions there is a bug on placement where players are booted.
Not sure where we lost compatibility, it seems like this has to do with versions.

Recommend we knock the game version up to 1.9.0.1
Server AFAIK can stay same version/instance.

**Comment by ron-murhammer** [comment]
Oh man. We need to find a better way to ensure compatibility. Having everyone upgrade again so soon after the last release will be a huge headache. It would be better to roll back the change that broke compatibility if possible.

**Comment by DanVanAtta** [comment]
Serialization proxy pattern and removing RMI are the only real long term solutions. Anything else seems like a bandaid, and namely I don't think we'll be able to cover/address the problem any other way.

We've had some pretty good bug fixes, everyone should already have had to redownload pretty much. But to some extent this is the reason we put in so much effort to make that an easier process.

I'll point out that reverting is not really an option too, everyone would have to redownload to get the reverted/updated game engine. 

Next steps here are to knock the game version up by one, to 1.9.0.1

**Comment by DanVanAtta** [comment]
https://github.com/triplea-game/triplea/pull/1487

**Comment by Cernelius** [comment]
> (09:46:38) Kom:  You were slapped by Kom
> (09:46:48) Kom:  still having the same disconnection on placement
> (09:46:54) Kom:  i tried some old exe file but same result
> (09:46:59) Kom:  not sure what's  the issue

---

> Kom:  i still can't place units
> Kom:  get disconnected
> Cernel:  uhm
> Cernel:  so how do you get around it?
> Kom:  tried some old version, didn't work
> Kom:  i just edit when i need to place
> Cernel:  you should really make a bug report
> Kom:  and avoid placing it
> Cernel:  ok it works for revised
> Kom:  tangoromeo same issue
> Cernel:  in V3 you would end up with an enormous quantity of units saved LOL
> Kom:  lol
> Cernel:  ok, and why all those people don't make bug reports
> Cernel:  since it is so common
> Kom:  lazy i guess
> guerrilla_J:  dont have to purchase anything
> guerrilla_J:  in v3
> guerrilla_J:  just have it empty

**Comment by Cernelius** [comment]
> Shaly (2) has joined
> (19:49:53) Shaly (2):  every time we place units we get dc 
> Jgriff31 has left
> (19:50:37) Cernel:  make a bug report specifying in which host it happens and what engine version are you using
> (19:50:41) AdamF:  @shaly, save game and try new bot
> (19:51:05) Cernel:  at Adam: you mean that some bots works and other not?
> (19:51:32) AdamF:  when I get the "cant place" bug, I save, and try another bot.
> (19:51:37) AdamF:  works most of the time
> (19:51:42) AdamF:  until bug happens again
> (19:51:45) Cernel:  ok

**Comment by Cernelius** [comment]
> (19:56:51) Shaly (2):  done it 2 times - i had 1 year break but on 1.6 it was stable 
> Flottos has left
> (19:57:11) Shaly (2):  can i install any fix? 
> (19:57:24) Cernel:  make a bug report specifying in which host it happens and what engine version are you using, and maybe there will be a fix
> (19:57:48) Shaly (2):  hmm okay - ty mate 
> (19:58:26) Shaly (2):  but i think 1.6 was more stable - no hard feelings 
> (19:58:53) Cernel:  1.6? that's many years ago
> (19:59:04) Cernel:  or you mean 1.8.0.9?
> Tjeerd has joined
> (20:01:01) Shaly (2):  i'm 34 and i was 13 for my first board game. But i'm sure i had just one year break - sorry i'm german but english is not fine. 
> (20:01:35) Cernel:  definitely 1.6 was much more than 1 year ago
> (20:01:50) Shaly (2):  hmm 
> (20:02:09) Shaly (2):  if u say that okay 
> (20:02:27) Shaly (2):  we try 3 bots all broke up 
> (20:02:40) Shaly (2):  after the the first unit placement 
> (20:03:00) Cernel:  I think the problem is the bots, because I don't have this problem in my private host
> (20:03:04) Shaly (2):  are u sure its a bot problem? 
> (20:03:13) Cernel:  with many different people
> Tjeerd has left
> (20:03:42) Cernel:  no, I don't really know
> (20:04:18) Shaly (2):  Cernel are u open for a qick test? and i'm not a bad player 
> (20:04:42) Cernel:  ok join my host

Inside my private host, running 1.9.0.0.3579:

> Shaly (2) has joined
> Cernel:  You have this map, or another one?
> Shaly (2):  hey mate - can u pls switch to a classic or 3rd edition game? 
> Shaly (2):  if u have TS - ii coul offer u a server 
> Cernel:  3rd edition iron blitz or not iron blitz?
> Shaly (2):  up2u 
> Shaly (2):  ts just for testing to place units 
> Shaly (2):  don't pck all - if its working we can play 
> Cernel:  lol no I don't like classic
> Cernel:  ok so it seems it is working fine
> Shaly (2):  yeah
> Shaly (2):  ty mate 
> Shaly (2) has left

I believe the problem is with the bots, that maybe are running an old version, and need to be updated to latest.

**Comment by Cernelius** [comment]
What version of TripleA the bots are running? Are the WarClub on a particularly old one? Maybe the problem is just that.

> (23:19:48) AdamF:  do u have latest downlowad?
> (23:20:01) Chinabot:  i think so?
> (23:20:11) Schniper:  what
> (23:20:16) AdamF:  .3627?
> (23:20:35) AdamF:  if both players do not have, game will kepp getting DC'd
> Monkyde has joined
> (23:21:22) Chinabot:  how do  you even check?  haven't had this problem recently.
> (23:21:46) AdamF:  check the version you have
> (23:21:57) Chinabot:  oh, i see, .3453
> (23:22:01) AdamF:  right
> (23:22:21) AdamF:  u need .3637...and for some reason "warclub" bots are no good
> (23:22:28) AdamF:  3627*
> (23:22:41) Cernel:  what is the problem with the warclub bots?
> (23:22:42) Chinabot:  ok, i will update and be back...
> (23:22:45) AdamF:  k
> Chinabot has left
> (23:23:11) Zerschmetterling:  Wir haben alles richtig gemacht. Wir werden einfach von unseren Computern Bochiert.
> (23:23:14) Cernel:  you mean that with new the warclub bots have the disconnection on placement and the other bots instead are fine?
> (23:23:32) AdamF:  thats what has been happening to me'
> (23:23:42) Cernel:  ok
> (23:23:58) AdamF:  especially if both players do not have latets version
> serhat has joined
> shadowhawk has left
> (23:24:14) AdamF:  and especially in war club bots

**Comment by Cernelius** [comment]
A reported case in lobby:

> AdamF has joined
> (21:45:14) johanpro:   anyone want to play europe 1940 2nd edition?
> (21:45:20) AdamF:  sunny
> (21:45:24) Sunny:  7
> (21:45:36) AdamF:  do you have version .3627?
> stephen_ham has left
> (21:45:44) Sunny:  ya
> (21:45:50) Sunny:  i had that bug lately
> (21:45:55) Sunny:  what u had just right now
> (21:45:58) scistein:  anyone want to play axis II Revised
> (21:46:03) johanpro:   anyone want to play europe 1940 2nd edition?
> (21:46:04) Sunny:  bot change helped
> (21:46:12) franz2018:  1941 anyone??
> (21:47:04) Sunny:  anaother bot
> (21:47:23) AdamF:  war clubs are no good
> (21:47:29) AdamF:  i dont know why
> (21:47:48) AdamF:  happened yesterday too
> (21:47:50) franz2018:  bot44
> (21:48:10) AdamF:  Mods: can we have some "regular bots"?
> (21:48:14) scistein:  gunzen how do I connect?
> (21:48:15) AdamF:  NOR war club?
> (21:48:33) Cernel:  what?
> (21:48:38) AdamF:  Cernel
> (21:48:38) Cernel:  what do you mean regular bots?
> (21:48:42) johanpro:   anyone want to play europe 1940 2nd edition?
> (21:48:43) yippi:  hi
> (21:48:43) Cernel:  regular bots are the WarClub ones
> (21:48:48) yippi:  bot7
> (21:48:52) AdamF:  every time I try to place units (bot 07)
> (21:48:57) AdamF:  we get dc'd
> (21:48:58) moimemme:  omw
> worth has joined
> (21:49:07) AdamF:  same problem as yesterday
> scistein (1) has joined
> (21:49:19) Sunny:  41, adam
> (21:49:21) AdamF:  both players have .3627
> (21:49:27) Cernel:  ok, I'll report it
> (21:49:32) Cernel:  you can report it too, btw
> (21:49:32) AdamF:  ty
> (21:49:59) Cernel:  so .3627 causes disconnections upon placement in Bot7_WarClub, right-o

**Comment by Cernelius** [comment]
Just copy pasting the whole chat, because I've not much of a clue myself (I can only say that for me while hosting with a recent version I never had this problem, and almost all of my games it's me hosting them):

> (21:47:31) -Villars:  ?
> (21:47:32) Patton77:  bot7 for revised
> (21:47:35) AdamF:  damn
> (21:47:39) -Villars:  what happened?
> (21:47:39) AdamF:  bad bot villars
> (21:47:46) AdamF:  the "placement bug"
> (21:47:46) -Villars:  ok i host
> BiggusDiggus has left
> (21:48:12) AdamF:  k
> (21:48:16) mortetvie:  sunniswarow, I am back
> (21:48:26) stephen_ham:  4
> (21:49:15) -Villars:  join, AdamF
> (21:50:24) stephen_ham:  We got problems here.
> (21:50:29) -Villars:  what now?
> ingcameroni has joined
> (21:50:45) AdamF:  same thing
> (21:50:53) AdamF:  do u have version .3627?
> (21:50:55) -Villars:  try again?
> (21:51:06) ingcameroni:  adam
> (21:51:07) -Villars:  3277
> (21:51:11) AdamF:  not good
> (21:51:15) AdamF:  u need new version
> (21:51:19) -Villars:  ?
> (21:51:20) AdamF:  Hi Ing
> (21:51:31) AdamF:  go to triples.org/downlowad
> (21:51:38) AdamF:  triplea
> (21:51:39) stephen_ham:  got the update.
> (21:51:40) AdamF:  .org
> (21:51:45) ingcameroni:  hi
> (21:51:53) ingcameroni:  cont...?
> NormanSchwarzkopf (1) has joined
> (21:51:56) SunnisWarOwFukIs:  sry in a game now
> (21:51:58) AdamF:  sure ing
> (21:52:01) mortetvie:  aww ok
> (21:52:12) AdamF:  did u fix settings?
> (21:52:16) ingcameroni:  yes
> (21:52:25) AdamF:  bot 01
> kolja has left
> (21:52:37) stephen_ham:  settings?
> (21:52:58) AdamF:  not u steph
> (21:53:05) AdamF:  bot 01 Ing
> vince79 has left
> (21:53:18) ingcameroni:  ok
> (21:53:33) mortetvie:  anyone for a game?
> (21:53:37) stephen_ham:  can we work this?
> (21:53:44) ingcameroni:  came
> (21:53:48) wirkey:  i've got no clue
> (21:54:00) wirkey:  i'll do my move in local mode
> (21:54:02) stephen_ham:  can you host?
> TheKhan has left
> (21:54:12) BridgeGold:  anyone up for global?
> (21:54:40) ingcameroni:  yes
> (21:54:40) AdamF:  we playing now, or u need time?
> (21:54:42) wirkey:  no
> (21:54:51) ingcameroni:  im in both1
> (21:54:54) -Villars:  3277
> (21:55:03) -Villars:  no change
> (21:55:10) wirkey:  but maybe we can skip a bug
> (21:55:15) BridgeGold:  come to bot41
> (21:55:16) stephen_ham:  Bot crashes when placing units. My host crashes when you do combat. 
> (21:55:47) BridgeGold:  bot41 works
> (21:56:06) ingcameroni:  hey
> (21:56:14) BridgeGold:  bot41
> (21:56:23) wirkey:  i only got a pre russian save
> (21:56:29) ingcameroni:  im in game now
> (21:56:32) ingcameroni:  sorry
> (21:56:34) stephen_ham:  ok
> (21:56:53) Olcayto:  ,
> (21:56:55) stephen_ham:  Where?
> yamamot0 has left
> (21:57:44) ingcameroni:  noo
> (21:57:51) ingcameroni:  the same problem
> gazza has left
> (21:58:03) stephen_ham:  try?
> (21:58:11) AdamF:  yes
> (21:58:14) BridgeGold:  bot41 works
> (21:58:15) AdamF:  hey mods
> (21:58:23) AdamF:  what is going on with the bots ?
> (21:58:50) AdamF:  You were slapped by AdamF
> (21:59:32) AdamF:  bot 2
> stephen_ham has left
> cjnatz33 has left
> Lukasz has left
> (22:01:03) BridgeGold:  the lower numbered bots are fucked
> (22:01:45) Cernel:  what?
> (22:01:50) Cernel:  what is the problem with the bot?
> (22:02:01) ingcameroni:  try 30
> (22:02:06) AdamF:  they keep crashing after placement
> (22:02:22) Cernel:  isn't that thet usual problem?
> (22:02:27) AdamF:  yes
> (22:02:40) AdamF:  both players have .3627
> (22:02:48) Sylvest888:  Don't place, just skip and edit after 
> (22:02:54) Cernel:  and you confirm that the problem is only for the bots from 1 to 8, while the 01 etc. works fine, right?
> (22:03:03) AdamF:  no
> (22:03:08) AdamF:  but trying 30 now
> (22:03:13) ingcameroni:  ok
> (22:03:16) ingcameroni:  try
> Prowilly has left
> TheKhan has joined
> (22:05:04) TheKhan:  bot 8
> tulkas has joined
> (22:06:07) Cernel:  ok, so does 30 work fine?
> (22:06:14) AdamF:  i cheated cernel
> (22:06:23) AdamF:  editied instead of palced
> AdamF has left
> KGB has left
> AdamF has joined
> antagonista has left
> (22:06:57) yippi:  45
> (22:06:57) TheKhan:  bot 8
> (22:07:01) yippi:  8 doesnt work
> (22:07:11) TheKhan:  then 44
> NormanSchwarzkopf has left
> (22:09:00) AdamF:  Cernel, is there a fix for the problem?
> (22:09:31) Cernel:  maybe nobody really knows what the problem is
> (22:09:49) Cernel:  can you tell me what version are you using and in what bots it works and in what bots it doesn't
> (22:09:56) AdamF:  .3627
> (22:10:29) Cernel:  ok, so it doesn't work in all bots or only some?
> (22:11:03) AdamF:  random
> (22:11:10) AdamF:  have not tracked the errors

**Comment by Cernelius** [comment]
My personal guess is that all the issue might boil down just to only the old bots from Bot1_WarClub to Bot8_WarClub being outdated and conflicting with latest versions, while the other bots might have no problems (not sure):

> (22:15:17) AdamF:  You were slapped by AdamF
> (22:15:22) AdamF:  bot 30 is ok
> (22:15:32) Cernel:  ok

**Comment by Cernelius** [comment]
Also, looks like there is some sort of bug that happens when you undo your placement instead. I'm not sure of this, and never happened to me, but it is not the first time I see this rumour. May be related to this, or just another different bug; duno:

> (20:19:17) vince79:  disconnected
> (20:19:26) vince79:  that new version has a big issue with placement of new units
> (20:19:35) moimemme:  y
> (20:19:45) vince79:  we must edit right ?
> (20:20:07) moimemme:  only when we need to undo placements
> (20:20:24) Cernel:  maybe make a bug report

 And, yeah, people keep complaining in lobby; no point pasting the same thing, sorry for the multiple report of the same stuff, but since people slap me for a solution (?), I guess I can just tell them I'll report (you can skip reading the chat below, as it is just the same aforementioned thing):

> (20:24:04) junkfood61:  Hello
> (20:24:10) junkfood61:  why do i keep dc'ing
> (20:24:13) junkfood61:  when i place units
> (20:24:23) junkfood61:  Can any one help resolve this issue?
> (20:24:58) BridgeGold:  global
> (20:25:10) Escadrille:  rev anyone?
> (20:25:22) Ondis:  revert to version 3453
> huund has joined
> (20:26:00) BridgeGold:  global bot40
> Raville has left
> (20:27:39) junkfood61:  You were slapped by junkfood61
> (20:27:41) huund:  Olcayto wanna play ?
> (20:27:43) Cernel:  yes?
> (20:27:46) junkfood61:  You were slapped by junkfood61
> (20:27:51) Cernel:  what?
> (20:27:52) junkfood61:  Can you help me
> (20:27:57) junkfood61:  I dunno whats wrong
> (20:27:58) Escadrille:  rev anyone?
> (20:28:01) Ondis:  i told u
> (20:28:03) junkfood61:  whenever i try to place units
> (20:28:06) Ondis:  revert to older verison
> (20:28:16) junkfood61:  But how do i do that?
> (20:28:17) junkfood61:  O_o
> (20:28:23) junkfood61:  do i just pick an older map?
> (20:28:24) Cernel:  it's a known bug, but if you want you can make a bug report
> (20:28:27) Escadrille:  huund, thought you quit 
> (20:28:42) Cernel:  just for the record, what engine are you using and in which host it is happening?
> (20:28:51) huund:  Ye. gonna play with my friend, told you to save the game
> (20:29:04) junkfood61:  Im using windows 10
> (20:29:13) Cernel:  no, I mean the TripleA version
> (20:29:53) junkfood61:  running the tripple A launcher 19.0.0.3627
> (20:30:03) Cernel:  ok and which host?
> (20:30:12) junkfood61:  Bot2
> (20:30:14) junkfood61:  bot4
> (20:30:16) junkfood61:  and bot10
> (20:30:18) junkfood61:  tried all 3
> (20:30:32) Cernel:  ah
> (20:30:35) Cernel:  bot10 is back
> (20:30:40) Escadrille:  to late mon
> (20:30:42) Cernel:  thought they limited to 8 only
> (20:30:49) Escadrille:  game gone already
> (20:31:15) junkfood61:  ill try bot 10 again
> (20:31:33) Cernel:  well, I'll report this, I guess, not much else I can do; maybe try the not plain WarClub bots
> (20:32:01) Ondis:  can someone linkk him
> (20:32:03) Ondis:  the github link
> (20:32:06) Ondis:  so he can get the older version
> (20:32:25) Cernel:  maybe use Bot04_NJ_WarClub; could be that the new one works; I duno
> (20:32:36) junkfood61:  Would be awesome if anyone could link github
> (20:33:05) Cernel:  uhm well, I'm not sure if I should encourage people downgrading, especially since the directives are to upgrade
> (20:33:14) Cernel:  but anyways, you can get whatever older version here
> (20:33:15) DayMar:  axis is favoured in smalls
> (20:33:28) DayMar:  due to additional battleship italy
> (20:33:47) Cernel:  https://github.com/triplea-game/triplea/releases
> (20:33:59) Cernel:  all the releases are there, just go forward for older and older
> (20:34:32) junkfood61:  Ty so much
> (20:34:38) junkfood61:  and sorry for slapping you

You can just join the lobby for a while and will probably see people complaining about this; I'm thinking they are all bot users, but not sure.

Also, it is awkward talking about different bots with some called just WarClub and some others called Something_WarClub; I suggest renaming, or at least not having things like "Bot1" and "Bot01". I already suggested that in WarClub.

**Comment by Cernelius** [comment]
The main problem with having multiple redundant properties doing the same thing, and other rubbish like that (kept for backward compatibility), is that it is more frequent than you might think that practically about everyone but the most experienced mapmaker end up overlooking the matter and setting both in the xml, and sometimes even one opposite to the other, and you have to wonder what this will cause and what the mapmaker actually intended, if anything.

For example, surtur is quite the experienced mapmaker, yet in the map he posted you can see:
http://tripleadev.1671093.n2.nabble.com/Domination-1914-Weltpolitik-tp7595270.html;cid=1486520643202-38
```
				<property name="SBR Affects Unit Production" value="false" editable="false">
						<boolean/>
				</property>
				
				<property name="Damage From Bombing Done To Units Instead Of Territories" value="true" editable="false">
						<boolean/>
				</property>
```
Similarly, if you have only 1 property not working by v1 rules, you are almost assured that about everyone but the most experienced mapmakers will get it wrong (missing to specifically set it properly), if they want their games working by v1 rules. Thus, v1 maps end up having the bombardment working like Revised, and it is annoying, when you play that (Games of Thrones comes to mind), to discover it in the middle of the game, while you assumed that all was Classic rules.

**Comment by DanVanAtta** [comment]
Do you have any recommendations for what should be done @Cernelius ?

**Comment by Cernelius** [comment]
As I said, I believe (not sure), the problem exists only if the hoster is on old and the hosted is on new, thus I think the matter boils down that the old WarClub bots are still on old and need to be updated. I'm not sure, but looks like people have problems only in those.

Also, while you are at it, I still suggest to name them better, that is:
- Not having some bots called "XXX_WarClub" and others called just "WarClub".
- Not having both Bot1 and Bot01 (I definitely suggest **Bot01** over Bot1, for various reasons).

**Comment by DanVanAtta** [comment]
Agree, they need to be upgraded and renamed.
