### ISSUE TITLE
lobby DB stack

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1484]
If we're going to migrate to a new DB stack. From previous discussion its seems we want to go to MySql.

Does anyone have any particularly good experiences with DB access frameworks?

I would propse:
mybatis + liquibase + hsqldb

The above would let us set up an in-memory DB for unit test, do DB migrations with liquibase, and then mybatis as an ORM layer.

**Comment by ron-murhammer** [comment]
I'd prefer hibernate over mybatis. Not sure we really need liquibase as the database schema is rarely ever changed (probably has been the same for years now).

**Comment by DanVanAtta** [comment]
Sorry to say I've a strong preference to avoid hibernate. We are using JDBC today, going from that to MyBatis is a pretty straight forward change since both use raw SQL.  MyBatis has a DB migration functionality built in to it, likely we'll go for something lower tech than that even. Liquibase is likely not too hard to add on, but for now I'm focusing on DB migration.

**Comment by ron-murhammer** [comment]
Based on our conversation, I think we are gonna just stick with JDBC for simplicity.
