### ISSUE TITLE
NodeBB forum - 'http://forums.triplea-game.org'

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1486]
A nodeBB forum has been set up here: http://forums.triplea-game.org/

It looks pretty good, easy enough to manage. This issue is to gather feedback, and keep track of some things to do before launching it.

Todo:
- [x] finish setting up email. Lost password, and email confirmation for registration
- [x] add a link in the forum to the triplea-game.org website
- [x] add a link from the .org website to the forum
- [ ] advertise the new forum in SF and warclub forums (begins the migration)

Previous discussion on the topic:
https://github.com/triplea-game/triplea/issues/1067

**Comment by ron-murhammer** [comment]
@DanVanAtta I think the main point is going to be discussing/convincing the existing mods that use warclub to use the new forum. Is the plan to consolidate both warclub and sourceforge forums to it?

**Comment by DanVanAtta** [comment]
Yes. I believe they are on board at this point. They've known the plan was to get off of Xoops/PHP to something new. I opened up a bunker post to discuss the same topic, just to be sure we have everyone in the loop here. 

forums.triplea-game.org is backed by NodeBB. RoiEx had it set up in almost no time. I think this is the replacement for the forums that we've been waiting for.

**Comment by beelee1** [comment]
just went to the new forum joined up but never received a confirmation email. Went back to the new forum just now and got the "your connection is not secure website has been configured improperly"

Just thought I'd give a heads up

![insecure connection](https://cloud.githubusercontent.com/assets/24382682/22196472/f2eaaf14-e112-11e6-8725-5a8b02942549.png)

**Comment by RoiEXLab** [comment]
@beelee1 The problem you had, was that you were accessing the site via https instead of http... https should work fine now, I worked on this about 8 hours ago, maybe you were accessing the site just when i was editing it...
Could you open [https://forums.triplea-game.org/](https://forums.triplea-game.org/) again?

**Comment by beelee1** [comment]
we're all good now roiEX. I didn't realize I had to click on the box to have the email sent. Good job on the site

**Comment by RoiEXLab** [comment]
@beelee1 Emails are currently not supported yet, we are working on this...

**Comment by beelee1** [comment]
ahh...was wondering thanks

**Comment by RoiEXLab** [comment]
@DanVanAtta 2. is done!

**Comment by RoiEXLab** [comment]
@DanVanAtta 1. and 2. are adressed, 3. is adressed in https://github.com/triplea-game/triplea-game.github.io/pull/169
4. can be adressed right after this PR is merged...

**Comment by bung** [comment]
Will the nodeBB forums be brought into the triplea-game website repo?

**Comment by RoiEXLab** [comment]
Probably not, because we already use the official Repository https://github.com/NodeBB/NodeBB
If we have a problem or found a bug, we can open an issue there

**Comment by bung** [comment]
@RoiEXLab Hmm, I'm not familiar with the product itself, so let me ask then, in one thread I read some comments about having to have an entire theme developed just to make minor design changes to the nodeBB instance. If you have already done something like change the header image, how/where is that being managed? If there was a repo for the "triplea theme" others could contribute/support the forums look and feel.

**Comment by RoiEXLab** [comment]
Allow me to explain:
NodeBB is very modular, the theme is another Repository https://github.com/NodeBB/nodebb-theme-persona
If we wanted to edit this theme, we could fork it and npm publish it afterwards which makes it available in our forum plugin installation list.
The way I edited the header was rather easy. I added a line of css in the "custom css" section which sets the background image of the header tag.
But yeah, we could have our own Repository for our custom theme.. Templating is rather easy.
You might have a look at the repository I linked above to see how it's done

**Comment by RoiEXLab** [comment]
But like I said, in this case WE would need to keep the theme up-to-date ourselves.

**Comment by DanVanAtta** [comment]
@RoiEXLab  do we have docs/notes on how the nodeBB forum was setup? I vaguely recall some, it would be good to have in case we need to repeat it, and to know fully what moving parts we have.

Otherwise I think we are fully set up with the new forum now? Any reason to not officially tell people to use it?

**Comment by RoiEXLab** [comment]
I setup nodebb according to the ["official instructions"](http://nodebb.readthedocs.io/en/latest/installing/os/ubuntu.html) with some minor modifications.
And the forum is ready to be used... The only downside is that PBF isn't working until my pr is merged...
