### ISSUE TITLE
Lobby Login

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1489]
The new nodeBB forum can expose an endpoint for doing auth (@RoiEXLab). This could be a way to unify login between the lobby and forum. I think for only this, it's potentially a good move. I dont' think we should capture any further data in nodebb. 

Some considerations:
- once authenticated, how does server know that future requests are valid for that same user? How do we do this today in the tripleA code?

**Comment by Cernelius** [comment]
> unify login between the lobby and forum.

Yes.

**Comment by Cernelius** [comment]
An item, tho, is that you should take care keeping the bans etc. set apart, as banned etc. people need to access forum to complain (moderators are not infallible, nor perceived as infallible).
Meaning that, if you get banned from the lobby, you should get banned from the lobby and all bots, but not from the forum; same for muting and booting.

**Comment by yamamot0** [comment]
unify login between the lobby and forum: yes
but people banned on the server should still be able to access the forum:. because they should be able to complain - and read the lobby rules :)

**Comment by DanVanAtta** [comment]
That's a good point yamamot0. Though we're going to stop keeping documentation in forum, so the rules will be available here: triplea-game.org/help

@RoiEXLab I've been wondering if we should keep forum and lobby on same server. I think it would be good if we did not constrain ourselves to that. To avoid same server we likely we just have set up an https connection. Thoughts?

**Comment by RoiEXLab** [comment]
@DanVanAtta what do you mean by a new https connection? If you mean a new subdomain like lobby.triplea-game.org I have no objections on that, I'd appreciate that.

**Comment by DanVanAtta** [comment]
server -> server communication, best to do that encrypted (ie: https)
Why the lobby subdomain?

**Comment by RoiEXLab** [comment]
@DanVanAtta Ok I misunderstood you, but I still don't get what exactly you want to do...

**Comment by DanVanAtta** [comment]
Hmm. wasn't the goal here to open an endpoint for the forum server to do auth for the lobby? IE: lobby communicates to that forum endpoint to verify user + pass

**Comment by RoiEXLab** [comment]
Yes, but there's an API for that... We call https://forums.triplea-game.org/api/ns/login with POST params username and password, and we get json as result...
https://www.npmjs.com/package/nodebb-plugin-ns-login

**Comment by RoiEXLab** [comment]
So its irrelevant where the lobby server is located...

**Comment by prastle** [comment]
Yes one login for both and bans affect both except ability to post in perhaps one category?
