### ISSUE TITLE
TripleA 1.9 Lobby suddenly unusable (after version update)

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#1493]
Hi,
Not sure what is going on but whenever I start Triple-A 1.9 it just freezes up. Buttons not displayed. Running via gradle with the most recent source allows the buttons to be displayed but none of them accept clicks. Appears to be some sort of server resource offline. 

Perhaps a problem with the moving on of the version number? Re-downloading still grabs 1.900.

EDIT: just checked out master and "gradle run" gets it to work.

**Comment by beelee1** [comment]
yea i just started up another one and all I get is a blank screen. The one already open still works

**Comment by snyderan** [comment]
I am also having all kinds of problems.  Noticed that the game only boots when my wifi is off.  Otherwise, it freezes every time.

**Comment by Tomab** [comment]
Yes, I can play the game just fine if I disable my net card or unplug my ethernet cable.  If I'm connected to the internet, the game freezes.  This is a terrible design, the game should never rely on online resources to start.

**Comment by simon33-2** [comment]
Yep - work around is to disable networking, start triple-A then re-enable networking.

#1494

**Comment by DanVanAtta** [comment]
A bump in game version: https://github.com/triplea-game/triplea/pull/1487 likely triggered this. That has been rolled back.

**Comment by simon33-2** [comment]
Hmm, so does this mean we can't change the version number?

Or that we need a lobby*.yaml reference that is static for a given version? I've noticed that the lobby*.yaml file appears to be omitted from the installer. Did that cause the problem?

**Comment by DanVanAtta** [comment]
yes, changing version number at the moment does seem pretty bad. We need to figure out what happened here and fix.

**Comment by simon33-2** [comment]
Done some debugging on this one. Seems that the code which is triggered when the engine is out of date hangs.

Around line 520 of src/games/strategy/engine/framework/GameRunner.java has:
        SwingUtilities
            .invokeLater(() -> EventThreadJOptionPane.showMessageDialog(null, latestEngineOut.getOutOfDateComponent(),
                "Please Update TripleA", JOptionPane.INFORMATION_MESSAGE, false, new CountDownLatchHandler(true)));


This block appears to hang even though getOutOfDateComponent() returns ok.

**Comment by ssoloff** [comment]
I'm not entirely sure about this, but it looks like `EventThreadJOptionPane#showMessageDialog(Component, Object, String, int, boolean, CountDownLatchHandler)` should not be called from the EDT because it subsequently awaits upon a latch.  This method kicks off the actual Swing message dialog on the EDT where the latch count is decremented:

```java
  public static void showMessageDialog(final Component parentComponent, final Object message, final String title,
      final int messageType, final boolean useJLabel, final CountDownLatchHandler latchHandler) {
    final CountDownLatch latch = new CountDownLatch(1);
    SwingUtilities.invokeLater(() -> {
      JOptionPane.showMessageDialog(parentComponent, useJLabel ? createJLabelInScrollPane((String) message) : message,
          title, messageType);
      latch.countDown(); // <-- latch count will be decremented on EDT
    });
    if (latchHandler != null) {
      latchHandler.addShutdownLatch(latch);
    }

    awaitLatch(latchHandler, latch);  // <-- awaiting on EDT; deadlock?
  }
```

There are only two other callees of this overload (in `TripleAFrame`), and they both invoke it on an instance of `ThreadPool` named `messageAndDialogThreadPool`.  So it's possible that `GameRunner` should also ensure this method is called on a non-EDT thread.

Actually, it looks like there's code in other `EventThreadJOptionPane` methods that show some kind of dialog that detects when it is running on the EDT and to bypass the whole `invokeLater()` and latch stuff and to just run the callback immediately.  The particular overload of `showMessageDialog()` in question probably was just overlooked.  Maybe the real fix is to introduce this same guard clause in this overload, as well:

```java
    if (SwingUtilities.isEventDispatchThread()) {
      JOptionPane.showMessageDialog(parentComponent, useJLabel ? createJLabelInScrollPane((String) message) : message,
          title, messageType);
      return;
    }
```

**Comment by simon33-2** [comment]
Looks like that if statement returns false if called immediately before the current JOptionPane code. Perhaps I've placed it incorrectly?

**Comment by ssoloff** [comment]
@simon33-2 No, I think you're ok.  It's perfectly fine for the thread executing `GameEngine#checkForLatestEngineVersionOut()` to not be the EDT.  But you still need to remove the `SwingUtilities.invokeLater()` wrapper around `EventThreadJOptionPane#showMessageDialog()` in that method in order for it to work correctly.  That is, the code you previously referenced should be:

```java
      if (ClientContext.engineVersion().getVersion().isLessThan(latestEngineOut.getLatestVersionOut())) {
        EventThreadJOptionPane.showMessageDialog(null, latestEngineOut.getOutOfDateComponent(),
                "Please Update TripleA", JOptionPane.INFORMATION_MESSAGE, false, new CountDownLatchHandler(true));
        return true;
      }
```

I ran with the above change, and I saw the "Please Update TripleA" message without anything hanging.

Just adding the guard clause to `EventThreadJOptionPane#showMessageDialog()` is not enough--it's simply there to protect against the case when someone **does** try to call it from the EDT (which currently doesn't seem to ever occur, but who knows what may happen in the future).

**Comment by ssoloff** [comment]
A quick follow-up to my previous comment...  I noticed some exceptions in the console when I did this.  The gist of the exception was that some UI code was executing off the EDT:

```
org.pushingpixels.substance.api.UiThreadingViolationException: Component creation must be done on Event Dispatch Thread
	at org.pushingpixels.substance.internal.utils.SubstanceCoreUtilities.testComponentCreationThreadingViolation(SubstanceCoreUtilities.java:2048)
	at org.pushingpixels.substance.internal.ui.SubstancePanelUI.createUI(SubstancePanelUI.java:57)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at javax.swing.UIDefaults.getUI(UIDefaults.java:769)
	at javax.swing.UIManager.getUI(UIManager.java:1016)
	at javax.swing.JPanel.updateUI(JPanel.java:126)
	at javax.swing.JPanel.<init>(JPanel.java:86)
	at javax.swing.JPanel.<init>(JPanel.java:95)
	at games.strategy.engine.framework.EngineVersionProperties.getOutOfDateComponent(EngineVersionProperties.java:135)
	at games.strategy.engine.framework.GameRunner.checkForLatestEngineVersionOut(GameRunner.java:520)
	at games.strategy.engine.framework.GameRunner.lambda$4(GameRunner.java:485)
	at java.lang.Thread.run(Thread.java:745)
```

It looks like the `EngineVersionProperties#getOutOfDateComponent()` method needs to run on the EDT.  Therefore, the correct change is **not** to remove the `SwingUtilities#invokeLater()` call in `GameEngine#checkForLatestEngineVersionOut()`; the guard clause in `EventThreadJOptionPane#showMessageDialog()` should be enough.

If you keep the `invokeLater()` call in `checkForLatestEngineVersionOut()`, the new expression `SwingUtilities.isEventDispatchThread()` in `showMessageDialog()` _should_ return `true`.

I just re-ran this, and I now get the "Please Update TripleA" message _without_ any exceptions reported in the console. 😃

**Comment by simon33-2** [comment]
@ssoloff I'm confused. Removing the invokeLater bit was the only change I made. What is the change I need to make - put "SwingUtilities.isEventDispatchThread()" somewhere - into getOutOfDateComponent() ?

**Comment by ssoloff** [comment]
Sorry for not being clear, @simon33-2.  Like I said, it was late last night when I wrote my previous comments. 😃

The only change I made (after my second comment) was adding the guard clause at the top of the specific overload of `EventThreadJOptionPane#showMessageDialog()` being called, as follows:

```diff
diff --git a/src/games/strategy/util/EventThreadJOptionPane.java b/src/games/strategy/util/EventThreadJOptionPane.java
index f84e06c..903d15e 100644
--- a/src/games/strategy/util/EventThreadJOptionPane.java
+++ b/src/games/strategy/util/EventThreadJOptionPane.java
@@ -26,6 +26,11 @@ public class EventThreadJOptionPane {
 
   public static void showMessageDialog(final Component parentComponent, final Object message, final String title,
       final int messageType, final boolean useJLabel, final CountDownLatchHandler latchHandler) {
+    if (SwingUtilities.isEventDispatchThread()) {
+      JOptionPane.showMessageDialog(parentComponent, useJLabel ? createJLabelInScrollPane((String) message) : message,
+          title, messageType);
+      return;
+    }
     final CountDownLatch latch = new CountDownLatch(1);
     SwingUtilities.invokeLater(() -> {
       JOptionPane.showMessageDialog(parentComponent, useJLabel ? createJLabelInScrollPane((String) message) : message,
```

**Comment by ssoloff** [comment]
@simon33-2, were you able to get this to work?

**Comment by simon33-2** [comment]
Sorry, must have missed this comment.

**Comment by ssoloff** [comment]
@simon33-2  NP, was just checking if you were going to submit a PR.  Since I didn't see any activity, I went ahead and submitted #1558.

**Comment by ssoloff** [comment]
@simon33-2: The fix for this issue has been merged to `master`.  I know you tested the PR directly, but when you have time, could you validate the fix in the latest release build and close the issue?  Thanks.
