### ISSUE TITLE
Startwindow frozen; 1.8 work; 1.9 not

### ISSUE THREAD

**Issue by xxxMarkusxxx** [triplea-game/triplea#1494]
Please help me a bit. I have allready played triplea allready a lot of time. But suddenly it don't work anymore. I use the latest Java version and reinstalled triplea allready. Startwindow appears but all buttons can't be select. Any idea???

**Comment by klousia** [comment]
same problem here.  except I turned on my computer and the problem happened after playing earlier today.  Deleted everything and reinstalled same result

**Comment by beelee1** [comment]
you can play locally if you turn your wifi off. Same issue as #1493

**Comment by xxxMarkusxxx** [comment]
okay thanks. Now it works again.

**Comment by DanVanAtta** [comment]
Merging with #1493, please see there for follow up
