### ISSUE TITLE
mp3 questions

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#150]
Playing mp3 sounds is not terribly difficult happily. We'll  need a couple of small jar libraries available from javazoom: http://www.javazoom.net/mp3spi/mp3spi.html, and a couple lines of code to decode MP3 codecs (wav files will still work): http://stackoverflow.com/a/17570819

The wav files today take about 110MB of space. Converting to 192 bit rate MP3 reduces that to 15MB

So two questions about this:
1. Which bit rate do we want? 
- 128 you can generally hear audio quality degradation, I think that rules it out from consideration. 
- 160 is a high bit rate and an option, it's the first bit rate you could probably call high quality sound. Here is a web page with sample comparisons of different bit rates: http://www.knowzy.com/Computers/Audio/Digital_Audio_Files/mp3/Comparing_MP3_Bitrates.htm. Though 160 you can *still* hear *some* differences, some degradation in audio quality. For our sounds, mostly sound effects, this likely won't matter. For the 1812 overture start sound, we *may* notice sound quality differences between 160 bit rate compared to 192 or 256.
- 192 bit rate is a high quality bit rate. Back in the MP3 days this was my favorite bit rate since it was better than 160 and sounded as good as 256. 192 starts to give you close to loss-less quality. You'll notice a difference between 192 and 256 if listening to classical music with lots of stringed instruments, and you have a trained ear. For our purposes, 192 should be plenty good enough.
- Last, 256 is CD quality. This is *really* close to loss-less, trained musicians will have trouble telling the difference from actual loss-less quality. Going above 256 generally needs some special circumstances, like sound production or sound editing work. 256 is the last bit rate that still makes some sense for us.

Second question:
Do we want to back up the lossless wav files somewhere? We would want to do this if we ever want to re-encode the sound files to another bit rate or sound format.

- option number 1, my preference, set 192 bit rate mp3 to be the standard and we'll keep it simple
- option number 2, create a loss-less sound folder to store a copy of the wav files
- optoin number 3, my preference if want a backup of wav files, create another repo to store the sound files in. This way the 110MB of wav's doesn't slow down our main repository, and chances are we'll only ever access the wav file backups once or twice more if we ever access them again.

**Comment by ron-murhammer** [comment]
@DanVanAtta Honestly I know almost nothing about technical details of MP3s and this might be a better question for the dev forum so you can get mapmakers input as they often have opinions on sounds/images/etc.

**Comment by DanVanAtta** [comment]
There are basically two questions in this issue. Which bit rate and whether to store an archive of the loss-less assets somewhere.

I have both  professional and hobby background relevant to this,  I attempted to give the set of possible answers in the OP. The exact answer we want to go with depends on some priorities and balances that are project specific and more or less up to the admins. If you have no strong preference, then I suggest we opt for the conservative and non-destructive choices.

That would answer the question of whether to archive loss-less audio assets, the answer would be yes. 

In that case,  @ron-murhammer , would you mind creating a repo called something like "lossless_assets". I'll submit a PR into that repo with our current wav files. This way we will always be able to re-encode them to whatever we want.

In parallel I'd like to experiment a bit with variable bit rate, perhaps post some audio samples, and I'll raise the bit rate part of this question on the forum.

**Comment by DanVanAtta** [comment]
@ron-murhammer  PS, we can rename the lossless asset repo at any time, so there is not much risk in creating it, particularly since we are not yet even touching the triplea-game repo.

The second repo is needed so we can eventually shed the 110MB of wav files from the current repo (and practically so we can re-encode files in case we choose to do so sometime down the road for whatever reason).

**Comment by ron-murhammer** [comment]
@DanVanAtta So do we really need another repo? If we all come to agreement on a standard and plan to move forward with mp3's then we really shouldn't ever need the wav's again. In that case isn't just having them in the history of the version control enough?

**Comment by DanVanAtta** [comment]
Having them in the history when not needed is bad because it consumes 110MB of space, which is a lot and a full 10% towards our total limit. Basically all the reasons for not storing binaries in git apply. So for example, it is 110MB of unused files you have to DL whenever you clone the repo, it is 110MB of object data Git has to traverse and maintain for git operations, etc..

I also don't think we will ever need the wav files again, particularly when we will replace them with highly sampled mp3 files.

If you're comfortable with that decision, then the second repo is not needed (I'm relatively comfortable with it, but I think the cost is minimal, so probably just better to do it).

In specific, the cost of this new repo would mainly be the set up cost. Which is very minimal (web ui forms make this easy). The repo would also sit comfortably with no maintenance requirements since it is a static content archive. Then a year or two or many from now it would be one of two conversations:  "yes, we were right, we didn't need the wav files anymore after all," or alternatively:  "yes, we found a reason for needing them and were happy to have had them."

**Comment by ron-murhammer** [comment]
@DanVanAtta I guess I'm a little confused here. Are you proposing that we permanently delete the wav files from all the history as well such as https://help.github.com/articles/remove-sensitive-data/. Or are you just saying we remove them normally in a commit? 

If its the latter then they will always exist in the history and can be brought back using something like: http://stackoverflow.com/questions/953481/find-and-restore-a-deleted-file-in-a-git-repo

If its the first one then we definitely need to back them up somewhere and making a new repo might make the most sense.

**Comment by DanVanAtta** [comment]
Once we have:
-  mp3 files in place
- updated Java code to work with mp3
- backup of the wav files

I am suggesting we permanently remove the wav files from the git object database (so the first option @ron-murhammer). The mechanism for removal AFAIK  would not quite be the "sensitive data removal". In that case I think they want to keep the original file and hide changes that have been pushed. Our case would be more akin to binary object removal, some like: http://git-scm.com/book/en/v2/Git-Internals-Maintenance-and-Data-Recovery#Removing-Objects

And from that, it sums up the reasoning why pretty well:
> There are a lot of great things about Git, but one feature that can cause issues is the fact that a git clone downloads the entire history of the project, including every version of every file. This is fine if the whole thing is source code, because Git is highly optimized to compress that data efficiently. However, if someone at any point in the history of your project added a single huge file, every clone for all time will be forced to download that large file, even if it was removed from the project in the very next commit. Because it’s reachable from the history, it will always be there.

The same page then has some steps for how to get rid of the file, it is kinda painful. Doing perma-delete from Git is pretty painful no matter how you do it.. On the plus side, @gaborbernat posted a link some time ago to a well known github project that had binary object removal script.

> If its the first one then we definitely need to back them up somewhere and making a new repo might make the most sense.

Confirming, it is the first one!

**Comment by DanVanAtta** [comment]
Addendum: I don't expect the perma-delete to happen for maybe a few weeks or months or longer perhaps. On the other hand, it would be good to set the stage in the meantime so we can do the object database cleanup when it comes time.

**Comment by veqryn** [comment]
I think we should continue to support the ability to play back .wav, as map makers use it (and if they only have a couple short sounds, it isn't a bad option).

Also, any advanced git commands, like permanently removing history, should be tested a lot first, on forks.

And lastly, are there no github or maven repository jars we could pull in, instead of a custom one that isn't published there?  Since we are moving to gradle for the build script, that would simplify things (along with increasing my trust of the source).

**Comment by DanVanAtta** [comment]
> I think we should continue to support the ability to play back .wav, as map makers use it

mp3spi is able to continue playing wav files, that is not disappearing.


> "Also, any advanced git commands, like permanently removing history, should be tested a lot first, on forks."

Certainly, but we aren't even close to ready to doing that yet. The first benefit of going to mp3 is a smaller DL size. Eventually we'll get the smaller repo too when we do the delete from the the git object DB.


> "And lastly, are there no github or maven repository jars we could pull in, instead of a custom one that isn't published there?"

Does not look to be the case, I checked. There is previous google code project that was migrated and has 2 of the 3 files in maven, but you need all 3, and those 2 are not compatible with the 3rd only available from javazoom.  Out of other libraries, javazoom is really nice since we just have to add a few lines to our existing code and we get backwards compatibility, and don't have to do radical library changes (like switching to use javafx).

**Comment by DanVanAtta** [comment]
Addendum:  another immediate benefit of mp3's is since we hold sound files in memory, memory footprint of the game should go down with the smaller file size.

**Comment by DanVanAtta** [comment]
I've opened a question up on the SF forum about bit rate: http://tripleadev.1671093.n2.nabble.com/mp3-sound-files-td7589462.html

#153 is open requesting a repo to archive the lossless sound files.

Those were the two questions raised, bit rate discussion will continue in SF and #153 will continue any further needed discussion on the archive repo.
