### ISSUE TITLE
Still unusable on Mac (Scramble issue)

### ISSUE THREAD

**Issue by Sabovitch** [triplea-game/triplea#1509]
Every time someone has the option to scramble on Mac, it just brings up the scramble option menu that flashes non stop. There is nothing to do to make it useable or make it stop.

Any help?

Please, I really want to play this game.

**Comment by simon33-2** [comment]
Have you downloaded the latest version? Works for everyone else.

**Comment by Sabovitch** [comment]
19.0.0? It's the only one I can find for mac.

________________________________

**Comment by simon33-2** [comment]
Depends on the build number. Current one is 1.900.3627

http://www.triplea-game.org/download/

**Comment by Sabovitch** [comment]
I have 3277


I can't find the newest one for mac, could you help me please?

I'd forever be in debt to you.


Jared

________________________________

**Comment by Sabovitch** [comment]
Nevermind, abort. I just didn't uninstall the old version. I'm a total idiot.



Please forgive me....


Jared

________________________________

**Comment by simon33-2** [comment]
I figured it was something like that.

Can you close the issue?
