### ISSUE TITLE
Luck calculator

### ISSUE THREAD

**Issue by Fabiouk** [triplea-game/triplea#1510]
Hello,

first of all, thanks a lot for the Triplea software, it's really nice.

I would like to have, if it is possible, a tool to calculate the luck during the game. During an Axis&Allies game, we can check the dice statistics, however if we roll a "1" against an infantry or against a fighter, the result is very different.

To be more precise, I was thinking to calculate the difference between the expected average TUV swing against the real TUV swing. It is not worthy for a single battle, but adding it up with all the battles (maybe with having the possibility to see separetely Pacific & European scenario) we can see if in average the Axis or Allies have gained or lost more then it should.

Please let me know your thoughts and if this is a feature that is possible to implement.

Cheers,

Fabio

**Comment by RoiEXLab** [comment]
If I understand you correctly you mean a feature which is already present.
There is a battle calculator built in tripleA, whihc allows you to "simulate" specific scenarios and test how well your chances are...
I forgot the name of the menu, but this Battle calculator is located somewhere in the menu bar at the top of every game's screen

**Comment by Fabiouk** [comment]
Hello,

I am aware of the battle calculator, I am using it very often. As you said, it allows to simulate the battles, giving % of victory, average units left and also average TUV swing.

Since I don't like to play the no-luck version, I would like to understand how much the luck impacts on the game. It is obviously impossible to be very precise for a number of reason, however I think that calculating the difference between the average TUV swing predicted by the battle calculator and effective TUV swing given by the battle result would give an idea on the luck's weight during the game. Cheers.

**Comment by RoiEXLab** [comment]
Although I think I know what you mean, I don't think this feature request is going to be useful.
I believe you want it to tell you "how well your dice karma is", wether your past dice rolls were lucky or not and if you'd have to expect to get better or worse dice rolls.
But thats the problem: Although we could implement such a feature it wouldn't change anything. If you rolled terrible numbers during 90% of the game and you lost battles you should have won by a lot, this "indicator" would tell you, that your next dice rolls are going to be good, but won't prevent them from being bad, you could still continue rolling bad values...

**Comment by ron-murhammer** [comment]
@Fabiouk I believe you are wanting the sum of all battles |expected TUV - actual TUV| for each side. As you are thinking this would be the best measure of determining which side has been lucky and by how much during the course of the game.

This is possible but has some limitations as the battle calculator always maximizes win% not TUV so think of the case you have a stack of bombers included in your defending army. The battle calculator will simulate taking these as casualty first even if say you have an 90% chance to win the battle. This will probably inflate the average TUV swing and therefore make it look like the attacker had extremely bad luck when the defender doesn't take these as the first casualties. There are other situations that this is true as well especially around air units attacking/defending that have high PU cost but lower attack/defense than other units.

The easier thing to do would be to make it so the dice statistics we already have persist across saving/loading so you can see them for entire games. While this won't consider how important each battle/roll was it does show if the luck has evened out in terms of actual rolls.

**Comment by DanVanAtta** [comment]
I've wanted dice stats as well. I agree TUV is a bit problematic. Though dice average and median stats are not very salient either.

Deviation from expected number of hits is very interesting After each combat roll you get a status message of how likely that roll was in terms of expected hits. For example, attacking with 2 tanks, the expected number of hits is 1. The possible number of hits are 0, 1, and 2, with expectations: 0.25, 0.5, 0.25. So if you get 0 hits, it'll show 25%. We could then track per roll the deviation from the expected number of hits. So for the last example it would be a "-1". Averaging all of the combat roll deviations would then show if there was a skew from the number of expected hits.


So another example:
- 2 tanks attacking, rolls: 1 hit, 2 hits, 2 hits, 1 hits.
- That displays per roll: 50%, 25%, 25%, 50%
- That is from expectation: +0, +1, +1, +0
- At end of battle shows average deviation:    (0+1+1+0) / 50 = + 0.5
The +0.5 means the one player on average got an extra hit every other roll than they were supposed to. Which can be pretty solid.
- A v2.0 version of this could do a backfill from history values and show a running total

**Comment by Fabiouk** [comment]
Hi Ron,

yes, this is what I want, the sum of all battles (expected TUV - actual TUV) for each side. I am aware of the limitations, your example is correct, and there are many others: a bomber that kill or not kill a blocker (i.e. destroyer) could be a very important battle from a tactic point of view, regardless the TUV swing. And obviously having less luck in important battle like in Moscow or India wouldn't be compensate with more luck in small battles.

However, I believe that this statistic would be useful to give an idea on how the luck impacted on the game.

I don't like dice statistics as it is done now. For example, I can roll five "1" with fighter and five "3" with infantry, resulting in 5 hits. The reverse, we would have 10 hits, while the average dice roll is always 2.

@DanVanAtta: just reading your answer now. I also like the method you propose on the deviation from expected number of hits. It doesn't take into account what you are hitting, so you can have a "very positive deviation" and killing a bunch of infantries, or you can have a very positive deviation killing fighters or navy.

Both methods have advantages and flaws, but either two would give a decent indication (IMHO). I wouldn't mind to have both implemented.

**Comment by GeoffBuchan** [comment]
So this is about tracking luck in the course of a game. Interesting. I recalled playing an online version of Settlers of Catan which tracked how often certain numbers were rolled.

From the opposite perspective, an enhancement to the battle calculator could show, say, a net TUV change histogram so you can visualize the possible spread impact of luck. It's useful to see prospectively, for example, TUV swings of a big naval battle might range from -70 to +90 with an average of +20, while another ground battle may average +20 with a range of +12 to +28.

One should expect a normal-ish distribution around the mean, but sometimes there can be rather fatter tails (e.g. AA guns in normal luck against multiple aircraft).

The histogram would help you judge how much risk you're taking on a given fight, and can better prepare you for potential adverse results.
