### ISSUE TITLE
Have popup window show up once per game instead of once per round

### ISSUE THREAD

**Issue by beelee1** [triplea-game/triplea#1516]
Not sure the best place for this but it looks as if there's a little of everything here. Anyway can you have a user action only ask you once the entire game whether you want to accept the action instead of once every round ?

I asked at triplea dev a little over a year ago and aaalafayette replied or implied, that it would be improved. He listed this link:
 [ https://github.com/triplea-game/triplea/pull/286
](url)
I scrolled through it but didn't see anything I could understand. He mentioned that BB, CA bombard was a problem as well because it would ask you if all your BB and CAs if they wanted to bombard when only a few qualified.

I see that was improved by checking how the game plays. Anyone know if the popup window was addressed ? Or the best place to find out ?

Thanks

**Comment by ron-murhammer** [comment]
@beelee1 Can you give an example of what popup you'd want only once per game?

**Comment by beelee1** [comment]
@ron-murhammer  It's a User Action trigger:
attachment name="userActionAttachment_Change_AAGuns" attachTo="Germans" javaClass="games.strategy.triplea.attachments.UserActionAttachment" type="player"><option name="conditions" value="conditionAttachment_Change_AAGuns"/><option name="activateTrigger" value="triggerAttachment_Change_AAGuns:1:false:false:false:false"/><option name="text" value="CHANGE_AAGUNS"/><option name="chance" value="6:6"/></attachment>

As you know the "1" means it'll fire once every rd. I wanted it to only fire once the whole game so if you didn't accept it you wouldn't have to keep seeing it.

Just trying to figure a way to give people different options for the game. That way they could try multiple scenarios inside one xml.

**Comment by beelee1** [comment]
well Idk why it won't let me edit. I'll try again.
activateTrigger value="Trigger_Attachment_Change_AAGuns:1:false:false:false:false"

**Comment by ron-murhammer** [comment]
@beelee1 Can't you use the "uses" parameter to make triggers only fire once per game? "uses 								values: integer for the maximum number of times it should be awarded. if missing it defaults to infinity"
