### ISSUE TITLE
New forum launch tasks

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1517]
Goal: get the users of the old two forums to start creating threads on the new forum

- Anything left to do for the forum itself? 
- Beyond data migration issues (discuss in #1518), anything to fix up before we start advertising that the new forum is ready?

**Comment by prastle** [comment]
skin sucks and email response
looked at what roi sent me its beyond me  to fix the email response

needs to be prettied up !

other than that I only question the captcha

**Comment by DanVanAtta** [comment]
Any opinions when we should post that the new forum is ready to be used? Should we go ahead, or wait for this weekend to give a chance to pretty things up? Personally this is a bit like ripping a band-aid off, the forum migration is not going to be all easy, but we should get to a far better place in the end.

The captcha is anti-robot, robots are finding the site regardless if we notify the forums or not that we have a new one available. IE: It's important to get a solid captcha going regardless of any other decision.

**Comment by prastle** [comment]
Well i had admin aproval on for a clean database

Roi wants it gone because elims work

i can send email to all admins and and pasword np here

or let it build us a crap database
ur call

**Comment by RoiEXLab** [comment]
@prastle There are tons of skins to choose from, you just need to find one matching your requirements... 
About the email template: maybe it's not the most creative and beautiful thing in the world, but it provides the user with the necessary information, it works

**Comment by prastle** [comment]
yes except i cant get them to load  (new skin)

current response is (email) 

Hello prastle,

Thank you for registering with TripleA Forum!

To fully activate your account, we need to verify that you own the email address you registered with.

Click here to confirm your email address
Thanks!
TripleA Forum

I just think it needs to be fleshed out more is all but yes a minor point

**Comment by RoiEXLab** [comment]
@prastle Oh, I think I found the problem... https://community.nodebb.org/topic/3784/skins-tab
The lavender theme is probably not supporting any other skins...

**Comment by prastle** [comment]
Added the link to new warclub in the old warclub in news

**Comment by prastle** [comment]
Sigh reset to vanilla and applied a skin.  It didn't work. I think you will have to do it @RoiEXLab

**Comment by RoiEXLab** [comment]
@prastle Weird, I'm sure this isn't supposed to happen... Theres not much I can do about it other than raising an issue at the nodebb project

**Comment by RoiEXLab** [comment]
@prastle I just tested this on my local nodebb installation (a pain when using windows) and it works there for the persona and the vanilla theme...
I'll do some research on what is happening

**Comment by prastle** [comment]
@RoiEXLab and @DanVanAtta  could we import the warclub database of users to new or is it best if a mass email sent and they just rejoin?

**Comment by RoiEXLab** [comment]
@prastle Migrating the database is most likely impossible due to the way passwords are stored (if nodeBB is using another hashing algorithm than xoops, which is probably the case there is no way).
So mass emailing is probably the best option...

**Comment by prastle** [comment]
Ok  ill write a mass email after i clean the deactivated and when you guys want it locked and ready.

**Comment by RoiEXLab** [comment]
@prastle Apparently nginx is causing problems regarding skinning nodebb... I will look into that

**Comment by RoiEXLab** [comment]
@prastle Nevermind, I found the problem... Every user can set his preferred skin of the forum... I had my preference set to spacelab, thats why it seemed, that the skin wasn't changing...
My personal preference was applied over the server wide one, if you log out, you will notice that as well...

**Comment by DanVanAtta** [comment]
Next steps here, post in both forums that we are moving the community to the consolidated forums. Once the new lobby picks up we'll consider next steps to make the old one's read only. Following that we'll consider further steps.

**Comment by prastle** [comment]
Can we freeze Source Forge?  Just asking because i have nidea.

**Comment by DanVanAtta** [comment]
Not sure @prastle , @ron-murhammer , do you know by chance if we can make the source forge forum read-only? (checking on future options)

**Comment by prastle** [comment]
New forum has a paypal plugin :) also a few other interesting plugins i have added to the installed but not activated have a look when ya guys are interested

**Comment by prastle** [comment]
@DanVanAtta  @ron-murhammer  Can we please change the community link from old warclub to the new on the website.  Also I would like to stop new users from joining old war club if you don't mind.  I am tired of deleting 5 to 10 spam a day there.  Thanks

**Comment by prastle** [comment]
Also after closely examining the permissions in the old warclub a read only solutionn is np.  This would conserve the massive history and data.   Thus no data transfer or closure is needed.  Only webmasters will have the ability to change.  This could be removed as well of course.  Thus all could still access as guests (including old registered) from a link on our new warclub/forum and and all could read away.  New Mods could be manually edited in to have access to the old data in bunker.  I hope this can be done somehow with source forge.  Just my sug.

Pras

**Comment by FrostionAAA** [comment]
Regarding Paypal: I can see that the paypal plug-in at the new forum is deactivated. I can also see that the plugin’s github development page ( https://github.com/theunknownartisthour/nodebb-plugin-paypal-subscriptions ) says that it is a “work in progress”, “currently not working” and that it has been 10 months since an update. I don’t think we can rely on that plug-in to work.

I think we should instead go for a TripleA member using his Paypal account to accept donations. It seems that this member must have a PayPal Business or Premier account. Then there is a guide here about how to make a donate button:
https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/donate_step_1/
This leads us to get a HTML code that can be pasted into a custom HTML widget at the new forum.

Any thoughts about who, when, if this is the way to go?

**Comment by ron-murhammer** [comment]
@FrostionAAA In general, it should probably be whoever is going to pay for the lobby server fees. That is really our only expense that donations are needed for.

**Comment by FrostionAAA** [comment]
@ron-murhammer Yes. It would be logical to have the donations go directly to that person. Regard what I wrote as a mini-guide aimed at that person 🤑 💰 But perhaps that person has other ideas about how to  receive the donations.

**Comment by prastle** [comment]
Yes i mentioned this as well in the new forum.
https://forums.triplea-game.org/topic/70/wish-list-for-the-lobby-and-the-new-forum/5

@FrostionAAA and @ron-murhammer and @DanVanAtta 

i have np opening a pay pal acct but it does require a response from dan and veq's pay pal being removed from website.

**Comment by prastle** [comment]
The new forum has been up and running for awhile and is slowly gaining steam.  Ideas on the next steps?  I believe all the links have been fixed.  Thxs  @ron-murhammer and @RoiEXLab
