### ISSUE TITLE
Outdated (?) Dice Servers (tdice.appspot)

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#1524]
The "alternative" dice servers

tdice.appspot.com/web
tdice.appspot.com/email

seem to no longer exist.

Both URL return a 404 error.

**Comment by prastle** [comment]
we also lost home page of original warclub?  The new updated warclub bots cant be joined except bot 3.  Also the marti dice server is down? What happened last night?

**Comment by panther2** [comment]
I think tdice.appspot has not been working for a longer time. 
The service appears to have been completely removed from the web.
Looks like it should be removed from TripleA, too.

**Comment by ron-murhammer** [comment]
I think the server crashed or something yesterday. Looks like some things haven't been brought back up properly yet.

**Comment by panther2** [comment]
@ron-murhammer 
Is tdice.appspot related to warclub?

**Comment by prastle** [comment]
it was working after server crash or did it crash again?

**Comment by RoiEXLab** [comment]
No tdice.appspot.com seems to be a domain managed by Google...
Yeah, we should probably remove that

**Comment by ron-murhammer** [comment]
Yeah, I think tdice.appspot hasn't worked for a while.

**Comment by panther2** [comment]
@ron-murhammer 
To remove this - is there anything touched apart from the two properties files in the dice_servers directory?

**Comment by ron-murhammer** [comment]
@panther2 Looks like just 2 property files. Here is a PR to remove the tdice options from the list: https://github.com/triplea-game/triplea/pull/1531

**Comment by panther2** [comment]
OK, thanks!
