### ISSUE TITLE
Derby DB has gone Read Only

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1528]
```
Caused by: java.sql.SQLException: An SQL data change is not permitted for a read-only connection, user or database.
```

This is majorly bad, only anonymous logins are working. Registered user logins are getting a 'socket closed' error when they log in with a valid password.

Started happening about 12~24 hours ago after running out of disk space. (https://github.com/triplea-game/triplea/issues/1525)

**Comment by DanVanAtta** [comment]
I've tried restoring the DB to a the latest backup, no luck. We can try a backup further behind it.

Otherwise we need to:
1. communicate this to the community
2. see about migrating off of Derby ASAP.

**Comment by prastle** [comment]
Posted in warclub

**Comment by panther2** [comment]
There's a posting on aaa.org, too.
http://www.axisandallies.org/forums/index.php?topic=39347.0

**Comment by ron-murhammer** [comment]
@DanVanAtta Did you try restoring from an earlier backup? It appears only anonymous logins are working for the lobby still.

If we can't resolve the db issue then we should probably ping @veqryn and Bung to see if they can assist.

We really need to keep a better eye on server memory usage to avoid stability issues.

**Comment by prastle** [comment]
@ron-murhammer we noticed the start of prob when lost lobby home page for war club.  Also the new scripted bots cant be used.  @RoiEXLab  killed them this am for me.  They cant be joined thus not use able.  We had hoped it was due to lack of memory last night.  Perhaps this isnt' a bad thing losing the database tho since it was broken anyways.  Maybe we just start fresh with new forum/warclub for database?

**Comment by prastle** [comment]
update 

American knight rewrote bot scripts 6 up and running now we just need nj bots

**Comment by DanVanAtta** [comment]
File perms on DB file, should be okay on next restart of lobby.

@ron-murhammer  The problem was running lobby with nohup, caused our 'alive' loop to print out an endless stream of errors since you can't read from stdin when there is no stdin. To solve the problem of keeping a session open earlier we would run the lobby from a 'screens' session

**Comment by DanVanAtta** [comment]
It's an open question why the lobby crashed the first time about 2 days ago. The restoration yesterday ran the lobby with nohup resulting in the disk fill up.

**Comment by ron-murhammer** [comment]
@DanVanAtta Alright. We probably need to better document how to admin the server (lobby, database, dice roller, etc).

**Comment by DanVanAtta** [comment]
We're changing lobby+DB config in a moment here, no point to document the old setup to change it hours later.

Dice roller does need some documentation desperately. I don't think anyone knows how it is deployed (myself included)

**Comment by RoiEXLab** [comment]
@DanVanAtta isn't the dice server the marti php folder located on the Warclub server?

**Comment by prastle** [comment]
Ya marti is on warclub thus we lost marti when we lost home page etc

**Comment by panther2** [comment]
Has this issue been resolved?

I was able to log in with my user name minutes ago.

**Comment by prastle** [comment]
Yes American Knight Relaunched last night at midnight with Dan's ? new code.  Looks to be working.  We just need new Lobby bots refired.

**Comment by prastle** [comment]
Unsure if the database is editable with sql again.  But user names are working again.

**Comment by DanVanAtta** [comment]
Registered user login problem is fixed.
Writes from  lobby UI would still be borked.
