### ISSUE TITLE
Connection to lobby fails

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#1529]
As reported on AAA.org:

![triplea_2017-02-12_09-53-25](https://cloud.githubusercontent.com/assets/20812775/22860822/4dc95b64-f109-11e6-9dbf-dd525e4c43b2.png)

To reproduce just try to join the lobby.

**Comment by RoiEXLab** [comment]
Related to #1528

**Comment by panther2** [comment]
Again in #1533
