### ISSUE TITLE
Please create repo: lossless_sounds

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#153]
Purpose: Store lossless wav sound files which will be replaced by mp3 encoded versions in the main repo.

**Comment by ron-murhammer** [comment]
Added my comments to #150

**Comment by DanVanAtta** [comment]
Seems like we are agreement on the need for the repo. Any further questions/clarification that I can help with?

**Comment by DanVanAtta** [comment]
@ron-murhammer , the comments in #150 were responded to, waiting for your response still. @veqryn , @ron-murhammer , please create the repo so we can  close this item.

**Comment by DanVanAtta** [comment]
Closing, will re-open again when this is really needed rather than so far ahead in advance.
