### ISSUE TITLE
Difficulties logging back into TripleA . . .

### ISSUE THREAD

**Issue by Kumerica** [triplea-game/triplea#1533]
It's been a while since I've played TripleA; I updated the latest version, but am having difficulties with connecting. Everytime I try to login, it says "Cannot Connect to Lobby: Socket Closed." Thoughts?

Any insights or direction would be appreciated.

Thanks,
Sagar

**Comment by beelee1** [comment]
Hi kumerica
#1528 explains things. If you login anonymously you can get on.

**Comment by Kumerica** [comment]
Thanks mucho, beelee1.

**Comment by panther2** [comment]
It seems to work again.
https://github.com/triplea-game/triplea/issues/1528#issuecomment-279648688

**Comment by prastle** [comment]
American Knight relaunched with dan's new code YAY! :)
