### ISSUE TITLE
Please create repo:  triplea-game.github.io

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#154]
Requested by "The Red Baron" for the github pages website. 

From: http://tripleadev.1671093.n2.nabble.com/TripleA-Website-Redesign-Migration-to-Github-Pages-td7589306i20.html

> One thing needs to happen. That is that someone with administrative privileges needs to create a repo under the TripleA repo called triplea-game.github.io. I will then be able to submit pull requests to the repo, and so will everyone else. I will do the rest. I will finish up duplicating the website content into my HTML and CSS pages, adding changes in areas discussed and in some other areas. Having the repo open will allow us to take the discussion there. For the moment I will plug along at creating the rest of the site. Once I get it to a reasonable level of finality, I will post it.

**Comment by ron-murhammer** [comment]
Added: https://github.com/triplea-game/triplea-game.github.io
