### ISSUE TITLE
Planning for Lobby Derby DB Migration to MySql

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1543]
Capturing below some of the steps to migrate the lobby from Derby DB to MySql. We should be able to do this without anyone particularly noticing. I'm a good bit ways along on these efforts, some PRs should be coming out soon. 

- [x] Remove lobby UI and logging code (avoids maintaining the dead DB code tied up there, the UI is currently not working anyways relative to the DB)
  - [x] #1544
- [x] Remove moderator password reset. It does not make sense to reset passwords for users that are logged in.
  - [x] #1545
- [x] Remove and/or disable IP based banning and muting, must be backwards compatible (again, avoids maintaining dead DB code/features, per #1488 the IP based ban/mute is not very effective)
  - [x] #1545
- [ ] Update login code to add a new user to the new MySql DB on a successful login to the old derby DB
- [ ] Migrate mac and username banning/muting to mysql
- [ ] Update registration code to add new users to the new MySql DB
- [ ] Update login logic to check both old Derby DB and new MySql DB for login creds
- [ ] Script up some admin/operational functionality to maintain the mysql tables
- [ ] Launch lobby from a service script (we need to be able to re-deploy/restart the lobby sanely before we can do much further work with it)

-------
Once user accounts are migrated:
- [ ] Update login code to look at only the MySql DB instead of Derby DB
- [ ] Remove everything related to Derby DB

**Comment by RoiEXLab** [comment]
Also be sure to add a row for bycrypt hashes

**Comment by RoiEXLab** [comment]
@DanVanAtta I could write the lobby service script, once the current PR is merged...
I will try to rework some of the scripts to allow easy updating

**Comment by prastle** [comment]
When the new db is up and running could we also somehow tie the bots to the mod lobby toolbox.  So they can be rebooted from the lobby, perhaps with a password, thus avoiding the need to login to the server.  If they could be setup the same as chat log pulls it would be GREAT!

**Comment by RoiEXLab** [comment]
@DanVanAtta I think it would be really useful, if we had an API between the DB and other applications like the lobby.
This would allow for easy access and would make it easy to change the structure later on, because we would just need to change this one software.

**Comment by bung** [comment]
@RoiEXLab That could possibly also allow user accounts to be the same between nodeBB and lobby?

**Comment by RoiEXLab** [comment]
Not quite...
Although I like the idea of having one account for both the lobby and the forum, we decided not to share the account for a couple of reasons... You might need to search through some issues on github. 
What I meant here, was that we have a software which wraps the db so we don't have to implement db code on every other piece of software.
For example:
This software accepts a couple of command like
```
login username password
ban username
createuser username password
...
```
And it will execute the respective commands.
If the database changes in any way we would just need to change this software, because all other applications would just continue using the same commands...

**Comment by bung** [comment]
Yep no problem, Ive been trying to read a bit, but I'm not sure I'll entirely catch up. Also, yea I get the niceties of API for that purpose for sure.

For the other bit, I would hugely encourage some way to connect accounts, it would make a massive difference in the user experience. It is something we've wanted to see happen for years, but I never sat down to learn derbydb, so I commend you guys for working on that for sure. I'll keep looking to find out more if you've already discussed this elsewhere.

**Comment by prastle** [comment]
doesnt matter derby is dead

**Comment by prastle** [comment]
btw back b
 @ roi can the other be implemented that you mentioned in chat? without a redl?

only ask because of the 10 broken bots

**Comment by RoiEXLab** [comment]
What we still could do is having them "connected" so in the forum stuff like stats and rank (if we have a working elo system) is being displayed with a users profile

**Comment by RoiEXLab** [comment]
Do you mean my scripts?
They should work fine now... I fixed a couple typos and now they automatically download the latest bot version (the one marked as latest in the release section of the triplea repo).
They require sudo though... at least once.
I'm just not sure if updating will work as expected... The files will be downloaded correctly but I'm not sure if the old ones will be overriden

**Comment by bung** [comment]
@RoiEXLab Yep absolutely, good point. Alright well I'll leave that feature/functionality discussion for later, and stay on topic for derbydb migration.

**Comment by RoiEXLab** [comment]
@prastle you can download my fork and just follow the [README Instructions](https://github.com/RoiEXLab/lobby/blob/user-update/README.md) be sure to download the user-update branch though.
Skipping the ./setup part should work. This script is supposed to only run once

**Comment by RoiEXLab** [comment]
@DanVanAtta has been inactive for the last 2 weeks I think. He's the one responsible for the lobby and the DB... That's why we're somewhat stuck in terms of progress

**Comment by bung** [comment]
@RoiEXLab The guys seem motivated to keep managing bots and lobby, but they don't have the ability to execute the technical steps you're suggesting. I appear to still have my original access level to the server and could set you up with the required access, can we talk via email or I can privately message you on Gitter.

**Comment by prastle** [comment]
LOL thxs for fork but  i can already host bots @RoiEXLab the problem is my connection can only support 1 or 2

what  i was wondering was if it had been installed on server  your other fix sorry wrong thread

**Comment by DanVanAtta** [comment]
@RoiEXLab  I thought we did decide to share the login between lobby and forum. Namely the lobby would query for login with username+pass against the forum DB. Though that would be the extent of the data sharing beyond whatever payload is returned from the one API. Was it unclear, or were there other reasons to not do the API call from lobby to nodeBB for auth?

@prastle @RoiEXLab  there are some issues involved with controlling bots from lobby. They are different processes, so some infra issues. Also given anyone can modify a local client, there are some additional security issues to consider. Furthermore future direction of bots would move away from these types of controls, so it would be throw-away code if we take that direction. Short term IMO we need to focus on getting the current set of bots more easily managed in their new  service enabled state before we starting adding more code at the problem.

@bung  we recently added service / init.d scripts for bot controls. It's quite simple to execute a restart using that, the command is copy/paste-able. We do still need to deploy those updates and note how exactly to run those management commands.

**Comment by RoiEXLab** [comment]
We did? Ok I recalled it wrong then...

About the lobby remote control: In order to not have any security issues, we'd need the lobby software to "advice" the wrapper software to start and stop bots...
Only the lobby software can safely authenticate user accounts!

**Comment by prastle** [comment]
@DanVanAtta  one of the major problems atm is that the NJ bots (some) and Germany bots(all) have been broken for a week or more.  No one has access to them except you.  The war club bots seem fine.

**Comment by prastle** [comment]
This causes all the lobby moderators a huge amount oh headache.  Since we are constantly answering questions about them and or booting them.  Not to mention making Triplea look very silly.

**Comment by wirkey** [comment]
Something is definitely wrong with the bots. 
-getting a flickering screen after some time
-battle calculator using all available cpu at times
-losing connection out of nowhere
I will try to write down what I did whenever this happens again.

**Comment by DanVanAtta** [comment]
Closing this issue in favor of using a Github project to track: https://github.com/triplea-game/triplea/projects/2. Thank you all for the feedback.

**Comment by RoiEXLab** [comment]
@DanVanAtta Does the postgresql DB have multiple columns for "new" and "old" hashed passwords?
If you want to "copy paste" all the date to the new db at some point we'd need that.
Once we have such a column I can create a PR to hash passwords with a proper password hashing algorithm like bcrypt

**Comment by DanVanAtta** [comment]
No, hash algorithm in new DB would be updated directly. We're already doing a migration of passwords, may as well migrate hash algorithm. The selection of algorithm needs to be wired in yet.

**Comment by DanVanAtta** [comment]
Actually, it seems the pass is first hashed on client side. We store hash on lobby, so we don't really have a chance to re-hash it, even if we had 'old' and 'new'.

**Comment by RoiEXLab** [comment]
In this case we'd need to change that.
Algorithms like bcrypt and scrypt need the "original" password to check if the hash matches, we should pass the hashed password to the client, as this allows an attacker to read the complete databases password column if he knows all the usernames (which can of course be brute-forced, or recorded by logging into the lobby and saving all usernames)

**Comment by RoiEXLab** [comment]
Possible hashing algorithms would be BCrypt, SCrypt and PBKDF2, although I'd prefer BCrypt or SCrypt.
Implementations exist in Java for all of them, we should under no circumstances develop one on our own.
Also we should probably encrypt the connection to the lobby so the passwords stay secure when they are no longer hashed before sending

**Comment by DanVanAtta** [comment]
> "we should pass the hashed password to the client"

I suspect this might be trouble, an attacker could work on hash collisions all day long once given the password hash.

> "Algorithms like bcrypt and scrypt need the "original" password to check if the hash matches,"

Yeah, the login system seems to be really odd. It is a bit hard to grok. I'll weight in again once I've understood it a bit better. At the moment it seems though we should not be doing so much hashing, rely on HTTPS to do the secure communication for us.

> we should under no circumstances develop one on our own.

:+1: 

> Also we should probably encrypt the connection to the lobby so the passwords stay secure when they are no longer hashed before sending

Agree, use SSL for what SSL was built for.

**Comment by RoiEXLab** [comment]
@DanVanAtta whoops typo, I meant we shouldn't ^^
Yeah we should use TLS, but we might need a certificate which costs money.

**Comment by ssoloff** [comment]
> Yeah we should use TLS, but we might need a certificate which costs money.

@RoiEXLab Have you looked into [Let's Encrypt](https://letsencrypt.org/)?

**Comment by RoiEXLab** [comment]
@ssoloff We are using Let's encrypt certificates for all of the self-hosted TripleA websites.
There are 2 problems with this: The Let's Encrypt certbot creates key files which are not in the right format.
There seems to be a way to [convert those files](https://docs.oracle.com/cd/E35976_01/server.740/es_admin/src/tadm_ssl_convert_pem_to_jks.html) though.
Let'S Encrypt only provides certificates for domains/subdomains, we'd need to setup something like lobby.triplea-game.org in order for it to work (or we could reuse the tripleawarclub.org certificate, and make things confusing, but I can test with this certificate now that you meantioned it ^^)

I believe the certbot supports renewal hooks, I will create a script which automates this process for us, because lets encrypt certificates expire every 90 days otherwhise.

But now that I'm thinking about it, it seems doable

**Comment by ssoloff** [comment]
@RoiEXLab 

> Let'S Encrypt only provides certificates for domains/subdomains

Thanks for the info.  I didn't know this.
