### ISSUE TITLE
transports omitted in casualty dialog

### ISSUE THREAD

**Issue by pkarp111** [triplea-game/triplea#1559]
I've observed the following behavior in the map
World War II v5 1942 Second Edition

In the casualty dialog during naval battles, I find that transports are
sometimes (usually, but not always) omitted from the dialog.  So it is
impossible to choose transports as your first casualties.  More rarely,
subs are also omitted from the dialog.

This is definitely not how it works in World at War 1940.

**Comment by panther2** [comment]
`So it is impossible to choose transports as your first casualties.`
This is rules compliant starting from v3. Transports have to be chosen last.

WaW1940 obviously follows another rule set.

**Comment by panther2** [comment]
> More rarely, subs are also omitted from the dialog.

Remember (unescorted by a destroyer) air units cannot hit subs starting from the v3 ruleset.

**Comment by ron-murhammer** [comment]
Agree. I don't think there is any issue here. Closing for now. Please reopen if necessary.
