### ISSUE TITLE
Unable to locate latest STABLE release, for distribution packaging

### ISSUE THREAD

**Issue by solbu** [triplea-game/triplea#1565]
I maintain TripleA on Mageia. 
We have a policy on using stable software, so I can't use any of the prereleases.
But I have a hard time locateing the latest Stable source code release since you removed all content on Sourceforge.

I would request that you add a link on the download page that links to the latest Stable source code.

**Comment by ron-murhammer** [comment]
@solbu - The latest stable downloads are located at the new website here: http://www.triplea-game.org/download/

**Comment by DanVanAtta** [comment]
Additionally, github provides a magic URL that gets you there too: 
https://github.com/triplea-game/triplea/releases/latest

**Comment by solbu** [comment]
@ron-murhammer: The sourcecode is /Not/ linked to on that page. Only a shellscript that the user is supposed to run in their GNU/Linux systems. I specifically asked for a link to the latest /source code/. :-)

@DanVanAtta: THat link should be on the download page, so those who want the latest stable source code can get it.

**Comment by simon33-2** [comment]
When I click on the link I see a zip and tgz of the source code. @solbu

**Comment by solbu** [comment]
@simon33-2: Not on the /download page, there isn't. And I specifically ask for a link that takes one to the latest STABLE source, not the latest pre-release.

**Comment by simon33-2** [comment]
That link DOES take you to the latest so called stable release. The latest pre-release is 3865 - the link takes me to 3635.

Although triplea-game.org goes to build 3627. Perhaps that's out of date?

**Comment by solbu** [comment]
http://www.triplea-game.org/download/ does not link to the latest stable SOURCE code, it links binary releases, and a shellscript. There is a difference.

**Comment by simon33-2** [comment]
Yes, but the link:  https://github.com/triplea-game/triplea/releases/latest

Does take you to a page with the source.

**Comment by solbu** [comment]
Again, that link is nowhere to be seen except in this thread.
Add that link somewhere.

**Comment by simon33-2** [comment]
Perhaps it should but that answers the question doesn't it?

**Comment by solbu** [comment]
It answers the question on where to get it, but that is not what this Bug repport is about. I want an actual link to https://github.com/triplea-game/triplea/releases/latest somewhere in the download page.

**Comment by simon33-2** [comment]
I would call it an enhancement request.
