### ISSUE TITLE
Adjust the new resource display in Actions and Operations

### ISSUE THREAD

**Issue by FrostionAAA** [triplea-game/triplea#1575]
To me the new feature seems to work fine. I just want to point out an aesthetic issue. As you can see in the below screenshots there seems to be a lack of space between the frame of the Actions and Operations window and the start of the “You have XX PUs, …” text. Is it possible to do something about this? Maybe add some margin?

![unavngivet](https://cloud.githubusercontent.com/assets/15268177/23911610/a248803e-08dd-11e7-8ab4-ea931b15c3f9.png)

The same thing goes for the text to the right of the “buttons”. I have made text arrows in my maps to make this less of an issue. Right now, the text displayed next to the buttons (text found in the maps actionstext.properties) does not allow a spacebar “space” before the text, so I compensated with the arrows. It would especially be an issue if the text starts with a capital I/i. It would be great if something could be done here also.

I don’t know if this is useful, but there seems to be enough space in the purchase window. Maybe some code used here to configure the behavior of the window can be used in the Actions and Operations?

![unavngivet2](https://cloud.githubusercontent.com/assets/15268177/23911641/b7c4321e-08dd-11e7-9df8-e2915375a2da.png)

**Comment by ron-murhammer** [comment]
@FrostionAAA I believe this is fixed now with #1576 being merged. Please re-open if not.
