### ISSUE TITLE
Standardize import order

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/triplea#1587]
The largest share (~34%) of the remaining Checkstyle warnings is due to violations of the [`CustomImportOrder`](http://checkstyle.sourceforge.net/config_imports.html#CustomImportOrder) rule.  This rule, inherited from the Google Checkstyle configuration, is defined as:

```xml
<module name="CustomImportOrder">
    <property name="specialImportsRegExp" value="com.google"/>
    <property name="sortImportsInGroupAlphabetically" value="true"/>
    <property name="customImportOrderRules" value="STATIC###SPECIAL_IMPORTS###THIRD_PARTY_PACKAGE###STANDARD_JAVA_PACKAGE"/>
</module>
```

The [TripleA code format](http://www.triplea-game.org/dev_docs/dev/code_format) does not explicitly define an import order.  However, because it does specify use of the Eclipse Organize Imports command, it seems implied that the default Eclipse import order is to be used.  As of Neon.2, the default Eclipse import order is:

```
java.*
javax.*
org.*
com.*
<everything else in lexicographic order>
```

I'd like to get rid of these 4,800 or so warnings, but I don't just want to assume a standard order without asking.  If I had to guess, I'd assume the default Eclipse import order is the TripleA standard, and the Checkstyle configuration should be updated to reflect this.  Is this true?

Regardless of what the standard import order is, as part of whatever PR addresses this issue, I would propose that an Eclipse `*.importorder` file be exported from the code style preferences and stored in Git alongside the other Eclipse code style templates (under `eclipse/format`).

**Comment by RoiEXLab** [comment]
I agree. The checkstyle file should be changed according to eclipse standards!

**Comment by ron-murhammer** [comment]
@ssoloff I think this should be resolved now so closing.

**Comment by ssoloff** [comment]
@ron-murhammer Agreed.  Thank you.
