### ISSUE TITLE
Show Convoy Zone Comments in Bottom Left

### ISSUE THREAD

**Issue by beelee1** [triplea-game/triplea#1590]
Have the map.showComments for convoy zones in map.properties show up in the bottom left of the screen where territory and production does now when set to false.

When true the description clutters the SZ too much. Currently i have a small roundel showing convoy ownership and it'd be nice to have the  info on what territories are impacted show up in the lower left of the screen as well.

maybe there is limited space ? Looks as if there is some sort of divider on the screen.

![screenshot_2017-03-28_20-42-34](https://cloud.githubusercontent.com/assets/24382682/24434781/462ae998-13f7-11e7-9a7f-f7aeedf4fd08.png)

**Comment by ron-murhammer** [comment]
@beelee1 Not really following what you are looking for here. Even if you turn map.showComments=true for global, I don't see any comments in the sea zones? Can you provide an example map and screenshot?

**Comment by simon33-2** [comment]
I think he might be referring to adding a comment for which territories/powers can lose production in that sea zone?

**Comment by DanVanAtta** [comment]
@beelee1 please chime in if you would, closing for the now.
