### ISSUE TITLE
WWI 1914 difficulties in incorporating into Triple-A

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#1594]
Just wondering what makes this difficult to incorporate into AAA?

There is a property "LAND_BATTLE_ROUNDS" which can be set to 1, the tank hit wastage can be handled in the same way as non-global BBs.

What part is too difficult? Contested zones?

**Comment by ron-murhammer** [comment]
Not sure. I know that a few folks thought about doing it a few years ago and here is the thread: http://tripleadev.1671093.n2.nabble.com/1914-development-tp7583942.html

You'd need to review that and review the 1914 rules closely then determine what if any engine changes would be needed.
