### ISSUE TITLE
Multiple Packages with same purpose?

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#1598]
Noticing this for a while now...
I'd like to split/merge some packages to be "more consistent" with naming.
For example: Whats the difference between `games.strategy.ui` and `games.strategy.triplea.ui`?
I'd like to have those merged into a single package to avoid confusion.
Other packages which are very larged could be split in smaller sub packages...

Any potentials Problems?

**Comment by ron-murhammer** [comment]
It should be fine as long as it doesn't break any reflection or save game/lobby compatibility. I think the reason is that we used to have some other games (chess, etc) so triplea specific was in a different package.

**Comment by RoiEXLab** [comment]
So should we move `games.strategy.*` -> `games.strategy.triplea.*` or the other way round?
I'd prefer the other way, but I believe this way is more likely to not break savegame compatibility

**Comment by ron-murhammer** [comment]
@RoiEXLab Either way is fine for now. I'd eventually like to do a total package renaming to align with standard package naming structure so everything would start with something like "org.triplea.*"

**Comment by RoiEXLab** [comment]
True, maybe even `org.triplea-game.*` although I'm not sure if java allows this.

**Comment by RoiEXLab** [comment]
I'd recommend doing this, once we have savegame format without reflection and a network system working without RMI in order to not break stuff

**Comment by ron-murhammer** [comment]
Yeah, that was my thought as well.
