### ISSUE TITLE
Rocket bugs

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#1612]
An official clarification has been issued that the previously reported bug with being able to see the results of the first rocket attack before deciding the second one is in fact not a bug.

The obvious solution to all this is to have a map property for "Strict Rockets" or whatever you want to call it. Or call it "Sensible rockets" if you want to use the official (illogical) rules by default. However @DanVanAtta has stated in the past that adding a map property is a very big deal. I have to ask why? What is the problem with adding a property to toggle between the two behaviours? There's obviously a few other issues which need to be sorted too but I don't see the point in bothering unless we're allowed to fix it properly which IMO requires a property.

**Comment by ron-murhammer** [comment]
@simon33-2 Map properties are fine to add if they are necessary. The challenge is that we already have tons of them and many are very rarely used. I think we just need to think carefully on whether its worth adding.

**Comment by simon33-2** [comment]
Ok, I'm strongly in favour of a new editable property, and default to sensible rules but have the property for the strict rules.

I didn't say above that should include all the remaining issues with rockets. Tried to log them off before in #1535. Issues like #1387 can be logged off as well as some map bug notes like the rockets disabling airbases before they scramble.

So if I submit a PR for these remaining issues would it be merged and will a test be insisted on.

**Comment by DanVanAtta** [comment]
> @DanVanAtta has stated in the past that adding a map property is a very big deal. I have to ask why?

Backward compatibility concerns and configuration/code complexity are my main concerns. If it makes sense for a map though, then it makes sense and we should accommodate accordingly.

> So if I submit a PR for these remaining issues would it be merged and will a test be insisted on.

Which maps would you expect for this property to be applied to? Are there any forum posts with further background information/discussion?

re: test - it's a big weakness in the TripleA project, we are nearly drowning in overhead from manual regression testing.   I would view it this way, it's not the code reviewers job to make sure something is tested, but to make sure it *was* tested. If an update is easy to review, and a review can examine entry paths easily into the code and reason about the update easily enough, and if there is really good description of what testing what was done, then we can acknowledge that sometimes things are really difficult to test in their current form in TripleA.

On the other hand, a lot of it is simply *trying* to test. It's not very commendable to do a minimal job, manual test, and force anyone else working on the project to figure out which manual tests were done and to repeat them (most likely though we'll be practicing the 'test once and never again' test strategy).

Regardless, throwing 2-5 lines of business code being updated in a new class that can be tested and extracted from UI is a trick that I suspect can almost be universally applied.  This is called creating a "test seam". Hopefully that answers the question and is not too unreasonable, if not, summarizing, I recommend make an effort to test something and as much as you can, and then document the manual test cases that were required.

**Comment by DanVanAtta** [comment]
@simon33-2 is this all fixed up with #1674, can we close this and track with the open PR instead?

**Comment by simon33-2** [comment]
Sounds reasonable to track in #1674. I believe it fixes everything.

Regarding the testing, I find it very difficult to get the tests working and actually achieving something. In the past I've had PRs not proceeded with because some problem I can't see how to fix the test. Annoying!
