### ISSUE TITLE
need files of older versions

### ISSUE THREAD

**Issue by Rogue77-NL** [triplea-game/triplea#1619]
Hello dear developers,

To make a long and tedious story short: can anyone send me the folders triplea_1_2_5_5 , triplea_1_3_1_1 and triplea_1_6_1_2 including their content, belonging to the older versions with the same numbers?

The long and tedious story is: I kept these old versions installed until last November, but with the mentioned folders stored away on an external drive. I then put the folders back with my program files, and uninstalled the programs. Today my system crashed, and I had to use a system recovery point from September (!) to restore it. As a result, TripleA versions 1_2_5_5, 1_3_1_1 and 1_6_1_2 are back in the registry (they show up under 'installed programs'), but their files (that were kept elsewhere in September), including the uninstall.exe files, remain deleted. This means I can't properly uninstall again, and I'd like to do a 'clean' uninstallation, instead of messing around in the registry (lacking experience).

Older versions are not available for downloading anymore anywhere (although I still found 1_8_0_3 on CNET...)

I hope someone will help me! Kind regards, and many thanks in advance.

**Comment by RoiEXLab** [comment]
Hmm... Not sure if we still have those files...
I personally use [CCleaner](https://www.piriform.com/ccleaner) to get rid of broken installation entries...
`Tools > Uninstall` Shows all installed applications. Selecting one of those an pressing "Delete" (or remove, not sure how it's labeled in english) instead of uninstall should do the trick

**Comment by Rogue77-NL** [comment]
Maybe someone else still has them, @veqryn perhaps? If not, I might follow your advice, but I do prefer regular uninstallations over installing more software. Thanks again!

**Comment by RoiEXLab** [comment]
In this case removing those entries from the registry shouldn't be that hard...
Found This: http://stackoverflow.com/a/18109613
Just Press WindowsButton + R type in `regedit`, hit enter and browse to the path inside the registry editor an remove the triplea entries...

**Comment by Rogue77-NL** [comment]
Thanks again! I am a bit confused. I installed CCleaner to check it out anyway, and it indeed gives me the option to 'delete' the entries from the list of 'installed programs' ('uninstall' is grayed out, since the uninstaller.exe file is missing), but so does Windows itself after uninstallation fails. Does 'deleting' the entries actually remove all remaining traces of these programs from my system? (As mentioned. I had to recover my system to a point before uninstallation, meaning they're installed again, right?). To be honest, I can't even find them in the registry. :-)

**Comment by Rogue77-NL** [comment]
Thanks again! I am a bit confused. I installed CCleaner to check it out anyway, and it indeed gives me the option to 'delete' the entries from the list of 'installed programs' ('uninstall' is grayed out, since the uninstaller.exe file is missing), but so does Windows itself after uninstallation fails. Does 'deleting' the entries actually remove all remaining traces of these programs from my system? (As mentioned. I had to recover my system to a point before uninstallation, meaning they're installed again, right?). To be honest, I can't even find them in the registry. :-)

**Comment by Rogue77-NL** [comment]
PS maybe this is something for the forum instead of a bug report, but it's kinda hard to be sure you're on the right one. ;-) I got here through 'feature request' on the new website, after I didn't find the previous releases in the appropriate section there. so jah.. :-) And I figured if anyone still has those folders it's probably one of the main developers.

**Comment by veqryn** [comment]
checkout: https://sourceforge.net/projects/triplea

**Comment by Rogue77-NL** [comment]
I did! :-) I couldn't find them there (section 'Files' is emtpy), but I now found this in the 'Code' section:
https://sourceforge.net/p/triplea/code/HEAD/tree/branches/ . Are you referring to that page? Which files should I download to uninstall the programs? Are the uninstallers for versions 1_3_1_1 and 1_6_1_2 available too? Sorry for the trouble, and thank you for your time!

**Comment by veqryn** [comment]
I suggest just uninstall using the control panel's uninstall procedure.
If that doesn't work, then I'm afraid at this point you're on your own.

**Comment by Rogue77-NL** [comment]
- What do you mean by control panel, Windows itself? If I try that, it seems to look for the uninstall .exe file too, and I get notified that it seems that the program was deleted already (since the uninstaller is missing). 

- Are the older versions (of the uninstall executable) really nowhere available anymore? Don't you have them?

I would need the folders triplea_1_2_5_5, triplea_1_3_1_1 and triplea_1_6_1_2 including their content to uninstall, perhaps just the appropriate uninstaller would do, or perhaps complete new installations would do the trick (after which I would uninstall again).

- What do you mean with your 1st response: "checkout: https://sourceforge.net/projects/triplea"? Where exactly do I need to check?

- What do you think about RoiEXLab suggestion? If I delete the entries from the list of installed programs (either through Windows itself or CCleaner), would that clear my system of all traces of the programs, or will the registry be polluted?

In case the older versions are still out there, perhaps they could be added to the 'download older versions' section on the new website. That's a feature request indeed. :)

Thank you again for your time and effort!
