### ISSUE TITLE
Commit Comments

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#162]
When looking at the git history, does everyone see all of the following?
- list of files changed
- author
- date of commit 
- commit comment

If so, good, and we are on the same page and also clearly do not need to redundantly include the above information in a commit comment. Example, for a while I was using only `git log` which does not show the file list, so I was adding file names often unnecessarily to commit comments. With an improved git log alias, clearly it wasn't necessary to always indicate the file changed.

example:
```
$ git log
commit 146679885bfc046794c4399a2bac5cf6cad4a03b
Author: Dan Van Atta <dhvatta@gmail.com>
Date:   Wed Sep 2 20:58:34 2015 -0700

    Add *.jar and *.ico to .gitattributes binary files list.
```

vs:
```
alias gl='git log --stat'
$ gl
commit 146679885bfc046794c4399a2bac5cf6cad4a03b
Author: Dan Van Atta <dhvatta@gmail.com>
Date:   Wed Sep 2 20:58:34 2015 -0700

    Add *.jar and *.ico to .gitattributes binary files list.

 .gitattributes | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)
```

**Comment by DanVanAtta** [comment]
I'm also generally curious to know how people are viewing commit comments (and/or git history). That perspective could help ensure we create a commit history that is useful for each other.

**Comment by gaborbernat** [comment]
I'm using http://jonas.nitro.dk/tig/ :)

**Comment by DanVanAtta** [comment]
screenshot?

**Comment by gaborbernat** [comment]
![Initial view](http://i.imgur.com/WZwme9Y.png)

![diff view](http://i.imgur.com/LkxzxZ8.png)

**Comment by veqryn** [comment]
I really only look at it through github, and if I absolutely have to then also TortoiseGit...
I'm still not really sure what this question is asking...

**Comment by DanVanAtta** [comment]
Of practical purpose this question is to make make sure that our commit messages do not include redundant information compared to the context in which they are viewed. The four data points listed in the OP are pretty standard for most git history viewing tools, and is a good common set to agree on. An implication of that agreement is that commit comments should not include those other three data points, it would be redundant.

At the same time, this is a good opportunity to share knowledge of tools, so in case someone is not viewing the history in a highly effective manner, we may be able to collectively help each other. To that extent, on Windows I would recommend looking at SourceTree (though personally I would use cygwin+Git CLI).

**Comment by DanVanAtta** [comment]
More directly, if everyone is viewing the commit history with all 4 pieces of information stated above, then we can agree to not add redundant information to commit messages. Alternatively it is impossible for someone to view the commit history with the 4 pieces of information, or perhaps there is an opportunity for them to use a better tool. For example, the files modified data point make it obvious what is an AI only change, so just as I was describing which files were modified needlessly in commit comments, same for prefixing  commit comment with "AI"

**Comment by DanVanAtta** [comment]
@ron-murhammer On second thought, labeling commits with "AI' or alternatively other things like "performance improvement" or "bug fix" has benefits. Hence it is not quite as redundant to the other data points viewed with the change history as it could be.
