### ISSUE TITLE
Dice server problems

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#1624]
```
Test
Contacting  dice.tripleawarclub.org
An error has occured!
Possible reasons the error could have happened:
  1: An invalid e-mail address
  2: Firewall could be blocking TripleA from connecting to the Dice Server
  3: The e-mail address does not exist
  4: An unknown error, please see the error console and consult the forums for help
     Visit http://tripleadev.org  for extra help
Text from dice server:

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>	M.A.R.T.I. Server --> "more accurate rolls than irony"- server</title>
</head>
<body>
<br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined function mysql_connect() in /usr/share/nginx/html/tripleawarclub.org/public_html/dice/dice.class.php:39
Stack trace:
#0 /usr/share/nginx/html/tripleawarclub.org/public_html/dice/dice.class.php(72): dice-&gt;connectDatabase()
#1 /usr/share/nginx/html/tripleawarclub.org/public_html/dice/MARTI.php(58): dice-&gt;checkIfMailsAreRegistered(Array)
#2 {main}
  thrown in <b>/usr/share/nginx/html/tripleawarclub.org/public_html/dice/dice.class.php</b> on line <b>39</b><br />

java.io.IOException: Cound not find start index, text returned is:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>	M.A.R.T.I. Server --> "more accurate rolls than irony"- server</title>
</head>
<body>
<br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined function mysql_connect() in /usr/share/nginx/html/tripleawarclub.org/public_html/dice/dice.class.php:39
Stack trace:
#0 /usr/share/nginx/html/tripleawarclub.org/public_html/dice/dice.class.php(72): dice-&gt;connectDatabase()
#1 /usr/share/nginx/html/tripleawarclub.org/public_html/dice/MARTI.php(58): dice-&gt;checkIfMailsAreRegistered(Array)
#2 {main}
  thrown in <b>/usr/share/nginx/html/tripleawarclub.org/public_html/dice/dice.class.php</b> on line <b>39</b><br />

	at games.strategy.engine.random.PropertiesDiceRoller.getDice(PropertiesDiceRoller.java:188)
	at games.strategy.engine.random.HttpDiceRollerDialog.rollInSeperateThread(PBEMDiceRoller.java:267)
	at games.strategy.engine.random.HttpDiceRollerDialog.access$000(PBEMDiceRoller.java:103)
	at games.strategy.engine.random.HttpDiceRollerDialog$1.run(PBEMDiceRoller.java:219)
```

**Comment by RoiEXLab** [comment]
It should work now again...
Apparently there was a file called `dice.class.new.php` which is compatible with the newer PHP version...
I just renamed 2 files to fix this issue.

**Comment by panther2** [comment]
Thank you!

**Comment by RoiEXLab** [comment]
No Problem

**Comment by panther2** [comment]
The issue seems to be back again.

**Comment by simon33-2** [comment]
I'm getting this error:
Italians roll dice for 1 battleship, 1 bomber, 2 cruisers, 1 destroyer and 2 fighters in 91 Sea Zone, round 2
Contacting  dice.tripleawarclub.org
Contacted :<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.10.0 (Ubuntu)</center>
</body>
</html>

An error has occured!
Possible reasons the error could have happened:
  1: An invalid e-mail address
  2: Firewall could be blocking TripleA from connecting to the Dice Server
  3: The e-mail address does not exist
  4: An unknown error, please see the error console and consult the forums for help
     Visit http://tripleadev.org  for extra help
Text from dice server:
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.10.0 (Ubuntu)</center>
</body>
</html>

java.io.IOException: Cound not find start index, text returned is:<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.10.0 (Ubuntu)</center>
</body>
</html>

	at games.strategy.engine.random.PropertiesDiceRoller.getDice(PropertiesDiceRoller.java:188)
	at games.strategy.engine.random.HttpDiceRollerDialog.rollInSeperateThread(PBEMDiceRoller.java:267)
	at games.strategy.engine.random.HttpDiceRollerDialog.access$000(PBEMDiceRoller.java:103)
	at games.strategy.engine.random.HttpDiceRollerDialog$1.run(PBEMDiceRoller.java:219)


@RoiEXLab 

Can this be fixed as a priority? Effectively, PBF/PBEM aren't working now. Seems a different problem to before. Do we need to change the page the dice roller calls?

**Comment by RoiEXLab** [comment]
#1656 has a fix...
TripleA simply couldn't handle a simple 301 redirect...
I updated the servers to use https, that's why "they weren't working"
I will enable both http and https until the patch is available...

**Comment by panther2** [comment]
Thank you!
