### ISSUE TITLE
Old Jar mechanism.

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#1648]
Why doesn't this work properly any more? I could accept a break between 1.8 and 1.9 because all the maps are different but that is already effectively provided because 1.8 jars look in $HOME/triplea/maps or <triplea_root>/maps for maps while 1.9+ jars have a configurable search directory. So long as they are different, there shouldn't be any problem.

Looking forward, I wouldn't like to see this being completely removed in 1.9.1+ Would be highly annoying when multiple versions 1.9+ are out there. I would say that removing this is effectively an argument that we shouldn't be doing anything backwards incompatible and indeed removing the knowledge of "what version I am" from the jar seems to say precisely this. We've already had some non backwards compatible changes in 1.9 e.g. build 2984 didn't work with build 3010+. This was quite naff and would have been better if the third version number had been moved on.

All that's really needed as I see it is reinstating knowledge of the version to the jar, adding to the installer creation of links to the old version's map directories and links to any old jars.

**Comment by DanVanAtta** [comment]
I understand the point of view of not wanting many versions. There certainly is a trade-off here, it's not clear one way or another whether to drop or support this issue.

If the game installs are small, they happily sit side-by-side in file system, they are clearly identified on launch, and easily downloaded (http://www.triplea-game.org/old_downloads/), then maybe it is not that much of a problem to launch the right version for the right save.

If we drop the feature altogether, then we shave off the largest chunk in terms of size off of the installer. This speeds up the download and the install4j install speed. We also gain simplification gains in the code base as well. Notably when coding we don't have to worry about what would happen to old jars, and we get to drop the infrastructure for it.

On the other hand, it is pretty convenient to have one version of tripleA and it launch old ones for save games, save games do live for months at a time. I think ideally we solve the backwards compat issue altogether, but that will be some time.

@simon33-2 please consider the above. Let me know what you think, how we should proceed. Should we fix up the old jar feature, and continue making sure it works? Or shall we drop it and make that process as convenient as possible? (other options?)

**Comment by simon33-2** [comment]
I don't know what to add to my previous comments. I don't see the big deal about the download size, why the jar would be ignorant about its version number or the trend in the project towards more naff setups and less usability. The problem with the old downloads is that it is not at all clear when you load a save game what version you should be loading it with. Would be nice if the computer could sort this out as it did in the past.

Just having the 1.9.0 install find the 1.8 installation seems to resolve most of the limitations but then what about 1.9.1 or 2.0?

**Comment by RoiEXLab** [comment]
Closing in favour of #2284
