### ISSUE TITLE
Feedback on Development-Initiatives.md

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#1650]
- Mobile factories - that's a bit of an unreasonable requirement isn't it?
- There is already support for consuming units. Factory_upgrade consumes Factory_minor. Does the AI not consider this and even if it doesn't, I'm not sure why this is a problem. Don't think I've ever seen anyone upgrade a factory in global yet. Perhaps there's another map where it makes more sense to do so?
- Improving performance. Yeah, it's pretty tragic.
- Re: UI improvements. The major problem with the UI is the enormous number of times that you are asked which colour you want and also told (or need to work out) you can only have black. Just auto select if there is only one option! Fight-all/roll until someone hits probably are lower order issues. A higher order issue is that battles are presented that are invalid for selection, either due to a dependent battle or not being an amphibious assault when not all amphibious assaults are processed.
- Battle calculator. The annoying part about this is multinational forces on attack. If you select a new nation for the attacker, all attacking units are zeroed out. I submit that it should leave the units for that nation and remove all other nations. Not sure if any maps allow multinational forces on the attack or if the rule that only the currently playing nation can have its forces attack applies in every map?
- Better info displays. There's really only one issue I have with the current "Stats" display and that is the lack of a column for total number of PUs from currently valid objectives.
- v5-1942 interception is not correctly supported. This is supposed to remove defending interceptors after the attackers fire, believe it or not.
- Repair and Purchase should be combined. Not correct according to the rules at present.

The most important issue to resolve though is #1645, at least for global 1940 players. Second is the Repair/Purchase problem.

Is that helpful @DanVanAtta ?

**Comment by DanVanAtta** [comment]
> Battle calculator. The annoying part about this is multinational forces on attack. If you select a new nation for the attacker, all attacking units are zeroed out. I submit that it should leave the units for that nation and remove all other nations. Not sure if any maps allow multinational forces on the attack or if the rule that only the currently playing nation can have its forces attack applies in every map?

:+1:  multi-national can also  lead to subtle incorrect calculations. I've been thinking a copy/paste feature would be a good step forward. Does not address this problem though. I agree we could use some investment to make the battle calc better.

> Better info displays. There's really only one issue I have with the current "Stats" display and that is the lack of a column for total number of PUs from currently valid objectives.

Agree. 

 > v5-1942 interception is not correctly supported. This is supposed to remove defending interceptors after the attackers fire, believe it or not.

Recommend/ask opening a new issue to track this specifically. More detail on how to reproduce would be appreciated

**Comment by DanVanAtta** [comment]
closing for now, please re-open @simon33-2 to pick up the topic again.
I'm adding 'ice-box' label as there are some good ideas here, someone may find inspiration from them and pick them up yet.
