### ISSUE TITLE
Persistent error in recent code line.

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#1653]
Every time I load a saved game from another player after running a recent release (just checked against origin/master) I get the following Java console:

triplea.engine.version.bin:1.9
Unit.toString() -> Possible java de-serialization error: Unit of UNKNOWN TYPE owned by UNKNOWN OWNER in territory: UNKNOWN TERRITORY with id: null

What's the cause of this one? Just checked out if #1583 was a cause and refactoring that still results in the error occurring.

**Comment by panther2** [comment]
I can reproduce this issue but it seems to be `map-xml-dependent:`
For example I can open savegames for `ww2global40_2nd_edition.xml` loading without issue.
Savegames for `ww2global40_balanced_move1st.xml` appear to have the issue mentioned.

**Comment by simon33-2** [comment]
So it could only occur for games I'm involved in? Hmm, perhaps #1583 is to blame then.
