### ISSUE TITLE
Destroyed scrambled Air units resurrected before amfibious land battle

### ISSUE THREAD

**Issue by dahlsdata** [triplea-game/triplea#1691]
Just tried to invade Italys capital by first defeating Italys fleet. 
In the naval battle Italy scrambled 6 air units from the capital, some italian and some german.
All 6 air units died in the naval battle. 
Then after the battle (before the following land battle for southern Italy), the fighters reappear and is now defending Italy.
In the attached savegame you can see the game history of UK`s turn to see the bug.

[triplea_UK_14.tsvg.zip](https://github.com/triplea-game/triplea/files/984022/triplea_UK_14.tsvg.zip)

**Comment by panther2** [comment]
No problem here.
The maximum number of air units that can scramble to SZ 95 is 3. So one German fighter and two Italian fighters scrambled to SZ 95. Three Italian fighters had to stay on land. So only those three scrambled fighters died in the naval battle. Those fighters defending in the land battle are the three fighters which had not been scrambled. 
You can retrace that in the game history.

Please close this issue unless you don't have additional questions regarding this subject.

**Comment by ron-murhammer** [comment]
Closing. If you have further questions feel free to re-open this issue.
