### ISSUE TITLE
Efficient XML Interchange

### ISSUE THREAD

**Issue by djensen47** [triplea-game/triplea#17]
Just saw a presentation on this format. It's supposedly 100% compatible with XML but it's about 3000% smaller.

It's widely used in industry but not so much with open source projects.

**Comment by veqryn** [comment]
This seems like something that only applies to the transfer of an XML, and would not change the difficulty of writing it or reading it. I don't think we want this.

**Comment by gaborbernat** [comment]
This would probably just make the XML smaller so result in smaller network overhead. I don't think network overhead is an issue yet. And if it does become someday we can win bigger by upgrading to YAML. I think we can close this.

**Comment by djensen47** [comment]
This needs to be re-opened (or opened as a different issue) and not summarily dismissed in this manner, please and thank you. 

First of all, there is an issue with network overhead. The current problem with posting to axisandallies.org is not only the server. The server seems to be getting backed up on uploads. Many times the error dialog will indicate failure but post the file anyway. Smaller files means less backup. 

Next, the files are _insanely_ large. Yes, one file on your drive is not a big deal. Trying thousands upon thousands. It adds up quick. My bill for AWS S3 is increasing my $5/month. Smaller files will help reduce this cost.

After watching a preso on EXI, almost any other binary format is better that gzipped xml. EXI was one idea, there's also Protocol Buffers, Message Pack, and even BSON would help on this front.

**Comment by djensen47** [comment]
The processing power needed to parse the EXI format is far less than standard XML.

YAML would be a very bad idea (sorry I usually don't like to criticize without the research behind it but I really should be working right now so I'll get it later, promise :wink:). 

The only positive YAML has is that it is more human readable. There are other formats even more readable than YAML. JSON5 or TOML come to mind. 

The thing is, these files need to be machine readable only. File size and processing should be the quality attributes for this feature not allowing a human to view the file..

**Comment by gaborbernat** [comment]
Please note that human readability does help with debugging and enhances
the chances of being open to adding new fields inside it (note newer
versions of TripleA should parse older version save files, doesn't it) ?

Bernát GÁBOR

**Comment by djensen47** [comment]
Yes this is does read older version. You can do that with a binary format?

- Why can't you debug a binary format? Just unpack the data into an object and investigate?
- How many issues that required debugging were errors in the XML itself?

**Comment by djensen47** [comment]
Yes this is does read older version. You can do that with a binary format too. I'm not saying to use a custom binary format but something like XML or JSON but just the binary representation of that. EXI in particular works almost exactly like XML. The different for "readability" would be you would have to process it into readable UTF-8 text first or use an XML editor that can read EXI.

Why can't you debug a binary format? 
  - Just unpack the data into an object and investigate, right?
  - How many issues that required debugging were errors in the XML itself? :wink: 

*Note:* My previous, deleted, response was missing some things so I updated and reposted since I know a few of you are responding via email.
