### ISSUE TITLE
Update stable version

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#1715]
I believe the latest master can be considered stable, but before updating 2 things should be done first!
https://github.com/triplea-game/triplea-game.github.io/pull/156 should be finally merged!
Once it's merged we no longer need to update the website manually, the latest stable version is always retrieved via javascript (I also added a fallback link for the case javascript is not working/disabled).
Also #1714 should be merged in order to have updated links.

@DanVanAtta @ron-murhammer

**Comment by simon33-2** [comment]
I would think #1583 would need to be reverted first. That change can be reincorporated with a bump in the version number.

**Comment by ron-murhammer** [comment]
Moving conversation to #1768
