### ISSUE TITLE
Add capability to download map via "custom protocol"

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#1723]
As discussed in https://github.com/triplea-game/triplea-game.github.io/issues/33 this would be a nice feature for the website.
We can configure install4j to write some values into the registry/create some files on linux based systems.
All we'd then need to do is to modify the main method so the maps are automatically downloaded when specific command line args are being passed.
@ssoloff @DanVanAtta How much work is needed to enable such a feature? Is it just a couple lines of code or do we need to change the download system before this feature can be implemented?

**Comment by ssoloff** [comment]
@RoiEXLab, the only thing I can accurately confirm is that it is straightforward to programmatically open the Download Maps window and start a download using the `DownloadMapsWindow#showDownloadMapsWindow(String)` method.  (Note that this method has been renamed to `showDownloadMapsWindowAndDownload()` in #1695, and a new overload was added to start downloading multiple maps.)

Now, communicating the map(s) to download from the command line to an appropriate place where you can call `DownloadMapsWindow#showDownloadMapsWindow()` is a different story.  I haven't had to do this before, but I think I'm going to need to when I try to incrementally introduce serialization proxies, so I thought I'd take a look at how command line arguments are currently processed in `GameRunner#main()`.

It looks like all information specified on the command line is communicated to downstream code via system properties (i.e. using `System#setProperty()` in `GameRunner` and `System#getProperty()` in downstream code).  If you go that route, it shouldn't require many changes beyond adding a new supported property definition.  In fact, `MainFrame` already uses this mechanism (via `triplea.game`) to load a saved game specified on the command line (see `MainFrame#start()`).

`MainFrame#start()` might also be the best place to trigger the `DownloadMapsWindow#showDownloadMapsWindow()` call after the frame window is visible.  You'll probably have to experiment a bit to see what provides the best UX.

**Comment by RoiEXLab** [comment]
@ssoloff I'm currently working on the install4j script and I believe I made the trigger (for windows only) work.
I couldn't test it though, since I don't have a License key for install4j in order to generate a test installer...
See https://github.com/triplea-game/triplea/compare/master...RoiEXLab:launcher-branch for my current changes

I'm still facing another problem: The desktop file for triplea on [freedesktop.org](https://freedesktop.org) systems is generate pretty much automatically, e.g. we can't configure much.
We'd somehow need to get the path the file was generated in and append `MimeType=x-scheme-handler/triplea` to it and append `x-scheme-handler/triplea=<DesktopFileName>` to a file called `mimeapps.list` located in the same directory

**Comment by ssoloff** [comment]
@RoiEXLab 

> I couldn't test it though, since I don't have a License key for install4j in order to generate a test installer...

Try contacting ej-technologies.  They provided me with a license key for install4j when I told them I wanted to contribute an installer fix to TripleA.  The owner is very supportive of open source.

> The desktop file for triplea on freedesktop.org systems is generate pretty much automatically, e.g. we can't configure much.

I'm afraid I have zero experience in this area and so can't offer much in the way of advice.

**Comment by RoiEXLab** [comment]
@ssoloff 
> I'm afraid I have zero experience in this area and so can't offer much in the way of advice.

It's not that complicated...
On Linux things like protocol handling are managed by the Desktop environment e.g. GNOME, XCFE, Unity, KDE, etc.
This is because if an application is installed those "desktop files" make is possible for those applications to be listed in the "start menus", just like it's done with triplea.
If you define a mime type for your app and register this mime time with your desktop file, it causes webbrowsers to open specific protocols with your app.

**Comment by prastle** [comment]
all i can say is wow! sorry for requesting something ii thought was a simple fix.
