### ISSUE TITLE
Validate YAML files during build

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/triplea#1728]
The YAML files consumed by TripleA (currently `lobby_server.yaml` and `triplea_maps.yaml`) should be validated during the build to avoid errors at runtime.

We currently [validate the structure](https://github.com/triplea-game/triplea/blob/master/.travis.yml#L6-L8) during the Travis build only.  However, this does not detect certain classes of problems, such as missing object properties that were the cause of #1704.  It has been [suggested](https://github.com/triplea-game/triplea/issues/1704#issuecomment-302001480) to enhance error detection by validating each YAML file against an appropriate schema.

Ideally, this validation should run via Gradle so contributors can know if their changes will break the build before they push.

**Comment by RoiEXLab** [comment]
I believe this can be closed.
