### ISSUE TITLE
Compatibility Testing: Document and Automate

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#1736]
Need to document the following and determine if we can create automated tests:

To check game compatibility, there are two things to check:

save games: save with new game, load from file with old and vice versa
network:
A) host a local network game with latest, then rebased to a different commit, launch a second instance and connect locally. Progress far enough to fight a battle.
B) with latest version, connect to lobby, play a game in a bot until you get to combat

Tasks
- [x] Document
- [ ] Automate tests

**Comment by RoiEXLab** [comment]
Good idea!
I believe it could become problematic if no lobby bots available, maybe we need another solution for that.

**Comment by ssoloff** [comment]
@RoiEXLab Can a dev just run the lobby and a bot locally to achieve the test goals so we are not reliant on what's available in production?

I've been following what you've been doing with the lobby scripts in triplea-game/lobby#27.  Is there a simpler procedure to run a lobby and bot locally?  If not, such a test/staging lobby might be another candidate for a Docker image.

**Comment by DanVanAtta** [comment]
There are launchers for lobby + bot in eclipse/launchers FWIW. Though there are also a few updates needed to get lobby running. A copy of the same version of derby.jar that lobby is running, and also the jdbc loader needs to be invoked..  I'm actively working to make this area better, have not fully decided whether to improve current set up or focus on new that will replace derby and may potentially alter how we launch lobby + DB.

**Comment by DanVanAtta** [comment]
@ssoloff  FWIW, some details on what needs to be done to have the lobby run and connect to derby: https://gist.github.com/DanVanAtta/72947202bd4dca0eeb586e5e16c510e4

**Comment by RoiEXLab** [comment]
@ssoloff Using `start-stop-daemon` you should be able to launch a "local lobby" server process in the background so you can try connecting to it.
The lobby scripts are using systemd which is more suited for permanent installations, not for testing, but you can of course still use the [run_lobby](https://github.com/RoiEXLab/lobby/blob/user-update/run_lobby) scripts etc.

**Comment by ssoloff** [comment]
The documentation portion of this issue has been addressed by triplea-game/triplea-game.github.io#188.
