### ISSUE TITLE
Document carrierCost=0 Functionality in POS2

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#1737]
Document the functionality of carrierCost=0 air units discussed in this thread (https://forums.triplea-game.org/topic/95/global-dominance/27?page=2):

Then you give it carrierCost=0, which lets it land in empty sea zones as if there was a carrier there. So on the next you move your hull into the sea zone and it should land just fine (isKamikaze could work as well but this seems cleaner). Then you buy the battleship, and it should consume the hull just like it would consume a sea unit version.

POS2 XML:
https://github.com/triplea-maps/the_pact_of_steel/blob/master/map/games/pact_of_steel_2.xml

**Comment by beelee1** [comment]
is the POS2 xml being actively updated ? If so who is/are the person/people ?

**Comment by ron-murhammer** [comment]
@beelee1 Anyone can submit a PR request to update the XML. There really hasn't been many game XML changes over the past year so it hasn't really needed updated.

**Comment by beelee1** [comment]
right on TY.  When it is updated does it go to a different version then ? with a changelog ?

**Comment by ron-murhammer** [comment]
If its only documentation updates then probably just incrementing the map version in: https://github.com/triplea-game/triplea/blob/master/triplea_maps.yaml

This will push the updated XML to anyone who downloads the map. Probably don't need to increment POS2's version or do anything to the changelog.

**Comment by FrostionAAA** [comment]
@Cernel tried to explain this issue to me. Thanks for the clarification. I hope I understand correctly now.

If a mapmaker wants to make a map with carriers and fighters with carrier capacity and cost within reasonable numbers, the map cannot have air units with carriers cost 0 be dependent on landing on carriers. That plane just lands on water without sinking and I would say that this is not the behavior a player og mapmaker would expect. When you look at the unit ingame it also clearly states “0 Carrier cost” which would be understood as “does not take up room on carrier”, and IMO players would by default expect air units to have to land on carriers to survive.

I think that this should change so map makers can have 0 carrier cost fighters be dependent on carriers.

But I really like Cernels idea about a new “isSeaPlane” option for the air units. It could just trigger this old (faulty) behavior to be true. It would be cool also to have this kind of sea plane behavior along side air units that are dependant on carriers while having 0 carrier cost.

**Comment by ron-murhammer** [comment]
Here is a PR to add the description: https://github.com/triplea-maps/the_pact_of_steel/pull/1.
