### ISSUE TITLE
Scripting Languages in TripleA Repo

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#1741]
I think we should have a discussion on choosing a default scripting language to use in the TripleA repo to avoid lots of different ones being used as this makes it difficult to maintain.

Python is being proposed in #1740 

**Decision for now: Go with Python 3**

**Comment by ssoloff** [comment]
As TripleA is a JVM project, I will throw Groovy out there for consideration.  Especially since we already use it for our Gradle scripts.

I'm ok with Python (preferably version 3).

(I'm assuming this issue doesn't apply to the shell scripts used for various things, and we will continue to use bash, sh, and Windows batch files, as needed?)

**Comment by ron-murhammer** [comment]
In theory, I'd like to consolidate the ones we have to a single scripting language as well but that would be a sizable effort. I don't particularly like that we have both sh and batch versions of the same scripts.

**Comment by RoiEXLab** [comment]
@ssoloff The script I created uses python3.
It's supposed to be used to create html files for the website every time the triplea_maps.yaml file gets changed and push them, so gradle isn't an option here.

@ron-murhammer I agree, it's not perfect having multiple script files for different oses.
Scripts which are just for travis should just exist for Linux based systems, having a windows version is not necessary.

**Comment by ron-murhammer** [comment]
@simon33-2 @DanVanAtta Any thoughts on this? Seems the 2 main suggestions so far are Groovy and Python.

**Comment by simon33-2** [comment]
I'd go with Python. I know that a bit and don't know Groovy at all so I guess I'm a bit biased there.

**Comment by ssoloff** [comment]
> don't know Groovy at all

Most Java syntax is also valid Groovy syntax (some Java 8 syntax is not yet supported).  So, in a sense, you do know a bit of Groovy. 😃  You can always start writing very Java-like code and transition to the more compact Groovy syntax as you learn the languages and its idioms.

**Comment by DanVanAtta** [comment]
Different languages have different uses, I'm wondering if we're being overly prescriptive. 

> I don't particularly like that we have both sh and batch versions of the same scripts.

Having multiple versions of the same script is a problem. Perhaps we should dig deeper on this one for where we are having problems.

I would also wonder what it would mean for existing scripts that have no duplicate if we decide a single scripting language. Would we then rewrite those scripts for the sake of rewriting them? Again this makes me think we should clarify where we are see the pain points.

**Comment by ron-murhammer** [comment]
@DanVanAtta My main concern is I don't want to have 5 different scripting languages used by different people and different things. Then those folks move on and its very hard to maintain all the different scripts. I'd rather come together as our small active group of developers and decide on what scripting languages we are comfortable with and prefer so we kind of have a standard.

In regards to converting existing scripts, its probably not worth the effort but always a possibility.

**Comment by ron-murhammer** [comment]
I'd say based on the conversation let's go with Python 3 for now. We can always reopen this if more scripting opportunities arise and we want to reconsider.

**Comment by DanVanAtta** [comment]
@ron-murhammer I don't think I we can exclude bash shell scripts. Though I'm very happy with saying either python or shell, whichever is better. For XML or YAML parsing, that is probably best not done in shell. On the other hand shell suites some tasks really well, and besides it is not going away - we have quite a lot of shell scripts and for better or worse it is part of our CI build.

**Comment by ron-murhammer** [comment]
@DanVanAtta Fair. I would like to try to use Python for any new scripts especially anything outside of the lobby stuff. I acknowledge that we most likely won't rewrite existing scripts.
