### ISSUE TITLE
Error pop-up when loading saved battle from previous version

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1771]
Following up from:  https://github.com/triplea-game/triplea/pull/1745

When loading a save game from 1.9.0.0.3635 with latest version, we are seeing an error pop-up as the battle progresses. Example:

> Current battle exists but is not on pending list:  Battle in:Ukraine S.S.R. battle type:Battle defender:Germans attacked by:Russians from:[Caucasus, Karelia S.S.R.] attacking with: [armour owned by Russians, armour owned by Russians, armour owned by Russians, fighter owned by Russians, fighter owned by Russians, infantry owned by Russians, infantry owned by Russians, infantry owned by Russians, infantry owned by Russians, infantry owned by Russians]

Task, fix it so we do not see the pop-up. The logging level seems inappropriate since the error is not fatal, so we can log this quietly. As a follow up, it does seem odd that we would log the message at all. There seems to be an incorrect assumption somewhere in code.

Attached is a save game that should repro. Load the save as a single player local game and click through on the battle. Before the battle is over you should see the above
 error message pop-up.

[test_save_1745.zip](https://github.com/triplea-game/triplea/files/1039161/test_save_1745.zip)

**Comment by simon33-2** [comment]
Problem is fixed. Wondering why this issue is open? Given that it only affects hard core users who have downloaded a build from github. The stable release was never impacted.

**Comment by DanVanAtta** [comment]
@simon33-2 it's part of what was the intent for the new release model, basically every new version on github would be marked a stable unless we found bugs. 

good to hear it is fixed, thanks.

**Comment by simon33-2** [comment]
Is that a good model? Might as well get rid of the stable release tag. I think a release that has been beta tested should be marked.

**Comment by DanVanAtta** [comment]
Quite a number of benefits to small, frequent iterations, from being able to update code and get feedback quickly, to being able to debug more quickly.

But, we've got some brittle code, lots of overhead with regression testing. Hence the 6 month cadence that we sometimes fall back too. We've still seen problems with that model as we allow things in and then have a big and disruptive bug bashing "stabilization" period. Instead the idea was to emphasize longer term investments that improve test, and iteratively ensure we don't merge broken bandaids on  :hankey:. Problem is, it's quite a lot to get there too, and we still miss things, and we're spending too much effort from our code review resources when they could more focused on code reviewing.

The ticket seems to be a hybrid, enlist beta testers to help us beta test specific releases, dev's focus on testing and decreasing complexity and increasing test coverage, and reviewers ideally more focused on reviewing code.

> Might as well get rid of the stable release tag.

By default I'll note any new release would be marked as "stable", we had to override it so new ones would be "prereleases", FWIW. 

> I think a release that has been beta tested should be marked.

Agree, pretty much model I think that can work towards that is a public spreadsheet with versions, let the beta testers mark directly if they have tested or not. Nice thing there is you can see results from others, if bugs have already been found can wait for next fix release.
