### ISSUE TITLE
Map Download Counts

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#1772]
To help gauge map popularity, it would be great to be able to show the number of map downloads. This appears to be possible in a limited sense with the github api: https://developer.github.com/v3/repos/releases/#get-a-single-release-asset

Though it doesn't seem to track the source code zips only release assets.

**Comment by RoiEXLab** [comment]
TripleA is downloading the maps via the "source code of latest master link": [Example](https://github.com/triplea-game/triplea/blob/master/triplea_maps.yaml#L33)
I believe those "clones" are not counted at all...

**Comment by ron-murhammer** [comment]
@RoiEXLab Yeah, I believe we'd need to change how we release/host map downloads in order to track it given the current github api.
