### ISSUE TITLE
Documentation - Problems & How To Fix

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1775]
Below is some context on what problems we've been seeing with documentation, and what (in my view) is still a problem.

### Documentation has been a lingering problem in a couple of ways:
- scattered
- redundant
- not consistent
- multiple copies to update
- not updated

### Progress we made
There were some earlier efforts to consolidate everything to: http://www.triplea-game.org/help/ (https://github.com/triplea-game/triplea-game.github.io/tree/master/dev_docs)

I'd guess we got somewhere around 50% to 80% of the way there to completing that effort. Next steps were to finish that effort, moving all docs to that location and then funnel users to the help section.

### Current short comings
- The documentation, though better grouped, is still not well organized
- Not all updated
- Too much of it, we could use more concise documents
- When updating the game engine, the documentation repo is a different repo. For example, update how the build works, to update the documentation for that requires a second and different PR. The two have to be kept in sync, and we have to keep promising to ourselves that we'll get around to adding the website documentation.

### For Discussion
I'm curious what other options there are that others have been thinking of how to address the documentation problem noted above. I do have a suggestion to help address this, I'm happy to discuss that further as well. Ideally I think we would identify here the full set of problems, present some options, and merge them into a plan.

###  My suggestion for something we could do

As one option, to help with the above, I'd suggest we split the developer facing documentation out from the 'public' facing documentation. This would involve moving the corresponding docs out of the website repo, back to the triplea repo. We would browse that documentation primarily as markdown via github.

The 'public' facing documentation would be whatever is left in the website, and we gear that towards the general user, power users, and map makers. It is an Open question if we want to have the map maker documentation somewhere else, but main point is that documentation only devs are concerned with (eg: checkstyle, coding standards, release process) is all in a different location.

Then by bundling the developer docs in the game engine repo, when we make changes to the game engine, we can update the documentation in the same PR. We can then double check that docs are updated appropriately.

**Comment by ron-murhammer** [comment]
@DanVanAtta Agree that the docs still need some love especially from an organization and many could use updates.

In terms of where to host them, I think we need to go in 1 of 2 directions:
1. All docs on the website with different categories
2. All docs but developer docs on the website, developer docs in the repo

My preference is actually option 1 so we keep everything together and then just have a link in the readme here to the developer docs.

**Comment by ssoloff** [comment]
What role does the GitHub wiki play in documentation?  It seems there's some dev-related docs on both the `triplea-game/triplea` and `triplea-maps/Project` wikis.

Do dev doc changes need the same scrutiny as a PR?  Would a third possibility be to host the dev docs on the wiki and just restrict write access to members?  The wiki itself is a Git repo so there's no worry about vendor lock-in if/when it ever comes time to migrate to a different hosting platform.

**Comment by ron-murhammer** [comment]
@ssoloff Yeah there is some docs on the wikis as well that was our first go at things. I think we decided it was kind of limited but don't remember exactly why we moved away for the wiki direction.
