### ISSUE TITLE
Code Formatting / Java Naming Convention

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#18]
We previously touched on this topic and found consensus we would like the "m_" and "s_" naming convention dropped. We did not discuss the "I" interface prefix convention, likely this would be dropped as well.

Next on the agenda block is the code formatting. The only remaining convention is then that curly braces are on their own line and to use tabs (announced to gasps and shocks of horror), otherwise the rest are effectively whatever happened to be in the eclipse formater when it was exported. This does create a small problem since multiple developers will not be able to auto-format code in both IDEA and Eclipse and get the same output (so in effect we may get auto-format wars going on).

The goal of this thread is to talk about updating our formatters for consistency. The goal is not to get your favorite formatting idiom in a spec, but more for us to agree on what the format spec should be. That agreement will ideally take the form of perhaps a wiki document that spells out in detail formatting decisions, and/or both eclipse and intelliJ formatters.

I think we have I think these options:
- do nothing, ignore this issue and allow intelliJ formatted code to be different
- spend time building an intelliJ formatter that mirrors the eclipse one
- use a 3rd party formatter that provides both intelliJ and eclipse formatters
- something else that guarntees consistent formatting

My proposal is to solve this would be for the 3rd option, a 3rd party format spec. Reasons:
- they've done the research, decision making, consensus building work for us.
- it's well documented we can arbitrate any formatting dispute (generally things that don't auto-format correctly)
- easy to provide intelliJ people with a formatter, same with eclipse people, adoption of this is easy :) , grab file, commit, then import into IDE
- The google java style spec is detailed: http://google.github.io/styleguide/javaguide.html

So, my question would be - is there agreement that we should try to find and use a 3rd party formatter? This lets us have consistent formatting and agreed upon formatting rules. If so, is google the only 3rd party that gives a formatter and spec? Any objections to going to that format spec?

**Comment by veqryn** [comment]
I don't remember seeing anything about the m_ and s_ variables.  Changing that would not only break savegames, but also break code that uses reflection.  Changing I interfaces would break our api's.  They may feel like formatting issues, but they are not. They are actually material changes.

On the actual topic of formatting, I would personally like to be able to auto-format in both eclipse and intellij, without any difference at all between them.  That would be great, and it should be easy to implement without having to download aor install a lot of crap, or spend hours configuring things.

On the other issues, I can be flexible on stuff like braces, tabs/spaces, etc.
I prefer longer line limits (120-150), tabs for indentation and spaces for lining things up after the indentation, braces on their own line for classes and functions, but on the same time for everything else, braces mandatory for single line if/for/while/else/etc.  But again, I am flexible on this.

**Comment by DanVanAtta** [comment]
Naming convention is tough because it tends to get baked in and you're stuck living with bad names/conventions.  Formatting generally is more tough because personal opinions start spilling out, and executing formatting changes everywhere  often doesn't happen.

This quickly brings up other points. Reflection means that we don't get compatibility between versions, and serialization breaks saves, yeah.. I think we should discuss those points more.

w.r.t not downloading too much crap. Either we can find two formatters out there on the web for the two IDE's that do the same thing, and we like the format,  or we take the time to mirror some agreed upon settings between two hand done formatters. My  suggestion is to avoid that, use the google formatter's provided, saves some time, then we can focus on formatting everything.

**Comment by veqryn** [comment]
Do those two style configs create formatting that does not change whether you use intellij or eclipse?  We should test them out on a big ugly class like TripleaFrame or something.

**Comment by DanVanAtta** [comment]
Funny enough, we don't even have TripleaFrame in our style. I was learning how to import a formatter into intelliJ and ran into the intelliJ recommendation that you import formatter settings into intelliJ using the eclipse formatter XML: https://confluence.jetbrains.com/display/IntelliJIDEA/Code+Styles

It appears intelliJ has solved this problem. Then the question I suppose remains is whether to adopt google code style, keep the current, some hybrid, or move to another format completely.

**Comment by veqryn** [comment]
@DanVanAtta @ron-murhammer 
I've added the google style eclipse format xml to our project, with 4 modifications:
<setting id="org.eclipse.jdt.core.formatter.comment.line_length" value="140"/>
<setting id="org.eclipse.jdt.core.formatter.join_lines_in_comments" value="false"/>
<setting id="org.eclipse.jdt.core.formatter.join_wrapped_lines" value="false"/>
<setting id="org.eclipse.jdt.core.formatter.lineSplit" value="140"/>

I've also exported my eclipse "cleanup" settings and added them.

I usually have my ide's set to cleanup & format on save, the entire file being saved.

**Comment by veqryn** [comment]
After much mucking around (like 2 hours), I've managed to get Intellij 14 community edition to respect Eclipse's format xml, with 1 and only 1 exception: Intellij insists on adding a freaking space after the * in a comment block.
Anyway, here is how I got it to work:
1. Import the xml into intellij's java code style, and then choose it as your style
2. Edit the general and java code style to use 2 spaces for tab size and indent, and 4 for continuation indent.
3. On java code style imports tab, change class and name counts to 99, and then delete the two lines under "packages to use import with *"
4. Download the plugin "Eclipse Code Formatter" and restart intellij
5. Open up settings again and go to 'other settings' and enable the plugin.  Make sure the following are checked: "Use the Eclipse code formatter", "Enable Java", "Use Eclipse 4.4 Java formatter / otherwise Eclipse 4.5 ....", "Optimize Imports"
6. Browse and select the Eclipse java formatter config file.

This *should* be all that is needed...

**Comment by DanVanAtta** [comment]
I just saw that you the line length is 140

setting id="org.eclipse.jdt.core.formatter.comment.line_length" value="140"
setting id="org.eclipse.jdt.core.formatter.lineSplit" value="140"


Google style recommends 80 or 100. 

IMO it should not go beyond 120, 140 is beyond pushing it. I can't find the article, but Google did some research and found that breaking after 80 or 100 was a tipping point. I forget the details but lines over 100 were bad, required more effort to understand, more bugs, etc.

So, any way we can walk 140 back to 120 or 100?

**Comment by ron-murhammer** [comment]
I prefer the longer length. I'm guessing the research is around if you have lines longer than 100 than you should try to refactor them. While true, in most cases people just let the line wrap which in my opinion is worse than a single long line. So I'd rather have a longer width than have lots of wrapping lines.

**Comment by veqryn** [comment]
This is part of the reason I changed the "join lines" to false.
You can make it shorter.  If you can fit a complete thought in 80 or less characters, good for you, I like that!
I think we should aim for 80-120 as the maximum for new code we write. 

BUT I would prefer to have the option to wrap the code the way I want to wrap it.  I hate when a formatter starts wrapping my code for me in an ugly/unreadable way, and I can't wrap it in a more sensible way because it is 81 characters long.

**Comment by DanVanAtta** [comment]
The "join lines" not being set I think is very good. Often in comments you want short lines.

The 140 line length causes me to have to scroll right. The scroll to right is *really* nice to avoid, makes it more efficient to read code. It looks like I can almost get 130 characters without need to scroll on my screen if I really squeeze things around.

So for me the compelling reasons of 120 are:
- it can likely avoid people from having to scroll right, which is probably the other benefit, perhaps the main one from the article. Consider how much easier it is to read code when you always only need to scroll down and not also scroll left and right.
- the length applies to comment text as well. To read a long javadoc comment i have to scroll left and right after every line, this is annoying.
- 120 characters is still a pretty long line IMO.

My arm can be twisted for 130, that would help me compared to 140, but I would prefer to see 120 if possible as a compromise between the 100 max suggested and 140 initial.

**Comment by DanVanAtta** [comment]
Quite a number of things:
- 2 space from 4 space indent has bought us a lot of space, 140 characters of code is 10 to 20 characters more code than it used to be.
- When doing the mass formatting, it looks it is better to tell it to re-wrap lines. 
- Once the formatter is committed, we do not want it to re-wrap line.

I was looking at different lengths and found going shorter wrapped weirdly. I noticed though that sometimes I had fewer lines. That means this prior mass formatting caused some weird wrappings.
- mass re-formatted code looks better with re-wrap on
- I realize that I often look at code in terminals, I'm also going to soon code a lot on a small portable laptop. 140 lines causes me a lot of horizontal scrolling. I would like very much to avoid all this scrolling.

- turns out most long lines are not comments and strings (as I would have expected), but are strings, method signatures with lots of parameters, and calls to those methods. So by going shorter with re-wrap we're mostly talking about whether we show method name plus two parameters on the first line with two more parameters on the next line, or do we show method name and one parameter on the first line and the other three parameters on the next line.

My request/recommendation:
- reformat with force re-wrap, go down to 120. At 120 very few lines required me to scroll left and right, it looked perfect. The choice where the formatter chose to wrap lines was often really good.  It also fixed some other odd wrappings from before where force re-wrap was not on:
  --  re-wrap @120,  you gain 1500 lines ,
  -- @125 you gain 900, 
  -- @130 you gain only 400 lines,
  -- @140 you lose 750 lines
- From the number of new lines from 140 to 120, the numbers tell me that we do not have *that* many lines that are between 120 and 140 and are impacted (over 140 and they are wrapped anyways). I'll point out too that wrapping a 180 charcter line at 140 is not as good as 120, I'd rather 120 + 60 rather than 140 + 40 characters. But also, these numbers say going to 130 at least is probably a no-brainer. I though would really like 120 


 

- If you're curious, i ran some numbers on how many lines we gain or lose at different line lengths:


dan@dan-desktop01:~/work/triplea$ git diff . | grep "^+" | wc -l
2977
dan@dan-desktop01:~/work/triplea$ git diff . | grep "^-" | wc -l
3746



- Okay, so with force re-wrap, I say go down to 120. At 120, the diff showed almost all lines fitting easily onto a terminal window. This is perfect.

But... 


dan@dan-desktop01:~/work/triplea$ git diff . | grep "^+" | wc -l
12941
dan@dan-desktop01:~/work/triplea$ git diff . | grep "^-" | wc -l
10610

dan@dan-desktop01:~/work/triplea$ git diff . | grep "^+" | wc -l
10430
dan@dan-desktop01:~/work/triplea$ git diff . | grep "^-" | wc -l
9194

dan@dan-desktop01:~/work/triplea$ git diff . | grep "^+" | wc -l
8028
dan@dan-desktop01:~/work/triplea$ git diff . | grep "^-" | wc -l
7607

**Comment by veqryn** [comment]
So, to condense what you want:
1. Reformat with join-lines=true and max-length=120
2. Put join-lines back to false
Is that what you meant by re-wrap?

I don't know how you can't fit 140 on you screen...

**Comment by DanVanAtta** [comment]
Yes.

I'm a bit surprised I can't get 140 to fit in my ideal case, eclipse, widescreen desktop computer. There's quite a few non-ideal cases where 120 will help: Terminal windows, git hub side by side code reviews, small laptop. 

To make it clear what the weird formatting is that can happen without join lines (I found this slightly interesting to realize), if you have two lines that look like this:
`public void foo( Object bar1, Object bar2,`
`  Object bar3) {`
And now let's say the first line is too long, then it would only wrap the line that was too long, and it gets odd looking:
`public void foo( Object bar1, 
   `Object bar2,`
  ` Object bar3) {`

Much nicer if it wraps it like this:
`public void foo( Object bar1, 
   `Object bar2, Object bar3) {`

**Comment by DanVanAtta** [comment]
Closing. @veqryn can submit a PR with the updates if desired. If we want to mass reformat again we can bring it up a-fresh. As is - we've now discussed this issue to death and have a number of other things to deal with.

We should can celebrate that we actually got rid of that old cold format!   :)
We also got a number of improvements with the clean, notably I really like having @Override everywhere now =D

**Comment by veqryn** [comment]
My killing of useless comment blocks has introduced a need to reformat again.
I will look into tomorrow just how long 140 vs 130 vs 120 lines are on my screen, and do that tomorrow sometime.

**Comment by DanVanAtta** [comment]
Do pls consider the other tools that are used to look at code beyond your IDE. Notably code diffs on github or reviewable.io, code diffs from git history (for me that is often on a terminal window and not eclipse)

130 looked to be a very clear point of diminishing returns. 120 I think is an okay compromise. IMO google has it right to suggest 100 as a max. Thanks for considering the shorter lines.

**Comment by veqryn** [comment]
120 line length it is.
almost all the code review tools look terrible at greater than this.
