### ISSUE TITLE
Request displaying of unit fuel usage when using fuel

### ISSUE THREAD

**Issue by FrostionAAA** [triplea-game/triplea#1804]
I know that not many maps use fuel. But if more maps are to experiment with this it might be a good idea to support the fuel feature a bit more. Or food supplies or whatever “fuel” units need.

Right now when units use fuel there is no way of knowing how much fuel is available, unless the player opens up the economy tab when moving units around. And this leads to the player being constantly forced to swap between the Action and Economy tabs. It would be nice to have an easy overview and since fuel is a movement thing, I would suggest it displayed when any moving of fuel-using units take place.

Here is what I propose, and I have no idea how hard this would be to implement, and this red text should of course only be displayed for units consuming fuel and be the fuel type for the specific unit. In this mockup setting the player has 26 fuel left to use, so first move leaves the player with 25, the next 24:

![unavngivet1](https://cloud.githubusercontent.com/assets/15268177/26761457/2362851a-4930-11e7-9be7-c8d1049b7017.png)

![unavngivet](https://cloud.githubusercontent.com/assets/15268177/26761461/2c49afaa-4930-11e7-8741-de34b5765145.png)

**Comment by FrostionAAA** [comment]
Just noticed the older "Enhance Fuel Movement request". https://github.com/triplea-game/triplea/issues/1310 Please merge :-P

**Comment by ron-murhammer** [comment]
@FrostionAAA Move your post to #1310 so closing this in favor of that.
