### ISSUE TITLE
Attack 0 Units Destroyed End Combat Round When Defending (1.9.0.0.4520)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#1809]
This is a major bug (regression), that I tested in TripleA_1.9.0.0.4520, but it is not present in TripleA_1.9.0.0.3627.
For example, if you attack a stack of Fort units only, in 270BC, they are automatically removed end round:
[BUG_20170605_270BC.zip](https://github.com/triplea-game/triplea/files/1050897/BUG_20170605_270BC.zip)

I had this bug also in my 270BC 40% (someone I was playing against noticed it), where the psilos alone are automatically killed end combat round when defending, and they are att 0, def 1, mov 1 land units. You can see the same in Lord of the Rings, if you attack a stack of hobbits only.

Is this an unintended consequence of trying to have def 0 units killed end combat round? Is this related to v5 AA Guns?

p.s.: It is not a big deal for me to zip, but I believe being unable to directly upload savegames is a substantial deficit for this repository, to function as the only bug report hub for all users (at least, it doesn't allow me to do so, thus I zipped the savegame; a thing I would never do, otherwise), as uploading the savegame with the bug is very important, beside reporting it. I can also tell you that very very few people report the bugs they encounter, even when prompted by a mod to do so, and linked to this repository.

**Comment by ron-murhammer** [comment]
@Cernelius What was the v5 AA Guns change you reference? Do you know what issue or PR that was?

**Comment by Cernelius** [comment]
Sorry, haven't followed here in a while (and I'm still not reading any but few exceptions); I was just guessing, as I'm not aware of anything else in the regular rules that might be related to having land units being killed like that; or maybe you decided to extend the v3 transports somewhat to land too? Duno.
Sorry, that was just a wild guess, nevermind me; maybe this bug has nothing to do with any rules.
Definitely, hobbits etc. are not supposed to all die if alone.
I just tested, it happens to WAW bunkers too. Just send 4 infantries to attack Switzerland round 1, and you'll see...
Definitely this is a major bug / regression for a lot of important maps.

**Comment by ron-murhammer** [comment]
@Cernelius This should be resolved in the latest pre-release now. The bug was introduced in #1646 with changes trying to minimize unnecessary prompts for battles.

**Comment by Cernelius** [comment]
Tested TripleA_1.9.0.0.4547 and confirm that this can be closed, for me.

My guess was that, for example, in v5, I see that if I attack a stack of 4 aaGun with 1 infantry, they all die immediately, both in .3627 and .4547. So, I was guessing if this bug was from that rule overboarding, as I'm not aware of something else supposed to autokill land units that are able to take hits (selected as casualties).
So, instead, it was something not related to that case, but a different matter?

**Comment by simon33-2** [comment]
@Cernelius Seems that the updates to the change resulted in the code looking at the attack power for the defenders, unfortunately.
