### ISSUE TITLE
Improve triplea_maps.yaml validation

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#1818]
While creating validation scripts for the website I ran into a couple issues with the triplea_maps.yaml file.
Because the map pages are generated based off this file invalid html and invalid links are easily introduced by the tripleabuilderbot.
In order to avoid that, we'd need to test validate the triplea_maps.yaml file more strictly.
This includes:
 - Checking if the value of `url` is a valid URL
 - Checking if the value of `img` is a valid URL
 - Checking if tha value of `description` contains valid HTML

By "valid URL" I mean a URL that returns a 200 status code when being requested.
By "valid HTML" I mean valid HTML 5, backwards compatible to HTML 4.01 because of swing.
"valid HTML" means:
 - Balanced tags, e.g. every tag must be closed in the correct order
 - valid characters, e.g. special chars like `&`, `<`, `>`, etc. must be repalced with `&amp;`, `&lt;`, `&gt;`, etc.
 - valid links. If the description contains `img` or `a` tags they need to exist just like the values of `url` and `img`

**Comment by ssoloff** [comment]
"Checking if the value of `img` is a valid URL" is addressed by #1818.

**Comment by ssoloff** [comment]
"Checking if the value of `url` is a valid URL" is addressed by #1856.
