### ISSUE TITLE
Potential Upcoming lobby updates - no screens GUI and use a prop file instead of command line arg

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1819]
Two potential updates I'm considering and looking at:
- remove GUI support for lobby. Now that we run the lobby as a linux service, not in a screen session, we no longer use the GUI part of the lobby. 
- instead of parsing command line args, I think it may be a good bit simpler to read a properties file. 

Mainly would like get early feedback on these ideas, I hope to start soon on them - thanks in advance.

**Comment by DanVanAtta** [comment]
Heh, turns out most of the UI code was already removed in: ce190b316518a493e20b8d589fa74b07854bce7c

This branch cleans up a small loose end from that removal: https://github.com/triplea-game/triplea/pull/1820

So now mainly looking at/discussing the possibility of using a lobby props file.

**Comment by ssoloff** [comment]
I have no issues with a properties file because our existing command line options already read like a properties file. :smile:

Note that we'll still need to support command line arguments, in general, in light of how the feature described in #1783 works.

**Comment by RoiEXLab** [comment]
I agree!
Especially the lobby should rely on `.properties` because we only have one instance of it.
Not sure about bots though. We still need to be able to pass port and name via the command line, as we are spawning multiple processes, and it would be a real pain to modify the properties file just before launching a bot!

**Comment by ssoloff** [comment]
@RoiEXLab, I was going to add this comment to #1783, but it may make more sense here...  Depending on how much existing command line arg code gets ripped out with @DanVanAtta's change, this may be an opportunity to introduce a real command line arg parser (e.g. Apache Commons CLI) so you have more flexibility in how you pass your download URL(s) (and the bot params you mentioned above) on the command line.

**Comment by RoiEXLab** [comment]
I used commons-cli earlier(, and yesterday to write my link-checker tool ^^)
And it works very well and is pretty easy-to use.
I'd definitely appreciate such a change!
