### ISSUE TITLE
UI options for income adjustment

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1836]
I'd like to discuss the UX of income % adjustment. At the moment I'm a bit concerned we are showing too much information on a prominent screen.

![income_shows_all_the_time](https://user-images.githubusercontent.com/12397753/26916179-1a06b346-4bde-11e7-8331-d842558ec55b.png)

In this location, it would seem that we would update the income percentage nearly every game. The option is presented to us whenever we play any game, if we do not regularly update it, why show it every time we host a game?  I personally do not think the income % option would be used that often as a percentage of total games, I suspect less often than bid.

A few suggestions I would propose:
- put the income % with the bid options
- do the above, but also take Cernel's suggestion and show the income % when an ai is selected:  https://forums.triplea-game.org/topic/113/ai-bonus-settings-revamp/43?page=3 . I think I like this the most, perhaps for AI games we woudl very often want to adjust income percentage.
- Hide the income column behind a "+" button. When clicked then show the column. It won't take players long to discover this, and they'll then know how to access it when they want it.

**Comment by DanVanAtta** [comment]
NB and FWIW - the income percentage column does look quite clean! But again, my concern is that this is a control/option which seems like we would use it all the time, and I'm not sure that would be the case. This then makes me think it'll be UI clutter more of the time than not.

**Comment by DanVanAtta** [comment]
Brainstorming, maybe we could move 'bid' options from where they are to have a similar treatment. For example, in 'map options' we could have a radio buttion 'allow income handicap', and then that reveals the income percentage and bid amount fields. In that mix, starting income would be a logical addition.

**Comment by DanVanAtta** [comment]
After sleeping on this, it might be I just need to get used to the change. Having a balancing factor on player selection is relatively common in other games. I'm curious if there are any updates we could think of that would be worth doing, in the end this would be far from the worst thing for me to learn to live with (as mentioned, does look clean)

**Comment by ron-murhammer** [comment]
The plan is to do something like choice 3: "Hide the income column behind a "+" button. When clicked then show the column. It won't take players long to discover this, and they'll then know how to access it when they want it." I'd prefer to track this in just one place (the forum thread) so closing this issue.
