### ISSUE TITLE
Checkstyle: Expand abbreviation "AA" to "AntiAir" or convert to "Aa"?

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/triplea#1847]
Building on the discussion in #1659...

While fixing Checkstyle abbreviation violations recently, I've been expanding `AA` to `AntiAir` instead of just converting it to `Aa` because it looked strange to me.  However, it was [pointed out](https://github.com/triplea-game/triplea/pull/1846#issuecomment-307275430) that `AA` is a common abbreviation throughout the codebase and may not be appropriate for expansion to `AntiAir`.

Any thoughts on what `AA` should be replaced with in type, member, and variable names?

* `Aa`
* `AntiAir`
* something else?

**Comment by ssoloff** [comment]
I have one pro and con for each (they just mirror each other):

* `Aa`
    * Pro: Easier to replace (no reformatting necessary)
    * Con: Looks a bit strange

* `AntiAir`
    * Pro: Reads better with only a small increase in verbosity
    * Con: Harder to replace (need to reformat lines that exceed the length limit after replacement)

**Comment by ssoloff** [comment]
Copying @DanVanAtta's [comment](https://github.com/triplea-game/triplea/pull/1846#issuecomment-307280896) from #1846:

> IMO `Aa` in class names over `AntiAir` pretty easily. Though for variable names, it is marginal IMO. I'm quite okay with `Aa`, but am not opposed `antiAir` either.

**Comment by ron-murhammer** [comment]
My vote is for Aa.

**Comment by simon33-2** [comment]
AntiAir makes hitting the 120 character line limit more likely. Still, I'd be happy with Aa.

**Comment by RoiEXLab** [comment]
Isn't the abbreviation stading for AntiAircraft?
In this case it would be even "harder" to replace those kind of strings...
But I agree, Aa looks weird

**Comment by ssoloff** [comment]
Good point about `AntiAircraft`, @RoiEXLab.

Thanks for the feedback, everyone.  It looks like `Aa` wins.  I will update #1846 and then submit a follow-up PR replacing all the occurrences of `AntiAir` I've introduced recently with `Aa`.
