### ISSUE TITLE
Official migration to a feature backlog list?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1851]
Jumping straight to it, two objectives in this issue:
1. Identify where we will track feature request items, and agree to this
2. Migrate our backlog items there (then close this issue down)

Context:
When tripleA was hosted in sourceforge, feature requests were tracked here:
- https://sourceforge.net/p/triplea/feature-requests/
- http://tripleadev.1671093.n2.nabble.com/Development-f1671667.html

With the github move we've been tracking feature requests here:
- https://github.com/triplea-game/triplea/labels/type%3A%20feature%20request

Over time it was pretty clear these issues were jamming the ticket queue and were not as helpful as they could be. We suggested a process to open and discuss features as issues, and then link to them in a feature backlog list  (and close the issue down until it is picked up). That list is in wiki here:
- https://github.com/triplea-game/triplea/wiki/Feature-Back-Log

My recommendation:
Open to feedback here, but FWIW I think we should formalize the backlog list idea and go for it. I like the flexibility where we can link and close down source forge tickets even. That solves a long standing consolidation problem. A single consolidated feature request list IMO would be very useful and would have benefits to our bug tracking.

**Comment by ron-murhammer** [comment]
@DanVanAtta I'm fine if we want to use the wiki list instead of just leaving them open and tagged as a feature in the issues queue.

In regards to SF, I kind of consider those issues dead at this point. I think its more effort than its worth to migrate and filter through them. I'd rather start fresh and have folks open new issues as such a large portion of the SF issues are outdated.

**Comment by DanVanAtta** [comment]
Okay, any good ideas we see in SF we can raise as a new issue and go through the latest feature request process. I took a pass at closing out feature requests and adding to the wiki: https://github.com/triplea-game/triplea/wiki/Feature-Back-Log.

Still more issues to move to the backlog, and a couple are not ready for backlog (which i think confirms this is a good move)

Also to-do here is update our process documentation to make this clear, that we are doing this.

**Comment by ron-murhammer** [comment]
We've decided to move all feature requests to the forum for better community visibility and discussion: https://forums.triplea-game.org/topic/182/guidelines-and-feature-request-list
