### ISSUE TITLE
Introducing new tool for evaluation - CodeCov

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1854]
Dashboard is here: https://codecov.io/gh/triplea-game/triplea

It also looks like we'll get commentary on PRs about coverage reports.  CodeCov was enabled here: https://github.com/triplea-game/triplea/pull/1852

FWIW - it required a `CODECOV_TOKEN` added here: https://travis-ci.org/triplea-game/triplea/settings (done).  Token value was obtained from the codecov.io website

Aggregating here any feedback/discussion about this tool. In the docs I saw it does not fail builds (seems okay). The setup was pretty minimal and is done.

**Comment by RoiEXLab** [comment]
@DanVanAtta I'm willing to give it a shot, but something seems not to be working correctly...
Somehow the commentary always consists out of N/A values ([example](https://github.com/triplea-game/triplea/pull/1783#issuecomment-307525234))

**Comment by DanVanAtta** [comment]
Looks like there is no comparison for the coverage report. Perhaps we need to send a coverage report after we merge to master.

**Comment by ssoloff** [comment]
@DanVanAtta Just in case you don't get notifications for closed issues, I left you some feedback in #1852.

At this stage, I don't think code coverage should fail the build.  When we're closer to 80% instead of 20%, then we can set a threshold. :smile:

**Comment by DanVanAtta** [comment]
@RoiEXLab turns out I configured travis with the token for my fork and not the triplea-game org repo. I updated that, and it looks like it is working more as expected now :)

**Comment by DanVanAtta** [comment]
>  I don't think code coverage should fail the build.
@ssoloff  IIRC from the docs correctly, I don't think it will.

**Comment by ssoloff** [comment]
@DanVanAtta Sorry, what I meant to say was that I **agree** coverage shouldn't fail the build at this point. 😊

**Comment by DanVanAtta** [comment]
Wow, with this working correctly, it is pretty great:
- single number of code coverage change
- head map
- individual class listing

:confetti_ball: 
:dancer: 

![looks_great](https://user-images.githubusercontent.com/12397753/27001354-f72d3f20-4d7c-11e7-8db3-4f0134051443.png)

**Comment by ssoloff** [comment]
I've noticed a few times now that Codecov reports changes in hits/partials for PRs that don't actually contain code changes.  For example, the [change report](https://codecov.io/gh/triplea-game/triplea/pull/1870/changes) for #1870 (which only modified `README.md`) shows coverage changes in five files.  I'm not sure if we have some non-deterministic tests or the code path changes are due to environmental factors.

**Comment by DanVanAtta** [comment]
Good spot. My first guess would be our tests, though at same time Codecov does not seem to be that old of a tool.

**Comment by ron-murhammer** [comment]
@DanVanAtta This is pretty much causing all the PRs to show as failing checks. Can we alter these checks to just be informational or lower requirements?

**Comment by RoiEXLab** [comment]
Closing, has been working well for the past months
