### ISSUE TITLE
Switch tab ordering on map download page.

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1864]
From: https://github.com/triplea-game/triplea/issues/1468#issuecomment-273809095
> As off topic, the other thing that I find annoying is that the "Available / Update / Installed" are subcategories of "High Quality / Good Quality" etc.. It should be the other way around: if you want to see the "Update" maps, you should not have to click on "Update" each time you change the Quality categories, but it would be better if you select "Update", and then you can move between "High Quality", "Good Quality" etc., while remaining on "Update".

Summary of task: update download maps window so that 'install/update/remove' are the top level tabs, instead of the quality levels being top level.

**Comment by prastle** [comment]
Yes very annoying having to switch to update in each.

**Comment by ron-murhammer** [comment]
Yeah, I'd agree with this as well.
