### ISSUE TITLE
v5-1942 air battles not supported

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#1867]
The optional interception rule in v5 (aka 42.2) is that fighters and bombers attack on a one, the defending interceptors are removed and remaining interceptors roll on a two.

Not the smartest rule out of the tools in the toolshed but those are the official rules. This is not possible to implement in Triplea-A at present. I propose an option in the UnitAttachment for the fighter to allow surprise strike in the air battle, similar to subs. The alternative would be a map property which has the advantage it can be made editable.

**Comment by DanVanAtta** [comment]
Closing, unable to action this.

I'd like to see this picked up in forums and fleshed out more:
- which maps are missing this potential rule?
- could use a decision on implementation details, the exact game mechanics, and some sample XML to be implemented.
