### ISSUE TITLE
Make TripleA java-9 ready

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#1882]
I managed to get gradle compiling TripleA using the lates java 9 jdk-preview:

Current gradle output when compiling against java 9:
[Gist](https://gist.github.com/RoiEXLab/bcc46a53c62958a4bb472a0c4b3f5e8f#file-java9)
Output when compiling with the latest java 9 jdk with java 8 source setting:
[Gist](https://gist.github.com/RoiEXLab/bcc46a53c62958a4bb472a0c4b3f5e8f#file-java9-8)

Some errors are java 9 specific (due to the new module system), we don't need to worry about them right now, but most errors can be "fixed" while still being able to compile TripleA with java 8.
I will create a PR adressing a couple of those issues...
(I will also update the log to representr the state of current master)

[Java 9 Countdown](http://www.java9countdown.xyz/)

EDIT: Updated log to reflect the state after #1883 gets merged

**Comment by ron-murhammer** [comment]
@RoiEXLab Good idea. Though also want to make it clear we would probably wait to actually upgrade to Java 9 til it has been out for say a year or so.

**Comment by RoiEXLab** [comment]
@ron-murhammer Of course!
I didn't meant to upgrade to java 9 straight ahead either, especially because current java 9 support is **** on intellij and eclipse (I tried both, none of them worked)

**Comment by RoiEXLab** [comment]
@ron-murhammer @ssoloff 
Any objections if we use the java 9 compiler with java 8 source and target setting once java 9 is fully released?
I managed to get compilation with gradle working: https://travis-ci.org/RoiEXLab/triplea/builds/250781163

**Comment by ssoloff** [comment]
@RoiEXLab If you do this, you'll probably want to investigate using a matrix build or something similar on Travis.  Regardless of whether we build with JDK 8 or 9, we'll want to run the unit and integration tests on both platforms as long as they're supported by TripleA.

**Comment by ron-murhammer** [comment]
Yeah, I think the key is we need to keep JDK 8 compatibility for a while.
