### ISSUE TITLE
Play by Website: Is it still used?

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/triplea#1885]
While I was evaluating the security of PBEM/PBF games, I came across a type of game I was unaware of: play-by-website (also called play-by-micro-website).  The only implementation of this type of game is [`TripleAWebPoster`](https://github.com/triplea-game/triplea/blob/master/src/main/java/games/strategy/engine/pbem/TripleAWebPoster.java).  It looks like all the code is still in place, but I can't find a way to select and configure it via the UI.

Looking through the history, it appears it was commented out from the UI in eef7d0a, but the commit comment seems to be totally unrelated to this feature.  Then the commented-out code was finally removed in 3a87026 during a routine clean up.

This feature might have the same vulnerability described in #1884 because it's possible the user could enter credentials into a host URL, which appears to be stored unencrypted in `local.cache`.  However, if the feature is considered dead, it'll be much easier to remove it rather than fix it. :smile:

**Comment by DanVanAtta** [comment]
I would suspect not used. I thought it was related to PBF, but could easily be an unfinished feature.

**Comment by ron-murhammer** [comment]
I'm guessing this was an unfinished feature.

@veqryn Any insight into this?

**Comment by veqryn** [comment]
This was going to be a more-integrated way to play the game than play-by-forum.
Perhaps contact the guy who wrote it and see if he is still interested in developing it further, with the new/engaged team?
If not, maybe get rid of it to focus on more immediate priorities, unless you want to explore this feature...

**Comment by ssoloff** [comment]
The original author appears to be "weigo" according to 4f96c42.  That commit is from the SF days, but there's no current SF user with that name.  There's a current GitHub user with that name, but it's unclear if they are the same person.

**Comment by ssoloff** [comment]
Bumping to see if anyone a) knows how to contact "weigo", and b) has an opinion on whether or not to pursue re-introducing this feature.  The fix for #1884 is nearly complete, and I'd like to know if I need to extend it to cover this play option, as well.

**Comment by veqryn** [comment]
I gave weigo's email to Ron and Dan.  Ssoloff, I don't have your email. Can you send to me?

**Comment by ron-murhammer** [comment]
@ssoloff Given that it was 4 years ago weigo last did anything regarding this, you can just remove it.

**Comment by ssoloff** [comment]
@veqryn I sent an email to the address you used in your most recent commit (556a149).  Please advise if that's no longer active.

**Comment by veqryn** [comment]
I did not receive anything.
Can you send to `veqryn`
a t
(hotmail)
[that is a Q in my name, not a G, fyi because some people mix it up]

**Comment by ssoloff** [comment]
@veqryn Confirmed that that was the addy I used.  I just resent.  Possibly it's going to spam?  If you still don't receive it, you can use the email listed in any of my commits.

**Comment by veqryn** [comment]
Found both of them. Not sure if it came in late or if I missed it the first because it looked like it came from github.  Thx

**Comment by ssoloff** [comment]
@ron-murhammer @DanVanAtta Should be able to close this issue now that #2001 has been merged.
