### ISSUE TITLE
Use `super` explicitly when we can?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1896]
I would like to discuss and suggest we update our code convention to use the `super` keyword when possible. I personally like it because it reduces the search time for impacted methods to effectively zero for me. Without the `super` keyword, if you see a method call, it can be one of three things: a local method, a static method (via static import), or a method on the super class. Prefixing with `super` eliminates two of those options to just one. This helps the default case IMO as well be narrowing down the three options to two. I'm curious what other people think on this topic?

The prevailing reason I think to not include the  'super' keyword is that it is not necessary - and we should not include things that are not necessary. IMO this limited case to explicitly include `super` is useful enough to be worth it. `super` is even a bit of a design smell IMO. From that perspective using it explicitly helps us label and find these potential design problems (a goal could be to drive our usage of `super` to zero or at least minimize it)

**Comment by RoiEXLab** [comment]
I personally always use shortcuts to get the method declaration.
On eclipse it's F3 and using intellij it's F4 I believe.
I like keeping the code short if possible

**Comment by DanVanAtta** [comment]
The actual shortcut key can vary, but it is not the point. The point is to allow the reader assumptions so we don't have to do IDE assisted method lookup of every method we see to know where it is defined. The extra verbosity of the `super` keyword I think really helps. Since a `super` call is a design smell to begin with, TBH I think we can keep the code short by fixing our design and removing the `super` usages altogether. Otherwise the explicit `super` callout I think is useful to indicate the potential design problem.

**Comment by ron-murhammer** [comment]
Not really a fan of putting super on all relevant method calls. I don't think it adds enough value for the extra verbosity.

**Comment by DanVanAtta** [comment]
It does not seem you guys have the search problem. I wonder why the difference. Recently, I spent a good fraction of a minute looking for a method in a code review to eventually find it was a super call. In an IDE it would be less time likely since I would probably have jumped to tooling right away, but in general I do prefer when code structure is used first as the primary guide of where code would be located rather than relying on tooling foremost.

Does not seem like I'll get a majority opinion here, thanks for the feedback.
