### ISSUE TITLE
html in javadocs

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1900]
HTML in javadocs and requiring them is started to annoy me a bit (minor readability issue and incurs a small overhead).  I'd like to bring this up for a vote in case others would also like to see plain text in the javadocs.

Issue: html in javadocs. 
For discussion/vote: should we keep html in javadoc, or stick to plain text for javadocs?

Simple example taken from the code:
```
  /**
   * allow other nodes to see the data.
   *
   * <p>
   * You can only unlock data that was locked by the same instance of the Vault
   * </p>
   *
   * @param id
   *        - the vault id to unlock
   */
```

vs proposed:

```
  /**
   * allow other nodes to see the data.
   *
   * You can only unlock data that was locked by the same instance of the Vault
   *
   * @param id
   *        - the vault id to unlock
   */
```

This would require a checkstyle change primarily. Not proposing a mass update, but let's stop the html in javadocs practice going forward to eliminate the overhead. We would update opportunistically going forward when we can.

Some reasons I'd give to remove html from javadocs:
- We don't generate javadocs. They are only read from the context of in-code (IDE), terminal (or other github tool), or github web UI. In any case the HTML markup is more noise than helpful.
- It's an overhead to wrap block comments in HTML compared to not doing it. Let's remove the small overhead and checkstyle policing - one less thing to worry about (and prettier comments)
- It's more human readable to not have HTML in commentary. 
- Less distracting, it's odd to worry about calling out a line break while documenting how a high level API functions.

Appreciate the feedback and vote between:
- [ ] HTML in javadocs
- [ ] plain text in javadocs

**Comment by RoiEXLab** [comment]
I like to avoid html in javadocs, but I like to use `{@link SomeClass}` to reference a class in the javadoc which makes it possible to click on it and view the source, I believe a similar thing is possible to format code, but it's much shorter

**Comment by ssoloff** [comment]
I use Eclipse's Content Assist about 50% of the time when I want to read the Javadocs for a method outside the current file.  Unfortunately, Content Assist is affected by lack of HTML the same way Javadoc would be.  For the method you chose, here is an example with HTML:

![with-html](https://user-images.githubusercontent.com/4826349/27168557-2d90bb32-5174-11e7-89b0-d5820d0ceb93.png)

and without:

![without-html](https://user-images.githubusercontent.com/4826349/27168564-35d6cc14-5174-11e7-8907-97838178ee2b.png)

You can imagine that for a much longer Javadoc, including ones that have lists or code, it becomes difficult to read because everything gets collapsed into a single paragraph.

With that, I'm a soft "HTML in javadocs", but I could be convinced to re-build my muscle memory to just <kbd>F3</kbd> to open targets in other files and read the Javadocs as text.

**Comment by DanVanAtta** [comment]
Some additional options perhaps:
-  Double line break in javadoc. Does that create the intended line breaks in the rendered HTML? IMO this is not great, easy to forget, but for breaking up blocks of text it might be okay.
-  I personally could be convinced to allow (and only allow) `<br />` in javadocs. Though I would still prefer none.

**Comment by ssoloff** [comment]
* Double line break doesn't change how Content Assist renders the Javadoc--it's still one big paragraph.
* `<br />` adds the line break but the "paragraphs" run together.  That is, there's no vertical space between paragraphs.

As I said above, I'm soft on the HTML option.  I'd rather have clean text-only Javadocs than use some convoluted intermediate solution with issues of its own, as you pointed out. :smile:

**Comment by ron-murhammer** [comment]
I kind of go either way on this one as I probably most look at the source so without HTML is easier to read but sometimes use IDE assist which as @ssoloff points out uses the HTML.

**Comment by DanVanAtta** [comment]
Looking at the screenshots from a fresh, I do prefer the non-html one (not sure how much is bias, but at first I thought they were my screenshots until I scrolled enough to see it was not the OP).

For consideration, looking at the screenshots, and reflecting on my eclipse usage, the first sentence or two are most useful. It's even more rare to hit the hot key to expand the javadoc to full text. Do ya'll use that feature much, or when it comes to a length javadoc do you go to the source to read it there?

It does seem like the one beneficial case we are discussing is getting more marginal. I think the decision is leanign to keep it simple and no html in javadocs, but let's give it its due consideration.

**Comment by ssoloff** [comment]
> Do ya'll use that feature much, or when it comes to a length javadoc do you go to the source to read it there?

In Eclipse, it's not necessary to press <kbd>F2</kbd> to expand the Javadoc window when the comment is too long.  If you put your mouse over the pop-up and start scrolling with the mouse wheel, you can view the entire Javadoc.

**Comment by DanVanAtta** [comment]
Do you do that often @ssoloff , or do you jump to the source? When I used eclipse I typically did not mouse scroll wheel in favor of keeping my hands on the keyboard.

Looking at a diff on github recently, was reminded of this topic, a screenshot to consider:
![example](https://user-images.githubusercontent.com/12397753/27507364-7b508fcc-5882-11e7-9c5b-e8dfea127f8e.png)

If we drop HTML from comments, the annotation version of the same could be an exception and we keep it, or we could choose to use single or backticks.

**Comment by ssoloff** [comment]
Meh, I'd say I do it 25-50% of the time I use Content Assist.  I'm usually interested in method parameter pre-conditions, or knowing if a method can return `null`, or knowing what types of unchecked exceptions a method can throw.  Unfortunately, those items tend not to be immediately visible in the Content Assist window without some scrolling.

In your last proposal, it almost sounds as if you're suggesting using Markdown in Javadocs.  Interesting.  Do you know if that's common enough that there's tool support out there?  For example, a doclet that allows the javadoc tool to process Markdown?

**Comment by DanVanAtta** [comment]
I'm trying to write a javadoc and the checkstyle warnings for html line breaks is a bit distracting. It's geting in the way, I'm avoiding line breaks to avoid adding `<p>` tags, and then when actually breaking, it's cumbersome to worry about proper `<p>` placement. What is really weirding me out though is I typically start a javadoc with a sentence or paragraph, standard. Though then the next line break and paragraph are surrounded by `<p>` tags, but we don't do that for the first paragraph? This can be noted in previous screenshots/examples. IMHO this is a sign of the death by a thousand of papercuts syndrome. For a simple javadoc there are a number of small ambiguous formatting decisions that need to be made.

I propose we do this:
- remove requirement for any html in javadocs, slowly work to remove it
- keep `<code><pre>` where we need it, last I check that is needed to help keep IDE's from comment formatting code blocks.
- use the `{@.. }` style annotation liberally as appropriate

@RoiEXLab I missed your comment about preference to use `{@.. }` style annotations. I agree, IIRC t those were even introduced to avoid html.

**Comment by ssoloff** [comment]
:+1:
