### ISSUE TITLE
Can open multiple download map windows

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1923]
IIRC, we fixed it so only one 'download maps window' could be opened.

On master I was able to click 'download maps' multiple times and get multiple new download map windows. Expected behavior is to have only one show up (and not be modal, and we do still have a bug where the window does not come to the foreground).

Task here: 
- if download maps window is already open, and 'download maps' button is clicked, either do nothing, or bring the open window to the foreground

**Comment by ron-murhammer** [comment]
Agree. Also +1 the download maps not coming to the foreground. That is one of the most annoying bugs that we have currently.

**Comment by RoiEXLab** [comment]
Closing via #2054
