### ISSUE TITLE
Tech jetPower Does Not Give +1 To Air Attack In WW2V3 (1.9.0.0.4975)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#1935]
In addition to the current abilities (giving +1 Attack for any isAir and non-isStrategicBomber units), the "jetPower" tech should also have airAttackBonus=1 (instead of current 0), when the property "WW2V3" is true (or whatever assures this tech working by v3 rules, in the game).

In "World War II v3 1941", when the optional "Raids May Be Preceeded By Air Battles" is selected, and you have Jet Power, the Air Attack value of your Fighters should increase by 1 (currently, it doesn't).

I also suggest to generally extend "jetPower" to give the same bonus both to regular att / def and air att / def, even in rulesets that don't have anything related as an official rule or option.

**Comment by Cernelius** [comment]
I want to clarify that this is an engine bug, not a map bug. Even though the games in the world_war_ii_v3 map can be customised to give the air attack bonus with the jetPower tech, this should be hardcoded and default in WW2V3 for that tech (in other maps, there may be the issue that you can't customise both the name and the behaviour of hardcoded techs).

**Comment by ron-murhammer** [comment]
@Cernelius Is this bug something introduced recently or something that has always been broken?

**Comment by Cernelius** [comment]
Tested now this problem existing in TripleA 1.8.0.9 as well, for "World War II v3 1941" (not a regression).
I cannot be sure, but I think this bug always existed, except that this behaviour may have existed as a bug only after the Air Battles Raids official option had been added and it had been clarified that Jet Power applies there too (just look at the latest FAQ / Errata for this game, not the rulebook).

**Comment by ron-murhammer** [comment]
@Cernelius Just made a PR to always add bonus air attack/defense along with the normal attack/defense bonus for jet power tech.
