### ISSUE TITLE
Can't recapture infrastructure

### ISSUE THREAD

**Issue by panguitch** [triplea-game/triplea#1952]
In testing recent game changes and their effect on Greyhawk Wars I've come across a new error. An infrastructure unit that used to be capturable and recapturable between two players now can be captured but not recaptured.

Example:

Here are two saved games (in zip) demonstrating the problem: [Recaptured bug.zip](https://github.com/triplea-game/triplea/files/1085965/Recaptured.bug.zip)

IuzRecaptured.tsvg is played on 1.9.0.0.3635. It shows Iuz moving its leader Iuz_the_Old (a factory unit of sorts) into a neutral territory. The battle is lost and Neutral captures Iuz_the_Old, triggering various notifications and production rule changes for Iuz. Round 2: Iuz conquers the neutral terriotry, recapturing Iuz_the_Old. All is right with the world.

FuryondyNotRecaptured.tsvg is played on 1.9.0.0.5043 and manifests this new problem. It shows Furyondy moving its leader Belvor_IV into a neutral territory. Battle is lost, Neutral captures Belvor_IV. Round 2: Furyondy conquers the neutral terriotry, but Belvor_IV is destroyed instead of recaptured. Sad Furyondy :(

These leader units are infrastructure/factories which also function as support units. They are destroyed when captured by other players, but not by Neutral or the originating player, which should be able to capture and recapture them back and forth.

This problem may be unique to Greyhawk Wars or to offensive infrastructure/support units. I tried it in Pact of Steel and there's no problem with those immobile/defensive factories or AA being captured and recaptured back and forth between Germany and Russia. 

I wonder if it has something to do with the fix @ron-murhammer made in response to another of my issues: https://github.com/triplea-game/triplea/pull/1827 since it was also related to infrastructure units with support attachments? Or is it caused by some other recent change?

**Comment by ron-murhammer** [comment]
The bug appears to be due to #1646

**Comment by ron-murhammer** [comment]
@panguitch This should now be fixed in the latest pre-release. Please test and confirm. Nice work spotting this as well!

**Comment by panguitch** [comment]
@ron-murhammer Yes, tested in 5060 and works great now. Thanks!
