### ISSUE TITLE
When restarting a game that was saved at the beginning of a prior round, last person to go gets double PUs

### ISSUE THREAD

**Issue by Grill-Meister** [triplea-game/triplea#1961]
When restarting a game that was saved at the beginning of a prior round, last person to go gets double PUs.   Steps to reproduce are as follows:

1. Play a map for a number of rounds.
2. Show the game history, right click on a round, and "Save the game at this point (BETA)"
3. Restart the saved game.
4. You'll see the person to go last get double-dose of PU's.  See attached.
![turn_complete](https://user-images.githubusercontent.com/21231960/27391194-470b55de-5671-11e7-9ff4-55d3272f5434.jpg)

**Comment by ron-murhammer** [comment]
@Grill-Meister Yeah, there are a significant number of issues with using the "Save the game at this point (BETA)" feature. Doubling PUs is one of them but lots of other sometimes funky behaviors such as if you save after combat moves they don't appear in the right hand panel so you can't undo them when you load back up. While this feature has been around for a while now, it truly still is a "BETA" feature. It would be good to collect up all the known bugs around this BETA feature in hopes of fixing them.

**Comment by Cernelius** [comment]
I'm almost sure that the income multiplication (extended to objectives too) is the only true bug of this feature, albeit I don't know what issues maps having a different last phase than end turn would have, if any.  

All other many issues are related to not taking a start turn history savegame while being at start turn, as instructed to.

Maybe the easiest way to solve this might be to have the history savegame option available only when you right click on a phase in history that is preceded by the phase of a different player (a start turn phase, normally) and you currently are at the start of the first phase of the latest player having a phase going on and having done no actions in it.

If the above would be possible (enforcing what is currently instructed), then I believe only this bug would need to be addressed, except for testing how it performs in the very few games not having endturn as the last phase.

I don't think that being able to take history savegames at different points than start turn would have much value. However, the fact that you have to be at start turn, not to have more bugs, is a bothersome limitation, making this feature hardly safely usable for common users, especially during live games.
