### ISSUE TITLE
Commit Access

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#1965]
@ssoloff @RoiEXLab I gave you both commit access given the quality and number of PRs you've both submitted and the lack of active committers we have. I don't have the bandwidth to continue to review and merge every PR and it seems Dan has been not quite as active recently.

My suggestion would be for you to review and merge PRs that primarily focus on low risk refactoring and minor UI changes to start. I would like to still review any functional changes to the game rules/logic and the AI.

Thanks for all your hard work.

**Comment by RoiEXLab** [comment]
Thanks! More than a year ago I joined this Project, has been a lot of fun so far!
I really appreciate this!

**Comment by ssoloff** [comment]
:+1: Thanks, @ron-murhammer.  I'm more than happy to keep helping out as time permits.
