### ISSUE TITLE
Latest version testing and regressions

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1974]
Overview:
Opening this issue to help get the latest version marked as a stable and then coordinate an upgrade. This is a difficult one because forced upgrades right now are bugged and would cause game freezes.

Problems identified:
- [ ] user account is not 'found' after logging in. Mods are not recognized, 'update account' to update email or password does not work. (I noticed that I was not a mod when logging in with the latest version).

Testing needed:
- [ ] PBEM
- [ ] PBF
- [ ] A couple AI vs AI games, make sure there are no errors over the course of the game.

Testing Completed:
- [ ] Lobby bot game, can connect and play through a combat round.

**Comment by ron-murhammer** [comment]
@DanVanAtta Any idea what's causing those lobby issues?

**Comment by DanVanAtta** [comment]
The updates to DBUser probably broke serialization somewhere. We might be able to fix it by updating in the new DB and not worry about fixing the regression in Derby.

**Comment by prastle** [comment]
tested .5157 i was able to login as a mod ill do an ai game

**Comment by prastle** [comment]
error log v3 41 hard ai vs hard ai

triplea.engine.version.bin:1.9
Jun 24, 2017 11:32:50 AM games.strategy.engine.chat.ChatController joinChat
INFO: Chatter:prastle (1) port:3300 ip:24.53.234.232 is joining chat:games.strategy.engine.framework.ui.ServerStartup.CHAT_NAME
host:45.79.144.53 port:3304
Loading map: iron_war, from: C:\Users\john\triplea\downloadedMaps\iron_war-master.zip
Loading resources from the following paths: [C:\Users\john\triplea\downloadedMaps\iron_war-master.zip, C:\Program Files\TripleA_1.9.0.0.5157\assets]
Loading map: world_war_ii_v3, from: C:\Users\john\triplea\downloadedMaps\world_war_ii_v3-master.zip
Loading resources from the following paths: [C:\Users\john\triplea\downloadedMaps\world_war_ii_v3-master.zip, C:\Program Files\TripleA_1.9.0.0.5157\assets]
Loading map: world_war_ii_v3, from: C:\Users\john\triplea\downloadedMaps\world_war_ii_v3-master.zip
Loading resources from the following paths: [C:\Users\john\triplea\downloadedMaps\world_war_ii_v3-master.zip, C:\Program Files\TripleA_1.9.0.0.5157\assets]
1 - Italians. strafing territory: Caucasus, alliedPlayer=Germans, maxWin%=100.0, maxAttackers=12, maxDefenders=11
7 - Japanese. strafing territory: Russia, alliedPlayer=Germans, maxWin%=100.0, maxAttackers=14, maxDefenders=13
8 - Japanese. strafing territory: Russia, alliedPlayer=Germans, maxWin%=100.0, maxAttackers=14, maxDefenders=14
15 - British. strafing territory: Western United States, alliedPlayer=Americans, maxWin%=100.0, maxAttackers=5, maxDefenders=3
21 - Germans. strafing territory: United Kingdom, alliedPlayer=Japanese, maxWin%=100.0, maxAttackers=10, maxDefenders=9
Game Player disconnection: Connection Lost
Game previously stopped, cannot stop again.Waiting on error latch timed out!


22 rnds hard ai beat allies total vict 18 vict cities

**Comment by ron-murhammer** [comment]
Log looks fine. I should probably remove that system.out for strafing. But no errors in 22 rnds :+1:

**Comment by DanVanAtta** [comment]
Closing:
- there are other more active discussions on this same topic
- we are formalizing a bit testing, this type of thing needs to be an ongoing process and not ad-hoc issues created every now and then.
