### ISSUE TITLE
Checkstyle for Class JavaDocs?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2004]
Proposal: require javadocs on class definitions and interfaces

I would like to use this issue to gather any feedback, commentary or objections to the proposal.

Some benefits I would highlight to having class level javadocs:
- a single class javadoc comment does good thing to design, forces an author to state what their class represents and what it is for.
- Helps avoid code bloat in the sense it becomes more obvious when new functionality is being added to classes that are not a good fit.
- Reader of code benefits quite a bit, no guessing or deriving the purpose of a class, you are told directly in a comment.

Looking around, I do see a good number of class javadocs, this looks to mostly be existing practice already.

This is following up on a proposal to remove javadoc requirement for public constructors (https://github.com/triplea-game/triplea/pull/1985)

For reference, the checkstyle code to add this would be something like:
``` 
        <module name="AtclauseOrder">
            <property name="tagOrder" value="@param, @return, @throws, @deprecated"/>
            <property name="target" value="CLASS_DEF, INTERFACE_DEF, ENUM_DEF, METHOD_DEF, CTOR_DEF, VARIABLE_DEF"/>
        </module>
+        <module name="JavadocType" />
        <module name="JavadocMethod">
```

**Comment by ssoloff** [comment]
The only suggestion I have is to consider applying this rule to just public types at first (the default scope is `private`).  We can always expand the scope later, if needed.

**Comment by DanVanAtta** [comment]
Good consideration, I agree to start with public scope.

**Comment by ron-murhammer** [comment]
Agree with javadocs req on public classes and interfaces.

**Comment by prastle** [comment]
Replying here so hopefully u or ron notice the new forum is down only u3 have admin login to my knowledge at admin level  @RoiEXLab  @DanVanAtta  @ron-murhammer

**Comment by ssoloff** [comment]
@DanVanAtta I believe #2035 resolves this issue.  Are there any other outstanding tasks that must be done before this issue can be closed?

**Comment by DanVanAtta** [comment]
No, closing - thanks for the follow up.
