### ISSUE TITLE
Feature Request Process with new NodeBB Forum

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2010]
For 'accepted' feature request tracking we seem to have consolidated on a list that includes links to background information per idea:  https://github.com/triplea-game/triplea/wiki/Feature-Back-Log

We are pretty close to getting to a finalized process, but I don't think we have it quite clear nor documented and publicized. I'd like to revisit and perhaps finalize this process in view of the new consolidated NodeBB forum.

Some Questions:
- should all feature requests that are user-facing (game players or map makers) go to the forums first? 
- should we keep one forum thread for all feature requests, as a running conversation, or split feature requests each into their own thread? If we do one request per thread, a forum section for feature requests would make sense.
- Are we happy with the wiki list for accepted feature requests? Is it clear who would move content to that list, is that going to work out in practice? I think it is useful to have the list of ideas that have been vetted and are ready to go, but there should be multiple ways to do that and perhaps some more practical.

**Comment by ron-murhammer** [comment]
@DanVanAtta I'm tempted to say it would be better to have a stickied forum post with the feature back log. This makes it easier to find and more consumable for our casual users who often are the ones making requests. We can still keep links back to the github issue for more implementation and technical discussions around requirements for it. This also gives a place for more casual users to provide suggestions and for us to show progress on which ones are implemented.

I would say most user-facing feature requests should be discussed on the forums. Though if it is minor changes or obvious improvements then its not a requirement. I think we should try to drive more conversations on the new forums and primarily use github issues for developer and technical discussions and bug tracking.

**Comment by DanVanAtta** [comment]
I had considered that a bit, though it would perhaps make sense to use that for receiving ideas rather than a backlog. We do have 2 distinct use-cases, with a few different considerations. Users want somewhere where they can post ideas or pain points they are having. Dev's want to see a list of ideas that have been well developed and are ready to go, and which are done. A single thread will be difficult I think for dev's, would be lots of content to go through and hard to know what has been completed.

I'm considering quite a bit a forum subsection to track it all. When completed we could maybe update the title. It's still though a challenge to know what can be worked on easily, the wiki 'master' list does have its advantages.

**Comment by ron-murhammer** [comment]
@DanVanAtta It is useful to show users what is in the backlog though which I think is another benefit of moving it to the forum. I also tend to completely forget about the wiki pages as we don't have much left there. I would actually vote to remove all wiki pages and consolidate that info into either the website, dev docs, or forum.

**Comment by DanVanAtta** [comment]
Forum posts can be edited, perhaps we could replace the wiki list we have with a locked/pinned forum post in a 'feature request' section.  We update that instead of the wiki list, and included there would be instructions to create a new forum post to discuss a new idea. We get a number of benefits this route, all is consolidated to forum and we still get the list of 'open' features.

A single forum thread I think will get messy/hard to track, multiple without a tracking list I think can suffer from a similar problem but in another direction. I think a 'master list' forum post with posting instructions with one sub-post for feature requests is perhaps the best option. Thoughts? Alternative options or opinions?

**Comment by DanVanAtta** [comment]
@prastle , you may be particularly interested in this topic

**Comment by ron-murhammer** [comment]
@DanVanAtta Yeah that works for me and I think is a good balance.

**Comment by prastle** [comment]
ya sorry was busy with paypal all day ya we could pin a list and make admin accessible only to edit the thread when new ideas come up.  Ill read above and think  :) gd ideas

**Comment by prastle** [comment]
Ok so first each category can have its own privileges
Thus it is easy to make areas that cant be edited by for example adding a new group or a new category with different privileges.   I also agree that trying to keep all in the forum as ron said would keep it all centralized and allow all to contribute without jumping sites.  Then the dev stuff gets picked /deleted/moved to github as it is fixed dealt with.  Just my 2 cents

**Comment by prastle** [comment]
Maybe we creat a developer group ;)   Just thinking out-loud.

**Comment by DanVanAtta** [comment]
I would suggest starting with a 'forum-moderator' group and add everyone to that with generous privileges. Keep it simple and use the one group for anyone that can help with anything related forum.

For tracking, should be no need to move anything to github. Code updates submitted here, then we go back and edit the pinned forum post to mark an item as completed. In the discussion thread that should be linked, perhaps we would comment there about progress and that it is being worked on.

**Comment by RoiEXLab** [comment]
@DanVanAtta Doeas postresql have enum types like MySQL?
If it has we, want to use those values as the work like strings, but just have a limited amount of possibilities

**Comment by DanVanAtta** [comment]
I created the forum subsection for feature requests.
While typing out the notes/instructions for the feature request list it is more obviously a thing that sounds good to 'dev', but would probably be a buzzkill. Plus why have the overhead.

I suggest we keep it  simple, let's go with a feature request section, we'll have one topic per idea. We then get a list view naturally from that. To know what has been done, we can update titles with a "Done" prefix.

**Comment by DanVanAtta** [comment]
To handle the open feature requests, I suggest we tag them with 'ice-box' and close them.

**Comment by DanVanAtta** [comment]
> @DanVanAtta Doeas postresql have enum types like MySQL?
If it has we, want to use those values as the work like strings, but just have a limited amount of possibilities

@RoiEXLab postgres has value constrains that can be applied to a column. So you can make sure that a value is in a given set, yes. It can be more arbitrary too, since it is any boolean conditionn, so you could also make sure that if in one set then first character is numeric, etc..

**Comment by DanVanAtta** [comment]
https://forums.triplea-game.org/category/42/feature-requests-and-ideas   

The feature request section is set up. Keeping it simple, new topic per idea and no master tracking list. No mention either to users to look for dupes or links to old ideas. Somewhere ther should be a tracking link to all our idea lists, but not in that forum post. The reason being is that we want to keep that clean, and any new issues or dupe issues is a signal that the feature request is still desired.

**Comment by DanVanAtta** [comment]
Closing now, thanks all.

**Comment by DanVanAtta** [comment]
Follow up points and summary:
- created feature requst forum section: .
- updated README to link to the feature request forum section.
- removed feature request wiki page, each issue listed there had the 'ice-box' label added
- added a link to the closed 'ice-box' feature request list to the readme: https://github.com/triplea-game/triplea/labels/ice%20box%20-%20revisit%20later

I'll label all open feature request issues now with 'ice-box' and close them down. Then any new feature requests will hopefully come up in the forum.

**Comment by ron-murhammer** [comment]
@DanVanAtta Good with everything but I would like to have a master post in the feature request forum. The instructions for posting can be very short and simple. I would like to have a consolidated list of the features though so we can sort of category and keep track as once you get to more than 10-20 posts its gonna be really hard to just use the forum posts as a list.
