### ISSUE TITLE
Postgres version for integration tests

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/triplea#2019]
I want to configure my dev environment so that I can run the integration tests locally.  Although no version is explicitly specified in `.travis.yml`, the Travis build logs indicate that Postgres 9.1 is being used.  I was just curious if this is the version that is or will be installed in production given that it is six years old and has already reached EOL?

Even if 9.1 is the version that will be used, it might be helpful to [explicitly specify the version](https://docs.travis-ci.com/user/database-setup/#Using-a-different-PostgreSQL-Version) in `.travis.yml` as a form of documentation.

**Comment by DanVanAtta** [comment]
https://github.com/triplea-game/triplea/pull/2020/files

**Comment by DanVanAtta** [comment]
Hmm, travis not terribly happy with that config. Prod version is 9.5

**Comment by ssoloff** [comment]
Thanks, @DanVanAtta!  I got my environment set up and the integration tests are running successfully.

Just for my own reference in the future, or for anyone else who is interested in using a Docker container to host Postgres for TripleA testing, here's all I had to do (assumes `$(pwd)` is the root of the `triplea-game/triplea` repo):

* Start Postgres on `localhost:5432` with an empty `postgres` user password (per the default `lobby.properties` configuration):

```shell
$ docker run --name triplea-postgres -p 5432:5432 -d postgres:9.5
```

* Create and initialize the lobby database (needs to be repeated if the `triplea-postgres` container is removed):

```shell
$ docker run --rm --link triplea-postgres:localhost -v $(pwd):/triplea postgres:9.5 \
    bash -c "cd /triplea; ./.travis/setup_lobby_database"
```

**Comment by ssoloff** [comment]
@DanVanAtta Just in case you didn't see my [previous comment](https://github.com/triplea-game/triplea/pull/2020#issuecomment-311526952) in your closed PR, this looks like it will [work](https://travis-ci.org/ssoloff/triplea-game-triplea/builds/247767909) in Travis:

```diff
diff --git a/.travis.yml b/.travis.yml
index 07b721b..a4b9b92 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,7 +1,10 @@
+dist: trusty
+sudo: false
 language: java
 jdk:
 - oraclejdk8
 addons:
+  postgresql: "9.5"
   apt:
     packages:
       # python for map file splitter
```

Note, however, that my build did not run the `deploy` phase, so there may still be issues with the Trusty container and the full TripleA build.

**Comment by ssoloff** [comment]
Closing.  Got the answer to my question about the Postgres version in production, and #2033 was submitted to follow-up on #2020 to document this.
