### ISSUE TITLE
Drop Custom Map Download Sites?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#202]
Today: launch game, click download map, click list games, then can select maps for download

Proposal: skip the list games step and go straight to the download map screen. One way to do this would be to completely remove the feature for  arbitrary map download sites. Another way would be to move the map repository selection box to the top of the final map download selection screen. In this alternative approach after clicking download, users would be taken to the final download screen and would see the default map list. Only *then* could they change the map hosting site.

On the other hand, if we remove the feature altogether, then both UX and UI can be simplified. Since there are appear to be no use cases anymore for the feature, my vote would be for dropping it.

**Comment by veqryn** [comment]
Sure, lets remove the custom sites completely.  It made sense 6 years ago, but today they don't.  Noone uses them, and it is just confusing to users.
