### ISSUE TITLE
Adding A Wiki With The Link To All "Ice Box" Feature Request

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#2023]
From:
https://github.com/triplea-game/triplea/issues/2010

Can I (or you) go ahead and make a Wiki here (with no list) having little more than this simple link (and telling to click on this link to accede to the list of finalised Feature Requests waiting for any developers to take them over):
https://github.com/triplea-game/triplea/labels/ice%20box%20-%20revisit%20later

Also, I believe a decision should be made if to have them all closed or them all open. I'm not clear why 2 of them are open, while the remaining 42 ones are closed.
I'm guessing, from now on, Feature Requests will be always closed upon getting the "Ice Box"?

This way, there would be a fairly visible way to accede to the full list of Feature Requests that are tracked here.
Will all the Feature Requests made here be eventually closed, when waiting for anyone to do them, correct? I guess so, otherwise the old ones that have been closed and in "Ice Box" should be reopened, as well.
Assuming that the process of closing Feature Requests that are not getting done nor further discussed (thus they appear finalised and in waiting) is kept, I think something like an easy to find link above is needed, to set the "Feature Request" that are closed waiting for a developer apart from those that have been closed because done, superseded, or other reasons.

I think that the best was a system like the sourceforge tracker, in which you had Tickets/Bugs and Tickets/Feature Request.
This way you could have your Bugs (actual Issues) under watch, and possibly have them reducing overtime, while the Feature Requests will, of course, keep increasing overtime.

Assuming that is not possible here, then I think that tracking the Feature Requests here and closing them and adding them to a changelog with a link to the Issue is the best thing.

It is good to use the forum for preliminary discussions, but once something is reputed to be defined enough, a Ticket or Issue is the best way not to lose it.
So, I would have kept the feature request list here in the Wiki, with the links to the related closed issues.
I've doubts about how the current "Guidelines and Feature Request List" is going to track stuff, unless there are plans to add links in there too?
https://forums.triplea-game.org/topic/182/guidelines-and-feature-request-list
For example I see:
"Handle infrastructure placement better"
Without a direct link to the Issue here where that matter was discussed, I see that list as less helpful than the list that was here in the Wiki with the direct links to all listed requests.
Maybe that list should have the links to the Issues here it is referring to? But it is surely strange to have a list in forum that it is linking to Issues here (but that is already a list in forum that it is referring to things not in forum).

However, a list to maintain is a burden, thus, as I'm suggesting, just an informative linking to a properly labelled group is preferable, and it is itself a list, already.

My suggestion, assuming something like in the old sourceforge tracker is not possible (having a separate "Issues" and "Feature Requests" in here), is to keep the list here in the Wiki.

I always suggested to use the (old) forum for preliminary discussions, but I think that once something is reputed to be clear enough, a "Feature Request" ticket is better than a forum post.
But I think the main matter is that a list needs linking to the specific issues; I don't think the current list in forum, referring to Issues here in GitHub is that helpful, since it has no links (and I guess there is no plan to add the links, since they would redirect here in GitHub, while now on that is meant to redirect to topics in that same forum).
What I'm mostly saying, is that I don't have a strong opinion one way or the other, for the future, but regarding the past I think that not having the links to the related Issues anymore is a big loss of usefulness for that list (I just see something like "Handle infrastructure placement better", with no link, nor a Topic about it in that forum subsection, as I would expect, and that is not really tracking anything).

For the future, I think I would, say, open a forum post if I want to discuss a matter on broad terms, but, then, I would still cut a "Feature Request" aimed Issue here in GitHub, maybe multiple originating from the same topic.
For example, say, you open a Topic about "Fuel Changes", that gets turned into several "Feature Requests", and maybe some "Bugs", here in GitHub.

Mainly, assuming that "Feature Requests" are still meant to be posted here in GitHub and not by developers only (correct?), what is the new plan for tracking them? They will be now just regular Issues and remain open or will all get closed with the Ice Box? If the first, I suggest to reopen all Issues that were closed and added to the Feature Request list in the Wiki; if the second, my suggestion, as per this post, is to make Wiki explaining that process, with the above direct link to get all current Ice Box labeled Issues.

I'm just mostly not sure where this is heading and I'm perplexed about seeing a list in forum that is referring to issues here in GitHub, without links (that is the list that was here in the Wiki, but with the links removed).
I would not forbid to make "Feature Requests" here in GitHub or closing them after some time without recording them anymore, as that would mix them up to all those closed for any other reasons, and I see that the "Ice Box" label is meant to set them apart, but I believe a Wiki with the link to that list is needed to make this process fairly understandable.

**Comment by DanVanAtta** [comment]
> Can I (or you) go ahead and make a Wiki here (with no list) having little more than this simple link 

No objection. Though, we should be funneling people to the forum for feature requests and the list of requests while trying to reduce the ice box list to an effective zero.


> I'm not clear why 2 of them are open, while the remaining 42 ones are closed.

I may have missed them, or they may have seemed more like UI or game engine bugs rather than feature requests. Thin line between bad behavior and a feature request. They perhaps coudl use more consideration before being ice boxed.


 > I'm guessing, from now on, Feature Requests will be always closed upon getting the "Ice Box"?

 Ideally they will go to the forum first. If they appear in github issues probably it will be asked to create a forum post instead. That at least is my understanding. 


 > I think that the best was a system like the sourceforge tracker, in which you had Tickets/Bugs and Tickets/Feature Request.

 I think you raise some good points, I don't disagree with them. We do have an added complication where a good chunk of the community would like to be active on the forum only. So essentially all feature request tracking/submission is being moved off github (to forum)

 > Assuming that is not possible here, then I think that tracking the Feature Requests here and closing them and adding them to a changelog with a link to the Issue is the best thing.

 We'll remove the 'ice box - revisit later' label is something is picked up and then completed. The presence of that label means it has not yet been done.

 > It is good to use the forum for preliminary discussions, but once something is reputed to be defined enough, a Ticket or Issue is the best way not to lose it.

 I agree, though in practice how well have we done in getting things done which we've tracked like that? Multiple comments about different ideas in a single forum post I think is certainly a recipe for items getting lost, many different threads will probably not work as well over time. I think it's a bit hard to maintain, but the thinking is to have a locked forum post that would be the list of well defined ideas that can get picked up easily.


  > So, I would have kept the feature request list here in the Wiki, with the links to the related closed issues.

  Yeah, partly it's try and just deprecate that system. We are using forum as much as possible for features. Ice box is trackign the stuff we had here, and that should shrink or just quietly sit. Items from the ice box can be raised on the forums again. The wiki is not getting much usage, I think we'll be looking to move most/all content off of it. That can change if we start finding it useful, just so far it does not seem to have its use compared to other tools/locations.

 

 > Mainly, assuming that "Feature Requests" are still meant to be posted here in GitHub and not by developers only (correct?), what is the new plan for tracking them? 

 To answer explicitly, github and feature requests would have no relationship, would not receive them there, nor track them there. Forum.



 @Cernelius, hopefully that helps clear things up. To some extent the process update is a made decision, but the new feedback is useful. Given the above, do you think it can be made workable to receive and track feature requests all in forum? We to some extent have to post there anyways. Tracking them in github is not very desirable since then there is cross-site dependency, overhead, pollutes the bug queue, creates a queue we can never close so we start settling for this ever-growing queue... It's also I think slightly confusing to users for a feature request to exist in different places dependending on life cycle. Saying bugs in github, features+ideas in forums is at the least relatively simple.

 I'm glad you chimed in when you did, it's not too late to change our process, and we are certainly looking to refine/improve it. I think keeping all feature requests in forum will help, my personal suggestion is for us to give it an earnest try for some time. I can still be convinced otherwise, but I do think we have seen some hard to solve problems tracking feature requests in github.

**Comment by Cernelius** [comment]
So, if I am understanding correctly, this is the aimed new process:

1) Someone makes a Feature Request topic here:
https://forums.triplea-game.org/category/42/feature-requests-and-ideas

2) Eventually, a developer will pick up something from there and open a pull request here:
https://github.com/triplea-game/triplea/pulls

3) There will be no Feature Requests in Issues, but it will be used only for actual Issues.

I don't feel 100% positive about this. As I said, I preferred the old sourceforge tracker, in which you could have cut a concise issue out of a forum post, while not having a single ever-increasing collection of mixed issues and enhancements, but I guess that is not supported here in GitHub, and it is viable that the poster does it by updating the first post of its topic, to keep track of the current status of its feature requests.
Still, you often want to make a topic to talk in general, and then split it into multiple feature requests (as I said, a "Fuel Changes" topic, that may originate tens different feature requests and become tens pages long). I guess that can be made by having / editing the list of them in the first post. Still not near as clean as cutting tickets.

Mostly the matter here is that now, that list is not that helpful or tracking, in the moment in which I just see something like "Handle infrastructure placement better" with no links or hints about where should I go to further discuss or see what that is about (and having a list in a forum linking to here would not really make sense). At this point, you might just want to restart from zero, and have the forum list just about what is made in that subsection in the forum (and reputed by the developers to be a worthwhile addition). Probably should also add a full list of all forum users that are supposed / allowed to update that list (probably not any moderators, not sure if any admins).

Specifically, should I go there in forum and re-make this Feature Request of mine, there, for example:
https://github.com/triplea-game/triplea/issues/1411

**Comment by Cernelius** [comment]
Also, this might make harder to sort out when something is a feature request or a bug fix, in the moment in which we are not talking of switching a label, but going in totally different places. The matter might be not that clear cut not that rarely, and it is not that uncommon that a matter may be both at the same time (a bug fix that comes with additional features or behavioural changes).
Especially since the loose nature of this project, there are many cases in which changing the behaviour may or may not be seen as a bug fix.

**Comment by DanVanAtta** [comment]
> issues and enhancements, but I guess that is not supported here in GitHub,

It is only as far as you can tag issues, which means you can give them arbitrary labels like 'enhancement' or 'feature'.  But I think it is splitting hairs that nuance perhaps, there is no 100%: "these are my bugs", and "this is everything else"



> Still not near as clean as cutting tickets.

Github does have a 'project' feature where you can create cards and put them into 'swim lanes' (status lanes):

[example project]

So we could deem that we track features which are picked up and active to go into a project. A project card is basically an issue, just a task, and we can do the breakdown there and split things up and definition, and keep the rest of the conversation in the forum thread.



> Handle infrastructure placement better" with no links or hints about where should I go to further discuss 

This is a downside to the 'ice box' label and closing those issues. In theory if I were being really diligent I would have transferred each to a forum post.. That seems like a bad move still. Regardless we do have the clean 'ice box' marker of all these items, our options are still open.



>  At this point, you might just want to restart from zero, and have the forum list just about what is made in that subsection in the forum (and reputed by the developers to be a worthwhile addition). 

Starting from scratch is what I think this is turning into. There are some positives to it. Anything that is really wanted will come up again.

> Probably should also add a full list of all forum users that are supposed / allowed to update that list (probably not any moderators, not sure if any admins).


I think the help/participation is encouraged welcome and useful. I think there is a natural "forum moderator" role that some people may want to fill, managing such a list and the rest of the forum would be up to them.

> Specifically, should I go there in forum and re-make this Feature Request of mine, there, for example:
#1411

It is up to you. If you do, it would be appropriate to remove the 'ice box' label from #1411 

I think maybe what is perhaps lacking is a way to designate an urgency and/or priority. Maybe we should better quantify benefit of each feature so it can be an easier choice of what we should pick up right away and what can linger. A first step is perhaps getting some sort of reasonable feature request process going. I think having it all be on the forum is a decent start, easy to explain etc.. There are some things to work out..

**Comment by DanVanAtta** [comment]
re -  bug fix vs feature request:

It really can be argued both ways so much of the time, it's prety much a political game. Some organizations just call it all 'improvements' and they have done with it. Maybe the answer is to group things at a more granular level:
- map feature fix
- game rule fix
- better UI
- better game play
- better UX

Then if we can group things into those categories, it can be easier to know which belong where.

**Comment by ron-murhammer** [comment]
@Cernelius The main point of this change is to try and consolidate feature requests onto the forum. This allows input from a larger portion of the community as most non-technical users don't like github issues as much. I just did an initial pass on organizing the existing forum posts and creating a list of features: https://forums.triplea-game.org/topic/182/guidelines-and-feature-request-list

This also provides more visibility to what features are potentially being actively worked on. My personal preference is to consider most things "feature requests" or "improvements" and only bugs if its clearly not functioning as intended or error messages or crashes. 

Eventually, I'd like to organize the list on the forums by type of "improvement" as @DanVanAtta kind of hinted at above.

**Comment by RoiEXLab** [comment]
If you want all of the "ice-boxed" issues in a list, you can simply visit [this link](https://github.com/triplea-game/triplea/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3A%22ice%20box%20-%20revisit%20later%22%20label%3A%22type%3A%20feature%20request%22).
Not the best way ever, but it gives a good overview

**Comment by Cernelius** [comment]
Ok. It was mostly not clear to me what was the process now and if the feature requests were supposed to be totally out of github (thanks for clarifying). I surely agree that the forum should be the first step for a feature request or any deliberate changes for how the game works on users and mapmakers, and I'm sure some remember I suggested that in the past, as well. I was comfortable with the old sourceforge process, in which first you would do a forum post about the matter, and then, once the discussion has died down and all has been fairly finalised, summarise and cut one or more ticket in the tracker, out of it, but of course this creates duplication of discussion, to some extent (but this didn't actually happen, because there were no really discussions in the tracker, just in the forum).

So I just wanted to be sure that this was a passage from a system in which all regarding the engine was supposed to be kept entirely in github to a system in which all regarding engine enhancements is to be kept entirely in forum, except only the pull requests to actually do it, with no intermediate "Issue" step at all.

Probably you will have to decide to what extent to keep the bugs in forum, as well, especially since, inevitably, some feature requests will be actual bugs, or anyways people will, to some extent, report bugs in forum, not just here (plus, as I said, it is often hard to set apart what is a bug and what is a feature request). For example, the problem reported by Frostion, of AA not attacking multiple rounds on the offence was a bug, not a feature request, and indeed he then cut a ticket here, after the forum topic:
https://github.com/triplea-game/triplea/issues/1966
So I think that one should not be in the feature request list, and stay in a different forum subsection.

So, thanks for the clarifications. I'm thinking to get around making the Wiki, as I believe it is really hard to understand how stuff work, otherwise, since the process has really switched from one extreme to the other, as I see it. That was mostly the reason why I was dubious to have understood your decision right.

**Comment by ron-murhammer** [comment]
@Cernelius Yeah the plan for now is to to feature/improvement discussion and requests on the forum to promote involving the community. For bugs and technical issues, we will still primarily use github issues as they tend to require less community involvement and are more clear cut or technical.

#1966 is a good example of one that could be considered a bug or a feature depending on your definition and view. The code was purposefully written to remove all attacking infra without attack or support values. So IMO its actually a feature request to expand functionality as it was technically working as intended.

**Comment by Cernelius** [comment]
> The code was purposefully written to remove all attacking infra without attack or support values. So IMO its actually a feature request to expand functionality as it was technically working as intended.

I personally got convinced that was a bug when I tested that the behaviour was the opposite for offence and defence: all else being the same, the AA would have been kept in combat in defence and removed from combat in attack, meaning that we would have the first behaviour (all else equal) for:
`<option name="attackAA" value="1"/>`
("attackAA" means active on defence only)
and the second one for:
`<option name="offensiveAttackAA" value="1"/>`
and since pos2 explains "offensiveAttackAA" just as:
`values: same as attackAA but for offensive side`
my conclusion would have been that the behaviour was intended to be the same in both cases, thus either removed in both cases or kept in both cases.
Hence, the simple fact that they acted differently was a proof of this being a bug, in my mind, relatively to:
`maxRoundsAA 						values: sets how many rounds the AA may fire in. negative (-1) means infinite. (default = 1).`
and considering that AA units are traditionally infrastructures unable to otherwise take part in combat (so, I would have excluded that an exception to the rule could have been intended for the standard case).
But I see that traditional AA units are also unable to combat move, thus unable to attack at all; so probably this thing was made having in mind that infrastructures should never attack.
So I get it that it is possible that this was intended to not work, as being intended infrastructures never being sent in attack, which also couples with the other bug (solved too) that they can't retreat.

Most likely, more in general, sending infrastructures in attack was something meant to never happen, so the feature request would be to support that happening without issues.

But all good, don't want to waste your time over what is admittedly almost quibbling (and over something already solved); just saying that I believe from a point of view of someone unable to read the code I would have been sure that is a bug, and would have came here to post it, instead of in the feature requests in forum, personally.

Not sure if I would have been redirected to post in forum, instead, and the point I was making is that is something more than switching a label. But all good, I just opened this issue to actually understand what was going on about the new process; I'm fine one way or the other, as long as I can understand it (which now I do as much as I can).

**Comment by Cernelius** [comment]
Actually, for the Wiki, a last item would be what you want to be the preference for the grey cases of something that it is not clearly a feature request nor clearly a bug, like the above. They should go preferably to forum or here?

For example (as we discussed), I want to open an issue about transports removed with triggers not removing the transported units and making the game crash (kind of the other side of the coin of the solved issues of dependent units ignored by conditions). That is not really a bug, as I'm sure triggers removing units were just not meant to be used to remove sea transports.
Would you suggest me to post this matter  here or in forum?

**Comment by Cernelius** [comment]
Also, is this the same matter that has been already decided and explained here? From what I understand that is just totally outdated now? I guess it should be closed, if you don't want to rethink this matter further.
https://github.com/triplea-game/triplea/issues/1851

So, to sum it up, rethinking about all, the only main issues that I see in this new process are (not trying rediscussing, just making a sum up of what seems agreed upon):

1) It is hard to say when something is a "**feature request**" or a "**bug report**", thus this would make quite often difficult to decide where the matter should be posted, especially for people not in the known, and very impractical to reorganise (closing and telling people to go elsewhere, as opposite to switching a label, especially when something is sorted out one way or the other, while the matter is ongoing, breaking up the discussion for no reasons but the inability of switching a label or moving it over, would be very annoying (it is not rare that something gets classified or reclassified one way or the other after some time the issue has been opened (the https://github.com/triplea-game/triplea/issues/1966 is a good example of something being reclassified as a feature request even after it got solved as a bug; so what? would you tell the user to reopen in forum to no purpose but reclassifying, since you can't anymore do it by just switching a label)); hence also the risk of things not getting properly reclassified, not to oblige people to restart all the discussion again or to abruptly close and restart right in the middle of it, which would happen a lot).

2) The problem of dividing up similar items between two completely different tracker overlaps with the unresolved matter of setting apart map bugs and engine bugs, especially since it doesn't seem a clear solution for tracking map bugs have been reached, yet, and it is easily impossible for people not in the known to decide about it, in the moment of making the bug report.

3) This process change causes a very big breakage of continuity, where all the feature requests that have been discussed and categorised so far will need to virtually be restarted again, all that have been recorded so far (and retained in "ice box") being likely mostly forgotten and probably increasingly so overtime.

4) There will be the need to continually check back and forth the "ice box" list, to progressively remove from the list those issues that have been reopened in forum, maybe by someone else, not realising the existence of an "ice box" related issue.

---

Minor note, if there is a label called "Feature Request", I think the other label should be called "Bug Report", not just "Bug", or, if calling it just "Bug", I think the other label should be renamed "New Feature".

**Comment by Cernelius** [comment]
Looks like folks are going ahead and using mainly the forum for bug reports too... That would solve 1 and 2...

This:
https://github.com/triplea-game/triplea/issues/2150
is another dubious example.

In my mind, if you say "gives 1 Power to 1 Allied Chasseurs/Fusiliers/Grenadiers and Marines", that means that you give +1 to each 1 of them, while the behaviour would be giving "1 Power to 1 Allied Chasseurs/Fusiliers/Grenadiers and Marines". Anyways, I didn't quite feel sure calling this a bug. Do you think that this is a bug report or some request?

**Comment by Cernelius** [comment]
How about you find some way to differentiate between Feature Request that are better to stay in the forum and Feature Requests that are better to stay here?

For example this old one:
Switch tab ordering on map download page
https://github.com/triplea-game/triplea/issues/1864

or this new one:
Support Attachment Unit Type Tooltips Display Correction Request
https://github.com/triplea-game/triplea/issues/2150

If anyone has good memory, I always said that discussions, and especially feature changes and removals, should be kept in the forum, but it is just weird that if I want to suggest to reorder the map download page I would want to start a forum discussion (!) about that. And that thing of changing the tooltip "and" to a stroke would be even stranger as a forum topic. Also now I'm not sure, since after I opened there, that looks more like a display correction than a feature request to me, @ron-murhammer  tagged it as feature request, that you said would not be tracked here anymore, instead of closing it and telling me to repost it in forum, that I guess it is what it should happen, based on this discussion.
So, what I'm saying, do you think it can be found a way to clearly differentiate between feature requests for the forum and feature requests for the issue here?
How about something on the like of forum for new / additional stuff and here for improvement / changes of existing stuff? Would that make sense?
Or how about keeping here anything that may be considered an "issue", even if not a bug. For example, the map ordering being not functional or a tooltip being unclear is an "issue" (of course, it can be discussed, and closed if not recognised so), even if not a bug, while, like making a ruleset for a new WWI game is not an issue at all, so that would be good for the forum, then going directly to pull requests without any issues in between of this process.
Or maybe UI vs game rules? With UI here and game rules forum? Tho there is the main problem that if something is difficult to distinguish then you will keep closing and telling people to move over?

I'm just mostly not making sense in my mind to open a forum topic if I just want to suggest reordering the download list tab or change a word in some tooltips.

Personally, as I said, I preferred the old Sourceforge way, in which you would have kept the discussions in the forum, and, once the matter was out of discussion phase, you would have cut a feature request ticket on the specific sorted matter. I guess this would be also more doable, as when you think that something does not qualify as a Feature Request, instead of tagging it as Discussion, you would close it and tell the poster to move to forum or try again making something that might be acceptable as a Feature Request. So, how about moving all Discussions about Feature Requests (meaning anything that does not qualify as being past a discussion phase) to the forum, instead of moving all Feature Requests?

Opinions?

Well, anyways, what you said we are already not following, since this correction I posted has been tagged as Feature Request:
https://github.com/triplea-game/triplea/issues/2150

**Comment by prastle** [comment]
Cer I LOVE YOU! but the main purpose is to allow all to input in a forum they can easily read.  Instead of being diversified over many sites.  One home, one place for all

**Comment by prastle** [comment]
ATM we are down to git and forum which is way better than the past imho

**Comment by Cernelius** [comment]
So, as I said, I preferred how it worked with the Sourceforge forum + tracker before gitub, but this doesn't really matter; the problem is that this is not making a lot of sense in my mind about what should go to forum and what should stay here. The clear example was this:
https://github.com/triplea-game/triplea/issues/2150
Should then this be closed and should I open a forum topic about changing the "and" to a stroke for the support tooltips? Why was it tagged as feature request?
Should this go to forum too?:
https://github.com/triplea-game/triplea/issues/2153
In my mind, in both these cases, it would feel strange opening a forum discussion about these things, but if clarified and closed I'll do.

**Comment by Cernelius** [comment]
So, to sum it up, going back talking about engine stuff and feature requests in forum is a step (backwards) in the right direction. Not sure if it is good not summarising the specific points anymore in any tickets, and there may be things that are not bugs but would not make much sense to stay in forum.

For example, you just opened an Issue about "passwordless lobby login", and I'm not sure how that is not a feature request, but I agree there is not much point in posting that thing in forum; up to you to clarify or find some labels for such things, if needed:
https://github.com/triplea-game/triplea/issues/2169

I'll let the decision makers making a wiki or whatever, explaining this matter to all, since the process is not fully defined to me. This is most likely needed, if you want to limit people from keeping posting feature requests in here (not sure now where they can read they shouldn't).

Maybe, instead of keeping here anything that it is a bug, you should keep here anything that it is an "Issue" or a not-additive improvement, and define that somehow, thus keeping in here feature requests to adress basic issues (like the tooltip correction I mentioned).

I will just add the general info that "Feature Requests" are supposed to be posted to the forum. Up to you to clarify the process more in details, as I believe it is needed (pretty much all the points I've doubts about you can read in this issue alleady).
https://github.com/triplea-game/triplea/wiki/Feature-Requests

**Comment by Cernelius** [comment]
I've provided two links, as there are some open feature requests not in ice-box, some open feature requests in ice-box and some closed feature requests in ice-box; up to you to sort this out.

**Comment by DanVanAtta** [comment]
We last discussed tracking map problems here: https://github.com/triplea-game/triplea/issues/1344, and latest were trackign them in this queue: https://github.com/triplea-maps/Project/issues

For context, "Map bugs" are "bugs" that can be fixed by updating map XML alone without game engine updates. We may do well to revisit that decision and track all such problems here as well. The triplea-maps/project issue queue does not seem to be very well used or watched.


We still need bugs to be tracked in github issues though. Hence the logical question of how to define feature request vs bug request. To one extent, dev's/admins are responsbile 
 to make sure that we get all bugs to github issues and track their open/close state appropriately.

 Now, what is a bug vs feature request? Additive improvement is a good definition. I would suggest a bug is anything that you would list on a "Why TripleA Sucks" list. This could include things outright broken, or things that are working but are annoying or confusing.

Perhaps the way to think about the two different lists is who/how they are consumed. It is both regrettably from a dev point of view, fixing a bug vs a new feature is a bit of a diffenet task. We want the wider audience to discuss game changes, hence features in forums. People will see dev's talking about features there, either from lack of clarity in process or not wanting to create github accounts, we'll see bug reports be created there naturally.

Regardless, the list of github issues are the things that must be fixed to have a well functioning game, the feature request list is the 'wish-list'. It can be a bit fluid sometimes as you discover something is actually working as intended, but in that case there should still be an update somewhere to clear up the confusion.



@Cernelius I'll re-open this to hammer out any further questions you may have, please close if things are pretty clear now at least in terms of "feature request" vs "bug". To discuss directly where to discuss bugs, whether 100% in github issues, or 100% in both github issues and forums please see: https://github.com/triplea-game/triplea/issues/2187. Since github issues is our chosen bug tracking software, we do need all open bugs listed there! (Which is a different requirement compared to feature requests. One is tracking, somewhat formal, improvements to the software so it does not suck, while the other is conversation and idea generation, and something for devs to do when they want to do something more fun than fixing bugs)

**Comment by Cernelius** [comment]
> We last discussed tracking map problems here: #1344, and latest were trackign them in this queue: https://github.com/triplea-maps/Project/issues

No, you are not. As you can read there, you decided to track them there, but you never updated the description at "Project" (that still reads "Issues global to all maps") and, eventually, you (meaning @ron-murhammer) reverted back on that decision.

> @DanVanAtta I think we need to make a decision on this on either:
> 
> Keep map issues in this repo (triplea-game) and tag them as such
> Keep map issues in https://github.com/triplea-maps/Project
> After we decide on the preference there, then we just need to update documentation/code to meet that.

> So based on number of issues opened, I think its better to just keep the issues in this repo. As we end up not using the other repo much and end up not checking it.

I actually think all map issues should be centralised there, instead of being opened in the specific repositories, not only the bugs, but it is up to you do decide and document it, so that people know.
Then, the next step would be closing all map issues in here, and reopening them in there, if it is not possible to move them.
As you have likely noticed, I'm already using Project to track projects specific to 1 map only (for example, napoleonic_empires, instead of opening an issue in that repository).

What I'm mostly saying is that I think you need another category in between of "Bug Report" and "Feature Request" for all those things that are issues and corrections but do not qualify as bugs.
My suggestion is if something is an issue, even if not a bug, then it should stay here, while if it is an addition, a change or of an improvement of something that has no issues, then it is better to stay in forum.
Of course, it is subjective, and it will be up to you to close the issues that don't qualify, and redirect to the forum.
I agree that wishlist stuff (like making Risk or whatever) is better to stay fully in forum, otherwise it is going to just keep piling up, while here only things that are bad and should be improved should be tracked as issues (I'm saying only bugs is too restrictive).
Also, the developers should consider talking with each other and define what is a bug, because I'm under the impression that some have a very restrictive definition for it and some other a more broad one.

Meaning this:

> Now, what is a bug vs feature request? Additive improvement is a good definition. I would suggest a bug is anything that you would list on a "Why TripleA Sucks" list. This could include things outright broken, or things that are working but are annoying or confusing.

And this:

> My personal preference is to consider most things "feature requests" or "improvements" and only bugs if its clearly not functioning as intended or error messages or crashes.

Are very different, so probably you should decide the official definition of what may rate as a bug, and make a Wiki about it.
My suggestion was to make another classification for those things that are improvements of things that have issues but are not true bugs. And I was saying that such things should better be tracked in an actual tracker.

Also, this needs updating:

https://github.com/triplea-game/triplea/blob/master/.github/CONTRIBUTING.md

If nobody else has anything to say here, I've not either, so I would close this again.

**Comment by Cernelius** [comment]
> For context, "Map bugs" are "bugs" that can be fixed by updating map XML alone without game engine updates. We may do well to revisit that decision and track all such problems here as well. The triplea-maps/project issue queue does not seem to be very well used or watched.

How to define stuff is not up to me, but I definitely would say that map bugs/issues are fix of anything inside the maps' folders, not just the xml.
If you want, you can split it up in "map games issues" and "map skin issues" (meaning the skin part of the maps, comprising the map-skins, that have only that, but not meaning the map-skins only), for xml and not xml, but I don't think it is needed.

And, as I said, you have already revisited that decision or, rather, the decision of tracking in Projects was never finalised or applied or communicated, unless I'm missing something (so, of course, it is not very well used, as I don't believe there is currently a way to know that anybody is supposed to post map issues in there).
Most likely, if you go that way, as I suggest, you will just need keeping closing issues reported in here and telling to reopen them in there (basically, people bug report in here and, after you verify that the problem is not in the engine, but in the map, just close the issue as invalid and tell to open it in Projects, instead).

Having the map issues tracked in Projects will also make easier to solve them, as anyone can contribute fixing any of them, not needing any particular skills, so it is better not to stay where you need to be a java developer, instead.

**Comment by Cernelius** [comment]
To make a partial summary, I think you should keep in a tracker (meaning in here), not in a forum, anything that has issues or it is deemed needing improvements, not only bugs (up to you to decide on each case).
Instead, changes of things that have no issues themselves or new/additive stuff or removal of any features, comprising features that have issues, if going the way of removing instead of fixing, I always said **should be kept and discussed in forum.**
I think "feature removal" is even more important to keep in forum than "feature request".
Finally, in the moment in which "feature request" stay there and "bug report" stay here, I believe you should clarify what is one and what is the other, for the casual user, as now where something stops being a bug is very unclear, and I've not even a clue where a new user is supposed to try to learn it, to then post in the right place.
I assume that if someone posts in here something that you believe is a feature request, you will close it as invalid and tell him to go in forum?
The clear example was what you intend to do with something like this:
https://github.com/triplea-game/triplea/issues/2150

**Comment by Cernelius** [comment]
I'm also quoting this from:
https://github.com/triplea-game/triplea/issues/2169

> Good idea. Though I think since this would be a feature request, it should be opened in the forum first :)

> I'm most interested in discussing how we could do this technically, I'm not requesting someone else to do the work. This issue is largely about technology, the UX improvement is hard to question and does not seem the least bit controversial if secure.
> 
> Would posting in forum help with that discussion? I suspect we would get more side tracked than anything else. Worse yet, long term the conversation thread would drop from relevance and would get lost.
> 
> I think it would be good to re-iterate the types of "feature requests" we want in the forums, topics that change game play, game rules, the UI in significant ways. Issues that are mostly straight technical I have trouble seeing the benefit of having be in two places. I do on the other hand see some issue, it's like going to the DMV to be first told you have to go the courthouse to come back with the right paperwork.

I see that you appear to go in the direction of having "feature requests" for the forum and "feature requests" for the tracker.
This is not what I was told here, that was that the "feature requests" were now supposed to stay fully in the forum.
However, I totally saw this coming, for the simple fact that, obviously, the forum is not the best place for tracking stuff.
So, instead, if you decide to split the "feature requests" here or in forum, then I believe you should give some guidelines about how that is being discriminated.
I don't believe you want to have feature requests here and there without a way and some guidelines to clarify how that should work.
I'm particularly not sure what "I'm not requesting someone else to do the work" means, in term of where to post the "feature request"? I would imagine that is relevant only if you are going to make a pull request.

Also, isn't this a "feature request" too? If so, again, why not in forum, then?
https://github.com/triplea-game/triplea/issues/2199

**Comment by Cernelius** [comment]
You have put in ice-box a lot of feature requests that are on about exactly the same level as this one, about adding a confirmation on finished downloads on map download page:
https://github.com/triplea-game/triplea/issues/2199

For example, this one about switching tab ordering on map download page (isn't it?):
https://github.com/triplea-game/triplea/issues/1864

So why switching tab ordering in map download page should not stay here, but go in forum, while having a confirmation in map download page should stay here, not in forum?
I would say that such things should both stay here, but, by all means, if you prefer to track them in forum, you decide the process. Just please decide it clearly, so that it is clear to anyone.
So, either explain why one is for forum and one is not, so everybody knows, or just open the new one in forum, not here, or reopen the old one out of ice-box.
If it is just me not getting it, and anyone else thinks the process is already clear and documented enough, no problem, this issue can be closed, then.

???

**Comment by Cernelius** [comment]
I would actually like this not getting forgotten (like probably most of the other feature requests now in ice-box, I guess):
https://github.com/triplea-game/triplea/issues/1864

So, you want me (or anyone) to reopen it in forum? Just asking confimation if you are sure that you want to track in forum also matters like just switching tab ordering on map download page. It will feel strange to me to open a forum discussion about that, but no problem for me.
