### ISSUE TITLE
5411: "Failed to create File association"

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#2037]
### My Operating System: 
Windows 7/64

### TripleA version: 
1.9.0.0.5411

### Map: 
irrelevant

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Installation granting admin privileges

### Do you have the exact error text? Please copy/paste if so

![tra](https://user-images.githubusercontent.com/20812775/27724705-63919b92-5d73-11e7-9f9e-f294a9aad5b5.PNG)

### Instead of this error, what should have happened?
File associations should be created

### Any additional information that may help:
./.

**Comment by RoiEXLab** [comment]
#2031 fixes this...
