### ISSUE TITLE
5419: Executed associated savegame does not load

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#2038]
### My Operating System:
Windows 7/64

### TripleA version:
1.9.0.0.5419
### Map:
irrelevant
### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Doubleclick on savegame, that is associated with TripleA
### Do you have the exact error text? Please copy/paste if so
TripleA starts, but savegame is not loaded
![aaa](https://user-images.githubusercontent.com/20812775/27740030-e5354710-5db0-11e7-8e39-23965d6646d3.gif)
You can see the savegame appearing for a short time on the left side, but then the last map loaded appears.
### Instead of this error, what should have happened?
The dialogue should show and go on with the savegame loaded.
### Any additional information that may help:
./.

**Comment by RoiEXLab** [comment]
@panther2 You are way too fast when it comes to find issues ^^
I knew already that this isn't working as expected, but good you created this issue anyway, because I never noticed the savegame was loaded for a short amount of time.
I thought it wasn't even loaded once.

**Comment by RoiEXLab** [comment]
#2039 has a fix

**Comment by panther2** [comment]
@RoiEXLab 

> Interesting: Loading savegames works perfectly, if the correct map is already selected.

I can't reproduce that, unfortunately.
In my given savegame I set Britain as AI-player and saved after R1 purchase.
After executing the savegame I experience the same as above: It is ture that the correct map will be shown, but the game starts as new game, ignoring the savegame status:

![aaa](https://user-images.githubusercontent.com/20812775/27748309-3f62ea30-5dcf-11e7-8e7a-af3794620b12.gif)

**Comment by RoiEXLab** [comment]
My theoriy isn't completely right then... 🤔 
#2039 should still work though

**Comment by RoiEXLab** [comment]
@panther2 Could you check if this is fixed in the latest pre-release?

**Comment by panther2** [comment]
Downloading...

**Comment by panther2** [comment]
@RoiEXLab 

So now, the savegame loads as expected. But when leaving the game the set-uo screen is reset to the former map again:

![tra](https://user-images.githubusercontent.com/20812775/27841230-e3b06a1c-60ff-11e7-990a-9f074dc52967.gif)

Video starts closing TripleA with G1940 active,
TripleA is closed,
Savegame v5 is doubleclicked,
Savegame is loaded and executed perfectly,
File - leave game brings us back to the,
Setup-screen - with G1940 being active again.

**Comment by RoiEXLab** [comment]
@panther2 This is a seperate issue (and was probably intended at some point).
Closing this issue.

**Comment by panther2** [comment]
@RoiEXLab 
I can live with that, just wanted to address it just in case it had not been intended.
Thank you anyway :smile:

**Comment by RoiEXLab** [comment]
No Problem, I just wanted to make clear this is more of a "feature-request" than a bug report.
Feel free to open an issue if this annoys you!
