### ISSUE TITLE
axisandallies.org - history and strategic fit

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#204]
@djensen47 : I've a lot of questions about axisandallies.org, my apologies for not having as much background on the subject as I would like.

- Would you mind giving some background on how axisandallies.org came to be and it's intended purpose?
- What unique functionality or features does axisandallies.org provide to tripleA not covered by other tripleA components already?
- Does axisandallies.org have a reason to exist as its own entity? Asked in another way, should tripleA consolidate redundant features with axisandallies.org, or should the two be treated as completely different entities?

**Comment by djensen47** [comment]
Prologue: don't delete this issue, I want to save my responses somewhere. :wink:

I started "David Jensen's Axis & Allies Archive" in 1997 to write articles about Axis & Allies as well as preserve other articles (that eventually disappeared, I was right). It didn't really succeed on that last front. In 200, I renamed it to axisandallies.org as a resource for strategies and house rules. I think the forums came along later that year or in 2001-2002.

> Would you mind giving some background on how axisandallies.org came to be and it's intended purpose?

The current purpose:
 1. Publish articles on strategy and house rules
 2. A resource for downloading rules 
 3. Promote events & playing the game
 4. Unofficially report official news about the game (as we know Wizards has done a horrible job of this)
 5. Create a vibrant community of Axis & Allies players (the forums)
 6. Enable and promote "play by forum" gaming

> What unique functionality or features does axisandallies.org provide to tripleA not covered by other tripleA components already?

TripleA is for game play with community in the form of the lobby. The only crossover is "play by forum." Unique offering is 1-4, maybe 1-5.

> Does axisandallies.org have a reason to exist as its own entity? Asked in another way, should tripleA consolidate redundant features with axisandallies.org, or should the two be treated as completely different entities?

They should be treated independently. For one TripleA is open source project and axisandallies.org is a business. I think a deep integration is mutually beneficial but I'm not sure which redundancies should be eliminated. I think people like using the forums to post their turns and coordinate the games (especially for organized play). But does axisandallies.org really need to host the files? Why don't the users of the game use their own Dropbox, Google Drive, or Evernote accounts?

**Comment by DanVanAtta** [comment]
@djensen47 , thank you for the detailed answer, documented here: https://github.com/triplea-game/triplea/wiki/TripleA-Related-Entities

#37 I believe covers games being posted to A&A.org.

Closing now that all questions appear to be covered.
