### ISSUE TITLE
Iron War always shows as needing update.

### ISSUE THREAD

**Issue by RogerCooper** [triplea-game/triplea#2056]
Iron War appears on the update tab, even after updating.

**Comment by ssoloff** [comment]
@RogerCooper I was unable to reproduce this problem using the latest pre-release version after manually forcing an update of Iron War (I reset the local version to `9.0` and then updated to `11.0`).

Could you please provide the following information:

* TripleA version
* Operating system
* The content of the `iron_war-master.zip.properties` file from your maps folder.  If you don't know where this folder is, you can find it in the Download Maps window:

![iron_war](https://user-images.githubusercontent.com/4826349/27837539-d7aa9c26-60b2-11e7-8b81-f42465930311.png)

**Comment by RogerCooper** [comment]
Version 1.9.0.0.3266
Windows X
#Wed May 24 21:46:20 EDT 2017
download.time=Wed May 24 21\:46\:20 EDT 2017
map.url=https\://github.com/triplea-maps/iron_war/archive/master.zip
engine.version=1.9
map.version=7.0

**Comment by ssoloff** [comment]
@RogerCooper I tried to reproduce using 1.9.0.0.3266 and your `.properties` file, but it successfully updated to version 11.

The only thing I can suggest you check is that the `.properties` file didn't somehow get set to read-only.  If TripleA can't write the new version to that file, the map will perpetually sit on the Update tab.  You can simply edit the file yourself and change `7.0` to `11.0` (presuming you've actually downloaded the latest Iron War map).

I actually tried this by setting my `.properties` file read-only, and when the download was complete, the TripleA debug console was opened with an error message indicating the file was not found.  I'm assuming if you saw such a message, you would have reported it. :smile:  So the read-only theory is probably invalid.

Somewhat unrelated, but I would suggest you upgrade to 1.9.0.0.3635, which is the latest official release.  Build 3266 predates that release by more than three months.

**Comment by DanVanAtta** [comment]
Let's re-open if we see this again or find a way to repro
