### ISSUE TITLE
Bot12 broken - connections to it frozen, can we debug it?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#208]
Any way to debug what is wrong with bot12? Currently it is broken, connecting to you it and you get a frozen java process, this is what it looks like right now (and the game is pretty much stuck in this state):

![bot12_broken](https://cloud.githubusercontent.com/assets/12397753/10183291/de93df96-66e2-11e5-9aa4-eea5588981ce.png)

**Comment by veqryn** [comment]
The bot logs is pretty much all you have to go on, especially when it is someone else's bot.  Fortunately the logs are pretty detailed (and you can always add additional logging if needed).
If you can guess what might have caused it, it is straightforward to set up your own bot while in debug mode, and then try to recreate the situation.
