### ISSUE TITLE
Project Tracking

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#21]
It's probably useful to have a list of items that have been identified as things to work on. I found the source forge ticket queue useful for giving some direction for some things to fix.

So, question: how are we going to track the existence of things we want to do, improve, fix, add, etc? Secondly, any thoughts how we will administer that list?

**Comment by ron-murhammer** [comment]
Umm? How is this issue different than #22? Seems like we probably just need one thread to discuss the tracking and prioritization of features/bugs/etc.

**Comment by DanVanAtta** [comment]
Tracking has not so much to do with prioritization, prioritization can have quite a bit to do with tracking. I spun this up originally as one thread, but talking about both topics as one is not very effective, I found myself going in circles.

**Comment by DanVanAtta** [comment]
Closing, this has been answered. github issues until it gets too complicated, in which case we'll track projects in JIRA.
