### ISSUE TITLE
Handle Infrastructure Placement Better

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#211]
Infrastructure and land unit placement is not a very nice process. Until all infrastructure is placed, specifying max units yields +1 units selected compared to the actual max. Here is a screenshot showing this problem, Tunis supports the placement of only 4 units, yet selecting max infantry yields 5, not 4:

![bunker_bug_allows_max_unit_to_be_5_not_4](https://cloud.githubusercontent.com/assets/12397753/10186094/1d3727d8-6703-11e5-94d0-fde4c255dfef.png)

A minimal fix would change the behavior so the max infantry button has a setting of 4, not 5 in this case.

Another possible more significant fix would potentially change the layout and split infrastructure and unit placement: 

![paint_mockup](https://cloud.githubusercontent.com/assets/12397753/10186390/7d0bf70e-6705-11e5-8f41-fd967e0a93db.png)

**Comment by gaborbernat** [comment]
I would place the infrastructure top, add a separator and there the
units. single column desing. Infrastructure does not need max button
:)

On 9/30/15, Dan Van Atta <notifications@github.com> wrote:
> Infrastructure and land unit placement is not a very nice process. Until all
> infrastructure is placed, specifying max units yields +1 units selected
> compared to the actual max. Here is a screenshot showing this problem, Tunis
> supports the placement of only 4 units, yet selecting max infantry yields 5,
> not 4:
>
> ![bunker_bug_allows_max_unit_to_be_5_not_4](https://cloud.githubusercontent.com/assets/12397753/10186094/1d3727d8-6703-11e5-94d0-fde4c255dfef.png)
>
>
> A minimal fix would change the behavior so the max infantry button has a
> setting of 4, not 5 in this case.
>
> Another possible more significant fix would potentially change the layout
> and split infrastructure and unit placement:
> ![paint_mockup](https://cloud.githubusercontent.com/assets/12397753/10186050/ba710560-6702-11e5-97e9-271a511e8900.png)
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/triplea-game/triplea/issues/211


-- 
 Bernát Gábor
Student -  Budapest University of Technology and Economics - Computer
Engineering, M.Sc. - Budapest, Hungary
System Integrator - Gravity R&D | Rock Solid Recommendations - Budapest
office | 5-7 Expo ter | H-1101 | Budapest | Hungary

**Comment by DanVanAtta** [comment]
Mockup updated (it's rough, should have a separator in it though doesn't yet)

**Comment by gaborbernat** [comment]
looks better for me :+1:

**Comment by ron-murhammer** [comment]
Yep. It would be great to fix this. Not sure what the code actually looks like though. I think the mockup looks good and is definitely an improvement.

**Comment by veqryn** [comment]
So, sometimes infrastructure actually does take up a normal slot.
I would only divide it when it doesn't take up normal slots.
You'll need to dig into the placement rules code a little more to figure this out.

**Comment by DanVanAtta** [comment]
To feature backlog: https://github.com/triplea-game/triplea/wiki/Feature-Back-Log
