### ISSUE TITLE
WarClub Forum - Read Only Voting and Archival Considerations

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2111]
Talking to @prastle , warclub forum came up and consideration if we should turn it read only.  Should we do that? I think it may make sense at this point to force new posts to be on the new forum and nothing new added to warclub forum. Would be an interesting landmark to see, just the one active (NodeBB) new forum.

Second, I do believe we would want to turn off the PHP software running warclub, which would be effectively us turning off xoops. My understanding is that this all runs on top of nginx, and we have the marti dice server also running. We would want to keep the dice server going for sure and only remove the PHP stuff.

It would be really great to archive a read-only version of the warclub forum. If anyone can figure out how to get a text dump of the forum posts, I'd like to help manipulate those files into markdown that we can then park on github.io (new website). The static content would then not be hosted by us anymore, and github doesn't charge for hosting it.

Also posted on forums about warclub going read-only: https://forums.triplea-game.org/topic/242/voting-to-set-tripleawarclub-org-forum-to-read-only

**Comment by RoiEXLab** [comment]
@DanVanAtta good idea porting the forum to gh pages...
We don't need to turn it into markdown, normal html is sufficient. 
I believe there are several tools which crawl Webservers and save every html page they can find.
Once everything is migrated we can come up with a better software solution for the dice server.

**Comment by ssoloff** [comment]
> We would want to keep the dice server going for sure and only remove the PHP stuff.

Doesn't MARTI require PHP?  Or is the "PHP stuff" you're talking about different "PHP stuff" than MARTI uses? :smile:

**Comment by prastle** [comment]
Yes @RoiEXLab  we could use the site u showed me

**Comment by RoiEXLab** [comment]
@prastle I don't recall a site I showed you, which one was it?
@ssoloff Yes MARTI runs on PHP on the same server, but compared to the xoops cms it would be very easy to just replace it with another language.

**Comment by prastle** [comment]
the one that showed history timeline of triplea.   i forget the name.  I used it to pull the old missing ladder rules and old ladder standings.  Digging now but cant find it.

**Comment by prastle** [comment]
https://web.archive.org/web/20160822045831/http://www.tripleawarclub.org/modules/comp/standings.php?lid=6

Found it

**Comment by prastle** [comment]
We would just need physically export the bunker then i think?

**Comment by RoiEXLab** [comment]
The biggest challenge is going to be an URL transform since jekyll does not support GET parameters, but with a couple of find and replace tools and a little bit of regex this should be possible in a feasible amount of time.

**Comment by prastle** [comment]
I might need some help in warclub.  Guests disallow was a switch flick.  Read only a long drawn out process of individual resets  by group times 7 groups etc.  @roiex can you look and see if there is an easier way?

**Comment by RoiEXLab** [comment]
@prastle Unfortunately I don't have the time right now...

**Comment by prastle** [comment]
np

**Comment by RoiEXLab** [comment]
@ssoloff @DanVanAtta @ron-murhammer I'd like to rewrite the MARTI software using another language.
(I'd use a URL like `dice.triplea-game.org` for the new software.)
Languages I'd consider are NodeJS or java + [spark framework](http://sparkjava.com/).
NodeJS is of course designed for Web-Applications and therefore well suited, but I just have some experience with it (just a little bit of coding for NodeBB plugins), the biggest challenges would be DB-Management/Access and deployment, although NPM makes stuff pretty easy.
Java on the other hand is the language we all know, and using this RESTful framework, we are able to write (and update) the needed code very fast and easily, but we'd need to convert certificates to the java keystore format every time if we want to use HTTPS at some point (letsencrypt provides renewal hooks so we could automate this process).

Also a question we need to consider: What DB should we use? Postgres?

Thoughts?

**Comment by DanVanAtta** [comment]
@RoiEXLab I'm thinking DropWizard to help us with the network protocol. It would be pretty easy to send JSON payloads back and forth. We then just need a system to map JSON to objects, and a mechanism to convert messages to JSON.

If we go with that for lobby, it would I think make sense to re-use that same java infrastructure. Java certs not the most fun, though it's about as easy as it perhaps can be with drop wizard. A lot of it comes down to using the `keytool` command to drop a keystore file in a magic location, then launch with JVM args pointing to that file.

The dice roller should be pretty simple, a trivial NodeJS application is hard to object to, so no strong objections here if we go that direction. 

> Also a question we need to consider: What DB should we use? Postgres?

I wonder if we can avoid a DB? What do we need one for? Would it be possible to re-use the lobby or forum?

**Comment by RoiEXLab** [comment]
@DanVanAtta Good idea using JSON.
JSON would make all of this stuff so much easier, no need to search for specific strings and extracting the necessary data using regex.

AFAIK A Database is currently needed to have a list of all registered emails (probably to avoid spam using our servers).

**Comment by ssoloff** [comment]
@RoiEXLab You might be able to get some ideas from [here](https://github.com/ssoloff/dice-server-js).  It's more of a toy example and doesn't meet all the requirements of a TripleA dice server, but it has an RPC-like JSON [API](https://github.com/ssoloff/dice-server-js/wiki/API), and it attempts to solve the dice roll integrity problem via JSON web signatures.

**Comment by RoiEXLab** [comment]
@ssoloff I digged into the MARTI code and the essential part is the de- and encryption part.
MARTI decrypts using the Rijndael-256 algorithm using it's own secret key. Should we continue using that algorithm or should we just use plain AES-256?
Or should we use a completely different attempt which essentially gets rid of email requirements and uses the savegame to store a signed dice roll string which can be verified using the servers public key?
Another question is if we should drop email

**Comment by ssoloff** [comment]
@RoiEXLab I'm not sure that the dice roll information needs to be kept secret.  Hence, use of encryption to "hide" the data is probably not necessary.  Presumably, MARTI is using encryption as a form of integrity checking to verify a dice roll hasn't been modified.  Signing the dice roll should be sufficient.

I don't know what the original motivation was for MARTI requiring email registration.  Simply to require some kind of identity verification before allowing use?  IDK.  But it would be ideal if the dice server could be totally stateless.

**Comment by RoiEXLab** [comment]
@ssoloff @DanVanAtta Some updates on the dice server software:
I had to rewrite all of the code, still not finished. Although I wanted to get rid of the email verification thing, we need to keep it, I found no way of ensuring valid dice rolls (including scenarios where users want to reload the savegame if they had bad luck with the dice rolls) without cluttering a database full of dice data which we wouldn't know of if this data will actually be used in the future, so we can't remove it after a game.
So the important question is which database to use (When we have to use one we can also store our keys in it): PostgreSQL or MongoDB?
This depends on the server we wanbt this software being deployed on.
Same server as lobby = PostgreSQL
Same server as forum = MongoDB

**Comment by ssoloff** [comment]
@RoiEXLab 

> So the important question is which database to use

If there's no compelling technical reason to choose one over the other, I'd go with whichever one is going to make life easier for a triplea-game.org admin.  For example, do admins spend a larger portion of their time managing the lobby database vs. the forum database?  If so, then they probably have many Postgres console commands memorized, whereas they may have to do a search to remember how to do something in the Mongo console.

**Comment by DanVanAtta** [comment]
My vote is for postgresql, keep the forum software isolated to itself as much as possible.  I read this recently: http://hackingdistributed.com/2013/01/29/mongo-ft/, not very flattering of mongo, and hence also why I would opt for postgres.

**Comment by RoiEXLab** [comment]
@DanVanAtta I did some research on ways to turn the forum to a jekyll site.
I found ninja crawler, a crawling software that allows for custom hooks: https://github.com/christophebe/crawler.ninja
Using this software we will be able to download every available site on the forum and safe ist as static page. The only thing that could potentially not work is when jekyll doesn't support permalinks containing get Parameters like `/forum.php?id=1234` so if anyone of you could check if this works I would appreciate it very much.
The only downside on cloning the website will be that we can't clone the hidden parts e.g. Bunker topics as there's no security on jekyll.

**Comment by RoiEXLab** [comment]
Sad news: Jekyll is (currently) not supporting GET parameters as permalinks, therefore it's not possible to convert the forum to jekyll without invalidating existing links.
A workaround would be to host a routing server on our own, which simply redirects the old links to the new links by using tge same conversion algorithm. 

Thoughts @DanVanAtta?

**Comment by RoiEXLab** [comment]
Also worth noting: The Warclub forum has what seems to be a crawling/sql-injection/ddos protection.
So I managed to ip ban myself for a day twice today while testing :D (I unbanned myself using a proxy)
I have a script to clone the server ready, might need some smaller Tweaks when it comes to forms etc. But should work for the most part.
I will upload the code to a repository when I have the time.

**Comment by RoiEXLab** [comment]
Also another potential solution for this issue: we could redirect clients via javascript. This way we wouldn't need an additional server, but would require javascript on the client

**Comment by DanVanAtta** [comment]
> Sad news: Jekyll is (currently) not supporting GET parameters as permalinks, therefore it's not possible to convert the forum to jekyll without invalidating existing links.
A workaround would be to host a routing server on our own, which simply redirects the old links to the new links by using tge same conversion algorithm.

Is a bit sad news, not a fan of extra complexity for something we are just trying to deep freeze. Regardless, once this is set up, we are intending designing for the content to be frozen, so as long as whatever we choose can remain stable, should be fine IMO.

**Comment by RoiEXLab** [comment]
@ssoloff In case you are interested: Heres the code for my website cloning script: https://github.com/RoiEXLab/jekyllifier
Since you have some experience with node.js I'd appreciate any feedback...
Note that the code is far from being final, but the basic cloning works

**Comment by RoiEXLab** [comment]
@ssoloff I pushed my first "working, but not really" alpha version to git. There's still a lot to do, so I created a todo list: https://github.com/triplea-game/dice-server-js/issues/1
Any insights and suggestions (also commits of course) would be really helpful! @DanVanAtta @ron-murhammer
