### ISSUE TITLE
Great War bug

### ISSUE THREAD

**Issue by Leijonma** [triplea-game/triplea#2120]
Dear triplea!

When I played Great War as CP today against Al on hard mode and tried to save the game it was not saved at all even the saving procedure was formally correct. Was the same yesterday too.

I have saved other games such as Big World before on triplea without problems.

In addition I failed when trying to enter OR leave Western Front with my units. Have not find any instructions on how to do this new kind of movement. My malpractice or bug?

In addition when building as Germany there is a display on what units you build. It said 70 artillery units 
even if it was only 7 in reality. This only happened once.

Greatful for help when You have time.

Leijonma

### My Operating System:
Windows 10
### TripleA version:
1.9.0.0.3635
### Map:
Great War version 4.4
### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
When I opened saved game only startup situation appeared on screen.
### Any additional information that may help:

EDITED BY @RoiEXLab

**Comment by RoiEXLab** [comment]
We need more information than "it's buggy" in order to resolve any issues.
Closing as invalid for now, will reopen once any additional information has been added...

**Comment by Leijonma** [comment]
# 2120

TripleA_1.9.0.0.3635

Windows 10

map Great War version 4.4

When I opened saved game only startup situation appeared on screen.

Leijonma

Skickat från min iPhone

21 juli 2017 kl. 14:01 skrev RoiEX <notifications@github.com<mailto:notifications@github.com>>:


Closed #2120<https://github.com/triplea-game/triplea/issues/2120>.

**Comment by RoiEXLab** [comment]
You still need to press play after loading a savegame...
Is an error message showing up? 
If so could you post it here?

**Comment by RoiEXLab** [comment]
I merged @Leijonma's posts in case anyone wonders

**Comment by Leijonma** [comment]
Hallo!

I am able to save Great War now by using .tsvg ending on file name. Without no save.

I am able to move in and out of the special map boxes by clicking on the target areas IN the boxes.

I am able to move naval units around the world using arrow conections.

Sincearly

Leijonm

Skickat från min iPhone

21 juli 2017 kl. 16:48 skrev RoiEX <notifications@github.com<mailto:notifications@github.com>>:


I merged @Leijonma<https://github.com/leijonma>'s posts in case anyone wonders
