### ISSUE TITLE
Units Cannot Move (1.9.0.0.5785)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#2121]
All units in Susa are unable to move.

[BUG_20170721_270BC_40%.zip](https://github.com/triplea-game/triplea/files/1165582/BUG_20170721_270BC_40.zip)

**Comment by Cernelius** [comment]
To be clear, this is a bug: those units in Susa should be able to move, while they all cannot, for no reasons.

**Comment by simon33-2** [comment]
Has this bug been fixed? I can reproduce it in the save game but I expect the problem has already occurred at this point.  Problem really is that the units don't get movement.

Can it be reproduced from an earlier point in the game?

**Comment by Cernelius** [comment]
I cannot answer as a matter of fixing, as I've not tested the new engines since some months.

Aside from this, in my experience, this bug happens consistently but rarely, and I've not seen a pattern. So, I've no clue if it is possible to create the conditions under which this bug will happen and what these conditions may be. I believe this bug is commonly encountered, albeit rarely, but people simply edit the moves and don't report the issue. I think anyone who played a lot had this bug several times.

I cannot be sure, but I think you should approach this as a purely random occurrence, that sometimes movement is not given to the units.

The only think I know is that, when this bug happens, it is per territory and it always applies to all units in a territory and happens to a single player turn and one or more territories.

I know of no other ways of reproducing this but keeping playing till it happens, which I recall being something like once every some tens of hours or so, of realtime human vs human games.
