### ISSUE TITLE
Improving Test

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2138]
Goal of this issue:
- talk about testing TripleA
- identify the areas that most need help in terms of testing
- identify key tests that will give us the best bang for the buck, save us time and do the best to ensure games won't crash

Motivation, what problem are we solving?
- "Test the crap out of it! Let there be no errors damn it!"

-------------

We still can have issues with RMI and other calls via reflection. There may be an opportunity to add more compile time checks to help us avoid errors.

As a suggestion, I'll be curious what setting up two AI's to play against one another server/client would look like. We could check for errors, player 3 or 5 rounds, have a few special save files to check special rules, and potentially cover a good number of maps. I'm pretty interested in this idea and will try to investigate it a  bit more.

**Comment by DanVanAtta** [comment]
My current thinking:
- not doing all release testing at merge time is good, lowers the bar a bit so we can move a bit faster and clean up when we are ready and need to
- form a test group to help scale out the testing process, add more headcount to regression testing
- simply track the test efforts of that group by release. Can gain information on which ones have been tested and occasionally converge on testing specific versions.

**Comment by DanVanAtta** [comment]
Related - Play testing group forum post: https://forums.triplea-game.org/topic/268/volunteers-needed-early-release-testing-group

**Comment by prastle** [comment]
I am just going to say bump.  and read the forum link.  since it seems i'm the only one posting to the spreadsheet :) @DanVanAtta

**Comment by DanVanAtta** [comment]
Indeed, we could use more testers. I'm intentionally not signing up myself given existing responsibilities and also that we want testers partly so the developers can focus on coding a bit more and less of the extensive regression testing.

Documenting as well a preferred way for bugs to come in would be useful. Keeping track of them in forums is not going to work well, we do need them as github issues.

**Comment by DanVanAtta** [comment]
closing for now, forum post seems to be carrying this thread.
