### ISSUE TITLE
Support Attachment Unit Type Tooltips Display Correction Request (1.9.0.0.5855)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#2150]
The current tooltips read something like:

_gives 1 Power to 1 Allied Chasseurs/Fusiliers/Grenadiers and Marines when Att/Def_

This is logically wrong, as it would mean that they support all of them, 1 each, while, instead, they support 1 of them.
Thus they should read:

_gives 1 Power to 1 Allied Chasseurs/Fusiliers/Grenadiers or Marines when Att/Def_

But I definitely rather suggest them being:

**_gives 1 Power to 1 Allied Chasseurs/Fusiliers/Grenadiers/Marines when Att/Def_**

(not having any "and" or "or", but just strokes)

Moreover, they are currently ordered alphabetically, while I believe it would be better they have the same order given in "unitType", so that the mapmaker can decide the display, in this case:

`<option name="unitType" value="Fusiliers:Marines:Chasseurs:Grenadiers"/>`

would become:

_gives 1 Power to 1 Allied Fusiliers/Marines/Chasseurs/Grenadiers when Att/Def_

**Comment by Cernelius** [comment]
Also, I suggest removing " when Att/Def" if they can support both in attack and defence. It is not needed to specify a situation if they always support and it keeps the description a bit shorter and "when Att/Def" doesn't read well, anyways (it should be "when Attacking/Defending", but this would be really too long for something that it is not needed).

**Comment by ron-murhammer** [comment]
@Cernelius Please open in feature request sub-forum so we can track them in one place.
