### ISSUE TITLE
List Bombard Ships By Bombard Value In Battlecalculator (1.9.0.0.5855)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#2153]
In the battlecalculator, on Land Battle, bombarding ships are listed by their attack power, which is pointless, while they should be listed by their bombard power, instead.

Meaning that they are currently listed by:
option name="attack"

while they should be listed by:
option name="bombard"

(bombard defaults to attack if missing)

**Comment by ron-murhammer** [comment]
@Cernelius Agree with the change but as we are moving all feature requests to the forum, I'd ask that you create a thread there discussing improving battle calc unit order for bombard units.
