### ISSUE TITLE
String localization

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2157]
It seems logical for us to support multiple languages. Thinking about this sooner and extracting strings earlier would make such a transition far easier.

Looking around, I was expecting to see some pretty slick localization frameworks but did not see very much that was all that appealing. I saw type-unsafe approaches with strings in-code: http://docs.oracle.com/javase/tutorial/i18n/resbundle/examples/StatsBundle_en_CA.java.

Other approaches I see switch between resource files. It's pretty easy to load properties, so some of this can be slick but it seems overkill for what we need.

----------------

Some requirements to clarify and discuss:
- I think it would be ideal if all string languages were side by side and not in different files. So we would have something that looks like this:
```
play_game_button:
  en: 'Play'
  fr: 'Jouer'
  ru:
```
I think the above would make it easier to keep things organized/consistent. For example we know easily above we are missing the 'ru' translation. With multiple files, props can get re-ordered and it may be more difficult.

-------------------

#### Java data representation

I was first thinking an enum to capture the translations, though that does not work out very naturally. On the other hand, a yaml file I think would work  well.

**Comment by RoiEXLab** [comment]
@DanVanAtta JavaFX supports internationalisation...
Have a look at [this file](https://github.com/triplea-game/triplea/blob/master/src/main/resources/org/triplea/client/ui/javafx/lang/TripleA_en_US.properties). We could create such a file for every other language. 
Currently the language setting is hardcoded, but I plan to implement a feature which scans the language directory for language files and adds them to a combobox enabling the user to choose between every available language.

**Comment by DanVanAtta** [comment]
> "I think it would be ideal if all string languages were side by side and ***not*** in different files."

Is there any way to group the translations to one file?

Can we decouple this project from JavaFX and have an easy transition, what would that look like?

**Comment by RoiEXLab** [comment]
I don't think so, the language files are simple properties files, but IMO this keeps things clean.

Of course we don't need JavaFX for this, but I was thinking that before we put too much effort in creating a language system, we might go ahead and work on the javafx gui instead which has built in support for localisation.

**Comment by DanVanAtta** [comment]
Multiple files can be a real PITA. If a key changes you have to update the property key in N places. N files to update vs 1. If we get to 15 languages somehow, I prefer the idea of copy pasting one block of text to get a new string than adding a property key to 15 files.
 
A property key lookup framework is pretty simple.

> Can we decouple this project from JavaFX and have an easy transition, what would that look like?

I find it hard to think we cannot. Swing AFAIK can be done to use localization as well, is it actually that different between the two? I do think a very simple custom route can be taken to the benefit of far easier management of the translations in a single file.

**Comment by DanVanAtta** [comment]
Apologies, did not read this very well:

> Of course we don't need JavaFX for this, but I was thinking that before we put too much effort in creating a language system, we might go ahead and work on the javafx gui instead which has built in support for localisation.

As far as a framework, I think it would be a really trivial amount of code:

```
new JButton(Strings.PLAY_GAME);
```

```
public enum Strings {
   PLAY_GAME
}
static YamlReader reader = new YamlReader(pathToLanguageFile)

static void setLanguage(String language) {

}

@Override
 public String toString() {
    return yamlReader.readProperty(this.name(), language);
 }
```

**Comment by DanVanAtta** [comment]
So the custom code looks to be really easy, I think arguably one YAML file would be easier than N properties file. Perhaps that is  a first point to agree on. If we do, then we may easily eliminate most built in frameworks on those grounds.

Moving beyond that, we would want to double check existing frameworks. With 'n' files likely there will be something. Considering a custom framework is likely to be quite simple, it's somewhat compelling to go with one. We also get the benefit we can get cracking on it now and start working on translations. If there is then a good migration path to JavaFX from there, I think we would have done well.

**Comment by RoiEXLab** [comment]
@DanVanAtta If we have a yaml file in the first place, we could easily split this file into multiple ones using small little scripts, so that shouldn't be too difficult.

**Comment by ssoloff** [comment]
What @RoiEXLab just said reminded me of something...

I once worked on a project that had a pretty huge L10N burden (they translated the product into something like 35 languages).  The G11N team wanted something like @DanVanAtta suggested, and have everything in one place and in a non-dev-friendly format so it would be easy to change (as they were the ones responsible for doing that).  However, the dev team didn't want to "fight their tools," and insisted on keeping each language separate at runtime and in their dev-tool-of-choice's preferred format.

The compromise was to have a separate repo for the G11N team, where they worked with files that contained all languages, in whatever format they wanted.  When those files were pushed, it triggered a build where a script was run to break up the monolithic files into corresponding properties files per language, which were then automatically committed to the dev team's repo at the end of the build.

Using a separate repo for translations is probably overkill for this project.  But maybe generation of the `.properties` files from the `.yaml` file as part of the Gradle build is worth investigating.  That way, we make editing the file easier (especially for non-devs who will probably be doing the heavy lifting), and we can use the existing Java resource bundle system.

The only issue I foresee is ensuring an IDE build runs the appropriate `processResources` task so running/debugging from the IDE does not complain about missing (or outdated) `.properties` files.  I believe the Eclipse Buildship plugin for Gradle does this, but we would have to verify.  Not sure how IntelliJ handles the Gradle `processResources` task.

**Comment by DanVanAtta** [comment]
What if the task were to simply splits the files up and then we check in the output? 
Some benefits:
- no extra IDE tooling
- no additions to the travis build
- can test updates out locally without check-in or updates in other repo's

**Comment by ssoloff** [comment]
:+1: Sounds like a logical first step.  If we are ok with the manual workflow, we just keep it as-is.  If it becomes overwhelming in any way, we can always pursue automating it at a later time.

**Comment by ssoloff** [comment]
One thing to keep in mind with the manual workflow: the onus will be on the reviewer to ensure a PR doesn't contain direct modifications to one of the `.properties` files without a corresponding change in the `.yml` file.  For PRs with large UI changes, that might be challenging.  Although, it could be as simple as the reviewer checking out the PR branch locally, running the YAML split task, and verifying that there are no diffs.

**Comment by RoiEXLab** [comment]
To revisit this topic, I like have no objections on having a yaml file, I'd like having a consistent scheme like this though:
```
# Scheme:
viewname: # Something like main, downloadmaps, preferences, everything lowercase
  guiobjecttype: # Something like JComponent, JLabel, everything lowercase
    guiobjectname: # Something like title
      # Refer to https://docs.oracle.com/javase/8/docs/api/java/util/Locale.html for more details about valid langcodes
      langcode: "Translation"

# Example; how the TripleA_en_US.properties file would look as yaml:
main:
  text:
    title:
      en_US: "TripleA"
      de_DE: "TripleA" # Would fall back to en_US or alternatively the first entry if not present here, but on ther positions
    subtitle:
      en_US: "The Worlds foremost Open-Source Grand Strategy Game"
      de_DE: "Das große, weltweit führende Open-Source Strategie Spiel" # Terrible translation btw :D
```
This is how I load in the file in JavaFX:
https://github.com/triplea-game/triplea/blob/a701f157eafcbbdee0d5c8493853cd24c3b61987/src/main/java/org/triplea/client/ui/javafx/FxmlManager.java#L43
Far from being final, the code should eventually detect all available language files, and list them in a settings-menu-combobox.
I believe it's possible to have ResourceBundle to automatically fall back to en_US or whatever.
