### ISSUE TITLE
Passwordless lobby login - Options and Design

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2167]
We would like to encourage user registration. Passwords are a PITA, to make logging in as a registered user I propose we add a passwordless lobby login system. Failing any better alternatives, I was thinking the passwordless system could store a local encoded hash that is sent to the lobby. Access to the file system could compromise this, so we would want to be sure we ask for the original password for anything sensitive.

What do people think? Are there other, better alternatives? If this sounds workable, any further thoughts on how we could do this specifically?

**Comment by prastle** [comment]
Well im a NOOB to this ...

But wouldn't it be easier if ya just force them all to re register to lobby?

You have joined an extinct LOBBY please rejoin here?

just a thought

**Comment by ssoloff** [comment]
Take a look at the `g.s.engine.pbem.CredentialManager` class we recently added in #1955 to protect PBEM/PBF credentials stored locally.  There's no reason that class couldn't be extracted to a non-PBEM-specific package and used to store the user's lobby credentials, as well.

IMO, user's should be able to opt-out of any kind of credential storage (even if it's encrypted), so I would again recommend doing what we did for PBEM/PBF and have a "Remember me" checkbox on the lobby login dialog.  The user's credentials would only be saved if this checkbox was selected.

> Access to the file system could compromise this, so we would want to be sure we ask for the original password for anything sensitive.

The current `CredentialManager` implementation is susceptible to an attacker gaining access to the user's file system and obtaining the key we use to encrypt credentials.  The key is stored in a location that has permissions restricting access to only the user, but if the user's account were compromised, or the user were tricked into running malicious code, all of the user's credentials could be disclosed.

`CredentialManager` is already set up to use a user-specified master password, although we always provide a randomly-generated value at this time.  Giving the user an option to provide their own master password, and prompting them for it the first time they need to access a credential, would give security-conscious users the ability to defend against the key-in-the-filesystem attack.  You could probably also use that to force re-authentication at critical points where a) you really want to make sure the user is who you think they are, and b) they really want to perform the action.  That's a big enough task that it would probably be better to do it in a PR separate from storing the lobby credentials.

**Comment by DanVanAtta** [comment]
Good feedback. Let me clarify goals + requirements:
- be able to login to lobby without typing a password (likely assumes an opt-in check box on first time logging in with password)

**Comment by prastle** [comment]
So to clarify, any users must login once then to be recalled? in future by the engine? similar to email etc?  If they choose to be recalled?  

To bring up a few old issues that I had hoped were being eliminated...

1 - name stealing ( they didn't password )
2 -trolls ( no accountability )

Hell long list talked about forever over the years by many mods

Hopefully I'm missing something here...

**Comment by DanVanAtta** [comment]
This ties into that.
One reason to not register and use a password is that it is an annoyance (having to enter the password), and then there is little benefit to registering. The idea here is to reduce the annoyance side of this equation while we other projects would increase the benefit to registering. This would then hopefully give people a reason to register.

**Comment by prastle** [comment]
I apologize for being skeptical but in my opinion not registering = someone that isn't serious about playing and thus is possibly a troll.  This of course doesn't include first time users.  Since their are often new names every day in the lobby (unlikely new players all of them).  I don't think i quite follow you.

**Comment by DanVanAtta** [comment]
cost/benefit of registering, today it is all cost no benefit.
typing password to login = PITA
getting name stolen = low risk, low benefit

If someone asks, should I register, unless they value name stealing, they will not. Gaining mod abilities is a reason to register, it is the only reason I registered.

The goal here is to discuss ways we can make it so registering is nothing but roses : )

**Comment by prastle** [comment]
Ok  reasons:
one your name cant be stolen
two you could become a mod
three no access to forum (other than guest read ability)
four no access to ladders
five (if it ever occurs) no statistical results 

OH WAIT!  that's as it is now ... hows that working?

Yes i know im an ass sometimes but just being blunt and truthfull

**Comment by DanVanAtta** [comment]
yeah, TBH none of those are terribly compelling. I went with no password until I *was* mod. Even though I almost would have a second account the password is annoying enough. Regardless, this is not a debate about the pron/cons of registering. The goal here is to look at technical ways to avoid entering in login password every time.

**Comment by prastle** [comment]
Might i ask why? Why is it you want players that can change names and abandon 20 min into a game and choose a new name to not require a password?  I seem to recall an idea you had about some how noting in lobby anonymous logins?  I am am not even asking for that.  All i am asking for is that players must register so the chaos of past doesn't continue in the future.  End of rant.   

The one thing i think you fail to realize is what you are promoting is for all lobby members to ignore any new name.  (IT COULD BE AN ASSHOLE!)

**Comment by DanVanAtta** [comment]
> choose a new name to not require a password? 

No, you will need a password if you register. The 'passwordless' feature is a checkbox option on login that stores a secure hash token on your server that on the next login could be presented in lieu of the user typing in their password.

**Comment by DanVanAtta** [comment]
Putting it in lay terms:
-> if on login you check this box, your password will be converted to a 1024 character long text value or longer. 
-> That value will be stored on your computer 
-> instead of sending your password to server, the 1024 long text will be sent
-> the server can match the long text instead of matching your password to authenticate.

So if someone else is on your computer, they can log in as you, or if you switch computers you would need to enter your password.

**Comment by prastle** [comment]
unless it is traceable through database anonymous logins still = huge headache

So that I can be clear.  I have np with random names.

I have a huge problem with chasing 30 of them that are same guy..

**Comment by prastle** [comment]
example jimmy etc etc

**Comment by prastle** [comment]
thus why many mods quit or stopped

**Comment by DanVanAtta** [comment]
Ya, as discussed the best way to deal with it is to add value to registering. Anon trolls will never go away fully.

**Comment by prastle** [comment]
Guess i disagree.  I'd say make them login and traceable.  
Thus when ya get a troll it can be dealt with simply. 
I truly hope i am incorrect in my viewpoint.  But with the loss of prob half the mod staff I doubt it tho.

GLHF

**Comment by DanVanAtta** [comment]
@prastle You clearly do not quite have full context as to what is being proposed! Even if everyone was forced to login, this would be a useful feature. Let's say we did force everyone to register, they would have to type their password every time to login. This feature would avoid that.

**Comment by prastle** [comment]
Takes only a second. Myself I want them all to have to type.  It elims easy access.   Maybe if they have to type they troll less.  Either way i believe if ya want to login and use free bots ya have to register.  
AHA!
There ya go ya asked for a motivational login requirement ....
 Free bots are only provided for registered members ...

**Comment by DanVanAtta** [comment]
From the perspective of making it more annoying to register before trolling, that makes it a tiny bit harder (emails are a dime a dozen, registering does *not* solve trolling). From the perspective of making the game easier for first time players so that they may become long time players it is a big step backwards. Far more important to optimize for a good game experience that will keep 999 out of 1000 players happier and make the game better for them.

**Comment by DanVanAtta** [comment]
@prastle I enjoy the debate, but it was all off topic. I"m at fault as well. If any dev wants to help weigh in on this issue, that is a *ton* of off topic crap they have to read. It basically buries this issue. We do not want it to be a 10 minute task to just read a ticket. I"m going to re-create this topic, issues need to be kept short and on-topic to stay effective.

**Comment by DanVanAtta** [comment]
https://github.com/triplea-game/triplea/issues/2169
