### ISSUE TITLE
passwordless lobby login

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2169]
A feature for registered users, do not require password to be typed on login. For here, discussion of how to accomplish this. `CredentialManager` seems to be a candidate.

**Comment by prastle** [comment]
Now that I know what your asking for. I agree i am sorry for yesterday.  I didn't understand where you were going with this.  A small input to your idea. When registered they don't need to type forum password either to join forum tie them all together.

**Comment by ron-murhammer** [comment]
Good idea. Though I think since this would be a feature request, it should be opened in the forum first :)

**Comment by DanVanAtta** [comment]
I'm most interested in discussing how we could do this technically, I'm not requesting someone else to do the work. This issue is largely about technology, the UX improvement is hard to question and does not seem the least bit controversial if secure.

Would posting in forum help with that discussion? I suspect we would get more side tracked than anything else. Worse yet, long term the conversation thread would drop from relevance and would get lost. 

I think it would be good to re-iterate the types of "feature requests" we want in the forums, topics that change game play, game rules, the UI in significant ways. Issues that are mostly straight technical I have trouble seeing the benefit of having be in two places. I do on the other hand see some issue, it's like going to the DMV to be first told you have to go the courthouse to come back with the right paperwork.

**Comment by simon33-2** [comment]
Can we use an ssh key to log in rather than usernames and passwords. It never ceases to amaze me that well into the era that these are easily obtainable for free, they are not in common usage and the somewhat inferior alternative of usernames/passwords are the norm.

**Comment by DanVanAtta** [comment]
That's a good idea, better to not  re-use the users password for this.

**Comment by RoiEXLab** [comment]
I was thinking more of something like an OAuth token in order to authenticate without having to store the actual password.
When changing the password or doing another "security relevant" task, the real password should be requested though.

**Comment by ssoloff** [comment]
@DanVanAtta Does #2395 resolve this issue?  Or are you anticipating a bigger, more fundamental change?

**Comment by DanVanAtta** [comment]
I believe #2395 resolves this exactly - thank you!
