### ISSUE TITLE
Cursor Disappears

### ISSUE THREAD

**Issue by prastle** [triplea-game/triplea#2185]
When launching a hosted game this chat error appears which I believe @ssoloff  has reported elsewhere.

triplea.engine.version.bin:1.9
Aug 07, 2017 11:32:41 AM games.strategy.engine.chat.ChatController joinChat
INFO: Chatter:prastle port:3300 ip:2001:0:5ef5:79fb:c0a:3ad7:3f57:ff9b is joining chat:games.strategy.engine.framework.ui.ServerStartup.CHAT_NAME
host:45.79.144.53 port:3304
Loading map: age_of_tribes, from: C:\Users\john\triplea\downloadedMaps\age_of_tribes-master.zip
Loading resources from the following paths: [C:\Users\john\triplea\downloadedMaps\age_of_tribes-master.zip, C:\Program Files\TripleA\assets]
Loading map: age_of_tribes, from: C:\Users\john\triplea\downloadedMaps\age_of_tribes-master.zip
Loading resources from the following paths: [C:\Users\john\triplea\downloadedMaps\age_of_tribes-master.zip, C:\Program Files\TripleA\assets]

  It is not map specific as it occurs in v3 41 and a couple others using the 1.9.0.0.6056 Engine. / Windows 10

After the initial combat move the cursor disappears but it is still there but invisible.  Also once combat is done the purchase/production box appears but is blank.  If exited the normal production box appears.

**Comment by ssoloff** [comment]
There are three separate issues reported above.  Two of these issues have been previously reported:

> When launching a hosted game this chat error appears

#1950

> Also once combat is done the purchase/production box appears but is blank. If exited the normal production box appears.

#2184

Therefore, this issue should specifically focus on

> After the initial combat move the cursor disappears but it is still there but invisible.

I've been able to reproduce the disappearing cursor in 1.9.0.0.6072 playing a local game using WW2 Classic: Iron Blitz 3rd Edition.

**Comment by prastle** [comment]
thxs @ssoloff

**Comment by ssoloff** [comment]
@prastle The fix for this issue is in build [1.9.0.0.6105](https://github.com/triplea-game/triplea/releases/tag/1.9.0.0.6105) or later.  Please re-open this issue if you still encounter the problem.
