### ISSUE TITLE
Checkstyle: Options for fixing ConstantName violations in Matches

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/triplea#2191]
When we enabled the ConstantName Checkstyle rule, it raised a significant number of new violations in the `Matches` class.  `Matches` uses PascalCase for a large number of constant (i.e. `static final`) field names.  These fields violate the ConstantName rule, which requires such a field's name to be either camelCase or UPPER_SNAKE_CASE.

The purpose of this issue is to discuss how we should rename the fields that are raising a Checkstyle violation.

`Matches` currently uses the following naming conventions for members that store or return a `Match` instance:

* Fields
    * PascalCase
    * camelCase
* Methods
    * camelCase

The options for renaming the PascalCase `Match` fields are the following:

* UPPER_SNAKE_CASE
* camelCase

Note that `Match` is an immutable type, which might suggest that UPPER_SNAKE_CASE is the appropriate naming convention.  (While it shouldn't drive the selection of one option over another, it should be noted that UPPER_SNAKE_CASE will lead to longer field names in many cases, which could require significant reformatting.)

If UPPER_SNAKE_CASE is selected, should the existing camelCase fields be renamed to match this convention?

If camelCase is selected, should all `Match` fields be converted to methods?  I'm only asking this because:

1. `Matches` is inconsistent in that it uses both fields and zero-arg methods for `Match` instances that do not require additional parameters.
1. The use of fields imposes a certain ordering because many fields are dependent on other fields.  If these fields were methods, there would be no ordering constraint.
1. `ProMatches` uses methods exclusively, even for `Match` instances that do not require additional parameters.

**Comment by ron-murhammer** [comment]
I kind of lean towards methods and camelCase since I think it ends up being shorter for references and a lot of match names are fairly long.

**Comment by DanVanAtta** [comment]
If the fields are final + immutable, our style rules say screaming snake case, otherwise camel. IMO let's not overthink it.

**Comment by ssoloff** [comment]
@DanVanAtta Agreed that the `Match` fields should be renamed to UPPER_SNAKE_CASE.

However, do you think it's more appropriate to convert those fields to methods at this time for the reasons listed above?  The primary reason I'm leaning towards that option is for consistency.  Seeing something like the following could be distracting:

```java
Match.allOf(
    Matches.UNIT_IS_SEA,
    Matches.unitHasAttackValueOfAtLeast(2))
```

vs.

```java
Match.allOf(
    Matches.unitIsSea(),
    Matches.unitHasAttackValueOfAtLeast(2))
```

Especially given that IDE syntax highlighting (at least on Eclipse) renders the constant field in **_bold italics_**, while the method is rendered normally.

**Comment by DanVanAtta** [comment]
I'm not a fan of screaming snake case everywhere, but that is personal preference. It would seem to me there is less guess work with the methods, I would consider whichever is easier to use, less error prone and less to remember.

Personally, I might go in a different direction, much of the `Matches` code has seemed very procedural to me. For example, I would much prefer a `unit.isSea()` method vs a `Matchers.doMatch(unit, Matcher.isSea())`. Even better, a method that would return an enum, so then you could do something like `unit.getType() != UnitType.SEA`, instead of having to do: `Matcher.doMatch(units, Matchers.not(Matchers.isSea());`

**Comment by ssoloff** [comment]
@DanVanAtta I agree that there are potentially better designs for the various predicates we use throughout the code.  However, the immediate goal of this issue is to get rid of the new Checkstyle warnings that were recently added when the ConstantName rule was enabled a few weeks ago.  So I'd prefer to address the low-hanging fruit first before attempting to tackle an API redesign. :smile:

Since both you and @ron-murhammer seem to have expressed a preference for camelCase methods, I think we can agree that that's how we'll fix these violations, and this issue can be closed.  Thanks for everyone's feedback!
