### ISSUE TITLE
Suggestion for Code Reviewer Regression Testing Policy Change 

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2193]
We've had a standing policy where code reviewers double check branches before merging them, meaning any new features are play tested and otherwise the updates are regression tested. 

Considering we have something like 20% automated line coverage, and that coverage is dodgy, we've a lot to test by hand. I've never been a very big fan of reviewers having this burden, it's adds more pressure to what is already the bottleneck in our development process, the review.

After some time though, the extra testing showed its value, regrettably bugs are a dime a dozen in this Jenga code base... My thinking based on that experience was that it was worthwhile to really test the incremental so we did not have to regression test the entire game. Yet, that was not even enough testing.

It's now a good time to revisit this now that we have a new 'tester' role and process. Notably we are now pinning releases for regression testing and have our testers do thorough regression testing. I think we can certainly move a bit faster now by not requiring reviewers to check out every PR branch and play test code, but instead have reviewers focus on whether code is well constructred, clear, and error free.

In this issue I'd like us to revisit how much test burden a code reviewer has, and clarify any new policy, how much testing should a code reviewer do? IMO ideally we would start enforcing unit tests and say code reviewer does no testing, but instead *ensures* enough testing was done by reviewing the automated tests and reviewing the manual test notes presented in PR overview. This then shifts the test burden back to where it most rightly belongs IMO, to developers and release testers, not code reviewers.

**Comment by ssoloff** [comment]
> IMO ideally we would start enforcing unit tests and say code reviewer does no testing, but instead ensures enough testing was done by reviewing the automated tests and reviewing the manual test notes presented in PR overview.

:+1:

> code reviewer does no testing

I keep wanting to write something pragmatic about this statement but always end up deleting it and starting over. :smile:  I think what I want to say is that, at least for the regular contributors, we all have an interest in ensuring a high-quality product, and that may mean a bit of exploratory testing by a reviewer would be the _responsible_ thing to do in some cases.

**Comment by prastle** [comment]
As a side note it is becoming very difficult to promote new releases when players are consistently crashing and discovering problems.  This is a completely off the wall thought! But maybe a solution would be to make all pre-releases auto launch to the test lobby?  That way testers know they are testing.  While only the current stable works in the stable lobby?  Just a thought.

**Comment by DanVanAtta** [comment]
> As a side note it is becoming very difficult to promote new releases when players are consistently crashing and discovering problems

Agree. It needs to stop... My hope is we can start enlisting 'beta' testers that will be very informed on how to test and not interfere with non-testing players. Then with some simple tracking I hope we can increase the amount of testing we do for specific releases, combine that with developers continuing efforts to catch stuff while we update the code, with some luck we'll avoid so many buggy releases. I'm very interested in additional ideas, practically from my point of view getting a strong 'beta tester' group together and rolling is the most important thing we can do now to avoid pushing so many bugs.

> But maybe a solution would be to make all pre-releases auto launch to the test lobby? 

To thoroughly test, you actually need to play old clients *and* new clients. It's typically most important to play the old clients though, if those work the new ones usually will too. It can be a bit tricky and very tedious to do all the testing we should be to cover everything.

**Comment by prastle** [comment]
kk bad idea but realize you are forcing all the non testers to deal with it aswell thus the chaos

But ya we need to test back compat as well

**Comment by DanVanAtta** [comment]
> kk bad idea but realize you are forcing all the non testers to deal with it aswell thus the chaos

Reducing the impact is best if we can. Likely should not be playing very serious games, saving often, and informing opponent of beta. Before that, play testers ideally would play the game quite thoroughly before even playing live.

**Comment by prastle** [comment]
kk

**Comment by ron-murhammer** [comment]
@DanVanAtta If we get a good enough and frequent enough "beta testing" group then I'm open to limiting/removing the PR reviewer responsibility around testing. I would say that needs to prove itself out though before we make any change to the PR review process.

"IMO ideally we would start enforcing unit tests and say code reviewer does no testing, but instead ensures enough testing was done by reviewing the automated tests and reviewing the manual test notes presented in PR overview."

While I agree with the thought behind this statement, you would need to add a lot of clarification unless you truly expect developers to have meaningful unit tests for every single line of code that is changed (probably ignoring pure formatting changes but including refactoring changes). For example, all of the refactoring the @ssoloff is doing in theory would need unit tests if were saying there is no burden on the PR reviewer to test basic functionality (that would be an enormous number of unit tests to write). You would also need to consider how to test UI code as a good portion of the bugs we've had recently have been UI bugs with #2184 being an excellent example of that.

**Comment by ssoloff** [comment]
> you would need to add a lot of clarification unless you truly expect developers to have meaningful unit tests for every single line of code that is changed (probably ignoring pure formatting changes but including refactoring changes)

Under the clarification topic, I would suggest that "safe" (as defined by Feathers) automated refactorings can probably be exempted from the unit test requirement.

**Comment by prastle** [comment]
to explain completely that has been typed in multiple spots gitter etc as well as forum.

IF you guys want testers and btw, the regular lobby players are the ones that really test it,

You need to allow them to have easy ability to post!  

They do not want to join another site.  Or learn github.

  So the real ? is where do we go from here? Hmm?  Are you guys going to TEST it before it is released? or is the lobby the guinea pigs?  That is the truthful explanation.

Thus i will repeat my suggestions of
 A a test release lobby ... which we have ... no one is there.
 B forum  testers that test what you ask them to.

After the last few releases I think all devs can see a problem!

The real ? is how do we fix this?

Before all reg users quit?

**Comment by prastle** [comment]
68000 at one pt yes im sure half spam!
 atm 320

think ya get the pt

**Comment by prastle** [comment]
Sorry as a final note! Why did i email all these people promoting new forum and lobby for it to screwup any games they had?

**Comment by prastle** [comment]
except we cant even fix and old password from a player from 6 years ago?

sorry but HMPH!

**Comment by prastle** [comment]
FIX THE DATABASE!

**Comment by prastle** [comment]
1 login to all!

Done venting but I seriously ? the direction all are concerned with.

Because most of it doesnt matter if ya cant fix a lobby login ... end of story

**Comment by DanVanAtta** [comment]
> you would need to add a lot of clarification unless you truly expect developers to have meaningful unit tests for every single line of code that is changed 

@ron-murhammer, I think that may have missed the implication of the second part of this: 

>  but instead ensures enough testing was done by reviewing the automated tests and reviewing the manual test notes presented in PR overview."

So no, there is no expectation that every single line have a meaningful unit test. But, if you do not do unit tests, then screenshots of the testing and test scenarios covered in manaul tests should be detailed. Personally I think some automated testing should almost always be included, it's generally trivial to take 3 or 5 lines of logic code, put that in a class, and then have an API that can be tested leaving the rest to be UI and integration testing.

> "beta testing" group then I'm open to limiting/removing the PR reviewer responsibility around testing. I would say that needs to prove itself out though before we make any change to the PR review process.

I'm not sure how we would measure this progress, in the meantime the overhead of reviewers testing is pretty killer and we are missing a lot of bugs. Our current process is pretty broken from that point of view, so I do not quite share the same bar where any new process would have to prove itself. I think the evidence is in, the reviewer testing is spotty, high overhead, wasteful, and not effective to cover all necessary regression testing. Hence the need for the beta tester group to begin with.

**Comment by DanVanAtta** [comment]
> Under the clarification topic, I would suggest that "safe" (as defined by Feathers) automated refactorings can probably be exempted from the unit test requirement.

I agree and would add we need to avoid a catch-22 where:
- the code is too poorly structure to add unit tests, we can't restructure the code without unit tests

**Comment by ron-murhammer** [comment]
@DanVanAtta I did miss that. I'm open to having reviewers ensure unit testing and appropriate notes/screenshots for manual testing instead of putting that test burden on the reviewers. I actually think that is a step in the right direction.
