### ISSUE TITLE
No Confirmation When Map Download Completes

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2199]
Task: notify user when map downloads have completed. Handle map window close case.

Background context:

I'd like to note an incomplete feature from a little while ago when the map download window was redone. It was intended for there to be a pop-up message to notify users when map downloads were done, the window would have an option to continue and close the map download window or to continue and keep the map download window open.

The problem I ran into though is in the case when the map download window is closed - there was no great way that I found to tie the window close event to an interrupt in the map download. We would cancel the temp file move, but the download would finish and completion notifiers fired. This lead to the possible download window being closed by user at say 50%, the temp file download continues and is orphaned, and then a bogus "Map Download Complete" prompt would fire when that download completed. 

A further complication is how to handle it when there are multiple maps too. Since maps can complete download one after another with some time gaps, pop-up windows are probably not the best way to notify the user.  I suspect a 'toast' pop-up window may be a good alternative, no user action required to close and we can append multiple completion messages to the single pop-up.

**Comment by RoiEXLab** [comment]
Suggestion: It is possible to display the system default popup notification, like when a device is plugged in or similar.
See this Stackoverflow answer for more information: https://stackoverflow.com/a/34490485 and just make sure the tray icon instance is desposed after its use.
