### ISSUE TITLE
Question: Project Prioritization (how will we)

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#22]
Question 1 - How do we keep track of priorities of what needs to be done? Do we have a wiki page with some mission statement items, maybe more granular with general things to improve? Do we supplement that, or only do prioritization in whatever project tracking mechanism we choose?

Question 2 - Does this process take into account that some contributors will only be able to work on low priority items?

**Comment by ron-murhammer** [comment]
1. Probably some combination of both. We should have some of the high level features listed on a wiki page or forum post with general priorities (I currently do this with the AI development). This is like a roadmap and provides info to our user base. Then using either github issues or whatever other tool we prioritize features/bugs/etc for developers so we have a general understanding of what needs worked on.

2. This is based on the contributor as we rate things but if they are new to the code base or have limited skills then they can choose easier tasks even if they are lower priority.

**Comment by DanVanAtta** [comment]
With respect to the second point, also consider that some people may not simply be interested in working on more than one or two items, both of which may not be in the top 3 of priority, yet it may be useful. So long as they are willing to test thoroughly, code with some quality, and deliver a complete product, I think we are shorting ourselves by rejecting this labor. I want us to keep that in mind since this is open source and not industry.

With all that said, it sounds like @ron-murhammer  your suggestion is to start a general list in wiki, then more specific items in a tracking system. The conversation in tripleA-test essentially concluded to use github issues and transition to JIRA if things become unmanageable.

**Comment by DanVanAtta** [comment]
Re-opening, I think there are some more details to think through and discuss.

- Projects are tracked in github issues
- wiki has a list of priority items, a roadmap effectively

I'm also assuming the roadmap will indicate priority, what we'd prefer to do first, then after, etc.

How are items linked between the roadmap and wiki? Do they need to be? maybe as one thought we can tag each roadmap item with a two word descriptor, use the same tag in corresponding github issues.

**Comment by ron-murhammer** [comment]
Yeah, that's pretty much along the lines that I was thinking. Sort of give each item a short name on the wiki and then create sort of 'epics' of issues using tags.

**Comment by veqryn** [comment]
I would actually like it if we took our discussion of project priorities back to the dev forum, and left git issues to specific issues surround some chunks of code, or project configuration, etc.

**Comment by gaborbernat** [comment]
For discussion of priorities, what's next use forum/mailing list. For tracking, if decided create a Github issue with a label of enhancement, and add it to a milestone for the issue.

**Comment by djensen47** [comment]
> I would actually like it if we took our discussion of project priorities back to the dev forum, and left git issues to specific issues surround some chunks of code, or project configuration, etc.

I'd rather not have this. I've been much more engaged (as has everybody else?) since we've moved here. The more things you ask a contributor to do (join a mailing list, sign a CLA, etc.) the fewer contributions you'll get. I think discussion here is fine but what we do need to do it tag issues appropriately.

What I've seen multiple times is that somebody makes an empty pull request (not sure yet how that works) for a "release," in the description for that "release" or "milestone" there is a checklist like this:

- [ ] Fixes issue #37 
- [ ] Adds new functionality XYZ
- [ ] Adds documentation for ABC

Github only seems to work for many many open source projects. I'd rather spend our time using/learning the tools provided here than trying to cobble together disparate solutions.

**Comment by djensen47** [comment]
Another thought (can be done in addition to the pull request) is to use issues + milestones + labels.

An issue can be assigned both a milestone and multiple labels. Both can be anything we want. Milestones could represent big or small releases. Labels could be used to both categorize issues and assign a priority high/low (none is medium?).

**Comment by djensen47** [comment]
https://github.com/roadrules/rickshaw-angular-directive/issues

^ That has one issue, which is basically a milestone for a release with checkboxes. In the issue list you can see the progress. Neat.

**Comment by ron-murhammer** [comment]
So its a difficult choice as we still have a good number of map developers and core users who will probably never look at github but use the forum frequently and still should be involved in priorities. But to your point, keeping things in one place is beneficial for the developers. One way or another we'll need to have discussion around priorities probably in both but where we keep the actual list is the question.

**Comment by DanVanAtta** [comment]
Forum -> drives issues to github. We need to be clear we have a process to move 'action items' from there to here.

We can use labels to mark the importance of github issues. Then prioritization will be pretty obvious.

**Comment by DanVanAtta** [comment]
2nd thought, i think we can still explore some ideas in this discussion:

@djensen47  earlier:
> use issues + milestones + labels.
>
>An issue can be assigned both a milestone and multiple labels. Both can be anything we want. >Milestones could represent big or small releases. Labels could be used to both categorize issues and >assign a priority high/low (none is medium?).

I like that. though I wonder a bit about the details. For us would a milestone be anything that needs multiple issues? Or would they be check boxes cookie-cutter type of issues of things to be done before we release (release branch created, tests pass, XYZ has been tested and widgets deployed, etc)

**Comment by DanVanAtta** [comment]
Maybe not. Closing again. I've opened a thread on the sourge forge forum on development priorities. Seems like the consensus there are that the priorities are to keep and get more developers and players (there is a solid map making user base out there).
