### ISSUE TITLE
play by forum - context and usage of 'post turn summary' button

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#220]
When playing a PBF game, clicking on 'post turn summary'  at the end of a turn results in the below error message:

![end_of_turn_error](https://cloud.githubusercontent.com/assets/12397753/10351449/79dd9b88-6cfe-11e5-9ba7-7fd33a95f1bf.png)

The error message makes it sound like the PBF game failed, but in reality the games were automatically posted without issue.

A second problem is the error message asks for the "error message" to be reported, but nothing is shown in the console, no further error details are given to the user.

I'm unsure of the intent behind this button, are there cases where it is needed? Something about it needs to be fixed, the error message to the user really makes it seem like the game is broken when it is not. If clicking on the button is unnecessary, then it perhaps should be disabled or hidden until it could be useful.

**Comment by ron-murhammer** [comment]
This is an issue with the A&A forum migration. It seems to ack forum posts slowly which causes TripleA to timeout and display the error.
