### ISSUE TITLE
Ignore

### ISSUE THREAD

**Issue by Heppisorus** [triplea-game/triplea#2202]
With the new release you can no longer withdraw units from a mixed amphibious assault.  Previously this was a settable feature within the XML and you could withdraw non amphibious assault units from a mixed attack.

Now if you have transports in a SZ with an Allied flotilla and there are enemy subs (that submerged) the game will automatically kill those transports.... this never used to be the case.

**Comment by ron-murhammer** [comment]
@Heppisorus Do you have a save game that reproduces the issue?

**Comment by Heppisorus** [comment]
Yup.
But it tells me that our save games aren't supported file types.

**Comment by ron-murhammer** [comment]
@Heppisorus Just zip the file then upload it and it should work :)

**Comment by Heppisorus** [comment]
[Spartan Axis August11th.zip](https://github.com/triplea-game/triplea/files/1219963/Spartan.Axis.August11th.zip)

**Comment by Heppisorus** [comment]
Please ignore this... I just retested and I cannot duplicate the issue I had.

As far as the subs I think there is just a new prompt or that I have never seen before but instead of moving the transports out... I left them there and you still had the option to either attack the subs or not...  seems it's working fine.  My mistake.

**Comment by Cernelius** [comment]
@Heppisorus Just assuming that this is what the admins would tell you, I think you should not make the title overly generic and if you believe your issue is invalid you can close it yourself (there is a button).
