### ISSUE TITLE
Flaw in game when air-transporting unit?

### ISSUE THREAD

**Issue by FrostionAAA** [triplea-game/triplea#2211]
### My Operating System:
Windows 10
### TripleA version:
1.9.0.0.5994
### Map:
Dragon War and maybe other maps.
### Issue
Don’t know when this flaw has been introduced, but I am pretty sure it has been introduced and has not always been there. I am experiencing that an air transport unit doesn’t seem to use its own movement when wanting to fly/transport, but is instead using the transportet units’ stats/limitations. Let me explain:

This is the air unit that wants to carry another unit:
![pic1](https://user-images.githubusercontent.com/15268177/29289360-6bbcdcae-813c-11e7-8016-18129808e2fd.png)

It can easily fly its own 4 movement by it self:
![pic2](https://user-images.githubusercontent.com/15268177/29289546-28333a68-813d-11e7-99ca-e948a77259c7.png)

This is the unit it wants to carry. It is a 2-movement land unit:
![pic3](https://user-images.githubusercontent.com/15268177/29289558-35578816-813d-11e7-80d0-e78e8ae284c5.png)

It can be loaded. No problem:
![pic4](https://user-images.githubusercontent.com/15268177/29289575-3ecc331a-813d-11e7-85ec-8a45875827a8.png)

![pic5](https://user-images.githubusercontent.com/15268177/29289580-44d3f158-813d-11e7-93e1-7e3b87582d79.png)

But when trying to fly, it seems to just want to move the two units, or maybe it is using the carried unit’s stats?
![pic6](https://user-images.githubusercontent.com/15268177/29289585-4d0dc09c-813d-11e7-971d-6c00ab09a6a0.png)
![pic7](https://user-images.githubusercontent.com/15268177/29289606-62ae9192-813d-11e7-9867-98bd73ce8e45.png)

It seems to not want to fly out over sea:
![pic8](https://user-images.githubusercontent.com/15268177/29289612-6c8828f4-813d-11e7-87c2-eaac29ccd6da.png)

Right now the two units have these stats:
```
        <attachment name="unitAttachment" attachTo="Air-Balloon" javaClass="games.strategy.triplea.attachments.UnitAttachment" type="unitType">
            <option name="maxBuiltPerPlayer" value="1"/>
            <option name="attack" value="1"/>
            <option name="defense" value="1"/>
            <option name="isAir" value="true"/>
            <option name="movement" value="4"/>
            <option name="transportCapacity" value="1"/>
            <option name="isAirTransport" value="true"/>
            <option name="isKamikaze" value="true"/>
        </attachment>    

    <attachment name="unitAttachment" attachTo="Wizard" javaClass="games.strategy.triplea.attachments.UnitAttachment" type="unitType">
            <option name="maxBuiltPerPlayer" value="1"/>
            <option name="isInfantry" value="true"/>
            <option name="attack" value="6"/>
            <option name="defense" value="3"/>
            <option name="canBlitz" value="true"/>
            <option name="movement" value="2"/>
            <option name="transportCost" value="1"/>
            <option name="isAirTransportable" value="true"/>
            <option name="UnitPlacementOnlyAllowedIn" value="Stormwood:Ironhorn:Athondir:Orcengor:Lionport:Necroloft"/>
        </attachment>
```
### To recreate:
1.	Load Dragon War and start game (Player will be Crowton nation per default (Blue player))
2.	Edit and place Crowton (Blue player) Air-Balloon and Wizard.
3.	Try it out.

**Comment by prastle** [comment]
its been there forever frosti
try cntrl select movement first of the fly pattern

**Comment by FrostionAAA** [comment]
Forever? Is it very hard to fix? It can't be optimal that players can experience this strange behaviour. If it is hard to fix, maybe the whole process of loading something onto a plane should just be remade to work like land transport. Click, Click and Move. Then maybe it will also be easier to implement AI support for Air and Land transport at the same time?

**Comment by prastle** [comment]
It doesnt only affect your flying 6 hit battleships ;)
i mean dragons :)

**Comment by prastle** [comment]
but ya
would be nice if finally fixed

**Comment by ron-murhammer** [comment]
@FrostionAAA There does appear to be a bug that doesn't exist in the current 1.9 release version as I tested this on TWW and it has the same problem where its fine in current release.
