### ISSUE TITLE
6157 - Incorrect battle messaging on 270BC

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2214]
![no_space](https://user-images.githubusercontent.com/12397753/29332007-5b424e82-81b3-11e7-900c-b316442dbee3.png)

Notice the text says "press space to...", but pressing space does nothing! Seems like the messaging needs to be wired into the 'focus on own casualties' setting, or made more generic.

------------

This might be a regression of the 'focus on own casualties' feature, that was toggled on, my understanding is a person should be able to 'space bar' click through these battles with that feature turned on.

**Comment by DanVanAtta** [comment]
This actually might be a regression of the 'focus on own casualties' feature, that was toggled on, my understanding is a person should be able to 'space bar' click through these battles with that feature turned on.

**Comment by Cernelius** [comment]
I suggest to just change ", press space to select" to just " selects", all cases. Keep it short.

Change:
Defenders fire, Carthage, press space to select 2 casualties.
to:
**Defenders fire, Carthage selects 2 casualties.**

I also wish to underline that "fire" is not that good, either. In the 270BC map there is noone who "fires". That is a bias in the wording that makes sense only for middle of XIX century onwards, as before firing was not necessarily the main way of dealing damages in all cases (even in Napoleonic you can have a mostly cavalry battle).

**Comment by ron-murhammer** [comment]
@Cernelius Agree though I think it should be:
Defenders fire, Carthage **select** 2 casualties.

As its an instruction to the player.

**Comment by DanVanAtta** [comment]
It used to be the case that you could click space bar, the 'okay' button would receive focus, I had the option set for that. I'll create a specific issue to track that.

**Comment by DanVanAtta** [comment]
Hmm, checking the latest, turns out the 'space' bar option is not there if you actually have to select casualties, you have to click the 'okay' button. Seems like the 'okay' button should be selected by default to be more cohesive with other options, with an option to toggle that off if desired.

Regardless, fixing the messaging is what is called for.
