### ISSUE TITLE
6157 - PU 'end with' summary is overly verbose, calculations are not clear

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2216]
![bottom_line](https://user-images.githubusercontent.com/12397753/29329765-c8014a62-81ab-11e7-8f5f-83ac1bf0f645.png)

Some problems with the dialog:
- Overall a lot of text and numbers
- Two times we have the text "end with", this is on the face of things confusing.
- Calculation text is not very clear, what does it mean exactly with "giving Carthage 999 PUs & 999% income for 1475 PUs"? Was the 999 added first, or after the 999%, and what was the basis? These questions should ideally be very obvious from the UI alone.

----------------------------

Maybe switching to a table like format might help, something like:
```
Starting PU: 1
Income: +53 -> 54
Multiplier: 999% -> 540
Bonus: +999 -> 1529 
Total: 1529
```

**Comment by ron-murhammer** [comment]
@DanVanAtta Yeah this could be improved though is considerably more interesting on complex maps. I made some initial improvements to reduce the size of the report on complex maps: #1996. I'd put this in the feature request bucket as its a nice to have and could use input from the community.

**Comment by DanVanAtta** [comment]
I was not able to figure out easily how the 999 PU & 999% calculation were applied. The messaging is not very useful, this is not a feature request, the PU summary is bordeline broken, certainly hard to use.

**Comment by DanVanAtta** [comment]
The "end with" text appearing twice is really confusing as well. I'm not sure what community input we can get at the moment other than, yeah, this is broken. They can suggest UI layouts, but I would be surprised if that would be the most useful considering they are not familiar with swing and the suggestion may not be technically the most easy. Really i think this needs someone to take a crack at the code and just submit a PR, maybe put some screenshots in the forums. I just really think we are going to get a design by commit paralysis problem if we go with the forum input route, I'm not sure how we avoid that or get useful input without experimenting with different UI treatments.

**Comment by ron-murhammer** [comment]
@DanVanAtta The messaging has mostly been this way for years though I agree its not great. If you want to see confusing turn summary reports load up a complex map with multiple resources and objectives. There is some discussion on trying to make improvements here: https://forums.triplea-game.org/topic/128/resource-system-assessment-and-improvements.

I do think input from the community on what they'd like to see in Income Summary report and potential layouts is important. Otherwise we are just designing in the what we think is best bubble.

Feel free to take a crack at it but I'll warn you that the code that generates that is all over the place and there are lots of various complexities as income can come from a bunch of different places.

**Comment by DanVanAtta** [comment]
No real disagreement. But to be blunt, the current messaging is not meaningful, we would almost as well remove it. It needs work, it's a problem. More input from those on the forums is useful, sure, though I'll let whoever tackles this go to that length. For the moment I was doing Q/A and this is a problem. The fact it has been around is immaterial, it just means we got used to the smell :hankey:

**Comment by ron-murhammer** [comment]
@DanVanAtta Agree. The conversation around the income summary mostly boiled down to most people don't read it as it isn't that useful (especially on simple maps) and its poorly formatted.

**Comment by simon33-2** [comment]
The only real issue I have with it is that the summary is not presented as a final figure. Should be (in the example) something like:
Carthage collect 1528PUs to hold 1529PUs.
54PUs from territories, increased by a factor of 999%
999PUs additional.

Or something like that. Point being that it first gives you a final figure then changes it. That is pretty dislikeable.

**Comment by DanVanAtta** [comment]
Stagnant issue, resolving. Needs clarification if we are going to tackle this.
