### ISSUE TITLE
6157 - Bring to 'front' combat window button would be useful

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2217]
On the below, there is a combat, but I managed to click around enough that I did not notice the battle window come up. This can happen in multiplayer games and causes a game delay. One person thinks the other is AFK, the other is waiting for combat not realizing the combat window is underneath other windows.

![could_use_bring_to_front](https://user-images.githubusercontent.com/12397753/29330215-5efc5230-81ad-11e7-9ae2-a617a9b689ad.png)

Suggested here, somewhere on the above screen we have a 'show combat' button that could be clicked to bring the combat window to front. This would give a better visual indication that a combat is active, and would avoid the need to dig through the open windows to find the combat window. We could als consider further visual emphasis, maybe have the button "shimmer" if the combat window is not at the foreground. To start I would suggest some control somewhere.

---------------

Opened a forum thread for UI ideas: https://forums.triplea-game.org/topic/291/ideas-for-a-show-combat-button

**Comment by DanVanAtta** [comment]
Opened a forum thread for UI ideas: https://forums.triplea-game.org/topic/291/ideas-for-a-show-combat-button

**Comment by simon33-2** [comment]
Macs are particularly bad for this. 

You should also have buttons for scramble, intercept, Kamikaze.
