### ISSUE TITLE
Topic: use a dedicated github organization for maps, or use the same one as the game engine?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#222]
Question: Should we use a different organization for hosting maps, or use the same triplea-game organization?

Initial discussion, some pros and cons:

All in all, there is not *that* much difference between the two options. A second organization offers a number of small practical advantages. For example:
- admin privileges are easier to maintain and organize when split as two orgs
- we get a very strong split between game engine and the maps
- the game engine organization is not polluted with various map repositories

Since the administrative structure of maps *will* be slightly different, I think by definition it is something of a different organization. The maps will need to be a bit more decentralized in terms of allowing work to progress and code checks. For example, if we one fine and ideal day we had 20 map makers all doing stuff in Git, we would want them to be able to update their repositories whenever, but for releases is when we would want the centralized control to kick in. For these we ensure that game code will control which map releases are used, so game engine admins will control which maps are available with and from within the game.

The second org really then makes it easier to decentralize the map updates and the acceptance and creation of new maps. Chances are pretty good beta maps will get posted to GitHub a good bit before the game engine would ever need to be updated to include them. So this split would allow map admins to take care of uploading the beta map from a zip file to GitHub without bothering the game engine admins. Then the game engine admins are engaged again when the beta map is done being tested and is ready for release.  

I've thought about this issue for quite a while. The drawbacks I can come up with are all mostly philosophical, mainly the splitting of repositories and/or having a different organization URL. These are more minor concerns to me with few practical implications.

So again, it's not *that* much of a difference and all in all surprising to at least me how many benefits there are in having the two organizations split up.

**Comment by DanVanAtta** [comment]
Worst case, we try out a split org, if it doesn't work out for some reason, then I'll spend 30 minutes to an hour moving the repositories over to the game engine.

**Comment by veqryn** [comment]
Second org would be best, because we can do different and more lax permissions.

**Comment by veqryn** [comment]
Actually, I think I misspoke, as I think I was thinking about repositories not organizations.
Somehow we are able to have different permissions for the 'io' repo vs the game engine repo, so there is no reason to think we can't have a different set of permissions for the maps repo.

**Comment by DanVanAtta** [comment]
"So again, it's not that much of a difference and all in all surprising to at least me how many benefits there are in having the two organizations split up."

Please respond to this and state concrete benefits why one org has more benefit than two. I listed at last three or four concrete benefits to having two orgs.



 better than two. 

Also please address the benefits of two orgs 
 I mentioned, as those are real benefits which we enjoy today. For example, turn around time for team permissions with one org has been about a week. With the map org structure, it has been less than a day.

The second org makes sense. The work flows of the two organizations are very different. 




> Somehow we are able to have different permissions for the 'io' repo vs the game engine repo, so there is no reason to think we can't have a different set of permissions for the maps repo.

Yes,

**Comment by DanVanAtta** [comment]
I want to address this directly:
>  so there is no reason to think we can't have a different set of permissions for the maps repo.

Sure, you can have different permissions. It's not a question of if you can do it with one org or not, you can do anything with one org that you can do with two. The key difference is *who* *has* to do that thing. We're talking about operations work here and who is on the hook for doing it. It makes sense to dole this out to other people and not keep it with game admins.

**Comment by DanVanAtta** [comment]
@veqryn , if you did mean just a second repo, can you explain how permissions would work when we potentially have up to 20 different map makers, each with different interests in different maps. It doesn't make sense to have all 20 be admin, and if all 20 have write permissions then they could still mangle each others maps. Also, any activity with the maps will also always go out to everyone, even if it has just to do with one map. One email thread/issue between two people about game balance of just one map would be spam for the rest of the group. People would not then limit their use of issues, we begin losing the benefits of  Github.

Please respect that I've thought hard about this question for nearly a month now, I've tried different configurations in Git, and none work well and pose problems. I would rely a bit on that expertise and not airmchair quarterback this one. Bottom line, unless every map admin will  always also be a game engine admin, then two orgs make sense. Since we could potentially use map admins that have no business touching game engine code, it really makes sense to have two orgs.


This really is a lot more about mechanics of if we can do something in github, it is about workflows and operations, and who will be *required* to do what.

**Comment by DanVanAtta** [comment]
*edit* made more concise.

There is quite a bit of benefit to two orgs, a case should be made for one org over two.

Two orgs allow for map admins:
- map admins can do work that is operational in nature. It is a good for game engine admins to have other people to do that work for them. For example, there is no way to give permissions that would let a non-game engine admin set up a new repository, create a new team, assign people to it, give them admin over the team, and then last admin is also then needed to finish setting up the release pipeline (it turns out sadly the bot account is not enough). Having  a map admin able to do all that is helpful, and none of it impacts the game code, which gets to the next point
- map admins are still limited, they cannot add games to be included with the game engine (either bundled or download)
- map admins can be *very* useful. Not taking advantage of that distribution of labor, making game engine admins do *everything*, it's hard to see how game engine admins will have time to do anything else that is not day to day operations. (pull requests, testing, responding to issues) 
- also, outline how it would work with just a few repo's for map. People are going to submit maps and then walk away forever. It'll be a complete pain to be an admin of just one map and not all of them or a dozen. Who wants to get emails for every issue and PR for maps that don't impact them? 
- fundamentally, the work flow of maps is very different from the game code. This is why there is actually so much benefit for such a small change. The second org allows for more flexibility, more levels of control that allow for an intermediate role that can be dedicated to support map makers (yet this intermediate role does not have extra access to the game engine, without a second org that distinction would not be possible)

**Comment by DanVanAtta** [comment]
Perhaps we can make a better decision with a more concrete analysis of the one org setup.

I can see how far I can get with a test map within the single game org without having owner. To do that  I'll need `tripleabuilderbot` invited into the org (standard read member permissions, note: invite into org is owner only ability)

**Comment by ron-murhammer** [comment]
@DanVanAtta @veqryn I think separate orgs is better. Keeps this core org cleaner and focused on the core parts of triplea and anything that deals with significant coding. Maps can be hosted in a separate org that has more admins and more lack permissions.

**Comment by DanVanAtta** [comment]
@ron-murhammer , I agree with those points.

@veqryn , @ron-murhammer 
I think it would be helpful to back up a bit and review requirements and facts, then approach this topic again form a high level point of view.

Requirements:
- Map makers are not be able to change which games are included with the game and which are available for download (current suggestion is for the game engine to keep a white list of maps with version and SHA1 checksum).
- Map makers should be able to operate independently of game engine admins up until the point of releasing new maps or new versions to the game engine. This is to minimize overhead for game engine admins and to reduce bottlenecks in the map making process.
- Automated. Map admin should not become a full time (nor even a part time job). Map admins will be best used to help onboard map makers to get them set up so they can be independent. Essentially help map makers with all the one time setup things, and to help guide them through the process. Worst case map admins will be running an update script to handle map updates received as zip files (this will help for a smoother transition, and can help to accomadate all of the current map makers).
- Highly collaborative and somewhat agile. For example, if we get a group of 3 young people that are eager to build a new map, we should be able to enable them very quickly. This means a turn around time of a day or two. To achieve that I would like to have a goal of at leaset 4 map admins, preferably 6 or 7 of them.

One of the key questions becomes, what can only organizations owners do that nobody else can? These items will represent bottlenecks in the map maker process and are items that map admins will not able to take care of. I spent some time trying to answer this question in detail, I found just three things that only org owners can do:
- add new people into the org
- delete teams
- programmatic assignment of teams to repositories

Thus we do see some potential conflict with the requirements. Programmatic assignment is needed for full automation of repository management, so it is quite detrimental that is on the list of owner only actions.

If the list of owner-only actions was only adding new people, I'd be more inclined to go with one org. So ultimately I think my suggestion will be for us to run with two orgs for at least a little while initially. If we do not get any benefit, I'll personally transfer ownership of each repo to the game engine org. At that time we'll also have more information of how the maps are being run and organized, and we'll have a better picture of if a single org or double org would work better. Mainly due to the automation limitation, it is my opinion that at this time - two orgs would fit the requirements better than one.

**Comment by DanVanAtta** [comment]
Bottom line:

Closing for now. Let's consider the two org setup as a prototype and revisit it a couple of months. Worst case, moving the repo's over to the triplea-game org won't be difficult and is non-destructive. This can be done with the Github 'transfer ownership' feature which moves everything including code, wiki and issues.
