### ISSUE TITLE
6157 - no longer have retreat confirmation when can only retreat to single territory

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2222]
We removed the territory selection dialog when there is only one territory to retreat to, this seems fine IMO. But, an effect of this is we lost a 'user confirmation' that they want to retreat. If you misclick and click 'retreat' instead of remain, that could be a game losing mistake. There is really no clean way to pick up a battle from where it was, so it's a bad mistake to make even if your opponent is willing to help fix it.

Recommendation:
- simple confirm dialog "are you sure you want to retreat to: <territory>". Then it will always be at least a two click process to retreat. On a personal note, some games where there are many battles I click 'retreat' to see available retreat options, having some cases where that actually retreats and other cases where it shows a dialog is inconsistent.

**Comment by Cernelius** [comment]
I think it was fine as it was before. Just the same thing no matter if you have only 1 retreat option or multiple, showing it even if only 1, which means that is confirmation and visual display of the same.
You might add a setting option for the new behaviour of no confirmation if only 1 retreat option.

**Comment by DanVanAtta** [comment]
> You might add a setting option for the new behaviour of no confirmation if only 1 retreat option

I think that is the ticket. 
I found the text of the territory being on the button in the 1 territory case to be relatively helpful - so I did not miss the window as much, but did miss the extra click for confirmation.

**Comment by ron-murhammer** [comment]
@DanVanAtta I believe this change was done on purpose with at least some player input. The prompt should display the territory name if there is only 1 option. If there are multiple then it goes through letting the user select one. I'm actually fine with the new functionality. I believe @simon33-2 made this change.

**Comment by DanVanAtta** [comment]
> I believe this change was done on purpose with at least some player input.

Yeah, but now the behavior of the retreat button is not consistent. It should be consistent, and it is not recoverable if misclicked. The short cut version I think is ideally behind a user preference.

**Comment by simon33-2** [comment]
Yeah, you could just as easily argue that there should be two clicks to not retreat. That is not recoverable either!

You seem to be just arguing against change here. There's no valid reason why this isn't an improvement.

**Comment by DanVanAtta** [comment]
Except there is always one click to remain, so no, I don't you could just as easily argue that. If you want to update it so it is a consistent two clicks over one, given that most battles are completed by spam pressing space bar, it's probably not a popular suggestion since it's an extra click but again we are spamming the space bar.

**Comment by Cernelius** [comment]
Having played both ways, I personally prefer as it was before. I think where you are retreating or not retreating should be visually displayed, not just referencing the name of the territory.
I think the map should be playable not requiring you to know the name of any territories (think also about unfamiliar games or games with hard to recall names, like "Jurassic FFA").

**Comment by DanVanAtta** [comment]
Staying in battle is more recoverable actually, it's pretty easy to tell your opponent not to confirm casualties, to not roll, that it was a misclick, and that the next roll would be ignored and any casualites edited back in.

On the other hand if you leave a battle early, recreating that location in the battle can be really painful and perhaps not even possible. It's much easier to ignore dice rolls than it is to simulate a battle.

**Comment by DanVanAtta** [comment]
IMO this is probably best a preference that can be turned on by clicking a checkbox when a single-territory retreat option is shown.

**Comment by Cernelius** [comment]
@simon33-2 Have you ever played "Jurassic"?
There names are "Fig", "Hit", "Hiw", Hia", "Shn", "Shr" and such.
And it is not a map's fault, as I believe a naming like this is adequate, there.

**Comment by Cernelius** [comment]
Anyways, I'm not really arguing here. I'm fine both ways, just had a preference for having it always displayed, not just named, but I'm good with either (just felt like a downgrade to me).

**Comment by DanVanAtta** [comment]
+1 on the naming point, sometimes the image was nice to remind you where the territory is. 
I think part of the issue is that some maps and play styles this is really helpful, for other maps and styles it's a frustrating extra click.

**Comment by Cernelius** [comment]
Sounds like something that would be best having as an engine setting.

Still, I would suggest the default behaviour being something that never requires you to know the name of any territories for making any decisions.

To explain the downgrade feeling, having to know / search for the territory name, instead of having the image, it is like going back from windows to dos.

Or like if you would change the purchase window as not having the units images, but just their names.

**Comment by DanVanAtta** [comment]
It'd probably be both, a checkbox and an engine setting. Checkbox to discover the setting in context and turn it on, and also an engine setting so you could turn it off if you wanted.

**Comment by simon33-2** [comment]
It would be a bit rich to complain that you didn't mean to continue the battle after dice are rolled, which they would be.

Anyway, I see there is some support for your viewpoint which surprises me.

I would have been happy to remove the notation on where to retreat to entirely!

Re: Jurassic, no I've never played that.

**Comment by Cernelius** [comment]
Actually, I don't really mind regarding the confirmation; just I think also visual is better than just named, confirmed or not, and I think you should not be required to know names at all.

To make another example, it would be like if, in the same phase, you remove the "Center" button beside the "Battle" buttons, having the territory names.

**Comment by Cernelius** [comment]
Meaning that if you can find a way to show the retreat-to territory without the confirmation step, that would be good too, as I see it.

Again, as a matter of principle, I think everything should be visual; knowing how stuff is called should never be required.

And definitely removing the notation on where to retreat to entirely would really damage the playability of a (huge) map like Jurassic, except in its early phases.

**Comment by Cernelius** [comment]
So, unless another way, my vote would be to go back as it was before, but it's not a drama and can live with either.

**Comment by simon33-2** [comment]
"Meaning that if you can find a way to show the retreat-to territory without the confirmation step, that would be good too, as I see it."

Perhaps but it's a pretty low order issue for me. I'd much rather get rid of redundant clicks and unselectable options.

**Comment by DanVanAtta** [comment]
> It would be a bit rich to complain that you didn't mean to continue the battle after dice are rolled, which they would be.

@simon33-2 "complain" is not the right word. Let's say you've been playing through to the late hours, you're on battle click 1000, a misclick is easy. I've had that exact scenario, both ways, with good attacker rolls, bad attacker rolls, before and after seeing defensive dice. Some opponents have taken the opportunity to capitilize on a game losing mistake, otherwise have honored the undo. I've even seen/had accidental retreats where instead of closing the retreat window I misclicked and actually retreated. 

Stuff happens, if you are blindly clicking buttons, having one behavior in one context and another behavior in another context is dodgy UX. We could make the buttons visually very different, though I don't think that is the most obvious or viable solution. Having an opt-in preference I think solves the inconsistency problem of whether the retreat button retreats directly or if it prompts further nicely. @simon33-2 do you foresee that conflicting with other plans or it would cause other UI difficulties?

for 7, 9, 12 hours straight vs an opponent, it is 3 am, and you're on battle click 1000, odds are good a misclick can happen. TripleA can sometimes be a contest of who can use the UI longest without first making a mistake, introducing a new path for a potentially game losing single click mistake is not good.

While the click is redundant, removing it breaks consistency with how the retreat is done otherwise. That's quite dodgy. To break that consistency, having it be an opt-in option I think is a clean way for a user to opt-in. 

It should be pretty easy to put this behind a checkbox setting as described, I'm not sure why there is so much resistance to that idea @simon33-2 . Do you think making this a user preference would be difficult, or bad for the UI somehow? 

------------------------

I think I put my finger on why this is not great UX - it overloads the 'retreat' control so it has multiple functionalities behind the one control. That suggests that this could be solved without the opt-in approach to make sure the single-action retreat button is visually very different from the territory-prompting retreat button. If they are very obviously different buttons then we would maintain a 1:1 between user control and output

**Comment by DanVanAtta** [comment]
> more advanced and possibly more interesting maps than the usual Revised and Global stuff, especially considering new players and players that approach new maps they don't know very well.

I'd note on larger maps with PBEM case, and particularly when learning additional maps and playing other multiple maps at once, it may be some days between a combat move and the combat playing out. Indeed, we should not be forcing people to remember where territory names are. The SZ case can be really difficult sometimes.

>  my suggestion is still reverting the changes that removed the single retreat option from being visually displayed.

Not quite the best fix IMO, trading one usability problem for another. I do like the thoughts on removing the intermediary screen. Instead of keeping 2 consistent clicks, maybe make it always 1. An alterantive I like is user opt-in route, but there are multiple ways to solve this. The problem specifically is that 'retreat' until now as always safe to click, and you gained information by seeing the territory. I put a good bit of  value in the former since I could zombie click it to remind myself of retreat options.

So I think we have a few options to play around with... We are *just* tracking the problem here. We could have very well tracked the excessive click too, and if there are other cases, it would be good to start tracking them too.

**Comment by simon33-2** [comment]
I don't mind the idea of putting in a configuration option but I wouldn't like to see this change reverted.

Indeed, adding one option per retreat territory seems workable.

**Comment by Cernelius** [comment]
What does "adding one option per retreat territory" mean?

**Comment by simon33-2** [comment]
Reworded.

**Comment by DanVanAtta** [comment]
Indeed, no suggestion to revert, but a fresh look for further improvement!

I think as you guys have suggested, a second control to 'zoom to territory' or 'show territory' seems workable as well. 

If anyone is inclined to look at this problem in detail, there are other approaches too. We could agument the battle window somewhere to always show the attacking and defending territories. Then a second control to 'show territory' would probably not be needed. TBD at that point if there is a real problem with misclicking, and if maybe we should have an option to always confirm retreats.

**Comment by DanVanAtta** [comment]
This is by design, closing.
