### ISSUE TITLE
6157 - Different staging screen treatments

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2232]
Looks like a copy/paste bug, we did not update all code that renders the staging screen window, so we've an inconsistent rendering of that window (when previously it was consistent):

![multiplayer_alliance_buttons_not_set](https://user-images.githubusercontent.com/12397753/29333874-4336e7e2-81ba-11e7-93af-9dabbb56c340.png)

![single_player](https://user-images.githubusercontent.com/12397753/29333909-5c510532-81ba-11e7-8df2-28cdb363ada1.png)

For example, in multi game there are cases for AI players and we may wish to give them bonuses. The alliance button was also intended to be used for multiplayer selection.

**Comment by ron-murhammer** [comment]
@DanVanAtta This was by choice given that additional effort to try and update the multi player games player selection. Originally, all the player selection screens were different but now at least local and PBF/PBEM are consolidated and have the new resource modifier options. It would be nice to eventually extend the functionality to that as well and even try to consolidate it more.

**Comment by DanVanAtta** [comment]
Understood. This should be covered by the UI update I'm working on, I'll assign to myself while working on that.
