### ISSUE TITLE
Regression vs blocker

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2237]
Regressions seem valuable to track as they are new bugs that users were never exposed to before. They are examples where we are breaking things. Sometimes intentionally, usually not though.

Blockers a bit of a loaded term, but often to mean something that needs to be fixed before something can be used. 

The two are not the same thing necessarily. Do want to stop tracking regressions and instead just label it all as bugs? If we do that, we may want to decide how we track the "must-fix" list. Whether we do that with an additional "blocker" label, or if we create release projects that would index the list of items.

**Comment by ssoloff** [comment]
I could go either way on keeping the regression label.  Personally, I find it useful because it helps me (as someone still relatively new to TripleA) prioritize one bug over another.  All other things being equal, I would probably choose a regression to fix before a non-regression.

If you are going to label an issue as a blocker, I think it would be equally useful to label the issue(s) at the other end as "blocked."  Then, when looking for a bug to fix, you can filter out the blocked ones without having to dig through all the comments to find out you can't work it until some other issue is fixed.

**Comment by ron-murhammer** [comment]
I prefer just one label that we use to flag bugs that must be fixed before the next release. Whether we call it regression or blocker or regression/blocker doesn't matter too much to me. We just need some way to flag what the important must have fixes are and most of these tend to be regressions but not always.

**Comment by DanVanAtta** [comment]
@ssoloff sorry to not have been more clear, in this context the thing blocked is very often the next release. Regressions are interesting since they are new. It's pretty hard to justify releasing a new bug, so they are usually release blockers.

I wonder though, if something is not a regression, but is still a (release) blocker, what exactly would it be? That makes me think that maybe 'regression' is actually a useful way to define a release blocker. @ron-murhammer @ssoloff , thoughts?

**Comment by DanVanAtta** [comment]
I'm not disagreeing, seems like we should have one such label. I'm wondering if we should define a 'release blocker' as only 'regression', where we break something that was previously working. That definition I think would potentially be valuable to keep it from being arbitrary what gets the 'blocker' label, otherwise we need to describe a severe bug. I'm assuming somewhat gaps in our process where we merge a PR with severe bugs will be rare enough that we can handle them as they come up.

**Comment by DanVanAtta** [comment]
Maybe rename the 'regression' label to 'must fix'?

**Comment by RoiEXLab** [comment]
I'm fine either way...

**Comment by ssoloff** [comment]
Given your [previous clarification](https://github.com/triplea-game/triplea/issues/2237#issuecomment-322688790) of what you're trying to achieve, I'd say "must fix" describes the concept better.

**Comment by DanVanAtta** [comment]
Should or would we ever apply a 'must fix' label to code that has been released? Does the label only apply to prerelease code?

**Comment by ron-murhammer** [comment]
Possibly if we weren't aware of the bug until we released and then realize that it must be addressed before the next release.

**Comment by DanVanAtta** [comment]
> Possibly if we weren't aware of the bug until we released and then realize that it must be addressed before the next release.

That's a bad scenario. Really I think that means we need to roll the last release back or put out an immediate patch and coordinate an upgrade. 

The retro-active, this is now a blocker, means our testing missed something huge and we're likely using our end-users as testers then. It also means the poor UX got past CR as well, I'm not sure I even want the option to exist where we can think "oh well, we'll just patch this up for the next release". It can also mean we did not put a feature behind a beta flag to properly test out the UX.

So at least for that scenario, applying a 'must-fix' to a feature already released I think is missing some bigger upstream problems and starts to invite some really bad release patterns, where we don't have to get it right, where we keep pushing out patch releases, we keep spending time on regression testing and spending more time between releases. I don't like that as an option even. 

--------------

On the other hand, I think it puts doubt into the CR process. If something gets past a CR, and someone else comes along and decides it is a 'must-fix', that creates conflict. I think the better approach would be to instead flag usability problems if an update has made it past CR.

------------------------

Considering that, at the moment I suspect it would be detrimental to use 'must fix' for intentional changes or for changes that were released. If we do, we need a definition. I suggest we instead maybe create a 'p0' label for things that have been released and suddenly must be fixed. 

If we can apply a 'must-fix' over UX issues to an already merged update but not yet released, IMO we would need some strong guidelines on when and who can do that. I suggest instead we avoid that and instead flag usability problems as we see them.

**Comment by ssoloff** [comment]
> I suggest we instead maybe create a 'p0' label for things that have been released and suddenly must be fixed.

Would having a set of "priority" labels (e.g. Critical, High, Medium, Low) to complement the "type" and "category" labels be worth considering?

**Comment by DanVanAtta** [comment]
'priority' labels and as a topic has come up a few times. The thing to solve is definitions when we have "Critical, High, Medium, Low", and secondly purpose. 

I do see a reason for a `p0` label, and a pretty clear definition.

***Reason & Purpose***: To communicate to game devs, admins and community that there is a known major problem. Provide a centralized place to coordinate resolution and mitigation.

***Definition***: A live and ongoing problem significant enough where at least 3 or more players would take some sort of immediate action to fix the problem (eg:  downloading and installing a latest and patched version).

We can haggle a bit about the 3 player bar, the intent is that it should not just be a problem that is in practice impacting exactly one or two people where we could probably take more targeted action to mitigate the problem. Secondarily, to emphasize, the problem should be signfiicant and noticeable, ie: immediate action, like you do not want to play the game unless it is patched.

---------------------------------

Summary: i'll go ahead and create a `p0` label for "live" ongoing major problems under the definition above. Let's use 'release blocker' for newly introduced problems that were found in testing. Both issues we should try to retrospect on to prevent the same class of problem from happening the future.

----------------------------------

Question: Should we explore the idea of having more priority labels? I suspect we are good with the 'default', 'p0' and 'release blocker' labels. My objection to a 'low' category is I suspect it'll be a graveyard and secondly it will get us in the trap of classifying priority when in practice it often does not matter. What more matters is whether an issue is important to a dev, and if in an issue is important to many game players or map makers. Since we have dev's come and go, they can make the updates, if they don't care about being admins but want to fix gameplay bugs only, we can't say "no, work on our p0's instead".  Hence, marking such game play bugs as low priority is not helpful. Really valuable initiatives may be worth highlighting, but 'projects' seem to me to take that role.
