### ISSUE TITLE
Let's Talk about TripleA projects - Voice Chat!

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#224]
We have recently completed and started a number of large projects:

- code migration to github
- code reformat
- website launch
- automated build of installation artifacts
- automated releases of installation artifacts
- smaller download (mp3's, lossless png compression)
- map migration to github

The first three are done and launched : )

The last four are effectively complete. It might be most efficient for everyone if we took 30 minutes to an hour to discuss where the projects are, how they are built, and what needs to be done still. Perhaps we could take the opportunity to discuss the tripleA project as a whole, and perhaps even properly introduce ourselves to each other.

@veqryn , @ron-murhammer , @gaborbernat , would you guys be willing to find some time, perhaps this weekend to talk about the project over skype or via google hangout (or something similar)?

**Comment by gaborbernat** [comment]
I'm on vacation traveling this weekend in London, so this weekend isn't
good for me, however after that I'm in.

**Comment by DanVanAtta** [comment]
Weekend is getting close, we should decide by tomorrow to keep this from getting last minute. @ron-murhammer , @veqryn , what do you think about this idea of discussing projects via voice rather than typing everything out?

**Comment by DanVanAtta** [comment]
Weekend is getting close, we should decide by tomorrow to keep this from getting last minute. Otherwise it might have to be next weekend or the following (maybe weekdays work out?)

@ron-murhammer , @veqryn , what do you think about this idea of discussing projects via voice rather than typing everything out?

**Comment by DanVanAtta** [comment]
Seems like there is not enough motivation to schedule something. Closing..

**Comment by ron-murhammer** [comment]
Sorry I've been really busy. Lots of traveling and I'm in the process of moving now. Maybe eventually but the next few weeks are tough for me.
