### ISSUE TITLE
Pls add Testing group as contributors

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2267]
@ron-murhammer can we mark members of the 'testing' group (so needs a better name!), as contributors on this repo? For now that would be: @panther2 and @prastle .

I'm thinking it's best to give the option to add some initial labels to a tester. This way it's the test reporter that uses 'p0' or 'blocker' to escalate major problems found when testing. This gives us a good bit of information when seeing such reports between admins, devs and testers and avoids admins from duplicating triage efforts when a problem is reported. The latter most point does not scale, let's say a zealous tester cuts 100 UX problems.  If we start closing because we don't like how our queue is now so full, it's a chilling effect on what gets reported and fixed. The point is that we will have a queue, we will work it faster than it grows. If it stagnates, we will force it to shrink by 'ice-boxing' the things we are just not going to work on. Meanwhile no one person has to look at every ticket reported, except in the specific cases of items marked as 'p0' or 'blocker', and to minimize overhead we can have test reporters label that for themselves. It's fine if we then discuss something down from a blocker or 'p0', but I do want to keep admins out of the triage game when it comes to build testing reports.

**Comment by DanVanAtta** [comment]
Assigning to @ron-murhammer for the specific action item and/or feedback. The process part of this topic is an open conversation though, please anyone feel free to add their 2 cents as helpful.

**Comment by RoiEXLab** [comment]
@DanVanAtta Just a small side note here: Assigning labels etc. requires Write Permission to this Repo

**Comment by panther2** [comment]
Thank you for considering this. Apart from the usability it would be an honour to be part of it.

Regarding permissions: I would never interfere in things I have no clue about (not being a programmer).

**Comment by RoiEXLab** [comment]
@panther2 I'm sure you wont ^^
Just wanted to mention it, so you just get the read permission and @DanVanAtta wonders why the newly created labels are not being used or whatever ^^
