### ISSUE TITLE
Lobby upgrade, postgres go-live

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2269]
Tracking tasks for lobby upgrade:

- [x] test latest lobby with current client: 3635
- [ ] double check postgres readiness, verify documentation exists on how to set that up, verify process status and  connnect to DB from CLI
- [x] verify postgres is installed on lobby server
- [ ] update lobby upgrade notes and documentation, verify that process and the install script
-----

Execute upgrade:

- [x] start postgres
- [x] stop bots
- [x] stop lobby
- [x] run lobby install script
- [x] start lobby
- [x] start bots

**Comment by RoiEXLab** [comment]
@DanVanAtta I can confirm postgres is already installed on the lobby server. (Version 9.5+173)
Not sure how it's setup though.
The lobby server needs a full restart in order to update, we should do that just before we update the lobby to use the opportunity

**Comment by RoiEXLab** [comment]
@DanVanAtta I'd close this issue given that we already updated the lobby.

**Comment by DanVanAtta** [comment]
@RoiEXLab for things like this that are pretty clearly done, feel free to close and ask to re-open if anything is remaining, or add the 'close pending confirmation' label and then close a few days later.

**Comment by DanVanAtta** [comment]
(assigning to someone means they are actively working a problem, that is not the case here, this was more or less orphaned but in a done state, hence the assignment not super appropriate, but all good :+1: )
