### ISSUE TITLE
Upgrade to install4j 7

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#2285]
Just noticed, that install4j recieved an update to verion 7 in june.
One of the big features is that it allows to create themes for the installer, we could display screenshots of the best maps while installing.
My concern is, that the license TripleA currently uses is only valid for install4j 6, so we might need to reapply for a new license.
@DanVanAtta Any chance you have more insight on this?

**Comment by DanVanAtta** [comment]
I suspect the install4j folks would be pretty happy to issue us a v7 license if needed. Their OSS support has been generous.

**Comment by RoiEXLab** [comment]
@DanVanAtta I know, if you look at their prices they indeed are ^^
@ssoloff What exact steps are neccessary to bump an install4j version again? + Is it time to update the bundled JRE? The current version we bundle is 1.8.0_66, which is really outdated,

**Comment by DanVanAtta** [comment]
We keep a copy of the install4j binaries in the assets repo which travis downloads and executes as part of build. You would need to update the build script and the asset files to be latest. I think we keep the key as well as an environment variable, if that were updated we would need to update the travis config for that (env variables are via their website).

Are there reasonable bug fixes in newer JREs? Regardless that should be pretty easy to update, similar, the files are in the assets repo, the travis build would then need to be updated to DL the correct file.

**Comment by ssoloff** [comment]
@RoiEXLab 

> What exact steps are neccessary to bump an install4j version again?

1. Add new install4j installer to assets repo (e.g. triplea-game/assets#13).
1. Upgrade build to use new install4j installer and Gradle plugin (e.g. #2040 and portions of #2031 [fb167b4]).
1. Upgrade build.install4j using new install4j IDE (e.g. portions of #2031).
1. Remove old install4j installer from assets repo (e.g. triplea-game/assets#14).

**Comment by RoiEXLab** [comment]
@ssoloff Could I hand you the ball on this? I'm still in the process of getting a code signing certificate 😅

**Comment by ssoloff** [comment]
@RoiEXLab I'll add it to the back of my task queue, but I'm concerned that it won't be as straightforward as the previous upgrades.  Being a major release, we may run into some breaking changes.  At a minimum, it's going to require some comprehensive testing.

**Comment by RoiEXLab** [comment]
Thanks @ssoloff 
this Issue has a pretty low priority, so don't feel obligated to hurry!

**Comment by ssoloff** [comment]
For anyone with an install4j 6 open source license key...  The v6 license key can be upgraded to a v7 license key [here](https://www.ej-technologies.com/support/upgradeProduct) at no charge.  This process will not revoke the v6 license key, so it can continue to be used until the v7 upgrade is complete.

**Comment by ssoloff** [comment]
The build after merging #2369 appears to have been successful.  I smoke tested the Unix installer from this build and observed no problems.  Closing this issue.
