### ISSUE TITLE
"triplea:" URLs do not work on Linux/Firefox

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/triplea#2286]
### My Operating System:
* Fedora 25 4.11.12-200.fc25.x86_64
* Firefox 55.0.1 (64-bit)

### TripleA version:
1.9.0.0.6358

### Map:
N/A

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
* Install TripleA on Linux with symlinks enabled.
* Use Firefox to navigate to `triplea:world_war_ii_classic`.

### Do you have the exact error text? Please copy/paste if so
TripleA starts and shows the following error after the main menu is displayed:

![launch-download-map-error](https://user-images.githubusercontent.com/4826349/29755700-b733828c-8b69-11e7-8ed0-49dd9f6fcfc0.png)

### Instead of this error, what should have happened?
TripleA should have opened the Download Maps window and either started downloading the map or informed me that it was already installed.

### Any additional information that may help:
Using `ps`, I grabbed the exact command line that was used to start TripleA (I added the line breaks to make this easier to read):

```
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.141-1.b16.fc25.x86_64/jre/bin/java \
  -splash:/home/ssoloff/Downloads/TripleA_1.9.0.0.6358/.install4j/s_8of556.png \
  -Dinstall4j.jvmDir=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.141-1.b16.fc25.x86_64/jre \
  -Dexe4j.moduleName=/home/ssoloff/Downloads/TripleA_1.9.0.0.6358/TripleA \
  -Dinstall4j.launcherId=33 \
  -Dinstall4j.swt=false \
  -Di4jv=0 \
  -Di4jv=0 \
  -Di4jv=0 \
  -Di4jv=0 \
  -Di4jv=0 \
  -Xmx1G \
  -Xms1G \
  -Di4j.vpt=true \
  -classpath /home/ssoloff/Downloads/TripleA_1.9.0.0.6358/.install4j/i4jruntime.jar:/home/ssoloff/Downloads/TripleA_1.9.0.0.6358/bin/triplea.jar \
  com.install4j.runtime.launcher.UnixLauncher \
  launch \
  ab9dd710 \
  /home/ssoloff/Downloads/TripleA_1.9.0.0.6358/error.log+  \
  games.strategy.engine.framework.GameRunner \
  'triplea:world_war_ii_classic'
```

You can see that the sole argument to TripleA is single-quoted, and those single-quotes are getting passed to the application rather than being removed by the shell (as evidenced by the error dialog).  Presumably, the way the install4j launcher starts TripleA is using an API that doesn't go through a shell but starts the process directly (e.g. the `system()` vs. `execve()` C API calls).  That would explain why the quotes are not being stripped.

This is probably an install4j issue, but would require further research to verify.  If so, but if it can't be resolved through install4j, a possible workaround is to modify TripleA to strip leading/trailing quotes before processing command line arguments.

I verified that this problem does not occur on Windows.

**Comment by ssoloff** [comment]
@RoiEXLab Please take a look when you have a chance, as the solution may be obvious to you.  Otherwise, I'll dig deeper when I can get around to it.

**Comment by RoiEXLab** [comment]
Hmm there are a couple things that could be the issue:
1. Could you verify the generated file in ~/.local/share does contain double quotes as supposed to?
2. Is this a Firefox only problem? Does chromium work without problems?
3. I assume you are typing this link directly into the adress bar, does it work properly when clicking on any links generated by the website?

@ssoloff The reason why it doesn't even try to open the maps window, is because it checks if the provided string starts with `triplea:` which it doesn't because it starts with a quote.

**Comment by RoiEXLab** [comment]
@ssoloff Also, while you're testing it: Could you check if this error still persists, when launching TripleA directly from the command line e.g. `/path/to/triplea "triplea:270BC Variants"`?

**Comment by ssoloff** [comment]
@RoiEXLab 

> Could you verify the generated file in ~/.local/share does contain double quotes as supposed to?

Yes, the `Exec` key has the URL argument in double quotes:

```
Exec="/home/ssoloff/Downloads/TripleA_1.9.0.0.6358/TripleA" "%u"
```

> Does chromium work without problems?

I have Chrome installed, but, for some reason, it doesn't recognize the custom protocol handler.  I didn't try to debug that too long and just punted.

> does it work properly when clicking on any links generated by the website?

The same problem occurs when downloading via the website.

> Could you check if this error still persists, when launching TripleA directly from the command line

This works fine using either double quotes or single quotes because the shell is stripping them.  However, if I escape the quotes, I can reproduce the problem:

```
$ ./TripleA \'triplea:world_war_ii_classic\'
```

**Comment by RoiEXLab** [comment]
@ssoloff Thanks for the report! I'm concerned, that this issue is a firefox-linux problem rather than an install4j Problem.
Could you create another protocol handler which runs the echo command or something similar which is the written to a file?
I have an Idea what might be happening:
Maybe firefox on linux tries to be smart, and inserts quotes automatically, so the actual command turns into:
```
/home/ssoloff/Downloads/TripleA_1.9.0.0.6358/TripleA "'triplea:world_war_ii_classic'"
```
which would also escape the quotes, so try removing the quotes around %u to see if that fixes the issue

**Comment by ssoloff** [comment]
@RoiEXLab 

>> Yes, the Exec key has the URL argument in double quotes

Apparently, this is the problem.  According to the freedesktop.org [Desktop Entry Specification](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html), the `%u` **must not** be quoted:

> Field codes must not be used inside a quoted argument, the result of field code expansion inside a quoted argument is undefined.

I edited my `.desktop` file to remove the quotes around `%u`.  Now when I go to a `triplea:` URL, the error dialog no longer appears, and the Download Maps window is correctly opened.

However, when clicking a link from the website, it appears TripleA is not normalizing the map name correctly.  For example, clicking World War II Classic results in the following message displayed after the Download Maps window is opened:

![download-maps-unknown-map-name-error](https://user-images.githubusercontent.com/4826349/29785091-518c1bca-8bf4-11e7-9c59-ad7a98c0c41f.png)

Apparently, the map name normalization code does not expect possibly URL-encoded entities, such as `%20`.  We should probably URL-decode the argument in `ArgParser` before passing it to `DownloadMapsWindow` since that code knows it's dealing with an URL.

**Comment by RoiEXLab** [comment]
That shouldn't be too hard to fix... I will submit a PR in about half an hour...
Thanks for the analysis!
