### ISSUE TITLE
Missing unit of time (AI pause duration)

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#2295]
### TripleA version:

1.9.0.0.6386

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)

Hit engine preferences, under "AI" see
![tra1](https://user-images.githubusercontent.com/20812775/29845504-5c3136e4-8d13-11e7-8633-5b3d44206639.PNG)

Is it 400 milliseconds? What is the maximum?

**Comment by ron-murhammer** [comment]
@panther2 Yeah, its milliseconds. I'm pretty sure it used to be there and must have gotten lost in the preferences updates.

**Comment by ssoloff** [comment]
@panther2 The permissible range of each setting, where applicable, is now available via tooltip by hovering your cursor over the text field containing the current value (`400`).
