### ISSUE TITLE
Install4j keeps "useless" information in Windows Registry when uninstalling

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#2308]
### My Operating System:

Win 7.64

### TripleA version:

all

### Any additional information that may help:

With every installation, install4j writes information as follows to the registry:

```
[HKEY_CURRENT_USER\Software\ej-technologies\exe4j\pids]
"d:\\download\\triplea_1.9.0.0.6426_windows-64bit.exe"=dword:000008a0
```

This version-specific information is **not** removed when uninstalling.
So by the time you get a huge list of dwords, that I manually remove from time to time.
Any chance this entry can be removed when uninstalling outdated versions?

**Comment by DanVanAtta** [comment]
There may be something in install4j somewhere. If not we may need to seek the help of the install4j people.

**Comment by RoiEXLab** [comment]
@DanVanAtta I don't think theres a setting, this seems to be an internal value of install4j alone... I will kindly ask the support about this, closing in the meantime

**Comment by RoiEXLab** [comment]
I'm guessing this is also the case using install4j 7, but this problem seems to be present using all install4j products, I had some entries for JProfiler in there (I uninstalled it).

**Comment by RoiEXLab** [comment]
I verified, this issue is also happens when using the latest version of install4j when creating the installer.
I will report, once the install4j support tells me more.

**Comment by RoiEXLab** [comment]
ej Support responded, they added this to their bug tracker
