### ISSUE TITLE
Asset Source Management and Packaging

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#231]
### Topic
 How to move binary files, aka "asset" files out of the triplea-game/triplea repo. Goal will be to have the source code repo only contain source code (we in danger of hitting the 1GB limit eventually, and it would be nice if we could prune the large binary data into other repo's so clone operations could be nice and fast)

I would like to use this issue to discuss requirements and start coming up with a high level plan of how to solve the problem. 

### Some Requirements  and Key Problems to solve
- TripleA repo has a good bit of binary data in it. We are threatening the 1GB repo limit. It represents a small scaling problem with respect to source code management.
- Files managed by Git LFS are links when obtained via git clone, so simply throwing Git LFS into the mix complicates the build process

### A potential first approach for discussion 

**assets folder**:
- create a second repo for the "assets" folder
- move the assets folder wholesale into the new repo
- move any lossless or pre-compressed files into a top level directory, and run compression/optimization tools (and verify)
- create a build script that will simply zip the assets folder and push it to releases (compression tools will always be a one-off process, never done by the build for simplicity and to "force" human verification)
-  add the lossless formats to Git LFS. I expect this will probably be just "wav" file types for now.
- finally, fix the game engine so tests can be run as normal and a local game can be launched from source code

**maps folder**:
- move all of these out of the repo in favor of the new map repo(s). The map to github migration project  should allow for this to be done.

**Comment by DanVanAtta** [comment]
@veqryn , @ron-murhammer  To summarize, this issue is requesting that we move binary assets, non-source code files, to staging repositories. We'll then use the staging repositories during the build process to create the installation artifacts. In the meantime the staging repositories are a way to scale out how we store binary data. If I'm not mistaken we are roughly at 750MB of our repo usage, hitting 1GB is going to be a reality one day not too far in the future. Hence this issue to address that problem with some gory details of how to solve it. Simply need you guys to agree on a solution and I'm then offering to build it into the release process.

**Comment by veqryn** [comment]
I am fine with this.  It does complicate things for new-comers, which I am a little unhappy about, but the upside could be worth it.

So, the new repository will have one folder called "assets" which has our current assets folder, and then possibly other top level folders for other things, like full sized lossless wave files, etc.  Is that right?

And then we would pull this in as a git subrepository or just with gradle?

And what about our lib directory?  I know most of it will get replaced by gradle pulling from maven or where-ever, but we will still need the upnp and maybe other jars.  Since it will be limited to just a couple jars, do we just leave that with the main git project (which would probably be my preference)?

**Comment by DanVanAtta** [comment]
I created the assets repo. It is currently storing some files needed during the release process: https://github.com/triplea-game/assets. Looks like a simple build script will be in order to zip up the assets folder and post it as a release. But will need to first double check how gradle can download it if we do that.


> So, the new repository will have one folder called "assets" which has our current assets folder, and then possibly other top level folders for other things, like full sized lossless wave files, etc. Is that right?

Correct

> And then we would pull this in as a git subrepository or just with gradle?

I was very unimpressed with subrepositories when I looked into them. Gradle I think is a clean solution since it already sets up the workspace. The assets folder will be just another thing to download for Gradle.

> And what about our lib directory? 

I agree jars that are not available in a maven repo can live with the source code for the medium term, maybe long term.  Sonatype does offer an open source license for a nexus (maven) repository where we could host jar files if we ever wanted.

**Comment by gaborbernat** [comment]
For the local JARs we can either swap them out for a version that does exist in the maven repository. Or just submit our version to the maven repository.

**Comment by DanVanAtta** [comment]
The jars needed for mp3 are an example of some that are not in any repository. There is not really any maven repository we can submit it to. Nexus is an option if we wanted to have a maven repo where we could host those jar files.

**Comment by gaborbernat** [comment]
If we go down that path stick to the more general artifactory repository :)

**Comment by veqryn** [comment]
I am still not too familiar with how gradle works, but with maven you can create a "local" repository inside of your git project, which gets automatically added to the available repositories.  And when it comes time for maven to pull in dependencies, it looks there.
I am sure gradle has something similar, and that would be a lot easier and more simple than using nexus or artifactory.

**Comment by DanVanAtta** [comment]
If I follow correctly, gradle simplifies some things compared to maven. Repositories and dependencies are decoupled. For us we only have one repo (taken from our build.gradle file):

```
repositories {
        jcenter()
}
```

Then dependencies are pulled in by name, in case it's a local file you can give a path too:
```
dependencies {
        compile 'com.sun.mail:smtp:1.5.4'
        compile 'com.google.guava:guava:18.0'
        compile files('lib/upnp.jar')
}
```

So if we wanted to get rid of the "files('lib/upnp.jar')", we could get some nexus credentials and upload the file there instead of having it with the source code. Considering we've been living with 700MB of binary data, I'm not worried about 20MB right now : )     Of note, Sonatype does have a cloud hosted Nexus service that is free for open source projects, so we wouldn't have to set much up.

**Comment by DanVanAtta** [comment]
Key issue next is to figure out how much of the assets folder is actually needed at runtime, this will tell us how much of it we need to pull in via gradle.

We then need a way to DL the asset file with gradle.

Finally, we need to have a static link where we can get the assets, likely this means creating a simple build script to host a zip of the assets.

**Comment by DanVanAtta** [comment]
#280 has the action items needed next, namely:

- [ ] move game assets from assets folder to repository https://github.com/triplea-game/assets 
- [ ] create a build script for that repository to bundle all the files into a zip
- [ ] update the build to download the latest zip release and extract/bundle it with the game installer 
- [ ] make sure local eclipse and gradle builds and unit tests still work

Resolving this ticket now in favor of #280
