### ISSUE TITLE
Loaded games cleared out

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#2314]
Entering the main screen either after quitting a game or on loading Triple A initially, if you load a game quickly enough it is cleared out by some automatic game selection logic. This no longer prevents loading a game from the command line though.

Is this issue clear? There's clearly some sort of race condition of a multithreaded process when single threading would have been more suitable.

**Comment by RoiEXLab** [comment]
Are you using one of the more recent versions of TripleA? I recall having fixed this big in a PR, but it isn't out in a stable version yet

**Comment by simon33-2** [comment]
Ok, I've just grabbed the most recent version. It seems that the problem is resolved for command line file specs but I can still get a problem but loading up something quickly enough after quitting a game. I guess with a fast enough computer, that would be unlikely.

**Comment by RoiEXLab** [comment]
Let's just rename this issue to focus on the existing issue...

**Comment by simon33-2** [comment]
What would be a better name?

**Comment by RoiEXLab** [comment]
Hmm. I can't think of a better name... 
It'll be sufficient to just edit your description of the issue

**Comment by ssoloff** [comment]
>  I recall having fixed this bug in a PR

#2039

**Comment by simon33-2** [comment]
Hmm, I can still get it to stuff up if I quit a current game and quickly load another one. It is annoying because when you click play the default game is loaded.

**Comment by simon33-2** [comment]
Video: https://github.com/triplea-game/triplea/files/1313981/loseSaveGame.zip

Shows one instance of it working, then one instance of it not working. Also posted in #2368.

**Comment by RoiEXLab** [comment]
@simon33-2  This Framerate (15FPS) is killing me, but you load a game, close it quickly, load another one quickly, click quickly on play and then it loads the previously loaded savegame instead of the newly selected one.
Is that correct?

**Comment by simon33-2** [comment]
Not quite. After exitting one large game, selecting another large game, then clicking "Play", the default game is loaded, not the selected game.

Do you want a slower frame rate?

I'm not sure why it worked in the first instance! Perhaps I was just a little too slow to see the problem.

**Comment by RoiEXLab** [comment]
More frames ^^ Not less, I can slow the video down on my own ^^
Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaahhhh. Now I think I know what you meant.
So you mean, you selecte the savegame, but instead of loading the savegame TripleA just loads the map without the savegame applied to it?

**Comment by simon33-2** [comment]
Yes, correct.

**Comment by simon33-2** [comment]
Do you want me to recreate the video?

Notice the round number in the bottom right. The filename ends with the round number which should be used (as you might expect). After the second time I load the game, it is set to 1.

**Comment by RoiEXLab** [comment]
@simon33-2 I don't think it's neccessary to recreate it...
I have an odie how we could possibly fix this...
