### ISSUE TITLE
Map directory CLI Argument not working for Headless Bots

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#2316]
Noticed this with the latest pre-release,
When starting a bot using `java [other args] mapFolder=/home/triplea/maps`, the setting is displayed in the starting log, but is not actually applied (TripleA still searches in /home/triplea/triplea/downloadedMaps).
There's of course a workaround for this, to just copy all the files to the default directory, but this is certainly not the intention.
I assume this was introduced with @DanVanAtta's changes to the Engine Preferences, it's not the case in the current stable release.

**Comment by DanVanAtta** [comment]
I'm not actively working on this, removing assignment.

**Comment by RoiEXLab** [comment]
No Problem, intention was to get possible input from your side, because I skimmed some of the affected code and couldn't find the introducing change...

**Comment by RoiEXLab** [comment]
Closing via  #2321
