### ISSUE TITLE
EventThreadJOptionPane#showMessageDialogWithScrollPane() runs UI code off the EDT

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/triplea#2323]
Originally reported in #2322.  The error log attached to that issue demonstrates that the `EventThreadJOptionPane#showMessageDialogWithScrollPane()` method invokes `createJLabelInScrollPane()` (which creates UI components) off the EDT.

This is a regression caused by the last commit of #2313 (962df43).  Testing in that PR didn't catch the issue because I use the Nimbus L&F, which doesn't have a robust AWT error handler like the Substance L&Fs.

**Comment by ssoloff** [comment]
@panther2 This should be fixed in build 6464 or later.  Please reopen if you continue to observe these types of errors.

**Comment by panther2** [comment]
Looks good so far in 6465 (tested with savegame from #2322). Thanks!
