### ISSUE TITLE
Player "Limit" (movement/attacking/placement) Always Behave As "all" (Units) When The Limit Is Exceeded (1.9.0.0.6380)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#2325]
The Player attachments:

**movementLimit
attackingLimit
placementLimit**

currently have the behaviour that, once the territory has a number of units in excess of the limit, then all units are impeded the respective actions, not only the specified ones.

For example, if I have:

```
<attachment name="playerAttachment" attachTo="Russians" javaClass="games.strategy.triplea.attachments.PlayerAttachment" type="player">
<option name="movementLimit" value="total:infantry" count="1"/>
</attachment>
```

What happens is that, if in the territory I want to move into there is 1 owned or allied infantry, already in there, then:
- no more infantries are allowed to move in there,
- but infinite other units still can (as the limit is referring to the "infantry" units only);
- and enemy infantries are not accounted for the limit.

The above behaviour is correct.

However, if in the territory I want to move into there are 2 or more infantries already in there, then the engine impedes me to move into any units at all.
I believe this is a bug.
I assume the correct behaviour should be, in the above case, that only "infantry" has any restrictions, while I should be able to move into any territories infinite quantities of other units, no matter how many infantries in the target territory.
Of course, in the case above, having 2 infantries in the same territory would never happen with Non Combat Moves, due to the correctly enforced limit of 1.
However, having more than 1 infantry in the same territory may of course happen due to other actions, and this is the reason for having separate movement, attacking and placement limits. For example, if I set only the above code, I can end with 2+ infantries in the same territory because I attacked the territory with 2+ infantries or because I placed 2+ infantries in the territory (since I'm limiting only non combat movements, with the setting above).

This bug is the same for all the above options, for their respective applications (non combat moving / combat moving / placing).

If I have:

`<option name="attackingLimit" value="total:infantry" count="1"/>`

then nothing at all can attack territories with 2 or more enemy infantries in it (while only infantries should be unable to).

If I have:

`<option name="placementLimit" value="total:infantry" count="1"/>`

then I can place no units at all in any territories with 2 or more mine or allied infantries in there (while I should only be unable to place more infantries).

This is the explanation of the above options, as per PoS2:

> movementLimit - values: only affects normal movement. count equal to the maximum number of units allowed in a territory. value must start with "owned", "allied", or "total", then after that is a colon delimited list of units or the word "all".
> You may have multiple instances of this, per player. example: `<option name="movementLimit" value="owned:Battleship:Battlecruiser:Cruiser:Destroyer:Submarine:Transport" count="4"/>`
> attackingLimit - values: only affects movement into enemy territory/units. count equal to the maximum number of units allowed in a territory. value must start with "owned", "allied", or "total", then after that is a colon delimited list of units or the word "all".
> You may have multiple instances of this, per player. example: `<option name="attackingLimit" value="owned:Battleship:Battlecruiser:Cruiser:Destroyer:Submarine:Transport" count="4"/>`
> placementLimit - values: only affects placement. count equal to the maximum number of units allowed in a territory. value must start with "owned", "allied", or "total", then after that is a colon delimited list of units or the word "all".
> You may have multiple instances of this, per player. example: `<option name="placementLimit" value="owned:Battleship:Battlecruiser:Cruiser:Destroyer:Submarine:Transport" count="4"/>`

Summarising:

- The above options work fine if the related units are exactly the same number as the set limit or lower (but the whole point of having them limited to some actions is that the other actions can have this limit exceeded, instead).
- The above options bug off if the related units are in excess to the limit, impeding entering any units (also units having no limits at all), not only the specified ones, just like if you set "all", instead of some units.
- I believe the task would be to look at the code and avoid that if the limit is already exceeded (by 1 or more), then all units are blocked, instead of only the specified ones.

These properties I believe are not frequently used, but are pretty handy, to enforce limits across multiple units. For example, you need these properties for cases like the aaGun limit of Classic, if instead it applies to more than 1 unit only (for example, you have two kind of aaGun, but only one of either can stay in the same territory).

I hope this can be fixed easily, as everything works fine if the units in the territory are exactly equal to the limit, but it bugs off if they are more than that. No clue why it is working fine for the exact limit, but not for more than that.

So, the option is already working fine when the limit is reached. It is needed to assure it still works the exact same way when the limit is (already) exceeded, instead.

To test it, just paste the above code inside whatever traditional games (to assign the movementLimit to Russians).

The case is particularly extreme for the attackingLimit. For example, if you paste this:

`<option name="attackingLimit" value="total:infantry" count="1"/>`

you will see that, then, you cannot attack at all, with any units, any territories with 2 ore more (enemy) infantries in them. I believe the correct behaviour should be that only the infantries should be affected, instead (this is what happens if we are exactly at the limit, not over it). Practically, in this case, with no other settings, as it works, the opponent can make itself invulnerable to anything by assuring to have 2 infantries in each territory (of course he can, since the limit here would be only for attacking, not for non combat moving or placing and, besides, it is set for a specific player, so the opponent may have no limits at all, on its own actions).

**Comment by ron-murhammer** [comment]
@Cernelius Does this work properly in the current stable release?

**Comment by ron-murhammer** [comment]
@Cernelius Can you also provide a save game showing the behavior so any fix can be verified?
