### ISSUE TITLE
Organizing the Issue Queue

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#233]
I was looking at the issue queue and was wondering how we can squash it. Namely how to close it out. Since I'm the author of over half of these, a good queue will always have actionable items, so I really should be able to close each one out pretty readily.

The problem appears to be for the moment bug reports and feature requests are not easily actionable. The trick for them IMO would be to hide them. Two non-mutually exclusive ways I can think of to do this:
- label them as "bug report" and "feature request", that way they can be excluded easily with a URL you can bookmark: http://github.com/triplea-game/triplea/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+no%3Alabel
- move them to another repo that is dedicated to issues, feature requests etc.

A second repo I'm not yet convinced about. Perhaps that could be a second step. Initially I did not think there was much benefit to it, but some consideration and there could be. Notably if we gave all-in permissions to just about anyone to that repo. We allow it to be a bit chaotic and for it to be an idea mill. Feature requests will be submitted there, and converted to "feature specs" which could then live in the triplea game queue proper. Bug reports could be triaged there and then converted to more spelled out, developer friendly bug reports in the game queue.

IMO labels are a good first step. A second repository is not a clear win, but I think worth some discussion and consideration.

For labels, looking at the current issue queue, one set of labels could be:

"Feature Requests": #55, #211, #232,  #37
"Bug Reports": #210, #221
"Project": #31, #214, #216
"Process": #215, #224, #231

Here are the titles of each issue and the current queue (for reference):
![issue_queue](https://cloud.githubusercontent.com/assets/12397753/10555213/894efaa2-7420-11e5-9b05-9426509ea335.png)

* Project vs Feature Request: one is ongoing, the other is a parking ticket. A ticket could be first labelled as a feature request, then could also be labelled a project when it is started.

**Comment by DanVanAtta** [comment]
One thing to consider, perhaps instead of "project" label we use a milestone for it instead.

**Comment by DanVanAtta** [comment]
@veqryn , @ron-murhammer , any objections if I take a first stab at assigning labels to the issues in the queue?

**Comment by ron-murhammer** [comment]
Go for it. My recommendation is to keep it clean and simple.

**Comment by DanVanAtta** [comment]
Came up and applied 4 labels so far:
**Feature Request** : tracking tickets for feature requests
**Process Improvement** : Process project, build and release or development process. Basically everything that is devops.
**In Progress** : Indicates being worked on
**Bug** : bug tracking tickets

**Comment by DanVanAtta** [comment]
Added another  label:
**needs solution**: indicates that the "how" to fix is not yet known. The difference between this and other tickets is in other tickets we know what to do, but have not done it yet. In this case, we are not yet sure what needs to be done.

@veqryn , @ron-murhammer , only issues labelled as "needs solution" or "process improvement" currently need to be looked at. The rest are parking/tracking tickets.
