### ISSUE TITLE
Existing Bombing Damage Not Displayed on Bombing Target Selection Window

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#2333]
**Bug:** Bombing target selection window doesn't display existing bombing damage

**Enhancement:** Wanted to know if it would be possible to add a visual component to the target selection window for Bombing runs.

The current window appears as this:
![image](https://user-images.githubusercontent.com/1427689/30190060-5386e084-93fd-11e7-9855-605904b3bb0a.png)

However I was wondering if a visual component could be added like this:
![image](https://user-images.githubusercontent.com/1427689/30190062-5a93e872-93fd-11e7-8e11-d46ec48a3280.png)

The issue was brought to my attention that if you have multiple of the same target in the same territory one perhaps with damage and the other that does not... currently there is no way to tell them apart.

**Comment by DanVanAtta** [comment]
Good catch, +1 to this suggestion.
@ron-murhammer should this be labelled as a usability problem instead as bug (aka defect)? A bug to me applies something is not working as intended or doing something very unexpected (and broken). This seems like a very good example of a usability problem to me, everything is working as intended, but in practice, the feature is difficult or impossible to use.

**Comment by ron-murhammer** [comment]
@DanVanAtta It could go either way. Given that there is important information missing to make a decision, I'd lean towards bug in this case as we are not displaying something that absolutely should be displayed. Not really a big deal either way though.

**Comment by DanVanAtta** [comment]
Instead of hijacking this issue further with bug vs usability, I opened a quick issue to discuss labelling: #2335, I only draw the nit distinction to justify having the two different labels, we perhaps may just want to merge the two labels.

**Comment by prastle** [comment]
Hepps drew a great diagram of what we talked about.  I am curious about the overall decision. Either way it is definitely hard to understand if you are a first time user.  Thus I definitely have to say its a usability issue.  Is this a bug?  hmm.   I would say it is also a bug.  Now that trains have been added we added one more thing that can be bombed to the  item roster.  Just my 2 cents
