### ISSUE TITLE
Bots being updated?

### ISSUE THREAD

**Issue by prastle** [triplea-game/triplea#2336]
I apologize if this shouldn't be brought up in this manner. I just don't seem to be getting any responses/posts in the gitter server thread other than me when things get updated to the bots. Thus why I am asking?
How are the bots being updated or was I the last one to do so? @RoiEXLab showed me an excellent program which sadly doesn't work. Fillezilla.
Do we need to keep manually updating the bots whenever a new map is released?

**Comment by prastle** [comment]
I apologize if this shouldn't be brought up in this manner.  I just don't seem to be getting any responses/posts in the gitter server thread other than me when things get updated to the bots.  Thus why I am asking?
  How are the bots being updated or was I the last one to do so?  @roiex showed me an excellent program which sadly doesn't work.  Fillezilla.   
  Do we need to keep manually updating the bots whenever a new map is released?

**Comment by DanVanAtta** [comment]
> Do we need to keep manually updating the bots whenever a new map is released?

Yes, that was the case before, still now. Ideally we would put the commands behind a cron job or similar to run on a periodic basis. The current script downloads everything and would use a bit too much network if we ran that all the time. We would be better to check frequently for latest versions and update as needed.

In the meantime making the update script 'one-touch' so you can login and run it and logout, that would be quite helpful to start.

**Comment by DanVanAtta** [comment]
(edit note: consolidated via copy/paste prastle's comment to the overview)

**Comment by RoiEXLab** [comment]
@DanVanAtta An update script would be very useful. It's not that difficult to update it manually using the new scripts, just a couple of commands and a restart, but it would be nice to have a simple update script which only accepts an optional version parameter (reimplement the assume stable version, if version is omitted), which also removes legacy bot versions automatically.

**Comment by DanVanAtta** [comment]
> which also removes legacy bot versions automatically.

I recommend putting the removal in a dedicated script so you are not forced to run it. We could then create a simple 'command wrapper' script for convenience and to document the full end-to-end, eg:
```
% cat update_all.sh
update_maps
remove_old_bots
install_new
```

Really to start, we need a map update script that downloads only the newest and missing, or at least run the current one automatically once a week.

**Comment by RoiEXLab** [comment]
@DanVanAtta Adding a cronjob to automatically update the maps seems like a good idea. The Problem is going to be that we currently need to restart bots for the maps changes to take effect.
So we either need to determin a way to check if the bots are currently in-game, or we add a file changed listener for the map directory, which then reloads the maps once they change.

**Comment by prastle** [comment]
Yes they still have to be restarted.  It's to bad filezilla doesn't work.  It made it real easy.

**Comment by RoiEXLab** [comment]
FileZilla is a tool to manage files on a remote server, nothing more. And it does do that as it's supposed to.

**Comment by DanVanAtta** [comment]
> The Problem is going to be that we currently need to restart bots for the maps changes to take effect.

Are you sure? I think I saw/noted that it would actually take effect when the map is started/played (note that we do a 'parseFull' at that time which parses all of the map XML). That may be the case though to pick up brand new maps.

IF we really do need a restart, we may instead better focus on how we do map loading for bots, so it would behave more similar to the headed single player case

**Comment by RoiEXLab** [comment]
@DanVanAtta I'm pretty sure, there are also other inconsistencies when it comes to headlessserver map loading.
Have a quick look at the HeadlessGameServer class and you will notice completely seperate code for map loading than for headed clients.
The main functional differenc being that HeadlessGameServers can't load maps that are not present in the triplea_maps.yaml file

**Comment by prastle** [comment]
@DanVanAtta  @RoiEXLab   The lobby is slow atm.  I stopped the DE server bots since they are not needed.  Perhaps we can load the new stable on them as a test?  Just a thought.

**Comment by prastle** [comment]
The new update all works fine... we should probably deleted this for now but up to @RoiEXLab
