### ISSUE TITLE
Lobby Crash

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#234]
It appears the lobby crashed a few hours ago. I believe this is the error from the logs:

Mon Oct 19 20:59:54 EDT 2015 SEVERE [Headless console eval print loop] ERROR -> java.io.IOException: Input/output error
Mon Oct 19 20:59:54 EDT 2015 SEVERE [Headless console eval print loop] ERROR -> 	at java.io.FileInputStream.readBytes(Native Method)
Mon Oct 19 20:59:54 EDT 2015 SEVERE [Headless console eval print loop] ERROR -> 	at java.io.FileInputStream.read(FileInputStream.java:199)
Mon Oct 19 20:59:54 EDT 2015 SEVERE [Headless console eval print loop] ERROR -> 	at java.io.BufferedInputStream.read1(BufferedInputStream.java:256)
Mon Oct 19 20:59:54 EDT 2015 SEVERE [Headless console eval print loop] ERROR -> 	at java.io.BufferedInputStream.read(BufferedInputStream.java:317)
Mon Oct 19 20:59:54 EDT 2015 SEVERE [Headless console eval print loop] ERROR -> 	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:264)
Mon Oct 19 20:59:54 EDT 2015 SEVERE [Headless console eval print loop] ERROR -> 	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:306)
Mon Oct 19 20:59:54 EDT 2015 SEVERE [Headless console eval print loop] ERROR -> 	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:158)
Mon Oct 19 20:59:54 EDT 2015 SEVERE [Headless console eval print loop] ERROR -> 	at java.io.InputStreamReader.read(InputStreamReader.java:167)
Mon Oct 19 20:59:54 EDT 2015 SEVERE [Headless console eval print loop] ERROR -> 	at java.io.BufferedReader.fill(BufferedReader.java:136)
Mon Oct 19 20:59:54 EDT 2015 SEVERE [Headless console eval print loop] ERROR -> 	at java.io.BufferedReader.readLine(BufferedReader.java:299)
Mon Oct 19 20:59:54 EDT 2015 SEVERE [Headless console eval print loop] ERROR -> 	at java.io.BufferedReader.readLine(BufferedReader.java:362)
Mon Oct 19 20:59:54 EDT 2015 SEVERE [Headless console eval print loop] ERROR -> 	at games.strategy.engine.lobby.server.headless.HeadlessLobbyConsole.printEvalLoop(HeadlessLobbyConsole.java:98)

**Comment by ron-murhammer** [comment]
This appears to be the method it errors on:
  private void printEvalLoop() {
    out.println();
    while (true) {
      out.print(">>>>");
      out.flush();
      try {
        final String command = in.readLine();
        process(command.trim());
      } catch (final Throwable t) {
        t.printStackTrace();
        t.printStackTrace(out);
      }
    }
  }

**Comment by ron-murhammer** [comment]
@veqryn Any ideas? Have you seen this happen before?

**Comment by veqryn** [comment]
no idea.  do you have access to linode?
is the lobby fine now?

**Comment by DanVanAtta** [comment]
I emailed @ron-murhammer some time ago, he bounced it before opening this ticket - it is back up now.

**Comment by ron-murhammer** [comment]
@veqryn I don't believe so. I just logged onto the tripleawarclub server and found that there were no screens running. So just restarted the lobby then the bots. Not sure if the server itself went down or the lobby crashed.

**Comment by veqryn** [comment]
@ron-murhammer: can you make an account here: https://manager.linode.com/linodes
I can then add you to the list of users who can reboot the servers remotely, etc.
I am still not sure if I am reading the graphs wrong or not, but I think the server might have been restarted...

**Comment by ron-murhammer** [comment]
@veqryn - Account created with username=redrum and email=ron.murhammer@gmail.com

**Comment by ron-murhammer** [comment]
So looks like there was a server restart yesterday which is why the lobby was down. Brings up a good point that it would be nice to have the run lobby script called on startup.

**Comment by DanVanAtta** [comment]
Cut #252 to capture the remaining action item, Closing. Please open additional issues if there are more action items resulting from this event.
