### ISSUE TITLE
Still incorrect handling of Facility bombing

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#2340]
### My Operating System:

Win7.64

### TripleA version:

1.9.0.0.6507

### Map:

wwII_Global_1940
wwII_v5

### Any additional information that may help:

This is a follow-up of #2322 and #2337 .

At a first glance, everything seems to run fine now.
Now the engine allows to choose to SBR correctly.

But starting (again) from this position 
[SBR_StartPosition.zip](https://github.com/triplea-game/triplea/files/1287053/SBR_StartPosition.zip)
you will realize that the max-damaged air- and naval-bases will not execute AA-fire against the tactical bombers. (Also the bombing itself is skipped, though this would be acceptable as further damage cannot be assigned.)

Also in these savegames

[SBR_StartPositionFactoryFrance.zip](https://github.com/triplea-game/triplea/files/1287059/SBR_StartPositionFactoryFrance.zip)
(Send any German (strat.) bomber to France.)

[SBR_v5_StartPosition.zip](https://github.com/triplea-game/triplea/files/1287060/SBR_v5_StartPosition.zip)
(Send bomber from Germany to UK.)

you will see that max-damaged factories don't fire their built-in AA-guns. (Also the bombing itself is skipped, though this would be acceptable as further damage cannot be assigned.)
Though these two scenarios should not occur as the attacker can only lose planes and gain nothing - but in case they occur - maybe due to carelessness - AA-fire should occur, too.

Whatever damage does not affect the self-defense antiaircraft ability of the facility.

**Comment by ron-murhammer** [comment]
@panther2 Ah, damn. I forgot about AA. I just need to make one more small change to fix the remaining issue.

**Comment by ron-murhammer** [comment]
@panther2 Can you try testing it out in a few scenarios again to see if its resolved in the latest pre-release?

**Comment by panther2** [comment]
@ron-murhammer 

Thank you.
The issue is resolved for the first of the above scenarios only.

In case the bombers are sent against max. damaged facilities only, they can be assigned to SBR, but AA fire is still missing. You can prove this by adding max. damage to the factoy in the above SBR_StartPosition, too.

Or by using the other two savegames.

**Comment by ron-murhammer** [comment]
@panther2 Alright let's try this one more time (sorry for the multiple false starts). I tested that it allows AA and bombing even if there are only max damaged targets.

**Comment by panther2** [comment]
@ron-murhammer 
I can confirm it runs fine now in all tested scenarios with 6542. Thank you!

**Comment by ron-murhammer** [comment]
@panther2 Excellent. Also any additional testing on other maps with various SBR rules is appreciated. I want to make sure the changes didn't have any negative effects. Thanks.

**Comment by panther2** [comment]
@ron-murhammer 
I did a quick testing on WWIIv3 and WWIIv4. No further issues there.
I will keep an eye on it when I come to test other maps.
