### ISSUE TITLE
Script standard proposal - usage text printed on no-arg invocation

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2341]
I'd like to make it standard for any ops scripts when run without any args will display usage and help text. This standard lets us then run any script we have safely without args to learn more, and won't have to wonder if the right help flags are `\h` `-h` `--help` `\?`, or something else, or if there is one even.

Any thoughts on this standard? If agreed next steps would be to add a note in the script heavy lobby repo, and see about updating scripts accordingly.

**Comment by RoiEXLab** [comment]
@DanVanAtta I'd suggest going with the Unix style flags only instead of the windows `\something` flags.

**Comment by DanVanAtta** [comment]
I'm hoping we use none of those flags, that's part of the point. No-args prints help text, no need for a flag.

**Comment by RoiEXLab** [comment]
@DanVanAtta Fine then, could potentially be problematic if the command does not require any arguments
