### ISSUE TITLE
Lobby login is very slow

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2344]
The lobby client login is very slow now that we are on a postgres only DB configuration. (very slow is around 30 seconds to a few minutes)

**Comment by RoiEXLab** [comment]
@DanVanAtta The more important question is which part is taking the most time.
Is it the server trying to process a request or the client taking too long to send a request and process a response?

**Comment by DanVanAtta** [comment]
client is the same, so presumably something server side. We tried same server hardware spec 2048 with both code bases and no noticeable difference. Good question indeed where the time being spent is.

**Comment by wirkey** [comment]
Login was still a bit slow.
More annoying is that I ain't a mod anymore. How am I supposed to abuse my powers if I don't have them anymore?

**Comment by Heppisorus** [comment]
Didn't you get the memo?

Awkward.

**Comment by DanVanAtta** [comment]
I'm questioning how much slower login actually is. I'm getting in under 20 seconds, but it was always a bit slow.. We had some severe minute plus logins, it does not seem that is the case anymore which really prompted this issue (90 second logins was a really long time).

We certainly need better data on performance, like how long it takes to log in.. Short term though there is not much to be done, particularly since we have not gotten many complaints about this.
