### ISSUE TITLE
introduce liquibase

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2356]
I think we should introduce liquibase into our stack. I think there are a few things to check on first, but there are some compelling reasons:

- the custom solution we have in the travis script is very obviously custom, it's not convincing that we run that against production. This has lead to a confused state where we do not know how to run DB commands properly.
- Our custom solution is not very adequate for update statements. It's much easier if we know something will not be executed twice vs making everything idempotent

-----------------

There are a couple of different ways to run liquibase and some investigation is needed. I think we will likely run it 'out-of-band' as a stand-alone command. So that means for example when you run integration tests, before running the tests a liquibase migration command would be run from CLI to update DB.

**Comment by ron-murhammer** [comment]
@DanVanAtta I'm fine if you want to add liquibase.

**Comment by ssoloff** [comment]
Inspired by [this article](https://martinfowler.com/articles/evodb.html#AllDatabaseChangesAreMigrations), an incremental improvement that wouldn't require fully switching to Liquibase would be to

1. keep a changelog table in the database itself that records each migration that has been applied, and
1. write a simple shell script that
    1. looks up the highest applied migration from the changelog table
    1. applies all migration scripts, in order, beginning with the first unapplied migration script until the most recent one
    1. for each migration script that is applied, add a new record to the changelog table

Even though the individual migration scripts may not be idempotent themselves, the orchestration script from (2) would ensure no migration is ever applied twice.

The script from (2) would essentially replace the last half of the `.travis/setup_lobby_database` script.  And it could be used in all environments: production, CI, and dev.

**Comment by DanVanAtta** [comment]
@ssoloff I was thinking similar, and a custom script do so would not be terribly difficult. But, for steps one and two that you have outlined, liquibase is exactly that (and not a whole lot more).

I think the next steps are to research how we would integrate liquibase and make it easy to run. I'll assign to myself to follow up further.

**Comment by DanVanAtta** [comment]
NB: @ssoloff @RoiEXLab liquibase runs migrations as a single transaction, so it simplifies a little bit the SQL that needs to be written. The `001_create_tables` file was created with liquibase in mind (at least in imitation of that setup)

**Comment by ssoloff** [comment]
Closing as we've since adopted Flyway to perform database migrations. @DanVanAtta, please reopen if necessary.
