### ISSUE TITLE
Planes Can Land on Edited Territory

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#237]
This happened earlier today:
- one player has a single plane on a territory due to misclick
- the other opponent captures the territory and kills the plane
- an edit is allowed and the plane and territory are put back
- at the end of the turn the plane crashes

Feature Request:
- Plane does not crash, if a territory is edited and a plane placed there, allow the plane should be able to land. In the case where combat occurred and edit was used to undo the combat, since the territory was held at the start of the turn, it reveals a game bug.

**Comment by ron-murhammer** [comment]
@DanVanAtta Agree but couldn't you just make the edit after end of turn. I'd consider this pretty minor if that workaround works.

**Comment by DanVanAtta** [comment]
If the edit is done before combat phase, then extra planes can potentially attack a territory which they were not able to previously. Sometimes it may not be completely obvious that was the case.

**Comment by DanVanAtta** [comment]
:white_flag:
