### ISSUE TITLE
Units edited during current movement phase ignored for bonus movement

### ISSUE THREAD

**Issue by Heppisorus** [triplea-game/triplea#2372]
### My Operating System:
Windows 10
### TripleA version:
1.9.0.0.6604 (all pre-releases I tried)
### Map:
Global variants, TWW (any map with units that provide extra movement)
### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Simply edit any unit that receives bonus movement from another unit... into the terr. with the unit providing the additional movement during the current movement phase (ie. combat, noncombat). The edited units will not receive the added bonus movement.
### Do you have the exact error text? Please copy/paste if so
No error is generated.
### Instead of this error, what should have happened?
Edited units should be subject to any bonus available at any point in a game phase.
### Any additional information that may help:
![edit bug](https://user-images.githubusercontent.com/30943648/30524243-e7517c26-9bbd-11e7-8de5-d9462bb85868.png)

**Comment by prastle** [comment]
:)

**Comment by ron-murhammer** [comment]
@Heppisorus @prastle This should be resolved in the latest pre-release. Please test and let me know.

**Comment by Heppisorus** [comment]
Sure thing

**Comment by Heppisorus** [comment]
Sure thing.  Look at it tomorrow.

**Comment by prastle** [comment]
Already checked yes it works.  TY

**Comment by ron-murhammer** [comment]
@Heppisorus Someone has to clean up your mess :)

@prastle Thanks! Gonna close this. If you find any issues, please let me know.
