### ISSUE TITLE
Clean up after upgrade to install4j 7

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/triplea#2377]
The following tasks need to be performed now that install4j has been upgraded to version 7 (#2285):

* [X] Backup the install4j 6 and 7 license keys (@ron-murhammer).
* [X] Remove the install4j 6 license key (`INSTALL4J_LICENSE`) from the Travis configuration (@ssoloff).
* [X] Disable the debug build feature on Travis (@ssoloff).

@ron-murhammer Since the first task may depend on the others (depending on how you choose to backup the keys), I'll hold off until the first task is complete.

**Comment by DanVanAtta** [comment]
@ssoloff backups of the keys are accomplished by distributing to multiple people. At least both Ron and I should have the keys, please send me the install4j 7 key.

When we remove the install4j 6 key, are we replacing it with the 7 key? Does 7 no longer need a license key?

Why disable the debug build feature in travis, can you point to me when it was added?

**Comment by ssoloff** [comment]
> please send me the install4j 7 key

Sure, not a problem.  However, I'd prefer to do this securely.  Can you email me your PGP public key so I can return the key to you encrypted?  I could also securely send you the key via ProtonMail if you have an account.

Alternatively, you can start a Travis [debug build](https://docs.travis-ci.com/user/running-build-in-debug-mode/) to [extract the key](https://stackoverflow.com/questions/31519546/how-i-can-decrypt-secure-env-variables/44059814#44059814) yourself from the `INSTALL4J_7_LICENSE` environment variable.

> When we remove the install4j 6 key, are we replacing it with the 7 key? Does 7 no longer need a license key?

install4j 7 does indeed require a license key.  I [upgraded](https://www.ej-technologies.com/support/upgradeProduct) the install4j 6 license key to obtain a new license key for 7.

In order to avoid breaking the build for a short period of time, I didn't replace the 6 license key with the 7 license key.  Rather, I created a separate Travis environment variable (`INSTALL4J_7_LICENSE`) to store the 7 license key.  The existing Travis environment variable (`INSTALL4J_LICENSE`) still contains the 6 license key.  Hence why I'm proposing in this issue to remove `INSTALL4J_LICENSE` as it is no longer used.

> Why disable the debug build feature in travis, can you point to me when it was added?

We enabled it specifically to extract the `INSTALL4J_LICENSE` environment variable from Travis to obtain the install4j 6 license key.  See [here](https://github.com/triplea-game/triplea/pull/2369#issuecomment-330127292) for where I initiated the process to enable debug builds after getting @ron-murhammer's blessing.

I'm proposing to disable debug builds because of [security considerations](https://docs.travis-ci.com/user/running-build-in-debug-mode/#Security-considerations).  In a nutshell, if a dev is not careful when running a debug build, an attacker could login via SSH and dump all of our secure environment variables.  If the dev doesn't notice that those secure environment variables were disclosed, we could have a big problem.  If the dev does notice that they were disclosed, we still have to go through the trouble of revoking all tokens/license keys stored in Travis.

**Comment by DanVanAtta** [comment]
Thanks for the context @ssoloff . I PM'ed you the link to our 'secrets' spreadsheet, that is perhaps actually the best place to put the license key. I would agree with removing the debug build flag.

**Comment by ssoloff** [comment]
@DanVanAtta Done.  install4j 6 and 7 license keys copied to the doc at the link you provided.

**Comment by ssoloff** [comment]
All tasks are now complete.  Closing.
