### ISSUE TITLE
Feature request: Option to enable/disable autosaves

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#2379]
If it is not too much work I would welcome an option (hopefully I did not miss it) to disable/enable autosaves.

My savegame folder regularly gets flooded with autosaves, that I never ever have needed.
Personally I save manually whenever I feel it is needed.

So an option to enable/disable autosaves would be helpful.

**Comment by simon33-2** [comment]
The most recent versions put it into a sub directory and have done for quite a while. Why's it cause you a problem? I don't think I understand.

You haven't found the usefulness of this change? I think it's great (although I would). I never used autosaves before but find them useful now.

**Comment by panther2** [comment]
When we discussed this feature in April I already mentioned my opinion on this, starting from here:
http://www.axisandallies.org/forums/index.php?topic=39766.msg1655321#msg1655321

I find savegames useful when I need them, this is why I save manually in case I feel I need one - having the opprtunity to assign a file-name myself.

Also in the current implementation it's hard to identify to which game a savegame belongs - I have to draw conclusions from the timestamp when testing different maps.

In my almost 9 years of using TripleA I never experienced a crash or a loss of current data. So I have never needed an autosave.

Additionally I am just a fan of "clean" harddrives, having control on what is saved and what is not. So I don't want to collect files that I never need.

Of course I fully respect that these automatic savegames might be considered useful by other players, so that is why I am asking for an option.

Many apps/games offer the option to enable/disable autosaves, so my question is not that extraordinary, IMHO.

But as I said, if it is too much work to implement this feature I will go on deleting all that files manually from time to time.

**Comment by simon33-2** [comment]
It's not just system crashes though. There's also the every day situation of forgetting an NCM. I use autosave in this case. If playing combat move before purchase, I can also use it for changing combats after getting to the purchase box.

If it really bothers you, make the autoSave directory read only. That'll stop 'em! I found it worked similarly when it was doing autosave onto a samba share.

**Comment by panther2** [comment]
There is no dedicated autosave directory. All those files go into my regular saveGame directory. Way too much files there...

**Comment by simon33-2** [comment]
You must have an old build. There is a dedicated autoSave directory now.

**Comment by panther2** [comment]
Simon, I am testing all the new versions day by day. How do you come to think I have an old build?

**Comment by simon33-2** [comment]
That is very strange. I'm looking at PR #1672 where this was done and it looks like only one step was ever made. I'll keep looking at why all the autoSaves might be going to the same directory. I agree that would be annoying, which was the reason I came up with the idea of putting them all in a subdirectory.

**Comment by simon33-2** [comment]
Looks like a problem on Windows only. I have reproduced it.

**Comment by simon33-2** [comment]
PR #2380 created to fix the problem of the autoSaves not going to an autoSave directory on Windows. (Mac and Linux are fine).

**Comment by simon33-2** [comment]
@panther2 Thanks for reporting this. This feature might have gotten a lot of negative feedback if it had gone out without the above fix. Hopefully, it is merged quickly.

**Comment by simon33-2** [comment]
BTW, the autoSave subdirectory gives a defacto option to specify the autoSave directory - by creating a link to wherever you would like it to be.

5 consecutive posts. Sorry.

**Comment by panther2** [comment]
I will take a look once it has been merged. A dedicated subdirectory for those files would be an improvement to the status quo, for sure.

**Comment by simon33-2** [comment]
Build 6676 should have this change.

**Comment by panther2** [comment]
Looks good. No need to think about an option any longer, IMHO. Thank you.
