### ISSUE TITLE
BANNING

### ISSUE THREAD

**Issue by Leijonma** [triplea-game/triplea#2388]
### Any additional information that may help:

Hallo AAA!

When I tried to log in to Lobby I got following message

"You are banned from the Lobby for 364 days... games.strategy.net.couldNotLoginExeption"

I tried to change everything, user name password email adress but nothing works.
Used the same laptop all the time at same internet connection.

I have done nothing offensive or even hardly played at all so I understand nothing.

Maybe I typed the wrong password at the most.

I have visited TrippleA the last couple of months and nothing as such happened earlier.

What is wrong and how to fix it?

hale   hans.leijonmarck@hotmail.com

**Comment by RoiEXLab** [comment]
@Leijonma Could you try logging in again?
We removed the only entry for one year, we got many reports of 1 year bans in the last couple of days, so we might have a deeper issue there...

**Comment by Leijonma** [comment]
Hallo AAA!

Have succeded to get to the Lobby now, twice.

Thank You TripleAAA

hale

Skickat från min iPhone

20 sep. 2017 kl. 20:49 skrev RoiEX <notifications@github.com<mailto:notifications@github.com>>:


@Leijonma<https://github.com/leijonma> Could you try logging in again?
We removed the only entry for one year, we got many reports of 1 year bans in the last couple of days, so we might have a deeper issue there...
