### ISSUE TITLE
OS Installer Files - Static Download Links

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#239]
A static download link for each of the OS specific installers would be really helpful for the website and perhaps could save us from updating partner site when we do releases.

I was thinking of how to do this and came up with an idea. Simply pushing an extra tag with a fixed name "stable" would do the trick. Specifically when we do a release we would run these commands to replace the stable tag with the latest release:
```
git tag -d stable
git push origin :refs/tags/stable
git tag -a 'stable' -m stable
git push origin --tags
```

So then to compare what the download (DL) links would look like, today the windows installer DL link is: 
https://github.com/triplea-game/triplea/releases/download/1.8.0.9/triplea_1_8_0_9_windows_installer.exe

The tag above would be in addition to the existing process, so we would also have the following DL link available: 
https://github.com/triplea-game/triplea/releases/download/stable/triplea_stable_windows_installer.exe

**Comment by DanVanAtta** [comment]
@veqryn , @ron-murhammer , this is an easy one to approve. What this issue is asking is that we run a script to push a special tag when we do releases. The special tag named "stable" will be used to construct a static link of the latest build. I'll create the script to do so and will offer to run it when needed. Please review this idea and give your thoughts.

**Comment by veqryn** [comment]
I am fine either way on this.
The only issue I can think of is that people might not think the file has changed if the name stays the same.

**Comment by DanVanAtta** [comment]
Thanks, I'll close this issue for now.

The static download link has two benefits. It's good for update and forget, namely thinking about the external partners like file share etc that still have 1.8.0.5 or earlier. It's also of potential benefit for the website. Under normal circumstances we will be directing people to the latest github release, which will have a standard version number on it.
