### ISSUE TITLE
Code Coverage - Require PRs to be green and have test coverage?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2407]
It's been noted since we added code coverage that we are getting red 'X' marks on PR builds, and we are effectively ignoring them, eg:

![codecov](https://user-images.githubusercontent.com/12397753/30892784-4e5d68ca-a2ef-11e7-9ee4-786690203ae8.png)

Thinking about this a bit, I think this is a bad state/process to have. We are incurring overhead to check if a build "actually" passed or not, yet meanwhile we are not getting any good value from code coverage since we are ignoring it.

I was tempted initially to suggest we just remove code coverage. Though, I think it might actually be better to go the other route and start requiring for the minimum code coverage to be hit. This can be a lot to ask for this code base since a lot of the code needs quite a bit of work to be testable. I suspect though, we do need to bite the bullet at some point and really start adding unit tests for anything we modify. After all, any modified code is effectively new code, and should be tested as such. Currently it seems we are still hand testing these updates, and that is a pattern we need to break out of so we can reduce our manual test burden.

Thoughts? Is there a general concensus to start requiring code coverage plug in to start going green (currently meaning 20% minimum code coverage on PRs)

**Comment by RoiEXLab** [comment]
I believe we should continue ignoring them for PRs that fix a typo or do some cleanup e.g. removing some unused imports/variables etc.
I agree that we should look at them more strictly, but I'd like to point out that integration tests are not affected the calculated coverage, so we might consider merging integTest and test into a single test task (if that calculates the real coverage)

**Comment by ssoloff** [comment]
The only real problem I have with this feature is the non-deterministic changes in codecov/project.  I think that's the most annoying part of the process and is what causes the double-check.  I looked into this a few weeks ago and came up with a good root cause candidate in the thread pool used by the `UnifiedMessenger` class.  From `VaultTest`:

```
This is because the lifecycle of the UnifiedMessenger (and internal classes such as
NioReader/Writer) are broken.  The UnifiedMessenger will create a new ThreadPool
with each instantiation, and this pool is never shutdown.
```

My initial thought was to move messaging tests to to integTest since they open sockets and thus are really integration tests.  Once in integTest, they would no longer affect codecov/project, but they would be broken nonetheless, and it does feel a bit like punting. :smile:

Other than that, as a reviewer, I think codecov/patch is a helpful indicator for how much effort I have to put into a PR.  I have found it fairly easy to keep patch coverage above the current project coverage for new features.

However, as @RoiEXLab said, it will be pretty difficult to hit that metric on bug fixes and pure refactoring PRs.  We should always strive to add tests to verify bug fixes.  If no tests are included with a PR, the author should justify their reasons.  For example, some reasons I'd be ok with:

* Purely automated refactorings
* Code that is extremely difficult to unit test; integration or manual tests done in lieu of writing unit tests

**Comment by DanVanAtta** [comment]
One nuance I wanted to convey:

> pure refactoring PRs.

If there is no test case, one could argue it was not a refactor and is a re-write. Part of refactoring is that there is validation of the existing code before any modifications (via unit tests), and then after changes those same validations pass. If there are no unit tests, then it was not a refactor and should have been at least tested manually. I then suggest we start enforcing code coverage really so one day we will start writing a lot more unit tests in earnest.

I think it does get a bit tricky when code is in such bad shape that unit tests require very deep surgery. Since we are only going for 20% coverage though, that's a really low bar and I think almost regardless of the update we should be able to hit that. By the same token, if we are mucking around with code, this is a difficult code base despite appearances, we have a problem of introducing bugs, and by that token we may be well off to insist refactorings are done properly with unit tests added to verify the updates.

Another gray area I see is UI code as well, we do not want to be testing Swing code. Though, with the builder lib for swing code, it is quite possible to split UI and logic more easily (I wrote those builders pretty much for that exact reason). If we do not require code coverage, I don't think the motivation or expectation will be there.

So I think we could have a policy where we expect every check to be green, but list a very few exceptions. Even for commentary updates, it could be a good policy to say you just don't simply update code unless you have a reason and also add test coverage. If we do so for long enough we may get the test coverage we finally want. I'm really not sure how we can get on that path in general, there is no good motiviation currently to add test coverage.

**Comment by DanVanAtta** [comment]
> Purely automated refactorings

The code base is brittle, even these kinds of things could break the code. But again, we have to practical, this is perhaps a good exception.

> Code that is extremely difficult to unit test; integration or manual tests done in lieu of writing unit tests

integration tests in lieu of unit tests IMO is a anti-pattern and a death spiral. Beyond integration tests belonging at the boundary of a system, so for the most part they are not appropriate anyways, I would really want our incentives to be to break up code so we can test it.

**Comment by DanVanAtta** [comment]
We agreed as a project that we would as a PR submitter describe how code is tested. If we start requiring the code coverage to be green, we will have automated that to some extent. If not, we would anyways expect details on the manual testing done. New here as proposed, in addition to describing manual testing that is done, there would be some rationale of why unit tests were not added.

I also think that until we require green code coverage reports, it will never be a project requirement to add unit tests and we'll get into the "excuses" game, endless back and forth excuses about why it was so difficult for 'poor' us to add unit tests when instead often we can sink that effort into unit tests and skip the back and forth in the first place. In short, I'm a bit tired of arguing why unit tests should be written, I would want that to be a stronger expectation.

**Comment by DanVanAtta** [comment]
I think there are two questions.
1. Do we want to require code coverage check to be green?
2. What is the list of exceptional cases where we can ignore it? 

For now I can think of two exceptions we would want:
  - renaming that is almost certainly not going to impact RMI (eg: local variables, parameter names)
  - "pure" UI code

For any other cases, perhaps we could allow exceptions so long as screenshots and details are provided of the manual testing that was done.

**Comment by ssoloff** [comment]
> renaming that is almost certainly not going to impact RMI

Heh, renaming can break RMI if it changes the sort order of the methods.  I'm actually going to submit a PR later today where I will be explicitly saying, "I renamed an RMI-callable method, but it doesn't change the sort order." :smile:

**Comment by DanVanAtta** [comment]
Indeed renaming can impact RMI! I edited the comment to give some examples where it is clearly okay like local variables and parameter.

**Comment by DanVanAtta** [comment]
I take that back actually, you're right, so long as the order is not changed since we invoke by method number. Serialization is where naming is more brittle and was a bit more of what I was thinking of.

**Comment by DanVanAtta** [comment]
I think I'm pretty convinced the simplicity of needing all checks to be green is just really straightforward, and we simply allow few and very specific exceptions to that policy. 

@ron-murhammer your thoughts? 

This would be a bit controversial as it starts to force everyone to write more tests and most importantly to design code so it can be tested. But, IMO that is a both a good and necessary goal at the moment and  I don't really see any other practical way to get there.

**Comment by ron-murhammer** [comment]
@DanVanAtta I'd say for most PRs we should strive for that and especially new features or enhancements. I think the exceptions are probably:
- Bug fixes
- Comment fixes/additions/removal
- Formatting
- Pure UI (IMO this doesn't exist in that many places given the way the code is today)
- Minor refactoring (very low risk and/or automated)
