### ISSUE TITLE
Flaky build - Source forge resource

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2426]
Build failure on validate yaml step:

``` 
http://tripleamaps.sourceforge.net/images/TripleA_total_world_war_mini.png: error requesting map resource (Connection reset)
```

1. We should not have a flaky build! Let's aggressively fix these issues so that the build is deterministic, it will be hell if we let these kinds of problems accumulate.
2. Ideally, we would have completely evacuated all tripleA assets from source forge. For this build failure, simply rehosting the asset should help avoid this error.

**Comment by DanVanAtta** [comment]
This is actually a bit of a pressing issue, we're seeing consistent failures right now due to SF asset issues, related: https://github.com/triplea-game/triplea/pull/2427

**Comment by DanVanAtta** [comment]
:+1:  I vaguely recall doing some of that, it was quite the effort though and there is a lot to be done. I think you are right on the corrective action @RoiEXLab .

**Comment by ssoloff** [comment]
After the merge of #2530, there should be no more SourceForge links that will be checked as part of the `validateYamls` task.  (There are two SF links in the descriptions of TWW and The Rising Sun, respectively, but we do not currently check links embedded in the map description.)

Any objections to re-enabling the `validateYamls` task?

**Comment by RoiEXLab** [comment]
Closing per #2550 and #2530
