### ISSUE TITLE
Removing non-Pro AIs

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#245]
The plan is to remove all AIs except ProAI, is that the plan?

To help clean up the code I'll be happy to see about removing it. @ron-murhammer  or @veqryn perhaps you may want the pleasure, so please let me know if either of you guys want to tackle it. Otherwise please confirm the plan is to keep just ProAI for now. (I understand eventually we may different play options for the ProAI, but for now it's the only AI worth playing).

**Comment by ron-murhammer** [comment]
@DanVanAtta That's my plan though I would like to enhance the Hard AI to have a second option of 'Fast AI' that uses a formula instead of the battle calc for people that want quick/easier games before we start removing any more AIs. Also want to get veqryn's buy in as well but that's my high level plan.

**Comment by veqryn** [comment]
I'd certainly like to remove StrongAI.
However, WeakAI and the NoMoveAI (or w/e it is called) are both useful.
Weak AI could possibly get removed, if ProAI is able to handle appropriately all the places that we currently use WeakAI (hint: even a game without AI's has at least several Weak AI's created for various things, just do a reference search).

**Comment by ron-murhammer** [comment]
Just made the PR to officially remove the StrongAI! Whoooo! I'm planning to leave WeakAI at least for the next release then potentially remove it as FastAI improves in speed. There is still a decent chunk of StrongAI code used for tech and bid but I'm looking to rewrite these soon to finally get rid of it all! Here is the PR: #394

**Comment by DanVanAtta** [comment]
:+1:
