### ISSUE TITLE
GameDataUtils ensure stream flushing

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2455]
Some follow up needed after: https://github.com/triplea-game/triplea/pull/2450

convert the try with resources blocks to follow this rough pattern:

```

final ByteArrayOutputStream sink = // ...
try (final SomeFilterOutputStream out = new SomeFilterOutputStream(sink)) {
  // write to out
} // <-- ensure out is flushed here
try (final ByteArrayInputStream source = new ByteArrayInputStream(sink.toByteArray());
    final SomeFilterInputStream in = new SomeFilterInputStream(source)) {
  // read from in
}
```

Avoids potential problem of:

>  Because the outer try-with-resources block has not yet ended, out may not have been flushed, in which case, all data may not have made it to sink. Thus, source may not contain the complete stream for input.

**Comment by ssoloff** [comment]
Closed via #2461.
