### ISSUE TITLE
How do I start a headless server?

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#2467]
Looking to start headless servers. Can't see how to do that in the wiki or another way.

**Comment by prastle** [comment]
First copy the old code they removed from the standard install.  Also install the headless server.exe and .bat files

then rewrite it for the current 

Thanks @ Roiex for the help

@echo off
SET PORT=3363
SET BOT_NUMBER=25

SET LOBBY_HOST=45.79.144.53
SET LOBBY_PORT=3304

java -server -Xmx320m -Djava.awt.headless=true -classpath bin/triplea.jar games.strategy.engine.framework.headlessGameServer.HeadlessGameServer triplea.game.host.console=false triplea.game= triplea.server=true triplea.port=%PORT% triplea.lobby.host=%LOBBY_HOST% triplea.lobby.port=%LOBBY_PORT% triplea.name=Bot%BOT_NUMBER%_Pras1 triplea.lobby.game.hostedBy=Bot%BOT_NUMBER%_Pras1 triplea.lobby.game.supportEmail=prastle27@hotmail.com triplea.lobby.game.comments="automated_host" triplea.lobby.game.reconnection=172800

pause

**Comment by RoiEXLab** [comment]
If you are using Linux you can find all sorts of scripts in the triplea-game/lobby Repository

**Comment by simon33-2** [comment]
Thanks, seems to work. Seems I've left a few dead bots in the lobby though. Not sure what to do with that or how to prevent it?

**Comment by RoiEXLab** [comment]
@simon33-2 I haven't noticed anything, after logging out and back in everything should be displayed correctly anyways...

**Comment by prastle** [comment]
Yes they were gone this am @RoiEXLab .  Thus I am guessing he closed them.
