### ISSUE TITLE
Odds Calculator Copy/Paste Button

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#247]
Being able to "copy/paste" between two battle calculator windows would be really helpful. A mockup is below:

From a code perspective, scoping it out a bit, the OddsCalculatorPanel is regrettably not in very good shape. Once OddsCalculatorPanel is cleaned up first then this should be a pretty easy feature to add. 

Otherwise I think the behavior implied by the mockup will be pretty intuitive:
- Click paste before clicking copy and nothing happens
- Click copy once to "save" the units in a "clipboard"
- Click copy again to overwrite the clipboard (perhaps we'll safeguard against zero'ing it if an empty unit set is 'copied')
- Basic copy and paste will work as pretty much expected
  - Paste will overwrite any existing unit counts
  - in case where a paste is done so two allied sides would be fighting, behavior will be same as changing the defender or attacker to also be allied. Namely the other side flips and the units are zero'd out. I think we may want to reconsider this specific behavior overall, it would be great if the odds calc never zero'd out any data entered in by the user unless it must for correctness or unless the user clicked the "clear" button. (Correctness case would be when a unit exists for one country but not another)

Nice icing on the cake, after clicking the copy button, we could change the text of the button to be "copied N units", and then set a timer to revert the text back after a second. Perhaps the same thing could be done for the paste button.

![copy_paste_mockup](https://cloud.githubusercontent.com/assets/12397753/10685791/f9502a28-7912-11e5-98f4-44d1d82b9976.png)

**Comment by ron-murhammer** [comment]
@DanVanAtta Seems like a useful feature to add. Might want to get some feedback on the forum to see what users think. Other than that I'd say feel free to take a shot at implementing it.

**Comment by DanVanAtta** [comment]
https://github.com/triplea-game/triplea/wiki/Feature-Back-Log
