### ISSUE TITLE
Need a time wait indicator when joining lobby

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2473]
Anonymous login to lobby seemed to render the lobby window faster for me, regardless on a non-anonymous login, with a wait of what was about 10 solid seconds - the game seemed to have frozen. 

Task:
- add an indicator that the game is connecting to lobby

**Comment by ssoloff** [comment]
A significant portion of this time is due to the lobby server generating a new 4096-bit RSA key pair per connection.  @RoiEXLab and I talked about this in Gitter recently, and I have a PR ready to go after we get this release out which should shave seconds off the login times.

**Comment by DanVanAtta** [comment]
An alternative - maybe something as simple as having a label be updated to "connecting to lobby" be printed on the login dialog, disabling the dialog fields, and making the dialog disappear after the lobby renders instead of before.

The goal is to provide feedback to the user on what the computer is doing. I assume the lobby login may always take a few seconds in perhaps the 90th percentile cases. That would imply that otherwise 10% of the time the app will appear to have crashed.

**Comment by prastle** [comment]
Ya I can agree login times seem to have increased.

**Comment by ssoloff** [comment]
Fixed in 1.9.0.0.7326 via #2548.  @DanVanAtta, please re-open if the solution isn't satisfactory.
