### ISSUE TITLE
unit tests are running slow

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2477]
Unit tests lose a lot of effectiveness when they are slow to run. Target should be around 10 to 20 seconds. Given a thousand to 10k unit tests, we need each one to run in 100ms or less.

We've a few particularly slow ones to look at:
![slow](https://user-images.githubusercontent.com/12397753/31326267-6f1f6b1e-ac7a-11e7-9624-575ae2f08d79.png)

Not sure of the options just yet, @ignore is always one but heavy handed and not very desirable. Opening this issue for tracking/visibility in case anyone would like to tackle this.

**Comment by ssoloff** [comment]
@DanVanAtta This will be covered by the PR I mentioned in #2473.  The slow unit tests were actually why I decided to look into how we can improve the speed of lobby authentication. :smile:

**Comment by DanVanAtta** [comment]
Down to 16s now. 
Thanks for addressing this @ssoloff , #2473 did the trick.
