### ISSUE TITLE
Map blends are not rendered correctly when zoom < 100%

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/triplea#2488]
#### Environment

TripleA 1.9.0.0.7079

#### Description

I'm not exactly sure what the **View > Show Map Blends** command is for, but I noticed that when it is enabled, and I lower the zoom below 100%, the map is not rendered correctly.  If you look at the screenshots below, it looks like the "blends" are not scaled before they are rendered.  It may be as simple as the zoom not being taken into account when these artifacts are rendered.

##### Show Map Blends: Enabled; Zoom: 100%

![map-blends-zoom-100](https://user-images.githubusercontent.com/4826349/31527150-6305c342-af99-11e7-9b5b-9b51700c761f.png)

##### Show Map Blends: Enabled; Zoom: 75%

![map-blends-zoom-75](https://user-images.githubusercontent.com/4826349/31527157-6977af2e-af99-11e7-96e4-e29cdf31dd18.png)

##### Show Map Blends: Enabled; Zoom: 50%

![map-blends-zoom-50](https://user-images.githubusercontent.com/4826349/31527162-703a0ee2-af99-11e7-92e3-dbea34038e6c.png)

#### Notes

I initially suspected the removal of the `yield()` call in #2485 as the root cause (since it was interleaved after a `setScale()` call), but I verified that the issue occurred before #2485 was merged.

I found #338 in the issue history.  It may not be related but could be a useful starting point for understanding how this area of the code works.

**Comment by ron-murhammer** [comment]
@ssoloff Interesting. I wonder if this is a known limitation.

@Cernelius @panther2 Are either of you aware of this?

**Comment by panther2** [comment]
No, I cannot add anything here, sorry, as I have never ever used this feature. 
What actually are those "blends"? On a first view it looks like the map colours are treated with some more transparency. But when scaling we see that there must be something more behind it...

All I can say is that I can reproduce this issue on other maps.

**Comment by ssoloff** [comment]
Thanks for digging up that reference, @panther2.

**Comment by ssoloff** [comment]
Fixed in 1.9.0.0.7291 via #2542.
