### ISSUE TITLE
Buy a Domain Name For Website?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#249]
@veqryn, @ron-murhammer A question came up in the website repo whether it would make sense to get a domain name for the website. Currently the website URL is: http://triplea-game.github.io/, and we could be a bit better off maybe with something like "www.triplea-game.org" (triplea.org is taken)

Do you guys think it is worth having a full blown domain name for the website? Do we have the community funds to buy it and cover any yearly costs for at least a few years, or would a funding drive be needed?

**Comment by williamdekryger** [comment]
@DanVanAtta You have changed the CNAME in the website repo without properly configuring the domain, downing the site. If the domain has not been purchased yet, please reverse the commit.

**Comment by DanVanAtta** [comment]
Apparently when the configuration *did* kick it, was not working. CNAME file removed.

**Comment by DanVanAtta** [comment]
This is done, we own triplea-game.org for 10 years. I'll request contact info from other admins when we get it set up and working. This issue is tracking that: http://github.com/triplea-game/triplea-game.github.io/issues/29
