### ISSUE TITLE
Feature: Create option to throw quietly logged errors

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#25]
Map parse errors on load should be quietly logged (ie: logged to console in background but not shown to  the user). For this issue, make that change, and also add an option to the game (default to off) where all such messages can instead be logged to standard error instead of standard out (which brings the console window to the foreground with the error message). This will be a useful option to be set to "on" for map makers and developers.

**Comment by gaborbernat** [comment]
:+1:

**Comment by djensen47** [comment]
:+1:

**Comment by DanVanAtta** [comment]
I can keep track of this issue on my own. I'm the only one that is going to implement it. I like the vote of support for it. Closing in favor of keeping our issue lists short
