### ISSUE TITLE
Forum Consolidation and SVN Migration

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2503]
Let's take inventory of the migration from old forums and sourceforge to the latest stack. I'd like for us to get a better idea of everything we have and be sure we have it all deprecated nicely so you would as automatically as possible be redirected to the latest.

New:
- http://www.triplea-game.org/
- https://forums.triplea-game.org/
- https://github.com/triplea-game/triplea
- https://github.com/triplea-maps/

Old:
- https://www.tripleawarclub.org/ (forum: https://www.tripleawarclub.org/modules/newbb/)
- https://sourceforge.net/projects/triplea-maps/
- https://sourceforge.net/projects/triplea/
- http://tripleadev.1671093.n2.nabble.com/

----------------------

There is a question mark on open tasks, I'm not fully sure what remaining tasks we would like to finish before we could really call this project migrated and consolidated to a single website and forum. We know also that we would like to unify the logins between lobby and forum, for now let's stay focused on finishing the deprecation of old websites, forum and SVN assets.

I could use confirmation that the below tasks are actually what need to be done. I'm sure a number are missing and could use help completing the list (please do mention what else we would want to do)
 
Open tasks (?):
- [x] migrate everything out of SVN triplea-maps. IIRC correctly the triplea-maps yaml has references to stuff in there
- [ ] work to turn off tripleawarclub.org php server
  - [ ] convert tripleawarclub.org to a static html, host that somewhere. Add link to this location to triplea-game.org
  - [ ] have tripleawarclub.org redirect to triplea-game.org
  - [ ] migrate marti dice server to a non-PHP stack. Create a build and deploy script for it. Once deployed, we would have no shared PHP server dependencies, we could then turn off the PHP stack that is hosting tripleawarclub
- [ ] nabble forum, verify we've done all that we should there as well. May be interesting to do a static html version and do an automatic redict to new forum
- [ ] verify 3rd party hosting sites of our game installer were updated to github

**Comment by RoiEXLab** [comment]
@DanVanAtta I'd like to point out I have a prototype of a dice server already here: https://github.com/triplea-game/dice-server-js I also created an issue to track things that need to be done before being able to fully use it https://github.com/triplea-game/dice-server-js/issues/1

About the cloning part: While there are several tools out there which offer (free and paid) cloning a website automatically, we will have compromise at some point.
If we want to keep existing links to the Warclub forum, we will continue to need a pre-processor to map the GET links to the individual html documents.
If we want to get rid of a preprocessor and have 100% pure html we will inevitably break existing links.
Option 3 would be to try saving all pages to Web.archive.org by hand, but probably too much work.

**Comment by prastle** [comment]
I wonder if we really need to save most of Warclub?  A lot of it is available here https://web.archive.org/web/*/http://www.tripleawarclub.org/modules/newbb/viewtopic.php?topic_id=2305  The only thing that is really missing is the bunker.  do we still need that since we have a new database anyways?  Just a thought.

**Comment by DanVanAtta** [comment]
I like the web archive idea @prastle 
Migrating dice server is a hard requirement, so we need at least that to happen before we can turn off the PHP platform.

**Comment by prastle** [comment]
I think @RoiEXLab  had a new one on the go.  But I am just throwing ideas out there.  Great job @ all

**Comment by RoiEXLab** [comment]
@prastle Yes, as mentioned earlier I started working on a dice server replacement.
Using web.archive.org would be the easiest solution.
Could you make sure the "most important" things are available there?
Also for saving the bunker: Just recreate the topics in the new forum

**Comment by prastle** [comment]
OK I will try and do some digging this week.

**Comment by prastle** [comment]
After a brief glance I think I have pretty much moved everything already that I felt was important when we built the new forum.  I think I imported most of the important stuff.  The rest is just comments, arguments over the years etc. and is way to much to import.  The bunker is a long list of issues!  Many have been solved as well as many no longer mattering.  Since we have the new database anyways. I think it is easiest to start with a clean slate.   jmho Pras

**Comment by prastle** [comment]
To continue
Old Statistics/Laders etc are already imported with web archive.  Since its a new database all we are really losing is info on trouble makers.  As well as info from the original builders.  In the bunker
  So lets start fresh! just my thoughts Pras

**Comment by RoiEXLab** [comment]
With that being said I'm probably going to continue the work on the new dice server software. 
It would be nice if @ssoloff could help me a bit with stuff like ESLint and automated tests, as it seems he has a couple repositories already using those tools.

**Comment by ssoloff** [comment]
Sure, @RoiEXLab.  It might be best to create a task list issue in the dice server repo of what exactly you want done.  I may not get to it for a while, though, because I'm currently doing a significant re-write of portions of the serialization proxy feature.  The circular references finally hit critical mass, and I couldn't overcome the problems without changing the design. 😞

**Comment by RoiEXLab** [comment]
Thanks @ssoloff I think I'll be able to get ESLint done on my own, seems to be fairly easy to setup.
The biggest question for me is what testing framework to use and how to set it up.

**Comment by ssoloff** [comment]
All I can offer is my experience. :smile:  I've pretty much used Jasmine exclusively for ES over the past several years.  It's very well supported and can do pretty much anything you need.

I have been playing around with Jest lately and see many things I like.  Jest is based on Jasmine (although now they've officially forked from Jasmine), so it is very easy to use for someone coming from that style of framework.  My only complaint about Jest is that Facebook tends to force everyone to work the way they do instead of offering customization points, which makes some things a lot harder than they need to be.

**Comment by RoiEXLab** [comment]
@DanVanAtta @ssoloff 
I'd suggest shutting down tripleawarclub.org at the end of the year.
By shutting down I primarily mean adding a CNAME record which redirects to forums.triplea-game.org so users will be redirected automatically and the site will no longer be reachable.
The actual shutting down the server procedure is going to depend on my coding speed: It'll be easier to shut down MARTI and the forum at once, so I need to finishe the new dice server before actually stopping the server...

**Comment by prastle** [comment]
good stuff

**Comment by ssoloff** [comment]
Regarding the dice servers...  Another option is to run both in parallel until we're sure the new dice server is ready for production.  We can just drop another properties file under `/dice_servers` pointing to the new server so users can select either one.  Then, when we're comfortable with the new server, we remove the MARTI properties file and decommission the app.

**Comment by prastle** [comment]
@ssoloff  and @RoiEXLab  We could really use some more bots in the lobby with the holidays.  I also believe Roi wanted the new dice server to be standalone.  Perhaps firing another small server to accomplish your test would kill two birds with one stone.  The funds are available.  And once it is up and working we could remove the bots if that is what is wanted.  Just a thought.

**Comment by DanVanAtta** [comment]
@prastle let's overshoot capacity on bots once and for all, not bother taking them down during low times and just keep enough running. My hope/goal there is that we don't need the admin overhead of setting them up again. With that said, it is easy to set them up, I just don't want us to worry about this for the next few months while we work on other items. One day we will not need bots at all...

---------------------

The main topic at hand is what we would need to do to kill the PHP server running on tripleawarclub. It sounds like the dice server is the biggest item considering the content is archived.

**Comment by prastle** [comment]
@DanVanAtta     Well we have never removed any bots.  I just idle them when they are not needed.  The Lobby just keeps growing and growing.  From advertising, the new engine and the new forum etc etc.
We had 85 peeps at one point today possibly more.  The ideal solution is most being able to host.  Sadly 75% cannot.  I really cant give you a number on the overshoot capacity.  We have slowly been growing.  I will say that for the last few days every bot full! Plus many hosts.  Also yes the only thing stopping the php server from being shut down from my understanding is the new dice server.
