### ISSUE TITLE
tripleabuilderbot needs write access

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#251]
To proceed with the automated release pipeline, the 'tripleabuilderbot' account needs write access to the triplea-game repository.

Only an org owner or admin of the triplea repo  can invite the tripleabuilderbot and grant it write access.   @ron-murhammer  or @veqryn, could you take care of that?

**Comment by veqryn** [comment]
The invitation was already sent when I posted about it two or so weeks ago. Please click/confirm the invitation and access will be given.

**Comment by DanVanAtta** [comment]
Found it, thank you.
