### ISSUE TITLE
Download Maps Window Layout Messed Up

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#2511]
It appears the layout in the download maps window got messed up with the list of maps no longer on the left hand side but floating at the bottom???

Glancing through recent PRs, my guess is that this is the culprit but not sure: #2478

![image](https://user-images.githubusercontent.com/1427689/31800253-2fba65ee-b505-11e7-9e1d-9d0234fbaa3f.png)

**Comment by ssoloff** [comment]
> Glancing through recent PRs, my guess is that this is the culprit but not sure: #2478

Yup, that's the guy.  I can't repro it with

```
cc3d77a (tag: 1.9.0.0.7131) Remove explicit call to close() on auto-closeable resource
```

but it occurs with

```
9acfd00 (tag: 1.9.0.0.7137) Add additional SwingBuilder components
```

I'll dig through and see if I can find the exact root cause.

**Comment by ron-murhammer** [comment]
Retested this and looks good. Thanks @ssoloff for the quick fix. Closing this.

**Comment by DanVanAtta** [comment]
Not the best regression to see, given this I marked 7062 as a pre-release again. We are back to 3635 as latest  :disappointed: 

Release notes were updated in (#258) and a lobby warning message would be made live with #2514. Test group will be jumping forward to 7175, with luck that will be marked as latest shortly (under 48hours)

**Comment by DanVanAtta** [comment]
I'm quite relieved that this was not a problem introduced before v7062. 
Let's clarify "P0" means a live problem :)
