### ISSUE TITLE
Add check config setting for lobby server so it launches on system start up

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#252]
From #234, the lobby server was restarted and when the server came back up the lobby was down. Adding a `chkconfig` setting or similar would launch the lobby on server reboot.

Assigning to @ron-murhammer  initially, please unassign if you aren't the right person to tackle this or if you won't be able to get to this task.

**Comment by ron-murhammer** [comment]
@DanVanAtta Agree this would be nice to have. I probably won't get to this anytime soon though so I'll unassign myself.

**Comment by veqryn** [comment]
fyi, it needs to be run from within a screen session, as this is how the lobby admins are able to interact with the console.

**Comment by DanVanAtta** [comment]
Sounds like then the screen session needs to be launched on start, and also then the lobby launched. Certainly a more complicated task than initially proposed. I don't the cost benefit trade off of this is favorable anymore, especially if we can get monitoring in place. In addition since notifications are now going to multiple people, the chance of this lobby problem is less likely. Closing.
