### ISSUE TITLE
Unable to View Error Log When Game Doesn't Load

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#2538]
https://forums.triplea-game.org/topic/350/unable-to-view-error-log

**Comment by DanVanAtta** [comment]
The more salient problem here to me is that we are quietly swallowing the error rather than displaying it. While working on map error handling in #2509 I noticed that.

**Comment by ssoloff** [comment]
@ron-murhammer Can this issue be closed now that we have the **Show Console Always** setting?
