### ISSUE TITLE
Bug Report for Owned+Contested Island Territories and Air Units

### ISSUE THREAD

**Issue by General-Dru-Zod** [triplea-game/triplea#2549]
[zipped.game.saves_10.27.2017.zip](https://github.com/triplea-game/triplea/files/1423800/zipped.game.saves_10.27.2017.zip)

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
see below
### Do you have the exact error text? Please copy/paste if so
see below
### Instead of this error, what should have happened?
see below
### Any additional information that may help:

I am testing various behaviors for contested territories and I am seeing inconsistencies in engine behaviors. I can reproduce the behaviors with .3635 release and with .7062 and .7316 pre releases. I am using Big World 2 : Balance of Power in the examples, since you dont have the files for the mod I am working on. However, my mod originates from Big World 2 : Balance of Power anyways, so were good.

The starting scenarios for the 2 examples were edited to re-create the conditions after Americas attacks of the previous turn which ended in stalemates of all land battles after 5 rounds. Each example has 2 contested territories each. Each contested territory has 1 American infantry and 3 friendly air units at the end of the American combat.

The examples are somewhat confusing as is. So I'll try to be as clear and concise as I can in order to explain. And later, perhaps we can consider testing the behaviors of other permutations. 

I am including 2 saves for each example. An Italain example and a Japanese example. 

*Save_Italians.1 -  Is before any Italian combat moves. Incase you want to redo the moves and see for your self. 

*Save_Italians.2 - Is after Italian non combat moves. Points of interest are Sardinia and Sicily. Air units that originated in Sardinia can not land in Sardinia or Sicily. Air units that originated in Sicily can not land in Sicily and can land in Sardinia. Unused air units in Italy (the control), can land in Sardinia and Sicily. Thus in conclusion, the tentatively expected behavior should be that the air units that originated in Sardinia and Sicily should also be able to land in both Sardina and Sicily.   

*Save_Japanese.3 - Is before any Japanese combat moves. Incase you want to redo the moves and see for your self. 

*Save_Japanese.4 - Is after Japanese non combat moves. Points of interest are North Philippines and South Philippines. Air units that originated in North Philippines can not land in North Philippines and can land in South Philippines. Air units that originated in South Philippines can not land in South Phillipines and can land North Philippines. Unused air units in Borneo (the control) can land in South Philippines and North Philippines. Also unused jap fighter in sz72 cant land in either North or South Philippines while all other unused can land there. Thus in conclusion, the tentatively expected behavior is that the air units that originated in North Philippines and South Philippines and sz72 should also be able to land in both North Philippines and South Philippines.

Conclusion:

1) Within each example, there are inconsistencies in available landing areas for the friendly air units. Specificly with the owned but contested island territorries.

2) Although both examples are essentialy identical, if we compare the results of each example, we have more inconsistencies between the 2 results. Again with available landing areas of the friendly units. Specificly with the owned but contested island territories.

3) Inconsistent results if I re-run same tests as well as with permutations of these tests.

Seems like some of the air units either forget their origin or the contested terrirtories are not stable, or both. Hard to say since I'm not 100% certain of intended behavior.

I added the following game properties to the Big World 2 : Balance of Power xml to simulate my mod.

property name="Contested Territories Produce No Income" value="true" editable="true"

property name="Abandoned Territories May Be Taken Over Immediately" value="false" editable="true"

property name="Land Battle Rounds" value="5" editable="true"

property name="Sea Battle Rounds" value="3" editable="true"

property name="Air Battle Rounds" value="1" editable="true"

**Comment by ron-murhammer** [comment]
@General-Dru-Zod Interesting. Not sure contested functionality is really that well defined as we don't have many maps that utilize it. Definitely sounds like a bug though given the inconsistency. Guessing it isn't an easy one to figure out and fix though.

**Comment by General-Dru-Zod** [comment]
@ron-murhammer  Yes, contested territories are not used very much. I was hoping to test it out though in my Big World 3 mod.  It would be a very different dynamic with "Land Battle Rounds=5", "Sea Battle Rounds=3", and Contested Territories Produce No Income" value="true.  However  it remains to be seen if it would be a constructive and fun dynamic in a live game. 

I'm gonna shelf the idea for now, because of the bug. But I will revisit it for sure, if it gets resolved.
