### ISSUE TITLE
Dice Server Returning Errors

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#2564]
Test
Contacting  dice.tripleawarclub.org
An error has occured!
Possible reasons the error could have happened:
  1: An invalid e-mail address
  2: Firewall could be blocking TripleA from connecting to the Dice Server
  3: The e-mail address does not exist
  4: An unknown error, please see the error console and consult the forums for help
     Visit https://forums.triplea-game.org/  for extra help
Text from dice server:
<!DOCTYPE html>
<html lang="en">
<head>
        <title>sanjuro.ca</title>
        <style type="text/css">
                html {
                        background:#000 url(http://www.sanjuro.ca/sanjuro.jpg) no-repeat center center fixed;
                        /*-webkit-background-size: cover;
                        -moz-background-size: cover;
                        -o-background-size: cover;
                        background-size: cover;*/
background-size: 100%;
                }
        </style>
</head>
<body>
</body>
</html>

java.io.IOException: Cound not find start index, text returned is:<!DOCTYPE html>
<html lang="en">
<head>
        <title>sanjuro.ca</title>
        <style type="text/css">
                html {
                        background:#000 url(http://www.sanjuro.ca/sanjuro.jpg) no-repeat center center fixed;
                        /*-webkit-background-size: cover;
                        -moz-background-size: cover;
                        -o-background-size: cover;
                        background-size: cover;*/
background-size: 100%;
                }
        </style>
</head>
<body>
</body>
</html>

	at games.strategy.engine.random.PropertiesDiceRoller.getDice(PropertiesDiceRoller.java:192)
	at games.strategy.engine.random.PBEMDiceRoller$HttpDiceRollerDialog.rollInSeperateThread(PBEMDiceRoller.java:238)
	at java.lang.Thread.run(Unknown Source)

**Comment by ron-murhammer** [comment]
@RoiEXLab Have you been working on the live dice server at all?

**Comment by ssoloff** [comment]
Weird...  MARTI seems to be responding on the HTTPS endpoint:

```
$ curl -X POST https://dice.tripleawarclub.org/MARTI.php

<!DOCTYPE html>
<html>
	<head>
		<title>	M.A.R.T.I. Server --> "more accurate rolls than irony"- server</title>
	</head>
	<body>
<br />
<b>Notice</b>:  Undefined index: send in <b>/usr/share/nginx/html/tripleawarclub.org/public_html/dice/MARTI.php</b> on line <b>17</b><br />
<br />
<b>Notice</b>:  Undefined index: numsides in <b>/usr/share/nginx/html/tripleawarclub.org/public_html/dice/MARTI.php</b> on line <b>18</b><br />
<br />
<b>Notice</b>:  Undefined index: numdice in <b>/usr/share/nginx/html/tripleawarclub.org/public_html/dice/MARTI.php</b> on line <b>19</b><br />
<br />
<b>Notice</b>:  Undefined index: subject in <b>/usr/share/nginx/html/tripleawarclub.org/public_html/dice/MARTI.php</b> on line <b>20</b><br />
<br />
<b>Notice</b>:  Undefined index: roller in <b>/usr/share/nginx/html/tripleawarclub.org/public_html/dice/MARTI.php</b> on line <b>21</b><br />
<br />
<b>Notice</b>:  Undefined index: gm in <b>/usr/share/nginx/html/tripleawarclub.org/public_html/dice/MARTI.php</b> on line <b>22</b><br />
fatal error: wrong input!
```

but not on the HTTP endpoint:

```
$ curl -X POST http://dice.tripleawarclub.org/MARTI.php
<!DOCTYPE html>
<html lang="en">
<head>
        <title>sanjuro.ca</title>
        <style type="text/css">
                html {
                        background:#000 url(http://www.sanjuro.ca/sanjuro.jpg) no-repeat center center fixed;
                        /*-webkit-background-size: cover;
                        -moz-background-size: cover;
                        -o-background-size: cover;
                        background-size: cover;*/
background-size: 100%;
                }
        </style>
</head>
<body>
</body>
</html>
```

**Comment by ssoloff** [comment]
Just curious, does `tripleawarclub.org` have any relation to `axisandallies.org`?  It just seemed like too much of a coincidence not to ask since Dave said he was switching from HTTP to HTTPS.

**Comment by ron-murhammer** [comment]
@ssoloff They shouldn't have any relation.

**Comment by ssoloff** [comment]
With a small hack, I was able to connect to MARTI:

```diff
diff --git a/dice_servers/tripleawarclub.properties b/dice_servers/tripleawarclub.properties
index 6820579d5..8b6916ac8 100644
--- a/dice_servers/tripleawarclub.properties
+++ b/dice_servers/tripleawarclub.properties
@@ -4,6 +4,7 @@ order=10
 name=dice.tripleawarclub.org
 #dice server host
 host=dice.tripleawarclub.org
+port=443
 #path in dice server post to post too
 path=/MARTI.php
 roll.single.start=your dice are: 
diff --git a/src/main/java/games/strategy/engine/random/PropertiesDiceRoller.java b/src/main/java/games/strategy/engine/random/PropertiesDiceRoller.java
index 5b17b32e9..471128865 100644
--- a/src/main/java/games/strategy/engine/random/PropertiesDiceRoller.java
+++ b/src/main/java/games/strategy/engine/random/PropertiesDiceRoller.java
@@ -145,7 +145,7 @@ public class PropertiesDiceRoller implements IRemoteDiceServer {
       httpPost.addHeader("X-Triplea-Game-UUID", gameUuid);
       final String host = m_props.getProperty("host");
       final int port = Integer.parseInt(m_props.getProperty("port", "80"));
-      final HttpHost hostConfig = new HttpHost(host, port);
+      final HttpHost hostConfig = new HttpHost(host, port, "https");
       HttpProxy.addProxy(httpPost);
       try (CloseableHttpResponse response = httpClient.execute(hostConfig, httpPost)) {
         return EntityUtils.toString(response.getEntity());
```

I think that confirms that MARTI is running fine, it's just no longer listening on the HTTP endpoint.

**Comment by ghostronin** [comment]
I have the same error I think:

Test
Contacting  dice.tripleawarclub.org
An error has occured!
Possible reasons the error could have happened:
  1: An invalid e-mail address
  2: Firewall could be blocking TripleA from connecting to the Dice Server
  3: The e-mail address does not exist
  4: An unknown error, please see the error console and consult the forums for help
     Visit https://forums.triplea-game.org/  for extra help
Text from dice server:
<!DOCTYPE html>
<html lang="en">
<head>
        <title>sanjuro.ca</title>
        <style type="text/css">
                html {
                        background:#000 url(http://www.sanjuro.ca/sanjuro.jpg) no-repeat center center fixed;
                        /*-webkit-background-size: cover;
                        -moz-background-size: cover;
                        -o-background-size: cover;
                        background-size: cover;*/
background-size: 100%;
                }
        </style>
</head>
<body>
</body>
</html>

java.io.IOException: Cound not find start index, text returned is:<!DOCTYPE html>
<html lang="en">
<head>
        <title>sanjuro.ca</title>
        <style type="text/css">
                html {
                        background:#000 url(http://www.sanjuro.ca/sanjuro.jpg) no-repeat center center fixed;
                        /*-webkit-background-size: cover;
                        -moz-background-size: cover;
                        -o-background-size: cover;
                        background-size: cover;*/
background-size: 100%;
                }
        </style>
</head>
<body>
</body>
</html>

	at games.strategy.engine.random.PropertiesDiceRoller.getDice(PropertiesDiceRoller.java:195)
	at games.strategy.engine.random.PBEMDiceRoller$HttpDiceRollerDialog.rollInSeperateThread(PBEMDiceRoller.java:266)
	at games.strategy.engine.random.PBEMDiceRoller$HttpDiceRollerDialog.access$000(PBEMDiceRoller.java:103)
	at games.strategy.engine.random.PBEMDiceRoller$HttpDiceRollerDialog$1.run(PBEMDiceRoller.java:218)

**Comment by ron-murhammer** [comment]
@ssoloff Weird. I just don't understand why it would stop listening on the http endpoint....

**Comment by ssoloff** [comment]
@ron-murhammer I should have been more accurate in what I stated.  It's not that the HTTP endpoint is disabled, it's that it is redirecting to the HTTPS endpoint (confirmed by running curl with `-L` [follow redirects]: `curl -L -X POST https://dice.tripleawarclub.org/MARTI.php`).

So it sounds like someone flipped a switch that said to redirect HTTP to HTTPS for the `dice.tripleawarclub.org` subdomain.  Undoing that looks to be the only real solution at this point as a code change won't help users running the current releases.

**Comment by ssoloff** [comment]
Nevermind, I realize I ran that curl command with an HTTPS URL instead of HTTP.  I get the same response as before with `-L` when hitting the HTTP URL.

**Comment by DanVanAtta** [comment]
Seeing a 301 moved permanently:
```
dan@dan-desk:~$  curl -X POST http://dice.tripleawarclub.org/MARTI.php
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>
```

I'm not sure about this bein ga port issue. The above seems to be returned from the web server.

**Comment by ssoloff** [comment]
An alternative theory is that HTTP always redirected to HTTPS, and, for some reason, that is no longer happening.

HTTP requests to `www.tripleawarclub.org` are redirected to HTTPS:

```
$ curl -L -v http://www.tripleawarclub.org/dice/MARTI.php
*   Trying 45.79.144.53...
* TCP_NODELAY set
* Connected to www.tripleawarclub.org (45.79.144.53) port 80 (#0)
> GET /dice/MARTI.php HTTP/1.1
> Host: www.tripleawarclub.org
> User-Agent: curl/7.53.1
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Server: nginx/1.10.3 (Ubuntu)
< Date: Fri, 03 Nov 2017 04:20:01 GMT
< Content-Type: text/html
< Content-Length: 194
< Connection: keep-alive
< Location: https://www.tripleawarclub.org/dice/MARTI.php
< 
* Ignoring the response-body
* Connection #0 to host www.tripleawarclub.org left intact
* Issue another request to this URL: 'https://www.tripleawarclub.org/dice/MARTI.php'
*   Trying 45.79.144.53...
* TCP_NODELAY set
* Connected to www.tripleawarclub.org (45.79.144.53) port 443 (#1)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: none
  CApath: none
* loaded libnssckbi.so
* ALPN, server accepted to use h2
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=tripleawarclub.org
* 	start date: Sep 28 18:01:14 2017 GMT
* 	expire date: Dec 27 18:01:14 2017 GMT
* 	common name: tripleawarclub.org
* 	issuer: CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x562543891010)
> GET /dice/MARTI.php HTTP/2
> Host: www.tripleawarclub.org
> User-Agent: curl/7.53.1
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200 
< server: nginx/1.10.3 (Ubuntu)
< date: Fri, 03 Nov 2017 04:20:07 GMT
< content-type: text/html; charset=UTF-8
< strict-transport-security: max-age=31536000
< 

<!DOCTYPE html>
<html>
	<head>
		<title>	M.A.R.T.I. Server --> "more accurate rolls than irony"- server</title>
	</head>
	<body>
<br />
<b>Notice</b>:  Undefined index: send in <b>/usr/share/nginx/html/tripleawarclub.org/public_html/dice/MARTI.php</b> on line <b>17</b><br />
<br />
<b>Notice</b>:  Undefined index: numsides in <b>/usr/share/nginx/html/tripleawarclub.org/public_html/dice/MARTI.php</b> on line <b>18</b><br />
<br />
<b>Notice</b>:  Undefined index: numdice in <b>/usr/share/nginx/html/tripleawarclub.org/public_html/dice/MARTI.php</b> on line <b>19</b><br />
<br />
<b>Notice</b>:  Undefined index: subject in <b>/usr/share/nginx/html/tripleawarclub.org/public_html/dice/MARTI.php</b> on line <b>20</b><br />
<br />
<b>Notice</b>:  Undefined index: roller in <b>/usr/share/nginx/html/tripleawarclub.org/public_html/dice/MARTI.php</b> on line <b>21</b><br />
<br />
<b>Notice</b>:  Undefined index: gm in <b>/usr/share/nginx/html/tripleawarclub.org/public_html/dice/MARTI.php</b> on line <b>22</b><br />
fa* Connection #1 to host www.tripleawarclub.org left intact
tal error: wrong input!
```

While HTTP requests to `dice.tripleawarclub.org` are _not_ redirected to HTTPS:

```
$ curl -L -v http://dice.tripleawarclub.org/MARTI.php
*   Trying 45.79.144.53...
* TCP_NODELAY set
* Connected to dice.tripleawarclub.org (45.79.144.53) port 80 (#0)
> GET /MARTI.php HTTP/1.1
> Host: dice.tripleawarclub.org
> User-Agent: curl/7.53.1
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Server: nginx/1.10.3 (Ubuntu)
< Date: Fri, 03 Nov 2017 04:20:27 GMT
< Content-Type: text/html
< Content-Length: 540
< Connection: keep-alive
< ETag: "56aaa2d7-21c"
< 
<!DOCTYPE html>
<html lang="en">
<head>
        <title>sanjuro.ca</title>
        <style type="text/css">
                html {
                        background:#000 url(http://www.sanjuro.ca/sanjuro.jpg) no-repeat center center fixed;
                        /*-webkit-background-size: cover;
                        -moz-background-size: cover;
                        -o-background-size: cover;
                        background-size: cover;*/
background-size: 100%;
                }
        </style>
</head>
<body>
</body>
</html>
* Connection #0 to host dice.tripleawarclub.org left intact
```

**Comment by ssoloff** [comment]
@DanVanAtta Interesting that you're getting a 301, while several of us are getting 404s with that empty `sanjura.ca` page.  Almost like there's a proxy or something between those of us seeing the 404 and `dice.tripleawarclub.org`, while you're getting the raw response.

What happens if you add `-L` to your cURL command to follow the redirect?

**Comment by DanVanAtta** [comment]
```
dan@dan-desk:~$  curl -L -X POST http://dice.tripleawarclub.org/MARTI.php

<!DOCTYPE html>
<html>
	<head>
		<title>	M.A.R.T.I. Server --> "more accurate rolls than irony"- server</title>
	</head>
	<body>
<br />
<b>Notice</b>:  Undefined index: send in <b>/usr/share/nginx/html/tripleawarclub.org/public_html/dice/MARTI.php</b> on line <b>17</b><br />
<br />
<b>Notice</b>:  Undefined index: numsides in <b>/usr/share/nginx/html/tripleawarclub.org/public_html/dice/MARTI.php</b> on line <b>18</b><br />
<br />
<b>Notice</b>:  Undefined index: numdice in <b>/usr/share/nginx/html/tripleawarclub.org/public_html/dice/MARTI.php</b> on line <b>19</b><br />
<br />
<b>Notice</b>:  Undefined index: subject in <b>/usr/share/nginx/html/tripleawarclub.org/public_html/dice/MARTI.php</b> on line <b>20</b><br />
<br />
<b>Notice</b>:  Undefined index: roller in <b>/usr/share/nginx/html/tripleawarclub.org/public_html/dice/MARTI.php</b> on line <b>21</b><br />
<br />
<b>Notice</b>:  Undefined index: gm in <b>/usr/share/nginx/html/tripleawarclub.org/public_html/dice/MARTI.php</b> on line <b>22</b><br />
```

**Comment by DanVanAtta** [comment]
And the plot thickens... I'm seeing the 301 redirect followed.  Are you still getting the 404?

```
dan@dan-desk:~$  curl -L -v http://dice.tripleawarclub.org/MARTI.php
*   Trying 2600:3c03::f03c:91ff:fef1:be1b...
* Connected to dice.tripleawarclub.org (2600:3c03::f03c:91ff:fef1:be1b) port 80 (#0)
> GET /MARTI.php HTTP/1.1
> Host: dice.tripleawarclub.org
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Server: nginx/1.10.3 (Ubuntu)
< Date: Fri, 03 Nov 2017 04:35:34 GMT
< Content-Type: text/html
< Content-Length: 194
< Connection: keep-alive
< Location: https://dice.tripleawarclub.org/MARTI.php
< 
* Ignoring the response-body
* Connection #0 to host dice.tripleawarclub.org left intact
* Issue another request to this URL: 'https://dice.tripleawarclub.org/MARTI.php'
* Found bundle for host dice.tripleawarclub.org: 0x5586916f1f20 [can pipeline]
*   Trying 2600:3c03::f03c:91ff:fef1:be1b...
* Connected to dice.tripleawarclub.org (2600:3c03::f03c:91ff:fef1:be1b) port 443 (#1)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 604 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_256_GCM_SHA384
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: tripleawarclub.org (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: CN=tripleawarclub.org
* 	 start date: Thu, 28 Sep 2017 18:01:14 GMT
* 	 expire date: Wed, 27 Dec 2017 18:01:14 GMT
* 	 issuer: C=US,O=Let's Encrypt,CN=Let's Encrypt Authority X3
* 	 compression: NULL
* ALPN, server accepted to use http/1.1
> GET /MARTI.php HTTP/1.1
> Host: dice.tripleawarclub.org
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx/1.10.3 (Ubuntu)
< Date: Fri, 03 Nov 2017 04:35:34 GMT
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Strict-Transport-Security: max-age=31536000
< 

<!DOCTYPE html>
<html>
	<head>
		<title>	M.A.R.T.I. Server --> "more accurate rolls than irony"- server</title>
	</head>
	<body>
<br />
<b>Notice</b>:  Undefined index: send in <b>/usr/share/nginx/html/tripleawarclub.org/public_html/dice/MARTI.php</b> on line <b>17</b><br />
<br />
<b>Notice</b>:  Undefined index: numsides in <b>/usr/share/nginx/html/tripleawarclub.org/public_html/dice/MARTI.php</b> on line <b>18</b><br />
<br />
<b>Notice</b>:  Undefined index: numdice in <b>/usr/share/nginx/html/tripleawarclub.org/public_html/dice/MARTI.php</b> on line <b>19</b><br />
<br />
<b>Notice</b>:  Undefined index: subject in <b>/usr/share/nginx/html/tripleawarclub.org/public_html/dice/MARTI.php</b> on line <b>20</b><br />
<br />
<b>Notice</b>:  Undefined index: roller in <b>/usr/share/nginx/html/tripleawarclub.org/public_html/dice/MARTI.php</b> on line <b>21</b><br />
<br />
<b>Notice</b>:  Undefined index: gm in <b>/usr/share/nginx/html/tripleawarclub.org/public_html/dice/MARTI.php</b> on line <b>22</b><br />
fa* Connection #1 to host dice.tripleawarclub.org left intact
```

**Comment by ssoloff** [comment]
>  Are you still getting the 404?

Yup.

**Comment by DanVanAtta** [comment]
On the other hand, I can reproduce the error in-game when testing the dice server:
```
java.io.IOException: Cound not find start index, text returned is:<!DOCTYPE html>
<html lang="en">
<head>
        <title>sanjuro.ca</title>
        <style type="text/css">
                html {
                        background:#000 url(http://www.sanjuro.ca/sanjuro.jpg) no-repeat center center fixed;
                        /*-webkit-background-size: cover;
                        -moz-background-size: cover;
                        -o-background-size: cover;
                        background-size: cover;*/
background-size: 100%;
                }
        </style>
</head>
<body>
</body>
</html>

	at games.strategy.engine.random.PropertiesDiceRoller.getDice(PropertiesDiceRoller.java:196)
	at games.strategy.engine.random.PBEMDiceRoller$HttpDiceRollerDialog.rollInSeperateThread(PBEMDiceRoller.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by DanVanAtta** [comment]
If the dice server is returning a redirect, seems like we should update the configuration as noted by 
@ssoloff to hit https directly. I can confirm that those updates result in a successful dice test.

I checked gitter and @RoiEXLab  updated the tripleawarclub postfix config. I do not know how though. With some luck @RoiEXLab would check back in soon.

**Comment by DanVanAtta** [comment]
https://github.com/triplea-game/triplea/pull/2565 Would update the game config.

**Comment by DanVanAtta** [comment]
I suggest we do this:
- update the config to use https (merge: #2565), wait for a new build
- post in forum about dice server, give link to the new build

---------------

Within the next 24 hours I'd suggest:
- coordinated regression testing on newest build
- mark that version as the latest (update download link)
- update lobby text to say that the newest has PBF and PBEM fixes

**Comment by DanVanAtta** [comment]
I suspect @RoiEXLab will check back and PBEM would be restored, though we still want to get users on the newest for PBF fix.

**Comment by DanVanAtta** [comment]
https://github.com/triplea-game/triplea/releases/tag/1.9.0.0.7386 has the latest updates

**Comment by RoiEXLab** [comment]
Sorry for the trouble everyone.
We had this problem when I migrated the Warclub sites over to https (that's why both were supported for a long time now), but I could've sworn I submitted a PR which made triplea follow 301 POST redirects. (I even found the PR, #1656).
So I thought with the new latest stable, everything should be working fine.
Everything should work fine again now, I configured nginx to accept connections over http again.

Again sorry for the trouble, I should have been doing more testing, but I was so sure!

**Comment by ssoloff** [comment]
@RoiEXLab I believe the #1656 code correctly follows 301 POST redirects.  It's just that some of us were not seeing the redirects.  @DanVanAtta saw the redirects when using cURL, and then was getting the same 404 as the rest of us when using TripleA.  It would be interesting to understand the root cause of that discrepancy.

**Comment by RoiEXLab** [comment]
Alternative would be to try and get a new dice server working as quickly as possible, to avoid having to deal with PHP :P

**Comment by RoiEXLab** [comment]
Nevermind, I found the reason why the 404 errors occured.
Apparently I didn't do the redirect to https correctly: I forgot to out-comment the server_name entry for dice.tripleawarclub.org, leading to the request being picked up by another configured http handler (the sanjuro.ca entry for example I just deleted, because the domain doesn't exist anyways).

Should we try turning it on again correctly this time, so triplea simply follows the redirect?

**Comment by ssoloff** [comment]
> Nevermind, I found the reason why the 404 errors occured.

Nice.  Still wondering why @DanVanAtta saw what he saw, but your analysis of the problem makes total sense from my perspective.

> Should we try turning it on again correctly this time, so triplea simply follows the redirect?

Probably not at this time.  As @ron-murhammer pointed out [here](https://github.com/triplea-game/triplea/pull/2565#issuecomment-341726855), that's just going to lead to potentially more users reporting certificate path validation errors.

**Comment by RoiEXLab** [comment]
@ssoloff Yeah, see https://github.com/triplea-game/triplea/pull/2565#issuecomment-341751600 for my answer

**Comment by RoiEXLab** [comment]
@ssoloff In case you're still interested:
I found the remaining nginx entry for sanjuro.ca in the tripleawarclub config and confirmed the same page as described above was being displayed when accessing the site with an unknown server subdomain.

BTW. The lobby is now reachable via lobby.triplea-game.org
