### ISSUE TITLE
PBF turns off dice

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#2577]
Loading a PBF game, the dice server selected by default is the internal dice server. Why is that? It wasn't the case in the past. It should select the marti server unless you select something else along the way.

**Comment by panther2** [comment]
I can't reproduce that here. Which version are you using?

**Comment by simon33-2** [comment]
1.9.7386.

Really? Every save game I load sets the dice server to the internal one.

**Comment by ron-murhammer** [comment]
Can't reproduce this either. If you have a save then to reproduce then please upload.

**Comment by simon33-2** [comment]
Might have been a bad save somewhere. Anyway, doesn't seem to be recurring.
