### ISSUE TITLE
Flaky test: OddsCalculatorTest#testKeepOneAttackingLand

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/triplea#2586]
Just noting that I experienced a [build failure](https://travis-ci.org/ssoloff/triplea-game-triplea/builds/299277404) due to the `OddsCalculatorTest#testKeepOneAttackingLand` test failing:

```
Failures (1):
  JUnit Jupiter:OddsCalculatorTest:testKeepOneAttackingLand()
    MethodSource [className = 'games.strategy.triplea.oddsCalculator.ta.OddsCalculatorTest', methodName = 'testKeepOneAttackingLand', methodParameterTypes = '']
    => org.opentest4j.AssertionFailedError: expected: <0.8> but was: <0.6>
```

This test seems to be statistical in nature, and this failure was at the very edge of the boundary condition.  Not sure if we should be concerned at this time.  This is the first time I've seen this test fail since I've started working on this project.

**Comment by ron-murhammer** [comment]
I'd like to get to a point where even rare failures don't occur. Preferably by seeding the dice or something.

**Comment by RoiEXLab** [comment]
I'd like to point out that OddsCalculator tests are causing flaky coverage as well.
This is especially annoying for "typo" or config imporvement PRs, where the coverage clearly shouldn't be affected, but codecoc still complains about the coverage and the PR goes red

**Comment by ssoloff** [comment]
Closing as I haven't seen this particular failure since I opened the issue 6+ months ago.  Seems like very little ROI at this point to fix.
