### ISSUE TITLE
Engine Preferences Malfunction

### ISSUE THREAD

**Issue by ManfredVonRichthofen** [triplea-game/triplea#2597]
### Map: World War II v3 1942

Engine Preferences - Combat - Don't work at all it does not matter what values I assume. I set all to True and still it runs as they were False. On version 1.8 things run as they did ( no automated) but the editing isn't working for this new version (1.9.). Please fix it

**Comment by ssoloff** [comment]
Whoops...  Confirmed that all three Combat preferences are not referenced anywhere in the code other than by the settings UI.  We'll have to go back through the history and find out when this broke in order to restore the functionality.  Thanks for reporting, @ManfredVonRichthofen.

**Comment by ssoloff** [comment]
All three settings appear to have been disconnected from `BattleDisplay` (where the actual decisions are made) in #2137.  Should be a relatively straightforward fix.

**Comment by ManfredVonRichthofen** [comment]
When you have it fixed please say so.

**Comment by RoiEXLab** [comment]
@ManfredVonRichthofen This issue should be fixed for TripleA v1.9.0.0.7516+

**Comment by RoiEXLab** [comment]
You can find the latest pre-releases [here](https://github.com/triplea-game/triplea/releases), please report back if something does not work for you.

**Comment by prastle** [comment]
@RoiEXLab It does appear to be working correctly now.
