### ISSUE TITLE
Axis & Allies .org moving to Discourse forums

### ISSUE THREAD

**Issue by djensen47** [triplea-game/triplea#2601]
Before the end of the year, we're moving the forums to Discourse. I was hoping to do this in November but my practice migration is taking a _long_ time.

The good news is that Discourse has an API. The bad news is the user token workflow is not documented.

Here is a conversation on meta.discourse.org discussing it:
https://meta.discourse.org/t/generating-user-api-keys-with-rest-api/61916

The new forum is currently located at forums.axisandallies.org but this will eventually change to be on the same domain as the current forum.

I've turned off registration in the new forum so please send me your email addresses and I'll invite you. webmaster@axisandallies.org

Thanks!

**Comment by panther2** [comment]
Mail sent, thanks!

**Comment by RoiEXLab** [comment]
@djensen Oh well, Setting up a NodeBB client could've been done in minutes, by simply copying the current code for the NodeBB TripleA Forum and changing the URL, but anyways I believe currently the TripleA forum code is doing something similar:
If I recall correctly, we query a new API key using the users credentials, do all of the posting stuff and dump the key afterwards, so if you could provide me all relevant links/routes which are required to be able to post and attach savegames that'd be really helpful.

**Comment by djensen47** [comment]
Here are the Discourse API docs: http://docs.discourse.org

Looks like you'll need posts and uploads:
http://docs.discourse.org/#tag/Upload
http://docs.discourse.org/#tag/Posts

I think you have to upload the file first, then include a link to it in the post.

**Comment by simon33-2** [comment]
Curious as to why discourse is superior to SMF?

**Comment by djensen47** [comment]
SMF is a huge mess of spaghetti code. There are no plugins, instead there
are mods as in modifications. You basically patch code to add new features.
The huge problem there is that upgrades are done the same way. So you might
end up in a situation where you cannot upgrade. The templating system is in
the same huge mess. Finally, it's not responsive so it looks terrible on
mobile.

**Comment by djensen47** [comment]
Any updates?

I'm not sure anybody has asked for an account login.

**Comment by RoiEXLab** [comment]
I'll have a look over the weekend.

**Comment by djensen47** [comment]
@RoiEXLab Thanks. Did I get an account set up for you already?

**Comment by RoiEXLab** [comment]
@djensen47 I don't think so... 
I'll send you an email

**Comment by RoiEXLab** [comment]
@djensen47 
So I did some coding, and ended up encountering the problem you already mentioned.
I honestly have no idea on how to get a user token, the links you provided do not seem to give much information, the only things I'm ending up reading is how to generate tokens once you have an all powerful admin token etc.
If there's no way to generate a token using passwords via the API, a viable workaround may be to use an API key instead of a password, but the problem is still how to generate a token?

Here's my initial attempt, that _could_ potentially work when we have a way to retrieve a token.
```java
public class AxisAndAlliesForumPoster extends AbstractForumPoster {
  private static final String FORUM_URL = "http://forums.axisandallies.org";

  @Override
  public boolean postTurnSummary(final String summary, final String subject) {
    try (CloseableHttpClient client = HttpClients.createDefault()) {
      final String token = createToken(client);
      try {
        post(client, "### " + subject + "\n" + summary, token);
      } finally {
        revokeToken(client, token);
      }
      return true;
    } catch (IOException e) {
      ClientLogger.logQuietly("Failed to post game to forum", e);
      m_turnSummaryRef = e.getMessage();
      return false;
    }
  }

  private String uploadSaveGame(final CloseableHttpClient client, final String token)
      throws ClientProtocolException, IOException {
    final HttpPost post = new HttpPost(FORUM_URL + "/uploads.json");
    final JSONObject object = newAuthenticatedJsonObject(token);
    object.put("type", "composer");
    object.put("synchronous", true);
    post.setEntity(MultipartEntityBuilder.create()
        .addBinaryBody("files[]", m_saveGameFile, ContentType.APPLICATION_OCTET_STREAM, m_saveGameFileName)
        .addTextBody("params", object.toString(), ContentType.APPLICATION_JSON)
        .build());
    HttpProxy.addProxy(post);
    try (CloseableHttpResponse response = client.execute(post)) {
      final String rawResponse = EntityUtils.toString(response.getEntity());
      return "\n[Savegame](" + new JSONObject(rawResponse).getString("url") + ")";
    }
  }

  private void post(final CloseableHttpClient client, final String text, final String token)
      throws ClientProtocolException, IOException {
    final JSONObject object = newAuthenticatedJsonObject(token);
    object.put("topic_id", m_topicId);
    object.put("raw", text + ((m_includeSaveGame && m_saveGameFile != null) ? uploadSaveGame(client, token) : ""));
    final HttpPost post = new HttpPost(FORUM_URL + "/posts");
    post.setEntity(new StringEntity(object.toString(), ContentType.APPLICATION_JSON));
    HttpProxy.addProxy(post);
    client.execute(post).close();
  }

  private JSONObject newAuthenticatedJsonObject(final String token) {
    final JSONObject object = new JSONObject();
    object.put("api_key", token);
    object.put("api_username", getUsername());
    return object;
  }

  private String createToken(final CloseableHttpClient client) {
    // TODO retrieve a user token somehow
    throw new UnsupportedOperationException();
  }

  private void revokeToken(final CloseableHttpClient client, final String token) {
    // TODO dump a user token somehow
    throw new UnsupportedOperationException();
  }
  /*
     Some unimportant code unrelated to the actual posting API
  */
}
```

**Comment by RoiEXLab** [comment]
@djensen47 Some general questions I asked myself while coding:
Is the new forum supposed to replace the current one?
If so, should TripleA still support the then old forum in terms of PBF, or should the new PBF entry completely replace the current one?
You mentioned you want to move the forum to the current URL, would this be immediately, so my first question becomes obsolete?
If it's not immediately I'd highly encourage you to use HTTPs for the time in between, simply because password security is important.

**Comment by djensen47** [comment]
> Is the new forum supposed to replace the current one?

Yes, it will completely replace it.

> If so, should TripleA still support the then old forum in terms of PBF, or should the new PBF entry completely replace the current one?

After the migration is done, probably in the late February or March time frame, the PBF entry should replace the current one. However, forums.axisandallies.org will not be the location of the new forums. It is there as a testing and staging  area. 

> You mentioned you want to move the forum to the current URL, would this be immediately, so my first question becomes obsolete?

I'm considering having the forum live on /forums/ or /forum/ or /community/

> If it's not immediately I'd highly encourage you to use HTTPs for the time in between, simply because password security is important.

Since forums.axisandallies.org is temporary I didn't want to bother with setting up SSL.

**Comment by djensen47** [comment]
@RoiEXLab Regarding the code. You might want to take a look at the source code for the Discourse mobile app. I also highly recommend utilizing meta.discourse.com because they actually want some documentation on how to do all of this. I was going to make an attempt but my schedule got super full. 

This conversation should help: https://meta.discourse.org/t/generating-user-api-keys-with-rest-api/61916

**Comment by RoiEXLab** [comment]
@djensen47 By briefly looking at the code it seems you need to generate a keypair and give me a public key of some sort?
I'm getting the same 400 error you mentioned, I'll try a couple of things but I'm not going to promise any results :(

**Comment by RoiEXLab** [comment]
@djensen47 Ok, I got the server to respond with error code 500, it seems I simply needed to pass all GET params to get another error.
Given those lines of code:
https://github.com/discourse/DiscourseMobile/blob/8242ceec39e0e38562751114b2a06089b24ff779/js/site_manager.js#L479-L485

I'm assuming (haven't really looked into any details), that the discourse app opens a browser windows with this GET params, that display a webpage to the user where the user can authenticate normally.
After a successful authentication the user is getting redirected to the passed URL, that in the case of an android app opens the app itself, probably with some GET params (not sure if that's possible).

That would be bad.
My other theory however (if no GET params will be passed to the callback URL) is that the client generates a keypair and sends the public key to the server so he can use it that way somehow? I really have no clue how they exactly do it.
If you have them time, and are savvy enough, could you log the GET request from your phone somehow including the response?

**Comment by djensen47** [comment]
I could probably setup mitm to look at the traffic. It might just be easier to post something over at meta.discourse.org

If  you explain the steps to where you are, I think they would be happy to help. Response time is decent enough, especially if you @ sam.

**Comment by RoiEXLab** [comment]
@djensen47 Will do during the week, I don't really have that much time either to learn about an undocumented API, but I'll try my best

**Comment by RoiEXLab** [comment]
@djensen47 Finally got some time to look at this again.
Seems you need to enable this feature first: 
![grafik](https://user-images.githubusercontent.com/8350879/37983567-1a21d886-31f4-11e8-9222-3e6049acf39c.png)
GET Request used was: http://forums.axisandallies.org/user-api-key/new?application_name=TripleA&scopes=post&nonce=asdasdasd&auth_redirect=<redacted>&client_id=TripleA&public_key=<redacted>

**Comment by djensen47** [comment]
Sorry I missed this, let me do this right now.

**Comment by djensen47** [comment]
It looks liker I have it enabled already:
![image](https://user-images.githubusercontent.com/527865/38289398-c9b81e2c-378a-11e8-9961-88b6e2fa0856.png)
