### ISSUE TITLE
Crashing during casualty selection since release .7374

### ISSUE THREAD

**Issue by panguitch** [triplea-game/triplea#2605]
A player brought it to my attention that Greyhawk Wars is crashing during casualty selection. This happens whether it's a human player or an AI. I'm not attaching a saved game because all you have to do to reproduce is start the game and have a battle with mixed troops. I did some testing and it appears this bug was introduced with release 7374 (can't reproduce in earlier versions, can in 7374 and later). I've attached an error log. Any insight as to the cause and/or fix for this is much appreciated.
[ghwarserror.txt](https://github.com/triplea-game/triplea/files/1469072/ghwarserror.txt)

**Comment by ron-murhammer** [comment]
The problem is this:
**Not found:games.strategy.engine.framework.ServerGame.PLAYER_REMOTE.Neutral**

An error was introduced into the engine but has been fixed. Please update to latest TripleA pre-release and retest.

**Comment by panguitch** [comment]
Yes, latest pre-release looks error-free. Thanks! 
I selfishly hope this goes live soon since Greyhawk Wars is basically a race to conquer neutral territories, hence unplayable on current release.
