### ISSUE TITLE
Banning 365 days

### ISSUE THREAD

**Issue by Leijonma** [triplea-game/triplea#2616]
### Any additional information that may help:

I received the message "You have been banned for 365 days" when trying to log in to lobby today 18/11-17.

Have not done anything offensive. It must be some bug. It happened before some months ago and then it was a massive isssue for others also.

Please help me get in the lobby again.

hale

**Comment by ron-murhammer** [comment]
@prastle Can you take a look at this?

**Comment by prastle** [comment]
Hale is not a name I recognize as a user.  The only person banned today to my knowledge (if it was posted by Champ) was an alias of our friend of many names.  I will Dig one moment.  No info posted by Champ.  He did mention that he was banning someone that we have a one year ban on.

**Comment by prastle** [comment]
This does bring up my issue that has been talked about tho.  All bans need to be recorded by the toolbox  as to whom when and why on the server.

**Comment by prastle** [comment]
So @Leijonma what is your normal online user name?

**Comment by Leijonma** [comment]
hale

If you want my email I can give it also (ifyou not already have it).

More facts is that when logging in ca 17 hours CET yesterday my computer demanded me to change some script and I had to accept to be able to get in to main tripl AAA, not lobby.

Sorry forgot to mention this yesterday.

As you recognise I am pretty bad computerwise which dosn't help trying to fix this problem.

Before I played A&A on GTO but it was shut down 4 years ago. So natural question is how long has tripleAAA?

Greetings

hale

Skickat från min iPhone

18 nov. 2017 kl. 23:51 skrev prastle <notifications@github.com<mailto:notifications@github.com>>:


So @Leijonma<https://github.com/leijonma> what is your normal online user name?

**Comment by RoiEXLab** [comment]
Not part of the Mod team, but your username was indeed banned.
Since I couldn't find a reason (and no log either) in the banning log we have, I simply unbanned the username 'hale'.
You should be able to login again.

**Comment by RoiEXLab** [comment]
@prastle Feel free to correct me if I'm wrong.

**Comment by Leijonma** [comment]
Hallo RoiEX!

Sorry but when I tried to log into TriplAAA today I got the message "You are banned for 363 days..."

I still can not log in.

Please try to fix this.
Trying to master WWII Global now because it is so common on AAA.

Greetings

hale

Skickat från min iPhone

19 nov. 2017 kl. 09:35 skrev RoiEX <notifications@github.com<mailto:notifications@github.com>>:


Not part of the Mod team, but your username was indeed banned.
Since I couldn't find a reason (and no log either) in the banning log we have, I simply unbanned the username 'hale'.
You should be able to login again.

**Comment by prastle** [comment]
So Champ did confirm that the banned name was Hale sadly I have no info.  But Atm we only have Jimmy and Bidsurfer banned so if the id matches that I would guess it is a 1 year ban.  Just the info I can offer.

**Comment by RoiEXLab** [comment]
@Leijonma Could you try logging in again?
Should definitely work now, assuming your given date is correct.

**Comment by Leijonma** [comment]
Hallo!

Have been able to log into Lobby today 19:30 CET.

Thanks.

hale

Skickat från min iPhone

21 nov. 2017 kl. 13:47 skrev RoiEX <notifications@github.com<mailto:notifications@github.com>>:


Closed #2616<https://github.com/triplea-game/triplea/issues/2616>.
