### ISSUE TITLE
Install4j bundled JRE

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#263]
Which JRE to bundle with artifacts created by install4j?

**Comment by gaborbernat** [comment]
Do not understand your question :)

**Comment by DanVanAtta** [comment]
install4j allows an arbitrary JRE to be bundled with the artifacts it builds. We drop the JRE in the install folder "JRE" and update the XML and it deploys it.

You voiced concern over Oracle's JRE as being included. In my experience, as a linux user, openJDK, and on the current system I'm working on, is completely buggy. The only JRE that does not cause system instability is Oracles. I'm not in love with Oracle, but it is what works.

Furthermore it's the JRE used by travis to test, so there is less difference between how we test and what we actually deploy if we go with Oracle JRE. You voiced concern over this bundling option @gaborbernat .

**Comment by DanVanAtta** [comment]
"I would oppose using the Oracle. I think we should stick with the install4j download. Maybe it has some extra required meta embedded, or could be in the long run. I see that change you made, and I do not like it. :|

There is an option in install4j for using system/bundled. I prefer bundled because that way we can control the users Java version."

So really the question is, if bundled, which bundle.

I guess it's probably worth asking if we should use system or bundled. "Controlling" the JRE maybe has benefit, but practically I can't think of anything specific. I see it inviting issues where users complain that the bundled JRE we force on them does not work on their system and they do not understand why their careful chosen JRE choice is not being respected. By that token I think we are inviting trouble by not using the system JRE when its available.

**Comment by gaborbernat** [comment]
I'm failing to understand why the bundled Java should not work?

**Comment by DanVanAtta** [comment]
OpenJDK JRE and any other I tried caused system instability on my OS (ubuntu). Oracle JRE is the only one that did not. I've no particular love for Oracle, but I've also generally little choice in the matter. Perhaps we should just not bundle JRE?  Otherwise how can you ensure this bundled JRE does not cause problems?

Oracle JRE works on every system without question. Effectively the only reason to not bundle Oracle JRE is if you really do not like proprietary software. It's a valid philosophical complaint, but the test burden we incur is too great in my point of view if we don't use it. We can go with openJDK, that is the only other Java that travis has installed. Running tests and deploying with a different java is a non-starter in my mind.  The whole point of this was to boost our efficiency, and that means not wasting extra time doing manual testing with some random non-standard JRE. Please detail what this JRE is as well. I was not able to find it searching for it via the google, and that is concerning already.


1) the triplea community is pretty stagnant, if you lock anyone out due to game bugs that is a big loss. This is probably pretty strong reason to not force any kind of JRE - we cannot know why or which exact JRE someone might happen to require.

2) seems like if we do bundle JRE, we get into a religious argument of GPL vs open source with proprietary software. From a practical point of view I want a JRE I know will work on my system and won't lock other users out with similar hardware and software. So if we do bundle something, I'd like to go for the less risky and better tested option.

**Comment by DanVanAtta** [comment]
Options:

build a Java bundled version only
build a non-bundled version only
build both bundled and non-bundled versions
bundle
with install4j JRE (@gaborbernat , do you know which one it is specifically?)
with oracle JRE
with openJDK JRE
@gaborbernat , if the windows installer is bundled, are we forced to produce a 32 bit and 64 bit version? Does unbundling avoid that?

**Comment by DanVanAtta** [comment]
@gaborbernat , could you compare the size of the two different JRE options? If the one install4j has is smaller would you submit a PR against the assets repo to update the assets there. Your instructions did not include where to get a JRE and I never opened install4j via GUI. The JRE that was mentioned I could not find anywhere, so I added a JRE simply to get things working.

**Comment by DanVanAtta** [comment]
I'm reading around to try and see what best practices are. It looks like download size vs more control and simpler UX. These days download size is less important, and if someone is going to DL 200MB, they can probably wait to DL another 30 or 50MB of JRE too.

So unless someone asks for minified DL size, let's stick to bundling a JRE. If there are complaints of the download being too large after we switch to mp3 then we should consider  creating multiple build artifacts.

**Comment by DanVanAtta** [comment]
The bundled JRE is also one less thing for the bot servers as well. That is quite attractive, so I'm pretty convinced there are more pro's to bundling a JRE than drawbacks. Now to find the smallest JRE to bundle and figure out if we need to produce 32 and also 64 bit versions of everything.

**Comment by DanVanAtta** [comment]
Answer to this issue seems to be to at least automatically create each type of installer, then it is up to the website. Closing this issue since #277 tracks that task. For more discussion of this issue see #276
