### ISSUE TITLE
Up Arrow hotkey for reposting chats, not functional

### ISSUE THREAD

**Issue by General-Dru-Zod** [triplea-game/triplea#2640]
### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Try reposting in lobby, bots, private host using up arrow hotkey.
### Instead of this error, what should have happened?
Should increment through all recent chat posts one by one for each press of up arrow hotkey. Last noticed as functional in 7342.

**Comment by ssoloff** [comment]
Thanks, @General-Dru-Zod.  Looks like this broke in 1.9.0.0.7378 due to #2570.  Working on a fix...

**Comment by RoiEXLab** [comment]
@General-Dru-Zod this issue should be fixed in the latest pre-release [1.9.0.0.7645](https://github.com/triplea-game/triplea/releases/tag/1.9.0.0.7645)
Please report back if anything does no work as expected.
