### ISSUE TITLE
Add a performance test for battle calculator

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2641]
Proposed Task:
- create a new unit test that runs battle simulator
- do a calc that ideally takes under 500ms, put an SLA on the test so it fails if the runtime increases by more than 30% (overall I think we are looking at 20 lines of code so far if not less)
- be sure to include all corner type cases, network game is a big use-case. (alternatively we can move to remove any network dependencies in the battle simulator).

**Comment by DanVanAtta** [comment]
It does not seem like this got picked up. The real ask here is that we do not reject PRs due to slight (less than 15% degradations in performance) and that we do not also ask every PR author to arbitrarily do a full performance test of the AI and battle calc on minor changes. 

@ron-murhammer , what are your thoughts on this -  do you think we should add  such a performance test to solve this problem? How can we best address the concern/problem here?

**Comment by ron-murhammer** [comment]
I mean it probably has some value to create a performance test but not sure anyone is gonna pick it up. Generally the BC is one of the only things that takes noticeable time and is used in several areas so we do need to be careful around its performance. If significant changes are made to it then some sort of performance evaluation should be included in the PR.

**Comment by DanVanAtta** [comment]
This was created due to a perceived need, IMO the ROI is not favorable so I'll close. There are some issues as noted:
- not picked up yet
- would add complexity to testing and time, not necessarily great
- can be solved pretty easily by testing and noting if AI seems performant enough
- we just don't have many examples where performance testing has been a big hindrance or a problem. I'd rather us focus on other priorities.
