### ISSUE TITLE
Add a 'how_to_host_a_bot.txt'  to the game installation

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2642]
Simple task, include a text file that directs game players to the triplea-game/lobby repo and the online instructions on how to host.

**Comment by DanVanAtta** [comment]
Note: our current online documentation may be lacking, the real work here maybe to improve that.

Some additional requirements:
- need steps for each OS
- all instructions should be hosted online/github, not bundled with the game install. This way we only need to keep one link up to date and documentation can more easily stay in sync and updates are live.

**Comment by prastle** [comment]
Well really the firt step is how to let them host.  Anyone that can host can host a bot. Which would be step two.
