### ISSUE TITLE
Fresh install: User is not prompted to download the tutorial map

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2646]
Repro:
- install mac OS DMG using https://github.com/triplea-game/triplea/releases/tag/1.9.0.0.7621
- open game

Notice:
- no prompt to play the tutorial
- no tutorial map is installed
- tutorial map is not selected as default map

<img width="796" alt="screen shot 2017-11-26 at 3 07 39 pm" src="https://user-images.githubusercontent.com/12397753/33245709-52f9b504-d2c0-11e7-9a51-2cfe2fb05621.png">

<img width="816" alt="screen shot 2017-11-26 at 3 40 56 pm" src="https://user-images.githubusercontent.com/12397753/33245712-57a69158-d2c0-11e7-9bf1-07b5d014e424.png">

**Comment by ssoloff** [comment]
The tutorial is no longer bundled with the installer, so if this is a problem, it shouldn't be Mac-specific.

Is this a box on which you've run TripleA before, possibly from an IDE?  If so, you'll need to delete the `TRIPLEA_PROMPT_TO_DOWNLOAD_TUTORIAL_MAP` entry in _~/.java/.userPrefs/games/strategy/triplea/settings/prefs.xml_.

Also, your user maps folder must be completely empty.  Any file or directory present in this folder (even unrelated to maps) will prevent the prompt to download the tutorial from being displayed (see the code in `MapDownloadController` for details).

**Comment by ssoloff** [comment]
Looks like this broke in [`71bcf7af9`](https://github.com/triplea-game/triplea/commit/71bcf7af9bee7f989a4fd563b17e527123e69c0f#diff-0840434b65a524f239ee2a067d3260b5R162) during the client settings framework rewrite: the default value of `TRIPLEA_PROMPT_TO_DOWNLOAD_TUTORIAL_MAP` was changed from `true` to `false`.  I'll submit a PR later this evening...

**Comment by DanVanAtta** [comment]
Thanks for taking a look. Rig is a fresh game install, no IDE.

Last I knew tutorial should be bundled with installer, it was one of the compromises for allowing no maps to bundled other than Tutorial. In part, it does not make sense to show the 'would you like to play the tutorial' prompt if the map is missing.

I'm curious if there was further discussion on not including the Tutorial.

**Comment by prastle** [comment]
Not to my Knowledge
It seems silly to down load an engine with nothinginstalled
 ;)

**Comment by ssoloff** [comment]
> I'm curious if there was further discussion on not including the Tutorial.

#1585

**Comment by prastle** [comment]
Thanks @ssoloff  Now I understand. But this it might be causing problems to new users.  Since any new user has no idea how to dl a map.  Thus if they ignore it where do they go from there? later?

**Comment by prastle** [comment]
Another side issue would be that all lobby mods expected it to still be there since all other maps were removed.  Thus many myself included would tell a new user to play the tutorial.  Which apparently isn't there now either.  Just my 2 cents

**Comment by ssoloff** [comment]
> But this it might be causing problems to new users. Since any new user has no idea how to dl a map. Thus if they ignore it where do they go from there? later?

I believe the intention of the message at the bottom of the dialog referenced in #1585 was to instruct users how to download a map if they click **No** when prompted to download the tutorial.  We can provide more detailed instructions for downloading a map in that dialog if users are having a hard time with the current text.

**Comment by DanVanAtta** [comment]
I recall more context now, sorry for the churn. Regardless it is a bit broken to have a tutorial map and it just be buried amongst the other maps. In part the dialog is missing, fixing that is a good start.

The intent is that clicking default menu's and pop-ups as a new user would get someone directly in the game, playing the tutorial. Our prompting system would ideally guide a player to a game after the download completes.

In retrospect, it may have been a bad call to remove the tutorial as a bundle. I'm thinking in an updated UI it would be better to incorporate it, we may want to add it back in for now so we do not have to guide new users to the map download and beyond to actually playing the tutorial.
