### ISSUE TITLE
installers - not installing into sub directory

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#265]
"We install directly into the directory they specify, instead of into a sub directory with our version number.
Are we not allowing people to install multiple versions anymore?"

**Comment by DanVanAtta** [comment]
The reasons for this seem mainly to be so we can group all triplea content into one folder. Off the top of my head there will be three key folder:
- savedGamed
- maps
- triplea_{version}

Thus having the installation go into `~/triplea/triplea_{version}` is useful to preserve game saves and map downloads.

**Comment by DanVanAtta** [comment]
It doesn't seem right that we make people clean up old game engines.  The game engines have their own map bundles and so the folders are large. **Perhaps we should instead of deploying to ~/triplea/triplea_{version}, deploy to ~/triplea/game_code**

Having it be clear which version is being downloaded and installed will help avoid the need to have the version number be encoded in the folder name. We also have features where nobody needs old game engines, the "old" jar files are packaged with a new game engine. So it really is the case we are leaving users to clean up old installations (ie: this is an automation gap for us).

**Comment by gaborbernat** [comment]
The current install model follows this. If you have an old version installed it will automatically upgrade the old to the new one. It has the drawback that multiple versions cannot be installed in parallel. On the other I value more the auto upgrade than the lack of this parallel version.

**Comment by veqryn** [comment]
just an fyi: 
savedGames and maps go into the USER_HOME/triplea directory, whereas the actual install goes into PROGRAM_FILES/triplea directory (or its unix/mac equivalent)

**Comment by veqryn** [comment]
IF we are going to install over top of a previous version, we need to remove files that should no longer exist.
example: we change the name of a sound file and fix something in it.  if you install over top of the old one, you now have two copies of it, and it will get played twice as often...

**Comment by DanVanAtta** [comment]
The USER_HOME/triplea should eventually become a configurable value. I have the versioned triplea directory installed to USER_HOME/triplea/triplea1_8_09 which works well for me. 

Ultimately I like the upgrade route rather than multiple parallel versions. Leaving users for manual clean up is not a good thing.

**Comment by veqryn** [comment]
What about the file cleanup needed from overwriting?

**Comment by DanVanAtta** [comment]
@gaborbernat , do you know if upgrade means deleting the prior installation and writing everything as if it were a new installation, or does it mean adding and modifying the things that are new or modified?

**Comment by gaborbernat** [comment]
I think it just overwrites the files, but I may be wrong. 

More information at: http://resources.ej-technologies.com/install4j/help/doc/index.html

**Comment by veqryn** [comment]
if we are really into the 'free upgrade', i would prefer we write to a new directory, and after full success of the install, uninstall the previous one.  this way a partial or cancelled install does not delete the old install.

**Comment by DanVanAtta** [comment]
Install4j has an option to do a "clean" upgrade, this is likely what we want:

> "If you would like to uninstall the previous installation before installing any new files, you can add the "Uninstall previous installation" action before the "Install files" action." (http://resources.ej-technologies.com/install4j/help/doc/)

@veqryn , it's a good thought and for shell script installers that would be for certain something to do. In this case I don't think deploying to a temp directory first is a reasonable requirement. For install4j I would hope they have that functionality built in already. Even if it's not, it's not all that terribly useful in effect. If a user really can't install a new version, they have trouble anyways since they *have* to upgrade to be able to play on a new lobby. If there are such severe problems with the installer that can't be remedied by retrying, we have bigger problems. 

In the meantime leaving every user to clean up old game installations is a bigger problem than a relatively much lower risk error case scenario. Particularly since not many users are very skilled computer-wise and will not even know where nor even how to clean up old game installations. Deleting entire program applications folders by hand (particularly in windows) is an act of courage, even if you know what you are doing.

**Comment by DanVanAtta** [comment]
I cut #278 to track the action item to use the "clean" upgrade feature. Will keep this open for a few days in case there is more discussion about alternatives or additional considerations to discuss.
