### ISSUE TITLE
Please do not depend on org.json:json which is non-free software

### ISSUE THREAD

**Issue by apoleon** [triplea-game/triplea#2672]
Please do not depend on org:json:json which is non-free software. It contains the infamous license clause "The Software shall be used for Good, not Evil." This dependency could be replaced by existing free software.

https://wiki.debian.org/qa.debian.org/jsonevil

**Comment by ssoloff** [comment]
Thanks for the heads-up, @apoleon.  Indeed, the JSON license is [not compatible](https://www.gnu.org/licenses/license-list.en.html#NonFreeSoftwareLicenses) with the GPL.

**Comment by ron-murhammer** [comment]
Yeah, we should look to change this dependency.
