### ISSUE TITLE
Rules clarification on LL low luck movement of fighters requiring carrier

### ISSUE THREAD

**Issue by airwalker1** [triplea-game/triplea#2675]
### Any additional information that may help:

Here is the scenario that seems to cause debate from many players. Does a carrier or multiple carriers need to move into a sea zone that would be required for landing of planes if some are shot down? 

In the example of the savegame below, I was playing Straha who has taken East Indies and has 3 carriers, 6 planes on carriers and two on E Indies. He attacks FIC with all 8 planes, with the carrier planes being able to land back on carriers (two movements there, two back), but the planes on East Indies are a movement of 3 and could only land on a carrier. It is my understanding that you MUST include the carrier to ensure a valid movement or it would be considered kamikaze. Straha's point is that the two planes from East Indies are automatically shot down first and therefore the remaining planes have movement left that would not require the carrier. As it is low luck, using this logic and scenario of 3 carriers he could calculate to send 12 fighters to FIC as long as 6 are shot down without ever moving the carriers. I consider that kamikaze as do some others. In my opinion it is wrong to send planes knowingly to their death to avoid movement rules, but I would like to publicly address it for clarification and feedback.

Please note in the savegame he moved the carriers to that zone during the combat phase, but said it was a mistake and asked to edit them back. That is why you will see one carrier remaining as we were discussing this issue.

  
[1.zip](https://github.com/triplea-game/triplea/files/1543894/1.zip)

**Comment by ron-murhammer** [comment]
The carriers have to be "able" to move to a place where ALL fighters can land (can't send fighters that have no potential place to land even if LL you know they die) but a player only has to move the carriers during non-combat if the fighters survive.

**Comment by airwalker1** [comment]
Please clarify: (can't send fighters that have no potential place to land even if LL you know they die)

In regards to the game I uploaded he sent 2 fighters that could not land except via carrier, but he claims those fighters are shot first and the remaining fighters have movement without carrier.

**Comment by ron-murhammer** [comment]
He would be correct. The fighters with the least remaining movement can be taken casualty first. As long as it was possible for him to move the carrier for them to land then the move is valid. He isn't forced to move the carrier if they die during combat.

**Comment by airwalker1** [comment]
So theoretically he can send 6 from FIC and 6 from the carriers and if 6 are lost he will not need to move carriers?

This is my concern as it goes up and up exponentially with carriers. Its sending half to their death, which can be calced in LL for the purpose of avoiding movement restrictions.

**Comment by ron-murhammer** [comment]
Correct. You just need to have the potential for all the fighters to land. You only have to actually move the carriers if fighters survive that can only land on the carriers. It doesn't really go up exponentially as it just scales linearly with number of fighters/carriers and this is one of the main benefits of carriers/fighters is the flexibility and range.

The thing you can't do is true kamikaze where you send fighters in that you know will die that have no carrier that could be moved to pick them up.

**Comment by ron-murhammer** [comment]
@airwalker1 Gonna close this now. Its probably better to open these types of questions/discussions on the forum here: https://forums.triplea-game.org/
