### ISSUE TITLE
New bug in battle calculator

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#2690]
### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
See screenshot:
![screenshot from 2017-12-16 07-25-09](https://user-images.githubusercontent.com/20733860/34059240-4899dd2e-e232-11e7-9af7-8cbe4f4f4aa7.png)

### Instead of this error, what should have happened?
See attached 
![screenshot from 2017-12-16 07-19-05](https://user-images.githubusercontent.com/20733860/34059073-84d31d60-e231-11e7-8b0a-ef146ff491b6.png)
screenshot from previous versions. Build 3627 & 7386 both work correctly.

### Any additional information that may help:
Apparently it works correctly without the bombardment added.

**Comment by ssoloff** [comment]
@simon33-2 7527 had several Battle Calculator bugs.  In fact, that release was withdrawn as a stable release because of those issues.  Please try 7621, which contains the Battle Calculator fixes.

**Comment by prastle** [comment]
actually 
use .7634
all bots run that and we need stable upgraded to that if ya have time @ssoloff

**Comment by ssoloff** [comment]
@prastle Sorry, making the decision to promote a new stable release is above my pay-grade. :smile:  I looked at the QA spreadsheet and didn't see an entry for 7634.  Were we even considering that release as a new stable?

@ron-murhammer @DanVanAtta Please see @prastle's request to release a new stable.

**Comment by prastle** [comment]
all bots run it :)
but np

**Comment by simon33-2** [comment]
Build 7621 resolves this problem. Probably should have checked for a new stable first!
