### ISSUE TITLE
create developer mailing list?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#27]
Some lightweight discussions would be nice via email.
LIke for example, hey Mr xyz repo owner, I've an interesting change on this branch in my fork, could you look at and tell me what you think?

Some things don't deserve a github issue I think. What do people think, create an email distro? Probably would be a google group.

Also nice thing, for short more informational messages, it would reduce our reliance on creating issues on the more transient, developer interested only topics.

**Comment by ron-murhammer** [comment]
I believe this exists but no one uses it anymore: https://sourceforge.net/p/triplea/mailman/

**Comment by veqryn** [comment]
we could just use each other's email addresses...
i'm ok either way

**Comment by gaborbernat** [comment]
I would vote for a Google Group if we do go for mails (that way developers hopping on later can revisit earlier mails). An interesting change definitely deserves a pull request. At most it will be rejected. The issue overload can be addressed by using the labels for issues. At the moment sadly on contributors can add them (so Ron, and Veqryn), but there's a feature request for label suggestion [here](https://stackoverflow.com/questions/13829466/how-to-put-a-label-on-an-issue-in-github-if-you-are-not-a-contributor-owner); so maybe this will change eventually.

**Comment by DanVanAtta** [comment]
I like the google groups idea, benefits I see:
- we remove one more dependency away from source forge
- we get a record of the conversations (which is quite the benefit IMO)
- there is effectively no email admin work needed by anyone (so the overhead cost is correct)

**Comment by djensen47** [comment]
Most open source projects I've been involved with use Github issues with a special tag. Subscribe to all new issues here an it becomes a mailing list. 

In my opinion, there are very few of us, there is no reason to create more work and more ways for miscommunication. 

For instance, what if I add an issue and missed a discussion on the mailing list? It's just repeat of the same old thing. Also, what topics would be on the mailing list that couldn't be distilled down as an issue anyway? Finally, if a topic is "too broad" we can create an action item at the end to break up the discussion into smaller actionable issue and close the "broad" topic.

**Comment by djensen47** [comment]
> LIke for example, hey Mr xyz repo owner, I've an interesting change on this branch in my fork, could you look at and tell me what you think?

This is not how the Github community works. As a potential collaborator, I fork the repo, make my change and make a pull request. The discussion of merits or lack thereof happen in the pull request comments. Pull requests are essentially github issues.

A "better" process is, that developer files an issue/feature request, they mention they would like to make a pull request. We say, "yeah that's great" (or not). They do some work and make a pull request. The pull request has the diffs, line-by-line commenting, and an associated issue. Then we discuss if needed.

**Comment by djensen47** [comment]
> Also nice thing, for short more informational messages, it would reduce our reliance on creating issues on the more transient, developer interested only topics.

I don't understand this argument. This is what Github is for, developers. It's also for non-developers to tell developers stuff. It's very flexible and we should be having discussion developer related issues here. 

The only thing I could see is questions on how to setup a developer environment. Even then, it's an issue "How to a start developing for TripleA" would just just need to be renamed to "Update documentation regarding how to set up TripleA developer environment."

Let's stop trying to make our collaborating complicated and anticipating needs we may or may not have. I'm all for changing as needed but pre-mature optimization is usually a bad thing.

Here's what I think this discussion should be about: 
What are the different types of issue tags that we need in order to organize the types of issues, discussions, questions, and whatever else we anticipate.

**Comment by DanVanAtta** [comment]
I think you make a lot of valid points @djensen47 . Email is a bad practice almost no matter what it boils down to. Even if you want to send an email like "I'm on vacation for 2 weeks", which you would not want to send publicly, it's best to not send the email. Why, because not everyone will get it and wonder what is up. Secondly, it means nobody will take the time to make sure there is a process so you can be absent for 2 weeks. Like for example, make sure nothing depends on you since this is open source and people walk away.

Okay, so now that we are likely on the same page in terms of thinking. We have today:
- sourceforge tools
- github

Travis has been brought up as a major new cloud tool, but that will be down the road.  How to integrate or deprecate sourceforge tools are another discussion (like the tickets that exist over there, or the forum, which is pretty robust and active, more so than github issues).

So, long winded - I agree, let's focus on using github well. I'll spawn up two new issues, one will be a conversation about using the github wiki we have. Secondly will be about organizing github issues.
