### ISSUE TITLE
Use TestFX as JavaFX Testing framework

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#2710]
Testing is important, and the coverage for the current Swing UI (as well as JavaFX currently) is pretty much 0.
I found TestFX, a testing framework for JavaFX. It let's you run those tests in headless mode, and let's  you easily check if buttons have certauin labels, are visible at certain times etc.
However the documentation is very poor (although they provide javadocs): See my issue over there: https://github.com/TestFX/TestFX/issues/494 for some of the Problems I noticed, and for the changes that we'd need to apply to the travis script for this to work.

I'm interested on your opinion on this, to avoid changes you dislike (Just read my post over there which sums it all up).

**Comment by ssoloff** [comment]
@RoiEXLab I think you covered the technical issues just fine over in the TestFX/TestFX repo.  I think it's great that they support headless out-of-the-box without using `xvfb`.  That would make it easier to adopt here because we've talked about adding `xvfb` to Travis on at least two occasions, and both times it was voted down.

With that said, here's my philosophy of testing the UI:

* If you find yourself writing UI unit tests, stop and ask yourself what you're really trying to test.  90% of the time, you're just trying to test business logic that happens to be wrapped up in the UI.  In those cases, extract the logic you want to test so it's independent of the UI and the dreaded spinning up of an EDT.
* I find the remaining 10% broken down as follows:
    * About 1-2% are what I would call UI integration tests.  A good example of this in TripleA would be testing the `BackgroundTaskRunner` class.  It relies on an EDT to verify we coded it correctly to integrate with the `SwingWorker` class.  Since we disallow headed tests on Travis, it has no tests. 😞 
    One alternative in this scenario is to fake the UI dependency.  But in cases like `SwingWorker` above, you're really not gaining anything because the key aspect you want to test is the foreground/background thread interaction.  Mocking it in that case seems like a smell.
    * About 3-5% are testing non-trivial behavior in the UI itself, such as the example you cited above: ensuring the state of the UI is as expected.  There are patterns out there (e.g. _Humble Dialog_) for testing things like this without a dependency on the UI, but at the cost of an extra layer in your software stack.  With a good UI testing framework, I would be ok with these types of tests in our codebase, assuming I could choose to exclude them from local runs easily (e.g. either via a separate Gradle task or using JUnit 5 categories).
    * The remainder are usually system-level smoke tests for the most common paths through the UI.  I've found these incredibly useful in the past.  However, given how the UI of TripleA is structured, they may require heavy maintenance.  But I would love it if our Travis build at least tried to run the client and click Quit on the main menu to prove each build can at least start properly. :smile:
* If you're going to test the UI, do it right.  For example, ensuring UI component creation occurs on the EDT, etc.  In that respect, choosing a good UI testing framework is key, and TestFX looks like a good candidate.

**Comment by RoiEXLab** [comment]
@ssoloff The great thing about javafx is that components must be created on the JavaFX Application Thread, it's very strict about that.
So no need to test that.
However I had the following things in mind:
I agree that most of the logic should be extracted, however we really shouldn't create a pure logic method for creating all the tabs in the SettingsPane which we pass a function to.
So I thought about tests checking if all labelable elements have the correct font, or checking if all screens have been initialized on start.
Because the current code structure creates the GUI in a way so all UI elements are created once (set invisible) and displayed when they are needed.
This is going to result in long startup times when more and more UI componens are being added, so at some point we need to load the invisible elements asynchronously.
Not sure how well this works with TestFX though, when we actually need to load all components before testing if they are actually there.

**Comment by ssoloff** [comment]
@RoiEXLab 

> The great thing about javafx is that components must be created on the JavaFX Application Thread, it's very strict about that.
So no need to test that.

Sorry for the confusion...  I wasn't suggesting we test that components are created on the EDT.  I was noting that most Swing-related tests (including some in our codebase) don't follow this "rule," leading to sloppy tests that could fail in the future (e.g. if a L&F like Substance, which enforces EDT creation, was active).  It's good to know that JFX enforces the thread affinity requirement itself.

> So I thought about tests checking if all labelable elements have the correct font, or checking if all screens have been initialized on start.

Just noting that those kinds of things may lead to a lot of test maintenance.  I'm not saying to not do them, but just throwing out a warning that we should carefully consider what types of tests will provide value. :smile:
