### ISSUE TITLE
unix installer smaller than others 220MB, others are 275+

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#272]
The unix installer is a good 50 MB smaller than the other two installers. This is a tracking ticket to investigate why.

278 MBtriplea_macos_1.8.0.10.445.dmg
220 MBtriplea_unix_1.8.0.10.445.sh
284 MBtriplea_windows_1.8.0.10.445.exe

**Comment by gaborbernat** [comment]
Java is not bundled with the UNIX installer.

On 11/10/15, Dan Van Atta <notifications@github.com> wrote:
> The unix installer is a good 50 MB smaller than the other two installers.
> This is a tracking ticket to investigate why.
>
> 278 MBtriplea_macos_1.8.0.10.445.dmg
> 220 MBtriplea_unix_1.8.0.10.445.sh
> 284 MBtriplea_windows_1.8.0.10.445.exe
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/triplea-game/triplea/issues/272


-- 
 Bernát Gábor
Student -  Budapest University of Technology and Economics - Computer
Engineering, M.Sc. - Budapest, Hungary
System Integrator - Gravity R&D | Rock Solid Recommendations - Budapest
office | 5-7 Expo ter | H-1101 | Budapest | Hungary

**Comment by DanVanAtta** [comment]
Any specific reasoning for no JRE with the unix installer?

**Comment by DanVanAtta** [comment]
Thanks @gaborbernat for shedding light on the reason why there is such a big file difference. We have other issues open to talk about JRE bundling, so no further action items in this issue that i can see now.
