### ISSUE TITLE
Cant open selected bot

### ISSUE THREAD

**Issue by airwalker1** [triplea-game/triplea#2725]
### Any additional information that may help:

Not sure when exactly this broke, but it works fine in 7898 - You cannot open the selected bot in 7923. It chooses a different bot. For example if I want to open bot 41 - it will open bot 91 instead.

**Comment by ssoloff** [comment]
Sounds like a sorted vs. unsorted index mismatch we saw during the review of #2714.  @RoiEXLab, could you please take a look?

**Comment by RoiEXLab** [comment]
Opened #2726

**Comment by prastle** [comment]
Ya I can confirm this occurred with .7922 as well.

**Comment by ssoloff** [comment]
@airwalker1 This should be fixed in pre-release 1.9.0.0.7942 or later.  Please re-open if you still observe the problem.
