### ISSUE TITLE
One off test failure - OddsCalculatortest

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#274]
https://travis-ci.org/triplea-game/triplea/builds/90217514  failed due to an inconsiste test (the build has been restarted since):

```
games.strategy.triplea.oddsCalculator.ta.OddsCalculatorTest > testKeepOneAttackingLand FAILED
    junit.framework.AssertionFailedError at OddsCalculatorTest.java:86
509 tests completed, 1 failed, 3 skipped
:test FAILED
```

**Comment by DanVanAtta** [comment]
#115 updates this test, reduces the run counts from 2000 to 1000. That may help avoid this, but at the very least worth knowing about the potential merge conflict.

**Comment by DanVanAtta** [comment]
Another instance of this failure: https://travis-ci.org/triplea-game/triplea/builds/97143812

> games.strategy.triplea.oddsCalculator.ta.OddsCalculatorTest > testKeepOneAttackingLand FAILED
    junit.framework.AssertionFailedError at OddsCalculatorTest.java:86

**Comment by DanVanAtta** [comment]
Another failed build due to this issue:  https://travis-ci.org/DanVanAtta/triplea/builds/99346482

games.strategy.triplea.oddsCalculator.ta.OddsCalculatorTest > testNoUnitsInTerritory FAILED
    junit.framework.AssertionFailedError at OddsCalculatorTest.java:106

**Comment by DanVanAtta** [comment]
OddsCalculatorTest.java needs to be made deterministic, let's set the random seed to a specific value so we can have consistent runs.

**Comment by DanVanAtta** [comment]
```
games.strategy.triplea.oddsCalculator.ta.OddsCalculatorTest > testKeepOneAttackingLand FAILED
    junit.framework.AssertionFailedError at OddsCalculatorTest.java:86
```
https://travis-ci.org/DanVanAtta/triplea/builds/100292416

**Comment by DanVanAtta** [comment]
Again:
```
games.strategy.triplea.oddsCalculator.ta.OddsCalculatorTest > testKeepOneAttackingLand FAILED
    junit.framework.AssertionFailedError at OddsCalculatorTest.java:87
```
https://travis-ci.org/triplea-game/triplea/builds/102763204

**Comment by DanVanAtta** [comment]
games.strategy.triplea.delegate.DiceRollTest > testGetTotalOffensivePower FAILED

**Comment by DanVanAtta** [comment]
```
games.strategy.triplea.oddsCalculator.ta.OddsCalculatorTest > testKeepOneAttackingLand FAILED
    junit.framework.AssertionFailedError: expected:<0.8> but was:<0.844>
```

**Comment by ron-murhammer** [comment]
Marking as high priority and bumping this as it seems to be causing some heart burn.

**Comment by DanVanAtta** [comment]
Flaky tests were removed, closing.
