### ISSUE TITLE
Great War 4.4 No-retreate-option-bug

### ISSUE THREAD

**Issue by Leijonma** [triplea-game/triplea#2750]
Hallo Triplea!

Sorry to disturb you but...

Attatched file is a saved game of Great War 4.4 from yesterday (reconstructed today 28/12 to faulty point) that malfunctioned.

Yesterday I attacked with British fleet in Mediterranean with intent to withdraw after one round of combat. However the only retreat option showed after one round of battle was "submerge submarine".
I turned that down, had extrem bad luck within LL and lost my entire fleet and probably the game.

In the attached reconstructed game it is the same. No retreat option at all besides "Submerge submarine". You should have a retreat option in this case.

Apart from this I have noticed in several other maps that when you make an amphibious assault there is no retreat option even for non-amphibious units when all amphibious units are eliminated.

Very greatful for any help with this.

Windows 10 version 1709

Leijonma/hale

### Do you have the exact error text? Please copy/paste if so
awda
### Any additional information that may help:

[hale 1.zip](https://github.com/triplea-game/triplea/files/1590633/hale.1.zip)

**Comment by simon33-2** [comment]
Hmm, I can duplicate this with build 3627 as well as 7621.

I'm not familiar with Great War so I'm wondering if there is anything special in that map which would prevent the retreat possibilities being activated?
