### ISSUE TITLE
Install4j - 64 bit and 32 bit installer options

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#276]
A bundled JRE seems to imply we are deciding 32 bit or 64 bit CPU architecture.

Which makes sense: 
  - have three installers with a bundled 32 bit JRE
  -  or a 64 bit JR?
  -  or produce six installers, three for each OS and a 32 bit and a 64 bit installer for each

IMO: produce 6 installers and then have a link on the website for "32 bit installers" where users can see the full list of installers.

If we get complaints about download size after moving to mp3 from wav files, then I would also recommend creating a third installer per OS that is a minified DL size.

**Comment by veqryn** [comment]
i still do not like forcing people to use the bundled jre instead of their own jre...
(but besides that, i think a 32bit installer + a 64bit installer, for each OS, is probably needed)

**Comment by gaborbernat** [comment]
Why? As far as 32 vs 64 bot goes I agree.

On 11/10/15, Chris Duncan <notifications@github.com> wrote:
> i still do not like forcing people to use the bundled jre instead of their
> own jre...
> (but besides that, i think a 32bit installer + a 64bit installer, for each
> OS, is probably needed)
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/triplea-game/triplea/issues/276#issuecomment-155497861


-- 
 Bernát Gábor
Student -  Budapest University of Technology and Economics - Computer
Engineering, M.Sc. - Budapest, Hungary
System Integrator - Gravity R&D | Rock Solid Recommendations - Budapest
office | 5-7 Expo ter | H-1101 | Budapest | Hungary

**Comment by DanVanAtta** [comment]
My 2 cents: Having two installers per OS is more complicated than having one. Most people should have their own JRE, but maybe not, it's at the very least not clear if there is actual benefit to bundling. The extra download size, +25% to the total size and eventually +50% when we go to mp3 is quite significant.

On the other side, it seems like most people don't care about download speeds anymore. I've spent time living in eastern europe where a 28K connection was great to have, and I have family living in countries where they barely get better than 128K. Hence I think there is a lot of value as well in having a smaller DL. Clearly I'm a bit torn on which direction to go.

**Comment by DanVanAtta** [comment]
@gaborbernat , did you mean to type "both"? your response above doesn't make complete sense to me, not sure which suggestion option you are agreeing to.

The bundled installer really does have a drawback that it is more complicated for users, they have to select their OS and 32 or 64 bit and not just their OS. That would mean the main download page would have six different buttons. It's not a very good UX, would be best to show them just one, but we'll likely be showing three, one per OS. Also the bundled JRE's inflate the download size significantly.

My inclination is then we go without the bundled JRE. Smaller DL and fewer installation download options for our users, will make it easier on them. On the other hand when we start getting complaints about people having trouble with the application not finding a JRE installation, then we go the route of producing all 9 build artifacts. We then add a link to the website for "additional downloads" where we give the full list.

**Comment by veqryn** [comment]
How difficult would it be to, during installation, detect whether we are x86 or x64, and also detect if a JRE is installed or not (and that it is >= java 8), and download the correct JRE only if needed?

**Comment by DanVanAtta** [comment]
@veqryn Good idea, though I'm concerned the creation and maintenance of the two OS specific scripts that would launch the game and download a JRE if needed will lead to more support problems than it solves.


@all, From the source forge counts, there is overwhelming demand for the non-bundled version. Yet there is still demand for both, bundled and not bundled. I propose we then do the one time update so  automation produces all 7 installer files (non bundled and 32+64 bit bundled versions for mac and windows (6), and one more non-bundled installer for linux). Once all the types are produced, it'll be up to the website to care of the the UX.
