### ISSUE TITLE
Game Notes appearance

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#2769]
### My Operating System: 
Windows 7.64
### Engine version:
1.9.0.0.8107 (maybe earlier - I have not cared too much about the game notes during the last months)
### Map name and version:
wwII_global_1940
### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
See the game notes when selecting a map or using the menu.
### Do you have the exact error text? Please copy/paste if so
![gn0](https://user-images.githubusercontent.com/20812775/34456768-f194feae-ed9f-11e7-9cd3-1a83e13cdfde.PNG)
![gn1](https://user-images.githubusercontent.com/20812775/34456769-f1ad7506-ed9f-11e7-8da7-db8747d1c460.PNG)

### Instead of this error, what should have happened?
In substance graphit the game notes have always appeared as solid black text on white background.
This is the look using 7621:

![gn3](https://user-images.githubusercontent.com/20812775/34456869-9cd21ca6-eda1-11e7-9f4a-3d19e3c72142.PNG)

### Any additional information that may help:
Maybe it is related to a test of `Use JavaFX UI`.
After switching back to the standard UI I have noticed the issue.

**Comment by panther2** [comment]
wwII_v3 looks like this now:

![gn2](https://user-images.githubusercontent.com/20812775/34456820-c0dac388-eda0-11e7-91df-cccdc816e537.PNG)

Have I missed any "Game notes look and feel change"?

**Comment by RoiEXLab** [comment]
You missed a "Look And Feel" Update ^^
This change was "made"(we updated the look and feel triplea is using) to be compatible with Java 9.
I will look into this. Shouldn't be too difficult to fix the coloring.

**Comment by RoiEXLab** [comment]
And no, this has nothing to do with javafx.

**Comment by RoiEXLab** [comment]
Opened #2770

**Comment by RoiEXLab** [comment]
@panther2 This issue should be resolved in the latest pre-release.
Please report back if I missed a panel.

**Comment by panther2** [comment]
Thanks, I will take a look.

**Comment by ron-murhammer** [comment]
@RoiEXLab @ssoloff It appears there is a similar problem in at least one other places (Unit Help). As both the background and text appear very light so its not readable anymore. I didn't really see the substance update  that was made but appears it had a few more side effects.

**Comment by ssoloff** [comment]
> I didn't really see the substance update that was made

#2717

**Comment by ron-murhammer** [comment]
@ssoloff Ok, I'm a little interested in that it appears you are hosting a new/fixed version of the substances now?

**Comment by ssoloff** [comment]
@ron-murhammer Yeah, please see the discussion in that PR; there were other alternatives discussed.  If we continue to use Bintray, the long-term plan would be to use a TripleA-organization-owned account instead of mine.

**Comment by ron-murhammer** [comment]
@ssoloff Ok, I would like to get any dependencies into the TripleA org owned repo as otherwise if you would disappear tomorrow and take down your stuff then we'd have a broken build. And yeah it would be great to get it published somewhere more official but not sure if/how that would be possible.

**Comment by ssoloff** [comment]
@ron-murhammer 

> Ok, I would like to get any dependencies into the TripleA org owned repo

Are you ok with [this solution](https://github.com/triplea-game/triplea/pull/2717#issuecomment-353422016)?

**Comment by ron-murhammer** [comment]
@ssoloff Yeah, if it isn't hosted somewhere then I'm ok with adding it into our TripleA repo. Probably not ideal but at least then we have all the bits somewhere that is less likely to disappear :)

**Comment by ssoloff** [comment]
@ron-murhammer #2779 and #2780 have two different solutions for the Substance dependency issue.

**Comment by RoiEXLab** [comment]
@ron-murhammer Is this still an issue?

**Comment by prastle** [comment]
Yes the notes in white was fixed @RoiEXLab
