### ISSUE TITLE
Automated Build - Produce full set of installer options and deploy to github

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#277]
Install4j needs to create these 7 installers:
- [ ] windows exe installer without java JRE
- [ ] windows exe installer with 32 bit java JRE
- [ ] windows exe installer with 64 bit java JRE
- [ ] mac dmg installer without  java JRE
- [ ] mac dmg installer with 32 bit java JRE
- [ ] mac dmg installer with 64 bit java JRE
- [ ] linux shell installer without  java JRE

Then each of these items needs to be deployed to github. (update the .travis.yml file to include the names of hte additional installer files and they'll be deployed)

**Comment by gaborbernat** [comment]
@DanVanAtta you can assign this issue to me

**Comment by DanVanAtta** [comment]
closing in favor of #354. #354 is the same task, but a slightly different approach given new information
