### ISSUE TITLE
HardAI ?

### ISSUE THREAD

**Issue by pjdouillard** [triplea-game/triplea#2778]
I am revisiting TripleA since a few years ago, and the game is great.

One point though concerning the 'supposed' HardAI:  What I see is the AI is not really harder, but 'luckier' than it supposed to be.  After a few dozens games now, I can confirm stack of soldiers (Attacking at '1') from the 'HardAI' are getting '1s' 50% of the time which hose any possible fight outcome prediction.

If this intended?

**Comment by ron-murhammer** [comment]
@pjdouillard I can promise you that isn't the case. All the AIs use the same dice roller as the player does. If you play say 10 games against the AI and export the dice stats at the end by going to the top bar Menu -> Show Dice Stats then you'll see that all the nations should have pretty much the same dice stats as long as your sample size is large enough.
