### ISSUE TITLE
Use install4j "clean" upgrade feature

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#278]
See #265 for background discussion of this problem. 

Summary: Migrating to install4j instlalers has lead to the game being installed to a generic folder and not a new one specific to each game version. This means users cannot have multiple game engines,  and no longer need to update links when they update their game nor do they have clean up any old game engines (which are bundled with maps and take up significant disk space).

*Task*: Ensure we are using the install4j  "clean" upgrade option:

"If you would like to uninstall the previous installation before installing any new files, you can add the "Uninstall previous installation" action before the "Install files" action." (http://resources.ej-technologies.com/install4j/help/doc/)

*Follow up tasks for future issues*: communicate to users that the install is now going to a non-versioned folder and the update process has been simplified (no more manual updates of links and shortcuts and no more manual clean up of old game engines)

**Comment by gaborbernat** [comment]
@DanVanAtta you can assign this issue to me

**Comment by DanVanAtta** [comment]
@gaborbernat , do you know if this will keep save game files around, even if they are in now in the same folder as the game engine installation?


For example, note the 'savedGames' folder below:
```
$  ls ~/triplea
assets         dice_servers  license  readme.html  TripleA.desktop             TripleA_RuleBook.pdf
bin            doc           maps     savedGames   triplea-headless            TripleA.vmoptions
changelog.txt  icons         old      TripleA      triplea-headless.vmoptions  uninstall
```
Specifically will that folder be preserved between installs? Do you know what will happen as well for maps?

**Comment by gaborbernat** [comment]
I will try but I would assume it is kept as it is created after the install operation.

**Comment by gaborbernat** [comment]
it keeps it, only removes installed content, not what is created after.

**Comment by gaborbernat** [comment]
this may be closed.
