### ISSUE TITLE
False negative build checks  (Remove codeCov?)

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2792]
Suggestion: remove any build checks that can 'fail' with a big red mark and we merge anyways. This would start with codeCov as it can red X a build for the wrong reasons.

Discussion:
Do we get any real value from codeCov is we are not enforcing a coverage percentage?

Task:
- [ ] survey from team what value there is in CodeCov
- [ ] either remove CodeCov or fix anything  that is making it red sometimes incorrectly so that it is a solid indicator of PR health.

Desired Outcome:
- Red/Green checks on PRs are solid indicators of PR health, red checked PRs are never merged (potentially enforceable via github)

**Comment by RoiEXLab** [comment]
I personally like having the coverage report to get a feeling on how much of the diff is being covered by tests.
If there was a way to simply get rid of the build integration check without getting rid of the report, I'd be fine with that.

**Comment by ssoloff** [comment]
I agree that Codecov provides value, and it would be great to get the non-determinism out of our tests, which is causing the > 50% failure rate of the codecov/project check.  With that said, if we can simply disable codecov/project and leave codecov/pr enabled, that would probably be the best short-term solution.

But note that even if we leave codecov/pr enabled, there will be PRs that are still red but are probably safe to merge.  We talked about this a few months ago.  For example, a PR that simply renames some variables via IDE assist, but those changes are in code without any test coverage, would fail the codecov/pr check.  I believe we agreed that as long as the PR author demonstrated this was the case, the reviewer would allow it to be merged even though test coverage was below the threshold.

**Comment by DanVanAtta** [comment]
A few ways to approach this issue. For me, the decision we made should/can be reviewed. New information has come to light, the following is really annoying!  :feelsgood: 
![screenshot from 2018-01-02 22-00-25](https://user-images.githubusercontent.com/12397753/34510536-77688c10-f009-11e7-851f-7aec540bf8f8.png)

![screenshot from 2018-01-02 22-00-08](https://user-images.githubusercontent.com/12397753/34510535-774d7ac4-f009-11e7-9a88-0c5f72122b50.png)

(scrolling down, the build is okay!)

Ultimately I think this is a significant cost.


------------------------

Second, and to be blunt to convey my point: this is the CI build, it is where we enforce our project standards - a bit red X should mean something more than 'nice to have'. 

------------------------

I personally don't use codecov to check test coverage, so for me it really is a nice-to-have only. I'm of the opinion that we should do whatever it takes to disconnect the false-postiive red "X" marks from our PRS by codecov. I can be swayed, but for me I think this is a nice-to-have vs a pretty real annoyance (and a process breakdown when you get down to it, ignoring safety guards is a bad practice)

**Comment by ssoloff** [comment]
@DanVanAtta Agreed.  But, as I stated above, the root cause of the big red X in that PR was due to the test non-determinism that's affecting codecov/project:

![checks](https://user-images.githubusercontent.com/4826349/34530698-f60369e0-f07d-11e7-94d6-eb2d92a724d4.png)

codecov/patch is still providing useful information.  So, my question still stands... is it possible to disable codecov/project while leaving codecov/patch enabled?  Alternatively, instead of disabling it outright, maybe there's a way to configure it so codecov/project just provides an "informational" annotation instead of pass/fail?

<hr>

Apologies if I conveyed codecov/patch as a nice-to-have.  Quite the opposite.  We really should be enforcing test coverage in PRs as much as possible.  We too easily fall back on "too hard to test."  We'll probably not make much progress on increasing test coverage in the codebase if we don't strongly encourage each other to do so.  Having this metric in your face on each PR is one way to do that.

**Comment by DanVanAtta** [comment]
It's tough to enforce a code coverage policy:
- I've found that when someone is insistent on not writing tests, or philosophically does not belive in it, they can waste a lot of time with a series of progressing excuses about how the code is too trivial to test, or can't be tested, or not valuable to test.
- Tests written to 'placate' are generally not high quality
- much of the tripleA code base is not written to be tested. In a number of places we may need some serious refactor to be able to test well.
- some code should be thrown away and re-written, large chunks of it is dead code.

If we can agree on one as a team, document it, enforce it somehow but provide an override, then we may be able to get away with a coverage requirement. Short term it sounds like fixing the non-determism will solve the more pressing problem taht we are getting "X" on items that otherwise do pass the build.

**Comment by DanVanAtta** [comment]
@RoiEXLab @ssoloff 
this needs resolution. I'm marking as a regression as we lost build verification. 

We previously had it so 'red X' on PR check meant, do not merge.  

Here is a recent example, when viewing the merge button, you had to scroll up to see the last build result, and even then the result was behind a button click:

![scroll_up](https://user-images.githubusercontent.com/12397753/34968331-7f214d20-fa1d-11e7-83bc-0f839700daa4.png)

Clicking the 'red X', you see:
![bingo](https://user-images.githubusercontent.com/12397753/34968353-9d148d38-fa1d-11e7-9378-afc35db2bb37.png)

**Comment by DanVanAtta** [comment]
I cut an issue to turn on branch restrictions. We should very well enable a few of them, I hope also we can enable 'require all branch checks'. I'll close this issue in favor of seeing what happens in the new discussion: https://github.com/triplea-game/triplea/issues/2847

**Comment by RoiEXLab** [comment]
@DanVanAtta The problem in this particular case is that integration tests are not counted by codecov.

**Comment by DanVanAtta** [comment]
@RoiEXLab TBH, I"m not sure if coverage is a useful metric for integration tests. Integration tests have a fundamentally different goal than compared to unit tests. I very much like 'system tests' that are testing just the integration boundary between what is unit tested and what is an external system (eg: integration test for a very thin DAO, but unit test everything from there on). Without digressing too much, integration test tends to be a verification of configuration, not functionality (and often the coverage of an integration test is often very extensive)
