### ISSUE TITLE
Build automation - move assets to triplea-assets repo and integrate with the build

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#280]
See #231 for some background.

- [ ] move game assets from assets folder to repository https://github.com/triplea-game/assets 
- [ ] create a build script for that repository to bundle all the files into a zip
- [ ] update the build to download the latest zip release and extract/bundle it with the game installer 
- [ ] make sure local eclipse and gradle builds and unit tests still work

**Comment by gaborbernat** [comment]
@DanVanAtta any progress update on this?

**Comment by DanVanAtta** [comment]
No updates. I think this is relatively low priority for the moment. Assuming no extra urgency, I think I'd like to get this done after we move the 'bundled' maps out of the engine source code.

**Comment by DanVanAtta** [comment]
Let's re-tackle this issue when we look at better ways to bundle map assets. Closing for now.
