### ISSUE TITLE
Many Window Sizes Too Small With New Default Substance

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#2810]
I noticed a number of windows are too small and display with scroll bars when they shouldn't now.

Battle casualty selection example:
![image](https://user-images.githubusercontent.com/1427689/34597132-72d2ecc0-f1aa-11e7-861e-07e55aa76c89.png)

**Comment by ssoloff** [comment]
@ron-murhammer The Select Casualties window has been fixed.  For the other windows, should we just keep updating the issue description as we find them, or should a new issue be opened for each separate occurrence?

**Comment by ron-murhammer** [comment]
@ssoloff I'll close for now though I'm pretty sure I've seen a few others as well.
