### ISSUE TITLE
Error popup Swing Thread Handling

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2831]
Error message popup can cause a deadlock with the right UI conditions. Was previously disabled due to this defect: https://github.com/triplea-game/triplea/issues/2820

It's a matter of time before the problem is found in more locations before we can launch a new release this deadlock vulnerability should be remove.

**Comment by DanVanAtta** [comment]
https://github.com/triplea-game/triplea/pull/2830 would re-enable the error pop-up

**Comment by ssoloff** [comment]
Just noting that I wouldn't be surprised if we have another threading scenario similar to what was reported in #2820 lurking about.  And it may not be possible to simply switch to a quiet log message.

I also noted that scenarios like #2708 would lead to the error popup constantly being re-displayed after dismissing it.  The infinite loop scenario is a bit of an extreme case, but there are some cases where multiple `logError()` calls are made in a short amount of time (e.g. one error triggers a cascade of others).  It would be nice if, while the error popup is displayed, additional incoming errors are pumped to the existing popup so the user only has to dismiss the popup once (again, assuming the errors are all raised in a period of time shorter than the user takes to read the message and dismiss the popup).

I'm probably not explaining that well.  If I can find a reproducible scenario that demonstrates what I'm talking about, I'll post it.

**Comment by DanVanAtta** [comment]
Makes sense, good follow up, I had similar thoughts / concerns that we would see another example.

There a few questions to solve, most important- how to fix deadlock potential. For lack of better ideas, here is what I'm considering:
- have the window render early in backgrounds similar to console, keep it around and only show / hide the window instead of creating a new one
- create a custom jframe that is displayed and does not block (perhaps something in JDialog would do the trick)

There are a number of additional questions to answer regarding behavior:
- if an error dialog is visible, should users be able to still chat? 
- should dialog offer a 'save game option'?

There a number of options to choose for handling various error message scenario. To give common context, the purpose of error pop-up is to give a reasonable and not overwhelming error message to user. They are going to be wanting to know if their game is ruined, if they need to save and reload, or if they can just continue with the game.

Some potential options for behavior:
- drop any messages when an error pop-up is already visibile
- buffer messagse for X ms and then show the pop-up, suppress any further error mesasage while visible
- open a new window each time, cap the max number of windows to a value N, stop showing the window once N are visible
- always show a new window, with a max of N per T units of time, add an option to the window to "stop showing this error" to suppress it for 5 minutes.
- always show a new window, checksum the windows and count how often we have shown each error. For any given error, cap the rate at which we create new windows to N per T units of time.

**Comment by DanVanAtta** [comment]
Bug was introduced with: https://github.com/triplea-game/triplea/pull/2782, merged 19 days ago, Jan 01.

Severity of bug is critical as the game deadlocks. Impact is relatively high since it requires just one map error. We may very well still have maps with missing unit images, game would deadlocked 100% time playing those.

I'm assigning to myself, I'm actively working on a fix.
