### ISSUE TITLE
Label Changes

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2833]
Quick FYI and discussion for recent label updates.  Some changes:
- rename p0 + p1 to "production - p0" and "production p1"
- regression renamed back to 'release blocker'
- type + category merged, just now 'category.*' labels, no 'type.*:' labels.

3rd is a bit more controversial, but it was not clear that having two dimensions for labeling was that useful. It was really not clear what defined those dimensions to begin with. With the labels all blended to 'category', it may be a bit more obvious how to group things cleanly. I think it's okay for issues to get multiple category labels (but too much overlap on too many issues may mean the categories are not very well defined).

**Comment by DanVanAtta** [comment]
I also combined the 'process', 'dev and admin process' and 'admin task' labels together to one label -> 'admin task'

'ice box' got renamed to 'ice box - close and revisit later'

'category: game rules' was renamed to 'category: incorrect game rules'

'category: code' was renamed to 'category: code improvement'

**Comment by RoiEXLab** [comment]
I'm fine with those changes

**Comment by DanVanAtta** [comment]
going forward, tweaks or new labels are welcome, no big need to create an issue.

I think we had a bit too many labels, need a small overhaul to get it back to more useful.

**Comment by ssoloff** [comment]
:+1:

**Comment by ron-murhammer** [comment]
That's fine with me. If anything we still have too many different tags and many of them are rarely if ever used.
