### ISSUE TITLE
I just downloaded TA.  It won't high;ight local game for some reason.  I followed yhr you tube instruction but it took me to a different screen than the one shown on youtube.

### ISSUE THREAD

**Issue by Mikoyan21F** [triplea-game/triplea#2835]

**Comment by ZjelcoP** [comment]
Did you already download any map?
If not please try downloading one first.

**Comment by Mikoyan21F** [comment]
Thanks!

**Comment by RoiEXLab** [comment]
I assume this resolves this issue?
Please report back if something is still not working

**Comment by ssoloff** [comment]
BTW, the fact that the OP wasn't prompted to download the tutorial map was fixed in #2650, which will be in the next stable release.
