### ISSUE TITLE
What would it take to convert TripleA into a web app?

### ISSUE THREAD

**Issue by jonearley** [triplea-game/triplea#284]
Not an issue, but has this been attempted before, considered or discussed? I would be happy to collaborate with others if there is an interest in converting TripleA into a web app.

**Comment by DanVanAtta** [comment]
I don't think a web app would be very feasible. A mobile app more so maybe. I think the nail in the coffin for a web app is the large game size. If the content was not in the browsers web cache it could take a really long time to download everything, each time you play. Plus, some maps are large. Means if you pick the wrong map to play then you are waiting for a couple hundred megabytes to download.

So I think overall this would be a very difficult effort, without that much of a return. What  are the benefits you are thinking of from a web app? Perhaps there could be some low effort half way steps that could help.

For example, I've thought being able to view and chat on the lobby from a webpage would be cool and useful. For example, when waiting for someone and on a work laptop, numerous times i would have wanted to hop on lobby right quick.

**Comment by gaborbernat** [comment]
I tend to differ. I think it could work. However, I think the first part would be to modularize the current project into separate modules (AI, rules, etc). Nevertheless, it would require lot of work.

**Comment by ron-murhammer** [comment]
This would be pretty difficult. The biggest challenges would be the large image sizes we currently have. Some maps are 200MB+. I think as @DanVanAtta mentions improving the online community around the game is the way to go.

**Comment by DanVanAtta** [comment]
It came up when talking about the website that it would be good to associate tripleA map files with the game. This way a person could download a map file from a web browser and automatically have tripleA launch.

Thinking about that kind of functionality for the lobby and game staging, we could maybe:
- add a web service API to the lobby so people with a web browser could view and chat in the lobby from the triplea website
- allow users to join a tripleA staging game
- use javascript to detect if there is a file association with a 'game launcher file' and tripleA, if not we give the user a download link to install the game. While that user does not have the game installed they can not take control of any countries or factions in the game staging screen and would be dropped if the game were to be launched
- when the game is launched, each player will download a small 'game launcher file' that is dynamically generated. This then launches the game for the everyone


Beyond that, splitting the game itself into a webapp and stand-alone version I think would be a bad move. The web service API stuff ties in nicely for the relatively simple functionality of game staging and chat, but doing so for the entire game and still allowing for the stand-alone version I think will either be a gigantic undertaking or a massive/fork duplication of code. Either way not too pretty.

@jonearley, does connecting all of the lobby and game hosting parts of the game to a web app go far enough to be helpful, or don't bother?

@jonearley , Are there any other benefits from a webapp you would like to see incorporated into the game proper? Even without going full blow web app, we can certainly look at the current shortcomings and some potential options to help improve those areas.

**Comment by jonearley** [comment]
@DanVanAtta a web app for the game lobby and game hosting parts could be interesting. This reminds me of playing battlefront 3 and using their web interface to jump in and out of games. I think battlenet does this too?

Mostly, it would be nice to just pickup where I left off playing a TripleA game from anywhere I have access to a browser and the internet. 

By web app, I mean an HTML5 web app, instead of a Java applet that could also run on the web.

I think the first step would be to study the code to figure out how much the UI code is mixed in with the game logic code. If it's mostly separate, then one possible approach would be to rewrite the UI code but not the game logic. I believe you can keep using Java if you use a project like GWT (http://www.gwtproject.org/overview.html), but you would have to rewrite the UI portions into a web version. There's also Java2Script (http://j2s.sourceforge.net/).

A separate thing to study would be the multiplayer aspect. I suspect that it would be somewhat different for Java and for the web, so if the multiplayer part is mostly separate, that would make it easier.

Another thing to consider is whether you need the entire game to work in the browser, if you only need the UI portion. If it's only the UI, you can run the game logic on the server, in Java, without having to rewrite it. I believe this is what the FreeCiv project did when porting to the web: they keep the server and all the game logic on the server, but they wrote a new UI in HTML5 to run on the web. (https://en.wikipedia.org/wiki/Freeciv#Freeciv-web) I think they started in 2007 and got something working by 2010. If they were trying to port the entire game and not only its UI, it probably would've taken a lot longer.

In any case a conversion of a project like this seems like a lot of work. Freeciv-web seems to have taken 2-3 people 2-3 years. That team might be able to give you a better idea of how much work it was.

**Comment by DanVanAtta** [comment]
> "how much the UI code is mixed in with the game logic code. If it's mostly separate"

They're coupled relatively tightly. Generally that has meant the current priorities are to  clean things up and reduce code. Procedural code, unnecessary complexity and unused code are IMO the largest problems facing the code base. By that token I've been focused on trying to prune things down for the moment.

Fundamentally removing functionality and forcing the lobby hosting to be a web app is not going to be palatable to many. So the web app code would then be something that would exist in addition to what we have today. Since the focus is more on simplifying a messy code base, I don't think the effort to create the parallel functionality is worth it.

> Mostly, it would be nice to just pickup where I left off playing a TripleA game from anywhere I have access to a browser and the internet.

I think we are on the path to achieving this. There has been discussion and general agreement that storing the game with Java Serialization is not so good and we would prefer a custom text based format. If we can achieve that, and small file sizes for game saves, I think we could route requests through the lobby to access github repository space where we can host game files.

**Comment by DanVanAtta** [comment]
#306 created to capture the feature request for cloud file storage of save games.
