### ISSUE TITLE
Future of repo: triplea-maps/Project/

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2843]
I'm opening a quick issue to discuss future of triplea-maps project repo.

Quick background:
When we spun up the project maps in github, it seemed to make sense to have a repo to aggregate map problems and to collect admin scripts. It turns out to be valuable for admin scripts, but it has not been valuable for map issue aggregation.

Repo:  https://github.com/triplea-maps/Project/
Issues: https://github.com/triplea-maps/Project/issues

Problem: 
- issue queue in project repo is a bit of a graveyard
- issue queue is yet another place to report a problem, creates confusion on where to report.
- split admin attention/focus. The same people tend to manage triplea-game and also triplea-maps/project, so the two queues just split our attention to no real benefit
- README links are out of date: https://github.com/triplea-maps/Project

My suggestion:
- disable issue queue for Project repo.
- rename the repo to 'admin-scripts'
- remove from documentation any links or mention of that repo.

**Comment by prastle** [comment]
off topic
but this i cant bury buy removing bots
The following Linode(s) have now been assigned a maintenance window in which a reboot will occur. Please note that these times can change as a result of the actions mentioned above. At this time your reboot schedule in UTC is as follows:

 * 2018-01-17 5:00:00 AM UTC - TripleA-Forum
 * 2018-01-17 5:00:00 AM UTC - botserver60_GA_USA


@DanVanAtta  @RoiEXLab

**Comment by DanVanAtta** [comment]
Cloning the repo, it takes a really long to clone due to lots of binary artifacts. This makes me suggest we split the repo and create a brand new one for the map admin scripts. Would result in two repos:
- map-making-tools
- admin-scripts


Does anyone know if the map making tools have live links to them, or is it cold storage?

**Comment by DanVanAtta** [comment]
@prastle , roger, but do please create a new issue or take that up in gitter : )

**Comment by prastle** [comment]
forum will be down from linode guess we need to broadcast that

**Comment by prastle** [comment]
kk :)

**Comment by DanVanAtta** [comment]
@ssoloff, this update may be of interest to you:

I turned off the issue queue in: https://github.com/triplea-maps/Project

I also opened up two PRs to move the admin scripts:
- https://github.com/triplea-maps/Project/pull/93
- https://github.com/triplea-maps/admin_scripts/pull/1

I think next steps will be to create a new issue to decide what to do with the map tools in `Project`, once we've decided that there is nothing left in the repo to deal with.

**Comment by ssoloff** [comment]
> Does anyone know if the map making tools have live links to them, or is it cold storage?

@DanVanAtta I believe they are cold storage.  When I was digging into how the various map making tools were being used by the community, the links in various forum threads led to the archived project sites on Google Code and not to this repo (e.g. see [here](https://github.com/triplea-game/triplea/issues/1722#issuecomment-302492631)).  That's not to say some may not exist, but it seems highly unlikely.

**Comment by ssoloff** [comment]
> Cloning the repo, it takes a really long to clone due to lots of binary artifacts.

@DanVanAtta Might be another opportunity to use Git LFS, as you originally suggested with the triplea-game/assets repo (see triplea-game/triplea#2682).  However, we still haven't officially made a go or no-go decision on that yet.

**Comment by DanVanAtta** [comment]
+1 for git LFS, but I think we can begin archiving instead.

I renamed the Project repo to [map_making_tools_cold_storage](https://github.com/triplea-maps/map_making_tools_cold_storage/settings), I also marked it as 'archived' in the settings which makes it read-only.
