### ISSUE TITLE
Need a paper trail for lobby deployments

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2845]
What was deployed when? We can't answer that question, task here is to design/agree on a paper-trail process so we can answer that question.

Possible solutions:
- tracking issue where we note times of deployments
- google doc spreadsheet to note time and version deployed
- file on the server that we update, perhaps automatically by having the installation script automatically update it.

I'm leaning towards a google doc just so the visibility is public and does not require a server login.

**Comment by RoiEXLab** [comment]
👍 For Google doc

**Comment by ssoloff** [comment]
I think Google Docs is a good short-term solution.  But having a "one-button" lobby deployment process that updated something automatically would be nice.  The "something" that is updated doesn't have to be a file on the server.  For example, it could be a log file or an annotated tag in the triplea-game/lobby repo.

**Comment by DanVanAtta** [comment]
I like the tag idea.

This command:
```sudo ./setup_lobby -h 1.9.0.0.6520 3304 /home/triplea/lobby``` (from https://github.com/triplea-game/lobby)
Would presumably push tag: `1.9.0.0.6520`

I wonder about the PR author. We might want a 'lobby_bot' user with some SSH keys setup on the lobby server for the shared account.

**Comment by ssoloff** [comment]
Minor detail: We might want to consider using the GitHub API instead of a Git client for something like creating a new tag.  While working on some of the Travis scripts, I found it to be much cleaner than using a Git client in the cases where we don't need to clone the repo (even shallowly), which this case appears to be.

**Comment by prastle** [comment]
@DanVanAtta Ya google docs should be fine.

**Comment by DanVanAtta** [comment]
This is completed with the infrastructure project! 

Version updates will be performed with this file: https://github.com/triplea-game/infrastructure/blob/master/roles/host_control.sh, any changes to that file are tracked in version control and will give us the desired audit trail of which changes happened on the servers.

Tagging: @RoiEXLab  @ron-murhammer @ssoloff @prastle, it's important to know that our audit trail for production server deployments is in the git history of the infrastructure project.
