### ISSUE TITLE
What to do with MapMakingTools in triplea-maps/Project?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2846]
What to do with the files in: https://github.com/triplea-maps/Project/tree/master/MapMakingTools?

The README.md should get taken care of as part of map maker documentation consolidation: https://forums.triplea-game.org/topic/501/need-feedback-map-maker-documentation-where-to-consolidate. Notably the file/contents are going to be replaced by something else.

Otherwise, we have hex tesselated and two map makers apps. I don't think either of these are available for in-game download, and the map creators I think there are really old. Is there anything that references or uses these applications anywhere (https://github.com/triplea-maps/Project/tree/master/MapMakingTools)?

**Comment by ssoloff** [comment]
Just copying my comment from [#2843](https://github.com/triplea-game/triplea/issues/2843#issuecomment-357827072) because it's related to this issue:

> > Does anyone know if the map making tools have live links to them, or is it cold storage?
>
> @DanVanAtta I believe they are cold storage.  When I was digging into how the various map making tools were being used by the community, the links in various forum threads led to the archived project sites on Google Code and not to this repo (e.g. see [here](https://github.com/triplea-game/triplea/issues/1722#issuecomment-302492631)).  That's not to say some may not exist, but it seems highly unlikely.

**Comment by DanVanAtta** [comment]
The content is now dropped, one fewer copies.
