### ISSUE TITLE
make master a protected branch (and require build checks)

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2847]
@ron-murhammer Github originally did not have these options, but in last two years they added options to disable force push and  require all build checks to pass and at least one reviewer. this captures our PR policy almost perfectly.

After you add 'master' as a protected branch, the configuration needed would look like this:
![policy](https://user-images.githubusercontent.com/12397753/34968595-e39cfa8c-fa1e-11e7-9a3f-7889b4e7da73.png)

For now all options except require build checks can be selected. I think it would be useful to have the permissions in github match our PR policy. I also think it would make our lives easier to require all build checks to pass. That would mean dropping code coverage plugin or disabling it from build checks (which may be in setings, but I think only @ron-murhammer  and @veqryn would have visiblity into that, already being discussed in: https://github.com/triplea-game/triplea/issues/2792).

**Comment by veqryn** [comment]
I like this and have instituted this on some of my work projects.
You can also force the 'merge' button to actually be a rebase-then-merge, which is nice for making the history easier to follow (I put this on all my projects).

**Comment by DanVanAtta** [comment]
@RoiEXLab @ssoloff , please give input if you would on above questions, build check requirements on when 'merge' button would be enabled (turns out we can add some options in git, we have none enabled right now -> meaning anyone with write access has force push/push access)

**Comment by RoiEXLab** [comment]
@DanVanAtta 
> After that we should discuss if we want to turn on the requirement for one approval (we are a pretty good about this, maybe we do not want to disallow the lone-wolf revert merge? On the other hand we may still want to require all merges to need at least one approve).

No objections on that. 

> Last topic would be whether we want to enable the build check option, meaning all build checks would have to pass to allow merge.

As mentioned earlier I have no objections on removing both codecov build checks, as long as the report is still being created.
I believe keeping one of those checks will sooner or later run into a false positive blocking a PR from being merged.

**Comment by ssoloff** [comment]
@DanVanAtta 

> Making master a protected branch

No objection.

> turn on the requirement for one approval

As you noted, I think all committers have been pretty responsible thus far with the use of self-merges.  So, at this time, I don't think it's necessary.  But, if the majority of the team thinks otherwise, I'm not going to put up any resistance to it. :smile:

> build check option

Probably a good idea to prevent merges when Travis is failing (although the two extended Travis outages this month have been quite annoying).  If it's an all-or-none thing (i.e. you can't select which build checks are required to be green), then go ahead and remove the Codecov checks (but as @RoiEXLab said, let's leave the coverage report upload in the build script).  If the Codecov checks can be left as "informational only," that might be ideal.

**Comment by ron-murhammer** [comment]
If everyone feels strongly about this being a beneficial step then I'm open to it. But requiring an approval for a 1 line fix seems like overkill to me and we haven't really had any issues with self-merges. I'm also a little hesitant about requiring build to be green given all the Travis issues we've had recently as @ssoloff mentions.

**Comment by ron-murhammer** [comment]
I've enabled master branch protection. Probably be good to have each dev vote/weigh in on:
1. Require review
2. Require status checks

**Comment by ssoloff** [comment]
My full answers are [here](https://github.com/triplea-game/triplea/issues/2847#issuecomment-358357433).  Without additional information, my summary is

1. :-1:
2. :+1: (only for Travis; disable Codecov status if there is no such thing as "informational")

**Comment by RoiEXLab** [comment]
@ron-murhammer 
1. 🤷‍♂️ 
2. 👍 (same opinion as @ssoloff )

**Comment by DanVanAtta** [comment]
Rather than having a written policy that we informally enforce, I see value in having it be automatically enforced so we are very conscious when we bypass it, to avoid the documentation, and to avoid mistakes when maybe we thought the build was run but it actually failed or has not yet completed.

Sounds like there is concensus on requiring the build checks to pass. I support that. Travis has not had too many problems, I suggest if we see travis outages we can pretty easily disable the build requirement check temporarily. We do have bigger problems if we can stop relying on travis to build the software, so staying in state of ignoring travis is very severe.

For requiring reviewer checks, It's not a problem anymore in practice both ways, getting a review or requiring a review. So I don't think it would change much from that perspective. But, something we really shoudl consider, if we require one review - we could pass out write permissions almost like candy. With write permissions, but not allowed to merge to master without a PR with an approval, it's very difficult to do anything of lasting damage. Meanwhile it's useful to have people with write permissions to help manage the labelling of incoming issues. This is something to consider

**Comment by DanVanAtta** [comment]
@ron-murhammer there seems to be consensus on adding requirement for build check (we can disable temporarily if travis is having issues).

@ron-murhammer  @RoiEXLab @ssoloff , please re-consider requirement for review in light that it could let us give write permissions more easily, which could in turn help with project maintenance tasks like keeping our issue labelling up to date.

**Comment by RoiEXLab** [comment]
@DanVanAtta I'm fine with either decision, but I don't think it'll be worth giving someone write access just to be able to organize issues better.

**Comment by DanVanAtta** [comment]
thanks for feedback, I'm pretty inclined to say let's enable build checks to increase the value of build checks - but there is not much value in requiring review at the moment, so just as well to skip it.

**Comment by ssoloff** [comment]
@DanVanAtta Even with the disseminating write permissions argument, I'm still leaning towards not requiring a review at this time given how the current team dynamics are working.  But I'm not militant about that view, and I don't think it would affect my personal workflow either way since I rarely self-merge.  So consider me a soft "no review required." :smile:

**Comment by DanVanAtta** [comment]
Not being able to label issues was an impediment for QA, average QA joe can't categorize the issues they find, and they can't pro-actively note when something they find is a blocker vs something that can be fixed later.   You also can't assign issues without write, and we cannot get a map admin to own the map list without involving devs.


I'm not necessarily advocating for the review requirement, but it is good for us to really understand the trade offs we are making. I suggest we revisit the review requirement later if it would seem useful to change things.

Otherwise I think next step is with @ron-murhammer :
- please enable requirement for passing build checks, see if codecov can be excluded or if it would need to be disabled entirely

**Comment by ron-murhammer** [comment]
I've made travis passing a requirement to merge now and was able to choose just that and ignore the codecov ones. I think for now, let's stick with just that. We can reconsider adding required reviews in the future.

**Comment by DanVanAtta** [comment]
Thanks @ron-murhammer , looks to be working as intended:


![working](https://user-images.githubusercontent.com/12397753/35205798-d13c17a6-feec-11e7-9779-9c9afb535af0.png)
