### ISSUE TITLE
Change project structure - use sub-projects

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2848]
I propose we re-organize the project files into a few sub-projects. I think we'll need at least:
- common
- client
- lobby

We may also want:
- bot
- dice-server

TBD in the future we may want to split client and map making tools.

### Benefits

- We get a cleaner code separation. This has a number of benefits into itself. Example, currently it can get very confused when something is calling `ClientLogger`, and we do so incorrectly from a server context. By splitting the code bases out it'll be easier to know which code has access to which module.

- Smaller distro size, by splitting dependencies we can reduce the number of non-essential dependencies in each artifact.

- Build speed, we can elect to do a sub-project build, by avoiding the full project build we get a slightly faster build.

### Cons

- build script complexity. This should largely be one-time cost rather than on-going (the additional complexity should be mostly if not completely handled behind the scenes)

**Comment by ssoloff** [comment]
:+1: for modularity.

**Comment by ron-murhammer** [comment]
Agree though I think we probably need to focus on package organization first to group the code into logic chunks before breaking into separate modules.

**Comment by RoiEXLab** [comment]
@ron-murhammer Right, I wanted to bring this point up as well.
The first goal should be to remove the `triplea` part of the packages, so `games.strategy.triplea.util` and `games.strategy.util` for example would become the same package etc.
Or just completely overhaul the complete package structure as a whole.

**Comment by ron-murhammer** [comment]
@RoiEXLab Exactly. Once we have the package structure in a good place then breaking things into a few separate projects/modules should be easy.

**Comment by DanVanAtta** [comment]
When splitting project up, the packages do not need to change and it's backward compatible. I suspect it'll also be more clear what a better package structure would be once we see how much stuff is in 'common' vs specific to client, lobby, or bots.

**Comment by DanVanAtta** [comment]
I'm working on this, I plan to start with a sub-module that works the same as the single module project. That will give us a jumping off point for splitting off or adding new sub-projects

**Comment by DanVanAtta** [comment]
packages can be moved between sub-projects and maintain compatibility, though for sub-projects there are a few questions to explore, namely what we would want for sub-projects. I suspect we'd want to try to line up one executable or build artifact per sub-project. (So lobby in its own, bots in another, game client in another).

To get there I think we'll want to do it incrementally, each sub-project at a time - all at once is a lot of things to change. A first increment could be to define the sub-projects and move just the main method to each one only (one class). Then it would be an ongoing project to migrate code out of the 'common'

**Comment by DanVanAtta** [comment]
> @RoiEXLab Exactly. Once we have the package structure in a good place then breaking things into a few separate projects/modules should be easy.

Yes, but it does not have to be difficult now, and secondly moving packages around does not necessarily make sub-projects that much easier. I'm also concerned that package restructure is a big open ended task that is not backwards compatible. Meanwhile, sub-projects can be done incrementally, would only help the re-packaging project effort, and would enable us to do things that simple package restructure cannot. Most notably we can get a split of library dependencies. This is helpful for a number of reasons, one of which is smaller game download size. So I just would not pin the two projects on each other, their benefits are mostly mutually exclusive and they are not as closely related as one would think.

**Comment by DanVanAtta** [comment]
There is a PR open to start down this path: https://github.com/triplea-game/triplea/pull/2920

For now, closing this issue to consolidate  to PR #2920
