### ISSUE TITLE
Stats Panel Glitch

### ISSUE THREAD

**Issue by General-Dru-Zod** [triplea-game/triplea#2855]
### My Operating System:
windows 10

### Engine version:
.7753 to .8352
### Map name and version:
Bad-Ass_4-Nation_FFA v.1.6.0.20
### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Just load game.
### Do you have the exact error text? Please copy/paste if so
No error text. The problem is the stats panel is listing "Envoy_I" and "Envoy_II" twice. I haven't noticed any other functional issues as pertaining to this. So it looks like a GUI glitch. 
### Instead of this error, what should have happened?
Should list the Envoy_I.II,III once each.
### Any additional information that may help:
I went back to check were the glitch began, The last release that loads it correctly is .7695, so somewhere between that and .7753 the glitch appeared.

I use the Envoy_I,II,III only to get the functionality that follows the logic rules of my diplomatic structure. They are not truly nations, just a means of getting an immediate real time feedback to use in my conditions.

I am attaching the link to the game and a image displaying the glitch.

https://www.sendspace.com/file/bwke05

[stats.panel.glitch_7753.zip](https://github.com/triplea-game/triplea/files/1636228/stats.panel.glitch_7753.zip)

Note, there are 2 versions of the game, it is same for both. However the TS (territory selection) version is still very incomplete.

**Comment by General-Dru-Zod** [comment]
Actually there is one other possible GUI glitch regarding Envoy_I, Envoy_II, and Envoy_III. It is related to their roundel images that are shown during diplomacy phases. The order (next to political actions) of the roundel images is not consistent. 

I will list the order from assumption all Envoy roundels should be on right side. However, I don't really know if this is a correct assumption, since I don't know exactly what the roundel order is truly based on.

During British diplomacy phase Envoy_I and Envoy_II roundels are on left side.

During Germans diplomacy phase  Envoy_I, Envoy_II, Envoy_III roundels are all on left side.

During Japanese diplomacy phase Envoy_III is on left side.

During Russian diplomacy phase Envoy_III is on left side.

Note these roundels were always out of order in every version. But it didn't seem like a big deal. 

Also note the Envoy order from top to bottom is coded was coded with that pattern so that inconsistency is ok.

Ok so the above may not be relevant to the stats panel glitch, but here it is anyways.

**Comment by ssoloff** [comment]
@General-Dru-Zod Since the primary issue you reported here was addressed by #2961, do you want to open a new issue for the out-of-order roundel images?  If so, could you please provide a few screenshots that demonstrate that problem?

**Comment by General-Dru-Zod** [comment]
So this issues primary complaint is resolved via #2961. Only the inconsistent roundels remains, but that is probably something to do with how it organizes the roundels to begin with. Its been a while since I coded that portion. I don't recall exactly what I figured out back then. But was mostly, alphabetical order of the relationships themselves determined the grouping of political actions. But once I used the Envoys that grouping got screwy as the order of roundels got inconsistent. But testing suggests its still functional.

**Comment by General-Dru-Zod** [comment]
So shall I open a new then?

**Comment by ssoloff** [comment]
@General-Dru-Zod :+1: Please do.  It could be as simple as we're using unordered containers for these things, which would explain the non-determinism of the display at different phases of the game.

**Comment by General-Dru-Zod** [comment]
Here are 2 shots of British diplomacy phase. Note the Envoy roundels are listed first for all political actions with Germans. And roundels order are switched for all political actions with Japanese and Russians. If you want I can provide shots of all nations phases. I did list the pattern above as well.
[Bad-Ass_4_Nation_FFA_roundels.for british.zip](https://github.com/triplea-game/triplea/files/1709878/Bad-Ass_4_Nation_FFA_roundels.for.british.zip)

**Comment by General-Dru-Zod** [comment]
Ok you can close this one. I opened a new for the roundels, #2966.
