### ISSUE TITLE
Making TripleA Easier for New Users

### ISSUE THREAD

**Issue by beelee1** [triplea-game/triplea#2867]
Sorry if this is the wrong place for this.

When someone for the first time makes it to triplea forum there should be a big button for new player. He/she can then hit info or new game. New game should give the new member a AI Button where they can play against the AI or go on to normal game play.

Obviously needs game choice specifics and w/e.

Basically make it as simple as possible : )

appreciate what all you guys do here : )

**Comment by DanVanAtta** [comment]
@beelee1  I could see there being value in a having a "New Players Start Here" category. We already have a lot of that documentation existing today: http://triplea-game.org/help/
I suspect it would be better moved to forum.

We do need to avoid a few potential problems/pitfalls:
- duplicative documentation
- documentation that is hard to keep up to date

If we consolidate documentation to the forums we'll have perhaps finally solved the duplication problem. How to keep up to date perhaps we'll just have to do one day at a time.

@prastle I think it's pretty clear we've a task here to move everything in: http://triplea-game.org/help/ (https://github.com/triplea-game/triplea-game.github.io/tree/master/help), to a new forums category

**Comment by beelee1** [comment]
thanks for the reply Dan
I still have trouble navigating Git. But I'm not giving up : ) Hope I'm not too annoying.

Yea forum seems best place for most things unless it's you smart guys crunching stuff out.

**Comment by Heppisorus** [comment]
This idea certainly has merit.

**Comment by prastle** [comment]
Yup @DanVanAtta  I think it is a great idea!

**Comment by DanVanAtta** [comment]
It's about done, website will soon redirect 'help & rules' directly to form: https://github.com/triplea-game/triplea-game.github.io/pull/288, and we've new topics for the help content that was migrated: https://forums.triplea-game.org/category/10/help-questions
