### ISSUE TITLE
Remove legacy WeakAI

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2881]
I can't think of a good reason to keep WeakAI around. It's a lot of code we maintain that can simply be deleted and would then help further refactoring. Task here would be to remove the weak AI. I'm curious if there are any strong objections, overall I think ProAI is always better (weak AI is pretty horrible as an AI player).

**Comment by ron-murhammer** [comment]
@DanVanAtta I'd like to keep Weak AI until we can make Fast AI run faster on large maps.

**Comment by beelee1** [comment]
I remember on the old forum a discussion where some liked the option of making a AI player deliberately weak as opposed to the other AI's. 

Maybe that can be obtained by the new features since then ?
