### ISSUE TITLE
Dev documentation is getting a bit behind, where to host, and needs refresh!

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2887]
Goal: dev setup, how to build, run, test, and package are all written down so anyone can verify and follow it (no tribal knowledge), ideally fully automated with a one-touch (gradle) script.

Question 1: Should we move the dev documentation back to the main project README?
 https://github.com/triplea-game/triplea/blob/master/README.md
Currently we link to it from the bottom of the project readme.

Question 2: How do we better organize/cleanup the documentation?  Would maybe fewer pages but better organized help? Should it be merged to one page?

A Problem/Task:
- we've some gaps in the developer setup. In specific I don't think we have anything about DB setup for integration tests or how to package with install4j. How to do JavaFX development would be good to include as we'll need to know how to use tools to manage/generate the FXML.

**Comment by ssoloff** [comment]
> Question 1

I think there's a bit much there to cram onto the top-level README.  In fact, I think the dev doc content on top-level README should be a relatively straightforward blurb of text and link to the dev docs folder.  The other two links currently there are somewhat in the weeds for a casual user visiting the project, and we should consider moving them to the dev docs README.

> Question 2

Agreed that it's probably split into too many files.  My gut feeling is there's too much information for one page, but that probably won't be clear to me until we actually start trying to consolidate the information.

We should probably start with an outline.  As we fill in the outline, it should be obvious if a single page or multiple pages are appropriate.

> I don't think we have anything about DB setup for integration tests

Yes, I've been meaning to add a link to https://github.com/triplea-game/triplea/blob/master/.docker/README.md from the dev decs.

> how to package with install4j

Do you mean running the Gradle `release` task?  We probably need a small table of the most commonly run Gradle tasks in place of the two "useful" tasks we currently have listed.

We should also briefly (no more than one paragraph) document use of the install4j IDE for editing the installer script.
