### ISSUE TITLE
forums documentation needs 'how to manually install maps'

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2888]
I'm migrating help content from website to forums, this is  a placeholder/remind of something to update and migrate.

Current and hopefully soon to be old documentation on how to manually map install:

```
## Manual Map Installation

Manual installation of maps can be accomplished by moving them to the downloaded maps folder, which can be found at `~/Documents/triplea/downloadedMaps`. You do not need to unzip it if the zip file is working properly. If you have issues, try unzipping it.
```

**Comment by ssoloff** [comment]
> how to manually map install

Just noting that this procedure needs to be updated.  It's missing the step where the unzipped map folder needs to be renamed to remove the _-master_ suffix.

**Comment by DanVanAtta** [comment]
it's also missing the 'direct clone' case, can clone a map in the downloads folder and it'll get picked up. Would be great if we simplified map loading one day as well.

**Comment by prastle** [comment]
I have always just rewritten the name with no master and never needed to unzip.  The only downside is it doesn't rec as needing an update like an installed map from repo for an update.  Just my Noob 2 cents worth.

**Comment by Cernelius** [comment]
Off topic, but related, and nevermind if I'm missing something related lately, but I believe it was much easier to explain back then when there was a button to open your "maps" folder, and all you needed to say was to open TripleA, click on that button and put the zip in that folder, that the button opened.
I know that feature has been removed for some technical reasons I don't understand, but I still suggest having it.

**Comment by DanVanAtta** [comment]
Closing, questionable how much this is actively needed.
