### ISSUE TITLE
unable to open saved game

### ISSUE THREAD

**Issue by justbleh** [triplea-game/triplea#2894]
I was playing a game with my wife, she saved it and when I went to open it I received an error message.
[jennmordorjohnorcs.zip](https://github.com/triplea-game/triplea/files/1657929/jennmordorjohnorcs.zip)

**Comment by RoiEXLab** [comment]
@justbleh Looks like your savegame is corrupted
The savegame you attachmed is completely blank (i.e. an empty file).
I once had a similar problem due to a power loss while I was working on my PC.
ANy chence something similar happened?

**Comment by justbleh** [comment]
yes, my wife just said that the computer shut down right after she saved it.  Is there any way to recover a previous version of the saved game? I tried restore a previous version from my the folder with my saved games but it said there were none, anything I am not thinking of?

**Comment by RoiEXLab** [comment]
@justbleh Unfortunately I don't think so. 
If you remember most of the units positions etc. you might be able to recreate the scenario using the edit mode, but otherwise there's not really much we can do. 

Closing this issue as there's nothing we can do about it.

**Comment by justbleh** [comment]
k, thanks

**Comment by RoiEXLab** [comment]
What could work with some luck is a file recovery tool to try to recover an autosave from the autosave folder (not sure if this was the folder you were talking about), in case it got deleted as well.

**Comment by prastle** [comment]
@justbleh  the newer engine takes a save every movement.  It's is possible you have a save file in the auto save folder if you have a recent engine.  This will save the previous last movement she made.  Check the last move time date stamp in the auto save folder if you have one.  Just a thought.

**Comment by RoiEXLab** [comment]
The default savegame folder should be located at `C:\Users\<Username>\triplea` where `<Username>` is the username of the current user.

**Comment by prastle** [comment]
LOL @RoiEXLab  I guess we typed at the same time 👍

**Comment by justbleh** [comment]
We all had the same idea at the same time! I just got back on to type that it was saved in the recent auto-saved subfolder.
Thanks again!
