### ISSUE TITLE
Map Feedback Doesn't Work

### ISSUE THREAD

**Issue by beelee1** [triplea-game/triplea#2896]
### Do you have the exact error text? Please copy/paste if so

![screenshot from 2018-01-23 17-27-36](https://user-images.githubusercontent.com/24382682/35308672-47b22362-006e-11e8-8645-cdb1529aafe8.png)

### Any additional information that may help: Mentioned at the triplea site as well:

[https://forums.triplea-game.org/topic/529/how-to-give-map-feedback](url)

Hmm...don't no why my links don't work on here. Keep getting 404 when i check it. Anyway : )

**Comment by ron-murhammer** [comment]
@beelee1 I'm not sure it ever worked.

@DanVanAtta I believe he is referring to the Map Feedback button in the download maps area. Was that ever wired up?

**Comment by prastle** [comment]
I think it also used to be in the help section in lobby as well which has been removed
the real ? is where did @beelee1 find it?

**Comment by prastle** [comment]
try this link
https://forums.triplea-game.org/topic/529/how-to-give-map-feedback

**Comment by prastle** [comment]
I would also like to clarify that it has never worked for me thus just went direct to GitHub.
Sadly after  a new release every 4 hrs for months i don't know when ? It became broken or if it ever worked.  :)

**Comment by beelee1** [comment]
@prastle it just shows up on the map dl thingy for me. Isn't that the same for all ?

**Comment by prastle** [comment]
yes ty @beelee1  but it also used to be in the help section but yes broken for all to the best of my knowledge

**Comment by beelee1** [comment]
@prastle ok misunderstood : )

would be cool if it worked though : )

**Comment by ssoloff** [comment]
It looks like the URL pattern the code is searching for is still based on the old convention of issuing map releases.  Now that we link to downloading the latest map from the `master` branch, it's broken.  Looks like a simple fix; I'll submit a PR shortly.

Note that some of the map repos have their issue tracker disabled (e.g. 270bc_variants).  This will prevent the Give Map Feedback command from working no matter how we fix it because GitHub will respond with a 404.

**Comment by ssoloff** [comment]
@beelee1 This should be fixed in pre-release 1.9.0.0.8479.  Please reopen if you still experience the problem.

**Comment by prastle** [comment]
great stuff guys @beelee1  @ron-murhammer  @ssoloff  can we add @beelee1  as a tester :) 
np here

**Comment by beelee1** [comment]
heh heh fixed = good : ) Thought it got canceled because i couldn't find it. Then i remembered to check closed :)

**Comment by DanVanAtta** [comment]
We may want to remove the feature or redirect it. How map makers can get feedback is a good question. It was suggested to have a forum post per map, at the time it was hoped we would do per-map issue tracking. That seems to have not worked out very well in practice.

1. In short I suggest we remove the 'map feedback button':
 - it's low value, not used very much, few map issues have been created
 - completely broken for some time and only now we have  a bug report, it's evidence that it's not used much. Even after fix, the featurew ill be partially broken as pointed out not all maps have issue.

2. Make decision if we want to disable map 'issues' in all map repos, force communication to be done in triple-game/issues, or forums. In general we've been moving to that direction.

**Comment by prastle** [comment]
to be blunt has it ever gotten you an answer? Has it ever worked? myself I agree completely but I don't know what you guys have ever seen from it..

**Comment by DanVanAtta** [comment]
I'm pretty convinced the right fix is to actually remove the feature. It was a "cool idea", but like many ultimately it's one more thing to distract from a users main goal, and we don't really want map repo's with issue queues.

I'm re-open'ing, discuss if removal is right option instead of fixing the feature.

**Comment by DanVanAtta** [comment]
Second thought, why tangle a bug report with that discussion, I opened: https://github.com/triplea-game/triplea/issues/2912 to discuss whether we should keep the map feedback feature at all (re-closing)
