### ISSUE TITLE
fighter doesn't fight

### ISSUE THREAD

**Issue by limo49** [triplea-game/triplea#2904]
[anz19.zip](https://github.com/triplea-game/triplea/files/1665772/anz19.zip)

**My Operating System:** WIndows 10
**Engine version:** 1.9.0.0.7621
**Map name and version:** World War II Global 1940 2nd Edition 3.9

**Can you describe how to trigger the error?**
- open savegame
- start local game
- go to French combat movement phase
- attack Greater Southern Germany from Germany with 2 inf + 1 ftr

you will see that no die is thrown for the French airplane

**Instead of this error, what should have happened?**
3 dice should be thrown for the French units (2inf + 1 ftr)

**Comment by beelee1** [comment]
Hi limo49
tried loading your save but it wouldn't work. Still says "zip" as opposed to the other saves. I think triplea git doesn't do zips for some reason so might want to repost the save in a different way.

Someone who knows will probably respond

**Comment by limo49** [comment]
I tried the link and it saves a correct zip with a tsvg inside...

**Comment by beelee1** [comment]
yea the problem may be the zip. Don't think they work with triplea here. I can't open it. Lets ask @prastle He's pretty smart : )

**Comment by beelee1** [comment]
got it to load. had to hit open with other applications, I think : ) See if i can get it on here
/home/greg/triplea/savedGames/anz19.tsvg

**Comment by ssoloff** [comment]
I dropped into the debugger to see why the fighter wasn't participating in the attack.  I noticed that its `m_transportedBy` property is set to "carrier owned by Americans," and it ends up being removed from the battle because it is considered a non-combatant.  So this appears to be the same problem reported in #2630.  However, that bug was fixed in 7621. 😕 

@limo49 Did you happen to start this game in a version prior to 7621 and then upgrade to 7621 sometime after transporting the French fighter on a USA carrier?

**Comment by ssoloff** [comment]
@limo49 Regardless of which version you were using, if you want to continue your game, you can workaround the problem by using edit mode to delete the French fighter in Germany and then recreating it before combat movement.  That will clear the property that is preventing the fighter from participating in the battle.

**Comment by beelee1** [comment]
`Regardless of which version you were using, if you want to continue your game, you can workaround the problem by using edit mode to delete the French fighter in Germany and then recreating it before combat movement. That will clear the property that is preventing the fighter from participating in the battle.`

Good advice here : ) Rd 19 and all

**Comment by ron-murhammer** [comment]
@ssoloff Yeah, I'm guessing the game was started with an older version otherwise the bug still exists some how...  Closing this for now.

**Comment by beelee1** [comment]
hey @ron-murhammer  will limo still be able to see solution to game in case he isn't familiar with git ? if it's closed it doesn't show up.

Or well...idk maybe but...just a thought

**Comment by ron-murhammer** [comment]
It'll still show up. He should get an email with our responses and if he clicks the link he'll still get to here and see it.

**Comment by beelee1** [comment]
cool

**Comment by limo49** [comment]
_@limo49 Did you happen to start this game in a version prior to 7621 and then upgrade to 7621 sometime after transporting the French fighter on a USA carrier?_

_you can workaround the problem by using edit mode to delete the French fighter in Germany and then recreating it before combat movement_

I confirm all you wrote
Thank you very much
