### ISSUE TITLE
Travis broken due to exceeding GitHub LFS quota

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/triplea#2921]
I'm not sure how, but we've either exceeded the 1 GiB storage quota or 1 GiB bandwidth quota imposed by GitHub LFS.  Travis builds are failing with this error:

```
Error downloading object: src/main/resources/org/triplea/client/ui/javafx/images/background.png (fc82f76): Smudge error: Error downloading src/main/resources/org/triplea/client/ui/javafx/images/background.png (fc82f760ee88fbd0ee86ebbe58c7bf263601ab882c12d6cc1806d554fafe354d): batch response: This repository is over its data quota. Purchase more data packs to restore access.
```

I'm going to guess we're exceeding the bandwidth quota due to the frequency of our Travis builds.

Relevant link: https://help.github.com/articles/about-storage-and-bandwidth-usage/

**Comment by RoiEXLab** [comment]
@ron-murhammer Could you check?
https://help.github.com/articles/viewing-storage-and-bandwidth-usage-for-an-organization/

**Comment by prastle** [comment]
Noob ? but can we just buy more space?  Just a ? @RoiEXLab

**Comment by ssoloff** [comment]
Just was able to look at this further now...  As the docs say, it affects forks, too.  The Travis build on my fork just failed for the same reason.

I'm going to create a test branch with LFS disabled and see if that is at least a possible solution.

**Comment by prastle** [comment]
Off topic but I need the Lobby yaml update for the new TOC when ya guys get it working please.
https://forums.triplea-game.org/topic/545/revised-tournament-of-champions-season-12-toc-12

**Comment by ssoloff** [comment]
Merge now requires a green Travis build, no?  I think you need admin rights to bypass.

**Comment by RoiEXLab** [comment]
Oh right. 
Forgot about that @ssoloff

**Comment by ssoloff** [comment]
@RoiEXLab It figures something like this would happen right after we enabled all the new constraints. :smile:

**Comment by ssoloff** [comment]
I followed [this procedure](https://stackoverflow.com/a/41961459/3900879), and everything seems to be working on that branch.  I cloned the test branch into a separate folder and confirmed it retrieved the images from Git and not LFS.

@DanVanAtta @RoiEXLab @ron-murhammer Do we want to disable LFS now so the build isn't blocked?

**Comment by RoiEXLab** [comment]
@ssoloff No objections on not using Git LFS all together.

**Comment by ssoloff** [comment]
I submitted #2922 to disable LFS in this repo and move the affected images from LFS back into Git.  Unfortunately the build still fails for reasons described in the PR, so @ron-murhammer (or @DanVanAtta?) will have to merge it.  I'm going to be out for a few hours so 🤞 it works as expected when merged.

My bad for not realizing we would exhaust the monthly bandwidth quota in ~7 days. 😞

**Comment by ssoloff** [comment]
Also, this probably raises the priority of removing large objects from the repo (#2890).
