### ISSUE TITLE
Travis Checkstyle threshold update script broken

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/triplea#2931]
The _update_checkstyle_thresholds_ script run at the end of a successful Travis build appears to have broken approximately 11 days ago.  It looks like it's due to marking `master` as a protected branch:

```
$ ./.travis/update_checkstyle_thresholds
Checking if Checkstyle thresholds should be updated for this build...
Updating Checkstyle thresholds...
Checking for changes to 'gradle.properties'...
  ...changes detected.
Pushing 'gradle.properties' changes to 'triplea-game/triplea:master'...
{
  "message": "Could not update file: Required status check \"continuous-integration/travis-ci\" is expected.",
  "documentation_url": "https://help.github.com/articles/about-protected-branches"
}
```

Not sure if there's a way to keep the script working in its current state with `master` protected.  The only alternative I can think of at the moment is to modify the script to open a new PR, which would have to be merged manually.

**Comment by DanVanAtta** [comment]
Options:
- do merge via webservice API (if even possible)
- remove checkstyle rules to 'zero' them out. Add them back in when we can also fix and keep them at zero too.


Zero'ing out checkstyle rules would help in some ways and is tempting, but it does seem easiest to remove the protected branch. Though, if we remove that we also remove build check too. For now I suspect those are reasonable enough casualties until we can figure something else out.

@ron-murhammer do you agree? If so the request here would be to remove the protected status from `master`

**Comment by ssoloff** [comment]
I found another project that follows this process in their Travis build (all using the GitHub API):

1. Create a new branch off `master`.
1. Upload the modified file to the new branch (this is what we do presently, but to `master`).
1. Create a PR to merge the branch created in (1).

Again, the PR created in (3) would have to be manually merged by someone.  Given that we're kind of in a quiescent state related to Checkstyle fixes (i.e. they're only happening about once a week), I think the manual merge is not too big of a burden since it basically requires zero effort to review.

I will try to prototype the above procedure in my fork.

**Comment by ron-murhammer** [comment]
@ssoloff Looks like you are still working through a PR to address this? I'm open to either adjusting the build to create a PR to update the checkstyle count or reverting the master protection for now.

**Comment by ssoloff** [comment]
@ron-murhammer Yeah, #2934 should fix the problem.  If we find we don't like having to merge PRs to update the Checkstyle thresholds, we can re-visit disabling branch protection for `master`.

**Comment by ssoloff** [comment]
The new script appears to be working. 🎉

**Comment by RoiEXLab** [comment]
🎉
@ssoloff @ron-murhammer Btw. The bot PRs seem like a good occasion to use the Rebase "merge"

**Comment by ssoloff** [comment]
@RoiEXLab That was my initial feeling, as well, when I went to merge the second bot PR.  But then I thought consistency may be a higher priority.  So, I'm not really sure. 😕  For now, I guess I'll just stick to the preferences I listed in #2877.
