### ISSUE TITLE
Propose to remove discussion label 

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2933]
I would suggest we remove the 'discussion' label, I don't think we would lose anything.

Reasoning:   'discussion' is applied to most any new issue, it's not very meaningful and arguably harmful as the absence implies there is no discussion to be had. 

Do we want something to replace 'discussion' with something else, or can we better clarify the purpose of the label?

**Comment by DanVanAtta** [comment]
Second thought, discussion label does seem to be a bit useful to distinguish solicitation for input vs issue tracking. Should we maybe move all 'discussion' issues to forums perhaps? There does seem to be something wrong with the current tracking that needs some improvement... Ideas very welcome, thanks.

**Comment by RoiEXLab** [comment]
I don't think moving discussions about implementation details to the forum is a good idea.

**Comment by ssoloff** [comment]
> discussion label does seem to be a bit useful to distinguish solicitation for input vs issue tracking

Yup, that's the way I've been viewing it.  Although, in many cases, I find an issue initially opened with the "discussion" label becomes an issue that is resolvable via a PR (e.g. #2901).  However, that may suggest that such issues should never be labelled with "discussion" in the first place?

> Should we maybe move all 'discussion' issues to forums perhaps?

Agree with @RoiEXLab that technical issues should, in general, not be discussed on the forum.

**Comment by ron-murhammer** [comment]
I've been mostly using it an issue requires feedback/discussion/debate before any changes are made. Once there is a consensus then I think removing "discussion" label if its something that we need to make changes for helps. I think we should try to have most non-technical discussions on the forum but there are still plenty of technical topics that fit better here.
