### ISSUE TITLE
Zen hub - give it a try?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#294]
https://www.zenhub.io/

Supposedly gives an easy way to attach files to github issues. Useful if we want bug reports to be files via github, and generally useful IMO. Any thoughts any this, any objections to giving it a trial run?

**Comment by ron-murhammer** [comment]
Looks cool. I'd be open to giving it a try.

**Comment by DanVanAtta** [comment]
zenhub app access has been requested. Owners, @ron-murhammer  or @veqryn , please check for it and kindly do the necessary.

**Comment by DanVanAtta** [comment]
@ron-murhammer , @veqryn , cancel that. Looks like I was able to click the "authorize access" button. Looks like zenhub is enabled now : )
