### ISSUE TITLE
AI Retreated from Moscow Round1 (Big World v3)

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#295]
AI Log: https://gist.github.com/DanVanAtta/0ebcac1ec7339af94c9e

Saved game: https://drive.google.com/open?id=0B0KtoTT3hWS-MXVlMjNTZ0RSMDA

AI retreated in round 1 from Moscow rather than a standard opening. Perhaps this is because the AI was only set to be Russia and was not also selected to be other players (IE: I set only Russia to be AI, rest are human)

**Comment by DanVanAtta** [comment]
Hmm. setting all allied players as AI, doesn't seem to matter. The AI has yet to engage in a single battle yet I am not making any moves. Looks like the decision whether to attack or not is perhaps now skewed to never attack.

**Comment by ron-murhammer** [comment]
Just tested Big World v3 Russia round 1 and seems fine to me: [test.txt](https://github.com/triplea-game/triplea/files/64406/test.txt)

**Comment by DanVanAtta** [comment]
I tried to repro right away and found that the retreat happened again yet slightly different. On another attempt russia did a standard round and attacked as normal. Also of note, none of the AI's would attack. I'm going to close this now since there is nothing more concrete to track down. The AI log might be of help to you maybe. IMO we should consider also improving the AI logging overall, make it more rigorous so determining what happened would be easier.
