### ISSUE TITLE
Multiple Canals Between 2 Sea Zones

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#296]
Lots of discussion around how multiple canals between 2 sea zones work: http://tripleadev.1671093.n2.nabble.com/WORLD-AT-WAR-td5862407i280.html

It seems to boil down to this:

1. You must own all canals between 2 sea zones in order to move between them currently. This is how the code reads in the engine as well how it functions in WaW and TRS: https://github.com/triplea-game/triplea/blob/master/src/games/strategy/triplea/delegate/MoveValidator.java#L1424

2. It appears that WaW and TRS are meant to allow movement if any canal is owned not all between 2 sea zones. That is what the 'experts' say and the notes seem to vaguely indicate.

3. So I think we need an engine change to properly support this. The question is does it make sense to have both a AND (need all to own all canals) and OR (own any canals) option? I'm not sure the first option is really needed since you could just create a single canal with more than 2 territories to cover this case I believe.

@veqryn Thoughts?

**Comment by veqryn** [comment]
I think they need to clarify what exactly they want, and have it agreed on by the major contributors and players of those two Sieg maps.  We should do that before we make any changes to code...

Canals work pretty well right now, and are pretty extensible.  So long as the attachments themselves are named differently, you can have multiple of the attachments.  And they do not apply just to sea zones: you can make them control movement between any two territories, based on the ownership of 1 or more other territories.

I would have to dig into the code to see if we already allow an "OR" relationship in some way, but my best guess would be that if we do not then it would be very very easy to copy over the code that allows AND/OR/XOR for condition attachments (triggers, etc).

**Comment by veqryn** [comment]
Actually, scrap the idea of AND/OR/XOR, as that is better applied to logic behind conditions attachments.

Instead, I would go with using the logic behind Territory Conditions (aka: "National Objects").
In the xml you do something like optionally specifying a number, followed by a list of territories.  The number is the minimum number you need to own (or allied control) for you to meet the objective.

The code to parse all this is already there, so it would be easy to use.

**Comment by ron-murhammer** [comment]
I've put my proposed changes in a thread here: http://tripleadev.1671093.n2.nabble.com/Multiple-Canals-Between-2-Sea-Zones-tp7590656.html

**Comment by veqryn** [comment]
Comments posted.  There is a much easier way that is also backwards compatible, that I posted for you...

**Comment by ron-murhammer** [comment]
PR for short-term solution of changing from AND to OR between canals: https://github.com/triplea-game/triplea/pull/343

**Comment by DanVanAtta** [comment]
Why is it a short term solution? I don't understand why we should allow technical debt after updating the canal functionality, which is what short term means to me here.

**Comment by ron-murhammer** [comment]
So this PR fixes existing canal attachments to support WaW/TRS multiple canals. Long-term I'd like to complete redesign canal attachments which feature is here: https://github.com/triplea-game/triplea/issues/344
