### ISSUE TITLE
Roundel order inconsistent for diplomacy phase

### ISSUE THREAD

**Issue by General-Dru-Zod** [triplea-game/triplea#2966]
### My Operating System:
windows 10

### Engine version:
any

### Map name and version:
Bad-Ass_4-Nation_FFA v.1.6.0.20

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Open a new game and cycle to any nations diplomacy phase. 

### Do you have the exact error text? Please copy/paste if so
No error, but inconsistent order for the roundels for each political action.

Envoy_I, Envoy_II, and Envoy_III. roundels order (next to political actions) is not consistent (the left to right side order as  compared to true nations).

I will list the order from assumption all Envoy roundels should be on right side. However, I don't really know if this is a correct assumption, since I don't know exactly what the roundel order is truly based on.

During British diplomacy phase Envoy_I and Envoy_II roundels are on left side.
During Germans diplomacy phase Envoy_I, Envoy_II, Envoy_III roundels are all on left side.
During Japanese diplomacy phase Envoy_III is on left side.
During Russian diplomacy phase Envoy_III is on left side.

Note these roundels were always out of order in every version. But it didn't seem like a big deal.

Also note the Envoy order from top to bottom is coded with that pattern, so what appears as an inconsistency there at first glance, is actually ok.

### Instead of this error, what should have happened?
I think it should list the roundels in same order for all groups. Each group consisting of all political actions with a specific nation. So the Envoy roundels should either always be on right side (2nd in the order) or always on left side (first in the order). As I believe they should be using an alphabetical order to assign those positions. 

Note the Envoys are not true nations. I only use them to achieve immediate feedback due to lack of a "activateTrigger" for politicalActionAttachments. I require that immediate feedback to make the diplomacy logic function as per the rules in the diplomacy section of game notes.
### Any additional information that may help:
[Bad-Ass_4_Nation_FFA_roundels.for british.zip](https://github.com/triplea-game/triplea/files/1709913/Bad-Ass_4_Nation_FFA_roundels.for.british.zip)

Link to game download below. Note, you do not have to signup, just close the spam window and behind it should be the download window. 

Also note the non TS version is the one you should open as the TS (territory selections) is incomplete.

https://www.sendspace.com/file/bwke05

**Comment by General-Dru-Zod** [comment]
Copy useful info from original:
This is probably something to do with how it organizes the roundels to begin with. Its been a while since I coded that portion. I don't recall exactly what I figured out back then. But was mostly, alphabetical order of the relationships themselves determined the grouping of political actions. But once I used the Envoys that grouping got screwy as the order of roundels got inconsistent. But testing suggests its still functional.

**Comment by General-Dru-Zod** [comment]
> `@General-Dru-Zod 👍 Please do. It could be as simple as we're using unordered containers for these things, which would explain the non-determinism of the display at different phases of the game.`

**Comment by ron-murhammer** [comment]
Do you have a screenshot showing the inconsistent ordering?

**Comment by ssoloff** [comment]
@ron-murhammer Zip file in the description contains the screenshots.

**Comment by ron-murhammer** [comment]
@General-Dru-Zod This should be fixed after #2978 is merged. You can see the screenshot result in the PR. Just needed to add an ordered set instead of unordered set to the code to ensure the roundels appear in the order defined by the XML relation changes.
