### ISSUE TITLE
Declare an official freeze of old SVN triplea content?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#297]
I think it is time we declare *all* content in the old triplea SVN repos to be under code freeze. Specifically, no new commits to SVN. Let's turn our focus to wrapping up PR's,  release testing, and then doing our first release from github.I think it would be reasonable to target a release in February or early March. 

I understand from PR #286 comments from @ron-murhammer  that there are a number of updated waiting. If that is case, let's get those in now, quick, and then declare that code freeze and release. @veqryn , @ron-murhammer , thoughts?

**Comment by DanVanAtta** [comment]
I understand from PR #286 comments from @ron-murhammer  that there are a number of updated waiting. If that is case, let's get those in now, quick, and then declare that code freeze and release. @veqryn , @ron-murhammer , thoughts?

**Comment by ron-murhammer** [comment]
@DanVanAtta Yeah I'd like to at least upload the list of map updates we have now to SVN. Then we can start thinking about a freeze and next release.

**Comment by veqryn** [comment]
Lets freeze the triplea engine SVN repo.
The triplea maps SVN repo is totally up to you guys, since I haven't been managing it for well over a year by now.

As far as doing a github release, i think that should depend on finishing up a lot of loose ends around the gradle build, but i am fine to target March or w/e, so long as we remain flexible.

**Comment by DanVanAtta** [comment]
@ron-murhammer @veqryn , I believe there is agreement the triplea engine SVN repo is officially deprecated. @ron-murhammer , you are going to be the last to touch the SVN maps repo, so we'll deprecate that once you are done (as previously agreed in Gitter chat).

Closing.
