### ISSUE TITLE
Help button on main screen is 404 link

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2975]
Repro:
- launch game
- Click help:
<img width="335" alt="screen shot 2018-02-10 at 3 51 06 am" src="https://user-images.githubusercontent.com/12397753/36061853-ac5005c8-0e15-11e8-8585-f008d8382e31.png">

Notice:
Game opens: http://triplea-game.org/help/, which is  a 404

Expected:
Not a broken link

**Comment by RoiEXLab** [comment]
@DanVanAtta https://github.com/triplea-game/triplea-game.github.io/commit/876b9cc64631c4bf308f24bb2100ec322e95ccd7

**Comment by DanVanAtta** [comment]
ya ya : )

good to document the bug. A 'temp' help page to redirect to forums would be good. Game engine itself needs some update though, as that page is gone.

**Comment by DanVanAtta** [comment]
Also 'Web' > 'How to host' has same 404 link.

**Comment by ssoloff** [comment]
@RoiEXLab Would it be easy to retrofit the link checker you wrote for triplea-game.github.io to, for example, check the links in `UrlConstants` during the build?  Maybe it would be easier if we extracted the URLs to a _.properties_ file that was used to initialize the values in the `UrlConstants` enum?

**Comment by RoiEXLab** [comment]
@ssoloff Well I haven't looked at the code for a while, but IIRC the way it works is basically by parsing HTML, getting all the external references and performing HEAD requests to see if the server returns 200.
So all that needs to be done would be to change the code to allow other files to be scraped for URLS

**Comment by DanVanAtta** [comment]
One issue to consider, we can check the game engine, but if a URL disappears then we would only know on the next game engine build. That could block game engine builds for things outside of its control. On the other hand knowing this would be very useful. Really I think the answer is we need a monitoring service/page. Something that checks a set of key URLs are available and live (we've plenty to check: lobby, dice server, forum, DB, links)

**Comment by ssoloff** [comment]
:+1: for a live monitoring service.

**Comment by DanVanAtta** [comment]
Help page was put back up, no longer 404's: http://triplea-game.org/help/

![screenshot from 2018-02-11 10-48-07](https://user-images.githubusercontent.com/12397753/36076990-18b429de-0f19-11e8-903a-70f8b43414fb.png)

**Comment by RoiEXLab** [comment]
@DanVanAtta @ssoloff Just had this idea, posting it here so I don't forget it:
If we're crearing a monitoring website at some point (after the dice server js project has been finished 😅 I want to build one ^^), we probably want to create a widget for the forum as well, that notifies users if a service is currently down.

**Comment by DanVanAtta** [comment]
There is some open source software from one of the major's that does the service monitoring. If I remember who/what it was, I'll post a link (maybe netflix? or linkedIn??)

Happy to hear @RoiEXLab . Some examples of what I was thinking of:
- https://status.github.com/messages
- https://status.aws.amazon.com/

Integrating with lobby would be okay with me. Though we woudl need to keep in mind that lobby might be dead (hopefully not), so we would need to keep that in mind and if it makes sense.
