### ISSUE TITLE
New labels for PR's:  WIP  & Preview

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2982]
Introducing two new labels, "WIP" and "PREVIEW"

![new_label](https://user-images.githubusercontent.com/12397753/36078326-72bdb980-0f29-11e8-95ba-389d2991a17d.png)

Why? PR queue was getting a bit static - simply assigning to people does not quite capture state as well as the label. The requires major release labels seemed to be working out well.

What do the new labels mean?
- _***Preview***_: this is so we don't have to put `[Preview]` and `[do not merge]` in the titles anymore. We've successfully used such PRs I think to give a very concrete sample of some in progress code. This early feedback is really good, and the preview branches tend to get closed soon enough that the queue is not completely cluttered so far. 

- _***WIP***_: 'work in progress'. Basically means the PR author is working on something. The idea is the author would remove this label when a PR is ready for review again.

Initial Naming Convention (subject to change): To keep the labels different from the others, I prefixed them with "PR" and put their comment in angle brackets for an additional visual indicator.

**Comment by RoiEXLab** [comment]
👍

**Comment by ssoloff** [comment]
:+1:

**Comment by ron-murhammer** [comment]
Seems fine. We can try it out for now and always adjust if necessary.
