### ISSUE TITLE
Recommendations for builder Annotations or Frameworks?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2983]
Are there any recommendations for "builder" annotations or frameworks? I'd like for us to briefly examine our options.

I am concerned if we do not select one. Hand-writing them or auto-generating them with IDE and checking in results can lead to problems long term. I think it would be best if picked a framework that auto-generated it for us and everyone, this would be easier to modify going forward and make better use of builders. With builders we can eliminate the `String, String, int, int, boolean` APIs for something a bit more sensible and easier to maintain : )

-----------------

I know of Lombok + Immutables as options. I like lombok for a number of things personally, but at same time it's builders are not compile-time safe. A library that would give us compiler errors if we do not set all properties would be very nice.

**Comment by ssoloff** [comment]
[Déjà vu](https://github.com/triplea-game/triplea/issues/1721)?  Should we just reopen that issue, as some discussion has already occurred?

**Comment by DanVanAtta** [comment]
New information is that the "hand-written" version is harmful, yeah, let's re-open  #1721

**Comment by DanVanAtta** [comment]
Re-opening.
@ssoloff yes, this is a repeat, but:
- old issue is dead
- more important to keep topics summarized, current, and linked than it is to keep everything in one thread. It was a mistake to close this, so re-opening now.

---------------

Active request to everyone:
- give recommendations for builder annotation library
- voice any strong objections to lombok or immutables if you know of any

**Comment by DanVanAtta** [comment]
Not a super popular issue... I'd like to use a better builder compared to Lombok, but I don't know what that is. We have plenty of uses for lombok, it's probably worth discussing on its own. I opened this issue to do so: https://github.com/triplea-game/triplea/issues/2985

This issue meanwhile has any open question: are there any good builder libraries out there, better than lombok that we can use?

**Comment by ssoloff** [comment]
Just based purely on reading, Immutables seems lighter-weight compared to Lombok and addresses the specific smell we're trying to clean up.

**Comment by DanVanAtta** [comment]
In terms of weight, lombok might be lighter actually in some ways, it's just a `@Builder` annotation, hard to be much lighter : )
I think the lombok equals and hashcode will be of most use to us. 

But having worked with lombok for some time, I do know it's builder could be better, hence the consideration/request for recommendation of other builder frameworks to satisfy that particular need.

**Comment by ssoloff** [comment]
@DanVanAtta Sorry, I meant "lightweight" in terms of library size and focus, not how much source code is required to implement a builder. :smile:

**Comment by ssoloff** [comment]
Closing as Lombok's `@Builder` has since been adopted.  @DanVanAtta, please reopen if necessary.
