### ISSUE TITLE
Considering Lombok Plugin for TripleA

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2985]
Despite some pitfalls, Lombok is quite powerful and should be useful for TripleA in my estimation. Some specific benefits would be its annotations to autogenerate code for:
- equals and hashcode
- getters and setters
- builders
- all arg constructors

###  Motivation 
Hand-written versions, or checking in auto-generated code adds to our maintenance cost. We have to test it (at least in theory :grin:) and we update it by hand. It's more to read... By using annotations to auto-generate this code dynamically, we no longer have to maintain it by hand.

So long as we can understand best-practices for its usage, we could really benefit as there are a lot of getters/setters and other boiler plate code in TripleA. New code would benefit almost immediately. Lombok usage can get a bit pervasive, a really good thing if there is consensus on the best practices for it.

###  Pitfalls / Concerns
I've been working with projects that have made heavy use of lombok for nearing 3 years now. There are some gotchyas. If we were to introduce lombok, there are a number of pitfalls we would want to be aware of:

- Byte code manipulation / rules out AspectJ.  practical impact is that lombok could interact with other frameworks that also do byte-code manipulation. The most notable/likely is AspectJ. While AspectJ is always compelling, lombok is really practical, in practice we'll gain more benefit as it's common-place vs aspectJ which has it's useful, but niche purposes.

- IDE needs to turn on annotation processing. This is an explicit step that needs to be done to have IDE see the 'auto-generated' code.
- Lose some directness, if you lookup a getter you go to the variable instead and you don't see a getter.
- Builder has some nuances and is not compile time safe. It's still very useful, but there are better builder semantics out there and so as far as builder Libs go, lombok falls a bit short. Notably defaulting values can be tricky with builders.
- Can be a crutch. `@Data` objects are necessary and very valuable in some contexts, in many others they are hamful. Just because it's easy to put a lot of setters and getters on objects, does not really mean you should. So there is some art to using lombok I suppose... but it is subjective too.
- Can be a bit obscure until you're a bit more lombok accustomed, eg:
```
@AllArgsConstructor(access = Access.PACKAGE)
@Getter
@ToString
@EqualsAndHashCode
public class Example{ 
  private final Player owner;
  private final UnitType type;

  public Example(Unit unit) {
     // note the 'this' call to the auto-generated all args constructor
     this(unit.getOwner(), unit.getType());
  }

   // a ton of boiler plater is cut out. Lombok would put in getters, equals, hashcode and a toString.
}
```

###  Request / Action Items 
- Have you used lombok before?  Yes / no ? 
- What is your opinion/perception of lombok for TripleA? 
  - 0 Strongly not in favor, 
  - 1 slightly not favor
  - 2 neutral 
  - 3 slightly in favor, 
  - 4 strongly in favor

**Comment by ssoloff** [comment]
* No
* 2

**Comment by RoiEXLab** [comment]
- No
- 2

A possible alternative would be to use another JVM compatible language like kotlin that supports the concept of a data class by default, haven't done that before but I just wanted to point that out.

**Comment by ron-murhammer** [comment]
- Minimal
- 1

**Comment by DanVanAtta** [comment]
What are the specific concerns @ssoloff ; @RoiEXLab ? Why strongly not in favor? 

> A possible alternative would be to use another JVM compatible language like kotlin that supports the concept of a data class by default

My goal is not to introduce data classes. Kotlin is interesting in some ways, but it's not necessarily an alternative, it's not mutually exclusive.

**Comment by ssoloff** [comment]
> Why strongly not in favor?

I thought "2" was "neutral"?

I'd suggest picking two or three types in the TripleA domain that would benefit from Lombok and creating a spike branch demonstrating its usage.

**Comment by DanVanAtta** [comment]
Derp, it is neutral, my mistake  : )

> I'd suggest picking two or three types in the TripleA domain that would benefit from Lombok and creating a spike branch demonstrating its usage.

Good suggestion, I can do that.

**Comment by ssoloff** [comment]
@DanVanAtta Can this issue be closed now that we've integrated Lombok into `master`?
