### ISSUE TITLE
Add game status feedback when AI is calculating

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#299]
There is a problem of no feedback to the user when the AI is doing long running calculations. Any thoughts on how to notify the user when the AI is busy calc'ing?

Some proposals:
- We could do a spinner.
- We could print a message in the bottom status bar area, next to where we print territories and their value.

**Comment by ron-murhammer** [comment]
@DanVanAtta Agree. I'd like to add something that shows the AI is thinking. You can obviously watch the AI log but most players don't want to do that. Just something showing turn progress or its thinking.

**Comment by DanVanAtta** [comment]
https://github.com/triplea-game/triplea/wiki/Feature-Back-Log
