### ISSUE TITLE
Lower AI default pause duration to 250

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#300]
From http://tripleadev.1671093.n2.nabble.com/Slow-Computer-Reaction-Times-tp7590362p7590365.html

 
"then you must have Game / AI Pause Duration (in the menu) set at 5000 (ms).  My suggestion is setting it at 250 (ms), if you want to see the moves at a good pace. "

5s is a *slow* pause. Shall we make it 250ms and allow users to slow it down when they want?

**Comment by ron-murhammer** [comment]
@DanVanAtta No the default I believe right now is 400ms. I personally play with it at 50ms and think the default should be lower but its not terrible.

**Comment by DanVanAtta** [comment]
@ron-murhammer , thoughts on 250ms as a default instead of 400ms? Similar to #298, opened a source forge post to get some community feedback:  http://tripleadev.1671093.n2.nabble.com/Default-quot-AI-Pause-Duration-quot-td7590442.html

**Comment by ron-murhammer** [comment]
@DanVanAtta Closing this as I think 400ms is fine for now. Doesn't seem to be a lot of feedback to change it. I think the bigger point is making sure people understand how to change it.

**Comment by DanVanAtta** [comment]
With some apolgies, I disagree @ron-murhammer. 400ms I think is *way* too slow. New players could be turned off completely from the game and instead of spending extra effort to find out what/why the game is running so slow, they may just close it up and go away. Given the huge volume of source forge downloads, but no huge volume of players, issues that could impact player abandonment I think are automatically high  importance. I would want this fixed. Simple change to 250ms should be easy. Then we'll have time to find a better way to "teach" players they can adjust this threshold.

**Comment by DanVanAtta** [comment]
@ron-murhammer , I don't think we'll ever get a "lot" of feedback unless we break the gaame. Any feedback, a weak signal, should really be payed attention to. Everyone else has gotten used to it and moved on. The accumulation of these small things cause for a really painful experience, that veterans likely have become so accustomed they no longer notice. This is the a "normalcy" of the absurd.

**Comment by ron-murhammer** [comment]
@DanVanAtta So I think the problem is we also get users ask the exact opposite which is that its too fast. Example: http://www.axisandallies.org/forums/index.php?topic=37179.0

I'm just not sure we've really gotten any consensus/data to support changing the default to be 250ms. Feel like I've been part of threads that want it faster/slower and its truly a user preference. Not sure the best way to determine the default since we get so little feedback. If you really feel strongly about it then I'm fine with changing it to 250ms.

**Comment by DanVanAtta** [comment]
We need an on-screen control for the AI pause duration that can be changed while the AI is executing its move. A slider would be a logical UI control. @ron-murhammer , would you agree that is a deeper solution to this issue? We need similar logic in the combats as well to replace the unnecessary space bar clicking..

**Comment by ron-murhammer** [comment]
@DanVanAtta Potentially. I think the only thing you'd have to be careful about is the slider isn't going to make the AI 'think' any faster. Just change the 'pause' between moves/battles. I could see a lot of people moving the slider all the way to minimum pause and wonder why the AI is still taking so long :)

**Comment by DanVanAtta** [comment]
@ron-murhammer , for certain I agree those are risks. We'd have the same labelling, so I picture this as more moving the UI control out from the game menu and onto a panel. We could perhaps complement this with some hover over text that explains exactly what the control does.

**Comment by DanVanAtta** [comment]
Really the problem is having feedback to know what is happening. Then letting the user know how/where to change the ai puase duration becomes the next problem (but a less important one at that point as well, since it'll be more obvious to the user that is what they need to find and adjust) . I restated the problem in #460, taking further conversation there..

**Comment by FrostionAAA** [comment]
Just an input … the tutorial map now instructs new players how to adjust the speed of things. Personally, I think the default speed should be adjusted to a new player that does not totally understand the rules and know the strategic possibilities of the maps yet and therefore needs the game to go a bit slower than the experienced player would prefer. Any experienced player can just and sould know how to adjust game speed.

**From the tutorial:**
_“Is the AI-player moving too fast or too slow for your taste? Then adjust the Pause-time in between moves of the AI-Player. Note: This does not alter the speed of thinking, just the time in between moves. 
Go to the ‘Game’-tab
Select ‘AI Pause Duration’
Set to 50ms for fastest moving AI
Set to 1000ms or more for slow moving AI"_

I think another problem related to this is that the “AI pause duration time” does notes not seem to spread the milliseconds/seconds chosen out on every aspect of the moves and actions no matter how much much time one sets in the “AI pause duration time”.

To me it seems that, for example, that after an AI players LAST combat move combat is immediately commenced and the battle window pops up, with none of the player-set AI time being allocated to follow this last combat move.

This is also the case in the combat window. When battling an AI attacker, during combat the “Attacker fire” phases are done in a split second, never allowing the defending human time to visualize that the heck happened. Of course this is also the case when two AI battle each other and the human just watches the battle window.
