### ISSUE TITLE
REV LL Battles

### ISSUE THREAD

**Issue by adamf2** [triplea-game/triplea#3002]
### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
After resolving a Battle in Arch to conclusion, (Germany took), screen shows "finish battle in Arch first"

**Comment by ron-murhammer** [comment]
@adamf2 Do you have a saved game or a way to reproduce the problem?

**Comment by prastle** [comment]
They had 8000 plus eng vs a 3621 i dealt with it asked the lower player to upgrade. was my thought

**Comment by ron-murhammer** [comment]
@prastle Ok, if it happens again then post details here.

**Comment by prastle** [comment]
for that you would need a post game from adam or his partner
but i can say it was a neat thing
i looked at it

**Comment by adamf2** [comment]
The other player , King Kelly would have the screen shot 


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Ron <notifications@github.com> Date: 2/15/18  9:17 PM  (GMT-05:00) To: triplea-game/triplea <triplea@noreply.github.com> Cc: adamf2 <adam12feinberg@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [triplea-game/triplea] REV LL Battles (#3002) 
@prastle Ok, if it happens again then post details here.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/triplea-game/triplea","title":"triplea-game/triplea","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/triplea-game/triplea"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ron-murhammer in #3002: @prastle Ok, if it happens again then post details here."}],"action":{"name":"View Issue","url":"https://github.com/triplea-game/triplea/issues/3002#issuecomment-366126522"}}}
