### ISSUE TITLE
Unloading transports

### ISSUE THREAD

**Issue by ZjelcoP** [triplea-game/triplea#3014]
Noticed a change in behavior while playing.
This could very well be intended behavior for good reason (AI or something) just wanted to verify.

At least as far back as 8659 up to 8847:
You select all units in a grand armada (Land, naval and air) and move all to a land territory
>> Result: for the landunits the movement is impossible. Air units from the stack will still move.
You have to single out the land-units from the navy to move them to a land-territory.

Up until last stable(7621) : you can select all units in a grand armada (Land, naval and air) and move all to a land territory.
>> Result: all land-units and air-units will move to the territory.

I find the previous behavior very convenient for quick movement especially in the case of large masses of units.

**Comment by prastle** [comment]
Ya I noticed that the other day as well.  God stuff!

**Comment by ron-murhammer** [comment]
@ZjelcoP Verified this is a problem. Can easily reproduce by loading any transport and trying to select the transport as well as its loaded units to a land territory. It then shows an error rather than just filtering out the transport and allowing the move.

@RoiEXLab @ssoloff I started looking at this and think it has to do with the order that the units are being passed and might be related to this change #2900

**Comment by ron-murhammer** [comment]
I believe this portion of the previous code isn't represented after the refactoring:
'''
-      final Unit t1 = TripleAUnit.get(u1).getTransportedBy();
-      final Unit t2 = TripleAUnit.get(u2).getTransportedBy();
-      // check if unloadable units are in a transport
-      if (t1 != null && t2 == null) {
-        return -1;
-      }
-      if (t1 == null && t2 != null) {
-        return 1;
-      }
```

**Comment by ssoloff** [comment]
@ron-murhammer I think the `null` comparisons are supposed to be covered by the `nullsLast()` call in the new code.  However, I can't see where `getTransportedBy()` is ever being called.  So we might be performing the comparison on the transportee rather than the transporter....?

**Comment by ron-murhammer** [comment]
@ssoloff Yep, that's what I'm seeing. The null comparison needs done on getTransportedBy() not the other comparator being called.

**Comment by ssoloff** [comment]
@ron-murhammer Yeah, confirmed that fixes the problem.  I'm seeing if there's a straightforward way to unit test this.

**Comment by ron-murhammer** [comment]
@ssoloff The core case that hits that condition is say a transport and a unit that its transporting. As the transport will have getTransportedBy() == null while the tranported unit won't.

**Comment by ron-murhammer** [comment]
I verified this fix resolves the issue.

**Comment by ssoloff** [comment]
Fix is available in 9623 or later.
