### ISSUE TITLE
No text on battle button

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3018]
![no_text_on_battle_button](https://user-images.githubusercontent.com/12397753/36347439-21801d1e-140c-11e8-8c1e-0acd5c1d6d0e.png)

[no_battle_text.zip](https://github.com/triplea-game/triplea/files/1734335/no_battle_text.zip)

Notice the button in combat window has blank text. Expectation is for it to show 'please click to select casualties'

**Comment by ZjelcoP** [comment]
For me the text is there (8847). UI-theme = default. When i hover the mouse over the field it turns white.
Text (also white) becomes unreadable, in previous versions(7621) contrast was beter, text was still somewhat distinguishable.

When selecting a different UI-theme like SubstanceOfficeBlue2007 The bar is standard near white. (even without mouse hover). The text is there but contrast is too messed to be able to read the text.

**Comment by ssoloff** [comment]
We probably shouldn't be hard-coding the colors on this button:

https://github.com/triplea-game/triplea/blob/febca53b80fb4b533ce8ffb9989c987b578b8a4e/game-core/src/main/java/games/strategy/triplea/ui/BattleDisplay.java#L598-L601

**Comment by ssoloff** [comment]
The above code goes all the way back to 2003 (5f160f3e3).  The Mac exclusion was added in 2006 (6f1fc81cd).  Any reason we shouldn't just nuke it and allow the L&F to set the colors on this button?

**Comment by RoiEXLab** [comment]
@ssoloff I'm all for simply nuking it!

**Comment by ssoloff** [comment]
@DanVanAtta Please advise if you're still seeing this issue in build 8905 or later.
