### ISSUE TITLE
Corrupt Map Delete Prompt Error

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#302]
It appears there is a bug with the new delete corrupt map prompt feature: http://tripleadev.1671093.n2.nabble.com/Triple-A-Error-tp7590611.html

**Comment by DanVanAtta** [comment]
Added bug fix commit 1f83c06 and merged it (user who reported is around, so I want to get them the test link). Please commit on this issue or PR#304 if there is any commentary about the bug fix.

**Comment by ron-murhammer** [comment]
@DanVanAtta Looks good. Thanks for the quick fix. Hopefully the user confirms that it works.

**Comment by DanVanAtta** [comment]
Fixed in #304 - user confirmed it worked
 : )
