### ISSUE TITLE
I'm ready to add my map

### ISSUE THREAD

**Issue by BeornTheBold** [triplea-game/triplea#3041]
I have a playable map that is ready to be shared with the TripleA community.  Please send me an invitation to join my own map team at triplea-maps.

**Comment by ron-murhammer** [comment]
@BeornTheBold Looks like this was done. Closing.

**Comment by BeornTheBold** [comment]
Hi Ron, I received the invitation and joined, now I need to transfer ownership of the repository to a dev team and my own team?  I’m not sure what to do next.  I have no team name.

- BeorntheBold

**Comment by ron-murhammer** [comment]
@BeornTheBold Are you able to do step 7 in the guide: https://docs.google.com/document/d/1FfF7N0srp9QG0_if5D-c1d1Aa1QTttdhxgm1GBh3pI4

You should be able to go here: https://github.com/BeornTheBold/another_world. And then go to settings and transfer ownership using 'triplea-maps'
