### ISSUE TITLE
map key listeners are not consistently active

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#305]
It appears in multiplayer games the key listener for the 'n' key (select next unit) is not kept around properly. In single player games I have not seen this problem. In multiplayer sometimes you have to click the map or interact with it for the key listener to be "recreated". At that point the "n" key is then active.

Debugging the code, when this problem occurs the event handler code for the "n" key press event is not executed at all (hence the hypothesis that the key listener is being destroyed and recreated)

**Comment by DanVanAtta** [comment]
I'd like to state explicitly, this bug is why most lobby players still believe that the 'n' and 'f' keys do not work. Initial launch of those features never worked very well, and now after being 'fixed', still does not work consistently. I personally gave up on using the features and I'm quite sure many others have as well.

**Comment by DanVanAtta** [comment]
Bumping this up since I run into this all the time. "F" is now very useful now that the highlight is strong. I keep clicking the map as a work-around to allow the "F" to key to then work. Same thing for undoing with "u" key.
@RoiEXLab , @frigoref , this is an excellent one to pick up if you have the capacity.

**Comment by DanVanAtta** [comment]
This is an important fix, the "f" and "n" key seem broken unless a person knows to click on the map first, which is very non-intuitive.

**Comment by RoiEXLab** [comment]
I think I can pick up this one...

**Comment by RoiEXLab** [comment]
@DanVanAtta I might have an Idea what could be causing this...
I found [this Question](http://stackoverflow.com/questions/13810777/what-causes-component-requestfocus-to-fail-sometimes) on Stackoverflow, leading to the possibility that this issue is due to the delay of multiplayer games...
Any ideas where this could be happening?

**Comment by DanVanAtta** [comment]
I've seen in some places we "clean up" listeners. I've suspected this is due to us removing the listener in multiplayer games, and then not adding it back until a click event has happened on the map.

**Comment by RoiEXLab** [comment]
@DanVanAtta 

> I've seen in some places we "clean up" listeners.

That's what I couldn't find... but maybe I searched for the wrong thing... If you can still find a place, please tell me...

**Comment by DanVanAtta** [comment]
New simpler repro:
- move a unit
- hover over unit and press 'u'

Expect: 
- move to be undone

Actual:
- nothing happens

Note, if you click the map anywhere, then repeat the hover and 'u' action, then the mvoe will be undone as expected.
