### ISSUE TITLE
Game Manual UX Treatment - Don't include Game manual with game installer

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#307]
We have two rule books included with the game software:
- TripleA_RuleBook.docx (12M)
- TripleA_RuleBook.pdf (20M)

Some problems because of this:
- When a user has the game installed, they will want to play the game, not read over the game manual. We lose the opportunity to have them read the game manual while they wait for the game download and install to finish
- We add 32M to the game download

My suggestion:
- Remove both rule books from the source code and place a copy into the assets repo: https://github.com/triplea-game/assets
- Add a link to download the rule books wherever there is a link to download the game. So namely, add the rule books to the travis deployment  so they are available in github releases along with the game installers

Open question:
- What to do with the "open rulebook" button on the game screen? 

My suggestion for this is to remove it altogether. The button is there so the user can find the game manual. If the link is next to the installer, then the user knows where the game manual is, and the button then no longer has a reason to exist, the problem it is trying to solve is already solved.

@veqryn , @ron-murhammer , please let me know if you have any objections or if this sounds reasonable enough.

**Comment by DanVanAtta** [comment]
@veqryn , @ron-murhammer , please let me know if you have any objections or if this sounds reasonable enough.

**Comment by veqryn** [comment]
FYI The docx does not get included with the zip or the installer, so actually it is just the 20mb pdf.

I feel it is pretty standard for games to install/download game manuals as part of the installation, and at 20mb it is not all that bad.  I'd prefer to keep it part of the installation, but if you are dead set against it then I am fine to do whatever.  I do not mind it going to the assets repo.

If we do move it then I would like the open rulebook button, as well as similar links in the menu, to open a web browser that goes and either downloads or opens the game manual from whatever URL we are moving it to.  I would not want this button removed.

**Comment by ron-murhammer** [comment]
Another interesting point is the size of the PDF. If I take the docx and create a PDF using Word2010 its only like 5 MB instead of 20 MB. Any idea why?

**Comment by veqryn** [comment]
The image quality was poor when we did it that way, and we had to use some other way of making it in order to keep the images from being reduced in quality.
If you can find a way to create the pdf that keeps good image quality while reducing the size by a significant factor, then we can do that too/instead.

**Comment by gaborbernat** [comment]
So did you manage to improve PDF size while keeping the image quality?

**Comment by DanVanAtta** [comment]
Turns out the game client opens up the PDF from a remote URL, it does not even open the copy bundled with the game. To open that you would have to find it via the file system.

**Comment by DanVanAtta** [comment]
#459 removes the docx file altogether. The PDF file has been uploaded to the assets repo (github.com/triplea-game/assets). The PDF file also has been removed from the game engine in that PR, and links/references updated to the new assets repo location (from the previous source URL locations)
