### ISSUE TITLE
Private Bot Hosting No Longer Works After 7621

### ISSUE THREAD

**Issue by prastle** [triplea-game/triplea#3093]
### My Operating System:
Win 10
### Engine version:
Any newer engine version past .7621
### Map name and version:
N/A
### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Bot scripts fail to connect to lobby.
### Do you have the exact error text? Please copy/paste if so

Error: Could not find or load main class games.strategy.engine.framework.headlessGameServer.HeadlessGameServer
Press any key to continue . . .

### Instead of this error, what should have happened?
Bot loads in the lobby.
### Any additional information that may help:
  This isn't really a big deal since we have all the bot servers.  I am just hoping we can get this easily working again since it would allow anyone that can host to host a bot or two if needed on a busy day.  Thus cutting our overhead or helping out during emergencies.  These scripts always used to work.  Not sure what changed again.   @RoiEXLab  @ssoloff  @DanVanAtta 
Scripts worked in 1.9.0.0.7621

Current Script
```batch
@echo off
SET PORT=3363
SET BOT_NUMBER=25

SET LOBBY_HOST=45.79.144.53
SET LOBBY_PORT=3304

java -Xmx320m -Djava.awt.headless=true -classpath bin/triplea-1.9.0.0.7964-all.jar games.strategy.engine.framework.headlessGameServer.HeadlessGameServer -Ptriplea.game.host.console=false -Ptriplea.game= -Ptriplea.server=true -Ptriplea.port=%PORT% -Ptriplea.lobby.host=%LOBBY_HOST% -Ptriplea.lobby.port=%LOBBY_PORT% -Ptriplea.name=Bot%BOT_NUMBER%_Pras1 -Ptriplea.lobby.game.hostedBy=Bot%BOT_NUMBER%_Pras1 -Ptriplea.lobby.game.supportEmail=prastle7000@hotmail.com -Ptriplea.lobby.game.comments="automated_host" -Ptriplea.lobby.game.reconnection=172800

pause
```

**Comment by RoiEXLab** [comment]
@prastle Nothing suspicious changed since 1.9.0.0.7621
Your log suggests that the jar file can't be loaded, so there are 2 possible options: Either your script is being executed in the wrong directory (should be installation directory in your case), or you mistyped the name of the TripleA jar file.

**Comment by prastle** [comment]
Its in the install directory of the new same as when we fixed last time.

**Comment by prastle** [comment]
AH kk i will try that

**Comment by prastle** [comment]
Yup that was it thanks @RoiEXLab
