### ISSUE TITLE
GameEngine Aware of Map Major Versions

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3103]
Breaking off this topic from #3030 - For preliminary technical discussion:
- implications of making game engine aware of map major versions. The idea here is that you could have a couple map versions installed, if loading a save game from a previous major version, the save game would load successfully.

**Comment by ron-murhammer** [comment]
@DanVanAtta Its an interesting thought and I would consider a nice to have. This doesn't come up all the often in my experience. Most players end up moving to the new version and generally new versions are backwards compatible with old save games. The other problem is you'd have to get map makers to actually understand when to increment major versions as currently map versioning is pretty much up to the map maker is varies significantly.

**Comment by prastle** [comment]
I disagree @ron-murhammer  I witness it all the time but perhaps it is just engine related not map.  That's for you to wizards 😄  to figure out

**Comment by ron-murhammer** [comment]
@prastle Can you provide an example that you've seen happen? Specific maps/versions would be helpful.

**Comment by DanVanAtta** [comment]
@ron-murhammer this is a pretty big problem for lobby players, not sure about PBEM if it would be as much. The scenario is basically you have 2 or 3 save games going, and need another 6 weeks to finish them (that is the lobby life). During this time there is a major upgrade. That means you have to hold off on the upgrade or else not be able to finish the save games. Meanwhile new players have downloaded the newest map, that is not compatible. In this case there is some map juggling that happens by players, or they drop their save games, or they stop playing new games. 

This is perhaps the worst compatibility problem we have for players. For dev's we tend to see the network and save game compatibility as bigger problems, for players those are problems too, but it's not quite the same level of map hand-management hell and losing saved games.

**Comment by ron-murhammer** [comment]
@DanVanAtta Most even major map updates are backwards compatible. Usually only if you are doing things like removing/adding territories to the actual map image or something pretty extreme are they not backwards compatible with save games. The reason for this is that the save game keeps a copy of the XML so as long as the assets still remain then the save game can load.

**Comment by DanVanAtta** [comment]
To some extent I think we are accustomed to what is an 'extreme' update. Correcting the name of a territory is generally not viewed as extreme, but it would break save games. Basically because it is brittle, I'm suggesting the extreme bar is really low. We simply don't see those updates because of the compat issue, i'm sure there would be plenty more if it were readily an option.

**Comment by DanVanAtta** [comment]
edit, rephrasing.

Extreme updates are probably only 'extreme' because of the game limitations. Map refreshes do not really happen because of this problem. Is it a rare thing because it is actually rare, or is it rare because people know they should not break maps?

**Comment by DanVanAtta** [comment]
@ron-murhammer perhaps we don't have to fix this as described. The problem to solve is how to allow someone to upgrade to latest map, and still play a save game from a previous version. 

There will be the desire for territory name corrections, etc.. Supporting this would help, even if it is the once per 6 months or per year per active map.

Something to consider is if we can make more of the map data immutable. Immutable XMLs would take little storage space, if a map carriers around with it previous versions already, then save games would have everything they need. As an idea,  maybe instead of making the game engine aware of major versions, we make the map aware of it and come with assets for each version.

**Comment by DanVanAtta** [comment]
this convo has gone stagant...

 I do strongly feel that not being able to have different versions of XML elements is greatly limiting. It means we need to coordinate map updates to all maps at the same time along with an engine release. It's prohibitive and generally we cheat by selectively making certain maps non-compatible with the current release.
