### ISSUE TITLE
Map Parsing Version

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3104]
Breaking off from #3030, a technical topic: 'map spec version'

Idea here is we create a tracking number to tell the engine which "XML version" the map conforms to, this tells the game engine how to parse the map data. This would allow a number of benefits, most notably we could support new non-backward compatible map specifications.

I mostly suspect this would be used in one or two ways:
1. Simplified 2.0 XML spec. We could open this up as a possibility
2. Support new formats, yaml potentially.

I'm curious how people like this idea and to discuss in more detail.

**Comment by ron-murhammer** [comment]
@DanVanAtta Honestly, I think this would make it more difficult to support the maps we have. I really don't want more than 1 standard as that would make it more difficult to help map makers debug and more for us to support. I'd rather stick to one standard and improve it. Even if that means having to once in a while, mass updates to the map repos.

**Comment by DanVanAtta** [comment]
> Honestly, I think this would make it more difficult to support the maps we have.

How do you see that? This would let us keep the working maps we have as is, and introduce new features as we want for new maps or the maps ready to get them.

> I really don't want more than 1 standard as that would make it more difficult to help map makers debug and more for us to support. 

I can understand this. The format we have, we're pretty locked in to it. So we are blocked from restructuring it to do thinks like make it possible that a map like war of relics would be feasible. The current spec is pretty complicated, there are a number of simplifications we could do that would make map making easier and need less support. A lot of support is needed now as the map parsing is old, supports everything and the kitchen sink, and the format itself is not simplified. So I disagree with those specific points, in many ways our lives would get simpler. The old maps people stop updating, and we move forward with a better/simpler/easier spec (or at least we open up the option).

>  Even if that means having to once in a while, mass updates to the map repos.

This is really not a casual thing. I don't think we should do this more than once every 3 or 4 years, if ever again. Mass updates breaks every save game, it's perhaps the most impactful thing we can do. Many players do play games out over weeks/months, during that time nobody could update to the latest, and then you get this mix and match where you maybe can't start a new game because you can't update the map.

Part of the point is that we can't do mass updates of maps. We can, but we're not going to unless it's something like a typo fix. If we have a really new spec, that is simpler, we are not going to go back and retrofit maps (too many of them, simply not worth it, no value gained to do refactoring of old map XMLs).

**Comment by ron-murhammer** [comment]
My main point is if we want a new standard that isn't backwards compatible then IMO we need to update all maps to that standard. Otherwise we are still stuck with the old standard for the vast majority of maps.

**Comment by DanVanAtta** [comment]
>  Otherwise we are still stuck with the old standard for the vast majority of maps.

I believe this will always be the case. If we change the XML structure a lot, say where it takes some solid time and testing to update it, we are simply not going to go through every map to fix it and refactor them (would takes weeks/months). Consdering we'd have to do that all at once, focus on only that; I don't think we will, nor should we even. Most maps are perfectly fine; not updating them and keeping them playable is perfect. Being required to update all maps at the same time, with great effort, means we simply won't. That is a bit sad, as the current map structure is pretty over-complicated.

-------------

I think one thing that is getting missed is that we are not likely to see a new standard for some time. We can use minor versions to turn on new incremental features in the existing parser that are backwards compatible. For example we could have set v1.1 as a stricter parsing to not allow upper case first letters in attachments, that would have avoided the open P1 about this: https://github.com/triplea-game/triplea/issues/3115

**Comment by DanVanAtta** [comment]
TBH I've been thinking of this feature for some time, it's the most valuable idea for maps in some time.

Reflecting back on the 1.8 -> 1.9 map migration:
- all we did was correct typos and convert properties from one name to another. It was kinda close to hell, it took a long time, and it was really impactful to map makers. I don't think we want to repeat that experience; secondly we did that for perhaps some of the most simplest cases. 

What I'm getting at is basically that even though we can, we likely never will do a mass map update again; it's too impractical for a number of reasons. Given most maps are fine, such a system with parse version would work well. 

An analogy is doc type on html, if that was not there, then when the world upgraded to html 4.0, any website that did not upgrade right then would have been broken. While it is a pain to deal with mixed versions potentially, in our case I think it'll be pretty easy in the end as most maps are pretty set. 

Most version updates I think will be minor new features for potentially new maps, or maps that deserve the refactoring to take advantage of anything simpler. If things get complicated, there are a number of steps we could take to simplify things. 

Without this feature though, I'm a bit sad as I think it makes updating the engine more difficult and locks us into a map XML spec that could be better (and this make map development and map maintenance more difficult)

**Comment by ron-murhammer** [comment]
I guess I just don't see the path to retiring versions. Given your example if we made v1.1 stricter parsing, will we ever retire v1.0? If not then I don't really see the point. Isn't that really just the same as having v1.0 support both if we never retire v1.0. Can you walk me through how we would have used this for the mass typo/spelling change?

**Comment by DanVanAtta** [comment]
Good questions. The main problem is that mass updates are not practical; nearly impossible since we have to coordinate those over multiple game engine versions, and all maps need to be updated at the same time. While we can do a mass update, anything more than a typo fix becomes quickly impractical. This means that we're stuck with our current v1.0 version, we'll never be able to move forward; stuck with the current XML structure and limited in what we can do as we have to keep all maps working.

I don't think versioning is going to get too nuts if we add a parse version. Most maps are essentially frozen, the maps that take advantage of new features will not be that many; I think it can be managed. I also don't think there will be that significant of differences generally in the parsing.

In this last example, we could introduce some code that looks like this:

```
String myValue;
if( version > CASE_SENSITIVE_PARSING_VERSION) {
  myValue = prop.equals("value");
} else {
  myValue = prop.equalsIgnoreCase("value");
}
``` 

That would keep existing maps working, and when we game version is forced and everyone is on upgraded maps, then we can retire the branching logic.  This turned out to not have been the best example, as it looks like maps were buggy already, regardless such a strategy could still have been employed to make sure no maps were broken for any game engine version.

**Comment by DanVanAtta** [comment]
> My main point is if we want a new standard that isn't backwards compatible then IMO we need to update all maps to that standard. Otherwise we are still stuck with the old standard for the vast majority of maps.

@ron-murhammer I don't think this is feasible. Bulk update is proving to be a bad choice given the pain we saw going from 1.8 to 1.9. We do not own all maps, so we broke Roger's maps, and we messed up people that were developing maps, and that was for all pretty straight forward fixes. If we do anything signfiicant, first we do not own all maps, second, bulk update for a complex change is not practical. To boot, there is no mechanism to protect existing game engines from reading the latest non-compatible map.

If there is a map version then we can filter out newer maps from older engines. We can have newer engines parse both new and old maps. We can find a way to fix a map like war of relics and push an updated version of that one map that is maybe not compatible with existing spec. (War of relics is example of how map spec has hit it's scaling point). We can also work with map makers to simplify so that maps are easier to create, and then at least the active core of maps, the half dozen to a dozen could take advantage of the bleeding edge features along with new maps. Meanwhile existing maps can comfortably stay as they are, and not be broken, and not require coordination to upgrade engines and effort to do the updates. 

I did not really want to raise this exact topic just yet, we are not ready for it. But in terms of compat, we solve a lot of problems here. This was raised in #3030; @RoiEXLab proposed a download manager so we can solve the problem of game engine not knowing it can't read a map file. With a simple version number we can solve that, and we solve a number of other problems at the same time. Otherwise, I'm curious what other proposals there would be to solve these problems:
- game engine does not know when it can't parse a map
- bulk updates not practical, how do we avoid updating every map so that map makers are not frozen in time when it comes to building new maps
- fix a map like war of relics

**Comment by DanVanAtta** [comment]
@ron-murhammer any further thoughts? Saying no here unfortunately is a non-solution, we've a number of map compat problems to solve.

For example:
- we break all maps and fix them, but then force an engine upgrade
- everyone with save games they want to finish playing will need to ignore the 'you have out of dates warning'. Some will upgrade and be not happy they lost a save game.
- folks with running save games will not be able to start any new games on that map until they finish save games.

Considering that tourneys/save games etc easily run for a month or three; this is a very major problem. This in combination with the fact that bulk upgrades has never gone well and has little value  (refactoring map XMLs that are never played is of no value); it does seem we have multiple problems with no way forward right now.

I'll add importance to not breaking save games, @prastle will tell you how many players we *lose* when we break save games, or force non-compatible releases.

@ssoloff @RoiEXLab; do either of you have any thoughts here if  a parsing version would be useful? I particularly like the idea that we'll be able to let the many dozens and dozens of map chill, remain working while we can move forward. Considering also that TripleA owns maybe only half or a third of all maps, not breaking existing maps seems like a requirement now rather than a nice-to-do.

**Comment by DanVanAtta** [comment]
2nd thought, I'll try to clarify and better explain the problems we are seeing in a new issue. We've about 3 or 4 pretty significant issues.  I'd like focused conversation on that; I still think a parsing version is the solution, but it does not seem we are agreed yet on the problems even.

**Comment by RoiEXLab** [comment]
@DanVanAtta I just wanted to throw in another think to think about:
In case we want to fundamentally change the map system altogether, a simple version system might either not do the trick, or force use to keep much "almost never used" code.
So in order to have some sort of versioning system, we have a solid basement to build on first, to avoid such issues, although even that is not a 100% guarantee.
