### ISSUE TITLE
Make maps install specific

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3106]
From #3030, suggestion by @RoiEXLab we move game download folder to the install location. This would make it so maps would be loaded with the corresponding engine version instead of shared. The installer is able to support not re-installing the maps;

@RoiEXLab one question, if we do need to 'force' map upgrades, would we update that installer to do a force ovewrite?

**Comment by RoiEXLab** [comment]
@DanVanAtta I'm not sure what exactly you mean with forced map overwrite. 
If I understand you correctly however, we would change the default installation directory to something like TripleA1.9 or create a 1.9 subfolder and regenerate the installer UID on a breaking release so users can't select the "update" option when running the installer.

**Comment by ron-murhammer** [comment]
Umm. So is the problem here that everytime we release a new version then people have to redownload all their maps even if they haven't changed?

**Comment by prastle** [comment]
no

**Comment by prastle** [comment]
the problem is
new engines don't always work with old maps
and old engines
don't always work with new maps
To explain
I haven't had to update a map in years
well maybe months
unless a newversion
also
as all know we need the update map fixed in the downloader

**Comment by RoiEXLab** [comment]
@ron-murhammer The basic idea is the following:
Currently maps are stored in a user specific directory even if TripleA is installed system wide. So it would make sense to have the default map directory located inside the installation directory.
This would have the bonus feature that we could (if we decide to include the major version number again) that users could have multiple incompatible installations of TripleA but still have seperate map folders without having to either swap each time they switch versions, or for us to create a third "maps" directory with a different name.

**Comment by ron-murhammer** [comment]
Well, we technically have a solution to the 'old engines don't work with new maps' as their is a property in the map XML to specify minimum version. As with 'new engines don't work with old maps', that should be pretty rare and only happen if we decide to make non-backwards compatible changes to the XML (I think we've only done this once in the last couple of years when we fixed attatchment and some other spelling issues).

**Comment by prastle** [comment]
Ya its simple
Force them to upgrade   JESUS CHRIST
sorry for swearing

**Comment by prastle** [comment]
to be BLUNT!
All bots run 8941
seen any complaints?

**Comment by prastle** [comment]
get over this we cant fix March 2016
But we can now move forward!

Just myy two cents shutting up

**Comment by ron-murhammer** [comment]
@RoiEXLab I guess to me most users just want one map directory. Map backwards compatibility is pretty rarely broken as most mapmakers don't update their map that much after its stable. The only time this is largely relevant is if we decide to make mass non-backwards compatible changes to the XML.

**Comment by RoiEXLab** [comment]
@ron-murhammer I believe the latter case is already reason enough to think about it, especially because it's really not a big change.

**Comment by ron-murhammer** [comment]
@RoiEXLab So my thought would be to keep a shared maps area but instead update the shared maps directory to have a version number so we can choose to create a new shared maps directory if we need to make major map XML changes. Rather than having one under each install.

**Comment by RoiEXLab** [comment]
@ron-murhammer Yes, that's basically the plan to have a system wide folder with versioning.
Choosing the installation directory wouldn't really change something, as @DanVanAtta already mentioned we can modify the installer to keep the map files even after updating TripleA.
So no reinstalls for minor updates, but clear seperation for breaking updates.

**Comment by ron-murhammer** [comment]
Essentially what we did when we migrated maps to github is what I envision. Just have some parameter to provide a new default maps directory that we can change if needed for major releases.

**Comment by DanVanAtta** [comment]
@RoiEXLab this is starting to sound very similar to: https://github.com/triplea-game/triplea/issues/3104 (map major version tracking by the engine). Is your original suggestion here any different from #3104?

I'm not sure if the one under each install actually would work. If we force an upgrade of existing files, that means users need a parallel installation, and I think we figured most people don't do that, and don't want it. WE'd be stuck in the same situation where old map files are gone and can't be loaded for backward compatible game play.

**Comment by General-Dru-Zod** [comment]
I agree, most users would not like to download maps every time a new engine is installed. Also testing the engine versions would become problematic. We would most likely have less maps tested in any given version due to extra steps of downloading maps. That or there would simply be less testing of any given version to avoid downloading all the maps again.

@ron-murhammer suggestion to leave the current shared "downloadedMaps" is ideal from a tester, mapmaker and player standpoint.

**Comment by DanVanAtta** [comment]
This was not quite clear. Based on my understanding from #3030, the proposal woudl be something like:
- move game download folder to install folder location. Mark it as write-once for installation so it is not overwritten on new installs. This means one download, installers would not delete maps that are already present.
- on game engine versions that can't read 1.9 maps anymore, say v1.10, instruct users to install that game engine to a new location. With that would be a new maps folder. V1.10 could then potentially have a way to 'see' new maps that are available only to it. Part of the problem is that 1.9 maps when upgraded, 1.9 engines will always see, and when 1.9 maps go to 1.10, 1.9 engines will break.

TBH I think this is solved by putting format versions in the XML. This way 1.10 engine could read 1.9 maps. 1.10 engine would also know it can't read 1.11 maps, so we would have that issue solved as well.

**Comment by DanVanAtta** [comment]
@RoiEXLab are we missing any benefits from this idea/suggestion? It seems to me the fact we would have to instruct users to not overwrite an existing installation when they want to take advantage of multiple installation bases makes it seem overly complex. We could probably just as easily do what we did for 1.8->1.9 as @ron-murhammer suggested to rename the download folder.

**Comment by RoiEXLab** [comment]
@DanVanAtta The most straight-forward solution would be to use a folder being shared across users, and simply include subfolders with major version numbers then.

**Comment by DanVanAtta** [comment]
That basically sounds like the folder rename strategy. One problem though is that map major versions and game engine versions are not always 1:1. A v1.10 may not make sense for maps. Having multiple folder install locations is not very ideal either. 

Some problems to consider:
- Users upgrade to v1.10, then v1.9 maps would be orphaned; We are again to the hand-management of versions of engines and maps to keep things working. 
- v1.10 maps would still be visible to v1.9 engines if the latest map is downloaded.

**Comment by Cernelius** [comment]
No, don't do this.
Even if it is somewhat not overwritten on new installs, a mapmaker may have maps in development in it, and managing (also deleting) TripleA versions at the same time, so better keeping them set well apart, to avoid the risk or the fear of deleting your maps, and not to make things just harder to manage, manually.
Other than this, it is good to be able to install TripleA wherever you want but, when you do this, you don't normally want to move your maps folder too (also think in term of installing TripleA on an external key or something).
It is good to have TripleA in one place and the maps in another one; maybe they can stay in a same place, but surely not one inside the other.
Also, the current default places are the most logical, as there is the program and there are the maps, that are not programs.

**Comment by prastle** [comment]
Off topic but I'm still annoyed we couldn't make the new one version 10.000 .  😄  Yes  The downloaded maps separate works well.  If they need the new engine to run some of them then they need to read the mapmakers post.  ATM All maps are back compat except the ones released in the past few months that only work on the new engines.  These have all been detailed as required by the map makers as requiring the new engines to run the new version.  Will a breaking release require all maps to be rewritten?

**Comment by ron-murhammer** [comment]
@DanVanAtta @RoiEXLab Did we determine any action items out of this discussion? Or can we close this for now?

**Comment by DanVanAtta** [comment]
Closing for now;  I personally would rather us focus more on re-organizing maps completely than simply how we store them in folders.
