### ISSUE TITLE
Exception  OddsCalculatorPanel.java:431

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#312]
After opening battle calc, "calculate odds" button does nothing and generates the exception below. Currently not my turn, network game.

Exception: 
```
games.strategy.triplea.oddsCalculator.ta.OddsCalculatorPanel.access$25(Lgames/strategy/triplea/oddsCalculator/ta/OddsCalculatorPanel;)Lgames/strategy/engine/data/Territory;
games.strategy.triplea.oddsCalculator.ta.OddsCalculatorPanel$15.run(OddsCalculatorPanel.java:431)
java.lang.Thread.run(Thread.java:745)
```

**Comment by AlihassanProgrammer** [comment]
show your code

**Comment by DanVanAtta** [comment]
I thought I had pasted the full stack trace, looks not. The problem is not readily reproducible from a game save. Problem is perhaps existing or new since the last release, got this while playing on the latest master as of 4 days ago.

**Comment by DanVanAtta** [comment]
Closing, not much to go on for this one..
