### ISSUE TITLE
Dragon Wars crashes during sea battle

### ISSUE THREAD

**Issue by hispublic** [triplea-game/triplea#3134]
[autosaveAfterDwarvesNonCombatMove.zip](https://github.com/triplea-game/triplea/files/1755363/autosaveAfterDwarvesNonCombatMove.zip)

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)

It looks like a Dragon IV (Livonian AI) is attacking a Monoreme boat (Greenskin AI) in Sea Zone 70.  This shouldn't be a problem because air units in this map ARE PERMITTED to end their turn in a sea zone.  This leads me to believe that the battle ended in a tie (battles have limited rounds) and the dragon must have no moves left so it cannot retreat and cannot stay.  I've restarted it several times with the same result. I don't know how to change the random dice seed, so it must be rolling the same numbers each time the battle is fought?

### Do you have the exact error text? Please copy/paste if so
```
TripleA engine version 1.9.0.0.8304
triplea.engine.version.bin:1.9
Loading map: dragon_war, from: C:\Users\C\triplea\downloadedMaps\dragon_war-master.zip
Loading resources from the following paths: [C:\Users\C\triplea\downloadedMaps\dragon_war-master.zip, D:\TripleA\assets]
Loading map: dragon_war, from: C:\Users\C\triplea\downloadedMaps\dragon_war-master.zip
Loading resources from the following paths: [C:\Users\C\triplea\downloadedMaps\dragon_war-master.zip, D:\TripleA\assets]
Error: Should not be possible to have a normal battle in: Sea Zone 70 and have abandoned or only bombing there too.
java.lang.IllegalStateException: Should not be possible to have a normal battle in: Sea Zone 70 and have abandoned or only bombing there too.
	at games.strategy.triplea.delegate.BattleDelegate.setupTerritoriesAbandonedToTheEnemy(BattleDelegate.java:598)
	at games.strategy.triplea.delegate.BattleDelegate.doInitialize(BattleDelegate.java:174)
	at games.strategy.triplea.delegate.BattleDelegate.start(BattleDelegate.java:75)
	at games.strategy.engine.framework.ServerGame.startStep(ServerGame.java:502)
	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:397)
	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:266)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInNewThread(LocalLauncher.java:58)
	at games.strategy.engine.framework.startup.launcher.AbstractLauncher.lambda$launch$0(AbstractLauncher.java:51)
	at java.lang.Thread.run(Unknown Source)
Loading map: dragon_war, from: C:\Users\C\triplea\downloadedMaps\dragon_war-master.zip
Loading resources from the following paths: [C:\Users\C\triplea\downloadedMaps\dragon_war-master.zip, D:\TripleA\assets]
Loading map: dragon_war, from: C:\Users\C\triplea\downloadedMaps\dragon_war-master.zip
Loading resources from the following paths: [C:\Users\C\triplea\downloadedMaps\dragon_war-master.zip, D:\TripleA\assets]
Error: Should not be possible to have a normal battle in: Sea Zone 70 and have abandoned or only bombing there too.
java.lang.IllegalStateException: Should not be possible to have a normal battle in: Sea Zone 70 and have abandoned or only bombing there too.
	at games.strategy.triplea.delegate.BattleDelegate.setupTerritoriesAbandonedToTheEnemy(BattleDelegate.java:598)
	at games.strategy.triplea.delegate.BattleDelegate.doInitialize(BattleDelegate.java:174)
	at games.strategy.triplea.delegate.BattleDelegate.start(BattleDelegate.java:75)
	at games.strategy.engine.framework.ServerGame.startStep(ServerGame.java:502)
	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:397)
	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:266)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInNewThread(LocalLauncher.java:58)
	at games.strategy.engine.framework.startup.launcher.AbstractLauncher.lambda$launch$0(AbstractLauncher.java:51)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by ron-murhammer** [comment]
@FrostionAAA Have you seen this issue before?

**Comment by FrostionAAA** [comment]
Well … the ”Should not be possible to have a normal battle in: ??? and have abandoned or only bombing there too.”-error is a returning error. I have not seen it lately, but I have seen it a number of times before.

I have seen it relate to sea territories, territory ownerships and whose units are inside a contested sea territory. In Age of Tribes it occurred in relation to the Nukes and their spawning of enemy “Sea-Radiation” (technically a suicide sea unit) inside enemy sea territory. And here in Dragon War, apparently it can happen when a sea unit is attacked by an air unit that stays in the territory after battle.

Both maps have "Abandoned Territories May Be Taken Over Immediately" value="true"
If changing this to false should fix the issue, please say so.

I have not been able to reproduce the error on either of the maps, and I have never had a save game with the error waiting to happen. So if anyone has such a save game, it would be super.

**Comment by hispublic** [comment]
@FrostionAAA  This is the smoking gun!!!  I just attached every auto-save from that play-through that was still there when the error hit. The saved game you are looking for should be in this stack of saved games.  The closest save with the error waiting to happen seems to be the AfterGreenskinsNonCombat save.  Start that save and look at the bay by the Elves, south southwest on the map.  You'll see a boat that gets attacked by a Livonian Dragon, which triggers the error.  I have seen once with this save that the dragon didn't attack but every other time, I had the error.  Thanks for checking it out.

[tripleA DW crash saves.zip](https://github.com/triplea-game/triplea/files/1759946/tripleA.DW.crash.saves.zip)

**Comment by FrostionAAA** [comment]
Thank you @hispublic for the savegames. They really helped a lot.

What I notice is that the sea territory where the battle takes place is actually not owned by the greenskins player as one might expect, but instead owned by a third party (pirates), and I suspect that this creates the issue/error when the battle step begins.

But the error can be avoided if you (use a save that is before the red player/lionia combat move with the dragon) go EDIT and change the ownership of the seazone to greenskins. Then the battle will commence with no error.

I have clue why, but "Abandoned Territories May Be Taken Over Immediately" set to false seems to prevent the breakdown error.

This is the only change in the next version 1.2.4 of Dragon War version, and it is already downloadable. This issue can be closed.

**Comment by ron-murhammer** [comment]
@FrostionAAA Cool. Glad that property resolved it. I still think there are some funky edge cases around contested territories especially with air units but as long as we don't have specific cases, I consider it low priority to revisit them.

**Comment by prastle** [comment]
I miss this map 😢   Iwsih it was live more thanks for the work @FrostionAAA

**Comment by ron-murhammer** [comment]
@prastle If you joined the lobby once in a while... you'd see that someone is playing it right now and they are in round 18 :)

**Comment by prastle** [comment]
probably passworded
again
