### ISSUE TITLE
Multiplayer map missing is over handled

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3144]
Seems to be different from single player case, in multiplayer case if starting a bot game with a missing map, we get many pop-ups:
![multiplayer](https://user-images.githubusercontent.com/12397753/36638166-e1977878-19a1-11e8-8bec-9874fd515ec4.png)

This would ideally be simplified to just the one error message saying the map is missing (no console, no 'failed to start game' error message)-+

**Comment by RoiEXLab** [comment]
@DanVanAtta 
I believe one popup is being caused by a server side error, and one by a client side error.
I believe I had to deal with this when fixing the minor version incompatibilies with bots.

**Comment by DanVanAtta** [comment]
That would make sense as far as the behavior is different from a single player game. 

I want to say it used to work so that we'd only see the one pop-up. Regardless, the current behavior is not right; there should only be the one dialog.
