### ISSUE TITLE
Enforce CodeCov? Remove it? 

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3166]
CodeCov keeps getting in the way, I think it's time to remove it. It creates noise in PR's, email, false positives. Meanwhile we are not likely to start requiring branch coverage *any* time soon.

In this issue, I'm looking for some ***really***  good practical benefits to code coverage, or please let us remove it. It creates  noise. I miss the days when a green check meant the build passed

Assigning to all for some final feedback. IMO there are two good choices:
- remove it
- turn to enforcing mode

*edit*: shorten and consolidated

**Comment by DanVanAtta** [comment]
In this issue, I'm looking for some really good practical benefits to code coverage. I'm pretty clearly tired of the noise it creates, i would like the plugin removed as it has not proven it's value (meanwhile it is a cost, I miss the days when a green check meant the build passed)

**Comment by DanVanAtta** [comment]
Assigning to all for some final feedback. IMO there are two good choices:
- remove it
- turn to enforcing mode

We are in a de-factor third option where we use it but ignore it (or not; but officially it is ignored). It does create noise in the meantime; so this is a really the group indecision decision IMO. Either way with removal or turning to enforcing I think it is good. Enforcing IMO is more ideal even, that is my real preference.  Otherwise let's please remove it.

**Comment by ssoloff** [comment]
I don't remember if this question was ever answered: can we disable the **codecov/project** check but leave the **codecov/patch** check enabled?  The former is a problem due to non-determinism in some tests; the latter is useful information and encourages PR authors to write tests.

Alternatively, does Codecov allow you to adjust the default thresholds?  Right now, if **codecov/project** is negative, it fails the build.  Can we change that threshold to, for example, -0.03% (or something sufficiently small but large enough to account for test non-determinism)?

**EDIT:** [This](https://docs.codecov.io/docs/commit-status) looks promising.

**Comment by ron-murhammer** [comment]
Well I gave it a shot but not sure if its working. I created a team yaml with the following:
`coverage:
  status:
    project: off
    patch: off`

**Comment by ssoloff** [comment]
@ron-murhammer Looks like that worked for #3173. :+1:

I would propose:

* Change `project` threshold to 1%.
* Keep the default `patch` configuration (which sets the threshold to the project baseline [currently ~20%]).

I'm still of the opinion that a failing `patch` status is a useful red flag.  If I see test coverage below this threshold, I want the PR author to state what testing they did manually.

**Comment by ron-murhammer** [comment]
@ssoloff Yeah, looks like it did work. I'm fine with those suggestions as that should minimize the noise.

@DanVanAtta @RoiEXLab Any thoughts? Agree with that configuration?

**Comment by DanVanAtta** [comment]
@ron-murhammer @ssoloff good work :+1: 

I think now the conversation starts for what kind of minimum bar for a red build due to coverage, and what that means : )

@ssoloff one problem with same coverage, refactoring can be dangerous. Most of the mass refactorings I've been doing I've tested as a single branch and then split up. Some things got through and one spike I failed to test well. In any of these cases though the coverage was same, maybe better due to removed code, and problems were introduced none-the-less.

**Comment by RoiEXLab** [comment]
I'm fine with the changes 👍

**Comment by ssoloff** [comment]
Just asking since this issue was closed...  Are we leaving the Codecov configuration as-is (both project and patch status off)?  Or was it modified, and we just haven't seen it yet because no new PRs have been opened since?

**Comment by DanVanAtta** [comment]
Now that thresholds are zero, let's pick up discussion in: https://github.com/triplea-game/triplea/issues/3188
