### ISSUE TITLE
SZ Numbers dont display with hover When Using .9319

### ISSUE THREAD

**Issue by prastle** [triplea-game/triplea#3168]
### My Operating System:
Win 10
### Engine version:
1.9.0.0.9319
### Map name and version:
New World Order 1.8.7
### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Hover over any Sea Zone.  Territories still work fine.  Check and it works fine for SZ using 1.9.0.0.8941
### Any additional information that may help:
I checked and it still works fine for SZ using 1.9.0.0.8941 .
I am unsure how many other maps are affected.

**Comment by prastle** [comment]
It also affects Revised and Big World.

**Comment by ron-murhammer** [comment]
@prastle Ok. I was able to reproduce it. I'll take a look. Strange that it only happens on some maps but not others.

**Comment by prastle** [comment]
@ron-murhammer  I haven't looked at all of them.  I just noticed while watching DayMar playing some NWO.

**Comment by ron-murhammer** [comment]
@prastle I'm pretty sure I know what the problem is. Hope to put a fix up shortly.

**Comment by prastle** [comment]
I figured ya would no biggee.  Just really noticeable in NWO since the sz are not numbered as well?

**Comment by DanVanAtta** [comment]
![verify](https://user-images.githubusercontent.com/12397753/36714489-54d966c4-1b47-11e8-9ac9-901781b62f20.png)

Lookin good now :+1:
