### ISSUE TITLE
Resource Images Missing

### ISSUE THREAD

**Issue by General-Dru-Zod** [triplea-game/triplea#3187]
### Engine version
9428

### My Operating System
windows 10

### Map name
Bad-Ass 4-Nation FFA v.1.6.0.20

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Got an error for missing techTokens_large.png which prevented purchase screen from opening. Because techTokens are purchased in this map and they use techTokens_large.png. This image is not included in this assests\resources folder anymore .

### Do you have the exact error text? Please copy/paste if so
I added a resources folder to my game folder and added the old techTokens_large.png to the folder. Is fine now.

### Instead of this error, what should have happened?
Some other maps might get errors if the images they use from the assets\resources folder are missing. I suggest including replacements for all the images that were in there previously. Even if those images are different now, just so it loads something and is error free.

**Comment by ron-murhammer** [comment]
Yeah, I meant to definitely have a techTokens_large.png just had it named wrong. It should be fixed. If someone wants to take the old *_large images and resize them then I'm glad to add additional ones back in. Closing this since it should be resolved now.
