### ISSUE TITLE
CodeCoverage Min Thresholds

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3188]
Picking up from:
https://github.com/triplea-game/triplea/issues/3166#issuecomment-369093614

> - Change project threshold to 1%.
> - Keep the default patch configuration (which sets the threshold to the project baseline [currently ~20%]).

> @ssoloff I'm still of the opinion that a failing patch status is a useful red flag. If I see test coverage below this threshold, I want the PR author to state what testing they did manually.

**Comment by ssoloff** [comment]
Bumping...

**Comment by DanVanAtta** [comment]
This is a pretty major item.
I think it would be the right thing to do, I don't know how else we can start improving coverage.

Some problems to consider:
- UI only updates, some code should not be covered. Maybe we make the coverage requirements sub-project specific, and have no requirement for the UI client layer?
- Some code needs re-design before we would *want* to test it. We also have cases of bug tweaks that are one-liners in non-tested code. I think this is a problem, but perhaps it's not a deal breaker. In general I think new functionality we should be trying to put in new, overly small classes that we can test and then plug in to the existing system. At some point, we can then start to combine this mini-modules, and we would replace the code with very monolothic, procedural untested to well organized, and very distributed and well tested components.

So really, I wonder:
- how do we deal with UI only changes, code that should not be tested with unit tests
- on the other end of the stack, how do we deal with system integration tests, something like a low-level DAO where the best test is a system-integration test.
- how do we deal with refactoring an bug fixes?

-------

I think this is probably all very workable if we can tune the threshold per sub-project. Integration components like lobby client or database DAO, and UI code, are likely to live in their own sub-projects anyways, so the two concepts would dovetail nicely.

**Comment by ssoloff** [comment]
> I think this is probably all very workable if we can tune the threshold per sub-project.

I didn't see anything in the Codecov docs that would suggest this is supported.  I don't think Codecov knows anything about Gradle, or any build system for that matter.  We could probably configure Gradle to generate code coverage reports on a subproject basis, and upload them all during the Travis build.  However, I'm pretty sure Codecov simply aggregates all the reports you send it, so there still wouldn't be any way to distinguish between subprojects.

@ron-murhammer When you set up the Codecov team YAML for #3166, did you notice that anything more than one set of thresholds can be applied to a single repo?

**Comment by ron-murhammer** [comment]
@ssoloff Correct, my understanding is that you can only have a separate YAML per repo not any kind of gradle sub-projects.

**Comment by RoiEXLab** [comment]
Codecov is no longer mandatory. Closing this...
