### ISSUE TITLE
@NotSafeToRefactor - annotate places where engine breaks

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3203]
From https://github.com/triplea-game/triplea/pull/3202
>  it was determined that renaming fields in AggregateResults did not break save game compatibility

This gives me the idea that we would do well to annotate anything that we cannot change due to compatibility. It is not a full proof solution, but it'll be at least *really* easy to tell when we're updating 
something that is going to break compatibility.

We may also want to distinguish the types of compatibility:
```
@NetworkCompat
@SaveGameCompat
@MapCompat
```

(I think we may already have @MapCompat as @MapSupport)

Ideas/thoughts on this? Anyone willing to help if sounds good?

**Comment by ssoloff** [comment]
How about one annotation with an array enum value that can be used to describe the reason?

```java
@Retention(SOURCE)
@Target(TYPE)
public @interface NotSafeToRefactor {
  RefactorConstraint[] value();
}
```

```java
public enum RefactorConstraint {
  SAVE_GAME_COMPATIBILITY, MAP_COMPATIBILITY, NETWORK_COMPATIBILITY;
}
```

Example usage:

```java
@NotSafeToRefactor({RefactorConstraint.SAVE_GAME_COMPATIBILITY, RefactorConstraint.NETWORK_COMPATIBILITY})
public class CanalAttachment extends DefaultAttachment {
```

---

Actually, it might be more useful to list what types of refactoring cannot be performed.  For example, "fields cannot be renamed" seems more useful than stating "save game compatibility" with the obvious follow up question, "what does that prevent me from doing?"

Then the previous example might be instead:


```java
@NotSafeToRefactor({RefactorConstraint.RENAME_FIELD})
public class CanalAttachment extends DefaultAttachment {
```

**Comment by ssoloff** [comment]
Actually, that last suggestion could get out of hand because if a type is serialized to a save game, there's several things you can't do (move package, rename type, rename fields, etc.).  That would be a pain to list on all such types.  So maybe the original suggestion is better, and we can just document what refactorings cannot be performed in the Javadocs for each reason/constraint.

**Comment by DanVanAtta** [comment]
Let's keep it easy to use, I'd like to avoid parameters to the annotations.

IMO best to document why not safe (ie: what is the coupling?), instead of what can't be done. The not safe things can be documented in the annotation itself.
