### ISSUE TITLE
Next version number?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#323]
Will next version actually be 2.0.1 or 1.8.0.11 (@veqryn,  @ron-murhammer)?

**Comment by ron-murhammer** [comment]
@DanVanAtta I was thinking 1.9

**Comment by DanVanAtta** [comment]
My proposed build number sequence would be:
```
1.9.1.0 = next release
1.9.1.1 = first development build after next release
1.9.2.0 = patch release
1.9.3.0 = next major release
1.9.3.1 = development build
1.9.3.2 = development build
2.0(.0) = first release when save games are (more) engine agnostic
2.0(.1) = first development build based on the 2.0.0 relesae
2.1(.0) = patch release for 2.0
2.1(.1) = development build
3.0(.0) = major release
3.0(.1) = dev build
3.1(.0) = patch release
3.1(.1) = dev build
3.2(.0) = patch release
3.2(.1) = dev build
4.0(.0) = major release
```
To explain the parentheses, for example: `2.0(.1)`
`2.0` == public facing version number
`2.0.1` == developer facing version number.


Effectively the idea is to combine the developer/public facing version numbers into one (quoting @veqryn  in #129, the last time we discussed the topic):

> End user visible version number: 1.0, 1.1, 2.0, 2.1, 2.2, 3.0, etc.
:
Developer visible version (following semantic versioning): 2.5.5, 6.0.5, 7.0.3, 8.0.5, 8.0.7, 8.0.9, etc.

One extra thing to mention, I suggest we switch to the "2.0", "3.0" sequence when we update how we save games, so save games can be (more) engine agnostic. At that time we could also drop the "old jars", and it would be a natural transition from "1.9.x" to 2.0

**Comment by DanVanAtta** [comment]
@ron-murhammer , @veqryn , a second question. Do we care if the next version is "serialization" compatible? I think for the moment the next version is, but if it turns out to not be compatible with 1.8.0.9 games, are we going to hunt things down and revert, or instead move forward and publish a new "old" jar? My vote is to go down the second route if reasonably necessary.

**Comment by ron-murhammer** [comment]
@DanVanAtta My thought is that its fine if the next version (1.9) isn't "serialization" compatible but that we still want to try to maintain lobby compatibility.

**Comment by veqryn** [comment]
Did we actually break compatibility with current gamesaves?
If we didn't, then we need to continue with 1.8.0.x
(And lets not break compatibility just for fun, but actually deliver some real features at the same time, otherwise it is not worth it to our users.)

After we break compatibility, then we should switch to the new versioning system we talked about in some other ticket, where only the first 2 numbers represent a compatibility break (instead of the first 3), and then the last number represents the "build" number given to us by the builder-bot.  I would also start us off with 2.0.x.x once we do break compatibility, just to represent the new management of triplea (you guys).

**Comment by DanVanAtta** [comment]
> "Did we actually break compatibility with current gamesaves?"
We certainly have tried to avoid it. Given that compatibility here could be something as tiny as renaming a variable, I can only saw we haven't knowingly done so on this release. I've been playing the latest version of master in the lobby/live, and have not yet had problems, so there is indication we have not as well.

> "If we didn't, then we need to continue with 1.8.0.x"
Why, the 1.8 is pretty meaningless, and the 1.9 I think would put our "new management" mark on this release just as effectively as going to 2.0.

> "After we break compatibility, then we should switch to the new versioning system "

I don't agree with this. When we move to two numbers, I would like them to indicate major+minor release - not  compatibility. My biggest concern and objection is that once we start incrementing from "2.0.x.x", it'll be confusing as sin why/when we would ever move to version "3.0.x" or "4.0.x". My fear then is we are stuck with a useless leading "2" as part of the version number from then on.

So, I would like us to move to version 1.9.0.x next, regardless of compatibility. @veqryn , @ron-murhammer , this is a very important point. Regardless of compatibility. Watching the user base over the last few releases, particularly this last one, most do not even *know* that there is cross-version compatibility. If you were to hang out in the lobby, there were many people saving up and launching old game versions even though 1.8.0.11 was compatible with 1.8.0.7, yet folks were behaving as if they weren't. So in effect, ,our attempts to have compatibility is a bit of a failed feature/attempt. In practice we're complicating mostly just  our lives only as developers.

**Comment by veqryn** [comment]
I disagree @DanVanAtta.

If we bump anything but the last number (under the current versioning scheme and code) then everyone's savegames will suddenly not work.  They will then be presented with a well meaning but probably confusing message explaining why, asking if they want to load it using a previous version.  They mindlessly click OK and then suddenly they have 2 copies of TripleA running, and the one that is now on the screen can not start new games.

It is a bad user experience, and even if we massage and ameliorate it, it will still be not the greatest experience.  So it is best done only when we have something serious to offer users, such as major new features for players and map makers, serious bug fixes, etc.


If your concern is that you feel like enough effort has gone into the engine since 1.8.0.11 that it somehow qualifies for 1.9.0.x, then I would suggest we take a different path altogether:

Separate the "software package versioning" from the "user visible versioning".  
User visible versioning exists almost purely as public relations.  It is there to tell the user that this is a new version, and some amount of work has gone into it, and some new features are available, etc.
Software package versioning exists primarily to tell developers about compatibility.  The best example is Semantic Versioning, which is my favorite (major.minor.patch).  It doesn't matter if you literally rewrote every line of code, solved every bug, fully completed all documentation, spent 40 hours per day for 10 years working on it.  If no public API changed, and no features were added or changed, then you can not increment your version number's major or minor, and have to increment it by only a patch digit.

The public facing version could have just 2 digits in it, while our semantic versioning could 3 or 4 digits (4 if we have the final number be the build number that builder-bot adds).  
For the dev version, the major number would increase whenever we break compatibility with savegames, while the minor number would increase for non-breaking new features or changed behavior, and the patch number for non-breaking bug fixes and minor stuff.

**Comment by DanVanAtta** [comment]
> If we bump anything but the last number (under the current versioning scheme and code) then everyone's savegames will suddenly not work. They will then be presented with a well meaning but probably confusing message explaining why, asking if they want to load it using a previous version. They mindlessly click OK and then suddenly they have 2 copies of TripleA running, and the one that is now on the screen can not start new games.

I don't disagree with that scenario, but in practice this is not what happens. The user base is very diligent to launch save games in the correct version, so this feature is ironically never used. It's was interesting to watch players agree to launch 1.8.0.9 in the lobby to continue a save  when we had launched 1.8.0.10. So please realize, that in practice, the upgrade pain winds up happening at every release, despite having put in a feature to mitigate that problem. This is part of why I think it's so important we go to a non-java serialization format, so we can upgrade the engine without coupling it to map xmls and game saves.

**Comment by DanVanAtta** [comment]
@ron-murhammer , @veqryn  - this wound up discussing much more about how to version number, rather than what the next will be. Perhaps I should not have been surprised.

Perhaps we can approach this from a requirements point of view. Define and agree upon what requirements must be satisfied, then perhaps a versioning scheme will be more obvious. 

For requirements, I see a needs for:
- a number that indicates to players, this is a new version you should go and download now
- a number that indicates to players that they can still play their old save games. I would like this number to be dropped ASAP, but we must still have it for now IMO. We can take the opportunity to clarify what save game compatibility means to our base while we explain the new numbering version.
- the builder bot number, this way a tester can tell us that they installed a specific development build number, and we'll know which commits were or were not in that release

In our case, I just don't see much benefit to semantic numbering. This project is centered around major and relatively rare releases, and it's bundled together as a monolothic jar (whether it be the lobby, client, or a bot). Given that, I don't see how knowing that one triplea.jar is byte compatible with another is that useful. I'm also taking into account that users tend to manage which version they are playing themselves, and that we will be working on cross-compatibility enhancements with high priority. @veqryn  - I'm curious what value we would could get from semantic numbering, I'm pretty sure I'm probably overlooking something.

**Comment by DanVanAtta** [comment]
> "For the dev version, the major number would increase whenever we break compatibility with savegames, while the minor number would increase for non-breaking new features or changed behavior, and the patch number for non-breaking bug fixes and minor stuff."

I need to consider this more.. It does seem like some book keeping is going on. @veqryn  What would happen if we make it so save games are always going to be compatible with future versions? 

Second, I see things a bit differently. If we have two numbers for our users, and one of them represents continued save game compatibility, then that would be redundant to the major number of the dev version. This means we simply could just use the public facing version instead.

This then leaves the minor and patch version numbers. For us, how important is it to know the difference between the two? We already get a patch version number for free thanks to the builder bot. If we do not distinguish between minor and patch versions, we save a bit on overhead and book keeping.

Thus, that gets me back to the original proposal, I think we can re-use the public version number and append digits to it to then form the developer version number.  If we want to distinguish between minor and patch, we'll have 4 numbers total. Otherwise if we lump minor and patch number together, we'll have 3 numbers. The leading 2 numbers will always be the public facing version number.

I see the difference in your proposal @veqryn  as having 5 numbers total, grouped between two numbers.  In my proposal, we would still have two distinct numbers, except one would always prefix the other.

**Comment by veqryn** [comment]
Honestly, I could be fine with just about decent version-ing system that is at least as good as what we currently have.

But I do still disagree about the savegame compatibility.  
Two points to make: 
1. Those users you see on the lobby, carefully launching a 1807 gamesave, are not our full user base.  There are lot of users who are not in the lobby, who play single player and/or play-by-forum only, who will be encountering a different situation as they upgrade and try to play old game saves.
2. Having lived through somewhere around 10+ previous rounds of save-breaking releases, and 15+ previous rounds of non-save-breaking releases, over the past 6 years, I would definitely say that the save-breaking releases are a much much worse experience for our users than the non-save-breaking releases.  I do not want to force that on our users when we have absolutely zero reason to, where literally the only change in the engine visible to them is a slightly better incarnation of pro-ai.

**Comment by DanVanAtta** [comment]
The lobby example was more to demonstrate that many users do not understand the save game compatibility feature. When releases happen, it's a good source of quick feedback. About point number 2, you have convinced me.

**Comment by DanVanAtta** [comment]
Okay, in consideration of the discussion, and these requirements (dimensions):
1. save game compatibility
2. release number
3. build number

@veqryn , @all: What are your thoughts on this sequence?  (please note, no changes from current version scheme until we next break save games)
```
1.8.0.12 = test release compatible with 1.8.0.11
1.8.0.12(.build) = development build after 1.8.0.12 
1.8.0.13 = stable release compatible with 1.8.011
1.8.0.14 = test release compatible with 1.8.0.11
1.8.0.15 = stable release compatible with 1.8.011
1.8.0.16 = test release compatible with 1.8.0.11
1.8.0.17 = stable release compatible with 1.8.011
1.9.0(.0) = first release where save games are not compatible with 1.8.0.11
1.9.0(.build) = first development release after 1.9.0(.0)
1.9.1(.0) = next release still compatible with 1.9.0 save games
1.9.1(.build) = first development build after 1.9.1.0
1.9.2(.0) = next release compatible with 1.9.0
1.9.2(.build) = development release
1.9.3(.0) = next release compatible with 1.9.0
1.9.3(.build) = development release
1.10.0 = next release that breaks save games
1.10.1 = release compatible with 1.10.0
1.10.2 = release compatible with 1.10.0
1.11.0 = save games broken
1.11.1 = release compatible with 1.11.0
2(.0) = first release where saves are encoded in a cross-engine format
2(.build) = first development release after 2.0
3(.0) = next release 
3(.build) = development release
4(.0) = next release
4(.build) = development release
```

**Comment by veqryn** [comment]
looks good

**Comment by ron-murhammer** [comment]
Works for me.

**Comment by DanVanAtta** [comment]
Version number list put in wiki for future reference, closing: https://github.com/triplea-game/triplea/wiki/Release-Version-Numbers
