### ISSUE TITLE
integration tests are run as source, not test

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3279]
I noticed we have the integration tests set up as source code, instead of test code:

https://github.com/triplea-game/triplea/blob/master/game-core/build.gradle#L65

```
sourceSets {
    integTest {
        java.srcDir 'src/integ_test/java'
        resources.srcDir 'src/integ_test/resources'

        compileClasspath = sourceSets.main.output + sourceSets.test.output + configurations.testCompileOnly + configurations.testRuntime
        runtimeClasspath = output + compileClasspath + configurations.junitPlatform
    }
}
```

There seems to be some extra complexity here, is there any reason to not set these tests up as a regular old tests? Also of note, we probably should not allow 'integ_test' to have visibility to 'test', probably best to not mix the two.

A second question I'm wondering about, why do we launch `ConsoleLauncher`? The javadoc for it says it is a tool to run tests from a console, it seems to exit right away when run from gradle.

```
task integTest(type: JavaExec, dependsOn: [compileIntegTestJava]) {
    group = LifecycleBasePlugin.VERIFICATION_GROUP
    description = 'Runs the integration tests.'

    classpath = sourceSets.integTest.runtimeClasspath
    main = 'org.junit.platform.console.ConsoleLauncher'
    args '--details', 'none'
    args '--reports-dir', "$buildDir/integ-test-results/junit-platform"
    args '--scan-classpath', sourceSets.integTest.output.classesDirs[0]
}
```
Does anyone have more context into this, why console launcher comes into play?

**Comment by RoiEXLab** [comment]
The console launcher is needed to run multiple test tasks with different source sets.
It's a Junit 5 tool.

**Comment by ssoloff** [comment]
> I noticed we have the integration tests set up as source code, instead of test code:

Not sure what you mean here.  In Gradle, everything is a "source" set.  AFAIK, there's no such thing as a "test" set.  `main`, `test`, and `integTest` are all source sets.

> Also of note, we probably should not allow 'integ_test' to have visibility to 'test', probably best to not mix the two.

I asked that question [here](https://github.com/triplea-game/triplea/pull/1773#discussion_r119212797), but assumed you wanted integration tests to be able to reference test-only utilities that are also used by the unit tests.  Since that time, I'm pretty sure some of the integration tests do indeed use utilities under _src/test/java_.

> Does anyone have more context into this, why console launcher comes into play?

To augment @RoiEXLab's answer, we're using that external process because, at the time we introduced JUnit 5, there was no native Gradle support for running JUnit 5 tests.  The JUnit 5 Gradle plugin is still in kind of a hackish state, and it doesn't extend easily to other source sets beyond `test`.

**Comment by RoiEXLab** [comment]
> Not sure what you mean here. In Gradle, everything is a "source" set. AFAIK, there's no such thing as a "test" set.

Intellij actually makes a difference there, although I'm not sure on the effect it has.
That's probably where his assumption comes from. Eclipse doesn't makes this seperation either.

> The JUnit 5 Gradle plugin is still in kind of a hackish state, and it doesn't extend easily to other source sets beyond `test`.

To be fair the Junit 5 team worked closely with the guys at gradle to allow for better support. Full support is [planned as of Gradle 4.6](https://github.com/gradle/gradle/issues/1037#issuecomment-362598058)

**Comment by DanVanAtta** [comment]
>> I noticed we have the integration tests set up as source code, instead of test code:

> Not sure what you mean here. In Gradle, everything is a "source" set. AFAIK, there's no such thing as a "test" set. main, test, and integTest are all source sets.

Not quite @ssoloff ; each source set has both 'java' and 'test' sources, for example:

```
sourceSets {
    integTest {
        java.srcDir 'src/integ_test/java'
        test.java.srcDir 'test/integ_test/java'
        resources.srcDir 'src/integ_test/resources'
        test.resources.srcDir 'test/integ_test/resources'

        compileClasspath = sourceSets.main.output + sourceSets.test.output + configurations.testCompileOnly + configurations.testRuntime
        runtimeClasspath = output + compileClasspath + configurations.junitPlatform
    }
}
```
Each source set has both a 'prod' and a 'test' area. If we add 'testCompile' dependencies they are added to the test part of the source set. In our case we've hacked the crap out of it basically and combined the two paths together. This would not be visible in eclipse, eclipse is known for mixing the path of test and source, it does not distinguish between the two. IntelliJ does keep the two paths different, working in that project it can be observed the integ_test will default to a 'prod source' type, not a 'test source'. Happily due to our build ordering we exclude the integ_test source, but if that were to change then in theory we'd package the integ_test code (potentialy brittle).

**Comment by DanVanAtta** [comment]
>> Also of note, we probably should not allow 'integ_test' to have visibility to 'test', probably best to not mix the two.

> I asked that question here, but assumed you wanted integration tests to be able to reference test-only utilities that are also used by the unit tests. Since that time, I'm pretty sure some of the integration tests do indeed use utilities under src/test/java.

For context, I had little involvement with the gradle build file, I did not set up how integ tests are done. Shared test utilities between the two should probably be done through a sub-project inclusion, there is overlap between integ_test and test, it's a bit hard to trace/confusing.

**Comment by DanVanAtta** [comment]
>> Not sure what you mean here. In Gradle, everything is a "source" set. AFAIK, there's no such thing as a "test" set.

> Intellij actually makes a difference there, although I'm not sure on the effect it has.
That's probably where his assumption comes from. Eclipse doesn't makes this seperation either.

We don't really see any impact here as we merged the test+prod classpaths for integ test and then called it all prod code. It's not a clean configuration, looking to split the project up more properly this is becoming a problem as the not clean configuration can't be readily ported into standard java project structure. 

It's also really weird that integ_test, prod code, has a dependency on test code.

**Comment by ssoloff** [comment]
> Each source set has both a 'prod' and a 'test' area.

Could you provide a reference, please?  I'm not aware of that feature in Gradle.  If that is the case, I'm confused why there are separate `main` and `test` source sets rather than a single `main` source set that has both prod and test slices?

---

> `test.java.srcDir 'test/integ_test/java'`
> `test.resources.srcDir 'test/integ_test/resources'`

Hmm, not sure what these lines in the `integTest` source set configuration are supposed to do.  It's almost as if they're changing properties in the `test` source set, which seems kind of strange.  If you print what these properties refer to within the `integTest` source set configuration, it does indeed appear it's the `test` source set:

```
println "test = $test"
println "test.java = $test.java"
println "test.resources = $test.resources"
```

produces:

```
test = source set 'test'
test.java = test Java source
test.resources = test resources
```

You get the same result if you prefix those expressions with `sourceSet.`, implying `test` above is really the `test` source set and not a property of `integTest`.

---

Here's the build file from the official Gradle (4.5.1) Java integration test sample:

```gradle
apply plugin: 'java'

repositories {
    mavenCentral()
}

sourceSets {
    integrationTest {
        java.srcDir file('src/integration-test/java')
        resources.srcDir file('src/integration-test/resources')
    }
}

dependencies {
    testCompile 'junit:junit:4.12'
    integrationTestCompile 'commons-collections:commons-collections:3.2.2'
    integrationTestCompile sourceSets.main.output
    integrationTestCompile configurations.testCompile
    integrationTestCompile sourceSets.test.output
    integrationTestRuntime configurations.testRuntime
}

task integrationTest(type: Test, dependsOn: jar) {
    group 'Verification'
    description 'Runs the integration tests.'
    testClassesDirs = sourceSets.integrationTest.output.classesDirs
    classpath = sourceSets.integrationTest.runtimeClasspath
    systemProperties['jar.path'] = jar.archivePath
}

check.dependsOn integrationTest
```

It's somewhat different from ours because it looks like they run their integration tests against the final jar rather than using _.class_ files, as the unit tests do.  But, other than that, we're pretty close.  We can probably improve our dependency configuration to be more declarative.

**Comment by DanVanAtta** [comment]
@ssoloff good example, I was wrong/confused by default source set vs properties of source sets.

> Hmm, not sure what these lines in the integTest source set configuration are supposed to do. It's 

the 'test' prefix would just extend the path presumably, eg: `sourceset.integTest.test.java.srcDir`

---------

Okay, I think we have a mixture of a few problems:

- it looks like by convention test code will have 'test' in the source set path. This makes IDEA recognize the folder as a 'test' sources. IDE wars aside, I do trust IDEA to do gradle parsing correctly; it's dangerous when you think you are more correct compared to an industry standard tool backed by a team of a hundred+ developers, usually the tooling gets it right.

- Junit5 hackery. It looks like basically we are executing junit via java command more than gradle itself.  There is a very big difference for the task type:
```
task integrationTest(type: Test, dependsOn: jar) {
```
We do not use 'Test' type but the junit 5 launcher. I think I understand this is more where I ran into troubles perhaps than actual pathing issues.


> Here's the build file from the official Gradle (4.5.1) Java integration test sample:

Where is that file from? Is it conventional for integration tests to be treated more like source code? It is a bit moot as the classpath is custom.

-----------

Open questions/items:
- can we get 'test' in the integ source path name so the folder can be properly identified as a sources root?
- should integ_tests have source code dependency on unit test? Test-utilities we can share via sub-project (and we will need to do that anyways), so I think the answer is no. This is actually a bit more significant, working through the integration tests I'm not sure we kept a clean split. For example utilities to create data are used in both unit and integration tests, moving the integration tests to a new sub-project I see the unrelated client tests that shared the same data now have problems in their unit test. Basically, "User" is a database object, and we use it for client code, the unit tests that create that are shared with the integration tests. This is overall not good, highlighted after trying to split lobby project.

**Comment by ssoloff** [comment]
> Where is that file from?

The [Gradle 4.5.1 complete distribution](https://services.gradle.org/distributions/gradle-4.5.1-all.zip).  It's in the _samples/java/withIntegrationTests_ folder.

---

> can we get 'test' in the integ source path name so the folder can be properly identified as a test sources root?

I think finding an IntelliJ solution to this problem is preferable to tinkering with the Gradle build script.  This [question](https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000608270-Gradle-additional-test-source-folders) appears to be related, and the linked issue looks promising.

---

> Basically, "User" is a database object

I view `User` as a lobby domain object.  It was a convenient abstraction to replace passing around three different pieces of user-related data (name, IP, and MAC) that previously existed.  In all cases, I believe `User` instances are created in the service layer.  They are only consumed by the database layer; there shouldn't be any cases where a DAO returns a `User` instance.  I believe `DBUser` is used in those cases.

There's a smell having those two classes, but I think we're stuck with `DBUser` for the time being because it's serialized between the server and the client, and changing it will break compatibility.

**Comment by DanVanAtta** [comment]
>> can we get 'test' in the integ source path name so the folder can be properly identified as a test sources root?

> I think finding an IntelliJ solution to this problem is preferable to tinkering with the Gradle build script. This question appears to be related, and the linked issue looks promising.

Adding more complexity to the build file is not very attractive. The customizations in the build file make updating it not so nice either. An update of: `java.srcDir` -> `test.java.srcDir` does cause the source folder to be labelled properly as test, though going that route I ran into issues with the test execution task which is of type 'java', not 'test'.

The real answer here I think is to wait for Junit5 + Gradle integration to be better.

------------------

> I view User as a lobby domain object. It was a convenient abstraction to replace passing around three different pieces of user-related data.

I agree that it is a lobby domain object, it's coupled to the DB layer. But, splitting the lobby integration tests to a sub-project I ran into a shared dependency problem where the client layer also depended on the same object. This means that the client uses the same object representing what it reads from the wire from the lobby. 

This is related to the 'test' and 'integ-test' folder sharing source sets, allows for us to do that pretty easily. The net effect though is that they do become inter-dependent, overall I don't think this is good as it increases client/lobby dependency and mixes the two all the more.


-----------------

Open questions/items:

should integ_tests have source code dependency on unit test?

**Comment by ssoloff** [comment]
>> I view User as a lobby domain object. It was a convenient abstraction to replace passing around three different pieces of user-related data.
>
> But, splitting the lobby integration tests to a sub-project I ran into a shared dependency problem where the client layer also depended on the same object. This means that the client uses the same object representing what it reads from the wire from the lobby.

I'm confused.  Are we talking about `User` or `DBUser`?  `User` is only used on the server side.  `DBUser` is shared between both client and server.

---

> should integ_tests have source code dependency on unit test?

Ideally, test utility code should reside in a separate source set that can be shared by both unit and integration tests without the integration tests having a direct dependency on the unit tests themselves.  However, I'm ok leaving things the way they are if it's going to require too much complexity in the build.

**Comment by RoiEXLab** [comment]
[Looks like Gradle 4.6 is already out](https://docs.gradle.org/4.6/release-notes.html)
So we should update the build scripts to use that instead and then decide what works best

**Comment by DanVanAtta** [comment]
> However, I'm ok leaving things the way they are if it's going to require too much complexity in the build.

The concern is the other way around, the fact they are coupled has meant that client and server test code have become coupled together. I ran into this when trying to split the tests between server and client.
