### ISSUE TITLE
Programming conventions, explicit scopes/keywords+

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3282]
Want to take this conversation out of band from a PR, noting a few things from: https://github.com/triplea-game/triplea/pull/3276

Please weigh in on how strongly you feel on these points (1-5, with 1 = opposed, 3 = neutral, 5 = in favor). I'll reserve my ranking for a bit to not overly bias.

### favor explicit imports in prod code
- makes refactoring a bit nicer when imports need updating, only need to update one import instead of one.
- boost to clarity, explicilty know we are dealing with a static and not a class variable, or parent variable. For TripleA code base, we are probably better off labeling things explicilty to help with clarity and give maximum compiler hints. There are a lot of variables access from parent classes, lots of static, omitting information does make it ambiguous.
- on rare occasion avoids name conflict, eg: StringUtil.

### using 'super' explicitly
- I like this as it makes the code smells a bit more obvious : )
- super is nice as you know it's not a static by looking at it without looking at the *very* top of the file

### Explicit 'static' on private methods where available
- this has found/prevented a few real bugs for me, inadvertent variable shadowing
- inappropriate dependencies can be discovered
- makes private method a 'helper'
- only infers more information, you know more when seeing it, it does not hurt
- private static != public static
- static methods are less coupled than non.. For example, uyou can move a static method just about anywhere in code, can't do that with non-static. On the other hand, static coupling is evil, but 'static' keyword alone does not determine that

### mark classes as final when possible
- unless explicitly designing for inheritance, disallow it.

**Comment by ssoloff** [comment]
I'm ok with all proposals except "using 'super' explicitly."

> super is nice as you know it's not a static by looking at it without looking at the very top of the file

I don't usually have a problem determining a call site is invoking a static method because the IDE renders it in an _italicized_ font.  If we really want to make static method calls easier to identify, it would probably be easier (and less dangerous; see below) to always invoke static methods through a class reference (e.g. `MyUtil.doSomething()`) even if it's in the same class.  The Eclipse static analyzer can be configured to warn in cases where the class reference is not used (not sure if Checkstyle can do the same thing).

> I like this as it makes the code smells a bit more obvious

Can you provide an example of the smell you're thinking of, please?

I actually think it's dangerous using `super` explicitly except when you're in an overridden method and want to explicitly call the superclass implementation.  Consider the following:

```java
public class Base {
  public void foo() {
    // ...
  }
}

public class Derived extends Base {
  public void bar() {
    // ...
    super.foo();
    // ...
  }
}
```

Then consider someone overrides `Base#foo()` in `Derived`:

```java
public class Derived extends Base {
  @Override
  public void foo() {
    // ...
  }

  public void bar() {
    // ...
    super.foo();
    // ...
  }
}
```

Unless someone updates the call to `super.foo()` in `Derived#bar()` (which may be several hundred lines away), the wrong implementation will be called.

Are you sure you're not talking about using an explicit `this` at instance method call sites?  That would seem to at least address your concern about identifying static vs. instance methods.  It's also not susceptible to the issue described above, and it can be enforced via code style tools (e.g. Checkstyle [RequireThis](http://checkstyle.sourceforge.net/config_coding.html#RequireThis)).

**Comment by DanVanAtta** [comment]
>  If we really want to make static method calls easier to identify, it would probably be easier (and less dangerous; see below) to always invoke static methods through a class reference (e.g. MyUtil.doSomething()) even if it's in the same class

I would agree, this is what I was trying to get at but was not eloquent enough to convey as such. I suppose the static 'origin' problem is actually more a question of if the static is in the same file or if it a static import.

Checkstyle may have some options to offer:
- http://checkstyle.sourceforge.net/apidocs/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStaticImportCheck.html

- http://checkstyle.sourceforge.net/apidocs/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.html


>> I like this as it makes the code smells a bit more obvious

> Can you provide an example of the smell you're thinking of, please?

When child classes use components from parent classes, it may be a sign of a number of problems:
* code re-use via inheritance instead of composition
* liskov-substitution principle violation
* Inversion of control violation
* Open-Close violation

Using 'super' is not universally bad, but it can easily invite the problems of inheritance (I believe there are some effective java chapters about this, basically avoid inheritance unless you have the right use-case).

With the most egregious example, I'll just leave this out there here:
```
public childConstructor() {
   super.variable = "newValue"; 
}
```

------------


> (e.g. Checkstyle RequireThis).

I can go either way on this one. I think the established convention has been to use 'this' only when required. I do think it gets a bit verbose, but I do like that it makes the 'too many class variables' problem easier to spot.

**Comment by DanVanAtta** [comment]
@ssoloff about `super`, in your example, I actually see the problem the other way around. Let's say we have:

```
public class Base {
  public void foo() {
    // ...
  }
}

public class Derived extends Base {
  public void bar() {
    // ...
    foo();
    // ...
  }
}
```

And *now* someone overrides the implementation:
```
public class Derived extends Base {
  @Override
  public void foo() {
    // ...
  }

  public void bar() {
    // ...
    foo();
    // ...
  }
}
```

In this case we call the wrong method! The `super` in my mind makes the parent-child contract more rigid, less wriggle room for child implementations to sneak in and steal the method call. In other words, it's more explicit, less likely to change, you will call the parent class.

In that sense I view it as a good thing, an explicit "yes, I am calling the parent class"

**Comment by ssoloff** [comment]
> The `super` in my mind makes the parent-child contract more rigid, less wiggle room for child implementations to sneak in and steal the method call.

If one is worried about a subclass overriding a method and changing the implementation, that sounds like the class is not designed for inheritance and should thus be `final`.

**Comment by RoiEXLab** [comment]
@ssoloff Or the method can be made final...

**Comment by DanVanAtta** [comment]
Yes, marking classes as final and methods final does solve the inheritance problem by not allowing it. It does go with the effective java principle. I would suggest that this does the same:
```
  public void bar() {
    // ...
    super.foo();
    // ...
  }
```
This method does not allow for `foo` to be overriden, the method `bar` is not designed for inheritance and hence it is disallowing it.

----

We should not be so abstract though, we do have a specific code base. In tripleA some `super` calls I would appreciate so I know not to look for that method in the same class. 

Are we concerned that explicit `super` is clutter?

**Comment by DanVanAtta** [comment]
I think there is disagreement whether super call is a benefit or not. I'm not worried about adding a new @Override method as mentioned in your example @ssoloff - all other methods in the class would call 'super' and so they would not be changed. I view that as a benefit, changes to existing code is more explicit, you have to actually update it to use the override method.

I may have this point of view from seeing consistent `super`. In that case a new `@Override` in the same class is never a problem where existing methods no longer work as expected, they retain their original behavior (which is usually better than going through a new code path not originally designed and tested)

**Comment by DanVanAtta** [comment]
Let's leave explicit `super` to the side. I don't necessarily feel that strongly about it. It does seem there is agreement for explicit static calls.  To do here would be to investigate and/or add these two checkstyle rules:
- http://checkstyle.sourceforge.net/apidocs/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStaticImportCheck.html
- http://checkstyle.sourceforge.net/apidocs/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.html

**Comment by DanVanAtta** [comment]
This might have been a silly point to bring up, my apologies @ssoloff; my point of view I'm not sure is still the same. Overall I don't see a needed action item on this front at this time, closing.
