### ISSUE TITLE
Repo README Review

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3289]
Does each repo contain a top level README.md with:
1. overview of the repo contents and how it fits in with the rest of the system
1. compile and build
1. test locally
1. deploy 
1. restart
1. check status (is it alive?)
1. check logs

https://github.com/triplea-game

- [ ] https://github.com/triplea-game/triplea
- [ ] https://github.com/triplea-game/triplea-game.github.io
- [ ] https://github.com/triplea-game/lobby
- [ ] https://github.com/triplea-game/tripleawarclub.org
- [ ] https://github.com/triplea-game/assets
- [ ] https://github.com/triplea-game/dice-server-js
- [ ] https://github.com/triplea-game/dice-server

**Comment by DanVanAtta** [comment]
@RoiEXLab @ssoloff can either of you volunteer to consolidate any existing dice server documentation to the corresponding repo?

**Comment by ssoloff** [comment]
Sorry, don't have bandwidth at the moment for additional tasks.  If you have specific questions, please list them, and I'll try to answer them when I get a chance.

**Comment by DanVanAtta** [comment]
A few questions that would really help @ssoloff / @RoiEXLab :
- Are both dice servers deployed? 
- Which one is legacy? 
- Is there any documentation on deployment beyond the section in docs/admin? (which is mostly TODO)

**Comment by RoiEXLab** [comment]
@DanVanAtta
> Are both dice servers deployed? 

Well we currently have a staging an a production version of MARTI. Nothing else.

> Which one is legacy?

While I started a rewrite from scratch project that can be found in the dice-server-js repository it doesn't work yet.
But the long term goal is to replace MARTI with a REST API.

> Is there any documentation on deployment/installation beyond the section in docs/admin?

There's just MARTI. @ssoloff Created a docker image that could be used for production (well documented in the MARTI repository), but other than that I don't think there's a documentation on how to set everything up without docker

**Comment by DanVanAtta** [comment]
Sorry< i was not clear enough with first question. Out of these two repositories, which ones are deployed?
- https://github.com/triplea-game/dice-server-js
- https://github.com/triplea-game/dice-server

From your answer @RoiEXLab , it sounds like the 2nd one `dice-server` is currently deployed and the *js is work in progress.

**Comment by DanVanAtta** [comment]
>> Is there any documentation on deployment/installation beyond the section in docs/admin?

> There's just MARTI. @ssoloff Created a docker image that could be used for production (well documented in the MARTI repository), but other than that I don't think there's a documentation on how to set everything up without docker

Where is the MARTI repository? :thinking:    I don't see it under: https://github.com/triplea-game/

**Comment by DanVanAtta** [comment]
@RoiEXLab @ssoloff please update the dice-server repo's when you get the chance.

I'll take care of the other ones, I created most of them.

**Comment by DanVanAtta** [comment]
Marking warclub:
- improved readme to prominently note deprecation: https://github.com/triplea-game/tripleawarclub.org/pull/29
- opened issue to discuss removing repo: https://github.com/triplea-game/tripleawarclub.org/issues/28 (is there anything still used? i see last commit was 25 days ago, are we using this repo for something still?)

If it turns out we still use this repo then we'll need to revisit this documentation, I suspect that is pretty likely given relatively recent commits.

**Comment by RoiEXLab** [comment]
@DanVanAtta 
The MARTI repository is just called 'dice-server'
To my knowledge the tripleawarclub.org repository just hosts some configuration files currently

**Comment by DanVanAtta** [comment]
I updated the list of desired items for top level README's, added for example 'how to restart' . We are at six items now: 
1. overview of the repo contents and how it fits in with the rest of the system
1. compile and build
1. test locally
1. deploy
1. restart
1. check status (is it alive?)
1. check logs

Is that an agreeable list? Anything missing?

**Comment by DanVanAtta** [comment]
Happily just one repo now is missing info and not otherwise marked as deprecated. I added a ticket to that repo, can resolve this ticket now.
