### ISSUE TITLE
Automatic Staging Lobby

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3291]
There were some previous attempts to get lobby to be auto-deployed on each merge: https://github.com/triplea-game/triplea/pull/458

That did not pan out in the end, I tried there to have Travis execute a SSH command to do the lobby deployment on a target server.

Getting this to work would be an excellent milestone:
- we'd have a well-known 'latest-lobby' useful for testing
- removes admin work of doing latest lobby to a test server
- ensures our deployment scripts work, serves as documentation.
- we'd be able to run a set of verification tests against a freshly deployed instance to do additional tests

------------------

I'm opening this issue to coordination on this effort. @ssoloff did you have any thoughts on this, have you made any progress already towards this task?

**Comment by ssoloff** [comment]
Nope, I have not attempted this.

**Comment by DanVanAtta** [comment]
I'm going to give a crack at this. 2nd attempt! : )

**Comment by prastle** [comment]
Ah that was what the linode notice was about 😄 

Great stuff! Good luck!

**Comment by DanVanAtta** [comment]
Good news and an important milestone hit: https://github.com/triplea-game/infrastructure/pull/1

This lobby is always now set to be the latest prerelease and would update on each merge:
http://172.104.27.19:7000

I also hooked up the infrastructure to automatically set up new servers with logging sent to paper trail and metrics to grafana.

With that system we'll be able to trigger deployments by updating source files : )
(though we likely wont' need to as prod can automatically sync to a 'latest' release and the prerelease can autoamtically sync to the latest pre-release)

Database is looped into the mix, so we get automatic DB migrations executed.

Left to do is Bot's (reach goal would be to wire up the dice server too).

This new issue goes into some more detail on what is new, has some screenshots of these new tools:
https://github.com/triplea-game/infrastructure/issues/3. 

Please gitter me your email for an invite link to the new tools.

Please post any questions/follow-up to: https://github.com/triplea-game/infrastructure/issues/3
