### ISSUE TITLE
Game-core jar shouldn't be included in installer

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#3296]
Why do we now have two jar-files inside the bin-subfolder? There is a 'game-core-1.9.0.0.dev.jar' next to the "triplea-1.9.0.0.9824-all.jar"? The size of the installer increased due to this.

**Comment by DanVanAtta** [comment]
now fixed
![screenshot from 2018-03-31 10-29-56](https://user-images.githubusercontent.com/12397753/38165821-8ad6d068-34ce-11e8-9f18-9eb1dd56fde3.png)
