### ISSUE TITLE
Travis -> Gitter Integration

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3312]
With https://github.com/triplea-game/triplea/pull/3311 we have travis reporting build activity to a gitter room: https://gitter.im/triplea-game/travis-build

**Comment by ron-murhammer** [comment]
Looks good to me. Once at least all the devs have seen this issue, we can probably close it unless you had further ideas.

**Comment by DanVanAtta** [comment]
The dedicate gitter room for the notification is maybe overkill. For some consideration, we may want to send the activity notifications to a different room, maybe the QA one (it's public, and QA is interested in new builds)
