### ISSUE TITLE
Unify test source sets (and seperate them differently)

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#3313]
An idea that just came to my mind:
The additional integTest source set might just overly complicate things.
Instead we could unify this source set with the "normal" test source set and annotate any integration tests with special [tags](https://junit.org/junit5/docs/current/user-guide/#writing-tests-tagging-and-filtering) so we can still run tests independent of each other.
I'm not 100% sure how the task dependency structure should be given that we need to tell jacoco to not add integ test coverage, but I think it would be easier to manage everything that way.

**Comment by RoiEXLab** [comment]
Alternatively we could of course just seperate by the class name and just exclude any class files ending with 'IntegrationTest' from being run

**Comment by ron-murhammer** [comment]
@RoiEXLab Makes sense to me. I think an annotation is probably better as its a bit more obvious and explicit.

**Comment by DanVanAtta** [comment]
How would this integrate with IDE tooling?
One nice thing about current setup is I can run all the unit tests by right clicking a single folder and running all tests, and it runs quickly. The faster run-time is important, at 20+ some seconds it's still slow but unit-test speed. The integration tests take a bit longer, long enough a dev would not run tests nearly as often.

**Comment by DanVanAtta** [comment]
I'll take the question to the PR to keep conversation in one place.
