### ISSUE TITLE
TripleA_1.9.0.0.9991_windows-64bit.exe - Virus!

### ISSUE THREAD

**Issue by General-Dru-Zod** [triplea-game/triplea#3337]
### Engine version
9991

### My Operating System
windows 10

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
I have McAfee Live Safe 2018. While trying to run TripleA_1.9.0.0.9991_windows-64bit.exe, after scan it says "TripleA_1.9.0.0.9991_windows-64bit.exe contained virus and was deleted". I did not go continue running it as it was auto deleted.

**Comment by RoiEXLab** [comment]
[Try again](https://www.virustotal.com/#/file/105ef053a9a1b3fdddd37f090cee575c7695baed73546cb6d4304a84fa96109e/detection)

Closing as there's not much we can do about it.

**Comment by prastle** [comment]
I would like to point out that I had the same error using windows defender.

**Comment by DanVanAtta** [comment]
The checksums of the files matched? Kinda curious we see this now and not earlier.

**Comment by tvleavitt** [comment]
> [Try again](https://www.virustotal.com/#/file/105ef053a9a1b3fdddd37f090cee575c7695baed73546cb6d4304a84fa96109e/detection)
> 
> Closing as there's not much we can do about it.

Actually, most anti-virus companies have a whitelisting process. Here's McAfee's.

https://kc.mcafee.com/corporate/index?page=content&id=KB85568
