### ISSUE TITLE
Null Exception Error

### ISSUE THREAD

**Issue by General-Dru-Zod** [triplea-game/triplea#3352]
### Engine version
.10025
### My Operating System
win10
### Map name
ww2v3
### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
It was happening while watching a game in the lobby, the private host was running .9997. The error poped up whenever I tried to view the resources tab. Then the error kept popping up as the players did stuff.

### Do you have the exact error text? Please copy/paste if so

![null exception error 001](https://user-images.githubusercontent.com/17499403/38462960-c9c6b862-3abc-11e8-8cb7-1044b0e3d576.PNG)

### Any additional information that may help

[null.exception_04.07.2018.txt](https://github.com/triplea-game/triplea/files/1886915/null.exception_04.07.2018.txt)

[ww2.v3_04.07.2018.zip](https://github.com/triplea-game/triplea/files/1886916/ww2.v3_04.07.2018.zip)

**Comment by ron-murhammer** [comment]
@General-Dru-Zod Are you able to reproduce the error using the save game you attached?

**Comment by prastle** [comment]
I can't reproduce this locally.  But I can confirm I observed iit in an online multi-player game of v3 41.  Zod is correct.  I am curious if one of the 5 players had an old engine?

**Comment by General-Dru-Zod** [comment]
@ron-murhammer I was able to consistently reproduce the error with if @prastle was hosting the game in  the lobby. I was able to reproduce the error locally only once with the game save above. Which was taken from prastles lobby game.

**Comment by ron-murhammer** [comment]
@General-Dru-Zod Ok. Can you try testing out the latest pre-release: https://github.com/triplea-game/triplea/releases/tag/1.9.0.0.10042

**Comment by General-Dru-Zod** [comment]
@ron-murhammer  Ok, prastle logged off already, so I will ask him to host the game again tomorrow while I have 10042 running.

**Comment by prastle** [comment]
We tested and yes 9997 was the problem works fine with 100042.  Thanks @ron-murhammer
