### ISSUE TITLE
Frequent lobby error: TLS is required, but was not offered by host smtp.

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3374]
### Engine version
~9687, latest lobby as of 4/16

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Not known, error message can be observed in lobby logs, perhaps triggered by PBEM game or marti dice server

### Do you have the exact error text? Please copy/paste if so

> Apr 16 20:52:03 tripleawarclub postfix/error[30183]: 987D910A524: to=<XXXXXX@tin.it>, relay=none, delay=231575, delays=231575/0.39/0/0, dsn=4.7.4, status=deferred (delivery temporarily suspended: TLS is required, but was not offered by host smtp.tin.it[xx.xxx.72.32])

### Instead of this error, what should have happened?
no error

### Any additional information that may help

This is close to 20% of all log messages (taken over a recent sample of 1000 log lines)
```
journalctl -n 1000 | grep -c "TLS is"
186
```

**Comment by RoiEXLab** [comment]
Hmm I remember changing the postfix server to require TLS so all the MARTI emails would be sent securely, but emails seems to be get sent normally.

**Comment by DanVanAtta** [comment]
@RoiEXLab can you comment on what was changed? We see this error quite frequently in logs, something is kinda broken. Alternatively, will you have time in the next month to look at this @RoiEXLab , can this issue be assigned to you for follow up?

**Comment by RoiEXLab** [comment]
I don't recall the exact location of the config file, but it was a simple setting that made postfix use TLS.
In theory there should be a setting to simply prefer TLS if available, but this didn't seem to do anything.
For verification I sent myself MARTI emails and checked the lock symbol in Gmail. 
I think red was insecure, grey was TLS and green was some advanced encryption I don't recall (Google has SMTP ports for all of them).
I should have enough time in October to have a look at this.

**Comment by DanVanAtta** [comment]
closing, low priority for now.
