### ISSUE TITLE
Map Blend Images Corrupted

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#338]
Started the game up from GameRunner2 and get the wrong unit colors on NWO. It appears that things are being loaded from 'assets' folder before the map folder. So I think a bug must have been introduced at some point.

I believe the assets folder is just there for defaults that the map folder should always override.

**Comment by DanVanAtta** [comment]
Hmm, not sure I'm quite seeing the same. Perhaps due to case sensitive vs non-case sensitive file system. Could you clarify with a specific item that is showing the problem?

**Comment by ron-murhammer** [comment]
Lots of things. Screenshot showing NWO with wrong color Italian units and wrong flag images.

![capture](https://cloud.githubusercontent.com/assets/1427689/12214020/01ea8e06-b64b-11e5-9926-67fed9330cb5.PNG)

**Comment by ron-murhammer** [comment]
@DanVanAtta This appears to be due to the optipng changes: https://github.com/triplea-game/triplea/pull/146

I tested tag 1.8.0.10.401 and everything looks right. Then I tried 1.8.0.10.406 and get the weird image problems like above.

Can you please take a look? We may need to revert these changes.

**Comment by DanVanAtta** [comment]
@ron-murhammer , there are two problems here. 
First, the blend images are not being rendered correctly
Second, we are getting the wrong images (flags). This second problem could use further confirmation.

We have an additional problem with the root folder of the game being screwed up. With that it's hard to know where it'll find images, if at all correctly. The map blend problem is not as trivial as reverting the optiPng run, I did that and still saw problems.

**Comment by DanVanAtta** [comment]
Looks like optiPng did cause the problem. I replaced the NWO map with an old one and everything looked 'normal' again.  My guess is the 'strip-all' for metadata also maybe botched transparency values.

To fix this, history re-writing to remove the optiPng change is the best way to go (otherwise we'll retain an extra 100Megs of unnecessary data in our clone).

Current PRs will need to be rebased when that happens..

**Comment by ron-murhammer** [comment]
@DanVanAtta Ok. That's consistent with what I found as well and agree re-writing history would be best.

So let's not open any new PRs and address the 4 open ones. Then we do the history re-write. Current PRs:
1. Fast AI - the only major issue with this you can run both Hard and Fast but since it doesn't break previous functionality its ok to merge. Issue to refactor to allow both Hard and Fast to have own battlecalc: #381
2. Installer - I'm still against removing the Ant build until we have a successful gradle release. I think we either split this or hold off and this will need to rebase.
3. Performance Log - I'll try to review this today or tomorrow
4. Map Download - I'll try to review this today or tomorrow now that you updated to point to SVN for now

**Comment by DanVanAtta** [comment]
2, 3, and 4 will be okay with the history re-write, Gabor and I are okay with dealing with that rebase. So only really need to get the Fast AI one merged.

I don't want to drag out the ant build conversation... But couldn't we consider anytime we do a merge and travis picks up and successfully builds with Gradle as a successful build? Travis has built the installers 300 some times now, that gives me a lot of confidence. But also, what element of the Ant build could we possibly want to keep around? I strongly think keeping the ant build file is just slowing us down, giving a false sense of security (illusion of a rollback when in fact rolling back to the ant build is neither trivial nor desirable), and last keeping that stuff around makes it harder to clean up the mess. There should not be 40 some files and folders at the top level of this project, a dozen of those files are unused, that is slowing us down

**Comment by ron-murhammer** [comment]
@DanVanAtta Ok. In that case feel free to do the history rewrite whenever you have the time.

Its not that I don't believe the gradle build doesn't produce artifacts its whether those artifacts 100% work. Mostly concerned about the Mac build since I don't think its had much testing exposure. At this point, I agree that its very unlikely we need the ant build but just want to make sure the gradle build lives through an official release first.

Its probably best to keep this conversion in the PR. I'm not sure there is a way to change my opinion on the matter other than if you get Veqryn to agree that he's fine removing it now rather than waiting til after the release.

**Comment by DanVanAtta** [comment]
#382 to talk about testing concerns and removing ant build files. My suggestion is we spend some time on your area of concern @ron-murhammer, namely verifying the mac install is good. We can in fact get started on that now. Since we have so much stuff built up, and are getting closer to a release, I think it makes sense to get a start.

**Comment by DanVanAtta** [comment]
#395 should fix this for maps included with the game engine.

**Comment by ron-murhammer** [comment]
@DanVanAtta - It appears the map blend issues are resolved but there are still issues with the wrong flag icons and units showing up.
![capture](https://cloud.githubusercontent.com/assets/1427689/12771171/aa8f0d16-c9ec-11e5-8c23-ac64b0d69d05.PNG)

**Comment by DanVanAtta** [comment]
Taking wrong flag and unit issue to #424

Thanks for the confirmation of the other fix.
