### ISSUE TITLE
battle in progress but is finished

### ISSUE THREAD

**Issue by prastle** [triplea-game/triplea#3385]
### Engine version

current triplea bots
### My Operating System
na
### Map name
Global
### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
na
### Do you have the exact error text? Please copy/paste if so
no
### Instead of this error, what should have happened?
the battle should have finished
### Any additional information that may help
You probably have this covered somewhere in issues.  I grabbed them a history save.

[glitch over battle finish.zip](https://github.com/triplea-game/triplea/files/1933092/glitch.over.battle.finish.zip)

**Comment by ron-murhammer** [comment]
@prastle Is this the same error as #3377

**Comment by prastle** [comment]
Similar but occurred in global map not nwo @ron-murhammer
