### ISSUE TITLE
Lobby downtime, a follow-up

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#3409]
Our lobby server was recently restarted due to the recent spectre/meltdown vulnerability.
However it failed to restart the IPv4 network interface (IPv6 worked), because of a wrong line in the a configuration file:
In the `/etc/network/if-up.d/sendmail` file (or similar, we can check the logs later) I commented out a line that tried to invoke the non existent `/usr/share/sendmail/dynamic` script and everything seems to work fine.

I don't know what this line did, I don't have the time currently, but we should check if mail services (especially MARTI) still work.

EDIT:
I noticed that the lobby server tried booting a non-existent bot,
we probably need to disable this by running `systemctl disable triplea-bot@<number>`

**Comment by prastle** [comment]
Quite a few bots keep crashing while being played in as well as some bot servers have too many bots.  SSH keys appear to be broken as it informs me it isn't the one expected and saved.

**Comment by prastle** [comment]
@RoiEXLab  Well it appears all we are doing is pissing off a lobby full of 50 people since they keep disconnecting and crashing.  Should I stop the confirmed broken servers for now?

**Comment by RoiEXLab** [comment]
ok, everything seems to be working fine now.
@DanVanAtta I want to point out, that 5 bots are being started although only 4 are specified in the infrastructure repo.

**Comment by DanVanAtta** [comment]
``` systemctl disable triplea-bot@<number>```
This step does not happen automatically. 
I wonder if the 5 bots is a misconfiguration or if it is due to an old bot server not being uninstalled.

Running 5 bots will crash a server, there is not enough main memory to run that many.

**Comment by prastle** [comment]
400 bots still screwed up
and ssh to bot servers but yes seems to be working now.

**Comment by prastle** [comment]
Also all bot servers had to be rebooted twice they did not auto launch when restarted.

**Comment by DanVanAtta** [comment]
Go for it @RoiEXLab , I'm pretty slammed for about a week, likely out of town for a long weekend this weekend as well.

**Comment by prastle** [comment]
also need 1 more in 501 that's missing

**Comment by prastle** [comment]
We will be fine only 50 peeps tonight

**Comment by prastle** [comment]
Three servers have afk bots atm.

**Comment by prastle** [comment]
No matter @RoiEXLab  from now on you can fix yourselves.  Power was out for 36 hrs here but either answer is the same.  Apparently you guys want no root.  NP after spending 2 hrs at 3am the other night to then discover he had removed my ssh without even telling me I feel really stupid... Alot of posted messages about nothing I was removed.   Make sure you guys fix from now on.

**Comment by prastle** [comment]
From now on when a bot locks since as we discovered we can only boot or stop them.  If I notice I will.  Hopefully someone restarts them.

**Comment by DanVanAtta** [comment]
Having a 5th bot *will* cause crashes; i suspect a lot of recent instability was perhaps due to this.

@RoiEXLab have we seen such instability with the correct 4 bots running? We can try allocating less memory per bot if 4 at current setting is not stable:  https://github.com/triplea-game/infrastructure/blob/master/roles/host_control.sh#L24  We should also get more specific about crashes, "unstable" may start to mean a lot of different things and maybe not always a memory problem.


@prastle sorry about the tight spot, I didn't notify you of the recent changes, that was my fault. The new `admin` user is the new `triplea` user. It is still wet behind the ears though, so please let us know of any commands that you are trying to run but cannot.

IT is actually news the frequency of restarts. The tripleA team is not always that unified, I was genuinely unaware that you log in to the servers daily to do restarts. 'restarts' are a very heavy handed fix that masks problems and allows them to accumulate. We need to start being proactive to fix crashes so we are not in such a whack-a-mole situation.

We can:
- add some logging to the restart convenience scripts, ask all admins to use the convenience scripts instead of 'systemct'
- start tracking bot crashes in a github issue. It would be good to know about the different kinds of crashes; and the constant reporting might help highlight how serious/pressing of a problem this would be.

**Comment by prastle** [comment]
1st it has always been four bots we discovered that last year you changed that @DanVanAtta 
2nd with four we have always had lock ups
3rd admin needs to be able to restart bots and stop them individually.  Yes I can  use linode to restart the server BUT that means emptying all other bots on that server that are still running.  Do it as you wish but the  simple solution is toolbox having a restart option if possible.

**Comment by prastle** [comment]
@RoiEXLab  @DanVanAtta Also as a side note I have to Giggle ... Who are the admin your reffering to?  Since generally it was only myself or zod  that have ever restarted?  You make it sound like we have a crew... WE DO NOT!  Hopefully your new system works since now only you or roi are restarting them ;)

**Comment by DanVanAtta** [comment]
> 2nd with four we have always had lock ups

Exactly what kind of lockups, what is the cause? With 5 we get a pretty specific "system out of memory" error, the bots almost do not even launch and stay started for more than 5 minutes. It's very clear this would be because the current memory calculation is for 4 application instances, not 5.

**Comment by DanVanAtta** [comment]
> Yes I can use linode to restart the server BUT that means emptying all other bots on that server that are still running. 

Restarting stuff is not a fix for anything, power it down instead so we can start it back up with a better/fixed configuration. The last message in logs being an errors is better than us panicking. There is a huge information gap as well, as you have/had all the access you need to restart bot instances.

**Comment by DanVanAtta** [comment]
> 3rd admin needs to be able to restart bots and stop them individually. 

In this context, system administration, `admin` is a user account on the linode machines. Instead of `ssh triplea`, you should use `ssh admin@`

**Comment by prastle** [comment]
Dear I love you but simple the truth is this is two years old...
Join the lobby look at waiting for players or in progress bots

**Comment by prastle** [comment]
naw
your turn only way ya learn is by doing

**Comment by DanVanAtta** [comment]
@prastle we need paper trail payed for: https://papertrailapp.com/events

**Comment by DanVanAtta** [comment]
There are a number of different reasons why bots would halt; Some of them are pure misconfiguration, or 'ghost' servers from scripts not running cleanly or cleanup. Others are long-running issues. Each need a different fix. The way to fix them is to diagnose in the logs what the reported error message is, then keep track of which different error messages we see and when, and fix each one in turn.

So far we are just restarting when we see a problem, so we just need to get a bit more proactive about fixing things so they stop happening all the time repeatedly.

**Comment by prastle** [comment]
yup read that days ago
and i need a lobby that doesn't  fail with a months notice
and bots that don't need 12 hrs to get working with someone adding their own root and removing me.

**Comment by DanVanAtta** [comment]
> and i need a lobby that doesn't fail with a months notice

Ya.. me too.

**Comment by DanVanAtta** [comment]
> and bots that don't need 12 hrs to get working with someone adding their own root and removing me.

You need to bring @RoiEXLab @ssoloff me, or @ron-murhammer  please next time.

**Comment by prastle** [comment]
brought roi
ron on holidays
also asked ssoloff

**Comment by prastle** [comment]
also if you check gitter
you will see time stamp

**Comment by prastle** [comment]
you got an email as well

**Comment by prastle** [comment]
So to be blunt since the lobby and forum pay for triplea and we have 600 in account after my donation last week myself of another hundred how about the lobby and forum become a concern?  Instead of all the other GitHub stuff.

**Comment by DanVanAtta** [comment]
okay, you did what you needed. We're a volunteer project. I've personally other professional commitments that 100% take priority, and some days I will not at all be available. I suspect others are falling into that case more and more often.

Look, us bickering helps nothing.

We need to start tracking errors, analyzing why bots are failing, exactly from a system level. We should then be able to classify these failures, and for each time a bot freezes identify which class it falls into. With that data we'll then fix one in turn.

Getting all bots to send logs to papertrail was a big step, the analysis becomes a lot easier and feasible for large scale analysis. If all we do is just restart a bot and proceed.. we will not get anywhere.

**Comment by prastle** [comment]
simple answer
bots are failing because no forced uupdate

**Comment by prastle** [comment]
To be blunt
I could care lless about root still think i need it BUT a rare thing.  What we need is three things. One admin works with old roi triplea scripts.
two a list all admin can use that get the admin ssh !!' = they need putty etc AND KNOW A BIT

**Comment by prastle** [comment]
three only admin you feel are worthy get ssh

**Comment by prastle** [comment]
either way we need more than 2 peeps available if the whole system crashes which it did

**Comment by prastle** [comment]
so root needs more than 3 peeps

**Comment by DanVanAtta** [comment]
ya, and we don't have them.

Are there any current problems?

Please pay for papertrail @prastle , the $5 per month so we can get some log history going.
I'm going to be gone for next 3 days, I'll take a look at bot issues when I get back.
@RoiEXLab please take a look in the meantime.

@prastle please create a github issue whenever there is a bot crash, create oen every time you have to mess or f*#$ with a bot please. It's like moderator banning, you have to report what you do (please).

**Comment by DanVanAtta** [comment]
papertrail action item: https://github.com/triplea-game/triplea/issues/3412 @prastle

**Comment by prastle** [comment]
sure round 18 one player
ghost bot
to be specific hey dont crash they just don't reload

**Comment by DanVanAtta** [comment]
https://github.com/triplea-game/triplea/issues/3413  << ticket for bot flakiness, investigation. @prastle good place to describe any problems, but please try to be concise, clear and specific as best you can.

**Comment by prastle** [comment]
I have not had any complaints about marti so i assume it launched fine?   Did anyone have to  tweak?

**Comment by RoiEXLab** [comment]
@prastle Didn't have to do anything once the server network was running again.
Closing this issue as several others were created.
