### ISSUE TITLE
Illegal movement restriction

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#3410]
### Engine version
1.9.0.10225 (and prior versions)

### Map name
wwII_global (and wwII_europe)

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)

On US1 try to move US ships from SZ 101 to SZ 121, TripleA illegally restricts your movement.
(Also the path is drawn via land territories - looks funny!)

### Do you have the exact error text? Please copy/paste if so

An image (shot during NCM phase) instead:
![sz121](https://user-images.githubusercontent.com/20812775/39596319-40e28886-4f12-11e8-984b-f322e7d6b220.png)

### Instead of this error, what should have happened?

US ships should be able to end their movement in SZ 121 while USA is not at war with Germany or Italy.

### Any additional information that may help

Rulebook says:

> While not at war with Germany or Italy, the United States may end the movement of its sea units on the Europe map only in sea zones that are adjacent to U.S. territories, with one exception: U.S. warships (not transports) may also conduct long-range patrols into sea zone 102.

SZ 121 is adjacent to Greenland (being a US territory). So the US should be allowed to end movement of its sea units there.

Players need to use edit mode to enforce this move (until this gets fixed).

The attached savegame starts with US1 NCM phase (Global map). So the issue can be reproduced easily.

[USmove121.zip](https://github.com/triplea-game/triplea/files/1972239/USmove121.zip)

( The issue has been noted on https://www.axisandallies.org/forums/index.php?topic=41967.0 )

**Comment by beelee1** [comment]
not sure if it's engine or Veqryn just didn't do it. Here's the xml:

!-- Americans in OOB are not allowed to move to or through these sea zones:
						125 Sea Zone:111 Sea Zone:119 Sea Zone:109 Sea Zone:104 Sea Zone:91 Sea Zone:87 Sea Zone:83 Sea Zone:70 Sea Zone:71 Sea Zone:72 Sea Zone:76 Sea Zone:80 Sea Zone:79 Sea Zone
					
 Americans in Alpha +3 are not allowed to end their movement in:
						Europe board: any sea zone not touching an American territory, plus 102 sz
						TODO: We need to disallow a movement ending in a territory
						TODO: Currently we disallow any movement into, instead of just disallowing the ending of movement in.  So, for example, SZ 106 and 116 could be moved into on the way to 121.
							65 Sea Zone:66 Sea Zone:85 Sea Zone:86 Sea Zone:88 Sea Zone:90 Sea Zone:103 Sea Zone:106 Sea Zone:107 Sea Zone:116 Sea Zone:117 Sea Zone:120 Sea Zone:122 Sea Zone
						Pacific board: any sea zone touching a Japanese controlled territory
						TODO: Currently we disallow any movement into, instead of just disallowing the ending of movement in.  So, for example, SZ 17, 22, 32, 33, 34, and 37 could all be moved through on the way to another territory.
						TODO: Currently we have a "set list" of territories. Obviously if Japan conquers more territories, then this list should expand, but it doesn't yet.
							6 Sea Zone:17 Sea Zone:19 Sea Zone:20 Sea Zone:22 Sea Zone:32 Sea Zone:34 Sea Zone:33 Sea Zone:36 Sea Zone:37 Sea Zone
				-->

**Comment by DanVanAtta** [comment]
@panther2 @beelee1 I think we'll have to take this one to the map makers to solve.

The map XML has SZ 106 on the movement restricted list, note the below with 'through' emphasized:

> !-- Americans in OOB are not allowed to move to or ***through*** these sea zones:

![screenshot from 2019-01-23 21-46-42](https://user-images.githubusercontent.com/12397753/51657130-698de200-1f58-11e9-9249-be9b76f2965d.png)


The latest map has (note that 106 is on the list):
``` 
  <attachment name="rulesAttachment" attachTo="Americans" javaClass="games.strategy.triplea.attachments.RulesAttachment" type="player">
      <option name="movementRestrictionTerritories" value="65 Sea Zone:66 Sea Zone:85 Sea Zone:86 Sea Zone:88 Sea Zone:90 Sea Zone:103 Sea Zone:106 Sea Zone:107 Sea Zone:116 Sea Zone:117 Sea Zone:120 Sea Zone:122 Sea Zone:19 Sea Zone:20 Sea Zone:36 Sea Zone"/>
      <!-- :6 Sea Zone:17 Sea Zone:22 Sea Zone:32 Sea Zone:33 Sea Zone:34 Sea Zone:37 Sea Zone -->
      <option name="movementRestrictionType" value="disallowed"/>
    </attachment>
```
https://github.com/triplea-maps/world_war_ii_global/blob/master/map/games/ww2global40_2nd_edition.xml#L4817


###

A game engine rule change is tricky here and could impact a lot of maps.

My first suggestion to fix this is to put a US only SZ great lakes SZ territory (connected via canal) that also connects to hudson bay. The path to SZ121 would still be the same distance in that case and pass through allowed territories.

**Comment by DanVanAtta** [comment]
Engine won't be able to readily fix this , I created a forum post asking for volunteers and discussion on changing the map to allow that movement via a different route.

**Comment by panther2** [comment]
@DanVanAtta 
OK, understood. We already have issues at the map repos 
https://github.com/triplea-maps/world_war_ii_global/issues/32
and
https://github.com/triplea-maps/world_war_ii_europe/issues/5
to keep that in mind.
