### ISSUE TITLE
Papertrail 

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3412]
Having all our logs in a central place available in a web console is really useful. 

@prastle could you please use the triplea fund to do the $5 per month account.

**Comment by prastle** [comment]
dan we have 600? plus in the linode account
buy it :)

**Comment by prastle** [comment]
@DanVanAtta looked into it perhaps we want the $6. a month plan which lets you search for 3 days?  Either way they don't take paypal.

**Comment by prastle** [comment]
@DanVanAtta  Upgraded us to 60 a year 3 day search 1 gb hopefully that is what you needed.

**Comment by DanVanAtta** [comment]
Thanks @prastle !

We are actually not that far over 100MB which would qualify us for a free plan if we could get under that. I suspect as we do more lobby activity logging, that will become more difficult (but perhaps we can get there and save on our project's yearly cost).

I'll close this otherwise as the task has been accomplished.
