### ISSUE TITLE
I Cannot Find My Autosave (1.9.0.0.10225)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#3415]
I have a problem that may also be a general issue.

I was playing just now a "270BC 40%" multiplayer game, in my private host, and I closed it due to issues in my private host, and, in the confusion, I didn't take a save.

The engine used to take autosaves, but now I go trying to reload it and the save is nowhere to be found.

**Do the engine still take autosaves? Where?**

I was playing with 1.9.0.0.10225, and now, without restarting any other games, I've tried to reload the following savegames, and none of them has my save:

autosave.tsgv
autosave_round_even.tsgv
autosave_round_odd.tsgv
autosave2.tsgv
autosaveAfterBattle.tsgv
autosaveAfterCarthageCombatMove.tsgv
autosaveAfterCarthageNonCombatMove.tsgv
autosaveAfterNumidiaCombatMove.tsgv
autosaveAfterNumidiaNonCombatMove.tsgv
autosaveAfterParthiaCombatMove.tsgv
autosaveAfterParthiaNonCombatMove.tsgv
autosaveAfterSyriaCombatMove.tsgv
autosaveAfterSyriaNonCombatMove.tsgv
autosaveBeforeBattle.tsgv
autosaveBeforEndTurn.tsgv

I've not restarted any other games (yet), so I'm sure not having overwritten anything.

Please tell me soon where exactly should I look to retrieve my autosave (if the engine I used still take autosaves (I assume it does?)). Not playing meanwhile, waiting for your answer. Thanks.

**Comment by panther2** [comment]
I would like to help, but I don't understand your question. You have listed your autosaves so you have found them... or are all those empty files?

What date and time do those files have - when have they been created? Aren't they from your game?

Of course the autosaves save at certain points during the game. So chances are that a small part of action (after saving until leaving the game) is missing.

**Comment by Cernelius** [comment]
None of those are my game. They are all old autosaves.
I've checked now the "savedGames" folder, and the only saves taken the same day are connection losts saves (that is not what I need, because it was me closing the game, there).
"autosave" and "autosave2" are 2018/02/28. All others I listed are older, apparently.
So where does the program autosaves now? Is nobody getting autosaves anymore?

**Comment by Cernelius** [comment]
Nevermind I see there is an "autoSave" folder now. I should have immagined.
I've lots of folders in there, as I like to archive the saves separately; so that is probably otherwise obvious to spot, for new users.
