### ISSUE TITLE
Disaster recovery plan

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3417]
Task here: work out the details of a disaster recovery (DR) plan, where to post and content.

There are a number of topics to decide:
- 1. How are p0 events initiated, is this a forum post? a github issue tagged with a label?
- 2. how are p0 events escalated. This needs to be automated, probably an email notification (which can be sent to an SMS email address if desired)
- 3. How will admin communication unfold, where will admins communicate in the event the lobby is down?
- 4. Where will public facing updates occur?
- 5. Once decided, where do we publish this information?

There are a number of things to work out. I was thinking any github issue with the p0 label added could trigger some automation that would send an SMS or email to admins. The public facing directions could ask that a p0 ticket be searched for, if not create a ticket with title "Lobby down". This will send an email to the admins already, then once confirmed we can add the 'p0' label that would in turn a specific email subject line to be sent to admins (so admins could set filters, or know if they get the confirmation that is very legit problem)

We can do public facing commentary in the same ticket to give status updates. I would suggest developer/engineering conversation be done in gitter, either a public or a private room (leaning personally towards a private/invite-only room)

For 5. I suggest we create a new pinned "what to do if the lobby is down" post in forums. I expect that would reach the right audience so enough people know that someone will file a report in a pretty timely way.

----------

Also in scope, how do we practice/enforce the DR plan? Backup plans are notorious for themselves failing, which is a shame since they are used in failure situations ... So we should probably try to automate some of the disaster recovery and practice outages every now and then.

**Comment by prastle** [comment]
Just for info. @DanVanAtta  @RoiEXLab  and all when I realized the lobby was down.  I asked in the gitter server thread and on the forum through PM as well as answering some ? on the forum.   Since Generally the forum will not be down when the lobby is down as well as gitter.  I also emailed you dan.  Can gitter be setup to auto email all in the server thread?  Which really needs to be thinned anyways since atm we only have 5 that can acess server now.

**Comment by prastle** [comment]
Starting a what to do if the lobby is down thread like the old warclub would probably work fine for the forum members.

**Comment by DanVanAtta** [comment]
@prastle the audience for the plan was more for the developer/project maintaners, for the super-technical what to do. If everything crashed, I think half of us would be deer-in-headlights and not sure what to do. 

Given there is no capacity to tackle this issue, no labor available to progress it, it's not actionable. There are many initiatives/projects I'd like to see worked on, opening an issue for them all is not going to help. Not having a DR plan is a big risk, but there does not seem the interest amongst maintainers to really jump in on it.

**Comment by prastle** [comment]
I agree
