### ISSUE TITLE
Need a TripleA How-to System Admin Doc

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3418]
One question for group, should this doc be public or private? As public we gain open source benefits, and we reduce the number of secrets we have. As private on the other hand we can include bot IP addresses (I would say passwords, but we already have those stored securely elsewhere, would not be good to mix them in that doc).

Second, we need to get the doc completed and shared. I would like @prastle to review the doc and verify he can follow it, help make sure it is complete. 

The doc I think needs to contain the process of how to traige/report and fix some likely problems. This means how to check logs, define explicitly the process so there is a step where we record somewhere that we took some actions to fix something, and last the nuts and bolts of how to do things like check services are running and restart them.

**Comment by DanVanAtta** [comment]
We do have a start of this document that is private, that would be a good starting point as it is a good chunk of this task already completed.

**Comment by prastle** [comment]
All of this was done or at least started on the forum.  Certainly all info could be public except passwords.  BUT I would like to point out if the passwords are already available interesting none of mine worked nor were they in the secret document.... when the lobby went down :)

**Comment by DanVanAtta** [comment]
This is effectively done/started - the admin forum does have a link to such a document. Moving all to be public minus passwords would be a good thing. Passwords not working was actually by design. Part of the need for documentation is so we have a clearer understanding of the system and can eventually just communicate better.
