### ISSUE TITLE
Set up a new lobby stack, Disaster preparedness

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3420]
I suggest that as an exercise, we each spin up a linode server and install a full lobby+DB stack on it, install data from backup, then login to the lobby from the game client.

For this we would assign the task to everyone, we could un-assign as we each complete it. What does everyone think?  Would this be a good drill? I'm reluctant to document this in favor of using the infrastructure scripts. The scripts make this process pretty straight forward, once we make the DB restore task easy, this would overall be a really easy task. Getting the DB setup for the first time and then loaded from a restore are not at all automated currently.

Maybe first we could have a volunteer try to build some key restore scripts, then this exercise would be easier and more relevant?

**Comment by DanVanAtta** [comment]
Assigning to everyone for input on this topic; it's pretty important we have good coverage in case things go wrong and that we all know what to do.

**Comment by prastle** [comment]
Without bringing up old  arguments I attempted to do that with all Council and Devs and Admin here.  Then it all changed again ...
https://forums.triplea-game.org/topic/653/server-admin-information/57
I guess ya need to ask all admin if they want to go through the new hoops...

**Comment by prastle** [comment]
@DanVanAtta  Off topic but concerning this Infra relaunch from linode is great! BUT it still reduces us to the linode members once working which I think you pointed out elsewhere.

**Comment by DanVanAtta** [comment]
Perhaps backing up a bit, how can we practice disaster recovery?

I'll raise this as a new dedicated issue to keep the topic focused.
