### ISSUE TITLE
Incorrect Tooltip Display For "airDefense" (1.9.0.0.10225)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#3421]
In my "WWIIv3 1941 Move-Buy-Move" mod of the "ww2v3_variants" map the tooltip display for the Fighter says "1 Air Defense", while it is 2.
I've tested the game, that appears playing correctly.

https://github.com/triplea-maps/ww2v3_variants/blob/master/map/games/WW2v3-1941-MBM.xml

This problem exists for all my games / mods of that map, that it is in turn a variant, or rather a copied original skin, of the world_war_ii_v3 map.
Side note, the air battle stuff is just how it is supposed to work per original rules in the errata for the referring World War II v3 1941 and World War II v3 1942 games of the aforementioned map. So, that is not a mod thing, actually.

**Comment by ron-murhammer** [comment]
@Cernelius This should be resolved in https://github.com/triplea-game/triplea/releases/tag/1.9.0.0.10235. Please test and let me know if its fixed.

**Comment by Cernelius** [comment]
I confirm.
