### ISSUE TITLE
Disaster Preparedness - first step, how to plan and practice a disaster? 

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3422]
Opening a thread to discuss how to plan and practice a disaster recovery procedure, please give input as interested in the topic.

**Comment by FrostionAAA** [comment]
Well ...Lucky for us we have both the website and GitHub to communicate through if one place gets annihilated.

What kind of disasters are we talking about? Vandalism, server inaccessibility, data recovery? 😯

I personally have all my own created maps on my HD and downloaded via TripleA, but I have not downloaded every single map there is to download. It might be a good idea if someone did so?

Concerning the engine data, I have no experience at all with that kind of thing 🙄

**Comment by prastle** [comment]
Server inaccessibility, and data recovery.. @DanVanAtta had a good idea about allowing us all to learn how to relaunch the server from scratch if the infrastructure launch fails.  This occurred a week or so ago.
