### ISSUE TITLE
Testing Dice Server Fails 

### ISSUE THREAD

**Issue by General-Dru-Zod** [triplea-game/triplea#3423]
### Engine version
Anything after 9713 fails.

### My Operating System
windows 10

### Map name
ww2v3 1941

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
I try to test the settings for a PBEM game. The dice server test fails.

See Forum https://forums.triplea-game.org/topic/835/testing-dice-server-fails

**Comment by ssoloff** [comment]
@General-Dru-Zod As a temporary workaround until your HTTPS issue is resolved, you can use vanilla HTTP to connect to MARTI by performing the following steps:

1. Exit TripleA if running.
1. Open File Explorer to the folder where you installed TripleA.
1. Navigate to the _dice_servers_ folder.
1. Open the _tripleawarclub.properties_ file in a text editor (preferably _not_ Notepad).
1. Change line 7 from `scheme=https` to `scheme=http` (i.e. remove the trailing `s` from that line).
1. Save the modified file.
1. Start TripleA.

If you test MARTI at this point, it _should_ work (or, at least, you won't get an SSL/TLS error).

**Comment by panther2** [comment]
@General-Dru-Zod 
To discard or confirm a Java issue please see the forum thread.

**Comment by RoiEXLab** [comment]
Solved https://forums.triplea-game.org/post/12433
