### ISSUE TITLE
travis-ci.com Migration

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#3427]
More info:
https://blog.travis-ci.com/2018-05-07-announcing-support-for-github-checks-api-on-travis-ci-com
https://docs.travis-ci.com/user/open-source-on-travis-ci-com

@ron-murhammer I already sent the request, this is just to provide some clarification of why this request was sent.

**Comment by ron-murhammer** [comment]
@RoiEXLab Should be approved now.

**Comment by RoiEXLab** [comment]
@ron-murhammer 👍 
If I understand [this](https://docs.travis-ci.com/user/open-source-on-travis-ci-com/#Existing-Open-Source-Repositories-on-travis-ci.org) correctly, all we need to do now is waiting for this repo to be migrated in a couple of months.
We can reopen this issue if anything won't work as expected .
