### ISSUE TITLE
Bots should scan for new maps - avoid service restart to pick up new maps

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3429]
We have a problem today that bot application instances need to be relaunched to pick up new maps. The ask/proposal here is that bots periodically check for new maps beyond just at startup without needing a restart. This would cut out maintenance overhead as today the restart is a manual process.

Please chime in if interested in working on this so we can avoid duplicate efforts. This is a good one to get completed!

**Comment by prastle** [comment]
@DanVanAtta  off topic but since the restarts by chron job erase all memory of previous commands (thus requiring to completely retype any) Is there also any way of keeping the previous logs?  If anyone is working on this that would be helpful as well.

**Comment by DanVanAtta** [comment]
tab completion and `history` command should help.

**Comment by RoiEXLab** [comment]
@DanVanAtta history seems broken the last time I tried to use it, it only showed the commands of the current session, I assume this might be related to the high memory usage, so the system tries to delete uneccessary info.

**Comment by DanVanAtta** [comment]
Sounds about right, the bot really just needs maintain a string list. The memory usage could be a good win, a running game AFAIK does not use much memory, most of the memory requirement seems to be for the initial map parse.

I wonder a bit how unified the logic is between the bot and stand-alone client. Happy to see any progress @RoiEXLab , please feel free to share any work in progress as you can.

> Basically we'd just parse all available maps on start

We'd need to check on game end too, part of the idea is that maps can be added/removed/updated, and we do not want to require an application restart. The game client used to require this too, we updated that so updates are picked up whenever the select game window screen is opened. 

It seems like bots are doing a deep parse as well, they should not need to. The parse time on a game client is pretty fast, even if you add the 30-45 seconds for War of Relics, but bots take a few minutes to get through all the maps and launch. Seems like they are doing the 'full parse' perhaps which loads the entire file as a game data object. Simply doing the shallow parse might have the same effect (to consider).

**Comment by Cernelius** [comment]
Somewhat related to:
https://forums.triplea-game.org/topic/780/allowing-players-to-upload-their-own-maps-into-bots-temporarily/4
>Actually, at the developers, why do the bots need to have the map at all?
>The skin, for sure there is no reason for the bot to need it, as the bot doesn't need to see the map and play it.
>The games (xml), it is good they have them, but one could just load a game you have, just as you can load a savegame (really, no difference).
>There is really no reason at all for the bot itself to have to have the map or to crash for not having it or to need the map for loading a savegame, either. But I know this is the way it works now.

**Comment by Cernelius** [comment]
Meaning you may prefer to go all the other way and have the maps having no maps at all, comprising also having no games at all, as well. Thus the bot itself would never parse anything.
Then the "Choose game" button would just give the games that the user itself have, like now for loading a savegame.
So, you just have the options of
- loading one of your xml,
- loading one of your savegames or
- loading an autosave from the bot.

**Comment by Cernelius** [comment]
An argument against what I just said may be that, then, users are less driven to update their stuff.
For example, if one updates WAW from 2.1.1 to 2.2, then the bots are updated, and all bots users are made to play the 2.2, while, if they would load their own games, you would see people keeping loading the old version for a long time, maybe just because they don't bother to update for years.
So, maybe having the bots having their own games list, instead of being almost purely a private host substitute, may be preferable. Just giving so pros and cons to think about, if anything I'm saying is any feasible.
