### ISSUE TITLE
Increase Default Run Counts Request (1.9.0.0.10242)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#3431]
If I'm not mistaken, the current default is 200 run count for dice and 500 for low luck.
I believe 200 is clearly too low a run count to be reliable, at least in some cases.
I think that, both for dice and low luck, the run count should be 1000, and at least 500.
Also, I don't see any major reasons for having different defaults for dice and low luck (I know this is a tradition), so I think the same default for both is preferable, as more intuitive (I guess most users don't even realize the values are different in each case).
So, I suggest to have the same default for dice and low luck, set at 1000, or at least at 500, the same for both.
But mainly 200 for dice is really too low, in my opinion.
Of course, customizing them is easy (so, doesn't matter to me, personally), but I guess it may be an annoyance for new users (and anyways I believe that the defaults should be prime choices, and this is my opinion about what that is).

**Comment by beelee1** [comment]
I'm set at 2000 for dice. It takes a lot longer than 2 seconds usually for me. I wonder if having different units is slowing it down more as opposed to the number of units ? 

At any rate, a boost of some sort might not be a bad idea. As Cernel said though, not really a big deal, just trying to optimize : )

**Comment by ron-murhammer** [comment]
@Cernelius I'm open to changing this but I'd like to see a poll or some forum discussion where at least a handful of players agree with the adjustments. I'm gonna close this until there is more community backing for the change.

**Comment by Cernelius** [comment]
Yeah this is probably better on forum, but since you have removed the program discussions from there... Is this a feature request?

**Comment by ron-murhammer** [comment]
@Cernelius Yeah, I'd say it fits best under feature requests.

**Comment by Cernelius** [comment]
Guess I'll limit it to a proposal to increase dice default from 200 to 500 or 1000, since I think low luck at 500 is fine.

**Comment by DanVanAtta** [comment]
It'd be interesting to run some stats to know when we are above a 97% confidence interval. I can try to crunch some numbers on that one evening this week.

**Comment by Cernelius** [comment]
The feature request is here:
https://forums.triplea-game.org/topic/863/increasing-regular-dice-default-run-count
