### ISSUE TITLE
MARTI emails inconsistencies

### ISSUE THREAD

**Issue by General-Dru-Zod** [triplea-game/triplea#3438]
### Engine version
10235
### My Operating System
win10
### Map name
ww2v3 1941
### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)

Playing a PBEM and the MARTI emails are not being sent as per setup. Experienced some inconsistent results as well. For example on German r1, I received 2 of 10 expected MARTI emails. And on Japanese r1, I received none of the expected MARTI emails. The opponent received MARTI emails as normal throughout. Btw, my opponent is the axis.

These are my opponents setup settings used initially, which were inconsistent and not functional for me.
Dice Server:dice.tripleawarclub.org
To:general.zod.v1@gmail.com
Cc:poorfool@outlook.it (my opponent)

After some mock PBEM tests with @prastle. I found that if the recipients were swapped, it worked. This is opposite of what the help button indicates to do.

These are my opponents new setup settings. So far they are functional.
Dice Server:dice.tripleawarclub.org
To:poorfool@outlook.it  (my opponent) + (also my initial setup)
Cc:general.zod.v1@gmail.com

One last note the test button works with either setup.

**Comment by General-Dru-Zod** [comment]
Correct me if I'm wrong. I think maybe the "dice server" section needs to be setup once. And by the player going first. 

In ww2 v3 1941 this would be the Allies because they always get a bid. 

I think part of he problem may have been that poorfool changed the setup of the dice server section, as relative to him. After I had already set it initially as relative to me. Meaning that he placed his email into the cc: field and my email into the to: field.

**Comment by panther2** [comment]
> Correct me if I'm wrong. I think maybe the "dice server" section needs to be setup once in a PBEM. And only by the player going first.

You are right, the dice server section needs to be set up only once. This setup is part of the savegames, then. It is irrelevat who sets it up. Also it is irrelevant who goes first. As long as there is as well a registered maill address in the "to" field as another one on the "cc" field the order does not matter.

Of course when players start to alter the settings, there is room for errors.

**Comment by ron-murhammer** [comment]
@General-Dru-Zod The order of the emails shouldn't really matter unless there is some kind of strange bug. Did you make sure to double/triple check that none of the emails were in your spam folder? If you can pretty reliably reproduce not seeing emails then that would make it much easier to debug this as I really haven't seen this reported.

**Comment by RoiEXLab** [comment]
I want to point out that we have some issues from time to time that some mails don't get send to specific mail providers for some reason.

**Comment by ron-murhammer** [comment]
@RoiEXLab True but given that Zod had a gmail address, we really haven't seen any gmail issues.

**Comment by General-Dru-Zod** [comment]
I can confirm that the MARTI emails were not sent to my spam box. Except
for the first one. But all subsequent MARTI emails bypassed spam box.

**Comment by General-Dru-Zod** [comment]
Oh btw, when I say subsequent MARTI emails, I am referring to the many tries after the initial failures. Those tries were in mock games to test if changes to the recipients mattered.

**Comment by DanVanAtta** [comment]
Few questions, @General-Dru-Zod  mostly for you if you would kindly chime in:
- is this an ongoing problem?
- is this a problem 100% of the time with the specific email address? Can you use a different email with luck?
- Is this a new problem, do you experience this in earlier versions of the game?

This is a likely P1 issue @ron-murhammer  @RoiEXLab .

**Comment by General-Dru-Zod** [comment]
@dan van atta,

This problem was resolved by having my opponent change recipients To: and
Cc:. He is sending to himself and cc to me now and is functional.

Problem was fairly consistent otherwise, meaning to: = me and cc: =
opponent. (in opponents settings)

This is a new problem.

**Comment by ron-murhammer** [comment]
@General-Dru-Zod Any further updates here? Unless we can create a way to consistently reproduce this with say test email accounts then I don't know that there is much we can do. Generally if both players use a gmail account, I've never seen any problems or switch to PBF instead of PBEM. Outside of that I've seen a number of challenges with other email providers and its hard to reproduce/address them. 

Gonna close this for now but can re-open if you think we can reproduce it.
