### ISSUE TITLE
Canal Attachment Improvements

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#344]
Discussion: http://tripleadev.1671093.n2.nabble.com/Multiple-Canals-Between-2-Sea-Zones-td7590656.html

Look to create a better canal attachment that is easier to use and covers more scenarios.

Something like this is what it would look like this in the xml (pseudo-code): 

name=Suez 
connection=Sz16:Sz34 
condition=conditionAttachmentOwnEgypt 
(unit exceptions, other stuff, etc...) 

It should be done in a backwards compatible way, similar to how things like isArtillery actually create support attachments behind the scenes, canal attachments could create whatever the new attachment is behind the scenes as well.

**Comment by DanVanAtta** [comment]
Any specific directions determined? Please document any specific action items if any exist. It does seem to me that the XML could be simplified.

**Comment by ron-murhammer** [comment]
Veqryn made some high level suggestions in the thread but still would need some design and details before implementing:

so it would look like this in the xml (pseudo-code): 
<canalSuez>
  name=Suez 
  connection=Sz16:Sz34 
  condition=conditionAttachmentOwnEgypt 
  (unit exceptions, other stuff, etc...) 
</canalSuez>

It should be done in a backwards compatible way, similar to how things like isArtillery actually create support attachments behind the scenes, canal attachments could create whatever the new deal is behind the scenes as well.

**Comment by DanVanAtta** [comment]
I vote we start versioning the XML map spec. IE: 
`<game xmlVersion=2.0> .. </game>` 

It's something I think we're going to want/need to do coming down the road. Namely we have some really long XMLs, lots of redundant information, clearly we are able to do better. Thus if we introduce a version, missing version is 1.0, we'll have a much easier time updating/augmenting the XML.

Second, please don't create any encodings that have to parsed (ie: no colon delimiter)

eg:
```
<canal>
<name>Suez</name>
<connection>Sz16</connection>
<connection>Sz34</connection>
<condition>conditionAttachmentOwnEgypt</condition>
</canal>
```
I also don't think a name element is needed for Canals. It's also seems extra to create a "conditionAttachmentOwnEgypt" entity just to say you must own egypt.

I hope we can then get it to be simpler, looking more something like this:
```
<canal>
<connection>Sz16</connection>
<connection>Sz34</connection>
<controllingTerritory>Egypt</controllingTerritory>
</canal>
```
Note, with this config you could have as many controlling territories as you like.

**Comment by veqryn** [comment]
I think you need to re-read that discussion @DanVanAtta.

The whole point is that canals need more advanced logic than just the controlling of some number of territories.

Instead of re-creating all this logic inside of a canal attachment (or whatever we call it in the future), just offload all that logic into something that already handles all logic and use cases perfectly: condition attachments.

**Comment by DanVanAtta** [comment]
I'm more suggesting we 'hide' the condition attachment as an implementation detail of the 'canalAttachment'. I  believe we should approach this problem from the point of view of what would be the simplest XML, rather than what would be the simplest most backwards compatible code change.

**Comment by DanVanAtta** [comment]
@ron-murhammer , was this updated/resolved in one of the PRs about canal movement?

**Comment by ron-murhammer** [comment]
@DanVanAtta This is a feature request to eventually expand and refactor canal attachments. I did the short term fixes to allow TRS/WaW to work with what we already have in #296

**Comment by DanVanAtta** [comment]
This ticket is not very actionable in its current state. @ron-murhammer Would you mind summarizing the proposed changes?

**Comment by ron-murhammer** [comment]
@DanVanAtta Updated the first comment. Essentially create a better canal attachment that handles all types of conditions rather than the limited version we have now. There is still a decent about of design that needs to be done on this before implementing.

**Comment by BeornTheBold** [comment]
I would like to see canals be a constructable item by a player, and be damageable by air strikes or even sea bombardment.  This could be done using current conditions logic, checking for the existence of a non-disabled unit (e.g. "canal") being in the territory.

**Comment by DanVanAtta** [comment]
@ron-murhammer , is this still worth tracking as an issue? Move to here: https://github.com/triplea-game/triplea/wiki/Feature-Back-Log, or perhaps we should re-summarize this and open as a new one issue if there is design to be discussed.

**Comment by ron-murhammer** [comment]
@DanVanAtta I guess I'm a little unclear what you want to do here? Are we trying to create a wiki page for feature backlog rather than issues?
