### ISSUE TITLE
My opponent in WWII revised can see PUs but I cannot and so cannot buy anything. My best guess is it's a java version issue. I'm running java 10. You might want to inform members not to upgrade java.

### ISSUE THREAD

**Issue by JesseBoulard** [triplea-game/triplea#3454]

**Comment by ron-murhammer** [comment]
@JesseBoulard Yeah, we haven't done any java 10 testing yet. Are you able to have it work with an older version of java?

**Comment by JesseBoulard** [comment]
Yes, uninstalling java 10 solved the issue, but I will need java 10 at some point. How do you choose an older version of java? It seems to default to the latest

**Comment by RoiEXLab** [comment]
I'm not sure if there is a stable out with this restriction:
By downloading the latest pre-release installer, it should restrict your java version to java 8.
This way you could use the different versions side by side.
