### ISSUE TITLE
Multiple applications bundled together in the same project

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#346]
We have the tripleA game, lobby code, dice roller code, and perhaps yet more applications all bundled with the triplea project. @veqryn , how would you want this solved?

I could see as potential solutions:
a) clearly splitting packages and clearly identifying what belongs to what
b) having multiple repo's.

Personally I would lean towards A because we have no maven repo set up. Also splitting out the common code could be painful for us, as well as managing it as 'common'

To elaborate on "a":
 - we would identify clearly the sub-applications we have in the project
 - Add to gradle a way to build each one. 
 - create a config folder, and under it a sub-folder for each application
 - organize the packages from `games.strategy.*` to `org.triplea.<application>.*` 

Thus we would have the source and configuration organized. Assets would live in the assets repo, preferably under a folder that has the same name as the application, ie: (lobby, client, and dice_servers)

**Comment by veqryn** [comment]
I'd don't mind a reorganization of the location of code, so long as it comes after most PR's are committed or closed, and the PR to move stuff around makes no changes and uses git mv to ensure history on those files is kept.

I am having trouble remembering how the dice roller stuff fits in, but at any rate I think the biggest trouble will be deciding what goes to lobby, what goes to client, and what would go to some series of appropriately named packages for common code.

**Comment by DanVanAtta** [comment]
dice roller is one of multiple applications bundled with TripleA. There is a lack of cohesion around the 'non-core' deployables in the TripleA project, namely: dice roller, lobby, and bots.

I propose we try to avoid solving the "common" code problem as much as possible for now. The main problem to be solved is how to group things so we can at least *see* everything. Same for the configs.

As a first suggestio, I propose we start by splitting up packages:
- org.triplea.client, everything that does not belong specifically in the other packages. Effectively this is going to be 'games.strategy.triplea' renamed.
- org.triplea.ai, the minimum set of AI code , 'games.strategy.triplea.ai'
- org.triplea.lobby, the minimum of what is needed to run/support the lobby
- org.triplea.diceroller, similar as lobby, minimum to launch/run a dice roller


Note, no common code package. Idea is to split off minimum into the lobby and dice roller packages, and the AI package will peel off very naturally as well. We still have the issue of bundling every class file together for each application, but it's not a huge problem. Thus I think there is benefit here that outweighs cost.

Last, the biggest issue will be updating executable paths, any scripts that reference main files. We'll also need to update map XMLs too.. Which is now at least very possible with all maps in github.

**Comment by DanVanAtta** [comment]
#389, is an example of 'another' bundled application - "map maker tools" specifically.

**Comment by DanVanAtta** [comment]
Several tickets are open to track the individual components which need to be unbundled/deployed indepenent of the game engine. Closing - this ticket is not readily actionable.
