### ISSUE TITLE
Document Discontinued Items 

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#3463]
I'm seeing that the names starting with "AI" or "Neutral" now don't default anymore to AI.

For example, the "Neutral_Axis" of "World War II Global 1940 2nd Edition" or the "AI_Confederate_Commanders" of "Civil War: A House Divided" are now assigned defalt to Human, while they used to default to AI.

I don't know if this is intended and it has been documented somewhere. I'm assuming it is intended, otherwise you would have at least deprecated it.

If so, are you sure you want to remove a functionality that impact on many available maps? I'm not against it (I actually tend to agree with it, as just having a wrong default is not a big deal and it is good to stop this practice beyond deprecating it) but, for example, I'm not seeing a stickied topic in Mapmaking, telling all those games need updating.

This is not an issue for this specific matter. Are there any other discontinued items done after 1.9.0.0.3266 and do you want to document them somewhere like:
https://github.com/triplea-game/triplea/wiki/Upgrade-Maps-Information
?

**Comment by ron-murhammer** [comment]
Yes the old starts with AI or Neutral functionality was removed when the new parameters were added. I decided negative impact to existing maps was minimal so wasn't worth keeping that old functionality.

**Comment by Cernelius** [comment]
I suggest having a stickied topic in forum Mapmaking telling the mapmakers that they should update their maps relying on AI or Neutral start names.

I agree no more is needed and I suggest to close this issue once it is confirmed that no other items have been discontinued since 1.9.0.0.3266.
