### ISSUE TITLE
Chat Dialog Box Missing

### ISSUE THREAD

**Issue by prastle** [triplea-game/triplea#3465]
### Engine version

10375
### My Operating System
NA
### Map name
WAW
### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Joined a game in progress running the newest engine and chat dialog bot was non existant.  Reverted to 10182 and it returned.
### Instead of this error, what should have happened?
Should have had the chat dialog box appear and been able to type in it.

**Comment by RoiEXLab** [comment]
@prastle #3465
Already opened that PR before you opened this issue.
100% Proof I'm a time-traveler

**Comment by prastle** [comment]
:) you are a god :)

**Comment by RoiEXLab** [comment]
@prastle The issue should be resolved, please check back if it really is, because you didn't mention any error message I got myself when experiencing thie

**Comment by prastle** [comment]
Just tried 380 and revised no error no chat box
Debug shows this
ripleA engine version 1.9.0.0.10380
Loading map: world_war_ii_revised, from: C:\Users\prast\triplea\downloadedMaps\world_war_ii_revised-master.zip
Loading resources from the following paths: [C:\Users\prast\triplea\downloadedMaps\world_war_ii_revised-master.zip, G:\10380\TripleA\assets]
Loading map: world_war_ii_revised, from: C:\Users\prast\triplea\downloadedMaps\world_war_ii_revised-master.zip
Loading resources from the following paths: [C:\Users\prast\triplea\downloadedMaps\world_war_ii_revised-master.zip, G:\10380\TripleA\assets]
Heap utilization statistics [MB]
Used Memory: 90
Free memory: 324
Total memory: 415
Max memory: 1820


Can't chat

**Comment by RoiEXLab** [comment]
Version 10300 might be a good starting point. I assume it's the first version this issue occurs, but I don't have the time to test different versions
