### ISSUE TITLE
It would be nice if dice stats were restored from saved games

### ISSUE THREAD

**Issue by asvitkine** [triplea-game/triplea#3478]
It would be nice if dice stats were part of the save game.

Right now, if you have a long-running game that you play over multiple days (e.g. with a human opponent over the internet), the dice stats gets reset whenever you reload the game.

It would be nice if they persisted.

**Comment by beelee1** [comment]
my saves have the dice in history still. Those are local games so idk if that makes a difference

**Comment by Cernelius** [comment]
I never understood that, either.

I'm largely uninterested about that feature (or at least I virtually never look at it) but it seems almost pointless if you can only look at a whole game dice stats playing it from start to finish in one go and cannot reference it thereafter, losing all stats as soon as you quit it.

**Comment by Cernelius** [comment]
But I think that the stats themselves shouldn't persist (that would mean being recorded in the savegame), but the program giving the dice stats should be able to go reading the history when you open it, rather than collecting the data since you start playing (that I assume it is what it is doing now).

**Comment by asvitkine** [comment]
Ah, if it's in the history already, then yeah sounds like the game should
just read from there.

**Comment by asvitkine** [comment]
I'll take a look at implementing.

**Comment by Cernelius** [comment]
How does it work for someone playing with you in a game you are hosting? It is you that make the stats and send the finalized info to the other player or do you send him the dice history and he creates the stats?

**Comment by Cernelius** [comment]
Unfortunately I don't play the very big maps, like a round 40 or World At War or Domination. That is what I was thinking.

**Comment by asvitkine** [comment]
The data is already in history which is already sent to players. So no
extra sending is needed.

**Comment by Cernelius** [comment]
Ok, right, but what I was asking was if you meant "raw data" (that you use to make the statistics) or the statistics themselves. I'm not a developer.

**Comment by asvitkine** [comment]
The history has the raw data. We rebuild the statistics from that. It's
fast because there's not really much computation in computing the
statistics - just iteration over the history which is already done when
e.g. receiving it.

**Comment by Cernelius** [comment]
Ok what I understand is that each terminal rebuilds the statistics from the history, and nothing changes about the data sent over the internet between terminals from now. Correct?

**Comment by asvitkine** [comment]
Yep, that's how it works.
