### ISSUE TITLE
Civil War, no notification error

### ISSUE THREAD

**Issue by wirkey** [triplea-game/triplea#3491]
### Engine version
8847

### My Operating System
Win10

### Map name
Civil War: A House divided V3.2.4 

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Taking a loan. This happens only in the bots. Cernel and redrum tried on Cernel's host and it worked fine. It does not happen if you do it in local mode

### Do you have the exact error text? Please copy/paste if so
NO: Confederate_Take_Loan_at30.OTHER_NOTIFICATION_SUCCESS set.

### Any additional information that may help
see upper left
[https://forums.triplea-game.org/assets/uploads/files/1530206909946-d9055f08-151d-490f-95a8-745dbfba847d-image.png](https://forums.triplea-game.org/assets/uploads/files/1530206909946-d9055f08-151d-490f-95a8-745dbfba847d-image.png)

**Comment by Cernelius** [comment]
Notifications work for me in my host but not in automated ones. It shouldn't be a map issue.

**Comment by ron-murhammer** [comment]
My guess is you have some sort of map version mismatch. As the error seems to indicate that one of the action text properties is missing. But it is clearly there and hasn't been changed recently: https://github.com/triplea-maps/civil_war/blob/master/map/actionstext.properties#L52

**Comment by wirkey** [comment]
tried it with 10440 in bot 204.
The loan notification error still shows. Map is playable, though

**Comment by Cernelius** [comment]
I'm not sure we are on the same page.
With:
>Notifications work for me in my host but not in automated ones.
I meant that using the latest prerelease and having the latest map I get the notifications on local or in my private host, but not in bots. Same for @wirkey.
I suggest you join a bot and try yourself.
