### ISSUE TITLE
Move Existing Fighters to New Carrier When Multiple Adjacent Factories

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#350]
http://tripleadev.1671093.n2.nabble.com/Select-Naval-placement-factory-td7590853.html
https://sourceforge.net/p/triplea/feature-requests/265/

If you place carriers in a sea zone with multiple adjacent factories it randomly chooses which territory to prompt about moving existing carriers which might not be the right one. Only fix is to use EDIT mode.

**Comment by ssoloff** [comment]
Reopening as the fix in #1766 was reverted in order to address the incompatibility reported in #2133.  See #2148 for the changes that need to be re-applied in the next incompatible release.
