### ISSUE TITLE
Endless Loading Game Bar Upon Joining Games Without Having The Map And Automated Map Download Broken (1.9.0.0.10440)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#3501]
When trying to join a game I don't have the map for:

> TripleA engine version 1.9.0.0.10440
> Loading map: , from: C:\Users\001\Documents\GitHub\
> Loading resources from the following paths: [C:\Users\001\Documents\GitHub\, C:\Program Files\TripleA\assets]
> Setting memory for new triplea process to: 2G
> TripleA engine version 1.9.0.0.10440
> Failed to start Game
> games.strategy.engine.framework.startup.launcher.MapNotFoundException
> 	at games.strategy.triplea.ResourceLoader.getMapResourceLoader(ResourceLoader.java:66)
> 	at games.strategy.triplea.ui.HeadedUiContext.internalSetMapDir(HeadedUiContext.java:75)
> 	at games.strategy.triplea.ui.AbstractUiContext.setDefaultMapDir(AbstractUiContext.java:104)
> 	at games.strategy.triplea.ui.TripleAFrame.create(TripleAFrame.java:226)
> 	at games.strategy.triplea.TripleA.startGame(TripleA.java:122)
> 	at games.strategy.engine.framework.startup.mc.ClientModel.lambda$startGameInNewThread$6(ClientModel.java:344)
> 	at java.lang.Thread.run(Unknown Source)

I get an endless loading "Please Wait" window, I cannot close.

I also get the "Download Map?" window, but I cannot click on it at all. If I try to do it, I instead appear to be clicking on that TripleA istance, I opened trying to join.

This issue seems consistently happening the same way in any case you join a game you don't have the map (practically, the original skin) for.

I'm on Windows 10.

**Comment by Cernelius** [comment]
Confirmed under 1.9.0.0.10467 too; rest the same.

**Comment by RoiEXLab** [comment]
@Cernelius Could you try out 1.9.0.0.10480 to see if this fixed this issue?

**Comment by Cernelius** [comment]
The specific issue is fixed, but, if you'll excuse the off topic (just tell me if you'd like a specific issue for this), I'd like to point out, as a side note, a behaviour that it is in place since a while, and, also, in my opinion, lowers the functionality of the direct to download feature upon crashing for not having the map (that is the original skin), at least for the casual user.

Each time something like this (not sure how to call it) is closed, I get something like this (in this case, this is what after clicking on the window asking me to visualize the error log):
![20180701_01](https://user-images.githubusercontent.com/19562310/42137174-1793d726-7d68-11e8-8156-bf5b1d9ba3ea.png)

Why do I get that "Client options" window? What's the point? I recall I didn't, in past (1.8.0.9 and for some time thereafter).
Anyways, I get to download the missing map after closing the "Client options" window, so I believe this issue can be closed, tho I tend to think that the user should get the download option right away after crashing, not after having to close other two windows hiding it (first you get asked about the error log, then you get the client options and then you get the proposal to download the missing map (I think the error log, in this case, is useless too, if the matter is just that you don't have the map, in the moment you would get prompted to download it)) (in my mind).

Anyways, I confirm this specific issue is solved and can be closed.

**Comment by ron-murhammer** [comment]
@Cernelius It probably would be better to open a separate issue so its clear that the original issue reported here is resolved.
