### ISSUE TITLE
On maps with scramble rules, AI will send undefended transport landing parties that will simply be killed by scrambled planes.

### ISSUE THREAD

**Issue by asvitkine** [triplea-game/triplea#3505]
On maps with scramble rules, AI will send undefended transport landing parties that will simply be killed by scrambled planes.

For example, this happened on WW2 Pacific 1940 2e with US Hard AI player sending some transports to invade Korea which were simply killed (with their landing parties) by scrambled planes from Japan. Complete suicide move with no chance of survival since unescorted transports have no defense.

Saved game attached that shows this in history.

### Engine version
Trunk at git hash ac1015bbfde02989d5181932fbd753416939f277

### My Operating System
Mac

### Map name
World War II Pacific 1940 2nd Edition

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Have no navy in the sea of Japan and have US fleet with loaded transports near by, with US on Hard AI.

### Do you have the exact error text? Please copy/paste if so
N/A

### Instead of this error, what should have happened?
The US should not have sent its transports unescorted into a scramble zone.

### Any additional information that may help
Saved game attached. See US combat moves in round 10 where they sent some transports undefended to land units in Korea and were completely taken out by scrambled planes.

This also happened a few other times in subsequent rounds, that can be seen in history.

[ww2_pac_end.tsvg.zip](https://github.com/triplea-game/triplea/files/2156826/ww2_pac_end.tsvg.zip)

**Comment by ron-murhammer** [comment]
@asvitkine I'm 95% sure that the gap is that the AI doesn't support scramble property "Scramble to Any Amphibious Assault" quite yet. As if you turn that off then I don't believe Japan can scramble to attack the transports. Scrambling is something relatively new to the AI which has a decent number of different options that are a bit challenging to take all of them into account as I'm not sure even I understand all of them :)

I mostly track AI requests here and added it to the list: https://forums.triplea-game.org/topic/105/ai-development-discussion-and-feedback
