### ISSUE TITLE
There is a lot of very similar code for display unit images in swing

### ISSUE THREAD

**Issue by asvitkine** [triplea-game/triplea#3507]
There is a lot of very similar code for display unit images in swing.

As I'm going through and updating more places to have unit tooltips, I find there's a lot of very similar logic for creating JLabels with unit icons and often "x 2" style strings.

It would be good to unify all of this code - maybe as a custom JComponent subclass (maybe JLabel subclass) for display a unit's icon.

Since I'm already adding tooltips to these, it should be easy to find them by looking at places where MapUnitTooltipManager.setUnitTooltip() is called.

**Comment by ron-murhammer** [comment]
Agree definitely could use some consolidation. I recently did a bunch of work with resource images and tried to create some helper method for generating the panel to be displayed. Example: https://github.com/triplea-game/triplea/blob/43ad70c34566632266d6f8c01a7df4204b87248f/game-core/src/main/java/games/strategy/triplea/image/ResourceImageFactory.java#L59

**Comment by DanVanAtta** [comment]
I'd agree would be a good cleanup.

Common component would likely work. Inheritance can have issues, a composition approach might work be cleaner, so good to think about it.

As a suggestion along those lines, I'm personally a fan of course of the swing builder components added that reduce the syntax on swing. I think combining that with a tool tip factory would be effective. This way we are not coupling the UI component with how we create the tooltip text. For example:
```
JLabelBuilder.builder()
   .text("..")
   .tooltip(UnitTooltipFactory.createUnitTooltip("..."))
   .build();
```

(https://github.com/triplea-game/triplea/blob/master/game-core/src/main/java/swinglib/JLabelBuilder.java)

**Comment by DanVanAtta** [comment]
This topic is getting a bit aged, will close this for now.
