### ISSUE TITLE
Unit tooltip in the latest pre-releases

### ISSUE THREAD

**Issue by FrostionAAA** [triplea-game/triplea#3510]
_(This post has been edited to be more up to date with the recent development, and also to pass on some of the feedback and ideas posted in the replies)_

Unit tooltips has recently been worked on and enhanced. The newest pre-releases have tooltips automatically pop up when player mouse-over a unit. This is great :-) But here are some suggestions:

1.	Add an option to turn off tool tips in the **game --> engine settings --> Game**. It would be great for people who for some reason or another wanted to turn tooltips off. 

2.	Would it not be much more practical, user friendly and readable to have unit tooltips display info on several short lines instead of one or two very long lines? It could be more compressed lines than the present. The unit info could be displayed as “2Att/3Def/2Move”, “2A/3D/2M”, “2/3/2” very similar to the purchase screen info. Or the info could be display more in full like in these screenshots to help new players understand.

3.	When/if tooltips were made to be displayed in shorter lines, it would be nice if some dubious phrases were rephrased for better understanding.

**Envisioned and possible changes:**
![example](https://user-images.githubusercontent.com/15268177/42202415-9e025c68-7e9b-11e8-913b-545b4e004270.png)

**Comment by Cernelius** [comment]
My suggestion is/was 1 second if this can be switched off and 2 seconds if it cannot.

Also, it should be optional per map (or even game). Once you have fully learned a game, you don't want to see tooltips anymore, unless the game has some random triggered dynamics (very rare).

**Comment by Cernelius** [comment]
Really, some info can be written more concisely. For example "**gives -1 power to 1 Enemy Units when Att/Def**" (side note, saying "power" is ill-defined or outright wrong: it should rather say "strength") (side note, can it say "Unit", instead of "Units", when the supported number is 1?) can be "**-1 Att/Def strength to 1 Enemy**", and I think everyone will understand it still (but I know that this is tricky to implement, as per past discussions, since the xml attachments define the situation of the unit giving the support (that gets traduced into "when Att/Def", in this case), so my suggestion would need the program to be able to reverse the Att/Def attribute when the receiver is enemy (meaning the opposite side in the battle (you can have hostile units on your side)) (for example "gives -1 power to 1 Enemy Units when Attacking" should become "-1 Def strength to 1 Enemy", that I think it would be also faster to understand).

**Comment by Cernelius** [comment]
Another issue is that the cursor tend to hide the tooltip, in particular the stack number. You can test this issue in "Lord of the Rings: Middle Earth".

**Comment by FrostionAAA** [comment]
Totally agree on the tooltip phrases needing reformulation.

On the stack numbers hidden, note that I have written the number in the mock up picture wish. I think would be good as we have no way of knowing where the number, by options, is set to be displayed. So we never know if it will be hidden behind tooltip. Tooltip could say like "2 Infantry" or "2 German Infantry".

It would be great if the tooltip mentioned ownership, especially for complex maps.

**Comment by RoiEXLab** [comment]
@asvitkine Probably something you want to have a look at ^^

**Comment by ron-murhammer** [comment]
The unit tooltip is used in a few places so I don't think stack number should be included and instead the tooltip should be adjusted to be a bit further away from the unit center to not cover it.

I do agree with avoiding long lines with commas though I think some of the info needs to be simplified and standardized in format. I think attack/defense/movement should just be displayed as "1/2/1" for example. Then more advanced/less used options get their own line like you have in the examples (support, transport cost, transport capacity, AA attacks, etc).

I think something like the first 3 lines being standardized to:
Unit Type - Owner
Land or Sea or Air Unit
A/D/M

**Example (revised):**
Infantry - Germany
Land Unit
1/2/1
2 Transport Cost

**Comment by asvitkine** [comment]
I'm a bit conflicted on the shorthand notation. On one hand, it's clearly shorter and nicer - but on the other hand tooltips are supposed to help new players and new players might not be familiar with it.

**Comment by asvitkine** [comment]
Sent https://github.com/triplea-game/triplea/pull/3511 to improve tooltip positioning, delay and improving the first line of text.

**Comment by Heppisorus** [comment]
I think a standardized format is good.
But if something more was needed for newbs...  why not something like this....
Example...

![tool tip](https://user-images.githubusercontent.com/30943648/42256185-c3ff1bb8-7f1d-11e8-88c2-8e5d205bd57a.png)

A tool tip within a tool tip might work well.  That would keep the info concise but allow some one who doesn't know a way to get clarification.

**Comment by Cernelius** [comment]
I thought about a tooltip inside a tooltip, as well, but I tend to rule it out, as it feels hypertrophic.

The item I was thinking about is that, as in the @FrostionAAA case, the support tooltips have a major limit, either:
- The supported unit list is given in the tooltip, making it ridiculously long/wide.
- The supported unit list is not given in the tooltip, leaving no way to know what is supported (this can be considered an issue, if the tooltip are supposed to give full info).

So, for this, the two solutions I see are either a tooltip in a tooltip, with the supported list, or telling in the supported units' tooltips what they are supported from. I prefer the second solution, and not listing the supported units in the supporting unit tooltip at all.

**Comment by Cernelius** [comment]
Also I think it would be more opportune if the tooltip appears 2 seconds after the cursor stands still on the image, not just standing on the image even moving.

**Comment by Cernelius** [comment]
Between the current and something like just 1/2/1 I'd offer a compromise:
```
Att/Def 1/2
Movement 1
```
But there is little point in considering other items before doing anything with the fact that you can have a support info with all a list of supported units that is going to make the tooltip super-wide regardless.

**Comment by FrostionAAA** [comment]
I have updated this post to be more up to date in regards to the recent changes, as well as updated with this threads feedback and discussions.

I also still regard this thread as “open” :-)

**Comment by ron-murhammer** [comment]
@FrostionAAA Good consolidation. I'm going to move this to the forum since it is really more of a feature request as that'll make it easier to track and allow a wider audience to provide feedback: https://forums.triplea-game.org/topic/942/unit-tooltip-suggestions-pre-release-feedback
