### ISSUE TITLE
Civil War, interest payback

### ISSUE THREAD

**Issue by wirkey** [triplea-game/triplea#3512]
### Engine version
10440

### My Operating System
Win10, 64bit
### Map name
Civil War
### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Every time you click on a user action and/or close the window the sum to payback as interest for the loan increases
### Any additional information that may help

[https://forums.triplea-game.org/assets/uploads/files/1530733788895-cw-hale-vs-wirkey.tsvg](url)

Please zip and post a save game to this bug report!

To zip a save game:
 - find the save game file ending with '.tsvg'
 - use a 'zip' program like winzip (file compression, example: https://www.wikihow.com/Make-a-Zip-File)

Once zipped, you can post the zip file to this issue, thank you! 
-->

**Comment by ron-murhammer** [comment]
@wirkey Uh, how did you create that save game? It definitely has a problem but if I start a new game on the latest version of CW then I don't see that same behavior.

**Comment by DanVanAtta** [comment]
It does not look like this should happen anymore. Tracing this back to the reported version, a map property called 'm_costPu' needed to be non-zero to see this behavior. Since then that code has been removed/rewritten, there is a note that 'costResources' has replaced 'm_costPu'
