### ISSUE TITLE
Unit tooltips sometimes don't show properly on casualties display

### ISSUE THREAD

**Issue by asvitkine** [triplea-game/triplea#3516]
Unit tooltips sometimes don't show properly on casualties display.

For example, when transports are shown carrying units, then tooltips for units that are not fully wide don't show if you mouse over them from the side. But do from the bottom.

<img width="439" alt="screen shot 2018-07-06 at 8 32 12 pm" src="https://user-images.githubusercontent.com/17648/42405233-d4d700dc-8160-11e8-8bbc-36315c9a5224.png">

This is because UnitChooser overrides getWidth() to always be fixed size of the image - even though it takes up more width in the gridbag layout. So there's this awkwardness that it's actually wider but when Swing's tooltip manager queries its width - it's not - and so it decides not to display the tooltip.

We could either stick some padding into the gridbag layout or change the component to not override getWidth() - e.g. instead overriding preferred size or similar.

**Comment by asvitkine** [comment]
Also, a related issue is that the battleship appears to be truncated in the above.

**Comment by ron-murhammer** [comment]
I believe the truncation is because many modals are hardcoded to 48x48 unit size. If you play any maps with units that are a bit larger they tend to be cut off in a lot of places.

I think either of those fixes for the width should work fine.
