### ISSUE TITLE
Bot Server Login for Restarting.

### ISSUE THREAD

**Issue by prastle** [triplea-game/triplea#3527]
### Engine version

N/A
### My Operating System
Win 10
### Map name
N/A
### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Attempt to login to server

**Comment by prastle** [comment]
<img width="828" alt="2018-07-08" src="https://user-images.githubusercontent.com/17258293/42423444-3b13c098-82c8-11e8-8b4b-b99de4e8dade.png">

**Comment by prastle** [comment]
Similar occurs on many of them now but my ssh password works.  also it is interesting to note that stopping and starting as admin using the docs no longer functions correctly.

**Comment by prastle** [comment]
Yes it was um 200 server I screen shoted

**Comment by prastle** [comment]
Same resulta as above which is new!  but to be honest I have not touched bots in a few weeks.

**Comment by prastle** [comment]
Also since I know you are going to ask this ? @DanVanAtta  Yes I can still login as my prastle ssh/sudo
But I cannot do anything with admin/mod and mod password nor as my ssh password.

**Comment by prastle** [comment]
k second logging in as admin
according to forum docs to server 100

**Comment by prastle** [comment]
100 works

**Comment by prastle** [comment]
600 does not

**Comment by prastle** [comment]
for a status check

**Comment by prastle** [comment]
simple point I booted 504 from lobby go login and stop it
 @DanVanAtta

**Comment by DanVanAtta** [comment]
>  If so please copy/paste any corresponding error messages or a screenshot if you would, that was very helpful.

@prastle , please do that. I can't help otherwise.

**Comment by DanVanAtta** [comment]
> simple point I booted 504 from lobby go login and stop it
@DanVanAtta

For the record I did not add the setting that made the bots aggressively restart when stopped. Regardless, this sounds like a different topic. We will need more details on what you needed to do and where you saw an error, and the exact message of the error to help.

**Comment by prastle** [comment]
@DanVanAtta   Today I logged in as admin using my ssh password on the London bot server and it works fine (500 series).  Note that any of the servers that throw the error previously screenshotted do not work and produce this with error 
<img width="964" alt="2018-07-09 2" src="https://user-images.githubusercontent.com/17258293/42474456-a3eb6616-8395-11e8-9ced-3954d0379372.png">
either the admin password or my ssh password.  In this instance I was logging into NJ.

**Comment by prastle** [comment]
I am unsure what you are not understanding?  I added a few more screenshots today.  When I log into some of the bot severs using admin and my ssh password they work.  Any bot server that throws the error of warning does not work for prastle or my ssh or admin.  NO BOT SERVER works with the admin/moderator password and admin login that is posted in the google docs in the admin section of the forum.  Thus as you said quite awhile ago any moderator needs to ssh to the bot server.  Once they have logged in as admin with their ssh key they can then run the listed commands.  The problem is only five of us have ssh. 4 devs and myself.  No mods.  In addition to this half the servers listed above do not work on for me.  Did that clarify the problem? 
      I should also add that once logged in the server should not ask for a password again.  The fact that it does indicates it is broken.

**Comment by RoiEXLab** [comment]
Seems to work now again
