### ISSUE TITLE
NJ bot server "problem running ip6tables"

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3533]
```
root@bot15_newark_nj:~# ufw status
ERROR: problem running ip6tables
```

This is not expected. Seems similar to the problem we had when the lobby would not restart well.

**Comment by DanVanAtta** [comment]
@RoiEXLab I think you debugged a similar problem after the last lobby restart. Do you recognize this as the same problem?

**Comment by RoiEXLab** [comment]
@DanVanAtta Not quite. The error message was slightly different.
However this should be fixable by fixing the underlying ip6tables command because it probably just got itself in a bad state

**Comment by DanVanAtta** [comment]
Running `iptables` on that machine did not do much, maybe you'll know of something more to look at @RoiEXLab ? Without knowing how it got into a bad state, hard to fix it. It's also a question how suddenly iptables got into a bad state at all.

I'm thinking we should decommission this server. Who knows what else is in a bad state, the state of the server is just not known and that is disconcerting. The cost of fixing it also seems a bit much compared to firing up a new one, or just shutting it down and then saving on monthly costs.

**Comment by RoiEXLab** [comment]
@DanVanAtta maybe it's a typo.
But `iptables` ≠ `ip6tables`. AFAIK `ufw` uses those tools in the background.
So if you tried to use the latter somehow (list the entries or something) it will probably give a much more detailed error message. 
The last time I had similar errors like this it was due to concurrency issues.
`ufw` isn't using the tools in blocking mode, so if you try to execute two `ufw` commands at the same time, or maybe directly after another it will break.

**Comment by RoiEXLab** [comment]
@DanVanAtta Investigated this issue further, and came to the conclusion that we might want to try restarting the server completely, hoping to fix this issue. I read some articles, where simple restarting did the trick.
Also this issue doesn't seem to be related in any way to my concurrency issue.

**Comment by DanVanAtta** [comment]
Restart did the trick   :raised_hands:  

I don't think/know if investigating the RC further at this point is worth it, so will close this issue.

Thank you for the assist @RoiEXLab

**Comment by RoiEXLab** [comment]
@DanVanAtta Restarting is probably the most underrated Problem solver ^^
Great to hear it worked this time.
