### ISSUE TITLE
Yearly Project Cost

### ISSUE THREAD

**Issue by veqryn** [triplea-game/triplea#3537]
Hey all,
So I noticed that the donation drives for 2018 and 2019 list the project costs as being $800 per year.
That seems high, and I'm wondering what we could do to lower the costs?

Could someone detail out by line item all the various expenses we have?

We may want to look into things such as:
Free https certificates with Let's Encrypt or through IAAS providers like AWS Certificate Manager.
Nearly free hosting of static websites, with nearly free edge location support, using things like S3 + CloudFront (or similar).
Serverless infrastructure such as hosting the lobby and the bots as individual docker containers using AWS Fargate (or similar).
Open source docker images can be hosted by docker hub for free.

**Comment by veqryn** [comment]
https://blog.patricktriest.com/host-webapps-free/
https://www.heroku.com/pricing

**Comment by RoiEXLab** [comment]
@veqryn 
Most of the costs are consumed by the bots. 3 bots/ a server is 5$ a month, take 6 of them and we have 30$ a month, 360$ per year.
Currently the Lobby, the Forum (and 1 or 2 other infrastructure related services) are running on a dedicated server for 5$ per month per server as well and there you have your yearly costs.
The https://triplea-game.org Website runs via Github Pages, and tripleawarclub.org and forums.triplea-game.org use both let's encrypt certificates.

You might want to have a look at https://github.com/triplea-game/infrastructure for some details.

Aiming for serverless infrastructure is probably a good thing. However in the current state of the engine there are a lot of things that need to be done before this could work.
Currently the lobby expects bot servers to have a dedicated IP address and checks if it matches the current TCP endpoint the established a connection to the lobby.

**Comment by prastle** [comment]
@veqryn  some months we have gone over but generally counting the test lobby and testing bots plus the new papertrail it is probably about $65.00 a month.  Lastr months linodes cost $55.00.  Month before was 70 something.

**Comment by prastle** [comment]
The $800.00 is slightly over budget for future improvements and safety.  Atm We are very close to the 2019 donation drive being finished.

**Comment by ron-murhammer** [comment]
Probably the easiest way to save money would be to do some testing/optimization on bot memory usage so we can host 2-4x as many on a single server as I really think there is some memory duplication or leaks. I did some testing a bit a few months back on memory footprint and made this change: https://github.com/triplea-game/triplea/pull/3370.

Going serverless and/or changing hosting provider would be a much larger initiative though doable.

**Comment by veqryn** [comment]
How much RAM is necessary for a single bot these days?  (I'm guessing ram is the constraint, not cpu.)
Just wondering if it would be possible to get the free services offered by heroku, aws, and others to host them.
Reducing useless and overly verbose logging might lower your papertrail bill.
Good to hear you are using github pages and lets encrypt!

**Comment by ron-murhammer** [comment]
@veqryn Probably depends if you measure it before/after that change. I was planning after the next stable release that I'd re-assess bot memory.

**Comment by prastle** [comment]
@veqryn  Curent Linode copy paste.

Date | Description | Amount
-- | -- | --
2018-07-01 | Invoice #11111303 | $56.84
2018-05-31 | Invoice #10815069 | $55.00
2018-04-30 | Invoice #10648942 | $73.06
2018-04-24 | Payment - Thank you | ($100.00)
2018-03-31 | Invoice #10483480 | $57.41
2018-03-01 | Invoice #10315606 | $50.00
2018-02-01 | Invoice #10148562 | $50.00

**Comment by prastle** [comment]
@veqryn  as an after thought if every member of the new forum donates 5 bucks a year it would be wayt over budget so I think this is a moot point.  Jmho
.

**Comment by veqryn** [comment]
I'm not sure whether the community has grown, shrunk, or stayed the same size since the last time I personally ran a donation drive, but I do think $800 is a lot to ask from our community.  While it might look like $5 per forum member (or double or triple per actually active forum member), it usually falls much more heavily on the few who do decide to donate.

Please correct me about the costs if I have them wrong:
$360/year for bots (6 x $5/month)
$60/year for lobby
$60/year for forum
? $200/year for log aggregation ?
? what else ?

**Comment by prastle** [comment]
x10 Linodes , 9@5 and old warclub at $10.00 = $55.00 a month without overages.  Plus papertrail which I already paid for myself for one year. https://github.com/triplea-game/triplea/issues/3412  ($6.00 a month if I recall?)  Dan tied this to the server gitter thread.  Any License fees I don't know about?  Forum auto backup by linode was talked about as well.  Thus basically with no overages we are at 720 per year.

**Comment by prastle** [comment]
@veqryn  after glancing at our linode account realistically if things continue the same we should have $125.00 carry over to 2019.  So in actuality if no NPO No new licensing and no changes 2019 is already paid for. ;)

**Comment by Deltium** [comment]
Hi Veqryn - good to see you.   The developers and Prastle have done a really fantastic job in making some material improvements both to the software as well as to the website.   Thanks to their efforts, we are indeed growing as a community.   Personally, I would like to see TripleA have a modest cash balance at hand at all times to work on special projects, or to cover unexpected costs.

**Comment by veqryn** [comment]
Well, congrats then.
I still do hope costs could be lower, or at least not increase.  Getting multiple bots per server would help with that.  But it sounds like things are under control.

**Comment by DanVanAtta** [comment]
Want to jump in with some updated numbers, we are currently in total at: $780/yr

  | Monthly Cost | Yearly Cost
-- | -- | --
Linode - 6 Bots | 30 | 360
Linode - Infrastructure Server | 5 | 60
Linode - PreRelease Server | 5 | 60
Linode - WarClub | 10 | 120
Linode - Forum Server + Backup | 7.5 | 90
  |   |  
GoDaddy - warclub Domain + private DNS registration | $3 | $30
PaperTrail | $5 | $60
Namecheap, triplea-game.org (expires 2025) |   | paid
  |   |  
Sum Total | 65 | 780

Bots seem to need some work, I suspect they probably do have a memory leak problem, and it looks like there is more contention with large games. We need to spend some time digging in there to really understand.  Overall bots are half our budget.

It would be great to reduce support server cost, but at some point what we lose is well worth the $5/month. 

We *can* probably shed the do-daddy cost. I created a forum post for follow-up: https://forums.triplea-game.org/topic/941/tripleawarclub-org-url-going-for-sale

I knocked us down from 6 bots to 5: https://github.com/triplea-game/infrastructure/pull/84

That gets us to $690/yr. We intend to move lobby to a smaller node which will save us $60/yr. $630/yr seems to be what our cost will be medium/long term unless we take more action.

Paper trail (log aggregation that is then viewable from a browser) does have a free plan if we can cut our log output down further, that would save another $60/yr. 

Of course, the big savings are going to be if we can drop bot servers. At the moment AFAIK our hands are pretty full, so we will likely have relatively high costs this year. It'll be pretty big for us if we can get bots to scale and host many on one sever.

**Comment by prastle** [comment]
@veqryn  @DanVanAtta   I would also like to add that since for the past few years now a vast majority of our community cannot host the bots have become necessary.  Since we already have enough cash to pay for them I disagree with shutting NJ.  Currently in the lobby on a Monday (our slowest day usually) we now have one empty bot.  Last weekend they were all full.  I 100% agree we need bot servers that can host more bots and hopefully one day easy hosting services.  Until that day occurs though I do not believe we can close NJ.

**Comment by prastle** [comment]
Thanks for the additional info @DanVanAtta

**Comment by prastle** [comment]
Thus it appears the 800 is a good total Goal.  Do you need any additional funds now? @DanVanAtta

**Comment by RoiEXLab** [comment]
@veqryn
> [...] that is different from the "Forum" server? Those sound like the same thing to me...

Forum Server = forums.triplea-game.org 
Warclub = *.tripleawarclub.org lobby.triplea-game.org

> ps: did the lobby db get wiped or lost at some point in the couple years? I was unable to login, and was forced to re-create my username...

😅 yup (I'm innocent for once :P )

**Comment by DanVanAtta** [comment]
>  Do you need any additional funds now? 

@prastle not that I'm aware of : )
IMO we would ideally come in under $500. I think for this year we'll just spend more, at some point we are better building new features than trying to save on operating costs.

> What does the infrastructure server cover?

$5/month

> What does the pre-release server cover? (ie: just the lobby server?)

pre-release server is just the one, it has a latest lobby, latest DB, and a latest bot. It's controlling configuration is here: https://github.com/triplea-game/infrastructure/blob/master/roles/host_control.sh#L42


> What does the WarClub server cover that is different from the "Forum" server? Those sound like the same thing to me...

To add to RoiEx's answer, we put the new NodeBB forum on a dedicated server. 'warclub' still retains it's old name, it is running DB, lobby, and marti dice server (Xoops is turned off)

> Lastly, where are you sending backups? (ie: Lobby Database and Forum Database)

A local copy is landing on the same server and another copy is being sent to the infrastructure-support server. This is the script that sets up the backup: https://github.com/triplea-game/infrastructure/blob/master/roles/lobby_db/tasks/run_daily_db_backup.sh


> I would like to suggest that backups don't go to a server, but instead go to a purpose-build long-term object storage, such as S3.

Interesting suggestion. I would agree that is the right thing to do, not sure on cost/benefit though. A few things to keep in mind:
- derby DB never had better than a same server backup
- the postgres migration was running with no backup for some time
- there is option to do linode mirror snapshot ($2.50  / month)

From my perspective the most critical data we have is forum. We have linode snapshot turned on for that. It *would* be disaster to lose that. The user db on tripleA is for the moment less disaster, but still would be bad to lose. I think if we start tracking match stats in triplea user DB, then turning linode snapshots would be a good move.

**Comment by veqryn** [comment]
S3 is pretty cheap.  It would cost around $1.26/month to store 100 GB in Infrequent-Access Storage.
Glacier is even cheaper, at around $0.41/month to store the same 100 GB.

Besides cost, the main reason why you want to use an S3 or Glacier-like service is that your data is replicated many many times, guaranteeing you that even if they lose 1 copy your data will still live on.  I believe S3 is replicated to something like 7 different geographically distributed data centers, with 99.999999999% durability guarantee.

Azure, GCE, and others have similar services:
https://www.slant.co/options/2332/alternatives/~amazon-glacier-alternatives
https://thewirecutter.com/reviews/best-online-backup-service/

**Comment by prastle** [comment]
@veqryn  yes derby died 2016  warclub still hosts marti and lobby to my knowledge.  Our goal was individualized servers for each process.  The bots went a little to far it seems... 2 or three bot servers is prob better for easy acess to data if something goes wrong,

**Comment by prastle** [comment]
thus I guess the goal is separate forum sep marti separate lobby separate bots

**Comment by prastle** [comment]
the testing servers were set up to try  and accomplish this before lobby introduction

**Comment by prastle** [comment]
Atm all are separate except marti/lobby = warclub

**Comment by veqryn** [comment]
Isolation is better achieved with containers (docker/rkt), but that is a topic for another day.

**Comment by DanVanAtta** [comment]
Ah, the many bots was not about isolation, it was pricing. It seems pricing model might be slightly updated, but you got the most ram for the buck at the nano size. RAM was the limiting factor for how many bots could start up stable on a given server. So, to max out RAM per cost meant putting bots on the nano (5$/month) servers.
