### ISSUE TITLE
install4j - make the JRE dynamically optionally bundled

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#354]
"JRE is downloaded at installation start if there are no good Java installed for the user. " #260 

This is needed for the next release, hence the 'urgent' label.

**Comment by DanVanAtta** [comment]
@gaborbernat , will you be able to get this done before the next release (next few weeks/month)?

Please submit a PR for any bundled JREs that will be needed to be available to this repo: https://github.com/triplea-game/assets. Reflecting on prior conversation and in light that Java8 provides stripped down JREs, I trust your judgement to make a good choice.

@gaborbernat , I'd like us to have a last final push in the coming weeks to get all of the installer/build issues wrapped up and taken care of.

**Comment by gaborbernat** [comment]
will work on this today/tomorrow :+1:  so probably yes; will see how it goes

**Comment by DanVanAtta** [comment]
Updated travis/install4j configs for the updated JRE names @gaborbernat . Once I confirm they are working, I'll leave the rest of the updates to you. Apologies for the merge conflict if you get any, please rebase to latest master. Thanks and good luck

**Comment by DanVanAtta** [comment]
#376 will resolve this.
