### ISSUE TITLE
Feature request: Can we start a game with one or more objectives disabled?

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#3546]
Several users have requested the above feature. I can certainly see the merit. Seems like there's a bit of work in it but I thought I'd ask the question.

This is particularly for the "World War II Global" suite of maps.

**Comment by Cernelius** [comment]
Hey @simon33-2 welcome back. Probably you missed they moved FR to forum.

Anyways, you can already do this, with triggers (assuming what you mean is having an objective that cannot be validated or does nothing, as coded, and, then, enable it, one way or the other, at some point in the course of the game).

**Comment by Cernelius** [comment]
Well, looks like they are still tagging stuff here as Feature Request, so I'm not sure. I understood all were moved to forum. Can be it is me I missed something, instead.

**Comment by beelee1** [comment]
@simon33-2 yea I made a tech and added it as a condition to the objective. Probably want to make one tech that activates all of the objectives. That way you only need to activate the one if you wanna play the regular game.

Then individual techs for the other ones. Maybe have one tech activate a group of objectives as well if certain ones are always being used.

**Comment by ron-murhammer** [comment]
As @Cernelius and @beelee1 mention, this should be possible with some combination of conditions/triggers/techs. And generally we are trying to have all feature requests in the forum now here: https://forums.triplea-game.org/category/42/feature-requests-ideas

Gonna close this and if you feel additional functionality beyond what is available would be helpful then please open a thread with additional details in the forum. Thanks!
