### ISSUE TITLE
Infrastructure Testing - Gitlab Flow

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3549]
There is a bit of a problem where updates to infrastructure scripts go to prod and it's not clear/obvious how to do local testing.

To make it easier I propose we use a "gitlab environment branch" strategy: https://docs.gitlab.com/ee/workflow/gitlab_flow.html#environment-branches-with-gitlab-flow

In our variation, our staging is the same as pre-production, so master would be deployed to the prerelease server as-is today. But, we would create a 'prod' branch and then switch prod servers to pull from that branch.

That would mean production deployments then happen after we merge 'master' into prod.

Does this sound good? Reasonable? If so I can document this up in on the infrastructure readme: https://github.com/triplea-game/infrastructure

**Comment by ron-murhammer** [comment]
@DanVanAtta That's fine with me and I agree that it does make sense to try to use the staging environment we setup since that is what its there for :)

**Comment by RoiEXLab** [comment]
👍

**Comment by ssoloff** [comment]
:+1:

**Comment by DanVanAtta** [comment]
Added notes about prod deployment: https://github.com/triplea-game/infrastructure/pull/100

I also updated infrastructure to be Fast forward rebase merges. I hope/think that will keep prod/master branches even with the same commits.
