### ISSUE TITLE
Ops Doc Consolidation

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3556]
We have a couple locations with operations documentation:

- Google ops doc
- https://github.com/triplea-game/infrastructure/blob/master/README.md
- https://github.com/triplea-game/triplea/blob/master/docs/admin/README.md
- https://github.com/triplea-game/triplea/blob/master/docs/admin/gradle_upgrade.md

Does anyone have any strong opinions on how to better organize this information? I'd like to propose we consolidate. My initial thought is the infrastructure scripts are what deploy the things we operate, that I think would be a natural place to consolidate. I'm curious if others have other thoughts or ideas of how to organize this information?

**Comment by ron-murhammer** [comment]
+1 for consolidation. I think the main question is google doc vs github repo. Benefit of github repo is closer to the scripts but drawback is non-developers can't easily contribute.

**Comment by prastle** [comment]
Ya I agree with @ron-murhammer.  we attempted to do it in the forum so all admin/mods had easy access. I think google docs through the forum is the best way just my 2 cents.

**Comment by DanVanAtta** [comment]
Forum has problem where only original author will update the OG post (even if everyone says/asks otherwise, this is what tends to happen). From a maintenance perspective that is bad for any kind of info that will evolve.

Github has benefit where changes can be discussed first and are notified automatically. WE can also be sure changes are done that make sense and are complete.

At the end of the day, i think we mostly need to clarify who the document is for. I think that really means clarifying the diffferent jobs/roles of system admin and community moderator.

**Comment by DanVanAtta** [comment]
Agreement, seems to be to consolidate to google doc, easy enough!
