### ISSUE TITLE
Technologies on "Players" tab should have tooltip descriptions

### ISSUE THREAD

**Issue by asvitkine** [triplea-game/triplea#3575]
Technologies on "Players" tab should have tooltip descriptions.

This way, it would be easy to see what they do. Since often times "Notes" for maps don't explain them anyway.

**Comment by ron-murhammer** [comment]
Depends on whether you are using hard coded or custom techs. Hard coded would be pretty easy to add generated tooltips for. For custom techs, a generated tooltip would need to parse conditions/triggers or just allow the map maker to specify them in a file. Take a look at Total World War as an complex example of custom techs.

**Comment by DanVanAtta** [comment]
I like where this is going. For this one, if we are considering hover-over tooltips, we may also want to go one further and provide a "?" button to show a list of techs and what they do. 

This could be a good complement to the suggestion. The idea is that even if a user never catches on that there is a hover-over text, they can still look for and find the help button to click.
