### ISSUE TITLE
The lobby crashed and all bots gone except the new 700 series!

### ISSUE THREAD

**Issue by prastle** [triplea-game/triplea#3588]
### Any additional information that may help
Who restarted it and anyone have any ideas?

**Comment by prastle** [comment]
@RoiEXLab  @ron-murhammer  @DanVanAtta

**Comment by prastle** [comment]
Yes we just did.  a second time first time was them with no warning.
I will close this now see this reference link.  https://forums.triplea-game.org/topic/944/lobby-upgrade-july-18

**Comment by DanVanAtta** [comment]
@prastle 's post here seemed good, got my attention. But by then the lobby was up and running again and the non-7xx bots did not reconnect properly.

IT was suggested to do the server ugprade given all games had been interrupted, we proceeded with that and those would be the linode notifications.
