### ISSUE TITLE
Linode disk space offer - forum followup

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3601]
Linode has an offer to encourage a migration that gives us more disk space. To do this, need to log in to linode, click through to the forum server, click "accept upgrade". Then wait for the downtime and upgrade, takes about 10 minutes.

We did this for *all* servers so far except the forum: https://github.com/triplea-game/triplea/issues/3552

@RoiEXLab ; given you're most familiar with forum, it would be great to have you on hand for this. It may also make sense to also do node upgrades while we are restarting the server.

**Comment by RoiEXLab** [comment]
@DanVanAtta As already mentioned by @prastle this already has been done today
