### ISSUE TITLE
Code Guidelines - Favor immutable, drop requirement for final keyword to be *everywhere*

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3660]
I'd like for us to change our code guidelines to encourage 'final' keyword and to try to use immutable state as much as possible, but not 'require' we have 'final' everywhere we can. That means instead of:

```
String s= "abc";

if(something) {
 s = "123";
}
```

We would flag that in review and suggest we make `s` immutable by converting to:

```
String s = something ? "abc" : "123";
```

As-is, we would let the first example go and nitpick the second asking for 'final' keyword. That seems to me to be missing the point. The 'final' everywhere convention I was on-board with as we had no such convention to favor immutable state and it was painful to see parameters being used in an "in/out" style. 

At this point, I'd like for us to focus our reviews on the higher level goal to make sure SRP is followed and immutables are favored, and not necessarily if proper usage of parameters etc are final. I think a lot of it has become busy work when it is really the principle of SRP and immutability that are important.

**Comment by ron-murhammer** [comment]
@DanVanAtta Agree as long as conditional statement doesn't end up being more than a couple of lines.

**Comment by simon33-2** [comment]
For my curiosity, what is immutable without inserting "final". Or by "drop final keyword everywhere", did you mean to insert it?

**Comment by DanVanAtta** [comment]
@simon33-2 immutable and final are sometimes related but not always. Many objects can be marked as final, but still be mutable. String arrays are an example of something that can be final but still mutable:
```
final String[] s = { "1", "2" };
s[0] = "2";  
```
Notice that the naming convention we follow, google java naming, makes a distinction between final types and constants: https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names

The other example to consider, is that immutability is a larger concept/design philosophy compared to adding the `final` keyword. It is the case though that if you favor immutable design, most all variables will be immutable. When 100% of parameters are effectively final anyways, at that point it can be reasonable to skip the keyword, it is a bit cluttering. 

"Drop final keyword" is slightly nuanced and maybe a bit hyperbolic, I wanted to imply we drop the final keyword on places where by convention we will have immutable types anyways, so the final keyword is potentially cluttering, for example:

#### Example A
```
void method() {
  final int  a = 1;
  final int b = 2;
  final int aSquare = a*a;
  final int bSquare = b*b;
  final int sumSquare = aSquare + bSquare
  final double result = Math.sqrt(sumSquare);
}
```

As compared to:

#### Example B
```
void method() {
 int  a = 1;
 int b = 2;
 int aSquare = a*a;
 int bSquare = b*b;
 int sumSquare = aSquare + bSquare
 double result = Math.sqrt(sumSquare);
}
```

In general either of the above I think is relatively fine. In general I prefer to omit 'final' keyword from local variables and parameters, but on the other hand I prefer for things to be final and/or immutable compared to not, it is more impactful and important to code quality so I prefer we use final+immutables everywhere we can compared to not. It only gets a bit grey when local variables or parameters all become effectively final.

With the new checkstyle rules: https://github.com/triplea-game/triplea/pull/3662, half of this issue is somewhat moot unless we want to dial back those rules. Notably the checkstyle rule will do exactly what it is supposed to do and check for us that we've added final keyword everywhere possible. Reviewers should not be checking/looking for that, better to focus on higher order concerns (like immutable design).

At this moment I don't think it makes sense to dial back the final keyword rules now we have a checkstyle rule for it. So remaining is largely to discuss whether we agree that immutable design is a best practice and that we should favor it.  With our current guidelines, example A would have been fine, and example B would have needed work to add keywords.  But, unless we favor immutable design, then this would have been theoretically perfectly fine too:

#### Example C
```
void method() {
 double result = 1*1;
 result = result + 2*2;
 result =  Math.sqrt(sumSquare);
```

Example C is still somewhat clean being the 3 lines, but it gets more complex when dealing with a local class variable that has setters/getters, is long lived and accessed across different threads and parts of the code. Part of the issue of mutable values is that their data state depends on execution flow. On the other hand immutable objects have a single data state that is set on initialization. Thus when you see an immutable object reference, if you can find where it was initialized then you'll know that objects state. For a mutable object that is not sufficient and you need to track it's entire life history to be sure nothing modified it between the time it was initialized and then reached another given point. If as well you ensure that immutable objects are initialized to non-null, then suddenly a lot of code becomes thread-safe, NPE-safe, and overall simpler. I like to combine that even with validation functions when building immutable objects, so that when you see an immutable reference in code you'll know:
A) it's not null
B) has the same state as when it was initialized
C) the state is valid

The above is pretty awesome to have IMO thanks to values being immutable and validated on initialization (which plays nicely with the 'fail-early' principle).

-------------------------------------

Summing up a bit, half of this issue was about checkstyle rules, the other half is about whether immutable design is a best practice. If we agree it is, then in review Example C we would likely ask for it to be written like Example A (though grant it, that is a pretty trivial example, so we might not ask for it there, but class variables for example could easily be converted to final and immutable, then we should ask for it). So the remaining question is (happy to clarify anything further too), is whether we agree immutable design is a best practice.


There is a lot of reading/background on immutability for Java, I'd almost call it a movement that started within the community around 2012~2014. https://www.google.com/search?q=immutable+design+pattern+in+java&oq=immutable+design+&aqs=chrome.2.0j69i57j0l4.3201j1j7&sourceid=chrome&ie=UTF-8

**Comment by RoiEXLab** [comment]
👍
I'm fine with this.

**Comment by DanVanAtta** [comment]
Good example @simon33-2 

As-written, you can't mark `I` as final of course, it is not immutable. (it is assigned to immutable values, but it itself is not immutable).  In theory, with that example there would be a logical necessity as well to re-assign the value, so you could not just simply mark the variable as final. We all agree that one should avoid re-using variables for different purposes, and I would guess you were thinking as well, it's often simpler/clear to just use a new variable:
```
final Integer I = Integer(3);
final Integer J = Integer(5);
```

But if you do this consistently, then all parameters and all local variables start to get this superfluous `final`. What's more, the `final` keyword does not guarantee immutability. So essentially the idea is that for method args it is more clutter than useful, and same for local variables. 

In this project, it's better to err on the side of stronger constraints IMO. So really suggestion here is to have a review guideline that we should try to make all local variables and all method parameters final. Our checkstyle will make sure we actually mark variables as final if we can, so when we do not it should be a strong signal to readers and reviewers.

I wonder if we should loop in marking class and methods as final where possible? I think we are about set to update the code guidelines to request immutable designs are preferred.

Another for question for group. I feel kinda burned recently by Guava immutable collections not being serializable, so I almost would not mind avoiding that and reducing the Guava dependency at the same time. Should we prefer the guava immutable collection types over the mutable JDK collections? (EG: `ImmutableList` instead of `ArrayList`)

**Comment by simon33-2** [comment]
If final is attached to every variable in the program, I wouldn't call it redundant. Perhaps annoying though.

**Comment by DanVanAtta** [comment]
"Clutter" is really the word. 

I was trying to be nuanced and avoid "redundant"  `final` is necessary but not sufficient for any given variable reference to be 'immutable'. (but IMO it is a good thing, I sometimes agree that the Java language designers should have had variables be `final` by default)  

I'll update the dev docs to reflect the latest here, that we should simply try to use immutable design, which means we'll see more `final` keywords appearing.

**Comment by simon33-2** [comment]
I find it annoying that the creators of the Java language didn't think that if a variable is final, the type can be inferred from whatever type the variable is set to. So in my example, you would have:

final I = Integer(3);

and the compiler would know that I should be of type Integer. Obviously not really a problem in that very simple case but it can be tedious at times to work out the data type and put it in even though the compiler does really know it already! And if it's final, no reason to use a superclass type.

**Comment by ssoloff** [comment]
> I find it annoying that the creators of the Java language didn't think that if a variable is final, the type can be inferred from whatever type the variable is set to.

Modern JVM languages like Scala and Kotlin fixed this oversight, if you're looking for a reason to switch. :smile:

**Comment by RoiEXLab** [comment]
@ssoloff Or java 10 with the var keyword ^^

**Comment by DanVanAtta** [comment]
Thanks all for the discussion. We need to update our guideline docs in a major way at the moment when looking at it. I don't think updating it now is a great idea/would be useful, but the culture shift/acknowledgement here I think was useful/good. Resolving as it seems we are at consensus.
