### ISSUE TITLE
Game freeze on casualty selection

### ISSUE THREAD

**Issue by beelee1** [triplea-game/triplea#3661]
### Engine version

10876

### My Operating System
linux

### Map name
global40 house rules with canada

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
US air battle with 2 escorts against 6 German and 1 Italian interceptor. US scores 1 hit, Germans select 1 German ftr as casualty, game freezes.

### Do you have the exact error text? Please copy/paste if so
Unable to access error but have a screenshot:
![screenshot from 2018-07-30 19-32-06](https://user-images.githubusercontent.com/24382682/43432395-4732ee0e-9438-11e8-8464-aaf7e8df473e.png)

### Instead of this error, what should have happened?
 Shouldn't have frozen
### Any additional information that may help
While trying to recreate, edited 6 more US escorts. They got 3 hits, Germany took all 3 hits and game continued. An error saying ANZAC was missing it's large flag came up but game didn't freeze. ANZAC flag is not missing.

Restarted with no edit and got 1 US hit and same thing ( game freeze ) happened.

**Comment by beelee1** [comment]
[autosaveAfterAmericansCombatMove.zip](https://github.com/triplea-game/triplea/files/2243410/autosaveAfterAmericansCombatMove.zip)

**Comment by DanVanAtta** [comment]
Can you get the same thing with the very latest @beelee1 ? 

I was not able to repro, managed to trigger roughly the same scenario and had no issues. Do you have any tips or pointers for how to trigger the crash?

If you can trigger the crash again, as devs we would want a "thread dump" to know where things are. If you can get that, it would be really valuable (it's not necessarily easy to do, but not hard either: http://lmgtfy.com/?q=java+thread+dump; can certainly give pointers if you're willing)

**Comment by beelee1** [comment]
thought that was latest. Yea wasn't able to get the error because of the freeze. I could see it in a small window but...I'll check the link and try and get the error

**Comment by beelee1** [comment]
thought that was latest. Yea wasn't able to get the error because of the freeze. I could see it in a small window but...I'll check the link and try and get the error

@DanVanAtta  well Idk what's going on but just retried everything and got the same air battle result and it works correctly. I spent over an hour with multiple computer startups and continued to get the original problem. Now it works. Idk what's up. I do have an older machine. Maybe it was just nuttin up or something.

Anyway if it happens again I'll get more info before posting. Sorry to waste your time

**Comment by DanVanAtta** [comment]
Not at all a waste, that was a real error; we just do not know how to trigger it. But, you're right @beelee1 we won't be able to make good progress on this problem without more info. I think the best we can do is try to be more prepared for next time and make it easier to get the necessary diagnostic info. I've one idea to do that, opened  https://github.com/triplea-game/triplea/issues/3663 to discuss it further.

**Comment by beelee1** [comment]
@DanVanAtta here's a little more info. Wasn't able to get the scroll bar or copy to clipboard work but a cashot at beginning and end of error.

![screenshot from 2018-07-30 23-43-33](https://user-images.githubusercontent.com/24382682/43438241-c72b4d30-9452-11e8-8c56-8f0d2da2e333.png)

![screenshot from 2018-07-30 23-43-50](https://user-images.githubusercontent.com/24382682/43438249-d5b81cb6-9452-11e8-992a-a9ade086bbea.png)

I took a. look at the thread dump thing. It'll take me a while to figure it out. 

Anyway the saved game did the same thing this time regardless of air battle. So probably not a factor

**Comment by DanVanAtta** [comment]
That stack trace has some really useful information at the top. Notably the `BattleCalculator:554` line, which would be this: https://github.com/triplea-game/triplea/blob/38578b881206c9e4c619adbdeec243cadcb214bd/game-core/src/main/java/games/strategy/triplea/delegate/BattleCalculator.java#L554

@beelee1 on a freeze, you only select casualties screen once? Do you see the "wrong number of casualties selected" prompt ever?

I've been trying to repro again and still have not been able to : |
The line of code above could do a loop potentially, though I was not able to yet spot how.

**Comment by beelee1** [comment]
@DanVanAtta  the first two times it did it there was 1 air battle casualty. I selected 1 German ftr each time and it showed the correct casualty selection. There is 1 Italian ftr in the battle also, so idk if that has anything to do with it.

The third time it happened there were no air battle hits and it froze again. I had run it 20 times or so with no hits and it worked ok. I'll work on it some more in a bit and try and get the thread dump

**Comment by DanVanAtta** [comment]
@beelee1 are you selecting bombard option?

**Comment by beelee1** [comment]
@DanVanAtta yes i am . Sorry I meant to mention that

**Comment by DanVanAtta** [comment]
Closing without resolution, without a repro we will not make much headway on this.

**Comment by DanVanAtta** [comment]
Thank you for reporting the problem though @beelee1 , if you see the issue again, please be sure to report it so we can have it on our radar again.
