### ISSUE TITLE
Test Utilities Library

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3674]
Wanted to get some quick design feedback before the PR would land:
- it would be useful to have a common testing util project which we can include in the other projects. Is 'test-util' a good name?
- this project would have very generic testing helper functions in it, intent is to include as a testCompile dependency in all projects.

A first example, hamcrest has nice custom matchers but the syntax to get to them is a bit wonky. We have just a couple examples, eg:

```
  private static Matcher<Iterable<File>> containsDirectoryEndingWith(final String name) {
    return new TypeSafeMatcher<Iterable<File>>() {
      @Override
      public void describeTo(final Description description) {
        description.appendText("iterable containing file with name ").appendValue(name);
      }

      @Override
      protected boolean matchesSafely(final Iterable<File> files) {
        return StreamSupport.stream(files.spliterator(), false)
            .map(File::getPath)
            .anyMatch(p -> p.endsWith(name));
      }
    };
  }
```
(Example is from [ResourceLoaderTest](https://github.com/triplea-game/triplea/blob/master/game-core/src/test/java/games/strategy/triplea/ResourceLoaderTest.java))

I'd like to re-write that as:
```
  private static Matcher<Iterable<File>> containsDirectoryEndingWith(final String name) {
    return MatchBuilder.<Iterable<File>>builder()
        .expectationDescription("iterable containing file with name " + name)
        .checkCondition(files -> StreamSupport.stream(files.spliterator(), false)
            .map(File::getPath)
            .anyMatch(p -> p.endsWith(name)))
        .build();
  }
```

So the above is a motivating factor, I'd want the above available in all projects. It looks like we have a few more tools that would be candidates to go into the propiosed `test-util` project, like [Assertions.java](https://github.com/triplea-game/triplea/blob/master/game-core/src/test/java/games/strategy/test/Assertions.java).

-----------------

1. Everyone on-board? Any objections to having a test-util project as a common test dependency?
2. Is `test-util` a reasonable name?

**Comment by RoiEXLab** [comment]
👍

**Comment by DanVanAtta** [comment]
https://github.com/triplea-game/triplea/pull/3675 adds this
