### ISSUE TITLE
CR guidelines, still up to date?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3689]
https://github.com/triplea-game/triplea/tree/master/docs/dev#code-review

In specific we had reasons for having the PR queue be a FIFO: https://github.com/triplea-game/triplea/tree/master/docs/dev#code-review-ordering

Do we no longer agree that the PR queue should be a FIFO? If the benefits are still there, then I'd like for us to make the FIFO policy workable again so we can easily follow it. Maybe it means we approve PRs but wait for merge. That is maybe missing the point though, and really that review should be dedicated to the earliest PR until turn-around is needed. I'm not sure that is necessarily effective when some PRs are larger than others, unnecessarily or not. The other part is how to ensure to avoid PR stagnation as well?

**Comment by DanVanAtta** [comment]
(yes, i am concerned about my PRs being stagnated, of note because I have more conflicting branches waiting for merges so I can submit more stuff into the queue). But in general I feel like our review guideline is not worth very much right now, either needs an update and refreshed agreement or we can save the maintenance and delete it.

**Comment by ron-murhammer** [comment]
I think we are generally starting reviews of PRs in FIFO order but will often merge smaller/simpler PRs as their review takes less time than more complex ones. I generally think that is ok as I don't want a lot of simple PRs to sit waiting around. If I make a 1 line bug fix and someone submitted a major 1000+ line feature PR that could take several iterations of reviews/updates, I don't think that small PR should have to wait to be merged and doing this keeps our queue smaller. Most PRs are being merged in at most a few days and we haven't been having as many massive refactoring PRs so I haven't seen a lot of problems here recently.

**Comment by DanVanAtta** [comment]
For perspective, the problem I think is when there are zero iterations and the updates are still a reasonable size (100 to 300 lines). On the one hand I think it's beneficial to have the discipline/practice that if there is 5 minutes available for review, it goes to checking over the larger work to make sure there are no blockers. The one-liners *can* wait. On the other hand, I do think that is over prescribed. The trick is really for us to have as many reviewers as we can, that *will* outweigh contributions soon/easily and we'll have a short PR queue and this would be a moot problem (PR review starvation)

But, we do need to update our review guidelines, I suspect we can trim it down, replace most of it with a link to this: https://blog.plaid.com/building-an-inclusive-code-review-culture/ (and similar posts)

I like this for example:

> Requirements for someone to have write access
contribute some cod

Still waiting on that cod :fish:
