### ISSUE TITLE
install4j installer - nohup/background the linux game launcher  

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#370]
use case:
- install the game on linux
- launch it from a terminal window with `./TripleA`
Then:
- close the terminal window, game closes

Suggested fix:
- have the ./TripleA script 'nohup' and 'background' the java process so you can kill the terminal window mistakenly and still have the game stay open

**Comment by gaborbernat** [comment]
It should not be run as such. If you want to stick to the terminal run it
via ./TripleA & - which will do the same

Bernát GÁBOR

**Comment by DanVanAtta** [comment]
That just backgrounds (without the nohup). So if you close the terminal window that launched the game, you'll still also close the game without the "are you sure you want to close without saving" prompt

**Comment by gaborbernat** [comment]
This is not install4j specific, it is the same with the current shell script we use. Personally I do not agree on making this change. Anyway, if you launch the installer from the system menu the installer creates, this is not the case.

**Comment by DanVanAtta** [comment]
It's not install4j specific, no. The behavior of the current shell script is not optimal either. Everything launched off the system menu is run without a console, yes. This ticket is to have the main game launcher to have similar behavior. Why do you not agree with this change?

**Comment by DanVanAtta** [comment]
@gaborbernat please check if this would be easy. Otherwise I can let this slide despite disagreement, i can agree this is less value/priority than a good many other items (but while we're on the topic and context, do check if you would pls)
