### ISSUE TITLE
UK Not Spending PUs

### ISSUE THREAD

**Issue by drockken** [triplea-game/triplea#3712]
### Engine version
1.9.0.0.11035

### My Operating System
Windows 10/64bit

### Map name
Ozteas 1941 Global Setup

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Load game.  Allow it to run through UK Purchase Units.  UK does not spend most of its PUs.  History shows most rounds it does not spend.

### Do you have the exact error text? Please copy/paste if so
No error text.

### Instead of this error, what should have happened?
UK should be spending its PUs.
[x123.zip](https://github.com/triplea-game/triplea/files/2258840/x123.zip)

### Any additional information that may help
I first noticed this issue with engine 1.9.0.0.10960.

**Comment by ron-murhammer** [comment]
@drockken Are you indicating that before 1.9.0.0.10960 that this used to not be a problem or that that was just the first version you noticed it?

**Comment by drockken** [comment]
The issue also exists in 1.9.0.0.10960.  It may or may not exist in prior versions.

Prior to 1.9.0.0.10960, I played 1.9.0.0.10303.  I do not recall the issue in that version (it might have been there, but I did not see or experience it.)

**Comment by ron-murhammer** [comment]
@drockken This PR should fix the issue: 3716. There was an issue with some of the recent AI purchase changes that were made where the AI makes more checks for complex maps that were causing it to fail to place fighters on carriers so its purchase failed.
