### ISSUE TITLE
Future for the domain: tripleawarclub.org  (release it back to public?)

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3722]
We're currently paying for the tripleawarclub.org domain. Should we:
- release the domain? GoDaddy says we can get a few hundred selling it, would go nicely to our operations costs.
- keep the domain?

I posted on forums if anyone wanted it, so far no interest expressed: https://forums.triplea-game.org/topic/941/tripleawarclub-org-url-going-for-sale

**Comment by DanVanAtta** [comment]
@veqryn ; @ron-murhammer any thoughts? This feels like a tough call to me, but I think it's 85% the fear of loss and nothing more. We would need a pretty good reason to revive a second domain, I have trouble seeing why we would and particularly since we can make more use of the `triple-game.org` URL.

I'm thinking around end of September it would make sense to release the domain unless by then we've found a volunteer to take it over or some plan to use it.

**Comment by veqryn** [comment]
I think there are still a lot of links out there that go to that domain, and it is useful to have them redirected to the new site.
I'd probably wait til 2019 to sell the domain.

**Comment by DanVanAtta** [comment]
DNS renewal comes up on 11/25/2018, if we can sell before then we'll save on the renewal cost. At the same time, I don't think paying for another year is necessarily a big deal either.

Doing a google search for warclub, we are looking pretty good. But, seems like the biggest priority would be dice URL and dice registration emails, eg: https://dice.tripleawarclub.org/

**Comment by veqryn** [comment]
What would the renewal fee be?

**Comment by prastle** [comment]
I am also curious if perhaps Roger might be interested in it?  Probably not since he has his own.

**Comment by DanVanAtta** [comment]
$30 for another year, we might be able to transfer the domain to namecheap which would be $15/year, but the time cost to figure that out might not be worthwhile.

**Comment by prastle** [comment]
I seem to recall you mentioning ten years somewhere.  Is there a savings for a ten year purchase? @DanVanAtta

**Comment by DanVanAtta** [comment]
@prastle  - Yes, but with Namecheap, and for the triplea-game.org domain. Namecheap will sell a decade of registration for $140, we have that for the triplea-game.org domain, with IIRC 7 years left.

**Comment by prastle** [comment]
Ok so 140 bucks.  How much work to swap to them?  Also how much to stay where we are for 10 years even tho possibly unused?

**Comment by prastle** [comment]
To clarify @DanVanAtta  I am a bit nostalgic about that org as well.  Since it requires another year before marti is moved perhaps we just keep it?

**Comment by DanVanAtta** [comment]
We have namecheap for triplea-game.org.

Why continue even paying for tripleawarclub.org if all it does is redirect to triple-game.org? we could instead finance a good chunk of a year instead for that money. 

> Also how much to stay where we are for 10 years even tho possibly unused?

If going with goDaddy, we're talking $300 for something we are not using. The point of this issue is more not to drum up the money to 'save' tripleawarclub, it's to check if anyone else has a use for it within the community because we do not, and to make sure there is nothing left over before we give it up.

**Comment by DanVanAtta** [comment]
Fear of loss @prastle ; it's bad use of money. We only need to update the DNS names, we don't have to migrate off the marti server to be able to give up the domain. The DNS migration should go to subdomains of triplea-game.org which would be free.

**Comment by prastle** [comment]
I am just asking ?s
I have np with closing it once Marti is moved.

**Comment by prastle** [comment]
KK hopefully someone wants it

**Comment by DanVanAtta** [comment]
my point, we don't even need to move marti. The DNS updates are all handled at (the internet) DNS registry, so we'd use namecheap or goDaddy to do those updates.

**Comment by prastle** [comment]
kk

**Comment by veqryn** [comment]
Move everything off the old domain, to the new domain or subdomains.
If it can be done smoothly by October, then I'd vote to sell the domain in November (after everything has transitioned) and save us having to pay $30/year.

**Comment by prastle** [comment]
This might be a bad idea but maybe we should add it to the Yaml in the lobby so that all members could have a chance to buy it?  Just a thought.

**Comment by prastle** [comment]
Only dedicated members join the forum. @veqryn  @DanVanAtta

**Comment by DanVanAtta** [comment]
@veqryn I think that sounds like a reasonable plan. I'll assign this to myself for the follow up and will get this going again when back from vacation (will be gone a few weeks, departure got delayed, will be leaving in a day or two).

@prastle  this forum post is up: https://forums.triplea-game.org/topic/941/tripleawarclub-org-url-going-for-sale   I'm happy to *give* the domain to any of our community members if they want it. It can be quite some effort to build a full fan site, I would guess any existing ones would be more interested rather than someone building one from scratch to fit the domain (but maybe that person is out there and they were just waiting for the domain to be motivated, idk, but as a project we do not really need to maintain it anymore)

**Comment by prastle** [comment]
It wasn't my interest to build another fan site.  I had just hoped a member would take it an promote triplea. Example Roger and his maps etc. Do what you wish. $ wise you are completely correct.

**Comment by DanVanAtta** [comment]
well, if someone takes it, it would be a "fan site", right? Splitting hairs I think there - I too think it'd be ideal for a someone in the community to take it. The migration of links should arguably happen anyways, and we'll do it reasonably slowly enough to give opportunity if such a volunteer appears.

**Comment by DanVanAtta** [comment]
I believe the consensus is to continue removing dependencies and release the domain name back to public domain.

**Comment by prastle** [comment]
atm I have it secured private until marti moved
