### ISSUE TITLE
Bomber Raid Incorrect Behavior

### ISSUE THREAD

**Issue by beelee1** [triplea-game/triplea#3728]
### Engine version

10876
### My Operating System
linux
### Map name
global 40 house rules with canada
### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
SBR'd western germany and france. Western Germany attack had no bmbr losses. France lost both bmbrs and western germany bmbrs disappeared after that. RD 10 USA combat

### Do you have the exact error text? Please copy/paste if so
no error
### Instead of this error, what should have happened?
the USA western germany bmbrs should still be there

**Comment by beelee1** [comment]
[bomber raid error.zip](https://github.com/triplea-game/triplea/files/2259990/bomber.raid.error.zip)

**Comment by panther2** [comment]
I have investigated a bit inspecting the game history of the savegame.
![battle](https://user-images.githubusercontent.com/20812775/43687025-07449dba-98cf-11e8-9144-1daa35e19ac3.PNG)

During the "Strategic Bombing Raid in France" (following the raid in W.Germany) the bombers are still there.

The bombers disappear during "Battle in Western Germany":
One can see that those bombers are never part of the battle, as no dice are rolled for them.
At the end of the battle there is a note "Some non-combat units are destroyed" followed by a list of units that includes those bombers.

So those bombers were obviously "non-combat units" (they did not roll during the battle) and thus were destroyed.

I have no idea what rules may be behind this procedure, as I am not familiar with this variant and its rules.

**Comment by beelee1** [comment]
Thanks for looking at it panther. My bombers have no attack or defense value as I want them to be SBR capable only. It appears that's why they die. They work fine if I don't have a regular combat or win a regular combat but die if I lose. 

I'll have to try to find a work around or make a feature request.
