### ISSUE TITLE
Lobby Bots Crashing and Restarting Daily

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#3735]
It appears that especially on the new 700 bots that they are frequently crashing and restarting (daily). This is easy to tell even if you just sit in the lobby as the ones that crash then restart but have no map selected and show "-". This causes issues for players that are playing in them as they not only have to then go to another bot but it seems they are losing their save game as well. 

Here was one that was reported on the forum: https://forums.triplea-game.org/topic/954/bot-702

Looking at the current lobby both 703 & 706 have restarted in the last couple of hours. Using the "started" column, I can see 706 joined back at 9:51PM CST and 703 joined back at 8:28PM CST. **Both fail to allocate memory right before they restart.**

**706 Logs**
https://papertrailapp.com/systems/bot70_nj_4g_usa/events?selected=962955919682088963&focus=962955919682088963
```
Aug 05 21:50:04 bot70_nj_4g_usa run_bot.sh:  OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000fee80000, 3145728, 0) failed; error='Cannot allocate memory' (errno=12)
Aug 05 21:50:04 bot70_nj_4g_usa run_bot.sh:  #
Aug 05 21:50:04 bot70_nj_4g_usa run_bot.sh:  # There is insufficient memory for the Java Runtime Environment to continue.
Aug 05 21:50:04 bot70_nj_4g_usa run_bot.sh:  # Native memory allocation (mmap) failed to map 3145728 bytes for committing reserved memory.
Aug 05 21:50:05 bot70_nj_4g_usa CRON:  (CRON) info (No MTA installed, discarding output)
Aug 05 21:50:05 bot70_nj_4g_usa run_bot.sh:  # An error report file with more information is saved as:
Aug 05 21:50:05 bot70_nj_4g_usa run_bot.sh:  # /home/triplea/bots/1.9.0.0.10663/hs_err_pid16712.log
```

**703 Logs**
https://papertrailapp.com/systems/bot70_nj_4g_usa/events?selected=undefined&focus=962935161262092289
```
Aug 05 20:27:35 bot70_nj_4g_usa run_bot.sh:  OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000f4f80000, 9437184, 0) failed; error='Cannot allocate memory' (errno=12)
Aug 05 20:27:35 bot70_nj_4g_usa run_bot.sh:  #
Aug 05 20:27:35 bot70_nj_4g_usa run_bot.sh:  # There is insufficient memory for the Java Runtime Environment to continue.
Aug 05 20:27:35 bot70_nj_4g_usa run_bot.sh:  # Native memory allocation (mmap) failed to map 9437184 bytes for committing reserved memory.
Aug 05 20:27:35 bot70_nj_4g_usa run_bot.sh:  # An error report file with more information is saved as:
Aug 05 20:27:35 bot70_nj_4g_usa run_bot.sh:  # /home/triplea/bots/1.9.0.0.10663/hs_err_pid27000.log
```

Here is the linode 70 CPU graph showing some significant spikes:
![image](https://user-images.githubusercontent.com/1427689/43696558-1d15e8a8-9904-11e8-9b36-3a7d8470ff65.png)

It appears in the **last 5 days or so that there have been about 10 restarts** (remove obvious failed restarts of the same bot from below to get unique restarts).
https://papertrailapp.com/systems/bot70_nj_4g_usa/events?q=Stopped%20TripleA%20Bot
```
Aug 01 20:40:36 bot70_nj_4g_usa systemd: Stopped TripleA Bot 01.
Aug 01 20:40:59 bot70_nj_4g_usa systemd: Stopped TripleA Bot 01.
Aug 02 07:05:04 bot70_nj_4g_usa systemd: Stopped TripleA Bot 01.
Aug 02 07:21:19 bot70_nj_4g_usa systemd: Stopped TripleA Bot 09.
Aug 03 23:05:10 bot70_nj_4g_usa systemd: Stopped TripleA Bot 06.
Aug 04 13:01:12 bot70_nj_4g_usa systemd: Stopped TripleA Bot 04.
Aug 04 19:11:57 bot70_nj_4g_usa systemd: Stopped TripleA Bot 03.
Aug 05 18:59:53 bot70_nj_4g_usa systemd: Stopped TripleA Bot 04.
Aug 05 19:00:44 bot70_nj_4g_usa systemd:  Stopped TripleA Bot 04.
Aug 05 19:01:32 bot70_nj_4g_usa systemd:  Stopped TripleA Bot 04.
Aug 05 19:15:05 bot70_nj_4g_usa systemd:  Stopped TripleA Bot 07.
Aug 05 20:21:31 bot70_nj_4g_usa systemd:  Stopped TripleA Bot 03.
Aug 05 20:21:48 bot70_nj_4g_usa systemd:  Stopped TripleA Bot 03.
Aug 05 20:22:07 bot70_nj_4g_usa systemd:  Stopped TripleA Bot 03.
Aug 05 20:22:25 bot70_nj_4g_usa systemd:  Stopped TripleA Bot 03.
Aug 05 20:22:46 bot70_nj_4g_usa systemd:  Stopped TripleA Bot 03.
Aug 05 20:23:08 bot70_nj_4g_usa systemd:  Stopped TripleA Bot 03.
Aug 05 20:23:35 bot70_nj_4g_usa systemd:  Stopped TripleA Bot 03.
Aug 05 20:23:52 bot70_nj_4g_usa systemd:  Stopped TripleA Bot 03.
Aug 05 20:24:10 bot70_nj_4g_usa systemd:  Stopped TripleA Bot 03.
Aug 05 20:24:29 bot70_nj_4g_usa systemd:  Stopped TripleA Bot 03.
Aug 05 20:24:46 bot70_nj_4g_usa systemd:  Stopped TripleA Bot 03.
Aug 05 20:25:05 bot70_nj_4g_usa systemd:  Stopped TripleA Bot 03.
Aug 05 20:25:30 bot70_nj_4g_usa systemd:  Stopped TripleA Bot 03.
Aug 05 20:25:49 bot70_nj_4g_usa systemd:  Stopped TripleA Bot 03.
Aug 05 20:26:09 bot70_nj_4g_usa systemd:  Stopped TripleA Bot 03.
Aug 05 20:26:27 bot70_nj_4g_usa systemd:  Stopped TripleA Bot 03.
Aug 05 20:26:53 bot70_nj_4g_usa systemd:  Stopped TripleA Bot 03.
Aug 05 20:27:17 bot70_nj_4g_usa systemd:  Stopped TripleA Bot 03.
Aug 05 20:27:35 bot70_nj_4g_usa systemd:  Stopped TripleA Bot 03.
Aug 05 21:50:26 bot70_nj_4g_usa systemd:  Stopped TripleA Bot 06.
```

**Comment by ron-murhammer** [comment]
@DanVanAtta @RoiEXLab So based on that, we have some sort of memory issue (either leak or just not enough). I'd recommend either reducing the number of bots on the 70 server to like 6-8 or increase its memory.

**Comment by DanVanAtta** [comment]
https://github.com/triplea-game/infrastructure/pull/102 would have 7 bots running, we would need to kick+stop the top 3 instances as well.

@ron-murhammer , I'm about to leave town, will be away from computer for 2 weeks, @RoiEXLab if i understand will be away for 3 weeks as well. :sun_with_face:  

Are you comfortable adding a new bot server? I think going back to the 3 or 4 per was more stable. 

It is not too bad:
- create machine in linode web UI (you'll pick the root password during this)
- ssh to it, add cronjob
- add host entry to `host_control.sh`
- watch gitter room for notifications on the server

Infra readme has  details

**Comment by DanVanAtta** [comment]
Actually.. I take that back, really just follow the setup steps on infrastructure, there is more than just the conjob, it does have it spell out, there is a curl command and nothing more to run on a new server.

I'm setting up 2 new servers that can be ready to go.

**Comment by DanVanAtta** [comment]
The 2 new servers are ready, https://github.com/triplea-game/infrastructure/pull/103 would add them in.

@ron-murhammer I'm going to pass this issue back to you, I will not be able to follow up.

**Comment by prastle** [comment]
@DanVanAtta  @ron-murhammer  @ssoloff  @RoiEXLab   We also need this server to be updated like the other servers were.  When you ssh as admin to the 700 server to attempt to run sudo service commands it asks for a password which it should not.  I have booted 708 and 709 from the lobby for now since I cannot manually stop them.

**Comment by ron-murhammer** [comment]
So to begin the setup of the next set of servers, the first thing was to fix the 700 ones by:
- Reducing to 7 bots: https://github.com/triplea-game/infrastructure/pull/106
- Increase number of possible bots to 10: https://github.com/triplea-game/infrastructure/pull/110

**Comment by prastle** [comment]
Presently the new bots running 2gb ram and double swap seem to be fine.  This =s 7x8 on a long weekend.  No crashes yet.  Yes this probably can be closed.  @DanVanAtta  @ron-murhammer

**Comment by prastle** [comment]
What does need fixing is the launching of new servers by infra since it obviously fails.  These are old bots that I resized.

**Comment by prastle** [comment]
I should also add @ron-murhammer  fixed the infra from 3 to 7.

**Comment by DanVanAtta** [comment]
Looks like this has been fixed some time ago.

My impression is that having at least 512MB RAM for swap space was a key configuration and was the difference between stable and not.

Marking as close-pending, please chime in if there is anything further.

**Comment by prastle** [comment]
np as long as a new infra bot server launch can be started directly from linode
@DanVanAtta

**Comment by ssoloff** [comment]
@ron-murhammer Tagging you simply because you are currently assigned... Can we close this issue?  Have there been any regular bot crashes due to OOM since the server resize?

**Comment by prastle** [comment]
Seems to be fine @ssoloff
