### ISSUE TITLE
Update dev environment to use Gradle build

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#374]
It's time a good time to delete the jars included in the 'lib' folder. Let's do so once the core contributors are ready. @ron-murhammer , @veqryn , would you mind confirming you've got your IDE of choice working with gradle for dependencies?

I had to do this:
- install gradle and buildship plugins for eclipse
- ran: `$ gradle clean cleanEclipse cleanProject cleanClasspath eclipse`

Then I deleted the triplea project and imported it as a gradle project

**Comment by gaborbernat** [comment]
Actually avoid running those commands, just use the import gradle option from within Eclipse.

**Comment by DanVanAtta** [comment]
@ron-murhammer , @veqryn  - any progress on this?

**Comment by ron-murhammer** [comment]
@DanVanAtta Not yet. I've run gradle commands from command line but just have it imported as a regular java project in eclipse 4.4.

**Comment by DanVanAtta** [comment]
Install these two plugins, then re-import as a gradle project:
- https://marketplace.eclipse.org/content/gradle-integration-eclipse-0
- https://marketplace.eclipse.org/content/buildship-gradle-integration
Then you should get a  'gradle' menu submenu option when you right click the project.

**Comment by DanVanAtta** [comment]
@ron-murhammer , @veqryn , any updates on configuring your IDE to download gradle dependencies? this is a bit of a blocker for forward progress, we would really benefit from cleaning up the large amount of legacy unused  code and configuration.

**Comment by DanVanAtta** [comment]
@ron-murhammer , @veqryn  - the root folder not found bug fix is blocked by this.

@ron-murhammer , you've had objection to deleting the ant build files. I think it's a good time to revisit that. The ant build file is out of date, and also all code in SVN for the game engine is frozen. If someone wanted to go back to the ant file, IMO they would basically need to drop all the updates we did in Github and go back to SVN. Since SVN is frozen, we are beyond the point of no return, in no case will we ever use the old ant build again for this project. No matter what problems would exist in Gradle, we would roll forward with a fix.

**Comment by DanVanAtta** [comment]
@ron-murhammer , please take a crack at this when you get the chance. It took only about 15 minutes for me.

**Comment by DanVanAtta** [comment]
We've got some PRs coming that add new Jars. The Jar binary is not being added, just the gradle dependency. That means it will not be long before it is necessary to get dependencies via gradle. Resolving.
