### ISSUE TITLE
Pre Release .11127 Battle Window

### ISSUE THREAD

**Issue by Heppisorus** [triplea-game/triplea#3742]
.11127
My Operating System

Map name

Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
![image](https://user-images.githubusercontent.com/30943648/43749071-941095e0-99c0-11e8-8e97-ca4b550b14ac.png)

Do you have the exact error text? Please copy/paste if so
No error.  But the Battle window is certainly sub-optimal as a usable UI. 
Instead of this error, what should have happened?
The dice roll section needs scroll bars to see results beyond 7 (which is the highest die result you can see with the Battle Window maximized)

Any additional information that may help

Attach a Zipped Save Game

**Comment by ron-murhammer** [comment]
It appears that #3669 caused that as it doesn't ensure that empty "roll at" are not displayed. Reverting that PR now.
