### ISSUE TITLE
Bots Sometimes Start But Fail to Join Lobby

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#3747]
It appears that if a bot starts up and is running but could fail to connect to lobby. The cron jobs don't appear to check that which means unless someone notices the missing bot then it isn't of any use and doesn't get restarted. This was the case for bot301 and I just manually stopped/started and now it appears in the lobby.

**Comment by DanVanAtta** [comment]
Isn't the lobby watcher thread functionality supposed to reconnect automatically? I'm surprised a 'restart' is needed if the bot app is running. Did the app start up and stay running? If there is not automatic reconnection, then the bot-app should terminate so it's not just hanging around idle. The server gitter room has a report of how many bot instances are running, fixing either behavior should give us visibility.

**Comment by DanVanAtta** [comment]
@ron-murhammer I'm adding 'bug' label, the fix I think would in application code, either properly crash and halt or properly reconnect.

**Comment by DanVanAtta** [comment]
@ssoloff @ron-murhammer , is this fixed? I want to say I recall @ssoloff  found something in the lobby watcher thread where that would die, and fixed it. Please re-open if that is not the case of if this is still a problem.

**Comment by prastle** [comment]
I can answer that in 8 minutes

**Comment by prastle** [comment]
Bots relaunch 300 series  in 12 min
with current lobby

**Comment by ssoloff** [comment]
> I want to say I recall @ssoloff found something in the lobby watcher thread where that would die, and fixed it.

#4111
