### ISSUE TITLE
Curious Tooltip Detail for .11131

### ISSUE THREAD

**Issue by Heppisorus** [triplea-game/triplea#3749]
### Engine version
.11131

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
![image](https://user-images.githubusercontent.com/30943648/43789285-8b05666a-9a3d-11e8-8115-6c6f3d4518a9.png)

### Do you have the exact error text? Please copy/paste if so
No error generated
### Instead of this error, what should have happened?
Sporadically when the cursor is not on the map (on the menu or minimap) the tooltip will still activate when the cursor is dormant.  It is detecting units that are hidden behind the UI areas.
### Any additional information that may help
It would be ideal if the Tooltip would only activate while your cursor was left hovering over the active portions of the map.

**Comment by Heppisorus** [comment]
Oh and BTW this release seemed to fix all the other issues with the Battle Window.

**Comment by DanVanAtta** [comment]
@Heppisorus ; @ron-murhammer , there was a good deal of work on tooltips, is this fixed in the latest?

**Comment by DanVanAtta** [comment]
Given lack of response, will assume things have been improved. Please feel free to re-open or create a new issue for any specific further improvements.
