### ISSUE TITLE
Correct OverBuy warning to be accurate

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3769]
This ticket is an investigation/tracking of where the over-buy warning is going to be incorrect. If we can fix that, then we have some options to make over-buy warning always displayed. 

This ticket is track logic changes that would happen to the over-buy warning, not in scope are any further UI changes or anything else related to purchases, but instead how over-buy is configured in XML and calculated in the game.

The fact that the overbuy warning can be turned off when it would be incorrect seems more like a work-around then a proper fix. Because we are working around logic that should work correctly, but needs to be turned off completely when it does not, I would classify that as somewhat mitigated code defect. The cost of this is a poor/degraded UX where game play mistakes (potentially critical) are allowed.

**Comment by simon33-2** [comment]
Main problem I am aware of is the automatic facility upgrade in the 1940 games when the Americans declare war, which happens at the start of combat movement - after purchase on the standard maps.

**Comment by panther2** [comment]
Yes, there's an issue for it at the map repo: https://github.com/triplea-maps/world_war_ii_global/issues/4
