### ISSUE TITLE
TripleA does not roll multiple Rocket attacks in wwII_global1940

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#3784]
As brought up here:
https://forums.triplea-game.org/topic/960/multiple-rockets-can-t-attack-the-same-territory-in-ww2-global-40-2nd-edition

### Engine version
Reproduced with 11235

### Map name

wwII_global_1940
most likely in every game.xml

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)

Give Germany Rockets tech, add another German airfield to Norway, proceed to Combat Move Phase

### Do you have the exact error text? Please copy/paste if so

Video instead:

![rocket](https://user-images.githubusercontent.com/20812775/44000078-53f052ea-9e19-11e8-8c94-4b4e50f19ee7.gif)

### Instead of this error, what should have happened?

As there are two airfield launching rocket attacks against UK, a second attack should have been rolled.

### Any additional information that may help

Rulebook says: "... each of your operative air bases can make a single rocket attack against an enemy industrial complex, air base, or naval base within 4 spaces of it. "

While the engine correctly asks for two target territories, only one attack is rolled.
First TripleA asks for the Western Germany Airbase, then for the Norwegian Airbase.
But it looks like only the Norwegian Airbase's Rocket is rolled, then.

See the turn summary here:
https://www.axisandallies.org/forums/index.php?topic=31084.msg1801670#msg1801670

[rocket.zip](https://github.com/triplea-game/triplea/files/2280821/rocket.zip)

**Comment by simon33-2** [comment]
This should be fixed in map 4.0.

**Comment by beelee1** [comment]
yea i checked out the latest global update simon but tech isn't active. What did you change that made it work ?

**Comment by simon33-2** [comment]
The most recent version of the global 2nd ed map.

**Comment by panther2** [comment]
Ah, I did not notice that edit in the xml coming with a recent commit, though it was about time to increase the version number :-)

**Comment by Cernelius** [comment]
Those are the versions of the games, not of the map. A map can have infinite games, each one with its own version number.

There is not a map versioning (sadly).

**Comment by panther2** [comment]
@Cernelius 
Yes. On that specific map it had been 3.9 for ages, regardless of changes and tweaks in the meantime. That's why I did not realize the change to 4.0.

> There is not a map versioning (sadly).
Agreed.

**Comment by Cernelius** [comment]
>On that specific map it had been 3.9 for ages, regardless of changes and tweaks in the meantime.

This seems to be the case quite often (sadly).

Personally, I almost always increase the game version number if I touch anything in the xml and the matter is in any ways perceptible to the user, except if the change is not specific to the map or game (like the general PUs to resources costs changes I made recently for a bunch of maps).

However, in this case, I'm not sure upgrading the very first digit is advisable? I usually do that in cases like WAW to 2.0, changing the very fundamental elements of the map itself, like adding some more territories that didn't exist before at all.

**Comment by simon33-2** [comment]
The second digit is already at 9. Major numbers 1 through 3 meant nothing really.

**Comment by panther2** [comment]
@simon33-2 

> This should be fixed in map 4.0.

My above stated reproduction of the issue was using exactly this version (latest commit 17 days ago).

**Comment by simon33-2** [comment]
I take it back. Not fixed in 4.0. Requires an incompatible release to fix all the issues with rockets.

**Comment by panther2** [comment]
Can't rocket attacks be rolled one after the other? There is no need to hide results of one rocket attack before the next one is rolled. 

Krieghund said: "There is no reason why you would need to declare all rocket targets before rolling for any rockets."

**Comment by General-Dru-Zod** [comment]
I am looking at one of my mods (Bad-Ass 4 nation ffa) where this feature used to function and it no longer does with .11311. The behavior is as described above, I choose multiple rockets to attack the same target but only one fires, and ends.

This may have been broken way back when we changed to v1.9 since it works in for my v1.8.0.9 version. It allows me to pick same target, furthermore the order is as follows.
1. rocket 1 selects target and fires
2. rocket 2 selects target and fires
3. rocket 3 selects target and fires
All same target.

**Comment by General-Dru-Zod** [comment]
Here is the xml for the v.1.8.0.9 engine. Place it in the ww2 variants game folder. Then edit a scenario to rocket same target.

[WW2v3-Bad-Ass_4-Nation_FFA_v.1.3.3.0_A_.zip](https://github.com/triplea-game/triplea/files/2287797/WW2v3-Bad-Ass_4-Nation_FFA_v.1.3.3.0_A_.zip)

**Comment by panther2** [comment]
> ... It allows me to pick same target, furthermore the order is as follows. ...

That looks good and rules compliant, according to Krieghund's clarification.
https://www.axisandallies.org/forums/index.php?topic=28562.msg1648393#msg1648393

Maybe something simply can be reverted to restore that functionality?

**Comment by General-Dru-Zod** [comment]
Maybe a global property can be added to determine the mode of target selection and firing for rockets. 

Meaning one modes sequence is as follows:
1. rocket 1, player selects target and fires
2. rocket 2, player selects target and fires
3. rocket 3, player selects target and fires
All same target or separate targets depending on existing global properties.

And other modes sequence is as follows:
1. rocket 1 , player selects target
2. rocket 2 , player selects target
3. rocket 3 , player selects target
4. All rockets fire
All same target or separate targets.

The former will follow the official A&A rules and the latter will alleviate concerns of seeing damages before all target selections are completed.

**Comment by simon33-2** [comment]
That idea is fine @General-Dru-Zod . Indeed, it is what I was intending to put into an incompatible release. It's just that the incompatible release has never been started.

The rockets should actually fire after the strategic bombing in your second scenario. Even in the first one the prevention of a scramble by rockets disabling the airbase means the current timing of rocket firings is wrong.

**Comment by ssoloff** [comment]
@panther2 This should be fixed in 1.9.0.0.11425 or later.  Please confirm when you have a chance.

**Comment by panther2** [comment]
@ssoloff I have recreated and tested the scenario given above using 11440.
I can confirm it works fine now. Thank you.

However rockets don't fire during the correct phase. But that's another issue I am going to open soon.

This one can be closed for now. Thanks @simon33-2 and @ssoloff .
