### ISSUE TITLE
Exiting lobby client sometimes exits TripleA completely

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/triplea#3793]
### Engine version

1.9.0.0.11270

### My Operating System

Linux localhost.localdomain 4.17.11-200.fc28.x86_64 <span>#</span>1 SMP Mon Jul 30 15:21:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)

* Join lobby.
* From lobby client, select **File > Exit**.

At this point, sometimes, the TripleA application exits completely.

### Instead of this error, what should have happened?

The TripleA main menu should be displayed.

### Any additional information that may help

This appears to be a race condition between `LobbyFrame#shutdown()`:

```java
public void shutdown() {
  setVisible(false);
  dispose();
  new Thread(GameRunner::showMainFrame).start();
  client.getMessenger().shutDown();
  GameRunner.exitGameIfFinished();
}
```

and `GameRunner#exitGameIfFinished()`:

```java
public static void exitGameIfFinished() {
  SwingUtilities.invokeLater(() -> {
    final boolean allFramesClosed = Arrays.stream(Frame.getFrames())
        .noneMatch(Component::isVisible);
    if (allFramesClosed) {
      ExitStatus.SUCCESS.exit();
    }
  });
}
```

The race is between the thread running `GameRunner#showMainFrame()` and the thread running the expression in `GameRunner#exitGameIfFinished()` that initializes `allFramesClosed`.

In #3502, `LobbyFrame#shutdown()` was changed as follows:

```diff
diff --git a/game-core/src/main/java/games/strategy/engine/lobby/client/ui/LobbyFrame.java b/game-core/src/main/java/games/strategy/engine/lobby/client/ui/LobbyFrame.java
index a139a802a..ba3bbe46a 100644
--- a/game-core/src/main/java/games/strategy/engine/lobby/client/ui/LobbyFrame.java
+++ b/game-core/src/main/java/games/strategy/engine/lobby/client/ui/LobbyFrame.java
@@ -221,7 +221,7 @@ public class LobbyFrame extends JFrame {
   public void shutdown() {
     setVisible(false);
     dispose();
-    GameRunner.showMainFrame();
+    new Thread(GameRunner::showMainFrame).start();
     client.getMessenger().shutDown();
     GameRunner.exitGameIfFinished();
   }
```

I can exacerbate the race condition and trigger the erroneous behavior consistently by replacing the line above with the following:

```java
new Thread(() -> {
  Interruptibles.sleep(1000);
  GameRunner.showMainFrame();
}).start();
```

Unfortunately, simply reverting the one-line change from #3502 doesn't work because the `loadGame()` call within `showMainFrame()` must not be run on the EDT, and will throw an `IllegalStateException` in this context.

However, if I move the proceeding lines onto the background thread, that appears to work:

```java
public void shutdown() {
  setVisible(false);
  dispose();
  new Thread(() -> {
    GameRunner.showMainFrame();
    client.getMessenger().shutDown();
    GameRunner.exitGameIfFinished();
  }).start();
}
```

@RoiEXLab, do you have any thoughts on the best way to proceed here?  The last snippet above doesn't put the code into a worse state than it already was, but there may be a better solution.  Did you gain any other insights while working #3502?

**Comment by RoiEXLab** [comment]
@ssoloff Not really. As you correctly observed I changed it so the action is performed on the right thread.
Using chained futures might look a bit nicer, but I don't really have a better approach to offer.
However I believe there's another place in the code where a new thread is created for this as well (same PR), so you might want to check if there's a similar issue for this.
