### ISSUE TITLE
Entering a passworded game fails to open.

### ISSUE THREAD

**Issue by prastle** [triplea-game/triplea#3799]
### Engine version

.11239
### My Operating System
Win 10
### Map name
270 40%
### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
When attempting to enter a pass worded game the dialog box to enter the password does not appear.
### Instead of this error, what should have happened?
Box should have opened and allowed a password to be entered.
<img width="965" alt="2018-08-13" src="https://user-images.githubusercontent.com/17258293/44071179-a7191d66-9f55-11e8-8269-bd449b47fd5d.png">

### Any additional information that may help
Box opens with .7634

**Comment by ssoloff** [comment]
Here's what appears to be the failure timeline:

* 10291: Last build to work correctly.
* 10300: `UiThreadingViolationException` raised when Client Options dialog displayed; can't even get to Password dialog.  See #3448.
* 10380: Client Options dialog displayed again; `UiThreadingViolationException` raised when Password dialog displayed.  See #3464.
