### ISSUE TITLE
Verify Linode root password

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/triplea#3827]
I attempted to login to `prerelease_staging` via the Linode Lish console using the `root` credentials in the master secrets document and was denied access.

Could someone please verify the password in the master secrets document is correct?

**Comment by prastle** [comment]
@ssoloff  We already suffered that problem while trying to fix the new bot servers.  I can confirm it is not there.  Perhaps we just delete them and make a new root and create new ones and record the new root in the secret docs?
  We can then add the new root to all the rest when Dan is back?  Just a thought.  @RoiEXLab  @ron-murhammer

**Comment by prastle** [comment]
I should also add that Linode detected probs two days ago and the infra support is maxed out as well.

**Comment by prastle** [comment]
It appears dan updated 13 days ago @ssoloff

**Comment by ssoloff** [comment]
@prastle Yes, prior to that it was blank.  IIRC, @ron-murhammer asked @DanVanAtta to add it about that time, but the password that's there now doesn't appear to work. :smile:

**Comment by prastle** [comment]
Wecome to our world :)

**Comment by prastle** [comment]
Thus why I suggest as a test as well
Delete staging and attempt reload if that works add in two new mega servers
record the root in master docs

**Comment by prastle** [comment]
fix the other roots later

**Comment by DanVanAtta** [comment]
We only need to change/fix the root password on two servers. One of those is about done already. That pass is on master secret file, please do not add/place it anywhere else. In theory anyone that knows that password should not participate in any tournaments or ladders as they can manipulate anything and everything (so community moderators should not know it, and unless you know linux+sql, you probably do not need it)

**Comment by prastle** [comment]
@DanVanAtta  simple point is
one root
for all devs
I guess I would be the only exception.
Either way
If they can't fix it when your on holidays we have a problem...

**Comment by DanVanAtta** [comment]
@prastle devs have the password for all servers except the two listed, and TBD on forum server.

> If they can't fix it when your on holidays we have a problem.

I fully agree, happily the full team has gotten more involved in the infrastructure project which is the important place to knwo.

> I would also like to add which is off topic for this thread. When is warclub being resized?
@DanVanAtta

don't know, no current plan here. Would be worth a dedicated issue so we can keep that convo tracked and in one place.

**Comment by prastle** [comment]
forum is fine
being roi and myself since we are the only ones that work on it
but I guess to explain better I think all devs and senior admin should have one root jmho
pick what ever one ya wish
but
just to be honest I could have reset every root when I rebooted each server last week.  I Truly do not understand why 4 of yas don't have it...

**Comment by prastle** [comment]
Warclub costs 10 bucks a month and runs lobby and marti now.  Do we need a 10 buck a month plan?
for that?

**Comment by prastle** [comment]
Also should we upgrade papertrail since you are talking in one spot? To enable all of them to fix easier?
@DanVanAtta

**Comment by DanVanAtta** [comment]
Forum server is not standard, I am unable to access it, I created: https://github.com/triplea-game/triplea/issues/3947 for follow-up. The only server left is infrastructure. I think it can probably be powered down for the moment. We have grafana running and scraping metrics, but we're not using it for the moment.

**Comment by DanVanAtta** [comment]
infra server is gone, new PreRelease server has a known password, at this point we have access to the full fleet and #3947 is open for final follow-up.
