### ISSUE TITLE
prerelease_staging out of disk space

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/triplea#3828]
(Migrated from triplea-game/infrastructure#109.)

<pre>
admin@prerelease_staging:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
<strong>/dev/root        20G   19G     0 100% /</strong>
devtmpfs        488M     0  488M   0% /dev
tmpfs           490M  4.0K  490M   1% /dev/shm
tmpfs           490M   51M  440M  11% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           490M     0  490M   0% /sys/fs/cgroup
</pre>

Comment from @DanVanAtta:

> To fix, looks like we need to clean up old deployments. There are 203 bot installations and 215 lobby installs. It's interesting the individual size of the lobby install is up to 30MB, regardless, if we never clean up we'll run out of space.

**Comment by DanVanAtta** [comment]
A new server is setup, it should become active after: https://github.com/triplea-game/infrastructure/pull/119 is merged. That would remove the release blocker from this label, I think we should use this issue to follow up to add a cleanup job so we don't run into this again.

**Comment by ssoloff** [comment]
I removed the **Release Blocker** label since `prerelease_staging` has been replaced with `PreRelease`.

I created #4145 to track the fact that infrastructure needs to clean up old builds.  Therefore, closing this issue, as the original problem described above has been resolved.
