### ISSUE TITLE
New installer - windows - clicking triplea Icon brings current game to foreground, rather than opening a new game

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#385]
Reported in: http://tripleadev.1671093.n2.nabble.com/Next-release-1-8-0-11-testers-wanted-tp7590912p7590940.html

"I had TripleA pinned to taskbar to easily open up multiple windows.
Now when opening it the taskbar-icon transforms into the open game removing the option to quickly launch an other game from taskbar."

I personally do not know windows so well, sounds like there is a difference in the shortcut menu behavior.

@gaborbernat , did you see any options in install4j that could alter this behavior?

I'm not marking this as a release blocker. It's an unfortunate "regression", but pretty clearly not worth reverting stuff to try and fix this (too much to revert, and too much benefit from what we would be reverting).

**Comment by gaborbernat** [comment]
I think in the latest install this should be already "fixed": http://i.imgur.com/2JtcC7M.png
