### ISSUE TITLE
New verion will not install

### ISSUE THREAD

**Issue by Heppisorus** [triplea-game/triplea#3857]
### Engine version
1.9.0.0.11472

### My Operating System
Win 10

### Do you have the exact error text? Please copy/paste if so
1.9.0.0.11472
### Instead of this error, what should have happened?
![image](https://user-images.githubusercontent.com/30943648/44352868-740cf280-a473-11e8-8065-ce7fedd95365.png)

### Any additional information that may help

Cannot continue on... cannot go back.  Does not revert to previously installed version.  Will not allow me to uninstall the half installed version.

**Comment by Heppisorus** [comment]
Fixed.  Must have been an issue with the custom engine version I had installed.

**Comment by RoiEXLab** [comment]
Closing then
