### ISSUE TITLE
Which maps to include with game engine

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#386]
feedback from users:

> 3-Maps included in download:
Showcasing a non WW2 map=okay, but feel the maps included should reflect the most played maps.
This to prevent all players from having to download maps right after install just to be able to play a game.
Thinking especially of new players. Let them play a few games first. Then if they want to expand they will go through the "trouble" of downloading more maps.
Where's Revised? Really can't cut that out i think. 
Great war? Middle earth? No need to be there i think.

**Comment by ron-murhammer** [comment]
I think this is a good one for discussion: http://tripleadev.1671093.n2.nabble.com/Maps-Packaged-With-TripleA-tp7591025.html

**Comment by DanVanAtta** [comment]
That SF discussion has taken a bit of a life of its own.. Is there agreement that if we can get some key features in, we can 'get away' with only including just the tutorial?

**Comment by DanVanAtta** [comment]
To be sure we're all on the same page, general concensus is to include only the tutorial map and require download of the rest.  We'll also need to add the previously bundled maps to triplea_maps.yaml so they can be available for download. Those maps are hosted in repo, so only the triple_maps.yaml update is needed for them.

**Comment by ron-murhammer** [comment]
@DanVanAtta - Yes as long as we make it easy enough for everyone (even the most basic user) to download maps.

**Comment by DanVanAtta** [comment]
We're pretty close. If someone clicks "choose game" before they have downloaded additional maps, we can display a pop-up asking them if they would like to download maps rather than view an empty choose game screen. How does that sound to you @ron-murhammer ?

**Comment by ron-murhammer** [comment]
@DanVanAtta - Agree. I think having that and finishing #471 are probably the 2 things we need in order to only include the tutorial map.

**Comment by ron-murhammer** [comment]
@DanVanAtta We've decided to only include the tutorial and changes made with #617
