### ISSUE TITLE
Java 1.8.0_181 Issues

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#3866]
So I downloaded Java 1.8.0_181 and noticed TripleA freezing a lot where I had to actually kill the application (both stable and pre-release). Usually just planning a turn or opening notes in game would do it. I rolled back to Java 1.8.0_171 and everything seems fine now.

Can someone else try it out and see if they see issues?

**Comment by ssoloff** [comment]
@ron-murhammer Not sure if you resolved this issue on your machine, but I've been using 1.8.0_181 since July 7, and I haven't experienced any freezes as you describe.

**Comment by ron-murhammer** [comment]
Yeah, I think I just needed a reboot :)
