### ISSUE TITLE
Organizing map download list

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#388]
Came up in #286, how to organize triplea_maps.xml

Current problems to solve:
- It's hard to find maps in the list
- The header sections are arbitrary
- We have tools in the list, yet there is no way to interact with the tools after they are downloaded, nor any indication of where they went.

Goals:
- showcase and/or tell people which maps are the really good ones
- fix the use-case today of: "you can't play with this person because you do not have the map" problem

**Comment by ron-murhammer** [comment]
@DanVanAtta Short-term improvement IMO would be to just have 2 categories (high quality and development) then sort alphabetically in each.

**Comment by DanVanAtta** [comment]
2 categories can make sense. I'd call them:  'release quality' and 'beta quality' . I'm afraid there are a lot of issues with having a "beta qualtiy" category. Perhaps we can solve them, but I think some of are deal breakers:
- many people already post their maps in development to SF. Having the same category in the game UI is not necessarily solving a problem for anyone
- development maps are likely to be updated much more quickly than `triplea_maps.xml`.  Game engine admins become a bottleneck, user feedback is not as useful
- if we have maps in development, that were already tested in SF for some time, what exact bar would they need to hit to go to "high quality"?  
- If a map simply never gains popularity, could it ever  be "high quality"? 
- What happens when a map maker abandons a map while it is still in development?
- How do users direct feedback to the map makers, after they have play tested the development maps? Unless you got the map from the SF forums in the first place, linking up feedback to the map maker could be difficult.

**Comment by DanVanAtta** [comment]
@ron-murhammer , updated the issue header with a goals section, let me know if you can think of any problems and goals we should keep in mind.

**Comment by DanVanAtta** [comment]
For this goal:
"fix the use-case today of: "you can't play with this person because you do not have the map" problem"

I think this is most cleanly solved by #390 - essentially in place dialogs that allow the user to download the map on the spot. This means that whole user flow of heading to the map download section simply because they don't have a map ceases. Instead folks would download from the section when they want to explore new maps, rather than by necessity. At that point, having just one category, I think is okay. 

The next efforts would then be to improve the summary and thumbnails of each maps, not all of them have previews. Beyond that, adding map download counts to show popularity. Download counts solve the arbitrary: "which section to put this" problem.

**Comment by DanVanAtta** [comment]
@ron-murhammer , another thought. We could simulate some headers with metadata. Effectively adding extra columns that could be sorted/filtered. For example "beta", "era". I would like to stay with just "popularity", and only once we can get those counts (would be a small feature addition). But wanted to throw this out as an idea in case we really need to categorize the maps beyond just their name.

**Comment by ron-murhammer** [comment]
@DanVanAtta Yeah eventually I'd like to make the download page like a table so you have columns for popularity, era, number of players, etc and can sort/filter. The UI changes wouldn't be too hard to make but we'd then also have to update all the maps to include this data as well which is a lot of data entry. I actually posted this concept probably about a year ago in the forums somewhere :)

**Comment by DanVanAtta** [comment]
Deciding which extra columns to have can be tricky. For example, does 'era' apply to maps that transition eras? Does 'fantasy' make sense as an era, I'd be afraid we would make a lot of one-off eras. Same goes for a number of metadata values.

Popularity I think is a clear win. We can get that dynamically as well.

My suggestion is to start as simple as possible with just alphabetical list. Then augment it with popularity (probably not even sortable by popularity yet)

Personally, once we have a list where you can easily find maps - I'd like to then focus effort on cleaning up map thumbnails, standardizing the maps so that their thumbnail descriptions are high quality.

Thoughts on that approach @ron-murhammer ?  Also, do you have any new thoughts on 2 vs 1 category?  We could still make 2 categories work, but we'll need to design it somewhat carefully..

**Comment by ron-murhammer** [comment]
@DanVanAtta Yeah, deciding on which columns and how to categorize isn't easy. Most likely for era we'd need something like 'ww1', 'ww2', 'fantasy', 'prehistoric', 'medieval', 'renaissance', 'other', etc. We could look to get input from mapmakers as well. This would mostly help players that are interested in certain maps or setups find options.

I think at least right now we need 2 'quality' categories. If we eventually add in popularity and lots of other metadata and allow sorting/filtering then maybe there isn't the need anymore. But if we just throw all maps into a single alphabetical list right now then there is really no way for people to know what to try out. I think we need to have the top 20-30 proven maps at the top in a separate category so people start there.

**Comment by DanVanAtta** [comment]
"Classic maps" - proven maps that are well balanced and have been popular at one point.  Whether ti is 20-30 in this category I think is a bit arbitrary, but in terms of maps that fit the definition, I think we'll have at least a dozen.

"Community maps" category - all the other maps, good maps contributed by the community

We have not yet discussed map skins. They are also in the map download list. Having a radio button to toggle between maps and skins would be a pretty slick feature. A third "Map Skins" category I think would be appropriate.

Are we in agreement to three categories? "classic", "community", and "skins"? Any disagreement on the naming of those categories?

**Comment by DanVanAtta** [comment]
This discussion on source forge is covering this issue fairly well now:  http://tripleadev.1671093.n2.nabble.com/Maps-Packaged-With-TripleA-tp7591025.html
