### ISSUE TITLE
Syntax errors in some Global-BM-related XML files

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#3885]
As mentioned here:
https://forums.triplea-game.org/topic/978/global-1940-balanced-mod3

### Engine version
11370 and newer

### Map name
wwII_global1940 (BM related XML files)

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Start any affected game, see the error (console).

### Do you have the exact error text? Please copy/paste if so
`Aug 25, 2018 7:24:30 AM games.strategy.triplea.ui.ObjectivePanel$ObjectiveTableModel setObjectiveStats
SCHWERWIEGEND: objective.properties keys must be 2 parts: <game_name>.TABLEGROUP.<#>;player  OR  <game_name>.player;attachmentName
Aug 25, 2018 7:24:30 AM games.strategy.triplea.ui.ObjectivePanel$ObjectiveTableModel setObjectiveStats
SCHWERWIEGEND: objective.properties keys must be 2 parts: <game_name>.TABLEGROUP.<#>;player  OR  <game_name>.player;attachmentName
`
### Additional Info:
@ssoloff already identified 

`objectives.properties:395:World_War_II_Global_1940_Balanced_Mod.Russians;triggerAttachment_Russians_4_Increased_Lend_Lease_War_With_Japanese;=Additional <b>2 PUs</b> for each lend-lease route that is open if Japan has declared war on Russia. objectives.properties:511:World_War_II_Global_1940_Balanced_Mod_with_Combat_Move_First.Russians;triggerAttachment_Russians_4_Increased_Lend_Lease_War_With_Japanese;=Additional <b>2 PUs</b> for each lend-lease route that is open if Japan has declared war on Russia. objectives.properties:567:World_War_II_Global_1940_Balanced_Mod_with_Combat_Move_First.Russians;triggerAttachment_Russians_4_Increased_Lend_Lease_War_With_Japanese;=Additional <b>2 PUs</b> for each lend-lease route that is open if Japan has declared war on Russia. objectives.properties:630:World_War_II_Global_1940_Balanced_Mod3.Russians;triggerAttachment_Russians_4_Increased_Lend_Lease_War_With_Japanese;=Additional <b>2 PUs</b> for each lend-lease route that is open beyond Round 2 if Japan has declared war on Russia. objectives.properties:709:World_War_II_Global_1940_Balanced_Mod3_with_Combat_Move_First.Russians;triggerAttachment_Russians_4_Increased_Lend_Lease_War_With_Japanese;=Additional <b>2 PUs</b> for each lend-lease route that is open beyond Round 2 if Japan has declared war on Russia.
`

Those lines contain `;=` where it should be `=` only.

**Comment by simon33-2** [comment]
Fix pushed.

**Comment by panther2** [comment]
Thank you @simon33-2
