### ISSUE TITLE
Map maker tools

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#389]
They are still in SVN. @ron-murhammer , any thoughts on how/where to migrate them?

My 2 cents, the code for the tools is all bundled in with the game. IMO we add building them to the gradle task that does the release and publish them each time as their own build artifact. Eventually once we at least build all the pieces that are possible from the triplea-game monolith, we can then look to splitting stuff out to their own code repositories:
- triplea-game/maptools
- triplea-game/diceserve
- triplea-game/lobby

**Comment by ron-murhammer** [comment]
@DanVanAtta Agree. I think let's at least move them over and get them building with gradle. Then we can look to restructure.

**Comment by DanVanAtta** [comment]
The creator tool is available from the game engine preferences menu. The UX on that could use work, but given that, it makes some sense to have the tool bundled with the game. As is though it is odd since the tool is packaged separately, then downloaded, then invoked from within the game..

A map making tool suite I think is called for. Any objections if it is a stand-alone tool? Or should we bundle it with the game and improve the game menus so it is easier to find.

**Comment by DanVanAtta** [comment]
consolidated to #502
