### ISSUE TITLE
Use pure systemd instead of sysvinit "wrapper"

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3942]
Migrated from: https://github.com/triplea-game/infrastructure/issues/40

> Just a small note:
We currently use the service triplea-bot@<number> start|stop|restart|status etc. command to start and stop bots, however this is the "legacy" SysVinit syntax that is kept for backwards compatibility.
We should prefer the systemd syntax systemctl start|stop|restart|reload|status triplea-bot@<number> to be more consistent with all the other systemd related commands.
When changing this we should tell all the people having access (like prastle) about this

**Comment by prastle** [comment]
Just list the new on the forum gmail docs
np

**Comment by DanVanAtta** [comment]
@prastle pls check topic, I believe that is pertinent to password: https://github.com/triplea-game/triplea/issues/3827

**Comment by DanVanAtta** [comment]
This issue can be closed, with ansible for deployment the command used is transparent. This is only relevant when hand-running commands, ideally we'd be sure such commands are documented and be sure those documents are with the preferred syntax.

FYI / CC: @RoiEXLab
