### ISSUE TITLE
Decide & Document Url naming convention

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3954]
1. Decide on casing:

Choices:
- lower camel
- lower snake
- lower case with hyphens

**Comment by DanVanAtta** [comment]
Did a search for "url naming conventions" and checked out the top half dozen links. 

Looks like REST contexts can favor lower camel case, otherwise the SEO pages and naming conventions were pretty uniform to recommend hyphens:

lower camel:
- https://www.restapitutorial.com/lessons/restfulresourcenaming.html


Hyphens:
- https://www.searchenginejournal.com/seo-friendly-url-structure-2/202790/
- https://moz.com/blog/15-seo-best-practices-for-structuring-urls
- https://www.palantir.net/blog/palantirnets-guide-digital-governance-url-naming-conventions


I would recommend we adopt the convention to use hyphens as a word separator, otherwise all lower case and avoid symbols.

**Comment by ssoloff** [comment]
> lower case with hyphens

[kebab-case](https://en.wikipedia.org/wiki/Kebab_case)

**Comment by DanVanAtta** [comment]
Thanks! seems decided, I opened a PR to add this to the documentation.
