### ISSUE TITLE
Some air units missing part of their movement capacity

### ISSUE THREAD

**Issue by zlefin** [triplea-game/triplea#3955]
### Engine version

1.9.0.0.11715
### My Operating System
Windows 10 64-bit
### Map name
Middle Earth Battle for Arda   v2.0.6
### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Select the 18 eagles in Hornburg and try to move them to East Enmet (where the Oliphaunt is)

what's happening for me is that it only lets 7 of the eagles go to EAst Enmet.
doing some testing by trying alternate moves, 6 eagles can go anywhere, 1 has 4 moves, 7 have 2 moves, and 3 have 0 moves.  So some of the eagles available moves are simply missing somehow.  and since it's the start of my first move phase for the turn they should have all their movement available.

The bug that caused this may have occurred a bit earlier in the game;  at some point earlier I got an error, but I don't remember where, since it didn't seem to cause any actual problems at the time.  It might have involved accidentally issued move orders to some eagles while in Show History mode; which is odd cuz normally the game prevents you from doing that.

If I use edit mode to delete those eagles and place an equal amount of new ones, the new ones work fine.  So the damaged info must be stored in these particular eagle instances.
### Instead of this error, what should have happened?
All 18 eagles should have been able to move their full 8 moves.
### Any additional information that may help
I know you might not be able to figure out what caused this unless I can get catch the error when something first screwed up; that's fine.
[Arda_game_EagleMoveBug.zip](https://github.com/triplea-game/triplea/files/2343658/Arda_game_EagleMoveBug.zip)

**Comment by DanVanAtta** [comment]
I'm having a lot of trouble getting 1.9.0.0.11715 to run to debug this further. I'm afraid we may have to admit defeat on this one and hope to solve it the next time a similar issue is reported. This was a very good error report @zlefin , thank you for submitting it.
