### ISSUE TITLE
Version number in artifact name & Features we Support Policy Discussion

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3957]
For discussion and decision as a general convention:

Definition:
***Non-dev***: those who are interacting with tripleA outside of a source code perspective. This would be either end-users (players), people who keep the system running (infrastructure/SystemAdmins), those who are doing QA, or our community & lobby moderators.

1. If we do not have an actual requirement given by a non-dev, should we support it? Basically, if we have something that the dev's like, but nobody really is asking for it, should we delete it without second thought? If the answer is yes, and if we have never had a user ask us to put version number in artifact, then the rest of the conversation is moot and we should check on forum if anyone remembers needing/using this and if not we should drop it.

2. If the answer is that some dev use-cases are strong enough that we will support it just for that, is this an example of something we want to keep because it is that useful? Maybe the answer is yes, if we do remove the version number in artifact name then we would get two benefits:
 - remove a dependency in all project gradle files to not know anything about the version number (which comes from game-core properties file, so that coupling would be dropped)
 - remove one coupling in infrastructure, which needs to know how to lop off build number (or use slightly risky globbing work-around)

**Comment by prastle** [comment]
The experienced admin's and council can add their opinion on an item removal.  This of course would require any of them to read git hub.  Thus I would suggest you post any major changes in the admin section of the forum.  Just my two cents.  @DanVanAtta

**Comment by DanVanAtta** [comment]
@prastle indeed, the question here was if dev can give code requirements; never a question whether non-dev could provide requirements (and hence be involved in a removal). 

Pondering this, I don't think this is necessarily the right question to ask. Certainly there are elements which are needed between dev's, so the answer is pretty clearly yes. It's not really worth hashing out where on the spectrum that falls as we can use our judgement.

That leaves the technical debt that we do not handle version number very consistently. I suspect we'll get it resolved soon as we'll be working in that area, a project card perhaps is a good way to handle it.
