### ISSUE TITLE
Issue Label Descriptions

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3961]
Github launched a new feature to attach a description next to label  :yellow_heart: 

Please take a look, we could use some to be filled in and any improvements/clarifications are always welcome.

**Comment by ssoloff** [comment]
:+1: I don't think all labels need a description, as many are self-explanatory.  Our best ROI will be in ones like the **Production** and **PR** labels.  Especially the **Production** labels, where there was a lot of confusion in the past over whether **P0** or **P1** was more appropriate (current devs probably no longer have any confusion, but a new dev will have to repeat the learning curve).

**Comment by DanVanAtta** [comment]
Good points, it has been a goal to keep tweaking the names to be self-explanatory. 

For p0 and p1, I think we may still need a definition of when those apply.
