### ISSUE TITLE
Decide how to handle Reported Bugs

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3971]
For consideration in this issue is how we will handle user-submitted bug reports. The bug reporting feature will let users send us errors and/or one-off bug reports.  At question here is what will the http-server do with these reports.

Options:
A) use github API to create an issue
B) store the record in DB and create a front-end UI to view this data, add buttons to mark a report as read and another button to create an issue from the report.

**Comment by RoiEXLab** [comment]
Hmm, I'd be fine with a) which is far easier to do, with some strict rate limits.
I'd suggest adding a label or something to "auto-generated issues" to be able to filter them or filter them out.
