### ISSUE TITLE
Cannot load even/odd autosaves in bot

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/triplea#3977]
### Engine version

1.9.0.0.11823

### My Operating System

Linux localhost.localdomain 4.17.11-200.fc28.x86_64 <span>#</span>1 SMP Mon Jul 30 15:21:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)

* Connect to a bot.
* Click **Open Saved Game > Change To autosave_even** or **Open Saved Game > Change To autosave_odd**.
* Click **OK** when prompted to change to autosave.

### Do you have the exact error text? Please copy/paste if so

Nothing happens. The bot never loads the save game.

### Instead of this error, what should have happened?

The bot should load the selected save game.

### Any additional information that may help

This does not affect **Change To autosave** (and **Change To autosave2** appears to no longer be supported).

When playing within a bot, the vanilla autosave is saved to the configured save game folder (e.g. _~/triplea/savedGames_).  However, the even/odd autosaves are saved to the _autoSave_ folder under the configured save game folder.  If I move the even/odd autosaves up one folder, both commands work as expected.  Therefore, I suspect when the even/odd autosaves were changed to be saved to the _autoSave_ folder, the corresponding load code was not kept in sync.

Here's the code that generates the save:

https://github.com/triplea-game/triplea/blob/0ca4660599856d0c39b3f6ae000bb290d2b35d17/game-core/src/main/java/games/strategy/engine/framework/ServerGame.java#L442-L447

The `autoSave()` method always places the save game in the _autoSave_ folder:

https://github.com/triplea-game/triplea/blob/0ca4660599856d0c39b3f6ae000bb290d2b35d17/game-core/src/main/java/games/strategy/engine/framework/ServerGame.java#L351-L358

An easier fix may be to just restore the even/odd autosaves to the configured save game folder and not store them under _autoSave_.  I believe _autoSave_ was added to avoid a lot of clutter in the user's save game folder due to the new per-phase autosaves added last year.  As the even/odd autosaves use a constant filename, there will, at most, be two additional files in the user's save game folder.

**Comment by simon33-2** [comment]
I wouldn't like them to revert out of the autoSave folder though. Can't it look in the correct place?

**Comment by ssoloff** [comment]
@simon33-2 Just to be clear, my proposal above was to only move the _autosave_round_even.tsvg_ and _autosave_round_odd.tsvg_ files out of the _autoSave_ folder.  NOT all of the _autosaveBefore*.tsvg_ and _autosaveAfter*.tsvg_ files.

Regardless, I'm sure it's doable to get the bot to load the even/odd autosaves out of the _autoSave_ folder.  In that case, would you recommend that, for consistency, we move the legacy _autosave.tsvg_ file to that folder, as well?  (Actually, looking at the relevant code, we might have to do that to keep everything clean, otherwise we'll be switching on the `AUTOSAVE_TYPE` to decide which folder to use.)

**Comment by ssoloff** [comment]
@simon33-2 _autosave.tsvg_ is still created by a bot in the following scenarios:

* Bot game stopped remotely by a moderator.
* A player connection is lost during a bot game.
