### ISSUE TITLE
java.lang.NullPointerException on Ubuntu 18.04 using OpenJDK 10.0.2

### ISSUE THREAD

**Issue by fernandodiacenco** [triplea-game/triplea#3997]
Hello, this is a report of a issue probably caused by OpenJDK10 instead of TripleA, but I'm reporting anyway in the hopes of improving the game

When installing ubuntu 18.04, and using the default-jre package, it will install OpenJDK 10, trying to run TripleA with it causes the error described bellow. 

If this is a duplicate or irrelevant, I apologize and please ignore.

### Java Version
java --version
openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.1)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.1, mixed mode)

### Engine version
1.9.0.0.9687 and 1.9.0.0.11885

### My Operating System
Ubuntu 18.04

### Map name
Greyhawk Wars and Middle Earth - Battle for Arda

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Select the map, set all to fast ai, set one to human, start game and BOOM

### Do you have the exact error text? Please copy/paste if so
>set 08, 2018 7:10:37 PM games.strategy.engine.framework.GameRunner lambda$main$0
>GRAVE: null
> java.lang.NullPointerException
> 	at games.strategy.engine.data.UnitType.equals(UnitType.java:66)
> 	at java.base/java.util.HashMap.putVal(HashMap.java:635)
> 	at java.base/java.util.HashMap.put(HashMap.java:612)
> 	at java.base/java.util.HashSet.readObject(HashSet.java:342)
> 	at java.base/jdk.internal.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
> 	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1160)
> 	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2209)
> 	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2080)
> 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1587)
> 	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2348)
> 	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2242)
> 	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2080)
> 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1587)
> 	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
> 	at java.base/java.util.HashMap.readObject(HashMap.java:1465)
> 	at java.base/jdk.internal.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)

(This error loops a lot until reaching 620 lines)

### Instead of this error, what should have happened?
The game would run normally.

### Any additional information that may help
If you install Oracle JDK, everything runs fine

I suspect that if I install OpenJDK 8 instead of having OpenJDK 10, it would work normally, but I could not test it

Thank you.

**Comment by ssoloff** [comment]
@fernandodiacenco Thanks for taking the time to report this.

Currently, TripleA is only supported on Java 8.  The principal issue blocking us from moving to Java 9+ is #3274.  Please subscribe to that issue if you're interested in being notified when TripleA supports newer versions of Java.

In the meantime, closing this issue as a duplicate.
