### ISSUE TITLE
MetaPower in BattleCalc "easter egg"

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#403]
![hover_over_meta_power](https://cloud.githubusercontent.com/assets/12397753/12700513/525056a8-c79b-11e5-8a7f-47c8bcc07975.png)

Discovered an unadvertised feature, hovering over the 'firepower' text in the battle calc reveals the pop-up above.

Rather than have this be a bit of an easter egg, may I suggest we add 'meta power' as a first class element on the battle cacl UI, and show just the formula on hover.

**Comment by ron-murhammer** [comment]
@DanVanAtta I'm fine with that. That is essentially the formula the FastAI is currently based on as well.
