### ISSUE TITLE
Gradle from Ant - Testing and Questions

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#405]
@ron-murhammer  you indicated that you didn't think the gradle build has yet been tested and proven.

Note, we made two switches, Ant to Gradle, and makensis to install4j. Before install4j, there wasn't even a mac installer, nor a linux installer.

The transition to gradle is proven. The output requirements of gradle we have tested and verified it matches what Ant used to do. Namely, it builds the all platforms zip, and calls the install4j builder (before we called the makensis builder).

Install4j is not yet proven. That is largely because we are adding so many features by using that new installer. As mentioned,  the mac and linux installers are brand new.

So, @ron-murhammer  do you have any concerns remaining about the gradle build not being tested or proven? Let's get those hammered out.

**Comment by ron-murhammer** [comment]
@DanVanAtta No specific concerns other than that it works when we release it to the masses.

**Comment by DanVanAtta** [comment]
Thanks, hopefully that clears up Ant vs gradle vs install4j vs makensis. The gradle piece is actually REALLY well tested at this point.
