### ISSUE TITLE
Can't run sudo journalctl as admin user

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/triplea#4071]
I tried running `sudo journalctl -f` as the `admin` user on host `bot35_frankfurt_de` and was prompted to enter a password.  According to _admin_user.sh_, `journalctl` should be a permitted `sudo` command without a password:

https://github.com/triplea-game/infrastructure/blob/7b1df339f2c26cedf4141c61e6d89d39ca97d708/root/tasks/admin_user.sh#L41

I think the problem may be that the path to `journalctl` is incorrect.  On the above host, it is located at _/bin/journalctl_.

**Comment by prastle** [comment]
yes sir
now you understand all my yelling :) @ssoloff ssoloft

**Comment by prastle** [comment]
none of them should prompt password for any of the old commands except they do now

**Comment by DanVanAtta** [comment]
@prastle are you referring to SSH login, are you able to get logged in to servers to begin with?

For journalctl a work-around would be to use papertrail.

@ssoloff adding the additional path seems correct. The 'grep -E' is used to make sure that an entry is not repeatedly added if already present. If we add a second entry the regex used would need to be made more specific.

**Comment by prastle** [comment]
@DanVanAtta  Yes I still can ssh to them.

**Comment by DanVanAtta** [comment]
After next merge to the infrastructure prod branch, admin will have sudo access for any command.
