### ISSUE TITLE
Return root Services to Admin function from Infra

### ISSUE THREAD

**Issue by prastle** [triplea-game/triplea#4072]
In the old days updating the Bot Servers could be done individualized.  The new infra as you guys discovered requires complete shutdown …. Bad Idea
  I would recommend we somehow add sudo services to admin (needs root for server to add new engine) or invent a way for Infra to allow singular shut down of servers while the rest run.  Old days meant I could empty and shut down a bot server and upgrade it.  Now we cannot.  The Lobby needs to stay dev only.  Just my two cents.  Infra works great for updating maps but has failed for the rest of its purpose.  To eliminate work.  You guys did more work last night than I ever did :) and my only complaint about the old structure was why can't anyone else help update.  Just my two cents.

**Comment by prastle** [comment]
In the old days updating the Bot Servers could be done individualized.  The new infra as you guys discovered requires complete shutdown …. Bad Idea
  I would recommend we somehow add sudo services to admin (needs root for server to add new engine) or invent a way for Infra to allow singular shut down of servers while the rest run.  Old days meant I could empty and shut down a bot server and upgrade new we cannot.  Lobby needs to stay dev only.  Just my two cents.  Infra works great for updating maps but has failed for the rest of its purpose.  To eliminate work.  You guys did more work last night than I ever did :) and my only complaint about the old structure was why can't anyone else help update.  Just my two cents.

**Comment by DanVanAtta** [comment]
> In the old days updating the Bot Servers could be done individualized. 

That can still be done. 


>  The new infra as you guys discovered requires complete shutdown

It does not, updates are installed but new versions do not take effect until a restart is manually triggered.

> Old days meant I could empty and shut down a bot server and upgrade it. Now we cannot

The intent is for prod bots to stay uniform, pre-prod is for testing new versions. We can can control individual bots to be on new versions regardless by updating the prod version, and then restarting the bot servers that we want by logging in to the machine and then as admin run:
```
sudo service restart triplea-bot@0x
```
(where x is the bot number, 01-0n, eg: `sudo service restart triplea-bot@02` )

**Comment by prastle** [comment]
Ok maybe they did not realize that it still worked and just did it all at once.  @DanVanAtta   either way it means only you for can do an update by approving the infra pr.  Which needs to be updated again to at least .12102 for the turn order fixes. @DanVanAtta

**Comment by DanVanAtta** [comment]
> @DanVanAtta either way it means only you four can do an update by approving the infra pr. 

That can't be correct as PRs were getting merged without me, the same people with write access for triplea-game have it for infra.

> Which needs to be updated again to at least .12102 for the turn order fixes. @DanVanAtta

I can see that. We've made a quick mess already by letting the test server crash and burn which introduced delays to merging to prod. The more frequently we merge to prod (eg: deploy), the better in many ways, many problems get fixed that way. On the other hand when we have months go by and then do things not quite the right way, it takes a bit first to untangle the knot we are in.

**Comment by DanVanAtta** [comment]
@prastle any more questions I can help with?

**Comment by prastle** [comment]
@ron-murhammer  updated here and I get the process now.  Thanks! 
https://github.com/triplea-game/infrastructure/pull/142/files
Feel free to close this.
