### ISSUE TITLE
Testing the infrastructure

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4076]
Infrastructure is driven by the cronjob one-liner that removes the old infrastructure clone, clones a fresh copy, and then executes an entry point script. The intent here is that this line stays pretty simple and is universal on all machines

Ways to test:
- cronjob expression can executed directly on the CLI. So you can log in to a machine and `crontab -l` and then copy/paste run it. (of note there are logs dropped on the file system, so they can be looked at for reference)
- the cronjob expression controls what is cloned, instead of cloning the master branch it can be hand-changed on a test machine to be an arbitrary fork/branch. The cronjob script is not altered by the automation so that update would remain. 

A docker setup should be very possible. Instead of cloning a repo we just need to invoke the update script from local file path where we have a live copy of the infrastructure repo. For code changes, if the docker host name can be fixed, then we would only need to add that to be aliased and handled the same as the prerelease machine

When it comes to testing specific components/tasks:
- the install files/modules are driven by a main driver script in each role folder, eg: 
  - https://github.com/triplea-game/infrastructure/blob/master/roles/lobby/lobby.sh
  - https://github.com/triplea-game/infrastructure/blob/master/roles/bot/bot.sh

For development or debug, those scripts can be invoked directly as well.  

@ssoloff @ron-murhammer ;    I'll see about trying to get these notes together for some documentation, but for now it seems like this will be useful information. I'm happy to answer questions or give more details. I'd be interested to discuss as well future directions, for example automating a local test with a docker setup. I think it would be a good path for live system tests that we could start building to replace our manual QA efforts. The kinds of tested executed there need to be carefully designed, I think those would be mostly smoke tests and compatibility checks.

**Comment by DanVanAtta** [comment]
Any thoughts @ssoloff , does that answer some questions on testing? Would you be interested to help set up a docker for local testing? If not, no worries, i can add it as an item on my backlog.

**Comment by ron-murhammer** [comment]
@DanVanAtta Personally, I don't really want to test changes locally but rather use the staging lobby/bots or just a small subset of the production bots. Problem is its not really clear on how to do that as things sit now. 

Examples:
- When trying to update the bots to the new stable, it would have been ideal to do this in the staging lobby first as then we would have caught the error of updating the wrong version number
- We now want to do a rolling update of bots to 12102 for the player ordering fix but it isn't clear how to test or do it with the artifact rename changes

**Comment by ssoloff** [comment]
> Would you be interested to help set up a docker for local testing?

@DanVanAtta I've been planning on setting up Docker images for the lobby and bots for a while to make them easier to deploy (not a full infra solution, but a step in the right direction, IMO).  I was waiting to get the `lobby`, `game-headed`, and `game-headless` projects teased apart from `game-core` before looking at Dockerization.  Now that those subprojects and their artifacts are stable, I can start looking into it, but it probably won't be complete any time soon.

**Comment by RoiEXLab** [comment]
Not really into docker containers, but google's new [jib project seems to make it pretty easy to create containers without too much work](https://github.com/GoogleContainerTools/jib/tree/master/jib-gradle-plugin#quickstart).
It's still in beta, but it looks promising.
Of course the lobby needs some additional configuration regarding the database, but this could already give the needed head-start

**Comment by DanVanAtta** [comment]
> @DanVanAtta Personally, I don't really want to test changes locally but rather use the staging lobby/bots or just a small subset of the production bots. Problem is its not really clear on how to do that as things sit now.

@ron-murhammer  Merges to master are automatically deployed to the prerelease server. The idea is that there would be no merges to prod directly, to master first, verifies on prerelease, then an explicit merge to prod to promote the deployment, and then an explicit restart of services on prod-only to complete the update.

> @DanVanAtta I've been planning on setting up Docker images for the lobby and bots for a while to make them easier to deploy (not a full infra solution, but a step in the right direction, IMO)

@ssoloff  Let's coordinate on this. If infra is deploying those components then we do not need another way to do so. At same time there are places I think in testing that would be useful to have those docker images.

> Not really into docker containers, but google's new jib project seems to make it pretty easy to create containers without too much work.

@RoiEXLab agree jlib looks interesting, but, infra does a lot of things:
- installs ssh keys
- configures OS to have apt packages and turns off passwd
- installs papertrail key
- adds monitioring/metrics
- app, which can be DB. 

With that said, I could imagine infra using jlib for the last mile when running  java apps, perhaps instead of docker. The immediate artifact in question is perhaps a docker container to emulate a linux server that would then be running jlib. Because that container may not necessarily have anything to do with a gradle build file, for example the DB component, jlib would not quite fit for that purpose
