### ISSUE TITLE
All existing network functionality

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#4084]
This is a compiled list of all the features that would need to be implemented when creating a new REST/Websocket-based controller system.

If a feature is tagged as REST, this doesn't necessarily mean it should be implemented using a REST API, but it could be done

IChatController:
  - joinChat (websocket)
  - leaveChat (websocket)

IStatusController:
  - setStatus (REST)
  - getAllStatus (REST)

IGameStepAdvancer:
  - startPlayerStep (websocket)

IServerRemote:
  - getSavedGame (REST)

IServerReady:
  - clientReady (REST)

IObserverWaitingToJoin:
  - joinGame (websocket)
  - ~cannotJoinGame~ (should be joined into the joinGame functionality)

IServerStartupRemote:
  - getPlayerListing (REST)
  - takePlayer (REST)
  - releasePlayer (REST)
  - disablePlayer (REST)
  - enablePlayer (REST)
  - isGameStarted (REST)
  - ~getIsServerHeadless~ (redundant, should always return true)
  - getAvailableGames (REST)
  - changeServerGameTo (REST)
  - changeToLatestAutosave (REST)
  - changeToGameSave (REST)
  - getSaveGame (REST)
  - getGameOptions (REST)
  - changeToGameOptions (REST)

IRemotePlayer:
  - getPlayerId (REST?, though not 100% sure this is needed when structuring the classes properly)

IRandomStats:
  - getRandomStats (REST)

IRemoteRandom:
  - ~generate~
  - ~verifyNumbers~
  - [showResults] (websocket, the clients shoudn't query the dice results, the server should send it to all of them using wss, so integrity is guaranteed)

ILobbyGameController:
  - postGame (REST)
  - updateGame (REST, but could be combined with postGame)
  - listGames (REST)
  - testGame (uneccessary, we could simply use another functionality to test if the service is reachable)

IModeratorController:
  - boot (REST)
  - banUsername (REST)
  - banMac (REST)
  - muteUsername (REST)
  - muteMac (REST)
  - getHostConnections (REST)
  - getChatLogHeadlessHostBot (REST)
  - mutePlayerHeadlessHostBot (REST)
  - bootPlayerHeadlessHostBot (REST)
  - banPlayerHeadlessHostBot (REST)
  - stopGameHeadlessHostBot (REST)
  - shutDownHeadlessHostBot (REST)
  - getHeadlessHostBotSalt (REST)
  - getInformationOn (REST)
  - isAdmin (REST, this tests if the current user is admin, we should know this when logging in, or find out using isPlayerAdmin)
  - isPlayerAdmin (REST)

IRemoteHostUtils (special case, if the lobby is supposed to be accepting requests only (and not creating them), websocket, because a moderator could stop a bot at any time, and this feedback could then be routed back to the game server at any time, otherwise the game server must somehow be able to verify the request came from the lobby, but REST would also work in this case):
  - getConnections
  - getChatLogHeadlessHostBot
  - mutePlayerHeadlessHostBot
  - bootPlayerHeadlessHostBot
  - banPlayerHeadlessHostBot
  - stopGameHeadlessHostBot
  - shutDownHeadlessHostBot
  - getSalt

IUserManager:
  - updateUser (REST)
  - getUserInfo (REST)

*Delegate (all websocket, even if some of them could be done via REST, we need at least a single websocket that sends the clients the most recent changes)

If you have any suggestions, please post them here, I'll update the list accordingly.

Unassign yourselves please, if you read this and have no further comments

**Comment by ssoloff** [comment]
@RoiEXLab Wow, even if we don't change the network transport, this alone is a great compilation of information about the system. :+1:

I didn't see any network functionality you missed, nor do I disagree with any of your websocket/REST classifications.  However, I suspect some changes will be inevitable when you actually hit the battlefield. :smile:

**Comment by ron-murhammer** [comment]
Looks pretty good to me. Definitely a great outline.

**Comment by prastle** [comment]
I WISH I COULD GROK
:)
