### ISSUE TITLE
Re-syncing prod infrastructure

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4087]
To fix the drift of the prod vs master branch in infrastructure, I'm thinking to force push a removal of the last 'n' commits that were not merged to master first.

**Comment by ron-murhammer** [comment]
Pretty sure that will break a lot of stuff and restart the lobby/bots.

**Comment by RoiEXLab** [comment]
I'd simply merge prod into master, and then force-reset prod to master or the other way round.
However you'd need to temporarily disable the "protected branch" setting because it prevents force pushing

**Comment by DanVanAtta** [comment]
We do need [4206ed](https://github.com/triplea-game/infrastructure/commit/4206ed5dc4cd3f660f2affe0adc588d07342b5f5), and that is not on 'prod' yet.

> I'd simply merge prod into master, and then force-reset prod to master or the other way round.

'prod' merges to master is the wrong way for things to flow. But the force-reset is the right idea, a force reset of master to prod would pick up the latest changes and remove the cherry-picks. 

Currently there are conflicts merge to prod from master. So the force-reset would fix that, but the existence of conflicts means we're off cadence, there should never be a conflict merging master to prod because prod should never change unless it gets an update from master.

I think the next steps are going to be to fix the prerelease server then force-reset prod branch to match master.

**Comment by DanVanAtta** [comment]
This is done now that we've had a merge to prod and can do so again without merge conflicts.
