### ISSUE TITLE
If bots lock up... Plan of Action

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4094]
If bots lock up again, I would propose:
1. Open a new github issue
1. Get a thread dump, post it to the issue
1. Restart the bot

If agreed to, let's look up the command to run a thread dump, or agree that we'll do that when we need to before any bots are restarted.

**Comment by prastle** [comment]
Lovely idea
what is the sudo script for a thread dump?
@DanVanAtta

**Comment by prastle** [comment]
Since #1 and #3 I already did

**Comment by prastle** [comment]
@DanVanAtta @RoiEXLab @ron-murhammer @ssoloff 
We have MIA bots again!  What is the thread dump command?

**Comment by prastle** [comment]
306, 401,404,406,406,503,505,602,604

**Comment by DanVanAtta** [comment]
@prastle next time please leave a few of the bot machines in the frozen state.

**Comment by prastle** [comment]
@DanVanAtta We did in the other thread and @ssoloff tried with thread dump.

**Comment by prastle** [comment]
To be clear two servers the second time were left alone for almost 24 hrs
