### ISSUE TITLE
AbstractAction lambda refactor

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#410]
There is a lot of code around creating "AbstractAction" objects, with a lot of syntax. This does look like a good opportunity to use a functional interface plus a builder class to cut down on the syntax, which will allow us to create AbstractActions pretty easily with lambda expressions.

Below are two examples, A and B of what some code would like before and after. Finally is the infrastructure code that would allow for this, notably the Functional Interface and the proposed new builder class 'SwingAction'

### Before:
```
final AbstractAction optionsAction = new AbstractAction("Show Who is Who...") {
   private static final long serialVersionUID = 5687214685515140202L;
      @Override
       public void actionPerformed(final ActionEvent e) {
         PlayersPanel.showPlayers(getGame(), m_frame);
      }
   };
   menuGame.add(optionsAction);
```

### After:
```
final AbstractAction optionsAction = SwingAction.of("Show Who is Who...", e -> {
         PlayersPanel.showPlayers(getGame(), m_frame);
 });
 menuGame.add(optionsAction);
```

### Before:
```
    m_leaveGame.addActionListener(new AbstractAction() {
      private static final long serialVersionUID = 699780405180654825L;

      @Override
      public void actionPerformed(final ActionEvent e) {
        leaveGame();
      }
    });
```

### After:
```
m_leaveGame.addActionListener(SwingAction.of( e -> leaveGame() ));
```

## Code infrastructure to allow the refactor

Here we create an AbstractAction builder class that accepts a functional interface parameter. 

```
@FunctionalInterface
public interface SwingActionFunction {
 public void doStuff(ActionEvent e);
}

public class SwingAction {
  
  
  public static AbstractAction of(final String name, final SwingActionFunction swingAction) {
    return new AbstractAction(name) {
      private static final long serialVersionUID = 1L;

      @Override
      public void actionPerformed(ActionEvent e) {
        swingAction.doStuff(e);
      }
    };
  }
  
  public static AbstractAction of(final SwingActionFunction swingAction) {
    return new AbstractAction() {
      private static final long serialVersionUID = 12331L;

      @Override
      public void actionPerformed(ActionEvent e) {
        swingAction.doStuff(e);
      }
    };
  }

}
```

### For further consideration, can be cleaned up more

Perhaps a bit up for debate, we could go one step further since most abstract actions do not actually need the `ActionEvent` object. So we could get rid of the "e" parameter with a third "of" handler:

```

  public static AbstractAction of(final Consumer consumer) {
    return new AbstractAction() {
      private static final long serialVersionUID = 331L;

      @Override
      public void actionPerformed(ActionEvent e) {
        consumer .accept(e);
      }
    };
  }
```

This would allow:
```
m_leaveGame.addActionListener(SwingAction.of( () -> leaveGame() ));
```

**Comment by ron-murhammer** [comment]
Yes. Honestly, this is a case where I think lambdas really shine. Both example A and B are better with lambdas and the infrastructure code is fairly straightforward. I think as long as you have say more than 3 instances of creating AbstractAction's like that then this is pretty much a no brainer.

I actually don't like the additional step as the notation of using "() ->" just seems weird. Adding extra parenthesis actually sort of makes it harder to read.

**Comment by DanVanAtta** [comment]
PR #439 adds a new SwingAction class and updates a god number of the existing examples of  'new AbstractAction...'
