### ISSUE TITLE
Invalid XML Ending in Colon Causing Domination_1914_Blood_And_Steel Parsing Failure

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#4112]
Sep 27 00:13:54 bot35_frankfurt_de run_bot.sh: SEVERE: Exception while parsing: jar:file:/home/triplea/maps/domination_1914_blood_and_steel-master.zip!/domination_1914_blood_and_steel-master/map/games/Domination_1914_Blood_And_Steel.xml
Sep 27 00:13:54 bot35_frankfurt_de run_bot.sh: games.strategy.engine.data.GameParseException: map name: 'jar:file:/home/triplea/maps/domination_1914_blood_and_steel-master.zip!/domination_1914_blood_and_steel-master/map/games/Domination_1914_Blood_And_Steel.xml', game name: 'Domination_1914_Blood_And_Steel', Unexpected Exception while setting values for attachmentTriggerAttachment attached to:PlayerID named:Bolsheviks with name:triggerAttachment_October_Revolution
Sep 27 00:13:54 bot35_frankfurt_de run_bot.sh: #011at games.strategy.engine.data.GameParser.newGameParseException(GameParser.java:108)
Sep 27 00:13:54 bot35_frankfurt_de run_bot.sh: #011at games.strategy.engine.data.GameParser.setValues(GameParser.java:1269)
Sep 27 00:13:54 bot35_frankfurt_de run_bot.sh: #011at games.strategy.engine.data.GameParser.parseAttachments(GameParser.java:1219)
Sep 27 00:13:54 bot35_frankfurt_de run_bot.sh: #011at games.strategy.engine.data.GameParser.parseMapDetails(GameParser.java:200)
Sep 27 00:13:54 bot35_frankfurt_de run_bot.sh: #011at games.strategy.engine.data.GameParser.parse(GameParser.java:97)
Sep 27 00:13:54 bot35_frankfurt_de run_bot.sh: #011at games.strategy.engine.data.GameParser.parse(GameParser.java:91)
Sep 27 00:13:54 bot35_frankfurt_de run_bot.sh: #011at games.strategy.engine.framework.headlessGameServer.AvailableGames.addToAvailableGames(AvailableGames.java:117)
Sep 27 00:13:54 bot35_frankfurt_de run_bot.sh: #011at games.strategy.engine.framework.headlessGameServer.AvailableGames.populateFromZip(AvailableGames.java:93)
Sep 27 00:13:54 bot35_frankfurt_de run_bot.sh: #011at games.strategy.engine.framework.headlessGameServer.AvailableGames.lambda$newGameRepository$0(AvailableGames.java:62)
Sep 27 00:13:54 bot35_frankfurt_de run_bot.sh: #011at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
Sep 27 00:13:54 bot35_frankfurt_de run_bot.sh: #011at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
Sep 27 00:13:54 bot35_frankfurt_de run_bot.sh: #011at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
Sep 27 00:13:54 bot35_frankfurt_de run_bot.sh: #011at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
Sep 27 00:13:54 bot35_frankfurt_de run_bot.sh: #011at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
Sep 27 00:13:54 bot35_frankfurt_de run_bot.sh: #011at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
Sep 27 00:13:54 bot35_frankfurt_de run_bot.sh: #011at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1870)
Sep 27 00:13:54 bot35_frankfurt_de run_bot.sh: #011at java.util.concurrent.ForkJoinPool.externalHelpComplete(ForkJoinPool.java:2467)
Sep 27 00:13:54 bot35_frankfurt_de run_bot.sh: #011at java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:324)
Sep 27 00:13:54 bot35_frankfurt_de run_bot.sh: #011at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:405)
Sep 27 00:13:54 bot35_frankfurt_de run_bot.sh: #011at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
Sep 27 00:13:54 bot35_frankfurt_de run_bot.sh: #011at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
Sep 27 00:13:54 bot35_frankfurt_de run_bot.sh: #011at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
Sep 27 00:13:54 bot35_frankfurt_de run_bot.sh: #011at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
Sep 27 00:13:54 bot35_frankfurt_de run_bot.sh: #011at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
Sep 27 00:13:54 bot35_frankfurt_de run_bot.sh: #011at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
Sep 27 00:13:54 bot35_frankfurt_de run_bot.sh: #011at games.strategy.engine.framework.headlessGameServer.AvailableGames.newGameRepository(AvailableGames.java:58)
Sep 27 00:13:54 bot35_frankfurt_de run_bot.sh: #011at games.strategy.engine.framework.headlessGameServer.AvailableGames.<init>(AvailableGames.java:43)
Sep 27 00:13:54 bot35_frankfurt_de run_bot.sh: #011at games.strategy.engine.framework.headlessGameServer.HeadlessGameServer.<init>(HeadlessGameServer.java:64)
Sep 27 00:13:54 bot35_frankfurt_de run_bot.sh: #011at games.strategy.engine.framework.headlessGameServer.HeadlessGameServer.start(HeadlessGameServer.java:557)
Sep 27 00:13:54 bot35_frankfurt_de run_bot.sh: #011at org.triplea.game.server.HeadlessGameRunner.main(HeadlessGameRunner.java:16)
Sep 27 00:13:54 bot35_frankfurt_de run_bot.sh: Caused by: games.strategy.engine.data.MutableProperty$InvalidValueException: failed to set string property value to 'St. Petersburg:infantry:infantry:infantry:infantry:infantry:infantry:infantry:infantry:infantry:infantry:infantry:infantry:infantry:infantry:infantry:infantry:infantry:infantry:infantry:infantry:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:gas:'

**Comment by ron-murhammer** [comment]
Fix via https://github.com/triplea-maps/domination_1914_blood_and_steel/pull/3

**Comment by ssoloff** [comment]
Thanks for fixing, @ron-murhammer.
