### ISSUE TITLE
Integ Tests fail out of the box

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4130]
Running `./gradlew check`, out of the box eventually gives:

> Task :lobby:integTest FAILED

Request here is that we do not get such a failure, the checks would instead complete. Part of this request is not to reduce test coverage and to keep parity between what travis would run and what is run via local gradle.

Task:
- suggest approaches that seem reasonable
- volunteer to implement

(side note: as recently mentioned by @RoiEXLab in another issue regarding potential use of jlib; this might be an opportunity, if gradle integrates with a docker easily enough then perhaps we can launch a container for the DB and then run the integration tests)

**Comment by DanVanAtta** [comment]
The updates to lobby-db docker makes this all a lot easier.

**Comment by prastle** [comment]
Off topic but do we need a piger papertrail plan? @DanVanAtta
