### ISSUE TITLE
https://forums.triplea-game.org/topic/1027/display-players-information-does-not-display-aliases

### ISSUE THREAD

**Issue by prastle** [triplea-game/triplea#4134]
Please view the link in the forum.

https://forums.triplea-game.org/topic/1027/display-players-information-does-not-display-aliases

**Comment by DanVanAtta** [comment]
@prastle seems resolved, can you confirm there is nothing outstanding?

**Comment by prastle** [comment]
I think the real fix needed is for it to show aliases even if they have left.  I guess that is a separate pr? @DanVanAtta   Close this if you wish and create a pr fixing that I guess.  It should be discussed in the bunker tho I believe.

**Comment by DanVanAtta** [comment]
It sounds like we'll track this in the bunker thread.
