### ISSUE TITLE
Infrastructure needs to clean up old builds

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/triplea#4145]
Follow-up to #3828.

The infrastructure scripts need to automatically clean up old builds to avoid running out of disk space.  This is particularly important for the `PreRelease` server that may deploy several builds per day.

**Comment by DanVanAtta** [comment]
https://github.com/triplea-game/infrastructure/pull/151/ should address this. 

Prod has an interesting issue where it can be a bit more difficult to know the current running and *not* clean that file up. For now at least pre-prod can clean old installs easily enough while it is restarting to bring up the new one.
