### ISSUE TITLE
speeding up build @ validate yaml

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4154]
The validate yaml step takes a pretty solid 10s, and it's the first thing run on a gradle check. The step also takes 10s every time instead of doing an incremental on just the things that have not been validated.

Any  ideas/thoughts how to speed it up? 

To describe the problem in more detail, for example if testing out a property and a failing test, running the build i wait 11s for the validateyaml, then the incremental gradle test build kicks in and it's 1s to see output. The validate yaml delays this feedback by 11s each time.

So just re-ordering the task or making it travis only are really good options IMO. I want to be sure there are not other ideas before I move this gradle task to travis only.

**Comment by DanVanAtta** [comment]
To describe the problem in more detail, for example if testing out a property and a failing test, running the build i wait 11s for the validateyaml, then the incremental gradle test build kicks in and it's 1s to see output. The validate yaml delays this feedback by 11s each time.

So just re-ordering the task or making it travis only are really good options IMO. I want to be sure there are not other ideas before I move this gradle task to travis only.

**Comment by ssoloff** [comment]
I usually run `./gradlew check -x validateYamls` locally.

**Comment by RoiEXLab** [comment]
@DanVanAtta You can also add the `--parallel` flag to have this task running in parallel with everything else.

**Comment by DanVanAtta** [comment]
Those responses were both helpful. 

I wonder if we should create a 'dev recipe book' in the documentation to capture typical work flows.
