### ISSUE TITLE
New lobby replacement/features - Dev Design & Coordination

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4155]
For dev coordination and discussion, some design notes & initial requirements for lobby replacement, http-lobby:
- I'm planning for http lobby to acquire more features and eventually replace good chunks if not all of lobby project. We still need to see what websockets will look like before we can really plan for how lobby project would be completely replaced.
- keeping the two modules, lobby and http-lobby independent so that the deployment concerns do not overlap and to keep a hard split between new and old.
- http server tech not fully vetted, regardless keeping our modules designed to be independent of an http layer should lend to good overall design
- JDBC code does not scale well, notably when it comes to testing it and then later coming back and making modifications. I'll be looking to do a clean replacement of this code. Notably, I expect match-challenges to add a number of tables, so there is motivation to improve the scaling.
- convincing test coverage
- initial phases looking for patterns that will scale well to many features. 
- not worried about API versioning for right now. Eventually, plan this to be handled where needed with version parameters or application load balancers.

**Comment by RoiEXLab** [comment]
Because you're mentioning `http-lobby`.
This module doesn't exist yet, any plans on creating it?
Also do we want to base the database scheme off the current scheme? 
This would make migration a lot easier.

**Comment by DanVanAtta** [comment]
Sorry, `http-server` instead of `http-lobby`

> Also do we want to base the database scheme off the current scheme?

Two schemas could get difficult to manage. Keeping the tables partitioned should work or sticking to backward compatible updates.

**Comment by DanVanAtta** [comment]
@RoiEXLab To be explicit, I was thinking for now keeping the same DB; in part to help with replacing and migrating lobby code and simplicity.

There is a question/decision of how to structure the servers. Do we drop web-socket capability into 'http-server', in which case it should be named something else? Does the web-socket server become it's own sub-project and executable?

I've been wondering if it's worthwhile to move the server logic to it's own sub-project so that it would then be a 'jar' dependency to the http server and/or websocket server.
