### ISSUE TITLE
Factory method naming convention

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/triplea#4159]
During the review of #4158, it was noted that we use two different conventions for naming factory methods almost evenly:

* `createXXX()`: 48%
* `newXXX()`: 52%

Item 1 of _Effective Java, Third Edition_ discusses factory method naming conventions.  Here's Bloch's summary of some common names:

* `from`: A type-conversion method that takes a single parameter and returns a corresponding instance of this type.
* `of`: An aggregation method that takes multiple parameters and returns an instance of this type that incorporates them.
* `valueOf`: A more verbose alternative to `from` and `of`.
* `instance` or `getInstance`: Returns an instance that is described by its parameters (if any) but cannot be said to have the same value.
* `create` or `newInstance`: Like `instance` or `getInstance`, except that the method guarantees that each call returns a new instance.
* <tt>get<i><b>Type</b></i></tt>: Like `getInstance`, but used if the factory method is in a different class. **_Type_** is the type of object returned by the factory method.
* <tt>new<i><b>Type</b></i></tt>: Like `newInstance`, but used if the factory method is in a different class. **_Type_** is the type of object returned by the factory method.
* <tt><i><b>type</b></i></tt>: A concise alternative to <tt>get<i><b>Type</b></i></tt> and <tt>new<i><b>Type</b></i></tt>.

Please vote for either `createXXX()` or `newXXX()` going forward.

<hr>

**EDIT:** A bit of a clarification...  A factory method does not include methods whose return type is `void`.  There are several other methods in the code named `createXXX()` not included in the above statistics because they have a `void` return type.  These types of methods are typically used in our code in UI classes to create subordinate components of a panel, dialog, or some other container.  In those cases, the `create` prefix is perfectly acceptable, and I'd even argue that a `new` prefix would be completely misleading.

**Comment by RoiEXLab** [comment]
Honestly, I really don't care if I'm writing new or create as first word in a method.
Pretty neutral on this one, however a convention would be convenient because I'm asking myself this question every time

**Comment by ssoloff** [comment]
@RoiEXLab Same here.  It doesn't really matter which one we choose as long as we're consistent.  So flip a coin. :smile:

**Comment by DanVanAtta** [comment]
weak preference here for 'new':
- it's shorter
- mirrors the 'new' operator, `new MyClass()` and `newMyClass()`
- IMO reads  a bit better

**Comment by ron-murhammer** [comment]
I'm fine with new as that seems to be the majority here. Consistency is what matters most to me. Guess I'm just not quite used to using new yet.

**Comment by ssoloff** [comment]
Thanks, everyone, for the feedback.  I documented the chosen convention in #4191.
