### ISSUE TITLE
Victory conditions not working

### ISSUE THREAD

**Issue by jonpfl** [triplea-game/triplea#4165]
### Engine version
1.9.0.0.9687

### My Operating System
Window 10 64 bit

### Map name
World War II Global 1942 2nd Edition

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Japan went an entire turn of owning 6 Pacific cities and it didn't saw I won

### Instead of this error, what should have happened?

[triplea_Rus8.zip](https://github.com/triplea-game/triplea/files/2457868/triplea_Rus8.zip)

**Comment by jonpfl** [comment]
Actually, my friend said it did announce for him, I must have missed it.

Sorry!!

**Comment by ssoloff** [comment]
@jonpfl As was pointed out in the [forum](https://forums.triplea-game.org/topic/1051/global-1942-victory-condition-bug), the history indicates the victory condition was triggered at the end of round 7:

> Players: Germans, Italians and Japanese have just won the game, with this victory: <body>The Axis achieve victory by controlling 8 Europe VCs or 6 Pacific VCs and keeping control of one of their own capitals!</body>

Your previous comment seems to indicate this was simply a misunderstanding.  Just want to confirm that's the case before closing this issue.
