### ISSUE TITLE
Convert Java 9 Labels to Project?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4169]
Looking at the labels, these look like they would be better as projects:

- Java 9+ Blocker (2 issues)
Prevents running the application on Java 9+ 

- Java 9+ Deprecation (1 issue)
Caused by a deprecated feature in Java 9+ but does not currently block migration to Java 9+

One benefit of a project is that we can get task boards (eg: https://github.com/triplea-game/triplea/projects/4), and quick notes can be added so not everyone needs to be tracked in issues (and we can keep our existing more focused)

Thoughts? Keep as labels, switch to a project? Switching to a project would mean creating a project and then swapping the label for the project tag.

**Comment by RoiEXLab** [comment]
Neutral, with a slight tendency towards project because it looks cool ^^

**Comment by DanVanAtta** [comment]
Cool - I created a Java9 project with basic kanban board: https://github.com/triplea-game/triplea/projects/7. The Java9 labels were replaced with the project link and the labels are now deleted.
