### ISSUE TITLE
Bot Autosaves go missing.

### ISSUE THREAD

**Issue by prastle** [triplea-game/triplea#4171]
It has often been noticed that a bot's auto save can supposedly disappear.  I personally think it gets lost when the game locks up.  Or someone inadvertently loads the wrong save file.  Either way it would be nice (if possible)  to have players playing in bots to receive the auto save file just as if they were hosting.  Another thought is (if possible)  for them to receive all the saves in the new auto save folder.

**Comment by simon33-2** [comment]
Ok, so if I kill I client connected to the bot, I can successfully load the autosave from the Bot. Once you've done that, you can save it locally. Presumably you can also get the odd/even round autosaves too.

Is the problem when you do something which removes the autosave before you can grab it or something else?

Sounds like you aren't sure so you're suggesting that the autosaves are saved for a longer period and/or in a more accessible place. If the Bot locks up, then there would be no autosave from that point but providing you are the first on to the bot when it is recovered you should at least be able to get the odd/even one. That proviso is a pretty big one so that's why you're suggesting it be saved in a different place? Is that the requirement?

**Comment by simon33-2** [comment]
I'm pretty sure those saves would be created but no mechanism has been provided to load them. I would agree that is not optimal.

**Comment by simon33-2** [comment]
I'm having a look at this and it may not be as difficult as I feared. Just one question. Does each bot have its own directory for storing autoSaves or do several of them mash in together?

**Comment by ssoloff** [comment]
> Does each bot have its own directory for storing autoSaves or do several of them mash in together?

@simon33-2 I believe all bots share the same folder, but the auto-saves are prefixed with the bot name so they don't collide.  See the code in `SaveGameFileChooser#getAutoSaveFileName()`:

https://github.com/triplea-game/triplea/blob/d68e99323d0ccf1ada722c3c6ad82027da532737/game-core/src/main/java/games/strategy/engine/framework/ui/SaveGameFileChooser.java#L75-L84

**Comment by simon33-2** [comment]
Yeah, I was thinking I'd just work on that assumption anyway.

The problem then is while the new autosave files are created, they do not be prepended with this information so each bot overwrites autosaves from each other bot. Which is not very useful.

**Comment by simon33-2** [comment]
Sorry about the several posts but the solution to not knowing the nation after the move phases on the bot is obvious! Remove the nation from the filename on bot autosaves! Not quite as pretty as for local games but still miles better than the status quo.

The major difficulty is that this change has to be done over two stable releases. First release has to allow the bots to accept the new parameter and the second one then has to be able to send it.

Given the above, can we get a fix for "Open Newer Save Game?" prompt, which cannot be responded to, at least for me. I'm not sure what's wrong with it though. I'll open an issue for that soon, unless it isn't needed.

**Comment by prastle** [comment]
Thanks @simon33-2 and @ssoloff

**Comment by simon33-2** [comment]
This will be in the next incompatible release. It's too late for a compatible release.

**Comment by ssoloff** [comment]
@prastle @simon33-2 Can this issue be closed now that #4207 has been merged?

**Comment by simon33-2** [comment]
What happens in the case that you can't get back to the same bot? I guess you can't load the autosave. Is that a likely problem?

**Comment by ssoloff** [comment]
@prastle Bumping this to determine if #4207 acceptably closes this issue for you.  As a reminder, #4207 implements the following request you made above:

> Yes I am asking for the bots to create saves similar to the way the new autosave folder does if you are hosting.
> example
> autosaveAfterAmericansCombatMove
> etc

**Comment by prastle** [comment]
@ssoloff I had a look at 4207 if it works then I am fine ty.  I have not tested myself I trust you guys have.  it should solve many issues when the new pre is stable.

**Comment by ssoloff** [comment]
@prastle Thanks.  @simon33-2 did testing as part of his PR.  I've personally used these new auto-saves in 1.10 bots recently, and they seem to work as expected.
