### ISSUE TITLE
Incorrect tooltip

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#4201]
### Engine version

Noticed with 1.9.0.0.12473, but has been there likely "forever"

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)

Start TripleA, hover over "Rule Book", see:

![included](https://user-images.githubusercontent.com/20812775/47269732-56870280-d562-11e8-9f6b-3071231306a0.png)

### Any additional information that may help

Despite what is stated in brackets the rulebook is not part of the installation.
So I suggest to remove that information.

**Comment by RoiEXLab** [comment]
#4202
