### ISSUE TITLE
HBG's Global War 1936-1945

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#4209]
What are the blockers to including a map for this in Triple-A? I am guessing that there are 2 types of dice and a build queue - although I'd think the build queue could be reasonably simulated using the "consumes units" property. Perhaps the rail line bit?

**Comment by DanVanAtta** [comment]
@simon33-2 I'm noticing this now and looks like you did not get proper traction here. Was a thread opened in the forum? I somewhat assume that this conversation happened by some other means, closing this in the meantime.
