### ISSUE TITLE
Read Game Engine Version from Config, and put it on the UI

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#422]
Problems:
- lots of build numbers, potential examples in SF threads of things being fixed in more recent version but still being repeated.
- when launching the game, the game engine is not displayed
- The console output still shows "1.8.0.9", even though we are version "1.8.0.10.x"

Today the game engine version comes from here:
```
import games.strategy.util.Version;

public class EngineVersion {
  public static final Version VERSION = new Version(1, 8, 0, 9);
}
```

I propose that instead we have the engine version be read from a file. This way in the build process we could write to the file the latest build number. To make it more backwards compatible, we would need to have the code that reads the file simply ignore the 5th number we have when it comes to compatibility.

Second, I think we should show the game engine version above the "Game Name". I've been confused myself before which version "Game version" referred to, whether map or engine. Most importantly, having the game engine version labelled will make it easier for testers to report which version they were using. With an auto-build producing lots of versions, this is getting to be more important to know.

![screenshot from 2016-02-02 01-03-11](https://cloud.githubusercontent.com/assets/12397753/12744401/ed1e1072-c948-11e5-839a-553d0c9807a8.png)

(In above screen shot, the idea would be to put "Engine Version: 1.8.0.10.884" above "Game Name: ")

**Comment by DanVanAtta** [comment]
I think there is a path here to having the version number specified exactly in one place. Today it is in two,  EngineVersion.java and secondly as a travis environment build variable.

If the version number is in a file, travis could read it. So this line:
```
- export TAGGED_VERSION="$BUILD_VERSION.$TRAVIS_BUILD_NUMBER"
```
would become:

```
- ENGINE_VERSION=$(cat engine_version.txt)
- export TAGGED_VERSION="${ENGINE_VERSION.${TRAVIS_BUILD_NUMBER}"
```
Then we would be able to remove the `BUILD_VERSION` variable from Travis (currently set to 1.8.0.10)


Then finally, so that each installer comes with the exact game engine number, we could overwrite "engine_version.txt" with the exact version number:

```
- ENGINE_VERSION=$(cat engine_version.txt)
- export TAGGED_VERSION="${ENGINE_VERSION.${TRAVIS_BUILD_NUMBER}"
```

**Comment by gaborbernat** [comment]
I would prefer setting the base in a game property file. And travis should read from this the number; and append the travis build number.

**Comment by DanVanAtta** [comment]
#426 adds this feature.

@gaborbernat , that is effectively what is happening. In the above the value is pulled from "engine_version.txt". In teh PR #426 we pull the engine version from ge_engine.properties. Travis will read that, append it with the build number, and then write it back.
