### ISSUE TITLE
NWO - wrong flag icons and units showing up

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#424]
Quoting #338:

@DanVanAtta - It appears the map blend issues are resolved but there are still issues with the wrong flag icons and units showing up.
![capture](https://cloud.githubusercontent.com/assets/1427689/12771171/aa8f0d16-c9ec-11e5-8c23-ac64b0d69d05.PNG)

**Comment by DanVanAtta** [comment]
I haven't been able to find changes that would have caused this yet. Note, NWO looks different on my OS, the correct units are found. 

![screenshot from 2016-02-04 19-41-34](https://cloud.githubusercontent.com/assets/12397753/12837424/8d16910a-cb77-11e5-986d-a9b4a720055b.png)

**Comment by DanVanAtta** [comment]
It's difficult to see why this is broken/changed. Here is what I've been able to determine so far:


The two chunks of code below look to be really key. The first one is how we load a full URL based upon a relative pathURL. For example, `getResource("flags/Germans_small.png")` would return a full file URL (an absolute path).


```
  public URL getResource(final String pathURL) {
    final URL rVal = m_loader.getResource(pathURL);
    if (rVal == null) {
      return null;
    }
    String fileName;
    try {
      fileName = URLDecoder.decode(rVal.getFile(), "UTF-8");
    } catch (final IOException e) {
      throw new IllegalStateException(e);
    }
    if (!fileName.endsWith(pathURL)) {
      throw new IllegalStateException("The file:" + fileName
          + "  does not have the correct case.  It must match the case declared in the xml:" + pathURL);
    }
    return rVal;
  }
```

The next interesting piece of code is the constructor for ResourceLoader which sets  `m_loader` 
```
  private ResourceLoader(final String[] paths) {
    final URL[] urls = new URL[paths.length];
    for (int i = 0; i < paths.length; i++) {
      final File f = new File(paths[i]);
      if (!f.exists()) {
        ClientLogger.logQuietly(f + " does not exist");
      }
      if (!f.isDirectory() && !f.getName().endsWith(".zip")) {
        ClientLogger.logQuietly(f + " is not a directory or a zip file");
      }
      try {
        urls[i] = f.toURI().toURL();
      } catch (final MalformedURLException e) {
        e.printStackTrace();
        throw new IllegalStateException(e.getMessage());
      }
    }
    m_loader = new URLClassLoader(urls);
}
```

At the bottom, note the "URLClassLoader", which is supposed to search against the paths provided, respecting the order. In a debug session I had the following values for urls:
`[file:/home/dan/triplea/maps/new_world_order/, file:/home/dan/work/triplea/assets/]`

The ResourceLoader is actually created twice, but both times the same `urls` param is the same.

Then in the same debug session I looked at the first chunk of code, which received as parameter `flags/Germans_small.png`, and then returned: `file:/home/dan/work/triplea/assets/flags/Germans_small.png`

It's odd that the first path wasn't used, since this file does exist: `/home/dan/triplea/maps/new_world_order/flags/Germans_small.png`

**Comment by gaborbernat** [comment]
are we done with this?

**Comment by DanVanAtta** [comment]
No, either something changed somewhere that I haven't spotted, or the way "URLClassLoader" works is a bit broken.

**Comment by DanVanAtta** [comment]
See  #454 for a fix.
