### ISSUE TITLE
Feature Requests Wiki Update

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#4249]
I see that there are 10 feature requests currently opened in GitHub.
https://github.com/triplea-game/triplea/issues?q=is%3Aissue+is%3Aopen+label%3A%22category%3A+feature+request%22

If you want to split feature request tracking between GitHub and Forum, can you please update the Wiki on how that should work (or let me know where it is currently documented, so I can update the Wiki myself, as I only remember it was decided to have all of them in Forum):
https://github.com/triplea-game/triplea/wiki/Feature-Requests

It currently says:
_Feature Requests should be posted in forum:_

Also, both backlog links are broken.

**Comment by FrostionAAA** [comment]
I have just added one of my requests to the forum, as I maybe should have done that in the first place 🙂 Maybe this will help the tracking.
https://forums.triplea-game.org/topic/1064/expand-randomstartdelegate-to-also-include-sea-units-and-sea-territories

**Comment by DanVanAtta** [comment]
If a feature request issue has been migrated, let's please close it so we do not have double tracking.

@Cernelius please update the wiki if you can/would to make the links current, or feel free to remove those links as would make sense.

I worked through the feature request list and it's down to just 3 from @FrostionAAA . I ice-boxed and closed mine, the 'feature requests' reported by @asvitkine were usability problems and not really feature requests. A "pure" feature request is something like "let's add the ability to edit unit images from within the game and save that to the map", vs something like "it's really confusing when the UI displays XYZ, it would be great if it filtered nonsense data points to avoid confusion and to be more useful." Hence, those issues were either labelled as 'usability' and/or as a "bug" too.

**Comment by DanVanAtta** [comment]
@FrostionAAA  please have a look at the remaining feature request items: https://github.com/triplea-game/triplea/issues?q=is%3Aissue+is%3Aopen+label%3A%22category%3A+feature+request%22

@Cernelius would you mind updating the wiki to be current? 

Once the above two items are done, is there anything further that should be done in the scope of this issue/task @Cernelius ?

**Comment by Cernelius** [comment]
Myself I'm just waiting if anyone else has anything to say (assuming the developers are all on the same page also on the matter of feature requests/bugs/usability issues), especially regarding the 3 open feature requests. I'm not sure it would make sense to update the Wiki in confirming that feature requests must be posted in forum in the moment there are any open? So, I don't think I can really update the wiki to be _factually_ current, just now.

Just letting anyone know that I'm waiting from further clarifications before changing the Wiki or closing this issue.

**Comment by Cernelius** [comment]
In particular, I would say this is not a Feature Request, but an issue of some kind (not sure if a bug or something else):
https://github.com/triplea-game/triplea/issues/3305
Just saying there I would change the label from Feature Request to maybe bug or something else. But just my personal view; I don't really know.
Especially the fact that TripleA doesn't allow you to specify what is the territory that is placing the carrier, as you should be able to, looks definitely like an issue to me; so I'm not sure why @ron-murhammer labelled that as a feature request (not saying it's wrong). Thus I feel further clarifications might be needed about maybe giving an explanation about the definition of what a feature request is in the Wiki as well?

**Comment by Cernelius** [comment]
Ok, this has remained opened enough time. I'm going to remove the broken links references and I'm closing this too, but I still believe that if you are going to track feature requests both here and in forum (because this is what you are doing), you should let everyone know how that works (anyways, people that see a "feature request" tag in here will assume that this is the right place to make feature requests, obviously).

**Comment by DanVanAtta** [comment]
To add a more conclusive note, forums is where feature requests should live, certainly the ones that are use requested. Some github issues opened turn out to be feature requests. It's not a clean process how those are tracked and/or moved to forums. Personally I wonder if forum tracking is actually that successful of a way to track feature requests (submitting them perhaps yes, but tracking I'm really not sure)
