### ISSUE TITLE
Windows 32 bit installer doesn't create a usuable installation

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#4255]
### Engine version

1.9.0.0.12226

### My Operating System
Windows Vista 32 bit

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Install Triple A.
Start Triple A.
splash screen flashes up but then quickly disappears. Triple A doesnt start

### Any additional information that may help
Problem is the TripleA.vmoptions file sets a minimum value of 2GB. This amount of memory is not available for this type of memory regardless of the installed memory. On my 4GB system, it doesn't work with amounts of 1200M.

Previously, this had no minimum or maximum. What was this change for, can I ask?

**Comment by ssoloff** [comment]
As a temporary workaround, you can edit the _TripleA.vmoptions_ file, located in the folder where you installed TripleA, to contain the following:

```
-Xmx1G
-Xms1G
```

**Comment by Davvoh** [comment]
Alright, when you say edit can you tell me how to edit it, or where to go to change that. I didnt fully understand. Thanks, i am sure what u mentioned is the problem i just dont know what u mean by edit

**Comment by ssoloff** [comment]
@Davvoh You can edit the file using a text editor like Notepad (don't use Wordpad, Microsoft Word, LibreOffice Writer, or any other "word processor").

When you installed TripleA, you should have been asked where you want it to be installed.  If you don't remember where that was, try looking in the following locations:

* _C:\Program Files\TripleA_
* _C:\Users\\<your username\>\AppData\Local\Programs\TripleA_

Once you find the installation folder, there should be a file called _TripleA.vmoptions_.  Open your text editor, and then drag and drop that file into the text editor window.  There should be two lines that look identical to what I pasted above except the ones are twos.  Simply change each `2` to a `1` and then save the file.

Try relaunching TripleA, and it should now start.

**Comment by Davvoh** [comment]
You sir are a legend. Legit cant find the right words to thank ya

**Comment by ssoloff** [comment]
@simon33-2 @Davvoh This issue should be fixed in pre-release [1.9.0.0.12959](https://github.com/triplea-game/triplea/releases/tag/1.9.0.0.12959).  If one of you would be kind enough to test and verify the fix, it would be appreciated.

**Comment by simon33-2** [comment]
This works on my old system.
