### ISSUE TITLE
Nicer way to do enum style java class

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#427]
Any suggestions for a nicer/modern way to do this?

I like that the correct output string comes from "toString", and meanwhile the rest of the code gets to use named constants. So I'm particularly how alternatives would look from a client perspective.

```
+package games.strategy.engine.config;
 +
 +public final class GameEngineProperty {
 +  public static final GameEngineProperty MAP_LISTING_SOURCE_FILE = new GameEngineProperty("Map_List_File");
 +  public static final GameEngineProperty ENGINE_VERSION = new GameEngineProperty("engine_version");
 +
 +
 +  private final String value;
 +  private GameEngineProperty(String value) {
 +    this.value = value;
 +  }
 +  @Override
 +  public String toString() {
 +    return value;
 +  }
 +
 +}
```

**Comment by gaborbernat** [comment]
Why not just do it as an enum with a String field?

**Comment by gaborbernat** [comment]
Like presented in, http://stackoverflow.com/a/3054272/296075

**Comment by DanVanAtta** [comment]
And also override toString() there?
enum toString() is not eligible for override, is it? I want to be able to use toString() rather when translating back to the "hidden" string value (like for example: 'engine_version').

**Comment by gaborbernat** [comment]
It definitely should be. Although I would prefer a getKey() function there.

**Comment by gaborbernat** [comment]
or just making the field public final, and refer it as ENGINE_VERSION.key :+1:

**Comment by DanVanAtta** [comment]
Could be a problem though if you do  "ENGINE_VERSION", instead of "ENGINE_VERSION.key". With the auto call to toString() in the first one, would lead to the wrong value.

**Comment by gaborbernat** [comment]
not if the toString also returns the key :D

Bernát GÁBOR

**Comment by DanVanAtta** [comment]
The updated code looks like this:

```

public enum GameEngineProperty {
  MAP_LISTING_SOURCE_FILE("Map_List_File"), ENGINE_VERSION("engine_version");

  private final String value;

  private GameEngineProperty(final String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return value;
  }

}
```

**Comment by gaborbernat** [comment]
Maybe the field name should be key to indicate we are talking about a key in the property and not the value.
