### ISSUE TITLE
Adding a config file to test classpath in gradle

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#428]
Found this:

   java.lang.RuntimeException: java.io.FileNotFoundException: /home/travis/build/triplea-game/triplea/build/classes/game_engine.properties

@gaborbernat , is there a clean way to add that to the gradle?

**Comment by DanVanAtta** [comment]
Specifically I need "game_engine.properties" to be added to the test resource classpath.

**Comment by DanVanAtta** [comment]
Hmm, second thought, need to confirm the problem here. Though gradle does not behave the same as  eclipse, so I suspect it is a resource pathing problem.

**Comment by gaborbernat** [comment]
Move it to the src/main/resources the file and it will work.

**Comment by gaborbernat** [comment]
Or to src/test/resources I think. Will  look into this later on, check for
Gradle source sets in the meantime if you  need it fast.

**Comment by DanVanAtta** [comment]
looks like i found a java fix for it, using getRootFolder() was just causing trouble.
