### ISSUE TITLE
TripleA Version Numbering - Semantics

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4346]
### Picking up from the discussions in:
- https://github.com/triplea-game/triplea/pull/4234
- https://github.com/triplea-game/triplea/issues/323

### For discussion:
- how to do TripleA version numbering

### Problems to solve:
- TripleA version numbering does not really make sense
- We use the same version number everywhere (I see this as a problem as it means any changes in one kind of compatibility indicate that other potentially compatible components would be flagged as incompatible).
- The version numbers do not really make sense to our users, this makes it hard to know which version is latest and what exactly is compatible with what and when (IMO in part we are solving this wrong and the compatibility question should just be completely solved by software; which would make a user-facing version number useful for labeling to know which version is being reported in bug reports and so users can know at an intuitive level which version is the latest and potentially newer than their current).

### A Suggestion:
We start to use 4 different version numbers for TripleA:

- a release or product number that is user-facing (eg: "18.11.<build_id>")
- network compatibility
- save-game compatibility
- map-parsing compatibility

I would view our current "product number" as the network compatibility number. For example that number is used by the game client to determine which lobby to join and whether the game client can multiplayer play against another client. IMO we then use the network compatibility number for dual purpose as the user-facing version number, and then we simply do not have a save-game compatibility or map number (which means they are "latest", and that in turn causes us to have such challenging compatibility problems when we update the code)

For discussion:
- Is the suggested approach a good way to go? Anyone see problems with it or have alternatives which they would like to suggest?
- If we decide we like that approach, we'll need to discuss some details of what the version numbers will look like and when/how they would change.

**Comment by simon33-2** [comment]
I didn't understand why the decision was made to avoid going 2.<build>

You're argument is that save game compatibility, network compatibility and map compatibility should be separated? Let's go through that.

If you made, let's say a new property but otherwise kept compatibility, then had a new or revised map using that property that map would not work in a previous version of the engine. However, I don't agree that we need a separate number for this scenario. You can just put in a minimum build number. Is there some other scenario which is not similar to this? Is the problem that you dislike the idea of comparisons on build number?

Can't say I like the idea that network and save game compatibility would not be kept together either. Aren't you saying that you might have a 1.10 and a 1.11 which could not load each other's save games but connect to each others network hosted games? That seems pretty crappy to me. If you did that you would have trouble loading autosaves for example. I can accept that others know more about this project than I but I thought I'd post my thoughts anyway. I just can't see the benefit of that proposal. Incompatible releases should be comparatively rare.

**Comment by simon33-2** [comment]
I note that you glossed over why using the build number would be a problem "on a few levels". In my example above of adding support for a new map property I cannot see the issue. What's the case where it becomes an issue?

Re: network vs savegame. I don't see the merit in separating. Sorry. Of course it is possible, just doesn't seem advised.

Sounds like you have in mind to have a perfect system for save games with backwards compatibility. I've got no idea how achievable that might be. I just wish you well with it.

**Comment by simon33-2** [comment]
Suggest closing with the merging of #4234

**Comment by DanVanAtta** [comment]
> I note that you glossed over why using the build number would be a problem "on a few levels". 

I'm not sure if you're just considering map properties, considering the whole system and how versioning is all tied to the single number, this introduces some problems:

- why exactly should changes in network compatibility impact save game? A new feature in login menu that does not work in old clients should really invalidate new engine from loading old maps because the major version changed?
- if the major version changes for something, somewhere in the game, it seems we may as well use a single number for all its worth, "1.8" -> "18", what's the use of the dot notations again with 1.9.1? why not call that 191?

> If you made, let's say a new property but otherwise kept compatibility,

- Let's say a property is instead renamed or removed, how do you keep compatibility?

> Sounds like you have in mind to have a perfect system for save games with backwards compatibility. I've got no idea how achievable that might be. I just wish you well with it.

Please don't put words in my mouth, also particularly when you have not understand the plan to begin with. Perhaps you can contribute to this, or are we just happy not being able to change variables or class names without breaking major compatibility? I have not suggested I want a perfect system, but something less brittle, easier to work with, and more obvious than java bean serialization. 


@simon33-2  this issue actually has not much to do with #4234; Currently only 2 version numbers in our build versioning have real meaning to them, going from 3 unnecessary to 2 unnecessary is not related to that we perhaps should be calling our game releases something other than just a single semver.

For example, if we stopped overloading the version number for everything we could easily talk about release 2019.01

I'm re-opening this issue because our current version number is not meaningful, hence "semantics". Why not just squash the version numbers together with our current system to have just one number that is hardcoded and a second be a build number?

**Comment by simon33-2** [comment]
I don't think I have anything to add to my previous comment.

Let's agree to disagree.

**Comment by DanVanAtta** [comment]
@simon33-2 it's not a matter of agreeing just between you and I, and in fact this train of conversation really had nothing to do with your MR other than it's both about version numbers in the abstract. WE currently have no long term plan anymore for version numbers, our previous plan was abandoned, and there are some potential improvements to make.

1. It would be great to use semver, but it would also be great if we could have an external release name ot not expose semver to our end users
2. a single version number for everything seems to be the 'convenient-but-inappropriate' anti-pattern
3. a single version number will not work if/when we further sub-divide the components of 'game-core'. 'Game-core' is not meant to be the final state, I expect we'll split off map parsing and network to their own modules. Those modules would then have no visibility to the game engine version. Thus, it seems to make sense for us to start thinking about different dimensions of compatibility and how to indicate that between different sub-systems, rather than having one overloaded semver do it all.

**Comment by simon33-2** [comment]
I disagree with point 2 for reasons already discussed.

I also disagree with point 1 - unless we can have backwards compatible save games. As it is, the two highest version numbers have direct effect on the users and hiding it from them would cause user frustration.

**Comment by DanVanAtta** [comment]
The reasons already discussed seem to be scant, or based on a misunderstanding:
> Aren't you saying that you might have a 1.10 and a 1.11 which could not load each other's save games but connect to each others network hosted games?

As far as I can tell, *you* are the one arguing for such a system. Eg: compat in either just save game or either network triggers a non-compatible version number upgrade.

In my suggestion, we'd have two different semver for those compatibility. It would be a decision then if we have a third, an overall one for the combined game. Thus in my suggestion the answer is if you had those two product numbers, you would know that something was not compatible. If you looked at the sub-system semver, then you would know for certain. With your route I do not think you can determine what is incompatible, just that something is.

I'm also not sure if we understand the distinction of semver vs custom semver. Semver is somewhat spelled out: https://semver.org/

As far as I know we have a custom semver, I'm also not sure if it is the highest two and not in practice the second highest that determines everything. Yes, the '1' in front would be seen by code as non-compat by itself, but when and by which rules should we change that value to anything? The other point of topic is that our current custom semver does not make necessarily make sense.

Having an external facing semver is not to say we will necessarily hide information from users. I also question that a bit and wonder how much information hiding we are actually doing and also how much of it is leaving it up to the user to solve problems the software should solve. For example, save games give no indication of which exact version they are, just get a bad version message or a serialization error. Ultimately my hope is we mostly solve that problem by making it rare and less of a problem to solve by introducing some possibility of backward compatibility. 

Regardless, more at suggestion is if the leading "1" is meaningless, IMO it effectively is as it has never and probably *will* never change, we may as well drop or give it meaning. For example `2018-03.9.124214`. If we also go on to create a public facing 'alias' for this, it does not mean we have to hide the version from the user. For example we could call that the 'blue-9' release, noting that we have a mapping of the compat number in the public name. We also can choose how many places, where and how to show the version number vs release name. In essence the question is if we should also name our releases, I'd agree it'd be unwise to take the name of a release and use that to completely hide compatibility version numbers.

**Comment by DanVanAtta** [comment]
Discussion summarized and continued in #4548
