### ISSUE TITLE
No surface warship objective confused by land units on transport

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#4347]
### Engine version
1.9 - 12640, 1.9 - 9687

Works properly in build 3635

### My Operating System
Ubuntu

### Map name
World War II Global 2nd Edition.

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Put a UK transport in the med and no surface warship. If there is a land unit on the transport, the Italians don't get the 5IPC bonus for having no enemy surface warships. However, they do get it if you remove the on board unit from the transport.

Perhaps this went wrong with #1930?

### Instead of this error, what should have happened?
Objective should be granted regardless of land units on board the transport.

### Any additional information that may help

<!--[ItalianMedObjectiveIssue.zip](https://github.com/triplea-game/triplea/files/2569118/ItalianMedObjectiveIssue.zip)

**Comment by ron-murhammer** [comment]
Interesting. I'll have to take a look at how `enemySurfaceExclusionTerritories` works to see why its picking up land units.

**Comment by ron-murhammer** [comment]
@simon33-2 This should fix it: #4348. `enemySurfaceExclusionTerritories` was missing a check to ignore air and land units.

**Comment by ron-murhammer** [comment]
@simon33-2 Once that is merged and you verify the fix, do you think we should put that fix into the 1.9 fix branch? Or can it wait for the next incompatible release?

**Comment by simon33-2** [comment]
We can probably live with this problem but given that a hot fix is in the works anyway would it be much trouble to put this into it?

**Comment by simon33-2** [comment]
Seems to work to me.
