### ISSUE TITLE
Replace TimedController abstract class with clock field

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#4354]
Just had this thought and I wanted to write it down before I forget it again.
We should replace the overridable method in TimedController with a field that gets populated with a [Clock Object](https://docs.oracle.com/javase/10/docs/api/java/time/Clock.html).
That's what the object was designed for.

**Comment by DanVanAtta** [comment]
Closing for now, issue is getting a bit old; It's probably not a good idea to keep track in issues of the various refactorings that need to be done. A wiki list is perhaps better or agree to skip the overhead and fix things as we work with the code and as the priority comes up. Tracking yesterdays dirty code could also have an inversion of priority problem where we fix things that would have helped some time ago but no longer.
