### ISSUE TITLE
Different delegate handling

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#4363]
This is a question for @veqryn : 
When discussing code internals with @ssoloff in various issues and pull requests we realized that attachments are treated differntly when it comes to actually load them.
While Attachments are simply getting deserialized from the savegame, or instanciated by the GameParser, delegates are created differently:
The savegame only stores the class name of the Delegate and when loading a new savegame, a new instance of a delegate is created base on that class name.
Do you know if there's a particular reason for that?
I'm simply curious to know.

**Comment by veqryn** [comment]
I believe it was this way since before I joined the project.

**Comment by RoiEXLab** [comment]
Too bad
