### ISSUE TITLE
Debian Bug: NPE on startup with OpenJFX 11 

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4372]
Just want to be sure we saw this and have it fixed in the latest: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=911078

>  After the switch to OpenJFX 11, triplea fails to start with a
NullPointerException.

> triplea.engine.version.bin:1.9
java.lang.NullPointerException
	at org.pushingpixels.substance.internal.utils.SubstanceColorUtilities.getDefaultBackgroundColor(SubstanceColorUtilities.java:759)

It looks like we perhaps saw this before and were not able to repro: https://github.com/triplea-game/triplea/issues/2507

**Comment by ssoloff** [comment]
Using Oracle Java 11.0.1 with a Substance L&F active, I was able to repro the NPE at startup using 1.9.0.0.7062 on Fedora.  I then ran both 1.9.0.0.13066 and 1.10.0.0.13112 in the same configuration, and no NPE was observed at startup.

Presumably the latest Substance binaries have fixed this issue.

**Comment by beelee1** [comment]
This reminds me, I encountered this recently:

[https://github.com/Microsoft/vscode-arduino/issues/644](url)

Didn't find anything on triplea about it at the time is why I mention it. I was on a fresh install of triplea, no triplea stuff whatsoever. Was also on a virtual box inside a windows machine.

Followed the solution and it worked fine.

Anyway, if this is unknown, I'll try and reproduce and start a separate issue.

**Comment by DanVanAtta** [comment]
I *think* I've replied to the thread stating that this has been confirmed. I'll check in on this further and try to help get the Debian bug closed.

**Comment by OrdoFlammae** [comment]
Was this confirmed with the bleeding edge version? I had an issue with this, but I was trying to see if I could fix it, and found that the github version does not have this problem.

**Comment by DanVanAtta** [comment]
This might very well be fixed, it looks like the Debian version had an update committed to it: https://metadata.ftp-master.debian.org/changelogs//main/t/triplea/triplea_1.9.0.0.7062-2_changelog "* Fix FTBFS with OpenJFX 11. (Closes: #874132)"

**Comment by DanVanAtta** [comment]
I've opened an issue to discuss the Debian fork and how to sustainably maintain the two code bases. Overall I think we need to try and unify the two so that the debian fork can pull from the latest TripleA without modifications, in which case we would be maintaining just one code base. Assistance in that effort is really appreciated.
