### ISSUE TITLE
How to incorporate the Tutorial Map

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#438]
Suggestion from the forums is to add a button to the main screen that launches the map. This would involve bundling the tutorial map with the game engine.

Thinking about how to support this, perhaps we should have an in-game tutorial that guides people to the map. The tutorial would open a help window, and highlight buttons to click and guide people through the process of downloading and then playing the tutorial map.

For next release we may go with the first approach simply because we can get it done sooner. I'm curious if there is another way to solve the problem and what people think of the first two approaches already mentioned.

**Comment by ron-murhammer** [comment]
@DanVanAtta - Yeah, I think having a button on the main screen that activates a tutorial of the main menu and then launches the tutorial map would be best. Agree that its probably best to get the tutorial map included first then consider that.

**Comment by williamdekryger** [comment]
@DanVanAtta @ron-murhammer I believe that it would be best if we could make a nice flow for users downloading TripleA for the first time. I am putting the finishing touches on the new download page, and would like to maybe incorporate some sort of reference to the tutorial. [Here](https://github.com/triplea-game/triplea-game.github.io/issues/6) is the thread about the download page.

Basically, I am thinking that, after selecting their OS, the download will start, and a user will be shown installation instructions. Next, I propose to write a "Getting Started with TripleA" page that will show users how to open the tutorial, and maybe help with some of the opening moves.

My idea is to potentially try to coordinate the website docs with the tutorial so that new users have no trouble getting set up. I would like to know thoughts/suggestions that you had on this flow.

**Comment by DanVanAtta** [comment]
I like the idea very much. No suggestions, I say run with it. 
I can:
- add the tutorial to the travis build so it is bundled with the game.
- add a launch tutorial button to the change notes, as well as adding a 'show change notes' button to the main screen.

**Comment by DanVanAtta** [comment]
The SF conversation about this was very interesting. Essentially that adding the button to the change notes will not be very good for new users, likely ignored.

@williamdekryger  and @ZjelcoP, any definitive thoughts on how/where to place the launch tutorial button?

**Comment by ZjelcoP** [comment]
Well from the two remaining options:
-Button gamescreen
-maps list
I have no definite preference, If i'd have to choose, I'd say 1.

To be considered:
-How to prevent players adjusting playertypes....as this will mess up the tutorial.

Request https://github.com/triplea-game/triplea/issues/457 is out, any chance it will be implemented this release? If so the tutorial could go as other maps in the mapslist provided it is easy to find.
If not can you make the game skip this settingsscreen or freeze the options, by use of a tutorial-launch-button?

**Comment by ron-murhammer** [comment]
@DanVanAtta This is resolved now with #617

**Comment by DanVanAtta** [comment]
We still have just a bit more to go on this one. The Tutorial map is now bundled, but we wanted to improve the new user UX so they could find it easily. 

I think we agreed to start by adding it to the main game window. First time launches of the game and the button will be shiny or something so it stands out.

**Comment by ZjelcoP** [comment]
Thanks for adding the Tutorial to the download!

Has anyone considered this issue? Think it is preferable to be resolved to prevent bad experience for some players. 

_To be considered:
-How to prevent players adjusting playertypes....as this will mess up the tutorial.

Request #457 is out, any chance it will be implemented this release? If so the tutorial could go as other maps in the mapslist provided it is easy to find.
If not can you make the game skip this settingsscreen or freeze the options, by use of a tutorial-launch-button?_

**Comment by DanVanAtta** [comment]
@RoiEXLab  or @frigoref , let me know if there is an aspect of this task that you can help with, could use help with wrapping this up.

Task is to add a "Tutorial" button that skips everything and launches the tutorial with one button click.

**Comment by RoiEXLab** [comment]
I think I could do that, if @DanVanAtta takes over the Mock Object thing ^^
 - I will look into that this evening...

**Comment by RoiEXLab** [comment]
I looked into that and so far I added a Button to the Main menu... I'm currently trying to figure out a way to get the tutorial map's GameData in order to construct a launcher object... If there is a Class providing a method like getGameDatabyMapname(String mapName) or similar please let me know...

One Small thing I noticed while skipping trough some of those classes: There are lots of classes being a Sample for subclasses with some methods being declared but not implemented... In my opiniont those classes should be declared as abstract classes - I will do this in a future PR

**Comment by DanVanAtta** [comment]
Getting the gameData IIRC can be done through the NewGameChooserModel, or at least that should have a mechanism that could be used or at least mimicked.

**Comment by DanVanAtta** [comment]
There is a lot of inheritance in the TripleA code base. IMO it is a pretty significant factor in the code brittleness.  Favoring composition would be better in many classes, rather than making classes abstract. But, it could be the case that an easier/first refactor will be to make classes abstract as appropriate.

**Comment by RoiEXLab** [comment]
Ok I found the neccesary Methods etc...
Now I'm getting a NullPointer when trying to launch...
The StackTrace is not helping at all:
```
Exception: null
java.awt.EventQueue.invokeAndWait(Unknown Source)
java.awt.EventQueue.invokeAndWait(Unknown Source)
javax.swing.SwingUtilities.invokeAndWait(Unknown Source)
games.strategy.common.swing.SwingAction.invokeAndWait(SwingAction.java:61)
games.strategy.triplea.TripleA.startGame(TripleA.java:127)
games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInNewThread(LocalLauncher.java:51)
games.strategy.engine.framework.startup.launcher.AbstractLauncher$1.run(AbstractLauncher.java:47)
java.lang.Thread.run(Unknown Source)
```

And `MetaSetupPanel.this` is not `null`.
You may have a look at [my branch](https://github.com/triplea-game/triplea/compare/master...RoiEXLab:tutorialmap-patch)

**Comment by RoiEXLab** [comment]
So I added a temporary try/catch statement around the erroring code:
```
java.lang.NullPointerException
	at games.strategy.triplea.ui.AbstractStatPanel$ResourceStat.getName(AbstractStatPanel.java:70)
	at games.strategy.triplea.ui.StatPanel$StatTableModel.getColumnName(StatPanel.java:259)
	at javax.swing.JTable.addColumn(Unknown Source)
	at javax.swing.JTable.createDefaultColumnsFromModel(Unknown Source)
	at javax.swing.JTable.tableChanged(Unknown Source)
	at javax.swing.JTable.setModel(Unknown Source)
	at javax.swing.JTable.<init>(Unknown Source)
	at javax.swing.JTable.<init>(Unknown Source)
	at games.strategy.triplea.ui.StatPanel$1.<init>(StatPanel.java:72)
	at games.strategy.triplea.ui.StatPanel.initLayout(StatPanel.java:72)
	at games.strategy.triplea.ui.StatPanel.<init>(StatPanel.java:64)
	at games.strategy.triplea.ui.TripleAFrame.<init>(TripleAFrame.java:340)
	at games.strategy.triplea.TripleA.lambda$0(TripleA.java:130)
	at games.strategy.common.swing.SwingAction.lambda$0(SwingAction.java:61)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

Any ideas what could be wrong here? @triplea-game/devs

**Comment by DanVanAtta** [comment]
- @RoiEXLab, NPE makes sense since the map is not found. We should update the code to return an optional.empty instead of null to help avoid that problem. But even when the map is found, there are further problems.

Another button on the main menu I now think is the wrong approach, and perhaps are looking at a solution in search of a problem. 
- It's pretty easy to load the tutorial. 

Let's let user feedback drive changes to this feature. As is, the UX I think is reasonable enough to find the tutorial.

**Comment by RoiEXLab** [comment]
@DanVanAtta 
What about a highlighting of the important buttons on first launch?
I could check if this is the first time launching, and if so I could draw some text explaining, hey this is buton...  And It does.... Or I could just leave it to highlighted/flashing buttons

**Comment by DanVanAtta** [comment]
Good thoughts, but first let's focus on removing what does not need to be there. Then we'll be in a good place to see how the UX needs updating, which buttons should be present when. I'd rather avoid first launch specific code, it kinda means that stuff is just hard to find to begin with.

**Comment by RoiEXLab** [comment]
Ok Closign #726 then...
