### ISSUE TITLE
TripleA Website And Forum Are Down?

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#4382]
I just tried to go to the website: http://triplea-game.org/ and got "ERR_NAME_RESOLUTION_FAILED"

Can someone confirm this?

**Comment by RoiEXLab** [comment]
@ron-murhammer For me everything is just working fine 🤔

**Comment by ron-murhammer** [comment]
Weird, guess I was just having funky internet issues. Seems fine now.

**Comment by tvleavitt** [comment]
I recommend signing up for a free third party web site / service monitor, to prevent "false positives" and confirm issues easily. There's a wide variety of these out there.
