### ISSUE TITLE
Forced to splash fighter at end of noncombat phase when purchased carrier could be placed

### ISSUE THREAD

**Issue by ryanrozy** [triplea-game/triplea#4429]
### Engine version
1.9.0.0.13066

### My Operating System
Windows 10

### Map name
World War II Revised

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Britain moved fighter during combat move phase from Gibraltar 4 spaces to sea zone 3 to join an existing carrier to take part in a sea battle before an amphibious invasion into Norway. Plane survived battle with no moves remaining and carrier was dead. Plane had no moves during noncombat phase and was stuck in sea zone 3. The game prompted a window to open asking if I wanted to keep moving air unit or end phase. I ended phase and plane was killed. But I had purchased a carrier in the purchase units phase in that turn and was going to place the new carrier in sea zone 3 to save the fighter. The fighter should only splash/die if I don't place the carrier in sea zone 3 at the conclusion of the mobilize new units phase.

### Instead of this error, what should have happened?
The existing fighter should have been allowed to remain in sea zone 3 where it would land on the newly built carrier being placed in sea zone 3 during the mobilize new units phase. If the player chooses not to mobilize the new carrier in sea zone 3 then a window should pop up stating that the existing fighter in sea zone 3 will die if the new carrier is not placed there with option to change placements or end mobilize new units and BOOM splashed/killed plane.

### Any additional information that may help
The zip file includes a PDF of the official Axis & Allies Revised FAQ dated April 21, 2010 in which it states in the 'Mobilize Units' section -> "Question. A newly built fighter can be placed directly on a newly built aircraft carrier. Can a newly built fighter be placed on an existing carrier, or can existing fighters be placed on a new carrier? Answer. AN EXISTING FIGHTER that is in the territory containing the industrial complex or THAT IS IN THE SEA ZONE WHERE THE AIRCRAFT CARRIER IS BUILT CAN IMMEDIATELY BE MOVED ONTO A NEWLY BUILT CARRIER. New fighters, however, can’t be placed directly on existing carriers." Link to PDF here:  [http://www.harrisgamedesign.com/pdf/A&A_Revised_5_FAQ.pdf](url)

Please zip and post a save game to this bug report!
[triplea.zip](https://github.com/triplea-game/triplea/files/2665973/triplea.zip) Note: Please see Britain's last noncombat move phase.

**Comment by Cernelius** [comment]
>The fighter should only splash/die if I don't place the carrier in sea zone 3 at the conclusion of the mobilize new units phase.

I don't thin so. Assuming this is not LHTR, Fighters land at the end of the non combat movement phase, during their owner's turn.

What that clarification I believe is telling is that you can move fighters from existing to new carriers (something that TripleA doesn't allow you to do, as you cannot choose or even see the carrier you land on).

But I'm not an official answers guy, nor I have an official clarification specifically on this, if anyone is wondering.

**Comment by ryanrozy** [comment]
I must agree with Cernelius given the totality of the rules explicitly stating that planes must LAND at the end of the noncombat phase.  Closed this issue, Thanks Cernelius.
