### ISSUE TITLE
Lobby Release Reference (1.9.0.0.13066)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#4432]
The current stable is, apparently, 1.9.0.0.13066, while the lobby says:
"All automated hosts have been updated to use the latest stable engine 1.9.0.0.12226. It's recommended that
all players download and install the latest release here: https://triplea-game.org/download/".

In the past, I pushed a change to that line, removing the release number altogether, but, then, it was added back. Are you sure you want to keep it referenced in the lobby, and do you have any idea about how to assure it getting reliably updated each time there is a new release?

Anyways, your call whether:
1. updating the lobby chatlog, referencing the correct current version, or
2. updating the lobby chatlog, as to specify that is the version that the bots are currently running (if that is true), yet not necessarily the latest stable, or
3. removing the version reference (this is what I pushed some time ago).

**Comment by Cernelius** [comment]
This is the release that, according to the lobby, is the one all bots are using and it is the latest stable:
https://github.com/triplea-game/triplea/releases/tag/1.9.0.0.12226

**Comment by ron-murhammer** [comment]
@Cernelius I removed it as we haven't done a good job keeping the message up to date.
