### ISSUE TITLE
Document "maxOperationalDamage" Relevance Fully in PoS2

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#4440]
Currently, this is the explanation given:
`maxOperationalDamage					values: is used with certain features like isAirBase, repairsUnits, and givesMovement to determine if those features work or not based on the current damage of this unit. A disabled unit will not participate in combat or be able to move.  Does Not work with isFactory or canProduceUnits.`

I would like to update this comment as to fully tell all cases relevant for the option, but I need a developer to look into the code and give here the full list. If that is actually the full list, I would like a developer to confirm it, and update the comment as to clarify that is exhaustive.

I believe this is particularly important, as the complexity of the matter implies that whatever missing in the clarification is virtually a wasted functionality or worse; so I hope this can be sorted out soon.

Current list:
`isAirBase`
`repairsUnits`
`givesMovement`

**Comment by ron-murhammer** [comment]
https://github.com/triplea-maps/the_pact_of_steel/pull/24

**Comment by Cernelius** [comment]
I would prefer the description telling the exhaustive list (that I understand it is); so I suggest changing:

`is used with certain features like`

to

`is used together with the following options only:`

Quite obvious anyway, but I would also change:

`to determine if those features work or not based on the current damage of this unit.`

to

`to determine if those features are active depending on the current damage of the unit being lower than the value assigned to this option.`

(also a comma before "to determine...")

Off topic, but personally I think the best would be if you can specifically disable whatever options, by listing them, but I'm not sure I've anything going on at the moment that would use this (a few times I wished I could set that you need to repair all damage to build anything).

Related matter, I find such explanations quite confusing (well, not for me, since I know the cases) on the damage, as we have two kind of damage, hitpoints and from bombing, and the definitions are hardly distinctive, between the two matters, especially when talking about repairing.

**Comment by Cernelius** [comment]
Actually, my bad, I got confused by the fact that pretty much in all cases when a value is set, that is the value at which point something changes, while, in the case, as the option says, that is the maximum value at which the unit is still operational, thus it gets disabled at 1 damage more than what set in the value.

Anyways, well, this is a good reason to be specific. But, to be correct, I believe the definition should be changed from:

`Determines if those features are active based on the current damage of the unit being lower than the value assigned to this option.`

to:

`Determines if those features are active based on the current damage of the unit not exceeding the value assigned to this option.`

**Comment by ron-murhammer** [comment]
Fixed the description: https://github.com/triplea-maps/the_pact_of_steel/pull/26
