### ISSUE TITLE
Saving dice server results for tournament/ladder audit purposes

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/triplea#4443]
Originally begun in https://github.com/triplea-game/triplea/pull/4441#issuecomment-448268733.  The conversation from that thread is repeated below:

> @ron-murhammer: @RoiEXLab @ssoloff Does the old and/or new MARTI server currently save the dice rolls anywhere? I think the idea behind this field was to allow dice rolls to be saved and then someone being able to request to see them. From a tournament/ranked standpoint, something like that would be really useful.
>
> @RoiEXLab: @ron-murhammer Not really saved in the sense of on the server, but just like with MARTI sent to the individual participants.
For a mod to verify games we'd need to add another possible email option though, MARTI supports an unlimited amount of destination emails which is simply not good because this allows the server to be misued for mass spamming.
>
> @ron-murhammer: @RoiEXLab Yeah, I think you could argue to move away from dice emails all together. Instead have dice rolls saved on the server in a database and have a little UI that could be used to search by some sort of game ID.
>
> @ssoloff: Just throwing this out there...  If the dice server cryptographically signs the dice rolls, the rolls themselves could be stored in the save game.  That would keep everything bundled together nicely instead of spread out on another server.  Then anyone with access to the save game can verify the rolls are legitimate by simply verifying the signature (possibly by using another API exposed by the dice server if we're using self-signed certificates).
>
> @ron-murhammer: @ssoloff Interesting idea. Might be an even better alternative. 
>
> @RoiEXLab: I thought about all of this for a long time a year ago.
The whole point of the system is to have a trusted random source that can generate random numbers, however simply bundling the signature in the savegame has a severe limitation: Nothing prevents a cheating user from reloading the old savegame and try rolling often enough, so at some point they win.
I also thought about using pseudo random functions that only generate a seed before a game starts and generate numbers in a predefined order.
This improves the system a bit, but still doesn't fix the problem where a user can simply change the move by reloading the savegame if a battle didn't turn out so well.
>
> So the key is notifying both users when a roll is attempted,which makes email a reliable choice.
Of course we could come up with a smarter system that uses game uuids and stores rolls per game in a database, but then we would keep the info forever because we don't really have some sort of cleanup mechanism unless we automatically remove games without any activity for a set amount of time.
>
> @RoiEXLab: @ssoloff The new dice server already signs the dice rolls and returns the signature that can be verified by passing it to the other endpoint. No need for a certificate, when using HTTPS, simply having a private key is sufficient.
>
> @ron-murhammer: @RoiEXLab Yeah, good point. I don't think putting it the save game alone would work.

**Comment by ssoloff** [comment]
> Nothing prevents a cheating user from reloading the old savegame and try rolling often enough, so at some point they win.

Yup, I forgot about the reload cheat.

> So the key is notifying both users when a roll is attempted

My main motivation for suggesting storage in the save game was to try to preserve the statelessness of the dice server.  But, even if we don't store dice rolls on the dice server itself, it seems we need some kind of audit trail, at least for the "requests" to roll dice.  As you said, email serves that purpose just fine.  However, users outside the game (e.g. tourney mods) would have no visibility of the audit trail unless they themselves happened to be on the email list for the game (e.g. that might be a requirement for being part of a tourney).  But I'd hate to be the tourney mod who got thousands of emails a day "just in case" I was asked to review some dice rolls. :smile:

Maybe a compromise for a stateful dice server would be simply to keep track of a dice roll sequence number per game.  The dice server would increment that sequence number on each roll and include it in the response.  Then, someone reviewing the save game could simply look for a break in the sequence to detect a cheater (or just do it automatically when loading the save game).  The point is that storing < 100 bytes per game (game ID + sequence number) would scale well, and we wouldn't have to be too concerned with cleaning up the database, even for millions of games.  Although, purging games whose last dice roll was more than a few years old might not be bad either.  But even with a timestamp, I don't think we'd exceed that 100 byte threshold per game.

(Note that there are some drawbacks with the above proposal.  For example, one of the inactive players who just wanted to load the save game and play through a few combat scenarios would have to ensure they switched from an external to the internal dice server to avoid artificially bumping the sequence number on the server.  Unless we made it hard for that scenario to play out, I can see a lot of players getting angry that they were accused of cheating because someone else simply wanted to play the save game when it wasn't their turn.  This might even be an issue today with email delivery, but the offending player could simply tell his opponents, "Ignore those rolls, I'm just playing around," or something.)

One final thought...  If we go stateful, it may require authentication on the server.  Otherwise, anyone could attack the server and cause it to persist lots and lots of data.  Those attacks could also affect the quality of the games themselves by, for example, changing the proposed sequence number, or, if the dice rolls themselves were stored, populating the database with dice rolls that were never really rolled by any of the participants.

I lied, one more thought...  Going back to the stateless approach...  What if, at least for PBF games, the dice server posted the results directly to the same thread being used for the game itself?  Then there would be a kind of parity between PBEM and PBF: PBEM dice rolls would be delivered via email, while PBF dice rolls would be delivered via forum.

**Comment by prastle** [comment]
Could we have a read only database for the dice results identified by the game id for when they need to be reviewed?  Perhaps it could be cleared once the game is finished and signed off by both players like the ladder?

**Comment by DanVanAtta** [comment]
Isn't this addresses already with Marti emailing the dice rolls? A player could compare the emailed dice rolls with a save game to verify they match.

**Comment by DanVanAtta** [comment]
Please re-open if there is more to discuss here.

**Comment by RoiEXLab** [comment]
I think the idea was to make the results publicly available, so they are actually stored in a db

**Comment by DanVanAtta** [comment]
Ah, thanks for the clarification @RoiEXLab 

I do think that would be a natural feature and would encourage any useful design notes/thoughts to be put up on the wiki.

I hope that features to track players game so we can have game stats would be coming along and eventually building on that to also track dice rolls would be a natural follow-up
