### ISSUE TITLE
Unintended paratroopers

### ISSUE THREAD

**Issue by panguitch** [triplea-game/triplea#445]
_From forum: http://tripleadev.1671093.n2.nabble.com/But-mommy-I-don-t-want-to-be-a-paratrooper-td7591187.html_

If you have an army that includes paratroopers and air transports, and you select all units and move them to attack a neighboring territory all at the same time, the engine automatically assumes the paratroopers rode the transport instead of walking. Assumes this even without going through the normal dialogue of selecting how many transports to board and which troops to board.

This matters because if AA shoots down the plane, the paratroopers die with it. But if the lazy bums had just walked, they wouldn't have gone down with the plane and could still fight.

This only happens if you move all units at once. If you move the paratroopers and the air transport separately, then the engine doesn't assume the paratroopers boarded the plane.

This gets really weird if your air transports can also have air battles.

1) air transports and paratroopers are in a territory that gets attacked by enemy planes
2) defender sends air transports into the air battle to fight those enemy planes prior to the main battle
3) enemy planes shoot down the air transport
4) paratrooper dies with the air transport, because the engine assumes the paratroopers were on board 

Bug only occurs if units are moved together. Moving either unit first prevents it.

Bug occurs if you shift-click, ctrl-click, or even click in the territory and select all units in the dialog that appears.

**Comment by ron-murhammer** [comment]
@panguitch - Yeah, I think paratroopers in general need some work. I'd eventually like to rewrite the entire transport system so air, sea, and land transports all share core logic and all function consistently.

**Comment by panguitch** [comment]
Sounds like a major undertaking. There are a couple of other odd things that have happened with paratroopers on Greyhawk Wars, but they're even more obscure than the two I've reported. If I can get a good handle on these others, I'll post them also. For the record at least, since I expect the complexity of the problem in relation to the number of maps affected makes paratroopers a lower priority.
