### ISSUE TITLE
Where to link the wikibook

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#448]
There is a lengthy wiki book: https://en.wikibooks.org/wiki/TripleA

IMO linking to it from in-game, and also from the website would be appropriate.

**Comment by williamdekryger** [comment]
@DanVanAtta What do you think about merging the Wikibook with other sources of documentation and hosting it on the website? I will soon begin gathering documentation from different sources to update and add to the website. Shall we add this to the list?

**Comment by ron-murhammer** [comment]
@DanVanAtta @williamdekryger - It would be nice to try and consolidate all the different manuals and wikis that are floating around into at least a single location. I'm guessing most people have no idea that wikibook exists...

**Comment by DanVanAtta** [comment]
I'm in favor of consolidation.
One drawback of website hosting is we lose the ability for community edit.  I would also bet that likely the last community edit of that wiki was some time ago.

So if we can find a new wiki engine that will run with jekyll, or something that will still allow wiki, I'm very much in favor of that consolidated to the website. Failing that, static text consolidated would be the next best thing IMO.

**Comment by williamdekryger** [comment]
@DanVanAtta @ron-murhammer I vote we create a repo called "docs" under our organization that we can use to host our documentation. I can write instructions for users to fork and send PRs. This is better than Wikibooks, because we can moderate our own docs.

The URL for the docs would then be http://triplea-game.github.io/docs. Once we get the domain set up, it could be http://docs.triplea-game.org, or any number of combinations. To sum up, I am proposing a second website which will be given the same look and feel as the main one, but focused on docs to make it easier for contributors. Thoughts?

**Comment by DanVanAtta** [comment]
Good idea. I wonder if we coudn't consolidate. Why not still use 'assets' rather than 'docs', similar for the website, why would it be a second one rather than re-using the existing one?

I'm on gitter if you'd like to chat.

**Comment by DanVanAtta** [comment]
@williamdekryger , can you make 'docs' be a section of the website? That would keep up us to one website instead of two. Otherwise I think the idea is good and you can run with it.

**Comment by DanVanAtta** [comment]
@williamdekryger , pls let us know what you would be planning

**Comment by williamdekryger** [comment]
@DanVanAtta @ron-murhammer I will be moving forward on website tasks as time permits. Please inform me what priority this task has, proportionate to the [download page](https://github.com/triplea-game/triplea-game.github.io/issues/6), which, though I haven't had much time to work on yet, is coming along. This specific task is actually fairly simple, though my plan is to consolidate *all* documentation to the website, including all of these (obviously updating obsolete information):
* http://tripleadev.1671093.n2.nabble.com/How-and-where-to-post-bugs-td3076194.html
* http://tripleadev.1671093.n2.nabble.com/Download-Maps-Links-Hosting-Games-General-Information-td4074312.html
* http://tripleadev.1671093.n2.nabble.com/Attentional-all-Apple-Mac-OS-users-must-read-to-be-able-to-play-td7580489.html
* http://triplea-game.github.io/files/TripleA_RuleBook.pdf
* http://triplea.sourceforge.net/mywiki/Installing
* https://en.wikibooks.org/wiki/TripleA
* http://triplea.sourceforge.net/mywiki/FAQ
* http://www.tripleawarclub.org/modules/newbb/viewtopic.php?topic_id=100&forum=1

**Comment by DanVanAtta** [comment]
download page is effectively top priority when it comes to the website IMO. We can remain with the scattered documentation for the next release, but personally I really want folks to use the website when they download the next stable.

@williamdekryger  - that's a good list : )
It'll be good to see consolidated docs. this issue is now "closed" since it's been answered and will be better tracked on the website trello board. Thanks.
