### ISSUE TITLE
Wrong About dialog displayed on macOS

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/triplea#4491]
### Engine version

1.9.0.0.13066

### My Operating System

macOS High Sierra 10.13.4

### Can you describe how to trigger the error?

Select the **Help > About** command from the macOS application menu.

### Actual Behavior

A vanilla macOS About dialog is displayed:

![Dialog Screenshot](https://user-images.githubusercontent.com/8350879/50678772-9b1e2800-1000-11e9-895d-12a66d3079e7.png)

### Expected Behavior

The custom TripleA About dialog (containing copyright and license information) should be displayed.

**Comment by RoiEXLab** [comment]
![Dialog Screenshot](https://user-images.githubusercontent.com/8350879/50678772-9b1e2800-1000-11e9-895d-12a66d3079e7.png)
With macOS High Sierra 10.13.4

**Comment by tvleavitt** [comment]
I can confirm that I'm seeing similar behavior with JDK 11 installed on a fresh install of Mojave (10.14.2) using the test installer.

![triplea about](https://user-images.githubusercontent.com/4445057/50719333-6b4a4100-104f-11e9-9cc7-635cf54162fe.png)

**Comment by tvleavitt** [comment]
Details. This only shows up prior to loading a map and starting to play it. Subsequent views show the custom "About" screen. Now, however, that this is also incorrect, in that if you load a new map, the "About" is not updated to reflect that.

![wrong about screen](https://user-images.githubusercontent.com/4445057/50720556-2ed51000-1064-11e9-9ba5-5b866c61936d.png)

**Comment by ssoloff** [comment]
@tvleavitt Thanks for the update.  Based on your above comment and the one you posted in #4455, my conclusion is that the problem described in this issue is not really a problem.  We are displaying the correct About dialog _when we've registered an appropriate handler_, which does not occur until the game window is displayed.  My error was that I did not realize the **Help > About** item would appear on the macOS application menu if we didn't register an appropriate handler.  Apparently, during those times when no custom handler is registered, macOS will register a default handler on our behalf that displays the default About dialog shown in the description of this issue.

It looks like our real problem is that we do not _unregister_ the About handler upon closing the game window.  I'll wait to see what @RoiEXLab's opinion is on this, but my inclination is to close this issue as "as designed" and open a new issue to ensure we unregister the About handler before returning to the main window.

**Comment by RoiEXLab** [comment]
Since the handlers _do_ work when registered and the linked issue will be fixed by this, I'm going ahead an merge this PR.
All the discovered follow-up issues can be addressed in future PRs.

**Comment by RoiEXLab** [comment]
Nevermind, wrong issue. I confused this with the PR.
My point still stands though, I'd suggest merging (because the listeners seem to work at least once) and address the discovered issues in a follow-up PR

**Comment by RoiEXLab** [comment]
Also to answer your question @ssoloff 
I would be fine either way: Closing this issue and reopening a new one, would be fine for me as well. But renaming this issue as we have identified the root cause would work for me as well.

**Comment by ssoloff** [comment]
Closing this issue in favor of #4517.
