### ISSUE TITLE
the wiki!

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#45]
Any guidelines or best practices for using and working with a wiki?  Second, given our current wiki, how are the pages coming up? I think the github workflow page could use some work to simplify it a bit, make it a cleaner to follow.

Are we needing any other important pages? 

To start the conversation with my thoughts, please speak if you have a different viewpoint:
I think the wiki is good for:
-  capturing  code documentation "stuff"  (descriptions of how to build, how to deploy, etc)
-  great place for organizing and summarizing results of discussions that occurred in github issues. 
- capturing decisions made

I do not think a wiki is good for:
- documenting the process of making a decisions, all the events and process and considerations, needs to be a summary thing
- not good for paragraphs of text, bullet points are good

Some best practices:
- do edit pages other people have created, seek that edits are always improvements
- do not get into edit wars, original author can revert edits, but before changing something back, always contact author
- favor using tables! It's easy to extend tables with more data, both more dimensions (columns) or more data points (rows).

**Comment by djensen47** [comment]
> not good for paragraphs of text, bullet points are good

A document that is nothing but bullets can also be difficult to read. :smile: Sometimes you need paragraphs to explain complex ideas: https://github.com/ReactiveX/RxJava/wiki/Backpressure and other times a wiki page can be only a single paragraph https://github.com/ReactiveX/RxJava/wiki/Observable

I think the Mosca project has a good balance: https://github.com/mcollina/mosca/wiki

The point is, say what you need to say. Be terse and to the point.

**Comment by DanVanAtta** [comment]
> Be terse and to the point.
:+1:

**Comment by DanVanAtta** [comment]
Does tripleA have a wiki already floating around somewhere?

Should the github wiki be *the* tripleA wiki?

**Comment by veqryn** [comment]
We do:
http://en.wikibooks.org/wiki/TripleA (most on how to play, how to use, etc)
and https://en.wikipedia.org/wiki/TripleA (general info about triplea)

I would imagine the github wiki to be about the code, config, project, and stuff surrounding that.
