### ISSUE TITLE
About handler not unregistered when leaving game

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/triplea#4517]
### Engine version

1.9.0.0.13066

### My Operating System

macOS

### Can you describe how to trigger the error?

1. Start TripleA and wait for main window to open.
1. Select **Help > About** from the menu bar.
1. Observe default About dialog:
  ![Dialog Screenshot](https://user-images.githubusercontent.com/8350879/50678772-9b1e2800-1000-11e9-895d-12a66d3079e7.png)
1. Start local game and wait for game window to open.
1. Select **Help > About** from the menu bar.
1. Observe map-specific About dialog:
  ![mac-about-dialog](https://user-images.githubusercontent.com/4826349/50726201-b740c880-10d7-11e9-9423-1f639b6a15bd.png)
1. Select **File > Leave Game** from the menu bar; answer **Yes** to prompt; wait for main window to open.
1. Select **Help > About** from the menu bar.

### Actual Behavior

The map-specific About dialog from step (6) is displayed.

### Expected Behavior

The default About dialog from step (3) should be displayed.

### Any additional information that may help

The About handler registered in `HelpMenu#addAboutMenu()` needs to be unregistered when closing the game window.

**Comment by tvleavitt** [comment]
As per my comment on #4455 (sorry, don't know how to link directly to it), under Java 8, and an older build, the About dialog isn't unregistered, but it does correctly pick up the fact that a new map has been loaded and a new game has been started (unlike under Java 11), so this is different behavior... the fix specified corrects the Java 11 problem, but I thought I'd mention this, in case the difference is an indicator that there's a larger issue or change in behavior between the two.

**Comment by ssoloff** [comment]
> sorry, don't know how to link directly to it

In the menu for each comment (the ellipsis in the top-right corner), there's an item called **Copy Link**.  You can use that to get a direct link to any comment within an issue/PR.

![copy-link](https://user-images.githubusercontent.com/4826349/50730512-02c99580-111d-11e9-82bf-19b4ae099356.png)

**Comment by RoiEXLab** [comment]
@ssoloff I didn't even know that. I always clicked on the the "xyz minutes ago" and copied the link from the url bar 😅
