### ISSUE TITLE
Path finding for train allows fields without tracks

### ISSUE THREAD

**Issue by sumpfralle** [triplea-game/triplea#4528]
### Engine version
1.10.13507

### My Operating System
Debian sid

### Map name
Total World War 1941 beta

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
When selecting a train and targeting a region that is reachable (within a distance of six), the preferred path suggests a shortcut (distance of five) through a region without train tracks. This move is impossible.

### Instead of this error, what should have happened?
No region without tracks should be taken into account when moving a train.

Attached you find a screenshot and a save game.
![triple-train-without-tracks](https://user-images.githubusercontent.com/1474141/50742581-8498ec00-120d-11e9-8839-93b1667e40f1.png)

[untracked-train.zip](https://github.com/triplea-game/triplea/files/2730964/untracked-train.zip)

**Comment by ron-murhammer** [comment]
@sumpfralle Works fine for me. I think you need a newer version of the pre-release to get all the route finding improvements. Here is what I get in the latest pre-release:
![image](https://user-images.githubusercontent.com/1427689/50742904-a9be3800-11d6-11e9-8b7c-3453d2dce344.png)

**Comment by sumpfralle** [comment]
Great!
