### ISSUE TITLE
ChangeLog Button on main screen

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#453]
Instead of showing a change log pop-up, how about we put a 'show changelog' button on the UI. This will then open the change_log file we have. 

- The pop-up is a bit intrusive, so it would be nice to remove it.
- The button helps people find the changelog information, let's say a person wants to skip it but later wants to review the details of the changelog.

**Comment by ron-murhammer** [comment]
@DanVanAtta - So I think we need both here. I think having the popup is useful as otherwise many people will never know what changed in the new version. But having the notes available to read after the popup is gone would be helpful.

**Comment by DanVanAtta** [comment]
I'm okay with having both

**Comment by DanVanAtta** [comment]
Change log is being moved to the website. Having it just be there for now seems appropriate, we can add links from in-game if it seems necessary.
