### ISSUE TITLE
PBF/PBEM not selectable in 1.10

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#4534]
### Engine version

Current master

### My Operating System
Ubuntu

### Map name
Any

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Click PBEM/PBF when starting a game.

### Do you have the exact error text? Please copy/paste if so
After selecting PBF info, login details are not enterable. Cannot start game.
PBEM is similar.

### Any additional information that may help
Seems to have gone wrong since 1.10.13537

**Comment by simon33-2** [comment]
Bisecting shows it has gone wrong between commits 1eed29e and a0d6519

**Comment by RoiEXLab** [comment]
I haven't added the info text for this yet.
You need to configure yoir credentials in the engine preferences
