### ISSUE TITLE
Travis: OS X build

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4546]
Noting a task and in case anyone wants to volunteer to take this forwards: https://docs.travis-ci.com/user/reference/osx

Looks like we can add builds that are run on a Mac, this can give us some additional test coverage and perhaps additional testing opportunities.

**Comment by tvleavitt** [comment]
I might be willing to take this on, the likelihood would increase substantially if the task were shared with a second individual. This is an area I'm interested in professionally, and I have some limited experience with this class of project already.

**Comment by DanVanAtta** [comment]
@tvleavitt awesome :smile: 

This specific task is potentially easy and is maybe a one-liner to the [.travis.yml](https://github.com/triplea-game/triplea/blob/master/.travis.yml) file

The effort here is mostly in:
- understanding what config to add to .travis.yml
- deciding on a reasonable config, there is some balanced between PR build time, failure rate, and test coverage
- ideally testing the travis build in a forked repository

@ssoloff : I'm pretty sure you have travis working against your fork, do you know of any documentation or steps that are available for how to configure travis to build branches from a forked repository?

**Comment by ssoloff** [comment]
> do you know of any documentation or steps that are available for how to configure travis to build branches from a forked repository?

Steps 1-3 at https://docs.travis-ci.com/user/tutorial/#to-get-started-with-travis-ci.

**Comment by DanVanAtta** [comment]
I think I can take this one off the back-log, it was pretty straight forward having had travis configured to build my repository fork.

Travis does not look to have a Java 8 JRE for Mac OS, build fails with:
```
Installing oraclejdk8
install-jdk.sh 2019-01-18 II
Expected feature release number in range of 9 to 13, but got: 8
```

For where Travis does have a JRE, Travis does not support postgres on the same image:
```
Installing openjdk11
Addon PostgreSQL is not supported on osx
```

The lack of postgres add-on seems like a deal break :disappointed:
