### ISSUE TITLE
Design for sub-projects: client-view and game-client

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4551]
I'd like to propose for design, two new sub-projects to help continue breaking up code.

### Goal

- remove dependency on game-core from game-headed and game-headless
- extract UI specific windows, models, controllers and configuration to their own sub-project

### Steps

Diagram below:

1. shows existing sub-projects
2. first phase, add two new sub-projects and begin migrating code 'up' the graph
3. remove/reduce dependencies to and from game-core

![dep-graph](https://user-images.githubusercontent.com/12397753/50947760-a20bc700-1454-11e9-9cf2-2bacbd79af3c.png)

### Notes

The 'temporary' dependencies in steps 2 are to help us migrate components gradually and avoid an all or nothing effort. Circular references between swing view code and model code will make this effort reasonably challenging.

**Comment by RoiEXLab** [comment]
Seems reasonable.
We might want to have single project for UI classes though instead of having a dedicated game-view project.

**Comment by DanVanAtta** [comment]
Agree @RoiEXLab , that would mean in the above diagrams we would drop the 'client-view' sub-project from each of the diagrams.

**Comment by DanVanAtta** [comment]
Okay, I remember now why 'client-view' was interesting; The idea behind that was to have one place for just the UI related code. There would also be code that is universal between the different UI's but unique to a headed client. For example, the map download model and infrastructure is unique to headed clients but we will have multiple UIs for it. The goal was to also help keep any UI code very cleanly split from model code.

**Comment by DanVanAtta** [comment]
Evolving this idea, I can see a lot of utility to split the `client-view` to ui specific sub-projects. Eg: `ui-swing`  `ui-javafx`

Benefits:
- dependencies are cleanly split
- build artifacts will contain only what they need
- FWIW, I think it's simpler to have one main output artifact from a project rather than many, IMO 1:1 between project and build artifact is perhaps ideal.


An updated "step 3" diagram would look like this:

![client-packages](https://user-images.githubusercontent.com/12397753/51633803-60c0f000-1f07-11e9-8980-47477beb8db2.png)

**Comment by DanVanAtta** [comment]
Thinking how the game-headed project would be organized, I'm thinking we'll have things like:

```
org.triplea.<feature>.featureViewModel.java
org.triplea.<feature>.view.swing.featureWindow.java
org.triplea.<feature>.view.javafx.fxFeatureWindow.java
```

That leads to this as the latest:
![screenshot from 2019-01-23 12-48-35](https://user-images.githubusercontent.com/12397753/51636095-3b36e500-1f0d-11e9-96d9-d5dc9a0673ef.png)

**Comment by DanVanAtta** [comment]
Diving into this more, the original client/server architecture is pretty strong and should be accounted for, a single 'game-client' package I do not think is enough. Splitting the server/client, we get (again with yellow being new sub-project):

![client-server](https://user-images.githubusercontent.com/12397753/51637312-4c352580-1f10-11e9-9409-a3efde37c8b7.png)

**Comment by RoiEXLab** [comment]
👍
