### ISSUE TITLE
lobby.game.reconnection time does not seem right

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4552]
https://github.com/triplea-game/infrastructure/blame/df6f175c5df7d9c8ded00142b7ffdd61be742d68/roles/application/bot/files/run_bot.sh#L57

```
 -Ptriplea.lobby.game.reconnection=172800 \
```

Lot of seconds, 2 days. 

This is a tracking ticket to discuss/rework/update/understand this property.

At issue, why is the reconnect time in days? Seems like an excessively large value. If the value is that large, is it working properly?

**Comment by ssoloff** [comment]
> If the value is that large, is it working properly?

Yes, as evidenced by the failure reported in #4102.

**Comment by RoiEXLab** [comment]
I was surprised by this as well.
I was assuming the reconnection time would be minutes

**Comment by DanVanAtta** [comment]
Linking this issue to PR, some more context behind this property is at: https://github.com/triplea-game/triplea/pull/4545#discussion_r247332872
