### ISSUE TITLE
Code Format Automation Problems

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4564]
After I had some time free up and was able to dive back into TripleA, it did not take long to see from afresh places where TripleA development really works against you, slowing and frustrating development. Automatic formatting jumps out right away as it is one perhaps the most frequently out of anything, it is a task encountered at every line and at  every character of code.

## Problem 1: incomplete formatting rules (hand-formatting still required)
- Auto-format does not nicely format multi-line builders, streams, or parameters
- Because we can and need to hand-format, it's one more thing to review.

## Problem 2: auto-format does not guarantee checkstyle formatting violations are fixed
Any formatting checkstyle violation should be fixable by running auto-format or code-cleanup. Currently at least auto-format does not automatically correct javadocs to comply with the checkstyle rules

## Problem 3: Triplea development in IDEA is extra tedious due to problems with 'save-actions' + 'eclipse-formatter' plugins
  1. IDE performance degradation, everything just gets slower - seems mostly related to save-actions plugin
  2. Save-actions does not always use eclipse-formatter plugin correctly. It's odd, save-actions can sometimes use the built-in formatter instead of the eclipse-plugin formatter. I do not know how to repro this, nonetheless it is pretty annoying and can lead to hand vs auto-formatter fights (given a checkstyle violation is at stake, it can't be ignored!)

## Ideal Requirements for any Solution:

1. Automated formatting of code, let us focus on the code, not the format
  - Remove need for hand-formatting
  - Remove need to review for formatting (in other words, enforce auto-formatting and remove hand-formatting)
2. No unreasonable or noticeable performance degradation for either Eclipse or IDEA

## Alternatives to Investigate

- Different formatter plugin, eg: google-java-format
- Update Eclipse format configuration

## Concerns
- How much will it cost to get a configuration that formats exactly right, or even reasonably well?
- How much will we pay for long-term maintenance costs? If we fork a plugin, what happens when it is updated and IDE versions are 3 years in the future? How much addition/removal/configuring of configuration files will we need to do over the next 3, 5, 10 years?

**Comment by DanVanAtta** [comment]
Chatting with @ron-murhammer , I think we can find a solution by evaluating these three questions:

***1.*** How many times does 100 vs 120 make a difference with google-java-format line wrapping rules?
***2.*** What will the cost of a fork of google-java-format plugin look like, how difficult will it be to create an updated plugin?
***3.*** Exactly how painful is the custom plugin to install for dev?

If anyone can get a clean answer to (1), that would be appreciated.  

My strategy to answer (1) was to build a plugin, format to 100, then format to 120 to see the diff. Only problem - going from 100 to 120 yielded ***no*** diff :scream_cat: !!   I'm not sure where I went wrong in building a plugin, FWIW the steps I took were:
- fork the [google-java-format repo](https://github.com/google/google-java-format)
- change the [source code for line length](https://github.com/google/google-java-format/blob/master/core/src/main/java/com/google/googlejavaformat/java/JavaFormatterOptions.java#L33)
- run:  `mvn -Dmaven.test.skip=true install` from top level folder
- run: `./gradlew buildPlugin` from the plugin folder
- Generates a zip file in a `distributions` folder which works to install the plugin from IDE.
- install ZIP in IDE, restart

**Comment by DanVanAtta** [comment]
Let's put this to a vote:

### Options

(A) Status Quo -> old school introduce local variable and hand formatting.

Because example (1) looks so bad, we can't even say that we are coming out even with the status quo, everyone doing any active work in TripleA will need to put in work to add and enhance the formatting beyond what the auto-formatter can do. 

(B) Google java format

We get removal of hand-formatting, we get better line-breaks, the plugin is easy to install, the spotless configuration update is a one-liner. 

(C) Improve current formatter

Feasible, but I suspect we'll add a lot of rules to always break when breaking is optional. If we like long lines to avoid unnecessary line breaking, it does not seem like this would actually be a good way to achieve that style preference.

(D) google java format fork

I've strong concerns over maintenance, updating the fork every time there is an IDE major release and keeping things working and updated.

## 

Shall we vote on the options?

TBH I would also expect for us to vote based on what kind of volunteering and effort we would want to put in. With option (A) I would expect to see periodic PRs going through the code base to maintain and fix the formatting. Similar option (C) and (D) I would expect effort to keep up the rules/configurations.

**Comment by DanVanAtta** [comment]
@RoiEXLab you had a strong opinion on line length, need your input on this one for sure.

**Comment by DanVanAtta** [comment]
*edit* shortened down voting options, status-quo and custom plug-in I think should be ruled out. The latter being a good idea, but side-by-side with improving formatter we should pick improve the formatter.

**Comment by RoiEXLab** [comment]
Hard question.
While I completely agree that having multiline statements without local variables is a desireable thing when writing new. modern code, there are still an awful lot of places where 100 chars will probably to short.

The other part that bugs me a little bit is kind of "lazyness" in the sense that when I joined this project I already had to change my own convention to suit the one we're currently using (which has actually become the one I'm now using almost exclusively, but that's a different story) + I'm already following a completely different convention at work, so having that convention change again is not the most prefferable thing to do.
So as long as adjusting our current formatter can be done with "good enough" results in a reasonable amount of time, I'd actually prefer that over adopting a different convention.

**Comment by DanVanAtta** [comment]
To one extent I think it is perspective. With current formatter the job is:
- run auto-format
- hand fix anything that is not clean.

When formatter makes all decisions, there is no step 2. We just run auto-format. Anything hand-formatted is reverted by the plugin. It is easier to configure and makes nearly all format decisions. I think it'll be difficult to create a good-enough format configuration that will match that. Even if we can, line length is just one of many examples where we would need to figure out what is good-enough and that will take a lot of effort to come to those decisions and will leave more conventions to learn compared to all formatting being automatic.

I propose we give google-java-format a try for 3 months. If it does not work out nicely enough, we can craft some formatter rules and switch. In that scenario we'll have fixed nearly all existing formatting SNAFUs and will be in a better place than where we are now. Are you willing to give that a shot @RoiEXLab ? I honestly think the automation and consistent formatting will make it easy and a non-event when getting used to it.

**Comment by DanVanAtta** [comment]
Worth mentioning, thanks for feedback/discussion @RoiEXLab . I would also consider the perspective of a new devloper and what would most easy for them. Something that is fully automatic and easier to setup, or something that leaves for some conventions to be learned?

**Comment by RoiEXLab** [comment]
@DanVanAtta I guess there's nothing speaking against giving it at least a try

**Comment by DanVanAtta** [comment]
@RoiEXLab considering the move further, there is for sure an upfront and one-time cost to switching. Notably merge-conflicts if there is any in-flight work.

To this extent, I would note that long term costs, no matter what size, will tend to dwarf just about any one-time cost (simply keep adding a year and eventually costs add up). It's akin to pulling off a band-aid. I'm not sure if we'll be so willing to do that twice.

**Comment by DanVanAtta** [comment]
@RoiEXLab this is still something I'd like to do. The benefit is:
(1) commentary is automatically formatted. I have to fight with the current formatter whenever I put line breaks in javadoc.
(2) plug-in applies format settings for you. With the eclipse plugin, by default you get 4 space indents for example and have to rely on formatting to get to the right spacing. That means any new line you go back to 4 space and have to be sure to hit format. It gets to be a bit much whereas the plugin does the right thing and new lines are generally formatted already.

Number (1) above is a very strong reason for me, I avoid new lines in javadoc commentary because of the issues and can run into situations where the applied format will never agree with checkstyle.

I don't think I'll be able to get this done anytime too soon though. To complete this we simply need to see which checkstyle rules need changing after running a mass format.

**Comment by DanVanAtta** [comment]
Closing in favor of #4940 and eventaul cut-over to google java format that will resolve this issue.
