### ISSUE TITLE
Prefix player-type

### ISSUE THREAD

**Issue by ZjelcoP** [triplea-game/triplea#457]
The new website sends me here for feature requests, so I guess it's open now?
Had a similar request in sourceforge page, but not sure that is being checked...

Request:

Have the option to determine the type of player in the XML or somewhere else, with "editable" selectable to "false".

Some maps only work properly as designed with a specific playertype assigned to a nation.
-Only Human
-Only AI
-Only do-nothing AI..

Presetting the Type of AI could be troublesome if you're going to change the available AI's.
Maps having this would possibly have to be updated with new choices.

Example of map benefitting: Tutorial.
Map needs Germany and Italy Human, all others AI. Already have all AI-players named AI_etc. This is a pretty ugly solution, simple "Russia" looks much better than "AI_Russia". Most important: it is not fail-safe...
Had a mate playtesting it and he changed some of the playertypes. Completely screws up the scenario. I currently know no way of preventing people from doing that. Putting it in Game-notes only works for those that actually read it...

Besides this one there are more maps benefitting from this, specifically 1 player maps.
Feudal-Japan: set all to AI, player only needs to change 1 nation to human.

**Comment by ron-murhammer** [comment]
@ZjelcoP - Agree. Having more options for defaulting player and constricting selectable players for each country would be nice. And yeah definitely separate XML parameters, none of the prefix crap :)
