### ISSUE TITLE
LGTM account

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4588]
I was a bit confused and thought @ron-murhammer was pointing out a LGTM violation: https://github.com/triplea-game/triplea/pull/4580#issuecomment-454606123

I'm wondering if this is due to API-key, and if we can use builder-bot?

**Comment by ron-murhammer** [comment]
@DanVanAtta Not sure but yeah, I put it under my account when I set it up as we were kind of testing it out then never changed it.

**Comment by DanVanAtta** [comment]
NP, please message me in gitter if you have any trouble using the bot account

**Comment by DanVanAtta** [comment]
@ron-murhammer I think you are the only one that can resolve this, assigning to you for next steps to switch LGTM accounts to the triplea bot account.

**Comment by ron-murhammer** [comment]
It doesn't appear that I can set the triplea bot account to post instead of my account as it must be an owner or admin of the repo.

**Comment by DanVanAtta** [comment]
Thanks for checking @ron-murhammer . I do not think it's worth elevating bot account perms for this reason, it has not come up too often. Seems like the issue is at an impasse, let's revisit if it comes up more often.

**Comment by RoiEXLab** [comment]
What happened to the LGTM Pull Request integration? I just realised it's missing.

**Comment by ron-murhammer** [comment]
@RoiEXLab Opps. I had deactivated it when trying to switch to the bot account. I just re-enabled it.

**Comment by RoiEXLab** [comment]
I almost assumed something like that because the timing was about right.
Thanks for fixing 👍
