### ISSUE TITLE
TripleA should have a feature to change lobby password

### ISSUE THREAD

**Issue by KJRNorway** [triplea-game/triplea#4592]
I would like to change my TripleA lobby password. I was told that Prastle was the only one who could do that, but he said that it was impossible. I suggested that he could remove me as an account, and then I could create it again, but that was not so easy I understand. And he also noted that it was a good feature request. So that is what I am doing now. Please make a way to change the password to the TripleA lobby. I would also like to suggest where it should be. When we start the TripleA window, one of the buttons is "Play Online". That starts an other window. this is where I believe the "Change password" button should be.

**Comment by panther2** [comment]
@KJRNorway 
You can change your password using the "Update Account" dialogue from the Account menu:
![account](https://user-images.githubusercontent.com/20812775/51326712-0d1a5680-1a70-11e9-9851-d3593f2125a2.PNG)
Simply enter the new password twice in the above dialogue.

However for doing this you of course need to be logged in to the lobby, what requires that you still know your current password for doing so.

So what is needed appears to be an easy workflow for resetting your password in case you have forgotten it.

**Comment by DanVanAtta** [comment]
This has been implemented: https://github.com/triplea-game/triplea/pull/4991 and should be available in the next release

**Comment by DanVanAtta** [comment]
Ah, I might have misread this request. #4991 is a password reset in case you forget your password; you can have a temporary password sent to your email.

Otherwise @panther2 is correct and the option to change password is available from the lobby menu.

**Comment by prastle** [comment]
@DanVanAtta  Yes they need an easy password reset sent to their registered email in the database.  Or an easy way of it being done from the toolbox when they have forgotten their password.
