### ISSUE TITLE
Automated Host Full Reset (1.9.0.0.13066)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#4596]
(the TripleA version referenced in the title is merely the current stable; I don't actually know what version the specific host is actually running, or what versions the players in it were using)

A few minutes before now I had this complaint in lobby, about Bot407_ATLANTA_GA suddenly disappearing, kicking or ghosting anyone out of it, and reappearing after a few minutes, but without any saves of the game in it. Consequently, that host's players lost the ability to continue their game. The game was "World At War". I also verified that the bot figures as started in 22.57, that is a few minutes after the issue came out, and seem to have completely lost its chatlog of whatever happened in it beforehand.

Lobby Chatlog:

> (22.54.08) Betar1:  hey
> (22.54.13) Betar1:  charles the scot
> Pherman1215 has joined
> (22.54.15) Betar1:  hey can u plz save
> wirkey has joined
> FearsomeChutoy4 has left
> LouisXIVXIV has joined
> (22.54.30) Betar1:  when kingcharles kept joining and leaving it screwed up game for me
> (22.54.34) Pherman1215:  bot 402 Louis
> Defka has joined
> MrTieGuy has left
> (22.54.47) Betar1:  hey
> (22.56.14) CharlestheScot:  yes, it is locked up
> (22.56.16) Betar1:  werent we 407
> (22.56.19) Betar1:  i cant find the bot now
> (22.56.20) Betar1:  :(
> (22.56.24) Betar1:  did u save?
> (22.56.26) CharlestheScot:  i cannot save either righ t now
> (22.56.30) Betar1:  i tried to save, it may have worked not sure
> jmelvin has left
> (22.56.41) Betar1:  are they updating 400 bots or something?
> (22.56.47) Betar1:  lets try 306
> (22.56.51) Betar1:  ill see if i can load my save
> (22.57.11) CharlestheScot:  i will stay here and guard...
> rdot4 has joined
> Umbrella has joined
> (22.58.00) Betar1:  ok
> (22.58.43) Betar1:  cant load it
> (22.58.47) Betar1:  You were slapped by Betar1
> (22.58.51) CharlestheScot:  You were slapped by CharlestheScot
> (22.58.53) Betar1:  hey can a mod please help us?
> (22.58.56) Betar1:  we cant save our game in 407
> (22.59.01) Betar1:  and now i am locked out of the bot
> (22.59.06) Betar1:  charlesthescot is in the bot but cannot save
> (22.59.15) Betar1:  You were slapped by Betar1
> (22.59.19) wirkey:  taking a look
> (22.59.22) Betar1:  thank you
> (22.59.34) Cernel (1):  407?
> (22.59.39) CharlestheScot:  yes
> (22.59.40) Betar1:  yes i cant find it now
> (22.59.44) Betar1:  the bot is locked up
> (22.59.49) Betar1:  it doesnt seem to exist anymore
> (22.59.58) Cernel (1):  407 is there
> (23.00.03) Cernel (1):  and none of you is in it
> (23.00.18) CharlestheScot:  i am here
> (23.00.19) Betar1:  oh now it reappeared i swear it wasnt there before lol
> (23.00.34) Betar1:  i jusst joined 407 and charlesthe scot isnt there
> (23.00.42) Betar1:  but he i think is in a different iteration of 407 i guess
> (23.00.51) Cernel (1):  also it is revised
> (23.00.54) Betar1:  he never left 407 afaik and thats where we were playing before
> (23.00.57) Cernel (1):  so if you were not playing revised
> (23.00.58) Betar1:  yeah its a world at war game
> (23.01.01) Cernel (1):  your save is not ther
> (23.01.06) Betar1:  :(
> (23.01.12) Betar1:  charles are you still  in 407?
> (23.01.23) CharlestheScot:  i am still in 407, will it come back?
> (23.01.28) CharlestheScot:  with the waw save/
> (23.01.31) CharlestheScot:  ?
> Jpablo has left
> (23.02.07) Betar1:  what roudn was it charles
> (23.02.14) CharlestheScot:  13
> (23.02.17) Betar1:  hm
> (23.02.21) CharlestheScot:  Yama
> (23.02.23) Cernel (1):  407 is here in the lobby and all the saves are revised
> (23.02.26) Lafalot:  407 shows a revised game CS
> (23.02.35) Betar1:  this is so strange
> (23.02.54) Betar1:  idk what happened.. this guy came in and out of our bot a few times and instantly i couldnt click anything
> (23.03.04) Betar1:  and then the bot disappeared because i couldnt see it in the list
> (23.03.19) Betar1:  and now the game is revised but charlesthescot is still in it with our world at war game
> (23.03.29) Lafalot:  yer Bot appears to be gone
> (23.03.37) Cernel (1):  I can tell you the bot has reset completely
> (23.03.43) Cernel (1):  even the log is completely gone
> (23.03.51) CharlestheScot:  this call for wirkey !
> (23.04.07) Betar1:  ok thank you for checking and helping cernel and wirkey
> (23.04.22) Betar1:  charles can u please try to save the game once more?
> (23.04.33) Betar1:  if you cant save it lets just reload latest in another bot ok?
> (23.05.44) Betar1:  brb restarting laptop
> Betar1 has left
> peirce has left
> (23.07.03) CharlestheScot:  yes
> Betar1 has joined
> (23.07.30) Betar1:  any luck with saving it?
> (23.07.36) CharlestheScot:  no
> (23.07.42) Ondis:  Great Scot!
> (23.07.48) Betar1:  reload latest in different bot ok?
> (23.07.51) Ondis:  someone is looking for a scot though not this scot
> (23.08.22) CharlestheScot:  the one from Inverness
> (23.08.29) Betar1:  whats that?
> (23.08.30) CharlestheScot:  yes B
> (23.08.31) Betar1:  what is inverness
> (23.08.50) CharlestheScot:  north of Edinburgh
> (23.08.57) Betar1:  oh you were talking to him
> (23.09.01) Betar1:  ha h sorry
> (23.09.10) Cernel (1):  You just slapped rdot4
> (23.09.12) Cernel (1):  hey rdot4 is it you that loaded that revised round 8 or 9 game in bot 407?
> (23.09.21) Betar1:  shit charles what the latest save you have?
> (23.09.25) Betar1:  charles 502 plz
> (23.10.17) CharlestheScot:  hang on, my save is rd 12, royal pain in the ass
> (23.10.25) Betar1:  fuck
> (23.10.26) Betar1:  me too
> (23.10.29) Cernel (1):  You just slapped rdot4
> (23.10.30) Cernel (1):  You just slapped rdot4
> (23.10.31) Cernel (1):  rdot4 what did you do in bot 407, if anything?
> (23.10.54) Betar1:  i dont understand wtf happened
> (23.10.56) CharlestheScot:  B, careful of language in lobby please
> (23.11.00) Betar1:  oh ya sry
> (23.11.56) CharlestheScot:  Cernel is it possible that a version is live in the save modes of 407
> (23.12.26) Betar1:  we lost about an hour of game play
> (23.13.19) CharlestheScot:  not the end of the world, lets see what plays out
> (23.13.30) Betar1:  charles what do you wanna do? can we please reload latest we have and just reenact what we did before?
> 

Bot407_ATLANTA_GA chatlog:

> --- rdot4 has joined ---
> --- wirkey has joined ---
> --- Cernel (1) has joined ---
> --- Betar1 has joined ---
> --- rdot4 has left ---
> --- Betar1 has left ---
> --- Lafalot has joined ---
> --- Lafalot has left ---

Screenshot:
![20190119_01](https://user-images.githubusercontent.com/19562310/51432964-1dcdf680-1c41-11e9-8b4c-51c36cbfbca0.png)

All the host's autosaves in it are round 8 or 9 of World War II Revised, while the players affirm they were playing World At War, in it, shortly beforehand.

It is not the first time something like this happen, and I would say it's a pretty big deal, as you just totally lose the game you spent time in.

**Comment by Cernelius** [comment]
So, it seems that the two hosted players were using TripleA versions 1.9.0.0.13066 and 1.9.0.0.12226.
The one in 1.9.0.0.12226 also affirms to be on a Mac terminal.

Lobby chatlog:

> (23.30.43) Cernel (1):  You just slapped Betar1
> (23.30.45) Cernel (1):  You just slapped CharlestheScot
> (23.30.46) Cernel (1):  just for the record can you both tell me what version of triplea you were using?
> (23.30.48) CharlestheScot:  thank you Cernel
> (23.31.26) Navalland:  did you abandon "the realistic values of territories" topic? I was very interested in.
> (23.31.32) GeneralEmCgee:  I really wish I could send you my laptop so you could figure it out Wirkey :p the Triple A save file is hiding very well
> (23.31.41) wirkey:  General, which save can't you find?
> (23.31.44) GeneralEmCgee:  ALL OF THEM
> (23.31.50) wirkey:  the one i sent you or the one you want to sent to me?
> (23.31.55) wirkey:  lol
> (23.31.57) GeneralEmCgee:  the save file is never there when I go to open it up and send a file
> (23.32.05) GeneralEmCgee:  but it's there when I start the game
> justinnissen has left
> (23.32.19) wirkey:  you use windows or mac?
> (23.32.23) GeneralEmCgee:  windows 10
> (23.32.23) Cernel (1):  You just slapped Betar1
> (23.32.30) Cernel (1):  You just slapped CharlestheScot
> (23.32.31) Cernel (1):  hey, so can you tell me what version of triplea you are using?
> (23.32.40) Cernel (1):  it should be something like 1.9.0.0.x
> (23.32.43) Cernel (1):  what is x?
> (23.32.57) wirkey:  ok, press your windows key + e
> (23.33.18) GeneralEmCgee:  9687
> (23.33.31) Cernel (1):  I was asking betar and charles
> (23.33.50) CharlestheScot:  .13066
> (23.34.05) GeneralEmCgee:  0.o sounds like I need to update
> (23.34.17) wirkey:  no, it'S not in the folder with the game itseld
> (23.34.31) Cernel (1):  yeah it's usually safer to be on latest stable, that should be what the bots run
> votato has left
> (23.34.48) Cernel (1):  You just slapped Betar1
> (23.34.49) Cernel (1):  so betar you can open triplea on local to know what version you have
> (23.34.50) wirkey:  do you have any folder on your computer with something like own files?
> (23.35.22) wirkey:  come to 506, so we don't have to interfere with Cernel
> Rumrem has joined
> (23.35.37) GeneralEmCgee:  son of a bitch thanks Wirkey lmao
> (23.35.42) GeneralEmCgee:  it was in my named folder
> (23.35.53) GeneralEmCgee:  was wondering wtf was going on
> (23.35.57) wirkey:  lol
> votato has joined
> (23.36.11) wirkey:  you are probably not a tech nerd
> (23.36.12) Cernel (1):  btw you can knwo and even customize your savegame folder if you click on Engine Preferences
> justinnissen has joined
> (23.36.44) Cernel (1):  You just slapped Betar1
> (23.36.45) wirkey:  don't tell him that, it will probably confuse him even more :-)
> (23.36.50) Betar1:  hey
> (23.36.57) Betar1:  sorry sound was off 
> (23.37.00) Cernel (1):  what version of triplea you are using
> (23.37.01) Betar1:  whatsup?
> (23.37.06) Cernel (1):  you can open it on local
> (23.37.14) Cernel (1):  and see it will say 1.9.0.0.x
> (23.37.15) Betar1:  12226 i think
> (23.37.20) Betar1:  which is strange
> (23.37.21) Cernel (1):  ok can you check it out?
> (23.37.26) Betar1:  i just did
> (23.37.29) Cernel (1):  ok
> (23.37.33) Betar1:  in about triplea think
> (23.37.34) Betar1:  thing*
> (23.37.37) Betar1:  on top left
> (23.37.38) Betar1:  i ghave a mac
> (23.37.45) Cernel (1):  so it says 1.9.0.0.12226?
> (23.37.50) Betar1:  i am 90% sure i downloaded the 13. one a few weeks ago
> jeep has joined
> (23.38.17) Betar1:  yes
> (23.38.20) Cernel (1):  ok
> (23.38.20) Betar1:  that is what it says
> (23.38.25) Cernel (1):  tx
> (23.38.26) Betar1:  1.9.0.0.12226
> (23.38.28) Betar1:  np
> (23.38.30) Betar1:  thank u

**Comment by Cernelius** [comment]
Just verified that same bot has still the chatlog and the started time decurring from that same point and, by reading the chatlog, it doesn't appear it had any further problems, so far.

![20190120_01](https://user-images.githubusercontent.com/19562310/51444085-21ba5100-1cf3-11e9-9c9f-d7e667c09ee1.png)

**Comment by RoiEXLab** [comment]
I just searched the logs, but I didn't find anything unusual there that would explain why the bot locked itself up.
However I saw a lot of EOFExceptions that would explain why no savegames could be loaded, indicating that something went wrong when saving them in the first place.

**Comment by RoiEXLab** [comment]
I don't think the chatlog is permanently saved, just in memory.
So yes, I'd have expected it to "lose" the log.
However the important things are logged into a more or less permanent way, spso we can still look stuff up after.

**Comment by DanVanAtta** [comment]
@Cernelius @RoiEXLab , is this an active issue, or should we close for now and focus on new incoming issues?

**Comment by Cernelius** [comment]
I didn't have this problem, as I'm not an automated host user, nor I cannot reproduce it myself.

But as a lobby user I can say that it is a seldom but recurring occurrence that people complains in lobby that:
1. They crashed.
2. The automated host has disappeared.
3. After a few minutes the automated host comes back, but without the savegame.

Anyways, I suppose this can be closed, if nobody has any insight into it. It was more of a notification than anything else, and the people experiencing this problem should really report themselves (which they never do).

@RoiEXLab appears to have seen the root of the cause, in the EOFExceptions indicating failures in autosaving, that I assume is the reason why the people didn't at least get to have their autosave, when the host was back.

**Comment by DanVanAtta** [comment]
@Cernelius logs are only kept for a few days on papertrail, and on servers they are kept for longer but limited for how long (we'd have to know exactly which server to look at). Hence unless we have the exact exception and stack trace recorded, by now they will have been lost.

I dug through recent examples of bot exceptions in logs and saw three classes of exception, one is a EOF. It looks like the error handling is there to at least not cause a crash, but there still was a small improvement to be made, coded and submitted here: https://github.com/triplea-game/triplea/pull/4684

The other two exceptions look more to be standard events that are being instead noted as errors (so those just need a messaging tweak). 

As far as I can tell that chases down all active leads that we have. Any new instances are IMO still worthwhile to report as we can confirm if we are seeing something new.
