### ISSUE TITLE
Code duplication between (Legacy) Swing UI and (in-flight) JavaFx UI 

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4599]
### Context and Concern
Model logic is duplicated between Swing UI and Java FX UI as [noted in PR4591](https://github.com/triplea-game/triplea/pull/4591#discussion_r249920107)

### Problems Because of this
- duplication increases maintenance cost, we duplicate code, add overhead to ensure consistency, and we duplicate testing.
- we make worse the design problems where we have view and controller+model code mixed together, solving that problem becomes more difficult as we gain two copies that can start to drift, rather than first fixing it for one set of UI code to then use the same model backing to graft a new JavaFx view.

### Desired Outcome
Group decision that this is a problem and general consensus that Swing UI and JavaFX code should not duplicate one another.  Specifically the Swing UI and JavaFX componentsare both views, they are different, if they have duplicated code it means we're mixing model and controller logic concerns in with our view and we should extract that.

### Some Discussion points / Possible Solutions
Not a silver bullet, but I've been thinking that a mix of view-model patterns presented by Martin Fowler could help here:
- [Presentation Model](https://martinfowler.com/eaaDev/PresentationModel.html)
- [Supervising Conteroller](https://martinfowler.com/eaaDev/SupervisingPresenter.html)

**Comment by ssoloff** [comment]
The JFX client hasn't seen active development in over a year.  Unless we're planning on restarting that soon, this discussion is probably premature.

**Comment by DanVanAtta** [comment]
This is pertinent in context of: https://github.com/triplea-game/triplea/issues/4551, notably how we arrange code between modules. Le's continue this thread of discussion in #4551
