### ISSUE TITLE
Add UI feedback when the computer is thinking 

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#460]
It's hard to know what is happening when the game is paused. Is it the AI wait duration, or the is the AI 'thinking'. For this ticket, let's add some feedback somewhere in the UI that displays the current status, what is happening in the game, whether it is pausing or if it is 'thinking'

For some background conversation #300

**Comment by ron-murhammer** [comment]
Agree. Would be great to get some sort of 'progress' bar though even just something that is spinning to show things aren't frozen would be good.

**Comment by DanVanAtta** [comment]
Dupe of #299
