### ISSUE TITLE
Is there a good solution for incorrect synchronization?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4618]
## Problem

- TripleA makes significant use of synchronization and locking. It's unclear how much of this is actually needed and correct

## Desired outcome

- Brainstorm if there any good ways to identify unnecessary locking so that it can be removed. 
- Brainstorm ways to avoid needing locking, eg: immutables

## Context
- Came up recently in a PR: https://github.com/triplea-game/triplea/pull/4590#pullrequestreview-193468547
- TripleA locking makes it hard to reason about the code, it's a significant tech debt item in the code base.

**Comment by RoiEXLab** [comment]
I think most of the time, even if the locks have an actual purpose, they lock way too much, more than what would actually be needed.
So I guess a good alternative might be to use synchronized collections as mid-term solution, which allow us to drop unecessary code, and only lock when the collection is actually being accessed.

However I don't think theres a single "good solution" for this. What might be interesting though is checking if there's a commit that introduced synchronization explicitly, or if it always existed so far.

**Comment by DanVanAtta** [comment]
I suspect the answer here is that we'll need to redesign how locking/synchronization is done and rewrite code that has a simpler mechanism.
