### ISSUE TITLE
Lobby DB backend

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#463]
Talking to Bung, admin of tripleawarclub, it would be useful to have a DB that can 'talk' with PHP more easily compared to Derby DB. Any suggestions?

My two suggestions are MySQL or PostGreSQL. PostGreSQL if I had to pick one.

**Comment by ron-murhammer** [comment]
@DanVanAtta - Agree though no idea how much work it would be to replace. I'm fine with either MySQL or PostGreSQL though I have more experience with MySQL so would probably vote for that.

**Comment by DanVanAtta** [comment]
We can re-raise this issue when someone is serious about doing it. A shared login between warclub and lobby would be one goal of such a change.
