### ISSUE TITLE
SLF4J no-op logger being used on http server

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4675]
### Engine version
1.10+

### My Operating System
n/a

### Map name
n/a

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Launch the http-server

### Do you have the exact error text? Please copy/paste if so
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
### Instead of this error, what should have happened?
No error message, use a non-NOP logger

**Comment by DanVanAtta** [comment]
Probably simplest fix is to include a SLF4J logger for http-server. I think we should do that across the board and switch/prefer to use the SLF4J API:
- nicer API compared to java.util, for example `log.warn("message", exception")` rather than `log.log(Level.WARN, "mesage", exception)`
- better names for debug levels, "debug" "trace" "info" make more sense compared to "fine" "finer" "finest"
- SLF4J hides the underlying logging implementation, we wouldn't have this problem going forward
- logback offers better performance than java.util.logging

Searching around for some references, this is an interesting read on the topic:
https://blog.overops.com/is-standard-java-logging-dead-log4j-vs-log4j2-vs-logback-vs-java-util-logging/

> Only 4.4% of projects exclusively used the java.util.logging naming scheme.

> This post stresses out that java.util.logging is, well, practically dead. Most serious projects choose to go with 3rd party logging frameworks.

**Comment by RoiEXLab** [comment]
I fixed this problem in my pr, by just including a dependency:
https://github.com/triplea-game/triplea/pull/4148/files

**Comment by DanVanAtta** [comment]
I think with some mass `sed` work we can switch over to using SLF4J predominantly without too much sweat. Are there any strong preferences that we continue to use the `java.util` logger API rather than SLF4j?  (cc/ @ron-murhammer @ssoloff)

**Comment by DanVanAtta** [comment]
PR is up to fix this problem.
Otherwise only left to be discussed would be logger API switch, I think we can hold on that for right now while other initiatives land.
