### ISSUE TITLE
Delete 'PR:Preview Label' - Github now has draft pull requests

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4677]
Looks like github has built in a feature that makes our "Preview" label no longer needed: https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by ron-murhammer** [comment]
I'm good with that.

**Comment by RoiEXLab** [comment]
Sounds good, however it doesn't look like there's a way to bring back a PR to the draft state, so having a "don't merge yet" label would still be useful.

**Comment by DanVanAtta** [comment]
Good consideration @RoiEXLab . I'm not sure if Github had a fast-follow since this was raised, but they added a button to mark a draft as 'ready for review:

![screenshot from 2019-02-19 14-05-23](https://user-images.githubusercontent.com/12397753/53050990-8c27f380-344f-11e9-8933-f09d3a30fcf5.png)
