### ISSUE TITLE
What is a high impact issue? / Issue prioritization?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4678]
### Problem / Goal

(1) Agree on a general definition of 'high impact' so we can know it when we see it.

(2) Agree/clarify how we will track these items.

(3) Agree/clarify if we need to have a 'low priority' category of some sort. For consideration, new items we tend to want to fix as they come in, if we can. Part of the thinking here is that things in the backlog can be fixed later without too much trouble. We could very well decide to instead "get serious" about backlog and not accept it and fix it with urgency (or close issues and not track them as problems if they are not actually problems or if they are problems that we just wont' realistically ever fix).

### Options for tracking:

Github provides us with two primary dimensions for tracking, labels and project columns.

(2.A: use both project column + label) Remove the 'top 10' column in bug triage and have a 'high impact' column. Have a matching 'high impact' label.

(2.B: use just project column) Just use bug triage project columns for tracking/categorizing bugs.

(2.C: use just labels) Use only labels for tracking/categorizing and not worry about the 'bug triage' project.

#### Labels
If we use labels, it would look something like this (note the description helps us add documentation):
![screenshot from 2019-02-14 18-12-28](https://user-images.githubusercontent.com/12397753/52830107-37b5fa00-3084-11e9-8cca-f036a3252df0.png)

#### Project Column

In the below example we can use project columns to categorize the different kinds of bugs and keep the labeling a bit simpler.

That would look something like this:
![screenshot from 2019-02-14 18-15-06](https://user-images.githubusercontent.com/12397753/52830171-7f3c8600-3084-11e9-8b9c-f9ef482961de.png)

**Comment by DanVanAtta** [comment]
It seems to me a 'high impact' label is a good replacement and more well defined version of a 'top-10' project column. I think we could consider 'regression bug' as 'high impact' and it would fit well. If the bug back log is otherwise just sorted as a FIFO queue (chronological, first come first serve), then filtering by a label gives us the same view. In this case I think '2.C' makes sense and the 'bug triage' project would be redundant tracking.

For (1), I think we have a rough working definition already, IMO let's do a free-for-all on adding 'high-impact' labels and keeping the descriptions well defined as a team. Any labels we could merge or perhaps should be better clarified, we can begin discussing that here.

(3) is a bit of a can of worms, but mostly coming up with a label/term for something where it is agreed by everyone that the fix can wait. From another point of view, any such items "hanging out" that cannot be readily worked on and closed out, they are adding overhead and hiding the things that we actually should be fixing. Any such items, that we really should be fixing and are not, will only bite us as either demonstrated as project failure (diminishing user base over time), or extra overhead as we will likely get repeat/duplicate reports and in tracking/analyzing the backlog. For example, let's say someone *did* want to find the things that need to be fixed in our backlog tail of 50 some issues, it's quite the task to even go through that list once, let alone have time to begin working on a problem.

(3) is also thorny, if someone takes the time to report a problem, it was important enough for that effort and should not be disrespected by saying the use-case that someone did care about, is not important. I would distinguish between as well issues cut by those close to the project vs those that are more casual community members. 

So, for (3), I think I would vote we find a way for the project maintainers to track 'their' issues, design, discussions, the project maintainers wish-list and to-do lists, to some other place. Then for community reported issues, we discuss on the spot as part of triage what we can do to fix the problem and try to mutually work out what a fix would look like. If we can't find something reasonable, then IMO we should try to be honest about admitting that the problem will never be fixed (we *do* have a backlog of things that we should fix, we should fix those first before we do any 'nice-to-have' fixes, and we probably have more 'must-fix' than we will ever fix; therefore 'nice-to-fix' will never be fixed unless we can just fix it on the spot). 

So for (3) TL;DR, we take dev issues out from the issue queue and find a new home for it, community member issues we agree on a fix, or if it's a nice-to-have and we can't fix it with low, on-the-spot effort, then we admit we will not fix and close. This negates the need for a 'low-priority' label.

**Comment by RoiEXLab** [comment]
For me high-impact issues are issues where a service is down, or non-functional to a high degree.
(We had this recently because a certificate wasn't reloaded properly and therefore expired at some point for the dice server.)
For this case I don't think having a label is sufficient. In this case I'd prefer getting mentioned, so I get a mail on my phone which makes me much more likely to respond within the next hour.
I'm usually not checking the repository more than a couple of times per day, so that is already a huge improvement.
Of course we could label those kind of issues afterwards, but this would only be useful for documentation purposes.

**Comment by RoiEXLab** [comment]
A crash would be higher in priority as well. For those kind of issues it would make sense to put them in a queue like you described, but they are not as severe IMO.

**Comment by panther2** [comment]
In the context of this topic and #4674 and when talking about priorities I just want to point out that "rules violations"  are of "high impact", at least to me. This is why I have created a list of unresolved rules issues that I have created from opened and closed Github issues recently here:
https://www.axisandallies.org/forums/topic/32958/triplea-engine-known-rules-related-bugs-issues/

I will add priorities (as estimated by me) to this list soon, as @ron-murhammer recently suggested.
Maybe you @DanVanAtta and @RoiEXLab are interested in this list, too.

**Comment by DanVanAtta** [comment]
I've added a starter set of 'higher priority' [labels here](https://github.com/triplea-game/triplea/labels
), please note the descriptions:
![screenshot from 2019-02-15 11-49-04](https://user-images.githubusercontent.com/12397753/52880881-06870980-3118-11e9-8a78-3b6b9dece908.png)

Hopefully that jogs the discussion, we're looking to clarify exactly what we mean when something qualifies as needing to be fixed before other things. Hence not talking about a production or an ongoing operational problem, but instead the impact of the different bugs. One way to measure a bug is a product of impact and frequency. If something is really impactful it is important, if something is super frequent it tends to be important. Generally we should focus on high impact high frequency items first. The discussion here is intended to define what a high-impact item actually is.

@panther2 agree on the game rules receiving higher priority. I added a high impact label to each issue in that list, filtering by the 'bad game rule' label should now produce the same list: https://github.com/triplea-game/triplea/labels/High%20Impact%3A%20Bad%20Game%20Rules

**Comment by panther2** [comment]
Great, thank you, @DanVanAtta .

**Comment by DanVanAtta** [comment]
With the theory that priority is a product of impact and frequency, just labeling impact as "high impact", or "high priority" quickly dilutes the meaning of "high priority"

On the other hand, not having a definition for "high impact" leaves it up to subjective debate and side-tracks from our goals.

Having the impact-type be labeled I think has been useful.  I renamed them from 'high impact:' to 'impact:'

I'm tempted for us to also label frequency, but I suspect it's a bit too much complexity and not really that needed.
