### ISSUE TITLE
Add 'submit map enhancement request' to the help menu

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#468]
In addition to having a menu to submit bug reports, let's also create one for reporting map problems.

**Comment by ron-murhammer** [comment]
@DanVanAtta Only concern here is whether the majority of our users will know the difference.

**Comment by DanVanAtta** [comment]
I think that's a problem for the UI to solve. It should be clear what the difference is based on the UI. Worst case, we spend some time moving tickets from the game engine queue to some map queue.

**Comment by DanVanAtta** [comment]
I don't think this is at the top of the list anymore. If we get a lot of issues routed to the general bug queue, we can revisit this idea and alternatives.
