### ISSUE TITLE
lobby backend structuring, lobby-engine and DB subproject

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4701]
## Design Proposal

- add two new sub-projects 'lobby-engine' and 'lobby-db-code'. This forces a more strict split between modules and isolates code between network, logic and persistence. Updated sub-projects are diagrammed below with 'lobby-engine' and 'lobby-db-code' being new.

![lobby-to-db](https://user-images.githubusercontent.com/12397753/53187931-0aec7000-35b9-11e9-81b5-cb3f8f2d05d5.png)

## Objectives
- Enforce lobby code module boundaries with compile-time dependencies
- Opens a migration path for new features and feature updates between http-server code and lobby code.

### Problems to solve

- We can shift code around between lobby and lobby-engine to isolate network code that will be replaced by http-server
- Avoid network and transport code from leaking into lobby-engine code. It's very easy for this to happen, Spark *is* temporary or at least just being evaluated, we'll defeat ourselves if we build new lobby-logic into the spark server.
- Maintain component boundaries going forward to help scale for additional DB layer complexity. Currently the DB is pretty simple, just a few tables, that is expected to significantly more complex.

**Comment by RoiEXLab** [comment]
👍
I'd consider that to be a good improvement.
I just wanted to point out that we should consider changing the db structure/concatenating similar tables and renaming them when we're changing the layout anyways.
I'm mainly thinking about the fact that the database name is `ta_users`, the same as the name of the table `ta_users` and the mute and ban tables are almost identical in terms of structure.

**Comment by DanVanAtta** [comment]
Agree @RoiEXLab but would caution that these code moves can get very complicated in a hurry. Essentially, incremental and one-thing-at-a-time I think will rule the day here. For DB tables, once they are isolated behind better APIs it's less of an issue, I agree that there are issues and suspect we may completely replace them.
