### ISSUE TITLE
 New Battle calc: CTRL-A

### ISSUE THREAD

**Issue by ZjelcoP** [triplea-game/triplea#4709]
1.10.14134

Windows 7

WAW/ Revised

Using CTRL-A then selecting a territory, a multiple of the units present is imported in the Battle calc.

sometimes 4x, 6x, 10x
Holding the mouse button will keep adding units indefinitely
Should reduce added untis by 1x per click.

**Comment by ZjelcoP** [comment]
Or am I using the function wrong? Same happens for mouse or laptop touchpad.

**Comment by ron-murhammer** [comment]
Hmm. Never thought anyone would hold down the mouse button. It does seem to start adding multiples if you hold it down instead of just clicking.

**Comment by ZjelcoP** [comment]
problem is with sensitivity, I am unable to select 1. One fast click means at least x6. Guess it depends on the hardware?

**Comment by ron-murhammer** [comment]
Oh interesting. I definitely have to hold the mouse button down a few seconds to start getting multiples. I should be able to add a check to ensure you have to click to get multiple rather than hold down.

**Comment by ZjelcoP** [comment]
But great improvements on the Battlecalc nonetheless! Thx

**Comment by ron-murhammer** [comment]
@ZjelcoP Do you have the same thing happen with using CTRL+B to open the battle calc? The new hotkeys CTRL+A & CTRL+D for adding units essentially use the same mechanism as CTRL+B does to open the battle calc. If I hold down CTRL+B for a few seconds then it opens multiple battle calc windows.

**Comment by ZjelcoP** [comment]
Indeed that is it. Hold click, then CTRL+A and it works fine! Thx
