### ISSUE TITLE
Infrastructure 2.0  - VMs, containers, ansible deployment

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4715]
Thinking on a number of infrastructure problems,  I'd like to propose a number of changes to infrastructure.

### Problems to solve:
- infrastructure scripting is difficult without being done directly on a linode server
- infrastructure deployment is done as a completely independent step and without any testing from the travis build. This makes it easy to break infrastructure, and adds overhead to monitor for broken infrastructure and after-the-fact fixes.
- breaking infrastructure can be structural, configuration versioning is a problem. Tentatively we're planning to solve this by baking in version-awareness logic in infrastructure, avoiding that will be a big win for improving maintenance and reducing complexity

### Change Proposal:
 - (1) use [docker-compose](https://docs.docker.com/compose/) to launch dockers lobby-db, lobby, and a headless bot
   - we could add to the '@Integration' tests to verify lobby and headless bot
   - travis can run docker, branch builds would be updated to these two commands:
    ```
    - docker-compose up -d
    - gradlew check   
    ```
 - (2) introduce [vagrant](https://www.vagrantup.com/)
    - we could launch VMs and run infrastructure deployment locally without linode
 - (3) convert the shell scripts in [infrastructure](https://github.com/triplea-game/infrastructure) to [ansible](https://www.ansible.com/) and move those scripts to [triplea code repo](https://github.com/triplea-game/triplea)
    - solves configuration versioning problem. We can update configuration files and deployment script as we update code. Since they are both built under the same version, they'll stay in sync when we download and install by version number.
   - ansible has a 'push' model for running deployments. We'd set up an ansible master that would deploy the latest prerelease to staging and latest release to prod. It would be one location to manage secrets, today we have a 'secrets' file hand-deployed to each server.

#### Environments
This table describes how we would do builds/testing/deployments:

|                      |  Build    |  Local    | Latest | Staging | Prod |
|   -------------   | -----      |   ------    | --------- | -------  |   ----- |
| ***DB***         | Docker | Docker  | Docker | Linode  | Linode |
| ***Lobby***    | Docker | Vagrant | Linode  | Linode  | Linode |
| ***Bot***        | Docker | Vagrant |  Linode  | Linode | Linode |
| ***Artifacts*** | Gradle | Gradle  | Gradle | Downloaded | Downloaded |

* Build: travis build
* Local: developer workstation
* Latest: a linode environment used by travis to verify master after merging, but before pushing artifacts to github releases.
* Staging: linode prerelease deployment, ansible master deploys latest prerelease version to this environment
* Prod: linode prod environment, ansible master deploys here the latest release version

#### Full Build Flow
Summarizing the full build flow (new steps are in bold):
   - PR submit
   - travis branch build
      - compose-up launches:
          - lobby-db
          - ***lobby***
          - ***bot***
       - gradles check runs tests and integration tests that verifies lobby-db, ***lobby, and bot***
   - merge
   - build is run with docker containers and integration tests again verifies
   - ***travis runs 'latest' deployment to deploy built artifacts to linode servers***
   - ***travis runs integration tests using 'latest' environment, a live linode environment***
   - travis deploys artifacts to github releases
   - ***ansible master would see the new 'prerelease' and deploy it to the staging environment***
   - ***if we check 'latest' release checkbox, then ansible master will 'see' that and deploy that version to prod.***

## Points for Discussion:
- Is this all-encompassing for the dev and release process? I like that the same integration tests can work against a docker, vagrant, or prerelease environment. 
- Any thoughts or concerns on ansible, docker-compose, vagrant?
- questions, ideas?

**Comment by RoiEXLab** [comment]
I like the proposal although I must admit that I never heard of the services you listed except of course of docker.
However I'm unsure about the part where you want to deploy a version to a test environment just for integration tests. Doesn't this make this step uneccessarily complicated and slow?

**Comment by DanVanAtta** [comment]
> Doesn't this make this step uneccessarily complicated and slow?

Fair concern. I think there are some pro's, let me know what you think:
- overall we do not build master that often; but we will add time to post-merge for when a new artifact is available. Compared to finding any potential problems sooner, this will hopefully be a very profitable trade-off.
- we get better coverage. It's the one time where we use actual ansible scripts and linode servers. The only thing that is not similar to prod is that we are pushing an artifact that is just built. To be hopefully clear, when travis is post-merge, doing tests on master before installers to github releases, it will deploy jar files built from gradle.

The key benefits we're looking at:
- we get a lot of testing parity and most test failures should reproduce with just docker. I'm hoping a key feature here will also be that we'll be able to mostly use fast docker tools and avoid vagrant unless we need to update the ansible infrastructure. The ansible will deploy our configuration files and configure servers.

Does that make sense?

**Comment by DanVanAtta** [comment]
@RoiEXLab also came to mind, perhaps could help, "latest" is potentially broken and will fail travis before we push artifacts. The idea is we can expect 'prerelease' to be pretty stable and non-deployable artifacts will not be built.

**Comment by RoiEXLab** [comment]
@DanVanAtta Ah I missed the part where this step was only supposed to run on master builds. Sounds somewhat like a E2E test lite edition, but I'm fine with that 👍

**Comment by DanVanAtta** [comment]
I'm still wondering how to build the ansible control host that would execute the deployment. It could be the case that we can do everything from Travis. For example, with 'concurrent build' set to 1, we could have branch builds deploy to a "CI" environment. If merged, then we deploy to 'staging'. I think if we had in travis configuration a version number, then we could download the `ansible.zip` for that version and run ansible against prod (for that version). This should be safe as ansible scripts are meant to be written in an idempotent way.

For secrets, we already use travis encrypted environment variables and this looks interesting for SSH keys: https://gist.github.com/lukewpatterson/4242707

**Comment by DanVanAtta** [comment]
Commits have landed added adding ansible codes, we are committed to this path.
