### ISSUE TITLE
Code reviewer / contributor role responsibilities and description

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#472]
I'd like to propose that we create a formalized "code reviewer" and a "code contributor" role.  In this issue I'd like to discuss these roles, their responsibilities, and eventually when we have consensus will then commit this info to a wiki doc and/or the readme.

### Code contributor:
-  will be just that, the person that submits a PR.

### PR Guidelines for a code contributor
- describe functional changes
- describe how to test the change
- describe refactoring that was done

### Code reviewer role:
-  would have write access
-  be responsible for shepherding PRs, and hitting the merge button at the appropriate time.

### Requirements for someone to become a code reviewer
- contribute some code
- provide valuable code reviews
- sustained engagement over at least a few months

### PR Merge Guidelines

At least one code reviewer must:
- try out any functional changes
- do a thorough code check
Before merge:
- all comments questions should be answered/addressed

Avoid self merges:
- contributors of a PR should not be considered as reviewers when it comes to their own PRs
- the reasoning for self merges should always be explicitly indicated
- The following are the exceptions to no self merges:
 - things that are more urgent, people waiting for a bug fix, people waiting to test
 - build process items
 - things that are just much easier to test when merged to master  (for example they only kick in when merging to master as well)

**Comment by ron-murhammer** [comment]
Looks pretty good to me and yeah definitely would recommend creating a wiki doc for this.

**Comment by DanVanAtta** [comment]
Doc moved to: https://github.com/triplea-game/triplea/wiki/Code-Reviewers-and-Pull-Request-Guidelines

As is it is a wiki, @all please feel free to refine/improve it.
