### ISSUE TITLE
Code Reviewer Invitation @gaborbernat

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#473]
@gaborbernat ,you're invited to become the 4th code reviewer. The responsibilities are outlined in:  #472.   Would you like to accept?

**Comment by gaborbernat** [comment]
Yes :)

**Comment by DanVanAtta** [comment]
@ron-murhammer , need an owner / team manager to invite gabor into the code reviewer team, would you mind taking care of this?

**Comment by ron-murhammer** [comment]
@DanVanAtta @gaborbernat Should be added now.
