### ISSUE TITLE
Introducing 'Database Rider' - DB Testing Framework

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4735]
## Database Rider

I've been thinking about introducing this framework for some time, and wanted to pitch it to the group before taking the last steps of integrating and using it: https://github.com/database-rider/database-rider

![screenshot from 2019-03-05 21-11-54](https://user-images.githubusercontent.com/12397753/53857488-532d6a00-3f8b-11e9-9ebc-67044eea1724.png)

### Overview

Test library where you specify DB table data in a YAML file. Before each test DB Rider will get DB in that state, then test executes, and can verify a post-state.

For example you can specify a YML with two user rows, run a test to find a user where you do a user lookup by name and can then verify data is retrieved.

![screenshot from 2019-03-05 21-20-37](https://user-images.githubusercontent.com/12397753/53857826-90dec280-3f8c-11e9-98c3-d940601e18e5.png)

![screenshot from 2019-03-05 21-19-33](https://user-images.githubusercontent.com/12397753/53857776-68ef5f00-3f8c-11e9-91b1-4c1f9a4c7d62.png)

### Benefits

- Avoids chicken and egg problem of DB data and testing. A lot of DB access needs data to be interesting, to get data insertion methods need to be written or production versions re-used. This problem is particularly bad when the system under test does not write the data, in which case data insertion code needs to be custom written for the test.
- Helps split production DB code used to insert and query data from DB code used to set up DB state
- Reduces custom DB test code, benefit of using a framework

### Drawbacks

- Frameworks not perfect and can require some understanding. For example, if one test creates two tables A and B with foreign key constraints, leaves that data, and another data clears table A but is not aware of table B, then there will be a FK violation when the second test is run first. I think we'll be able to configure or ensure all tests are additive, so I think we can avoid this by convention; but we will have to be a bit careful and solve it, can't promises someone won't trip over this.

## Desired Outcome for this issue

Discussion so that the new testing framework would not be a surprise.

- Any experiences that can be shared? For my part, I worked with DB rider a bit. I think it would help a good bit as we are using JDBC code to test more JDBC code. With http server writing to DB and no write equivalent being added to lobby, in my view such a test framework would be very handy.

- Any concerns, questions, comments?

**Comment by RoiEXLab** [comment]
Seems promising to me.
I don't have any objections to introduce new stuff to test stuff in general. 🤷‍♂️ 
(Except if the plan is to introduce h2 as in-memory database to test stuff, then I'm against that because I had problems in the past resulting from the difference to the prod DB 😋 )

**Comment by DanVanAtta** [comment]
https://github.com/triplea-game/triplea/pull/4745 migrates a first test DAO to have a DB rider test.
