### ISSUE TITLE
Style proposal, prefer clarifying parens

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4754]
I'd like to propose we clarify style guideline where clarifying parentheses are officially preferred:

eg:
```
boolean value a = (a == other) || (b == other);
```

vs:
```
boolean value = a == other || b == other;
```

There is IDE automation for this:
- Eclipse has a code style setting for 'always' to have parentheses in expressions:
![Screenshot from 2019-03-11 09-09-39](https://user-images.githubusercontent.com/12397753/54138837-8897e480-43dd-11e9-957f-382cca4d3b6f.png)
- IDEA has an analysis check that will make this show up as a compiler warning

**Comment by RoiEXLab** [comment]
@DanVanAtta If you ask me I'd vote to not include them everywhere:
They make sense for combined || and && logical expressions to make clear in which order the expressions ar applied, but for cases like the one you showed in the example. I don't think they should be mandatory.

**Comment by DanVanAtta** [comment]
I find these two cases hard to distinguish:
```
value = other = something || another
value = other == something || something;
```

I believe we may have removed all examples of same line assignments from TripleA, in general it can't just be assumed as a rule of thumb. As a programmer expectation, I've often seen parens to help this to indicate clearly where the assignment ends and the value evaluation begins). 

Going to our style guide (which we have agreed is authoritative specifically for cases where we disagree in style), I found:  https://google.github.io/styleguide/javaguide.html#s4.7-grouping-parentheses

> Optional grouping parentheses are omitted only when author and reviewer agree that there is no reasonable chance the code will be misinterpreted without them, nor would they have made the code easier to read. It is not reasonable to assume that every reader has the entire Java operator precedence table memorized.

The last sentence does make clear operator precendence is in mind, but the text does say that both author and reviewer should agree:  "[Optional grouping parentheses would] have made the code easier to read".

**Comment by RoiEXLab** [comment]
@DanVanAtta Notw that this is just my personal preference and probably the thing I will go with when coding my own stuff.
At the same time I don't have any strong objections, so I'll go with the majority on this one

**Comment by DanVanAtta** [comment]
Regrettably I think we probably have bigger fish to fry, inertia is against this one, closing while we focus on other objectives.
