### ISSUE TITLE
Bugs when combat move is before purchase

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#4756]
### Engine version
All

### My Operating System
N/A

### Map name
Many including "World War II Global 1940 Balanced Mod3 with Combat Move First"

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
(1) Damage an airbase or naval base so that it is inoperative. No opportunity presents to repair before combat move.
(2) Move all units out of a capital. Plunder that capital's PUs. It is now possible to spend that money, which is incorrect.
(3) PBF post option is provided before purchase - this is wrong. Should be showing purchases before asking defender decisions.

### Instead of this error, what should have happened?
(1) Suggestion - in the event that a base is inoperative, offer the opportunity to repair in a special phase which occurs before combat move
(2) I say don't do the combat in combat movement - create a NonFightingBattle so that it occurs automatically in BattleDelegate.start()
(3) I suggest a special movement phase to allow posting only, and an XML option to prevent posting in the normal phase.

### Any additional information that may help

#1184. Probably too hard to fix and not high enough impact. It's already in the notes.

**Comment by ron-murhammer** [comment]
Well to be honest, (1) is really a direct implementation change by moving the phases around. Base repair is done alongside purchases so if you want repair before combat move then you essentially need a purchase phase beforehand. You probably can create a limited purchase phase before combat move where the only option is to repair not buy any units. Though I personally think that if you want that behavior then you are better off keeping purchases before combat move.

(2) Does that also happen if there is an isInfra unit in the capital? If not you might be able to just add a filler isInfra unit to each capital to prevent it.

(3) Probably a good feature request. I think posting can only be done at the end of a move phase or end turn phase at the moment.

**Comment by simon33-2** [comment]
Yeah, I can live with (1) if I have to - it doesn't come up often.
Regarding (2), yes it still happens with an isInfra or isFactory unit in the territory. I'm not sure where this change would need to be made?
(3) is probably the main game. It might not be too hard to do either.

**Comment by ron-murhammer** [comment]
@simon33-2 I believe 1 is now resolved with https://github.com/triplea-game/triplea/pull/4775

**Comment by DanVanAtta** [comment]
Moved to forums: https://forums.triplea-game.org/topic/1700/bugs-when-combat-move-is-before-purchase

Per: https://github.com/triplea-game/triplea/wiki/Bug-Report-And-Feature-Request-Tracking
