### ISSUE TITLE
Network Chat Missing

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4761]
## Repro Steps

In all cases below notice there is a network button but no chat window

(1) Local host 
- launch game
- click 'host game'

(2) With Local Lobby 
- start a local lobby
- start a headed game
- connect to lobby and host a game

(3) Local Lobby + Bot
- start a local lobby and headless bot
- start a headed game
- connect to lobby and join a bot

### Screenshot of problem:

In this screenshot notice there is no chat:
![Screenshot from 2019-03-13 14-19-01](https://user-images.githubusercontent.com/12397753/54315321-035a2e80-459b-11e9-862f-5ca5129a22e3.png)

---------

If anyone wants to jump in on this one, feel free. I'll try to look into this otherwise at some point before the 1.10 release.

**Comment by RoiEXLab** [comment]
@DanVanAtta I won't have the time to dig into this during the next 2 weeks, but in case someone wants to have a look I'd recommend checking the latest chat changes to figure out when this problem was introduced.

**Comment by DanVanAtta** [comment]
Narrowed the  problem down to an impossible `instanceof` condition check: 
https://github.com/triplea-game/triplea/commit/408faa97c782ad9c1585d244aa3b2e4a27515847#diff-80614d8aaef02b03e24f48595cf4436aR116

Working on this..
