### ISSUE TITLE
Unable to view map when selecting territories for bombardement.

### ISSUE THREAD

**Issue by ZjelcoP** [triplea-game/triplea#4772]
I believe there have been more requests on how to select territories for coastal bombardment.
My issue is that because of the popup prompting you to select the territories you are no longer able  to have a look at the map to determine the correct choices.
Scrolling the map is impossible unfortunately.

**Comment by beelee1** [comment]
yea can't scroll but you can click and grab the window and move it out of your way

**Comment by ron-murhammer** [comment]
Yeah, the bombardment territory selection UI is pretty bad especially when you have multiple options and lots of ships. It really needs to be revamped to be more like the scrambling UI.
