### ISSUE TITLE
Use JavaFX for front-end

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#4773]
Related to #4621
So I'll have a lot more free time starting saturday for about a month, so I'm planning to finally pick up the work I started for the JavaFX UI.
I just wanted to make sure, we're all on the same page here:
I'm planning to migrate everything that is game-launching related step by step. I must admit that I probably can't get all of this done in the next month, but I'll have to start somewhere.
So I wanted to get a couple of questions out there:
Are you ok with the design choice with the greenish beige color choice? I'll have to redo some of the existing frames, but I think I'll go with a bottom-up approach this time, so I'll design the smaller components before the actual containers. Also I definitely need to adjust everything so it works for smaller screens as well.
Also are you fine that the game will have this clearly visible design difference at some point?

(@ssoloff I'm just tagging you because this is a clearly visible change you might have strong feelings about. In case you don't have anything to add feel free to just unassign yourself without any further comment.)

**Comment by DanVanAtta** [comment]
@RoiEXLab my 2 cents, I suspect this will be a very challenging migration. Simply completing it and having it work will be quite a lot. I suspect reducing the number of things changing as much as possible will help towards that goal. Once we have a better pattern/framework in place and lots of legacy code removed it should be much easier to continue iterating to clean things up.

What are your thoughts for how to actually migrate @RoiEXLab ? Which areas of functionality would go first? Would this be a parallel effort, by component or screen, or a flip the switch to the new UI and fix everything that does not work?

**Comment by ron-murhammer** [comment]
@RoiEXLab I'm fine with that color choice and remember we had started discussing some initial mockups on the forums a while back. Honestly the game-launching UI is pretty basic and I'm pretty open to taking it in just about any direction.

**Comment by RoiEXLab** [comment]
@DanVanAtta I think there's already enough JavaFX code in place that getting everything working (of course it won't look good in the meantime) is a feasible project.
The download dialog and the lobby will be rather complex tasks tbh because I think the logic is still tightly coupled to the UI there. But we can easily just fall back to the swing implementation there and everything should continue to work.
So there are basically 2 tasks I want to tackle: Adding a launching screen that also works with PbF/PbEM (+maybe multiplayer launching screen) and wiring everything up so that functionality that doesn't exist falls back to the swing implementation.
I also need to add some settings to the framework that I only added to swing when working on the PbF/PbEM changes, and while I'm at it, I should also add a dialog to allow non-persistent storage of the forum/email credentials.
