### ISSUE TITLE
Resolve DB tuning warnings

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4776]
Interesting tool on [hacker new](https://news.ycombinator.com/):  [postgresqltuner](https://github.com/jfcoz/postgresqltuner)

Running it gave the following suggestions:

```
=====  Configuration advice  =====
-----  backup  -----
[URGENT] Configure your wal_level to a level which allow PITR backup and recovery
-----  checkpoint  -----
[MEDIUM] Your checkpoint completion target is too low. Put something nearest from 0.8/0.9 to balance your writes better during the checkpoint interval
-----  extension  -----
[LOW] Enable pg_stat_statements in database template1 to collect statistics on all queries (not only queries longer than log_min_duration_statement in logs)
-----  report  -----
[URGENT] Use the --ssd arg if the VM in running on a SSD storage
-----  sysctl  -----
[URGENT] set vm.overcommit_memory=2 in /etc/sysctl.conf and run sysctl -p to reload it. This will disable memory overcommitment and avoid postgresql killed by OOM killer.
-----  version  -----
[LOW] Upgrade to latest version

```

Full output from the postgresql run available here: https://gist.github.com/DanVanAtta/2785be62018f2dfad3c04cf0d5b2189c

Creating this ticket to keep track that we resolve these suggestions.

**Comment by RoiEXLab** [comment]
Indeed interesting. Promising nevertheless

**Comment by DanVanAtta** [comment]
Added a wiki page to note the DB tuner tool: https://github.com/triplea-game/triplea/wiki/DB-Tuning

The wiki page will also be a good place to add any tuning/configuration notes
