### ISSUE TITLE
Build step: `validateYaml` is getting flaky

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4789]
I'm not sure how often others are seeing this error, I've been seeing it locally maybe about 10% of the time, but seems to be a growing problem:

```
Execution failed for task ':validateYamls'.
> https://github.com/triplea-maps/minimap/archive/master.zip: map resource not available (500)
```

It just killed a PR build: https://github.com/triplea-game/triplea/pull/4788

A gradle build check that is validating resources over the network is not very ideal. AFAIK the best practice is you want your build tools to stay local, so you could for example work from an airplane without the build failing.

The `validateYaml` check is a useful step, but perhaps we can make it more robust. Maybe we don't actually need to check URLs are valid as part of build, maybe just that the file has the right syntax. Then on post-merge, perhaps there is a good time to then check that the URLs are also good.

**Comment by RoiEXLab** [comment]
I just restarted the builds. I hope it's just a temporary github downtime.
Note that one of the reasons this check exists is that the triplea-game.org repo actually checks the validity of links so we don't end up having any dead links on the website, so a failed build here will mean a failed build there.
A compromise (the best one I could come up with at least) would be to somehow check if the file was actually modified in the current PR and skip this check if it wasn't.

**Comment by DanVanAtta** [comment]
I like the idea of a skip, but I think a skip should be based on if the check has already been run compared to looking at git history for modifications.

Gradle has capabilities to skip if there were no modifications since the last run. I checked into that some time ago and it looked like we would just need to create output result files from the task, at which point gradle can automatically run if needed.

Regardless of anything, gradle tasks that no-op on no changes is a design ideal for any gradle task, we should build that in to `validateYaml` regardless of anything else.

With respect to this problem, I think the next step we should take is to more deeply understand this problem. If we simply run the odds of failure less often, while the build will be more stable, it will still be fundamentally non-deterministic.

@RoiEXLab you're right about the website crawler, but I think that is a tool/app that verifies that, no?
It looks like this failure is us looping over all URLs in the map listing and checking that there is a valid map zip behind each one.

- It'd be cool if we could check many URLs in one call. Perhaps there is a webservice API.
- Likely we should check status code, if there is a 404 then the script fails. On a 500 perhaps sleep for 50ms and then retry once.

------------

Really long term, map URLs might wind up in the TripleA database if we serve the data from application instead of files. A fundamental redesign like that is perhaps a more true fix as we woiuldn't need to check for valid URLs at build time anymore. I've no idea how far out such a project would be. If we can build file uploads to http-server, it might not be that difficult to start building :smile:

**Comment by DanVanAtta** [comment]
Haven't seen this problem in some time, closing..
