### ISSUE TITLE
Control-P is mapped to two functions

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#4815]
### Engine version
1.10

### My Operating System
Ubuntu

### Map name
Any

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Run a PBEM/PBF game. The File|Post menu item has a speed key (or whatever Java calls it) of Ctrl-P. Unfortunately, that is also the key to highlight the "Players" panel. I suggest that "Post" should be change to Ctrl-O since every other letter in post is already used.

**Comment by ron-murhammer** [comment]
@simon33-2 Should be addressed with https://github.com/triplea-game/triplea/pull/4836. I changed it to CTRL+M for "manual game post" as CTRL+O is for the objectives panel.
