### ISSUE TITLE
Audio Requirements - Be able to play wav vs mp3

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#482]
If we have problems playing both mp3 and wav, and if it is a choice, I would like us to choose mp3. Here are the reasons:
- mp3 at even mid level compression levels will sound *identical* to wav files.
- mp3 files are a good 80% smaller than a wav file. A wav file can easily be 3-7MB in size. Include 10 of these and we already have gigantic files and maps.
- To be clear, wav is a *lossless* audio codec, it has every single bit that was originally recorded and has zero compression applied. These files are suitable for music editing or transcoding, neither of which is our use-case.
- The size of the wav files slows down everything.. We store audio files in memory in cache, we are eating up a lot of memory. Consider that all audio files compressed will consume 13MB, we could cache every game sound for the cost of caching 2 wav files. Secondly, the game install and download time is dominated by audio and image assets. It's pretty slow installing the game because of this.
- There are multiple free tools available on all OS's to convert from Wav to MP3. So it's never a choice of having only a wav file, or having an MP3, you can always convert from Wav to Mp3.

**Comment by DanVanAtta** [comment]
In short, I'm proposing we drop wav files altogether. Keep things simple, and look to our requirements.

Some good news, this article has a nice description of how to get mp3 files to work: https://thiscouldbebetter.wordpress.com/2011/06/14/playing-an-mp3-from-java-using-jlayer/

JavaFx media objects are PITA, and require a hack to get the JavaFX environment initialized. Wtih respect to the article, it turns out we do not need mp3spi, just jlayer. Then using JLayer objects we can play audio.

**Comment by ron-murhammer** [comment]
I'm open to moving to just mp3's but that means all existing maps would have to be converted.
