### ISSUE TITLE
Http server next steps

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4842]
I'd like to split out the http server binary from lobby once again. Reasons:
- as different applications we can scale them differently
- any debugging will be easier, traffic patterns, memory leaks, will be separated and we can distinguish between problems
- Code separation, lobby binary and http server binary being tangled together will likely gradually become more joined, eventually it'll be hard to split them. Of importance, http servers are intended to be stateless, but lobby is stateful, mixing these two paradigms is not necessary and as mentioned can cause code spaghetti issues.

I'd also like to start investing in drop wizard and no longer spark. Spark had a nice demo in my opinion, it's basic and has virtues there, but I'm not confident code complexity will scale well nor that we won't see issues when traffic grows. On the other hand I've worked with drop wizard for several years and have seen it perform very well in production contexts under high load. It has some additional features like JSON marshaling that should in the short term simplify things for us, I also like that it is not dependent on everything being a static call to register endpoints and services. From that latter perspective I think code complexity should scale better (plus I've seen patterns where it works well, so IMO it's already far beyond well-proven and I know it to be solid from professional experience working with it)

**Comment by RoiEXLab** [comment]
Sure, try it.
I really don't have any strong preferences

**Comment by DanVanAtta** [comment]
Thanks for the feedback @RoiEXLab 

After giving it a shot, some things have been a bit nicer, simpler as there is automatic serialization of JSON and the handling of configuration values seems more developed. I do also like the integration with JDBI and that has been easy to work with.
