### ISSUE TITLE
Lobby Chatlog Degenerates With Special Characters (1.9.0.0.13066) 

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#4845]
After a user inputs special characters (I've seen this with Arabic letters too), the lobby chatlog appears badly formatted, or anyways generally undergoes a display change from beforehand, on my end.
![20190527_01](https://user-images.githubusercontent.com/19562310/58429787-49f1fc00-80a7-11e9-83bb-b3c62d5fd6ec.png)

**Comment by DanVanAtta** [comment]
this is a really good bug report as special characters are not something people normally think to test.

I'm not able to repro with 2.0. 2.0 has a new JVM, perhaps that handles the extended unicode characters well.

![Screenshot from 2020-03-10 20-36-22](https://user-images.githubusercontent.com/12397753/76380039-fd626f00-630e-11ea-80d7-c0e458c5a468.png)
