### ISSUE TITLE
Master build failing

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#4847]
I just noticed that the master deployment is failing because it looks like I removed too much of the code in #4810
I think adding back the download plugin should be sufficient, however I currently don't have the time to do it.

I'll try this evening if nobody else has done it until then

**Comment by DanVanAtta** [comment]
Is a fire, but it's not production happily. Thanks for noticing @RoiEXLab,  ball is in your court on this one.

**Comment by RoiEXLab** [comment]
Hmm I just saw that #4846 fiddles around with the gradle config as well, I don't want to introduce merge conflicts.

Evening will tell

**Comment by DanVanAtta** [comment]
@RoiEXLab it's likely safer for us to rollback the changes that broke master and try to roll back forward with fixes. Merges are blocked right now, I've only a few days to get things merged and could incur very extreme merge conflicts if PRs do not go through. For context I'll be traveling and hence anything blocked for more than a week will sit around for over a month. With large and complicated changes, and that much time between initial context of what was changed and coming back to it, it'll become a very ugly picture.

I recommend then if you can't figure out a quick fix that we simply start by rolling back. Git does make it easy to roll forward again, so it is really not a big deal to roll back and is likely a safer course of action.

**Comment by RoiEXLab** [comment]
@DanVanAtta Thanks for the reminder, I completely forgot about this.
A fix is on the way.

**Comment by DanVanAtta** [comment]
Great to see this fixed @RoiEXLab , good work!
