### ISSUE TITLE
Docker Image out of Date, Could use documentation

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4873]
Problem:
- Docker installs wrong database name
- We are missing instructions on where this is set and how to update. Grepping across the code base I was not able to find where the DB name is set.
- This is holding us back from updating to not use the postgres super-user and instead use an app specific DB user. This is a growing problem as additional tables are being added.

Current workaround:
- After launching docker with `run_docker`, a dev needs to know to run `drop_db` followed by `run_flyway`, currently the `drop_db` step is tribal knowledge (bad)

Desired resolution:
- PR with documentation on how to update docker database

If anyone can quickly outline where/how docker sets up DB, I could potentially take it from there.

**Comment by DanVanAtta** [comment]
@ssoloff can you chime on with any quick pointers on this one? @RoiEXLab? I'm happy to do the heavy lift here, but am really struggling to find anything beyond the base image defined in the Dockerfile.

**Comment by ssoloff** [comment]
> If anyone can quickly outline where/how docker sets up DB

Via _lobby-db/Dockerfile_.  See the Postgres Docker image [documentation](https://hub.docker.com/_/postgres) for how to customize the container.

> I was not able to find where the DB name is set

Via the `POSTGRES_DB` environment variable in the Dockerfile.

**Comment by DanVanAtta** [comment]
Thanks @ssoloff 

Added documentation link in PR: https://github.com/triplea-game/triplea/pull/4942
