### ISSUE TITLE
Tooltips can be very long. Toooo long.

### ISSUE THREAD

**Issue by FrostionAAA** [triplea-game/triplea#489]
Sometime tooltip popups can be VERY long. Sometimes they go way off screen and are not even visible. Would it be possible to change the engine generated tooltips so that there were some more line breaks?
Here is an example of what I’m talking about:
![tooltip](https://cloud.githubusercontent.com/assets/15268177/13411433/465c719c-df3d-11e5-96e0-9ca2d2236d6d.png)

**Comment by DanVanAtta** [comment]
@FrostionAAA  The above map is Age of Tribes?

**Comment by FrostionAAA** [comment]
Yes. That map is still in beta. But, the issue is the same on any other map. All of a unit’s properties seem to listet in ONE line under the Att/def/move info line. And that second line can be very long.

**Comment by FrostionAAA** [comment]
Just want to bump this request, and say that any changes should ofcourse also affect the units in the purchase window. I made this new little mockup picture.

PS: It seems that there are some pieces of info or some circumstances that at the moment creates line breaks. But I can figure out what they are.

![unavngivet](https://user-images.githubusercontent.com/15268177/26994061-4967eac2-4d66-11e7-92b2-73401833944d.png)

**Comment by FrostionAAA** [comment]
I am closing this issue as another newer issue asks for the same thing. https://github.com/triplea-game/triplea/issues/3510
