### ISSUE TITLE
Domination 1914: No Mans Land --Italy Tech

### ISSUE THREAD

**Issue by josiah1111** [triplea-game/triplea#4916]
1.9.0.0.13066
Windows 10 

Domination 1914: No Man's Land

When Italy gains armour tech, tanks do not appear in build window.

**Comment by beelee1** [comment]
Hi josiah
You should add a saved game showing the incorrect behaviour. It will help people to diagnose it.

**Comment by ron-murhammer** [comment]
@josiah1111 What version of Dom NML are you playing?

**Comment by josiah1111** [comment]
1.9.0.0.13066 I’ll work on getting that save to you (PS great game —I’m really enjoying it)


Sent from Yahoo Mail for iPhone


On Friday, July 12, 2019, 8:26 AM, Ron <notifications@github.com> wrote:


@josiah1111 What version of Dom NML are you playing?
