### ISSUE TITLE
Blends Don't Function (1.10.15051)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#4929]
I tried Show Map Blends on "270BC 40%". They don't work anymore in 1.10.15051, albeit the map appears to be redrawn upon selecting/deselecting. They still work for the current stable 1.9.0.0.13066. Please, fix.

**Comment by RoiEXLab** [comment]
#4930 fixes this issue.
Turns out the code that gets triggered when clicking the button sets the map scale to itself in order to trigger a redraw, which doesn't work anymore since scaling no longer triggers a redraw
