### ISSUE TITLE
Google Java Format Cut-over plan

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4940]
Below is a plan and notes for the formatting cut-over and follows up on: https://github.com/triplea-game/triplea/issues/4564 where we agreed to give google java format a try.

All in all I hope this then results in a formatting PR that does not linger for long. We will be blocking the PR queue and will need to resolve conflicts, so in essence the faster we get this done and move forward, the better.

Plan:
(1) discuss and approve plan
(2) submit PR with format update. Any PRs that are opened afterwards will wait until the format PR is merged and will need to handle merge conflicts. We will merge any PRs opened before the formatting PR and the formatting PR will need to resolve those merge conflicts.

Formatting PR will have at least three commits:

(1) use bot account to run formatter
(2) update checkstyle to use line length 100 to follow google java format spec
(3) fix checkstyles, typically these will be long strings and newly required javadocs
(4*) fix conflicts, merge all PRs opened before the format update and fix conflicts

Explanation of PR commits:
(1) Using bot account as author is simply to avoid skewing stats for lines added and removed. It will also help slightly with git blame and history to more easily identify formatting only changes
(2) Formatter will use line length of 100 but it will not wrap long strings automatically for us. If we keep line length 120, we'll still need to fix these strings and we'll fix them to be 120. We'll then have an inconsistent line length where all code except strings will wrap to 100 characters. If we then update to have a consistent line length we'll need redo the same fixes to get to 100 characters. The idea is to save work and go directly to a consistent line length.
(3) After updating the format, there can be more line breaking meaning some methods will become longer and will breach the length requiring them to have a javadoc. Google java format also does not automatically break long strings and that must be done manaully.

Plan for review of the formatting PR:
- we have historically reviewed formatting changes and had the 'author' format everything to be "perfect." I strongly propose we skip this. Where formatting is a problem, we instead fix it later as needed. The first example, we had lots of fixes to code that was dropped anyways and was wasted work. Furthermore, if there is interest to go through a long diff and find formatting issues, some of which will be pre-existing problems, it's just as well for that to be done post-merge with fixes. Overall looking at the diff, there are just a couple hand-formatted javadocs that will be slightly mangled, so overall the review of bad auto-formatting is far less needed than in the past where we really did get some whacky formats.
- The other updates will be isolated commits, ideally the review of those will be pretty trivial and done without too much effort.

Post-Merge:
- Once the format update is merged, fast-follow with a PR with documentation/setup instructions. We can have people contribute and comment as they follow them, this will help account for the variety of dev environments and isolate documentation changes from all the other updates.

Summary of benefits:
- Formatting done automatically is one less thing we will need to worry less about. We do have an automated formatter but there are still formattings that are done by hand or left up to author. Removing these will incur a frequent and small recurring benefit.
- Current formatter does not work well in javadocs and IDEA, often there are situations where there is a conflict between checkstyle and formatter where javadocs require hacked formatting to not get in a state where the formatter creates a checkstyle violation.

**Comment by DanVanAtta** [comment]
@asvitkine FYI on the above, please comment if you any large updates (more than a dozen lines) in-flight (on your computer) that are not submitted for PR. If so, I'll be happy to coordinate with you  that those updates are submitted for PR before we update formatting.

**Comment by asvitkine** [comment]
No changes besides the ones I have open. Thanks for pinging.

**Comment by ron-murhammer** [comment]
@DanVanAtta Alright. I'm fine giving this a shot and your approach looks good to me. I don't really have any major in-flight branches so now is as good a time as any if we are gonna do it.

**Comment by DanVanAtta** [comment]
PR to with google java format applied is open!
