### ISSUE TITLE
Combat Window Territory Thumbnail Not Rendering Correctly

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4953]
## Problem
Territory thumbnail in combat window is not rendering correctly

## Repro
Start a combat, notice the territory thumbnail rendering

Not able to repro with SHA: f55fd39fae124aaa7bbe2384544f29b5f617a180 (before seamless zoom, problem is introduced at seamless zoom or thereafter)

### Observed:
![Screenshot from 2019-08-09 14-10-36](https://user-images.githubusercontent.com/12397753/62809849-f8a3b700-bab0-11e9-835b-68102b6471e2.png)

### Expected:
![Screenshot from 2019-08-09 14-14-23](https://user-images.githubusercontent.com/12397753/62809850-f8a3b700-bab0-11e9-8294-69d23918caed.png)

**Comment by RoiEXLab** [comment]
Yeah, that's probably my fault. I'll have a look, should be super simple to fix in theory

**Comment by RoiEXLab** [comment]
Ok, it's not what I initially expected. Looks like this regression was introduced in #4927

**Comment by RoiEXLab** [comment]
Ok I found the issue.
It's super dumb and I think I made the same error a while back in a different place
