### ISSUE TITLE
Battle Window Goes to Background on Casualty Selection

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4954]
## Problem

During combat, when the 'select casualties' window appears, the battle window goes to background, behind the map window. This causes the battle window to no longer be visible.

I was able to repro this problem before seamless zoom, problem is introduced sometime between then and the latest release.

## Repro

Fight a combat that has a casualty selection. When "Select Casualties" button is clicked, notice the combat window goes to background.

In the screenshot below, notice the combat window is not visible (it is behind the map window):
![Screenshot from 2019-08-09 14-52-26](https://user-images.githubusercontent.com/12397753/62811127-6651e200-bab5-11e9-8094-3266acdb56a8.png)

### Expected Behavior

Combat window should stay visible, casualty selection would appear on top of that window.

Casualty selection should look like this with the combat window visible:
![Screenshot from 2019-08-09 14-20-30](https://user-images.githubusercontent.com/12397753/62810791-f858eb00-bab3-11e9-91a5-203db710752b.png)

**Comment by Cernelius** [comment]
Maybe off topic, but please make so that the battle window is always superimposed to the map window.

**Comment by ron-murhammer** [comment]
Closing this based on fix.
