### ISSUE TITLE
"Network Commands" Design Idea to Replace RMI

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4986]
Wanted to pitch an idea for an architecture change that I'm tempted to prototype.

The gist is the following, instead of having a RMI call like: `remoteDelegate.executeRemoteMethod("arg1",  "arg2")`, we would replace it with a String payload that indicates through a lookup table which method to call.

Essentially the RMI call would be replaced with a universal entry-point that would look something like this:

`universalRemoteDelegate.sendMessage(payload)`, where payload would be structured roughly as follows:

```
- module: remoteMethods
  method: methodName
  args:
       firstArgName: "argValue"
       secondArgName: "argValue2"
  from: nodeId
  gameId:  gameUuid 
```

Then the client side would then have a lookup table that would likely be a couple of switch statements, eg:

```
class UniversalDelegate {

    void receiveMessage(String yaml) {
        String module = yaml.readModule();
        switch(module) {
             case(remoteMethods):
                     remoteMethods.handle(yaml);
                     break;
             case(BattleDelegates):
                 :
             case(PlayerDelegates):
                 :
             case(ChatDelegates):
                 :
             case(GameDelegate):
                 :
             case(SoundDelegate):
                 :
        }
    }
}

class RemoteMethods {
   void handleMethod(String yaml) {
        String methodName = yaml.getMethod();
        switch(methodName) {
              case methodA:
                       this.methodA(
                            yaml.getArgs().get("firstArgName"), 
                           yaml.getArgs().get("secondArgName");
        }

   }
}
```

### Benefits and motivation

- much compatibility concerns drop away and are more obvious. It's unclear which of many methods today are invoked by RMI, there can be surprises. With the above the RMI is reduced to essentially a single method that then interprets the String payload and goes on to call the right method.
- Network calls become very clear, you can trace the code back to the network handling code and then know it'll be invoked over network.
- String payload allows for greater compatibility. Today swapping method ordering, changing names, or adding a RMI method means the game can crash when communicating with a different version. With the explicit handling we could have a client warn the user that an unsupported feature is being used or wire in legacy handling or simply have the game intelligently warn that an unsupported game feature is in use.
- We might be able to drop state from the server and have a pure relay server for the bots. If a server can avoid maintaining a game data object and just relays network messages, then we can potentially have bots just be a relay of the network commands. If we can do that, the memory footprint of a bot dramatically drops and the bot instances become network bound instead of memory bound. With luck we could then use one bot instance to handle *many* games.

**Comment by RoiEXLab** [comment]
Interesting consideration. From a high-level perspective this sounds good.
Open question:
AFAIK there are currently a lot of complex objects like GameData being sent over the network. snakeyaml-engine has a way to serialize and deserialize those with limitations, but how exactly are you planning to send complex objects over the network?

2 things to consider:
1. Transport independent. Right now it sounds like you're keeping the nio socket and everything as-is. Ideally the API would be designed in a way the actual transport (TCP, websocket, etc.) can be easily replaced using something future-proof.
2. I'd recommend formatting everything as JSON to keep the packet size rather small. I believe snakeyaml-engine should have a simple way to change the formatting, so that shouldn't change anything API-wise.

> We might be able to drop state from the server and have a pure relay server for the bots. If a server can avoid maintaining a game data object and just relays network messages, then we can potentially have bots just be a relay of the network commands. If we can do that, the memory footprint of a bot dramatically drops and the bot instances become network bound instead of memory bound. With luck we could then use one bot instance to handle many games.

I'm not quite able to follow that idea. I'd appreciate if you could elaborate on that further

**Comment by DanVanAtta** [comment]
> but how exactly are you planning to send complex objects over the network?

Likely leave as is. We may have some opportunity to send 'deltas' instead of the full object.

> Transport independent. Right now it sounds like you're keeping the nio socket and everything as-is. Ideally the API would be designed in a way the actual transport (TCP, websocket, etc.) can be easily replaced using something future-proof.

Perhaps we would already be there? The key is to get a 'string' from one computer to another, then the string would have encoded all information to call the right method. How that string is delivered is transport independent as far as I can tell.

> I'd recommend formatting everything as JSON to keep the packet size rather small. I believe snakeyaml-engine should have a simple way to change the formatting, so that shouldn't change anything API-wise.

Isn't YAML smaller? There are no braces or extra quotes. I like YAML for how it encodes maps, the payloads would be human readable. JSON is also pretty error prone. I don't think packet size is really the right consideration as the overhead of the real network call is likely far larger than a few bytes here and there. 


> We might be able to drop state from the server and have a pure relay server for the bots.

Notice that the payload has a `gameId` in it. We could potentially have one instance of a bot receiving and forwarding the string messages to the correct recipients. If the payload is just a string, the bot does not need any of the handling code, just needs to know how to grab the gameId and send it to the correct players.

**Comment by RoiEXLab** [comment]
> Isn't YAML smaller? There are no braces or extra quotes. I like YAML for how it encodes maps, the payloads would be human readable. JSON is also pretty error prone. I don't think packet size is really the right consideration as the overhead of the real network call is likely far larger than a few bytes here and there.

Well "normal" YAML makes heavy use of spaces and newlines to format everything nicely.
JSON on the other hand when used for minimal file size, can omit nearly every space and newline, so it all becomes a single-line string (obviously unreadable)
I mean we could make this a debug setting, as mentioned already snakeyaml probably doesn't really care which style preference you choose.

In the end it is really just formatting and if you ask me you'll end up formatting production strings in a parser anyways to be able to visually "close down" irrelevant branches if you ask me.
A nice but probably irrelevant (for now and the near future) benefit is that JSON is the de-facto serialization format of the web, so any browser has a built-in parser and serializer

**Comment by DanVanAtta** [comment]
A benefit I did not mention was test-ability. I think we'll have some good luck testing that specific payloads are emitted and that certain payloads are handled correctly. In this case I think we'll be dealing with the payloads quite a lot. That is a place where I see a lot of interactions with the format taking place. Size is probably not the right consideration. Network compression should be able to reduce any white space sequences to a nearly equivalent number of bytes as having a single character. The escaping and error-proneness of JSON has me concerned about it as a format. I don't think web communication with the server is feasible in the next few years. It would be great, but we are so far away from that. Regardless, eventually it should not be that bad of a transformation if push comes to shove on changing the encoding format and update the decoding.

**Comment by RoiEXLab** [comment]
> Notice that the payload has a `gameId` in it. We could potentially have one instance of a bot receiving and forwarding the string messages to the correct recipients. If the payload is just a string, the bot does not need any of the handling code, just needs to know how to grab the gameId and send it to the correct players.

So you're implying that in the future every player should have their "own" GameState, and every player sends its actions to any other player to keep it synced. Is that correct?
AFAIK currently the bot itself is responsible to validate all moves and shares its "correct" game state with all the other players afterwards?


I wish you good luck with this project. I could imagine changing the part that actually send messages is the simplest part, because all RMI calls go through an InvocationHandler IIRC, but you never know

**Comment by DanVanAtta** [comment]
> So you're implying that in the future every player should have their "own" GameState, and every player sends its actions to any other player to keep it synced. Is that correct?

Note sure. Latency in multi-player games is a pretty big problem for non-hosts, it can really slow games down. If we're passing full gamedata objects around over network for every move and every game update, we would have room for some good gains. On the other hand simply reducing the amount of full gamedata transfers could be a good win too.

It may be more appropriate to still have one player be 'the host', we could potential decouple that from the message relay so that the host is not always the broadcaster and move that to the bot server only.

@RoiEXLab do you suspect I may be over-selling the benefits? I'm wondering that even if we take care of the easy stuff, essentially replace UnifiedMessenger and it's dependent with a string based command-pattern, is that a good gain? I'm thinking it's in part the extended network graph of the additional messengers and remote delegates that can make network calls less obvious. Even then, the backward compatibility aspects I think are appealing as well.

**Comment by RoiEXLab** [comment]
I don't think you're overselling, I just think the "benefit" is not really the next step after this feature works but would require a couple of intermediate steps which is a lot of work

**Comment by DanVanAtta** [comment]
Moved design proposal to wiki: https://github.com/triplea-game/triplea/wiki/Network-Commands
