### ISSUE TITLE
Continuous Builds (AKA continuous deployment)

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5]
I heard Travis suggested as a continuous build tool. Free for open source, seems attractive. An alternative would be bamboo, but IMO I like the idea of staying in GitHub + Travis tools for now as a good thing.

**Comment by ron-murhammer** [comment]
So I don't think we are at a point of needing a continuous build tool yet. We don't release very often or have many developers/unit tests to make running it for every commit worthwhile. I personally have lots of experience with Jenkins and a little bit with Bamboo.

**Comment by DanVanAtta** [comment]
TripleA code base likely hits a lot of criteria for needing a continuous build:
- it's a medium/large code base that is relatively old and has had a number of contributors
- automating builds/deployment will save time and effort, very important on an open source project where people will get busy with other work
- perhaps the key benefit of the continuous build is you have something that runs your tests on a regular basis. We had broken tests when I first started looking at the code seriously not too long ago, so I would suggest this is evidence we have a need for such a system. (the alternative is to have a human at  run builds automatically, record log outputs, run times, number of tests, etc.. )

Last I would suggest that not needing a continuous build is similar to someone saying that we don't need unit tests, we don't need version control, we don't need ant, we don't need functional/acceptance tests or a release process ;) So with respect, unless it costs something after being set up, the automation benefit we gain I think makes this a pretty easy case. The key then is agreeing on which tools to use.

**Comment by DanVanAtta** [comment]
Cloud based build tool and free for open source the two main criteria we have. AFAIK this leaves:
- Bamboo
- Travis

**Comment by ron-murhammer** [comment]
So to clarify, I'm not saying we couldn't use a continuous build tool but that there are a lot of things I would prioritize before setting one up. We really don't have many unit tests or many contributors. Right now running the unit tests we have means almost nothing since it provides so little functional coverage. I would rather spend time improving unit tests than setting up continuous builds at this point. As we get more unit tests and more contributors then a continuous build tool becomes a higher priority.

**Comment by DanVanAtta** [comment]
It's not just a matter of running the tests, you need to record the results as well and publish/communicate them. The overhead of doing this manually is large and simply just won't get done too often if not automated. We get more benefit from automation setting it up sooner (and it tends to be easier to set up as well).

I bring this tool up namely because I think it is an important early step on getting a handle on our tests. Having a central authority that runs the tests regularly is IMO invaluable to making sure they stay working and are used.

**Comment by DanVanAtta** [comment]
Alright, no point in arguing about things we fundamentally agree on. If anyone disagrees, please raise/open an issue, but otherwise:
- if anyone sets up a continuous build, prefer/start with Travis, otherwise go to Bamboo.
