### ISSUE TITLE
NullPointerException when trying to load installed maps

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#5022]
### Engine version
1.10.15336

### Map name
any installed map (latest versions)

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Start Triple A, hit "Select Map", select any map.
A window pops up:
![npe](https://user-images.githubusercontent.com/20812775/63292077-2a90f680-c2c5-11e9-8bea-4f54a30c936d.PNG)

 I have got a "NullPointerException" in the error.log:

### Do you have the exact error text? Please copy/paste if so

[error.log](https://github.com/triplea-game/triplea/files/3517278/error.log)

### Instead of this error, what should have happened?
TripleA should allow me to choose the game-type, select the players and start the game.

### Any additional information that may help

Interestingly after some tries I can load the map as expected and continue.
So this error seems to be maybe related to a fresh installation?

**Comment by RoiEXLab** [comment]
This seems to be some sort of race condition, not sure why exactly this happens sometimes. Can't reproduce it, but I created #5023  which hopefully fixes this.
