### ISSUE TITLE
CheckStyle and spotlessApply conflict

### ISSUE THREAD

**Issue by OrdoFlammae** [triplea-game/triplea#5024]
Apparently CheckStyle and spotlessApply have different ideas about how to do things. CheckStyle wants the ending curly brace of every method to be on its own line, while, when spotlessApply runs, it moves the ending curly brace of empty methods to the same line as the declaration. Which side do we want to go with? So far, we've been using the spotlessApply way of things, so should we just remove the one check from the CheckStyle?

**Comment by DanVanAtta** [comment]
@OrdoFlammae do you have any example Java files or code examples where you've seen this behavior?

**Comment by OrdoFlammae** [comment]
For example, in AaInMoveUtil.java, the current code is
```
AaInMoveUtil() {}
```

CheckStyle complains if it isn't
```
AaInMoveUtil() {
}
```

This happens around 356 times currently in 253 files.

**Comment by DanVanAtta** [comment]
The gradle build checks for violations and fails if there are any. I suspect maybe you're not using the checked-in checkstyle configuration. Could you check that you've configured the checkstyle plugin to use it?

It should look something like this:
![Screenshot from 2019-08-21 12-15-41](https://user-images.githubusercontent.com/12397753/63461481-91b9c280-c40d-11e9-81d5-4d1d043ad464.png)

We've a checked-in settings config as well under `/.ide-intellij`, importing that might auto-configure this for you. It'd be interesting to know if that is or is not working as well.

**Comment by OrdoFlammae** [comment]
It looks like the problem is that my Checkstyle version is later than yours (8.23).

**Comment by DanVanAtta** [comment]
I'm able to repro the problem after bumping up the checkstyle version. It does seem the checkstyle rules are in conflict.
I submitted a PR to remove the conflicting checkstyle rules: https://github.com/triplea-game/triplea/pull/5031

**Comment by RoiEXLab** [comment]
Fixed in #5031
