### ISSUE TITLE
Move Documentation to Wiki? Use wiki for design docs?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5033]
I'd like to propose we expand and formalize our use of wiki. Notably:
- move any design docs to wiki
- move any documentation from git to wiki

Previously a blocker from using wiki for documentation was the lack of an ability to create sub-trees to categorize the information. With a 'sidebar' file we can create such a structure: https://github.com/adriantanasa/github-wiki-sidebar/wiki

I've already committed to the wiki repo that update to have a sidebar that allows for nested lists. (Essentially there is an options.json file that is dropped in that provides some markup, from there the _Siderbar.md file is just a standard MD file with links and nested lists).

I think with the documentation as a wiki we'll be a bit more encouraged to update it without needing to go through a PR process. This perhaps will help make the documentation, particularly the non-dev (eg: map maker) documentation be more of a living document. It also should provide a nice home for design documentation and notes (which currently we have very little of).

For background, we've discussed wiki a bit before, mostly in context of tracking feature requests:

- "Feature Requests Wiki Update" #4249
- "Feature Request Process with new NodeBB Forum " #2010
- "the wiki!" https://github.com/triplea-game/triplea/issues/45
> I would imagine the github wiki to be about the code, config, project, and stuff surrounding that.

**Comment by ron-murhammer** [comment]
I'm fine with that. Anything we can do to ensure documentation is 1. consolidated in one place and 2. is easy to maintain and update even for less technical users is a win IMO.

**Comment by RoiEXLab** [comment]
I always found it a little bit hard to navigate through the git documentation in the webclient, so that's a win in my opinion

**Comment by DanVanAtta** [comment]
Thanks for responses! Has been a go!

@OrdoFlammae considering you've recently joined and had to go through the setup with fresh eyes, any feedback you have on the documentation is very welcome! Really appreciate the clean setup and noting things that are out of date, it's been good :smile:

**Comment by DanVanAtta** [comment]
#5046 is a new thread to discuss any further documentation improvements and feedback.
