### ISSUE TITLE
'Shift' Click to Unload Transports no longer works

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5035]
### Engine version
1.10.14690+

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
- Load a transport with a land unit
- Shift Click SZ containing transport
- Try to unload on an adjacent land territory
- Notice: error Message

### Instead of this error, what should have happened?
Land units on sea transport should unload

### Any additional information that may help
I bisected the error to this commit: 1860c849a61a9f003abe70b3645487690dcc2d63 (tag: 1.10.14690) Fix incorrect transports unloading

**Comment by DanVanAtta** [comment]
https://github.com/triplea-game/triplea/pull/5037 fixes this, but possibly breaks the bug-fix that originally introduced the probelm

**Comment by ron-murhammer** [comment]
@DanVanAtta I think this will have side effects and probably isn't the best way to fix this. Closing in favor of #5049.

**Comment by ron-murhammer** [comment]
Closing based on #5049.
