### ISSUE TITLE
Documentation Discussion / Improvements

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5046]
Want to create a conversation thread on the documentation and track discussion on how it can be improved and what we think about it now that it is in wiki. Anyone should feel free to improve it, otherwise would be happy to see any discussion on the state of documentation and what people think of it.

@OrdoFlammae as the newest person to contribute, any feedback you have is very valuable, thank you for your recent contributions and jumping in!

**Comment by Cernelius** [comment]
About documentation, has the "ice box" process been documented anywhere? I'm not finding it in the wiki.
Reference:
https://github.com/triplea-game/triplea/issues/3960

**Comment by DanVanAtta** [comment]
See response in #3960; The labels can be viewed here: https://github.com/triplea-game/triplea/labels and there is a description next to them in case they are not self-descriptive. 

We could use a policy/way to remove stale issues that are beyond their useful life and are simply not worked on. It's ideal for them to be solved, at some point the ROI of having a long queue of things you'll never work on is self-defeating. For now as there is no such policy, it's a bit beyond the existing documentation. There is a 'team communication' document which notes a bit about how issues are to be used. Beyond that it's been a bit tiresome to constantly restate why software projects use bug tracking software and how bugs are to be tracked. Again ideally that is not something that needs a manual for someone to be able to do. It's for example like a door, if you need to read instructions for how to use it, it's a problem with how the door is designed.

How issues are handled by the team, beyond how they are submitted, perhaps could use clearer instructions, but I'm not sure if we have a policy that is really that formal beyond we track things and fix them as we have effort/interest/availability.
