### ISSUE TITLE
Consolidate included images

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#5048]
Consolidate images as we have them in 2 different places:
https://github.com/triplea-game/triplea/tree/master/game-headed/assets
https://github.com/triplea-game/assets

**Comment by DanVanAtta** [comment]
They need to be downloaded, run `./gradlew downloadImages`

**Comment by ron-murhammer** [comment]
@DanVanAtta Why do they need to be downloaded? All the other asset images are included in the assets folder directly?

**Comment by DanVanAtta** [comment]
- It's an anti-pattern to check in binary files to git.
- We're close to the 1 gig limit. If we cycle through the image files we'll run out of space.
- The new downloadImages task creates infrastructure so we do not have to continue checking in binary files.

**Comment by ron-murhammer** [comment]
@DanVanAtta I'm not necessarily against the direction here but have 2 issues:
1. Inconsistency where most of the existing binary files are in the included assets folder
2. Not clear that some extra gradle command needs run to pull in necessary images when running from source

**Comment by DanVanAtta** [comment]
The existing files should be migrated. It's not appropriate to migrate them all ad-hoc as soon as the first latest example comes along. It's also not right to never download them because they are all checked in and to forever continue that. It's a low ROI activity to migrate them all just for consistency. Rock and a hard place. 

FWIW `./gradlew run` will execute the download images command. 

The change could have been better advertised.

**Comment by ron-murhammer** [comment]
I guess I prefer consistency as a few small images in this repo or in a separate asset repo doesn't matter much. Otherwise it can be confusing to other developers why images are in a bunch of different places. I guess I'll update this issue to instead say consolidate images.

**Comment by DanVanAtta** [comment]
As part of the consolidation, we also have images in `src/main/resources`, eg:
`./src/main/resources/org/triplea/game/client/ui/javafx/images/join_game.png`

**Comment by DanVanAtta** [comment]
Just to be sure, `https://github.com/triplea-game/assets` is the desired consolidation location. We can recreate that repo pretty readily and avoid any space limitation, we also already download assets from that location as part of the full build.

**Comment by DanVanAtta** [comment]
Was looking for a way to get eclipse to run the downloadImages task automatically on build. It looked like there might be a gradle config to do this, I was not able to get eclipse working well enough to test this out.

```
modified: build.gradle
──────────────────────────────────────────────────────────────────────────────────────────
@ build.gradle:9 @ plugins {
    id 'io.franzbecker.gradle-lombok' version '2.0' apply false
    id 'net.ltgt.errorprone' version '0.8.1' apply false
    id 'com.diffplug.gradle.spotless' version '3.23.0' apply false
+    id 'eclipse'
}

apply from: 'gradle/scripts/yaml.gradle'
dan@dan-desk:~/work/triplea$ gd 3
──────────────────────────────────────────────────────────────────────────────────────────
modified: game-headed/build.gradle
──────────────────────────────────────────────────────────────────────────────────────────
@ build.gradle:17 @ ext {
    releasesDir = file("$buildDir/releases")
}

 
+eclipse {
+   autoBuildTasks downloadImages
+}
 
```

**Comment by DanVanAtta** [comment]
All images and mp3 files from: https://github.com/triplea-game/assets 
Are now in: https://github.com/triplea-game/triplea/tree/master/game-headed/assets

We can close this issue or keep tracking until all images are in the assets repo.

**Comment by DanVanAtta** [comment]
" until all images are in the assets repo."

To clarify, not all images in game-headed are located in the assets folder.

**Comment by DanVanAtta** [comment]
The two locations noted in the description are consolidated! Closing, further consolidation of all the other locations is an outstanding technical debt.
