### ISSUE TITLE
Running Lobby locally is not documented

### ISSUE THREAD

**Issue by OrdoFlammae** [triplea-game/triplea#5050]
### Engine version
1.10.15393

### My Operating System
Linux Mint

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Launch lobby, client, connect to lobby with client.

### Do you have the exact error text? Please copy/paste if so
No Client Version, games.strategy.net.CouldNotLoginException

### Instead of this error, what should have happened?
Should have connected.

**Comment by DanVanAtta** [comment]
@OrdoFlammae I was able to connect locally. Are you updating the 'engine preferences > testing > lobby host' to localhost? The setting needs a restart to take effect, also the lobby DB needs to be running for lobby to accept the connection.

**Comment by OrdoFlammae** [comment]
I got it working. However, the whole process isn't documented, as far as I can tell. I thought to connect to a custom lobby, you used the connect to networked game. Also, how can you tell if the lobby DB is running? Do you just run `./run_docker` and `./run_flyway` every time you need it?

**Comment by DanVanAtta** [comment]
The `./launch_db` is all-in-one. Tempted to remove that script though.

There is a `./build_docker` command that is truly one-time, from then on after system restarts it's the two commands mentioned. If there are changes that need to be applied to DB, `./run_flyway` is the command, and there is a `./drop_db` command to help with iterating on a new migration file. Flyway fails if a previously run migration file has been updated, hence the drop and recreate of local DB.

The README has some notes: https://github.com/triplea-game/triplea/tree/master/lobby-db

Curious if those notes are sufficient, happy to see a PR to update it as useful. There could be a link in wiki to that README, that seems important. I suspect it's better to have that info localized to the project, not sure if we want to move the README contents to lobby, but perhaps it would make sense.

**Comment by DanVanAtta** [comment]
The process of connecting to local lobby needs to be documented..

There are notes on: https://github.com/triplea-game/triplea/tree/master/lobby, not sure again if it makes more sense to reference that README from wiki or to move the instructions to wiki. The notes on updating game settings do need to be added in one of those locations.

**Comment by OrdoFlammae** [comment]
Seeing that the codebase consistently has READMEs in every individual project, in my opinion, it makes more sense just to reference that README from the wiki.

**Comment by DanVanAtta** [comment]
Added some documentation notes here: https://github.com/triplea-game/triplea/wiki/Local-Build-and-Testing#connecting-to-a-local-lobby
