### ISSUE TITLE
Eclipse Google Java Formatter Plugin Missing

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5051]
It looks like google bodged up the plugins and did not release an official v1.7 eclipse plugin for google java format, yet spotless and Intellij use 1.7 by default. Hence there is a difference between how eclipse formats (uses 1.6, per the official instructions: https://github.com/google/google-java-format#eclipse)

An existing issue was raised with them (https://github.com/google/google-java-format/issues/331) and there is a link to an unofficial 1.7 plugin file: [unofficial 1.7 eclipse plugin](https://github.com/google/google-java-format/files/2774507/google-java-format-eclipse-plugin-1.7.0.jar.zip)

@ron-murhammer could you see if you can download the unofficial plugin, unzip it, and place the extracted jar file in the drops folder and see if that works? I was able to repro the problem you were having and the unofficial worked on my local eclipse.

**Comment by ron-murhammer** [comment]
@DanVanAtta Yep, that works.

**Comment by DanVanAtta** [comment]
Cool, I'll update the setup instructions, thanks for giving it a shot :smile:
