### ISSUE TITLE
Install4j8 Upgrade

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5057]
I submitted a request for an updated license.

Of note they recommend bundling the jetbrains JRE for swing desktop applications to pick up fixes not available in other JREs. They recommend another JRE for JavaFX apps to avoid bundling.

Opening this thread to consolidate communication on the topic.

**Comment by RoiEXLab** [comment]
Interesting, I'd be happy to give JBR a shot.
I don't think we're at the point to focus at JavaFX, but we should definitely keep that in mind

**Comment by DanVanAtta** [comment]
Adding this as a release 2.0 task
