### ISSUE TITLE
Issue Templates

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#5072]
Just noticed this message:
![Template](https://user-images.githubusercontent.com/8350879/63613126-47d50600-c5e0-11e9-8c28-ce8e173d0709.png)
Basically this ["new" template system](https://help.github.com/en/articles/about-issue-and-pull-request-templates) would allow us to have multiple templates depending on the situation, which is nice so we don't have to remove all the layout just to have a discussion ticket (which is what I just did).
However it looks like @ron-murhammer would have to do that because they are buried somewhere in the Repo Settings.

Ideas for potential templates?

**Comment by DanVanAtta** [comment]
@RoiEXLab see: https://github.com/triplea-game/triplea/issues/4686

**Comment by DanVanAtta** [comment]
Seems we have some natural categories, something perhaps like:
- Bug
- Feature Request (with a stop sign on this one)
- Project Discussion
- Code Design Discussion

-----

I suspect we may want to revisit how we track feature requests before or after we design categories, probably after and focus on reflecting current process.

**Comment by RoiEXLab** [comment]
> Feature Request (with a stop sign on this one)

That's exactly what I was thinking 👍 

I also agree with those other categories

**Comment by ron-murhammer** [comment]
Here are the base templates that are available that we can customize:
https://github.com/triplea-game/triplea/pull/5082

**Comment by DanVanAtta** [comment]
@ron-murhammer are you intending we submit PRs into your branch, or will you handle getting the baseline in place? Will any file in "ISSUE_TEMPLATE" be picked up, or is there a config in the settings where each file is specified?

**Comment by DanVanAtta** [comment]
Added a few commits to the branch. @RoiEXLab , feel free to take a pass at it and let's merge it up!

Thanks @ron-murhammer again for getting it started.
