### ISSUE TITLE
No new pre-releases?

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#5073]
The latest pre-release is 1.10.15422, created about 14 hours ago as of typing this.
Some pull requests have been merged in the meantime.

Should not at least https://github.com/triplea-game/triplea/pull/5064 have initiated a new pre-release?

Have I missed something?

**Comment by RoiEXLab** [comment]
No you haven't the deployment has been fixed just a few minutes ago, the first artifact was created a few seconds ago.
Thanks anyways ^^
