### ISSUE TITLE
Irritating minor Intellij issue

### ISSUE THREAD

**Issue by OrdoFlammae** [triplea-game/triplea#5074]
Intellij keeps marking an error in `build.gradle` on the first line
```
import net.ltgt.gradle.errorprone.CheckSeverity
```
Is there a way to fix this, or am I just going to have to live with it.

I'm also having a similar issue with the scripts in `scripts/`, where Intellij doesn't find the dependencies. My build works just fine, but it's rather irritating to have Intellij mark errors where no errors exist.

**Comment by DanVanAtta** [comment]
I see this error as well, agree it would be nice to see it fixed

**Comment by OrdoFlammae** [comment]
I've been looking around, it might be an Intellij bug, where it just doesn't expect import statements inside a gradle file. I'm not sure what's going on with the scripts, since the stuff they're using is clearly in the classpath, but for some reason Intellij's parser is just not using it. For the build.gradle file, the problem is that Intellij is not even sticking `net.ltgt.gradle.errorprone.*` on the classpath at all. I'm wondering if the jar files that the scripts are using were imported for a completely different reason, since if I copy problem imports over to the build.gradle file, they still doesn't work, even though they're on the classpath. Another interesting pattern I've noticed is that all the problem imports require jar files, and as far as I can tell, the ones that don't require jar files to be satisfied (are build in to Gradle) don't have any issues.

**Comment by RoiEXLab** [comment]
It is an intellij bug, I haven't even found a workaround for this unfortunately :/

**Comment by OrdoFlammae** [comment]
Has it been reported?

**Comment by RoiEXLab** [comment]
I found a ton of similar IntelliJ issues, but not this exact issue.
But I haven't really found an up-to-date issue regarding this though

**Comment by OrdoFlammae** [comment]
Well, this isn't really an issue that can be solved, so I'm going to go ahead and close it. I'll see if I can either find the issue, or create my own.
