### ISSUE TITLE
Available map list resource leak

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#508]
When the game launches we scan for available maps in the background. This is so we can cache that list and then show the choose game screen (in theory) immediately. 

It turns out there is a resource leak, the zip files are still open/being access on windows. We can tell this is a problem since the files can no longer be deleted (access  denied error).

Since we can now parse available map files without reading the entire zip file, and the choose game screen now loading quickly, we may not need the available game cache anymore at all. Then again, that perhaps may not be the problem.. So this needs a bit more investigation.

**Comment by DanVanAtta** [comment]
The background cached maps causes a number of problems, and with the map parsing that is now magnitudes faster, there is much less value. Plus, the code for it is complicated, and it uses up a lot of memory as well.

I really don't think it's worth 'fixing' the cache to find and resolve the resource leak. My intent is to remove the cache completely at a cost of the choose game window potentially loading more slowly.

**Comment by ron-murhammer** [comment]
@DanVanAtta There also appears to be some issues across restarts. If you launch a game as 1.8.0.9 then close TripleA then launch 1.9, you get an error as it tries to parse old maps. Not sure if this is the same leak or a different issue.

**Comment by DanVanAtta** [comment]
I suspect that is unrelated, probably a bug in 1.9 if I had to guess. I think the XML DTD file was missed in the 'attatch' update. Some quality time is needed with the map parse exceptions to sort them out and make them go away in 1.9

**Comment by DanVanAtta** [comment]
For this one, task is to populate the available game list without ever actually opening up the game zip files. If we open the zip files, we will not be able to delete them on windows
(TODO; verify that simply opening the file causes the file handle leak on windows, maybe we are doing something else that is actually causing the leak)

**Comment by RoiEXLab** [comment]
Is this being fixed by #693 ?

**Comment by DanVanAtta** [comment]
I don't know. The windows virtual box VM I have at the moment is too flaky to do development work on, and this is a windows only problem.

**Comment by DanVanAtta** [comment]
@RoiEXLab , if you want to take a poke at this, please feel free. I need to do some work to get set up on windows before I can start tackling this effectively.

Chances are good we are not closing a file somewhere. A simplified repro case would be ideal.

**Comment by DanVanAtta** [comment]
This is proving to be a difficult problem. According to this java file leak detection tool: http://file-leak-detector.kohsuke.org/, the file handle in this code snippet is not closed:
```
/* NewGameChooserEntry.java, line ~43 */


 public NewGameChooserEntry(final URI uri)
      throws IOException, GameParseException, SAXException, EngineVersionException {
    m_url = uri;
    final AtomicReference<String> gameName = new AtomicReference<>();
    try (InputStream input = uri.toURL().openStream()) { // line 45 << indicated to leak the file
      final boolean delayParsing = GameRunner2.getDelayedParsing();
      m_data = new GameParser().parse(input, gameName, delayParsing);
      m_gameDataFullyLoaded = !delayParsing;
      m_gameNameAndMapNameProperty = getGameName() + ":" + getMapNameProperty();
    }
  }
```
https://github.com/triplea-game/triplea/blob/master/src/games/strategy/engine/framework/ui/NewGameChooserEntry.java

**Comment by DanVanAtta** [comment]
http://www.genevski.com/2010/04/javaneturl-and-jarurlconnection-may.html

> URLConnection and its subclasses may open resources like files and sockets and keep them open "for a while" to improve efficiency. [...]   Even with OpenJDK, it is very likely to have resource leaks if the URL is referencing an entry in the jar file.
[...]
According to the javadoc, this behavior can be controlled by the property "useCaches" which probably defaults to "true".

This looks to have been the problem : )
Will hopefully have a fix out shortly.

**Comment by RoiEXLab** [comment]
@DanVanAtta works, can be closed

**Comment by RoiEXLab** [comment]
@DanVanAtta This can be closed, I guess
