### ISSUE TITLE
Game engine compatibility and Map Compatibility with Relation to Map Version -> Map Max Version

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5081]
Working on Version, the topic of Map compatibility version number comes up.

Today, we have a 'min version' number to tell the engine when it knows it should not attempt to parse a map version and instead warn user that they need to update. For example, if a map min version is 2.1 and the engine is 2.0, the engine will simply fail and tell user to upgrade the engine.

But, for the other way round, when a map is 'old' and an engine is too recent, we do *not* have a 'max version' field for maps. Today in that case the engine hits a parse error, or we are forced to upgrade all maps.

I think it makes sense to add a 'max version' field for maps so that an engine can at least more gracefully handle the situation where it cannot parse a map rather than failing with a parse error (or forcing us to upgrade all maps in a coordinated way such that old engines and new engines will be able to read them, which is difficult).

For example, we could have a map that has, min version 1.9.0.2, and max version 2.1. This then opens up the possibility even where we can add logic so that we are not always forced to upgrade all maps and can have a game engine hook to detect if a max version is below a certain value and to change how we parse the map to support that map. At some point, for example version 5.0, we could say that we've upgraded all maps to beyond version 2.1 and then simply fail on maps that have a max version of 2.1 (which would be the behavior of today)

Building on this idea, we essentially have compatibility 'zones' that are going to be defined by engine releases depending on when we update map parsing logic. For example, let's say 1.9, 1.10, 2.0, and 2.1 all can parse the same maps, and 2.2, 2.3 and 2.4 can parse the same map. At that point we have a mapping of game engine numbers to another single number, {1.9, 1.10, 2.0, 2.1} -> 1, and {2.2, 2.3, 2.4} -> 2
If we then call that the map version number, it then really simplifies the logic around maps. We can simply say a given map is "version 2" instead of saying "min = 1.9 and max = 2.1". This also has the benefit we never have to retrofit maps with a max version number. For example today a latest map would have min version '2.0', and when engine version 2.1, 2.2, 2.3, etc.. come out, the game engine will not be able to know at what point it can no longer parse the map. Instead if that map were labeled with version "2", the game engine will know when it can only read map version "3" and could then fail gracefully (or potentially fall back to a map version "2" parser)

The biggest benefit here is that we buy liberty to not have to always upgrade all maps when we make parsing changes. We should keep all maps playable, previous attempts to upgrade all maps has shown it to be massively painful even for very straight forward changes (it is painful due to shear quantity and secondly we do not host all maps in existence).

**Comment by RoiEXLab** [comment]
Well semver has a concept of defining ranges.
See https://devhints.io/semver for some examples.
Might be overkill having this degree of control, but just wanted to point it out.
But max version would probably work good enough (semver ranges aren't perfect either)

**Comment by ron-murhammer** [comment]
Personally, I don't think we'd ever use it. And if we did then we are essentially killing off maps and wouldn't be that different from just deleting them. Unless I'm missing something here.

**Comment by DanVanAtta** [comment]
@RoiEXLab having a range or a max value is not necessarily a problem. Mapping that range to a single number though means we do not have to update maps when we discover a new max. For example, let's say all maps are compatible with 2.0. Then eventually at 3.1, they are no longer compatible. That implies either:
- the map will have no max range, in which case a 3.1 engine will try to parse it and error out (the behavior we have today).
- or, we update all maps to mark them as having a max of 3.1

On the other hand, if all maps compatible with version 2.0 had version "A", and then when version 3.1 comes along, it could see the "A" and know it cannot be parsed. That happens for us without having to update maps and add in a max. 

--------

@ron-murhammer there is a nuance I think that could be missing. Such max value could be used to extend the life of some maps.

Today, if we change map parsing but do not update a map, the map is basically unusable. We would just as well delete it. Furthermore, the UX is poor as the game engine just blows up and fails to read the map.

With a max version at the least the game engine would be able to gracefully tell the user which TripleA version they should use (an earlier version). This is the very inverse of the 'min' version on maps.

Best case, we could extend the life of the map by adding in some backward compatibility code. For example some of the renames could be pretty easily handled by having the engine check version and use one name or another. As an extreme example, we could be to go as far as using the 'old jar' mechanism.

It's also worth considering we get a really nice migration path. Today if we upgrade  map then it forces players to use a new game engine. Considering a lot of updates like that are in bulk, we'd be locking out those users almost all at once. It's really most impactful for soft releases to a new version as we can't change all maps to open up the new version as we'd still want to support old engines, so the new version would not have any maps to use (or the engine would be forced to stay compatible; hence having a max version alleviates that restriction and buys us options).

**Comment by ron-murhammer** [comment]
@DanVanAtta I mean I can see your points, I just don't think users are going to download an old version to play a map that we essentially are killing off. If we moved back to a system where we packaged old engine versions then it could be useful but other than that I think its kind of overkill and unnecessary.

**Comment by DanVanAtta** [comment]
I don't think people will download old versions either, but at least the error message can be accurate. Sorry if I implied we would be killing a map, it's not at all what I meant. For example, if we fix one of the many typo's in map XMLs, we can't simply push that change as it breaks all current versions of the engine. We are then stuck living with any map XML errors and new maps must continue with the same mistakes. On the other hand with a max, a new engine could still more easily read old maps, and it would not be the case that a new engine suddenly can't read maps. That puts us in a tough situation when maps only work with either old versions, or new, but not both.

**Comment by DanVanAtta** [comment]
To clarify:
1) Fix typo in game engine. Now the game engine can't read any maps
2) We fix the maps, now previous versions of the game engine can't read maps.

That essentially means we can't fix maps, or if we do, we have to create/update maps that are intended to work specifically with new engines. When we upgrade maps, it's a difficult process.

**Comment by RoiEXLab** [comment]
You reminded me of something:
Because of backwards compatibility, we still "Normalize" attachment setters and getters to make sure all maps with this "case error" which was previously ignored would continue to work after having removed the reflection.
Even though I fixed the typo for all maps, we decided to go for backwards compatibility, because maps might not be updated that fast.
At this point it might be safe to remove that feature
