### ISSUE TITLE
Usability problem - Download Maps Has Empty Tabs

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5090]
**Describe the bug**
Download maps window having empty tabs is confusing. For example, start a download and then select another tab. If the tab is empty, then it looks buggy. A desired fix would be to remove the "available" tab if it has no content. (note, if a map is uninstalled, then we may need to add the tab back in).

**To Reproduce**
1. Open download window
2. Download all maps from any of the categories
3. Switch tabs
4. Start a download
5. Switch back to the category where all maps are downloaded
6. Notice the behavior looks broken

**Expected behavior**
After step (2) above, remove the tab so user cannot view an empty tab.

**Screenshots**
For example, one tab will look like this:
![Screenshot from 2019-08-25 15-27-40](https://user-images.githubusercontent.com/12397753/63656732-f1390a80-c74c-11e9-9cb2-e92c8c4cae2f.png)

Then switching tabs, can see:
![Screenshot from 2019-08-25 15-27-30](https://user-images.githubusercontent.com/12397753/63656731-f0a07400-c74c-11e9-9be1-473bef96fe39.png)

**OS (please put an X in the appropriate box):**
[] Windows
[] Mac
[X] Linux

**Comment by asvitkine** [comment]
This UI isn't the same anymore.
