### ISSUE TITLE
Two jar-files in /bin - increased size of the *.jar file

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#5095]
I noticed the increased size of the downloader (here Win7 64bit) with Version 2.0.15540.

An image says more than 1000 words:
![bin](https://user-images.githubusercontent.com/20812775/63674543-08c4d180-c7e7-11e9-96de-c607a0890464.PNG)

Starting the game the engine picks the first *.jar:
![bin2](https://user-images.githubusercontent.com/20812775/63675119-63126200-c7e8-11e9-8a5b-2fc061e7f9e3.PNG)

Apart from the double-jar, why has the size of the *.jar increased from 18 to 27 MB?

**Comment by DanVanAtta** [comment]
Artifact size increased when version number was updated. With luck fixing the double artifact will also fix that as well.
Fix is up for PR: https://github.com/triplea-game/triplea/pull/5097
