### ISSUE TITLE
IDE launcher files

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#51]
I've got a couple of eclipse launchers with args to launch the game and the headless server, and a third for running tests. It's preferable I think to have these files checked in, easier than giving details of how to set them up. Also when I clean my environment it's one way I can see to make set up time easier and more efficient.

Questions:
- Any objections to these launcher files being checked in? 
- To the intelliJ users, can intelliJ piggyback on the eclipse launchers, or do we need versions for intelliJ?
- Any suggestions for good folder structures to hold these files?

**Comment by gaborbernat** [comment]
these should not be checked in, there are and will be Gradle tasks that users can call instead :)

**Comment by DanVanAtta** [comment]
:+1: 

I'm a bit surprised gradle can create launchers with the right runtime path.

Does gradle create more than a project, but also la launcher? Secondly, the eclipse command is going to be: ./gradlew eclipse?  Thanks.

**Comment by gaborbernat** [comment]
Look here: https://github.com/eclipse/buildship/blob/master/docs/user/Overview.md

Gradle does not create it, but you can create it with a push of a button via that plugin (the official Gradle plugin for eclipse)

**Comment by DanVanAtta** [comment]
Sounds good, this is not that much of an issue then. It does sound like we do have to code something for gradle to execute our various tasks (like for example running main game,  headless server, lobby).

Gonna go ahead and close this, sounds like gradle will handle this.
