### ISSUE TITLE
Snyk security scanner

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5127]
**Topic and Overview**

Found out about: https://app.snyk.io/
It's like codecov or LGTM, but for security vulnerabilities.

It has a badge we can add!
![Screenshot from 2019-08-29 18-21-44](https://user-images.githubusercontent.com/12397753/63986685-e7cfdb00-ca89-11e9-918f-95c954c4c5bd.png)

It's free for open source.

**Desired Outcome**
Add Synk scanning to repo. Requires owner to add permissions and go through the snyk setup. Was pretty painless to do that for a forked repo, took a few minutes.

**Comment by RoiEXLab** [comment]
Github has some sort of built-in security scanner that is currently in public beta.
I don't think java/maven is supported yet, so it might be worth giving it a shot nevertheless

**Comment by DanVanAtta** [comment]
The cost to us seems about right, just enabling a configuration. If snyk does manage to find anything, it'll be incredibly valuable.

**Comment by DanVanAtta** [comment]
@ron-murhammer any action on this? Having an automated security vulnerability checker configured against the code base seems like a valuable thing to have. It should be a matter of just granting access to the app and not take much time.

**Comment by DanVanAtta** [comment]
@ron-murhammer bump, please have a look, this should take 5 minutes.

**Comment by DanVanAtta** [comment]
@veqryn , @ron-murhammer ; please have a conversation, something like this should not take 15 days and receive zero responses from the owners. Something seems wrong.

**Comment by DanVanAtta** [comment]
@ron-murhammer @veqryn , i've no suggestions here other than to magically create time and capacity, [wave fairy dust]. Perhaps the triage process could be improved. My concern is that when there is capacity for an integration, a delayed response can lose that time window and drag things out and conflict with other projects. The 'waiting on this' scenario means other initiatives are started to try and fill the pipeline, meanwhile too much is then worked on and doesn't get over the finish line quickly enough. On the other hand idle, but available efforts is a horrible situation for this project as we need all the capacity and effort possible. 

I guess just ignore this last thread, in the interest of being focused and effective... Let's get stuff done.

**Comment by ron-murhammer** [comment]
Taking a look at this now. Sorry I have been busy the last few weeks and was focusing on finishing up the unit image colorizing/flipping work.

**Comment by ron-murhammer** [comment]
Configured and PR to add the badge: https://github.com/triplea-game/triplea/pull/5209

Good news is it appears it didn't find any security vulnerabilities!

**Comment by veqryn** [comment]
I'm ok with thi.

Also, since I've been pretty out of the project for a few years now, I have triplea repo configured to not ping me unless someone `@veqryn` in a thread/issue/pr.

Perhaps we can think about adding DanVanAtta or another committed team member as an owner?

**Comment by DanVanAtta** [comment]
Ron is a far better project manager/owner than I and has the community backing while I'm good at making myself unpopular. The owner permission I think would be useful for being able to manage team membership, beyond that I would not use it for anything without Ron's consent anyways. So maybe no point.

Having two people with owner is important. If @veqryn, you'd rather step back a bit further from this project and I be the 'backup' owner, then perhaps it could make more sense. 

Bottom line, Ron is the project lead, he is better at that role than I, having a single authoritative, final decision maker is valuable.
