### ISSUE TITLE
Lock Map option no longer honored during combat

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/triplea#5156]
**Describe the bug**
The **View > Lock Map** menu option, when enabled, no longer locks the map during combat.  Upon starting a battle, the map is centered on the battle territory.

**To Reproduce**
1. Enable **View > Lock Map**.
1. Create at least one battle during combat movement.
1. Scroll the map to a location away from the territory where combat will occur.
1. Begin combat phase.

**Actual behavior**
The map is centered on the battle territory.

**Expected behavior**
The map position should not be changed when combat starts while the Lock Map option is enabled.

**OS (please put an X in the appropriate box):**
[X] Windows
[] Mac
[] Linux

**Additional context**
Works as expected in 2.0.15703; does not work in 2.0.15714.

In [this code](https://github.com/triplea-game/triplea/pull/5148/files#diff-b89f33450b1eaec80444d48846001deeR31-R34), I suspect `getDefaultValue().orElse(false)` should actually be `getValueOrThrow()` since Boolean client settings always have a default value.

(I also noticed that sound effects no longer work in 15714, but they work in 15703.)

**Comment by DanVanAtta** [comment]
I suspect the lock map issue is introduced here: https://github.com/triplea-game/triplea/pull/5148/files#diff-b64b921312bc432716370a9b8af40d05L409

Sound effects no longer working is pretty major, probably introduced in the same PR

**Comment by DanVanAtta** [comment]
> In this code, I suspect getDefaultValue().orElse(false) should actually be getValueOrThrow() since Boolean client settings always have a default value.

That's where the bug is. `getDefaultValue()` always returns false for 'lock map'

The boolean client setting has a 'getSetting' method because boolean values always do a have a default value of false now.

**Comment by DanVanAtta** [comment]
https://github.com/triplea-game/triplea/issues/5160 and https://github.com/triplea-game/triplea/issues/5161 fix the two problems noted here.

**Comment by ssoloff** [comment]
Confirmed both issues are fixed in 2.0.15739.  Thanks!
