### ISSUE TITLE
Download Map Window Appearing Behind Main Menu

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#516]
If I open Download Maps, close it, and open it again then it doesn't come to the front. First time I open it then it does.

Happens on at least Windows 7.

**Comment by RoiEXLab** [comment]
Did your pull request fix this issue? If it did please close this issue.

**Comment by DanVanAtta** [comment]
I'm pretty sure it did not.

**Comment by DanVanAtta** [comment]
Now that the download window is modal, this could be fixed maybe.

**Comment by RoiEXLab** [comment]
Can stil confirm for Windows 10 x64

**Comment by RoiEXLab** [comment]
#1001 has a Fix
