### ISSUE TITLE
Find Territory no longer centers map on selected territory when Lock Map enabled

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/triplea#5162]
**Describe the bug**
The **View > Find Territory** command no longer centers the map on the selected territory when the **View > Lock Map** menu option is enabled.  Lock Map, by design, is intended to only prevent programmatic map position changes, not user-initiated changes.

**To Reproduce**
1. Enable **View > Lock Map**.
1. Run the **View > Find Territory...** command.
1. Select a territory from the dropdown list.

**Actual behavior**
The map position does not change.

**Expected behavior**
The map is centered on the selected territory.

**OS (please put an X in the appropriate box):**
[X] Windows
[] Mac
[] Linux

**Additional context**
Works as expected in 2.0.15703; does not work in 2.0.15739.  (It works as expected in both releases when Lock Map is disabled.)

I suspect the [removal of the `MapPanel#withMapUnlocked()` method](https://github.com/triplea-game/triplea/pull/5148/files#diff-b64b921312bc432716370a9b8af40d05L399-L421) in #5148 is the root cause.

**Comment by DanVanAtta** [comment]
Thanks for reporting :+1: 
A fix is up for PR

**Comment by ssoloff** [comment]
Fix confirmed in 2.0.15760.  Thank you.
