### ISSUE TITLE
Integ Tests 'not safe' to run in parallel; Non-deterministic test output

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5163]
**Describe the bug**
Running integration tests in parallel can result in test failures depending on test ordering and concurrency.

**To Reproduce**
Run tests with `./gradlew --parallel integTest`

**Expected behavior**
Ideally test cases would be able to run in parallel, 100% success rate.

**Additional context**
The problem is rooted with the manipulation of DB data per test. 
Perhaps if we can get all tests to use 'insert' mode so they add their data, that would allow existing tests to keep using the dataset that they expect. This approach would need to solve for the case of 'expected datasets' having additional data. I think there might be a flag for expected dataset to ignore additional data.

**Comment by RoiEXLab** [comment]
Just learned that in theory JUnit supports parallel test execution, so ideally we'd check if unit tests can be executed in parallel and try to extend that to integration tests as well, even though it won't be that easy
