### ISSUE TITLE
Please turn on auto-delete of branches

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5176]
**Topic and Overview**

To skip the busy-work of branch cleanup, in settings, please turn on auto-delete:
![Screenshot from 2019-09-03 11-05-39](https://user-images.githubusercontent.com/12397753/64197389-d9434400-ce3a-11e9-9a28-13fea73c993c.png)

**Comment by ron-murhammer** [comment]
Agree. Done.
