### ISSUE TITLE
Asset Contributor Team

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5183]
I created a team 'asset-contributor': https://github.com/orgs/triplea-game/teams/asset-contributors/members?add=true

My thinking is anyone on that team will have write access to the map maker asset repo: https://github.com/triplea-game/map-maker-assets/; they'd be able to merge their own PRs, merge PRs from guest members, or even push to master directly. I'd like anyone that submits a good PR or is a well known community member to be added. 

Though, only owners can add new team members. @ron-murhammer sound good? Could you add @beelee1 to the team?

**Comment by ron-murhammer** [comment]
Agree. Done.
