### ISSUE TITLE
Hide Opponent Units More Than One Territory Away

### ISSUE THREAD

**Issue by jmgraySC** [triplea-game/triplea#5187]
For play-by-email games, a nice feature to consider if possible would be to "hide" competitors' units that are more than one territory away from those that you occupy or control.

The territory zones in question would have to be visible from a map perspective, however competitive units include in said territories would not be visible.  Would offer a nice enhancement for building strategy over several turns, not allowing competitors to necessarily see what is going on.  Good example could be a pincer movement taking a turn or two to develop.

Technology purchases could be added in if desired to help minimize the limitation, radar for example.  

If no technology is purchased, then the units would not reveal themselves until they enter a territory that is one move away.

**Comment by DanVanAtta** [comment]
'Fog of war' feature is something desired. The blocker is how to prevent someone from taking a save game and then loading the game from their opponents point of view.

**Comment by ron-murhammer** [comment]
Yeah, we have a feature request for this already: https://forums.triplea-game.org/topic/551/fog-of-war

Primarily, for both fog of war and any kind of card system, we would need a way to password protect certain nations in a save game.

**Comment by Cernelius** [comment]
An issue I see for typical TripleA games, and especially for historically based games, is that you have a starting setup with units spread over the map.

If you would start with fog of war, that would not make sense, as having a fixed starting setup, you can know where everything is at start (by just loading the game on local as all the players), so you would try to hide what cannot be hidden.

If you would start without fog of war, then applying it only to whatever new it happens on the board after the game starts, that would not make sense, as there can be no reasons why you have perfect knowledge at start game, but lose this ability immediately as the game start. Moreover, you still know the exact starting location of all the stuff, so you would have to spend a huge quantity of time guessing where the units can possibly be based on their starting locations, that would make the game much harder to play competitively than just knowing everything all the time.

I think fog of war can really work feasibly only for games in which you just start at a point only and build up pretty much everything you'll have from there. For example, it would probably work well for Feudal Japan, but not for most TripleA games currently in existance, unless you are merely going to play them against the AI or without a competitive gameplay.

I'm curious what games you had in mind for this feature, but I really think it will not work very well on any games having a very developed starting setup, which comprises all the games of the World War II series.
