### ISSUE TITLE
Stalebot Integration

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5196]
Would be great to have a bot do the closing of 'stale' issues. I'd be happy to add the config once the app is given permissions. I'm thinking we'll exempt game-rule tickets from the closing on stale. Would be excellent I think to have the stale text request that any outstanding tasks be created as new, individual task tickets. That in essence is automating a process that we implicitly have today. ie: https://forums.triplea-game.org/post/26858

https://github.com/apps/stale/installations/new

-----------

I've been noticing stale bot in use on travis, the link to the actual bot I found after discovering their blog post on closing old issues:
- https://blog.travis-ci.com/2018-03-09-closing-old-issues

**Comment by DanVanAtta** [comment]
@ron-murhammer bump, given the permission sets, this is something you have to configure. It should not take long, please weigh in.

**Comment by ron-murhammer** [comment]
@DanVanAtta This should now be installed across the repos. If you want to give it a try then you should be able to just create a `stale.yml` in the repo. I'll leave this issue open in case you want to discuss which repos and the configuration.

**Comment by DanVanAtta** [comment]
Thank you @ron-murhammer ; added a proposed config: https://github.com/triplea-game/triplea/pull/5210
Let's follow up as part of the PR and iterate on threshold, configuration, and stale text as part of the PR.
