### ISSUE TITLE
code folder structure update

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#52]
Unless my arithmetic is off, we have 27 files at the top level folder and 16 folders. This is quite a lot of content at the top of the project folder. Consider we are rebuilding our build system (ant to gradle), it should be a good time to move to a more organized folder structure.

Below is a summary of how many files we have by file extension type:
```
~/work/triplea$ find . -maxdepth 1 -type f  | sed 's/.*\.//g' | sort | uniq -c | sort -nr
      6 xml
      6 sh
      3 bat
      2 txt
      2 plist
      2 gradle
      2 exe
      1 vimrc
      1 properties
      1 pdf
      1 md
      1 ini
      1 html
      1 /gradlew
      1 gitignore
      1 docx
```

The 6 XML files include:
```
$ ls *.xml
build.xml            launch4j_embedded_jre.config.xml
digests-include.xml  triplea_java_eclipse_cleanup.xml
launch4j.config.xml  triplea_java_eclipse_format_style.xml
```
3 of those files look like logger files that just need to be on the classpath. Standard thing to do AFAIK is to have a "resources" folder for this. For us, we can probably put these files in data or assets maybe since those are on most paths. We could also create a resource folder to house them.

The two eclipse xml files could use a home, likely with other IDE files.

The 6 *.sh and 3 *.bat files can likely go into a scripts folder.

There looks to be a long tail of documentation files, we can probably organize those in a docs folder.

I'm interested to hear thoughts if this is reasonable, and or alternatives or improvements/additions.

For  convenience, here is the listing I get from the top level tripleA folder:

```
~/work/triplea$ ls
assets                            maps
bin                               old
build.gradle                      readme.html
build.xml                         README.md
changelog.txt                     run-headless-game-host-mac-os.sh
data                              run-headless-game-host.sh
dice_servers                      run-headless-game-host-windows.bat
digests-include.xml               run-server.sh
doc                               ServerInfo.plist
fix_mac_icon.sh                   settings.gradle
gradle                            src
gradlew                           system.ini
gradlew.bat                       test
icons                             triplea_embeded_jre.exe
Info.plist                        triplea.exe
installer                         triplea_java_eclipse_cleanup.xml
junit                             triplea_java_eclipse_format_style.xml
launch4j.config.xml               triplea_mac_os_x.sh
launch4j_embedded_jre.config.xml  TripleA_RuleBook.docx
lib                               TripleA_RuleBook.pdf
license                           triplea_unix.sh
MacOS_users_read_this_first.txt   triplea_windows.bat
```

**Comment by gaborbernat** [comment]
once the ant to gradle transition is complete some of these files will be removed :) (no eclipse, ant files, etc). we can also remove afterwards some of the other non used files, such as the old folder.

**Comment by DanVanAtta** [comment]
Careful, those are not project files, formatter and cleanup really probably should be in version control since they can evolve. 

Regrettably I think, gradle won't get rid of too many files. Sticking the scripts into a "scripts" folder already will get us a pretty big bank for our buck (50% of files roughly now organized out of top level folder).

**Comment by DanVanAtta** [comment]
The old folder are "old" but supported engines. The code has logic to spin up JVMs from classes in those Jars to play maps for old game engines.

**Comment by veqryn** [comment]
i guess it all depends on how the next build process works, and what is built
i do like that i can click on and directly run the .exe and .sh files, and have them work (assuming the bin folder has a triplea.jar in it, from previously building), but i think those references are relative and can be updated
the 'assets' folder is purely for "game assets" such as unit images, etc, and we should not mix build/config/code/env stuff into that folder
i do not think any of the root level files need to be on the java classpath, because they are all just config files for building (like the launch4j stuff, and the .sh/.exe/.bat), for ide's, etc.

**Comment by DanVanAtta** [comment]
Next build process will need to find the resources somehow, just like the ant one does. Looks like gradle is not yet so far along that it contains references to these files yet (so only build.xml needs to be updated, but only looks like for a few). Looks like the clean-up can be done. Below is what would be my attempt at it, may as well be specific about what goes where. Leaves us with 23 files:


```
mkdir scripts
mv *.sh *.bat scripts/

mv license/ readme.html changelog.txt MacOS_users_read_this_first.txt doc/

mkdir doc/rulebook
mv TripleA_RuleBook.* doc/rulebook/

mkdir resources
   ## will need build.xml updates (gradle doesn't have these files yet it appears)
mv launch4j* digests-include.xml Info.plist ServerInfo.plist system.ini resources/ 

  ## remove these two built windows binary files? (these two moved into scripts or left alone are alternatives)
git rm triplea_embeded_jre.exe triplea.exe 
```

Now *23* files and folders left:
```
~/work/triplea$ ls
assets        derby_db      installer  resources
bin           dice_servers  junit      scripts
build.gradle  doc           lib        settings.gradle
build.xml     gradle        maps       src
classes       gradlew       old        test
data          icons         README.md
```

**Comment by DanVanAtta** [comment]
Seems like there is no opposition to organizing the files. It seems like next steps would be to do work and submit a PR. Closing this issue until there is more to discuss.
