### ISSUE TITLE
Desura + Partner Sites

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#521]
Looking at the release instructions for updating partner sites: https://github.com/triplea-game/triplea/wiki/Release-Update-Desura-and-Partners

We have three, desura and two others. Both of these two have 1.8.0.3:
- http://www.freewarefiles.com/TripleA_program_56699.html
- http://download.cnet.com/TripleA/3000-18516_4-75184098.html

For these last two I recommend we drop them. It's hard to see the value in uploading the 3 or 4   different OS installers per release to those two sites.

@veqryn , @ron-murhammer , thoughts about dropping our listing from download.cent and freewarefiles.com?

My unverified impression of desura is we get some significant downloads/plays from there.  Looking at the stats provided: http://www.desura.com/games/triplea/stats, we're getting a dozen people per day. That is actually not too bad. @ron-murhammer  or @veqryn , is it easy for either of you two to update desura? I think I have access to do so, but it's something I'd rather leave alone personally. Second question, is the current desura info up to date, or is it another situation where people are getting old versions?

**Comment by veqryn** [comment]
I'm fine with dropping those.
Desura gets a good number of downloads, and maybe there is a way to automate most of the process of uploading to them.
I think Desura is on 1805.

**Comment by DanVanAtta** [comment]
Desura needs quite a bit of updating.. Mentions the multiple AIs and 11 maps being included. For desura and for sure the other two sites,  ideally we would add a static link to: "https://github.com/triplea-game/triplea/releases/latest", or even better the github.io website download page.

**Comment by ZjelcoP** [comment]
Updated the FreewareFiles links and info few months back. Have been monitoring it and there are about 200 downloads per month through that site now.
Seems worth keeping it I'd say...

Desura offers 1.8.0.3 if you choose to download without account. No idea about logged in downloading.
Cnet is also still on 1.8.0.3

I can update all these if okay and you supply me login details

**Comment by DanVanAtta** [comment]
@veqryn @ron-murhammer , could either of you hook @ZjelcoP up with the credentials for the triplea desura account?

**Comment by ZjelcoP** [comment]
http://www.freewarefiles.com/TripleA_program_56699.html
Has been updated to 1.9.0.0

http://www.desura.com/
Is currently down after being bought and is awaiting relaunch.

http://download.cnet.com/TripleA/3000-18516_4-75184098.html
Is managed by tripleadevelopers@gmail.com.
If the details for that email-account are unknown I can apply to take over the download-link.
Easier if someone has the login.

**Comment by veqryn** [comment]
@ZjelcoP I sent the pw to @ron-murhammer and @DanVanAtta
