### ISSUE TITLE
Pre-releases not showing pictures and gifs in notifications

### ISSUE THREAD

**Issue by FrostionAAA** [triplea-game/triplea#5213]
**Describe the bug**
The latest pre-releases do not render images and gif files that should be displayed in notifications.

**To Reproduce**
You can see this when starting Iron War, Dragon War, Star Trek and other maps that have notifications during map start.

**Comment by Cernelius** [comment]
While at it, can you please add WebP images too? They are way better than all formats currently supported, especially GIF.

https://developers.google.com/speed/webp/
(here you can find a converter too)

**Comment by ron-murhammer** [comment]
I'm fairly certain this is a Java bug as I had noticed the same thing for TWW in the pre-release and tracked it down to this: https://bugs.openjdk.java.net/browse/JDK-8222250

**Comment by RoiEXLab** [comment]
This might be a good reason to switch to JDK 13

**Comment by RoiEXLab** [comment]
Nevermind, I just saw that it seems this Bugfix was backported to 11.0.4 and later

**Comment by DanVanAtta** [comment]
https://github.com/triplea-game/triplea/pull/5269 updates installers to install4j8 with 11.0.4 bundled

**Comment by DanVanAtta** [comment]
@FrostionAAA if you would, could you check if this is fixed with the latest prerelease? The installer is on a new major version and has a different JDK installed with it, with luck all will go smoothly.

**Comment by FrostionAAA** [comment]
I tested with TripleA 2.0.16005. It seems to work again :-)
