### ISSUE TITLE
Standards Change: DB table + column comments

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5214]
I'd like to propose we keep doing table comments but make column comments optional and use them when helpful and non-obvious.

For example, column comments on why we have both a `bcrypt_password` and `password` field seems helpful.

Otherwise it seems like column comments are usually pretty obvious and have become busy work, eg:
```
comment on column lobby_user.date_created is 'The timestamp of the creation of the account.';
comment on table moderator_action_history is 'Table storing an audit history of actions taken by moderators';
comment on column moderator_action_history.id is 'Table storing an audit history of actions taken by moderators';
```

**Comment by prastle** [comment]
Fine w/me
