### ISSUE TITLE
UI Freeze Problem vs AI

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5216]
**Describe the bug**
When progressing to combat phase, a pop-up appears warning player should fight one battle first, but combat window is also opened and neither the combat window nor the warning dialog can be closed.

Reported in:
https://forums.triplea-game.org/topic/1555/new-version-bug-2-0-15781/2

**To Reproduce**
- load attached save game
- allow game to proceed to combat phase

**Expected behavior**
- AI likely should fight battles in dependent order so that the dialog does not pop-up to begin with
- Screen focus should not be locked between the two windows, should be able to close one window or the other.

**Zipped Save Game**

[autosave.tsvg.zip](https://github.com/triplea-game/triplea/files/3618138/autosave.tsvg.zip)

**Comment by ron-murhammer** [comment]
@DanVanAtta The save game is not compatible with the latest pre-release so this isn't testable anymore. Do we know how to recreate a similar save game?

**Comment by DanVanAtta** [comment]
We'll need to repro and get a new save. Setting up a battle with amphib assaults perhaps could be a shortcut and then launching the AI on it. I suspect the problem is rooted in the battle order selection, that AI perhaps is choosing which battles to fight and then other logic added to enforce battle ordering is kicking in, causing this issue.

**Comment by DanVanAtta** [comment]
The problem can still be reproduced, the situation creates a game freeze.

The save game is compatible with this SHA: d41d54609a26722c03cfda819be50e07e22df26b

To avoid errors loading the save game due to version, set the product version in `product.properties` to:
```version = 2.0.15781```

(I'm pretty sure that tag, 2.0.15781, could also be checked out for compatibility, the SHA above is the latest version from Sep 12)

**Comment by asvitkine** [comment]
My recollection is the problem was caused by a battle being incorrectly marked as dependent - which should no longer happen after the fix. Is it possible this dependency is still encoded in the save game and therefore the problem appears when loading it - but wouldn't appear in a new game?

**Comment by DanVanAtta** [comment]
Which fix are you referring to @asvitkine ?
The dependency is not encoded in the save game, the AI FWIW does make the same decisions and given that we're dealing with a fixed version of the code, the same sequence plays out and is hence reproducible.

**Comment by asvitkine** [comment]
I was referring to my fix #5653. The symptom of that bug was indeed a pop up that says a sea battle was completed.

It was caused by an incorrect call to:
```
battleTracker.addDependency(battleAmphib, battle);
```

Which that change fixed. Are you saying the dependency added by the above is not part of the saved game? I would assume it was. If so, that change probably should have fixed this bug.

However, right now I'm having trouble loading the link to the forum post in the bug report.

**Comment by DanVanAtta** [comment]
The forum post does not matter, load the SHA noted, then the save game, hack the game version property value (or else there is another deadlock), and the AI should create and then get itself into a deadlock with the out of battle order problem.

**Comment by asvitkine** [comment]
@DanVanAtta that SHA is before my fix though. If you patch the fix from #5653, does it still repro?

**Comment by DanVanAtta** [comment]
The save game could not be loaded in Nov (deserialization incompatibility), the fix is in December, we won't be able to check that save game at that point.

**Comment by asvitkine** [comment]
But we can patch in the diff locally to the code base at that SHA.

**Comment by DanVanAtta** [comment]
Good point, let's re-open until we can confirm the fix. @asvitkine would you be willing to do that?

**Comment by asvitkine** [comment]
Thanks! I confirm that the issue still persists even with that fix patched in.

So that means it's a different issue - although could be of similar nature (e.g. an incorrect dependency being marked).

**Comment by asvitkine** [comment]
When I load an autosave of that game "before battle" and set germans to humans, it appears that every battle is being marked as being dependent on the battle in Dijon - including the battle in Dijon itself!

So definitely seems like there's a bug there in how battle dependencies are marked.

**Comment by asvitkine** [comment]
Actually looks like it's not related to dependencies. The error message comes from:

```
    final IBattle battle = battleTracker.getPendingBattle(territory, bombing, type);
    if (currentBattle != null && currentBattle != battle) {
      return "Must finish "
          + getFightingWord(currentBattle)
          + " in "
          + currentBattle.getTerritory()
          + " first";
    }
```

So it's not a dependency. Seems a battle gets started, but not marked as finished?

**Comment by asvitkine** [comment]
It seems the currentBattle member of BattleDelegate is set to the Dijon battle even before Germany makes the combat move, it's set in loadState() when restoring the save game.

So the issue doesn't repro from scratch there - it's just encoded in the save game.

**Comment by asvitkine** [comment]
To confirm the above, you can load the save game but set Germans to a human player. Then, perform two battles (if only one is performed, for some reason BattleDelegate code isn't called). You'll hit the same error.

So the bug is in whatever version produced this save game. Is there a repro to produce a save game that has currentBattle set in BattleDelegate outside of combat phase?

**Comment by DanVanAtta** [comment]
@asvitkine the version used was likely the lastest when this ticket was cut.

I'm not aware of too many changes in this area of the code. Seems we will need either a preventative fix or handle the scenario.

@asvitkine are you still able to follow up on this?

**Comment by DanVanAtta** [comment]
Alright, I think we can chalk this one up to something being just weird.. 

I created a save game where I created strategic bombing attack and saved the game after AA fired (really the first place to save after a bombing combat). 

I hacked in the below code to always hit the 'Must finish' dialog, and it never even executed:

```
@ BattleDelegate.java:222 @ public class BattleDelegate extends BaseTripleADelegate implements IBattleDelega
  public String fightBattle(
      final Territory territory, final boolean bombing, final BattleType type) {
    final IBattle battle = battleTracker.getPendingBattle(territory, bombing, type);
-    if (currentBattle != null && currentBattle != battle) {
-      return "Must finish "
-          + getFightingWord(currentBattle)
-          + " in "
-          + currentBattle.getTerritory()
-          + " first";
+    if (true || (currentBattle != null && currentBattle != battle)) {
+      return "Must finish battle!";
 ```

On the other hand, I did notice this NPE:
```
SEVERE: null
java.lang.NullPointerException
	at games.strategy.triplea.delegate.battle.BattleDelegate.start(BattleDelegate.java:116)
	at games.strategy.engine.framework.ServerGame.startStep(ServerGame.java:520)
	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:399)
	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:289)
```
Though, the above was not game-crashing, it did open up the game staging screen (a new window) *and* the in-progress game continued.
