### ISSUE TITLE
Feature Request Tracking - Move to wiki?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5221]
@ron-murhammer are you still tracking feature requests in forums?

I'm thinking we may want to move that list to wiki. I'm opposed to any forum process where the original post is editted by people other than the original author. 
- I think that worked well when it was usually the case that it was always the same person, I don't think that extends to a team
- Updating original post is pretty confusing, nobody then knows exactly what the original post says. It's human nature to skim and not read such content

Taken altogether, it seems like @ron-murhammer is a single-point-of-failure for tracking feature requests.

If we move to wiki, we'd simply need to create a wiki page, move the list of requested features there, and update the forum post to reference that wiki list.

**Comment by ron-murhammer** [comment]
Yeah, its here: https://forums.triplea-game.org/topic/182/guidelines-and-feature-request-list

We can move to the wiki though I would like to still link to it from the forum and keep the discussion related to each feature request in the forum.

**Comment by DanVanAtta** [comment]
Cool, we're in agreement @ron-murhammer, it would be a move of only the "index" of features. We would continue to encourage that feature requests land in forums to start with and be discussed there.

**Comment by DanVanAtta** [comment]
@ron-murhammer added the list of open feature requests to: https://github.com/triplea-game/triplea/wiki/Feature-Requests

Should we continue to strike-thru the finished items, or remove them from the list?

Side-note: the list would benefit from some markdown of the link, we should probably convert each link to be more like: `[topic#353](https://forums.triplea-game.org/topic/353/add-cansubmerge-unit-attribute)`

**Comment by ron-murhammer** [comment]
So the reason I strike-thru is to show progress and it essentially becomes the feature release notes. So I think that is still a good idea.

**Comment by DanVanAtta** [comment]
I'm wondering about the overhead/upkeep, but I like the indication of progress. If we strike thru we may want to note which PR number added the specific item. I wonder a bit if the release notes themselves aren't just a good enough list of the things that have been added, if we really need to show progress in the feature index list.

**Comment by DanVanAtta** [comment]
We should also consider if instead of wiki, if maybe it makes more sense even to use a project and swimlanes.

EG: https://github.com/triplea-game/triplea/projects/12

**Comment by DanVanAtta** [comment]
I'm a bit skeptical of using a project for feature tracking, but it should not be ruled out.
@ron-murhammer certainly a bit concerned that the release notes are not doing their job and we're doubling up or re-inventing that effort. Maybe the answer is to annotate the feature request list with the other changes and then eventually the set of strike-thrus and other additions then become the release notes.

We should do what's needed/useful and keep our overhead low, that is the metric I would be looking at when making a decision here.

**Comment by Cernelius** [comment]
Well, you already had a feature request list in the Wiki in here. That was deleted when you moved feature request tracking to the forum (tho feature requesting here too never actually stopped). You can see what remains of that list under "Older Feature Requests from Github that Need Thread to Be Discussed/Reviewed".

Wherever it is, it is better staying where the feature requests are being tracked, and not being duplicated anywhere else (also, feature requests would be better staying in only one place too).

For making the matter less personal, you could repost it in forum under the "Admin" account, instead of as a thread of "redrum" or anybody; then clarifying in the first post that the current maintainer is "redrum", and whatever else you want (or you can also tell all moderators to freely contribute updating it, though at least it would implied all admins are free to edit the Admin posts).

Just my suggestions, of course.

**Comment by RoiEXLab** [comment]
I'm more or less neutral on this.
The main benefit of the forum for feature requests is that they can be discussed with the community before we actually have to code anything, just to find out everyone else hates this feature.
So as long as we keep this sort of review process I'm open to most suggestions.
Where exactly we want to track feature requests that were discussed thoroughly doesn't really matter to me as long as it is consistent.

**Comment by ron-murhammer** [comment]
For now, let's keep the feature request list in the forum so its in the same place as the requests. Closing this for now.
