### ISSUE TITLE
Snyk Config Not Quite Correct

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5224]
Snyk link does not seem to refer to the right repo, eg:

https://app.snyk.io/org/ron-murhammer/test/github/6535410a-de61-4168-b006-bd6ebc83786e/0bca06218746082ea131aa31d4a1019bbe99da77..d7158c616c823e9e48a3cf8a9acef992f87ee77a?fromStatus=true

Clicking through, I get a:
>  Unable to display this organisation. The organization does not exist, or you do not have permissions to access it.

**Comment by ron-murhammer** [comment]
It appears to work for me. Maybe some sort of permissions issue?

**Comment by DanVanAtta** [comment]
Note the URL listed:  'ron-murhammer/test'
I'd guess you're the only one with access @ron-murhammer

**Comment by ron-murhammer** [comment]
Probably. I didn't see any obvious option for configuring it to an organization rather than user. Did you?

**Comment by DanVanAtta** [comment]
snyk.io looks to work around the concept of organizations. It looks like security scanner issues are simply not available to those outside of the organization.

@ron-murhammer , @RoiEXLab,  please IM me your email address in forum and I can send you an invite to the snyk organization.

We could choose to drop snyk if this all feels like too much of a hassle. I think probably the most compelling reason to have it is if a vulnerability is discovered in one of our dependencies, at which point it should be flagged. If we get a lot of false positives then this might not be worth it, otherwise it seems like it is a one time config to add people.

***re: Organizations****
Snyk creates a default organization based on username, and hence the reason for the link URL. It took some digging to find where to create a new organization, I removed the existing integration and re-added a triple-game organization. On the snyk website, the organization needs to be selected in the top left, eg:
![Screenshot from 2019-09-17 11-34-14](https://user-images.githubusercontent.com/12397753/65069374-69a37d80-d93f-11e9-9bda-916e0174e6db.png)

**Comment by ron-murhammer** [comment]
Yeah, that's what I thought as well. Sent you my email. I'm fine keeping it for now and putting the 3 of us in the "snyk org".

**Comment by DanVanAtta** [comment]
TL;DR 
@RoiEXLab, please IM me your email address in forum and I can send you an invite to the snyk organization.
