### ISSUE TITLE
Propose: TODO tracking token convention

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5249]
I'd like to propose we introduce a TODO convention where a 'grep token' or a 'find token' of some sort is attached to TODO comments.

Concern:
- TODO comments are often meaningless to everyone except the author. If the TODO comment is not resolved, it hangs out in the code base
- Coming back and finding all TODO comments that related to a project or task is non-trivial, it's easy to miss.

Observations:
The TODO comments for http lobby that look like this: `TODO: Project#12 ....` has seemed pretty successful. 

So the recommendation is that we add some sort of identifier to TODO comments, it could be a project number, an issue number, or a forum discussion number. EG:
```
TODO: Project#12 ...
TODO: Issue#5312 ...
TODO: Topic#1183
```

If such a tracking number is missing, I think the incentive to create something to help track it will help us avoid future 'dangling' TODO comments that wind up never getting resolved and ultimately more/or less just add more code maintenance effort. Understanding a TODO comment, whether it is current, and what exactly is meant by it is difficult.

As another observation, we have a lot of "remove on the next release" comments and tracking them all down has been non-trivial. Worse yet, not all of them are trivial simple removes, eg: https://github.com/triplea-game/triplea/pull/5242

**Comment by ron-murhammer** [comment]
I'm fine with that. Unfortunately, it doesn't solve the larger problem of all the existing TODOs but I think makes sense for any added moving forward.

**Comment by RoiEXLab** [comment]
I can only agree with what both of you already said, noting to add here.

**Comment by DanVanAtta** [comment]
Cool, I updated the wiki: https://github.com/triplea-game/triplea/wiki/Code-Conventions#todo-comments-attach-a-tracking-token-5249

Let it be so!  :grin:
