### ISSUE TITLE
Faster review turn-around for iterative PRs

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5251]
Hate to bring this up, but a PR like https://github.com/triplea-game/triplea/pull/5240 (backend for user accounts) waiting 3 days for any kind of review is too slow. There are 2 or 3, maybe more iterations waiting for that PR to land and most all was already written in one day. That is stretching out one days of work to 6, 9 maybe 12 days. The delay adds context switching and overhead, merge conflicts. There are tools introduced in #5240 needed by other parallel work.

The alternative to hanging around waiting for iterations would be to land it all as one, which is very monolothic and unreviewable. It seems we need to reduce review overhead, do faster initial passes, and/or add a cut-off for when a self-review only is the best we can do.

**Comment by ron-murhammer** [comment]
Well guess the good news is its merged now. Not sure that we can ever guarantee reviews within 3 days for sizable PRs. Unfortunately, I've been busy the past few days and the little time I've had has been trying to push forward my large movement cost PR.

**Comment by DanVanAtta** [comment]
Understood and I hate I'm coming off as criticizing. I'll be a bit terse for brevity:
- waiting for review is a blocked state, we need to try and minimize that for project flow
- we probably should prioritize reviewing before working on our own PRs
- reviews should be limited to about 30 minutes, most people can only review around 400 LOC in that time, PRs are then ideally under 400 LOC
- it would not be fun to be a maintainer and just spend all your time reviewing

I totally understand about other priorities and ability for time investment, on the other hand it's a major problem if 3 days worth of full work, needing 5 or 6 iterations drags out for half of a month. 

I think it just comes down to that we don't have enough reviewers/maintainers and this project is not going to priority A in our lives. I'm between jobs and dealing with injury, so I've got time now to sink into TripleA, I respect that others are not in that position, and my own situation will change pretty soon.

I think there are three actionable things we can do:
1) Personal priority shift, try to get a review started right away before we advance our own PRs. I don't know how to balance this when the queue is 10 deep and a person can spend all their free time reviewing, perhaps that's a burden of maintainer, perhaps there is a balance
2) Automate more of the review. The area of opportunity I see is reducing review for style and code clarity and we can then focus on "is this the right change" and "is this structured well". Something like "sonar" https://github.com/triplea-game/triplea/issues/5244 I think can help there
3) Add a pressure release valve. Rather than building up a queue, create a mechanism where sometimes we don't require a review. I think ideally everything is reviewed and we keep the project pipeline full for everyone so nobody is blocked.

I think we need to also balance against 'quick reviews' as well, sometimes a fast review can be worse than no review at all (I learned that the hard way on other projects)

**Comment by DanVanAtta** [comment]
NB: 

> reviews should be limited to about 30 minutes, most people can only review around 400 LOC in that time, PRs are then ideally under 400 LOC

I've read a few places that reviewing past 30 minutes yields diminishing returns, the rate of detect detection and useful commentary drops off exponentially after 30 minutes, ergo, one should stop at that point. I can pull up references/citations if interested.

**Comment by ron-murhammer** [comment]
Generally agree. I generally try to focus on whatever is the oldest PR (regardless of mine vs others). Also when I personally have a major PR in flight, I tend to focus on it to avoid losing all the context I have if it sits around too long (this also tries to avoid dragging the review out too long which is hard on both the author and reviewers).

Keeping most PRs to 400 LOC is a good goal. Though some things especially which touch a lot of existing code, sometimes have to be longer to get to a usable state and have a logical grouping of functionality.

The other recommendation I would have is maybe we create a IM group of the active developers in the forum chat. If you have an important PR that is gonna block further work you are planning in the short term then highlighting that priority would help. Otherwise we start at the bottom of the queue on things that are older but maybe could wait.

**Comment by DanVanAtta** [comment]
- Strong yes on the IM group.
- 400 LOC really is a goal, some PRs have trouble not being 1000. I think 1000~1500 is getting to a harder limit when it really just needs to be done in multiple pieces; either that or be okay with a week long review.
- Agree we should try to reduce context switches, IMO it's part of the issue there are not many of us.

IMO a pressure relief valve process should probably kick in around day 3; I think ideally we get an initial response and/or full review turned around in 48 hours. Given how many of us there are, I suspect we'll run into constraints there.

To recommend more options, a PR label to indicate something is part of a 'chain' of PRs might help. A 'terminal' PR with nothing depending on it I think generally can wait longer.

**Comment by DanVanAtta** [comment]
Hmm, re-reading the 1000~1500 and being okay with a week long review, I'm not sure I like that. As a reviewer, there's a lot of context switch in an update that is that large. Perhaps some distinction should be made between prod code and test code. Regardless, trying to keep PRs manageable to a day or two of review I think is clear; Really the question is how can we get the review side to align with that?

**Comment by DanVanAtta** [comment]
I created a "PR: More to Follow" label so we can label the iterative PRs explicitly
