### ISSUE TITLE
Save files don't properly load when double clicked on macOS

### ISSUE THREAD

**Issue by NickClark** [triplea-game/triplea#5253]
**Describe the bug**
When opening a save file on macOS, it opens TripleA, but doesn't load the file.

**To Reproduce**
Double Click any save file. Notice that when TripleA starts, no save file is selected.

**Expected behavior**
The opened file should be selected. Even better if it could jump back into the game.

**OS (please put an X in the appropriate box):**
[] Windows
[x] Mac
[] Linux

**Comment by RoiEXLab** [comment]
Hey @NickClark , thanks for bringing this to our attention.
Which version of TripleA are you using?

**Comment by NickClark** [comment]
I've tried both 1.9.0.0.13066 and a recent 2.0 nightly

**Comment by RoiEXLab** [comment]
Ok, I dug a little bit into the issue.

Looks like this never actually worked because macos opens files a bit different than all other operating systems :(
I'll try a blind fix and would appreciate if @NickClark could verify it actually works once we have a build artifact (aka a new pre-release)

**Comment by RoiEXLab** [comment]
Opened #5262

**Comment by NickClark** [comment]
I'll take a look. Where's your CI's build artifacts hosted? Or is this not ready to test yet?

**Comment by RoiEXLab** [comment]
Ok, the latest pre-release should have the changes, let us know if it works.

**Comment by NickClark** [comment]
Tested v 2.0.16018 Still doesn't work with a newly created game

**Comment by RoiEXLab** [comment]
Wait, what do you mean with "newly created"?

**Comment by NickClark** [comment]
Meaning I didn't use an 1.9 save, I made sure to make a new 2.0 save file.

**Comment by RoiEXLab** [comment]
Ok, I'll have to try something else then.
There wasn't any error message either, right?

**Comment by NickClark** [comment]
No... is there a way to turn on extra logging?

**Comment by RoiEXLab** [comment]
Well there is, but unhandled exceptions always trigger an error window, so you won't get anything out of that.

**Comment by RoiEXLab** [comment]
Ok, can you try https://github.com/triplea-game/triplea/releases/tag/2.0.16048 ?
I don't expect the feature to work, but you should get an info message when trying.

**Comment by NickClark** [comment]
No info message shows... hmm. It opens the app... and it is the right version. Side note (just so you have my environment details), the window that opens reports itself as Java version 11.0.4 and Engine Version as 2.0.16048. Loaded Savegame reported as "-"

**Comment by RoiEXLab** [comment]
Ok, this helps a lot already.
This means that my approach was incorrect, I'll see if I find the correct one

**Comment by RoiEXLab** [comment]
Ok, could you try something different?
Try opening triplea as usual and double open a savegame in finder or something while triplea is running.
I currently assume that the event may be fired too early, do opening triplea first might be a workaround.
If this doesn't help I'm out of ideas :/

**Comment by asvitkine** [comment]
One thing I noticed is that the 2.0 bundle doesn't have the file extension listed in its Info.plist, unlike 1.9.

So in 1.9, we have in Info.plist:


<key>CFBundleDocumentTypes</key>
<array>
<dict>
<key>CFBundleTypeExtensions</key>
<array>
<string>tsvg</string>
</array>

So this is correct. But for 2.0 prereleases, we're just missing CFBundleDocumentTypes entries.

Do we know what changed in how we generate that file?

**Comment by asvitkine** [comment]
Also, given we're changing the save format in 2.0, should we use a different file extension?

**Comment by asvitkine** [comment]
Also, the docs for setOpenFileHandler() explicitly state:

"Please note that for macOS, notifications are only sent if the Java app is a bundled application, with a CFBundleDocumentTypes array present in its Info.plist. Check the Apple Developer Documentation for more information about Info.plist."

So fixing that should be the first thing to do. If things still don't work after that, we can investigate more.

**Comment by RoiEXLab** [comment]
That file is generated by install4j, it could be very much the case that at some point an update changed stuff.
@asvitkine if you want to dig further, you can download the install4j UI client (and use an evaluation license) and check the settings for the macos launcher.
Also I just remembered that we upgraded to a newer version some time ago and the newer version finally supports registering url handlers. Currently we're manually doing everything.

**Comment by asvitkine** [comment]
I guess another thing we can do is just bisect through the prerelease builds and find out when the Info.plist file changed and find the offending commit.

**Comment by RoiEXLab** [comment]
I don't even think you'll have to go through the builds, searching the git history of `game-headed/build.install4j` should already be enough to find a relevant commit

**Comment by asvitkine** [comment]
Actually, now that I try the installer again, it has a checkbox to associate the save game file type and this controls whether the CFBundleDocumentTypes is inserted into Info.plist. So this part actually hasn't changed, it seems.

However, I'm not sure why we provide this checkbox and not just do it all the time. I don't think I've seen any other Mac app do this - generally apps are signed and the Info.plist is not dynamically generated by the installer - since that would break signing. (Of course, TripleA builds aren't signed since we don't have that set up, but if we do want to do that in the future, it won't work with the current set up.)

**Comment by RoiEXLab** [comment]
The checkbox mostly makes sense in a windows environment because on Windows the registry acts as a lookup table for the application to launch.
On macos however every application defines its own file extensions, so no entry is replaced in any scenario.

**Comment by asvitkine** [comment]
Honestly, I think the right solution is to not use an installer at all on macOS. Given the bundle is self-contained, we should just provide a zip of the bundle.

But if we're relying on install4j to actually create the app bundle (e.g. put the JRE inside it, set the plist, etc), it might require some rework to do. Unless install4j actually has an option to just produce the app bundle instead of the installer...

**Comment by asvitkine** [comment]
In fact, the setting we're using now for macOS is marked deprecated in install4j. I'll send a PR to switch to the recommended one.
