### ISSUE TITLE
Instead of crashing game when unit image is not found, insert a 'no-image' image

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#528]

**Comment by gaborbernat** [comment]
+1

**Comment by DanVanAtta** [comment]
Still being debated a bit in the SF forums. It may make sense to use a unified unit image palette and adjust the hue of each unit in the case there are no 'overrides'. The examples we have are all corner cases where the casing of a unit image for one country is messed up.  A unified image palette would solve that. So perhaps we do not even need the no-image image. My concern about the no-image image is that it could bury mistakes that need to be fixed.

**Comment by ron-murhammer** [comment]
@DanVanAtta Can we link the SF discussion so we don't lose it?
