### ISSUE TITLE
Setting Status in Bot Games Does not Work

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5288]
**Describe the bug**
Not sure if this has always been a problem or if it's new.

Setting chat status works when hosting a network game, but joining a bot game, status does nothing.

**To Reproduce**
- Launch a local lobby, bot and headed game runner
- join the local lobby and join the bot game
- start a game
- click "Status..." in the chat window and set status to any value
- Notice: status is not applied to the chat window name. Contrast this with locally hosted games where this works.

**Expected behavior**
Status should have consistent behavior between local hosted (network) games and bot games.

**Comment by prastle** [comment]
It has never worked to my knowledge that only works for lobby
or priv host possibly

**Comment by prastle** [comment]
Just checked does not work for private host either in  stable

**Comment by DanVanAtta** [comment]
@prastle if you host a local network game, start it, and set status, that does not work with the latest release?  Want to be clear that was what you checked vs joining lobby and hosting and starting a game that way.  We have two scenarios to check and to be sure about.

**Comment by prastle** [comment]
I hosted a lobby game with current stable it does not work there either

**Comment by prastle** [comment]
Win 10 etc

**Comment by prastle** [comment]
If you read the testing lobby I can check further

**Comment by DanVanAtta** [comment]
This has been broken for a long time, ice-boxing, admitting defeat on this one. Perhaps we'll fix this after migrating network communication to websocket.

**Comment by RoiEXLab** [comment]
@DanVanAtta Did you verify this issue still exists on master?
I could imagine that due to my recent changes to the network code, we could potentially get an exception that would've been swallowed otherwise

**Comment by DanVanAtta** [comment]
Probably does still exist. 

The problem is more the status endpoint for local hosts on game stating screens IIRC is just a black-hole, missing implementation.

**Comment by RoiEXLab** [comment]
@DanVanAtta I just had a quick look at the code, and the code for the underlying data seems to be fine.
Maybe it's just a display issue? My best guess at the moment is that it could be an issue from the mismatch of public and local ip 🤷‍♂️
