### ISSUE TITLE
Export screenshot without stats

### ISSUE THREAD

**Issue by ZjelcoP** [triplea-game/triplea#529]
From Sourceforge:  http://tripleadev.1671093.n2.nabble.com/Can-anyone-give-me-a-blank-Great-War-map-that-I-can-print-out-tp7590319p7590321.html

> Since it is a recurring, albeit probably not frequent, occurrence people wanting to get a blank image of the triplea maps, to print them out and play them on board, I think it would be cool if TripleA would easily support this. So I suggest to:

Split the Export/Export Screenshot function into 2:

1) "Export Screenshot with title-stats"
2) "Export Screenshot without title-stats"

The first one would work just like the current Export Screenshot, while the second one would always set both screenshot.title.enabled=false and screenshot.stats.enabled=false, upon taking the screenshot. 

Have the same request for other reasons. Whenever you want to show off a map, or rework it into some other design you get those ugly stats in there. See this example: http://triplea.sourceforge.net/mywiki/ScreenShots
and again: http://triplea-game.github.io/

Thx Zjelco

**Comment by ZjelcoP** [comment]
Actually wonder if anyone ever finds those stats of any use? If not cancel those alltogether and be done with it......

**Comment by DanVanAtta** [comment]
Would you mind asking the question on SourceForge as well? That will hit the active map makers who are not checking github, and if nobody objects then dropping the stats altogether IMO is a good idea.
