### ISSUE TITLE
Some of the Pop Ups Have Their Buttons Swapped

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#530]
It appears some of the recent UI refactoring has causes some pop ups to have buttons in reverse order and the opposite one defaulted. Example is the end game pop up:
![capture](https://cloud.githubusercontent.com/assets/1427689/13801876/3e1b67b8-eb04-11e5-8b05-e4623b6b03b5.PNG)

Current stable release:
![capture2](https://cloud.githubusercontent.com/assets/1427689/13801889/6b280af4-eb04-11e5-9774-3b77f5fb4916.PNG)

**Comment by DanVanAtta** [comment]
We've set the default to be the negative now, to avoid confirming politics. Since this is single player, the bug of auto-confirming is not going to be hit quite as easily. Working as intended... Either we find a more robust manner, or the bug is the fact that this does not say "Do you want to quit?"

**Comment by ron-murhammer** [comment]
@DanVanAtta Can't we just have different defaults depending on the pop up? Also I'd prefer style wise to keep things consistent with all 'yes' (positive) buttons on the left and 'no' (negative) buttons on the right.

**Comment by DanVanAtta** [comment]
With different defaults, the 'no' button would sometimes be on the left hand side, no? I agree that a different solution is better. I'm thinking we apply a game latch, show a jpanel/jframe toast, and have the user click yes/no there. Benefit to this is the game map would still be scrollable, solves our problem of space bar 'auto-confirming', and the toast is still always on top. I was thinking the toast could be about the size of the minimap, and pop up bottom right above where player names are located in MP games, or left of the tech listing in single player.

**Comment by DanVanAtta** [comment]
#539 to fix

**Comment by ron-murhammer** [comment]
@DanVanAtta This appears to be fixed with the reverts. Closing it.
