### ISSUE TITLE
Map Info Pop-up is blank

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5317]
**Describe the bug**
Launching "Civil War: A House Divided", when the game starts there are two pop-ups that give the background to the scenario. Checking on latest master, there is no content in this pop-up.

**To Reproduce**
- download and start "Civil War: A House Divided"
- notice no content in message dialog

**Expected behavior**
- Content dialog is supposed to have background information on the scenario, it is not being rendered.

**Screenshots**
Observing:
![Screenshot from 2019-10-06 09-56-22](https://user-images.githubusercontent.com/12397753/66272540-ed0a0d80-e81f-11e9-86d0-d48176e50e37.png)

**Comment by ron-murhammer** [comment]
@DanVanAtta Do you think this related to https://github.com/triplea-game/triplea/issues/5213?

**Comment by ron-murhammer** [comment]
@DanVanAtta I did a quick test with latest pre-release and JDK 11.0.4 and see the dialog properly:
![image](https://user-images.githubusercontent.com/1427689/66273139-f0f55a00-e836-11e9-8b87-4d5f093197f7.png)

**Comment by DanVanAtta** [comment]
Ah, I'm using Java 11.0.2, this problem would be expected for that version. Thanks for checking @ron-murhammer , this is a quick one to resolve : )

**Comment by ron-murhammer** [comment]
@DanVanAtta Yeah, I ran into the same thing a bit ago and forced myself to upgrade my JDK as it was getting annoying while testing :)
