### ISSUE TITLE
Update unit scroller images and make them look good

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5344]
Anyone wanting to pick this up is welcome, otherwise I'll pick this back up perhaps in a week.

Task 1: Update unit scroller images with images containing a drop shadow: https://forums.triplea-game.org/post/27360

Task 2: if the images do not look good on mac, with a light colored theme, then we need to solve with likely one of these two approaches:
A) add some logic to invert colors
B) add some logic to use an alternative icon which will have inverted colors

**Comment by DanVanAtta** [comment]
- Buttons are now narrow enough to not be cut-off on the right hand side on initial map render
- Updated the button images

![Screenshot from 2019-11-17 16-23-32](https://user-images.githubusercontent.com/12397753/69016779-a4815c00-0956-11ea-9c2b-e495d11fb03d.png)

**Comment by DanVanAtta** [comment]
Napoleonic empires has a mini-map that is even more narrow than revised.

I'm thinking adding another 20px or so to the side-bar is probably a better fix at this point.

The unit move history also easily gets cut-off and adds scrollbars:
![Screenshot from 2019-11-17 18-10-06](https://user-images.githubusercontent.com/12397753/69019684-84599900-0966-11ea-9694-9696fd03224e.png)

**Comment by DanVanAtta** [comment]
Napoleonic empires has a mini-map that is even more narrow than revised.

I'm thinking adding another 20px or so to the side-bar is probably a better fix at this point.

The unit move history also easily gets cut-off and adds scrollbars:
![Screenshot from 2019-11-17 18-10-06](https://user-images.githubusercontent.com/12397753/69019684-84599900-0966-11ea-9694-9696fd03224e.png)

**Comment by RoiEXLab** [comment]
Can this be closed now that #5509 is merged?

**Comment by DanVanAtta** [comment]
yes, the minimum requirements of drop-shadows and not being cut-off seem to be met.
