### ISSUE TITLE
Report bug dialog fails during submission

### ISSUE THREAD

**Issue by sumpfralle** [triplea-game/triplea#5349]
# User Description
After an (unrelated) exception the GUI offers to upload a bug report (which is a nice feature).
After describing the issue and clicking "Post" an error is displayed and the issue is not filed.

## TripleA Version
2.0.16191

## Java Version
11.0.5-ea

## Operating System
Linux

**Comment by DanVanAtta** [comment]
The http server is not yet deployed, so the system was communicating with a server that does not exist. The error is expected, but in the meantime the bug report is valid. I'm planning to have this fixed in the short term, hopefully within the next 10 days.

**Comment by DanVanAtta** [comment]
Config is updated on (prerelease) server, verified this now works.

Related to:
- https://github.com/triplea-game/triplea/pull/5896 - Renew app token
- https://github.com/triplea-game/triplea/pull/5852 - Add encrypted app token to deployment
