### ISSUE TITLE
Parallel Integration Test Mayhem

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5352]
DB data between sub-projects is causing problems when building sub-projects in parallel. AFAIK devs should be using `./gradlew --parallel ...`  (or the `./verify` script)

An example of the problem, http-server, lobby, and DB-dao sub-projects all interact with DB data. We have a race-condition over which ones will clear and insert data into DB yielding non-deterministic test output. Adding more DB unit tests increases pressure on this race condition and it's hit a tipping point in some in-flight work I have.

How to solve? Some options:
1) We could no longer support parallel sub-project builds. The cost is slower build times for everyone on local development.
2) Move all tests that interact with a live database to a specific sub-project. Removing the DB dependency from all other sub-projects would allow sub-projects to be built in parallel. This sub-project could be called something like 'system-test' and be the only one that spins up live resources and interacts with DB. Removing the "real" DB dependency dependency from all other sub-projects would allow us to build in parallel sub-projects in parallel and not worry about tests trampling one-another.
3) Remove dependencies on live DB data. I'm not sure if this is feasible. It's a catch-22 for the lobby controller's, those are due to be removed in about 4 or 5 PRs from now, those PRs are running into this problem. The http server system test would be difficult to not have hit a live DB and we lose test coverage if we are not integrating with a real DB.

(2) seems to be the only viable option. Before making this update I want to get the opinions of the other contributors. Please let me know if the problem is not clear.

**Comment by RoiEXLab** [comment]
From the options you've given I'd lean towards option 2 as well, however I wonder about this scenario:
Is it possible to isolate the test cases from each other? If we created a temporary db for each test case that would eliminate the problems, right?

**Comment by DanVanAtta** [comment]
Having 'n' databases could be a challenge. We'd have to solve the performance problems, how to clone a baseline database and/or run DB migrations quickly, second configuration would be a challenge for dynamic ports, instance to be spun up at the right time. If we go with an in-memory route, something like H2, it still would be costly to spin that up per test and we would still have an integration test problem as eventually we would want to communicate to a real database and do so from multiple sub-projects.

Additive only data could be a good way to go so we avoid the deletion of data, which is the root cause behind these problems. Though, I don't know if that plays well with `@ExpectedData` tags. Second, we might have some brittleness with identifiers. For example, 'user_role' table IDs values would become 'magic' identifiers spread around, we could not add to that table as it has UK constraints.

I certainly am leaning towards (2). It isolates the sub-project/tests that need external applications to be running (DB on docker and app container), which should let us have all the other tests be run in parallel without any conflict (to be clear, two levels of potential parallelism, sub-projects in parallel, which is current problem, and second, future looking, running the unit tests themselves in parallel)

A benefit of going with (2) is we get some divide-and-conquer, we solve our parallel sub-project problem in the short term and can then look at ways to solve how to run those tests in parallel if ever possible (ie: additive data)

**Comment by DanVanAtta** [comment]
`integration-testing` as a new sub-project does put forward a good use-case for transitive dependencies. As-is, for such a sub-project we have to find and duplicate all dependency lines and add them to the new project. Any new dependencies used for any integration test will result in a cascading change to multiple sub-projects to add the dependency.

I was pretty neutral about transitive vs non-transitive dependencies before, I think this example is swaying me to favor transitive. At another level, with transitive dependencies we could cleanly see which sub-projects are adding new dependencies, which I think is another benefit.

From a practical perspective, it does look indeed that `compile` is deprecated, but still works. It looked like from StackOverflow the `api` keyword is to be used instead of 'implementation' for transitive dependencies, but that did not work. It looks like perhaps transitive dependencies are turned on by configuration flag. So it seems we'll either need to use `compile` and not worry about it until it is removed, or see if we can turn on that configuration flag (preferred).

Perhaps it's better to revisit/decide if we really want non-transitive dependencies.

**Comment by RoiEXLab** [comment]
@DanVanAtta 
The `api` keyword is only available using the [`java-library` plugin](https://docs.gradle.org/current/userguide/java_library_plugin.html).
We're using the "normal" `java` plugin as you can see in the upper lines of every buildscript.

**Comment by DanVanAtta** [comment]
Okay, that explains why it's not found. Do you know the preferred way to turn on transitive dependency resolution? More to the point, would you agree with such a move? 

Merging integ tests together has yielded a missing dependency: https://github.com/triplea-game/triplea/pull/5360

It's not efficient to figure out which one is missing and I'm concerned at the upkeep/redundancy.

**Comment by RoiEXLab** [comment]
> Do you know the preferred way to turn on transitive dependency resolution?

Not really, I the only common way I know is using java-library.

> More to the point, would you agree with such a move?

I don't have any strong feelings for one approach or another. In the end were not a library so it really doesn't matter what approach to use as long as it works and is convenient

**Comment by DanVanAtta** [comment]
Some oddness when running integration tests from a sub-project, launching the server is okay but when we get to the actual test it seems that logback is removed from the classpath. Trying to restore it via gradle dependency did not work. I don't know if transitive dependencies would have actually fixed that, I swapped all 'implementation' dependencies to 'compile' and it still did not change anything..

I think I'm probably still pro-transitive at this point for the simplicity, but it seems like we should pick carefully what should be transitive vs not, perhaps not worth the care/attention that it would need.

One oddity of using `java-library` for transitive dependencies for integration-testing would be marking `http-server` as a `java-library` so that its dependencies are transitive to the testing. `http-server` is an app, not a library, so that is weird..

Otherwise, PR#https://github.com/triplea-game/triplea/pull/5360 is up that essentially resolved this issue. After that update sub-projects can be run in parallel without issue and `./verify` script is deterministic again.

**Comment by DanVanAtta** [comment]
This is resolved with #5360 being merged.
