### ISSUE TITLE
Add Human Player Names

### ISSUE THREAD

**Issue by CoolNewfie** [triplea-game/triplea#5362]
For PBEM games with multiple players, it would be nice to set the player name so there is no confusion about who is playing what country.  I would set the name on the "Select Local Players and AI's" menu.

**Comment by Cernelius** [comment]
I don't think this matters only for PBEM. Whenever you take a save game, it would be nice if the names of the playing players are somehow recorded for the respective game players. For example, when you reload a multiplayer game you played live, but didn't finish, in the past, you would know and be sure about who is playing what player.

**Comment by Cernelius** [comment]
By the way, I would record all playing players, also the AI, so it would be known this game player was played by that AI player. Also knowing from what point to what point in history each game player was assigned to whatever playing player. When you play multi, and especially FFA, live, it is quite common that someone substitutes someone else at some point, and it would be nice being able to see the history of the assigned players for the players.

**Comment by DanVanAtta** [comment]
Moved to forums: https://forums.triplea-game.org/topic/1701/add-human-player-names

Feature request tracking policy: https://github.com/triplea-game/triplea/wiki/Bug-Report-And-Feature-Request-Tracking
