### ISSUE TITLE
Review Plan for Http Lobby

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5374]
It's getting to be a bit difficult to find good blocks to carve off from the next part of http lobby work.

We have:
- chat [complete]
- add 'system-id' to DB to replace hashed mac [complete]
- moderator controls for lobby (boot/ban) [complete minus some test coverage]

I've got two branches, one that I was hoping to have all of chat on it, by itself, and a second that has all of the above. Getting the chat branch to build by itself and keep things working is a bit artificial, not terribly trivial, but with some more effort I could get it to build. The branch is 3k lines added.

Second branch, has essentially all of the above, with tests for the most part and all building and the lobby fully functional and very few implementation placeholders. That branch is 6k lines added (was previously 8k lines, thank you @RoiEXLab  for the recent reviews getting it down to 6k lines). 

We are at a decent trade-off decision point, considering the chat-branch large is still pretty large, do we:
A) review the chat branch with a good number of implementation placeholders, some broken functionality, and then follow-up with system-id in Database and then all of the client side changes (as a series of 3 PRs)
or
B) review the 6k line branch that is more complete and more functional

In either case there will still be more iterations to fix up loose ends. Both are a bit too large to review, the 6k one is overwhelming and has multiple functionalities, it's hard to even self review it. On the other hand, our capacity is limited, the effort to get the 3k line review ready is non-trivial and perhaps could be better spent fixing up the 6k line review and doing the final iterations.

In any case, the implementation for moderator to automated-host controls still needs to be worked on, there is no shortage of things to do.

@ron-murhammer , @RoiEXLab , can you either of you assist in this review, and what are your thoguhts/preferences for how to proceed?

-----

for reference, this is the 3k line branch with chat only: https://github.com/triplea-game/triplea/compare/master...DanVanAtta:http-chat?expand=1

And this is the more complete branch with 6k that lands chat, moderator chat controls, and DB updates: https://github.com/triplea-game/triplea/compare/master...DanVanAtta:http-server?expand=1

**Comment by RoiEXLab** [comment]
I think having multiple smaller iterations is better. I personally think review time is at least in my case independent of the size of the pr. There are smaller PRs where I spent looking 10 minutes at the same class in order to understand the code in depth, whereas that obviously doesn't work for large PRs, where I try to finish the review in under an hour, because even though I have quite some free time recently I certainly don't want to spend it looking at code for 2 hours where I could do certainly more fun things in the meantime.

The only downside to multiple smaller iterations is that it's harder to get the big picture, but at the same time that's still hard for larger PRs because of the sheer amount of classes (I wonder if a class diagram would help reviewing?), so there might not even be that big of a difference in reality.

**Comment by DanVanAtta** [comment]
> I think having multiple smaller iterations is better. 

Agree, at least in genearl.

> I personally think review time is at least in my case independent of the size of the pr.

I wonder if this is because of diminishing returns. Some studies advise not reviewing more than 500 LOC, or for more than 30 minutes, essentially useful feedback falls off exponential. This is why I also think large reviews are 'cheating', nobody is reviewing such a diff in the same detail as a single class that is well focused. Hence, we skim instead of reviewing everything. It's perhaps another reason for singular focused and well scoped diffs.

> I certainly don't want to spend it looking at code for 2 hours where I could do certainly more fun things in the meantime.

Indeed, and we need to consider the trade-off cost of you not working on some other aspect of this project. I would say it takes me about 5x longer to write code than it is for you to review, and about 2 or 3 times long to break up a PR than it takes to review it. The last couple larger PRs both took 1 to 2 hours each to break up, verify things were still working, re-run all tests, fix any missing pieces, and very demoralizing to repeatedly test the same code (but having to do so because it's now broken up and slightly altered).


----------------------

I think we need to keep a few things in mind, and let's focus on this specific example and not generalities of review:
1) Only one reviewer for a project is a project anti-pattern. Would it be better to review post-merge and simply contribute any desired changes and/or comment on the merged branch where things are unclear? 
2) We need to keep in mind time. 6000 LOC, if at 500 LOC / day, we're talking 12 solid days. With 1 hour ideally per breakup, and 30 minutes for review, that is 12 hours just to break things up and 6 hours to review. Would we be better spending that time finishing the lobby migration and/or working on JavaFx? We also have a few bugs that need attention, the timing bug for retreat dialog is really scary and I don't have confidence it'll be found easily.
3) We do want to do other things than reviewing PRs and breaking up PRs. My last 6 out of 10 hours towards this project has just been in PR breakup.

I'm a at a bit of a stand-still for the next piece, all the code I'm submitting is anywhere from 10 days to 30 days old at this point. I've lost context and out of cadence from the ideal iteration cycle where each iteration could have been specifically. Notably, the iterations are now inter-dependent, reversing that is both difficult and painful as it is undoing work to then later redo the exact same work.

My best thought for going forward is to do very small PRs of independent class and keep iterating and building on that. It'll be context-less in the extreme and introduce a lot of unused code. Creating a more meaningful, larger PR will be a few thousand lines, lots of effort and some hours.. which is about where I am.

**Comment by DanVanAtta** [comment]
Are there any thoughts for us to know if we are making the right decision? Namely to review closely. CR is very valuable, please do not get me wrong on that, and I appreciate the feedback and see a ton of value in it. At the same time, how do we know when we are in a desperate enough of a place where even that ROI is not even worth it?

In other words, when would it be better to stop doing review (reviews are a blocking activity), have @RoiEXLab just focus on JavaFX?

Is there some alternative that we can explore, perhaps maybe if it continues to be @RoiEXLab only reviewing thousands of lines of code, that we do post-merge reviews and start commenting on merged PRs and marking places in code where we should revisit to fix technical debt?

I'm really concerned as well by the battle sequencing bug and that we have yet to even start addressing that; I really fear it's going to be weeks, perhaps months to get that fixed and might require rewriting `MustFightBattle` and the surrounding sequencing logic to get there. I hope the fix can be found and strategic, after some hours investigating it, I'm feeling very uneasy about our prospects on that one.

**Comment by DanVanAtta** [comment]
I'm inclined to say we continue trying to break up changes to small pieces for easier reviews and moving them forward. If we can identify any strategies to speed this up, that would be a win. Perhaps we can agree on a system to keep revisiting potential improvements while still moving forward. It might be on a case-by-case basis where we do that though.
