### ISSUE TITLE
Medium Luck

### ISSUE THREAD

**Issue by gamergray** [triplea-game/triplea#538]
Originally posted at source-forge.
redrum suggested I post it here.  I don't have the coding knowledge myself.

Even before we discovered TripleA and the rest of the online gaming community, my buddy and I had developed a system to reduce the odds of getting "diced".  It is similar to Low Luck.   

Instead of just totaling the attack factors and defense factors, we would group them by power, total the units, divide by six, assign the "auto hits" and then roll for the remaining units.  (total the 1's divide by 6, assign the hits, roll for each of the remaining 1's; total the 2's divide by 6 assign the hits, roll the remainder; total the 3's ... the 4's...) 

For example  Germ attacks with 18 inf, 4 art, 5 tank, 1 fighter, 1 tac bomb, 2 strt bomb 
14 inf @1, = 14@1 = 2(6)@1 + 2@1 = 2 hits plus roll two 1's 
4 inf and 4 art @2, = 8@2  = 1(6) @2 + 2@2 = 2 hits plus roll two 2's 
5 tanks and 1 fighter = 6@3 = 1(6) @3 = 3 hits and no rolls 
1 tac and 2 strt = 3@4 = roll three 4's 

We see this as an alternative to the predictability of low luck, and the other extreme of getting diced, especially when the stacks get big.  
Could the guru's here create and add this feature to the tripleA engine?

**Comment by DanVanAtta** [comment]
Interesting, so if I understand correctly, 5 infantry would throw 5 dice, but 6 would get an auto-kill?

**Comment by DanVanAtta** [comment]
5 infantry attack*

**Comment by gamergray** [comment]
Yes, exactly.
