### ISSUE TITLE
Rename @IntegrationTest to @EndToEndTest (?)

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5388]
Looking at coverage metrics, it's a bit misleading in some cases, there are some classes marked as not covered but are actually pretty well covered.

My understanding is that `@IntegrationTest` is used now only to exclude certain tests from coverage metrics.

I would suggest we rename this tag to `@EndToEndTest` to better capture its intent and when it should be added.

The terminology of integration and system test can be a bit fuzzy. Bet let's say we have a system with decomposed modules where database (DB), calls module A, calls module B, calls module C, ie: `DB -> A -> B -> C`. I'll assert that a good test strategy for this is to have contract and unit testing for every module and the test between `DB` and `A` would be an 'integration' or 'system' test and would use a real DB. This gives us coverage of `A` (and the other modules), but specifically the system test of  `A` could be the DB rider tests testing a JDBI DAO classes. Since there is no implementation, there is literally nothing to unit test there, so even with a DbRider test, testing these classes, they are omitted from coverage.

On the other hand, we do still want some tests that will send a representative sample set of requests from `C` down to `DB` and back, and verify there are no errors. To avoid testing all permutations of test cases and call flows, this test will only validate we get a valid looking answer back, but will not test logic and will do very sparse error condition checking, leaving the heavy logic and error condition checking to the previous unit tests.

I'll suggest that it is this latter kind of test, that sends sample requests, 'end-to-end' that we want to exclude from coverage metrics, as we are mostly just verifying that the system is well connected and well configured. To avoid confusion with the 'boundary' type of test, that is often called a 'system' or 'integration' test, to avoid that confusion I'll suggest we rename `@Integration` test to `@EndToEndTest` and remove most of those tags except for the places where we have an end-to-end test.

For consideration, the places where we have an integration test in-place of a a series of unit tests, we may wish to continue using this tag so we can see the lack of true code coverage. In these cases, where we would want to restructure our testing, we might perhaps want to use a second tag to better identify these tests, but also still exclude them from coverage.

Curious if there any thoughts/objections to these ideas.

**Comment by RoiEXLab** [comment]
I'm pretty neutral on this, but I think if this annotation is renamed (as well as the underlying tag) all of the existing "integration tests" should be re-evaluated to check if they actually belong ito the E2E category.
My only concern is that way too few tests will actually fall into this category.
Also it might make sense to still keep an integration tag around, in case we want to separate independent unit tests from tests that require an external db or something.
This might be useful in case we ever want to try giving parallel unit tests a shot, which likely won't work with tests having external dependencies.

**Comment by ron-murhammer** [comment]
Neutral as well.

**Comment by DanVanAtta** [comment]
Let me reframe/emphasize the problem:
1. Our coverage reports are not useful when answering the question of "which DAO classes are tested?" The picture they give is misleading.
2. `@Integration` could be a misleading name, particularly when not all tests in `integration-testing` would have it.

> My only concern is that way too few tests will actually fall into this category.

Why is this a concern? All of the 'http controller' classes will fall under this category, the `ChatIntegration` test for chat messengers falls under this category as well.

> Also it might make sense to still keep an integration tag around, in case we want to separate independent unit tests from tests that require an external db or something.

I think that is already achieved with the `integration-testing` project, any test in that sub-project requires DB.

> This might be useful in case we ever want to try giving parallel unit tests a shot, which likely won't work with tests having external dependencies.

It's only a problem for DB, that is only because we delete data. AFAIK we could turn on parallel tests for all the other sub-projects.

**Comment by DanVanAtta** [comment]
@ron-murhammer @RoiEXLab ; do you have any other ideas/suggestions how to solve the problems noted above, or would strategic removal of `@Integration` be reasonable? Any thoughts on naming to avoid the annotation from being misleading, or any other kind of strategy that we could employ?

**Comment by RoiEXLab** [comment]
> Why is this a concern? All of the 'http controller' classes will fall under this category, the ChatIntegration test for chat messengers falls under this category as well.

It's a subjective separation, in my head I have another definition of E2E. Using your definition it sounds far more reasonable.

> Any thoughts on naming to avoid the annotation from being misleading

Names are just names, I think you were the person to actually introduce the term "integration" for those kind of tests, so changing it would be no big deal IMO, as long as we do it consistent and can agree on a name.

**Comment by DanVanAtta** [comment]
I was curious on that history, to nitpick, I was not actually involved in creating the `@Integration` annotation, but I certainly supported it and may have suggested the idea (which maybe is where the name was seeded from):
https://github.com/triplea-game/triplea/pull/3321/files#diff-df74f54255947de6bf342beea3ad0625

We're certainly dealing with slightly fuzzy terms, it's up to us to give them meaning but also not try and conflict with well used terms. It sounds like there is at least no objection to removing `@Integration` tests for the "edge tests" that are for example verifying DAO objects. 

Maybe we can instead be more direct and rename the tag to `@ExcludeFromTestCoverage`.

**Comment by RoiEXLab** [comment]
I'd be fine with the latter suggestion

**Comment by ron-murhammer** [comment]
I'm fine with that as well.
