### ISSUE TITLE
Designing Automatic Deployments

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5398]
Opening an issue to get feedback on potential design decisions for deployments. A number of options are now available with travis pipeline, notably now we can execute steps post-deployment of artifacts to github release, which means they can be downloaded and used as further steps in our automation.

### Unify secrets between prerelease and prod

Thinking to keep all passwords/secrets to be the same between prerelease and production. This adds a level of simplicity so we don't have to encrypt two versions of passwords and keep track of them. Thinking that the security bar between prerelease and prod will not be that different, if one password, like the DB password, or the server root password can be compromised on one, it likely can be cracked on the other too.

### Do preelease and production deployments on every build

After the deployment of artifacts to github thinking there will then be the prerelease deployment step. It will deploy the latest binary and configuration. This will be done from travis.  Once the prerelease deployment is done, the production deployment will kick off. 

### Production Deployment and avoiding deploying non-backward compatible changes

The version of production that will be deployed will be controlled by a variable value defined in ansible. We will also have a second variable 'pre_release_only' that will be set to 'true' when we do pre-release deployments. Ansible tasks that are not compatible with the last version of production will have a `when: pre_release_only` attached to them so that they are selectively run only in pre-release. This way we can still do things like add a new bot server to production, or update configuration while keeping the deployed binaries the same.

### Users (admin) will continue to have public keys deployed

So essentially only ansible will use root+password, admin users will have their public keys automatically deployed for passwordless-ssh

### Use ansible-vault to encrypt most secrets

Ansible-vault is a CLI tool to do encryption, essentially we'll use a travis environment variable to store the vault password, we'll store that value in a file that is then passed to ansible where it can then decrypt vault encrypted values. This will let us check in encrypted values for the DB password and the password for server

### Use root and SSH passwords for ansible deployment

This is one that I've been pondering the most. I think ideally we would use SSH certs for everything. Previously I was thinking we would have a one-time setup process for new servers to create an ansible user, deploy a cert, and update the hostname. If we use root and a ssh password, then we can have ansible configure the host in its entirety. Given that public cracking attempts will be locked out after 3 tries, and  a sufficiently long password, this should be secure enough. The benefit of full configuration from deployment script without any manual setup is very nice. We would be able to deploy a new bot by launching the linode server and then checking in a new line to an inventory configuration file

**Comment by prastle** [comment]
Makes sense to me. @DanVanAtta

**Comment by RoiEXLab** [comment]
Sounds good to me as well, the only potential problem I see here is deciding if the change is incompatible.
Particularly, how would I, in a PR indicate incompatible changes?

**Comment by DanVanAtta** [comment]
### Update on SSH Keys Vs Password

An update to using root+password, turns out linode by default now have password SSH turned off. They also have a UI where you can add a SSH key to your account, and when creating a linode you can select that key to be added to the root user. 

It looks like we can use ansible-vault to check in an encrypted private key file and then decrypt that file when running deployment. We're still using root user, but we would then be using SSH keys and not passwords, and secondly, there is still no configuration needed on the new or existing linode before we can run the deployment automation.

### Flagging incompatible changes

To your question @RoiEXLab , non-compatible scripting would be omitted through a conditional variable. So in essence, you would start out with a block like this:
```
- name: a task that is run in prod
  some_command: some ansible command
```
Then say we need to change that so we use maybe a new folder, we download a new file, something that would not work in current production, the update would look like this:

```
- name: a task that is run in prod
  some_command: some ansible command
  when: !pre_release_only

- name: this task is not run in prod
  some_command: some other command
  when: pre_release_only
```

Notice the two mutually exclusive 'when' blocks above. If an updated/new command would have no impact on production, then we can run the command even if the resulting updates are not yet used. I'll note there is still a vagrant local configuration, so we can test out deployments to a local VM before having to run them in prerelease or prod.

**Comment by prastle** [comment]
The UI also worked in the past for adding a root as I recall.  JYI @DanVanAtta
