### ISSUE TITLE
Retreat Prompt Appears too Early / Swing UI Appears Deadlocked

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5399]
**Describe the bug**
- https://forums.triplea-game.org/topic/1609/triplea-2-0-16244-issues-with-an-unreleased-game/4
- https://github.com/triplea-game/triplea/issues/5010

On battle start, get a retreat prompt and error message prompt: 
`GRAVE: battle not displayed, looking for:cdf141ff-876c-4160-96b7-b8b8bda93bec showing:null`

The two windows compete for focus and neither allow focus, cannot be closed. UI appears deadlocked. 

Another variant is the battle window itself is rendered along with an immediate prompt such as 'retreat subs', or 'retreat'. The two windows again compete for focus and neither can receive focus.

**To Reproduce**
Unknown, happens at battle start

**Expected behavior**
Neither dialog should appear

**Impact**
Neither window can gain focused and neither can be closed. (to-be-confirmed, a workaround may be to close one window with the 'X' icon; if this does not work then the game is un-recoverably frozen).

**Screenshots**

**Zipped Save Game**

**Additional context**

**Comment by DanVanAtta** [comment]
@ron-murhammer @RoiEXLab @asvitkine @ssoloff this is an all-hands-on-deck situation for this bug; any/all assistance is welcome and needed. Please add any technical details to this issue as we try and narrow down where the bug could exist.

This one is very concerning, I would guess this easily could be a 20 to 40 hour bug to solve, if a person can do 5 hours / week, we're getting into a months level time-frame before seeing resolution.

**Comment by ron-murhammer** [comment]
@DanVanAtta Do you know the best way to at least have this occur or how frequently it occurs? Wondering if running all AI on certain maps would cause it to happen? Or is it only when human players are involved?

**Comment by RogerCooper** [comment]
This may be related to bug I have experienced many times recently, where the battle window can't be closed even though all units on one side are destroyed. When that happens, I can try to quit the game, move the windows and reveal the save option.

**Comment by DanVanAtta** [comment]
I linked: https://github.com/triplea-game/triplea/issues/5010 to this issue, let's keep this issue as the primary discussion thread until we find out that the problems are not related. There are a few variants to the problem, exactly with which dialog appears first, essentially something in the sequencing is wrong where the battle proceeds to far and then we have dueling windows that deadlock each other.

This WWII revised save sometimes reproduced relatively consistently: https://github.com/triplea-game/triplea/files/3528473/combat.zip
The exact frequency is hard to say, or what conditions are needed to trigger the problem.

Running AI is a good way to test a lot of behavior, there are is a UI freeze behavior with AI choosing the wrong battle that causes a freeze that might get in the way of reproducing this problem: https://github.com/triplea-game/triplea/issues/5216. I also wonder as well if the AI is given a different retreat or submerge prompt, which skips the swing rendering and then avoids the scenario. Overall it does not hurt IMO as it exercises lots of code and worst case we'll detect other problems in need of a fix.

I previously had gone through the merge history of the last year looking for 'acquireRead' or 'acquireWrite' lock thinking that perhaps we had removed an important one around game data. I found there was a removal around screenshot exporter, which does not seem related, otherwise did not turn anything up in that search. There were updates to submarine submerge, but those looked pretty kosher. Overall it seemed like bisecting the problem from the history will not be a good approach because we do not yet know how to deterministically trigger the issue.

Overall I'm thinking the surface area of this problem is too large and can suggest we try to do 3 things:
1) continue seeing if we can reproduce the problem in a known way
2) isolate the locations in code that could cause such an issue (then we can review history and/or see if we can spot the issue relative to other changes that we have made)
3) see if we can artificially create the problem by injecting code that we suspect would trigger the issue

**Comment by asvitkine** [comment]
If we can trigger the issue, perhaps we can connect with jvisualvm and see
where the threads are stuck?

**Comment by DanVanAtta** [comment]
Running the game from IDEA, thread dumps are possible. #5010 actually has a few of these. I don't know though if we have a trace to one of the threads that are causing the lock, or if we are just seeing locked threads. It would be great to get a stack trace from the scenario highlighted in [forums#1609](https://forums.triplea-game.org/topic/1609/triplea-2-0-16244-issues-with-an-unreleased-game/4) to see how similar the stack traces are.

**Comment by DanVanAtta** [comment]
Let's go ahead and consolidate this bug into #5010, closing this issue in favor of #5010.
