### ISSUE TITLE
Name Change Proposal 'PlayerId' -> 'GamePlayer' and 'PlayerName' to 'Username'

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5427]
Before executing on these, curious for feedback:
1. Rename 'PlayerName' -> 'Username'
This matches the DB terminology and helps disambiguate a player name for the other variants of players. So for example, a ChatParticipant would have a 'username' instead of a 'playername'. If on the other hand we wish to stick with 'PlayerName', then it would make sense to phase out 'username'. In part, do we want to prompt users for their "username" when they log in, or do we want to prompt them for their "player name"? I think when it comes to UI and domain teriminology, the latter could actually make more sense (username is a pretty nerdy and internal term, player name almost makes more sense to people. When looking at chatter names in lobby, in common parlance one would more likely call those player names and not username)

2. Rename 'PlayerId' to 'GamePlayer'

`PlayerId` has always grated on me as a name, as it would more imply an identifier than an actual data object or an entity with properties. The naming suggestion is for two reasons, one, to better match domain terminology, we could elect to call this a `Faction` or a `GameFaction` (at least for internal naming). The `GamePlayer` choice is not unreasonable and the [javadoc](https://github.com/triplea-game/triplea/blob/master/game-core/src/main/java/games/strategy/engine/data/PlayerId.java#L19)  inspires that consideration:

```
/** A game player (nation, power, etc.). */
```

**Comment by prastle** [comment]
Makes sense to me.

**Comment by RoiEXLab** [comment]
Pretty neutral on this one.
As @prastle already mentioned, your reasoning seems reasonable, so no reason from my side to not go for it.

**Comment by DanVanAtta** [comment]
I'm actually a bit on the fence for first one, bit tempted to rename `username` -> `player_name` in DB. It's an open question for:
1. `username` -> `player_name`
or 
2. `playerName` -> `username`

**Comment by Cernelius** [comment]
If that applies to guests too, definitely "username". Otherwise, I would call them "assignees" (with the meaning of a user that is assigned to manage one or more game players).

**Comment by DanVanAtta** [comment]
To be sure we're on the same page - how do you mean by 'guests'  @Cernelius ?

**Comment by Cernelius** [comment]
I don't actually have a clear idea of what a guest is, but, anyways, I would not call it a player.
In my opinion a guest is anyone connected to a host (thus except the user that is hosting, unless it also joins its own host), no matter if currently assigned to any game players (in this case, everyone would be a guest, if the host is automated (bot)).

So, I would say guest= hosted user =all users in the host minus the hosting user= all users in a automated host (bot).

I think I should have said "applies to any guests as well, no matter if assigned to any game players", instead of "applies to guests too".

**Comment by DanVanAtta** [comment]
Thanks for the clarification. To step back a moment, the goal is to align the terms used in the code with the terms that actual game players use in day-to-day. To that 'extent', I suspect the concept of a "player" wins over the concept of a "user". The latter is techy back-end jargon, the former is what people actually say, eg: "A player joined", "a player was booted", "a player left"

That is more or less my 2 cents, I'm open to compelling examples where 'username' is a more well understood term used by the community, but again I think that is more than likely a term dev's came up with a long time ago independent of what people would naturally call it.

**Comment by Cernelius** [comment]
I'm fairly certain nobody would say "a player joined" if they are in a game in progress and another user joined it.

**Comment by DanVanAtta** [comment]
"an observer joined"
"a player joined as an observer"

Perhaps we'll just disagree, I don't think anyone except us, the devs & moderators use the term 'user'. We only use that to clarify what we are talking about because we never defined the terminology very well and made up our terminology that players do not actually use. That again is the problem, the terminology we use is not aligned with the average user.
