### ISSUE TITLE
Map Version Number Simplification

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#546]
I suggest we simplify map versions and get the map version from the travis build number. Practically speaking that means the game engine we will be getting the version number from the download URL.
- this simplifies things quite a bit (hopefully not overly so)
- the major version number of a map can be changed, but it does not seem to have much point in doing so.
- for sake of map comparison, we use the URL pretty much exclusively, and when a new map version is updated, we updated the URL. The update to the version number is redundant since the version will always be baked into the URL.

**Comment by ron-murhammer** [comment]
@DanVanAtta Seems like a good idea. Might be worth trying to implement this now with the map roll out.

**Comment by DanVanAtta** [comment]
Closing, bit stale. I would like for us to rethink map versioning, perhaps with a single config file per map that has it. When we revisit this topic we can think a-fresh how we want to do it.
