### ISSUE TITLE
Things we have to do before 1.9

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#547]
- [x] figure out how we'll hook up the tutorial map, and do so
- [x] determine which maps will be included, update build to make that so.
- [x] [release blockers](https://github.com/triplea-game/triplea/issues?q=is%3Aissue+is%3Aopen+label%3A%22Release+Blocker%22)

Anything else to add to this list?

**Comment by ron-murhammer** [comment]
@DanVanAtta I went through and marked what I think the issues we should address before the next release: https://github.com/triplea-game/triplea/issues?q=is%3Aopen+is%3Aissue+label%3A%22Release+Blocker%22
