### ISSUE TITLE
Rename "Export Map Screenshot" (2.0.16492)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#5483]
I suggest renaming "Export Map Screenshot" to:

**Take Game Picture**

or

**Take Gameboard Picture**

Reasons:

- "Take" is better than "Export", as it is something visual that you are prompting to save, differently from the other options, that are all game data.
- "Gameboard" is better than "Map", as map, right or wrong, is a term used in TripleA to refer specifically to a scenario featuring a default skin with all its games (1 or more) (for example, "world_war_ii_classic" is a map, offering two games). What units are present on the "board", as well as the ownership colours, etc., is defined at a game, not at a map, level.
- "Picture" is better than "Screenshot", as screenshot literally means the image you have on the screen (usually not all the "gameboard", and always also other things).

To sum it up, what "Export Map Screenshot" is saying is that I'm somehow exporting what of the map I have on the screen, that is definitely not what this function is doing, and that, knowing TripleA terminology, makes me even think I'm exporting just the picture of map itself only, regardless of the current state of the game I'm playing.

Also "Take Game" or "Take Gameboard" would be in line with saying "Save Game", that is a strongly related function, in which I export the current state of the whole game for the map (saving the game, not the map, that I will still need, in order to reload the save later).

If not accepting this suggestion of mine, I still strongly believe you should at least change the word "Screenshot" to something correctly descriptive, as it is literally referring only to what you have on the screen at the moment (either all you have on the screen or the portion of the gameboard you are visualizing).

**Comment by Cernelius** [comment]
And it is also confusing since, playing TripleA, you may be taking actual "screenshots", maybe for bug reporting or moderation complaints. So, for example, if you ask people to do that, maybe they'll click on this function, instead.

**Comment by DanVanAtta** [comment]
The option being in the 'export' menu would be odd to be named "save..." and would not fit with the other options.

Per the suggestion "Take Gameboard Picture", a rename to: "Export Gameboard Picture" at least improves this some.

**Comment by Cernelius** [comment]
"Export" is good for me.

What I was mostly pointing out is that the Export section offers mostly Game items to export, while the Export Gameboard Picture is the only view item, with maybe the exception of Export Unit Charts, that anyways fails to export the units images (so it is purely a game exporter, as well, unless the map, or the mapskin, has a tooltips.properties file in it, which most don't, and that I personally believe it is out of place in the mapskin, as it should be game, rather than map, related).

Don't you think it is inconsistent or strange to have a "Game" and "View" menu, then having an "Export" menu that mixes "Game" and "View" items, to export, together? I was trying to differentiate them, by calling with "Export" the things that are purely game related (thus, for example, don't change if you change the mapskin you are looking at, during the course of the game) and the things that are view related (thus, for example, depend on what mapskin you are looking at, at the moment).

Also I'm actually not sure if it would be better calling it "Gameboard" or "Mapboard"? I went with "Gameboard", because I believe it is more common a term, in general boardgaming. Opinions on this?

**Comment by Cernelius** [comment]
One reason I wonder if "Mapboard" may be better than "Gameboard" is that, in the board games, you also have the "Battleboard", that is part of the "game", but not of the "map". @panther2 Any opinions on this, especially on mapboard vs gameboard vs battleboard?

**Comment by Cernelius** [comment]
Of course, when you play a boardgame, the map is a constituent part of the game, you are playing (together with the unit pieces, possibly other boards, possibly the paper money, etc.), while in TripleA the game is a subset of the map, the remaining part being the (original) mapskin, which in turn is, on the other hand, consistent with the fact that, in boardgaming, you can use a same map to play different scenarios (for example, Revised having an OOB and LHTR version or Anniversary having a 1941 and 1942 scenarios, that are different not only in starting setup, but also in turns order), and you could see those scenarios as different games, using a same map.

**Comment by panther2** [comment]
@Cernelius I think I tend to "gameboard", as we are playing a boardgame (digitally) and are taking a screenshot of the current status of the gameboard. I don't think it will be confused with the battleboard.

**Comment by Cernelius** [comment]
Allright. I tend to prefer gameboard too, mainly because mapboard would make me think that we are taking a picture of the map only, without the units in it.

Otherwise, I would call it "Export Mapboard Picture With Units", but that would have the problem that it seems saying that you are getting the units also if the View/Show Units is disabled, and maybe also the units that are made invisible by map.properties. So it would need to be "Export Mapboard Picture With Visible Units", that is probably too long.

Side note, I think that if you say "Export Gameboard Screeshot" you mean that you are exporting only the part of the gameboard you currently have on the screen, thus why I suggested changing "Screenshot" too.

Anyways, I confirm that "Export Gameboard Picture" is good with me.

Side note, I recall that, in the past, it was decided to change screenshot to snapshot. Not sure why screenshot has got back, thereafter, but, anyways, I don't really like either.

**Comment by Cernelius** [comment]
When you export, the programs says "Map Snapshot Saved", both in the title and in the description.

That should be harmonized.

Also I suggest avoiding the redundancy of having the same thing written both in the title and the description.

And I advise running a search of all TripleA, if any words like "screenshot" and "snapshot" are still somewhere, see if they should be changed too.

**Comment by DanVanAtta** [comment]
Follow up renaming was completed in #6031
