### ISSUE TITLE
Versioning Scheme (for use in Chocolatey community package)

### ISSUE THREAD

**Issue by MillironX** [triplea-game/triplea#5484]
I have written a [Chocolatey package for TripleA](https://github.com/MillironX/chocolatey-packages) that I would like to push to the [Chocolatey community package feed](https://chocolatey.org/packages). However, the Chocolatey mods are afraid of version incompatibilities that would arise from fitting TripleA's five-part version number into Chocolatey's four-part version number ([and rightfully so](https://chocolatey.org/docs/createpackages#versioning-recommendations)).

**Is there a recommended scheme for dealing with situations like this?** I know that @DanVanAtta mentioned that "updated version semantics" will be implemented soon in #5025, but I couldn't find any other references to how version numbers are decided currently or will be in the future (sorry if I just don't know where to look).

**Comment by DanVanAtta** [comment]
@MillironX thanks for the work. Good news, we've adopted a 3 point version number. Last discussed/decided in: https://github.com/triplea-game/triplea/issues/4875, it has been implemented, please note the version number on the release packages: https://github.com/triplea-game/triplea/releases

In short, the version semantic is:
`<compatible>.<release_number>.<build_number>`

Hence, on release that are not backward compatible, we'll increment the first number, on significant updates/releases, we'll update the second number, and the build number is auto-incrementing.

**Comment by MillironX** [comment]
Thanks for that clarification, @DanVanAtta. The Chocolately package has now been approved: 
https://chocolatey.org/packages/triplea/.
