### ISSUE TITLE
Proposal for Various Coding Conventions

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5489]
List of conventions that have come up in various PRs, hoping to discuss here and document so that we may make the call-outs and refer to the convention.

### A) Avoid mutability

We have two conventions set towards this:
1. use final where we can
2. favor immutability

The 'use final' where we can AFAIK is to encourage immutability. But, to another extent, if all we are saying is "use the eclipse setting to auto-apply final", it seems meaningless. We can write the following:
```
int value = 2;
if(condition) {
  value = 3;
}
```

That can be re-written to be immutable:
```
final int value = condition ? 3 : 2;
```

On the other hand, if we write:
```
int value = condition ? 3 : 2;
```

The above is flagged in review, but the first example would not be. It seems we might be missing the point.

I'd suggest we make our convention to be to "really" favor immutability and to take a second look at any mutable data in review and see if we can transform mutable data to be immutable, ie: "avoid mutable data". Either that, or perhaps we should drop the "apply final everywhere" since it's kinda meaningless.

### B) Favor `Collections.emptyList()` over `List.of`

`List.of()` is shorter than `Collections.emptyList()`, but it also seems more indirect as it's the same as `List.of(String[0])`, essentially an unused argument. It strikes me as the same as something like `size() == 0` vs `isEmpty()`, the latter is more direct to intent/meaning.

### C) Import inner classes

Instead of:
```
someClass.innerClass.methodCall();
```

Favor:

```
import someClass.innerClass;

innerClass.methodCall();
```

### D) Testing, favor using helper functions  for "given, when, then" like structures to tests

IE: we want to try and have tests that are as much as possible like:
```
void test() {
  givenConditionsReturningValue("value");
  String result = someObject.doSomething();
  assertThat(result, is("value"));
}
```

Essentially this is saying we should favor relatively short tests.

### E) Use `@DislayName` on tests

To help document what is being tested, use `@DisplayName`

```

@Test
@DisplayName("verify error handling for IOExceptions")
void errroHandling() {
   when(...).doThrow(new IOException());
   // test ...
}
```

### F) Use Hamcrest `assertThat`

Instead of
```
assertEquals(expected, actual)
```
Favor:
```
assertThat(actual, is(expected));

// or

assertThat(actual, equals(expected));
```

### G.1) Favor `Optional.ofNullable`

Instead of:
```
if(someObject != null) {
   someObject.methodCall();
}

// favor

Optional.ofNullable(someObject).ifPresent(someObject::methodCall);
```

If there is a large block of code, then extract the logic, eg:

Instead of
```
  if( someObject != null) {
     // more than 5  lines
  } else {
    // more code
  }
```
Favor:
```

Optional.ofNullable(someObject).ifPresentOrElse(this::nonNullBehavior, () -> nullBehavior());

private void nonNullBehavior(SomeObject someObject) {
   // more than 5 lines
}

private void nullBehavior() {
  // more code
}
```

### G.2)  Refer to objects by their interfaces

Effective Java Item 52: http://thefinestartist.com/effective-java/52

### H.1) Do not mutate parameters, avoid "out" and "in/out" parameters

From Clean Code:

>     Arguments are most naturally interpreted as inputs to a function.

>   Anything that forces you to check the function signature is equivalent to a double-take. It’s a cognitive break and should be avoided. In the days before object oriented programming it was sometimes necessary to have output arguments. However, much of the need for output arguments disappears in OO languages

(referenced in: https://softwareengineering.stackexchange.com/questions/245767/is-modifying-an-incoming-parameter-an-antipattern)

### H.2) Avoid boolean parameters on public methods

Avoid:

```
public int doComputation(boolean isAttack);
```

Favor:
```
public int doAttackComputation();
public int doRetreatComputatoin(); // gotchya! // isAttack == false could mean anything, here it means 'retreat'
```

or favor using an enum:
```
public int doComputation(CombatMode.ATTACK);
public int doComputation(CombatMode.RETREAT);
```

Instead prefer to have two different APIs

### I) Use most restrictive scope possible

Use the most restrictive modifier available that still allows the code to compile, ie (in this order):
- private
- package-default
- protected
- public

### J) Mark values as static where possible

This helps mostly for reading comprehension and to highlight static dependency anti-pattern, eg:

Instead of:

```
private void thisDoesNotUseClassState(NoCompilerGuarantee arg) { }
```

Prefer:
```
private static void thisDoesNotUseClassState(GuaranteedByTheCompiler arg) {}
```

### K) Avoid 'static coupling'

Instead of:
```
public constructor() {
  myVar = StaticCall.compute();
}
```

Prefer:
```
public constructor(Supplier<Integer> compute) {
  myVar = compute.get();
}
```

The idea is to avoid using static dependencies. A common way to avoid static dependencies is to use interfaces. 

### M) Avoid boolean property values

Instead of:
```
visible: true
visible: false
```

Favor:
```
visibility: visible
visibility: hidden
```

Instead of:
```
isAttack: false
```

Favor:
```
combat: attack
```

**Comment by RoiEXLab** [comment]
@DanVanAtta I agree on most of the items, but I think there are some cases for H where this doesn't apply. When the method name includes the boolean state that is being modified like in a setter, then it would really make things complicated if an enum would be created, so that the user of the api might need to convert an existing boolean to an enum which is then converted back. A similar thing will be the case when generics are involved (see the ClientSetting framework), I mean obviously there are some yes or no settings which are internally represented as a boolean where using enums or different methods would just make thing unecessarily complicated, so I think that should be clarified.

Also I'm not sure what exactly you mean with M). Are you talking about property/config files? The syntax looks like yaml. That should be clarified as well

**Comment by ron-murhammer** [comment]
Uh the other one that came up recently that should be discussed is the usage of `var`.

**Comment by DanVanAtta** [comment]
Another one to suggest:

### N) Use 'assertThat' string parameter to describe why we assert a condition

Instead of:

```
assertThat(collection, hasSize(2));
```

Prefer:
```
assertThat("3 units added, one unit filtered, we expect to have 2", collection, hasSize(2));
```

**Comment by DanVanAtta** [comment]
@RoiEXLab  Boolean settings are perhaps an exception, but we can still avoid them sometimes:
eg: `setVisible()` and `setHidden()` vs `setVisbile(true)` and `setVisible(false)`. It's perhaps a biggest issue when there are multiple parameters and when we should be most concerned.

Conventions are not always going to be 100%, there will be times to strategically violate them.

For (M), XML or YAML, does not matter too much. I was doing some usability reading and it went into this topic I tended to agree. The `isVisible = false` example is more to keep track of for a reader, you have to invert the condition and correlate back to the property key. It is not always obvious or the case what the inverse will be.

@ron-murhammer I'm not sure what the `var` convention should be exactly. AFAIK, the java community convention is to use it in places where the variable name matches the type name, so instead of:
```
Image image = new Image();
```
Prefer:
```
var image = new Image();
```

If typing is particularly not clear, it's better to keep the type information. The above example is perhaps the most clear-cut, I think there is still a lot of judgement involved when it's good vs bad.

**Comment by ron-murhammer** [comment]
@DanVanAtta Yeah, I think just adding some guidance like that around `var` would be good. Just don't want it to be abused to make things "shorter" everywhere but make it very hard to read and bug prone.

**Comment by DanVanAtta** [comment]
Any further comment before these couple dozen conventions become official?

**Comment by RoiEXLab** [comment]
Not from my side

**Comment by ron-murhammer** [comment]
Agree with most. Here are the ones I'm a little torn on:

B - Could go either way on this one. I just prefer a standard and ideally do a mass update so we don't have a crazy mix of them.

G1 - I'm against this mostly because of readability and what most developers/projects currently use. It stills feels wrong to me to create an optional and immediately check it. It also seems to 'hide' the null check vs "x != null" is very explicit and easy to see.

K - So generally, I agree with preferring passing objects to calling lots of static methods to allow for more decoupling and easier unit testing but I wouldn't go as far as passing suppliers everywhere. I think it depends on the functionality/method and how related it is to the method that's using it. I think this can also quickly lead to having methods with lots of additional parameters. IMO, this can be a case of over-engineering if you'd apply this across a project as a standard.

**Comment by DanVanAtta** [comment]
Thanks for the reply.

For B, agree we need a standard. Most code is not written for when the `List.of()` and `Map.of()` API even existed, so those usages are in the minority. My impression is `List.of()` is an updated version of `Arrays.asList()` that is consistent to other collection types and has better naming. I wouldn't want to see the old `Arrays.asList()` used for an empty list necessarily for the same reasons I stated in the blurb of B.

@asvitkine you have favored using `List.of()` instead of `Collections.emptyList()`. Do you have a strong preference or any other reasoning one way or another you could share?


G1. I sympathize with the readability concern and the concern over hiding. I think that concern comes down what a person is completely used to. It's like learning how to multiply, at first it requires thought, eventually it becomes hard wired and your brain sees the pattern and knows the answer without thought. I'd suggest the same is for `if(x != null)` as `Optional.ofNullable(x)`, they're both just null checks. Because they're both just null checks, I don't have any problem seeing the "optional" be unwrapped, it's not necessarily just a wrapping type, and used as just a wrapping type IMO is an anti-pattern. My personal thought is optional values, as a type, should be as short lived as possible. IE: if you get a return value of an optional, you should unwrap it right away. If using an optional as a local variable, it should be used with it's full API.

For me the more compelling reason is to use the Optional API is that it can be chained in a very clean way to have further computation. I also think the method reference variant is quite clean. If we favor the 'old-school' if check, then having both an if check and a chained Optional variant potentially side-by-side is going to seem inconsistent. 

> most developers/projects currently use

I'm somewhat suspicious of that reasoning as most professional shops do not have the incentive to update their technology stack.


Re: K: the topic of supplier is a bit of tangent. The point is a common way to break static coupling is to use interfaces. We do need to design API's well, too much injection, too many args, supplier's everywhere are all smells.


W.r.t supplier, I think effective Java 3 comes into play on this one: https://kea.nu/files/textbooks/new/Effective%20Java%20%282017%2C%20Addison-Wesley%29.pdf

> Page 199: ITEM 44: FAVOR THE USE OF STANDARD FUNCTIONAL INTERFACES199Item 44:  Favor the use of standard functional interfaces


> If one of the standard functional interfaces does the job, you should generally use  it  in  preference  to  a  purpose-built  functional  interface.  This  will  make your API easier to learn, by reducing its conceptual surface are

> Now you know that you should typically use standard functional interfaces in preference to writing your own. But when should you write your own? Of course you need to write your own if none of the standard ones does what you need, forexample if you require a predicate that takes three parameters, or one that throws a checked  exception.  But  there  are  times  you  should  write  your  own  functional interface even when one of the standard ones is structurally identical. 


> You should seriously consider writing a purpose-built functional interface inpreference  to  using  a  standard  one  if  you  need  a  functional  interface  that  sharesone or more of the following characteristics with Comparator:•  It will be commonly used and could benefit from a descriptive name.•  It has a strong contract associated with it.•  It would benefit from custom default methods.

**Comment by DanVanAtta** [comment]
I suggest this, let's decide which of these we are not sure about. The rest we'll adopt. I'll then copy/paste the controversial conventions into their own issues. We can then all weigh in and then perhaps take a vote if we don't align.

**Comment by asvitkine** [comment]
+1 for reaching agreement on a subset and landing those and then opening a new discussion on the remaining ones.

From your list here are the ones I'm not yet convinced of (that I'd like to discuss more):
B, D, E, F, G.1

I think we could also discuss G.2 more - per our conversation on my recent PR - but I also think G.2 is generally adopted by the project already and the controversial part would debating if in some cases we *shouldn't* follow it, so it seems fine to land the guidance in meantime.

For the other ones:

B:
I prefer List.of() over Collections.emptyList() for the reasons I mentioned on the other PR. In particular, one less API to remember and more concise (so less wrapping and messy code).

D:
First, this should be ordered after F, since F is discussing the test constructs that this example is using.

Otherwise, I'd like to understand more concretely about exactly how this would apply to the types of tests we have. For example, in MoveBatcher tests, we perform a sequence of operations on a MoveBatcher object then check the results of batching. How does a givenFoo() function apply there? Is it just the suggestion of moving the set up code to a helper function? Does that actually improve something - it seems it just makes it harder to understand what the test is doing...

E:
I think we should flesh this out more. For example, currently many of our tests start with the word "test", but the example you have doesn't. Let's make a stance on that as well.

F:
I'm not convinced that we should never use assertEquals(). It seems for simple cases, it's still much more concise than the alternative.

G.1:
I find the simple control flow in the first example much more readable than the suggested alternative.

**Comment by DanVanAtta** [comment]
@asvitkine thanks for weighing in, some quick responses in case we can put a cap on some of these:

### D
Helper functions can increase test readability by labeling the setup that is happening. This avoids the reverse-engineering you need to do when you see a sequence of statements and need to figure out what is being done. The label also helps convey intent more directly. 

This post goes into the concept in more detail: https://phauer.com/2019/modern-best-practices-testing-java/ (see "heavily use helper functions")

The helper functions also helps with the 'arrange-act-assert' pattern: https://medium.com/@pjbgf/title-testing-code-ocd-and-the-aaa-pattern-df453975ab80. In essnes we get test code that looks like this:
```
@Test
void someTest() {
   givenConditionOne();
   givenConditionTwo();

   ResultObject result = doComputation();

   assertThat(result, is(expectedResultObject));
}
```

### E:

The 'test' prefix is legacy from when this project used Junit3, it used to be a requirement for test methods to start with the word 'test'. I'm okay with having us describe the 'DisplayName' more. I've personally found it to be a best practice to document the test strategy/setup employed at a high level in a javadoc on most tests. The 'DisplayName' annotation really helps this. To keep in mind, tests are a maintenance cost, whenever they break developers need to answer: 1) what was this test testing, 2) why was this test accurate to begin with, and 3) is this test failure valid or does the test now need to be fixed?

I can share horror stories of mass poorly written tests where small changes take a few minutes then the next hours one is trying to understand why dozens of tests failed, what they were doing to begin with, and how to fix them.

### F:

It's hamcrest vs junit API. We've slowly started to move to hamcrest. It has some benefits:
- better error messages. For example `assertEquals(a, b)` just fails and says it was false, but if `assertThat(a, is(b))` fails, you get a toString() of both a and b.
- extensible, we can create custom matchers for us in hamcrest, eg: `assertThat(connection, isValidNetworkConnection())`
- readability, the `assertEquals(expected, actual)` is a bit flipped, it's a very common mistake for the args to be swapped. With the `assertThat` API, it's quite obvious that the expected is the second arg.
- uniformity, `assertEquals(null, a)` should in theory be written with `assertNull(a)`. `assertThat(...)` is uniform, just the matcher changes

The rule of thumb is to avoid mixing junit and hamcrest matchers in the same class file. The convention really is trying to say that if we are writing new tests, we should prefer hamcrest.

**Comment by RoiEXLab** [comment]
> - better error messages. For example `assertEquals(a, b)` just fails and says it was false, but if `assertThat(a, is(b))` fails, you get a toString() of both a and b.

Actually I don't think that's still the case. I haven't checked, but I'm pretty sure the error message prints both objects.

> The 'test' prefix is legacy from when this project used Junit3, it used to be a requirement for test methods to start with the word 'test'.

True, but from what I know it's still convention to prefix the method name, that's why most of our tests still have that prefix. Just like methods annotated with `@BeforeEach` are usually called `setUp()`.
So I agree with @asvitkine that we should probably agree on a convention for the method names of test cases.

**Comment by DanVanAtta** [comment]
> better error messages

Happy to hear junit5 assertEquals finally fixed that. There are other cases where you get better error message, like collection size check, collection content check, string contains check. The hamcrest API itself is designed to also split the concern of error message from assertion validation, which leads to better error messages across the board and cleaner custom assertion code 

> but from what I know it's still convention to prefix the method name

I'm skeptical on this one. If it's the convention, why would jUnit4 have dropped the requirement? Readability can actually suffer with redundant 'test' prefix. Seems like a kingdom of nouns problem, it's obvious it's a test method by the annotation.

> setUp()

I agree it is still conventional, the method does have to be named something after all.. I've read in some places that this is getting debatable for preference of stating what is being set up.

**Comment by DanVanAtta** [comment]
For 'test' prefix, it was not included in the original set. I am opposed to a convention on it. In some test cases that may make sense, across the board, maybe not. There are multiple kinds of naming conventions and different kinds of tests written as unit tests: https://dzone.com/articles/7-popular-unit-test-naming. I would not want it to be 'wrong' when it makes sense to use a different convention. If we were to pick a convention, I'd favor we avoid the 'test' prefix as it is largely redundant. I'm happy ignoring this when I see it, I'm more concerned that we actually write tests and that we try to write easily understood and maintainable tests.

**Comment by DanVanAtta** [comment]
@RoiEXLab confirmed that assertEquals does a `toString()`. Though, consider a case as well where you do not have an equals method on an object, you want to compare a property, and for debug it's useful to know the full state of the object. eg:
```
assertEquals(value, object.getProperty());
```
vs:
```
assertThat(object, hasValue(value));
```
With the second we can get an output of the full object however the 'hasValue' matcher would define it. This is particularly helpful when there is a sequence of values on an object to validate and knowing all the values is helpful. It avoids the case where debug 'toString()' code is injected to inspect the full object state.

**Comment by DanVanAtta** [comment]
concrete example:
```
    assertEquals(6, mfb.getAttackingUnits().size());
```
That does not print out the collection contents when it fails.

**Comment by DanVanAtta** [comment]
I think maybe it's better to leave the optional conversation for another day. I was not very used to it for a very long time, eventually I realized it is exactly an `if(value != null)` check, and my brain got used to that. I think it comes down to what a person is used to seeing. Most coders have seen the several different patterns of for loops, those that assign, those that search, those that map, to the point where the pattern is quick to identify, ie:
>  I think that concern comes down what a person is completely used to. It's like learning how to multiply, at first it requires thought, eventually it becomes hard wired and your brain sees the pattern and knows the answer without thought.

It's analgous IMO to many other learned behaviors, like long division, it's written differently in the US vs Europe, it's really hard to understand the other way when one is maybe slightly superior. Qwerty vs dvorak keyboards is another example, dvorak is shown to be good for about 5% increase in typing speed, but getting used to it is very difficult. I wonder what coders will do in 5 years on new projects. Businesses have a horrible tendency to keep code and old practices around, for example all of the Kobol code that is still out there. Old habits die hard.

But again, I think the optional concern becomes more of an issue when we use the optional API to its fullest and do things like 'map' + 'filter' that can start to be more objectively less error prone, which introduces a mixture of patterns. I've also found that when optional is used well and not piecemeal, you can wind up with less code overall and no NPE issues.

With all that said, I added to wiki the conventions that have had no discussion, implicitly accepted and cut issues for the others to discuss on their own. Let's please be sure to try and accomplish these discussions quickly/efficiently, we do not gain any points for winning on these topics, and we need to remember we are not producing any value here but are trying to reduce overhead so that we may do other value-producing activities at a higher rate.
