### ISSUE TITLE
AI Pause Duration Interface

### ISSUE THREAD

**Issue by RuinChristmas** [triplea-game/triplea#549]
When you go to Game -> AI Pause Duration, it won't let you enter an invalid number.  However this can be annoying because users can't see which numbers are allowable.  Also, it won't even let you to type an improper number at any time - even if it's part of a valid one.

For example: duration is set to 500 ms and I want to make it 1000.  So I delete the number and type 1... but I can't!

This is a minor issue but it seems that a better interface would a. list the allowable values b. if a user types in an invalid onne either an error message pops up (preferable IMO), or it won't let you click OK

**Comment by DanVanAtta** [comment]
#55 would help with this, somewhat related.

**Comment by DanVanAtta** [comment]
This is now fixed by moving the value to a settings window. The validation is done after you click save, so this is no longer a problem.
