### ISSUE TITLE
Game Settings UI Window

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#55]
Anyone have any thoughts or desire to change how  the various game settings are presented to users?

Some problems we have:
- settings a a bit scattered between the various menus
- settings can be ambigious, "focus on own casualties" without more context could mean a lot tof things.

Some possible ways to improve:
- tabbed settings window, 3 or 4 column layout:  `<name, value, recommended value, description>`

Why?
- The settings are getting a bit scattered, adding more could make things kinda gnarly. Would be nice to organize settings now while we have fewer. That will help give a cleaner framework for adding more.

**Comment by ron-murhammer** [comment]
Personally I agree and think that many maps have an overwhelming number of options that are very difficult to understand. I think the UI needs to be more descriptive and better organized. One thing I'll point out is somehow separating or prioritizing the most used settings such as low luck, no tech, etc would be a big win.

I'm not sure if the ordering is hard coded or if its based on the map XML. So that is something to consider as well as to whether you want to standardize setting UI for all maps or allow map creators to have more control over how the settings appear.

**Comment by DanVanAtta** [comment]
I was more thinking about the other options. The map options IMO are kept together nicely enough at least and could be left alone.  It would be nice to get them to be less hidden from behind the button during the lobby staging.

Regardless, some examples of options I was thinking of would be: sounds, combat preferences: "focus on own casualties", casualty selection; some view options: map zoom, map colors, unit size, etc..

**Comment by ron-murhammer** [comment]
Oh I see. You were thinking the setting menus at the top when you're in a game. I honestly think a pretty large percentage of players don't really even know most of them exist. It would be nice to make some of the common ones easier to use and notice. Personally, I really like the Civ 5 interface style of having all the most common info and options present on the interface around the edges. Then you can keep the more obscure settings in menus that people won't use as often.

**Comment by DanVanAtta** [comment]
I'm not sure if there is disagreement. The first thing to do I think is to gather the settings and have them make sense. Picture the civ5 settings screen after the game loads. Lots of options, graphics, sound, gameplay. 

During the game you get the same settings but the ones which are fixed for the game are grayed out. I'm thinking something similar. 

To be concrete:
- We convert the "engine preference" screen available from the initial game menu to be our settings screen. We remove the fluff from that screen and aggregate settings to it. Then when we have more options coming out, we'll have an easy place to put them.

The settings tabs I think we'll need so far:
- sounds  (sound on/off , volume)
- combat (casualty selection and confirmation)
- java (memory)
- view (map zoom)


The tabs also gives it good room to grow and/or be re-organized. As well we can do top/bottom layout of each pain. The top labelled "basic" with the common stuff, "advanced" for the more esoteric stuff people probably won't change.

**Comment by DanVanAtta** [comment]
Also to be included would be all the font options. There are a lot of them, they could use some explanation and easier discovery.

**Comment by veqryn** [comment]
On the UI thing in general, it would nice if TripleA looked like an actual game, rather than a funny colored Oracle ERP application (a comment from my wife).

**Comment by djensen47** [comment]
> On the UI thing in general, it would nice if TripleA looked like an actual game, rather than a funny colored Oracle ERP application (a comment from my wife).

:+1:  :smile:

**Comment by DanVanAtta** [comment]
I saw Mac today for the first time. It looks very different from window Linux. For example, the initial loading icon by the TripleA icon vs a black and gray loading bar, quite different. Also I liked the color scheme. A preview window the look and feel option would make that feature much more useful.

I've also wondered about changing the default look and feel from release to release (as a stray thought). 

So for a settings UI I was thinking of somethign similar to other games. There is one settings window with all the options. Here we can try to add some help text to our options to explain what they do. This window should remove (aggregate) a bunch of the options from the menus. To organize the options I was thinking a tabbed window.

When a user is in the game staging windows, pretty much all options should be available. Then when a game starts, some options may no logger be available, but they are grayed out, or otherwise hidden.

This is not that small of a change, I see it being successfully done by starting the UI and having some settings on it. Then moving more and more of them to it. Hopefully this will create a unified setting framework over not too long (the sound options has some generic promising code that maybe could be expanded, probably one of the first tabs to be created) . One goal will be in the future it'll make it very easy to have an option be a UI setting.

**Comment by djensen47** [comment]
I haven't done much gaming on my Mac or even a PC in a while but what I recall is that all the windows have a custom look and feel. I'm thinking something like Steam. Even IntelliJ has a nice dark theme called "Darkula."

The best way to proceed would be with mockups. Describing UI with text is a start but I discourage changes without mockups. I'd even suggest taking it a step further and get some feedback from users.

> I've also wondered about changing the default look and feel from release to release (as a stray thought).

The version number on the main dialog should be good enough.

**Comment by djensen47** [comment]
> Hopefully this will create a unified setting framework over not too long (the sound options has some generic promising code that maybe could be expanded, probably one of the first tabs to be created) . One goal will be in the future it'll make it very easy to have an option be a UI setting.

Are there any OSS libraries to assist with this?

**Comment by DanVanAtta** [comment]
@djensen47 Thanks for the feedback, sorry for the delayed resonse.

> The version number on the main dialog should be good enough.

The main dialog here is the console window that pops up? For end-users that generally stays hidden until there is a game error. Otherwise in the game UI we show map version and not game engine version. It is actually a bit confusing even since it is labelled as "Game version" but actually refers to map version.

So it does seem like the game engine version probably should be in the UI somewhere rather than being printed to console.


> The best way to proceed would be with mockups. Describing UI with text is a start but I discourage changes without mockups. I'd even suggest taking it a step further and get some feedback from users.

No strong disagreement, though what we have now seems very arbitrary and ad-hoc. Thus I would rather bias towards action rather than not. Hopefully a mock up woudl happen, in the meantime what I'm thinking is a standard tabbed swing window pane. It would likely start by adding tabs to the sound options window, and then continuing with that style adding more tabs beyond "sounds". Hopefully that gives a pretty good idea of what is intended, and then nice benefit is we have a single window with all the settings. We can then skin things afterwards to improve the aesthetic.


> Are there any OSS libraries to assist with this?

I didn't quite convey my point very well. We do use OSS libraries, but every time we do we re-implement how we interact with that library each time. Thus what I was more getting at was creating some standard DOA-like code so we can access preferences in a unified way. This would then hopefully make it relatively trivial to not only persist a system preference, but also to present that setting to the user as an option they can modify. Right now doing that is not too bad, but it's not trivial to create ad-hoc user settings. Generally you need to find a menu to add the item too, or some window you can attach it, and there are about 6 different locations that can be chosen from. 


So I think part of the bottom link with this issue is that the settings and user preferences is lacking some very high level design of how those settings will be presented to the user, and where. So I'd like to see us move to having all settings available from one window (that has tabs to group the settings). From there we can work on grouping, aesthetic, and adding help/explanatory text to the settings so folks will know what "focus on own casualties" means.

**Comment by DanVanAtta** [comment]
working on this.

**Comment by DanVanAtta** [comment]
Conversation has gotten long here, summarizing the current state and direction in: https://github.com/triplea-game/triplea/issues/834
