### ISSUE TITLE
Default/Last Options disappear

### ISSUE THREAD

**Issue by RuinChristmas** [triplea-game/triplea#550]
When you load a game, or play a game, and then exit back to the main menu, then start a new game, your options are reset.  What I mean is if I played or loaded a game with Low Luck/Honorable Victory, etc, then start a new game, it's back to projection of power/dice.  I assume most people would want either the default options or the options that were used in the last save game loaded. (The way to get them back is to "Choose Game" again but I don't think this should have to be done, since there is set default button)

**Comment by ron-murhammer** [comment]
@RuinChristmas - Doesn't the 'Make Default' button in the 'Game Options' window do this?

**Comment by RuinChristmas** [comment]
@ron-murhammer - no but I feel that it should.  

I set my options (low luck etc). And click "make Default".  Every time I go to "Choose Game" and select that map (let's say revised) it's all good.  Got the default options that I set.  

However, if I load a saved game (of the same map), when I exit out, the map will be loaded and I'll be at the screen where you can set the players to AI or Human.  Cool, so I start playing, only to find out that now I'm playing dice and tech (or whatever options were set when i first downloaded the map), disregarding the defaults i set.  BTW same thing if i don't just start playing and actually click Options - I can see that the original settings are back.

**Comment by ron-murhammer** [comment]
@RuinChristmas - Oh ok, I see what you mean now. The default options you've set aren't loaded after exiting a new or saved game which isn't intuitive as they should be the 'default'.
