### ISSUE TITLE
Designing: Github Actions CI

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5508]
In this issue, let's identify the tasks to run and a strategy for how to get it all done.

- run checkstyle
- run unit tests
- run integ-tests
- rebase to latest master
- run spotlessApply
- auto-remove unused lombok log annotations
- coverage report

- spotlessApply I think is okay committing back to the original PR branch
- rebasing to latest master I'm not sure is okay to commit back to the original branch. We can do the rebase before running any tests, and just simply not commit it back. If we do that, then there may not be any ordering dependencies.

### Open Questions

- [ ] How to spin up a postgres DB for the integ tests

**Comment by RoiEXLab** [comment]
About the postgres question:
Individual steps are really just docker images, so we can either hope there is an postgres action already there for use [look at that](https://github.com/marketplace/actions/setup-postgresql), and we configure it using bash as usual, or we create our own docker container with everything setup for us and use that directly.

**Comment by RoiEXLab** [comment]
Looking at the action I linked, it looks like user and database can be configured from the yaml already.

**Comment by DanVanAtta** [comment]
Seems like it could be the same as the postgres docker image we use already

**Comment by DanVanAtta** [comment]
The spotlessApply github action is working like a charm, my latest Java PR made use of it to fix a formatting violation :smile: 

@RoiEXLab one thing I'm wondering, is how to have github actions configured as a status check? I see the way to see output from actions is from the 'actions' tab, it's odd it is not attached to a PR. I thought actions were meant to automate workflow like branch verification before merge, is it not yet there for status checks?

**Comment by DanVanAtta** [comment]
See for example: https://github.com/triplea-game/triplea/pull/5511, I'm not clear how that could become a status check and it looks like it was not run.

**Comment by RoiEXLab** [comment]
@DanVanAtta I believe the reason why it didn't work is because the semantics of the yaml file are probably wrong, there are some duplicate keys, and I believe one job is defined in the wrong location
