### ISSUE TITLE
Mandatory anti-aircraft

### ISSUE THREAD

**Issue by RuinChristmas** [triplea-game/triplea#551]
(note I have a save file that demonstrates this but github won't let me upload it)

The interface forces a player to take the shortest flight path in non-combat even if it is over an AA gun.

Situation from revised map: Option: always on AA. Caucasus is German controlled. Yakut is Japanese, but Novo, Kazakh, Evenki, and Russia are still Russian.  Japanese fighter in Yakut has combat in Evenki (1 movement) and then wants to land in Caucasus.  If i try to direct the fighter there, the interface chooses the shortest path (Evenki-Russia-Cauc) and asks me do I want to take AA fire in Moscow.  No, I want to fly over Novo and Kazakh, which is within the fighters range but AFAIK there is no way to do this, since it won't let me choose those territories as intermediate steps (Cannot advance units to battle in non-combat)

Note also if Kaz were Axis-controlled i could move there as an intermediate step, and then on to Cauc with no problem.

"If you're ctrl-clicking it should at least change to say something like "Set Waypoint" to show you that you're on the right track."

**Comment by ron-murhammer** [comment]
@RuinChristmas If you zip the save game then it should allow you upload it. Like this:
[triplea_37063_Egy1.zip](https://github.com/triplea-game/triplea/files/183403/triplea_37063_Egy1.zip)

**Comment by DanVanAtta** [comment]
control clicking will set waypoints. How to improve the game UI to better indicate that is a good question. I've asked zjelco if the tutorial will cover it. Perhaps a help button on the same confirm AA dialog would be a good place for it, it's most important for exactly this situation (avoiding AA).

**Comment by RuinChristmas** [comment]
@ron-murhammer - caja won't give me the option to zip the file from the right click menu . I'm not sure why. Working on it. Can you tell me how to zip from the command line? (software manager says i have zip and p7zip installed)

@DanVanAtta - okay that worked but yeah it was tricky, I had to ctrl-click in each territory and the cursor is still white x circled in red, and the error message "Cannot advance units to battle in non-combat" still displays at the bottom. I.E. no indication that I'm doing the right thing.  If you're ctrl-clicking it should at least change to say something like "Set Waypoint" to show you that you're on the right track.

**Comment by DanVanAtta** [comment]
:+1:  to this: "If you're ctrl-clicking it should at least change to say something like "Set Waypoint" to show you that you're on the right track."

**Comment by ron-murhammer** [comment]
Yeah, probably improving way points is the easier and more short term fix. Pathing is hard period and you'd have to consider what AA rules are on plus there are many other situations like this where a unit should actually take a longer route to avoid something in more complex maps.
