### ISSUE TITLE
Convention? Favor hamcrest assertThat for new tests

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5526]
Instead of:
```
    assertEquals(6, mfb.getAttackingUnits().size());
```
Favor:
```
assertThat(mfb.getAttackingUnits(), hasSize(6);
```

Benefits:
- custom matchers
- better custom matcher code, the concern of how to print failures is split from the concern of how to validate the assertion
- bigger library of checks, matchers is extensive. For example, the Optional matchers library that has been used quite a bit.
- better error messages. In the above example you see the collection contents vs a failure of this number was not equal to another number. The custom matcher can also give more context to the value under test
- prevents swapping of 'expected' and 'actual' parameter positions, `assertEquals(expected, actual)`  is easy to swap/confuse the expected vs actual arg positions (we have this quite a bit).
- uniformity, `assertEquals(null, a)` should in theory be written with `assertNull(a)`. assertThat(...) is uniform, just the matcher changes
- can write 'higher-level' matchers for better checks, eg: instead of writing a series of assertions to validate a set of values, can write a single matcher, ie:
```
assertNotNull(move.getStart());
assertEquals(5, move.getLength();
```
Can write:
```
assertThat(move, isValidMoveWithLength(5));
```

Or:
```
assertTrue(move.getTerritories().contains(territory));
```
// vs
```
assertThat(move, containsTerritory(territory)); 
```
The latter would print out the full move object so you can see which territories are in the move sequence. The first one would just print out 'false'.  Being able to diagnose quickly why tests fail becomes important at scale, when there are many tests, it becomes important.

**Comment by ron-murhammer** [comment]
I'm fine with this.

**Comment by asvitkine** [comment]
In #5503, MoveBatcherTest really wants to check equality.

For example, it currently has:
    assertEquals(new MoveDescription(List.of(transport1, transport2), sz19ToSz18), moves.get(0));

In that case, I'm not sure that decomposing into other concepts is useful - it really wants to see that exact move output from the result of running the algorithm.

I guess it would have to be written as:

    assertThat(moves.get(0), is(equalTo(new MoveDescription(List.of(transport1, transport2), sz19ToSz18))));

That's a bit longer and less readable. Why not still allow assertEquals() for cases that don't need the extra features?

**Comment by DanVanAtta** [comment]
```
assertEquals(new MoveDescription(List.of(transport1, transport2), sz19ToSz18), moves.get(0));
assertThat(moves.get(0), is(new MoveDescription(List.of(transport1, transport2), sz19ToSz18));
```
TBH I don't think either one is terribly readable, but they are pretty equivalent and just have the parameters reversed in this case. OTOH, I do think the second does make it more clear that `moves.get(0)` is the element under test.

> Why not still allow assertEquals() for cases that don't need the extra features?

I suppose a few reasons:
- (moot) Prior to Junit5, matchers were included with the Junit package, this allowed for the potential of classpath collisions and very odd errors. This was avoided by staying consistent
- the two are equivalent, there is not strong reason to need/use 'assertEquals'?
- elides benefit of the consistent 'assertThat' for assertions
- assertEquals mixed with assertThat has the expected and actual parameters flipping, this is difficult when in the same file.

**Comment by DanVanAtta** [comment]
Looking at the above comment, the assertEquals does have some issues, there are lots of comma's and parens, it's a bit difficult to see where the 'actual' param starts, the second helps that (thought the expected parameter is  messy; side-note, a builder might help make it a bit cleaner).

**Comment by DanVanAtta** [comment]
@RoiEXLab not that I could find

**Comment by DanVanAtta** [comment]
Seems like this is adopted, any last minute objections, concerns or comments?

**Comment by RoiEXLab** [comment]
Not really.
It's perhaps worth noting that it would be pretty simple migrating existing tests using intelliJ.
It offers a structural replace functionality that can be used to migrate a certain junit assertion with one click and a little bit of configuration.
I have successfully used it in the past to migrate to assertJ matchers which are somewhat similar to hamcrest.

**Comment by ron-murhammer** [comment]
Good here.

**Comment by asvitkine** [comment]
Sounds good.

+1 to migrating existing things over if it's easy - so that we don't have an inconsistent state.

**Comment by DanVanAtta** [comment]
Thanks all, sounds decided. Added this to wiki: https://github.com/triplea-game/triplea/wiki/Java-Test-Code-Conventions#favor-hamcrest-assertthat-for-new-tests--5526
