### ISSUE TITLE
Suicide/Munitions units not firing

### ISSUE THREAD

**Issue by CrazyGerman** [triplea-game/triplea#556]
[Possible_suicide_bugs.zip](https://github.com/triplea-game/triplea/files/185246/Possible_suicide_bugs.zip)

Game is Age of Tribes BETA. Germanic combat phase, 3 mortar bombardments in Teutonia do not fire. I'm unable to isolate, see related post in the development forum.

**Comment by DanVanAtta** [comment]
Is this the related post? http://tripleadev.1671093.n2.nabble.com/Maps-and-Mods-f1671664.html

**Comment by CrazyGerman** [comment]
That link took me to maps and mods. Here is the permalink -

http://tripleadev.1671093.n2.nabble.com/Questions-Bugs-and-BattleCalculator-Suggestions-td7591799.html

**Comment by DanVanAtta** [comment]
Ideally enough context that this problem can be picked up at a future date, we'll understand what is wrong and what should happen, and how to reproduce. I've requested that similar instructions be added to the project readme page, so it'll be visible here: https://github.com/triplea-game
 
(PR: https://github.com/triplea-game/triplea/pull/557/files)
