### ISSUE TITLE
Next release a 1.9 instead of 1.8?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#558]
Since most maps are going to be updated, most save games are not going to be playable anyways. Also given the number of changes, and the difficulties of getting a map transition, it's a bit overall cleaner to keep the next release separated. For example, with the many new map versions a second lobby instance is likely going to be needed.

I think this is one of the best times for us to do a non-backwards compatible release. The only real extra cost is we add the 1.8.0.9 jar with the 'old_jars' (assuming we spin up the 2nd lobby anyways). This will give us a good opportunity to do a number of things:
- fix attatch mispelling (this is important, the maps have all been rolled forward, we're a bit past the point of no return).
- remove unused public non-static API (unused static unless inovked via XML is always safe to remove, reflection does not call static methods)
- rename variables

**Comment by ron-murhammer** [comment]
@DanVanAtta We need to check both save game and lobby compatibility to determine what version we should move to and what needs done on release.

**Comment by DanVanAtta** [comment]
lobby compatibility is still there, so is save game. But, if we merge the attatch fix, then we'll lose save game compatibility. @ron-murhammer , the question here is to make the decision to go to 1.9 for the next release, a number of good reasons to do so. 

*If* we decide to go to 1.9 *after* we have a release candidate, instead of now, we'll have squandered an opportunity to make the many other changes we would want. Because we already moved so far with the 'attatch' fix, and the number of issues around map upgrades, we're already started down the 1.9 path. I think at this point we need extremely compelling reasons to stay on 1.8. Sticking to 1.8 is very costly right now.

**Comment by ron-murhammer** [comment]
@DanVanAtta I'm fine moving forward to 1.9 as we have a lot of changes and agree I'd rather move forward. My only point was let's not update versions if we don't need to. If for some reason we choose not to merge the attatch change before releasing then probably no need to go to 1.9.

**Comment by DanVanAtta** [comment]
"attatch" will be the first place where we absolutely need to go to 1.9. For the map transition, a hop to 1.9 would be very convenient, but not strictly required. I think we have consensus to move to 1.9.

**Comment by DanVanAtta** [comment]
It should now be open season on variable name changes : )
Method calls we still need to be a bit careful, but most calls are compile time checked. We have an opportunity to clean out a number of unused public methods.

**Comment by ron-murhammer** [comment]
@DanVanAtta Agree though watch for the reflection crap. Doing a pass on removing as much of the m_ crap and unused methods as possible might be worth it. Only thing I'll say is the more code we touch if we have serious bugs on release it will be more painful to track them down.

**Comment by DanVanAtta** [comment]
I spotted once a place where we could pass in an enumerated type rather than string for method calls. Probably worth doing a survey of what is not compile time checked. Most of the remote delegate stuff gets remote objects, but at least is compile time checked. The XML code likely is where 90% of the non-compile time checked stuff is likely to exist. 
 Point taken nonetheless to be careful about cleanups.
