### ISSUE TITLE
Figures in Classic WW II Setting are sometimes not distinguishable from each other

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#559]
I played the WW2 setting of TripleA, and I noticed that sometimes You can't distinguish which "nation" the figure belongs to.
I would whish for an option to enable a small Symbol on the figure to make this clear.

**Comment by DanVanAtta** [comment]
Notes: Perhaps this won't be too difficult, when we draw units in the territory panel we draw a flag icon next to them. We likely can use similar code behind a feature flag to draw the same mini-flag icon next to each unit.

**Comment by RoiEXLab** [comment]
Implemented #653
