### ISSUE TITLE
Github Releases Page Not Currently Working

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5613]
Release page is going 'unicorn', taking too long to load and failing to load.

I contact github support about this and got a message back saying they are seeing similar reports for other projects:

> We're currently investigating similar reports regarding this issue, and I've added your report to our list.
> While we can't share a specific ETA just yet, we'll be sure to update you as soon as there's any news to share.

_Originally posted by @DanVanAtta in https://github.com/triplea-game/triplea/issues/5608#issuecomment-558920915_

**Comment by DanVanAtta** [comment]
Links that are direct to a specific release (tag) do still work.
Latest at this moment is: https://github.com/triplea-game/triplea/releases/tag/2.0.16914

**Comment by DanVanAtta** [comment]
Github responded, said they see the page is loading (not sure if they did anything).  I'm able to access the releases page only when logged out of github.

**Comment by RoiEXLab** [comment]
Same @DanVanAtta

**Comment by DanVanAtta** [comment]
Problem looks to have been a large number of draft releases which went on to only impact logged in maintainers. Github support deleted those releases, problem is fixed.

**Comment by RoiEXLab** [comment]
Finally 👍
