### ISSUE TITLE
PR: follow-up, Show warning dupe matcher

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5639]
@asvitkine this warning seems legitimate to fix:

game-core/src/main/java/games/strategy/triplea/ai/pro/data/ProTerritoryManager.java on lines 379..385

```
        PredicateBuilder.of(Matches.territoryIsWater().or(Matches.isTerritoryEnemy(player, data)))
            .and(
                Matches.territoryHasUnitsThatMatch(
                    Matches.unitCanScramble()
                        .and(Matches.unitIsEnemyOf(data, player))
```

We would not want to maintain both pieces of code in parallel, looks like the logic can be made into a `Matches` predicate and consolidated without too much trouble.

_Originally posted by @DanVanAtta in https://github.com/triplea-game/triplea/pull/5619/review_comment/create_

**Comment by DanVanAtta** [comment]
@asvitkine handled this in #5619 :+1:

**Comment by asvitkine** [comment]
Actually, this didn't get handled in the original PR - we still have this in two places. Let's re-open and I can send a PR for it.

**Comment by DanVanAtta** [comment]
Ah, my mistake, thanks for pointing that out @asvitkine
