### ISSUE TITLE
"Must complete Battle in 110 Sea Zone first" shown in all-AI game

### ISSUE THREAD

**Issue by asvitkine** [triplea-game/triplea#5646]
**Describe the bug**
This is on tip of tree, playing all Hard AI game of Global 2nd edition.
 
**Engine Version or SHA**
c3709c28a46f060b96cfd65e3c80f6337ac5c357

**To Reproduce**
1. Run a Global 2nd edition game with all players set to Hard AI.

**Comment by asvitkine** [comment]
To repro, you may need to get this fix in first or else it might hit an issue earlier: https://github.com/triplea-game/triplea/pull/5647

Adding instrumentation, the battle being attempted is in Normandy Bordeaux. But actually looking at the AI moves in question, it's not obvious why the sea battle must be completed first. In my example game, the units attacking Normandy are unrelated to the units in the sea battle - they consist of units just moving from land territories and not involving the sea battle.

Perhaps the engine is incorrectly associating the sea battle as a dependency?

**Comment by DanVanAtta** [comment]
Is this the same problem as: https://github.com/triplea-game/triplea/issues/5216 @asvitkine ?

> When progressing to combat phase, a pop-up appears warning player should fight one battle first, but combat window is also opened and neither the combat window nor the warning dialog can be closed.

**Comment by asvitkine** [comment]
I'm not sure it's the same. In this case, I didn't observe any freeze, just this popup but the AI game kept going.

**Comment by asvitkine** [comment]
For reference, it doesn't happen with 16749 - which is an old build I had around.

I'm going to try bisecting.

**Comment by asvitkine** [comment]
Looks like it's not deterministic because some games, Germany simply doesn't attack Normandy on turn 1. So not obvious when it started. I'll try to just debug it instead of bisecting.

**Comment by asvitkine** [comment]
Interesting, if I load up the game after germany does its combat move when the bug happens, and play the turn out as a human, I don't get this dependent battle warning.

**Comment by asvitkine** [comment]
Ok, so the cause seems to be this logic related to scrambling:
```
      // now make sure any amphibious battles that are dependent on this 'new' sea battle have their
      // dependencies set.
      if (to.isWater()) {
        for (final Territory t : data.getMap().getNeighbors(to, Matches.territoryIsLand())) {
          final IBattle battleAmphib = battleTracker.getPendingBattle(t, false, BattleType.NORMAL);
          if (battleAmphib != null) {
            if (!battleTracker.getDependentOn(battle).contains(battleAmphib)) {
              battleTracker.addDependency(battleAmphib, battle);
            }
            if (battleAmphib instanceof MustFightBattle) {
              // and we want to reset the defenders if the scrambling air has left that battle
              ((MustFightBattle) battleAmphib).resetDefendingUnits(player, data);
            }
          }
        }
      }
```

This logic seems simply wrong. Basically, what it's doing is if scrambling is happening, it marks any adjacent land battles as dependent on it. But, it doesn't take into account whether any units are being landed from that sea zone.

The reason I wasn't able to repro it as a human is I answered "no" to scrambling.

So seems like a plain old bug that can be fixed by making the logic take that into account and only add a dependency if units are being landed from that sea zone.

However, I'm going to debug more to see if something from my recent changes could have affected this somehow.

**Comment by asvitkine** [comment]
I tried on an old revision dc33138dba9a208ab7fb22c9b94afe26808916e8 and was able to repro the issue as a human player by just moving a ship Sea Zone 110 as Germany and attacking Normandy by land and selecting some units to scramble.

So seems like an old bug, but perhaps triggered by recent AI logic changes that made AI choose different combats than before. I'll look at making a fix.

**Comment by DanVanAtta** [comment]
Sounds good, thank you for digging into this @asvitkine
