### ISSUE TITLE
Test Conventions (?)  1) is(nullValue())   2)  @Mock & @InjectMocks order

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5649]
Proposing a couple conventions for better consistency in test code:

1) Prefer to use `is(..)` with `nullValue()`

Instead of:
```
assertThat(value, nullValue());
assertThat(value, notNullValue());
```

Prefer:
```
assertThat(value, is(nullValue());
assertThat(value, is(notNullValue());
```

2) Order injected mocks first, then the injected object, then any further mocks

Example,

With a constructor:
```
  LobbyChatClient(
      final GenericWebSocketClient webSocketClient, final ChatClientEnvelopeFactory clientEventFactory) {
```

Instead of:
```
  @Mock private GenericWebSocketClient webSocketClient;
  @Mock private ChatClientEnvelopeFactory clientEventFactory;
  @Mock private ClientMessageEnvelope clientEnvelope;
  @InjectMocks private LobbyChatClient lobbyChatClient;
```

Prefer:
```
  @Mock private GenericWebSocketClient webSocketClient;
  @Mock private ChatClientEnvelopeFactory clientEventFactory;
  @InjectMocks private LobbyChatClient lobbyChatClient;
  @Mock private ClientMessageEnvelope clientEnvelope;
```
In the above, the injected mocks are listed first, then the `@InjectMocks` object, then any other mocks that happen to be used are then listed later. This ordering makes it a bit more clear which objects we are injecting and which ones are just used in the test for other reasons.

**Comment by DanVanAtta** [comment]
Part (2) decided here IMO is over-specified. A good convention, but I think I'd rather see tests than worry that folks have stayed 100% consistent to ordering of mocks and test values.

@ron-murhammer , (1) has an element that came up in a PR but I also see we violated recently too. Please have a look over and give your yay or nay.

**Comment by ron-murhammer** [comment]
I don't know that I really agree with 1. The second option seems just as easy to read and shorter. But not a big deal either way and I'd rather see consistency.

**Comment by DanVanAtta** [comment]
(1) is pure style preference. @RoiEXLab raised it in a CR. I don't really mind either way.

(2) is hard to enforce/police, it's a personal style that perhaps can be more widespread, but at the end of the day it's not the most important thing to look for. I think we should do it, but I'm not going to call it out or look for it in reviews, hence I don't think it's necessarily worth codifying.


For (1), seems our votes are:
- in favor
- neutral
- weakly against

Without further discussion, I think the final decision will be for us to not worry about any inconsistency or style preference (1) and just do what you want when writing tests. We do have higher order concerns to focus on after-all, unless it can be reasoned this is better consistent.

**Comment by RoiEXLab** [comment]
> to not worry about any inconsistency or style preference

I'm fine with that, I always try to make the test sound more like natural language. That's why I like to use the `is` method often, but I don't mind if someone doesn't use this unecessary wrapper either, it's code after all, not some sort of novel ^^

**Comment by DanVanAtta** [comment]
Closing, while I'm in favor of us following both conventions, I'm not in a position anymore to advocate that we do anything about it (documentation, enforce it in review, etc..)

If anyone would like to take up this cause, please re-open or create a new issue with the proposed conventions.
