### ISSUE TITLE
AI and/or engine code is dominated by GameMap.getNeighborsValidatingCanals()

### ISSUE THREAD

**Issue by asvitkine** [triplea-game/triplea#5654]
AI and/or engine code is dominated by GameMap.getNeighborsValidatingCanals().

This is what shows up at the leaf of most function calls with significant CPU cost. Example:

![Screen Shot 2019-12-03 at 11 37 36 PM](https://user-images.githubusercontent.com/17648/70113116-f0eebc00-1625-11ea-9c76-2650bc2336cd.png)

We should investigate if this can be optimized. In particular, the underlying code uses streams API and lots of abstraction, which might be nice for readability but may not be great for performance.

At the very leafs, we also see the code querying attachments, which might be O(n) operations:

![Screen Shot 2019-12-03 at 11 42 32 PM](https://user-images.githubusercontent.com/17648/70113277-9f92fc80-1626-11ea-9979-6790adbf0e2f.png)

Perhaps there's some caching that can be done so that all attachments don't need to be scanned to find canals, for example.

**Comment by DanVanAtta** [comment]
Good work pinpointing this @asvitkine, it's great research for focusing our efforts. With that said, I'll note this fun saying:
> It's better to optimize correct code than it is to correct optmized code.

So we should tread carefully, perhaps ideally starting by adding a test harnass before we engage in a lot of performance tuning. Overall the O(n) algorithm and lack of caching seem to be really good targets for better perf. Again, good research, thank you!  :+1:

**Comment by RoiEXLab** [comment]
IIRC this code is used by the route finding algorithm as well.
Some time ago parts of this were "parallelized" using parallel streams which increased performance by a noticeable amount. This might explain the heavy CPU usage because it uses a lot of CPU cores.

Regardless I think caching values might help a lot here, I'm pretty sure that (without looking at the code) most of the time the values don't change at all. And in this case the overhead of streams shouldn't matter at all.

**Comment by ron-murhammer** [comment]
As @RoiEXLab points out this is used for route finding and there are some comments I believe in the code pointing out that performance of that matters. This fires a lot in the AI as it calculates various unit move options and for the player every time they select units and move the cursor around.

**Comment by DanVanAtta** [comment]
Moved this to a wiki page for more generalized tracking/discussion: https://github.com/triplea-game/triplea/wiki/Performance-Improvements

**Comment by asvitkine** [comment]
> Moved this to a wiki page for more generalized tracking/discussion: https://github.com/triplea-game/triplea/wiki/Performance-Improvements

What happened to that wiki page? It doesn't seem to be there anymore.
I recall I documented how to profile/optimize there. Did it get lost somehow?

**Comment by asvitkine** [comment]
> > Moved this to a wiki page for more generalized tracking/discussion: https://github.com/triplea-game/triplea/wiki/Performance-Improvements
> 
> What happened to that wiki page? It doesn't seem to be there anymore.
> I recall I documented how to profile/optimize there. Did it get lost somehow?

I see it was deleted here:
https://github.com/triplea-game/triplea/wiki/_compare/43cbf2ce1ae81eaf3c9d47e845972e60cfaadcff...fe412fa80c09f875b13120e3caf0a41c90034be7

Why?

**Comment by DanVanAtta** [comment]
@asvitkine we moved the wiki documentation to code, the docs/ folder. The profiling page is now located here: https://github.com/triplea-game/triplea/blob/master/docs/development/how-to/performance-profiling-triplea.md

For reference, there was some discussion about the move, for context you can read that here:  https://github.com/triplea-game/triplea/issues/7302

**Comment by asvitkine** [comment]
> @asvitkine we moved the wiki documentation to code, the docs/ folder. The profiling page is now located here: https://github.com/triplea-game/triplea/blob/master/docs/development/how-to/performance-profiling-triplea.md
> 
> For reference, there was some discussion about the move, for context you can read that here: #7302

Thanks! I couldn't find it. Should we add information to the wiki to point at those doc's?

**Comment by DanVanAtta** [comment]
README is the preferred place and is the most logical starting point. Having multiple "sign-posts" to send people in the right direction is arguably a good thing, so a link on the wiki would not be bad. My only concern would be that is then used as a starting point for further wiki additions rather than going into /docs.
