### ISSUE TITLE
Merging Integration-Testing  & lobby-db into http-server

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5664]
Motivation:
- we may recall that when http-server is started from integration tests that Travis does not show output from it. Generally this is okay, but is a huge problem if we get a travis only 500.
- https://github.com/triplea-game/triplea/pull/5661 now is generating a travis only 500.

History:
- we had this fixed before by launching an http-server from jar
- logback pathing issues broken when we included integration-testing, all classpaths got more or less mangled together and we wind up with a classdef not found error launching the http-server
- we moved forward with the integration-testing subproject and removed the independent jar file launch and lost server output
- before integration-testing subproject, we had a nondeterministic build as DB updates when testing http-server ran they could conflict with lobby-db

Proposal:
- merge up sub-projects and re-enable jar launch of http-server

Benefits:
- fewer sub-projects. Now that we no longer have lobby using DB, having all tests depending on DB in one sub-project keeps the same solution we wanted by having all such tests in the 'integration-testing' subproject.
- better cohesion of DB code with where it is used.
- we regain output of http-server in travis

Challenges
- in-flight PRs need this debug output, yet the merge conflicts may potentially be bad. Our new post-merge review process likely will come in handy here.

**Comment by RoiEXLab** [comment]
Actually I wondered why there were still 2 separate projects.
So I don't see a reason to not go for it 👍
