### ISSUE TITLE
Unable to Join Lobby (2.0.17022)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#5681]
Using TripleA 2.0.16996 I can join lobby.

Using TripleA 2.0.17061 I cannot join lobby.

I see the lobby, with the name I choose in it, but I cannot interact with it, and I see a window telling me "Disconnected fr...".

I'm on Windows 10.

p.s.: Lately I'm frequently experiencing cases in which a new release disables me from loading the savegames of a previous one, that much lowers my propension to update my prerelease, especially if I have any games going with other persons. Is that normal? It would be of much help if something like the second digit would be increased any time savegame compatibility is consciously broken.

**Comment by DanVanAtta** [comment]
Were you getting a 403 error @Cernelius ? 

We recently fixed a problem where authorization was not being applied. That lead to cases where the auth rules were not correctly defined (now that they are being applied, this is noticeable).

> lately I'm frequently experiencing cases in which a new release disables me from loading the savegames of a previous one, that much lowers my propension to update my prerelease, especially if I have any games going with other persons. Is that normal?

yes and no. It speaks to the absolute brittleness of TripleA and how hard it is to work with. I can guarantee that 90% of those changes that caused that would have looked innocent and were not at all intended to have that effect. We would only know by firing up a save game manually. Given we've had about 50 merges in the last week, that is 50 times we would have done it, in prep of a PR there is about 3-5 rounds of testing, so we're talking a repetition of that test 150 or 250 times in just the last week.

We're in a non-compatible mode right now, which means there is no guarantee for one version to be compatible with the next. Using a prerelease is a "at your risk" activity, it's discouraged to do so for the sake of just picking up new features. Beyond other intents, it is intended for testing and feature preview.


With that said, it looks like we have a different/new issue on connecting to lobby in the latest @ b5fa8391f9dbb6f47d5fc6aca610e3dea7dcfd9d

```
SEVERE: null
java.lang.NullPointerException
	at games.strategy.engine.chat.Chat.lambda$getStatus$15(Chat.java:140)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1624)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:548)
	at games.strategy.engine.chat.Chat.getStatus(Chat.java:141)
	at games.strategy.engine.chat.ChatPlayerPanel.getDisplayString(ChatPlayerPanel.java:236)
	at games.strategy.engine.chat.ChatPlayerPanel.lambda$createComponents$1(ChatPlayerPanel.java:129)
```

**Comment by Cernelius** [comment]
All I get is a very small window with nothing else written but "Disconnected fr...". Nothing in the console. Confirmed for 2.0.17075.

**Comment by DanVanAtta** [comment]
Okay thanks @Cernelius 
FYI the version number is typically most useful to know the 'min' version of when the issue started. This let's look at the diff of that version from the previous to see what changed. If the bug ticket is open, it's pretty safe to presume that the latest version would still have the issue.

**Comment by Cernelius** [comment]
Do you think this just needs to be fixed or could I do something to avoid being disconnected?

**Comment by Cernelius** [comment]
I've tested the following versions:
With 2.0.16996 I can use the lobby.
With 2.0.17016 I can use the lobby.
With 2.0.17017 I can use the lobby.
With 2.0.17022 I am immediately disconnected from the lobby.
With 2.0.17030 I am immediately disconnected from the lobby.
With 2.0.17043 I am immediately disconnected from the lobby.
With 2.0.17061 I am immediately disconnected from the lobby.
With 2.0.17075 I am immediately disconnected from the lobby.

So, I assume the problem has to be with something you changed moving from 2.0.17017 to **2.0.17022**.

**Comment by DanVanAtta** [comment]
There were a couple of problems, this should be now fixed though as the prerelease spitfire server has been restarted and is on the latest version.

(1) Long term fix, restart server on deployment of new versions: https://github.com/triplea-game/triplea/pull/5751

(2) Render error message on EDT thread, doing so otherwise yielded an error (hence no error message):  https://github.com/triplea-game/triplea/pull/5749

(3) Fix observed race condition on socket open which could potentially cause errors connecting: https://github.com/triplea-game/triplea/pull/5750

**Comment by beelee1** [comment]
just had trouble trying to join with 16920. Posted at triplea site. I'll try again with latest pre

**Comment by beelee1** [comment]
yea new one works fine. On a side note, can we have the "installer" command add a space between parentheses ? So it's easier to copy.  (./TripleA_...unix.sh)  ( ./TripleA_...unix.sh ) Not a huge deal but ... :)

**Comment by DanVanAtta** [comment]
@beelee1 dedicated issues, even if one sentence, are preferred so that topics are as independent and as bite-sized as possible. It makes it easier to get things done. Regardless, the formatting update is submitted here: https://github.com/triplea-game/triplea-game.github.io/pull/329
