### ISSUE TITLE
Loading transports with multiple units regressed since 1.9

### ISSUE THREAD

**Issue by asvitkine** [triplea-game/triplea#5706]
**Describe the bug**
While testing my movement refactoring changes, I noticed that loading transports is not working great when multiple units are selected and seems to be worse than earlier builds. In particular, moving a selection of 3 infantry and 1 tank onto a transport results in 1 tank being loaded only, whereas previously, 1 infantry and 1 tank would be loaded.

**Engine Version or SHA**
1667ee6365fbdea45abbd34180e2d4f08ccb19eb

**To Reproduce**
1. On Global 40 2nd edition...
2. As germany, select 3 infantry and 1 tank in poland
3. Try to load them on the transport

**Expected behavior**
1 infantry and 1 tank should be loaded.

**OS (please put an X in the appropriate box):**
[] Windows
[X] Mac
[] Linux

**Additional context**
This is not related to my recent MovePanel changes - the bug exists without them. But it could be due to my refactoring of unit to transport mapping. I will try to bisect.

**Comment by asvitkine** [comment]
Actually, looks like r16749 is not working either. But it works in 1.9.

**Comment by asvitkine** [comment]
@DanVanAtta is it possible for me to get permission to set labels on issues? I'd like to be able to tag issues as pre-release problem, for example. (And PRs as WIP or not.)

**Comment by asvitkine** [comment]
I'll investigate more tonight, but also seems like there might just be some flakiness with this. I synced to 2.0.16769 (which is higher than a prerelease build of 16749 I have), and it did not exhibit the issue. But 16749 does. So either it's flaky, or there's something else going on - like a revert/reland of the bug.

**Comment by asvitkine** [comment]
Looks like the cause is #5416. Investigating the problem.

**Comment by DanVanAtta** [comment]
@asvitkine re: label permissions -  https://github.com/triplea-game/triplea/issues/5711

**Comment by asvitkine** [comment]
So with the fix, I think we're back to the same behavior as 1.9.

However, that behavior is not correct. For example, trying to load 3 infantry and 2 tanks onto 1 transport results in only 1 tank loaded, due to the algorithm as it stands (it sorts the units and tries to find tail sublists that work - which ends up being 1 tank only). This is the same as 1.9.

This can be improved by just using the TransportUtils.mapTransports() and getting the units that can be loaded via that. So I plan to add that improvement as a follow up along with test coverage.
