### ISSUE TITLE
New Triage Permission in Github

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5711]
Looks like Github added some new permission levels: https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization

Of note, '**triage**', which should allow people to label issues without giving write permissions. I updated the 'committers' team to have 'triage' permission, so @triplea-game/devs   can now add/remove labels.

*edit* Getting tired here, correction on the team, it's the 'dev' team that have been upgraded to 'triage' from read

**Comment by RoiEXLab** [comment]
👍
