### ISSUE TITLE
Map downloads are complete options interchanged

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#572]
When you are downloading new Maps, you are prompted to decide wether you want to download more maps with the following message: 

> Map downloads are complete, would you like to continue downloading more maps?

But when pressing Yes, the window closes instead of staying open - when pressing no it stays open instead of getting closed.

I don't understand the logic behind SwingComponents.prompUser() but I would recommend using  a if(JOptionPane.showMessageDialog()== JOptionPane.YES_OPTION){} instead.

**Comment by DanVanAtta** [comment]
That was fixed once, an auto-merge reverted that. Also notice too that the download maps button is in the main button once again and the change to move it was also lost. We'll need to fix that problem once more..

**Comment by DanVanAtta** [comment]
Actually, the fixes are pending a PR.
