### ISSUE TITLE
Horizontal-Scrolling should work

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#574]
When playing a game, you are able to scroll nort/south using your mouse wheel.
Some newer mouses have the ability to tilt the mouse wheel sideways. This should make the map scroll west/east

**Comment by DanVanAtta** [comment]
I took a quick look at that functionality. It looks like Swing is too old of a library to support that, only does north / south scrolling. If you find a way to support it, I would be very eager to see it added. The code that does the scrolling would not be too hard to modify to handle the left right scroll, but again, Swing is too old to support it.

**Comment by RoiEXLab** [comment]
OK I'll try to find a way...

**Comment by RoiEXLab** [comment]
Ok you're right, that SWING does not support Sideway scrolling the way you'd expect...
There is a work around for this using an AdjustmentListener on the JScrollPane's horizontal scroll bar.
If the scrollbar could be hidden in some way that could be the solution.

**Comment by RoiEXLab** [comment]
This would be possible when some Progress in #611 is done using a ScrollPane Hvaluechanged listener

**Comment by ron-murhammer** [comment]
I think we should probably just close this for now until we make significant progress on JavaFX or some other framework that would support it.

**Comment by RoiEXLab** [comment]
After some testing I know now, that a "real" JavaFX Application is needed in order to recieve sideway scrolling events...
