### ISSUE TITLE
Increased installer download size / triplea.jar size

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#5755]
Starting from 2.0.17295 I noticed an increased size of the installers, for example the Windows64-installer increased from 66 MB to 86 MB.
The "culprit" appears to be the triplea-game.jar file inside the bin-directory, that now has a size of 58 MB instead of about 18 MB before.

What happened?

**Comment by RoiEXLab** [comment]
#5741 added javafx.web to the dependencies, which is being used to "render" the HTML of the game notes in the alpha javafx-client.
I didn't realize it would increase the size by that much. I mean the 20MB aren't as bad per-se if this actually provides extra functionality, however currently this client is just experimental (even though I started working on it again), so we might want to consider creating an extra subproject for this, so we can ship the "normal" client without all the javafx stuff

**Comment by Cernelius** [comment]
Starting from 2.0.17295 I noticed an increased size of the installers, for example the Windows64-installer increased from 66 MB to 86 MB.
The "culprit" appears to be the triplea-game.jar file inside the bin-directory, that now has a size of 58 MB instead of about 18 MB before.
What happened?

The file increased of 40 MB but the total size only of 20 MB? So what did decrease of 20 MB? Just curious.

Maybe it is because I still remember the times when the TripleA download was huge, but, also since now my connection is better (and it always was fairly good), I would not even notice 40 MB of difference, as it downloads in seconds anyways.

**Comment by RoiEXLab** [comment]
> The file increased of 40 MB but the total size only of 20 MB? So what did decrease of 20 MB? Just curious.

I assume that's due to the compression applied to the installer

**Comment by Cernelius** [comment]
I also wonder how much decompressing slows down the installation, since, at least for me, installing takes more time than downloading. I mean confronting the gain in download time of compression against the loss in installation time of the same, for a terminal and connection. I've no clue, maybe decompression time is irrelevant.

**Comment by RoiEXLab** [comment]
I doubt that compression is the slow part in your case. Compression algorithms are pretty fast these days.
I think the slow part is probably the copying of all the assets

**Comment by panther2** [comment]
@RoiEXLab I would welcome a smaller installer size/a separate project, as downloading from Github - despite my fast internet connection -  is quite slow compared to downloads from other sources. And considering the fact that I download and update at least once or twice a day it does make some difference.

**Comment by Cernelius** [comment]
Just for info, I just downloaded 2.0.17308 for Windows 64 bit and it took 5 or 6 seconds.

**Comment by panther2** [comment]
Nice, this is my average Github-download speed:
![download](https://user-images.githubusercontent.com/20812775/71478487-3c912180-27f0-11ea-8e1a-64aaa3e9cc79.PNG)

Downloads from other sources usually are at least 4-5 MB/sec.

**Comment by RoiEXLab** [comment]
@panther2 I feel ya, it's the same for me ^^
It's interesting though, it seems to be an issue with GitHub and certain ISPs from what I was able to google.

**Comment by DanVanAtta** [comment]
@RoiEXLab if I understand right, the goal here is to create a unique installer for JavaFX?

What if we, as an alternative, put the JavaFX dependencies on a new branch for 2.0, then once we have a 2.0 release done, we immediately cut a 3.0 that moves to JavaFX?

**Comment by DanVanAtta** [comment]
We could also just eat the download cost and try to go to JavaFX directly now and not bother with the component removal as well, as a third option.

**Comment by RoiEXLab** [comment]
> @RoiEXLab if I understand right, the goal here is to create a unique installer for JavaFX?

Yes, this is one option.

> What if we, as an alternative, put the JavaFX dependencies on a new branch for 2.0, then once we have a 2.0 release done, we immediately cut a 3.0 that moves to JavaFX?

It's not as easy as this sounds, for a lot of UI changes I have to make small adjustments to the current code (from visibility changes to small refactorings), so the merge conflicts could become annoying

> We could also just eat the download cost and try to go to JavaFX directly now and not bother with the component removal as well, as a third option.

What exactly do you mean with "go to JavaFX directly now"?

**Comment by DanVanAtta** [comment]
To hopefully clarify some options:
1) different installer
2) disable/roll-out all javafx, cut the 2.0 branch, then immediately revert after the 2.0 branch is cut to restore Javafx.
3) We cut the 2.0 branch, bite the bullet on file size, and we just start work and launching with the JavaFX UI

**Comment by DanVanAtta** [comment]
Do we have immediate action items that we can embark on, or is this a long-term fix that we are looking at here?

**Comment by DanVanAtta** [comment]
https://github.com/triplea-game/triplea/issues/5973 should address this. Eventually we'll have a second installer with the JavaFX loading screens, it will again be larger size in size as it will have additional bundled assets. We will need to address the increased installer size at that time

**Comment by RoiEXLab** [comment]
@DanVanAtta Unfortunately it seems like pack200 doesn't work like at all.
When looking at https://travis-ci.org/triplea-game/triplea/jobs/657867570?utm_medium=notification&utm_source=github_status it becomes clear that none of our classes is compressed using pack200 so we could as well just drop it.

The installer size is now some healthy 60 MBs which should be an improvement
