### ISSUE TITLE
Objective panel doesn't wrap any more in 2.0

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#5792]
**How can the problem be recreated?**
Open up a map with National Objectives. e.g. Global 1940 but v3 should work too
Only one line is displayed for the national objectives in the Objective panel. Previously, as many lines as needed were shown.

**When the problem is fixed, what should have happened instead?**
Objectives should be visible without oversizing the panel.

**Which Engine Version are you using?** 
2.0.17351

**Expected behavior**

Should be as it was in 1.9 - If the objective doesn't fit on the line, it should wrap to the next one.

**Screenshots** 
1.9 below
![Screenshot from 2019-12-30 18-47-47](https://user-images.githubusercontent.com/20733860/71572805-fe1f9d80-2b34-11ea-9697-f095262035b1.png)

2.0 below
![Screenshot from 2019-12-30 18-47-54](https://user-images.githubusercontent.com/20733860/71572820-0c6db980-2b35-11ea-8930-e3c96eabd776.png)

**Zipped Save Game**

**Comment by DanVanAtta** [comment]
@simon33-2 I'm seeing wrapping (World War II global 1940 Original):
![Screenshot from 2020-01-19 16-14-54](https://user-images.githubusercontent.com/12397753/72691034-e2c20580-3ad6-11ea-9701-8e15bfea6891.png)

Is the behavior you're seeing consistent? Could you be more precise how you're hitting this scenario. Are there scrollbars?

**Comment by ron-murhammer** [comment]
I tried reproducing this as well and couldn't either.

**Comment by simon33-2** [comment]
Sorry I haven't been on for a while but I've tried in a few different ways to reproduce it on 2-17884 and all of them worked. I notice you're using a different UI Look and Feel to me. I tried changing that from SubstanceGraphite to Metal, Nimbus, Motif (IIRC) and in all cases I could reproduce the problem. 

Also tried using Windows x64 instead of Linux.

What UI Look and feel are you using that you can't see the problem?

**Comment by DanVanAtta** [comment]
@simon33-2 : Confirming you meant "worked" and not "did not work"

> Sorry I haven't been on for a while but I've tried in a few different ways to reproduce it on 2-17884 and all of them worked.

If so, this is somehow no longer happening, or are you still seeing this problem?

**Comment by simon33-2** [comment]
I mean I'm still seeing the problem. Attempts to reproduce were successful is what I was saying.

**Comment by DanVanAtta** [comment]
@simon33-2 which OS are you using?

**Comment by DanVanAtta** [comment]
@simon33-2 tried metal, nimbus, motif, and a number of substance L&F's, none reproduced (linux).

@simon33-2 which OS and L&F are you using that reproduces the problem? When the game launches, is the 'objectives' tab the first one selected?

**Comment by DanVanAtta** [comment]
@simon33-2 one more question, when you try to shrink the size of the right hand panel, are you able to decrease it's size and see wrapping? do you see scrollbars, or does the text create a minimum width?

**Comment by DanVanAtta** [comment]
@ron-murhammer do you know who/which forum post this same issue came up in? We could really use more info on how to repro.

**Comment by ron-murhammer** [comment]
Yeah, I believe its here: https://forums.triplea-game.org/topic/105/ai-development-discussion-and-feedback/232

I'm about 90% sure it has to do with Mac OS since I don't ubernaut is on that as well. That or its a common L&F that Mac OS users choose.

**Comment by doctored** [comment]
yeah, i can confirm that same behavior on mac. i am ubernaut on other places but someone got before me here. :P

**Comment by DanVanAtta** [comment]
@doctored a few questions for you if you would:

(1) Which Look and Feel (L&F) are you using? 


You can get to L&F through the settings menu:
- launch game
- engine preferences
- UI Theme tab

You can also access the settings while in-game:
- game menu
- engine settings menu
- UI Theme tab

(IF changing in game, could be worthwhile to resize the the right hand menu bar to help force re-rendering).

(2) Does it matter which L&F that you use, do you see this behavior no matter which one is selected?

(3) If you resize the right hand menu bar, what is the behavior? Does it give you scrollbars, does it force a minimum width, does the text start to wrap?

**Comment by doctored** [comment]
hmm, seems to be working for me now actually tried a few things cannot replicate the objectives descriptions not wrapping in the sidebar under version 2.0.18171

not sure what the previous build i was using but i def saw it before.

**Comment by DanVanAtta** [comment]
I'd be more comfortable if we knew exactly what the problem was, but that is good news!

Thanks for jumping in here @doctored, please let us know if you see any other oddities (none of the dev's currently have reliable access to a Mac OS system).

**Comment by doctored** [comment]
will do it's on my list to test the revised ai soon. :)

**Comment by prastle** [comment]
@doctored if you create an account on the new unstable lobby I can now add you as a mod (as ubernaut?) so you do the mac testing directly live.
