### ISSUE TITLE
Version 13066 has major problems

### ISSUE THREAD

**Issue by RogerCooper** [triplea-game/triplea#5835]
This version gives an immediate error on running any scenario. The menu does not appear on the top of the screen.

Jan 09, 2020 10:20:36 PM games.strategy.engine.framework.GameRunner lambda$start$0
SEVERE: No enum constant games.strategy.triplea.ui.screen.UnitsDrawer.UnitFlagDrawMode.LARGE_FLAG
java.lang.IllegalArgumentException: No enum constant games.strategy.triplea.ui.screen.UnitsDrawer.UnitFlagDrawMode.LARGE_FLAG
	at java.lang.Enum.valueOf(Unknown Source)
	at games.strategy.triplea.ui.menubar.ViewMenu.addUnitNationDrawMenu(ViewMenu.java:478)
	at games.strategy.triplea.ui.menubar.ViewMenu.<init>(ViewMenu.java:80)
	at games.strategy.triplea.ui.menubar.TripleAMenuBar.<init>(TripleAMenuBar.java:36)
	at games.strategy.triplea.ui.TripleAFrame.lambda$new$4(TripleAFrame.java:276)

**Comment by DanVanAtta** [comment]
Thanks for the error report. As a workaround, see if you can load the latest release, turn off flags, then try again on 13066.

Long term we should catch the 'enum.valueOf' error for unrecognized type and default to none.

**Comment by DanVanAtta** [comment]
Ah, had latest vs prerelease version mixed.

@RogerCooper, please see: https://forums.triplea-game.org/topic/1531/fixed-menu-absent-new-bug-in-old-version

**Comment by DanVanAtta** [comment]
Specifically this comment: https://forums.triplea-game.org/topic/1531/fixed-menu-absent-new-bug-in-old-version/6
