### ISSUE TITLE
Websocket Design Update - Consolidation & Unidirectional communication (websocket listeners only)

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5845]
Websocket connectivity was clean, now I think it's overly abstracted and hard to understand. Before moving on it would make sense to clean this up so we have clean API's for it all once again.

I'm thinking:
1. Enforce websocket communication to be unidirectional, ie: server -> client only. All client->server communication would be standard http calls.
  Benefits:
  - The 'listener' pattern would be the only one
  - We could drop ClientMessageEnvelope, serialization/deserialization of messages would be more automatic as dropwizard and feign would be doing that for us. Overall this simplifies the messaging protocol.
  Cost:
  - Can no longer do point-to-point websocket communication. AFAIK this is only really nice for remote server shutdown messages. We can almost always fake this communication type by having clients check that broadcasted messages are to them and ignore the ones which are for other clients.

2. Consolidate websocket endpoints and clients. Considering any client receives all messages from server, this should simlify very nearly identical code on client and server side. This should also make race conditions easier to reason about and much harder to avoid (which recently caused some very large headaches: https://github.com/triplea-game/triplea/pull/5786)

**Comment by RoiEXLab** [comment]
Good considerations, I do see some potential long term problems though:
> All client->server communication would be standard http calls.

Should work good enough for all existing lobby-functionality, but if we ever want to migrate the in-game communications to HTTP/websocket we might run into the following problems:
- The overhead might be pretty high, if we send a full HTTP-request with headers and everything the game experience might not be that smooth in cases where combat is done for example, and people just spam next if their units are all the same
- Request Ordering: If everything is done by using requests we'd have to implement a system that guarantees a consistent command order. Either client-side by waiting before sending each request until the previous request (which makes things slow on high-latency connections), or server-side by buffering any requests that might come out-of-order (which makes things ugly).

So we could of course try to deal with this problem when it actually becomes one, but I thought we might as well consider it now

**Comment by DanVanAtta** [comment]
AFAIK websocket is susceptible to packet drops and out of order message same as standard http. Is that not the case?

**Comment by RoiEXLab** [comment]
Websocket is just a fancy TCP wrapper, so no:
https://stackoverflow.com/a/11809503

Of course if all HTTP requests are sent over the same TCP socket (which is the default behaviour in HTTP 2), out-of-order from the client side is not a problem, but there's no guarantee that the same tcp socket will be re-used, it's probably up to the HTTP client library on how to handle this.

**Comment by DanVanAtta** [comment]
Resurrecting this as I'm making some progress towards this task.

I hope updates in this direction can make it easy to fix 'ghost chatters': https://github.com/triplea-game/triplea/issues/6037

Some updates:
- I don't think unidirectional communication is sustainable. Standard HTTP endpoints give us:
  -  'free' routing
  -  unmarshalling from JSON to java objects
  - access controls

I suspect eventually we're going to want bi-directional communication. To get there I think we just need to improve the system for message routing and marshalling. 

The biggest and most compelling item I see though is associating websocket sessions with http requests. It's a bit at the heart of the ghost player bug and even hosted games not disconnecting. The session disconnect is very reliable, but it's not triggering anything because we have not associated sessions to the initial http request that joined a chatter to lobby or joined a game to the lobby.

So, I think we should embrace bi-directionalism, to this extent:
- (1) working to wrap http communication behind a facade, bit of a strangle pattern to convert various http calls to websocket
- (2) reduce the interface between the code and http communication. Notably I think it makes sense to have 2 websocket endpoints, one intended for players to connect to, and a second for games to connect to. That implies we'd then have just two clients to communicate to the lobby, one used by games themselves (ie: lobby watcher thread to send updates on player counts, game status, etc), and a second for players to use.
- (3) simplify websocket listener mechanism. Instead of adding 'bundles' of listeners how we do now, driven from an enum configuration, I'm thinking the generic websocket connection or server connection should be made available and we can add single listeners to it. We certainly off the deep end with a very abstract and DRY mechanism for adding listeners, at the end of the day it looks very hard to replicate and extend - it's quite complex. I'm hoping to then cut out a lot of our middle-ware and make this simpler for both server and client.

At the end of this:
- we'll have a more extensible model. Hopefully something we'd want to start using for game hosts themselves and we can start replacing peer-to-peer network calls. If we do it right, it'll be easy to get to a place where we have stateless bots that act as pure network proxy servers. (That would be HUGE, it'd reduce our monthly operating costs by 80% and would drastically simplify the code as we could remove all the "headless" model variant. From there additional simplifications would become much easier. The benefits go on, we could have all players hosting easily and transparently using bots servers.)
- session removal will be easier to act on, we could de-list games and players when they disconnect this way, it would be reliable and low overhead.

**Comment by RoiEXLab** [comment]
@DanVanAtta Sounds like a reasonable approach.
Currently I can't really wrap my head around how we would hide the different transport methods behind a single api, but I'm convinced there's a good way to achieve that.

> [...] we could remove all the "headless" model variant [...]

I agree with the rest, but I think we need to keep a version for tournaments to ensure the host doesn't use a rigged client.
At this point the headless implementation should be basically a no-op UI, no no real development overhead.
