### ISSUE TITLE
Ctrl+Z Double Tab Yields IllegalArgumentException

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5847]
**How can the problem be recreated?**
- Press ctrl+z once to hide the action panel.
- Press ctrl+z again
- Observe IllegalArgumentException popup

**When the problem is fixed, what should have happened instead?**
- Should undo previous 'ctrl+z' behavior and actions panel becomes visible again.

**Which Engine Version are you using?** 
509508e43830df5a2194cb94c529d2b16e5d0338

**StackTrace**
```
java.lang.IllegalArgumentException: proportional location must be between 0.0 and 1.0.
	at java.desktop/javax.swing.JSplitPane.setDividerLocation(JSplitPane.java:759)
	at games.strategy.triplea.ui.TripleAFrame.lambda$get$9(TripleAFrame.java:723)
	at org.triplea.swing.SwingComponents.lambda$addKeyBinding$5(SwingComponents.java:491)
	at org.triplea.swing.SwingAction$2.actionPerformed(SwingAction.java:84)
	at java.desktop/javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1810)
```

**Comment by DanVanAtta** [comment]
Perhaps we should just remove this hotkey? Is it really useful? @ron-murhammer thoughts?

AFAIK this hotkey is undocumented in the UI. We might have it buried in our 'help' text, but IMO that does not really count when it comes to usability of ctrl+z.

**Comment by RoiEXLab** [comment]
I had a quick look at this issue but haven't had the time to submit a PR.
Basically in `TripleAFrame:726`, `1.0` needs to be replaced with `gameCenterPanel.getMaximumDividerLocation()`, or alternatively the ternary operator needs to be unwrapped into a full if else statement.
The problem is that there are 2 overloads of the set divider method.
The one that accepts a double requires this value to be between 1 and 0, the one that accepts an Integer has no such limitation and interprets the value as pixels rather than a ratio.

**Comment by RoiEXLab** [comment]
I have no idea why this only happens when pressing it twice though

**Comment by DanVanAtta** [comment]
On the second instance, the action panel is collapsed, I suspect that is the issue. Are we sure we need to support the hotkey before 'fixing' this?

**Comment by DanVanAtta** [comment]
My vote is to remove the hotkey binding:
- there is a UI control to do this
- the functionality to collapse the right hand bar AFAIK is not frequently used, it is not a very good candidate for a hotkey
- ctrl+z is not discoverable without RTFM (sub-par UX)

As such, the ROI for a fix seems pretty low here.

@RoiEXLab , @ron-murhammer  would you agree?

**Comment by DanVanAtta** [comment]
Ah, should also mention, we are pretty short on hotkeys, many (maybe too many) are mapped. I'd rather see 'ctrl-z' being mapped to an undo of the last moved unit.

**Comment by ron-murhammer** [comment]
Yeah, I'm fine removing that hotkey as I agree ctrl+z probably isn't a good choice and isn't used much anyways.

**Comment by RoiEXLab** [comment]
I didn't even know this hotkey existed until this issue, so 🤷‍♂ 

In case anyone wants to keep it, we could always revert the upcoming changes and go for my fixx suggestion
