### ISSUE TITLE
Show Map Only Broken / Irreversible

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5860]
**How can the problem be recreated?**

1. Launch Triplea
2. Start a local game
3. Select All AI's
4. Toggle menu: view > show map only
5. Toggle menu: view > show current game
6. Notice that the map window blanks out

- Clicking 'show history' or 'show current game' stays with blanked out map
- Clicking 'show map only' again after cycling through 'show current game' sometimes restores the map-only view.
- There does not seem any way to get the action tabs with map or map with history to render properly once again.

**When the problem is fixed, what should have happened instead?**
- Map should continue to render properly.
- Should we continue to support the 'show map only feature in the game menu?

**Which Engine Version are you using?** 
2.0 latest @ 7d3b57fd7f4ea977f45e235433b661fdc8896760

**Screenshots** 
![Screenshot from 2020-01-19 22-18-22](https://user-images.githubusercontent.com/12397753/72703348-3a2d9900-3b0a-11ea-9663-d4943fae30d8.png)

**Comment by DanVanAtta** [comment]
Both the left and right sidebars can be collapsed manually. The feature also suffers from usability as it's not obvious this would be an AI-only feature.  ROI for fixing this is very low.

**Comment by Cernelius** [comment]
In all these years, I never realized this feature existed, or at least I cannot recall having ever used it, yet I always had it unclickable right under "Show history". First time I learn it becomes clickable only with all AI. I even wonder if this is intended at all?

There may be a user case for a feature like this to work, especially if not restricted to AI only game, to give a true full view, as collapsing the right bar while in Current Game still keeps a few pixels of collapsed bar, for clicking to reopening it, so it is not actually completely removing that bar, thus not actually truly giving you a full view.

As long as the AI only case, it may be good for showcasing the program, like letting all AI running in max map view, to upload a video of it (to YouTube or something).

By the way, it is in "Game", not in "View", unless the "Show current game" and following options have been recently moved to "View".

**Comment by DanVanAtta** [comment]
> I even wonder if this is intended at all?

**Comment by DanVanAtta** [comment]
Indeed the option is in game.

The feature is pretty old. It's a copy/paste too. 

While saving a few pixels would give a true full screen view, the ROI is not there. Fixing this will probably be 3-20+ hours of work. Furthermore, the feature adds complication to 'show history' and 'show current game', both of which are already difficult to work with and has a material impact for making 'ctlr+h' to turn on/off history.

**Comment by DanVanAtta** [comment]
We need to be careful about what features are in the game. Each feature is an ongoing cost, it makes other features more expensive to both build and maintain. In a sense, the more features you have, the less valuable they all become. The valuable ones become harder to find, are harder to build, and are more difficult to keep working.
