### ISSUE TITLE
how and where to push releases

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#59]
A how-to push release page on the wiki could be useful. Particularly if time goes by and we forget how to do it. Part of the question is, where do we release, and how?

It looks like github-releases is a slick way to go. Keeps us in the git framework. Releases would then be available from: https://github.com/triplea-game/triplea/releases
 
There should be a way to tag and upload to the github-release. Those steps are what I'm thinking should belong in a wiki.

After that a next step would be to have Travis push automatically for us. PR #58 Adds Travis, these steps look to be roughly what we need to have Travis push builds for us: https://gist.github.com/vinceallenvince/a7611b10f84e61eebdcc

**Comment by veqryn** [comment]
I do plan to make a wiki on how to do full releases, hopefully tomorrow if I have time.
We can look into github releases a month or so after the next release.  I don't want to introduce our users to something completely just yet, and I do want to get this next release out with minimum fuss.

**Comment by DanVanAtta** [comment]
Thanks for the wiki: https://github.com/triplea-game/triplea/wiki/How-To-Release (note, name of page might be changed as we organize the wiki).

Closing, only item left to discuss would be to use github-releases. Seems like there is lack of labor to do that, so I think it would more appropriate to submit a pull request with that work rather than discuss it here. Since using github releases would not take away from anything, would just add a valuable step to the automation process,  let's worry about when someone is inclined to work on it.
