### ISSUE TITLE
Changing The Recognition of Mapskins (2.0.17884)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#5901]
Instead of however it is currently done, I suggest mapskins being added to the original map menu, while playing, under only the conditions:

**The mapskin file name name starts exactly as the original map name, immediately followed by the "-" character, and have the word "skin" anywhere after the map name.**

**Comment by DanVanAtta** [comment]
What problem are we trying to solve or improve? 
This seems like a feature request and would be more properly reported to forums.

Long term, I'm not sure if this is the direction we should go with magic naming of map names. I'd like to see us get to a place where maps are uploaded from in-game, likely that means that maps would receive a map ID value. We could then identify map skins through XML by referencing the map ID and would not rely on naming.

**Comment by Cernelius** [comment]
>What problem are we trying to solve or improve?

There are likely a number of them, but, not being a developer, I cannot exactly know how it currently works. The potentially highest impact one, I believe, is that if I make a mapskin for a map, any other maps that have that same name as the first part of their own name will use that mapskin too. For example, if I make a mapskin for `feudal_japan_warlords`, it will be available for `feudal_japan` too.

**Comment by Cernelius** [comment]
>Long term, I'm not sure if this is the direction we should go with magic naming of map names. I'd like to see us get to a place where maps are uploaded from in-game, likely that means that maps would receive a map ID value. We could then identify map skins through XML by referencing the map ID and would not rely on naming.

I approve of looking at the file name, as it is good that we force mapmakers to keep name consistency between a map and all its mapskins, but the recognition should be more precise than it currently is. Also, on the other side, disallowing the "-" character in maps folders names would help (this way mapskins must have the dash, while maps can never have it).

**Comment by DanVanAtta** [comment]
@Cernelius could you link the forum discussion relating to this?

Can you help clarify how often we see/run into the problems you have discussed, or are they more still just potential problems?

> as it is good that we force mapmakers to keep name consistency between a map and all its mapskins

I don't know if that is a good thing and not just one more thing to get wrong and makes map making just more error-prone and complicated. There are other solutions available that would be less error-prone

**Comment by DanVanAtta** [comment]
If we change the skin recognition as described, would we have to update all existing map skins, is this a backward compatible suggestion?

**Comment by Cernelius** [comment]
I don't think currently the mapskins have any problems.

The only mapskins currently available in download list are:
`diplomacy-map_skin1`
`diplomacy-map_skin2`
`diplomacy-map_skin3`
`middle_earth-map_skin2`
`napoleonic_empires-topographical_map_skin`
`new_world_order-skin_gudkarma_1`
`new_world_order-skin_pulicat_1`
`new_world_order-skin_sieg_2`
`world_war_ii_global-battlemap_skin`

So, my preferred name is the one used for the map skin of WWII Global, that is:
`<map name>-<skin name>_skin`

So, for example:
`big_world-small_skin`

However I see that, by the current practice, we have the word "skin" after the dash or at the end of the name or after the dash but before the end of the name. The name "map" sometimes figures too, sometimes no. Every time the name "map" is present, we have the extended name "map_skin" (in my opinion, redundant). As a curiosity, we accidentaly have "map_skin" also for the WWII Global skin, though this is just the result of having the "battlemap" name (a reference to another program), followed by underscore separation, then "skin".

So, if we don't want to change any mapskin names and keep them all working, my suggestion should be reduced to this:

**The mapskin file name name starts exactly as the original map name, immediately followed by the "-" character, and have the word "skin" anywhere after the map name.**

According to this discussion:
https://forums.triplea-game.org/topic/1627/how-to-delete-maps-from-triplea-maps-on-git/5

>These are the rules for finding a map skin based on a map name:
>```
>    return mapSkin.startsWith(mapName)
>        && mapSkin.toLowerCase().contains("skin")
>        && mapSkin.contains("-")
>        && !mapSkin.endsWith("properties")
>```

So, the only matter would be changing the "-" requirement from containing it anywhere to have it immediately after the "mapName". Basically the requirement would be to start with "mapName-".

This would solve both the potential problems of seeing a map as a mapskin if the map already has a dash and using a mapskin for another map having a longer name that start the same, and would also formalize the currently followed practice of having the dash actually immediately after the map name.

I maintain that I would prefer the "skin" part being mandatory either immediately after the dash or at the end of the name (not a clear preference for either), but this would not be compatible with the current naming.

Updating the first post.

**Comment by Cernelius** [comment]
If I can argue for a moment on the problem report vs feature request matter, I would say this is a "problem", if only a "potential" one.

For example, right now there are 3 games going on in the lobby for each of "Big World 2 : Balance of Power" and "Domination 1914 No Man's Land". If anyone would make any mapskins for these maps, the other maps they originated from would get those mapskins available too, except that the view will fail to display properly (and, anyways, they should not be given, as they are mapskins for other maps).

![20200301_01](https://user-images.githubusercontent.com/19562310/75616672-69e1af00-5b54-11ea-864e-34b1085770d3.png)

Otherwise, I would have posted it in the forum.

**Comment by DanVanAtta** [comment]
My thinking on this topic remains:
- best to not encode map types and map relations through name
- forward looking, map name will be less important and more ephermeral when maps are stored in a database and not primarily as files
- would prefer to see the relationship between maps be encoded as map attributes, eg:
```
<map_type>skin</map_type>
<map_id>1234</map_id>
```

**Comment by DanVanAtta** [comment]
@Cernelius I agree there is a problem here.
On the other hand, 3.0 I'm planning to have a new system for finding map components. When we re-design how that is done, we can/should plan to address finding skins as part of that. In the meantime, I don't think this is actually actionable. The ROI to make this update, retro-fit any clashing skins, update and test the logic is a lot of effort to resolve an issue that so far does not really have that much of an impact.
