### ISSUE TITLE
Failed to retrieve Token. 

### ISSUE THREAD

**Issue by redanto** [triplea-game/triplea#5922]
**How can the problem be recreated?**
I am unable to post game summary to the forum.  When I test the forum I get the following message
Failed to retrieve Token. Code: not authorised Message: A valid login session was not found. Please log in and try again.

Here are the details

Feb 09, 2020 8:50:21 PM games.strategy.engine.pbem.TripleAForumPoster postTurnSummary
SEVERE: Failed to post game to forum
java.lang.IllegalStateException: Failed to retrieve Token. Code: not-authorised Message: A valid login session was not found. Please log in and try again.
	at games.strategy.engine.pbem.TripleAForumPoster.getToken(TripleAForumPoster.java:150)
	at games.strategy.engine.pbem.TripleAForumPoster.postTurnSummary(TripleAForumPoster.java:50)
	at games.strategy.engine.framework.startup.ui.editors.ForumPosterEditor.lambda$testForum$4(ForumPosterEditor.java:143)
	at java.lang.Thread.run(Thread.java:748)

Feb 09, 2020 8:56:39 PM games.strategy.engine.pbem.TripleAForumPoster postTurnSummary
SEVERE: Failed to post game to forum
java.lang.IllegalStateException: Failed to retrieve Token. Code: not-authorised Message: A valid login session was not found. Please log in and try again.
	at games.strategy.engine.pbem.TripleAForumPoster.getToken(TripleAForumPoster.java:150)
	at games.strategy.engine.pbem.TripleAForumPoster.postTurnSummary(TripleAForumPoster.java:50)
	at games.strategy.engine.framework.startup.ui.editors.ForumPosterEditor.lambda$testForum$4(ForumPosterEditor.java:143)
	at java.lang.Thread.run(Thread.java:748)

Feb 09, 2020 9:01:55 PM games.strategy.engine.pbem.TripleAForumPoster postTurnSummary
SEVERE: Failed to post game to forum
java.lang.IllegalStateException: Failed to retrieve Token. Code: not-authorised Message: A valid login session was not found. Please log in and try again.
	at games.strategy.engine.pbem.TripleAForumPoster.getToken(TripleAForumPoster.java:150)
	at games.strategy.engine.pbem.TripleAForumPoster.postTurnSummary(TripleAForumPoster.java:50)
	at games.strategy.engine.framework.startup.ui.editors.ForumPosterEditor.lambda$testForum$4(ForumPosterEditor.java:143)
	at java.lang.Thread.run(Thread.java:748)

**When the problem is fixed, what should have happened instead?**

**Which Engine Version are you using?** 

**Screenshots** 

**Zipped Save Game**

**Comment by panther2** [comment]
Please ask for support in the respective support category of the affected forum, so either 

https://www.axisandallies.org/forums/category/28/triplea-support
or
https://forums.triplea-game.org/category/10/player-help

Thank you.

**Comment by RoiEXLab** [comment]
This doesn't seem to be a common issue, so it's likely a problem on your end.
Did you make sure to use your username (not email) and the correct password?

**Comment by panther2** [comment]
@RoiEXLab He has already fixed that, as I noticed successful postings on the forum.

**Comment by DanVanAtta** [comment]
Do we know what the fix was? If this is not an error, we need to update the
code to not allow for the error report and make the error text clear what
the user should do. As is, the code handles this as if it were a game
crash, seemingly then an error handling bug

**Comment by redanto** [comment]
Hi Dan,  My apologies.  It was what I call an ID10t error.  I had the wrong password in the forum and that was the issue.   Just a stupid mistake on my part.   


-----Original Message-----

**Comment by DanVanAtta** [comment]
Thank you for the context.

The software should have been more clear that the password was likely incorrect and disallow the error report upload. Whenever there is an error report upload, it is because the software thinks something crashed.

**Comment by DanVanAtta** [comment]
Re-opening, the software should distinguish between standard error scenarios and those where the server is for example, unavailable.

**Comment by DanVanAtta** [comment]
Desired action item, better/adequate error handling to tell user that auth failed and what that implies. Should not be a 'severe' logging. A successful test of a fix would have a clean error message on an incorrect password and a more verbose/scary error message if the forum is down or the API request is refused.

**Comment by DanVanAtta** [comment]
Error messaging is improved in: https://github.com/triplea-game/triplea/pull/6252
