### ISSUE TITLE
Game Launch Navigation

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#5965]
Due to the recent changes in #5954 I thought I'd share my current plan for the navigation model for JavaFX:
Squares Represent Screens, Circles Actions.
The lines in between them without arrows should be obvious, the arrows represent an action that happens within the screen (without technically leaving it).
I it's clear enough.
![ScreenModel](https://user-images.githubusercontent.com/8350879/75041806-98f58200-54bd-11ea-83f7-8d7a967ef1e4.png)

As you can see I plan on making PbF/PbEM and dice servers an opt-in feature for any kind of game-mode, rather than a different "game-mode".
I hope that this way we can reduce a lot of code for game launching and we just have to implement small screens that slightly modify the `GameData` object being created by the game-loader.

Note that there is a small inaccuracy in my graphic when it comes to the "Player Selection Screen". Obviously this Screen needs to be slightly different when playing over the network:
We need:
1. A chat area
2. An actual player/node assignment
3. A way to change the map without actually losing the connection to the game host. Currently the existing "Map Selection Screen" simply creates a GameData object based on the users selection and I'm not sure how to make it that it optionally passes through an object responsible for network communication 🤔 

I'd be happy to hear your opinion on this. Thoughts? Questions? Concerns?

**Comment by DanVanAtta** [comment]
Like the diagram, some initial thoughts:
- we may want to put 'load save game' in the first selection row. Loading a save game could land a person lower on the diagram to player selection screen with settings and map filled in. Notably, we probably don't want to go through a map selection screen to then load a save game.

**Comment by RoiEXLab** [comment]
@DanVanAtta I'm not sure if I made that clear enough, but my idea was to make savegame loading part of the map selection screen, so that you can either choose a map to start a new game, or press a button somewhere on the side to load a savegame.
But in the end it shouldn't really matter to the player selection screen how the GameData object was created, it should only matter that it exists and that it can pre-fill fields if the values are available.

**Comment by ssoloff** [comment]
> As you can see I plan on making PbF/PbEM and dice servers an opt-in feature for any kind of game-mode, rather than a different "game-mode".

I think that's a good idea.  IIRC, this data is already a kind of "attachment" to the overall `GameData` that can be added/removed/changed at the start of game play.  So reflecting that in the UI is probably a step in the right direction.

**Comment by ron-murhammer** [comment]
@RoiEXLab What's the difference between "start local game", "host game", and "connect to game" actions? I generally agree with the direction you are going with this and have PBF, PBEM, and dice server as options for any game.

**Comment by RoiEXLab** [comment]
"Start local game" creates a game local to your computer, no network involved.
"Host game" does the same, only that it opens a TCP socket so that other clients can connect.
"Connect to game" does connect to a remote game, basically the same thing happens when connecting to a hosted game on lobby.

**Comment by ron-murhammer** [comment]
@RoiEXLab Ok. I wonder if we need to have them spell it out a bit more like "Host Network Game" and "Connect to Network Game". Or maybe just tooltips.

**Comment by RoiEXLab** [comment]
The good thing is that we can remove 2 of the currently existing buttons, so that frees up a lot of space for things like that

**Comment by DanVanAtta** [comment]
@RoiEXLab it might help to have a similar diagram for the full set of launching screens.
I'd personally like to broaden the conversation a bit. I'm not sure if we really need an 'about' tab, second, we have a technical consideration of how we support preferences. AFAIK, once the game launches we'll only be able to support swing components (unless we can have the preferences menu open up a JFX window). Given that, we'll potentially have a preferences written in both swing and JFX for some time. The preferences window is the only component I can think of that is both rendered in the staging screens *and* in the game as well.

**Comment by DanVanAtta** [comment]
This is moot for a moment in the context of JavaFX: https://github.com/triplea-game/triplea/issues/6756

Though, I think we should update the game as-is to have the enhanced/better navigation. I'd like to continue discussing this topic in the context of the swing client.

**Comment by RoiEXLab** [comment]
@DanVanAtta I think my point of view should be clear, I created the illustration in the main post after all.
 Basically I think the main screen should have a big "Play" button where the "Game Selection Screen" I proposed in the original post should pop up.
For settings I can think of 2 variants:
1. We put a gear somewhere in a corner where users can change their settings
2. We put a smaller "Settings" button near the "Play" button

Map Creator or other Map Making related utility should be another button near the Play button. In the long run we should be able to fine tune this.

There will be a lot of free space on the main screen using this approach.
This free space could be the replacement (or addition) to the current lobby text. We put news, changelogs or other stuff that could be interesting there. There a lot more people will see it. We could even make it dependent on the game version to inform users of important issues a certain version has. ("Deletes all your data, sells your children on the black market, don't use!" etc.)

WDYT?

**Comment by DanVanAtta** [comment]
Morphing the current screen to move the 'play' options behind a play button makes a lot of sense. I think the 'download' maps button probably will then need to be added to the main screen and we'll want to be sure it's also present whenever selecting maps as well.

Implied in this as well is hiding the side-bar panel until the player has reached a "game staging" screen. 

Having a 'news text' is an interesting idea. I'd only be a bit afraid that we might let it go stale (perhaps an auto-kill of the message after 30 days would be useful). Beyond that, probably most important first to re-arrange and improve the game elements, then such an update would probably have its place.
