### ISSUE TITLE
Missing Hash Procedure on Account Creation

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#5985]
I just tried registering an account on the pre-release server and got this error message:
`Password not encoded properly, too short`.

I dug into the code and found out this check is supposed to verify that the password is actually a SHA-512 hash, and so obviously my "normal" password does not have the required 128 characters for the hash, which causes the error.
I checked the code further and noticed that the `PasswordBCrypter#hashPasswordWithSalt` is only available for the `http-server` module and thus can't be used client-side just before the request with the "unhashed" password is sent.
Furthermore I noticed that for the login procedure there's a mechanism that "upgrades" the password to a hash it if no such hash is available, but there's no such thing for account creation.
I'm not sure what your original intentions for this mechanism were @DanVanAtta, but it is pretty obvious that you seem to have missed to add a similar mechanism to account creation.

**Comment by DanVanAtta** [comment]
I might get to this soon, though unassigning for now (assignment indicates active work underway)

The check for hashed value would seem to be a miss, probably just needs to gdvremoved

**Comment by RoiEXLab** [comment]
@DanVanAtta I actually have a slightly different interpretation of the assignment.
I think the assignment should indicate who is expected to make the next move on the issue or pull Request.
So if someone else assigns you it means (in my opinion obviously) you are expected to answer a question or add some missing information to it and unassign yourself once that's done.
If you assign yourself however I'd agree with you that it means something along the lines of "I'm working on it".
I hope this clarifies why I assigned you.

**Comment by DanVanAtta** [comment]
Perhaps we should hash out/define what assignment means (maybe in another issue). IMO in the context of next move, the '@' metnoin seems sufficient and/or redundant. IMO it's most useful to indicate "this is the group of people who need to look at an issue or PR", that way others can skip over those items and save themselves time. It also avoids the assignment ping-pong that happens in PR. From another perspective, those without write permissions could not follow the process of "It is your move now" as they cannot assign issues. We should be careful to make our processes generally work with or without write permissions.

**Comment by DanVanAtta** [comment]
Meant to actually unassign from myself.. regardless, i'm taking a look at this now. As a general note, we should avoid assigning bugs to the 'bug author', it elides responsibility from reviewer, maintainers, and punishes someone from being productive, and really post-merge, the burden for bug fixes is the team with write permission (maintainers), or anyone else that can come along. Any time we can use the efforts of a random volunteer, it helps increase our capacity and avoids the horrible bottleneck that is on the maintainer team. The other thought of "oh, I didn't write this, someone else should fix it" is just passing the buck and slows us down. @RoiEXLab @ron-murhammer TL;DR, do not assign issues to the person we think introduced bugs.

**Comment by RoiEXLab** [comment]
Don't get me wrong, I'm not accusing you of introducing a bug. The only reason I assigned you is because you're probably the only person who truly understands the http-server code. (I checked if there was an easy fix for this, but I couldn't find one)

**Comment by RoiEXLab** [comment]
The idea being that for any further progress on this we require your expertise.
And at least in my opinion an assignment is a pretty good indicator for "person dependencies"

**Comment by DanVanAtta** [comment]
I certainly did introduce this problem :grin: 
'@' mentioning me was a good thing to do as I could suggest a fix here. Though, anyone else could have gone through the commit history/TODO comments, PRs, generally dug in and could have provided a fix at a greater cost.

A PR with a fix is up.

> I checked the code further and noticed that the PasswordBCrypter#hashPasswordWithSalt is only available for the http-server module and thus can't be used client-side just before the request with the "unhashed" password is sent.

Passwords are meant to be sent via plaintext. I forget where, but I tried to communicate pretty clearly that we could not send passwords hashed until we get rid f the legacy upgrade path. Once we get rid of the old md5 passwords completely, then we can hash passwords client side. There are  some TODOs about this in the code as well.

EG: PasswordBcryptor
```
  @Override
  public String apply(final String password) {
    // TODO: Md5-Deprecation remove hashing here, move to client-side
```

> Furthermore I noticed that for the login procedure there's a mechanism that "upgrades" the password to a hash it if no such hash is available, but there's no such thing for account creation.

The upgrade is server side for storage from md5 to bcrypt.

**Comment by DanVanAtta** [comment]
PS: good QA work @RoiEXLab finding out this was a problem :100:

**Comment by RoiEXLab** [comment]
@DanVanAtta Thanks, the thing is I ran into this Problem quite a while ago, but forgot to actually create an issue to adress this 😅

**Comment by DanVanAtta** [comment]
Fixed with: https://github.com/triplea-game/triplea/pull/5990
