### ISSUE TITLE
Remove ant "support"

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#601]
If I'm not completely wrong, ant is no longer really used in this project - the build.xml file doesn't even work for me.
It has been replaced with gradle.
If you have no objections, I will do a pull request removing all of the ant files...

**Comment by DanVanAtta** [comment]
In case we need to do a 'hotfix', @ron-murhammer  would be on the hook for it, and he has requeseted we keep the files around so he could do that. We haven't actually used gradle yet to do a release. The 1.8.0.9 version on github was uploaded by hand. After next release the unused stuff is planned to be deleted (others have also asked that it get deleted sooner too..)

**Comment by ron-murhammer** [comment]
@RoiEXLab We are holding off removing the ant build til we do a full release with gradle which should be soon.

**Comment by DanVanAtta** [comment]
removed: https://github.com/triplea-game/triplea/pull/1365
