### ISSUE TITLE
"IllegalStateException - Not all units present in" error on ww2 global 2nd e

### ISSUE THREAD

**Issue by asvitkine** [triplea-game/triplea#6011]
**How can the problem be recreated?**

This was on prerelease 2.0.18193.

I played a game on ww2 global 2nd e with myself, the host local player, playing as British and UK_Pacific and a networked player playing Americans and all other players set to Hard AI.

This error occurred multiple times on different AI player's turns (with different territories mentioned in the error). I believe when it occurred on China's turn, the result was that no battles happened and Chinese units stayed in Japanese territory without resolving battles.

Unfortunately, I did not capture a saved game and when I tried an all-AI game on the same map later, no error occurred.

This error occurred pretty early into the game (I think starting at end of Round 1 and persisting into Round 2 at which point we gave up playing on 2.0.18193 and restarted a new game on an older version - 2.0.16749 which went without any issues).

I did have "Beta features" enabled in my client, but I'm not sure if there were any relevant ones in the codebase. I believe the other player did not have this set but also got error messages.

**When the problem is fixed, what should have happened instead?**

No error messages.

**Which Engine Version are you using?** 

2.0.18193 prerelase

**Screenshots** 

I only captured the last one which was the most verbose but before this, similar errors kept popping up but that listed fewer units.

![Screen Shot 2020-03-03 at 7 03 30 PM](https://user-images.githubusercontent.com/17648/76092717-df52e280-5f8d-11ea-9add-af66865d50f4.png)

**Zipped Save Game**

Didn't save one. :(

**Comment by asvitkine** [comment]
Note: I likely don't have time to help with the investigation unfortunately, but the problem is pretty bad and I would consider it a 2.0 release blocker.

@DanVanAtta FYI

**Comment by Cernelius** [comment]
I cannot be sure, but I believe this is a very old bug that rarely happens, not anything prerelease only (unless now it happens not rarely).

**Comment by ron-murhammer** [comment]
@asvitkine Ok. Thanks for the report. If you are able to reproduce it again or see it happen and capture a save game please add that here.

This error usually means that somehow things got mixed up and the engine is trying to remove units from a territory that are no longer there. Unfortunately, there is almost no way to no why that happen and lots of places that could potentially cause it.

**Comment by DanVanAtta** [comment]
FWIW, the report error button works and would include a stack trace automatically.

Closing as it does not seem this is immediately actionable, but please do keep the error reports coming, it's a perfect habit to have to report-them-as-you-get-them.
