### ISSUE TITLE
SAXParseException Error

### ISSUE THREAD

**Issue by RuinChristmas** [triplea-game/triplea#602]
upgraded to 1387.  tried to play revised. Got this error

```
SAXParseException: game: World War II Revised, line: 798, column: 26, error: Element type "attatchmentList" must be declared.
SAXParseException: game: World War II Revised, line: 799, column: 154, error: Element type "attatchment" must be declared.
```
goes on for pages and pages of the same, ends with:

`SAXParseException: game: World War II Revised, line: 1763, column: 8, error: The content of element type "game" must match "(info,loader,triplea?,diceSides?,map,resourceList?,playerList,unitList?,relationshipTypes?,territoryEffectList?,gamePlay,production?,technology?,attachmentList?,initialize?,propertyList?)".`

**Comment by ron-murhammer** [comment]
@RuinChristmas This is due to some changes in the map XML we just map. We are going to have a separate map folder and this should be resolved in the latest pre-release.
