### ISSUE TITLE
Battle calc Freezes on 18289 Prerelease

### ISSUE THREAD

**Issue by beelee1** [triplea-game/triplea#6034]
**How can the problem be recreated?**

Was playing Oztea 1939 Global and when I'd click on the battle calc to advance the combat sometimes it'd freeze and I'd have to go to the bottom bar where my icons are and click on the triplea army dude again to get it to finish the battle. Before, in 13066, I'd just click on it and it'd advance.

Didn't happen on all battles but it did happen multiple times on different games. Usually German Player turn. 

**When the problem is fixed, what should have happened instead?**

Should behave the same as 13066

**Which Engine Version are you using?** 

18289 pre

**Screenshots** 
Was unable to get a shot because of the freeze.

**Zipped Save Game**

Saved game won't recreate it ( in the history ) but I'll post one anyway. Seems to happen the most in the 119 SZ battle.
[oztea_1939_global-master saved game 1.88 .zip](https://github.com/triplea-game/triplea/files/4315280/oztea_1939_global-master.saved.game.1.88.zip)

I'm gonna piggyback on saved games. 13066 I'd just hit enter a couple times and it'd overwrite. Doesn't do that now. Takes a couple more clicks. Looks different too. I can get used to the looks but don't like the extra clicking.

Don't mean to sound overly critical. Just providing feedback. Appreciate what you guys do.

Edit
Seems maybe the submarine popup might be causing it. I'm gonna do some more testing a bit later here.

**Comment by DanVanAtta** [comment]
@beelee1 could you clarify what you mean by:

> battle calc to advance the combat 


Could you also clarify what you mean by "it" in:

> Before, in 13066, I'd just click on it and it'd advance.

**Comment by beelee1** [comment]
yea I'm gonna do some more testing again soon. I think it was the space bar or click that wasn't forwarding the same as 13066

**Comment by beelee1** [comment]
hmm...I can't seem to recreate this. It happened on consecitive nights and multiple times tho. I'm going to continue testing. Please close ( actually I'm gonna close for now ) if you want and I'll reopen if necessary. Pretty sure it was space bar and click but ... sorry to bug ya

**Comment by DanVanAtta** [comment]
No bother, would rather problems be reported than not.

**Comment by beelee1** [comment]
so what's happening is when i start the 119 battle I have to go to the bottom bar n click on the triplea dude before it will advance. 

[18289 sub attack freeze.zip](https://github.com/triplea-game/triplea/files/4347664/18289.sub.attack.freeze.zip)
 Sorry I cant get a better screenshot but it's the little triplea dude at the bottom that i gotta click on. A "2" shows up next to him when the battle window opens and i have to click on the main map window to get it to advance. The save starts right before combat. On linux. It happens right away
![Screenshot from 2020-03-18 02-53-05](https://user-images.githubusercontent.com/24382682/76938329-6b390880-68c4-11ea-83d1-fe33abf895a8.png)

**Comment by DanVanAtta** [comment]
@beelee1 good problem to uncover, thank you for reporting. I took a look at this and I wonder if you can help clarify it.

I'm on linux, when I start the sz119 battle, I see this:
![Screenshot from 2020-03-28 00-55-08](https://user-images.githubusercontent.com/12397753/77818370-03867880-708f-11ea-91e2-8d1e544095b2.png)

From here the game is seemingly frozen, the 'submerge' button is visually disabled, and there is nothing to click on in the combat.

But, moving the window, we see there is a submerge dialog that is *behind* the combat window:
![Screenshot from 2020-03-28 00-55-16](https://user-images.githubusercontent.com/12397753/77818385-1c8f2980-708f-11ea-9508-c43c094321d8.png)

The interesting part, the 'space' button listener is still active on combat window. If you click on the combat window, and press space bar, then you get a *second* submerge dialog, and this one is properly always on top:

![Screenshot from 2020-03-28 00-55-48](https://user-images.githubusercontent.com/12397753/77818406-36c90780-708f-11ea-9445-e1125225ac63.png)

@beelee1 is that roughly what you are seeing?

If so, I think we have some clear action items:
1. the initial submerge dialog needs to be in-front of the combat window
2. pressing space bar with combat window selected should not open a second submerge question dialog window

**Comment by beelee1** [comment]
yea that's pretty much it. I was getting to the second (behind) window by clicking on the icon. I haven't had a chance to test anything recently, but yea, that's pretty much what's happening.

**Comment by DanVanAtta** [comment]
Hmm, it's quite odd, but the submerge dialog now properly shows in front of the combat window. @beelee1 could you see if you have the same behavior on the latest?
