### ISSUE TITLE
Logging in to Prerelease 2.0.18289

### ISSUE THREAD

**Issue by beelee1** [triplea-game/triplea#6047]
**How can the problem be recreated?**

so I can only log in once with my old name. I have remember me on. Next time it says name "taken" or something similar. Joined with two new names and same thing happened.

**When the problem is fixed, what should have happened instead?**
I should be allowed to log in with my name

**Which Engine Version are you using?** 
18289 pre

**Screenshots** 
![Screenshot from 2020-03-13 20-31-39](https://user-images.githubusercontent.com/24382682/76672320-c50a9d00-6569-11ea-94bc-98002250293b.png)

**Zipped Save Game**
no game started

**Comment by beelee1** [comment]
I have 3 accounts on lobby. beelee, beelee1,beelee2

beelee1 is working but not the other 2. They all have the same email. Idk y beelee didn't work after the first time. 
Anyway...:)

**Comment by DanVanAtta** [comment]
When logging in with a  new name @beelee1 , do you see the old name still listed in the lobby?

The first time logging, when you are successful, are you disconnecting from the lobby before rejoining, or are you attempting to create multiple sessions?

**Comment by beelee1** [comment]
I joined and then left. Restarted triplea to join the second time and that's when I noticed it. I then made new names and tried it again to see if it did it. For some reason the second name worked but not the other two. 

I've never tried joining with multiple names at the same time. I'm gonna do some testing here in a bit. I used the same pw for them which is my original one as well. I wouldn't think that'd matter but maybe ?

**Comment by beelee1** [comment]
Ok i think I got it sorted. I didn't realize it was set to login anonymously as is shown in above screenshot. I'll test some more and close if that's the case. Is anonymous the default ? I don't think it is on 13066 but I don't really pay attention just hit log in.

**Comment by DanVanAtta** [comment]
The error messages on login should be relatively intuitive. If you spot something that is not quite direct in telling you what went wrong, please let us know.
