### ISSUE TITLE
Possible Android App?

### ISSUE THREAD

**Issue by johnpaulmckean** [triplea-game/triplea#6061]
I've been a lover of the triplea game since 2009 and am wondering where this codebase stands in regards to UI/business logic being mixed.

@DanVanAtta  it seems you were trying a few years ago to heavily rewrite the UI, how'd that end up going?

**Comment by RoiEXLab** [comment]
@johnpaulmckean The state of the codebase has slightly gotten better, but there are still a lot of issues with it.
There is an ongoing effort to clean all of this up, but were still a long way from a state where porting TripleA to a different device would be feasible.

You can have a look at https://github.com/triplea-game/triplea/releases/tag/2.0.18384 at the "triplea-game-headed-javafx-2.0.18384.jar" distribution where you can see the start of a completely rewritten UI, https://github.com/triplea-game/triplea/projects/13 tracks the progress of the navigation screens (excluding the main game screen).
So once we migrated all non-game screens, we're in a state where we're about 50% through the migration, which seems achievable in 2020.
But simply reaching the 100% is not enough unfortunately. 100% Will mean that in theory we could run TripleA on an android or iOS device, but the UI likely won't be good enough for smaller screens, so from this point on there will still be a lot of polishing to do.

However our current efforts are trying to get [2.0 released](https://github.com/triplea-game/triplea/issues?q=is%3Aissue+is%3Aopen+label%3A%22Pre-Release+Problem%22), which still has some problems we'd like to address, so there won't be that much progress until that's done.

**Comment by DanVanAtta** [comment]
@RoiEXLab has been leading the JavaFX UI overhaul charge.
My estimation here is even less optimistic. The launch screens we have mostly re-written but still need a ways to go to get that done. I'd estimate the launcher screens to be 20% of the total effort to get the rest of the game UI re-written. We also still have more cruft in the launchers to clean up, simply getting JavaFX swapped out for the current UI is not necessarily putting us in a place where we can have an android app.

We also need to look at things like save game files, the fact that game data is transferred over network and that is a large payload. Memory usage is likely to be too much for an android app, we need to also take into account the differing UI events.

TBH, I don't think this is a tractable project for us. I'd say we are 3-6 years away, if we started working on it in our spare time, with our limited team.

I also believe we have other higher priorities items to tackle first:
- changing maps to be uploaded from the game, eliminate the hated and unpopular git work required to create maps
- enable save games to be uploaded, replace PBF and PBEM with cloud saves
- add player stats, enable in-game match making and tournaments
- change game serialization to be a text format, allows for developer productivity and cross-version compatibility
- changing bot games to be a network proxy. Will reduce operating cost by over 50% and drastically increase how many players can play on bot servers. Will drastically simplify code
- we need to finish getting the launch screens migrated to JavaFX

What makes it more difficult, is we don't really have a path to incrementally migrate parts of the UI a bit at a time. Without that capability, landing the project all at once is much less likely to succeed. Regrettably my view towards getting to an android app is just pessimistic, as much as I'd like to see it happen.

**Comment by RoiEXLab** [comment]
> TBH, I don't think this is a tractable project for us. I'd say we are 3-6 years away, if we started working on it in our spare time, with our limited team.

Just to clarify. I think we would be able to "run" TripleA on a mobile in like 3 years. Not that it would work particularly well or even have 100% functionality.

But I agree that there are other priorities
