### ISSUE TITLE
Map Caching Design

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#607]
There are some problems with the current map cache:
- The current map caching has a leak that holds on to references to files.
- It is entangled/coupled with a lot of other code, static state
- still slow when all maps are downloaded, 1 or 2 seconds in best case (SSD hard disk)

I don't think we can read from zip files any faster than we do. So not much to be gained there.

To suggest a solution:
- read from the file system, and then write a summary yaml file that will serve as the cache. Periodically we can scan disk for any updated files or maps and update the summary file as needed.

Thoughts? alternatives?

**Comment by ron-murhammer** [comment]
@DanVanAtta Seems reasonable to me. Is the reason you want to write out to a file so it lasts across restarts? Otherwise you could just hold the info in an object.
