### ISSUE TITLE
Lobby has run out of empty bots!

### ISSUE THREAD

**Issue by prastle** [triplea-game/triplea#6071]
Currently the lobby has every bot full.  If the Devs could fire up a couple more bot servers that would be great!  I have allocated the funds to linode already Thanks! Pras.

@DanVanAtta @RoiEXLab @ron-murhammer

**Comment by DanVanAtta** [comment]
- Added 5 additional 1.9 bot servers, each has 7 bot hosts on it. This increases our monthly operating costs by $50/month
- Checked in deployment scripts used to code base: https://github.com/triplea-game/triplea/pull/6074

Will be following up with some documentation on how to set up a linode and run the infrastructure.
