### ISSUE TITLE
Dark Box Glitch on certain screens

### ISSUE THREAD

**Issue by Chungmeister09** [triplea-game/triplea#6080]
![image](https://user-images.githubusercontent.com/62574173/77367614-ec632600-6d30-11ea-9449-dab5c2be1030.png)

![image](https://user-images.githubusercontent.com/62574173/77367667-069d0400-6d31-11ea-87f9-35e48ad2bf14.png)

![image](https://user-images.githubusercontent.com/62574173/77367833-54b20780-6d31-11ea-8172-811eb3981bfd.png)

![image](https://user-images.githubusercontent.com/62574173/77367865-64315080-6d31-11ea-8d99-583f6735a8a1.png)

Menus, option screens while selecting units in all of the games.  Can only be fixed by dragging the popup window off the screen and then only works temporarily for the current country move.

**Comment by DanVanAtta** [comment]
Which version of the game are you running @Chungmeister09 ?

**Comment by Chungmeister09** [comment]
Hi dan,

I am running 1.9.0.0.13066

Thanks!

Andrew Chung

**Comment by DanVanAtta** [comment]
I suspect the problem might be java version @Chungmeister09 

Could you try downloading and installing the latest TripleA which comes with an updated java?
https://github.com/triplea-game/triplea/releases/download/2.0.18437/TripleA_2.0.18437_windows-64bit.exe

Second, if you do not see a problem with that version of 2.0.x, you can try updating to a latest version of java 1.8 on your computer. When TripleA launches, you should see the version of java in the upper left next to the game version. Please let us know if any of that works.

**Comment by Chungmeister09** [comment]
Hi Dan,

I"m still having some issues with the game.  The boxes doing the blackout
happens about 75% of the time during the game.

Thanks!


[image: image.png]
[image: image.png]

**Comment by DanVanAtta** [comment]
Hmm, another long-shot chance is to try changing the "look and feel", try either "metal", or one of the substance L&Fs. You can toggle that in the engine settings menu, look and feel.

**Comment by RoiEXLab** [comment]
What could potentially help is to do a clean re-install of the latest driver version for your graphics card.
We don't really control the rendering of those components, so we're just wild guessing

**Comment by Chungmeister09** [comment]
Hi Guys,

[image: image.png]

Still having this issue from time to time.  I changed the look and feel to
metal and had the same issue and checked my device manager and no updates
for my graphics card were available.

Thanks!

Andrew

**Comment by DanVanAtta** [comment]
@Chungmeister09 could you check if you have not already if you see this problem with the latest prerelease? https://github.com/triplea-game/triplea/releases/tag/2.0.18790
