### ISSUE TITLE
Travis build permissions

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#6087]
It looks like there is some weirdness going on with Travis permissions. Notably I was not able to re-trigger builds and it just generally looked like the triplea-game organization was disconnected from my account in travis.

I signed up for the travis.com beta and clicked some migration buttons. It looks like on travis.com, triplea-game/triplea has the right account permissions again. @RoiEXLab , @ron-murhammer ; opening this as a discussion tracking ticket in case ya'll see this and for any further discussion/tracking.

**Comment by DanVanAtta** [comment]
Looks like we should be using 'travis.com' no instead of travis-ci.org

https://travis-ci.com/github/triplea-game/triplea

**Comment by RoiEXLab** [comment]
Seems to be working now, 2 things that need to be done IMO:
1. Make the checks required like it used to be.
2. Inform every dev who should know about this change
3. (Close this issue)

**Comment by DanVanAtta** [comment]
Re required:
![Screenshot from 2020-03-28 10-21-55](https://user-images.githubusercontent.com/12397753/77829239-0492c680-70de-11ea-9a69-78107a63a852.png)

The PR in queue that used travis-ci.org is "disconnected" from the travis-ci.com checks it looks like. It can be recreated or we can just ignore it for that one PR. Otherwise new PRs are building against '.com' and the check looks to be coming back and is marked as required.

**Comment by DanVanAtta** [comment]
This is not a problem so long as you go to travis-ci.com, the retrigger is avialable there.
