### ISSUE TITLE
UX: placement, label - tell user what they should do.

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#6099]
**How can the problem be recreated?**
During placement, we show a lot of blank space and no label/indication for a player to click a factory.
To make it clear what the user should do, below the 'done' button, we could show a one-time text of "click a factory to place there"

**Comment by DanVanAtta** [comment]
We should strongly consider whether to have, during placement phase, if the units in 'units to place' should go back to the old treatment and be displayed in the placement panel.

**Comment by ron-murhammer** [comment]
I definitely think having them in the old place would be better as all other phases tend to have the immediate action at the top of the panel.

**Comment by DanVanAtta** [comment]
If we go back to the old UI treatment for the placement phase, something I very much support, then instead of a label we could consider adding a hovertext on the units to place to tell a user they need to click the map to place.

**Comment by DanVanAtta** [comment]
Adding to 2.0 project as a TODO. Arguably this was a problem in the last release, the latest UI treatment in the 2.0 prerelease exacerbates the problem.
