### ISSUE TITLE
CR painpoints - promtpness and CR forecasting - how to fix?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#6108]
There is a common thread in most any article about CR best practices:

https://www.ideamotive.co/blog/code-review-best-practices

> Make the Code Review a priority

> Code review is a blocker for merging a feature, so if a developer requires some piece of code to be available for the new feature, it could be a problem. Required changes can be manually merged into the new feature before the start, but it can lead to code conflicts, on the other hand, the developer will wait to do nothing until changes are made.

> So it is essential to make developers understand that pending code reviews (and overall pull requests) are actually more important than their own ongoing work (of course in a reasonable way, critical fixes are even more critical). It’s not an easy topic, because developers seem to care about their focus state a lot, but it can be communicated like this: make code review first thing developer do when:

>    Starting work in the morning
    Going back from lunch
    Going back from Fussball/PlayStation/darts break
    Going back from meeting

 https://medium.com/palantir/code-review-best-practices-19e02780015f

> A code review is a synchronization point among different team members and thus has the potential to block progress. Consequently, code reviews need to be prompt

## For us this has been a problem:
- we are a small team
- 4th quarter in 2019 when we had a lot of PR throughput, CR created a significant bottleneck.
- Overall CR remains the biggest bottleneck in the code development flow
- Knowledge is potentially getting silo'd.

## What have we tried to do?
- added a process to treat the queue as a FIFO
- tried aggressive splitting of PRs to make them more reviewable
- created a system (that seems to not have been adopted ) for most-merge reviews
- created a system of "review these first" via labeling to alleviate review bottlenecks

## Recent examples

I don't think we are there for having prompt reviews, examples:
- https://github.com/triplea-game/triplea/pull/6053 > took 7 days for a first review
- https://github.com/triplea-game/triplea/pull/6091 open for 3 days without any action at all

## Not Getting the full benefit of CR

I suspect we are also not really benefiting as much as we could from review:
- it was not broadly known that the 'infrastructure' project is long dead, and that is despite a couple dozen PRs to update and bring infrastructure into the project and make it part of CI
- arguably, when doing reviews too quickly, or with the wrong focus, we are doing the work of 'codeclimate' but just in a manual manner. 

## CR following the shiny object

In the meantime, I do think we are suffering from "follow the shiny object" and something like https://github.com/triplea-game/triplea/pull/6086 is reviewed by 4 people and within 24 hours.

## Counter Examples, CR has been useful

- We have had useful feedback/commentary that has found problems
- We've had external reviewers beyond this project contribute to CR https://github.com/triplea-game/triplea/pull/6007

## Problem summary

- we are a small group, we do not have full-time reviewers
- CR has not been prompt
- CR is one of the most salient process bottlenecks that is slowing down this project
- We are not getting the full benefit of CR
- CR is mostly done by one person, Roi, in response to PRs from one person, myself, this is a problem.

**Comment by DanVanAtta** [comment]
IMO having lost the tight QA group and feedback loop, and CR bottlenecks are the two most salient and biggest process problems we have.

Before I suggest possible approaches to the above, @ron-murhammer , @RoiEXLab , do you have any thoughts on the problem and any suggestions for future direction?

**Comment by ron-murhammer** [comment]
Honestly until the next release I would vote to have minimal CR. Just focus on making sure the PRs are actually doing what is intended and no major risks. I'm willing to sacrifice detailed code review and some code quality for throughput.

**Comment by DanVanAtta** [comment]
I think that is a bit shortsighted if we go back to the old ways for the sake of one release. In part, the deficiencies noted is really how we got to this situation in the first place with a delayed release. 3.0 would suffer from the same problems and see the same drag on efficiency. IMO we need to have sustainable processes that we do not abandon. Those processes need to have us move faster and more effectively, or be changed. If we abandon a process to do that, then the process is highly suspect.  This issue is about how we do change our long-term process in a sustainable way and not find ourselves in this problem now, a month from now, or a year from now.

**Comment by ron-murhammer** [comment]
Agree long term. But I'd rather fix the immediate problem which is getting to at least a release candidate ASAP then we can discuss the long term solution.

**Comment by DanVanAtta** [comment]
We're essentially *at* a release candidate and have been there for some time.. It would be great for us to finish QA and know the full set of issues sooner. We could better partition that work. The current set of issues to fix can also be picked up by anyone as well, which would be excellent.

I think an analogy is swimming. It's about hydrodynamics. It's always kinda fun to see an 8 year old smoke a muscle bound weight lifter in a swimming pool, who nearly drowns after one lap, because the 8 year old has refined technique and the muscle bound person uses shear force. When a person gets tired swimming, the form drops, and it slows you down. When moving slow, the best thing to do is to fallback on training, process, the techniques that you develop and practice because those *are* the things that make you go fast. If on the other hand you drop the technique, start thrashing at water, it's the wrong instinct. Alternatively, if thrashing is faster than the technique, then the technique is essentially wrong. The technique, process and tools are the things that should be making you go fast, not slowing you down. If you go faster by abandoning the technique, the technique is a problem.

**Comment by DanVanAtta** [comment]
I'm paraphrasing a bit Uncle Bob who said it much better than I can, here is the original quote (though I think this line of thought is more broader than just TDD, it applies to the entire development process):

https://www.goodreads.com/author/quotes/45372.Robert_C_Martin?page=4

> “Crisis Discipline

> You know what you believe by observing yourself in a crisis. If in a crisis you follow your disciplines, then you truly believe in those disciplines. On the other hand, if you change your behavior in a crisis, then you don’t truly believe in your normal behavior.

> If you follow the discipline of Test Driven Development in noncrisis times but abandon it during a crisis, then you don’t really trust that TDD is helpful. If you keep your code clean during normal times but make messes in a crisis, then you don’t really believe that messes slow you down. If you pair in a crisis but don’t normally pair, then you believe pairing is more efficient than non-pairing. Choose disciplines that you feel comfortable following in a crisis. Then follow them all the time . Following these disciplines is the best way to avoid getting into a crisis. Don’t change your behavior when the crunch comes. If your disciplines are the best way to work, then they should be followed even in the depths of a crisis.”
― Robert C. Martin, The Clean Coder: A Code of Conduct for Professional Programmers

**Comment by DanVanAtta** [comment]
To be clear, the problem I don't think is the content of CR's - it's just the lack of clarity when and if it'll happen and the impact that has for PR planning for follow-on changes and the implications for round-trip time.

I think this issue is probably solved by:
1. Prioritizing review above all other maintainer work (at least a persons own PRs)
2. Giving immediate commentary to new PRs:
  - whether general directions looks good
  - if testing statement looks adequate
3. Give an ETA or expectation of when a CR could occur, eg: "Hey this looks  good, if nobody else gets to this, I should be able to provide a CR tomorrow". If the timing does not work out, then the PR author can have that conversation. If we have issues where CR's just can't be timely, then we could consider in those cases doing post-merge reviews. 
4. Minimizing round-trips, avoiding day-long roundtrips. 
5. Providing as complete of a review as possible on the first iteration, avoid "now that you fixed these things, please fix these things." If unable to do so, be explicit that there is more feedback possible and that the review is not complete.
6. Always provide suggestions and alternatives to blocking issues, ensure the PR author has a path forward and the last comment states what that is, eg: "Handling of X could have a problem, that needs to be fixed. Perhaps we could think of something like Y, I'm not sure though, maybe you might have some ideas? If not, perhaps Z could work too."

**Comment by DanVanAtta** [comment]
Beyond the points mentioned above, I think we probably could use a CR "relief valve" to account for when review capacity is particularly low. Notably that would be if no initial comment is given within 36 hours, then we favor self-reviewing and merging those PRs and just skip the review (as presumably the reviewers are just busy).

Would like to close this issue out..

**Comment by RoiEXLab** [comment]
> Notably that would be if no initial comment is given within 36 hours, then we favor self-reviewing and merging those PRs and just skip the review (as presumably the reviewers are just busy).

I would be fine with that

**Comment by DanVanAtta** [comment]
Would like to see the SOP described in: https://github.com/triplea-game/triplea/issues/6108#issuecomment-605844346, either be adopted as SOP or be discussed further.

**Comment by DanVanAtta** [comment]
I think google really captured a lot of the essence of this issue in: https://google.github.io/eng-practices/review/reviewer/speed.html

> When code reviews are slow, several things happen:
> The velocity of the team as a whole is decreased. Yes, the individual, who doesn’t respond quickly to the review, gets other work done. However, new features and bug fixes for the rest of the team are delayed by days, weeks, or months as each CL waits for review and re-review.

> Developers start to protest the code review process. If a reviewer only responds every few days, but requests major changes to the CL each time, that can be frustrating and difficult for developers.

> If you are not in the middle of a focused task, you should do a code review shortly after it comes in.

> When we talk about the speed of code reviews, it is the response time that we are concerned with, as opposed to how long it takes a CL to get through the whole review and be submitted. The whole process should also be fast, ideally, but it’s even more important for the individual responses to come quickly than it is for the whole process to happen rapidly.


https://google.github.io/eng-practices/review/reviewer/comments.html

> In general, it is important to be courteous and respectful while also being very clear and helpful to the developer whose code you are reviewing


https://google.github.io/eng-practices/review/reviewer/pushback.html

> When a developer disagrees with your suggestion, first take a moment to consider if they are correct.
> However, developers are not always right. In this case the reviewer should further explain why they believe that their suggestion is correct. A good explanation demonstrates both an understanding of the developer’s reply, and additional information about why the change is being requested.

https://google.github.io/eng-practices/review/reviewer/comments.html#courtesy

> Explain your reasoning.
Balance giving explicit directions with just pointing out problems and letting the developer decide.
Encourage developers to simplify code or add code comments instead of just explaining the complexity to you.
