### ISSUE TITLE
[General Map Issue] Missing Resources

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#612]
I'm not sure if this is the right place to report this, but one thing I noticed, is that there are many maps in the lastest "pre-release" version with missing/"not-on-the-right-place" resources/images.
When playing standard Diplomacy for example every time when hovering over an invalid territoy when doing combat moves, an error is thrown out, reporting, that error.png was not found - error.png is in the wrong directory.
Other Maps like Civil War: A House divided are not playable, because the map image cannot be found

**Comment by ron-murhammer** [comment]
@RoiEXLab - I would check the current version in SVN with 1.8.0.9. If that has the issues then it is an existing problem. If those are fine but the new github ones have issues then we have a problem.

**Comment by RoiEXLab** [comment]
Playing WW2 Classic in the lastest stable 1.8 version worked fine, trying playing it in 1.9 after downloading it throws the following error:

INFO: Found too many files for: world_war_ii_classic  found: [C:\Users\Robin\triplea\downloadedMaps\world_war_ii_classic.zip, C:\Users\Robin\triplea\downloadedMaps\world_war_ii_classic.zip]Exception: null
INFO: Found too many files for: world_war_ii_classic  found: [C:\Users\Robin\triplea\downloadedMaps\world_war_ii_classic.zip, C:\Users\Robin\triplea\downloadedMaps\world_war_ii_classic.zip]
Game frame is null, but entered player step: russianTech for player: Human:Russians
Game frame is null, but entered player step: russianPurchase for player: Human:Russians
Game frame is null, but entered player step: russianCombatMove for player: Human:Russians

```
java.awt.EventQueue.invokeAndWait(EventQueue.java:1321)
java.awt.EventQueue.invokeAndWait(EventQueue.java:1296)
javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1348)
games.strategy.common.swing.SwingAction.invokeAndWait(SwingAction.java:61)
games.strategy.triplea.TripleA.startGame(TripleA.java:127)
games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInNewThread(LocalLauncher.java:51)
games.strategy.engine.framework.startup.launcher.AbstractLauncher$1.run(AbstractLauncher.java:47)
java.lang.Thread.run(Thread.java:745)
Game frame is null, but entered player step: russianNonCombatMove for player: Human:Russians
Exception: null
com.sun.proxy.$Proxy13.reportMessage(Unknown Source)
games.strategy.triplea.delegate.AbstractEndTurnDelegate.showEndTurnReport(AbstractEndTurnDelegate.java:179)
games.strategy.triplea.delegate.AbstractEndTurnDelegate.start(AbstractEndTurnDelegate.java:172)
games.strategy.engine.framework.ServerGame.startStep(ServerGame.java:517)
games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:425)
games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:280)
games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInNewThread(LocalLauncher.java:63)
games.strategy.engine.framework.startup.launcher.AbstractLauncher$1.run(AbstractLauncher.java:47)
java.lang.Thread.run(Thread.java:745)


It seems that there are some maps that aren't correctly configured...
```

**Comment by RoiEXLab** [comment]
Also Middle Earth is missing an error.gif file...

**Comment by DanVanAtta** [comment]
If every map needs one, keeping it with the game engine could make sense.

**Comment by RoiEXLab** [comment]
Well it seems that the Images are themed to match the maps style... Diplomacy looks 1930 style while StarWars looks futuristic or something like that...

**Comment by DanVanAtta** [comment]
What's the latest on this issue? Kindly, could we summarize the latest action item, and/or error message that needs to be worked on?

**Comment by RoiEXLab** [comment]
Currently WWII Maps are working fine for me...
I didn't notice any mayor Issues recently

**Comment by DanVanAtta** [comment]
Good to close?

**Comment by RoiEXLab** [comment]
Well since there is the map errors issue still open...
