### ISSUE TITLE
The Moderator' Toolbox displays incorrect info.

### ISSUE THREAD

**Issue by prastle** [triplea-game/triplea#6126]
**How can the problem be recreated?**
Access the admin toolbox and examine the Events logs.
**When the problem is fixed, what should have happened instead?**
Example A - Banned beelee for 1 min it displays 1 hour
Example B - Adding a moderator shows as removing one as well as removing a moderator shows as removing one.
Some fine tuning and a careful check of the data listed should be done here.
**Which Engine Version are you using?** 
2.0.18542

**Comment by prastle** [comment]
I would like to add that after testing most of the functions they all appear to working correctly just displaying the info incorrectly.  Another issue which could relate to this is it appears I need to close and rej/refresh the lobby in order for beelee as a new mod to appear to me even tho he has left and rejoined and it shows as a mod to him.   I am curious if this is due to the Nano size of the lobby host.  I am unsure if this is an issue or not.

**Comment by DanVanAtta** [comment]
Example B is fixed in: https://github.com/triplea-game/triplea/pull/6145

**Comment by DanVanAtta** [comment]
@prastle regarding stale data, most of the moderator toolbox tabs have a 'refresh' button on them. If you make someone a moderator and they are in the chat, they'll need to rejoin.

**Comment by DanVanAtta** [comment]
Example A will be fixed by: https://github.com/triplea-game/triplea/pull/6161

**Comment by prastle** [comment]
Good Stuff!
