### ISSUE TITLE
A moderator should NEVER be able to ban a moderator.

### ISSUE THREAD

**Issue by prastle** [triplea-game/triplea#6128]
Join the Pre lobby as a mod with another mod.  Using The functions ban that mod in any way you feel like or boot him.

**When the problem is fixed, what should have happened instead?**
It should be impossible for a mod to ban a mod ….. Only  an Admin can ban a mod or in the current structure  a "SuperMod"

**Comment by prastle** [comment]
At the present moment even a Mod can Ban a SuperMod

**Comment by DanVanAtta** [comment]
- 'SuperMod' is an older term. 'Admin' was already in use to mean a 'mod' in 1.9, hence 'superMod'. At this point 'SuperMod' should just be renamed to 'Admin'

Should admins be able to ban moderators? If that happens, does that imply the moderator should no longer be a moderator and removed as a moderator first? If so, then we can have a blanket rule that moderators are immune from banning.

**Comment by prastle** [comment]
The blanket rule should be a "user" cannot ignore or "mute" a mod or admin.
A "Mod cannot mute or ignore or ban a mod or Admin
only an admin can remove or ban a mod

**Comment by prastle** [comment]
@DanVanAtta So to answer your ? Yes an Admin can removee or ban mod.

**Comment by prastle** [comment]
And to clarify your worries before we talk about it I am pretty sure we only have 3 or 4 admins in the database @DanVanAtta

**Comment by prastle** [comment]
So yes we can have a blanket rule that mods can't be banned.  Except by admin

**Comment by DanVanAtta** [comment]
@prastle the exception complicates this just slightly. Perhaps easier to say if we need to ban a moderator, we instead make that person no longer a moderator.

Asked/said in another way, if we need to ban a moderator, should they really remain a moderator?

**Comment by DanVanAtta** [comment]
> The blanket rule should be a "user" cannot ignore or "mute" a mod or admin.
A "Mod cannot mute or ignore or ban a mod or Admin
only an admin can remove or ban a mod

Muting a moderator is probably a bug, if confirmed @prastle or anyone , please create an issue so we can track that independently. The fix is actually different compared to removing the ability to ban a mod.

```
1 issue, 1 problem, 1 fix
```

**Comment by DanVanAtta** [comment]
@prastle do we really need this?
I know this was the behavior in 1.9, what value do we get from building this into 2.0?
- Are we trying to prevent moderators from going rogue?
- Are we trying to avoid misclicks that ban a moderator instead of someone else?

Keep in mind that it'll be visible who issued bans and we can undo bans from the database if we need to. It'll be a bit annoying, but can be done. If a moderator goes rogue like this, they probably would be aware that they'd be banned. Is this truly worth the complexity and effort to build, or just a nice to have for the sake of keeping parity with 1.9?

**Comment by DanVanAtta** [comment]
@prastle I wouldn't mind seeing this feature. At this point I think the ROI might be low. If a moderator goes rogue, then we undo their bans and ban them. Unless there is another reason that makes the return on investment greater, I'm hard pressed to say we should spend the effort on this.

**Comment by prastle** [comment]
Np your right it does record it.  Hopefully I am only being pessimistic :) @DanVanAtta
