### ISSUE TITLE
Recent inexplicable crashes of current stable

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#6134]
Different from other bug reportings this time I only post a link to 
https://www.axisandallies.org/forums/topic/34935/triplea-crashes

The reporting user is on Win 10 64bit.
I am on Win 7 64bit (still).

There is not much to add as those crashes seem to occur somehow arbitrarily.

**Comment by DanVanAtta** [comment]
Sorry to say @panther2 we won't be able to do much and are not going to release a 1.9 fix. If you can get a thread dump, it would help us know if we potentially have a problem in 2.0

https://access.redhat.com/solutions/19170

**Comment by panther2** [comment]
@DanVanAtta Yes, I'll try that.
