### ISSUE TITLE
Javadoc checkstyle rule not evaluated when run in gradle

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#6135]
Issue: our checkstyle config requires javadocs on certain methods/classes, but it is not being checked properly when we run gradle:

![Screenshot from 2020-04-05 08-36-26](https://user-images.githubusercontent.com/12397753/78502964-96bb5000-7718-11ea-83de-ade7e849f01f.png)

The net effect is we'll see these warnings (usually) in IDE but checkstyle run through gradle does not show them.

**How to Solve?**

Personally, I have not been terribly bothered by the lack of the checkstyle rules. Getting into a habit of explaining the purpose behind classes is good, adding some documentation to public methods can be good too. Unless otherwise forced, these tend to not happen, but you also wind up with less than useful comments too.

A) Should we just honor this situation and remove the javadoc requirement from checkstyle
B) Should we spend some time to try and fix the config so that gradle checks for javadocs properly?

If we go with (B), there are some follow-on questions like if we should relax requirements and what to do about the javadoc backlog that it creates.

(A) on the other hand is arguably the lightest weight, no backlog, no future requirements for javadoc unless we think we need them. If we go this route then we'll need to check in review that methods are documented where helpful (checkstyle in part is to help automate consistency checks and checks we otherwise would do in review).

Any thoughts on direction?

**Comment by RoiEXLab** [comment]
Mixed feelings on this one.
I recall @ssoloff once went ahead and added a lot of javadocs for various method to satisfy the checkstyle rules, maybe he has a better idea if A) would be worth.

Regardless I think we should figure out why exactly gradle doesn't pick up those changes.

**Comment by DanVanAtta** [comment]
> 

Regardless I think we should figure out why exactly gradle doesn't pick up those changes.

**Comment by DanVanAtta** [comment]
> Regardless I think we should figure out why exactly gradle doesn't pick up those changes.

Will be perhaps moot. I have noticed our checkstyle file is not compatible with the latest checkstyle plugin version in IDEA (kinda tedious to find the right version for it to work). I suspect that has a lot to do with it. IMO first we need to decide what value we are getting from the javadocs though. If we have the rule there just because that was a default rule, I think we should challenge that a bit (otherwise we might be missing the point of why we have checkstyle)

**Comment by DanVanAtta** [comment]
Let's revisit this if we find we are having to ask for a lot of javadocs in CRs. I think we probably will be, a summary javadoc on classes for their intent and expected usage and some sample code for how it is used I generally find to be really helpful. We do not want classes to have to be understood by reverse engineering the code, a good comment will give the reader a general expectation of what to expect and help make understanding the class functionality and fit much easier..
