### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#615]
We have some versioning problems. Looking to discuss potential ways to solve
### Maps

I tend to think we should have the game store all versions of a map it can so we can have more arbitrary map compatibility.
### Game engine

A way so new game engines can always play with older ones.

If we can solve these issues, we'll be able to release game engine updates much more readily. The map version problem is becoming a bit more pressing since map revisions are potentially much more frequent.

**Comment by ron-murhammer** [comment]
@DanVanAtta I think mostly just having a clear definition of what breaks compatibility would be the best place to start. I actually don't really want to try and keep multiple versions of maps around and prefer the map owner kind of choose whether to break backwards compatibility and push people to move forward or create a new map if the changes are that drastic and they want to leave the old one as playable.

**Comment by DanVanAtta** [comment]
It's quite easy to break compatibility. There will always be tension to not upgrade maps, long running save games will always exist, and meanwhile a person will be reluctant to upgrade. I think the trick would be finding a good way to clean old versions. My point ultimately is we should grease the wheels here, right now it's a painful process and we will be hitting it more often.

**Comment by ron-murhammer** [comment]
I actually haven't seen very many maps break compatibility and if they were going to often the creator would actually create a new map rather than new version of the same map. Though you could argue the reason for that is due to them wanting to avoid breaking compatibility. I'm open to solutions but the one thing I want to avoid is users have 5 versions of a 200MB map.

**Comment by DanVanAtta** [comment]
Linking to  #546

**Comment by DanVanAtta** [comment]
I think we can avoid the 5 versions of large maps in a couple of ways. We can keep a queue of used maps, and offer to clean up the ones that have not been played in 3 months. Alternatively or in addition, when a new version is downloaded, we could offer to auto-clean old versions.
