### ISSUE TITLE
When Joining Lobby it displays twice.

### ISSUE THREAD

**Issue by prastle** [triplea-game/triplea#6172]
![2020-04-10](https://user-images.githubusercontent.com/17258293/78997611-e6cd5480-7b14-11ea-9d58-286b6dcd421d.png)
**How can the problem be recreated?**
Joining the lobby.

**Comment by beelee1** [comment]
fwiw it did it to me on 18667. i just noticed it after seeing this

**Comment by DanVanAtta** [comment]
Fixed with: https://github.com/triplea-game/triplea/pull/6179

**Comment by DanVanAtta** [comment]
Thanks for reporting @prastle  @beelee1 , keep the bug reports coming, ya'll have the hang of it! :smile:

**Comment by prastle** [comment]
np and off topic but is this a bug or a feature request next?
nm long winded ill type tomorrow
