### ISSUE TITLE
Can't Finish Moves with Done Button

### ISSUE THREAD

**Issue by beelee1** [triplea-game/triplea#6194]
**How can the problem be recreated?**
In 18719 pre i loaded a save from 18613 which worked on 18701 but when i finish combat or non combat moves the done button won't finish the phase. It just blinks when I click on it.

**When the problem is fixed, what should have happened instead?**
it should work 

**Which Engine Version are you using?** 
18719 pre
**Screenshots** 

**Zipped Save Game**
[can't finish moves with done 18719.zip](https://github.com/triplea-game/triplea/files/4465558/can.t.finish.moves.with.done.18719.zip)

**Comment by beelee1** [comment]
Done button does work for when I place guys

**Comment by DanVanAtta** [comment]
If you load a save from the same version, does it work @beelee1 ?

**Comment by DanVanAtta** [comment]
I've spotted the problem I believe.. a fix should be coming pretty soon.

**Comment by DanVanAtta** [comment]
Problem is a logic defect introduced in another recent fix. The impact is pretty significant, any move phase where you have moved units you will not be able to end and the 'done' button will do nothing.

This is fixed by: https://github.com/triplea-game/triplea/pull/6202

**Comment by DanVanAtta** [comment]
A fix is being built, 18741 should have it.
