### ISSUE TITLE
Latest release will not advance to Combat phase TWW 3.0

### ISSUE THREAD

**Issue by muzzman71** [triplea-game/triplea#6195]
![image](https://user-images.githubusercontent.com/63522491/79056519-5df20e00-7c25-11ea-92f6-404f832c98a6.png)

**Comment by DanVanAtta** [comment]
@muzzman71 if you head to 'settings' > 'game' > 'show console = on', do you see any error messages or otherwise in the console?

**Comment by DanVanAtta** [comment]
@muzzman71 when you say latest release, you are referring to 13066?

**Comment by muzzman71** [comment]
![image](https://user-images.githubusercontent.com/63522491/79057155-0dca7a00-7c2c-11ea-9665-26565d2e792b.png)

No Debug messages, and latest release of TripleA 2.0.18719  (soory getting back to you late, had to get gas)

**Comment by muzzman71** [comment]
![image](https://user-images.githubusercontent.com/63522491/79057403-36a03e80-7c2f-11ea-8cc4-1bc1476eeb7f.png)

18729 has same issue

**Comment by muzzman71** [comment]
![image](https://user-images.githubusercontent.com/63522491/79057502-3e141780-7c30-11ea-958f-6e32d5093e6f.png)

18734 same

**Comment by DanVanAtta** [comment]
@muzzman71 you're probably running into this problem: https://github.com/triplea-game/triplea/issues/6194

A fix should be available in perhaps as little as an hour: https://github.com/triplea-game/triplea/pull/6202

**Comment by DanVanAtta** [comment]
A fix is being built, 18741 should have it.

**Comment by beelee1** [comment]
@DanVanAtta 18741 is working correctly :)
