### ISSUE TITLE
Dev-Setup running docker on Mac

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#6230]
> @asvitkine you need to launch the docker DB:
> 
> ```
> cd lobby-db
> ./build_docker  # build is one time
> ./launch_db
> ```
> 
> Let us know if those commands do not work for you @asvitkine
> 
> If not, and you're on windows, @RoiEXLab may have set up docker on windows already. Between the two of you would be really great to see some setup documentation be created.
> 
> I have on my radar to create a contributing.md file to explain these steps and expectations.

I installer docker from MacPorts (i.e. running docker command prints output), but these scripts are still not working.

```
$ ./build_docker

Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

```
$ ./run_docker 
Stopping docker...
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
xargs: illegal option -- -
usage: xargs [-0opt] [-E eofstr] [-I replstr [-R replacements]] [-J replstr]
             [-L number] [-n number [-x]] [-P maxprocs] [-s size]
             [utility [argument ...]]
```

(I'm on Mac.)

Seems these scripts don't really work on Mac? Can we have a way to exclude this test suite until someone who knows docker and these scripts (not me) can make them work on Mac?

_Originally posted by @asvitkine in https://github.com/triplea-game/triplea/pull/6189#issuecomment-612897805_

**Comment by DanVanAtta** [comment]
@asvitkine the checked in scripts are pretty thin, the build script is one line:
```
docker build --tag triplea/lobby-db:latest .
```

The run script is essentially these three commands with some extra stuff to parse the container name:
```
docker container stop $runningContainerId > /dev/null
docker container rm $runningContainerId > /dev/null
docker run -d --name=triplea-lobby-db -p 5432:5432 triplea/lobby-db > /dev/null
```

Our dev-setup instructions are probably a bit too spread out.

I found these notes: https://github.com/triplea-game/triplea/wiki/Local-Build-and-Testing

Which recommends trying to install docker-ce: https://store.docker.com/editions/community/docker-ce-desktop-mac

@asvitkine would you see if the docker-ce version works for you?

**Comment by asvitkine** [comment]
> @asvitkine the checked in scripts are pretty thin, the build script is one line:
> 
> ```
> docker build --tag triplea/lobby-db:latest .
> ```

Running that command directly gives me an error:

```
$ docker build --tag triplea/lobby-db:latest .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat [path to dir above triplea]/Dockerfile: no such file or directory
```

Is there a missing step?

**Comment by asvitkine** [comment]
Actually, if I run it from lobby-db dir, I get a different error:

```
docker build --tag triplea/lobby-db:latest .
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running
```

(I'm surprised the path specified is not relative to the working directly but relative to ../..).

Anyway, is there a step missing?

**Comment by asvitkine** [comment]
Also, it's really invasive to require some passive running program (docker daemon) on my computer in order to run these tests. I don't want something random constantly running on my computer in order to run ./verify. It's very intrusive and also would be taking my system resources even when I'm not doing anything related to triplea.

Why do we need this thing to run the tests? Can we add a flag to exclude these specific tests from ./verify so that I can easily run all the other tests?

**Comment by DanVanAtta** [comment]
> Why do we need this thing to run the tests? 

This is a long answer. Some quick responses:

1. There are some really brittle areas of the code, save-game serialization, network, that you can break easily without even realizing it.

2. If you do not run any tests, then arguably any PR submitted should list a full manual regression test of every aspect of the game. 

3. Failing to test properly a PR means will break a release (we are in a special place this last 18 months, typically though we'd release compatible updates frequently (bi-weekdly) without doing a formal RC). That means any merge needs to be solid. The post-merge time is not the time for testing.

4. If you have any tests break on CI and can't run them locally, then you are debugging on CI. That is not going to be practical, it'll take too much time, it's too slow an iteration speed.

**Comment by DanVanAtta** [comment]
> Also, it's really invasive to require some passive running program (docker daemon) on my computer in order to run these tests. I don't want something random constantly running on my computer in order to run ./verify. It's very intrusive and also would be taking my system resources even when I'm not doing anything related to triplea.

Docker daemon should not be taking too many resources when you have no containers running. The same argument could be made about gradle which also runs a daemon. If you want to add some utility scripts to turn on docker daemon and off when done, I won't argue. It does seem to be picking and choosing though, it's not uncommon for dev machines to run a docker daemon.

As far as the failures you're seeing @asvitkine , it looks like you are just missing docker daemon running. The lobby-db scripts do assume the current folder is 'lobby-db'.

**Comment by asvitkine** [comment]
I'm asking about docker specifically - why is it needed? What does it provide that we can't do without having a dependency on it? e.g. if we need it to run a server, why can't we run the server directly from the code in the codebase?

I'm not asking about why tests are important. I understand that.

Though, if I'm making changes to X and Y doesn't depend on X, then I shouldn't need to run tests for Y, which is my argument for being able to exclude specific test suites in the meantime.

But I'm also just wondering why we need docker here at all. Why can't things be self contained in the codebase?

**Comment by DanVanAtta** [comment]
> Though, if I'm making changes to X and Y doesn't depend on X, then I shouldn't need to run tests for Y, which is my argument for being able to exclude specific test suites in the meantime.

That is part of the point. The dependency graph in TripleA is extreme. It's not that often you can actually say X does not depend on Y. There are lots of cases where core game engine uses logic from the AI (for example, if you remove weak ai, you completely break the battle calculator). The same goes for save-game and network code which are notoriously coupled and brittle. This problem is at the core of why TripleA is actually a difficult code base, it's incredibly coupled.

> I'm asking about docker specifically - why is it needed?

It is needed to run a postgres database which is needed for the lobby server. If you want to run the headless bots, they need to connect to a lobby server. FWIW, we used to require you to install a full postgres database before we switched to a docker container.

If you are interested in the background of why no in-memory database, this thread was where we decided to use a real database: https://github.com/triplea-game/triplea/issues/1758; the real-database is also helpful as running a lobby server on an in-memory database for manual testing introduces additional testing, so it's unlikely anyone could only ever need an in-memory database.

> Why can't things be self contained in the codebase?

It would be a nice feature to have gradle to start up the needed docker database, in which case it would seem more self-contained. It is nice as well that gradle installs dependencies for you. That means the requirements of TripleA for development are just Java and Docker (and gradle is installed for you).

**Comment by asvitkine** [comment]
Thanks, that helps explain things!

I still think it's helpful to run targeted tests. If I'm changing gameplay code, then I shouldn't need to run lobby server tests. Presumably the lobby server doesn't run any gameplay code?

On the other hand, the CI infra should still run all tests, but that part seems to have been resolve now.

**Comment by DanVanAtta** [comment]
> I still think it's helpful to run targeted tests.

Indeed, as a final verification before you push a PR, it's useful to run the full battery. If you set up travis to build your fork, you can theoretically use Travis to do that, but you'll want to be set up to run locally to debug any failures you see.

> Presumably the lobby server doesn't run any gameplay code?

The new http-lobby is pretty well split, it should be pretty obvious as any code that the lobby depends on will be in http-clients. The "old" network code that uses a custom Java RMI implementation, still used by the game-bot, does invoke 'gameplay code'. Before a recent addition with the number of RMI methods you could have broken that code by re-ordering methods. There are still brittle aspects to it, and it's not always clear that you are invoking something that is actually on a network path.

An early design principle of TripleA was to make network interactions transparent to all game code and for a network game to "look" like a single player game. In some ways that was a good design. Where things fall apart is there was very little discipline for modularity, code tends to be 'plopped' in instead of being placed into an isolated module, any needed code is either copy/pasted or just made public and invoked directly. Hence, in many respects we have a [BBOM](https://en.wikipedia.org/wiki/Big_ball_of_mud)

**Comment by DanVanAtta** [comment]
Side comment, perhaps it's more evident why we recently rewrote the lobby to use HTTP, and why I think it's a very high priority for 3.0 to re-write the bots and P2P network code to use websockets. The http migration generally makes network interactions easier (UnifiedMessenger is difficult to use correctly and creates brittle coupling). 

For more context, there are still methods in `Player` that are invoked by network, changing those will break network. Recently, if still not the case, there is network code that invokes the sound player. To make matters worse, AFAIK there is no automated testing of any of these interactions. We do have a 'smoke' test that will at least connect a bot to a lobby and verify that works; but we do not have anything deeper that actually starts a game and verifies those interactions.

**Comment by DanVanAtta** [comment]
@asvitkine closing this topic out, with a docker daemon running, you're able to get `verify` to run to completion on a master branch?

**Comment by DanVanAtta** [comment]
Just noticed this that might horrify you @asvitkine, when launching a single player game locally:
```
Apr. 13, 2020 10:48:47 A.M. games.strategy.engine.message.UnifiedMessengerHub messageReceived
INFO: Adding endpoint: games.strategy.engine.message.unifiedmessenger.HasEndPointImplementor:games.strategy.engine.framework.ServerGame.DELEGATE_REMOTE.edit, from: Node(name=dummy, address=dan-xps/127.0.1.1, port=0)
```

That *is* the server code firing up. That means that all games are actually tied up with the network code, a local player game is actually a single player network game. It should be everything but the port being open missing.

So in essence, the design is to send all calls through a messenger that will then "fork" the messages to any network clients. In this way there is "transparency" about network communication. We have the AI code mixed in to the gameplay code, which is in turn all going through paths that can kick off network calls. 

TripleA is deceivingly difficult to work on.
