### ISSUE TITLE
Moderator Toolbox Game info is missing.

### ISSUE THREAD

**Issue by prastle** [triplea-game/triplea#6241]
**How can the problem be recreated?**
As requested I am separating the issues I found into multiple bugs.
  Join the pre release lobby and host a game.  As a moderator right click on the hosted game or a bot.

You will notice that in 1.9 stable a moderator sees the host info button.  It is missing from 2.0 as well as the ability to use the many functions and view who is inside a bot.  I do not believe screen shots of this would be appropriate.  This does need to be fixed..

**When the problem is fixed, what should have happened instead?**
The moderator should be able to view the host  info as well as what players are in the bot or host.
**Which Engine Version are you using?** 
2.0.18790

**Comment by DanVanAtta** [comment]
This is not something to fix, it's intentionally not implemented. The connectivity between lobby and headless bots broke in a pretty horrible way.

Why is it needed to view players in a game/host? What's the use-case for it?

**Comment by prastle** [comment]
Anon users that have been banned like to direct connect to bots and private hosts to avoid lobby bans
Also the banning system does not remove a player from a bot or a host,  Next point and issue.  thus we need a way to find them

**Comment by DanVanAtta** [comment]
> Anon users that have been banned 

There has *never* been a difference between banning an anon user and a registered user. Email address is the difference between the two, banning has never used email address.

> Anon users that have been banned  like to direct connect to bots and private hosts to avoid lobby bans

In 2.0 you cannot direct connect to a private host or a bot when banned. Either game checks with the lobby when new players are joined to see if the player is banned, and if so rejects them.

> Also the banning system does not remove a player from a bot or a host,

That *should* be the behavior in 2.0. If not it is a recent regression.

**Comment by prastle** [comment]
Then that is the issue.  it is not removing the banned player instantly.  I can't say Yama and I waited for 10 min to see lol.

**Comment by prastle** [comment]
The banned player sits in the bot for longer than 5 minutes
we did not stick around to test how long

**Comment by prastle** [comment]
Also with out being able to see whom is in a bot without joining it is a nec thing

**Comment by DanVanAtta** [comment]
The player removal should be pretty quick.
I just tested it out, it was near instant.

![Screenshot from 2020-04-13 18-40-35](https://user-images.githubusercontent.com/12397753/79176912-5877fd80-7db6-11ea-9dc3-e9594fbdce62.png)


One thing to note, the game is not closed, but you should be disconnected. You can chat, but it should not be visible as you are not actually connected. The game is left open so you can get a save before closing.

> Also with out being able to see whom is in a bot without joining it is a nec thing

Somewhat agree, but it's very expensive to implement. Given you do not need to search for players anymore to know which rooms to ban them, it should much less needed/important than it was.

**Comment by prastle** [comment]
I can live with that answer ( I am not selling it to the rest of the mods lol).  I guess we shall see how well it works close this issue.

**Comment by prastle** [comment]
Reopening to clarify the missing/incorrect player info.  
When right clicking with toolbox function to activate the show players function it displays everyone who has ever joined the bot since it restarted? not the current players in the bot.
![2021-01-16 (3)](https://user-images.githubusercontent.com/17258293/104829309-8526dd00-5840-11eb-9382-78be5c94d861.png)

**Comment by prastle** [comment]
Bump

**Comment by Cernelius** [comment]
I believe this is a triplicate of:
https://github.com/triplea-game/triplea/issues/6969
https://github.com/triplea-game/triplea/issues/7804

I would close two of these three issues, but I'm not sure which ones.

**Comment by DanVanAtta** [comment]
My 2 cents, we want issues that 100% up to date without any additional details in them (any unnecessary but useful additional details provided by links). To that extent, this task would be closed and we otherwise pick one of the other tasks (earliest)

**Comment by DanVanAtta** [comment]
Lets use https://github.com/triplea-game/triplea/issues/7804
