### ISSUE TITLE
The Bad Words table does not function.

### ISSUE THREAD

**Issue by prastle** [triplea-game/triplea#6242]
**How can the problem be recreated?**
Join the new pre release lobby as a moderator and add a bad word to the table.  Rejoin anon as the bad word after refreshing and making sure it is there.  It allows you to join.

**When the problem is fixed, what should have happened instead?**
It should not allow the bad word to be used in a login name or at minimum the same word.
**Which Engine Version are you using?** 
2.0.18790

**Comment by DanVanAtta** [comment]
I could not repro this @prastle . I see there is one bad word in the table on prerelease, joining as that word, upper case, or suffixed with 123 all reject the login.

**Comment by DanVanAtta** [comment]
Is there confusion about whether existing players in the lobby should be booted? Adding a 'bad word' does not impact already connected users, just new players joining, anon or registered.

**Comment by prastle** [comment]
HMM Then maybe you fixed it I tested that with Yama a day or 2 ago 1 min

**Comment by DanVanAtta** [comment]
Yes, it was fixed pretty recently : )

**Comment by DanVanAtta** [comment]
https://github.com/triplea-game/triplea/issues/6173
