### ISSUE TITLE
Notifications are hidden by Battle window

### ISSUE THREAD

**Issue by ZjelcoP** [triplea-game/triplea#6248]
**How can the problem be recreated?**

-2.0.18816
-Win 10
-Play the Tutorial until you get to battles.

Playing the Tutorial there are several notifications.
The battle window now hides the notifications. You are unable to read them, the battle window always stays on top. Only way to proceed is to Space bar through the notifications without reading them.

Notifications should have priority over battle window.

Also when completing Combat moves and there is only one battle this battle immediately starts. You no longer have the option to start it yourselves. This may be intentional but I'm not sure I like it and it definitely doesn't help the Tutorial.

![afbeelding](https://user-images.githubusercontent.com/13902879/79275010-b7687000-7ea5-11ea-8e8e-f99662047210.png)

Cheers Zjelco

**Comment by beelee1** [comment]
bummer was it hoping it was fixed. Sounds like #6132 . If u move window is the other one behind it ?

**Comment by DanVanAtta** [comment]
@beelee1 have you been able to reproduce the problem of #6132? This might be a different issue as the notification windows are not spawned by the battle proper.

**Comment by DanVanAtta** [comment]
Crud, I'm not seeing this problem on my computer.

@ZjelcoP could you double check with the very very latest just in case I had the version number wrong and this is actually fixed.

When you move the window that is behind the battle window, does it stat to display on top of the battle window, or does it *always* appear behind the battle window?

**Comment by DanVanAtta** [comment]
I'm trying a slightly 'blind' fix for this with: https://github.com/triplea-game/triplea/pull/6251

Not being able to repro really hurts the chances it'll get properly fixed. :crossed_fingers:

**Comment by ZjelcoP** [comment]
Issue hasn't changed with 2.0.18827

-Battle window stays on top even if you move the notification around.
-The Battle window cannot be moved while a notification is active.
-A small size notification is impossible to view (fully hidden by battle window) and can only be closed by space bar.
-A lager notification can be grabbed by the edge and moved to a corner to view, however battle window will stay on top.

Also the second issue is starting to bug me more:
_Also when completing Combat moves and there is only one battle this battle immediately starts. You no longer have the option to start it yourselves. This may be intentional but I'm not sure I like it and it definitely doesn't help the Tutorial._

I like to have a local view of the map before starting a battle. It now feels like everyone is in position and just when you want to give the order to attack you find everyone already rushed off.
I can see why it might have been put in for sake of efficiency but please make it optional under combat settings.
