### ISSUE TITLE
Can't host with bot in 18816

### ISSUE THREAD

**Issue by beelee1** [triplea-game/triplea#6249]
**How can the problem be recreated?**
when i click on bot and hit host it lets me select a game from my dl maps and as soon as it starts some blue error message flashes real quick and it kicks me back to the lobby.

**When the problem is fixed, what should have happened instead?**
it should allow me to join like it used too.
**Which Engine Version are you using?** 
18816 pre i am on linux
**Screenshots** 

**Zipped Save Game**

Silver was able to host and I could join his game. I didn't ask but would guess he's probably on windows. i asked pras to try but haven't heard back yet.

@DanVanAtta can u try with linux ? It may be on my end but the other pre's worked so idk

**Comment by beelee1** [comment]
just heard from pras and he can host with bot. He's on windows

**Comment by beelee1** [comment]
also sound has been kinda intermittent. sometimes it works. just in lobby

**Comment by DanVanAtta** [comment]
OS should not matter. We actually have an automatic test that verifies a bot can connect to lobby every time we do a prerelease. If anything, it'd be more reliable on linux than any other OS as that is what we test on.

> when i click on bot and hit host 

How do you mean by this @beelee1 ? You can only join bots, which host button are you referring to?

**Comment by DanVanAtta** [comment]
@beelee1 if you would, please see if the error message is printed to console, that might give us a lead on this.

**Comment by DanVanAtta** [comment]
(open the console via game preferences > game > show console = yes)

**Comment by prastle** [comment]
I believe he is calling a private game host a bot @beelee1 ? @DanVanAtta .   Yes I can host a private game.  I believe the bot issues @RoiEXLab  was rewriting somewhere else?

**Comment by beelee1** [comment]
@DanVanAtta  yea so if i try to join bot that already has game it does the above weird stuff. It never actually starts a game so can't access debug.

If i start game from bot with no game it works fine and silver was able to join as well. So... I guess that's it and has always been this way and I didn't know. I'll close but wait for a response or you can close :)

**Comment by beelee1** [comment]
well unfortunately it's still acting weird. This may/probably just a bot thing in general, but it says "map options" are selected but they don't work. Anyway, this seems kinda back burner and figure it out later. i'm an inexperienced bot user and I know linux or my end may have issues with it. I wouldn't close though.

**Comment by DanVanAtta** [comment]
> How can the problem be recreated?
when i click on bot and hit host it lets me select a game from my dl maps and as soon as it starts some blue error message flashes real quick and it kicks me back to the lobby.

The bot/game staging screen can take a while to render. I believe in 1.9 instead of the UI blocking, you should see the main screen for a few moments, perhaps long moments, then the bot staging screen should show. I believe it's a known problem/bug that if you have a really long pause, and select a map from the intermediate main screen then you'll get an error when the staging screen actually loads. Does this problem "go away" if you wait long enough after joining a bot for the staging screen to load @beelee1 ?

**Comment by beelee1** [comment]
@DanVanAtta I looked at this again using 19225 pre. i was able to get it to kinda work. I think my bot inexperience was probably the biggest issue and as you said above there were some known issues that I remember Roi mentioning as well. At any rate here's what I did on latest test.

Join lobby go to "Join" game not "Host". From there it takes back to startup page and i select which game I want and put it in the little window.

![Screenshot from 2020-05-07 07-56-38](https://user-images.githubusercontent.com/24382682/81297058-637e2080-9038-11ea-96ce-d2bfc464e453.png)
 Then I fill out "Map Options" then choose the Players and everything works fine except for this:

![Screenshot from 2020-05-07 07-46-00](https://user-images.githubusercontent.com/24382682/81297312-afc96080-9038-11ea-8613-78a7e905baba.png)

![Screenshot from 2020-05-07 07-48-26](https://user-images.githubusercontent.com/24382682/81297332-b657d800-9038-11ea-8a0c-534dbde4f18f.png)
 For some reason it takes me to "Map Version" 1.88.0 (3rd image) when I started out on 1.91.0 (2nd image)
So idk what's up with that. Otherwise I think it's just my bot and Lobby inexperience combined with known issues.

**Comment by beelee1** [comment]
Oh yea, to answer your above question, waiting didn't make a difference. I can't hit debug on the console because the game never actually starts. Takes me back to start page. That was hitting "Host" and not "Join" though, so kinda two different things.

**Comment by DanVanAtta** [comment]
@beelee1 will close this for now, please re-open or cut a new issue if you would if you continue to see problems
