### ISSUE TITLE
Aircraft casualties should take those with least move pts

### ISSUE THREAD

**Issue by stevebakes** [triplea-game/triplea#6256]
Aircraft lost in battle should take those with the least movement points remaining. Not sure if currently it is random or if it is taking those with most mvmt points.

**How can the problem be recreated?**

(Use attached save-game to shortcut steps 1-3)
1. Start WW II v3 1942
2. Do something for Japan and Russia
3. On Germany's turn, attack SZ12 with destroyer from SZ13, FTR from France, FTR from Germany.
4. Run a round of battle, if Britain hits take a fighter. If there are 2 hits by Britain take the destroyer as well, so that 1 FTR remains. If Britain dies and hits nothing, start again :-(
5. After battle, remaining fighter SHOULD be the one from France (2MP) and the destroyed fighter should be the one from Germany (1MP remaining). In Non-Combat move, fighter is unable to return to France because the wrong fighter was removed.

Engine 2.0.18816. Problem occurs on both Linux and Windows.
 
[2020-4-15-World-War-II-v3-1942.zip](https://github.com/triplea-game/triplea/files/4480116/2020-4-15-World-War-II-v3-1942.zip)
**Zipped Save Game**

**Comment by panther2** [comment]
Your issue is valid. Thank you.

It is not a duplicate but another consequence of casualty selection as discussed in #4133.

**Comment by DanVanAtta** [comment]
Is there a reason/case for us to split out the casualty selection by movement points? I'm wondering about any kind of unit type. We split the different countries already, it seems if you have identical units then you do in fact always want the least movement unit to be taken as a casualty.

**Comment by stevebakes** [comment]
I don't believe there is a need to split by movement points in the casualty selection dialog, just remove the units with least MPs when that unit type is selected as a casualty.
Only relevant for unit types that are able to move after combat. Non-air units can't move after combat in A&A, I don't know if other game variants have different rules.

**Comment by panther2** [comment]
@DanVanAtta Correct, that is one of the conclusions as discussed in #4133 :

>When it comes to selecting casualties from within groups [of air units] it appears to be reasonable to implement a sort of "autoselection". As the player would always choose to lose the plane with the least remaining movement points, this might be handled automatically by the engine, if wanted, IMHO.

**Comment by panther2** [comment]
I really recommend to read #4133 for the context of this issue. It is worth the time.

**Comment by DanVanAtta** [comment]
There might be some quick fixes, but we probably want to rewrite how casualty selection is done.

FWIW, AA casualties are computed differently from this scenario, it is an independent problem for now.

**Comment by Cernelius** [comment]
@panther2 Shouldn't you be allowed to select same type of air with more movement left first, if you so wish?

>Is there a reason/case for us to split out the casualty selection by movement points? I'm wondering if this is a generic rule for all unit types. We split the different countries already, it seems if you have identical units then you do in fact always want the least movement unit to be taken as a casualty.

You might want to try to have units with lower movement surviving if that would, then, not oblige you moving a carrier to land them. However, the situation is so marginal that I would agree going ahead always selecting lowest movement first, when you would have the choice.

**Comment by DanVanAtta** [comment]
I'm starting to think the most feasible fix here is to split out the movement of units:
- avoids massive re-write. 
- could be useful recall to players of how many movement points are left

**Comment by prastle** [comment]
bumped
