### ISSUE TITLE
Introduce ruleset object - GameData.ruleSet

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#6264]
For consideration, and design review/comment:
- thinking to create an object `RuleSet` that would be attached to `GameData`
- the backing data structure of `RuleSet` would be a string->string map (very similar to game data game properties)
- we would not allow direct access to rule set data, but provide query methods to check if various rules are set and potentially enumerate return values.
- the rule set map would provide a centralized place to gather rule settings, we'd move all static getter methods and computations to rule set
- the rule set object would be a staging ground for allowing rules to be defined per-game
- all map / game rules would find their way and be exposed from rule set
- all rules could get presets/be computed; this gives us the option to define "this is the v3" ruleset and still allow players to turn on/off any rules they would want

If we introduce the map data structure now, it can be expanded later without breaking save game compatibility.

For example:

```
RuleSet
   Map<String, String> := {
                      "air_can_fire_at_subs" : "true", 
                     "bombard_casualties_can_fire_back" : "true",
                     "v3" : "true" }
   
   boolean canAirFireAtSubs();
   boolean canBombardCasualtiesFireBack()
   boolean someV3Rule() {
         return someV3Rule.isTrue() || v3.isTrue();
    }
```

One thing I've also been pondering whether it makes sense to use ID values for rules with the intent to use IDs in game data in the future. This way any label we have would just be a human readable and we could rename it later if we chose to.

In this case we could rename the rule labels without it needing to break/change how save game data is persisted. The 'getter' methods would still be the same no matter if we used string identifiers or numeric identifiers.

Thoughts?

**Comment by RoiEXLab** [comment]
No objections, sounds good
