### ISSUE TITLE
Wild Unit Help Rendering

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#6273]
**How can the problem be recreated?**

- start single player game on Total World War: December 1941 3.0
- select help > unit help
- wait for "loading data prompt"
- observed flicking odd rendering, see screenshot below:

![Screenshot from 2020-04-16 22-20-37](https://user-images.githubusercontent.com/12397753/79534877-ab5ce980-8030-11ea-8178-c4ee8ef3178e.png)

**Comment by RoiEXLab** [comment]
@DanVanAtta I'm not observing any kind of rendering issue on my machine

**Comment by ron-murhammer** [comment]
Yeah, not seeing this either.

**Comment by DanVanAtta** [comment]
Cool, though we're left not knowing what the problem is and how to reproduce it, the fact we don't see it on some machines does not mean it does not exist. The data points are perhaps useful.

You are both running windows @RoiEXLab @ron-murhammer ?

**Comment by DanVanAtta** [comment]
I do *not* see this problem on 8171.

**Comment by DanVanAtta** [comment]
On latest pre-release install or 13066, I do not see this issue, only when building from source. Seems that it's most likely a java version problem.

Not going to be user impacting, I think the ROI to further investigate this is probably low.

**Comment by RoiEXLab** [comment]
Yes, I'm using Windows
