### ISSUE TITLE
In WWII Revised, deselecting units with right click, or ESC key, does not work

### ISSUE THREAD

**Issue by swurzer121** [triplea-game/triplea#6279]
**How can the problem be recreated?**
In Revised, right click on any unit, then right click, or hit ESC key
This used to deselect the unit.  It no longer does so.

**When the problem is fixed, what should have happened instead?**

**Which Engine Version are you using?** 

**Screenshots** 

**Zipped Save Game**

<!--
Please zip and post a save game to this bug report!

[2020-4-17-World-War-II-Revised_deselect_unit_bug.zip](https://github.com/triplea-game/triplea/files/4494958/2020-4-17-World-War-II-Revised_deselect_unit_bug.zip)

**Comment by DanVanAtta** [comment]
This update should help the right click case: https://github.com/triplea-game/triplea/pull/6393

It might not be that right click is broken in 2.0, 1.9.0.0.13066 also had a problem.

If you do not move the map via right click drag, right click deselect should work. But, if you right click drag the map, then select a unit, you'll need to right click twice to deselect the unit. This was a bug in 1.9.0.0.13066, #6393 should fix this so if you select a unit and then right click - the unit will be deselected.

**Comment by Cernelius** [comment]
Oh, I've been annoyed by this for a rather long time but I've never been really sure what was that. Initially I thought it was just me moving the cursor by like 1 pixel unintentionally while right clicking, thus having the drag behaviour instead of the deselect one.

**Comment by DanVanAtta** [comment]
Yeah, if there were ever a way for the game to gaslight you... :grin: 

https://github.com/triplea-game/triplea/pull/6394 will fix the escape key behavior in 2.0 and have it working again.

As fixes are now in flight, will close. Please re-open or comment if there is more to this issue than what either #6393 or #6934 fixes.

**Comment by swurzer121** [comment]
👍
