### ISSUE TITLE
Bot Chat History Unavailable to Mods

### ISSUE THREAD

**Issue by prastle** [triplea-game/triplea#6283]
**How can the problem be recreated?**
Right click on any bot and select the missing chat log function.  I still believe that chat log functions will be required by all moderators in the future as long as we have bots.  Even if all other functions are semi available in the new section being unable to at least pull the chat logs will result in a "He said! She Said! Free For All!"  Since proof is no longer available.  Just my "two cents."  @DanVanAtta 
  @ron-murhammer

**Comment by DanVanAtta** [comment]
@prastle I'm planning bot chat history as a 2.1 feature.

Do we have any *evidence* how often this feature is used?

**Comment by prastle** [comment]
Every post in the bunker that came from a bot chat lol.  Yes there is evidence.

**Comment by DanVanAtta** [comment]
AFAIK I know most of those posts are from lobby chat. Can you count how often we see that perhaps over the last month to get a sense?

**Comment by prastle** [comment]
@DanVanAtta it is not widely used NOW! because they know we can.  If you remove it … things will go badly.

**Comment by DanVanAtta** [comment]
"remove" is relative, it just has not been rebuilt. I suppose that is the same thing though from your perspective.

**Comment by prastle** [comment]
Months of arguments when the bots came out were solved by posting the chat visibly.  At times even in the lobby for all to see.  This will remove completely our ability to see if "George" is joining and crashing bots etc etc or flaming

**Comment by prastle** [comment]
Up to you just giving you fair warning

**Comment by Cernelius** [comment]
I question the opportunity of releasing the lobby at all until this feature is readded.

For as long as there will not be an easy way to get the chat log of bots, I tend to think it would be advisable updating all the rules (in forum) as to make bots exempted from any of them (just like private hosts).

**Comment by Cernelius** [comment]
I believe the current rules, subjecting bots to the same rules as the lobby and more, are inherently linked to the ability, for every moderator, of getting the chat log of the same. Therefore, one would make largely no sense without the other.

**Comment by DanVanAtta** [comment]
We can do chat history as a compatible update. The big question is whether we want to push 2.0 back waiting for it, or are okay getting chat history post-2.0.

**Comment by Cernelius** [comment]
If nobody (with the authority to do so) is going to update the rules to make them any consistent with a situation in which moderators cannot get the chat log, the only reasonable thing to do is holding off on releasing 2.0 until this function is available.

**Comment by DanVanAtta** [comment]
@Cernelius the rules have issues but are not the determining factor:
- should be fast to update, it's the least laborious of just about anything
- are & have been out of date for some time, they need a refresh, which is more laborious
- are rarely read if ever by players, which is perhaps another problem.

The really desired thing here is to know how often this functionality is used. It does not seem we can get that data reliably and the assumption is then that it's probably used a lot more than it actually is. I personally suspect it's essentially never used, but I could also see how it's difficult to resolve situations otherwise when chat history is needed.

**Comment by Cernelius** [comment]
If you are asking me (or anyone) if what @prastle said is correct, I confirm.

**Comment by DanVanAtta** [comment]
@Cernelius @prastle I was hoping a bit we could get the decision out of the anecdotal territory, the data may tell us strongly one way or another.

**Comment by prastle** [comment]
@DanVanAtta there is no DATA!  Since mods don't have to chase bots anymore BECAUSE the players know we can view their chat logs when they act like donkey's towards each other...  Thus it is not used much NOW.   If it is removed all bots will be private hosts as I explained elsewhere.

**Comment by prastle** [comment]
Mods will not physically join a bot to sit and wait for a person to continue their rants in order to prove a complainents point of view.  Nor will they attempt to search for a culprit in the bots physically with the host info removed.

**Comment by DanVanAtta** [comment]
Implemented in: https://github.com/triplea-game/triplea/pull/6409

**Comment by prastle** [comment]
Reopening to add some further issues tied to this

**Comment by prastle** [comment]
To clarify this a bit more the old toolbox chat logs also listed "George has joined" and the time etc.  It also showed days worth of chat history not just the current game or perhaps its the past few hours?

**Comment by prastle** [comment]
![2021-01-16 (5)](https://user-images.githubusercontent.com/17258293/104829584-3dee1b80-5843-11eb-957c-535c040cc0f5.png)
