### ISSUE TITLE
Code convention: favor 'var' when type information is redundant to the variable name

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#6290]
Proposing a convention/guidelines on our usage of Java 9 `var`

The following is a really good guide: https://openjdk.java.net/projects/amber/LVTIstyle.html

> Omitting an explicit type can reduce clutter, but only if its omission doesn't impair understandability. The type isn't the only way to convey information to the reader. Other means include the variable's name and the initializer expression. We should take all the available channels into account when determining whether it's OK to mute one of these channels.

In short, recommending we favor `var` when:
- variable is partially or fully redundant to the type
- hiding ugly nested generic types (which perhaps are better created into a data type object, though var is a potential tool in our toolbet)

### Good
```
var diceRoll = new DiceRoll(..)
var territoryImage = new Image(...)
var unitCount = unitsLeft() - unitsHit();
```

### Not Good
```
var hits = new DiceRoll(...)
var power = new  HashMap<Unit, Integer>();
```

## Collections

Plural names on collections can be fine. EG:

```
var units = new ArrayList<Unit>();
```

If the underlying 'non-var' version is clearly a collection already, the var variant is likely okay. Map types should be considered a bit more as often maps need to be carefully named. For example:

```
var units = new HashMap<unit, Integer>();  // << not well named
```

Something that describes the key to value relationship is generally going to be more clear:
```
var unitHitpoints = new HashMap<unit, Integer>();
```

**Comment by RoiEXLab** [comment]
Seems like a good guideline to me 👍

**Comment by DanVanAtta** [comment]
Added to convention list: https://github.com/triplea-game/triplea/wiki/Java-Code-Conventions#guidelines-for-var-usage-httpsgithubcomtriplea-gametripleaissues6290
