### ISSUE TITLE
Commit Comment Standards

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#6316]
I feel like we could use a standard for commit comments. Do we agree?

Commit comments will ideally make our history useful. If you look at `git log`, the last 'n' changes should hopefully all make sense and not be noise. It'd also be great for the comment to tell you enough where you don't need to see which files have changed.

In this case, the following commit comments examples would be insufficient:

- "fix bug"
- "fix transport bug"
- "formatting"
- etc...

A standard should indicate what we expect to be in a commit comment. It is a philosophical opinion on how useful commit history is in general. Some feel it's not useful, so the comment barely matters, others feel that it is potentially useful and for a very long time after the fact.

My 2 cents is I do not want any important context in a PR that is not in a commit comment. Having to look at PR discussions to understand code I think is quite bad; that's a minimum I'd certainly want to avoid. 

How do others feel?

**Comment by RoiEXLab** [comment]
I agree that some comit messages are less then ideal, but often times I don't really feel like an auto-formatting commit needs extra description

**Comment by DanVanAtta** [comment]
Here is an example:

```
  Simplify code (#6299)
   
    * Simplify code
    
    * Auto-Formatting
```
To understand what was simplified you need to look at the PR or the diff. Having to go to some other system to understand this is a rule of thumb for something to avoid. If you have 30 commits, and each one you need to go look up in another tool, you are not going to be efficient. It's evidence that we're failing to capture context in the git history where it arguably belongs and is the reason for it. Said another way, instead of using git history what it is for, we're using github PRs for that purpose.

Specifically, the messages not in commit but in a PR are for the reviewer and only the reviewer, at the time of review. The messages in the commit is the stuff that lives on with the code and is for all future developers trying to understand the code. The rule of thumb basically comes back in, if you can't understand the code through the commit history, IMO the tool of commit history is not being used well and instead we're using our review tool in its place.

With that said, we do have a large number of quite good quality commit messages.

It would be great IMO to get more consistent about it. (ESLint)[https://github.com/eslint/eslint] is a fantastic example of a well done open-source project. For example they have a very spelled out [commit standard](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint)

**Comment by RoiEXLab** [comment]
I have thought about this in the meantime and I realised a similar thing.
I think most of the time I just want to make a commit without thinking about what this commit actually changes, but I never come back to actually clarify what actually changed.

**Comment by DanVanAtta** [comment]
Part of the issue is different audiences at different times.
A high level commit of what changes is useful, but you don't want to restate the diff either. A comment to guide someone to making sense of the diff is worthwhile. Perhaps most important is the reasoning and 'why' behind a change. That is a kind of context that is useful to have in history.

**Comment by DanVanAtta** [comment]
An interesting link that proposes a standard commit comment and ties into semver:

https://www.conventionalcommits.org/en/v1.0.0/

**Comment by ron-murhammer** [comment]
Agree in general though I'll also admit I'm rarely looking over the list of commits so probably not a ton of value here. I think its hard to capture the "why" in a commit message given the length. I think a bit more about what is changed or scope is probably more reasonable and the why and details captured in the PR/references.

**Comment by DanVanAtta** [comment]
I strongly feel that PR is throw-away, it's good for the reviewer. Anything that can be written in a PR, can be just as easily written in a commit comment. For a long time now the only thing I update in PR is the checkbox, everything else is pre-populated from commit message.

From another perspective, a rule of thumb I've learned is if you need to go to an external context to understand 1 of n elements, it does not scale. Imagine if you had 30 commits to understand and you needed to go to 30 different PRs, it does not work.

I don't think including 'why' is necessarily that bad, but it is a few more minutes of typing. Here is an example:
```
commit 61ababe53ae7fa6ade82353e0d57bd584b4f5161 (tag: 2.0.19022)
Author: Dan Van Atta <dhvatta@gmail.com>
Date:   Thu Apr 30 05:48:04 2020 -0700

    Exclude test classes from code climate (#6355)
    
    This update disables code climate analysis of test code to
    avoid false-positives.
    
    Tests seem to generate more false positives than actual items
    to fix. For example, tests can often have numerous areas of similar
    code and be fine.
    
    While tests should certainly be kept clean as they are a maintenance
    burden and like prod code need to be read, understood, and maintained,
    the analysis does not seem to be generating actionable items for
    test code.
```

I like that you do *not* need to go look to a PR to understand why we removed codeclimate from test code. I'll emphasize that the above was pre-populated into a PR, it's hard to reason why you would want to type 'why' into a PR that has limited value when you can add it to the comment and have it both provide more lasting value *and* be pre-populated into a PR. It was attempted to document that a really good PR/commit comment will fully populate your PR and all you would need to do is then check some checkboxes and state what testing you have done.

The 'what' has changed can be controversial as you can see that with `git log -p` or any diff'ing tool. An overview of the changes that were done is still useful though to guide a person to know what they are looking at.

**Comment by DanVanAtta** [comment]
Seems this has hit a dead-end.

To revive the topic, this is an interesting and related write-up: https://dhwthompson.com/2019/my-favourite-git-commit

EsLint has a very interesting standard written up: https://eslint.org/docs/developer-guide/contributing/pull-requests#step-2-make-your-changes

Such a convention would go far for having [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/); but at the very least I wonder what others think about such a standard (as demonstrated by eslint).

**Comment by DanVanAtta** [comment]
Also pertinent, related to commentary and the lower value of comments in a CR as opposed to a commit or the code itself:

https://google.github.io/eng-practices/review/reviewer/comments.html#courtesy

> Accepting Explanations

> If you ask a developer to explain a piece of code that you don’t understand, that should usually result in them rewriting the code more clearly. Occasionally, adding a comment in the code is also an appropriate response, as long as it’s not just explaining overly complex code.

> Explanations written only in the code review tool are not helpful to future code readers. They are acceptable only in a few circumstances, such as when you are reviewing an area you are not very familiar with and the developer explains something that normal readers of the code would have already known.

The above applies as well to overview statements and other explanations that are only written for the PR.

**Comment by DanVanAtta** [comment]
I think the best outcome here is to document the expectation that the PR overview be auto-completed from commit comment. It would probably be also helpful to note the expectation that we do not use review comments for code documentation and that the PR and CR process is short-lived and not intended for historical reference (use commit history or the code itself and/or design documentation to understand it instead of referring back to potentially numerous historical PRs).

Will assign to myself as a reminder to update the developer SOP documentation.
