### ISSUE TITLE
Code Review Best Practices

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#632]
I think we are starting to get away from code review best practices and should have a discussion on how to improve code reviews.

A few articles: 
http://www.developer.com/tech/article.php/3579756/Effective-Code-Reviews-Without-the-Pain.htm
http://www.daedtech.com/how-to-use-a-code-review-to-execute-someones-soul/
http://kevinlondon.com/2015/05/05/code-review-best-practices.html
https://smartbear.com/learn/code-review/best-practices-for-peer-code-review/

Might be worth adding a few good links to our coding standard wiki at one of these pages:
https://github.com/triplea-game/triplea/wiki/Code-Guidelines
https://github.com/triplea-game/triplea/wiki/Code-Reviewers-and-Pull-Request-Guidelines

**Comment by DanVanAtta** [comment]
Automating a test coverage report and complexity analysis would help. Couple potential candidates (and we could potentially use both too as well):
- https://www.codacy.com/, looks pretty complete. IMO let's give it a demo.
- https://scan.coverity.com/travis_ci - static analysis, probably also worth a demo. Requires a bit more setup than codacy
- (code climate : does not support java :-1: )

**Comment by DanVanAtta** [comment]
I updated the code review process page with some feedback guidelines:
https://github.com/triplea-game/triplea/wiki/Code-Reviewers-and-Pull-Request-Guidelines/_compare/792899f287c75108e3cc2af75ab296576dade815...859096c2189542238f403db6139036a6ba31925e
Please feel to add to it, or revise.

**Comment by DanVanAtta** [comment]
A couple of the articles linked suggested 'self-commenting' on PRs to point out the interesting changes and reasoning. I think we should adopt that. It would help for both small and larger PRs, and particularly for small ones which tend to be the most complex.
