### ISSUE TITLE
Organize Issues (sweepboard.com)

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#633]
This looks kind of promising to provide more than just label functionality: http://sweepboard.com/

**Comment by RoiEXLab** [comment]
Looks promising to me...

**Comment by DanVanAtta** [comment]
Sweepboard needs access to the org it appears.
I have no objection to demo'ing it.

@ron-murhammer , are there any specific processes you see taking place with sweep board that are not taking place now? Asked another way, how would sweep board help our process? 

One thing that has been lingering is a discussion of how to label. I've found it's best to try and keep issues down to exactly one label. Extra labels should be for dimensions which are completely unrelated. For example, one label could indicate state, "received, in-progress, in-review", while another would be the type of issue. 

There are lots of grey lines, but clearly we should avoid "bug" + "UI bug" as labels.  Namely multiple labels should be considered a taxonomy smell.

**Comment by ron-murhammer** [comment]
@DanVanAtta Yeah, personally I think the biggest problem right now is we have 80 some issues but its hard to tell what is in progress and priority of them. It would be great to know which ones could use my input and if I have time which ones are high priority to tackle.

**Comment by DanVanAtta** [comment]
'high priority' and 'release blocker' I think satisfy knowing which ones to take on first.

'discussion' at this point i think is the most useful label. Those are the items where the task is not clear, and some input is needed. Once the task becomes clear, and it is a matter of someone executing on it, then we remove the discussion label.

In progress we had a label for, but it was not used in practice. We have unofficially been using issue assignments to indicate in-progress. That I think could continue working for the time being. If someone with non-write wishes to be un-assigned, it's easy for them to request it (same for requesting assignment).

**Comment by DanVanAtta** [comment]
So 'discussion' effectively indicate which issues need input.

**Comment by DanVanAtta** [comment]
@RoiEXLab  @ron-murhammer  - what are the thoughts on http://sweepboard.com/ in the end? Would you recommend we use it?

**Comment by RoiEXLab** [comment]
Well I didn't use it before, but of sweepboard allows me as a contributor without write permission to label my own issues etc. I would give it a try.

**Comment by RoiEXLab** [comment]
@ron-murhammer @DanVanAtta are we stil going for this?

**Comment by DanVanAtta** [comment]
This is stale, what are the next steps on this issue?

**Comment by ron-murhammer** [comment]
Going to try out ZenHub which can be discussed here: #1059
