### ISSUE TITLE
TripleA Ladder challenge time

### ISSUE THREAD

**Issue by KJRNorway** [triplea-game/triplea#6331]
andrewthree challenged me, KJRNorway, to a New World Order Ladder game. The time was set to 1AM, but it did not say anything about time zone. I accepted it and then the time changed to 3 AM, and still no time zone indication.
Please make sure there is a time zone accompanied with times in TripleA Ladder challenges and make sure the time does not change when the challenge is accepted.

**Comment by prastle** [comment]
The challenge section of the ladder does not really work.  As I have said elsewhere I would recommend players just challenge on the forum or in the lobby.  It only allows 1 challenge and has some other issues as well.
