### ISSUE TITLE
Unable to quit hosted game when lobby is down

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#6336]
### How can the problem be recreated?

- Host a game on lobby
- Disconnect (turn off) the lobby
- Click the 'Quit' button > it fails with error message and does not allow for the hosted game to quit.

The error message is for a failure to invoke the "removeGame" endpoint on the server. As the server is not listening, this is expected.

### What is an expected fix?

 The game client should silently ignore this error and allow for the game host window to close.

### Which Engine Version are you using? 

2.0
commit bdaccd4ee91632ab7bfddde66a56778de4d990a1 
Date:   Sat Apr 25 18:01:40 2020 -0700

### (Optional) Additional information

![Screenshot from 2020-04-25 20-33-57](https://user-images.githubusercontent.com/12397753/80296994-1f377a00-8734-11ea-8455-4c7170a91e36.png)

**Comment by prastle** [comment]
I can confirm this has happened to me as well.  @DanVanAtta
