### ISSUE TITLE
Routes are not drawn correctly

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#634]
Routes are only drawn with a curve, when the route comes from or goes into a sea territory.
Also the "curve" shouldn't be longer that the distance between the 2 route joints
The behavior in general is weird... Just take a look at this screenshot...
![screenshot TripleA example](https://cloud.githubusercontent.com/assets/8350879/14936457/8ab87a72-0eed-11e6-9e94-04de0e1bea17.png)

**Comment by RoiEXLab** [comment]
I'm trying to fix this myself by implementing a new algorithm using the commons-math library...
I know, that the implementation of new libraries has to be discussed first, but I want to try if this works first...
But form some reasen when replacing MapRouteDrawer.java with [this Code](https://gist.github.com/RoiEXLab/5907b89487b3a465e4b2ca4b4a207859), I'm getting a NullPointerException.

Can anyone tell me why that is!?!?
I think I wasted 2 hours so far wihtout result...
@triplea-game/devs

**Comment by frigoref** [comment]
Can you at least explain where the exception occurs?

**Comment by RoiEXLab** [comment]
Thats the problem... It seems that the points Array is null somewhere, but i have no idea where.

**Comment by frigoref** [comment]
What does the error stack say? No line number?
Could you please rework the method so it is easier to read? Move common logic to private methods, add comments that explain what the code is supposed to do, etc.

**Comment by RoiEXLab** [comment]
@frigoref Thanks for helping...
I added comments explaining what the different things are supposed to do...
Just look for the //start and //end and you'll find my code. My created functions are at the end of the class.
I' trying to create a [Spline Interpolator](https://en.wikipedia.org/wiki/Spline_interpolation) to get a nice looking curve. The problem is, that the interpolate method of apache commons math only accepts valid f(x)=y functions -> x has to increase all the time... Therefore I have to split the y coordinates and the x coordinates into 2 seperate functions with x as the "index". The NullPointer happens, when I'm trying to put every x coodrinate into a double array. Primitives can't be null.
I have no idea why it is null. I think it's happening at `points[i].getX();` at the end of the class.

**Comment by frigoref** [comment]
That's actually not what I meant:
A wise man told me once we should have a rough rule of 20 lines per method and the method here has about 150 lines which makes it hard to read. 
This probably results into splitting up drawRoute into pieces like
initialize
drawLine
drawImages
or something like that. 
There seems to be also many duplicated code that could be packed into own methods like the drawImage calls for cursorImage and for movementImage.

On the issue of the NullPointerException: Please recheck the points array initialization:
`//Start - My Code
      
      Point[] points = new Point[numTerritories + 2];
      // find all the points for this route
      
      //the first point should be the unit's position
      if (routeDescription.getStart() != null) {
        points[0] = routeDescription.getStart();
      }
      //the following points should be the joints of the route
      for (int i = 1; i + 1 < points.length; i++) {
        points[i] = mapData.getCenter(territories.get(i-1));
      }
      //the last point should be the cursor position
      if (routeDescription.getEnd() != null && numTerritories > 1) {
        points[points.length - 2] = new Point(routeDescription.getEnd());
      }`
The following code logic is depending on points array not having any null values, but the checks sometimes lead to null values e.g. when numTerritories = 1.

**Comment by RoiEXLab** [comment]
I know what's causing this problem... it seems, that in the diplomacy map joints connecting to land territories are doubled. Another thing for #650 .
@frigoref I changed everything in #654 check if thats more of what you expect...

**Comment by RoiEXLab** [comment]
Can be closed.
I will open an issue on the diplomacy map project for the issue on that map
