### ISSUE TITLE
Hover over Unit duplicates keyboard shortcut V & I functionality

### ISSUE THREAD

**Issue by tvleavitt** [triplea-game/triplea#6347]
### How can the problem be recreated?
Hover over a unit in the Tutorial map, hit "I". Details pop up. Remain hovered over it. Details pop up a second time in a second window overlaid on the first one, and slightly offset.

### What is an expected fix?
If details for a unit are already displayed, "tooltip" like functionality should be disabled for the unit in question, or the pop up should close the previous pop up and replace it.

### Which Engine Version are you using? 
2.0.18979 on Windows

### (Optional) Additional information
I question the need for the keyboard shortcuts "V" and "I" when tooltip functionality provides the same function, albeit the user has to wait a second or two.

**Comment by ron-murhammer** [comment]
Yeah, I'm thinking it might be best to remove those shortcuts now that we have hover over tooltips that I think are much more intuitive.

**Comment by DanVanAtta** [comment]
`I` and `V` also displays territory information when used while hovering over either a territory a unit. The tooltip and info displays funny enough are slightly different. The tooltip shows just unit info, the info display shows both territory and unit information.

I'd agree to drop the 'I' and 'V' hotkeys entirely:
- the territory information is not that helpful, you can click territory tab and get the same information. - - 'I' and 'V' are *magic* hotkeys and intrinsically not as useful as they could be. Notably there is nothing to tell most users that those are active hotekeys unless a person hunts around in the documentation and reads a block of text (which the majority of users don't do and/or will not retain).

**Comment by RoiEXLab** [comment]
@DanVanAtta I believe this can be closed#6384 has been merged
