### ISSUE TITLE
Toolbox IP/System-id search & correlation

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#6364]
Off topic Sorry but since it affects the  toolbox I will mention it here.  Is it possible to add a search function that will  look for id#s and ip #s?  if we just type in an interesting one we notice in lobby?  Or is that all corelated with the alias tab? @DanVanAtta  @RoiEXLab   Edited in to explain better If a user had two ips but used same id or vice versa etc.  Will it corelate and show all ten of them?

_Originally posted by @prastle in https://github.com/triplea-game/triplea/pull/6354#issuecomment-622076947_

**Comment by DanVanAtta** [comment]
@prastle a search for a given IP or system-id would make sense, be a logical extension of the toolbox.

When you say correlation, how do you mean? Currently the aliases tab of player info will find all matching system-id *or* IP.
By correlation do you mean transitive searches? EG, given the following pairs `<a,b> <c, b> <c, d>`; that a search for 'a' would return `<a,b> <c,b> , <c,d>` Currently a search for `<a,b>` would in that example return `<a,b> <c,b>`. I'm not sure returning/finding `<c,d>` would necessarily be really valuable and accurate (but we can think it through).

**Comment by prastle** [comment]
The best examples of what I am talking about (which I had to manually do of course) is some of these links in the watchtower.
https://forums.triplea-game.org/topic/356/bidsurfer/60
https://forums.triplea-game.org/topic/20/jimmy/29
https://forums.triplea-game.org/topic/19/spark

**Comment by prastle** [comment]
I can think of times when we had a user with access to three or more computers often with multiple ips (or for example myself ;) ) That would often create new nicks to annoy and troll that could only be found by both sys id and ip being corelated to behaviour with new name.

**Comment by prastle** [comment]
Someone with a laptop or a couple of them ;) might have 4 diff ips and a few diff system ids.

**Comment by prastle** [comment]
So to keep it simple a system id search or ip search or name search needs to find all names ever used by that system id plus all ips used by that name plus all names used by a+b etc

**Comment by DanVanAtta** [comment]
Multiple machines should still have the same IP address, different system-ids though. If someone is adept enough to change both, then you can't really be sure it's the same person unless they give themselves away. In that case I think all you can do is to re-ban their new identifiers.

For a transitive search to be useful, we would need to catch someone who is able to change both identifiers but only changed one at a time. I suspect that is going to be rare enough that the return on having a more complicated search is not there.

> So to keep it simple a system id search or ip search or name search needs to find all names ever used by that system id plus all ips used by that name plus all names used by a+b etc

Currently the player info "aliases" tab will pull that information.

**Comment by prastle** [comment]
You are correct it was a rare thing that I had to do.  
"For a transitive search to be useful, we would need to catch someone who is able to change both identifiers but only changed one at a time. I suspect that is going to be rare enough that the return on having a more complicated search is not there."
  I was mentioning now in case it was an easy addition.

**Comment by DanVanAtta** [comment]
Maybe not *too* difficult, but I think it gets more to having the right features. Features are not a one time cost, they have an upkeep cost.

**Comment by prastle** [comment]
"Multiple machines should still have the same IP address, different system-ids though. If someone is adept enough to change both, then you can't really be sure it's the same person unless they give themselves away. In that case I think all you can do is to re-ban their new identifiers."  Correct thus why as an example myself with three ips and three diff machines as well as a laptop I understand exactly what you are saying and thus how I caught the above links.  All good to close this if you wish I was just mentioning.
