### ISSUE TITLE
Weird Black Lines are drawn below some units

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#637]
Sometimes when 2 different units of the same nation are in one country there is this weird black box below them
![Example](https://cloud.githubusercontent.com/assets/8350879/14938660/22ab08b2-0f2b-11e6-84f9-3801595d9571.png)
(Just ignore the Flag symbol it tested it without - same result)

**Comment by ron-murhammer** [comment]
This is intended. When there are too many units to fit in the territories placement areas it creates a solid line extending from the territory for additional units.
