### ISSUE TITLE
PBEM / Dice Roller In-game toggle

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#641]
Some ideas:
1. game title bar should show if you are connected to a dice server. IE: "TripleA - DiceServer: TripleaAWarClub". This gives feedback to the player that they are connected to a dice server.
2. In-game toggle option to connect to a dice server. Available from any game type.

**Comment by ron-murhammer** [comment]
@DanVanAtta Yeah definitely part 1 and I thought we might have had an issue for that already. Part 2 would be nice to have but not quite as critical.

**Comment by DanVanAtta** [comment]
Part 2 is not urgent, but there are a number of benefits:
- simplify the main game screen, no longer need to launch PBEM explicitly
- can allow for people to play a PBEM game while waiting for an opponent to join. Today you cannot do both at the same time, it is either PBEM, or host a networked game
- enables better in-game support for switching live games to be PBEM. We just next need to add the capability to attach email addresses to games

**Comment by DanVanAtta** [comment]
backlog: https://github.com/triplea-game/triplea/wiki/Feature-Back-Log
