### ISSUE TITLE
I am ready to add a new map to the repository

### ISSUE THREAD

**Issue by SwampyAcres** [triplea-game/triplea#6417]
I have a playable map that I am ready to add to the community. Please send me an invitation.

**Comment by DanVanAtta** [comment]
Invite was sent, let's follow up in: https://github.com/triplea-game/triplea/pull/6427/files

Looks like next step needed is to upload the map to github in a repository under your account, and then transfer ownership of that repository to triplea-maps. Then we need to make sure all the links added in #6427 are valid/correct.

**Comment by SwampyAcres** [comment]
Hi Dan, 
 I had followed the directions here:
https://docs.google.com/document/d/1FfF7N0srp9QG0_if5D-c1d1Aa1QTttdhxgm1GBh3pI4/edit
and thought I had already transferred ownership? At any rate, I have again followed these steps today and have received the following message from GitHub:  
Moving repository to triplea-maps/steampunk_advanced. This may take a few minutes. 
So hopefully you know have all the updated map files. 

-----Original Message-----

**Comment by SwampyAcres** [comment]
Hi Dan, 
 Sorry one more thing. The map files in the repository I transferred to triplea-maps is NOT in this structure:

|  |       url: https://github.com/triplea-maps/steampunk_advanced/archive/master.zip |


The direction document does not say to do this! So I did not put it in this structure. However, what you have in the directory is a fully functioning map with all associated files, so imagine you can just move these into the appropriate file structure as mentioned. Sorry... not very good at this. 

-----Original Message-----
To: reply@reply.github.com <reply@reply.github.com>
Sent: Tue, May 12, 2020 8:07 am
Subject: Re: [triplea-game/triplea] I am ready to add a new map to the repository (#6417)

Hi Dan, 
 I had followed the directions here:
https://docs.google.com/document/d/1FfF7N0srp9QG0_if5D-c1d1Aa1QTttdhxgm1GBh3pI4/edit
and thought I had already transferred ownership? At any rate, I have again followed these steps today and have received the following message from GitHub:  
Moving repository to triplea-maps/steampunk_advanced. This may take a few minutes. 
So hopefully you know have all the updated map files. 

-----Original Message-----

**Comment by DanVanAtta** [comment]
@SwampyAcres the structure actually looks pretty alright. Is there something specific that looks off to you?

**Comment by DanVanAtta** [comment]
Noticed that while launching steampunk_advanced, the game engine wanted me to download 'steampunk' first. It's odd for maps to need other maps to be downloaded. It looks like this is a missing update that is needed.

Specifically this line:
```
steampunk_advanced-master/map/games/Steampunk_Advanced.xml:8470:		<property name="mapName" value="steampunk" editable="false">
```

Ought to be:
```
steampunk_advanced-master/map/games/Steampunk_Advanced.xml:8470:		<property name="mapName" value="steampunk_advanced" editable="false">
```

@SwampyAcres please let me know if you could use any help updating it. AFAIK you should be able to "pencil-icon" update the file directly:  https://github.com/triplea-maps/steampunk_advanced/blob/master/map/games/Steampunk_Advanced.xml
