### ISSUE TITLE
Map Downloader - No TripleA Icon

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#643]
All sub windows/frames/dialogs of the main frame have the TripleA Icon.
The Download Maps Window does not.

![Example](https://cloud.githubusercontent.com/assets/8350879/15253298/f08df3ce-1931-11e6-9d25-7edb0c33f924.png)

**Comment by DanVanAtta** [comment]
Which window is the download window exactly? the download map window? I think it's likely only different out of omission, not intentionally.

**Comment by RoiEXLab** [comment]
I wouldn't call this a Feature Request - More something like a low - priority Bug Report...
Also I think that I know why the Icon is not getting displayed... The select Game Frame is a "sub"-frame of the mein TripleA Frame while the DownloadMaps Frame is on the same level like the TripleA Frame... I looked into that a while ago, but I couldn't find the reason
