### ISSUE TITLE
Red Rectangle instead of the "Battle-Field"

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#645]
![screenshot Bug](https://cloud.githubusercontent.com/assets/8350879/15024201/3b1bfec2-1234-11e6-8871-3f47e051b251.png)

**Comment by ron-murhammer** [comment]
@RoiEXLab I'm pretty sure that is probably a map not engine issue.

**Comment by DanVanAtta** [comment]
I agree it's likely a map configuration problem. But, the game engine should be better about detecting and / or handling this.    `Garbage in -> error message out.`, applications should never output garbage. Related concept:  'Postel's law' - https://en.wikipedia.org/wiki/Robustness_principle

**Comment by RoiEXLab** [comment]
I have an Idea whats probably causing the Problem...
This "battle-field-frame" is zooming to match the size of the territory right?
On the Diplomacy Map it seems, that Map joints are doubled... if this is showing the small distance between doubled joints the red color is the border...

**Comment by RoiEXLab** [comment]
Same as with the route... I opened an issue at the diplomacy repo
