### ISSUE TITLE
Units per factory left is not working correctly

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#646]
[Bug Video](https://youtu.be/4wK7iul9oWQ)
_Sorry for the bad quality... I'm not a professional video-recorder ^^_
If there are no units left to deploy, the limit seems to be back at the maximum. It shouldn't allow the user to increase the number and get an error afterwards

**Comment by DanVanAtta** [comment]
Somewhat related to https://github.com/triplea-game/triplea/issues/211, both relate to the place units feature.

**Comment by RoiEXLab** [comment]
#1548 has a fix
