### ISSUE TITLE
OS version + Java compatability

### ISSUE THREAD

**Issue by ZjelcoP** [triplea-game/triplea#6465]
Question resulting from #6461 
Can someone point me to or provide me with what OS-versions and Java-versions are compatable with 1.9.0.0.13066 and upcoming stable release?
Couldn't find it anywhere. 

 Mac OS X 10.3
Mac OS X 10.4
Mac OS X 10.4 PPC Mac OS X 10.4 Intel
Mac OS X 10.5
Mac OS X 10.5 PPC Mac OS X 10.5 Intel
Mac OS X 10.6
Mac OS X 10.7
Mac OS X 10.8
Mac OS X 10.9
Mac OS X 10.10
Mac OS X 10.11
macOS 10.12
macOS 10.13
macOS 10.14
macOSX (deprecated)
macOS 10.15 

 Windows NT
Windows 98
Windows Me
Windows 2000
Windows XP
Windows 2003
Windows Vista
Windows Server 2008
Windows 7
Windows 8
Windows 10
Windows Server 2016

**Comment by RoiEXLab** [comment]
It's a bit hard to pin down an accurate list of compatible oses.
Basically TripleA 1.9 is compatible with all systems that Support Java 8 and TripleA 2.0 with all systems that support Java 11.
However 1.9 isn't too strict and takes more or less any java version that seems to work, so you're not limited to oracle JDK, or openJDK, you can basically make use of every java vendor out there, so you might be able to find versions for unusual OSes even if they're not officially supported.

But if we just think about the installers limits, I think I can give you a good estimate:
1.9 Installer should work on Windows XP+ (even though Windows XP just happens to work more or less by chance and is not listed as supported), and Intel-based (read as non-PowerPC) Mac OS X 10.8.3+ (and a lot of linux distributions). See https://www.java.com/en/download/help/sysreq.xml for more details.

The 2.0 Installer should work with Windows 7 SP1+ as well as macOS X 10.10+ as well as a lot of linux distributions
See https://adoptopenjdk.net/supported_platforms.html for more information

**Comment by ZjelcoP** [comment]
Many thanks, very helpfull!

Cheers Zjelco
