### ISSUE TITLE
Axis and Allies Global 1940 - Can land a plane in a newly conquered territory

### ISSUE THREAD

**Issue by akreider** [triplea-game/triplea#6471]
On the Japanese turn I moved an infantry into Suiyuyan on the Combat Move. The territory was unoccupied and under Chinese control.  On the non-combat move, Japan was able to land a plane in the territory -- which is a violation of the rules.

I'm using the Balanced Mod 3 map.

(I apologize if this is the wrong place to post this).

**Comment by beelee1** [comment]
Hi ak
can you attach a saved game showing that. It might be a map/xml error. You could also tell the BM guys at https://www.axisandallies.org/forums/topic/27121/g40-balance-mod-feedback-thread/1239

**Comment by akreider** [comment]
Oops. It has a warning message at the end of my non-combat move.  So it follows the rules.
