### ISSUE TITLE
Lobby Frame won't open

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#649]
I tried to connect to lobby in Terms of testing, and I got the follwing Stacktrace:
`Exception: null
games.strategy.engine.chat.Chat$1.run(Chat.java:149)
games.strategy.engine.chat.Chat.init(Chat.java:171)
games.strategy.engine.chat.Chat.<init>(Chat.java:98)
games.strategy.engine.chat.Chat.<init>(Chat.java:103)
games.strategy.engine.lobby.client.ui.LobbyFrame.<init>(LobbyFrame.java:52)
games.strategy.engine.framework.startup.ui.MetaSetupPanel.connectToLobby(MetaSetupPanel.java:242)
games.strategy.engine.framework.startup.ui.MetaSetupPanel.access$100(MetaSetupPanel.java:43)
games.strategy.engine.framework.startup.ui.MetaSetupPanel$5.actionPerformed(MetaSetupPanel.java:154)
javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
org.pushingpixels.substance.internal.utils.RolloverButtonListener.mouseReleased(RolloverButtonListener.java:124)
java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
java.awt.Component.processMouseEvent(Component.java:6535)
javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
java.awt.Component.processEvent(Component.java:6300)
java.awt.Container.processEvent(Container.java:2236)
java.awt.Component.dispatchEventImpl(Component.java:4891)
java.awt.Container.dispatchEventImpl(Container.java:2294)
java.awt.Component.dispatchEvent(Component.java:4713)
java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
java.awt.Container.dispatchEventImpl(Container.java:2280)
java.awt.Window.dispatchEventImpl(Window.java:2750)
java.awt.Component.dispatchEvent(Component.java:4713)
java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
java.awt.EventQueue.access$500(EventQueue.java:97)
java.awt.EventQueue$3.run(EventQueue.java:709)
java.awt.EventQueue$3.run(EventQueue.java:703)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
java.awt.EventQueue$4.run(EventQueue.java:731)
java.awt.EventQueue$4.run(EventQueue.java:729)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

Maybe this is to be related to the Substance error mentioned in #628 

EDIT: line numbers may vary

**Comment by ron-murhammer** [comment]
@RoiEXLab I believe lobby backwards compatibility is broken so you can't join the 1.8.0.9 lobby with 1.9.x

**Comment by RoiEXLab** [comment]
In earlier 1.9 versions this worked fine... I could connect to the lobby without problems...

**Comment by DanVanAtta** [comment]
The NPE is not good. We could use to improve the error handling so we know for certain when it is an unknown method, or invalid arg. The NPE is not necessarily the expected error when compatiblity is broken: unrecognized method, or bad arg are more typical.

We may have easily broken compatibility with the variable renaming. Reflection/serialization is evil like that.

**Comment by DanVanAtta** [comment]
Task here seems to be to deal with the NPE in the stack trace, improve the error messaging/handling, and then lets see where we are.

**Comment by DanVanAtta** [comment]
I believe this is because the lobby expected/sending  a variable named "m_chatter", while that has been renamed to "chatter". A person can work through the NPE, but the initial chat list will not be rendered.

There is some work to be done to make sure that different versions of the lobby and client can more easily talk to each other, and so we don't have such subtle version conflicts. Regardless, this should hopefully go away when connecting to a 1.9.0.0 lobby. It can be tested by launching the lobby (there is an eclipse run script to do so), and uncommenting from the "lobby.properties" file

**Comment by RoiEXLab** [comment]
@DanVanAtta as mentioned in #829 I don't think that the lobby.properties file is working since the lobby_server.yaml file is hosted on Github.,,

**Comment by DanVanAtta** [comment]
You're right about lobby.properties.
We get the location of the file from game_engine.properties, which has the yaml file as the backup. We would update the IP address there to change to local.

**Comment by DanVanAtta** [comment]
The way to test this is to launch a local lobby, and see if you can connect to it. There was an attempt once to auto-deploy a new lobby, but the integration with the server was not successful. Remnants of that are in `travis.yml` still.

**Comment by RoiEXLab** [comment]
@DanVanAtta Should I just remove the lobby.properties File, since it got replaced by the yaml File?

**Comment by DanVanAtta** [comment]
If you would, yes. Adding in commented out values that would enable local testing would be helpful.

**Comment by DanVanAtta** [comment]
Lobby frame not opening was a problem due to differences in version and java RMI expected certain variable names that are no longer present. 1.9 can connect to a 1.9 lobby without issue.
