### ISSUE TITLE
Updating the Tutorial map for 2.0 release.

### ISSUE THREAD

**Issue by ZjelcoP** [triplea-game/triplea#6494]
Updating the Tutorial map for 2.0 release.
#6346

So far found following issues with easy fixes ready to put in:

    Player selection

    Make Germans and Italians defaultType="Human" isHidden="true"

    Action tab vs Actions

    Twice in notes

    Battle notification mess up

    Move to before battle
    Alter text of notification
    Notes: To continue click Actions >> Done //and then Battle in Slovakia Hungary... // Cut off this last part

    Stats-tab vs players

    Stats-tab mentioned 3 times in notifications

@tvleavitt, @Cernelius, and others, if you have any more points to fix I'd love to hear them.
Off course I'll also review it thoroughly myself but other eyes are welcome.
Though I took great care of the language part I'm not a native English speaker so any more points on verbiage, formatting and grammar / punctuation etc. are also welcome.

Cheers Zjelco

**Comment by Cernelius** [comment]
Great initiative.

Just a thing I've been curious: Why did you decide to go with v2 rules? For consistency with the rulebook? Since the rules go from v1 to v5, I tend to think it would have made the most sense to go either with v1 or with v5, as one being the original and the other one being the latest, while anything else is neither (I consider Global II being v5 rules too (with additional items and some values changes)).

**Comment by ZjelcoP** [comment]
Honestly can't really tell one from the other.... ;-)
Revised is played a lot in the lobby and to me doesn't seem to have too many weird exceptions.
Newer versions seem to get more complex.
Older but more basic ruleset, easier for newbies i guess.

**Comment by panther2** [comment]
We should really stop calling v2 "Revised". From a rules perspective v3, v4 and v5 are way closer to the original games than v2 is to "Revised".

**Comment by ZjelcoP** [comment]
Found minor bug in the map:
Sea zone 115: in 1 spot naval and ground units are shown on top of each other.
-Could only reproduce in that seazone
-2.0.19427 as well as 1.9.0.0.13066
My bet: there is an error/near double in placement file.
115 Sea Zone  (2696,488)  (2696,436)  (2693,380)  (2693,321)  (2747,429)  (2695,436)  (2697,538)  (2695,592)  (2694,270)  (2838,406)
Been too long ago for me to play with this. Anyone have a quick fix?
![Placement bug](https://user-images.githubusercontent.com/13902879/82738597-ed1c3680-9d38-11ea-93b6-80a601165ef2.png)

**Comment by ZjelcoP** [comment]
Went through whole tutorial, fixed what i found:
[https://github.com/triplea-maps/tutorial/pull/27](url)
[https://github.com/triplea-maps/tutorial/pull/28](url)

If anyone would like to review the minor changes please do.

**Comment by ZjelcoP** [comment]
No further comments thus far, changes merged, briefly tested.
