### ISSUE TITLE
Do we need to renew papertrail?  Is anyone still using it?

### ISSUE THREAD

**Issue by prastle** [triplea-game/triplea#6503]
Hi Team,

Good day! I hope you are doing well despite this very difficult time. This is to notify you that your account is past due. The invoice was due on 05/05/2020 for $60 and is currently 15 days past due.

We realize that this may be an oversight and would appreciate it if you would make a payment no later than today.

Thank you in advance for promptly taking care of this matter.
Stay safe!

**Comment by prastle** [comment]
![image](https://user-images.githubusercontent.com/17258293/82494413-863c1a80-9ab7-11ea-9f17-35d4db9c5c91.png)

**Comment by RoiEXLab** [comment]
I haven't been using it for a while now, but when analysing production incidents in the lobby for example it has been very convenient in the past

**Comment by prastle** [comment]
@RoiEXLab @ron-murhammer So it is worth $60.00 a year and should be renewed?

**Comment by ron-murhammer** [comment]
I haven't used it in a while but did when we were having lots of bots crashing a while back. I'll leave it up to @RoiEXLab and @DanVanAtta.

**Comment by DanVanAtta** [comment]
Same, haven't used it for a while and last I recall we hit the log truncation limit frequently. IMO @prastle let's save the money and cancel for now.

**Comment by prastle** [comment]
Oki doki I will email them.  That card was replaced anyways ;)
