### ISSUE TITLE
Managing bans, IP and otherwise

### ISSUE THREAD

**Issue by tvleavitt** [triplea-game/triplea#6509]
This ticket arises out of a discussion in #6498. We ban users primarily based on IP addresses, and secondarily based on system-ids (MAC addresses for network cards).

A number of issues and ideas came up, but this issue focuses on determining how best to deal with longer term IP bans, given that most end users will be using dynamically assigned IPs that change over time, and it is user unfriendly to have a legitimate users inherit a ban imposed on someone else; a secondary but still salient concern is that this has the potential to block legitimate users as well.

Dan comments: "If we are concerned by IP banning the action to take is to remove the unlimited bans and/or very long duration bans and properly have the expire after a few months (but maybe keep the system-id around)." and " it would be nice to measure system-id vs IP ban effectiveness".

It appears, at least according to one source: "The typical lease time for ISP’s in the United States is roughly 7 days. However in most instances your router will renegotiate this lease prior to its expiration. During the lease renegotiation, it is very common for the same IP to be reassigned to your router. In fact our research has discovered many homes that have theoretically dynamic IP’s, but have held the same IP for multiple years."

What process can we put in place to review / auto-expire long term IP bans, and what data do we need in order to do this accurately, in a way that doesn't restore access to known bad actors?

**Comment by Cernelius** [comment]
Of course, the more one openly talks about, thus explains, how banning exactly works, the more information any banned user is able to access to, increasing its own chances to learn how to circumvent the banning system or decreasing the time needed to achieve such aim, or both. Not the first time I point out this.

**Comment by prastle** [comment]
Yes we have attempted to point that out for years @Cernelius .  Hopefully the new system and database that records all will alleviate this issue.

**Comment by tvleavitt** [comment]
A user sophisticated to look through Github bug reports already knows how
to avoid bans; I could probably do a quick Google search and find a ton of
information on the subject. Any security professional will tell you
"security by obscurity" just creates false confidence. Also, all this code
is open source, a sophisticated attacker will just go straight to the
algorithm to look for flaws.

If we're using pure MAC address for system-id matches, that's easily
defeatable, as this article mentions (also for the simple reason that
software tools exist to edit this).

Here's a discussion of other tools you can use to at least make a malicious
individual's life more difficult.

https://www.nextofwindows.com/the-best-way-to-uniquely-identify-a-windows-machine

I'm not sure if this needs to be moved to a new issue, because it is more
technical (how can we enhance effectiveness) rather than policy: how long
should bans last? What metrics do we use to lift it extends them, etc.?

Thomas Leavitt

**Comment by tvleavitt** [comment]
Here's some discussion of techniques under Linux.

https://stackoverflow.com/questions/10152762/best-way-to-get-machine-id-on-linux

Thomas Leavitt

**Comment by DanVanAtta** [comment]
@Cernelius please have a read of: https://en.wikipedia.org/wiki/Kerckhoffs%27s_principle

>  "one ought to design systems under the assumption that the enemy will immediately gain full familiarity with them". In that form, it is called Shannon's maxim. This concept is widely embraced by cryptographers, in contrast to "security through obscurity", which is not. 

https://en.wikipedia.org/wiki/Security_through_obscurity

**Comment by DanVanAtta** [comment]
Re: IDs, in part there is not much to do for this as the ID is software generated. We need to avoid system calls as IIRC steam does not allow apps that make system calls. The current mechanism to store a UUID is maybe about as good as we can get. It would be nice to be able to HMAC the ID against something known, but it comes back to being software controlled and that could also in turn be defeated.

RE: IP efficacy, we can measure readily if one of system-id or IP change, but if system-id changes can we be sure that it is not a completely different person with the same IP? It's not clear if we can accurately measure either false-positives or false-negatives.

In terms of duplication of IPs it should not be as bad as one would think given we have a user-base under around 1k. We also do want to be sure that a person cannot simply hop onto a different device to get around a ban.

For a political matter, explaining that IPs is not unique is not necessarily easy, removing features that people believe are helpful even if they are not necessarily and potentially harmful is a difficult task. Having tried that experiment to remove IP banning, it did not go over well at all. 

That has me wondering if maybe it is worth keeping an IP ban for say only 2 weeks but the system id ban indefinitely? It's a bit hard to say, particularly as in-practice IPs do not to be somewhat long lived. We should also consider that:
- there are not that many bans that occur
- those that are banned for long periods of time we really do not want to come back. Risking having a few users get caught in this is perhaps the price to be payed.
- our SOP for banning for long periods of time is currently broken, which is perhaps another problem, but currently it's more an issue that we do whack-a-mole where we ban for only an hour, or day, or just merely boot a user and fail to realize they should be banned for extended periods of time.

**Comment by prastle** [comment]
👍  @DanVanAtta
