### ISSUE TITLE
maps die on linux/mac due image name casing problems

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#651]
Example, WaW is not playable on linux/mac due to wrong casing in Americans/marine.png

Next steps:  finish discussion of how to solve naming problem. Standardizing unit image names to a given casing could be an answer. We can write a checker script for it and deploy it to the game build.

**Comment by RoiEXLab** [comment]
IMO there are only 2 options that make sense in terms of casing:

1. All lowercase - easy to implement easy to remember for MapMakers. (example: americans/marine.png)
2. First letter (and special letters, like the A in TripleA) uppercase just like you would name a class in java. - more intuitive (looks better although nobody ever wants to look in the maps folder...) and not hard to remember (example: Americans/Marine.png)

**Comment by DanVanAtta** [comment]
I like number one, underscores for spaces and all lowercase (sometimes called lower snake_case). Plus side, that is often used for file system names, and a script can probably check for that condition as well (grant it, it would be best though if the game engine could flag it as well).

**Comment by RoiEXLab** [comment]
Can this be closed, or should this be renamed to Name Casing norm or something like that?

**Comment by DanVanAtta** [comment]
The game no longer crashes, so no longer high priority. Let's allow a new issue for discussion on further improvement to missing image handling.
