### ISSUE TITLE
"Status" Not Working in Hosts (2.0.19485)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#6512]
In a host, the "Status" button does nothing.

Tested that the same problem exists in 1.9.0.0.13066.

**Comment by RoiEXLab** [comment]
@Cernelius Could you clarify what you mean by that?
When I'm joining a bot or a locally hosted network game, the Status button works as expected for me.

**Comment by Cernelius** [comment]
> @Cernelius Could you clarify what you mean by that?
> When I'm joining a bot or a locally hosted network game, the Status button works as expected for me.

Exactly what I said. However, I tested that now it works in all cases mentioned by you or me or both, beside the fact that I cannot host anymore in lobby with 2.0.19485.

**Comment by prastle** [comment]
As I just said in lobby and was ignored by u and Silver can u please explain to me why it is needed in A bot?  Status was only ever used by a host...

**Comment by Cernelius** [comment]
In a host whose "Status" is "In Progress", the "Status" button does nothing.

Tested that the same problem exists in 1.9.0.0.13066.

**Comment by Cernelius** [comment]
> As I just said in lobby and was ignored by u and Silver can u please explain to me why it is needed in A bot?  Status was only ever used by a host... @Cernelius

I think the behaviour is the same in automated and non-automated hosts, as far as I tested.

**Comment by prastle** [comment]
I just tested with my own host and it works fine.  It was never meant to be used in a bot.  Only a host can display status.

**Comment by Cernelius** [comment]
> I just tested with my own host and it works fine.  It was never meant to be used in a bot.  Only a host can display status.

Was your host's "Status" "In Progress", when you tested?

**Comment by prastle** [comment]
Gd point it does not work once in progress Ill shut up you are correct sorry

**Comment by Cernelius** [comment]
> In a host whose "Status" is "In Progress", the "Status" button does nothing.
> 
> Tested that the same problem exists in 1.9.0.0.13066.

I've just tested that the problem doesn't appear to exist in 2.5.22294.
