### ISSUE TITLE
Concurrent Modification Exception in 19485

### ISSUE THREAD

**Issue by beelee1** [triplea-game/triplea#6521]
### How can the problem be recreated?

Map is Global 40 House Rules with Canada.

When Bombing raid is undertaken this error is thrown.

![Screenshot from 2020-05-24 02-48-05](https://user-images.githubusercontent.com/24382682/82749036-11453b00-9d6c-11ea-9f02-f2b87d6232f5.png)

### What is an expected fix?

Not sure but it works in 13066

### Which Engine Version are you using? 

19485

### (Optional) Additional information
here is save with 130666 where it works. Max scramble to sz 110 and sz 111. Pick Factory as one target and airfield as next. Note it will say "units may die" or something because it is a A0 D0 unit but it is made for SBR only. Ignore the warning and continue. 

/home/greg/Desktop/13066 vs 19485.zip

here is pre 19485 where the error is thrown:

/home/greg/Desktop/19485vs13066 SBR Error.zip

My suspicion is something must have changed where the "units will die" prompt that was able to be ignored is now no longer able too ? idk ? I thought they would just die then so maybe something different. Anyway it basically breaks the map so...

**Comment by beelee1** [comment]
[19485vs13066 SBR Error.zip](https://github.com/triplea-game/triplea/files/4673163/19485vs13066.SBR.Error.zip)

[13066vs19485.zip](https://github.com/triplea-game/triplea/files/4673166/13066vs19485.zip)

**Comment by RoiEXLab** [comment]
Thanks to @asvitkine this should be fixed in the latest pre-release that should be ready in the next couple of minutes

**Comment by beelee1** [comment]
Thanks Guys :)
