### ISSUE TITLE
giveUnitControl not working in 19510 the same as 13066

### ISSUE THREAD

**Issue by beelee1** [triplea-game/triplea#6564]
### How can the problem be recreated?

Global 40 House Rules
Buy units for UK Pacific and after you place them they don't turn British

### What is an expected fix?

They should turn British

### Which Engine Version are you using? 
19510 pre

### (Optional) Additional information
It works correctly in 13066. Also the original Global 40 map works correctly in 19510. I have added a lot of modifications to the original map but they work with 13066.

I went as far back as I could with previous versions but couldn't find when it changed. I haven't kept them all but I suppose there is a way to find them on the git repo. Idk how to do that yet.

I'll post 2 saves.

Thanks

**Comment by beelee1** [comment]
[G 40 HRs 13066 UKP turns British.zip](https://github.com/triplea-game/triplea/files/4711124/G.40.HRs.13066.UKP.turns.British.zip)

[G 40 HRs 19510 UKP Does Not turn British.zip](https://github.com/triplea-game/triplea/files/4711126/G.40.HRs.19510.UKP.Does.Not.turn.British.zip)

**Comment by DanVanAtta** [comment]
This was an excellent bug report @beelee1 , thank you! It was clear and the save games really helped save time to determine the problem. I walked through the equivalent 2.0 code and 1.9.0.0.13066 in a debugger in parallel and was able to find the problem. 

This would be fixed after https://github.com/triplea-game/triplea/pull/6569 is merged. Any save game that already has this problem will be doomed, the problem will be encoded in the save game. FWIW, any such games probably do not make it past Pac UK before noticing the problem as it would always be triggered by Pac UK round 1.

**Comment by beelee1** [comment]
Thanks @DanVanAtta  happy you were able to fix so easily : )
