### ISSUE TITLE
Game Crashes When Scrambled Fighters Have No Where to Land Other than the Territory to Which it Scrambled

### ISSUE THREAD

**Issue by regularkyd** [triplea-game/triplea#6583]
### How can the problem be recreated?

In WW2 Path to Victory, Germany attacks France, Normandy, and Southern France on G1. French fighter scramble to normandy (from France. . . per land scramble rules). Germany takes Southern France and France, but retreats from Normandy (or otherwise loses the battle with the fighter surviving). Game immediately crashes.

Alternatively, attack only France and Normandy. French fighter scrambles to Normandy. Germans retreat from Normandy or otherwise lose fight with fighter surviving, while capturing France. Game offers to land fighter in either Normandy or Southern France. If player picks Normandy, the game crashes.

### What is an expected fix?

One fix would be to allow the fighter at issue to land on the the territory it scrambled to (or an intact carrier therein) IF the territory from which it scrambled is no longer a viable landing spot. This should occur without error.

**Comment by Cernelius** [comment]
In my personal opinion, merely based on realism, if a scrambled fighter cannot always choose whether to land in the territory it scrambled to or in the territory it scrambled from, then it should not acquire the capacity to land in the territory it scrambled to for missing the only option it would have otherwise had.

Meaning, in this case, I would make the fighter (not the game!) crash.

**Comment by regularkyd** [comment]
I could see that point of view, though it seems unrealistic not to let the
fighter land in a successfully defended territory if it can't go home for
some reason. Ultimately, whatever the developers decide is ok by me--i.e,
allow the fighter to land in the territory to which ti scrambled or simply
kill the fighter) we just want to avoid game crashes!

**Comment by regularkyd** [comment]
Actually, I just downloaded and tried the prerelease, and I see this
problem has already been fixed! So please disregard my bug report. Thanks
so much!
