### ISSUE TITLE
Scrollbar on notifications and battle screens blocks stuff

### ISSUE THREAD

**Issue by ZjelcoP** [triplea-game/triplea#6592]
### How can the problem be recreated?
Start any map that uses notifications.
Many notifications the scrollbar blocks a small part of the text, right side and bottom.
-If there is a very large notification this makes sense as you can scroll.
-With small notification that perfectly fit fully in the screen a small part is also blocked. Scrollbar is unnecessary here.
-Many notification have been built in specific size to prevent scrolling. This negates that effort.

### What is an expected fix?
Place the scrollbar outside the original size of the notification so it doesn't make scrolling necessary for nearly all notifications.

### (Optional) Additional information
2.0.19707

![Notifications scrollbar](https://user-images.githubusercontent.com/13902879/83809299-7d059d00-a6b6-11ea-962b-db83eb14fbad.png)
![Notifications scrollbar 2](https://user-images.githubusercontent.com/13902879/83809305-7ecf6080-a6b6-11ea-9a39-6c66a98e5411.png)

**Comment by Cernelius** [comment]
Sorry if off topic, but I'm assuming it is related. Can the "i", or whatever, symbol, be removed too, as it takes space on the left of the window and move all the notification to the right, displacing its actual centre (while being useless, in my opinion)?

**Comment by ZjelcoP** [comment]
13066 doesn't have those scrollbars yet. Can't find where thus was changed.

**Comment by ZjelcoP** [comment]
And now also in battle windows. Really have to fix this before releasing.
2.0.19912

![afbeelding](https://user-images.githubusercontent.com/13902879/84191733-3a1e3d80-aa99-11ea-9917-571db1b66cd6.png)

> Sorry if off topic, but I'm assuming it is related. Can the "i", or whatever, symbol, be removed too, as it takes space on the left of the window and move all the notification to the right, displacing its actual centre (while being useless, in my opinion)?

Now the "i" starts creating a white bar. Please remove that useless "i" messing up graphics.
![afbeelding](https://user-images.githubusercontent.com/13902879/84192452-49ea5180-aa9a-11ea-9afb-48976c9d369c.png)

**Comment by DanVanAtta** [comment]
@ZjelcoP I can't change screen sizes to get scrollbars, nor do I see them.

Some questions:
1. Which OS are you running? 
2. Which java version is reported on the main screen? 
3. What is your screen resolution? 
4. Do you see the same issue if you change the UI look & feel  (in the settings windows)?
5. Do you see the same white bar in 13066?

**Comment by DanVanAtta** [comment]
@ZjelcoP by any chance did you change the look & feel without a restart? The 'I' is not really a culprit of the bad graphics. It looks like the dialog window is being rendered with one L&F and the content another. For example notice the title bar has a white background. Typically with the dark foreground you'd see the title bar be a dark color as well. For example:

![Screenshot from 2020-06-15 23-09-10](https://user-images.githubusercontent.com/12397753/84737727-60425280-af5d-11ea-9a73-c949bc1dd087.png)

Which L&F are you using?  If you restart the application, do you see the same?

**Comment by ZjelcoP** [comment]
Which OS are you running?
_Win10_

    Which java version is reported on the main screen?
_Actually couldn't find current version. Can't run TripleA without it right? Right?.._
_Downloaded and installed JRE 8u251. What changed?
-White bar no longer in transports notification.
-Main screen graphics were a bit blurry, thought it might be because of new laptop. With JRE 8u251 installed suddenly perfectly crisp again..._
_Scrollbar issue still there..._

    What is your screen resolution?
_1920 x 1080 144Hz_

    Do you see the same issue if you change the UI look & feel (in the settings windows)?
_Yes_
_Normally never touch this. Graphite for life!_

    Do you see the same white bar in 13066?
_Nope. The I's are there in 13066 without causing scrollbar issues so those I's are probably unrelated._

**Comment by DanVanAtta** [comment]
Thanks for the responses.

Java version is printed in the top left of the main window, eg:
![Screenshot from 2020-06-16 16-38-29](https://user-images.githubusercontent.com/12397753/84838671-da231c00-afef-11ea-8792-21798e7d8d65.png)

@ZjelcoP indeed java is required, it is bundled with the game as well. Java11 is required, Java 8 would not work. Its strange then that you see any difference at all installing JRE 8u251. How are you installing 2.x? Are you using the windows installer, or downloading the zip and/or Jar files?

**Comment by ZjelcoP** [comment]
Now I see the Java Version, it's 11.0.6.
Pretty sure it was not visible there before manually downloading java.
I always download and execute these files for prereleases: TripleA_2.0.20026_windows-64bit
Stable i download through the website.

**Comment by DanVanAtta** [comment]
Is anyone else on win10 seeing this?

**Comment by RoiEXLab** [comment]
@DanVanAtta I haven't checked for this particular window, but I'm getting the "i" Symbol on all "Information Dialogs" I think 🤔

**Comment by DanVanAtta** [comment]
The "i" is expected, part of swing.
The scrollbars are the concern.

**Comment by DanVanAtta** [comment]
@ZjelcoP perhaps try uninstalling all Java versions, uninstall the game. Then install only the game. Perhaps even though the game is supposed to provide its own Java version, some shared component is being used and the game is picking up the Java 8 version incorrectly.

This is the only remaining important issue as far as I can see in 2.0 that we need to address. Having checked for changes in the related window rendering code, there is suspicious code to calculate window sizes, but that has not changed in some years. Either with Java11 that code is now behaving differently because the system is returning different results, or we are seeing some sort of installed java version conflict. The fact that you saw any difference @ZjelcoP changing Java install hints towards the latter (which is really unexpected).

**Comment by ZjelcoP** [comment]
Hi Dan,

did some testing:
-_uninstalling all Java versions, uninstall the game. Then install only the game._  >> no change
Two other win 10 devices: Both do not show the issue....

Found the culprit: win10 scale and layout. New laptop had display scaling at 125%. Turning it off immediately resolves the issue. Turn it on, issue is back.
Just strange that 1.9.0.0.13066 doesn't show the issue with display scaling at 125%. 

Cheers Zjelco

**Comment by RoiEXLab** [comment]
@ZjelcoP Interesting

> Just strange that 1.9.0.0.13066 doesn't show the issue with display scaling at 125%.

I suppose that's because Java 1.8 isn't really aware of screen scaling, AFAIK the screen will just get slightly blurry

**Comment by tvleavitt** [comment]
Good detective work. Makes sense. I'll bet other Win10 apps will display
similar issues.

Thomas Leavitt

**Comment by Cernelius** [comment]
@ZjelcoP Try to use the "all platforms", instead of any installer. In my past experience, all problems with the Window's zoom has always been caused by the installer, not by TripleA itself.

That is mostly why I always used the "all platform", instead of any installer, though eventually I resigned setting the Windows zoom to 100%, instead.

**Comment by DanVanAtta** [comment]
If all platforms has a difference it means the JRE bundled with the game
has issue. A proper fix is for us to select one that does not have the
problem. Per the forum posting about all platform, unless we can reason why
we have it, we'll remove it to simplify. The all platform means we have to
support any JRE, always ask what us installed, how, and funny enough that
information is not always posted on the first communication when reporting
problems.
