### ISSUE TITLE
map drawer exception -  cannot cast to sun.java2d.xr.XRSurfaceData

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#660]
```
Exception: sun.awt.image.BufImgSurfaceData cannot be cast to sun.java2d.xr.XRSurfaceData
sun.java2d.xr.XRPMBlitLoops.cacheToTmpSurface(XRPMBlitLoops.java:145)
sun.java2d.xr.XrSwToPMBlit.Blit(XRPMBlitLoops.java:353)
sun.java2d.pipe.DrawImage.blitSurfaceData(DrawImage.java:959)
sun.java2d.pipe.DrawImage.renderImageCopy(DrawImage.java:577)
```

Not sure what triggers this: could be route drawer code, driver reset, not sure..   Regardless, the game is unplayable after hitting this error. The full stack trace is pretty gigantic, here it is: 
 https://gist.github.com/DanVanAtta/ba628706d3b397339126b3beb3f355a4

*update* it is gfx card being reset. Can trigger it by turning on a second monitor.

**Comment by ron-murhammer** [comment]
@DanVanAtta When did it occur? Any idea how to reproduce it? Do you see it often?

**Comment by DanVanAtta** [comment]
I can see it repeatedly if I manually have the gfx card reset, IE: turn on a second monitor. This occurrence was effectively random. Seems like those two are probably the same problem.

**Comment by ron-murhammer** [comment]
@DanVanAtta Do you know if this is an existing 1.8.0.9 bug?

**Comment by DanVanAtta** [comment]
No, I think it's likely though. I think chances are I'll have some time maybe to look at this in a few weeks. Till then it could use tracking at the least.

**Comment by DanVanAtta** [comment]
Hitting the error again while leaving the game open.  Notice in the stack trace the "substance UI" part.

```
sun.java2d.pipe.ValidatePipe.copyImage(ValidatePipe.java:186)
sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3318)
sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3296)
org.pushingpixels.substance.internal.utils.ButtonBackgroundDelegate.updateBackground(ButtonBackgroundDelegate.java:445)
org.pushingpixels.substance.internal.ui.SubstanceButtonUI.paint(SubstanceButtonUI.java:336)
org.pushingpixels.substance.internal.ui.SubstanceButtonUI.__org__pushingpixels__substance__internal__ui__SubstanceButtonUI__update(SubstanceButtonUI.java:490)
org.pushingpixels.substance.internal.ui.SubstanceButtonUI.update(SubstanceButtonUI.java)
javax.swing.JComponent.paintComponent(JComponent.java:780)
javax.swing.JComponent.paint(JComponent.java:1056)
```
Screenshot of how the game is rendering:

![result](https://cloud.githubusercontent.com/assets/12397753/15310721/c7bdb236-1ba7-11e6-8fe2-6a7e1b3808ef.png)


This makes me wonder what straight swing would look like compared to Substance.. Given the stack trace, looks a bug deep in substance (in fact, no tripleA classes are even in the stack trace)

**Comment by RoiEXLab** [comment]
One thing to mention:
It seems that recently more and more issues are caused by/related to the Substance Library...
Maybe we should move to another opensource look and feel library or even create one from scratch

**Comment by DanVanAtta** [comment]
@RoiEXLab , I'm open to that. I do not have much lover for Substance at the moment. It's great, but it really is causing some problems, so not so great..

**Comment by DanVanAtta** [comment]
Given this is in Substance, not much we can do. Closing as this is not actionable.
