### ISSUE TITLE
Labelling PRs for release notes

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#6614]
Thinking about how we can make sure the release notes stay complete and are fully updated, it seems to be a small nightmare! 

Notably we have no way of knowing if all PRs are included. To make matters worse, any time we try to make sure we have all PRs included, we are essentially starting from scratch making the effort redundant each time.

I propose we go back to labeling PRs for inclusion in release notes. In this way we can filter PRs by label, and if know the last PR from the previous release we can then verify that the filtered list of PRs matches the release notes.

To proceed:
1. Agree to this
2. Define labels (should correspond 1:1 with release note types)
3. Label any merged PRs that already in release notes
4. Label any PRs that we *should* include in the release notes and update the release notes

An initial suggestion for labels:
- fix: fixes a defect or performance issue that was a problem in the previous release
- updated feature: improves something that existed
- new feature: a new feature
- map XML options: a new or updated map XML configuration
- AI: an updated related to any of the  AI's

**Comment by RoiEXLab** [comment]
That's a good idea for PR labels, something that would encourage me to put more thought into labeling.
However I don't think we should keep it a manual process, there are several tools out there that could generate a changelog for us that we just have to paste on the website eventually, or we create a script for that as well.

**Comment by DanVanAtta** [comment]
Creating a script is an interesting idea. We certainly can query the github API for PRs with a specific label and an ID greater than a specific value. It would be a great way to make sure we have a complete list and to simplify some of the manual work.

One concern, I don't think that would be quite fully sufficient though. PR titles might not be very meaningful to users and we may want to re-word and/or re-summarize them. For example, for XML changes, I  was thinking we may want to give a quick example of the XML tags that were added.

**Comment by DanVanAtta** [comment]
I don't know how well we do to get an automatic release note scraping system together for 2.0, perhaps..

Looking at the release notes we have, there are two dimensions, one is a category, then the second is the type of change. That implies two dimensions of label, one for game area and another for update type. Is that going to become difficult? Should we simplify it?

Second, perhaps we can capture during PRs the comment that should go in the release notes. We could have a section called "release notes mention" or something similar. We could then take that text and plop it directly into the release notes, potentially scraping the text automatically. Any concerns or thoughts?

**Comment by RoiEXLab** [comment]
Hmm, a "release notes mention" section could do the trick. This way you're always reminded of it

**Comment by DanVanAtta** [comment]
Perhaps all we really need is a scrape-able 'release note' section on PRs.

**Comment by DanVanAtta** [comment]
Okay, I got a script together and updated the PR template. There is a magic comment where you can put release notes now.

Details are in: https://github.com/triplea-game/triplea/wiki/PR-Release-Notes

PR template updated in: https://github.com/triplea-game/triplea/pull/6790
