### ISSUE TITLE
Automate Complexity Analysis on PRs

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#662]
Run something that will score the cyclomatic complexity of PRs. Can be something like find bugs. 

Goal is to help avoid PR reviews that are basically: "This is great, but the code quality is low and has high probability of containing bugs in its current state, and an even higher probably if modified."

Desired End result: single number on PRs that someone can independently iterate on.

**Comment by ron-murhammer** [comment]
Agree. It would be nice to incorporate some static analysis tools like findbugs, pmd, checkstyle, etc. These could help in other areas beyond complexity analysis as well.
