### ISSUE TITLE
PR process and assignemnt

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#663]
Process point: I don't know if it's useful to assign PRs to people.

Folks who submit a PR, usually do not need to have it assigned to them to know they have the next action. Usually a comment will indicate that, so the assignment is a bit redundant. Plus, it does not extend to everyone since only people with write access can change labels or assignments. This means assigning a PR to someone without write access is not very useful, there is no way to flag when it is ready to be reviewed again, other than to comment. Bottom line, assignments at best are redundant to the commentary in the PR, at worst the assignments become stale.

I think we can solve this pretty easily by saying it is up to the code reviewer to make it clear what next action needs to be taken, so there should be a final comment from a reviewer stating as exactly as possible what next needs to be done. 

The flip side to that, there may be a number of commits coming to address everything, so the submitter of the PR should eventually leave a final comment stating the PR is ready for review again.

**Comment by ron-murhammer** [comment]
@DanVanAtta Yeah, I forgot non-committers can't change the assignments. I've been trying to use them to indicate who's court the ball is in. Otherwise its often hard to know which PRs are ready for review. When there are only a handful it isn't a big deal but when we had like 30 open I had to use something to keep track of which you were updating and which ones I was reviewing.

**Comment by DanVanAtta** [comment]
Perhaps it can go like this:
- reviewer takes a look, if all is good, add some compliments and merge
- something needs fixing, reviewer assigns it. At that point the reviewer knows to update stuff, and let's the person that did the first review then is responsible for responding to updates. Other reviewers can then skip the PR knowing that they are being handled.

**Comment by ron-murhammer** [comment]
@DanVanAtta Yeah I think that works. Sort of what I've been doing since non-committers can't assign them back to me :)
