### ISSUE TITLE
2.0+ Compatibility Requirement for PRs is Back

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#6630]
For a long time while developing 2.0 we allowed for any updated to break compatibility. From now-on we need to ensure that all PRs keep compatibility. Any breakages in compatibility regrettably will need to be reverted and fixed.

I hope to build in a test 'soon' that will automatically check for save-game compatibility. Until then, we need to be relatively confident and/or manually verify that after any changes we can still load a 2.0 save. 

Hopefully, if anything, this is motivation for us to realize once again how painful TripleA save-game compatibility is and how much it hinders our progress and takes up our time in overhead. Now that we can no longer once again freely break compatibility, the project to change how save-games are serialized is not only important but is now more urgent..

**Comment by DanVanAtta** [comment]
cc: / @trevan @RoiEXLab @asvitkine

**Comment by trevan** [comment]
Does the compatibility need to be forward and backwards?  Or just backwards?

Also, the changes I'm making only appear to affect saves that occur in the middle of a battle.  My latest PR (https://github.com/triplea-game/triplea/pull/6593) was breaking compatibility but only if I loaded a save that is in the middle of a battle.  Pre-battle and post-battle saves loaded fine.  So you'll want your test to check those type of saves.

**Comment by DanVanAtta** [comment]
@trevan just backward, new versions need to be able to read old saves.
