### ISSUE TITLE
Drop Change Log?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#665]
There was a really interesting conversation some time back about the tutorial map, and the change log pop-up was brought up. A couple of interesting points were made:
- tripleA has far too much text. The Change log is an example where there is a wall of relatively not useful text.
- if new features require someone to go and read the full change log, then we have failed at making the feature discoverable in the game. For example, 'c' key centers on units, but there is almost no way for people to know about this without reading about it. Hence having a button somewhere that does that action, and has a hover text, 'c will center the unit', is a much better UX.

In sum, I propose we simplify, and cut the change log out. Going forward let's be sure that there is a natural way to find game elements (in addition to the standard adding text to the game help menus, a bit of an all of the above approach). Said another way, the change log does not seem to actually help anyone that much, it is not read most of the time, and if we rely on that, then it is too easy for people to skip a few releases and to miss some key features.

**Comment by ron-murhammer** [comment]
@DanVanAtta So I'm fine dropping the change log from in game popup but I think we still need to have a change log posted for every release. This is pretty standard practice, either on a webpage or forum would be fine. For experienced users, they want to know what we changed especially if its bug fixes or under the covers improvements. UI changes don't matter much since as you describe they should be obvious.

**Comment by DanVanAtta** [comment]
A big part of the point is that any feature should have some UI element attached to it. Otherwise it's a "magic" feature. It lacks discoverability, represents a UX problem. 

The 1.9.0.0 release has massive change notes. I'm not sure they're that valuable at this point, even for the experienced players. 

I'm open to keeping them on the website. We should move the data out of the game engine in that case completely. One benefit is we no longer would be duplicating that data in N places, could just update the website code directly.

Doing that though, I really do wonder if it's a distraction. Folks ideally would want to be focused on other tasks, like playing the game. That makes me think we should drop them and focus on the UX that allows for the features to be discovered in-game. Failing that, throwing them to the website I think is the next best option, and perhaps a more comfortable path to migrating them out of the game engine.

**Comment by ron-murhammer** [comment]
@DanVanAtta I don't think that is necessarily possible in all cases. If I make significant AI enhancements there is no UI element that will show that. Same with rule delegate enhancements or fixes.

An example is EU4: https://forum.paradoxplaza.com/forum/index.php?threads/eu4-1-17-released-now.928374/

**Comment by DanVanAtta** [comment]
That is a very good point. How about we move it to the website? We'll keep the one list there, and can link to it from the SF forums and A&A.org.

Similar to here, we'll keep a change_log branch that has the change notes + markup for the next release. During release we merge the branch, and the notes would be live on the website. Keeping an extra page on the website does not hurt. If anything it is more content for the search engines to crawl.

Agreement to move the change log entirely to the website repo, and create a change_notes page there to display them?

**Comment by ron-murhammer** [comment]
@DanVanAtta Yeah I'm good with moving it over to the website repo.

**Comment by DanVanAtta** [comment]
Big rough, but the change notes were added to the website: http://triplea-game.github.io/release_notes/

**Comment by ron-murhammer** [comment]
@DanVanAtta So merged the PR and looks good. I think the one thing that jumped out at me is do we want to have 'developer name(s)' next to each item or not. Seems like the 1.9 covers at least most of the changes but some inconsistency on some having developer name and some not.

**Comment by DanVanAtta** [comment]
I'm of the opinion no:
- self-effacing principle
- the names adds some clutter/distraction
- it's one more thing, one more element of overhead when we update the notes
- not terribly clear to me why it's valuable or important, particular if we stop listing the really small changes (given the length of the list, IMO it's more important to have the key changes, rather than everything)
- can be ambiguous if multiple people work on something

With that said, giving community credit is nice, but I do not think it is necessary nor terribly important.

**Comment by ron-murhammer** [comment]
I'm fine either way as I think now that we are on github its much easier to see who has contributed. I also don't think we need to put lots of the minor ones and the ones that don't really have any effect on the end user. My thought is the change log should really be geared towards our power users that want to know all the major changes we made that effect any aspect of the game. I would propose we remove all names from the 1.9 section then (leave old sections as they are). Probably would be nice to make a pass to organize and clean them up a bit as well.

**Comment by DanVanAtta** [comment]
No disagreement. I like that the purpose of the change notes is suddenly much more clear now that they are on the website.

**Comment by DanVanAtta** [comment]
Took a pass at the release notes: https://github.com/triplea-game/triplea-game.github.io/pull/65

Some more pruning could be done, so the notes need another pass or two IMO.
