### ISSUE TITLE
Has ctrl z been removed for full screen ?

### ISSUE THREAD

**Issue by beelee1** [triplea-game/triplea#6688]
### How can the problem be recreated?

ctrl z used to hide the sidebar in 13066. Doesn't work in 19942. I don't see it listed in help anymore either.

### What is an expected fix?

I'm guessing it was removed ? Personally I kinda liked it :)

**Comment by DanVanAtta** [comment]
Yes, ctrl+z was buggy, it was removed.

https://github.com/triplea-game/triplea/issues/5847

**Comment by beelee1** [comment]
Thanks for the reply
