### ISSUE TITLE
Gradle test failing due to problematic naming

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#670]
When developing on your local branch, it is very useful to be able to run the gradle tests without needing to create a PR first...
For some reason `gradlew/gradle test` is failing on my machine. I think this is caused due to the fact, that 

`triplea\test\util\triplea\mapXmlCreator\` and `triplea\src\util\triplea\mapXmlCreator\`

are both the `util.triplea.mapXmlCreator` Package.
In eclipse this is causing no problems, however when running  `gradle test` I'm getting a `cannot find symbol exception` while building, because Classes in `triplea\src\util\triplea\mapXmlCreator\` aren't in `triplea\test\util\triplea\mapXmlCreator\`

**Comment by DanVanAtta** [comment]
@RoiEXLab  please create a gist with the full error message.

**Comment by RoiEXLab** [comment]
[Here you go...](https://gist.github.com/RoiEXLab/be1671f4482fc35ed1069852e77212a9)

**Comment by ron-murhammer** [comment]
@RoiEXLab if you just run all the unit tests from an IDE do you get the same problem?

**Comment by RoiEXLab** [comment]
@ron-murhammer No It seems just to be a Gradle-Eclipse Issue...

**Comment by RoiEXLab** [comment]
Closing... cannot reproduce anymore
