### ISSUE TITLE
JavaFx Settings Menu / Co-existing in Swing

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#6710]
The settings window is perhaps the only component that is both visible from the staging screens and the game-proper. Currently we have duplicated the settings code to enable the JavaFX variant and have two versions, one in swing and another in JavaFX.

How do we get it so we only have one version? 

It looks like Swing content [can be embedded](https://docs.oracle.com/javafx/8/embed_swing/jfxpub-embed_swing.htm) in JavaFX applications. Perhaps we can just keep the settings window in swing and render it from JavaFX.

I don't think there is a good option to convert the settings window to JavaFX and have it be rendered from JavaFX and Swing (it seems to be a one-way street).

**Comment by RoiEXLab** [comment]
It is possible to embed swing in JavaFX and vice-versa. There are some limitations and downsides (mainly worse performance, and partial missing functionality when embedding javafx inside swing).

However I don't think such an "embedded" frame would be the best solution to this problem. Embedding isn't that easy as documentation might suggest, it requires some boilerplate code. Work that might as well be spent to bring JavaFX development forward.
A while ago I created a project to track the missing steps to get a working (functionality-wise) "Start Screen" running, i.e. the UI controls to launch a game etc.: https://github.com/triplea-game/triplea/projects/13
As you can see there isn't too much missing there. The tricky part is writig elegant code, not getting it running. If those parts are implemented in JavaFX, we should be able to just drop the current swing code for the same controls and just create the "swing-javafx-bridge" when actually launching the game. This approach avoids a drastic design change within the same screen.

Your opinion?

**Comment by DanVanAtta** [comment]
@RoiEXLab you're then thinking to do more the opposite, have the settings screen be rendered with javaFX from within the swing app?

**Comment by DanVanAtta** [comment]
@RoiEXLab I think we'll need to back up from that. It may be the right thing to do, the ordering is wrong though IMO.
- a settings screen in JavaFX commits us to having JavaFX in the app. Until we have the staging screens replaced, we are not ready for that. 
- the parallel code route is burdensome. There is no reason we can't re-use the core logic code of the original settings screen. I think we need to avoid parallel code for any kind of logic and focus on having a re-skinned UI. As soon as we start writing the same logic twice, I think we'll fall into a trap. Notably if we get into that trap, the migration is going to be an extraordinarily heavy lift, possibly more so than we have resources.

I think then the thing to do is, for now, render the settings as the swing component & remove the JavaFX parallel code.

**Comment by DanVanAtta** [comment]
Let's consolidate this discussion to forum: https://forums.triplea-game.org/topic/2076/javafx-update-of-staging-screens

And use the project to track any TODO items.
