### ISSUE TITLE
prod 2 bots are not relaunching

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#6729]
I sent you a PM @DanVanAtta  it might be inconsequential but it appears the prod 2 bots are not relaunching.  They work fine in .200081.  Will they need to be micro managed through infrastructure every update?

_Originally posted by @prastle in https://github.com/triplea-game/triplea/issues/5025#issuecomment-647160992_

**Comment by DanVanAtta** [comment]
@prastle moving this to a new issue. Please get in the habit kindly of creating new issues so we can keep conversations about one topic. Some topics are going to get incredibly involved, discussing this in the 2.0 thread would hijack that and also result in confusion. It also gets less sustainable if we try to discuss yet more topics.

Can you describe what you mean by "not relaunching" @prastle ?

**Comment by DanVanAtta** [comment]
>  Will they need to be micro managed through infrastructure every update?

Were you managing them by hand in any way @prastle ? I wonder if there is a communication gap, in general we should not be needing to log into the servers for anything, and if we do it should be documented so we can fix the real problem with a true fix.

**Comment by prastle** [comment]
@DanVanAtta 
  
Sure I can describe... I did not realize I needed an acurate description to describe "Not launching" and micro manage...  
LOG INTO THE LATEST PRERELEASE LOBBY!
NOTE THAT THE TWO LINODE BOT SERVERS OF 14 total bots ARE NOT THERE !  Only the lobby server bots are of 2 bots.,,,  NOW LOG INTO 2.0.20081  Note that the servers are there...

Thus why I asked do they need to be micro managed every release?

**Comment by DanVanAtta** [comment]
@prastle the detailed description is to avoid back-and-forths and so we can be sure we are both looking at the same thing. While something might be obvious to you, without looking at your screen and being there in person, it can be very non-obvious.

First, you said nothing about prerelease until just now.  Is this a problem on prerelease or prod2?? This is why having specific instructions of what you are doing is useful so I can follow along exactly and not guess what you mean or fill in words for you. This is why we have the question template in issues and ask that people fill it out so we can use our time efficiently.


> LOG INTO THE LATEST PRERELEASE LOBBY!

You mentioned prod2, is the problem in prod2 or prerelease? 

> NOTE THAT THE TWO LINODE BOT SERVERS OF 14 total bots ARE NOT THERE ! 

What makes you think there should be two linode servers of bots for prerelease? 

> Only the lobby server bots are of 2 bots.,,,

2 bots in the prerelease lobby is expected.

> Thus why I asked do they need to be micro managed every release?

Please double check when you ask such questions that they are both specific and helpful.

**Comment by prastle** [comment]
I guess I asked a stupid ? by private messaging...  so production2 has the 2 servers running off 
2.0.20081
 and all pre release has just 2 bots from the pre server?  Thus why I ask why did we launch these bots?

**Comment by DanVanAtta** [comment]
Prod2 is running 20026 with 4 bot servers running 28 bot game instances.
Prerelease has no bot servers and is running 2 bot game instances.

> Thus why I ask why did we launch these bots?

Which ones are you referring to?

**Comment by prastle** [comment]
prod 2
is what I am referring 2.  Why do we need 28 bots on an old pre release?

**Comment by DanVanAtta** [comment]
prod2 is not a pre-release environment.
2.0.20057 or greater will connect to prod2.


> is what I am referring 2.

Was this a question?? It could be worth taking an extra minute to type complete sentences for clarity of communication.

**Comment by DanVanAtta** [comment]
The connection rules can be found [servers.yml](https://github.com/triplea-game/triplea/blob/master/servers.yml), updates to that file impact live users.

```
[2.0 - 2.0.19800) -> prerelease
[2.0.19800 - 2.0.20098) -> inactive, "you need to upgrade message"
[2.0.20098+) -> prod2
```

Considering you need a version under `2.0.19800`, I would have been a bit surprised if you were actually connecting to prerelease. A build from source code will have version `2.0.0`, that is the typical way now to access the prerelease lobby.

It sounds like you're connecting to the prod2 lobby all along here.

@prastle I'm not really sure what questions you have at this point. Please clarify any that you may have. I'm happy to help get this straightened out.

**Comment by prastle** [comment]
It is all good... It appears i had a broken download or something since 2.0.20123 opens and has all servers.  I am sorry for the inconvenience.  Feel free to close this issue. Thanks @DanVanAtta
