### ISSUE TITLE
64 bit IP address support

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#673]
I checked 'whatismyip' today and was surprised to see a 64 bit IP address. I could host and connect to the same game using the 64 bit IP, but an opponent connecting got an error message back "null" (no screenshot available).

We may have other things broken with 64 bit IPs. Supporting them is going to get more important as 64 bit IP is rolled out throughout the US.

**Comment by RoiEXLab** [comment]
Are 64bit IP's actually a thing? Never heard about those... I know that here in Germany IPv6 IP's are getting more "popular" (I heard that some ISP's sell IPv6 only internet) - so more and more ISP's are supporting IPv6 by default...

**Comment by DanVanAtta** [comment]
Apparently yes. I found out recently the hard way that I now have a 64 bit IP address (to my displeasure). It was assigned to me by Comcast, which is a major provider for most of the United States West Coast, a relatively large chunk of the US population.

**Comment by ron-murhammer** [comment]
Interesting. I wasn't aware that it wouldn't work. No idea if this would be an easy fix or if we are talking about needing a new library.

**Comment by DanVanAtta** [comment]
:white_flag:  for now
