### ISSUE TITLE
Turn posting with current release and pre-releases is broken.

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#6735]
### How can the problem be recreated?
As reported on the forum
https://forums.triplea-game.org/topic/2073/turn-posting-is-broken-with-pre-release-my-map-is-now-posting-turn-history-in-weird-way
and further tested starting from here:
https://www.axisandallies.org/forums/post/1410278

the posting of turn summaries ist somehow broken.

Look here:

![2](https://user-images.githubusercontent.com/20812775/85267647-ceaf7500-b475-11ea-8866-27ccd09a550e.png)

Note that some parts of the summary are posted as plain text and only the rest as "code-block".

### What is an expected fix?

It should look like this (posted with latest 1.9.stable):

![1](https://user-images.githubusercontent.com/20812775/85267522-ab84c580-b475-11ea-941b-29d62e8a8f25.png)

The whole summary is posted as "code-block".

### Which Engine Version are you using?

2.0.123 (first noted with 2.0.080)

### (Optional) Additional information

The bug has been introduced at any time starting from 2.0.18907 (last version I tested turn posting successfully with).

I verfied that this is not a map issue by testing other maps, too, for example:

![3](https://user-images.githubusercontent.com/20812775/85268066-51d0cb00-b476-11ea-8989-c71f96f04e1b.png)

**Note:** Despite the XML-map version is something like 1.9 or 3.0 the engine somehow enhances the map version to 1.9.0 or 3.0.0 for any reason.... maybe this is related?

**Comment by RoiEXLab** [comment]
#6780 might have a fix for this.
If my theory is correct then https://github.com/triplea-game/triplea/releases/tag/2.0.20036 should be the last version without this issue and https://github.com/triplea-game/triplea/releases/tag/2.0.20039 the version that introduced it
