### ISSUE TITLE
Use Lobby as Email Relay for PBEM

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#675]
Would be a nice feature to be able to route a save game file through the lobby to send PBEM games. Effectively we would combine the following actions into a single action:
- saving a game
- attaching it to an email
- sending it to an opponent

**Comment by ron-murhammer** [comment]
@DanVanAtta What is the use case here? Is it sending the save game to everyone when a lobby session is over so it can be continued later? Or do people want to essentially play PBEM games on the lobby?

**Comment by DanVanAtta** [comment]
It's actually for simple PBEM games, as a way to provide for an in-game 'send-email' function. Avoids folks from having to "save", and then send the save via email with an external program.

**Comment by DanVanAtta** [comment]
For latest, refer to: https://github.com/triplea-game/triplea/issues/1049
