### ISSUE TITLE
Lobby Game Lag

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#676]
Playing a game via direct connection is noticeably faster compared to playing over the lobby. Why and where is the lobby introducing lag into the game?

**Comment by ron-murhammer** [comment]
No idea. The part of the code I know the least is probably the lobby code. I wouldn't consider this a bug but more of an enhancement to reduce lobby lag. I think we probably want to try to utilize 'bug' label for things that are actually not functioning properly.

**Comment by DanVanAtta** [comment]
Not quite the lobby code that is the culprit, but the network game code that is connected to the lobby. Hosting a network game directly does not have the same lag. In theory the lag overhead of lobby should be minimal.
