### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by blinchik1aaa** [triplea-game/triplea#6765]
Bot 303 crashed - WAW 1940 map - when an attack on neutral country (Croatia) started (rd 1, during combat phase).

Bot crashed again when reopening the map.

**Comment by DanVanAtta** [comment]
Thanks for reporting @blinchik1aaa 

Same problem as: https://github.com/triplea-game/triplea/issues/6766

This has been fixed on the 1xx, 2xx and 3xx bot servers. 4xx servers are not yet patched.
