### ISSUE TITLE
Game Crash when NWO map enters combat

### ISSUE THREAD

**Issue by mortetvie** [triplea-game/triplea#6766]
Game crashes when combat begins (may be specific to neutral nations).

Bot405_London:  Jun 23, 2020 5:33:28 PM games.strategy.engine.framework.startup.launcher.ServerLauncher launchInternal
Bot405_London:  SEVERE: Unrecognized error occurred. If this is a repeatable error, please make a copy of this savegame and report to:
Bot405_London:  https://github.com/triplea-game/triplea/issues/new
Bot405_London:  java.lang.RuntimeException: Exception on remote
Bot405_London:  	at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:58)
Bot405_London:  	at games.strategy.engine.framework.$Proxy38.startPlayerStep(Unknown Source)
Bot405_London:  	at games.strategy.engine.framework.ServerGame.waitForPlayerToFinishStep(ServerGame.java:545)
Bot405_London:  	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:408)
Bot405_London:  	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:297)
Bot405_London:  	at games.strategy.engine.framework.startup.launcher.ServerLauncher.launchInternal(ServerLauncher.java:169)
Bot405_London:  	at games.strategy.engine.framework.startup.launcher.ServerLauncher.launchInternal(ServerLauncher.java:37)
Bot405_London:  	at games.strategy.engine.framework.startup.launcher.AbstractLauncher.lambda$launch$0(AbstractLauncher.java:16)
Bot405_London:  	at java.base/java.lang.Thread.run(Thread.java:834)
Bot405_London:  Caused by: java.lang.RuntimeException: Exception on remote
Bot405_London:  	at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:58)
Bot405_London:  	at com.sun.proxy.$Proxy16.fightBattle(Unknown Source)
Bot405_London:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Bot405_London:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Bot405_London:  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Bot405_London:  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)

**Comment by DanVanAtta** [comment]
Thanks for reporting this @mortetvie 

A fix has been deployed for bot serves 1xx, 2xx and 3xx. 

4xx is still on a slightly older version and will experience this problem. We'll patch that server as soon as the games on it finish up.

**Comment by DanVanAtta** [comment]
All bots are now updated.
