### ISSUE TITLE
Problem Report Information in Lobby (2.0.20183)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#6768]
Currently the lobby is missing clear information on where to report problems.

I think the "Help" function should have a direct link for reporting problems.

Otherwise, or until that is made available, I suggest adding this link at the start of the lobby chatlog, like in the past:
https://github.com/triplea-game/triplea/issues

I know that they get the information when a bot crashes.

**Comment by Cernelius** [comment]
I meant something like this somewhere in the starting chatlog:

>Report every problem in here:
https://github.com/triplea-game/triplea/issues

**Comment by DanVanAtta** [comment]
That's a good idea @Cernelius 

Updated the lobby message: https://github.com/triplea-game/triplea/pull/6776

To change the 'help' menu players will need to download a new version  (so can't be done quickly).
