### ISSUE TITLE
Live Games - New Players Lag The Game

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#677]
Motivation and Summary:
While new players are joining a game, the entire game is frozen. For advanced round games, where the game data object is around 1MB, and many people join and some over slow connections, it can make lobby games difficult to play.

Task:
- Identify what/where is blocking the game when new players are joining
- Identify and implement a way to prevent this, so that game data can be sent to the new player without freezing the in-progress game.

**Comment by ron-murhammer** [comment]
I have a feeling this would be difficult to do properly as you'll need to play with data locks and threads. Might be better to focus efforts on improving save game format and reducing its size then this is pretty much a non-issue.

**Comment by DanVanAtta** [comment]
If there is a nice way to do the transfer in a background thread, could be a big quick win. The file save format I regret is likely some time out.

**Comment by RoiEXLab** [comment]
Side Note: I would call this a low priority bug

**Comment by DanVanAtta** [comment]
TripleA community is pretty large. Consider a live game, live games that go past 10 rounds tend to get lots of visitors. Consider also it being large map, where an individual visitor typically lags the game for 30 seconds. That is 30 full seconds where nothing can happen in the game UI.

Now, one person joins the game, and is very common, will leave about 10 seconds after joining. There is also an exit lag as well, but it is not as bad. This is nearly 40 seconds of nothing happening due to lag. If you are trying to keep your turn under 3 minutes, it's already a 30% increase in the game play there. Then consider if this happens for 3, 4, 5 more players that join, it's a pretty massive game delay that makes it hard to play.

The password feature is most used expressly to avoid this game connection lag. Really this should probably be called a bug, the threading/locking for joining observers is simply not correct nor scalable. Games that last into late rounds, and on large maps, is not necessarily a common case, so this is an example of somethign that is highly annoying, but not necessarily critical to fix.

**Comment by DanVanAtta** [comment]
Backlogged: https://github.com/triplea-game/triplea/wiki/Feature-Back-Log
