### ISSUE TITLE
JodaTime lib

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#678]
Any objections to bringing in JodaTime?

**Comment by ron-murhammer** [comment]
I thought Java 8 introduced better date/time classes now in the standard JDK?

**Comment by DanVanAtta** [comment]
Regrettably that is coming in Java 9 and was not in 8.

**Comment by DanVanAtta** [comment]
If a place comes up to use Joda time, it seems like there is no objection to using it. Closing in the meantime.
