### ISSUE TITLE
@Developers - 2.0 Issue Surge & Fix Release

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#6795]
- I'm expecting we'll push a fix release tomorrow or the day after
- @asvitkine @trevan @RoiEXLab , if ya'll could focus on any of the error reports and fixing any issues, would be appreciated. I'd like for us to get as many quick fixes in as possible.

I documented the issue lifecycle here: https://github.com/triplea-game/triplea/wiki/Issue-WorkFlow-And-LifeCycle

Just importantly be sure to assign something to yourself when you start any work and unassign (if failed to fix) or close the issue when a PR is up (and quite confident in the fix).

**Comment by trevan** [comment]
I don't have permissions to assign myself to issues or to close issues.
