### ISSUE TITLE
should we remove Dynamix AI?

### ISSUE THREAD

**Issue by veqryn** [triplea-game/triplea#68]
Now that we have a much better AI, should we remove the half-done, land-only, Dynamix AI?
The main reasons to keep it around would be because maybe some people like playing against it, or maybe Redrum is still using it for inspiration on his own AI.
@ron-murhammer: Redrum, mostly looking for your opinion on this, as you are the official AI guy these days.

**Comment by DanVanAtta** [comment]
#58 ,#54, #65 (sorry to make you redo the eclipse formatting, but it'll be easier than redoing #54 which was done by hand)
#66 (important fix, removes one "synchronization" keyword to mitigate a deadlock problem I'm seeing)

**Comment by veqryn** [comment]
See #70

**Comment by ron-murhammer** [comment]
Hmm. I've mostly used Strong and Weak AI as inspiration as they are easier to follow but have taken a few things from Dynamix such as the AI log window, fighter/carrier sorting, a few matches, and a few utils. At this point, I don't think there is really much left that is useful. I'm fine with removing it as long as you can't think of any other features or utils that would be useful.

@veqryn, Thoughts? If you agree then I'll review the pull request and merge it.

**Comment by veqryn** [comment]
Ya, I would like to get rid of it.

**Comment by ron-murhammer** [comment]
Merged. Closing this issue.
