### ISSUE TITLE
Perf Console remembers it was closed (was: Performance Console Removal?)

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#681]
Any objections if we remove performance console, instead have the output simply go to Standard out? 

Tasks:
- Remove performance console
- Remove any PerfTimer usages in the code
- Delete the StopWatch class, we have a the Perftimer with a much simpler API that does the same thing

**Comment by ron-murhammer** [comment]
I'm fine either way on this. When testing it is kind of nice to have a separate performance window. Its probably more of a debug tool used by developers more than anything so whatever we feel is most useful is probably best.

**Comment by DanVanAtta** [comment]
I find it annoying it keeps popping up all the time. Really the thing to do is that whenever it is closed, we set a system prop to remember that it is closed. As is, when you close it, it'll pop-up again the next time the game is launched.

I agree it is nice to have the different window for perf, and slightly better than stdout. Let's do the improvement above instead.

**Comment by DanVanAtta** [comment]
Put on a backlog list: https://github.com/triplea-game/triplea/wiki/Feature-Back-Log, closing.
