### ISSUE TITLE
Combat results dialogue box too big

### ISSUE THREAD

**Issue by jfstolar** [triplea-game/triplea#6825]
### How can the problem be recreated?

When combat occurs, the box is too large for the screen and I have to manually shrink it every time to see the bottom button.
I am using a 4k screen.

### Do you have any ideas for an expected fix?

adjust the box size to a smaller percentage of the screen

### If playing a prerelease, which version are you using?

Game Version:

Latest and greatest just downloaded today version 2

### If playing a prerelease, does this happen on the latest release?

- [ ] yes
- [ ] no

**Comment by asvitkine** [comment]
Can you provide a screenshot? What resolution is your monitor set to?

**Comment by jfstolar** [comment]
I'm running on a Dell Precision 5510 with latest windows 10 release build
and with a 4k laptop screen.

As you can see in the screenshot, the combat window is too large. Even if I
hide the taskbar at the bottom, I can't select casualties.  I have to
manually shrink the windows each time (the size settings don't stick).
Thanks

**Comment by asvitkine** [comment]
I'm not seeing a screenshot? Maybe because you replied over email and not through GitHub UI?

**Comment by jfstolar** [comment]
![Screenshot (7)](https://user-images.githubusercontent.com/17705658/85959838-75a77b80-b964-11ea-89ca-ec72b88e2b37.png)

Attached via github this time.

**Comment by asvitkine** [comment]
Interesting. The width of that window is over 3000 pixels, yet the code tries to make a 1024x768 window when the monitor resolution is higher than that.

So maybe your system is set up to do 3x scaling. My guess is the bug in TripleA is we query the display size, but don't account for HighDPI scaling. I'll take a look to see if that can be fixed.

**Comment by jfstolar** [comment]
You got it! I'm doing exactly 3x scaling. Thanks for looking into this.

**Comment by asvitkine** [comment]
Let me know if it works for you with that change!

**Comment by jfstolar** [comment]
Yes. Download the latest build and it works perfectly. Thanks!
