### ISSUE TITLE
Save Game Manager UI

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#686]
We could use a UI window that shows save games.
1. Has a default folder
2. Folder options configurable, can add extra folders to be search, for example, "/home/user/Downloads"

The save game UI would perhaps be pretty similar to the install map dialog. Selection list on the left, details on the right.

With each save game, can indicate:
- opponent count + names
- game round
- map
- date last played
- date started
- (?)  last game type played (local vs AI, PBEM, lobby, direct network)

Each game should have an option to load it, and a second button to delete it (with delete confirmation)

When saving games, we will just overwrite the last game save. Add an option to the game menus to "save game as" to be able to "fork" the game.

**Comment by ron-murhammer** [comment]
@DanVanAtta Yep this is pretty standard for most strategy games and would especially help less tech savvy users to manage their saves.

**Comment by DanVanAtta** [comment]
back logged: https://github.com/triplea-game/triplea/wiki/Feature-Back-Log/
