### ISSUE TITLE
The battle calculator on domination 1914 NML is freezing games. After you hit calculate, the calculation never completes and the gaem becomes frozen. This may be realted to multinational calcs, calcs  with multiple nations units on defense that is, or calculating when it is not your turn. I think multinational calcs are causing it however.

### ISSUE THREAD

**Issue by samstreeter** [triplea-game/triplea#6868]
### If playing a prerelease, which version are you using?

Game Version:

### If playing a prerelease, does this happen on the latest release?

- [ ] yes
- [ ] no

**Comment by asvitkine** [comment]
Do you have specific repro steps?

**Comment by beelee1** [comment]
@asvitkine this means he's probably playing live in the lobby
 _calculating when it is not your turn_
Not 100% certain but it may also happen if using Edit. A lot of things don't work correctly when in edit mode.

**Comment by asvitkine** [comment]
I'm going to close this out since it's an old report and there were lots of improvements to the relevant code.
