### ISSUE TITLE
Use mock objects only in test code

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#687]
This is a far better place for discussing Code Snippets...
https://github.com/triplea-game/triplea/compare/master...RoiEXLab:Mock-test-patch-1

**Comment by RoiEXLab** [comment]
> These test helper methods should just be mocks:
@Mock
private IDelegateBridge mockDelegateBridge;

I understand, why it makes sense to create mocks instead of helper methods, but I think it's actually better to still create a private variable and calling a getTestDelegateBridge(GameData data) method, in Order tohave at least the data (which is needed everywhere) assigned by default, so no extra line of code in the method being called first(or the consturctor) is needed

**Comment by RoiEXLab** [comment]
So I created a Mock object just like you told me and no I'm getting a NullPointer at the `when(bridge.getData()).thenReturn(data);` line...

**Comment by DanVanAtta** [comment]
You're missing the @RunWith annotation at the top of your class:
```
 import junit.framework.TestCase;
 
 public class AirThatCantLandUtilTest extends TestCase {
```

Shoudl be:
```
 import junit.framework.TestCase;
 
@RunWith(MockitoJunit4Runner.class)
 public class AirThatCantLandUtilTest extends TestCase {
```

The RunWith tell Mockito to pick up this class, find and create mocks for any @Mock annotations. Otherwise the @Mock does nothing, and your `bridge` object is just:  `private IDelegateBridge bridge;`, which is the same as `private IDelegateBridge bridge = null`.

**Comment by RoiEXLab** [comment]
Actually it is `MockitoJUnitRunner.class`

**Comment by RoiEXLab** [comment]
Still not working ._.
Not getting a NullPointer, but an initialization error since this class is not having any &#64;Test Methods

**Comment by DanVanAtta** [comment]
That's easier to deal with. You're running a Junit3 test with a Junit4 runner sounds like.

Remove the ` extends TestCase `, then add a '@Test' to any public method that begins with the word test.

**Comment by RoiEXLab** [comment]
Well I think now we're getting to the "real" problem...
for whatever reason assertions are failing or throwing exceptions...
I noticed, that I did a `when(bridge.getStepName()).thenReturn("NonCombatMove")`, but the test methods are checking `data.getSequence().getStep().getName().endsWith("NonCombatMove")` where data is `bridge.getData()`

**Comment by DanVanAtta** [comment]
Not sure if I follow the latest, could you be more explicit? Preferably with some exact error messages. It sounds a bit like you expect the "when...thenReturn" to modify the behavior of the code. It does not modify the execution flow at all, it only defines behavior of what the mock objects should do when they are invoked. If no behavior is defined, they will typically return 'null'. Hence, if you did not define a behavior for: `data.getSequence().getStep().getName().endsWith("NonCombatMove")`, you'll get a NPE in there.

**Comment by DanVanAtta** [comment]
@RoiEXLab  do be careful of 'trying to hard' to test the code with mocks. Some of it is just not easily testable, and doing really complicated things to test with mocks is not worth it. Instead focus on breaking up the functionality into modules which can in turn be tested.

**Comment by RoiEXLab** [comment]
The Problem is, that LoadGameUtil.loadTestGame("revised_test.xml") returns valid gameData (non-mock-data) which cannot be modified that easily (there are no setter methods) that's  why `data.getSequence().getStep().getName().endsWith("NonCombatMove")` is actually not returning a NullPointer but a default value instead which cannot be modiefied due to the lack of setter methods...

**Comment by DanVanAtta** [comment]
Instead of:
```
GameData data =  LoadGameUtil.loadTestGame("revised_test.xml")
```

Try this:

```
@Mock
GameData data;
```

Then you don't even have to bother with the LoadGameUtil. 

Side comment: This is a good example why static method calls are not so good, lots of tight coupling, which makes more and more of the system related to one another, making things that much harder to change since you have to then trace the entire spider web to change the smallest module.

**Comment by RoiEXLab** [comment]
Oh man... Couldn't you take over this one?
I think this would go much quicker since you are more experienced using JUnit and Mock Objects...
I know know how they work and what their purpouse is - but currently this is not more than a Q&A with you doing the thinking...
This way I could focus on well more relevant tasks like bugs or highly requested features etc.

**Comment by DanVanAtta** [comment]
Sure, sounds like we would both be more effective that way.

**Comment by RoiEXLab** [comment]
Ok thanks

**Comment by RoiEXLab** [comment]
Actually It may be better to start at the begginning because of the setRandomSource thing... Well it's your decision now

**Comment by RoiEXLab** [comment]
Changed the Title to be more general

**Comment by RoiEXLab** [comment]
Since all tests are now using Junit 4 the only goal of this issue is to remind us to change the test objects to mock objects.

**Comment by DanVanAtta** [comment]
Adding a note to prefer mockito over mock objects to: http://www.triplea-game.org/dev_docs/dev/code_standards
