### ISSUE TITLE
Allow AI to place bid in allied territories

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#69]
Please assign to @ron-murhammer 

Code to do it would look something like this:  

( https://reviewable.io/reviews/triplea-game/triplea/54#-JwSqFD6mzl6vTFqIOEF, ProPurchaseAI.java)

```
    /*
       * Currently the place delegate does not accept bids by the AI to territories that it does not own. If that gets fixed we can add the
       * following code in order to bid to allied territories that contain our units (like Libya in ww2v3) (veqryn)
       * for(Territory alliedTerr : ourFriendlyTerr)
       * {
       * if(!Matches.isTerritoryOwnedBy(player).match(alliedTerr) && alliedTerr.getUnits().getMatches(Matches.unitIsOwnedBy(player)).size()
       * > 0)
       * {
       * ourSemiRankedBidTerrs.add(alliedTerr);
       * }
       * }
       */
```

**Comment by veqryn** [comment]
If someone is working on a set of files, and they make comments mixed with some commented out code like that, I generally consider that as a whole to be a comment, not dead code.

I also would like to cut down on needless issues being opened.

**Comment by ron-murhammer** [comment]
So the AI bid logic needs completely rewritten as it still uses the logic from the old Moore AI. So I'm not going to put any small changes into it as it would just be a waste of time.

**Comment by ron-murhammer** [comment]
The comment is actually copy and pasted from the old Moore AI as well so it can just be removed. I'm gonna just close this issue. If anything I would eventually like to discuss exactly what the best strategy would be for a good AI bid algorithm but there are still a number of AI priorities ahead of that so will table it for now.
