### ISSUE TITLE
The latest TripleA loads with most buttons disabled.  The enabled PlayOnline button does not trigger any action.  

### ISSUE THREAD

**Issue by nekengren** [triplea-game/triplea#6902]
The latest TripleA loads with most buttons including StartLocalGame disabled.  The enabled PlayOnline button does not trigger any action.  
![image](https://user-images.githubusercontent.com/67523308/85934415-e6d92700-b8af-11ea-9c86-b5e66c3c1dc3.png)

**Comment by beelee1** [comment]
Hi @nekengren 
You are using an old triplea version "1.9.0.0.3627". Try updating to the latest and see if it works. A new "2.0" version came out recently that is incompatible with previous saved games but "1.9.0.0.13066" should still work.
