### ISSUE TITLE
Tackling, De-Duping & Fixing Error Reports

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#6918]
Now that error reports are live, we have a new set of challenges:
- how do we de-dupe error reports effectively?
- how do we know which ones are fixed?
- how do we know which ones were supposed to be fixed but turns out were not? (IE: we fixed, closed the issue, released, but a new version still has a problem)
- how do we avoid splitting conversations between multiple same-error report issues?

In the short term we have to do manual work. I recommend we favor the earliest error report that we have seen. I can't recommend a good way to know we fixed error reports, I'm interested in any ideas/suggestions to help out. We could do an error report registry somewhere, or perhaps just focus on getting fast-turn-around patch releases out..

Long term, we need some automation. I'm most concerned we'll have a long running compatibility breaking release and will see error reports get created even though they are fixed in a version users can't pick up. (Tangent: that adds more importance for us renew focus on compatibility projects so that is less of a problem).

I think we could have Spitfire keep track of error report titles in database and de-dupe them for us. If it sees an existing error report then comments on it, if it sees the error report has been fixed then it can inform the user of a fix version (assuming the fix version is greater than the current version being run).

A DB table column that adds the error report title and issue number should be enough to know that an error report exists and as which issue. A column with the fix number seems logical. Though, I'm not sure the best way for the server to know a fix has been done. Perhaps we could do a magic comment like "Fixed in version: X.Y.Z" and the server could read that to know that an issue has been fixed (perhaps then we would not even need the fixed version column). It would be nice for the server to respond to issues after the magic comment has been added and to close the issue, but then we need the server to do issue scanning and I don't think we really want that. So i'm curious if anyone has good suggestions for how the server can handle a fix notification and what that could look like.

**Comment by trevan** [comment]
Some of the error reports appear to be caused by map makers.  I think #7045 (and its duplicates), #7044, and #6898 only occur when the maps are being modified.  Should these be reported?

**Comment by DanVanAtta** [comment]
Reportable issues should generally be game-crashes. Non-reportable issues should be items where a user can "create the error" and we can tell them how to fix it, EG: hosting on the same port twice, injecting a syntax error into XML or a properties file.

Generally the game should never crash through any series of clicks or actions that a user can take, but only when something actually exceptional (and error-like) happens. For example, server crashes or data corruptions during network transfer, NPEs and any other game-bug.

**Comment by simon33-2** [comment]
What are all the tripleabuilderbot issues. Are many of them fixed already? Interesting in helping clearing them out if possible.

**Comment by DanVanAtta** [comment]
The 2.1.x reports should get de-duped when users report them. Namely they are told an issue already exists and they cannot create a new one. The de-dupe is based on title. So we do not have a sense of frequency.

With that said, all of the error reports are either game crashes that users experience on a day to day basis or they are items where the game has poor error-handling and is using control-flow-by-exception to handle non-happy cases.

For example, let's say a field requires only numbers, and a user types in letters. The code in TripleA is often instead of saying "you should not input letters here, only numbers", it's throwing a NumberFormatException and showing that to the user. 

So, for all error reports we either need to:
- fix the problem
- fix the logging/error handling. Convert any severe logging down to warning and be sure we have a clear human-understandable message that tells a user how to fix the problem they encountered. For example, with double hosting and failing to bind to a port, we shoudl tell the user "this port is already in use, choose a different port" rather than showing "SocketBindException".

Severe logging will show an option to submit a bug report, warning logging will only show a dialog to the user without option to submit.

@simon33-2 any fixes are really welcome, assign issues to yourself as you pick them up and unassign them if you stop work on them.

**Comment by tvleavitt** [comment]
Should we have a separate mechanism that logs an attempted duplicate
report? Seems like frequency and details would be useful debugging and
prioritization tools.

End users with duplicate reports should be given an opportunity to follow
the existing one and comment; perhaps also including a stack trace?

Thomas Leavitt

**Comment by DanVanAtta** [comment]
We could get frequency in database, but I'm not sure how to expose that publicly well. Having the system comment on existing issues perhaps would work. To some extent we just need to get around to doing that as well. Arguably we would be better to focus on fixes.

Reports that are existing are shown as a link to users, so they can comment on them if they go that far to click on it.

**Comment by DanVanAtta** [comment]
A PR was submitted so that we get de-duping on title. Perhaps we could go further. Resolving this issue for now.
