### ISSUE TITLE
Victory Bonds not working for Steampunk Advanced

### ISSUE THREAD

**Issue by SwampyAcres** [triplea-game/triplea#6933]
After upgrading to 2.0 I notice that "Victory Bonds" technology no longer does the dice roll. It is still research-able via the tech tree.. it give the +1 production (which is part of "Victory Bonds".. .but it does NOT do the dice roll for extrac IPC. 

Please see attached save game. Both France and USA have rolled "Victory Bonds" tech.. but neither is collecting income. Please note I just changed changed the file extension to ".zip".. it is not actually a zip file, just rename to ".tsvg" . I had to do this as GitHub doesn't allow tsvg file types. 

[2020-6-30-Steampunk-Advanced.zip](https://github.com/triplea-game/triplea/files/4851078/2020-6-30-Steampunk-Advanced.zip)

**Comment by SwampyAcres** [comment]
Hi.. I am now using Triplea version 2.2.20868 and the issues appears to be resolved.

**Comment by DanVanAtta** [comment]
A magic fix is not cool, as it might break again without us realizing, but hey, that is good news   :+1: 
Thanks for reporting back @SwampyAcres
