### ISSUE TITLE
Hidden Units Are Accounted in the "Players" Tab (2.0.20234)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#7000]
Hidden (per the `dont_draw_units` skin property) units are still accounted in the "Units" column in the "Players" tab. I believe they should better not. For coherency, they shouldn't be accounted in the TUV, either.

I have a map in which every land zone has a factory, thus I've hidden them all (it's pointless to show any of them). However, this is making the "Units" column in the units table almost useless, in the moment it counts them. It doesn't matter for the TUV, since these units have value 0.

@ron-murhammer Is this actually a problem or did you intend for such units to be accounted in the "Players" tab? If the behaviour is intended, please change the label to whatever it is fitting with my request of changing it. I see such units are not accounted in the Territory tab, instead.

**Comment by DanVanAtta** [comment]
Thanks for the problem report @Cernelius 

#7245 will fix this

**Comment by Cernelius** [comment]
Testing with 2.1.20688 on my unreleased map, it appears to work fine for the units (I've not tested for the TUV, as all hidden units cost nothing).
