### ISSUE TITLE
The Maps Folder Resets to Default When Closing The Program (2.1.20365)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#7004]
I actually assume this is what it is doing, as I don't have a "downloadedMaps" folder in the default location, so, every time I open TripleA, it's like I have no maps at all.

I also suspect that all "Engine Preferences" customization is lost every time you close the program.

This is a major problem for me, since I keep the maps not in the default location. Now I have to customize "Engine Preferences" each time I open TripleA, over and over again (or my "Select a Game" window will be empty).

This didn't happen with 2.0.20234.

I'm on Windows 10 and Java version 11.0.6.

**Comment by RoiEXLab** [comment]
Perhaps cause by #6926 ?

**Comment by DanVanAtta** [comment]
Almost certainly related.

**Comment by Cernelius** [comment]
Likely not very important to common users, but I believe this is a regression.

Tested it still exists for 2.1.20688.

I'm currently simply using the folder at its default location.

It seems that, at least for what I've customized, the rest of the "Engine Preferences" customization is not lost, instead.

The "Maps Folder" field is just blank (not even showing the default path that it is using).
