### ISSUE TITLE
TripleA dowloadedMaps folder setting not saving.

### ISSUE THREAD

**Issue by NetHackFan1006** [triplea-game/triplea#7029]
In the newest update (TripleA-2.1.20365 on a Windows 10 machine), the engine preference to select the folder path for downloaded maps will not save. It starts off not looking at any directory for maps. When I tell it where to look then the engine can find the maps. But even after saving the options once I quit the program it resets to nothing. When starting TripleA the path to the maps is always blank. 

-Edit- I have uninstalled and reinstalled TripleA and the problem persists.

**Comment by Cernelius** [comment]
https://github.com/triplea-game/triplea/issues/7004
