### ISSUE TITLE
Map Making work flow - game engine pick up map clones.

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#703]
It's very ackward to download a map, expand it, modify files, load it in the game, and then to repost the zip file somewhere.

I'm thinking we should update the game engine, so if you cloned a map repo directly into 'downloadMaps', that the game engine would pick up the map.

The change needed to the engine is so that it will look inside of a 'map' folder for game files.

**Comment by ron-murhammer** [comment]
@DanVanAtta I thought this already worked. I believe if you extract a zip in the maps folder it will still load the game.

**Comment by DanVanAtta** [comment]
There is a nuance here perhaps. Part of the idea is to eliminate all zipping/unzipping from the work flow.

Effectively it would be to support this type of thing:
```
cd ~/triplea/downloadedMaps
git clone git@github.com:triplea-maps/world_at_war.git
```

And then allow the map to be loaded by the game engine.
