### ISSUE TITLE
We seem to be missing alot of bots at a quick glance.

### ISSUE THREAD

**Issue by prastle** [triplea-game/triplea#7087]
### How can the problem be recreated?
join the lobby and glance at the number of available bots
### Do you have any ideas for an expected fix?
Fix the chron job for reattachment?  NIDEA why they are missing
### Attach a Save Game
screen shot attached

![2020-07-09](https://user-images.githubusercontent.com/17258293/87104167-10397180-c225-11ea-9f84-f2b0adfcc5a3.png)

**Comment by DanVanAtta** [comment]
It is this problem: https://github.com/triplea-game/triplea/issues/7005

Every time we merge each bot will download the full list of maps. With the full list of maps we get duplicates. If the bot crashes or restarts then it'll hit #7005 and crash on start and restart (causing an infinite restart).

**Comment by DanVanAtta** [comment]
@prastle thanks for the bug report here  :+1:
