### ISSUE TITLE
Back button for turn phases

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#710]
The first one is a Back button in the "Place Units" phase in particular. This will save a huge number of edits. 

http://tripleadev.1671093.n2.nabble.com/Development-To-Do-list-tp7582044p7592337.html

Related:

> The second one is a combined "Purchase Units", "Repair Units", "Politics" and "Combat Move" phase. Second best would be to expand the back button to all the above phases except the first. Indeed, adding a "Back to Politics" button in combat move would mean you don't need to show it by default when war on neutrals is the only option. I guess that could be argued. Some of this violates the exact rule about turn order so that part might need to be an option. Particularly I want to be able to try combat moves and then change purchases.

**Comment by Cernelius** [comment]
Related:
http://tripleadev.1671093.n2.nabble.com/Seig-trio-default-rules-discussion-tp7590530.html;cid=1468248178488-560

**Comment by DanVanAtta** [comment]
Closing in favor of: https://github.com/triplea-game/triplea/issues/1025
