### ISSUE TITLE
To Docker or Not To Docker

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#7140]
Opening an issue to discuss docker containers.

@tvleavitt said in: https://github.com/triplea-game/triplea/pull/7126

@DanVanAtta O.K. First off, to be transparent, I'm mostly speaking from theoretical knowledge here rather than practical experience (colored by extensive discussions about Facebook's architecture with an SRE there that I know), cross-checked via Google searches to make sure I'm not talking out of my ass. Also, the sum of my knowledge about your deployment architecture is what I've read on threads here. I don't have a solid sense of your knowledge, so I apologize if I'm repeating the obvious, but, as outlined in the link below, containers have a very specific benefit: "Code running inside a container behaves independently of the underlying system: the application is entirely separate from the infrastructure." I see this as a significant win.

https://www.padok.fr/en/blog/container-docker-oci

Here's a how-to for deploying containers with Ansible, since that's the automation tool I see in use:

https://www.techrepublic.com/article/how-to-deploy-a-container-with-ansible/

I think using containers might be worth considering, for the reason mentioned, and using docker "swarm mode" might even be more resource-efficient and perhaps even cut costs by letting you run fewer nodes; I don't have an idea of what your resource usage looks like right now. I presume there's a dashboard somewhere in Linode or whatever that tells you. Probably not the most significant of issues.

Note: it sounds like each node is "monolithic" in that all the services deployed are duplicated on each host. Again, speaking entirely theoretically, it might be of benefit to look at how they could be disaggregated and put in separate containers while still being run on one host (as outlined here), and then further down the line, examined for how they could be consolidated and deployed across multiple hosts. Again, less of a priority.

https://www.techcrumble.net/2019/12/how-to-run-multiple-containers-with-docker-compose/

_Originally posted by @tvleavitt in https://github.com/triplea-game/triplea/pull/7126#issuecomment-657292020_

**Comment by DanVanAtta** [comment]
Re: resource usage, this HTOP perhaps tells the story :grin: 

![Screenshot from 2020-07-12 17-34-03](https://user-images.githubusercontent.com/12397753/87260334-326e0200-c466-11ea-92bf-25ec3d5ff0aa.png)

**Comment by prastle** [comment]
Granted i always realized that "plopping" a server did not auto deploy...  @DanVanAtta   I guess I just expected it to auto pick up the most recent stable.  You have fixed that I believe.  I guess in the future we need to add to the infra code before we deploy thus basically takes a day.  I was simply asking for a few spare numbers to be added (for rare cases and weekends when more bots are needed) which as you already explained will cause a failed deployment.

**Comment by DanVanAtta** [comment]
Re: server re-use, from the these two comments:

- https://github.com/triplea-game/triplea/pull/7126#issuecomment-657263619
- https://github.com/triplea-game/triplea/pull/7126#issuecomment-657265109


Essentially what @prastle had done was to re-use the same server name we have defined in ansible inventory. By swapping the physical linode, and updating the DNS entry for that hostname, the inventory entry then became valid again and he simply needed to wait for the next merge whereby travis then executed a production deployment that used those inventory entries. So in effect @prastle was swapping servers.

@tvleavitt  we deploy multiple bot instances to each server, each instance becomes a 'service' that can be controlled via 'systemctl'. The big difference whether we had a docker container or not is what that 'systemctl' service would control. With a docker container it would be a docker start, without one we are invoking a start script that does a 'java -jar' command. 

We've had some discussions before about whether to use docker or not. The reason to use it was not necessarily compelling. It's a bare-metal vs container trade-off. For development, having postgres be in a docker container has been really valuable. I think the development use-case for things like that, or an nginx, is quite compelling.

When it comes to deployment to prod, it's something of a question of where do you want your configuration? Do you want to configure most everything in a Dockerfile and then deploy that container, or do you want to encode that configuration via ansible commands? For the most part, for now, we have chosen the latter.

Then again, the ansible deployment is somewhat new and I don't think we had it full-fledged until 2.0.

**Comment by DanVanAtta** [comment]
This is one issue where we discussed container before:
-  https://github.com/triplea-game/triplea/issues/4715

There was another good one where we discussed this directly but I'm not finding the link.
