### ISSUE TITLE
Dice Rolling

### ISSUE THREAD

**Issue by gregorytisone** [triplea-game/triplea#7159]
The dice rolling mechanics are way off.  For example, I had 5 Battleships (hits on 1, 2, 3, and 4) and 14 Fighters (hit on 1, 2, and 3) and only got 5 hits in an attack.  I tried the attack several times and only could get 5 hits.  That's way off and makes it feel like the game is cheating.  I even did the Battle Calculator and had an 85% percent chance of winning.

This is not the first time this has happened.  This just really made me angry.  I know you will get unlucky sometimes, but the rolling can be absurd.

**Comment by beelee1** [comment]
Do you have a saved game where it did it ? I know it seems off at times, especially when rerolling and getting the same result, but I believe the roller works correctly.

**Comment by gregorytisone** [comment]
I do have a saved game.  

Additionally, I thoroughly appreciate the fast response.  If you believe the roller is working properly, hat is good for me. 
 
Thank yuh very much for taking the time and for your response,

Gregory Tisone

**Comment by RoiEXLab** [comment]
@gregorytisone Any chance you are playing with Low-Luck?

**Comment by gregorytisone** [comment]
Thank you very much for the suggestion.  I do believe I have low luck
enabled.

I sincerely appreciate your help with this.  This is my favorite game and
your assistance has made the game play even more enjoyable.

Thanks again,

Gregory
