### ISSUE TITLE
Cannot authenticate for user "lobby_user", when running run_flyway script

### ISSUE THREAD

**Issue by dummyacc-prog** [triplea-game/triplea#7180]
Following the information on this page: https://github.com/triplea-game/triplea/wiki/Local-Build-and-Testing

I'm running the commands one by one, and getting authentication error when running **run_flyway.sh** script.
Docker is running on Docker quickstart and I can see the **postgres** image as well as the **triplea/lobby-db** one.

Any idea how/where to add the correct credentials, or what are they ? Do I need to modify the setup-database script ?

![Capture](https://user-images.githubusercontent.com/68329772/87631851-e01c3200-c740-11ea-92c8-62d2b697a3a9.PNG)

**Comment by tjrbrom** [comment]
Go to **pg_hba.conf** (I assume you got postgres installed), and change METHOD from md5 to trust, for ipv4 and 6.

Then run `pg_ctl reload` and try again.

**Comment by DanVanAtta** [comment]
Feel free to submit a PR with in any corrections/fixes so that this is more "out of the box". The setup of a local database and the dev environment is ideally easy for everyone.

Please re-open if there are further issues here.
