### ISSUE TITLE
Negative PU Number (-9953) on Greyhawk Wars 1.1.0

### ISSUE THREAD

**Issue by fernandodiacenco** [triplea-game/triplea#7186]
Hello,

When using the new Triplea 2.1.20365 on Greyhawk Wars 1.1.0, something odd happened

From turn 11 to 12 my nation (Pomarj) got negative PUs (-9953)

I've attached the save files from before and after

I'm using Debian 10 with OpenJDK 11

Never encountered this error on Triplea 1.9

### How can the problem be recreated?
Load save file "before-bug" as Pomarj and end turn

### Do you have any ideas for an expected fix?
Hmm no, but i'm pretty sure it has something to do with lines and... code and... variables, and most certainly bananas

### Attach a Save Game
Here
[bugs.zip](https://github.com/triplea-game/triplea/files/4933867/bugs.zip)

### If playing a prerelease, which version are you using?
Leaving blank

### If playing a prerelease, does this happen on the latest release?
Leaving blank

### Is there anything else we should know?
I think you guys are great and thank you for your time.

**Comment by asvitkine** [comment]
TripleA 2.1 is ancient at this point, so I'll close this out. Hopefully fixed since then.
