### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#72]
We have a Travis CI file in our build. It works and has been building in my local repo: https://travis-ci.org/DanVanAtta/triplea, I'm already at build 41.

*All* we need to do for Travis CI to build triplea-game is to grant it access and then click a button on the travis CI web UI to turn builds on. So this all a simply a matter of clicking yes, all configuration is done and already pushed into master.

@veqryn  and @ron-murhammer , could you please find the email and grant access (should be dated Aug 7th)? 

After we get Travis CI permissions, and turning build son,  any branch with the .travis.yml file will automatically be built (compiled and tests run). Later Travis CI can be updated to do more, like create and push releases when we want it to.

**Comment by ron-murhammer** [comment]
Approved.
