### ISSUE TITLE
Broken Automated Hosts (2.1.20613)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#7205]
A few minutes ago I tried to join Bot703_Jersey and I was unable to, receiving the message "Could not join game: Game is launching, try again soon".

A few minutes ago I tried to join Bot802_London and I was unable to, receiving the message "Could not join game: Game is launching, try again soon".

Then, I tried to join Bot703_Jersey for a second time and, this time, I was able to join it, but the game appeared in a "waiting for players" status, but with every player taken by one of ColRegularPop and Von_Kuulness (a condition that I believe should last only for a few seconds, before the game is launched automatically), while no user but me was in the host.

I operated a "Boot Game" on Bot703_Jersey, but it came back immediately, still broken the same way. I'm leaving it be in case this may be useful for any developer to indagate the problem.

Then, I tried to join Bot802_London for a second time and, again, I wasn't able to.

I operated a "Shutdown" on Bot802_London and it came back after a few seconds, apparently without problems.

>Lobby chatlog:
(00:03:07) Aposteles:  802
(00:03:28) tog3:  sure
(00:04:40) tog3:  boot nr?
Aposteles has left
Aposteles has joined
(00:05:23) Aposteles:  Tog 703?
(00:05:28) tog3:  ok
plonk has joined
(00:05:41) Aposteles:  could not join.. game is launching it says
plonk has left
(00:06:37) tog3:  yezs
(00:06:45) Aposteles:  Cernel? The Bot 703 and 802 should maybe be resett
(00:06:57) Aposteles:  not able to join or launch from them
(00:06:58) tog3:  something is wrong
(00:07:18) tog3:  603
(00:07:31) djfruda:  i guess is over rommel
spiral slapped Maraxus
(00:07:42) Aposteles:  You were slapped by Aposteles
djfruda slapped RommelsAsparagus
(00:07:45) RommelsAsparagus:  yes, becasue a) you have been killing me with dcei
(00:07:51) djfruda:  ehehehehe
(00:07:52) RommelsAsparagus:  and b) I made a big mistake there
(00:07:56) RommelsAsparagus:  so gg
(00:07:58) Cernel:  ok
(00:08:01) djfruda:  u play risky 
(00:08:03) RommelsAsparagus:  i got unluckly
(00:08:05) djfruda:  yep
(00:08:05) RommelsAsparagus:  no i dont
(00:08:25) djfruda:  3 against 2 in a decisive battle is risky for me
(00:08:28) Aposteles:  Tog? 603?
(00:08:29) RommelsAsparagus:  i got unlucky a lot in that game
(00:08:41) RommelsAsparagus:  hence whY i said I messed up
(00:08:49) djfruda:  yep
(00:08:53) RommelsAsparagus:  yup
hedin41 has left
(00:09:19) djfruda:  gg
(00:09:21) djfruda:  cya
(00:09:26) RommelsAsparagus:  farewell
djfruda has left
RommelsAsparagus has left
(00:11:43) Cernel:  I'm booting Bot702 from the lobby but fixing Bot802, thanks for reporting
RommelsAsparagus has joined
(00:12:30) Cernel:  sorry Bot702
(00:12:40) Cernel:  Bot703 not Bot702
(00:13:02) Cernel:  I'm not doing anything to Bot702, that was a typo
(00:13:26) Cernel:  I'm booting Bot703 from the lobby but fixing Bot802, thanks for reporting
troz slapped drock
RommelsAsparagus has left
(00:18:01) Cernel:  Hey ColRegularPop and Von_Kuulness: I saw you were using the automated host 703, when it broke down. It may be good if you report what you experienced (as an issue in the project's repository, not ...
(00:18:13) Cernel:  ... here or in forum).
(00:18:25) Cernel:  https://github.com/triplea-game/triplea/issues
nunu has left
dsc has left
(00:20:43) Cernel:  Looks like Bot703 reconnects immediately, I think I'm leaving it be.
djfruda has joined
troz slapped djfruda
(00:24:08) Cernel:  Bot802 should now work fine if anyone needs a bot

**Comment by Cernelius** [comment]
Automated hosts seem to be generally problematic.

>Lobby chatlog:
Aposteles has joined
(00:36:13) Aposteles:  603 again?
doctorxeron has joined
(00:38:08) Aposteles:  I think we must change the bot
(00:39:05) tog3:  ok
(00:39:07) tog3:  nr
(00:39:15) Aposteles:  trying to find one that works
MisterBigfoot has joined
(00:41:29) tog3:  603
andrewthree has left
Vlada has left
(00:44:03) Aposteles:  Cernel, could you reset bot 603?
(00:44:07) Aposteles:  You were slapped by Aposteles
(00:44:23) tog3:  903
Matt_Peterson has joined
(00:44:36) Cernel:  Yes, but a moment
(00:44:39) Aposteles:  I am in 904
(00:44:51) Aposteles:  thanks
(00:45:07) Cernel:  bot 603 works fine for me
(00:45:11) Cernel:  I just launched the game
(00:45:25) Cernel:  if you had any problems I can only suggest you report them
(00:45:52) Cernel:  looks like 1 user is sitting in there
(00:46:13) Cernel:  please be sure not to remain in not in progrees bots if you are not searching for a game

**Comment by Cernelius** [comment]
I shutdown Bot603_California to remove a user from it (according to the TripleA automated hosts rules, I should have booted the user from the bot, but this possibility has been removed upgrading to 2.0, so I did it by shutting the host down, instead), then the user (namely spiral) let me know that he believes not to have been in there, at the moment.

>Lobby chatlog:
(00:47:36) spiral:  Revised bot 802
KJR has left
(00:49:17) Cernel:  hey spiral, by rules you are not supposed to occupy multiple automated hosts, I'm removing you from Bot603 since you seem to be searching for in 802
(00:49:39) spiral:  I'nm not in 603
(00:49:50) Cernel:  ok then I guess that was a ghost of you
mattd3v has joined
(00:50:01) spiral:  when i leave bots for some reason it sometimes says i am still there
(00:50:06) spiral:  this started a few weeks ago
(00:50:09) Cernel:  In this case, I will report it as a problem
(00:50:09) spiral:  not sure what is going on
mattd3v has left
(00:50:31) spiral:  so when i go back it says spiral(1)
(00:50:38) Cernel:  It would be good if whenever you have a problem you report it in the project's repository
(00:50:48) spiral:  how do i do that?
(00:51:04) Cernel:  you need to register in GitHub, then open an issue in here:
(00:51:05) Cernel:  https://github.com/triplea-game/triplea/issues

**Comment by Cernelius** [comment]
Bot901_Frankfurt was just reported as having its game "crashed".

I joined the automated host and all appeared normal to me, like any regular World War II Revised games in progress. However, Edit Mode was enabled an the game was not being played.

Then the user to whom the turn player was assigned disconnected and the automated host went back waiting for players with the save-game autoreloaded. Again, still all apparently normal.

Then I assigned all players to myself and, as normal, the game started soon after, automatically.

The game was correctly reloaded at the point when the disconnection happened, Edit Mode being enabled (as I said). However, apparently, nothing gameplay related was actionable and it was also impossible to turn off edit mode. Here it is a screenshot:
![20200720_001](https://user-images.githubusercontent.com/19562310/87972913-0686f800-cac8-11ea-8193-13778fa8787b.png)

(the host chatlog was created previously, when I joined the host as an observer, and all looked normal to me (as I said))

Then I booted the game from the lobby, but it reconnected after about 1 second.

However, after waiting maybe around 1 minute (I don't know if this was in any way related to the fact that I booted the game, but I don't think so) the game went back fully playable, all appearing normal (I was able to place units and turn off edit mode). Here they are two screenshots:
![20200720_002](https://user-images.githubusercontent.com/19562310/87972934-0c7cd900-cac8-11ea-9a27-af86b2eab721.png)
![20200720_003](https://user-images.githubusercontent.com/19562310/87973113-54036500-cac8-11ea-953c-d3fed1fb28ad.png)

>Lobby chatlog:
(20:03:06) MasterBlaster:  game crashed spiral
MasterBlaster slapped spiral
(20:03:16) spiral:  ?
Matt_Peterson has joined
(20:03:37) MasterBlaster:  can u save that game?
(20:03:46) Cernel:  Games should never crash.
ColRegularPop has joined
(20:03:50) spiral:  i have save
straun has joined
(20:04:07) Cernel:  If they do, you are supposed to report the problem.
(20:04:07) MasterBlaster:  901 cernel
(20:04:09) spiral:  or at leastt it says game saved
straun slapped RommelsAsparagus
Hitman95 has joined
hans has joined
AdamF slapped Hitman95
(20:05:19) AdamF:  603
(20:05:25) Hitman95:  hey adam
(20:05:28) AdamF:  hi
corsair has left
(20:05:51) Hitman95:  cant now taking my turnis on axis and allies online on steam
(20:05:56) Hitman95:  need a cal
(20:05:58) AdamF:  k
(20:06:01) AdamF:  k
Von_Kuulness has joined
MasterBlaster has left
(20:06:21) spiral:  bot 904 mb
MasterBlaster has joined
(20:06:41) MasterBlaster:  back
Maraxus has joined
(20:06:52) spiral:  bot 904
(20:06:59) Cernel:  so the game looked normal to me, what did you experienced?
(20:07:09) MasterBlaster:  edit
(20:07:11) Cernel:  *experience
(20:07:20) Cernel:  yes you were in edit mode
(20:07:27) MasterBlaster:  i wanted to edit something
Leatherneckinlv1 has left
(20:08:12) Cernel:  I see
(20:08:17) hans:  now tried on 2 comps, and find that with 2.0.20234 I can link, but not with 2.1.20365
(20:08:41) Cernel:  the game is stuck in edit mode and nothing can be done, right?
(20:08:46) hans:  jave version on both comps the same: 11.0.6
colonelMustard_withtheRope has joined
(20:08:55) hans:  not even in edit mode
(20:09:03) MasterBlaster:  noq all fine
(20:09:08) MasterBlaster:  now
(20:09:18) MasterBlaster:  thx cernel
(20:09:27) hans:  it gets stuck in the 'playonline' 'start local game' ect screen
straun slapped RommelsAsparagus
(20:09:50) MasterBlaster:  hi hansi
(20:09:57) hans:  Hi MB
mpla has left
(20:10:59) MasterBlaster:  New Turbo Kid here :)
corsair has joined
(20:11:35) Cernel:  I try to boot the 901 bot but probably it will come back
Maraxus slapped ToughOmbre2
(20:11:58) Maraxus:  bots acting funny
(20:12:07) ToughOmbre2:  pick another
(20:12:08) hans:  so not just me?
(20:12:21) MasterBlaster:  :)
(20:12:34) hans:  Don't be funny MB ;-)
(20:12:45) Maraxus:  604
(20:13:12) MasterBlaster:  best dutch export ever ..New Kidz Turbo
hans has left
Wassmuss has left
jan_ has left
dsc slapped tomasdmo2
(20:21:00) dsc:  grab a save
(20:21:04) dsc:  i need to rejoin
(20:21:10) dsc:  game gave up on me
dsc slapped tomasdmo2
(20:21:43) tomasdmo2:  ok
(20:21:55) dsc:  tell me when ready
(20:22:27) tomasdmo2:  rdy
(20:22:45) dsc:  704
(20:22:46) tomasdmo2:  704
Nasterly has joined
colonelMustard_withtheRope has left
MadFritzy has joined
alessandro has left
Mezten has joined
seancb has joined
seancb has left
(20:32:07) corsair:  run it back vlada?
sailingcondor has left
Cernel slapped MasterBlaster
(20:35:11) Cernel:  hey MasterBlaster a questior regarding the crash you experienced in 901
(20:35:24) MasterBlaster:  ok
(20:35:36) Cernel:  Did you noticed whether or not someone joined the host shortly before or at the same moment as it happened.
(20:35:46) Cernel:  *did you notice
Blondie has joined
(20:36:00) MasterBlaster:  no there was nobody
(20:36:09) Cernel:  ok, thanks was just wondering
(20:36:19) Cernel:  as the game didn't actually crash, by the way
(20:36:29) Cernel:  apparently, it just froze for some minutes

I didn't operate any shutdown on the host, in case this may be detrimental to inspecting it.

The crashed apparently happened about half a hour before the creation of this issue.

**Comment by DanVanAtta** [comment]
@Cernelius / anyone, have we had any recent reports of this problem?

Side-note, long conversation threads are useful, but perhaps better to post to a gist first and then give a link to the gist (to keep the issue/discussion here cleaner - https://gist.github.com)

**Comment by DanVanAtta** [comment]
Yup, this is certainly still happening, marking this as 'urgent'.

**Comment by DanVanAtta** [comment]
I think the OP is on-topic, the latter posts from @Cernelius here look like they are probably different problems. (The bots could use work... they are not terribly stable in general. 2.x did not change much in the bots so we are largely dealing with structural/legacy problems).

**Comment by prastle** [comment]
Yup a 2 year problem..,. Edit mode is also involved

**Comment by DanVanAtta** [comment]
The "game is already in progress" seems new

**Comment by Cernelius** [comment]
I don't know. We have seen all kind of weird different bad behaviours with the bots over the years happening all the time, just we never reported anything, or almost so. Bots were mostly fixed by making them crash by booting an active user in them, which worked most of the times.

Myself, since I'm not a bot user, I always had the opinion that the bot users should have made the reports, except that nobody ever reported anything, or almost so. Also these issues should have reported by the users initially experiencing them, I think (just saying, no problem here).

I feel cannot make a call upon what is a regression and what not.

**Comment by DanVanAtta** [comment]
A code fix for the "game is already in progress" problem is up: https://github.com/triplea-game/triplea/pull/7262
