### ISSUE TITLE
Pre releases can't post to axisandallies.org

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#7250]
### How can the problem be recreated?
Start play by forum game. Get to end of turn. Attempt to post. Sits there for several minutes then stops with a blank message. Manual posting also doesn't work.

Problem is observable in 2.1.20625 and 2.1.20696. Works properly in 2.1.20365

Presumably triple-game.org is also affected.

**Comment by panther2** [comment]
The last posting I tried was with 2.1.20613 - no issues with that version.

**Comment by panther2** [comment]
@simon33-2 
I have just successfully tested the 2.1.20696 version on both forums.
No issues at all.

Maybe it was something temporary that occurred to you?

**Comment by simon33-2** [comment]
Just tested again in 20696, still running a few minutes later.

Also didn't work in 20625.

Perhaps not a global problem? Are you sure 20696 is ok?

**Comment by simon33-2** [comment]
Now an error:
![Screenshot from 2020-07-27 07-12-40](https://user-images.githubusercontent.com/20733860/88489623-a0730700-cfd8-11ea-8468-df51b2b6121c.png)

Second message is blank.

**Comment by panther2** [comment]
@simon33-2 
>Are you sure 20696 is ok?

Yes, I have just tested again. Look here:
https://www.axisandallies.org/forums/post/1421980

**Comment by simon33-2** [comment]
Seems to be working with build 20723.

**Comment by simon33-2** [comment]
Actually, I may have tested on the wrong version. It seems that this is not a problem on Windows. However, it does appear to be a problem on Linux - Ubuntu 18.04 32 & 64 bit.

**Comment by Cernelius** [comment]
Why is the "Report a Problem" form not suggesting telling which system is being used, right in the opening post?

**Comment by DanVanAtta** [comment]
> Why is the "Report a Problem" form not suggesting telling which system is being used, right in the opening post?

The complaints about needing to sign up to github and the reported "hoops" to report a problems, we've limited the information we gather to a near bare-minimum to make it as easy as possible.

**Comment by DanVanAtta** [comment]
It's odd this would be an OS specific problem.. @simon33-2 you're able to test on both a Mac and Linux system and only find the problem on one? Do I understand that correctly?

**Comment by simon33-2** [comment]
I haven't tried on a Mac. I do have a Mac though. I'll give it a go.

**Comment by simon33-2** [comment]
Perhaps my mac is too old (10.7, Lion). Doesn't seem like Triplea 2.1 will install on it. Yes, I have set software is installable from any source.

**Comment by simon33-2** [comment]
Perhaps this isn't that strange. I've noticed that the pre releases add support for an extra factor authentication scheme. Does this scheme work properly on Linux?

**Comment by panther2** [comment]
> Perhaps this isn't that strange. I've noticed that the pre releases add support for an extra factor authentication scheme. Does this scheme work properly on Linux?

Are there OS reltaed dependencies regarding the support for 2FA OS, @RoiEXLab ?

**Comment by RoiEXLab** [comment]
There shouldn't be any. The only problem I can imagine is that the auth token isn't stored properly but "Connection timeout" clearly seems to indicate someting else

**Comment by simon33-2** [comment]
Let me know if I can assist in any way.

**Comment by DanVanAtta** [comment]
If the auth token were stored improperly other parts of the game would be broken. The OS consideration I believe is a red herring.

For those that have either seen this working or not, can we please clarify:
- is this a problem with the latest release?
- is this a problem with the latest pre-release?

**Comment by simon33-2** [comment]
Update: It works perfectly using the Windows version on Ubuntu via Wine.

**Comment by simon33-2** [comment]
No change in the new release - 2.2.20790

**Comment by DanVanAtta** [comment]
@simon33-2 , @panther2 , would you mind summarizing where/when you have found this to work and when not?

**Comment by simon33-2** [comment]
I'm not aware of any change in the state here. Just tested posting with 2.2.20868 on Ubuntu 64 bit with Java:
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

Still doesn't work.

However, it does work using the Windows version via Wine.

**Comment by simon33-2** [comment]
This seems to be working in 2.5.22294!

**Comment by DanVanAtta** [comment]
Does anyone know if this is still a problem?

**Comment by simon33-2** [comment]
On 222594? Yes. Although it does have a relatively simple workaround which actually works better for me in other ways - like the way the wine version can auto launch from Firefox which doesn't work as seamlessly with the native Ubuntu version. Also resources might be slightly more economical on the wine version.

**Comment by DanVanAtta** [comment]
What's the work around?

**Comment by simon33-2** [comment]
I explained that.

Use the Windows version on Linux via the wine Windows compatibility layer. Oh maybe you aren't familiar with wine?

**Comment by DanVanAtta** [comment]
Not completely, but makes sense, thanks @simon33-2

**Comment by simon33-2** [comment]
Hmmm, somehow, something went wrong with wine, possibly a wine upgrade?

Anyway, it seems that this has all of a sudden started working on Linux. Oh, I see something different. The Java version has gone to 11.0.6. But "java -version" still shows "1.8.0_201"

Anyway, will leave this open for a few days in case anyone has something to comment on it but am happy to close it. Seems that it is not a universal problem, although it isn't completely clear on what causes the problem.

**Comment by beelee1** [comment]
@simon33-2 cool it's working. Dan be back Aug 10 just so u know
