### ISSUE TITLE
"Big World : 1942 v3 Rules" Naval Bombardment casualties do not return fire (2.1.20688)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#7278]
Load the save-game and look at Americans round 3 "Battle in Azores". Otherwise, start a game and have a battle in which one or more casualties are from naval bombardment.

The problem is that the defending units killed by naval bombardment didn't return fire.

The correct behaviour is that naval bombard casualties should always return fire.

Save Game:
[02.zip](https://github.com/triplea-game/triplea/files/4998118/02.zip)

I'm using TripleA 2.1.20688, but someone else was hosting the game in the lobby (I don't know which version of TripleA it was using).

Game Version: 3.8.0 (even though it is incorrectly given as "Map Version" in the starting screen after loading the save-game (this map has multiple games (the original "Big World : 1942" and one modification of it))).

---
I'm assuming, and I'm as certain as I can be about it, that whatever game ending in "v3 Rules" is supposed fully to follow the "v3" rules set, no matter if it is a custom map of the basic games following such rules set. Therefore, I believe that this is a wrong behaviour, also no matter if it always was the game's behaviour.

@veqryn Can you confirm the above? I'm asking you because I've no idea where else to look at if someone would argue that this is a custom game, so the current behaviour cannot be considered wrong (look at the following chatlog, for an example).

Lobby chatlog:
>(01:42:41) Cernel:  hey chasm or any bw v3 players
Cernel slapped chasmDiver
CustomSoldier has joined
(01:42:57) Cernel:  anyone ever noticed that naval bombard casualties aren't returning fire?
(01:42:57) chasmDiver:  hey
n0m3 has left
(01:43:09) Cernel:  is this happening since when?
(01:43:14) chasmDiver:  no they dont
(01:43:26) Cernel:  ... right and you know that in v3 rules they should right?
(01:43:26) chasmDiver:  they nver returned fire
(01:43:31) Cernel:  lol
(01:43:39) Cernel:  why did nobody report this bug?
(01:43:41) chasmDiver:  I think its a setting
(01:43:45) Cernel:  no way
(01:43:48) chasmDiver:  its a setting Cernel
(01:43:50) Cernel:  that game is called v3 rules
(01:43:55) Cernel:  no way it must be a bug
(01:44:07) Cernel:  that game is supposed to be v3 rules, they return fire in v3
(01:44:12) chasmDiver:  Ive always played the map that way
(01:44:18) Cernel:  there is not the options in the menu
(01:44:19) chasmDiver:  but its a settings
RommelsAsparagus has joined
(01:44:34) chasmDiver:  v3 means v3 subs and transports rule
(01:44:40) Cernel:  no it is not, there is not the setting in Map Options
(01:45:03) Cernel:  lol no v3 means v3 rules, that game should be fixed to make naval bombard return fire
(01:45:12) Cernel:  it's just a bug apparently everyone got used with
(01:45:14) Cernel:  used to
(01:46:21) Cernel:  so will v3 players be fine if BW v3 gets changed to have naval bombard casualties return fire?
Leatherneckinlv1 has left
(01:46:23) chasmDiver:  You are right it is a setting on bw balance of Power but not v3
(01:46:34) ice:  but cernel
(01:46:41) ice:  we are the noobs
(01:46:42) Darth_Vader:  just play a different game
MisterBigfoot has joined
(01:46:47) chasmDiver:  IoI
(01:46:57) Cernel:  well I think I should report this as a bug
(01:47:02) chasmDiver:  go to sleep before the chicken wake you up ice
(01:47:03) ice:  defenatly
(01:47:07) ice:  i will
(01:47:09) Cernel:  thus have the BW v3 game changed as to have return fire on naval bombard
(01:47:09) ice:  gnight
ice has left
MisterBigfoot has left
(01:47:52) Cernel:  if that happens, I'm just asking if any bw player here would be upset because he prefers no retrun fire on naval bombard
(01:48:40) chasmDiver:  they will all be
sbrodk1 has left
(01:48:59) chasmDiver:  Italy is crippled then
(01:49:52) Cernel:  well, nonetheless, I believe this is a wrong behaviour and I will open an issue to have BW v3 be changed to returning fire on naval bombard
(01:50:07) chasmDiver:  some will rage quit and never come back
(01:50:20) Cernel:  despite the fact that I don't actually intend to play the game
(01:50:27) prastle:  Snorts
(01:50:55) prastle:  OH look ships firing at sea don't use your artillery at them ...
(01:51:05) prastle:  feel free cer
(01:51:11) Cernel:  I'm pretty sure BW v3 rules is meant to work exactly like WWIIv3 but on a bigger map
(01:51:11) prastle:  good catch
zuzab has joined
(01:51:18) prastle:  yup
(01:51:58) chasmDiver:  you are going to depopulat the bigworld community iif you do that
(01:52:08) Cernel:  I'll paste this discussion so the developers can ponder the matter a bit over it
(01:52:24) prastle:  np here
(01:52:57) chasmDiver:  ask champ... he has the most number of games on the map

**Comment by DanVanAtta** [comment]
Do we know if this is still a problem?

**Comment by Cernelius** [comment]
I've not played this game since then (of course, I can test it to verify it is still a problem, like anyone can do).

**Comment by DanVanAtta** [comment]
IF it's a missing property, then it's a missing property : )   (map fix)

**Comment by Cernelius** [comment]
> IF it's a missing property, then it's a missing property : ) (map fix)

Actually, it is a missing upgrade.

I've checked all items listed in the current
https://github.com/triplea-game/triplea/blob/master/docs/map-making/map-features-change-log.md
finding the following missing change (among other things):

`="Naval Bombard Casualties Return Fire Restricted"` >> `="Naval Bombard Casualties Return Fire"`

This is the pull request with the changes to address this issue:
https://github.com/triplea-maps/big_world/pull/7

Since the problem documented at the opening post may be fixed now, this issue should be closed when the referenced pull request is merged.

It is likely that variants of this game have this problem too. It may be good to mass-search all maps in the repository to see if any other present this same problem.

**Comment by Cernelius** [comment]
Off topic (this would be a new issue), there is also a property called "Occupied Territories" that I'm not aware has any purpose. If it is a deprecated or discontinued property, it should be renamed or removed, but I'm not aware of any documentation on the matter (otherwise I would have fixed this too).
https://github.com/triplea-maps/big_world/blob/bd78280d1be1ffb0bc57ba153b07ca617b109e36/map/games/Big_World_1942_v3rules.xml#L3620

By searching in
https://triplea-game.org/release_notes/
I found this:
>Deleting game option property “Occupied Territories” since it does not do anything anymore. (veqryn)

So, I assume this is an item missing in
https://github.com/triplea-game/triplea/blob/master/docs/map-making/map-features-change-log.md
.

The question would be whether this property has been just removed or substituted with something else (thus whether the fix would be only removing the property or removing the property and adding something else). This has to be documented officially (or at least I'm not aware of any such documentation), then someone may fix the matter on the map.

**Comment by CharlieAtlas** [comment]
> This is the pull request with the changes to address this issue:
> [triplea-maps/big_world#7](https://github.com/triplea-maps/big_world/pull/7)

So should this be closed then?
