### ISSUE TITLE
Gamenotes broken

### ISSUE THREAD

**Issue by ZjelcoP** [triplea-game/triplea#728]
Version:1.9.0.0.1732

Gamenotes show just the XML part. Edit: in any map.
![notes-bug](https://cloud.githubusercontent.com/assets/13902879/15456462/0ff11b24-2071-11e6-89e3-6dd028bd18b5.png)

**Comment by DanVanAtta** [comment]
https://github.com/triplea-game/triplea/pull/738 has a fix
