### ISSUE TITLE
About Menu - UI changes

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#729]
About menu has some problems:
1. It is hard to read, black text on dark background
2. The info in it seems redundant:
 - The tutorial and game manual give the game phases information
 - The help information presented seems out of place, perhaps better on website, or really left to the game manual and tutorial
 - The info about developers and where the game is hosted seems redundant. It's a quick search to find TripleA now. We could maybe use a community links section on this page, but again that would strike me as redundant to content we have on the website.
- We have an about menu/screen in the game as well

![about_menu](https://cloud.githubusercontent.com/assets/12397753/15456710/a79e7fe6-202d-11e6-9061-e476d64539a1.png)

My first reaction is to eliminate the main menu button. Otherwise we should clarify the goal, the problem that the window solves, and then update it to accomplish that goal.

**Comment by ron-murhammer** [comment]
@DanVanAtta Yeah really the only useful info here are the links as the rest is either displays outside of this or part of the tutorial. I'm fine with just removing it all together. We should probably have a 'website' button instead the sends folks to the main TripleA website where all the links/info exists and can much more easily be updated.

**Comment by DanVanAtta** [comment]
removing in: https://github.com/triplea-game/triplea/pull/750

**Comment by RoiEXLab** [comment]
This can be closed...
