### ISSUE TITLE
Revisiting Commit Comment Standards - standard prefix word?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#7299]
I'm thinking we may want a standard for commit comments where the comment is prefixed with a standard word. I'm thinking this set: {add, fix, update, cleanup, simplify}

A few data points have me thinking this:
(1) eslint is a model open source project and has such a thing: https://github.com/conventional-changelog-archived-repos/conventional-changelog-eslint/blob/master/convention.md, it seems to be useful and work well for them. The precedent is there that it can be done.
(2) We have a list of checkboxes for PRs that sometimes seem annoying. I feel like we should be able to know if something is a problem fixed based on the commit comment and title. If not, will the the commit commentary history be good enough for future maintainer to understand (arguably that is where it is most important and really counts)?  In addition, it's a bit odd when you preface a problem fix with a few cleanup changes. What if the first three commits are cleanups but then then last is a problem fix? It just seems kinda odd to have the option to select many checkboxes, to the point where it would just not be that helpful.
(3) Looking at most of the PR titles, we tend to prefix most with one of the standard keywords, most of them do have "fix", "update" or "add" as a prefix on them. Looking at that pattern, the ones that do not seem to certainly convey a little bit information than they could.

In sum, I propose we make the standard prefix word a convention, put it in with the developer documentation and remove the checkbox list in PRs. 

I don't think we need to go to the length of build enforcement:
1) might not be flexible enough, for example dependabot PRs could fail
2) might be a big barrier for new developers, requiring people to do an interactive rebase to reword commit comments could be a lot to ask
3) there are not that many developers and we should be starting people with a clean set of convention standards/documents, so it does not take long to learn the convention, see it in practice, and then do it. I don't think it's too much to socialize this practice.

**Comment by trevan** [comment]
What's the difference between "cleanup" and "simplify"?  I would think that simplify is a subset of cleanup so is that prefix just to be used when the cleanup is a small change?

And is "add" for new functionality?

**Comment by DanVanAtta** [comment]
That intended list is not necessarily meant to be exhaustive, certainly open to edits & additions.

In my mind simplify and cleanup are similar, only that cleanup is usually more purely removing or making consistent, and simplify is more altering. If they are used more or less interchangeably it would not bother me all that much.

'add' would be for more or less something new. 'Add null checks', or 'update method to check for null' could be I suppose interchanged. I don't think we need to necessarily be too strict about it.

**Comment by trevan** [comment]
> In my mind simplify and cleanup are similar, only that cleanup is usually more purely removing or making consistent, and simplify is more altering. If they are used more or less interchangeably it would not bother me all that much.

Interesting.  That is almost the opposite of how I see the two words.  "simplify" was simple changes to the code while "cleanup" was more intensive alterations to the code.
