### ISSUE TITLE
Enable Travis CI to start building (now that it has github access)

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#73]
#72 is not complete, I can't re-open it, hence the new issue..

Now that travis CI has access to github, you need to also tell Travis to start doing the builds: https://travis-ci.org/profile/triplea-game  (simply a matter of clicking the button towards the center of the page showing a big "X")

Note that my view of that page says admin is needed:

![need_auth_screenshot](https://cloud.githubusercontent.com/assets/12397753/9264792/5a5c6d6a-41df-11e5-859d-185782d4eb6b.png)

**Comment by veqryn** [comment]
Done, I think...

**Comment by DanVanAtta** [comment]
triplea-game is showing up in travis UI. It's likely waiting for the next branching/merge event. You can try pushing a test branch up to test it out. Hopefully it should build master on the next merge as well. 

(not closing issue just yet for some potential follow up discussion, no action items remain AFAIK)

**Comment by DanVanAtta** [comment]
Travis CI just built a branch submitted in a PR!   So... Behold!! Build number one:
![build_num1](https://cloud.githubusercontent.com/assets/12397753/9270275/3d17fcd8-4225-11e5-8b71-6d251eed0bfa.png)
(https://travis-ci.org/triplea-game/triplea/builds/75568288)

I'm curious if it'll build master after the merge.

**Comment by DanVanAtta** [comment]
Yes, Travis does build triplea-game master after merging into it (as well as branches submitted for PR). We're already at build number 5 now: https://travis-ci.org/triplea-game/triplea
