### ISSUE TITLE
Bot crashes

### ISSUE THREAD

**Issue by blinchik1aaa** [triplea-game/triplea#7339]
### How can the problem be recreated?
Not sure - bots while playing WAW map crash. Often have had battle calculator open when it happens, but don't think always. Hard to pinpoint the actual cause of it / correlate to anything specific 

### Do you have any ideas for an expected fix?
No

### Attach a Save Game
Will look to save one - have had no luck saving the crashes yet

**Comment by blinchik1aaa** [comment]
Just had another crash happen, this time hosted by a player (not bot)

The map was Big World BOP. Opponent started using battle calc at the beginning of his turn and the game crashed. 

Again - could not get a save

**Comment by blinchik1aaa** [comment]
One more add to this. Had bot crash on my end when using Battle Calculator and opponent was in "Edit mode".

Could not get a save as the bot was completely not responsive.

**Comment by DanVanAtta** [comment]
While this is a problem, ongoing and has been for some time, going forward the focus is more on bot deprecation and replacing them with a network bridge.
