### ISSUE TITLE
Install map window - always on top and closes when game loads

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#734]
Install map window needs to be go back to being truly independent - it's own JFrame.

- It's always on -top, which is annoying
- It closes when a game is launched, which is the really concerning thing.

**Comment by DanVanAtta** [comment]
@RoiEXLab  - could you take a look at this when you get a chance, please let me know your thoughts.

**Comment by RoiEXLab** [comment]
Ok reverting on that change then... Will still try to find a way to get the right icon displayed

**Comment by DanVanAtta** [comment]
Fixed, no longer always on top, and stays open on game launch
