### ISSUE TITLE
Move triplea_maps.yml to maps Project Repo?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#737]
I would like to suggest we move triplea_maps.yaml to the map project repo.

Each time we update triplea_maps.yaml, we trigger a whole new game engine build. It is unnecessary since the game will read the yaml file at runtime, the contents are not baked in with the game release.

Another benefit to moving, map makers are being asked to make forks of the project so they can update just this one file. The maps project repo is very small, so clones/forks are efficient.

Last benefit I would suggest, we would have a split in the commit history, the simple change log to the game engine will be much more on topic about what has changed in code, rather than detailing various map changes.

**Comment by ron-murhammer** [comment]
Agree, let's do it.

**Comment by DanVanAtta** [comment]
https://github.com/triplea-game/triplea/issues/737

**Comment by RoiEXLab** [comment]
Seems to Work, can be closed...
