### ISSUE TITLE
TWW will not load in a bot with the new stable!

### ISSUE THREAD

**Issue by prastle** [triplea-game/triplea#7382]
### How can the problem be recreated?

Join a bot and try to load TWW
### Do you have any ideas for an expected fix?
It should load.

Game Version: Newest stable
![broken tww](https://user-images.githubusercontent.com/17258293/90341113-da796c80-dfca-11ea-84c7-aa1083fd21ed.png)

**Comment by DanVanAtta** [comment]
@prastle could you check if you still see problem? I was not able to trigger it.

**Comment by DanVanAtta** [comment]
Please re-open or a cut a-new if we see this problem again, closing in the meantime.
