### ISSUE TITLE
Export game.xml creates flawed code

### ISSUE THREAD

**Issue by RogerCooper** [triplea-game/triplea#7480]
### How can the problem be recreated?

Use Export game.xml from the Export menu. When I run the file created I receive the error:
Could not find delegate 'games.strategy.triplea.delegate.battle.BattleDelegate'. This can be a map configuration problem, and would need to be fixed in the map XML. Or the map XML is using a feature from a newer game engine version, and you will need to install the latest TripleA for it to be enabled. Meanwhile, the functionality provided by this delegate will not available.

[operation-dandelion.zip](https://github.com/triplea-game/triplea/files/5145211/operation-dandelion.zip)

### If playing a prerelease, which version are you using?

Game Version:

### If playing a prerelease, does this happen on the latest release?

- [] yes
- [] no

**Comment by RogerCooper** [comment]
Here are some details:

"games.strategy.triplea.delegate.battle.BattleDelegate" is written instead of "games.strategy.triplea.delegate.BattleDelegate"

also

"occupiedTerrOf" instead of "originalOwner"

**Comment by DanVanAtta** [comment]
This should be fixed now with: https://github.com/triplea-game/triplea/pull/7687

**Comment by DanVanAtta** [comment]
Another recent PR updated the delegate search to only look at the last word of the delegate name. That would have the 'battle.BattleDelegate' vs 'BattleDelegate' case fixed.

**Comment by DanVanAtta** [comment]
@RogerCooper  please re-open if you see any issues with the new latest.
