### ISSUE TITLE
Pull Request Management

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#75]
So I think we need to have a little bit of a process around pull request reviewing and assignments. 

When you open a pull request please assign it to me. I'll then do an initial review and do 1 of 3 options:
1. Merge the pull request.
2. Add comments on what needs discussed/changed and assign it back to the requester.
3. Assign to Veqryn if I don't feel comfortable with the portion of the code base so he has it in his queue.

Veqryn tends to be the bottleneck since he knows the code base the best so we want to minimize using his time as much as possible which is the reason I'll do an initial review.

Then as they are discussed please assign it back and forth between the reviewer (Veqryn or myself) and requester so that its clear who needs to take action.

This should help to identify who currently needs to take action on the pull requests rather than just having a whole list of them.

I just went through all the pull requests following this process so its clear where things are at.

Thoughts?

**Comment by DanVanAtta** [comment]
Only admin can assign. Assumption could then be that unassigned => pending @ron-murhammer  review. Otherwise yeah, leave comments, pass it along, or merge it.

I the plan, it's a plan and low hanging fruit stuff doesn't sit around.

**Comment by ron-murhammer** [comment]
Oh well. Github drives me crazy with lack of fine grained permissions control! I guess just ignore the part about passing them back and forth. And yeah I'll take all unassigned ones.

**Comment by veqryn** [comment]
Sounds good to me.

**Comment by DanVanAtta** [comment]
@ron-murhammer , more to discuss, or good to close?

**Comment by DanVanAtta** [comment]
Why the re-open? What goal do we wish to achieve?

**Comment by ron-murhammer** [comment]
I will add an update to this actually. So if the PR relies on other PR's that haven't been merged then I'll leave it unassigned. I hadn't really considered this before but now that we have a good portion of PR's dependent on #103 I figured it would be good to point out.

**Comment by DanVanAtta** [comment]
We probably should discuss how to get more code reviewers. As is, Veqryn doing all code reviews, he is a bottleneck and I do not think has that much time or desire. Also, he has nobody to submit his code reviews to, which is a bit broken. 

Overall, we should probably look at a metric for PRs as well to gauge that we are doing something. Whether that be number of open PR, average age of PR, or something else, we should look at some of those numbers so we sure we in effect doing more than just paper pushing.

**Comment by DanVanAtta** [comment]
@ron-murhammer , I think a wiki with process would be good. Issues seem to be to be good places to discuss what that process should be. For the sake keeping our lists short, can we close this issue?
