### ISSUE TITLE
Moving Units is cancelled when "scrolling" with right-click

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#760]
Small "Issue"
When you are trying to move your unit out of the screen, and you don't want to use the edge scrolling feature, because it's too slow or whatever. And you are using the "move map by right click dragging feature" instead, your move is cancelled - because the right click event does that normally.

**Comment by DanVanAtta** [comment]
Any suggestions for how this can be fixed at @RoiEXLab ?

**Comment by RoiEXLab** [comment]
@DanVanAtta we need to check if the map was dragged and if so, we need to cancel the cancel event

**Comment by lensz** [comment]
I would also like to add, that movement is also canceled when I'm scrolling via [trackpoint](https://en.wikipedia.org/wiki/Pointing_stick).

Like this:
I press and hold the middle mouse button and now all my mouse movements are considered mouse wheel movements. 

Normal (via touchpad) mouse wheel scrolling does not cancel the movement. So I guess the problem is the mouse button click, just like in the right click drag scrolling scenario.

So someone is working on this, maybe exclude besides right click also middle click from the cancel-movement-list.

**Comment by RoiEXLab** [comment]
#1438 adresses this issue.
@lensz this should fix your issue as well... Please check that once the changes are merged using the then newest prerelease...

**Comment by lensz** [comment]
I just merged your pull request and right click scrolling works like a charm.

Middle mouse scrolling not so much, but there is a good chance, that this has nothing to do with your changes. 
More than often the middle click scrolling is interpreted as a normal left click even in the version before your changes.
I'll make some tests to give hopefully better feedback.


If further comments should better be posted in the pull request, let me know.

**Comment by lensz** [comment]
Okay, so it seems, that the middle mouse scrolling does not result in the `isMiddleMouseButton` variable to be true. Only a click without scrolling does that.

So in a kind of unpredictable way, while scrolling some inches, the selected units simply move to the current territory (via [case five](https://github.com/triplea-game/triplea/pull/1438/commits/db0f36c7c74f6a3932f7bab43c6d686d1a4ca541#diff-2f972e5d6c89799c13a8f096968999b7R759)).
Strangely scrolling down works in most cases, while scrolling up nearly always fails.

Really annoying stuff :dancing_women:

**Comment by ron-murhammer** [comment]
@lensz @RoiEXLab So seems that a portion of this issue is resolved with #1438 then. Do we want to merge that at this point or continue to work on it?

**Comment by RoiEXLab** [comment]
Well since I don't know exactly what is happening when using the "trackpoint" control @lensz talks about there's not much I can do since I have no way to test things like key codes etc.
I'd like to have the current PR merged and since I think @lensz Issur is slightly different I think a new issue should be opened an this one should be closed...

**Comment by RoiEXLab** [comment]
Also noticed an error when scrolling with pressed mousewheel. Triplea zooms in and out and the limiting seems to fail resulting in a null pointer - unrelated to my changes, opening an issue tomorrow (today in 16 hours)

**Comment by ron-murhammer** [comment]
@RoiEXLab Alright. I merged #1438. After you open a new issue summarizing remaining items then we can close this.

**Comment by RoiEXLab** [comment]
Opened #1443
