### ISSUE TITLE
package restructure

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#763]
Two tasks:
- Identify places where we name classes by name. We have several scripts, and locations in code even where we do that. Before we can really move stuff around, we need to make it a safe operation.
- Actually move into a new structure, a topic we should begin discussing
#759 gets a start on this by moving the map making tools to: `tools.*`

Also proposed in #759 is truncating to `triplea`

```
triplea.ai
triplea.common
triplea.engine
triplea.rules
triplea.tools
triplea.ui
```

**Comment by DanVanAtta** [comment]
I'm okay with rooting everything under `triplea`. I think command line contexts where we execute java against a full qualified class name, it could be useful there.

An alternative I was considering was no root package:
```
ai
common
engine
tools
ui
```

**Comment by frigoref** [comment]
I am also fine with restructuring, but I think we should put in more thoughts on what the different packages should contain, e.g., why having ui and common.ui.
Currently I'd suggest a clear MVC top-level structure we try to enforce:
model - data classes (e.g. Territory, UnitType)
view - everything related to UI and UI experience
control - everything related to process logic (e.g. battle logic)

**Comment by ron-murhammer** [comment]
@DanVanAtta Its usually better to have a somewhat unique root package in case anyone would ever want to use the code in other projects.

**Comment by RoiEXLab** [comment]
I'd appreciate those changes but I want to make my suggestion... I Like those 5 root packages but I think if there are no subpackages for those it will get pretty messy... So I'm suggesting having subpackages like ui.startup or similar in order to maintain a clean package

**Comment by ron-murhammer** [comment]
@RoiEXLab Yep, that's the plan. Also those 5-6 base packages are mostly just initial suggestions. Might be a few more.

**Comment by frigoref** [comment]
I fully agree to have subpackages and not just a few root or 2 level packages. It also seems logical to have a common root package triplea. Can we agree on those two things so far?
Furthermore, how about properly restructure the subpackages into the MVC packages?

**Comment by DanVanAtta** [comment]
I suggest this:

`triplea` for a top level.
Then group things by executable, or a set of related executables. Basically anything that can be launched as a stand-alone app. There are four that come to mind:
- client game `triplea.client`
- lobby server `triplea.server.lobby`
- dice rollers  `triplea.server.dice.roller`
-map tools  `triplea.map.*`


Most packages would be under `triplea.client`
Let's try to maximize cohesion, keeping related things together.
That means grouping by functionality. AI would be a good package. UI would not since it is too broad, and would scatter related entities around in the codebase. For example: `triplea.client.odds.calculator` would be a good root package, which might have a UI screen where the UI components would live. But the point is that we have something like:
- `triplea.client.odds.calculator.ui` 
- `triplea.client.odds.calculator.logic`

instead of:
- `triplea.client.ui.odds.calculator` 
- `triplea.client.logic.odds.calculator`

First step is to fix hardcoding of class names, we have a number remaining. Then move to the four broad categories above. Then I think we should see where we are, and which functionality can be grouped together, which we can do piece-meal.

**Comment by RoiEXLab** [comment]
@DanVanAtta I like your suggestion.

But the point is that we have something like:

>     `triplea.client.odds.calculator.ui`
>     `triplea.client.odds.calculator.logic`
> 
> instead of:
> 
>     `triplea.client.ui.odds.calculator`
>     `triplea.client.logic.odds.calculator`

That's exactly what I meant.

**Comment by DanVanAtta** [comment]
So latest suggestion, everything is rooted under `triplea`, then we would have the following packages:
```
client
lobby
dice.roller
tools.image
tools.map.making
tools.map.xml.creator
```

**Comment by RoiEXLab** [comment]
@DanVanAtta in order to not break savegames: should we perform these changes before 1.9?
