### ISSUE TITLE
Console error messages broken

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#764]
Does not appear that error messages have actually been making it to the console for some time.

1. Need to verify.
2. Fix problem.

There were some recent changes to log almost all stack traces to the ClientLogger, though it appears there was a problem before that update:
- https://github.com/triplea-game/triplea/blob/master/src/games/strategy/debug/ClientLogger.java

The way the console works is that we redirect std out and std err to it. When it is written to, it checks if the window is visible, and if the message is on Std out, it will show the window if it is hidden, while std error will simply print the message only if the window is open.

**Comment by RoiEXLab** [comment]
I don't know if this is related, but one thing I noticed, is that the stacktraces are incomplete/weird when not explicitly catching the exception

**Comment by DanVanAtta** [comment]
#790 fixes this.

@RoiEXLab   The stack traces being weird might have to do with how they are printed.
