### ISSUE TITLE
Prerelase 1.9.0.0.1950 install dir

### ISSUE THREAD

**Issue by FrostionAAA** [triplea-game/triplea#765]
When I install with the latest prerelase, 1.9.0.0.1950, then the default install dir is set to:
“C:\Program Files\triplea”, at least on my PC.

My old version of TripleA dir is names “TripleA”, and I would guess that it is named this because of the old installer settings.

Would it not be better to set new release to also use capital letters in the directory name? TripleA instead of triplea?

**Comment by DanVanAtta** [comment]
To complete this issue, a person would need to get a copy of install4j and run the tripleA install builder with the naming update. That should generate a build.install4j, that can be compared to the one checked in, and an appropriate update made: https://github.com/triplea-game/triplea/blob/master/build.install4j

**Comment by DanVanAtta** [comment]
Installer installs the game with a capitol T now, and the version number trailing, eg:
`TripleA_1.9.0.0.3432`
