### ISSUE TITLE
Map XML -> Game Code Bridge is Brittle, Cannot safely update code

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#767]
There is logic so that certain XML data will call specific functions. Often via reflection. For this issue, let's discuss ways we can solve this. We need to identify where this is happening, and fix it so we can easily know which methods are needed to support Map XMLs.

**Comment by RoiEXLab** [comment]
All old methods are deprecated and have a do not remove comment in the Javadoc...

**Comment by DanVanAtta** [comment]
Why are these methods "old", they should still be in active use. For example, the attachment XML will call modules in our code directly.

How do you know that they all have been identified?

**Comment by RoiEXLab** [comment]
Well they are deprecated and have something like "this is kept for backwards compatibility do not remove" in their documentation. 
Since we were moving all maps to gihub we could also try updating those maps

**Comment by DanVanAtta** [comment]
It does not seem like the problem is clear:
- Not all TripleA code is compile time checked. Specifically you can remove a method, have the code compile fine, and then it dies with "method not found" when you load specific maps.
- There is a mechanism to read map XML elements, and then invoke methods that have a matching name

The task here is to:
A) identify everything that *can* be called through XML names
B) create a mechanism where we would get a compile time error if were to remove any such methods.

**Comment by ron-murhammer** [comment]
@DanVanAtta Yeah I think this really boils down to removing the reflection used during parsing map XML. I don't think there is an easy way without addressing the major issue to resolve this.

**Comment by RoiEXLab** [comment]
Also, I think it would be useful to mark "map-used" methods with some sort of annotation for now...

**Comment by DanVanAtta** [comment]
#853 annotates the classes loaded by XML

**Comment by RoiEXLab** [comment]
I think the only easy option to get those compile-time checks is to not use Reflection, but a "read-execute" mechanism e.g. a switch statement, calling `CanalAttachment `when `games.strategy.triplea.attachments.CanalAttachment` is used inside the xml

**Comment by DanVanAtta** [comment]
I think a `switch` statement approach would be appropriate. After that type of update, we could move the various map support classes around without worrying about breaking maps

**Comment by DanVanAtta** [comment]
We've got annotations now, if anyone has any ideas for something better, please create a discussion issue. Otherwise this issue has hit a dead end for now.
