### ISSUE TITLE
Loaded Savegame: not displaying

### ISSUE THREAD

**Issue by tvleavitt** [triplea-game/triplea#7673]
### How can the problem be recreated?
Load a saved game.

### Do you have any ideas for an expected fix?
It should display the save game name in the left-hand navigation as with prior versions.

### Attach a Save Game
[2020-7-2-Twelve-Clans.zip](https://github.com/triplea-game/triplea/files/5228562/2020-7-2-Twelve-Clans.zip)

### If playing a prerelease, which version are you using?
2.3.21150

Game Version: ?

### If playing a prerelease, does this happen on the latest release?

- [] yes
- [x] no

**Comment by tvleavitt** [comment]
![triplea-lefhand-2 3 21550](https://user-images.githubusercontent.com/4445057/93272120-a8922c00-f769-11ea-8755-d48ea4fc68c4.png)

**Comment by DanVanAtta** [comment]
The missing game notes is fixed by: https://github.com/triplea-game/triplea/pull/7676 

The performance problem is fixed by: https://github.com/triplea-game/triplea/pull/7693

**Comment by tvleavitt** [comment]
Did you post the note above to the wrong issue? Those are not relevant to the very specific problem described here.

**Comment by DanVanAtta** [comment]
haha, I sure did.
