### ISSUE TITLE
source forge links not yet updated

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#769]
We've still a number of links to source forge, we really need to get these updated..

**Comment by DanVanAtta** [comment]
#768 address some of the critical / really out of date links. It's okay IMO if we still make use of source forge for documentation. There is no need I see to move all documentation over, right now.

**Comment by DanVanAtta** [comment]
We should though create new issues and track anything that is glaringly out of date, or that really needs to get migrated.  The PR #885 fixes some of the more critical out of date links.

**Comment by RoiEXLab** [comment]
@DanVanAtta BTW I changed the Website link in wikipedia: https://en.wikipedia.org/wiki/TripleA
