### ISSUE TITLE
Lobby Ban Rate

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#770]
We could use some logging on the lobby to know how often we reject logins due to ban. For example, are there so many people right now unable to play due to bad/overly broad banning that it is for example say worth clearing all bans. Alternatively, is it the case that banning is mostly working well? We need to enable a data flow that would allow us to answer that question.

**Comment by Cernelius** [comment]
My "Random Bans" Topic in the TripleAWarClub is closely related to this.
That topic is secreted in Admins/Bunker, thus accessible only by logged users belonging to the following Groups:
Webmasters,
Lobby/Forum Mods,
Senior Staff.

**Comment by DanVanAtta** [comment]
I had in mind a different topic @Cernelius . Here we would measure how often do banned users try to log in, how often are we blocking them?
