### ISSUE TITLE
Requiring that redistribution rights for maps in our offical repo be assigned to TripleA

### ISSUE THREAD

**Issue by tvleavitt** [triplea-game/triplea#7752]
We should require that map makers whose works are distributed through our repository to assign us certain rights (such  as an unlimited right to re-distribute, etc.), if they adopt a license that otherwise impose limitations on the right to redistribute their content.

Of course, this is complicated by the fact that there is no "us", officially, and thus no entity to assign rights to... although maybe that's not specifically required? I think only an intellectual property lawyer specializing in FLOSS could answer. That same lawyer could likely tell us exactly what rights we do need to request.

**Comment by DanVanAtta** [comment]
If maps were GPLv3, that should work?

**Comment by tvleavitt** [comment]
I don't know. My issue with using the GPL in the context of this is that we're dealing with content, and not code (at least in my opinion) and that the proper licenses are CC based. CC based licenses also cover a wide variety of scenarios.

Also, requiring GPLv3 means that a map creator can't retain copyright to original art and music while distributing a map through us (this could be either an actual copyrighted work for which we are given a specific license to distribute using a non-CC license or one of the more restrictive CC licenses, such as CC BY-NC-ND). Which you may or may not see as important. I, personally, don't have a problem with people making maps available that can't be modified or contain copyrighted artwork that can't be reused, though of course I prefer them to be licensed otherwise for obvious reasons.

Right now, for instance, an author could make a explicitly non-GPL map and put their own license in it, but grant us permission to distribute, that's up to them. I want to avoid the problem of a pissed offmap maker NOT explicitly granting us permission, then demanding we take down a map and all derivatives by claiming copyright to the items in question.

**Comment by DanVanAtta** [comment]
CC is a no.
CC BY-NC-ND could be problematic for the "non-derivative" part.

My plan is going forward maps will become distributed entities and that the artwork, map and XML will all become independent entities.* I wouldn't want to keep track of which artwork is allowed to be modified and which must remain with which map. From a map maker perspective, it's basically assumed you can take any map and modify it. I would like to continue that tradition. My thinking is then we really do want a GPLv3, that if a map is granted to TripleA, then it is granted to the broader community.


* To explain by distributed entities, my thinking is that we'll have a unit artwork pallette and all units artworks will have an ID. That artwork would then be referenced by ID in the XML. Thus, the XML would be an independent element and would reference all dependencies, such as map tiles and units by their IDs. You could then in theory upload units that are completely unused and simply made available. I believe this will add a lot of optimizations and can make map-making and contributions more collaborative.
