### ISSUE TITLE
Content that may be rights impaired exists in our map repo

### ISSUE THREAD

**Issue by tvleavitt** [triplea-game/triplea#7753]
Our map repo has content, some of it fairly popular, that undoubtedly violates trademarks (the most obvious and simple case is map named "Atari"), and other content that possibly violates copyright (haven't reviewed every map).

Right now, we're making a passive decision to accept any potential legal consequences for doing so (likely limited to removing the map from our repo on receipt of a demand letter): but who is "we"? Is "we" the admins of this project as defined in GitHub? I suspect a court might view that to be the case. Do our admins know what the legal and financial implications are? Am I, technically, by being made a admin of this project or team member, liable for this violation? While the most likely sequence of events is receipt of a "cease and desist" letter or a DMCA take down notice being issued to us or GitHub, the theoretical liabilities are rather significant (as outlined in the URL below): to wit, "Damages and lost profits that can be as much as $150,000 per infringement" (for copyright violations). A DMCA take down notice might well lead to GitHub taking the entire TripleA website offline until a resolution is reached.

https://www.upcounsel.com/trademark-infringement-penalties

To me, this makes implementing the suggestions outlined in #7021, which would, as stated, stop digging the hole deeper, urgent. If a map maker can't specify what the license for each element included is, we shouldn't distribute it through our repo.

While it may be unpopular with the user base, the safest policy here would be to summarily eject maps with this issue from the repo (unless it could be demonstrated that the presumptive issue does not exist because of some other reason), or alter them to remove the offending components; we or the creator could rename "Atari" to "Landing At Ari" for example, the graphically embedded title is probably defensible as being clearly unlike the existing Atari logo and thus credibly arguable as confusing. Other maps are not so easily fixable (those using trademarked names and referencing such in the notes). 

Other maps are arguably in violation of trademarks that would probably be difficult to enforce in this context, such as "Total Ancient War" or "Total World War" (e.g. "Creative Assembly, the Creative Assembly logo, Total War and the Total War logo are either registered trademarks or trademarks of The Creative Assembly Limited.") "Total" and "War" are such generic concepts that even closely related content that uses similar but not identical wording is probably not in violation. That said, caution would dictate renaming them given the hassle factor of mounting a defense and the limited effort required.

We could compensate for this by making adding "foreign repos" (the content of which is beyond our control) easier / more obvious in the UI.

**Comment by DanVanAtta** [comment]
Thank you for raising this @tvleavitt  - I agree we should become proactive here.

For definitions,  admins are the org owners and possibly those with write permissions. 

Re: foreign repos - I don't support this, though I don't think we can nor should try to limit maps that someone can simply plop on their hard disk. We should keep in mind the active plan is to get maps out of the github repositories this quarter and move them into database.

I think this project is a really good one to proactively perform an audit and ensure compliance. When maps go to database, we have a question of what to do with the unowned maps (90%) of them and if we can slap them with a GPLv3 license. I believe any owned owns will be easier and most map makers will readily agree. Assuming we can get all maps to have an explicit license, would the next be to identify all maps with issues, make them unavailable, and then fix them?

**Comment by DanVanAtta** [comment]
This is a useful reference that I have found: https://www.americanbar.org/groups/intellectual_property_law/publications/landslide/2014-15/march-april/its_how_you_play_game_why_videogame_rules_are_not_expression_protected_copyright_law/

@tvleavitt can you explain why licensing would impact copyright? I'm wondering because if a map maker does not have a copyright, any license they provide would not be theirs to give, right? I'm not disputing that maps should have a license, just wondering how it's so directly related to copyright.

**Comment by tvleavitt** [comment]
Spent all day working. I'll read the article and then I'll provide more feedback over the weekend.
