### ISSUE TITLE
Should be able to select any combination of amphib or non-amphib units

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#7756]
For your information, at least for v3 and following rules sets, it is a wrong behaviour of TripleA to force assigning hits to sea borne units of the same type first: You should be always able to select the specific unit to take out, amongst the ones that can be targeted (of course, when two or more units are the same, it makes sense for TripleA to make you choose only the type and the number of that type, to simplify).

For example, if I attack a territory with 2 sea borne infantry units and 2 other infantry and take 2 hits, TripleA obliges me to take out the 2 sea borne infantry units. Instead, I should be offered these options:
- Take out the 2 sea borne units.
- Take out the 2 land borne units.
- Take out 1 sea borne unit and 1 land borne unit.

If you are wondering if there are cases in which you want to take out land borne units first, yes there are (even without accounting possible marine bonuses).

_Originally posted by @Cernelius in https://github.com/triplea-game/triplea/pull/7740#issuecomment-698148852_

**Comment by asvitkine** [comment]
I think this may be fixed already? Amphib units are shown separately with a special no-retreat icon now, I think.

**Comment by asvitkine** [comment]
I confirm the above is true. Closing.
