### ISSUE TITLE
Victory City count not updated when it changes hands by an event

### ISSUE THREAD

**Issue by RogerCooper** [triplea-game/triplea#7797]
### How can the problem be recreated?

Run the attached xml with all players AI. the problem will happen on turn when Britain enters the war.
### If playing a prerelease, which version are you using?

Game Version:

### If playing a prerelease, does this happen on the latest release?

- [] yes
- [] no

**Comment by DanVanAtta** [comment]
@RogerCooper looks like the XML mentioned did not get attached, could you please upload?

Also a few questions:
- which turn does Britain enter the war?
- which version of TripleA are you running? Latest release downloaded from triplea-game.org or latest prerelease from github.com/triplea-game/triplea?
- what is the victory count expected to be updated to?
- do you know if this feature used to work, and if so roughly when? Should we be looking at the code history to look for a possibly breaking change, or is this something that just never worked?

**Comment by Cernelius** [comment]
As far as I know, victory cities cannot have a count (only the value).

**Comment by RogerCooper** [comment]
Britain enters on turn 2 which should update the Allied victory city count to 1. Using version 20868.
I don't if this ever worked.


-----Original Message-----
