### ISSUE TITLE
player info is wrong

### ISSUE THREAD

**Issue by SilverBullet1234** [triplea-game/triplea#7804]
### How can the problem be recreated?
when looking at a players info, it showed he was in a bot (201), but there was no one in the bot.  and another player said he noticed that also. 

### If playing a prerelease, which version are you using?

Game Version:

### If playing a prerelease, does this happen on the latest release?

- [] yes
- [] no

**Comment by DanVanAtta** [comment]
Thanks for the bug report @SilverBullet1234 
No ETA on when this will be fixed, hopefully within the upcoming next two releases. We're releasing about every 6-8 weeks these days.

**Comment by Cernelius** [comment]
Isn't this substantially a duplicate of:
https://github.com/triplea-game/triplea/issues/6969

And, yes, it makes both features mostly useless.

**Comment by prastle** [comment]
Yup!
