### ISSUE TITLE
Leaving an unsaved game and then restarting the same map opens up to the unsaved spot (with errors)

### ISSUE THREAD

**Issue by trevan** [triplea-game/triplea#7839]
1. Open up pre-release TripleA of at least 2.3.21447
2. Select a map (I usually pick 1940 global but I've done other maps)
3. Start a local game
4. Do at least one step in the round (in 1940, that would be production). You just have to press Done.  You don't actually have to do anything
5. Leave the game
6. Restart the game by just pressing "Play".  Don't press "Select Map" or "Open Saved Game" as that will not trigger this issue.
7. The game will start from where you left.  You will also generally get a missing image error.

I was able to figure out that this was introduced by @DanVanAtta in 2.3.21447 which is the PR #7611.  I undid that one line change in the latest master and was able to fix this issue.

I looked into why the missing image errors and it is because there are some event listeners from the old game session that are still active.  When the game plays, it will trigger those event listeners and they'll try to render icons.  But their resource loader has closed and so they can't find any images and the error is thrown.

**Comment by DanVanAtta** [comment]
#7913 shoudl fix this @trevan ?
