### ISSUE TITLE
I'am ready to add my map

### ISSUE THREAD

**Issue by Navalland2** [triplea-game/triplea#7850]
I have a medium sized WWII map that ready to be shared. Please send me an invitation to join my own map team at triplea-maps

**Comment by DanVanAtta** [comment]
Did you lose access to: https://github.com/Navalland?

**Comment by Navalland2** [comment]
I had to cancel my old mail address thus failed to get the previous one.

**Comment by DanVanAtta** [comment]
team invite sent @Navalland2

**Comment by DanVanAtta** [comment]
@Navalland2  to edit the triplea_maps.yaml file, anyone can do so:
- Navigate to the file: https://github.com/triplea-game/triplea/blob/master/triplea_maps.yaml
- click the pencil icon
- click 'create pull request'
- github will guide you through creating a fork and a new branch, it should win up creating a pull request.

Please use this issue if you have any troubles/questions, will be happy to assist.

**Comment by Navalland2** [comment]
I have created it in here https://github.com/triplea-game/triplea/pull/7890. I hope I did it correctly.

**Comment by Navalland2** [comment]
I have tried to replace the base tiles with the new ones but it exceeded the limit and I don't know how to get image with the extention of https://raw.githubusercontent.com 

Also still not sure about the correct way of creating pull request for permission of editing yaml files.

**Comment by beelee1** [comment]
yea Idk how to do the base tiles by click n drag. Might try a search for how to add with a terminal for windows I assume ? For the yaml scroll all the way to the bottom after your changes. Note that there are two scroll bars, so if you don't see it at the bottom of the maps, continue scrolling with the other one.

**Comment by Navalland2** [comment]
I can't do anything really without permission, I've tried all of them.

**Comment by beelee1** [comment]
So it looks as if you haven't added the map to the yaml yet ? Last one I see is the 1941 Balanced mod. Click on the pencil icon, scroll to the last map, click there and move down a couple lines and use the last game as an example. You have to be careful to do everything exactly the same. I struggle when I add a new one anyway.

But you obviously want to fix your base files first. What's the name of the repo ?

**Comment by Navalland2** [comment]
https://github.com/triplea-game/triplea/pull/7954 I hope it will work well. it is aggression_1941.

Base tiles work fine just I wanted to change sea colour to slighly lighter shade of blue.

**Comment by Navalland2** [comment]
Looks like there is something wrong in file structure. How can I solve the issue?

I had updated the XML but system still consider the oldest one, Is it because of the wrong file structure?
