### ISSUE TITLE
Weird Behaviour in 2.3.21903 Pre Release

### ISSUE THREAD

**Issue by beelee1** [triplea-game/triplea#7865]
### How can the problem be recreated?World War II Global 1940 2nd Edition

Sounds are on for game start but are muted after that. Also, I played Germany's turn then hit ctrlq/leave game. WW II Global was still selected as the map as usual and when I started another local game, not a save of where I just was, it took me to Russia's turn of the game I had just left and threw this error:

![Screenshot from 2020-10-09 00-32-04](https://user-images.githubusercontent.com/24382682/95548617-14fbf600-09cb-11eb-813c-ecf0be3ea217.png)

### Do you have any ideas for an expected fix?

Should work like the stable does

### Attach a Save Game

[weird behaviour in 2.3.21903.zip](https://github.com/triplea-game/triplea/files/5352808/weird.behaviour.in.2.3.21903.zip)

### If playing a prerelease, which version are you using?

2.3.21903

Game Version:

### If playing a prerelease, does this happen on the latest release?

- [] yes
- [] no

### Is there anything else we should know?

To clarify, I left the sound on. It just didn't work except for the startup music.

Edit
I'm on ubuntu 20.04 I know there were some sound issues with linux in the past.

**Comment by trevan** [comment]
I already opened https://github.com/triplea-game/triplea/issues/7839 on the issue of opening the game after closing it and getting that error.

So this issue should track the sound problem.

**Comment by beelee1** [comment]
@trevan Right on I'll close this

**Comment by trevan** [comment]
I think this issue should stay open but focus on the sound problem.
