### ISSUE TITLE
Sounds not playing or distorted

### ISSUE THREAD

**Issue by FrostionAAA** [triplea-game/triplea#7905]
Map sounds and their playback in the newest prereleases of tripleA seems to be bugged. (at least in v2.3.22024)
Sounds are either not played or they are played very distorted.
I think it can be recreated by just starting an all AI game of Dragon War (distorted) or Age of Tribes (no sound beyond intro sound)

**Comment by tvleavitt** [comment]
I noticed this the other day when starting a game... it settled down after a few minutes, but it was really really jittery on launch.

**Comment by beelee1** [comment]
I'm not sure if this is related #7865 but it had some sound issues as well.

**Comment by trevan** [comment]
Can one of you try and find which build started showing this issue?

**Comment by FrostionAAA** [comment]
@trevan I will when I have the time. Thanks.

**Comment by beelee1** [comment]
It doesn't do it in 2.2.20868 I'll check a few other others after a bit unless Frostion finds it first :)

**Comment by DanVanAtta** [comment]
I think this is likely to be fixed at same time as:  #7865 

It seems the 'resource loader' gets messed up, at which point resources like sounds are not found. It's the same problem for not being able to find images, the resource loader is the thing that gives the 'root file path' from where we find things like sounds and images.

**Comment by FrostionAAA** [comment]
I am not sure, but i think 2.3.21422 is the first version that distorts sounds.
And maybe 2.3.21385 is the last version that does not have distortions.
FInd them listed here: https://github.com/triplea-game/triplea/releases?after=2.3.21424
I hope the sound issue can be figured out :-)

**Comment by trevan** [comment]
The only PR in that range that would affect sound is #7602.  The message is "Fix: Disable audio if there is no audio device" so it would seem like that is a good possibility.

**Comment by trevan** [comment]
Yup, that change caused this.  I played Dragon Age with Hard AI on master with the change reverted and the sound worked fine.

**Comment by trevan** [comment]
@FrostionAAA thanks for finding the initial problematic build.  I've created a PR with a fix for this.
