### ISSUE TITLE
Problem Accessing Site

### ISSUE THREAD

**Issue by beelee1** [triplea-game/triplea#7921]
### How can the problem be recreated?
Logged in 02:30 CST US and got a hacked image.

![Screenshot from 2020-10-17 02-23-59](https://user-images.githubusercontent.com/24382682/96331595-2cb72800-1024-11eb-8e3c-991f084cab98.png)

curious if anyone else has. The chat seems to work, at least i sent a message anyway.

### If playing a prerelease, which version are you using?

Game Version:

### If playing a prerelease, does this happen on the latest release?

- [] yes
- [] no

### Is there anything else we should know?

Hadn't seen it before so thought I'd mention it. Idk if it's someone recently pissed off or capn crunch improved his computer skills, lol.

**Comment by panther2** [comment]
See #7920

**Comment by beelee1** [comment]
wow I can't believe I missed 7920 lol Should I go ahead and close this ? It's got the image, which actually looks kinda cool, but basically redundant. I'll leave it open for a bit. 

Actually I'll just close it
