### ISSUE TITLE
Release 2.3

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#7927]
I think we can draw a line where we are and publish the next release. Does anyone know of anything we *must* fix before publishing 2.3?

The items that were in the [2.3 project](https://github.com/triplea-game/triplea/projects/18) are not necessarily must-do and will probably land at the same time if we release now and launch 2.4 in a month or two.

If anyone/everyone could spend some time doing regression testing, it would be really timely!

**Comment by trevan** [comment]
I think https://github.com/triplea-game/triplea/issues/7839 needs to be fixed before 2.3.  It puts the game in a bad state and is really easy to encounter.

**Comment by trevan** [comment]
I think https://github.com/triplea-game/triplea/issues/7905 is a regression so that should probably be fixed before 2.3

**Comment by DanVanAtta** [comment]
I think/hope both of those should be fixed by the in-flight PR. I should have been more clear, I think once the current set of PRs are merged, then we are perhaps at a good place to draw the line for 2.3

**Comment by panther2** [comment]
@DanVanAtta 

> The items that were in the 2.3 project are not necessarily must-do and will probably land at the same time if we release now and launch 2.4 in a month or two.

Where are those listed? I can't find the list. I remember the "Internal Dice Roller" being one of the tasks...

**Comment by Cernelius** [comment]
By the way, there is still "Release 2.4" open in projects.
