### ISSUE TITLE
Error in XML for WW@v3 1941 Balanced Mod

### ISSUE THREAD

**Issue by Batman6794** [triplea-game/triplea#7965]
Russia's second objective (Southern Lend Lease) states that no axis ships must be in SZ34, but the XML has typo for the objective, setting it to SZ64 instead.

**Comment by beelee1** [comment]
@Batman6794 this is @JGreenLowe map. He should be aware of it now, hopefully :)
If not, I think he's over on https://www.axisandallies.org/

**Comment by JGreenLowe** [comment]
Thanks for catching that! The correct sea zone for that objective is SZ34 -- hopefully now both the game text and the XML reflect that. If there's anything else I need to do, just let me know.

**Comment by Batman6794** [comment]
You’re welcome! Thanks for making a fun mod! i’m very much enjoying it so far!
________________________________
