### ISSUE TITLE
TripleAwarclub.org domain expires on Nov 25/2020

### ISSUE THREAD

**Issue by prastle** [triplea-game/triplea#7972]
### If playing a prerelease, which version are you using?

Game Version:

### If playing a prerelease, does this happen on the latest release?

- [] yes
- [] no

### Is there anything else we should know?
Should I renew this again with GoDaddy?  I have been told in the past that this would be let expire.

**Comment by prastle** [comment]
Bump @RoiEXLab @DanVanAtta

**Comment by RoiEXLab** [comment]
I don't think there should be a problem when it expires, everything should be migrated now
