### ISSUE TITLE
[Discussion]How to handle current warnings

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#803]
When my Warning Resolving PR #802 is merged, there will be 63 Warnings left with 52 of them being auxiliary class warnings.
This means that non-public classes are called from outside their siurce files e.g. `RouteDescription` is a non-public class inside `MapPanel.java` and is accessed from `MapRouteDrawer.java`.
In my opinion those classes should get their own source File because of 2 Reasons, the first being to resolve the warning, the second to simplify the TripleA Codebase.
The class `DownloadFileDescription` is overriding `equals()` but not `hashCode()` could somebody fix that?
A lot of serializable classes have no `serialVersionUID`
There are some try-with-resource statements which define unused resources... Not sure what to do with them since I cannot see what they are supposed to to.
If you have better ideas on how to handle those warnings please let me know...

**Comment by DanVanAtta** [comment]
https://github.com/triplea-game/triplea/pull/808 Fixes the `DownloadFileDescription` missing hashcode function.

For the first item @RoiEXLab  - pulling classes out to their own source files is almost always a good thing, I'm in favor of that refactor.

The missing serialVersionUIDs need to be generated. Best yet though we use a library function that creates the swing components, or uses lambdas, that can avoid needing the serial version UID altogether. Simply adding them in would not be a bad thing as well..

> There are some try-with-resource statements which define unused resources... 

Could you cite some examples? It would help in answering the question

**Comment by RoiEXLab** [comment]
If you merge my cleanup PR, then you may take a look at `DownloadFile.java` line 71:
```
try (PerfTimer timer = Perf.startTimer("Download map: " + downloadDescription.getUrl())) {
  URL url = downloadDescription.newURL();
  try {
    DownloadUtils.downloadFile(url, fileToDownloadTo);
  } catch (Exception e) {
  ClientLogger.logError("Failed to download: " + url, e);
}
```

**Comment by RoiEXLab** [comment]
@DanVanAtta Thoughts?

**Comment by RoiEXLab** [comment]
@DanVanAtta can be closed, if you are answering my "try-with-resource" question
