### ISSUE TITLE
Problem Posting with Play by Forum 

### ISSUE THREAD

**Issue by Keine-Andeutung** [triplea-game/triplea#8032]
### How can the problem be recreated?
When Trying to Post with the Play by Forum option, there is no post instead there is an error saying : 'java.lang.IllegalStatException: Failed to upload savegame, server returned Error Code 500
Message: 
{"path":"/upload","error""[[error:uploads-are-dissabled]]"}

### Do you have any ideas for an expected fix?
Either Triplea is not uploading correctly or the tripleaforum isn't accepting uploads. either problem should be fixed

### Attach a Save Game
tried it with several savegames but didn't make a difference

### If playing a prerelease, which version are you using?

Game Version:

### If playing a prerelease, does this happen on the latest release?

- [] yes
- [] no

**Comment by DanVanAtta** [comment]
@Keine-Andeutung please give it another try, I tried adding adding a setting to allow file uploads. I'm not sure if it'll work, but worth trying again. please let us know how it goes or if you get the same error message.

**Comment by Keine-Andeutung** [comment]
Tried again and got the same error message.

**Comment by DanVanAtta** [comment]
I'm able to repo this with a test post.
I suspect this started happening after we upgraded nodebb version.
I tried just now to re-install the nodebb write plugin API to no avail:
```
sudo npm install nodebb-plugin-write-api
cd /opt/nodebb
sudo ./nodebb upgrade
sudo ./nodebb setup
sudo systemctl restart nodebb
```

@RoiEXLab could you have a look at this one?

**Comment by RoiEXLab** [comment]
I'll have a look at this tomorrow

**Comment by RoiEXLab** [comment]
https://github.com/NodeBB/nodebb-plugin-write-api/issues/134

**Comment by Keine-Andeutung** [comment]
Just tested it after the update. But it still throws the same error. Though the cange doesn't seem to do anything other than using a variable for the if-statement.

**Comment by RoiEXLab** [comment]
@Keine-Andeutung I haven't updated the plugin version on the forum until now.
So now you should be able to try again

**Comment by Keine-Andeutung** [comment]
Same error still. Although that's not surprising considering the change of NodeBB doesn't seem to change how the code works.

**Comment by RoiEXLab** [comment]
Just verified this myself.
Hmm I'll guess we have to wait then

**Comment by RoiEXLab** [comment]
See https://github.com/julianlam/nodebb-plugin-2factor/pull/52#issuecomment-726183382
