### ISSUE TITLE
Can't move pieces, e.g. land troops or ships, purchased by UK Pacific in Global 40 House Rules with Canada

### ISSUE THREAD

**Issue by Raybeat3000** [triplea-game/triplea#8054]
Java ver.: 11.0.6
Engine ver.: 2.4.22192
Map Name: Global 40 House Rules with Canada
Map ver.: 2.662.0

Hi.  I am unable to move ieces, e.g. land troops or ships purchased by UK Pacific in Global40.  The purchased pieces show up on the map but not in the "select  box" during combat or noncombat phases.  This is a new problem.  Things work fine in the prior version of Triple A (Engine ver. 2.2.20868).

Thanks, Raybeat3000

**Comment by DanVanAtta** [comment]
@Raybeat3000 , would you mind checking if you have this problem with the very latest? 

https://github.com/triplea-game/triplea/releases/tag/2.5.22265

**Comment by Raybeat3000** [comment]
Isn't 2.4.22192 the latest Triple A version for Windows?
By the way, the same problem occurs with Version 2.3.22161.  The last version that works correctly is Version 2.2.20868.

**Comment by DanVanAtta** [comment]
2.4.22192 is the latest release.

2.5.22265 is the latest pre-release (essentially a 'beta' version)

**Comment by Raybeat3000** [comment]
Sorry, I misunderstood.  I'm about to try the same game (same map, etc.) with the Beta Version 2.5.22265.  I'll report shortly.  Thanks.

**Comment by DanVanAtta** [comment]
No worries, it's slightly confusing, thank you for checking - with luck this problem is already fixed

**Comment by Raybeat3000** [comment]
Hi.  Previously reported problem does NOT occur in Version 2.5.22265.  Thanks.  
I'll use this pre-release and report any issues that I come across (hopefully none).  Thanks again.

**Comment by DanVanAtta** [comment]
Good to hear!
I suspect 2.5 will be released quite shortly so that others will pick up that fix an a few others.
Thanks for reporting the problem.
