### ISSUE TITLE
Extra Hard AI

### ISSUE THREAD

**Issue by shawnlg777** [triplea-game/triplea#8072]
I would love to see a feature that has extra hard AI in WWII Classic 3rd addition.

**Comment by CharlieAtlas** [comment]
I would give the AI an income bonus.  That is the easiest way to make it more difficult.

**Comment by DanVanAtta** [comment]
@shawnlg777 , we have created a forum category dedicated to discussing AI, perhaps this would be a good topic to bring up there? I suspect getting an 'extra hard' AI is largely a matter of determining where the AI is currently weak and where it can be improved.
