### ISSUE TITLE
where are all syntax for commands for game xml ???

### ISSUE THREAD

**Issue by sneakingcoward** [triplea-game/triplea#8109]
canNotTarget and canNotBeTargetedBy

where can we get the syntax for all commands ?
not in pos2 ??

**Comment by beelee1** [comment]
Not sure if this is what you want or not but Roger's site has a lot of info

https://axisandallies.fandom.com/wiki/Special:Search?query=game+property

There's also this

https://forums.triplea-game.org/topic/1178/game-xml-tips-examples/5

that might be helpful, but can't access the site right now. I'm not sure if canNotTarget has been updated for use with all units or not. Seems as if it was limited before.

**Comment by CharlieAtlas** [comment]
There is also this.  

http://www.starlords3k.com/XOB.html

**Comment by beelee1** [comment]
yea disregard my second link. I thought it was the one CharlieAtlas posted :)
