### ISSUE TITLE
Battle Calc reaches 10,000 rounds for any battle with Edit mode active

### ISSUE THREAD

**Issue by jimparker96313** [triplea-game/triplea#8111]
### How can the problem be recreated?
Conduct any battle calculation with edit mode active.

### Do you have any ideas for an expected fix?
Either change error to alert the user to exit Edit mode before running calculation, or make the battle calculator work normally in edit mode.  

### Attach a Save Game
Sample game is attached.  But occurred on even fresh games.
[triplea_35861_7rus.tsvg.gz](https://github.com/triplea-game/triplea/files/5504838/triplea_35861_7rus.tsvg.gz)

### If playing a prerelease, which version are you using?

Game Version:  2.5.22294

### If playing a prerelease, does this happen on the latest release?

- [] yes
- [] no

### Is there anything else we should know?
This is really a minor issue for playability.  It just tripped me up because I had forgotten I was in Edit mode, and the error message led me to believe something weird was happening with the battle.  I kept trying different combinations, and when 2 inf vs 1 inf yielded a stalemate, I finally realized what was happening.

**Comment by DanVanAtta** [comment]
Thanks for the error report @jimparker96313 . In 'edit' mode, combats do not take any casualties and the selections are all manual. I suspect that before we added the round limit that the calc would have kept going indefinitely.

I think the most feasible fix might be to disable the battle calculator in edit mode. The battle calculator and combats share the same behavior, if we make the battle calc work normally then so too would combats.

**Comment by jimparker96313** [comment]
Sounds like a good plan to me.

**Comment by jimparker96313** [comment]
This is merely a nice to have feature.  I understand what is happening, so I will close this issue.
