### ISSUE TITLE
Documentation:Typical Git Workflow

### ISSUE THREAD

**Issue by CharlieAtlas** [triplea-game/triplea#8135]
https://github.com/triplea-game/triplea/blob/master/docs/development/dev-process/typical-git-workflow.md

I think this could be more beginner friendly.  Being a beginner myself, I am starting to understand what it is saying now after working with IntelliJ-IDEA for a few weeks.  I think it would be good to have a version of this page showing how to do it in IntelliJ using the mouse and graphical inputs.  

Is that a useful thing?  Should I make a new page? Any other thoughts?

**Comment by DanVanAtta** [comment]
Sorry for the delayed response @CharlieAtlas . I think the best would be to find well written help pages that we can link to. This way we can save the work that someone already has done nor would we need to maintain that documentation.

**Comment by DanVanAtta** [comment]
I think in part we should also consider changing the page to more clearly state that we are defining the branching workflow. 

For example, some various different workflows are described in:
- https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow
- https://guides.github.com/introduction/flow/

Perhaps we should take the advice of using the links better and try to link to a description of the feature branch workflow. At the same time having sample commands I think is still kinda useful as that is more explicit and clear than any description we could ever write.

**Comment by CharlieAtlas** [comment]
Linking to other resources is always a time saver!  An issue I see is what if they don't stay up to date, or just disappear at some point?  It is good to know the primary purpose of the page though.  

The main thing i would want to do would be to show how to do it with screen captures, probably right below the equivalent command.  I know CLI is faster, and probably all around better, but at least for me it is easier to find things in the menu when I have a vague idea of what I am looking for than trying to remember the command.  The biggest hurdle I see is that there is more than one IDE in use, and there might be others in the future as well, which is kind of part of what you mentioned in the forum post that I made about the documentation in general.
