### ISSUE TITLE
set all allied factions to button setting allies to human regardless of setting

### ISSUE THREAD

**Issue by doctored** [triplea-game/triplea#8162]
### How can the problem be recreated?

self-explanatory, was working prior to 2.0

### Do you have any ideas for an expected fix?

no idea

### Attach a Save Game

N/A

### If playing a prerelease, which version are you using?

Game Version:

### If playing a prerelease, does this happen on the latest release?

- [] yes
- [] no

**Comment by DanVanAtta** [comment]
The behavior of the button changed in 2.0 and later to be "click to play". If you click the alliance button, then you will take the seat of each faction in that alliance. For example, if you join a multiplayer game, you can click 'axis' to play all of axis (with a single click).

**Comment by doctored** [comment]
thanks for clarifying i think that's definitely a bit confusing in terms of UX tho given its previous functionality especially when setting up a PBF/PBEM or local game. perhaps we can make the tooltip for those buttons a little more helpful like instead of saying set all to 'human' maybe it should be 'my control'

**Comment by DanVanAtta** [comment]
Funny enough the tooltip was buggy and before 2.0, IIRC, it always said 'set all to human' and so that never changed.

I think you're right that though the tooltip could be improved to something like "click to play".

**Comment by DanVanAtta** [comment]
Of interest, the tooltip is different in multiplayer games where it says for example: "click to play [allies]'

What are your thoughts to that @doctored , if we had the singe player game have the same text, would that make it easier?

**Comment by doctored** [comment]
yeah that's def more clear. :)
