### ISSUE TITLE
Game Freezes on AI Withdrawal v 2.5.22294

### ISSUE THREAD

**Issue by Cochise77** [triplea-game/triplea#8182]
Playing the Big World: 1942 v3 Rules map, I've encountered an issue where the game freezes on the battle window.  When it occurs, the AI appears to hang on the withdrawal decision.

TripleA version 2.5.22294 on Windows 10

**Comment by Cochise77** [comment]
Same behavior when the AI is faced with the submerge decision after a couple rounds of battle.

**Comment by asvitkine** [comment]
Closing this. I tried on 2.6 for 10 rounds of hard AI and didn't see any freezes.
