### ISSUE TITLE
Intercept Causes abort on Bots - "territoryEffects is marked non-null but is null"

### ISSUE THREAD

**Issue by drockken** [triplea-game/triplea#8189]
### How can the problem be recreated?

On a Bot (not local), load map: WWII Global 1940 2nd Edition
Selection all nations - doesn't have to be multiple players
At the start of the game, Edit 2 UK fighters to Novgorod
Edit 1 bomber to Germany (may not be important)
Germans declare war on the Soviet Union
Strategic bomb Novgorod with the 3 bombers from Germany
When the option to intercept the bombers presents, select all 3 fighters to intercept.  Game aborts with the error text below.

Additional Information: I cannot recreate this issue with the attached game-save in LOCAL games.  It is repeatable on Bots, and has happened many times in many territories in many games.    It always seems to happen when multi-nations are intercepting.  I don't know if it happens without multiple nations intercepting.

SEVERE: Unrecognized error occurred. If this is a repeatable error, please make a copy of this savegame and report to:
(6:52:23 PM) Bot205_Atlanta:  https://github.com/triplea-game/triplea/issues/new
(6:52:23 PM) Bot205_Atlanta:  java.lang.NullPointerException: territoryEffects is marked non-null but is null
(6:52:23 PM) Bot205_Atlanta:  	at games.strategy.triplea.delegate.power.calculator.MainDefenseCombatValue$MainDefenseCombatValueBuilder.territoryEffects(MainDefenseCombatValue.java:27)
(6:52:23 PM) Bot205_Atlanta:  	at games.strategy.triplea.delegate.power.calculator.CombatValue.buildMainCombatValue(CombatValue.java:51)
(6:52:23 PM) Bot205_Atlanta:  	at games.strategy.triplea.delegate.power.calculator.TotalPowerAndTotalRolls.getUnitPowerAndRollsForNormalBattles(TotalPowerAndTotalRolls.java:383)
(6:52:23 PM) Bot205_Atlanta:  	at games.strategy.triplea.delegate.battle.casualty.CasualtyOrderOfLosses.sortUnitsForCasualtiesWithSupport(CasualtyOrderOfLosses.java:108)
(6:52:23 PM) Bot205_Atlanta:  	at games.strategy.triplea.delegate.battle.casualty.CasualtySelector.getDefaultCasualties(CasualtySelector.java:295)
(6:52:23 PM) Bot205_Atlanta:  	at games.strategy.triplea.delegate.battle.casualty.CasualtySelector.selectCasualties(CasualtySelector.java:118)
(6:52:23 PM) Bot205_Atlanta:  	at games.strategy.triplea.delegate.battle.AirBattle$AttackersFire$2.execute(AirBattle.java:702)
(6:52:23 PM) Bot205_Atlanta:  	at games.strategy.triplea.delegate.ExecutionStack.execute(ExecutionStack.java:34)
(6:52:23 PM) Bot205_Atlanta:  	at games.strategy.triplea.delegate.battle.AirBattle.fight(AirBattle.java:113)
(6:52:23 PM) Bot205_Atlanta:  	at games.strategy.triplea.delegate.battle.BattleTracker.fightAirRaidsAndStrategicBombing(BattleTracker.java:1342)
(6:52:23 PM) Bot205_Atlanta:  	at games.strategy.triplea.delegate.battle.BattleTracker.fightAirRaidsAndStrategicBombing(BattleTracker.java:1323)
(6:52:23 PM) Bot205_Atlanta:  	at games.strategy.triplea.delegate.battle.BattleDelegate.start(BattleDelegate.java:113)
(6:52:23 PM) Bot205_Atlanta:  	at games.strategy.engine.framework.ServerGame.startStep(ServerGame.java:519)
(6:52:23 PM) Bot205_Atlanta:  	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:398)
(6:52:23 PM) Bot205_Atlanta:  	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:289)
(6:52:23 PM) Bot205_Atlanta:  	at games.strategy.engine.framework.startup.launcher.ServerLauncher.launchInternal(ServerLauncher.java:173)

### Do you have any ideas for an expected fix?
No.

### Attach a Save Game

[intercept.zip](https://github.com/triplea-game/triplea/files/5550398/intercept.zip)

### If playing a prerelease, which version are you using?

Game Version:
2.5.22294

### If playing a prerelease, does this happen on the latest release?

- [] yes
- [] no

**Comment by bung** [comment]
This is still an active issue. We had bots crash today trying to do intercepting of SBR runs on London...

`(12:15:15 p.m.) Bot705_Jersey:  Apr 16, 2022 6:15:23 PM games.strtegy.engine.framework.startup.launcher.ServerLauncher launchInternal
(12:15:15 p.m.) Bot705_Jersey:  SEVERE: Unrecognized error occurred. If this is a repeatable error, please make a copy of this savegame and report to:
(12:15:15 p.m.) Bot705_Jersey:  https://github.com/triplea-game/triplea/issues/new
(12:15:15 p.m.) Bot705_Jersey:  java.lang.NullPointerException: territoryEffects is marked non-null but is null
(12:15:15 p.m.) Bot705_Jersey:  	at games.strategy.triplea.delegate.power.calculator.MainDefenseCombatValue$MainDefenseCombatValueBuilder.territoryEffects(MainDefenseCombatValue.java:27)
(12:15:15 p.m.) Bot705_Jersey:  	at games.strategy.triplea.delegate.power.calculator.CombatValue.buildMainCombatValue(CombatValue.java:51)
(12:15:15 p.m.) Bot705_Jersey:  	at games.strategy.triplea.delegate.power.calculator.TotalPowerAndTotalRolls.getUnitPowerAndRollsForNormalBattles(TotalPowerAndTotalRolls.java:383)
(12:15:15 p.m.) Bot705_Jersey:  	at games.strategy.triplea.delegate.battle.casualty.CasualtyOrderOfLosses.sortUnitsForCasualtiesWithSupport(CasualtyOrderOfLosses.java:108)
(12:15:15 p.m.) Bot705_Jersey:  	at games.strategy.triplea.delegate.battle.casualty.CasualtySelector.getDefaultCasualties(CasualtySelector.java:295)
(12:15:15 p.m.) Bot705_Jersey:  	at games.strategy.triplea.delegate.battle.casualty.CasualtySelector.selectCasualties(CasualtySelector.java:118)
(12:15:15 p.m.) Bot705_Jersey:  	at games.strategy.triplea.delegate.battle.AirBattle$AttackersFire$2.execute(AirBattle.java:702)
(12:15:15 p.m.) Bot705_Jersey:  	at games.strategy.triplea.delegate.ExecutionStack.execute(ExecutionStack.java:34)
(12:15:15 p.m.) Bot705_Jersey:  	at games.strategy.triplea.delegate.battle.AirBattle.fight(AirBattle.java:123)
(12:15:16 p.m.) Bot705_Jersey:  	at games.strategy.triplea.delegate.battle.BattleTracker.fightAirRaidsAndStrategicBombing(BattleTracker.java:1342)
(12:15:16 p.m.) Bot705_Jersey:  	at games.strategy.triplea.delegate.battle.BattleTracker.fightAirRaidsAndStrategicBombing(BattleTracker.java:1323)
(12:15:16 p.m.) Bot705_Jersey:  	at games.strategy.triplea.delegate.battle.BattleDelegate.start(BattleDelegate.java:113)
(12:15:16 p.m.) Bot705_Jersey:  	at games.strategy.engine.framework.ServerGame.startStep(ServerGame.java:519)
(12:15:16 p.m.) Bot705_Jersey:  	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:398)
(12:15:16 p.m.) Bot705_Jersey:  	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:297)
(12:15:16 p.m.) Bot705_Jersey:  	at games.strategy.engine.framework.startup.launcher.ServerLauncher.launchInternal(ServerLauncher.java:173)`

**Comment by asvitkine** [comment]
I looked at this and I'm pretty sure this should be fixed in 2.6 already.
The relevant combat classes have been rewritten so the specific error stack can't happen and the place where we get a territory's effects always returns non-null on 2.6.

Closing, but please re-open if there's evidence of this on 2.6.
