### ISSUE TITLE
migrate the bundled readme.html to website. 

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#820]
The readme.html bundled with the game is quite good, but it should be on the website. Task: move it to the website.

https://github.com/triplea-game/triplea/blob/master/readme.html

**Comment by RoiEXLab** [comment]
@DanVanAtta Are you requiring adding some CSS etc... in order to move it to the Website?
If not you probably should ^^

**Comment by DanVanAtta** [comment]
I'm indifferent, but the page should be migrated and not bundled with the game.

**Comment by RoiEXLab** [comment]
I looked at the readme Website, and it seems, that the  TripleA Website itself already replaced this file...

1. What is TripleA ?
2. About TripleA
3. Getting Started
4. Playing A Game
5. The TripleA Community
6. Developer Documentation
7. Contributing to TripleA
8. Credits & Acknowledgements

Is pretty much the Website's Content...

**Comment by DanVanAtta** [comment]
The readme has a lot of detail about using the map making tools and process. That has not been ported over, it does seem like otherwise the website has come a ways in covering much of the readme topics.

**Comment by DanVanAtta** [comment]
This is done! 
http://www.triplea-game.org/playing_the_game_engine_readme/
