### ISSUE TITLE
Idle timer next to player names in multiplayer

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#821]
A timer to indicate "time since last game action" next to player names in multiplayer would be helpful.  Would know if someone is there or not. 

We likely would want to also have a hidden 'is alive' counter as well, so we can indicate when connectivity has been lost.

**Comment by simon33-2** [comment]
We are talking about the lobby here? It is a nice to have

**Comment by DanVanAtta** [comment]
lobby network games, next to the chat dialog. Would also probably want a preferences option to turn it on/off.

**Comment by DanVanAtta** [comment]
backlogged: https://github.com/triplea-game/triplea/wiki/Feature-Back-Log/
