### ISSUE TITLE
round 10.000

### ISSUE THREAD

**Issue by GXIII** [triplea-game/triplea#8224]
round 10,000 reached in battle?

**Comment by DanVanAtta** [comment]
Did TripleA give you an option to 'report to triplea'? 

We appreciate the error notification here, though we are missing a lot of information and will not be able to solve this with the provided info.

**Comment by GXIII** [comment]
It said to report to tripleA but it went to GitHub
    On Sunday, November 22, 2020, 03:53:08 PM EST, Dan Van Atta <notifications@github.com> wrote:  
 
 


Did TripleA give you an option to 'report to triplea'?

We appreciate the error notification here, though we are missing a lot of information and will not be able to solve this with the provided info.
