### ISSUE TITLE
[High Priority] Travis not Running on some PR commits

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#826]
Look at #825.
The Travis Build didn't trigger.
But the TripleA master builds are still running

EDIT: It seems that only some commits are triggering new builds...  #827

**Comment by DanVanAtta** [comment]
I do not see #827 being built in the pull history log on travis: https://travis-ci.org/triplea-game/triplea/pull_requests

It does look like travis missed it.

There is nothing we can do to fix this. We can report it to the travis org. So far the frequency is quite low, if things get bad/broken, then we should revisit our tooling.

**Comment by RoiEXLab** [comment]
Close?
