### ISSUE TITLE
I am ready to add my map

### ISSUE THREAD

**Issue by TheDog-GH** [triplea-game/triplea#8300]
I have a playable map that is ready to be shared with the TripleA community.  Please send me an invitation to join my own map team at triplea-maps

**Comment by DanVanAtta** [comment]
Invite sent

**Comment by TheDog-GH** [comment]
Please can you have  a look at this map repository 
https://github.com/TheDog-GH/settlers_age_of_tribes

I have tried to follow Frostions, 
Guide - How to make your map downloadable in TripleA
but his 2018 guide is a little out of date.

I have stumbled, I think I have uploaded my map, Im not sure, but in a flat file structure with no map folder, like RogerCooper said, but that was for using on Google Drive, can I still have the same structure or for GitHub do most of the folders need to be in a map folder?

Also I did **not** get the chance/option to assign;
_"two Teams that you want to have access to your map; MapAdmins and your own personal team (Your GitHub Name). "_

Please help.

**Comment by beelee1** [comment]
yea you need all the files (base tiles, flags, PUs etc ...) in one folder called map. Then the readme and a description. So in your home triplea downloaded maps folder, open it up and you'll see those 3. That's what should be in your repo. It should look like this

![Screenshot from 2020-11-30 22-59-37](https://user-images.githubusercontent.com/24382682/100699177-e6aded80-335f-11eb-9d1b-4f00bfb37a3e.png)

#

So you should be on master branch and all your stuff should be in the map folder. The two team thing is automatic I think. Both you and triplea will have access to your map. Are you on windows ?

**Comment by beelee1** [comment]
@TheDog-GH  Did you get this resolved ? If so, you can close it.
