### ISSUE TITLE
Single Process TripleA - https://github.com/triplea-game/triplea/projects/21

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#8330]
It's been a long-standing desire for TripleA to be a single process and not launch a new one every time a person launches a game.

This problem bites us from time to time, makes debuggers sometimes not attach and is cumbersome when opening a server port as the port cannot just stay open when a game is laucnhed but needs to be relaunched.

So far, it looks like this project won't be too bad to implement. The biggest hurdle I see so far is to avoid any `System.exit` calls and to only close the app when all windows are open. For example, when closing a game we go back to the main frame, when main frame closes it does a System.exit. The result of this is if there are other game windows open, the process is terminated and they'll prematurely close.

I'm sure there will probably be other hidden problems, it's a question what those are and how many we will find.

**Comment by RoiEXLab** [comment]
IIRC another problem is that the code makes the assumption that there can only ever be one window/instance of xyz, so a lot of the fields are static references to the invividual objects.
I don't think it's necessary to make everything a non-static object, but we definitely need to make sure to update those static references properly to avoid memory leaks

**Comment by DanVanAtta** [comment]
So long as the static references are re-used after a game is opened and closed, memory leakage I don't think is the concern. `ClipPlayer` is an example where the instance is static, it could get overwritten by a new reosurce loader so suddenly one map is playing sounds that should instead be played on another. I agree that these static references are a liability. It is also where a fair amount of work already has gone, the static calls to `System.exit` were some of the earliest and most salient examples.
