### ISSUE TITLE
"Slow But Perfect" Casualty Option

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#838]
#834 for some more context.

Since nobody knows what this does, it does not seem like this feature is providing much value.

**Comment by RoiEXLab** [comment]
I always thought that this switches to an advanced algorithm for the default selection of casualties when battling...
I never saw any performance difference... 
Maybe that's just because of my good computer, or computers simply got good enough since this feature got implemented

**Comment by DanVanAtta** [comment]
* Found some background on when this was created: http://tripleadev.1671093.n2.nabble.com/OOL-Order-of-Loss-or-of-selecting-casualties-tp7587338p7587436.html

* Took some timing measurements of the difference between the two methods: https://gist.github.com/DanVanAtta/007b84b38506bd3b75e2e49a25815606

* Determined as well that the option only applies to the battle calculator. 

The new default adds some caching and uses support ordering to make faster decisions. It seems unlikely that the average user would know the impact of this setting, and likely most people use the default.

Seems like we can jettison the old, brute force, battle calc casualty sort algorithm in favor of the newer one (which has been the default for some time already).

**Comment by ron-murhammer** [comment]
@DanVanAtta I would leave that option even though its probably rarely used by anyone. The brute force is still better but is about an order of magnitude slower. The new algorithm handles most maps fully but I don't think properly takes into account units that provide support to enemy units.

**Comment by DanVanAtta** [comment]
@ron-murhammer  please file bugs for any problems with the default algorithm, those are open bugs. 

"Rarely used" is I think overstating it. Nobody knows what the "perfect but slow" option even does, how can anyone use it?

**Comment by ron-murhammer** [comment]
@DanVanAtta Well I wouldn't really call it a bug. More like a feature request to improve default casualty selection. 

Not sure how many people use it or if its a lack of understanding or that they wouldn't use it anyways.

**Comment by DanVanAtta** [comment]
Lack of understanding is the first problem. I had to look at the code to know what it did, and Cernel did not even know what this option did. It is a very bad sign when not even Cernel knows what it does, he is familiar with just about every feature we have.

We could solve the "bug" vs "feature request" issue by calling the two both "an improvement" ;)

In this case though "bug" label is I think more appropriate. It is expected for the default battle calc algorithm to work. Anything missing or not working is a problem, and should be tracked.

I think this still feeds into the original conversation. IF we fix the last couple of problems with the *default* casualty algorithm, at what point will the brute force be ever then be useful again? There is no value in keeping an unused feature around, and we pay a significant cost for having them.

Rather than invest time documenting these two features, and fixing bugs in exactly one of them, I think we would be better off prioritizing our work and merging the two features, and fixing whatever bugs there may be. That consolidates our test effort as well. The value gained by the maybe one person that uses this feature is not significant, there are few battle calc's where the difference is even all that match. So not only is this a "rarely" if ever-used feature, namely because nobody knows what it does, but even if you did know, the cases where it would make a difference are very few.

**Comment by ron-murhammer** [comment]
@DanVanAtta I'm fine removing that option if you want as it probably isn't used much. One thing to note is that the 'perfect but slow' is actually the 'better approximation' of the 2 algorithms but doesn't run fast enough to be viable and isn't perfect.

I actually disagree with bug vs feature here. This is essentially an approximation algorithm situation and its probably up for debate if there is even a 100% correct solution as it would end up having to consider lots of different probabilities and even what casualties the enemy would choose to select. Choosing the 'optimal' casualties when considering varying attributes of support allied vs enemy, amount per unit, number of units, and rolls along with the units standard values isn't easy.

Honestly, the current one covers such a large percentage of scenarios and making it much better would take a pretty large effort. You can ask around that the current one vs the previous which could only handle basic artillery support (not multiple units or values or rolls) was a major change but anything beyond what we have now would only be noticed on a few select few maps.

**Comment by Cernelius** [comment]
Can a full list or at least some examples be made of cases in which the autoselect by Perfect would be different from Default, before deciding to delete Perfect?
I think it may be good to support advanced uses of supports.

Also, if it is not already so, I suggest only Perfect always applying outside of the battlecalculator, because the battlecalculator is the only case in which the slowness of Perfect is noticeable.
Wouldn't it be better having always Perfect outside of the battlecalculator and being able to choose between Default and Perfect in the battlecalculator itself, each time (instead of in Engine Preferences)?

And I want to eco LaFayette: Nobody knows what the "perfect but slow" option even does, how can anyone use it?

**Comment by DanVanAtta** [comment]
@Cernelius , it turns out it would be quite complicated to provide such a list. The caching version has been in use, for technical reasons it's very attractive to remove the old brute force version. When we come back to potentially remove the brute force version, we can try to spot the obvious differences..

Summarizing: In the engine settings window there is a button to control which casualty selection is used. One is brute force and the other has caching and a few other tweaks. The code for each is largely copy/pasted forks, it is difficult to tell the differences. General inclination is to remove the brute force version

**Comment by Cernelius** [comment]
I've no clue what the "perfect but slow" does better than the other one, if anything. I only know that was made by Veqryn and redrum; so I guess they should know.

**Comment by DanVanAtta** [comment]
Veqryn wrote the oriignal, Red wrote the update. Differences summarized a bit with:

> "You can ask around that the current one vs the previous which could only handle basic artillery support (not multiple units or values or rolls) was a major change but anything beyond what we have now would only be noticed on a few select few maps."

@ron-murhammer , any other notable differences you can remember? Asked another way, is there anything in the 'old' selection method that really should be salvaged?

@Cernelius , since the one replaces the other, and it's such a large fork in the logic, and everyone is using the default without knowing the differences, the solution will not be to continue with them both as independent choices/options. The two code paths should get merged for sanity of the code, which means either the option is renamed to fit the difference it makes, or it is broken up into multiple controls depending upon how many different things can be altered, or alternatively it is all merged into one. Given the feature, the latter is the best option for now.

Future casualty selection preferences are likely going to be best for in-battle options. For example a control that says you want to select lowest TUV instead of lowest attack power first for that battle (perhaps with a checkbox to make that the default).

**Comment by Cernelius** [comment]
> Veqryn wrote the oriignal, Red wrote the update. Differences summarized a bit with:
> 
> > "You can ask around that the current one vs the previous which could only handle basic artillery support (not multiple units or values or rolls) was a major change but anything beyond what we have now would only be noticed on a few select few maps."

No. This refers to the previous one, which is not available anymore, not to either of the current two available ones.
My guess is that the "Perfect but Slow" handles more things than the default, but I don't know.
Also I know that a significant problem with the autoselect is that it doesn't handle supports related to infrastructure (like the "Fort" of Rome Total War (a capturable infrastructure giving defensive bonus to allied archers)), but never got around opening an issue about it.
When the new ones were made, I also suggested keeping an option (off as default) for having a not support-related casualty option (autoselecting casualties without taking into account supports at all), but Veqryn was strongly against.
As now, the biggest limit of any autoselect is that they don't see AA attacks, so, if you make a map with a lot of multiple combat rounds AA attacks, the autoselection is likely to be very bad.
Anyway, only @Veqryn or @ron-murhammer can give more info, unless a developer wants to delve into the code.
I'm just suggesting knowing what the "Perfect but Slow" does better, if any, before eventually removing it.
As far as I know, Veqryn and redrum just made these two options but never told anyone what are they for.

**Comment by DanVanAtta** [comment]
High time to put this to bed. Brute force is slower and not the default/used option. The code management complexity is on the other hand quite costly. https://github.com/triplea-game/triplea/pull/1474 removes the option and allows only the default algorithm.
