### ISSUE TITLE
More zoom

### ISSUE THREAD

**Issue by DanLeeDR01** [triplea-game/triplea#8397]
Hello,

Can you add more zoom ?

On some very crouded maps like world at war you can not zoom in just a litle bit. With unit size on small its still to difficult to see all the territories.

Kind regards,

Danny

**Comment by Navalland2** [comment]
As far as I know the only way to have more zoom is increasing the resolution of the base map than creating polygons, placements, and reliefs from the stratch.

**Comment by RoiEXLab** [comment]
In theory there's no real zoom limit, but if we'd allow zoom levels larger than 100% you'd start seeing the individual pixels of the raster images which doesn't look good.
That's why zooming is capped at 100%

**Comment by TheDog-GH** [comment]
Complete
https://github.com/triplea-game/triplea/pull/12082
