### ISSUE TITLE
Triple A Iron war 

### ISSUE THREAD

**Issue by larrykid** [triplea-game/triplea#8399]
When playing the axis , Russia does the same move every time they hole up in Leningrad and let you move around them as long as you have a force in Byelorussia , taking territories and streaking thru its back line.

The USA are lame and cant seem to mount and offensive on Germanys fleet keeping the US at bay and wreaking the US fleet periodically and at the same time they build lame vs the Japanese, USA should devout 75% to one side or another. This AI on Russia and US is very herky jerky Why does the US do the same move with planes, it tries to fly them in from Alaska in Russia territories at the top of the map...why not fly them into Britain to help with blowing up Germanys fleet and adding protection for Russia? All the island allies countries ANZAC Australia and so forth don't turtle up their boats and if Japan moves to close they bolt towards Africa only to get pummeled  by Italy off the coast with free subs. Also if they do turtle up and Italy runs a sub or boat into the money Buoys, they attack it no matter the cost one by one...lol So basically if your Italy you run your free sub into a Buoy to the west and the allies attack it, on the next turn Italy destroys those boats and does it again. Allied boat need to stay together. They will defend a 10 dollar buoy and lose 40 bucks or more in boats.

Great game though it has all the right stuff , AI needs tweeked.

**Comment by larrykid** [comment]
Also noticed that countries will run a transport filled with troops out in the open with no cover and where they stop is within 2 moves of enemy boats , Britain, France, Brazil all have done this more than once. There goes 20 for the boat, 2 soldiers for 20 and arty piece for 11 and a total of 3 iron plus fuel two land to moves from Axis boats...
one more thing why is Russia stuck on buying transport planes , by round 4 they got like 5 or 6 laying around doing nothing and they dont use them, they use them to soak hits...

**Comment by larrykid** [comment]
Ok answered my own question i had not played the Allies yet , just seeing if the computer could beat me on hard . I switched to play the Allies, When i play the Axis , game is really over by round 5 or 6. Anyway some of the allies get a free air transport every round, but Russia doesn't use it anyway and i think they should receive 1 extra infantry a round and on round 5 it goes to 2 , to reflect the Russian zerg at the end.

**Comment by DanVanAtta** [comment]
Forums has more of the community watching and would happily engage with more discussion like this. Interesting/amusing thread - recommend to check it the forums:   https://forums.triplea-game.org/
