### ISSUE TITLE
Axis and Allies maps

### ISSUE THREAD

**Issue by larrykid** [triplea-game/triplea#8400]
Guys if you make new maps, Can we stop making traditional maps with the basic look? WAW or Iron War maps are way better. There are literally 40 plus maps that use basic bitch mode lol, i dont want to play those, Give me more territories and something to look at.

**Comment by CharlieAtlas** [comment]
The people here generally only work on the engine and bug fixes.  The best way to get new maps is to make them.  There are so many of the maps that look alike because making new graphics etc. is a ton of work.  But changing the unit composition, stats, icons, etc. is a much simpler change.

**Comment by DanVanAtta** [comment]
Will second that, most map makers hang out in the forums: https://forums.triplea-game.org/category/5/maps-mods
