### ISSUE TITLE
Join triplea-maps to upload my map

### ISSUE THREAD

**Issue by ZarophChello** [triplea-game/triplea#8406]
As per Frostions guide, using this issue to join triplea-maps to upload my map warcraft:lordaeron wars to the triplea repository.

**Comment by DanVanAtta** [comment]
Will need to get the guide updated : )
@ZarophChello , post the map to a new repository, once done we'll fork it into the organization and then give you admin.

**Comment by ZarophChello** [comment]
My map repository is at:
[https://github.com/ZarophChello/lordaeron_wars](https://github.com/ZarophChello/lordaeron_wars)

**Comment by DanVanAtta** [comment]
Check for a setting to make the repository public @ZarophChello , I get a 404 going to that link.

**Comment by ZarophChello** [comment]
Ah it was set to private, thanks.

**Comment by DanVanAtta** [comment]
Forked, new repository is: https://github.com/triplea-maps/warcraft_lordaeron_wars
You should have an invite for admin of that repo.

Next you'll need to update: https://github.com/triplea-game/triplea/blob/master/triplea_maps.yaml to list your map so it's available for download by others from in-game. Let me know if you have any questions.

**Comment by ZarophChello** [comment]
I see the invitation, thanks.

I just edit it and make a pull request? Since I cant edit the file directly.

**Comment by DanVanAtta** [comment]
> I just edit it and make a pull request? 

Yes, exactly
