### ISSUE TITLE
MapXML creator cannot be launched from the game

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#843]
If I'm not missing something, it does not look like the map creator that frostion imported can be launched from within the game. 
Task:
- add button to launch it. Main class is at: `tools.map.xml.creator.MapXmlCreator`

**Comment by RoiEXLab** [comment]
@DanVanAtta Preferences Window?

**Comment by DanVanAtta** [comment]
That launches the old map making tool, not the new one that was ported over recently. Or have I been working with 1.9 for that long that I do not realize we did not have that link in 1.8.0.9

**Comment by RoiEXLab** [comment]
There is a new one?

**Comment by DanVanAtta** [comment]
yes: https://github.com/triplea-game/triplea/blob/master/src/tools/map/xml/creator/MapXmlCreator.java

**Comment by RoiEXLab** [comment]
Ah I see...
Is this new MapCreator an addition or an replacement for the old one?
If it's an replacement, then we could simply change the class name of the old Creator with the class name of the new one...

**Comment by DanVanAtta** [comment]
Additional AFAIK. @frigoref , could you weigh in?

**Comment by frigoref** [comment]
The new MapCreator is a start for a replacement of the C#-based version. (sry, didn't notice the thread earlier)

**Comment by RoiEXLab** [comment]
@frigoref Ah Thanks... If it's finished, is the old MapCreator obsolete?

**Comment by frigoref** [comment]
The old MapCreator should be kept as reference for the moment I guess, but its usage is deprecated.

**Comment by RoiEXLab** [comment]
@frigoref What would you suggest to do?
Switch out the class name to be the new one or create a new button?

**Comment by frigoref** [comment]
Sorry, What class name are you referring to? I am confused.

**Comment by RoiEXLab** [comment]
@frigoref The Map Creator is currently being called by calling javaw.exe (on Windows) with the class name of the old MapCreator e.g. `tools.map.making.MapCreator` we could replace this with the new one if it's ready to be replaced...

**Comment by frigoref** [comment]
What is the new one? Sry, currently my thoughts are around work and EM ^^ and I still do not understand what should be replaced.
The MapCreator package I developed could replace the old map creator application as the number of affected users is quite small, the old map creator is not up-to-date anyway and the new MapCreator needs testing.

**Comment by RoiEXLab** [comment]
@frigoref 
Old one: `tools.map.making.MapCreator`
New one: `tools.map.xml.creator.MapXmlCreator`

**Comment by DanVanAtta** [comment]
@frigoref  @RoiEXLab  - this is urgent. People need an in-game way to launch the map making tool. At the very least we need some good documentation on how to run, but the in-game way would fit in with the existing tools.
This is just about the last urgent issue before we release..

**Comment by RoiEXLab** [comment]
@DanVanAtta I can do this... The question is should I replace the ild one or just add a new button next to the old one?

**Comment by DanVanAtta** [comment]
A new button please -  then we can take our time deciding whether to drop the old one or not.

**Comment by RoiEXLab** [comment]
#877 Adds this button next to the old one...

**Comment by RoiEXLab** [comment]
@DanVanAtta this can be closed
