### ISSUE TITLE
I would like to add my map

### ISSUE THREAD

**Issue by axisalliescontango** [triplea-game/triplea#8461]
Hello,

I have a playable map that is read to be shares with the TripleA community.  Can you please send me an invitiation to join my own map team at triplea-maps?

**Comment by DanVanAtta** [comment]
Just post the map to a repository under your account @axisalliescontango , provide the link and then we'll fork it and then send you an invite.

**Comment by axisalliescontango** [comment]
Hi Dan, 

I've posted the map.  Hoping this is the link you need, but let me know if it's not:

https://github.com/axisalliescontango/g40_alt_universe/tree/master

Thanks.

**Comment by DanVanAtta** [comment]
Done, here is the new repo: https://github.com/triplea-maps/g40_alt_universe/

You should have an invite in your email to gain admin access over the new repo.
