### ISSUE TITLE
TripleA Error :: Remote method call exception

### ISSUE THREAD

**Issue by HSThompsn** [triplea-game/triplea#8482]
At the time, was playing with (4) other friends on the Pact of Steel 2 map.  Then this error randomly popped up:

_"Remote method call exception: Not in a step, but trying to add event: 1 fighter moved from Italy to 13 Sea Zone. Current history node is: null  java.lang.IllegalStateException: Not in a step, but trying to add event: 1 fighter moved from Italy to 13 Sea Zone. Current history node is: null"_

**Comment by DanVanAtta** [comment]
Did that crash the game @HSThompsn ? I think we've seen that before and the impact is not too horrible, that there will be game actions missing from the history.

**Comment by HSThompsn** [comment]
Hey Dan!

Let me just start by saying my friends and I have been playing since 1998 when we got that first glorious board game.

As adults, we can’t thank you and the team enough for allowing us to indulge in our long standing love affair by removing the hours of board setup.  We’ve all been friends since middle school, and now with our mid-30’s, kids, careers, wives, etc.  just being able to hop online together and blast out a round in the hour we carve out is AMAZING.

So thank you guys so much.

To answer your question, it’s weird.

If you hit the X to close the alert window, the game continues.

If you hit “okay” on the prompt button, the game crashes to lobby (saving the crash file too though for re-load).

Hope this helps. If you guys need anything, you’ve got five veterans on call.

Love love TripleA!

-Andrew (Chris, Adam, Frank, and Nick)
