### ISSUE TITLE
Download Maps windows needs to be adjusted

### ISSUE THREAD

**Issue by FrostionAAA** [triplea-game/triplea#851]
Problem one:
The left side window of the “Download Maps” screen seems to be a few pixels to narrow for the 400px map preview pictures. Yes you can manually make the windows larger by mouse click-holding the frame of the window and dragging it to the right, but as a standard the window opens up to small, therefore generating the left/right scroll bars. Look at this picture, it is how it looks as standard:
![downloadwindow](https://cloud.githubusercontent.com/assets/15268177/16136548/cc132f72-342b-11e6-972a-fe1aaebe8370.png)
Problem two:
It seems that the left side preview window is also scrolled like half way down? If you click a map that has a long description and has preview pictures, like Diplomacy in this picture, it will be scrolled down when shown, thereby not showing the title text and the top of the preview picture.

**Comment by DanVanAtta** [comment]
#854 will make the download window about 30% larger. Gets rid of some of the scrollbars.

As for problem two, that's been an ongoing problem since 1.8.0.9. The larger window seems to have helped (maybe). It's been an elusive problem thus far.

**Comment by RoiEXLab** [comment]
@DanVanAtta can be closed as well...
