### ISSUE TITLE
Prerelease error - “INFO: Found too many files for…“

### ISSUE THREAD

**Issue by FrostionAAA** [triplea-game/triplea#855]
I have been messing around with updating the yaml file / map download list to include my maps, and in the process I noticed an error that I first thought was related to running my maps in tripleA pre-releases, but now I can see that the error occurs when running any map in the pre-release. The console does not pop up, so one has to start a map and open the console manyally.

I did a clean install of tripleA (1.9.0.0.2148), first removing all game versions from my games dir and removing the downloadedMaps, maps and save game dir completely. EVERY map I have downloaded, even if I just download only one map, shows this error when I start the map (besides the tutorial map - maybe because it is not in the downloadedMaps dir?).

**Error report looks like this:**

_triplea.engine.version.bin:1.9
INFO: Found too many files for: 270bc  found: [C:\Users\David\triplea\downloadedMaps\270bc.zip, C:\Users\David\triplea\downloadedMaps\270bc.zip]
INFO: Found too many files for: 270bc  found: [C:\Users\David\triplea\downloadedMaps\270bc.zip, C:\Users\David\triplea\downloadedMaps\270bc.zip]
Heap utilization statistics [MB]
Used Memory: 72
Free memory: 331
Total memory: 403
Max memory: 910_ 

Or in case of the ”Pacific Theater Solo Challenge” map like this: 

_triplea.engine.version.bin:1.9
INFO: Found too many files for: pacific_challenge  found: [C:\Users\David\triplea\downloadedMaps\pacific_challenge.zip, C:\Users\David\triplea\downloadedMaps\pacific_challenge.zip]
INFO: Found too many files for: pacific_challenge  found: [C:\Users\David\triplea\downloadedMaps\pacific_challenge.zip, C:\Users\David\triplea\downloadedMaps\pacific_challenge.zip]
Heap utilization statistics [MB]
Used Memory: 69
Free memory: 206
Total memory: 276
Max memory: 910_

**PS:**
I think there is a misspelling in the popup error window title?
An error has occured! (The TripleA error popup window title.)
An error has occurred! (Correct spelling according to my Microsoft Word spell-check (English, USA))

**Comment by RoiEXLab** [comment]
See #620 for more information...
AFAIK This is supposed to be fixed just before the Release

**Comment by DanVanAtta** [comment]
This message means the game found multiple locations with the same map files. It always then uses the first one it found based on the order in which it searched. https://github.com/triplea-game/triplea/pull/905 will update this warning message.
