### ISSUE TITLE
Can't Download maps

### ISSUE THREAD

**Issue by Heppisorus** [triplea-game/triplea#8556]
No idea what this means after I installed the newest engine.

![image](https://user-images.githubusercontent.com/30943648/103422720-d82a4000-4b70-11eb-93a1-9671f7ba052e.png)

**Comment by DanVanAtta** [comment]
Did you click the 'report to triplea' and also submit a bug report with it?

**Comment by Heppisorus** [comment]
I did

**Comment by DanVanAtta** [comment]
Thanks, you did @Heppisorus : https://github.com/triplea-game/triplea/issues/8555

**Comment by Heppisorus** [comment]
Is there any info on this?  Something I should be doing or trying?

**Comment by DanVanAtta** [comment]
@Heppisorus could you try re-installing but to a 'custom' location inside your home folder?

**Comment by Heppisorus** [comment]
Sure.  I will give it a try.

**Comment by DanVanAtta** [comment]
Are you still seeing this problem @Heppisorus ?
