### ISSUE TITLE
270bc_variants Delete (2020/01/02)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#8565]
I want to (and can) delete
https://github.com/triplea-maps/270bc_variants

I'm however asking permission to proceed, since this will be followed by a request to delete the game from download list (which I cannot pull myself).

---

The reason is that
https://github.com/triplea-maps/270bc_wars
is substantially the successor.

Also for this reason, I'm going to ask it to be upgraded to "Good" quality (which is where 270bc_variants is).

**Comment by Cernelius** [comment]
Does the merging of
https://github.com/triplea-game/triplea/pull/8567
implies that I can now proceed with this deletion?

**Comment by DanVanAtta** [comment]
Yes

**Comment by Cernelius** [comment]
Done, thanks.
