### ISSUE TITLE
Can't post to axisandallies.org

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#8597]
### How can the problem be recreated?
Play by forum on axisandallies.org, can't post turn.

Only happened since recent forum upgrade so perhaps not a triple-a bug but maybe it may need to be changed to support the upgrade? Nice if some input could be provided to djensen in any event.

### If playing a prerelease, which version are you using?

Game Version:
2.5.2294

### If playing a prerelease, does this happen on the latest release?

- [] yes
- [] no

### Is there anything else we should know?
Is this a duplicate? Couldn't find where this had been reported.

**Comment by RoiEXLab** [comment]
Duplicate of #8584

**Comment by Cernelius** [comment]
@RoiEXLab I was wondering myself if this could have been closed and if automatic error reports can be really considered duplicates of deliberately opened issues, especially with such undescriptive titles...

**Comment by RoiEXLab** [comment]
Well @djensen47 added some description to it so it's fine I guess

**Comment by djensen47** [comment]
Yeah, I went to look for the issue here first before filing. Found it and commented.

**Comment by simon33-2** [comment]
Oh ok, tried to find an existing issue and couldn't locate it.
