### ISSUE TITLE
"Victory Bonds" Technology does not work with Version 2.5.222294

### ISSUE THREAD

**Issue by SwampyAcres** [triplea-game/triplea#8609]
Game = Steampunk Advanced
Triplea Version= 2.5.222294

Issue= This game has a technology role for "Victory Bonds" that does two things
1) Adds two dice rolls (10 sided die) to add PU
2) Adds 1 production to factories

When the player successfully rolls and gets Victory Bonds.. the factory production increases, but the rolls for the extra PU does not occur. This problem did not exist in version 1.9. See code below

I have attached a save game demonstrating the issue (France has "won" victory bonds.. factory production increased yet, no tech role). GitHub does not allow .tsvg file type, so I just renamed my save game to a .pdf. Just change file extention back to .tsvg. 

[2021-1-9-Steampunk-Advanced.PDF](https://github.com/triplea-game/triplea/files/5791254/2021-1-9-Steampunk-Advanced.PDF)
<attachment name="techAbilityAttachment" attachTo="victoryBonds" javaClass="games.strategy.triplea.attachments.TechAbilityAttachment" type="technology">
			<option name="warBondDiceSides" value="10"/>
			<option name="warBondDiceNumber" value="2"/>
			<option name="productionBonus" value="1:Factory"/>
			<option name="minimumTerritoryValueForProductionBonus" value="1"/>

**Comment by DanVanAtta** [comment]
Thank you for attaching the save game @SwampyAcres , it was really helpful and made fixing this much faster.

#8993 will fix this problem for save games, once that is merged and new latest is built, that prerelease engine can be used to then see the war bonds dice roll happen.

Meanwhile there is map fix that can be done, if players update to the latest maps then a fix will appear there for the current game engine.

**Comment by ron-murhammer** [comment]
This appears to be fixed so closing.
