### ISSUE TITLE
RouteDrawing glitch when hovering beyond Map "borders"

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#863]
![Screenshot](https://cloud.githubusercontent.com/assets/8350879/16191197/64aa3032-36e3-11e6-8de3-20d7c848755c.png)
Note, this is not a problem of the RouteDrawer itself, more a problem of the route given/ the MapPanel give...
If we'd change the MapPanel to have `<0` and `>MapPanel.widht` offset, this problem can easily resolved...

**Comment by DanVanAtta** [comment]
What exactly is the glitch?

**Comment by RoiEXLab** [comment]
@DanVanAtta in the Screenshot my mouse is actually hovering over the west Canada...
But the route is drawn to West Canada in the East of the map. 
As I'm writing this... I habe an Idea what's may causing this... I max jump in with a fix soon

**Comment by RoiEXLab** [comment]
@DanVanAtta Problematic when playing Americans on Maps like Classic WW II... Works, but Route is  not appearing...

**Comment by RoiEXLab** [comment]
Since my lates update on that, I could find any greater glitch, than a route going behind the globe or something like this... Closing since this has nothing to do with this issue...
