### ISSUE TITLE
TripleA won't run properly under MacOS Big Sur 11.1

### ISSUE THREAD

**Issue by noharm1010** [triplea-game/triplea#8658]
### How can the problem be recreated?
I can start TripleA but in engine settings menu  the game freezes and sometimes blinks.

### Do you have any ideas for an expected fix?
I think it's Java related?

### Attach a Save Game
No, not necessary 

### If playing a prerelease, which version are you using?

Game Version:

### If playing a prerelease, does this happen on the latest release?
Tried several versions, including the beta but all won't start.

- [] yes

**Comment by DanVanAtta** [comment]
Is the OS a common denominator? Does anyone else running Big sur 11.1 also have this problem?

AFAIK no developer has mac, let alone multiple OS versions, this could be difficult to fix if it's a problem for anyone on just Big sur.

**Comment by beelee1** [comment]
There was a problem a few years ago on macs that caused a flashing on startup. Think it was pre git on sourceforge. Thought I had the old sourceforge page but must have lost it.

**Comment by noharm1010** [comment]
https://user-images.githubusercontent.com/16231183/104958302-0f517b80-59d0-11eb-9e43-57443357c72c.mov

I uploaded a short movie where you can see that the settings menu is displayed in a tabpage.
I can't select a option, only thing happening is allot of blinking.

There is a Windows laptop @home so I can play the game, but I prefer it on my MacBook with large screen :-)

**Comment by DanVanAtta** [comment]
Thanks for posting the video. Do you have access to other versions of Mac OS, do we know if this specific to Big Sur?

**Comment by beelee1** [comment]
yea thats how it did it before as far as blinking/flashing, except was the whole screen.

**Comment by DanVanAtta** [comment]
Does any other screen do that? Perhaps the download maps window?

**Comment by noharm1010** [comment]
I only have access to Big Sur so i'm not able to test it with other MacOS versions.
The blinking/flashing screen is only available in the settings menu. But when I play the game and somewhere in the game is a pop-up, the same problem occurs again. 
For example, I'm not able to play the tutorial till the point where I buy new army units. 
At that point a new window appears here I need to buy items but i'm not able to select the buttons.

**Comment by asvitkine** [comment]
@noharm1010 are you still experiencing this? I don't get this on 11.6.

**Comment by noharm1010** [comment]
> @noharm1010 are you still experiencing this? I don't get this on 11.6.

It seems to work by now, I'll pick up the game again.
Thnx for the remider.
