### ISSUE TITLE
Want to add a custom map to TripleA

### ISSUE THREAD

**Issue by kevinkunker** [triplea-game/triplea#8673]
I have a playable map called "World War 1 End of Empires" that is ready to be shared with the TripleA community. It is a game that focuses on World War 1 in Europe with a start date of April 6th, 1917, when the United States entered the war. Please send me an invitation to join my own map team at triplea-maps. I have been following this guide on how to make my map downloadable on TripleA: https://docs.google.com/document/d/1FfF7N0srp9QG0_if5D-c1d1Aa1QTttdhxgm1GBh3pI4/edit

**Comment by kevinkunker** [comment]
My repository is currently located at [https://github.com/kevinkunker/world_war_1_end_of_empires](url)

**Comment by kevinkunker** [comment]
I don't know if anyone already sent me an invitation to join triplea-maps, but I haven't received one. If I'm doing something wrong (like if the guide I'm using is outdated) please tell me because otherwise I won't know what I should do. If you don't like the map then I can always change it to be better. Thanks!

**Comment by kevinkunker** [comment]
OK I got the invitation, thanks!

**Comment by DanVanAtta** [comment]
The word doc needs to be updated as the process is a bit different. You'll notice that there is a new repo in triplea-maps @kevinkunker , the repo hosted under your personal space is now a duplicate and can be removed if you wish.

**Comment by kevinkunker** [comment]
OK, I saw the new repo and will be pushing updates to that. The only other thing I saw to do in the word doc is to update the Yaml file, is that the same?

**Comment by DanVanAtta** [comment]
yes

**Comment by kevinkunker** [comment]
OK thanks for your help @DanVanAtta, I think I will close this issue now. I am happy to see my map in TripleA downloads! Also, I don't know if you tried the map yet but there was a bug where there were no territory connections to Prussia but I fixed that.
