### ISSUE TITLE
Saved games functioning differently than fresh ones

### ISSUE THREAD

**Issue by BeornTheBold** [triplea-game/triplea#868]
This can be recreated as follows:
1. Assign ownership of a sea zone to the neutral player (e.g. <territoryOwner territory="Sea Zone 1 Hudson Bay" owner="Neutral"/>)
2. Place a neutral sea unit in the same zone that can fight (e.g. <unitPlacement unitType="pt_boat" territory="Sea Zone 1 Hudson Bay" quantity="1"/>)
3. Set the production value of the zone to something greater than zero (e.g. <attatchment name="territoryAttatchment" attatchTo="Sea Zone 1 Hudson Bay" javaClass="games.strategy.triplea.attatchments.TerritoryAttachment" type="territory">
                        <option name="production" value="5"/><option name="blockadeZone" value="true"/></attatchment>)
4. Start the game and "attack" the zone with a battle capable sea unit that can defeat the neutral unit.

If the game has never been saved, the sea zone will reflect ownership of the attacking player by placing his flag there, and the production value of the sea zone will be added into his income.  However, if the game is ever saved and relaunched, not only will subsequent "captures" of the space no longer affect income, the previous "captures" will no longer be in the player's income either.

**Comment by BeornTheBold** [comment]
For some reason the examples I gave did not post.
`<attatchment name="territoryAttatchment" attatchTo="Sea Zone 1 Hudson Bay" javaClass="games.strategy.triplea.attatchments.TerritoryAttachment" type="territory">
                        <option name="production" value="5"/><option name="blockadeZone" value="true"/></attatchment>`
`<territoryOwner territory="Sea Zone 1 Hudson Bay" owner="Neutral"/>`
`<unitPlacement unitType="pt_boat" territory="Sea Zone 1 Hudson Bay" quantity="1"/>`

**Comment by RoiEXLab** [comment]
@BeornTheBold Side note:
You can edit your post, when you are on your PC...

**Comment by BeornTheBold** [comment]
Also the Stats tab does not reflect the income from sea zones, even in a fresh game, though the income is received.

**Comment by DanVanAtta** [comment]
A new issue would be useful for the SZ income problem. @BeornTheBold , in that new issue for the SZ income, could you provide some more background/context to which maps have SZ income, or give us a link to one that potentially does? An XML snippet would also be useful.

**Comment by BeornTheBold** [comment]
Hi Dan,

The only completed map I am aware of that has sea zone income is the Napoleonic one where sea convoy spaces are used.  They only provide income for the original owner though, and when control is lost no one gets income from the sea zone.

I am working on a map where I’m trying to make control of the sea as important as control of the land.  It is a massive Free for all, and I want the sea zones to be treated similarly to land territories, so that the controlling nation receives the value assigned to the sea zone.

I have come up with a sort of work around, where I created a merchant ship, and using the national objective method a player receives bonus income for each territory that contains at least one of his merchant ships.  There are two downsides to this method though, one in that national objective income is not reported in the stats or economy tabs (making it hard to see what nations are actually ahead economically) and the second is that opposing merchant ships can coexist in a sea zone and both players receive income.

- Byron
