### ISSUE TITLE
Select Games and Download maps window Sizing

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#869]
#854 for some background

Immediate task is to address scroll bars on the download maps window and select games window. Ideally the code to control how large the overall window is will unified (effectively as if it were a library function of some sort)

These images courtesy of FrostionAAA  from #854 demonstrate the problem:

> Note that the long map location is treated like one word, and it is currently being pushed/forced down one line below the “Location:” text.
![selectagame](https://cloud.githubusercontent.com/assets/15268177/16200215/ac5ea6e6-370c-11e6-8811-884f0f8ea38f.png)

**Comment by RoiEXLab** [comment]
Small side note: This JEditorPane is fille with bad written html text... Maybe that's whats causing this issue...
(First the location and heading part has it's own html tag and then the notes folow with another html tag

**Comment by DanVanAtta** [comment]
This was done!
