### ISSUE TITLE
transport unloading behavior - bad defaults 

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#875]
From #553  Check on the below problem, and verify if it is still current. If not, then we should fix it.

> Setting - six transports with six infantry, three tanks, three artillery
(i.e. three transports have inf/art, three have inf/tank) loaded in them, ready to unload. You see this problem almost every game in revised with UK unloading units into Europe.

> 3) click a infantry and an arty and move them to the land. Gives you the menu box "What transports do you want to unload" , but default is take one art from an inf/art tranny and one inf from an inf/tank tranny. I guess this should be an option but certainly not the default.

**Comment by ron-murhammer** [comment]
@DanVanAtta This should already be resolved in #762
