### ISSUE TITLE
Hangs on Startup

### ISSUE THREAD

**Issue by RogerCooper** [triplea-game/triplea#8754]
### How can the problem be recreated?

Running 2.6.12, the TripleA icon appears on screen and then it hangs.
### If playing a prerelease, which version are you using?

Game Version:

### If playing a prerelease, does this happen on the latest release?

- [] yes
- [] no

**Comment by DanVanAtta** [comment]
I broke this last night, the prerelease version was updated and did not parse well. This will be fixed pretty soon: https://github.com/triplea-game/triplea/pull/8755

**Comment by RogerCooper** [comment]
The previous version was giving me problems as well, with errors on mods that I had just downloaded updates for, which I could only resolve by manually deleting the old folders.
