### ISSUE TITLE
Not all sounds are played in version 1.9 prerelease

### ISSUE THREAD

**Issue by FrostionAAA** [triplea-game/triplea#878]
There seems to be some sort of sound bug in the prerelease.

The short description of the issue:
“game_start” and “required_your_turn_series” sounds seems to play when starting maps and gaming, but other sounds like combat and land capture sounds do seldom play.

A longer description of the problem can be read on the development forum (On the forum I have finally verified that it is not only me who have noticed the missing sounds):
http://tripleadev.1671093.n2.nabble.com/Is-there-a-sound-bug-in-the-pre-release-v1-9-td7592719.html

**Comment by DanVanAtta** [comment]
#904 has a patch that fixes this. The default sound files were not playing, country specific ones should still be playing. After #904 is merged, all sound files should play as expected (assuming they are mp3 and also the map sound.properties file has updated file names)
