### ISSUE TITLE
Feature Request/Error: Please Fix That Planes Automatically Get Lost at Sea On Defending Carriers

### ISSUE THREAD

**Issue by MasonMediaKidvision** [triplea-game/triplea#8789]
Hi, it looks like every feature (as far as I can tell) of WWII Classic 3rd Edition matches the classic rules from the board game- with one exception (let me know if there are others!:):  In the "Classic" board game, fighters defending on a carrier can cross one territorial line to land on a friendly island or coastal land territory, if their carrier is sunk.  In TripleA, they seem to automatically die.  Can this be fixed anytime soon?  If not, are there reasons that it would be difficult to do so?  I would be happy to pass on issues/challenges to friends that know various programming languages.

Thank you so much, playing this game has been something to look forward to each week and has connected me to friends old and new, all over the US and even the world during Covid.  Much appreciated,
-Daniel:)

PS I may be able to produce videos and tutorials if there is a need.  Thanks Again:)

**Comment by beelee1** [comment]
Hi Mason

It looks as if it may be possible. You'd need to alter the xml. This is from Pact of Steel 2

placeNoAirCheck does everything normal 'place' does, except it does not kill any aircraft at the end of the turn (you can also use step properties to do this with the normal delegate)

I've never used this, so not exactly sure how it works, but you could try asking here also

https://forums.triplea-game.org/category/28/map-making

**Comment by Cernelius** [comment]
I guess you should **prove** the fact that in Classic 3rd Edition the intended rules are that defending fighters that cannot land on the same zone can land on a nearby zone, whereas they are always lost in Classic 2nd Edition (I'm not sure myself and I guess chances are that not many other persons are). On the matter, you should clarify whether or not the air you mention would be able to land also on a friendly carrier inside a narby sea zone.

A problem is that TripleA doesn't have a defined rules-set between the so-called v2 and the default (mostly but not all v1). I've advanced a proposal under which the rules-set of Classic 3rd Edition would be called "Second Rules Set".
https://forums.triplea-game.org/topic/2565/triplea-rules-sets

Uder that proposed classification, this rule you are mentioning should apply to all rules set from "2RS" onwards (so all of them but "1RS").

---

There are several, if not many, other differences between the arguably intended rules of Classic 2nd and 3rd Edition (I'm not talking about any optional one, which are a lot, an several of them missing).

**Comment by Cernelius** [comment]
>In the "Classic" board game, fighters defending on a carrier can cross one territorial line to land on a friendly island or coastal land territory, if their carrier is sunk. In TripleA, they seem to automatically die. Can this be fixed anytime soon? If not, are there reasons that it would be difficult to do so? I would be happy to pass on issues/challenges to friends that know various programming languages.

I don't know if there are any differences on this regard between the 2nd and 3rd Editions of Classic, but this statement is false as far as I know.

In the 2nd Edition of Classic, defending fighters can never land on any non-island coastal territories: they can only land on (their original or an other) carrier in the sea zone of the battle or on an island in the same sea zone (with island meaning a land zone which is entirely surrounded by only one sea zone).

What is being described is true from Europe, Pacific and Revised onwards.

I'm closing this issue as invalid. Please open an other one if you believe that there is indeed an issue or to clarify if you were referring only to Classic 3rd Edition rules, or else re-open this issue if you believe that I'm wrong.
