### ISSUE TITLE
v3 Fighter/Carrier rules do not work in different phase order

### ISSUE THREAD

**Issue by Navalland2** [triplea-game/triplea#8796]
Not sure if it is bug. Turn order in my game is Combat-NonCombat-Purchase-Place. Air units cannot be placed next to factory sea zones even if they are planned to be placed on carriers.

**Comment by DanVanAtta** [comment]
@Navalland2 can you post a sample of the map that has this with a save game at the point of error? Can you describe more precisely where you are trying to place an air unit, when you would expect them to be placed?

**Comment by Navalland2** [comment]
Sorry my fault. This topic can be closed.
