### ISSUE TITLE
view game statistics causes the map to revert to an older state, breaks history

### ISSUE THREAD

**Issue by doctored** [triplea-game/triplea#8825]
self-explanatory also causes this error:

https://github.com/triplea-game/triplea/issues/8183

[autosaveBeforeEndTurn.tsvg.zip](https://github.com/triplea-game/triplea/files/5945865/autosaveBeforeEndTurn.tsvg.zip)

Game Version: 2.5.22294

**Comment by Cernelius** [comment]
I confirm the behaviour for 270BC Wars. It's amazing that something that should be only for making statistics actually manages to change the game itself like a sort of broken "undo" feature for entire phases or rounds.

**Comment by doctored** [comment]
i've noticed also it always to revert the map exactly 1 round

**Comment by asvitkine** [comment]
I believe I fixed this by reworking the logic in 2.6.

**Comment by doctored** [comment]
yeah i've been checking it in my recent TWW game seemed like it was no longer happening thanks! :)
