### ISSUE TITLE
Ready to Add New Map

### ISSUE THREAD

**Issue by axisalliescontango** [triplea-game/triplea#8828]
I have a playable map that is ready to be shared with the TripleA community.  Please send me an invitation to join my own map team at triplea-maps.

https://github.com/axisalliescontango/young_grasshoppers_tournament_edition

**Comment by DanVanAtta** [comment]
Maps to be joined to triplea-maps neither need to be playable nor require a map admin team:
- maps in development are welcome
- github used to have different access policies that made map teams useful, no longer and instead permissions are granted directly without the team.

With that said, I forked the given repo into triplea-maps after a quick content review, please delete the original repo.
