### ISSUE TITLE
Windows to Mac issue

### ISSUE THREAD

**Issue by Thegoodcaptain** [triplea-game/triplea#8922]
My opponent is on a Mac and gets this error message when trying to open the file. Prevents us from playing by email or forum. Any fix for this? Many thanks.

![IMG_3600](https://user-images.githubusercontent.com/79759787/109393302-acf47080-78d5-11eb-8cba-68a909437d6a.PNG)

**Comment by Thegoodcaptain** [comment]
update: he got his turn going but then gets this error...
![IMG_3602](https://user-images.githubusercontent.com/79759787/109394025-b4b61400-78d9-11eb-8868-ff5457d004b6.PNG)

**Comment by beelee1** [comment]
yea idk what's going on with the unit error message. the game obviously has the image. I wonder if some triplea updates and or mac ones are causing it.

You could ask your opponent to switch to linux : )

**Comment by Thegoodcaptain** [comment]
Thanks. I don't know what that means but I will forward this comment to him. Much appresh.

**Comment by beelee1** [comment]
@Thegoodcaptain heh heh just a joke. Linux is a different OS same as windows and mac are

**Comment by Thegoodcaptain** [comment]
ah hell. hah. okay, thanks

**Comment by DanVanAtta** [comment]
The first error message posted just means that launching directly into a map is unsupported when double clicking a save game file.

The missing unit image error is odd. Does that happen for any map, or just classic?

**Comment by DanVanAtta** [comment]
Is the 'unsupported feature' error shown when launching from a save-game, or when selecting a save-game file from 'open save game'?
