### ISSUE TITLE
Jettison Headless Server UI?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#893]
AFAIK we are just logging in via command line to control headless (bot) servers. There is a UI feature that forks a lot of code, and could all potentially be dropped:

![class_that_drop_away](https://cloud.githubusercontent.com/assets/12397753/16371408/3a5a8472-3bfb-11e6-93b5-bbff2acd297e.png)

**Comment by DanVanAtta** [comment]
There is nobody really maintaining the bots these days.. I'm not sure if Bung was using this before, and if it was very useful. AFAIK bots we'll just launch and restart via CLI. I'm not sure why we need a control panel for it anymore.

@ron-murhammer , do you have any further context?

**Comment by DanVanAtta** [comment]
Here is how we launch a bot:
```
java -server -Xmx320m -Djava.awt.headless=true -classpath bin/triplea.jar games.strategy.engine.framework.headlessGameServer.HeadlessGameServer triplea.game.host.console=true triplea.game.host.ui=false triplea.game= triplea.server=true triplea.port=3402 triplea.lobby.host=XXX triplea.lobby.port=3303 triplea.name=Bot2_TripleAWarClub triplea.lobby.game.hostedBy=Bot2_TripleAWarClub triplea.lobby.game.supportEmail=XXX@hotmail.com triplea.lobby.game.comments="automated_host" triplea.lobby.game.reconnection=172800
```
The UI is turned off. So we don't need that. The console is turned on, but I suspect nobody is or knows how to use it.

**Comment by DanVanAtta** [comment]
Gathering some more usage info here:  http://www.tripleawarclub.org/modules/newbb/viewtopic.php?post_id=16930

**Comment by prastle** [comment]
Frankie9 runs all the bots now except private ones like cernel's and my own.  We rarely are having problems now.  His email is nuobodu9@gmail.com if you need more info.  He response very quickly generally when their is a problem.

**Comment by DanVanAtta** [comment]
AmericanKnight uses this feature. It is *the* way for interacting with the derby_db. We cannot remove this code until we provide an alternative to manage the mod list. Recently this feature broke as well, a ticket is open to repair or replace it.  

For follow up to what happens to this feature, see: https://github.com/triplea-game/triplea/issues/1352
