### ISSUE TITLE
ww2_oil_and_snow_1st_edition

### ISSUE THREAD

**Issue by merleyn** [triplea-game/triplea#8941]
Hello Triple A developers...

After spending half a year on my first TripleA-map... and disccusing it at the forum....

(  [https://forums.triplea-game.org/topic/2115/total-global-world-war-ii-fusion-clean-up-project/17?page=1](url) )
( [https://forums.triplea-game.org/topic/2592/global-wwii-oil-snow-project?_=1614545959986](url) )

.....I was trying to get it for evaluation and possible sharing in the Triple A community...

( for a newby as me it was really a hard time uploading it at Github even with the help and support files..
  a painstaking evening trying to solve this...  hoped it worked out well now... let me know )

anyway:
hereby my request if my map could be evaluated and added to the impressive Triple A
downloadable maps..

keep up the great work!!
Greeting from the lowlands...

**Comment by DanVanAtta** [comment]
Please upload your map to a github repository and send us a link. Let us know if you have any questions.

**Comment by merleyn** [comment]
https://github.com/merleyn/ww2_oil_and_snow_1st_edition
[https://avatars.githubusercontent.com/u/34524925?s=400&v=4]<https://github.com/merleyn/ww2_oil_and_snow_1st_edition>
merleyn/ww2_oil_and_snow_1st_edition<https://github.com/merleyn/ww2_oil_and_snow_1st_edition>
Contribute to merleyn/ww2_oil_and_snow_1st_edition development by creating an account on GitHub.
github.com


I am having hard time uploading th

________________________________
Van: Dan Van Atta <notifications@github.com>
Verzonden: zondag 28 februari 2021 22:34
Aan: triplea-game/triplea <triplea@noreply.github.com>
CC: wodamn_ebbe <el_ebbe@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [triplea-game/triplea] ww2_oil_and_snow_1st_edition (#8941)


Please upload your map to a github repository and send us a link. Let us know if you have any questions.

**Comment by merleyn** [comment]
or:  https://github.com/merleyn/ww2_oil_and_snow_1st_edition/tree/master/map
________________________________
Van: Dan Van Atta <notifications@github.com>
Verzonden: zondag 28 februari 2021 22:34
Aan: triplea-game/triplea <triplea@noreply.github.com>
CC: wodamn_ebbe <el_ebbe@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [triplea-game/triplea] ww2_oil_and_snow_1st_edition (#8941)


Please upload your map to a github repository and send us a link. Let us know if you have any questions.

**Comment by merleyn** [comment]
thanks for helping me out so far....     the map is visible now in the experimental list & downloadable too... but not possible to play as it seems nested twice in the same master folder giving this error:  _Could not find map: ww2_oil_and_snow_1st_edition Typically this will be because the map is not downloaded.  If you are *sure* you have the map, double check that the game XML can be found under one of the locations listed below and the 'mapName' XML attribute in the XML file has the correct name. Searched these locations: C:\Users\merlijn\Documents\triplea\downloadedMaps\ww2_oil_and_snow_1st_edition\map C:\Users\merlijn\Documents\triplea\downloadedMaps\ww2_oil_and_snow_1st_edition_   ANy idea how to solve that?  I lost track of where the map is now and forking and so...

**Comment by beelee1** [comment]
@merleyn yea it's a naming error. For some reason the zip and the folder inside the zip aren't the same. If you rename the zip by adding"_1st_edition" to the end of it it'll work

**Comment by beelee1** [comment]
Right on success !
