### ISSUE TITLE
Restricted Bombard Casualties Firing Back

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#8948]
### Reproduction Steps

1. open attached save game
2. click 'done' to end purchase turn
3. say 'yes' for units to bombard, battle will then auto-start
4. notice in the first round of combat that the defender fires back

Expected: defender should not fire back, bombard casualty should be removed immediately

### Attach a Save Game

[restricted-bombard-firing-back.tsvg.zip](https://github.com/triplea-game/triplea/files/6059818/restricted-bombard-firing-back.tsvg.zip)

### Engine Version

Engine Version:  2.6  @ e1cf9ee366c45830b9443c1ab5aeeadd70a82b88

**Comment by asvitkine** [comment]
I actually get an NPE with the above saved game. Will investigate.

**Comment by Cernelius** [comment]
For general information, this is also related to an old problem.

V1 (Classic) being the default for TripleA, naval bombard casualties should fire back as default (like if I make a map with no properties at all in the game XML file), whereas TripleA has naval bombard casualties fire back disallowed as default and a property for allowing them to fire back (which is the exact opposite of how it should be).

For general information, naval bombard casualties fire back in v1 as well as in all rule-sets from v3 onwards and do not fire back in v2 only.

**Comment by Cernelius** [comment]
> I actually get an NPE with the above saved game. Will investigate.

Same for me. I reported it here:
https://github.com/triplea-game/triplea/issues/11784
