### ISSUE TITLE
Multiple map.ymls, some with older format versions, preventing TripleA from starting.

### ISSUE THREAD

**Issue by tvleavitt** [triplea-game/triplea#8952]
![2021-03-01 18_17_16-New Issue · triplea-game_triplea - Avast Secure Browser](https://user-images.githubusercontent.com/4445057/109588045-f521b780-7abc-11eb-83c1-1cfa1e6befb8.png)

TripleA is cycling through these repeatedly, at least a half dozen maps or more. I've clicked ok 50+ times. Thus, I can't start TripleA. Looks like there are multiple map.ymls, some under maps folder (and dated 02/04) (as specified in the error message) and one in the "game" root directory. (dated today). Where are they supposed to be? I presume the most recent is the best.

C:\Users\Thomas Leavitt\triplea\downloadedMaps\greyhawk_wars-master\map

map_name: greyhawk_wars
games:
- {xml_path: games\Greyhawk_Wars.xml, name: Greyhawk Wars}
version: 0

Maybe multiple map.ymls are a side effect of my previously downloading an earlier release, and earlier versions aren't deleted? Looks like the file in maps is a duplicate of the one in the top level directory (which has the proper attributes).

Seems like the proper elements are in that one:

C:\Users\Thomas Leavitt\triplea\downloadedMaps\greyhawk_wars-master

map_name: greyhawk_wars-master
games:
- game_name: Greyhawk Wars
  file_name: Greyhawk_Wars.xml
version: 0

I'm going to try and manually remove the bogus versions.

**Comment by DanVanAtta** [comment]
You can remove all 'map.yml' files and the engine will regenerate them. It is meant to be a one-time generation to backfill already downloaded maps that do not have one. Otherwise yeah, the bogus ones simply need to be dropped.

**Comment by tvleavitt** [comment]
I deleted all the bogus versions, since the one in the top level directory seemed to be current and complete.
