### ISSUE TITLE
Show Player Info lobby command sometimes does not correctly list which games a player is in

### ISSUE THREAD

**Issue by zlefin** [triplea-game/triplea#8984]
### Reproduction Steps

Go to lobby.
Right-click on one of the players' names on the right edge of the screen
Select the option "Show Player Info"

For some players, it shows several games, including games the player is not in (verified by going into those games directly, and noting that player is not in it, and then re-checking show player info for that player).
It seems quite common, and is affecting a lot of the players who are online atm, I've observed it being common in the past as well.

By logging into the lobby a second time under a generic name (so I could see my own info with "show player info"), and running some tests, it appears that the list gets added to, but not removed from properly.  I made a note of what games were in the list for my regular account "zlefin", then I had that account start a new game in one of the bots that was not already on that list, on the map minimap.  Played a few rounds.  Then I used the other account to see the "zlefin" accounts Show Player info, and that new bot was now on the list.

I'm not sure what exactly "show player info" is supposed to do.  So I'm not sure if there are other errors with it.

### Engine Version

Engine Version:
2.5.22294

**Comment by DanVanAtta** [comment]
This should be fixed in 2.6 via: https://github.com/triplea-game/triplea/pull/8747
