### ISSUE TITLE
2.6.73 appear slow

### ISSUE THREAD

**Issue by TheDog-GH** [triplea-game/triplea#9001]
Testing 2.6.73 with my unpublished Settlers: War of the Lance (same as 2.6.39), the one with no enemy within 3-4 Territories.
A local game with 6AI, 2 Factions of 3 aside.

Speed

```
v 2.5.22294 43 40 44 40 45 44 45 mean = 43
v 2.6.73    60 65 63 62
```
Slower than 2.6.35

For reference here is the old version stats
v 2.6.35 55 51 46 49 48 45 47 mean ~ 49

DanVanAtta said
_For game play speed, 2.6.55 is seemingly the only thing that could have made a difference between *35 and the current. If you could check that version and the one preceding, that will narrow it down, but I don't readily see where the difference would come in._

**Comment by TheDog-GH** [comment]
Adding more data and adding values for v2.6.83 gives the following result.

So Im thinking park this lot and maybe look at the speed issues at the end of the publishing of the public 2.6 ?

As I am only doing a very simple test and it does not pin down the actual point of it being slow, but if I had to guess though it would be in the combat phase.
 
```
2.6.83   59 58 56 59 58 =58
2.6.73   60 65 63 62 60 =62
2.6.71   54 56 55 57 59 ~56
2.6.67   60 62 57 56 55 ~58
2.6.60   54 56 56 56 54 ~55
2.6.59   Input ==null
2.6.58   Input ==null
2.6.57   Input ==null
2.6.56   Input ==null
2.6.55   No Code to test
2.6.40   Input ==null

Old data
v 2.6.35    55 51 46 49 48 45 47 mean ~ 49
v 2.5.22294 43 40 44 40 45 44 45 mean = 43

```

**Comment by TheDog-GH** [comment]
Later versions than v2.6.35 & v2.5.22294 are slower, but are acceptable.  Speed will hopefully be addressed in the future.

**Comment by TheDog-GH** [comment]
Downloaded the latest version to compare it to the speed the speed tests before, sadly its still slow compared to 2.5.

2.6.410   63 65 65 65 66 ~65 seconds 

compared to v 2.5.22294 = 43

**Comment by TheDog-GH** [comment]
Some good news for a change.
Note this applies to version 2.6.477

2.6.477 50 50 47 54 47 ~ 50 seconds

**So back to 2.6.35 times.**

This improvement might be due to 2.6.472 if I understand it correctly, though Im not sure.

**Comment by DanVanAtta** [comment]
The update in 2.6.472 should be most notable when rendering the physical map. So simply scrolling around the map would exercise that update.

https://github.com/triplea-game/triplea/releases/tag/2.6.471 is more likely to have been the difference with:

> * (Possible performance gain): inject resource loader into map data and re-use existing resource loader for territory effect images

Creating a resource loader requires a scan of the installed maps, avoiding that each time we render a territory effect image should be an improvement there.
