### ISSUE TITLE
2.6.73 Cannot exit TripleA with just the AI playing

### ISSUE THREAD

**Issue by TheDog-GH** [triplea-game/triplea#9002]
Testing 2.6.73 with my unpublished Settlers: War of the Lance (same as 2.6.39), the one with no enemy within 3-4 Territories.
A local game with 6AI, 2 Factions of 3 aside.

I used to be able to press [x} top right to leave the game, with 6 AI playing each other. This no longer works, it hangs and I have to load Task Manager and end task.

I also tried File> Leave Game, that hangs
I also tried File> Exit Program, that hangs

DanVanAtta said
_Whenever the game engine freezes a stack trace is key. Launching TripleA from console (on windows) and following the steps here: https://access.redhat.com/solutions/19170 to obtain that._

**Comment by TheDog-GH** [comment]
As requested
[console.log](https://github.com/triplea-game/triplea/files/6097870/console.log)

20:03:24,567 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
20:03:24,567 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
20:03:24,567 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/C:/Program%20Files/TripleA-2.6.73/bin/triplea-game-headed-2.6.73@bd9e0f04d4.jar!/logback.xml]
20:03:24,583 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@4b741d6d - URL [jar:file:/C:/Program%20Files/TripleA-2.6.73/bin/triplea-game-headed-2.6.73@bd9e0f04d4.jar!/logback.xml] is not of type file
20:03:24,614 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
20:03:24,614 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [org.triplea.debug.Slf4jLogMessageUploader]
20:03:24,614 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [swingMessage]
20:03:24,614 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.FileAppender]
20:03:24,630 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
20:03:24,630 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
20:03:24,677 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@9:90 - no applicable action for [rollingPolicy], current ElementPath  is [[configuration][appender][rollingPolicy]]
20:03:24,677 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@11:30 - no applicable action for [fileNamePattern], current ElementPath  is [[configuration][appender][rollingPolicy][fileNamePattern]]
20:03:24,677 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@13:26 - no applicable action for [maxFileSize], current ElementPath  is [[configuration][appender][rollingPolicy][maxFileSize]]
20:03:24,677 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@14:25 - no applicable action for [maxHistory], current ElementPath  is [[configuration][appender][rollingPolicy][maxHistory]]
20:03:24,677 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@15:27 - no applicable action for [totalSizeCap], current ElementPath  is [[configuration][appender][rollingPolicy][totalSizeCap]]
20:03:24,677 |-INFO in ch.qos.logback.core.FileAppender[FILE] - File property is set to [C:\Users\RYZEN/triplea/triplea.log]
20:03:24,677 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
20:03:24,677 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [console]
20:03:24,677 |-WARN in ch.qos.logback.core.ConsoleAppender[console] - This appender no longer admits a layout as a sub-component, set an encoder instead.
20:03:24,677 |-WARN in ch.qos.logback.core.ConsoleAppender[console] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
20:03:24,677 |-WARN in ch.qos.logback.core.ConsoleAppender[console] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
20:03:24,692 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to DEBUG
20:03:24,692 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [swingMessage] to Logger[ROOT]
20:03:24,692 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [console] to Logger[ROOT]
20:03:24,692 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]
20:03:24,692 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.http] to INFO
20:03:24,692 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
20:03:24,692 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@2eae8e6e - Registering current configuration as safe fallback point

20:03:25.536 [main] INFO  o.t.game.client.HeadedGameRunner - Launching game, version: 2.6.73@bd9e0f04d4 
20:03:25.708 [Thread-4] DEBUG g.s.e.data.gameparser.GameParser - Parsing game XML: file:/C:/Users/RYZEN/triplea/downloadedMaps/settlers_age_of_tribes/games/settlers_age_of_tribes.xml

**Comment by DanVanAtta** [comment]
I believe I found the cause behind this issue. I don't think you even need to have an AI game, just try to exit.

FWIW, a thread dump / stack trace is not the same as the logs : )
Thank you though.
