### ISSUE TITLE
2.6.83 Still cannot exit TripleA without End Task

### ISSUE THREAD

**Issue by TheDog-GH** [triplea-game/triplea#9015]
Playing (single player v AI) or (AI v AI) it **now shows** the Dialog box Yes or No to Exit, but pressing
Yes or
File> Leave Game or
Exit Program

All hang/continue playing and will **not** exit, so must end task.

**Comment by DanVanAtta** [comment]
Thanks for checking & reporting this.

This will be fixed by: https://github.com/triplea-game/triplea/pull/9017
