### ISSUE TITLE
Cannot Download any Maps Into a Non-Default Folder Path (2.6.89)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#9027]
Although now the customization is not lost and the maps folder path is customized as `D:\Programs\TripleA\downloadedMaps`, if I try to download 270BC via the program, I get this:
![20210314_1](https://user-images.githubusercontent.com/19562310/111055929-084c6400-847b-11eb-80f3-05ed2a3582a7.png)

I have also tested it works fine on the default path, but I had to define it manually, as `C:\Users\001\triplea\downloadedMaps` (which I believe it is what would be the default), because of this problem:
https://github.com/triplea-game/triplea/issues/9026

**Comment by asvitkine** [comment]
@Cernelius is this still an issue?

**Comment by Cernelius** [comment]
I've just renamed and moved my "downloadedMaps" folder out of the way (so that it is as if I deleted it) and tried again with the latest pre-release (2.7.14825) by first customizing the `downloadedMaps` folder on the `D:\Programs\TripleA\downloadedMaps` path, then closing the program and thereafter downloading "270BC".

It appears to me that I have not experienced the problem.

When was this fixed? Was it fixed collaterally? It is strange that this issue has not been closed.

However, I'm seeing that the program still created a "downloadedMaps" folder in the default path. I guess that this folder is created either as soon as you launch TripleA or when you click on "Select Game" if it does not exist and you have not customized the path yet. I would argue that in my case this folder should not have been created: it should be created only upon clicking on "Download Maps" without having customized the path somewhere else beforehand.

I'll also point out that it is seriously limiting not to have the option to reset to default singularly. If I would want to go back to the default path, I cannot do it without resetting to default every other setting too. It would be nice to have a "Reset to Default" button for every setting.

**Comment by DanVanAtta** [comment]
I would suspect this was fixed some time ago, but maybe also recently too. 
The "DirectoryNotEmpty" means that the code was trying to delete a directory that was not empty.
The extraction code is a lot simpler (as of very recently) and deletes the target and temp directories cleanly now. Deleting the target directory is not ideal but a least evil of all other solutions.

 > It is strange that this issue has not been closed.

Not particularly. It can be tough to relate different issues to different problems. Or, it can be easy to be working through somewhere and then incidentally fix a problem.
