### ISSUE TITLE
RFC: Map Versioning Design 

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#9048]
Trying to design how we can avoid managing download version values per map. I by-hand updated a generated map.yml file for every map with the latest version. I managed to blow that work away thinking I needed to regenerate them all :grin: 

This triggered a realization that map.yml is better as a static file and not one that is updated so frequently. It was pitched to simply use modification time stamps to compare out of date or not. I'm thinking that is a nice way to go. It avoids the need for the previous system where a '.properties' file was created per map to track the version and nor do we need to track version in map.yml. 

To do out-of-date detection via file modification time stamps, please poke holes in this design:

- update map server to look at the timestamp of the latest SHA per map repository and store in maps_db
- when engine requests list of maps to download, add the latest SHA timestamp to the JSON payload
- after receiving the payload, engine compares the latest timestamp to the modification timestamp of the map folder
- maps with a last modification timestamp before the latest are considered out of date

**Comment by beelee1** [comment]
> ...I by-hand updated a generated map.yml file for every map with the latest version...

:+1:

**Comment by RoiEXLab** [comment]
Interesting idea. A couple of questions though.
What exactly do you mean with
> timestamp of the latest SHA

Are you referring to the timestamp of the latest commit?

> maps with a last modification timestamp before the latest are considered out of date

Good idea in theory. In practice we might need to add some buffer to avoid a scenario where a user downloads a map just when a new version is published so the users end up with the old version until a new version is published. Maybe only considering the timestamp with hourly accuracy  is good enough for this. No map should ever take longer than an hour to download. Or maybe double checking after downloading is a better approach, not sure.
