### ISSUE TITLE
Incorrect Statistics in the Battle Calculator

### ISSUE THREAD

**Issue by bkelly1984** [triplea-game/triplea#9049]
### Reproduction Steps
Run a simulation on the battle calculator.

### Engine Version
Java Version: 15.02
Engine Version: 2.6
Build: fa39cabff04a8ed4149f18762cb3b6e056274b73

### Is there anything else we should know?

Hail TripleA Gurus,

I've noticed the Battle Calculator is incorrectly calculating the "Ave. Defender Units Left", "Units Left If Def Won", "Ave. Attacker Units Left", and "Units Left If Att Won" fields in a "World War II Classic" game map. Below is an example with 10 attacking units vs 8 defending units.

![Figure 1](https://user-images.githubusercontent.com/24846405/111922576-383dcd80-8a60-11eb-9e7a-b937532b3805.png)

*Figure 1: Attacker average loss is .72 units?  Defender has ALL units left when victorious?  I don't think so!*

The problem appears to be in the MustFightBattle object that the calculator creates to simulate the fight. MustFightBattle.getRemainingAttackingUnits() (line 265) is called which creates a new Collection containing all the original units and then removes everything killed. The issue is that the killed parameter in MustFightBattle is always empty.

I am not certain where the killed parameter should be populated, but the bottom of cleanupKilledUnits() (line 617) seems about right. At the bottom of this method, I added:

`this.killed.addAll(killedUnits);`

And the battle calculator seems to be working much better now.

![Figure 2](https://user-images.githubusercontent.com/24846405/111922591-53104200-8a60-11eb-8063-abf577823c1b.png)

*Figure 2: Losing 5.21 units on average seems much more believable, as is 2/6 units should defender win.*

I'm new to the code, so I am not sure if there is a better place for this, if my change would incorrectly include transformed units, or if this is only a symptom of a more complicated evolution of the code. Hence, I leave it to the existing gurus to fix.

Thank you, please let me know if I can provide more information.

**Comment by DanVanAtta** [comment]
If you're comfortable submitting a PR for this update and to vet it further, please let us know. We'll be happy to give you any support needed to complete that process.
