### ISSUE TITLE
TotalWorldWar error on TripleA

### ISSUE THREAD

**Issue by malmessi** [triplea-game/triplea#9069]
Could not find step name:Germany submerge subs?  If this problem happens frequently and is something you cannot fix, please report it to TripleA

**Comment by beelee1** [comment]
@malmessi What triplea version are you using and what OS are you on ? Also can you attach a saved game showing the error ?

**Comment by malmessi** [comment]
Hello

TripleA 2.5.22294

java 11.0.6

Map TotalWorldWar December 1941  2.8

Map Version 2.8.0

OS Win 8 Pro (6.3)

**Comment by beelee1** [comment]
hmm...2.5 is the stable release and TWW been around a long time. Any chance you can attach a saved game showing the error ? Or the steps to recreate it ?

**Comment by malmessi** [comment]
Yes, it is attached.

The error is not visible in the Show History, so I sent a map BEFORE CM, you need to open and click DONE on the CM list, then you have to be patient and play many times until defending sub rolls for a 1 (over 12!!) getting a hit before Usa can roll...

PS I had IMPROVED DESTROYER with Usa so defending sub firing first and killing me is another error I think....

Please see JPG image too....

**Comment by beelee1** [comment]
Sadly I can't access the save. Can you take the save from your saved games and put it in a zip file and upload it ? I tried putting the folder into a zip but that didn't work either. It needs the .tsvg thingy at the end and renaming it didn't work.

I think if you compress to zip from your saved games folder it'll work though. Maybe :)

**Comment by malmessi** [comment]
Zipped.

When you say "an you take the save from your saved games and put it in a zip file and upload it ?" do you mean I have tu use github or an attachemnet is ok if Zipped ?

**Comment by beelee1** [comment]
yea so this is my savedGames folder

![Screenshot from 2021-03-30 02-10-49](https://user-images.githubusercontent.com/24382682/112948112-43969600-90fd-11eb-995c-34ca24218e29.png)


I compress the G 40 Hrs 2.672 into a zip file so it can be uploaded to git. 

[G 40 Hrs 2.672.zip](https://github.com/triplea-game/triplea/files/6227067/G.40.Hrs.2.672.zip)

Then I can open the zip and put it in my savedGames. 

It's the only way I know  how to do it. It needs the .tsvg at the end. Renaming didn't work for me.

**Comment by malmessi** [comment]
[Test.zip](https://github.com/triplea-game/triplea/files/6227607/Test.zip)

**Comment by malmessi** [comment]
Zip uploaded

**Comment by beelee1** [comment]
right on the Test zip worked for me. Yea not a whole lot of info on the error. All it shows is

![Screenshot from 2021-03-30 17-18-40](https://user-images.githubusercontent.com/24382682/113064438-9bc0ad00-917c-11eb-98f2-36e7b883333a.png)
 
and

![Screenshot from 2021-03-30 17-20-46](https://user-images.githubusercontent.com/24382682/113064465-a8450580-917c-11eb-89b0-64b626d246db.png)

unfortunately I'm not sure what's going on. Looks as if you can just ignore it and keep playing though.

**Comment by beelee1** [comment]
Yea that's a bummer. You might mention it here https://forums.triplea-game.org/topic/1181/total-world-war-december-1941-3-0-0-6/626 I haven't seen hepps around a lot lately but it'll probably come to his attention sooner or later.

**Comment by trevan** [comment]
I know why this is happening and am working on a fix.

**Comment by trevan** [comment]
The reason why the sub is still firing first even with "Improved Destroyers", is because all subs have a "Substrike" AA attack.  This attack is never negated by Improved Destroyers.  It is 2/12 chance of hitting but is only used for the first round.  The normal sub attack is not a first strike and is happening after the usa player fires.
