### ISSUE TITLE
Moving onto a new Java Version

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#9118]
Java 16 was released a couple of weeks ago and early development of Java 17 is about to start soon.

Which raises the question if we should plan to use a newer version of the JDK at some point.

For Oracle JDKs they provided a roadmap where JDK 17 is going to be an LTS release again:
https://www.oracle.com/java/technologies/java-se-support-roadmap.html

We're only using the AdoptOpenJDK distribution so we probably shouldn't rely too much on this schedule. However the newer versions provide many new features we might be interested in. Most notably "Records" which finally allow to quickly define "data classes" in java without all of the required boilerplate code.
It's not as fine-grained and feature-rich as lombok, but it might allow us to reduce our dependency on lombok a little bit with the nice side-effect that we are potentially running less frequently into compatibility issues with lombok and error-prone.

Thoughts?

**Comment by RoiEXLab** [comment]
Perhaps noteworthy: We're currently not compile-time compatible with JDK 16 but the challenges seem pretty minor, mostly due some minor changes to the standard library.

Also I tried out the new jpackage tool to create an installer from a JAR file. The installer feels nice and is easy to use for simple installations but the feature set is rather small but sufficient for most cases

**Comment by DanVanAtta** [comment]
We agreed we would stick to LTS versions. I suppose we can re-evaluate that choice, though I think there are larger factors to consider. Generally our focus should be:
- getting the maps server done and 2.6 stable and launched
- remove all bots and bot code by converting all network code to websocket and using the network relay to replace game server.
- change how save games are done to be a text encoded list of game change deltas

For 'record' objects, IMO they look good. I think TripleA has a biggest problem where almost nothing is modeled as an object. We have just lots of methods and data that is passed around but not a lot of encapsulation and in other cases where there are objects, so much is tacked on that they have little consistency. For example, a "MapFolder" object came up and would be a good candidate to have methods like "getPolygonsFile()", "getGameXmlFiles()", "getSoundFiles()", "getUnitImages()", etc.. and generally any/all methods to control how map folder system access is done. Hence, I don't think more value objects are largely what we need per-say, less data being passed around and encapsulated would help avoid having so much procedural logic and so many different call paths (and generally very little real encapsulation).

When it comes to replacing the installer, let's do that if it makes sense, but the focus I do think needs to be on the 3 areas mentioned above.

With regards to lombok and error-prone, error-prone like many other google products does have issues with working all the time, keeping compatibility. For example Guava constantly had breaking changes, even the google-java-formatter they are two versions of eclipse behind. Error-prone I'm sure works really well for the internal google projects, as an open-source tool it has a number of problems. To that extent I sometimes question the value-add of error-prone.

Bottom-line, I think waiting for java 17 to be truly LTS is our default decision, let's be sure it works with all tooling and avoid making a cutting-edge change to as soon as it's available to avoid having to deal with conflicts and any other issues with existing tooling. Overall the next priorities are: 2.6, removing bots, fixing save games.
