### ISSUE TITLE
v2.6.118 Economic Victory dialog box appears, pressing Yes to continue, the dialog box disappears, but the game does not continue

### ISSUE THREAD

**Issue by TheDog-GH** [triplea-game/triplea#9119]
When playing Settlers: Age of Tribes, one of my games, and the Economic Victory dialog box appears, pressing Yes to continue, the dialog box disappears, but the game does not continue. 

This also happens in 2.6.127

**I think this is related**
https://github.com/triplea-game/triplea/issues/9020

it says
@bkelly1984  commented 5 days ago
This is a problem caused by attempting to create a JOptionPane from outside a Swing event thread in EventThreadJOptionPane.showConfirmDialog. Some work was done to render some components within SwingUtilities.invokeLater, but I am guessing Swing in the newer versions of the JVM are less tolerant.

I'll rewrite the method and try my hand at submitting a pull request.

**Comment by bkelly1984** [comment]
Hey TheDog-GH, this is related insomuch that I may have revealed something that was previously broken. What's going on is that the buttons are reversed. "Yes" ends the game while "No" continues.

Here's the code from EndRoundDelegate.signalGameOver(), starting at line 336:

```
        stopGame =
            EventThreadJOptionPane.showConfirmDialog(
                null,
                "<html>" + displayMessage + "</html>",
                "Continue Game?  (" + title + ")",
                ConfirmDialogType.YES_NO);
```

So if pressing "Yes" to the "Continue Game?" dialog sets stopGame to TRUE. Hence, the game stops. I checked with bombardment, another non-Swing thread that opens a ConfirmationDialog, and confirmed that it expects "Yes" to return TRUE. So, I expect this has been backward for a while.

It's not a hard fix. Just add a "!" before the call. I can post another fix when I have time.

**Comment by bkelly1984** [comment]
@TheDog-GH This should be fixed. Dan rolled in the change. Give a shout if it isn't.
