### ISSUE TITLE
Broken link in the github read me development doc

### ISSUE THREAD

**Issue by jsarles-code** [triplea-game/triplea#9279]
https://github.com/triplea-game/triplea/blob/master/docs/development/README.md 

https://github.com/triplea-game/triplea/blob/master/docs/development/ide-setup

this leads to a broken page. 
Thanks,

**Comment by beelee1** [comment]
This one has some info

https://github.com/triplea-game/triplea/tree/master/docs/development/how-to/ide-setup

**Comment by jsarles-code** [comment]
Thanks!

**Comment by butterw** [comment]
I have a problem when setting up checkstyle in intellij IDEA according to the docs/development/how-to/ide-setup guide:
- When I add checkstyle.xml to the project, I get prompted for the samedir property
- I tried entering:  configFile.parent which does allow me to add Checkstyle.  
But I get the warning: The Checkstyle suppression filter file was not found and will be ignored

- Should the latest available Checkstyle version be used. It seems to only load it if I set to 8.8.  
- How to load suppression.xml from the same directory ?

**Comment by beelee1** [comment]
we'll ask @RoiEXLab

**Comment by RoiEXLab** [comment]
We use 'spotless' for formatting so you can just run the gradle task 'spotlessApplyJava' to format javacode properly

**Comment by DanVanAtta** [comment]
Our checkstyle config is dated, you need to use version 8.24 IIRC (probably not the right one, it's a lingering area of technical debt for us to fix that).

**Comment by DanVanAtta** [comment]
Links on the development README page are now fixed. The page has been significantly updated as well and hopefully is both more concise and easier to follow now.
