### ISSUE TITLE
Version 2.6.213 takes 301 seconds to load

### ISSUE THREAD

**Issue by TheDog-GH** [triplea-game/triplea#9301]
I have just upgraded from 2.6.203 to 2.6.213.  

From a double click to load TripleA, to a menu I get;
2.6.203 takes 10 seconds
2.6.213 takes 301 seconds

No error messages, but I guess it is checking for something?
All my maps have been already been unzipped, so its not that.
Running it a second and third time did not it make it load any faster.

**Comment by DanVanAtta** [comment]
Is that timing consistent?

**Comment by TheDog-GH** [comment]
2.6.213  just ran it 3 more times and the load time is about 10 seconds, I cannot reproduce it.

Good news for you and bad news for me, I must be going mad :-/

**Comment by DanVanAtta** [comment]
Not quite, not being able to reproduce does not mean the issue is gone. The out-of-date maps check is configured to only run so often. Chances are good the out-of-date check coincided with installing the newer version.

**Comment by TheDog-GH** [comment]
Perhaps is should say what it is doing, with something to show it is working on it?

As currently it says nothing and appears to have crashed, ie. has stalled.
