### ISSUE TITLE
Migrate to JUnit 5 (Lambda)

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#935]
2 Days ago a stable version of [JUnit 5 was released](https://github.com/junit-team/junit5/releases).
We might should take a look at it, since it looks promising.
Found [this](https://github.com/junit-team/junit5-samples/blob/r5.0.0-M1/junit5-gradle-consumer/README.md), could come in handy...

**Comment by DanVanAtta** [comment]
No reason to not start using Junit5 where it is helpful. It'll be interesting to learn more about it. I assume that we can migrate one test class at a time. In that case where you would like to apply it, add the imports and update or add a test. It'll then be an ongoing task to update test code to be cleaner and use newer technologies.

**Comment by RoiEXLab** [comment]
@DanVanAtta I'd like to keep this open until all Tests are using the JUnit 5 API

**Comment by DanVanAtta** [comment]
@RoiEXLab , IMO we should close this. It is not immediately actionable. Tickets should be actionable, otherwise, all things being equal, should be closed.

I don't think there is any disagreement to move to Junit 5 as it makes sense, and and we have enabled the Junit 5 runner.
