### ISSUE TITLE
Game Notes display isn't readable

### ISSUE THREAD

**Issue by butterw** [triplea-game/triplea#9350]
Issue: black text is forced on Notes display, making the text very difficult to read on dark background look and feel.

The issue is present in v2.6pre and v2.5 and is caused by the line: 
`gameNotesPane.setForeground(Color.BLACK);` which forces the text color to black 
This is done in the Game Notes and the map selector display and doesn't seem to be required.
  
![How it looks](https://raw.githubusercontent.com/butterw/ui/7c5acf90d63bde3b0d5d89c61084d88a3b12c69f/assets/GameNotesMenu_dark%20LookandFeel-dark%20text_Readabilitybug.png)
![vs How it should look (setForeground removed)](https://raw.githubusercontent.com/butterw/ui/7c5acf90d63bde3b0d5d89c61084d88a3b12c69f/assets/GameNotesMenu-dark%20LookandFeel.png)

### Reproduction Steps

- set triplea to a Substance look and feel with a dark background.
- open Help > games notes or map selector on a map with basic notes (ex: ww2_v6 map)

### Is there anything else we should know?
The issue was discussed in this [thread](https://forums.triplea-game.org/topic/2810/fontsize-and-dpi-scaling?page=1):
- There is an issue is related to high-Dpi scaling (images are blurry with it enabled (default), disabling it makes text too small, which is a problem in particular for the notes display).
- Another issue is that (multiple instances of) games notes can get hidden behind the map if the dialog isn't closed.

**Comment by asvitkine** [comment]
The background color issue has been fixed by https://github.com/triplea-game/triplea/commit/2ff89e6dafb8fb0c43df45674965298be6e2d64f
