### ISSUE TITLE
Link to IDE Setup in Developer Documentation 404s

### ISSUE THREAD

**Issue by tvleavitt** [triplea-game/triplea#9372]
The Developer Setup Guide docs file
https://github.com/triplea-game/triplea/tree/master/docs/development
has a link to "setup plugins and formatter" that is bad
https://github.com/triplea-game/triplea/blob/master/docs/development/ide-setup

This is among the first things seen, so it seems important to have working.

**Comment by butterw** [comment]
See https://github.com/triplea-game/triplea/issues/9279
