### ISSUE TITLE
1.9.0.0 release!

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#941]
Let's begin the release process! Is everything in that we would want for the 1.9.0.0 release? What would we want to include?

Current 1.9.0.0 release nominee: version 1.9.0.0.2461 

I started this source forge thread to let folks know about the prerelease: http://tripleadev.1671093.n2.nabble.com/TripleA-1-9-0-0-Prerelease-td7592899.html

My thoughts are we will spend a week or two testing, and if anything needs fixing we will roll forward. Ideally this will not involve any delays or pauses in normal development, but items which are fixes for 1.9.0.0 will get priority over regular/normal PRs. Once we are happy with things, we'll begin the process of migrating folks over.

As is, we need to determine how to migrate Derby DB data as well to a new lobby instance, I'm not sure right now how to do that.  Otherwise let's use this thread to discuss the next release, process and progress.

**Comment by DanVanAtta** [comment]
Once all the 1.9 labelled PRs are merged, I think we will really be ready to release: https://github.com/triplea-game/triplea/pulls?q=is%3Apr+is%3Aopen+label%3A%22Include+with+1.9+release%22

**Comment by ZjelcoP** [comment]
Good job on the progress, looking forward to the release! Major improvements!
Would you be so kind to update the Tutorial to the latest version (May22nd) as I had made some minor corrections, mostly graphic.

Cheers!

**Comment by DanVanAtta** [comment]
@ZjelcoP  - it's been updated to 0.75 (latest)
For future reference, this is the file that has the download URL: https://github.com/triplea-game/triplea/blob/master/.travis.yml

(recall, tutorial is special being the only bundled map that we have for the game)

**Comment by ron-murhammer** [comment]
Only major open issue that I'm aware of is #999

**Comment by ron-murhammer** [comment]
I think we are looking pretty good now. No major outstanding issues. Hopefully after a week or 2 we should be good to release.

**Comment by DanVanAtta** [comment]
Current TODO list:
- We need to fix the descriptions in the settings window
- Determine how bots pick up maps, I can launch a bot, but having trouble getting it to load a specific map folder
- Additional 1.9 testing..

**Comment by simon33-2** [comment]
If the fix for the balanced mod new map fix works, I think this will be a release that people would be champing at the bit for. I really like the improvements but I don't think that one can be omitted.

Otherwise, is there anything prevent this being generally available?

**Comment by DanVanAtta** [comment]
We need to get the 1.9 bots up. It's been tricky to configure them with a new maps folder, this code update should allow us to get them up and running: https://github.com/triplea-game/triplea/pull/1046

Cernel has suggested some last minute name changes/corrections. Hopefully we can get those in and the testing will not take too much longer. Otherwise we still need testing, people to continue playing 1.9 and report any problems.

**Comment by RoiEXLab** [comment]
@DanVanAtta Before releasing we wanted to refactor/rename all of the packages as discussed in #763 right?
Just mentioning before we forget

**Comment by DanVanAtta** [comment]
Renaming variables could make sense.
Package rename/re-org can happen after/anytime, merge-conflicts IMO are largest concern there.

**Comment by DanVanAtta** [comment]
http://www.triplea-game.org/download/    << 1.9 DL!
