### ISSUE TITLE
Typo should read Defensive not as as at the bottom of the map 'Defencive Agent'

### ISSUE THREAD

**Issue by BCS-DSO** [triplea-game/triplea#9461]

**Comment by BCS-DSO** [comment]
typo Defensive, not witha c thanks for a new game, roman roads aka railways should give the legion +1 not just 2 all the time.

**Comment by beelee1** [comment]
@BCS-DSO what map is this ? Do you know who made it ?

**Comment by BCS-DSO** [comment]
2.6.294 first punic war the latest experimental map on latest prerelease under an ubuntu variant though mouse just locked up. suggestion was to add roman roads aka railroad

**Comment by beelee1** [comment]
right on yea this appears to be and old abandoned map. doesn't have any game notes. So probably won't get changed unless somebody wants to take it on. You could try asking at the triplea site if anybody knows anything about it.

https://forums.triplea-game.org/
