### ISSUE TITLE
Inconsistent Pop-up treatment

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#957]
> There seems to be inconsistencies when it comes to popup names. Some have names identical to what the player has just pressed, some have different titles, some have no titles, some have TripleA icons, some have Java icons, and some have no icons. I would propose that a general rule of window appearance should be names that are consistent with what the player clicked and perhaps showing TripleA icons, leaving everything Java or error related showing java icons. 

From: http://tripleadev.1671093.n2.nabble.com/Requesting-game-menu-cleanup-of-names-icons-descriptions-tp7592876.html

**Comment by FrostionAAA** [comment]
I can give some examples of how the inconsistencies appear (in version 1.9.0.0.2471):

Help -> Unit help… -> (Opens a window with no title and with Java icon)
![helpunithelp](https://cloud.githubusercontent.com/assets/15268177/16798311/c0fbea64-48eb-11e6-96f5-7d1ff8b13959.png)

Help -> Movement/Selection help… (Opens a window named something else, with title but no icon)
![helpmovementselectionhelp](https://cloud.githubusercontent.com/assets/15268177/16798323/c810269e-48eb-11e6-9570-44e8c5be4586.png)

File -> Save… (Opens a window with title and with TripleA icon)
![filesave](https://cloud.githubusercontent.com/assets/15268177/16798326/cb705e12-48eb-11e6-82b8-e89481e40e9c.png)

I would say that the save example is a good example of how it should look like.
