### ISSUE TITLE
New Triplea Account Unable to Create Topics or Post

### ISSUE THREAD

**Issue by Board3659** [triplea-game/triplea#9591]
For some reason I can't comment or reply in the triple-A forum

**Comment by beelee1** [comment]
@DanVanAtta you got time to take a quick look ? He opened his account 29 days ago and is trying to make a map. says "No privileges" for some reason

**Comment by panther2** [comment]
@Board3659 

See https://www.axisandallies.org/forums/post/1546161
for a maybe first aid....
