### ISSUE TITLE
Slow Loading of Data in the Battle-Calculator (2.5.22294)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#9635]
The battle-calculator takes about 6 seconds to load data in "270BC Wars".

### Reproduction Steps
1. Download "270bc_wars".
2. Start "270BC Wars".
3. Open the battle-calculator.
4. Wait until you can "Calculate Odds".

### Is there anything else we should know?
I've tested on a new version of the game (which is to be released soon), but the version currently available has about the same issue.
A few seconds might seem like not a big deal, but it is quite bothersome when you want to make several simulations. Moreover, it might be many seconds for users in weak terminals and I suspect the battle-calculator might fail to work for some users. A few hours ago I had this conversation, confirming the problem for other users (and I had several similar conversations in the past):
![20210916_01](https://user-images.githubusercontent.com/19562310/133524017-c8dd1d71-d514-4dc1-b30b-36cadab60566.png)

Moreover, I intend to make and release other even heavier games, for which this problem is likely to be even more serious.

**Comment by asvitkine** [comment]
Fixed in 2.6.
