### ISSUE TITLE
Increase Xmx and Xms to 3072M for All 64bit Releases (2.5.22294)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#9654]
I request changing the first two lines of the `TripleA.vmoptions` file to:
```
-Xmx3072M
-Xms3072M
```

This change should be applied at least to the "windows-64bit" release and should not be applied to the "windows-32bit" one. I don't know if it should be applied to other releases.

The reason for the change is that the current default appears to be too low to properly support the "270BC Wars" game, giving errors when it is not enough, and may even cause the game to freeze indefinitely.

I think this change should cause virtually no problems, as I surmise that virtually everyone who is using a 64 bit system is likely to have 4G or more of memory (and, in any case, the 32 bit version is still available for download, for anyone having less than 4G of RAM).

I had several occurrences which seemed to show the default `Xmx` being too low. Here are all the relevant chat-log excerpts from the last of these cases, which happened yesterday (meaning a few hours ago, for me).

My host:
>(23:39:00) Pug:  3rd heap space error
(23:39:00) Cernel:  when did you have the error?
(23:39:00) Pug:  when trying to move something
(23:39:00) Cernel:  if you want, I can tell you how to increase the RAM assigne to TripleA
(23:39:00) Cernel:  but to make it effective you need to restart triplea
(23:39:00) Cernel:  np here, you want that?
(23:39:00) Cernel:  default is 2G, but it can be increased
(23:39:00) Cernel:  I've it at 4G

Thence the lobby:
>(23:34:20) Pug:  cernel, frozen. What are your parameters? 4096?
(23:34:25) Pug:  You were slapped by Pug
AA_Adam has joined
ToughOmbre has joined
AA_Adam has left
(23:35:58) RommelsAsparagus:  ..
(23:36:18) Cernel:  ah
(23:36:34) Cernel:  for some reasons I didn't hear the slap
Cernel slapped Pug
(23:36:56) Cernel:  so I tell you here how to increase the memory for TripleA
(23:37:05) Cernel:  open your TripleA folder in Programs
(23:37:09) Pug:  ok ... TripleA.vmoptions ... which are your parameters? 4096?
(23:37:31) Cernel:  this is what I have set:
(23:37:33) Cernel:  -Xmx4096M -Xms4096M -Xss2048K 
(23:37:43) Pug:  ok, will try the same
(23:37:57) Cernel:  but you need to close all TripleA instances and rejoin the lobby
Pug has left
(23:38:05) Cernel:  to make the changes effective
Pug has joined

Thence my host again:
>(23:39:00) Pug:  ok, let's hope it works
(23:39:27) Pug:  too many graphics or why does it happen? never had it before on another map
(23:40:19) Cernel:  this is the heaviest game in TripleA by far, as a matter of the dimension of the game file
...
(23:53:16) Cernel:  but can you give me more information about when the error for hitting the maxium memory was happening before? was there a pattern? was it happening under some situations?
(23:53:54) Pug:  with Egypt it happened all the time I clicked on a unit to move
(23:54:21) Cernel:  ok, and then eventually the game froze completely on that same turn
(23:54:46) Cernel:  so it's just like the RAM assigned kept going up until it needed to go up further and couldn't any longer
(23:55:05) Pug:  looks like Selaucia can hold for long if Egypt puts no real pressure on Syria
(23:55:14) Cernel:  can you open your task manager and tell me how much RAM the process is currently using for you?
Wassmuss has joined
(23:55:43) Cernel:  yes, it is very important to pressure Syria a lot to avoid Syria doing Seleucia factory safely
(23:55:53) Pug:  4.6M for jdk
(23:56:05) Cernel:  and also the current weakness of Greece means that Syria doesn't have to invest much in Anatolia
(23:56:19) Cernel:  you mean 4.6G?
(23:56:25) Pug:  yes
(23:56:31) Cernel:  oh that a lot
(23:56:43) Cernel:  it means you are hitting even the new maximum at 4G you just set
(23:56:55) Cernel:  let me se how much it is for me
(23:56:59) Pug:  yes, already was slow once
(23:57:18) Pug:  @wassmuss: lost with France on Napoleonic
(23:57:27) Cernel:  3.1G for me
(23:57:42) Pug:  interesting. Why less?
(23:57:43) Cernel:  so it is curious that the hosted person is using more RAM than the one hosting (that is me)
(23:57:55) Cernel:  I don't know
(23:58:08) Wassmuss:  @against which player?
(23:58:10) Cernel:  with this game, the RAM used is usually around 3G for me
(23:58:17) Pug:  TheWasp
(23:58:21) Cernel:  also when I play on local
(23:58:43) Cernel:  and I believe it works with the default limit at 2G, but I see this is not the case for you
(23:58:54) Pug:  32bit or 64bit java for you?
(23:59:08) Cernel:  64bit of course
(23:59:35) Cernel:  32bit can never exceed 2G for a single process, and proctically they can get not much more than 1G

**Comment by Cernelius** [comment]
After I made my opponent increase the `Xmx` to 4096M, we played on for about 1 hour, reaching round 3, and didn't have any issues, whereas beforehand he/she reported errors and we crashed on the very first round of the game.

I would label this problem as "Major" if it would happen to a game which I believe is popular (but "270BC Wars" is certainly not).

**Comment by DanVanAtta** [comment]
> Are you sure the program doesn't have a default setting which is used (just like in the case you have that value) if you have nothing specified in "vmoptions"?

Mostly, the JVM does a computation to determine min, starting, and max memory if not specified. Specifying those values overrides any defaults chosen by the JVM. Generally it is advised to let the JVM compute these values.

> Are you sure that the proposed 3GB would be problematic for systems having 4GB?

It might not be, it could. It certainly would be a problem for systems with less than 3GB available or even total memory (eg: 2GB systems).

**Comment by Cernelius** [comment]
Here it is yet an other example (This was until a few minutes ago, and I was privately hosting in the lobby.):
>(2021-12-15 1:4 (GMT+1)) JackariahHooch: I've noticed battle calc crashes me a lot for some reason
(2021-12-15 1:4 (GMT+1)) Cernel: have you increased the ram?
(2021-12-15 1:5 (GMT+1)) JackariahHooch: my ram is good
(2021-12-15 1:5 (GMT+1)) Cernel: I mean the ram assigned to triplea in the vmoptions
(2021-12-15 1:5 (GMT+1)) JackariahHooch: oh I see, no I haven't
(2021-12-15 1:6 (GMT+1)) JackariahHooch: what's vmoptions?
(2021-12-15 1:6 (GMT+1)) Cernel: it's where you have installed triplea
(2021-12-15 1:6 (GMT+1)) Cernel: it's a file called TripleA.vmoptions
(2021-12-15 1:7 (GMT+1)) Cernel: try to change the first two lines to:
(2021-12-15 1:7 (GMT+1)) Cernel: -Xmx4096M -Xms4096M
...
(2021-12-15 1:23 (GMT+1)) Cernel: did it crash because of battlecalculating?
(2021-12-15 1:23 (GMT+1)) Cernel: have you changed the ram now?
(2021-12-15 1:23 (GMT+1)) JackariahHooch: can't find the folder you were talking about
(2021-12-15 1:23 (GMT+1)) JackariahHooch: and yes
(2021-12-15 1:24 (GMT+1)) Cernel: it is usually in "programs"
(2021-12-15 1:24 (GMT+1)) Cernel: programs/TripleA
(2021-12-15 1:24 (GMT+1)) JackariahHooch: found it
(2021-12-15 1:24 (GMT+1)) JackariahHooch: I don't have an app that I can open file with
(2021-12-15 1:24 (GMT+1)) Cernel: right click an open it with a text editor
(2021-12-15 1:25 (GMT+1)) JackariahHooch: won't let me
(2021-12-15 1:25 (GMT+1)) Cernel: ah
(2021-12-15 1:25 (GMT+1)) JackariahHooch: it's not a txt file, it's a vmoptions file
(2021-12-15 1:25 (GMT+1)) Cernel: probably you don't have enough priviledged assigned to change files in there
(2021-12-15 1:25 (GMT+1)) JackariahHooch: "open with" just tells me I need to download an app
(2021-12-15 1:25 (GMT+1)) Cernel: yeah but it can be modified with a text editor, even notepad
(2021-12-15 1:26 (GMT+1)) JackariahHooch: How do I open it in notepad?
(2021-12-15 1:26 (GMT+1)) Cernel: well if you double click on it, when it tells you that you don't have the program to open it, it should offer you alternatives
(2021-12-15 1:27 (GMT+1)) JackariahHooch: it doesn't
(2021-12-15 1:27 (GMT+1)) Cernel: I assume one of these is going to be a text editor
(2021-12-15 1:27 (GMT+1)) Cernel: are you on what system
(2021-12-15 1:27 (GMT+1)) Cernel: I only know windows
(2021-12-15 1:27 (GMT+1)) JackariahHooch: yeah I'm on W10
(2021-12-15 1:27 (GMT+1)) JackariahHooch: I can't post screenshots here or I'd show you what I'm looking at
(2021-12-15 1:28 (GMT+1)) Cernel: you have to click on a thing that allows you to select an other app
(2021-12-15 1:28 (GMT+1)) JackariahHooch: yeah you right click and hit "open with", right? is that what you mean?
(2021-12-15 1:28 (GMT+1)) JackariahHooch: and it usually gives you a list of apps
(2021-12-15 1:29 (GMT+1)) Cernel: yes and there you should have the option to select an other app under the option to open the microsoft store
(2021-12-15 1:29 (GMT+1)) JackariahHooch:  it's not there, just the windows store
(2021-12-15 1:29 (GMT+1)) Cernel: weird
(2021-12-15 1:29 (GMT+1)) JackariahHooch: nvm, found it
(2021-12-15 1:30 (GMT+1)) Cernel: right, it's small
(2021-12-15 1:30 (GMT+1)) JackariahHooch: so now I'm looking at
(2021-12-15 1:30 (GMT+1)) JackariahHooch: -Xmx2048M -Xms2048M -Xss1250K 
(2021-12-15 1:30 (GMT+1)) JackariahHooch: thanks for helping btw
(2021-12-15 1:30 (GMT+1)) Cernel: -Xmx4096M -Xms4096M -Xss1250K 
(2021-12-15 1:31 (GMT+1)) Cernel: there is a line break between each one
(2021-12-15 1:31 (GMT+1)) JackariahHooch: how do I get access to save?
(2021-12-15 1:32 (GMT+1)) Cernel: ah, it is not letting you save?
(2021-12-15 1:32 (GMT+1)) Cernel: it means that you haven't given yourself the ability to save in there
(2021-12-15 1:32 (GMT+1)) JackariahHooch: yeah access denied
(2021-12-15 1:32 (GMT+1)) Cernel: the easiest way is that you cut-paste the file in your user folder, make the changes and cut-paste it back where it was
(2021-12-15 1:34 (GMT+1)) JackariahHooch: ok mission accomplished
(2021-12-15 1:35 (GMT+1)) Cernel: lol
(2021-12-15 1:35 (GMT+1)) Cernel: you can tell me if it will make any difference
(2021-12-15 1:35 (GMT+1)) JackariahHooch: do I need to restart client?
(2021-12-15 1:35 (GMT+1)) Cernel: nope
(2021-12-15 1:35 (GMT+1)) Cernel: uhm
(2021-12-15 1:35 (GMT+1)) Cernel: maybe yes
(2021-12-15 1:35 (GMT+1)) Cernel: yes I think so
(2021-12-15 1:35 (GMT+1)) JackariahHooch: ok
(2021-12-15 1:35 (GMT+1)) JackariahHooch: brb
(2021-12-15 1:37 (GMT+1)) JackariahHooch: sweet that seems to have worked
(2021-12-15 1:37 (GMT+1)) Cernel: are you noticing the battle-calculator being faster or what else is different
(2021-12-15 1:38 (GMT+1)) Cernel: I don't really know what were you experiencing
(2021-12-15 1:38 (GMT+1)) Cernel: I only know that the default RAM of triplea is too little for this game
(2021-12-15 1:38 (GMT+1)) JackariahHooch: sweet that seems to have worked
(2021-12-15 1:38 (GMT+1)) JackariahHooch: thanks
(2021-12-15 1:39 (GMT+1)) JackariahHooch: well here's my risky battles
(2021-12-15 1:39 (GMT+1)) Cernel: ok, but what do you mean, I'm interested to know what was the issue
(2021-12-15 1:39 (GMT+1)) Cernel: beside sometimes crashing
(2021-12-15 1:39 (GMT+1)) JackariahHooch: when I opened battle calc it just crashed client like 1/3 times
(2021-12-15 1:39 (GMT+1)) Cernel: were you crashing every time you tried to use the battle-calculator?
(2021-12-15 1:39 (GMT+1)) Cernel: ah
(2021-12-15 1:39 (GMT+1)) JackariahHooch: but only on this board for some reason
(2021-12-15 1:40 (GMT+1)) Cernel: yes I know, because ram is tight and the battle-calculator consumes a lot of ram
(2021-12-15 1:40 (GMT+1)) JackariahHooch: damn forgot guy in athens
(2021-12-15 1:40 (GMT+1)) Cernel: can I paste this conversation to the developers to ask them to increase the RAM assigned as default?
(2021-12-15 1:40 (GMT+1)) JackariahHooch: yeah
(2021-12-15 1:41 (GMT+1)) Cernel: thanks, I'll give you the link to where I paste it

**Comment by DanVanAtta** [comment]
It's almost always better to use JVM defaults entirely. This takes into account the system, the current load, and it's requirements. For example, the min size of having 3GB means an 8GB system will run out of memory as soon as you connect to two games (3GB for the lobby, which consumes the exact same memory as the app, then 3GB for that first game, then not enough memory to connect to a second).

If instead we got rid of vmoptions entirely the main app would probably consume around 100MB or so, then the game apps would grow in their memory usage to some default max of the system. In other words, the system should already be increasing the amount of memory needed when it needs it. It is perhaps not precisely because we are specifying a max memory. Thus by specifying a max memory we are actually reducing the effective max available (we are capping it), and by specifying a min memory we are potentially using far more memory than would be needed to run the lobby window.

It's also not conclusive to just make that update and see if things worked. Closing out additional windows can free up memory, restarting the app could resolve memory leaks, or it could be other processes reduce their memory consumption freeing up more memory for the OS.

The general rule of thumb is to eliminate any non-defaults for memory usage unless truly needed otherwise. It could be that most of these problems are avoided if we entirely remove the min/max setting and allow the JVM to use its algorithm to do that (which has been tuned and developed by far smarter people and far more systems than we have experience)

**Comment by DanVanAtta** [comment]
Said perhaps more simply, by default, when not specified, xms is usually around 100MB and xmx is 2/3 the total available memory. IF we then removed the xmx and xms specification, we would save on memory for the main game screens that require almost no memory, and you would get a much bigger max memory available as well (if and when it were needed, the JVM dynamically requests more memory from the OS when it is needed).

**Comment by Cernelius** [comment]
> If instead we got rid of vmoptions entirely

I certainly believe it is good being able to set the items presented in that file without having to use any commands, so I like that file not to be removed. However, instead of removing the file from the package, the default entries for the wanted items may be left blank and that meaning using JVM defaults (so power users still have the file if they want to add values to it). Meaning that the file, once opened with a text editor, may look like this (if this is actually better for the problem at hand):
```
-Xmx
-Xms
-Xss
```
I may try to remove the file and see how it goes for me.

---

I confirm that the problem with the most recently mentioned user was that, upon using the battle-calculator, the game would crash for him/her and this didn't happen any longer, for the remaining hours we played, once he/she doubled the default memory values given in the `TripleA.vmoptions` file.

**Comment by Cernelius** [comment]
How about having the program first looking for an (optional) `TripleA.vmoptions` file somewhere within the "map" folder? If no file is found there, then the program uses the values given by the `TripleA.vmoptions` in the installation path, otherwise it doesn't (much like now it does for many assets). That way, a very heavy map (as, in theory, there are virtually no limits to how huge a map may be) may have high `Xm` values, and, if they are too much for a system, only that map will fail to work. Or maybe this is not feasible because those values can be applied only upon starting the TripleA process, so they cannot be changed upon changing the selected game?

**Comment by Cernelius** [comment]
I've recently increased my "TripleA.vmoptions" values to as much as 
```
-Xmx6144M
-Xms6144M
```
because of hitting the 4G RAM cap during a "270BC Wars" game I was hosting sometime after round 10. Everything seems fine now.

Here it is a lobby "report" that I suspect is due to the standard 2G RAM cap.

>(01:09:45) Ondis:  You were slapped by Ondis
(01:09:48) Ondis:  Hey Cernel
TITO has left
(01:09:51) Ondis:  I gotta tel yo
(01:09:51) Cernel:  hi
hans has left
Adis has left
(01:09:56) Cernel:  what?
(01:10:04) Ondis:  Your map man, it does some weird stuff to my computer and has done so on two different machines over the years
(01:10:16) Ondis:  Sometimes it starts to like either memory leak or like take up huge CPU amounts
(01:10:28) Cernel:  it's just a massive game
(01:10:33) Cernel:  so it requires a lot of RAM
(01:10:34) Ondis:  and today when I tried to play with Elk, two of my AVs would constantly use up huge amounts of CPU
(01:10:40) Ondis:  even when just loading up the map
Benghazi has joined
(01:10:47) Ondis:  nah man I dont get these problems with Total War
(01:10:47) Cernel:  it's relatively normal
(01:10:50) Cernel:  just a huge game
(01:10:50) Ondis:  nono its not
(01:10:57) Ondis:  No, dont get it on other maps that are bigger
(01:10:59) Ondis:  Civil war, total war
(01:11:04) Ondis:  Its taking up huge amounts of CPU usage
(01:11:06) Cernel:  270BC Wars is way bigger than TWW as a game
(01:11:08) Ondis:  its like Bit coin mining levels
(01:11:15) Ondis:  My AV goes banans man
(01:11:20) Cernel:  270BC Wars is way bigger than anything else
(01:11:24) Ondis:  two different AVs start like processing files or something
(01:11:33) Cernel:  it's just because the game is big I tell you what to do
King2 has joined
King2 has left
(01:11:46) Cernel:  you need to increase the RAM assigned to TripleA
King2 has joined
King2 has left
(01:11:55) Cernel:  you on windows
(01:12:01) Cernel:  ?
(01:12:03) Ondis:  I dont believe you, sorry. Its no reason to trigger my anti virus where it literally start chugging more CPU than a modern FPS
Krautz has joined
King2 has joined
(01:12:27) Ondis:  Something is very poorly optimized somewhere
(01:12:31) Ondis:  and its not good
(01:12:33) Ondis:  Its a good map
(01:12:33) Cernel:  I assure you that the reason is simply becauuse the game is massive
(01:12:35) Ondis:  but this is not good
(01:12:42) Cernel:  and coded in an extremely inefficient way
(01:12:45) Ondis:  What massive, its like a few hundred megabytes
(01:12:47) Cernel:  that is why it needs so much memory
(01:12:51) Cernel:  but you can increase it
(01:13:03) Cernel:  so are you on windows?
(01:13:06) Ondis:  Yes
(01:13:10) As_you_like_it:  or maybe its actually bitcoin mining in the background
King2 slapped Brandtaucher
(01:13:18) As_you_like_it:  and ofc they dark web gay porn sites
Brandtaucher slapped King2
King2 has left
(01:13:24) Cernel:  lol
(01:13:32) Brandtaucher:  now theres king, king1 and king2!
(01:13:33) Cernel:  so go in programs
(01:13:38) Cernel:  open the "triple" folder
(01:13:42) Ondis:  Well it triggers like 50% CPU usage of a quadcore CPU, it doesnt seem to make a difference what CPU either
(01:13:46) peirce:  yeah, I find that if you stop downloading Terabytes of Super-HD Porn it speeds up the frame-rate
(01:13:48) Ondis:  some process leaks
(01:13:49) Cernel:  in the triplea folder you can find a "vmoptions" file
(01:13:58) Ondis:  vmoptions k
(01:14:03) Cernel:  no leaks it's just big
King2 has joined
(01:14:05) Ondis:  why does it trigger my anti virus?
King2 slapped Brandtaucher
(01:14:11) As_you_like_it:  Super-HD #D porn for the people
(01:14:14) Cernel:  open that with a text editor (like notepad)
(01:14:17) As_you_like_it:  3d
Brandtaucher slapped King2
(01:14:22) Cernel:  lol
(01:14:23) King2:  bot is freaking out
(01:14:24) Ondis:  It literally triggers two of my AVs, both Avast pro, and once disabled, it triggers Malware Executable of Windows itself
(01:14:27) peirce:  lol
(01:14:31) King2:  had to rejoin repeatledy
(01:14:31) Brandtaucher:  ill save and change
(01:14:32) Cernel:  and change the values you find it
(01:14:35) Cernel:  in it
(01:14:36) Cernel:  to:
King2 slapped Brandtaucher
(01:14:52) King2:  save and we can change bots
(01:14:59) As_you_like_it:  rejoin repeatledy sounds pornish ;P
(01:15:05) Cernel:  the file is actually called "TripleA.vmoptions"
(01:15:08) Brandtaucher:  204
(01:15:09) As_you_like_it:  sorry not going to troll enjoy the night gents
(01:15:15) Cernel:  -Xmx6144M
(01:15:24) Cernel:  -Xms6144M
(01:15:24) King2:  can you save
(01:15:25) peirce:  I think that's exactly what we were doing, As-You-like-it
(01:15:29) Cernel:  this way, it should be fine
(01:15:33) Brandtaucher:  go to 204 king
(01:15:39) Ondis:  What will that do?
(01:15:54) Cernel:  you need your computer to have 8+G of RAM to play that game with a good responsitivity of course
Brandtaucher slapped King2
(01:16:05) Cernel:  it will increase the ram assigned to triplea
(01:16:08) Ondis:  How can a game on triplea require 8 gig?
(01:16:09) Brandtaucher:  204
King3 has joined
(01:16:11) Cernel:  from 2 GB to 6 GB
(01:16:11) Ondis:  but I have 16
(01:16:14) Cernel:  yes
Brandtaucher slapped King3
hammond has joined
(01:16:20) Brandtaucher:  204
(01:16:25) Cernel:  but the vmoptions limit to 2GB regardless of what you have
(01:16:35) Ondis:  Its not even the Ram thats the issue
(01:16:37) Cernel:  so since you have 16, you can set it even bigger than I said
(01:16:42) Cernel:  but what I said should be enough
(01:16:43) Ondis:  its CPU 
(01:16:57) Ondis:  It triggers
(01:16:58) Cernel:  the CPU goes crazy BECAUSE you hit the ram
(01:16:58) Ondis:  the Anti Virus
(01:17:06) As_you_like_it:  oooh 16 inches thats dark web stuff
(01:17:07) peirce:  that's a crazy amount of Ram to be dedicated to a game with graphics like this - must be a serious glitch in the coding
(01:17:08) Cernel:  but of course the CPU will still go a lot
King3 has left
Krautz has left
(01:17:13) Cernel:  but you should be good
(01:17:26) Ondis:  How cna limiting it to 2gb ram be good then?
(01:17:30) Ondis:  Wont it trigger my CPU even morE?
(01:17:35) Cernel:  as I said, it is just a huge game file
(01:17:37) Ondis:  and why is it triggering the CPU usage of the ANTI VIRUS
(01:17:47) Ondis:  it doesnt explain why its trigger the CPU usage of two anti virus progrma
(01:17:51) Cernel:  well that I don't know
(01:18:00) Ondis:  well its an issue :P you should be aware of it
(01:18:01) Cernel:  maybe the antivirus is just not making sense
(01:18:03) peirce:  glitch in the code, gets hung up somewhere
Brandtaucher has left
(01:18:06) Ondis:  yeah
(01:18:09) Ondis:  pierce is right
(01:18:15) Ondis:  reun a debugger
(01:18:16) Ondis:  when u have time
(01:18:18) Ondis:  :P
(01:18:21) Cernel:  it see a program it does not recognize using an insane amount of memory and CPU and just assumes the worse
(01:18:23) Cernel:  anyways
(01:18:27) Cernel:  I told you what to do
(01:18:32) Cernel:  change that file as I said
(01:18:32) peirce:  there's no way something with graphics like this game should be using anywhere near 8gb or Ram
(01:18:37) Cernel:  and you should be good
(01:18:39) Cernel:  ok
(01:18:39) peirce:  it's a board game
(01:18:43) Cernel:  sorry now I have to play
(01:18:57) Ondis:  doesnt make sense
(01:19:00) Cernel:  let me know if anything still has issues AFTER you do that
(01:19:00) Ondis:  somethings fishy :)
(01:19:05) Cernel:  bye

**Comment by DanVanAtta** [comment]
Update: Xmx & Xms are no longer specified. This should have the effect of increasing max memory where it is available.

There is some information at the following links for what the defaults are:
- https://stackoverflow.com/questions/4667483/how-is-the-default-max-java-heap-size-determined

Please do re-open this issue if any questions or follow-up desired  (or cut a new issue), otherwise will mark this as closed for now
