### ISSUE TITLE
Test Map Problems

### ISSUE THREAD

**Issue by RogerCooper** [triplea-game/triplea#9661]
### Reproduction Steps

1. Click download maps
2. Install "Test Map"
3. Select a game. You will receive an error message

### Engine Version

2.6.394
Engine Version:

### Is there anything else we should know?
The test map should be eliminated or made playable

**Comment by DanVanAtta** [comment]
@RogerCooper you should have the full permissions to be able to resolve this issue. If there is no reason to download the test map, we should remove it presumably. To do so, we just need to remove the listing from the 'triplea-maps.yaml' file. We should consider removing the map repository as well to prevent the map from appearing in 2.6

**Comment by RogerCooper** [comment]
I will put this on my to-do list.
