### ISSUE TITLE
Prod DNS resolution failure

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#9708]
Unable to connect to lobby and forums due to DNS problems:

```
$ dig prod2-lobby.triplea-game.org

; <<>> DiG 9.16.1-Ubuntu <<>> prod2-lobby.triplea-game.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 14082
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;prod2-lobby.triplea-game.org.	IN	A

;; Query time: 3072 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Wed Oct 13 21:08:56 PDT 2021
;; MSG SIZE  rcvd: 57
```

Note the 'servfail' status above.

Verified that 'lobby' is running on the box (logged in via linode lish console).  Not sure if there is anything we can do if it's truly that DNS is borked right now...

**Comment by beelee1** [comment]
@DanVanAtta so lobby seems to be working again. Started a game in a bot made a few moves and spiral joined and talked to him a bit.

Anyway just a FYI in case you weren't already aware
