### ISSUE TITLE
Game is Freezing on Exit and/or Leave

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#972]
I notice that when trying to 'exit' or 'leave' either a single or multiplayer game, that the UI freezes and the game does not exit. There is no error message either, so the game is either spinning or doing nothing. We'll want to take a thread dump when this happens to get some stack traces, that will tell us what is being executed and the problem is.

**Comment by FrostionAAA** [comment]
I can confirm that besides leave and exit, the red X / close window button in windows also freezes the game. Got to shut it down in task manager.
