### ISSUE TITLE
TripleA 2.5 dialog box error

### ISSUE THREAD

**Issue by tlburnett** [triplea-game/triplea#9769]
![TripleA error](https://user-images.githubusercontent.com/94263019/141662925-207cd5f2-2d0a-4300-b9ac-122358994639.jpg)

I'm not a GitHub code guy or whatever, I just enjoy playing TripleA on my HP Ryzen 7 Game PC.  I'm submitting this TripleA 2.5 error message because the popup dialog box told me to!  I actually preferred TripleA 1.9, but it no longer works properly.

**Comment by DanVanAtta** [comment]
The map 'crazygs_ww1' appears to have an invalid XML file (based on the error message). We'll have to look deeper into this, in the meantime the map is likely unplayable. To avoid the above error message try deleting the map zip or moving the map zip to a different folder that is not in 'downloadedMaps'

**Comment by tlburnett** [comment]
Okay, that worked perfectly.  The message had appeared as soon as I start TripleA, but it no longer does.  Thanks!
