### ISSUE TITLE
2.6 Bug Space bar does not cycle through units anymore. 

### ISSUE THREAD

**Issue by jsarles-code** [triplea-game/triplea#9785]
### Reproduction Steps

1.After launching 2.6, I started up pacific 1940 2nd edition. In 2.5 by hitting the space bar Triple A would start cycling through my available units to move, it doesn't appear to be doing this anymore. I know"." also works, but space bar was helpful in a lot of ways to speed up time spent on moves. 
2.
3.

### Engine Version

Engine Version: 2.6

**Comment by jsarles-code** [comment]
This issue

**Comment by jsarles-code** [comment]
Yeah the spacebar command doesn't appear to work to "skip" units. sometime it appears to work and sometimes it doesn't

**Comment by DanVanAtta** [comment]
'spacebar' was problematic because whenever a button was 'activated, spacebar would activate that button rather than doing the 'unit skip'. I think you can observe this by clicking the 'next' button and then pressing spacebar will repeat.

Use '>' and '<' to go through units.

**Comment by jsarles-code** [comment]
Interesting, ok that so makes sense. I don't truly understand why that is problematic but I can understand that might have caused other issues? 
I personally have been a huge fan of the spacebar, it's a much bigger area to hit on a keyboard and I think it allows me to play the game so much faster. 

If we put that issue aside I have a separate issue, let me know if you would like me to create a separate issue. 

so I've discovered that the space bar doesn't start skipping units until you have manually hit the skip button. 
This seems like an issue right? If I start using the < and > buttons as you described , I can start cycling through units. This works well. But as soon as I as run into a unit I want to skip the user needs to physically click the on screen skip button. Once the user has clicked the "skip button" (checkmark button) on screen , only then can the user use the spacebar to skip units. This would be okay unless the user breaks this cycle. 
If I repeat the steps as I've described and then I move a unit then the user loses the ability to use the spacebar to skip through units. I have to physically click on the on screen skip button and only then can I once again use the spacebar to skip. 

I think this is a separate issue because even if the user cycles through their units using the < > buttons they have lost the ability to use the spacebar to skip units unless they click the screen first. 
Here's the process in steps 

2.5 Engine Version
Hit space bar to cycle to the next  unit 
Move the unit or hit space bar to skip or "s" to sleep 

2.6 Engine Version
use < or > to cycle to the next units. 
At this point the user must either physically move the unit or click the on screen skip button. 
If the user clicks the on screen skip button (checkmark) 
the user can then start using the space bar to skip the next unit that comes up 

but if the user needs to move their next units, they can move them and then
 cycle to the next units using the < > buttons 
after this they must once again click the on screen skip button to skip their units. 
The user can use the space bar repeatedly to skip through units, but if they need to move a unit that means they need to hit the onscreen button before they can once again take advantage of the space bar to skip units. 

I've also created a separate issue about the sleep button missing or being deprecated? https://github.com/triplea-game/triplea/issues/9786 

I think using the <> buttons to cycle through units to cycle makes sense. 

Let me know if anything is unclear or in-precise here. 
Thanks

**Comment by DanVanAtta** [comment]
> so I've discovered that the space bar doesn't start skipping units until you have manually hit the skip button.
This seems like an issue right? If I start using the < and > buttons as you described , I can start cycling through units. This works well. But as soon as I as run into a unit I want to skip the user needs to physically click the on screen skip button. Once the user has clicked the "skip button" (checkmark button) on screen , only then can the user use the spacebar to skip units. This would be okay unless the user breaks this cycle.

This is the problem with space bar. By default, the space bar will activate the last activated button. *Then*, if there is no such button, the space bar event is actually sent to our code and we can then process it as a 'skip unit event'. This why using space bar is not super ideal, but it can be unclear which button is being activated when pressing it.

>  I have to physically click on the on screen skip button and only then can I once again use the spacebar to skip.

Having to physically click the screen should be a problem for any of the hotkeys. I'm interested if that is not the case. This needing to click the screen is actually a major problem in multiplayer as the code in various unknown places loses screen focus, which makes hot keys feel buggy as they do not work without that magic click-on-screeen

**Comment by DanVanAtta** [comment]
Given that we have removed space bar as the 'skip unit' button, does this resolve the concerns raised in this issue? What would a fix to this issue look like? I don't think it's readily possible to use the space-bar as a hotkey in a deterministic way.

**Comment by jsarles-code** [comment]
So I guess my issue was only a personal preference. I really liked the
speed at which you could cycle through units with the space bar.  I feel
like some functionality is being lost from the default setup here.  But I
understand you are saying it's causing issues elsewhere .  User issues
probably are more important than ease of use and if people such as myself
want ease of use there are probably ways to use the hot keys to fix it.

**Comment by DanVanAtta** [comment]
Being able to skip with '>' and '<' is the same right, though with a less convenient key? Is there a bigger difference here that I'm not understanding? @jsarles-code

**Comment by jsarles-code** [comment]
Sorry yes, I was using a word incorrectly.
What I meant to say is that a user used to be able to hit the space bar and
it would select a unit and if you hit space bar again it would check off
that unit, which meant that you could use the space bar to cycle through
units and quickly check them off if they didn't need to move during that
phase.
Now I am not sure how to get the same effect with the hot keys.

My initial issue with the change is that it used to be possible to use the
hot keys to quickly scan and check off all the units the player has on the
board. This allowed the user to scan every piece, quickly move them or
check them off, and go to the next available unit.

After the change happened I was no longer able to quickly cycle through the
countries available units, check them off, move to the next unit. I guess I
am just uninformed on how to properly use the hotkeys. I can understand
that one button doing multiple things is maybe not ideal.
