### ISSUE TITLE
Problem with Update Maps prompt after installing new version

### ISSUE THREAD

**Issue by tvleavitt** [triplea-game/triplea#9790]
I've seen this multiple times before. The pop-up window continues off the bottom of the screen (and I have a 27" iMac, so it's high resolution) and any associated interface elements are inaccessible since the contents of the window can't be scrolled. I don't imagine I'm *that* uncommon in having a lot of maps installed.

This can be worked around by closing the window and then manually initiating an update, but it's totally avoidable: either put the critical UI elements at the top of the window when prompting people whether they want to update their out of date maps, make the window scrollable, or change the process to open up "Download Maps" to the "Update" tab.

![tripleaupdatepromptscreenshot](https://user-images.githubusercontent.com/4445057/142083945-ef86d56b-f6a3-4b80-9030-60b4969c9bd6.png)

**Comment by DanVanAtta** [comment]
@tvleavitt are you seeing this in 2.6 or are you seeing this in 2.5 after having installed 2.6?
This looks to have already been fixed, the contents of the 'out-of-date' message is put in scrollbars if the character length is more than 1000 (including hidden HTML characters).

**Comment by DanVanAtta** [comment]
This does look solved now - I observed scrollbars on a large list of map updates.
