### ISSUE TITLE
Remove GameRunner (not GameRunner2)

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#981]
From #974.
TripleA currently features 2 Gamerunners (`GameRunner.java`.`GameRunner2.java`). One of them is supposed to be compiled against jdk 1.3 as target, so that tripleA can still run on older JRE's, crashing immediately telling the user that he needs to update his java Version.
I'd vote for removing this feature and to have a single GameRunner instead (e.g. to remove `GameRunner.java` and to rename `GameRunner2.java` to the first one).

Thoughts?

**Comment by DanVanAtta** [comment]
The Install4j installer should be downloading a good JVM on install if one is not present. I think that means they can be consolidated. There are scripts out there that reference the game runner file, so we'll need to be careful we get those updated.

**Comment by RoiEXLab** [comment]
I guess this can be closed...
