### ISSUE TITLE
Include National Objective Income in Stat & Economy tabs

### ISSUE THREAD

**Issue by BeornTheBold** [triplea-game/triplea#984]
Income from national objectives is not included in the stat or economic tabs and thus must be manually tracked if you want to know a player's total income.  Maps that make extensive use of national objectives result in large portions of income unseen in these stats.

**Comment by ron-murhammer** [comment]
@BeornTheBold Good point though do you think it should just be added into what is show in the 'production' amount? Or a separate column? Also the Economy tab really only tracks existing resources not production.

**Comment by Cernelius** [comment]
As I said in another issue, in my opinion it would be preferable having a button "show main/all stats". Only the main stats are shown default.

Main stats should be only 3: PUs, Production, TUV

And in these the Production should include the NOs income.

Then, if you click on "show all stats", you have all stats, coprising "Units", "VC", "Ter.Prod", "Obj.Prod", "PlaceMax" and whatnot, also the resources you are going to get from the units you have, like in Civil War, mind you.

NOs of course do not belong to the Economy tab, which shows only the Resources you have.

**Comment by simon33-2** [comment]
I reckon a separate column would be the best way.
