### ISSUE TITLE
Show Carrier Capacity in Territory Tab

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#994]
Requesting: When there are carriers present in a territory, show the total carrier capacity.

Counting carrier capacity can become quite tedious, for example, how many planes can land on this?
![territory-tab-esxample](https://cloud.githubusercontent.com/assets/12397753/16940771/e4b205b6-4d40-11e6-92fe-1aac97923097.png)

**Comment by FrostionAAA** [comment]
I hate counting also, both transport and carrier capacity, but what would you have it say in the tab if aircraft took up different capacities, with fighters taking up 2. You then have 2 Light Carriers with 3 cap free each. They get 2 Figters parked on them and another wanting to join them (as there are 2 cap free in the fleet.)
Would the approach to this feature not  be to let tab info include used and free cap be sides every single ship picture?

**Comment by ron-murhammer** [comment]
Yeah this isn't an easy one since planes can have different carrier costs so you'd need to display the raw carrier capacity which wouldn't necessarily be number of planes that could land.

**Comment by DanVanAtta** [comment]
Not clear exactly how to do this one, closing without adding a backlog task. I appreciate the valuable feedback - thank you.
