### ISSUE TITLE
Political Screen Feature Request

### ISSUE THREAD

**Issue by BeornTheBold** [triplea-game/triplea#997]
Currently the political screen shows each relationship in three colors (red for any relationship with archeType of war, gray for archeType neutral, and green for archeType allied).  However it would be much easier to visualize the relationships if every relation type had it's own color that could be specified in some type of properties file (similar to map.properties).  For example I have a map that has 9 relationship types: Allied-Aligned-Friendly-Cooperative-Neutral-Uncooperative-Unfriendly-Hostile-War.  It would be very helpful to see the stages visually with yellow-orange-red showing increasing alarm as war approaches, or teal-blue-purple as things move towards alliance.  Backward compatibility could be preserved by using the current colors unless overridden by the new file.

**Comment by DanVanAtta** [comment]
Any suggestions what the XML might look like?

**Comment by BeornTheBold** [comment]
I was thinking to just do it like colors are defined for nations in the map.properties file.  It could even be part of the map.properties file.  For example there are now things like this:
color.Austria=4ed1e6
color.Britain=9c64e3
So why not just add some for political relations:
color.Relation.War=e5002d
color.Relation.Hostile=ead61c
and so on?

**Comment by FrostionAAA** [comment]
Nice idea 👍 Btw, why has nation colors never been in the XML and been in a properties file instead?

**Comment by ron-murhammer** [comment]
@FrostionAAA I think things that are UI only such as colors/sizes/etc have been put in properties file instead of XML. Probably so they are easier to change for users.

**Comment by BeornTheBold** [comment]
I am not a Java programmer, but it seems to me changing this code:
`private Color getRelationshipTypeColor(final RelationshipType relType) {
    final String archeType = relType.getRelationshipTypeAttachment().getArcheType();
if (archeType.equals(Constants.RELATIONSHIP_ARCHETYPE_ALLIED)) {
      return Color.green;
    }
    if (archeType.equals(Constants.RELATIONSHIP_ARCHETYPE_NEUTRAL)) {
      return Color.lightGray;
    }
    if (archeType.equals(Constants.RELATIONSHIP_ARCHETYPE_WAR)) {
      return Color.red;
    }
    throw new IllegalStateException(
        "PoliticsUI: RelationshipType: " + relType.getName() + " can only be of archeType Allied, Neutral or War");
  }`
to this code:
`private Color getRelationshipTypeColor(final RelationshipType relType) {
    final String archeType = relType.getRelationshipTypeAttachment().getArcheType();
	
	**Color color = getPlayerColor (relType (GetName));
	if (color != null)
		return getPlayerColor(relType(GetName));**

    if (archeType.equals(Constants.RELATIONSHIP_ARCHETYPE_ALLIED)) {
      return Color.green;
    }
    if (archeType.equals(Constants.RELATIONSHIP_ARCHETYPE_NEUTRAL)) {
      return Color.lightGray;
    }
    if (archeType.equals(Constants.RELATIONSHIP_ARCHETYPE_WAR)) {
      return Color.red;
    }
    throw new IllegalStateException(
        "PoliticsUI: RelationshipType: " + relType.getName() + " can only be of archeType Allied, Neutral or War");
  }`

might accomplish this, if map.properties simply as additions like player colors:
color.War=E5002D
color.Hostile=FD6E0E
color.Unfriendly=EAD61C
and so on.....
