### ISSUE TITLE
Territories missing names

### ISSUE THREAD

**Issue by scousemart** [triplea-game/triplea#999]
I've been looking and trying out the latest version of Triple A and I've noticed on the maps I've downloaded that a lot of the territories are missing their names. Obviously it's only a cosmetic problem but I thought you should know. The only maps I've seen this are the 3 World War II Pacific maps:
World War II Pacific 1940 2nd Edition,
World War II Pacific 1940 Original,
WW II Pacific 1940 Original J1-Balanced.

Would you like me to list the territories?

I hope this helps and I've not repeated someone else's post!

**Comment by DanVanAtta** [comment]
Which engine version are you using @scousemart ? We had a somewhat similar problem that was fixed in the last week or two. 

Yes, please list one or two of the territories. But, no need for a full list.

**Comment by scousemart** [comment]
Hi @DanVanAtta 
Engine is 1.9.0.0.2565 There are approx 26 missing name territories. A couple of examples: Western United States, Caroline Islands.

**Comment by ron-murhammer** [comment]
@DanVanAtta So I went to test this issue and World War II Global 1940 2nd Edition doesn't load with the following error:
```
Could not parse:jar:file:/C:/Users/ron/triplea/downloadedMaps/world_war_ii_global.zip!/games/ww2global40_2nd_edition.xml
Exception: World War II Global 1940 2nd Edition:The following option name of techAbilityAttachment of class TechAbilityAttachment are either misspelled or exist only in a future version of TripleA. Setter: productionBonus
games.strategy.engine.data.GameParseException: World War II Global 1940 2nd Edition:The following option name of techAbilityAttachment of class TechAbilityAttachment are either misspelled or exist only in a future version of TripleA. Setter: productionBonus
	at games.strategy.engine.data.GameParser.setValues(GameParser.java:1364)
```

The issue appears to be that there is no longer a method called setProductionBonus(String) in TechAbilityAttachment. I think we probably need to revert #970 or at least that part of it though I'm guessing there may be other issues as well.

**Comment by DanVanAtta** [comment]
Anything with a annotation tag in #970 needs to have a single String arg, so part of that update does need to be fixed.  I can get that update tonight or tomorrow.

Otherwise, I was able to see the missing territory names. I'm not sure if it is a game engine issue, or if there is a naming problem.

**Comment by DanVanAtta** [comment]
Rolled back #970, removes the map can not load problem

**Comment by ron-murhammer** [comment]
@DanVanAtta Seems to work fine now and I don't see any territory name issues on Global 1940.

@scousemart I'm going to close this as it appears to be resolved now. Please retest with the latest pre-release and reopen if you still see issues.

**Comment by scousemart** [comment]
@ron-murhammer Thanks for the help. Unfortunately I'm on holiday and don't have access to my pc until next week. I'll test and let you know asap. Just curious, the problem I had was with the Pacific 1940 maps. I realise you found a problem with Global 1940, did you find a problem with Pacific 1940?

**Comment by DanVanAtta** [comment]
Found and fixed two problems with Pacific 1940. Territory name files need to be in 'territoryNames/', not 'misc/'. Second, the prop to print territory images was turned off: https://github.com/triplea-maps/world_war_ii_pacific/blob/master/map/map.properties#L22

Both problems were fixed in  https://github.com/triplea-maps/world_war_ii_pacific/pull/1

After that was merged, travis build a new map version,  and I then bumped the map version to make it live: https://github.com/triplea-maps/Project/pull/33

Leaving closed as this is now fixed.
